// History overviews from the German Wikipedia (generated by scripts/build-history.mjs,
// CC BY-SA 4.0). Import only in server components: the JSON is large and must not
// end up in a client bundle — pass the one text a page needs as props.
import data from './geschichte.json';
import type { Continent } from './types';

export interface WikiText {
  title: string;
  url: string;
  paragraphs: string[];
}

const d = data as {
  fetched: string;
  countries: Record<string, WikiText>;
  continents: Record<Continent | 'welt', WikiText>;
};

export const HISTORY_FETCHED = d.fetched;

export function countryHistory(code: string): WikiText | null {
  return d.countries[code] ?? null;
}

export function continentHistory(id: Continent | 'welt'): WikiText | null {
  return d.continents[id] ?? null;
}
