import type { Epoch } from '../types';

export const E2: Epoch = {
  id: 'mittelalter',
  name: 'Mittelalter',
  period: '1066–1485',
  events: [
    {
      id: 'normannen-plantagenets',
      title: 'Normannen und Plantagenets',
      date: '1066–1199',
      text: [
        'Mit der Schlacht von Hastings 1066 eroberten die Normannen England. Sie brachten Burgen, das Lehnswesen und die französische Sprache. Unter den Plantagenets wurde England Teil eines großen Reiches, das bis an die Pyrenäen reichte.',
      ],
      subtopics: [
        {
          id: 'eroberung-1066',
          title: '1066 und die normannische Eroberung',
          date: '1066–1087',
          text: [
            'Nach dem Tod Eduards des Bekenners wurde am 6. Januar 1066 Harold Godwinson, der mächtigste angelsächsische Adlige, zum König gekrönt. Doch zwei andere beanspruchten die Krone: König Harald Hardrada von Norwegen und Herzog Wilhelm von der Normandie, der behauptete, Eduard und sogar Harold selbst hätten ihm den Thron versprochen.',
            'Im September landete Harald Hardrada mit Harolds verbanntem Bruder Tostig im Norden. Harold eilte mit seinem Heer nach Norden und siegte am 25. September 1066 bei Stamford Bridge; Hardrada und Tostig fielen. Nur drei Tage später, am 28. September, landete Wilhelm bei Pevensey an der Südküste. Harold musste in Eilmärschen zurück.',
            'Am 14. Oktober 1066 trafen beide Heere bei Hastings aufeinander, an der Stelle, wo heute die Kleinstadt Battle liegt. Die Angelsachsen verteidigten sich lange mit einem Schildwall auf einem Hügel, doch die Normannen lockten sie mit vorgetäuschter Flucht herunter. Harold fiel – der Teppich von Bayeux zeigt einen Krieger mit einem Pfeil im Auge, was oft als Harold gedeutet wird. Am Weihnachtstag 1066 wurde Wilhelm in der Westminster Abbey gekrönt. Man nennt ihn seither „Wilhelm den Eroberer“.',
            'Der rund 70 Meter lange, gestickte Teppich von Bayeux erzählt diese Geschichte in Bildern aus normannischer Sicht. Aufstände schlug Wilhelm grausam nieder; bei der „Verheerung des Nordens“ (1069/70) ließ er ganze Landstriche verwüsten, Zehntausende verhungerten. Fast der gesamte angelsächsische Adel wurde enteignet, sein Land erhielten normannische Ritter als Lehen.',
            'Überall entstanden Burgen, zuerst aus Holz auf Erdhügeln (Motte), dann aus Stein, wie der „White Tower“ des Tower of London. 1086 ließ Wilhelm in ganz England aufschreiben, wem welches Land, Vieh und welche Mühlen gehörten. Das Ergebnis, das „Domesday Book“, ist eine einzigartige Quelle; die Menschen verglichen die gründliche Prüfung mit dem Jüngsten Gericht (Doomsday). Wilhelm starb 1087 in Rouen.',
            'Der Adel und der Hof sprachen nun Französisch, die Kirche Latein, das einfache Volk Englisch. Daher hat das Englische bis heute viele französische Wörter. Ein bekanntes Beispiel: Die Tiere auf der Weide behielten englische Namen (cow, pig, sheep), das Fleisch auf dem Tisch der Herren französische (beef, pork, mutton).',
          ],
          quiz: {
            leicht: [
              ['In welchem Jahr eroberten die Normannen England?', '1066', ['1016', '1215', '1485']],
              ['Woher kamen die Normannen?', 'Aus der Normandie in Frankreich', ['Aus Norwegen direkt', 'Aus Schottland', 'Aus Italien']],
              ['Wie nennt man Wilhelm seit 1066?', '„Wilhelm der Eroberer“', ['„Wilhelm der Große“', '„Wilhelm der Fromme“', '„Wilhelm der Rote“']],
              ['In welcher Schlacht siegte Wilhelm 1066?', 'Bei Hastings', ['Bei Stamford Bridge', 'Bei Bosworth', 'Bei Agincourt']],
              ['Welcher englische König fiel bei Hastings?', 'Harold Godwinson', ['Alfred', 'Knut', 'Eduard der Bekenner']],
              ['Wo wurde Wilhelm gekrönt?', 'In der Westminster Abbey', ['In Canterbury', 'In Rouen', 'In York']],
              ['An welchem Tag wurde Wilhelm gekrönt?', 'Am Weihnachtstag 1066', ['Am 14. Oktober 1066', 'Am 1. Januar 1067', 'Am 6. Januar 1066']],
              ['Welches Kunstwerk erzählt die Eroberung in Bildern?', 'Der Teppich von Bayeux', ['Das Book of Kells', 'Die Magna Carta', 'Das Domesday Book']],
              ['Was zeigt der Teppich bei einem Krieger, der oft als Harold gedeutet wird?', 'Einen Pfeil im Auge', ['Eine Krone', 'Ein Schwert im Herzen', 'Einen Speer im Bein']],
              ['Welcher norwegische König beanspruchte 1066 die Krone?', 'Harald Hardrada', ['Knut', 'Olaf', 'Erik']],
              ['Wo besiegte Harold die Norweger?', 'Bei Stamford Bridge', ['Bei Hastings', 'Bei York Minster', 'Bei London']],
              ['Welches Buch ließ Wilhelm 1086 anlegen?', 'Das Domesday Book', ['Die Bibel', 'Die Angelsächsische Chronik', 'Die Magna Carta']],
              ['Was wurde im Domesday Book aufgeschrieben?', 'Wem welches Land und Vieh gehörte', ['Die Gesetze des Königs', 'Die Geschichte der Wikinger', 'Gebete']],
              ['Welcher Turm in London stammt von Wilhelm?', 'Der White Tower', ['Big Ben', 'Die Tower Bridge', 'The Shard']],
              ['Welche Sprache sprach der Adel nach 1066?', 'Französisch', ['Englisch', 'Deutsch', 'Norwegisch']],
              ['Welche Sprache sprach das einfache Volk?', 'Englisch', ['Französisch', 'Latein', 'Griechisch']],
              ['Woher stammt das englische Wort „beef“?', 'Aus dem Französischen', ['Aus dem Lateinischen', 'Aus dem Norwegischen', 'Aus dem Keltischen']],
              ['Wer erhielt das Land des angelsächsischen Adels?', 'Normannische Ritter', ['Die Bauern', 'Die Schotten', 'Die Wikinger']],
              ['Wie nennt man die Verwüstung von 1069/70?', 'Verheerung des Nordens', ['Große Pest', 'Danegeld', 'Anarchie']],
              ['Wo starb Wilhelm der Eroberer?', 'In Rouen', ['In London', 'In Hastings', 'In Paris']],
            ],
            mittel: [
              ['Wann wurde Harold Godwinson gekrönt?', '6. Januar 1066', ['25. Dezember 1066', '14. Oktober 1066', '28. September 1066']],
              ['Was behauptete Wilhelm über seinen Anspruch?', 'Eduard und Harold hätten ihm den Thron versprochen', ['Er sei Eduards Sohn', 'Der Papst habe ihn gewählt', 'Er habe die Krone gekauft']],
              ['Mit wem landete Harald Hardrada im Norden?', 'Mit Harolds Bruder Tostig', ['Mit Wilhelm', 'Mit Knut', 'Mit dem König von Schottland']],
              ['Wann fand die Schlacht von Stamford Bridge statt?', '25. September 1066', ['14. Oktober 1066', '28. September 1066', '6. Januar 1066']],
              ['Wo landete Wilhelm?', 'Bei Pevensey', ['Bei Dover', 'Bei Hastings direkt', 'Bei London']],
              ['Wann landete Wilhelm?', '28. September 1066', ['25. September 1066', '14. Oktober 1066', '25. Dezember 1066']],
              ['Wann fand die Schlacht von Hastings statt?', '14. Oktober 1066', ['25. September 1066', '25. Dezember 1066', '1. Januar 1067']],
              ['Wie verteidigten sich die Angelsachsen bei Hastings?', 'Mit einem Schildwall auf einem Hügel', ['Mit Kanonen', 'Mit einer Burg', 'Mit Schiffen']],
              ['Mit welcher List lockten die Normannen die Angelsachsen?', 'Mit vorgetäuschter Flucht', ['Mit Gold', 'Mit Feuer', 'Mit einem Holzpferd']],
              ['Wie lang ist der Teppich von Bayeux etwa?', 'Rund 70 Meter', ['Rund 7 Meter', 'Rund 700 Meter', 'Rund 2 Meter']],
              ['Aus wessen Sicht erzählt der Teppich?', 'Aus normannischer Sicht', ['Aus angelsächsischer Sicht', 'Aus norwegischer Sicht', 'Aus päpstlicher Sicht']],
              ['Wann fand die Verheerung des Nordens statt?', '1069/70', ['1066', '1086', '1100']],
              ['Was geschah mit dem angelsächsischen Adel?', 'Er wurde fast ganz enteignet', ['Er wurde reicher', 'Er durfte alles behalten', 'Er zog nach Norwegen']],
              ['Woraus waren die ersten normannischen Burgen?', 'Aus Holz auf Erdhügeln', ['Aus Stein und Glas', 'Aus Eis', 'Aus Ziegeln aus Rom']],
              ['Wie nennt man eine Burg auf einem Erdhügel?', 'Motte', ['Pfalz', 'Hillfort', 'Palast']],
              ['Wann entstand das Domesday Book?', '1086', ['1066', '1100', '1215']],
              ['Womit verglichen die Menschen die Prüfung für das Domesday Book?', 'Mit dem Jüngsten Gericht', ['Mit einer Steuererklärung heute', 'Mit einer Hochzeit', 'Mit einem Turnier']],
              ['Wann starb Wilhelm der Eroberer?', '1087', ['1066', '1100', '1135']],
              ['Welche Sprache sprach die Kirche?', 'Latein', ['Französisch', 'Englisch', 'Griechisch']],
              ['Welches Fleischwort stammt aus dem Französischen?', '„Pork“', ['„Pig“', '„Cow“', '„Sheep“']],
            ],
            schwer: [
              ['Wie viele Tage lagen zwischen Stamford Bridge und Wilhelms Landung?', 'Drei', ['Dreißig', 'Einer', 'Zehn']],
              ['Was geschah mit Hardrada und Tostig?', 'Beide fielen', ['Beide wurden gefangen', 'Beide flohen nach Norwegen', 'Sie wurden Könige']],
              ['Wie wurde der Teppich von Bayeux hergestellt?', 'Gestickt', ['Gewebt aus Seide', 'Gemalt', 'Gedruckt']],
              ['Wie viele Menschen verhungerten bei der Verheerung des Nordens?', 'Zehntausende', ['Dutzende', 'Hunderte', 'Millionen']],
              ['Was wurde im Domesday Book außer Land verzeichnet?', 'Vieh und Mühlen', ['Gedichte', 'Kirchenlieder', 'Kriegsschiffe']],
              ['Woher kommt der Name „Domesday“?', 'Von „Doomsday“, dem Jüngsten Gericht', ['Von einem Ort Domes', 'Von einem Mönch', 'Von „Dom“ für Kirche']],
              ['Welches Fleischwort ist mit „sheep“ verwandt, aber französisch?', '„Mutton“', ['„Lamb“', '„Veal“', '„Ham“']],
              ['Warum hat Englisch viele französische Wörter?', 'Weil nach 1066 der Adel Französisch sprach', ['Weil die Römer Französisch sprachen', 'Weil die Wikinger Franzosen waren', 'Weil es eine Kolonie Frankreichs war']],
              ['Was ist das Besondere am Domesday Book?', 'Eine einzigartige Quelle über das ganze Land', ['Ein Roman', 'Ein Liederbuch', 'Eine Bibelübersetzung']],
              ['Was tat Harold zwischen Stamford Bridge und Hastings?', 'Er eilte in Eilmärschen nach Süden', ['Er ruhte sich aus', 'Er segelte nach Frankreich', 'Er wurde gekrönt']],
              ['Welcher Teil des Tower of London ist der älteste?', 'Der White Tower', ['Die Tower Bridge', 'Das Traitors’ Gate', 'Der Jewel House']],
              ['Woher stammte Wilhelms Anspruch laut normannischer Darstellung?', 'Aus einem Versprechen Eduards', ['Aus einem Krieg', 'Aus einer Wahl in London', 'Aus einer Erbschaft von Knut']],
              ['Wie nennt man die Herrschaftsordnung mit Lehen?', 'Lehnswesen (Feudalismus)', ['Demokratie', 'Republik', 'Kapitalismus']],
              ['Welche Stadt in der Normandie war Wilhelms Sterbeort?', 'Rouen', ['Caen', 'Bayeux', 'Falaise']],
              ['Welches Ereignis machte Harolds Heer vor Hastings müde?', 'Der Kampf bei Stamford Bridge und der Eilmarsch', ['Eine Seuche', 'Ein Erdbeben', 'Ein Fest']],
              ['Was ist ein Schildwall?', 'Eine Reihe dicht aneinander gehaltener Schilde', ['Eine Steinmauer', 'Ein Graben', 'Ein Burgtor']],
              ['Welche Stadt ist nach der Schlacht von 1066 benannt?', 'Battle (bei Hastings)', ['Victory', 'Conquest', 'Normanton']],
              ['Wie viele Anwärter auf den Thron gab es 1066 insgesamt?', 'Drei', ['Zwei', 'Vier', 'Einen']],
              ['Welche Rolle hatte Harold vor 1066?', 'Mächtigster angelsächsischer Adliger', ['Bischof', 'Wikingerkönig', 'Herzog der Normandie']],
              ['Was brachten die Normannen nach England?', 'Burgen, Lehnswesen und Französisch', ['Kartoffeln', 'Den Buchdruck', 'Die Demokratie']],
            ],
          },
        },
        {
          id: 'plantagenets-becket',
          title: 'Heinrich II., Becket und Löwenherz',
          date: '1135–1199',
          text: [
            'Nach dem Tod Heinrichs I., eines Sohnes des Eroberers, stritten seine Tochter Matilda und sein Neffe Stephan um den Thron. Der Bürgerkrieg von 1135 bis 1154 wurde später „die Anarchie“ genannt; die Angelsächsische Chronik klagte, „Christus und seine Heiligen schliefen“.',
            '1154 wurde Matildas Sohn Heinrich II. König, der erste Plantagenet. Durch Erbe und seine Heirat mit Eleonore von Aquitanien herrschte er über ein Reich von Schottlands Grenze bis zu den Pyrenäen, das „Angevinische Reich“, benannt nach Anjou, der Heimat seines Vaters. Er war ein tatkräftiger Herrscher: Reisende Richter sprachen überall im Land nach denselben Regeln Recht, und Geschworene (jury) wirkten an Verfahren mit. So entstand das gemeinsame „Common Law“, das bis heute die Grundlage des Rechts in England, den USA und vielen anderen Ländern ist.',
            'Heinrich machte 1162 seinen Freund und Kanzler Thomas Becket zum Erzbischof von Canterbury. Doch Becket verteidigte nun entschlossen die Rechte der Kirche, etwa dass Geistliche nur vor Kirchengerichte kamen. Der König soll im Zorn gerufen haben: „Wird mich niemand von diesem lästigen Priester befreien?“ Vier Ritter nahmen das wörtlich und erschlugen Becket am 29. Dezember 1170 in der Kathedrale von Canterbury.',
            'Ganz Europa war entsetzt. Becket wurde schon 1173 heiliggesprochen, und Heinrich musste 1174 öffentlich Buße tun und sich an Beckets Grab auspeitschen lassen. Canterbury wurde zu einem der größten Pilgerorte Europas.',
            'Heinrichs Sohn Richard I. „Löwenherz“ (1189–1199) war ein gefeierter Ritter, verbrachte aber kaum ein halbes Jahr seiner Regierung in England. Er führte mit Philipp August von Frankreich den Dritten Kreuzzug, kämpfte gegen Sultan Saladin und eroberte Akkon, nicht aber Jerusalem. Auf dem Heimweg wurde er in Österreich gefangen genommen, auf Burg Dürnstein festgehalten und erst gegen ein riesiges Lösegeld freigelassen. 1199 starb er bei der Belagerung der Burg Châlus in Frankreich an einem Armbrustpfeil.',
            'In diese Zeit verlegt die Sage den Geächteten Robin Hood, der im Sherwood Forest bei Nottingham mit seinen „fröhlichen Gesellen“ die Reichen bestiehlt, den Armen gibt und gegen den bösen Sheriff von Nottingham und Prinz Johann kämpft, während König Richard fern auf dem Kreuzzug ist.',
          ],
          quiz: {
            leicht: [
              ['Wer war der erste König aus dem Haus Plantagenet?', 'Heinrich II.', ['Richard Löwenherz', 'Wilhelm der Eroberer', 'Johann Ohneland']],
              ['Wen heiratete Heinrich II.?', 'Eleonore von Aquitanien', ['Matilda', 'Isabella', 'Margarete']],
              ['Wie heißt das gemeinsame englische Recht?', 'Common Law', ['Code civil', 'Römisches Recht', 'Scharia']],
              ['Was sind Geschworene auf Englisch?', 'Jury', ['Judge', 'Lord', 'Sheriff']],
              ['Wen machte Heinrich II. zum Erzbischof von Canterbury?', 'Thomas Becket', ['Thomas Morus', 'Augustinus', 'Anselm']],
              ['Wofür kämpfte Becket als Erzbischof?', 'Für die Rechte der Kirche', ['Für den König', 'Für die Bauern', 'Für Frankreich']],
              ['Wie starb Thomas Becket?', 'Er wurde von Rittern erschlagen', ['Er starb an der Pest', 'Er ertrank', 'Er fiel im Kreuzzug']],
              ['Wo wurde Becket ermordet?', 'In der Kathedrale von Canterbury', ['Im Tower', 'In Westminster', 'In Rom']],
              ['Was wurde Canterbury danach?', 'Ein großer Pilgerort', ['Die Hauptstadt', 'Eine Festung', 'Ein Hafen']],
              ['Welchen Beinamen hatte Richard I.?', 'Löwenherz', ['Ohneland', 'Der Eroberer', 'Der Bekenner']],
              ['Auf welchem Kreuzzug kämpfte Richard?', 'Auf dem Dritten Kreuzzug', ['Auf dem Ersten', 'Auf dem Kinderkreuzzug', 'Auf dem Fünften']],
              ['Gegen welchen Sultan kämpfte Richard?', 'Saladin', ['Süleyman', 'Harun ar-Raschid', 'Mehmed']],
              ['Wie lange war Richard etwa in England?', 'Kaum ein halbes Jahr', ['Zehn Jahre', 'Sein ganzes Leben', 'Gar nicht']],
              ['Wo wurde Richard auf dem Heimweg gefangen?', 'In Österreich', ['In Frankreich', 'In Italien', 'In Spanien']],
              ['Wie starb Richard 1199?', 'An einem Armbrustpfeil', ['An der Pest', 'Im Bett', 'In einer Seeschlacht']],
              ['Welcher sagenhafte Held lebte im Sherwood Forest?', 'Robin Hood', ['König Artus', 'Merlin', 'Beowulf']],
              ['Wen bestahl Robin Hood der Sage nach?', 'Die Reichen', ['Die Armen', 'Die Mönche', 'Den König Richard']],
              ['Wer ist Robin Hoods Gegner?', 'Der Sheriff von Nottingham', ['Der Erzbischof', 'König Richard', 'Saladin']],
              ['Wie nannte man den Bürgerkrieg 1135–1154?', '„Die Anarchie“', ['„Die Rosenkriege“', '„Die Revolution“', '„Der Bürgerkrieg Cromwells“']],
              ['Bis wohin reichte das Reich Heinrichs II.?', 'Bis zu den Pyrenäen', ['Bis nach Rom', 'Bis nach Russland', 'Nur bis London']],
            ],
            mittel: [
              ['Wer stritt nach Heinrich I. um den Thron?', 'Matilda und Stephan', ['Richard und Johann', 'Harold und Wilhelm', 'Edward und Henry']],
              ['Was klagte die Chronik über die Anarchie?', '„Christus und seine Heiligen schliefen“', ['„Gott will es“', '„Wehe den Besiegten“', '„Alles ist verloren“']],
              ['Wann wurde Heinrich II. König?', '1154', ['1135', '1066', '1189']],
              ['Wessen Sohn war Heinrich II.?', 'Matildas', ['Stephans', 'Wilhelms', 'Richards']],
              ['Wie hieß Heinrichs großes Reich?', 'Angevinisches Reich', ['Britisches Empire', 'Normannisches Reich', 'Danelaw']],
              ['Wie sprachen die reisenden Richter Recht?', 'Überall nach denselben Regeln', ['Jeder nach eigenem Recht', 'Nach Kirchenrecht', 'Gar nicht']],
              ['Wo gilt das Common Law heute noch?', 'In England, den USA und vielen anderen Ländern', ['Nur in Frankreich', 'Nur in Rom', 'Nirgends']],
              ['Wann wurde Becket Erzbischof?', '1162', ['1154', '1170', '1173']],
              ['Welches Amt hatte Becket vorher?', 'Kanzler', ['Bischof von London', 'Ritter', 'Abt']],
              ['Vor welche Gerichte sollten Geistliche laut Becket nur kommen?', 'Vor Kirchengerichte', ['Vor königliche Gerichte', 'Vor Jury-Gerichte', 'Vor gar keine']],
              ['Was soll Heinrich im Zorn gerufen haben?', '„Wird mich niemand von diesem lästigen Priester befreien?“', ['„Tötet sie alle!“', '„Gott will es!“', '„Der Staat bin ich!“']],
              ['Wie viele Ritter erschlugen Becket?', 'Vier', ['Zwei', 'Zwölf', 'Einer']],
              ['Wann wurde Becket ermordet?', '29. Dezember 1170', ['25. Dezember 1170', '14. Oktober 1166', '15. Juni 1215']],
              ['Wann wurde Becket heiliggesprochen?', '1173', ['1170', '1200', '1300']],
              ['Was musste Heinrich 1174 tun?', 'Öffentlich Buße tun und sich auspeitschen lassen', ['Abdanken', 'Nach Rom ziehen', 'Einen Kreuzzug führen']],
              ['Wann regierte Richard Löwenherz?', '1189–1199', ['1154–1189', '1199–1216', '1066–1087']],
              ['Mit welchem französischen König zog Richard auf den Kreuzzug?', 'Philipp August', ['Ludwig IX.', 'Philipp IV.', 'Ludwig VII.']],
              ['Welche Stadt eroberte Richard auf dem Kreuzzug?', 'Akkon', ['Jerusalem', 'Konstantinopel', 'Kairo']],
              ['Bei welcher Burg starb Richard?', 'Châlus', ['Château-Gaillard', 'Dürnstein', 'Windsor']],
              ['Bei welcher Stadt liegt der Sherwood Forest?', 'Nottingham', ['London', 'York', 'Canterbury']],
            ],
            schwer: [
              ['Wessen Sohn war Heinrich I.?', 'Wilhelms des Eroberers', ['Eduards des Bekenners', 'Heinrichs II.', 'Stephans']],
              ['Wie lange dauerte die Anarchie?', 'Von 1135 bis 1154', ['Von 1066 bis 1087', 'Von 1189 bis 1199', 'Von 1215 bis 1217']],
              ['Wie nennt man Robin Hoods Gefährten?', '„Fröhliche Gesellen“ (Merry Men)', ['„Tafelrunde“', '„Templer“', '„Musketiere“']],
              ['Gegen welchen Prinzen kämpft Robin Hood in der Sage?', 'Prinz Johann', ['Prinz Arthur', 'Prinz Edward', 'Prinz Harold']],
              ['Wo war Richard Löwenherz gefangen, nach dem Österreich-Text?', 'In Österreich (Burg Dürnstein)', ['In Jerusalem', 'In Paris', 'Im Tower']],
              ['Was eroberte Richard auf dem Kreuzzug nicht?', 'Jerusalem', ['Akkon', 'Zypern', 'Jaffa']],
              ['Woher stammt der Name „Angevinisches Reich“?', 'Von Anjou, der Heimat Heinrichs', ['Von Angeln', 'Von Engeln', 'Von den Angelsachsen']],
              ['Was war die Folge von Beckets Mord für Canterbury?', 'Es wurde einer der größten Pilgerorte Europas', ['Es wurde zerstört', 'Es wurde Hauptstadt', 'Nichts']],
              ['Welche Rolle spielten Geschworene im Common Law?', 'Sie wirkten an Verfahren mit', ['Sie waren Henker', 'Sie waren Priester', 'Sie waren Soldaten']],
              ['Wie reagierte Europa auf Beckets Ermordung?', 'Mit Entsetzen', ['Mit Freude', 'Mit Gleichgültigkeit', 'Mit einem Krieg']],
              ['Wie lange regierte Heinrich II.?', 'Von 1154 bis 1189', ['Von 1135 bis 1154', 'Von 1189 bis 1199', 'Von 1066 bis 1087']],
              ['Was war das Lösegeld für Richard?', 'Riesig', ['Gering', 'Ein Pferd', 'Nichts']],
              ['Wer war der König, als Becket ermordet wurde?', 'Heinrich II.', ['Richard I.', 'Johann', 'Stephan']],
              ['Welcher Teil der Kirche war Becket als Erzbischof?', 'Ihr Oberhaupt in England', ['Ein einfacher Mönch', 'Ein Kardinal in Rom', 'Ein Templer']],
              ['Was ist ein Kanzler im Mittelalter?', 'Leiter der königlichen Schreibstube und Berater', ['Ein Henker', 'Ein Bauer', 'Ein Bischof']],
              ['Welches Ereignis verlegt die Robin-Hood-Sage in Richards Zeit?', 'Richards Abwesenheit auf dem Kreuzzug', ['Die Magna Carta', 'Die Pest', 'Die Rosenkriege']],
              ['Mit welcher Waffe wurde Richard tödlich getroffen?', 'Mit einer Armbrust', ['Mit einem Langbogen', 'Mit einem Schwert', 'Mit einer Lanze']],
              ['Wann musste Heinrich II. Buße tun?', '1174', ['1170', '1173', '1189']],
              ['Wer war Heinrichs Mutter, die um den Thron gekämpft hatte?', 'Matilda', ['Eleonore', 'Isabella', 'Margarete']],
              ['Welche Rechtsgrundlage schuf Heinrich II. in England?', 'Ein einheitliches Recht für das ganze Land', ['Das römische Recht', 'Das Kirchenrecht', 'Das Recht der Wikinger']],
            ],
          },
        },
      ],
    },
    {
      id: 'magna-carta-parlament',
      title: 'Magna Carta, Parlament und Eroberungen',
      date: '1199–1328',
      text: [
        'Der unglückliche König Johann musste 1215 die Magna Carta unterzeichnen – der Grundstein dafür, dass auch der König an Gesetze gebunden ist. Bald entstand das Parlament. Eduard I. eroberte Wales und versuchte, Schottland zu unterwerfen.',
      ],
      subtopics: [
        {
          id: 'magna-carta',
          title: 'Die Magna Carta und das erste Parlament',
          date: '1199–1295',
          text: [
            'Johann Ohneland (1199–1216), der jüngste Sohn Heinrichs II., verlor 1204 die Normandie und andere Gebiete an den französischen König Philipp August. Mit dem Papst Innozenz III. stritt er um die Besetzung des Erzbistums Canterbury; der Papst verhängte ein Interdikt über England, sodass jahrelang keine Gottesdienste stattfinden durften, und bannte den König. Um die verlorenen Gebiete zurückzugewinnen, presste Johann seinen Baronen hohe Steuern ab. Nach der Niederlage bei Bouvines 1214 erhoben sich die Barone und besetzten London.',
            'Am 15. Juni 1215 musste Johann auf der Wiese von Runnymede an der Themse bei Windsor die „Magna Carta“ (Große Urkunde) besiegeln. Sie schützte vor allem die Rechte der Barone und der Kirche. Berühmt ist Artikel 39: Kein freier Mann darf verhaftet, eingesperrt oder enteignet werden außer durch ein rechtmäßiges Urteil seiner Standesgenossen oder nach dem Gesetz des Landes. Ein Rat von 25 Baronen sollte die Einhaltung überwachen.',
            'Johann ließ die Urkunde gleich vom Papst für ungültig erklären, und es kam zum Krieg. Doch nach Johanns Tod 1216 wurde die Magna Carta im Namen seines jungen Sohnes Heinrich III. erneuert, 1225 in einer endgültigen Fassung. Vier Originalexemplare von 1215 sind erhalten. Später wurde die Magna Carta zum Symbol der Freiheit und beeinflusste etwa die Verfassung der USA.',
            'Unter Heinrich III. (1216–1272) rebellierten die Barone erneut. Ihr Anführer Simon de Montfort berief 1265 ein Parlament ein, zu dem erstmals auch Vertreter der Städte (Bürger) und der Grafschaften (Ritter) geladen waren – ein Vorläufer des Unterhauses. Simon fiel noch 1265 in der Schlacht von Evesham.',
            'Eduard I. (1272–1307) berief 1295 das „Musterparlament“ (Model Parliament) mit Vertretern von Adel, Kirche, Grafschaften und Städten ein. Das Parlament gewann das Recht, neuen Steuern zuzustimmen. Später teilte es sich in das Oberhaus (House of Lords) und das Unterhaus (House of Commons). 1290 vertrieb Eduard alle Juden aus England; erst 1656 durften sie zurückkehren.',
          ],
          quiz: {
            leicht: [
              ['Welcher König musste die Magna Carta besiegeln?', 'Johann Ohneland', ['Richard Löwenherz', 'Heinrich II.', 'Eduard I.']],
              ['In welchem Jahr wurde die Magna Carta besiegelt?', '1215', ['1066', '1295', '1485']],
              ['Was bedeutet „Magna Carta“?', 'Große Urkunde', ['Großes Land', 'Großer König', 'Große Kirche']],
              ['Wo wurde die Magna Carta besiegelt?', 'In Runnymede', ['In London im Tower', 'In Canterbury', 'In York']],
              ['An welchem Fluss liegt Runnymede?', 'An der Themse', ['Am Severn', 'Am Avon', 'Am Tyne']],
              ['Wessen Rechte schützte die Magna Carta vor allem?', 'Die der Barone und der Kirche', ['Die der Bauern', 'Die der Frauen', 'Die der Wikinger']],
              ['Welche Region verlor Johann 1204?', 'Die Normandie', ['Schottland', 'Wales', 'Irland']],
              ['An welchen König verlor Johann die Normandie?', 'Philipp August', ['Ludwig XIV.', 'Karl der Große', 'Napoleon']],
              ['Mit welchem Papst stritt Johann?', 'Innozenz III.', ['Gregor VII.', 'Urban II.', 'Leo III.']],
              ['Wer erhob sich 1214 gegen Johann?', 'Die Barone', ['Die Bauern', 'Die Schotten', 'Die Franzosen']],
              ['Wofür wurde die Magna Carta später zum Symbol?', 'Für die Freiheit', ['Für die Monarchie', 'Für den Krieg', 'Für die Kirche']],
              ['Welche Verfassung beeinflusste die Magna Carta?', 'Die der USA', ['Die Chinas', 'Die Russlands', 'Die Japans']],
              ['Wer berief 1265 ein Parlament mit Städtevertretern ein?', 'Simon de Montfort', ['Johann Ohneland', 'Robin Hood', 'Thomas Becket']],
              ['Wie heißt das Parlament von 1295?', 'Musterparlament (Model Parliament)', ['Langes Parlament', 'Rumpfparlament', 'Volkskammer']],
              ['Welcher König berief das Musterparlament ein?', 'Eduard I.', ['Heinrich III.', 'Johann', 'Richard I.']],
              ['Welches Recht gewann das Parlament?', 'Neuen Steuern zuzustimmen', ['Den König zu wählen', 'Kriege allein zu führen', 'Den Papst zu ernennen']],
              ['In welche zwei Häuser teilte sich das Parlament?', 'Oberhaus und Unterhaus', ['Senat und Kammer', 'Bundestag und Bundesrat', 'Rat und Volk']],
              ['Wie heißt das Unterhaus auf Englisch?', 'House of Commons', ['House of Lords', 'White House', 'Westminster Hall']],
              ['Wie viele Originale der Magna Carta von 1215 sind erhalten?', 'Vier', ['Eines', 'Keines', 'Hundert']],
              ['Wer vertrieb 1290 die Juden aus England?', 'Eduard I.', ['Johann', 'Heinrich VIII.', 'Wilhelm der Eroberer']],
            ],
            mittel: [
              ['Wann regierte Johann Ohneland?', '1199–1216', ['1189–1199', '1216–1272', '1272–1307']],
              ['Wessen jüngster Sohn war Johann?', 'Heinrichs II.', ['Richards I.', 'Wilhelms', 'Heinrichs III.']],
              ['Worum stritt Johann mit dem Papst?', 'Um die Besetzung des Erzbistums Canterbury', ['Um einen Kreuzzug', 'Um Gold', 'Um Irland']],
              ['Was ist ein Interdikt?', 'Ein Verbot von Gottesdiensten für ein ganzes Land', ['Ein Steuergesetz', 'Ein Kriegsrecht', 'Ein Handelsverbot']],
              ['Wofür presste Johann hohe Steuern ab?', 'Um verlorene Gebiete zurückzugewinnen', ['Für Kathedralen', 'Für einen Kreuzzug nach Jerusalem', 'Für die Armen']],
              ['Nach welcher Niederlage erhoben sich die Barone?', 'Nach Bouvines 1214', ['Nach Hastings', 'Nach Crécy', 'Nach Bannockburn']],
              ['Was besetzten die Barone?', 'London', ['York', 'Paris', 'Rom']],
              ['An welchem Tag wurde die Magna Carta besiegelt?', '15. Juni 1215', ['14. Oktober 1215', '25. Dezember 1215', '1. Januar 1215']],
              ['Bei welcher Stadt liegt Runnymede?', 'Bei Windsor', ['Bei Oxford', 'Bei Dover', 'Bei Bath']],
              ['Welcher Artikel der Magna Carta ist besonders berühmt?', 'Artikel 39', ['Artikel 1', 'Artikel 100', 'Artikel 7']],
              ['Was garantiert Artikel 39?', 'Keine Verhaftung ohne rechtmäßiges Urteil', ['Wahlrecht für alle', 'Religionsfreiheit', 'Pressefreiheit']],
              ['Wie viele Barone sollten die Einhaltung überwachen?', '25', ['5', '12', '100']],
              ['Was tat Johann gleich nach der Besiegelung?', 'Er ließ sie vom Papst für ungültig erklären', ['Er feierte', 'Er dankte ab', 'Er ging auf Kreuzzug']],
              ['Wann wurde die endgültige Fassung der Magna Carta erlassen?', '1225', ['1215', '1216', '1295']],
              ['In wessen Namen wurde die Magna Carta 1216 erneuert?', 'Heinrichs III.', ['Johanns', 'Richards', 'Eduards I.']],
              ['Wann berief Simon de Montfort sein Parlament ein?', '1265', ['1215', '1295', '1258']],
              ['Wo fiel Simon de Montfort?', 'Bei Evesham', ['Bei Lewes', 'Bei Hastings', 'Bei Bannockburn']],
              ['Welche Vertreter kamen 1265 erstmals ins Parlament?', 'Vertreter der Städte und Grafschaften', ['Bauern und Frauen', 'Nur Bischöfe', 'Nur Barone']],
              ['Wann berief Eduard I. das Musterparlament ein?', '1295', ['1265', '1215', '1307']],
              ['Wann durften Juden nach England zurückkehren?', '1656', ['1290', '1500', '1800']],
            ],
            schwer: [
              ['Welche Wirkung hatte das Interdikt?', 'Jahrelang fanden keine Gottesdienste statt', ['England wurde katholisch', 'Der König wurde Papst', 'Die Steuern sanken']],
              ['Welcher Vorläufer entstand 1265?', 'Ein Vorläufer des Unterhauses', ['Ein Vorläufer der Monarchie', 'Ein Vorläufer der Kirche von England', 'Ein Vorläufer der Armee']],
              ['Welche Stände kamen ins Musterparlament?', 'Adel, Kirche, Grafschaften und Städte', ['Nur Adel', 'Nur Bürger', 'Bauern und Soldaten']],
              ['Wie heißt das Oberhaus auf Englisch?', 'House of Lords', ['House of Commons', 'House of Windsor', 'House of Tudor']],
              ['Was erklärte der Papst zur Magna Carta?', 'Sie sei ungültig', ['Sie sei heilig', 'Sie gelte für ganz Europa', 'Nichts']],
              ['Was folgte auf die Ungültigerklärung der Magna Carta?', 'Ein Krieg zwischen König und Baronen', ['Frieden', 'Eine Kaiserkrönung', 'Ein Kreuzzug']],
              ['Wann starb Johann Ohneland?', '1216', ['1215', '1225', '1199']],
              ['Wann regierte Heinrich III.?', '1216–1272', ['1199–1216', '1272–1307', '1154–1189']],
              ['Wer war Simon de Montfort?', 'Anführer der aufständischen Barone', ['Ein König', 'Ein Bischof', 'Ein Franzose im Dienst Philipps']],
              ['Was bedeutet „Ohneland“ bei Johann?', 'Er erbte als jüngster Sohn zunächst kein Land', ['Er hatte kein Haus', 'Er war ein Seefahrer', 'Er verlor ganz England']],
              ['Welche Gruppe wird in Artikel 39 geschützt?', 'Jeder freie Mann', ['Nur der König', 'Nur Frauen', 'Nur Leibeigene']],
              ['Wann wurde die Magna Carta im 19./20. Jahrhundert weltweit berühmt?', 'Als Symbol der Freiheit', ['Als Kochbuch', 'Als Kriegsplan', 'Als Kirchenlied']],
              ['Welche Rechte gewann das Parlament mit der Zeit?', 'Die Zustimmung zu Steuern', ['Die Wahl des Papstes', 'Die Krönung des Königs', 'Gar keine']],
              ['Welche Abmachung enthielt die Magna Carta zum Schutz der Kirche?', 'Die Freiheit der englischen Kirche', ['Die Abschaffung der Kirche', 'Einen Kreuzzug', 'Steuern für den Papst']],
              ['In welchem Jahr verlor Johann die Normandie?', '1204', ['1214', '1215', '1199']],
              ['Wie lange blieben Juden aus England verbannt?', 'Über 350 Jahre', ['Zehn Jahre', 'Hundert Jahre', 'Bis heute']],
              ['Wofür steht Runnymede heute?', 'Für den Ort der Magna Carta', ['Für eine Schlacht', 'Für einen Palast', 'Für eine Universität']],
              ['Welche Instanz entschied laut Artikel 39?', 'Seine Standesgenossen oder das Gesetz des Landes', ['Der König', 'Der Papst', 'Die Kirche']],
              ['Warum war die Magna Carta zunächst kein Erfolg?', 'Sie wurde vom König gebrochen und annulliert', ['Sie wurde verloren', 'Sie war auf Französisch', 'Niemand las sie']],
              ['Welcher König regierte zur Zeit des Parlaments von 1265?', 'Heinrich III.', ['Eduard I.', 'Johann', 'Richard I.']],
            ],
          },
        },
        {
          id: 'wales-schottland',
          title: 'Wales, Schottland und Braveheart',
          date: '1277–1328',
          text: [
            'Eduard I. (1272–1307), wegen seiner Größe „Longshanks“ (Langbein) genannt, wollte ganz Britannien beherrschen. In Wales herrschte Fürst Llywelyn ap Gruffudd. In Feldzügen 1277 und 1282/83 eroberte Eduard Wales; Llywelyn fiel 1282. Um das Land zu sichern, ließ Eduard gewaltige Burgen bauen, etwa Caernarfon, Conwy, Harlech und Beaumaris. 1301 gab er seinem Sohn den Titel „Prince of Wales“, den seither der englische (britische) Thronfolger trägt; in Caernarfon findet bis heute die feierliche Einführung (Investitur) statt.',
            'Als in Schottland ein Streit um die Thronfolge ausbrach, ließ man Eduard als Schiedsrichter entscheiden. Er setzte John Balliol ein, verlangte aber Unterwerfung. Als die Schotten sich mit Frankreich verbündeten („Auld Alliance“, 1295), marschierte Eduard 1296 ein, nahm Balliol gefangen und brachte den „Stein von Scone“, auf dem die schottischen Könige gekrönt wurden, nach Westminster.',
            'Der Widerstand wurde von William Wallace angeführt. Am 11. September 1297 besiegte er die Engländer an der Brücke von Stirling. 1298 unterlag er bei Falkirk. 1305 wurde er verraten, in London gefangen und grausam hingerichtet. Der Film „Braveheart“ (1995) machte ihn weltberühmt, nimmt es mit der Geschichte aber nicht genau.',
            '1306 ließ sich Robert the Bruce zum König der Schotten krönen. Nach Eduards I. Tod 1307 errang er am 23./24. Juni 1314 bei Bannockburn einen großen Sieg über das viel größere Heer Eduards II. 1320 erklärten schottische Adlige in der „Erklärung von Arbroath“ an den Papst: Solange auch nur hundert Schotten am Leben seien, würden sie sich nie der englischen Herrschaft beugen. 1328 erkannte England im Vertrag von Edinburgh-Northampton Schottlands Unabhängigkeit an.',
            'Eduard II. (1307–1327) war ein schwacher König, der sich auf Günstlinge stützte. Seine Frau Isabella von Frankreich und ihr Verbündeter Roger Mortimer stürzten ihn 1327; er starb kurz darauf in Gefangenschaft. Der Stein von Scone wurde erst 1996 nach Schottland zurückgegeben und liegt heute im Schloss von Edinburgh – nur für Krönungen kommt er nach London.',
          ],
          quiz: {
            leicht: [
              ['Welcher englische König eroberte Wales?', 'Eduard I.', ['Heinrich II.', 'Johann', 'Wilhelm der Eroberer']],
              ['Wie wurde Eduard I. wegen seiner Größe genannt?', '„Longshanks“ (Langbein)', ['„Löwenherz“', '„Ohneland“', '„Bekenner“']],
              ['Welche Burg ließ Eduard in Wales bauen?', 'Caernarfon', ['Windsor', 'Edinburgh', 'Stirling']],
              ['Welchen Titel trägt der britische Thronfolger seit 1301?', 'Prince of Wales', ['Duke of York', 'Prince of England', 'Lord of the Isles']],
              ['Wer führte den schottischen Widerstand 1297 an?', 'William Wallace', ['Robert the Bruce', 'Macbeth', 'John Balliol']],
              ['Welcher Film machte William Wallace berühmt?', '„Braveheart“', ['„Gladiator“', '„Robin Hood“', '„Highlander“']],
              ['Wo siegte Wallace 1297?', 'An der Brücke von Stirling', ['Bei Bannockburn', 'Bei Falkirk', 'Bei Hastings']],
              ['Was geschah mit Wallace 1305?', 'Er wurde hingerichtet', ['Er wurde König', 'Er floh nach Frankreich', 'Er wurde Mönch']],
              ['Wer wurde 1306 König der Schotten?', 'Robert the Bruce', ['William Wallace', 'Eduard I.', 'John Balliol']],
              ['Wo siegte Robert the Bruce 1314?', 'Bei Bannockburn', ['Bei Stirling', 'Bei Falkirk', 'Bei Culloden']],
              ['Gegen welchen englischen König siegte Bruce 1314?', 'Eduard II.', ['Eduard I.', 'Eduard III.', 'Heinrich V.']],
              ['Welcher Stein wurde nach Westminster gebracht?', 'Der Stein von Scone', ['Der Stein von Rosetta', 'Der Blarney-Stein', 'Ein Stein aus Stonehenge']],
              ['Wozu diente der Stein von Scone?', 'Zur Krönung der schottischen Könige', ['Als Grabstein', 'Als Mühlstein', 'Als Grenzstein']],
              ['Wann wurde der Stein von Scone zurückgegeben?', '1996', ['1328', '1707', '1945']],
              ['Wo liegt der Stein von Scone heute?', 'Im Schloss von Edinburgh', ['In Westminster Abbey', 'Im Tower', 'In Stirling']],
              ['Mit welchem Land verbündeten sich die Schotten?', 'Mit Frankreich', ['Mit Spanien', 'Mit Norwegen', 'Mit Wales']],
              ['Wann erkannte England Schottlands Unabhängigkeit an?', '1328', ['1314', '1297', '1707']],
              ['Welcher walisische Fürst fiel 1282?', 'Llywelyn ap Gruffudd', ['Owain Glyndŵr', 'Hywel Dda', 'Arthur']],
              ['Wie war Eduard II. als König?', 'Schwach', ['Sehr stark', 'Grausam und erfolgreich', 'Heilig']],
              ['Wer stürzte Eduard II.?', 'Seine Frau Isabella und Roger Mortimer', ['Robert the Bruce', 'Der Papst', 'William Wallace']],
            ],
            mittel: [
              ['Wann eroberte Eduard Wales?', '1277 und 1282/83', ['1066', '1314', '1400']],
              ['Welche Burgen ließ Eduard außer Caernarfon bauen?', 'Conwy, Harlech und Beaumaris', ['Windsor und Dover', 'Edinburgh und Stirling', 'Warwick und Kenilworth']],
              ['Wann erhielt Eduards Sohn den Titel Prince of Wales?', '1301', ['1282', '1307', '1215']],
              ['Wen setzte Eduard als schottischen König ein?', 'John Balliol', ['Robert the Bruce', 'William Wallace', 'David I.']],
              ['Wie heißt das Bündnis zwischen Schottland und Frankreich?', 'Auld Alliance', ['Entente cordiale', 'Holy Alliance', 'Triple Alliance']],
              ['Wann wurde die Auld Alliance geschlossen?', '1295', ['1297', '1314', '1066']],
              ['Wann marschierte Eduard in Schottland ein?', '1296', ['1295', '1314', '1306']],
              ['An welchem Tag siegte Wallace bei Stirling?', '11. September 1297', ['23. Juni 1314', '15. Juni 1215', '14. Oktober 1297']],
              ['Wo unterlag Wallace 1298?', 'Bei Falkirk', ['Bei Stirling', 'Bei Bannockburn', 'Bei Flodden']],
              ['Wo wurde Wallace hingerichtet?', 'In London', ['In Edinburgh', 'In Stirling', 'In York']],
              ['Wie genau ist „Braveheart“ historisch?', 'Nicht sehr genau', ['Völlig genau', 'Es ist eine Doku', 'Es spielt im 20. Jahrhundert']],
              ['Wann fand die Schlacht von Bannockburn statt?', '23./24. Juni 1314', ['11. September 1297', '1. April 1320', '14. Oktober 1306']],
              ['Wie war das englische Heer bei Bannockburn?', 'Viel größer als das schottische', ['Kleiner', 'Gleich groß', 'Es gab keines']],
              ['Wie heißt die schottische Erklärung von 1320?', 'Erklärung von Arbroath', ['Erklärung von Edinburgh', 'Erklärung von Scone', 'Magna Carta Scotia']],
              ['An wen richtete sich die Erklärung von Arbroath?', 'An den Papst', ['An den König von England', 'An Frankreich', 'An das Volk']],
              ['Was sagt die Erklärung von Arbroath sinngemäß?', 'Solange hundert Schotten leben, beugen sie sich nie England', ['Schottland gehört zu England', 'Der Papst soll regieren', 'Frieden um jeden Preis']],
              ['Welcher Vertrag erkannte 1328 Schottlands Unabhängigkeit an?', 'Vertrag von Edinburgh-Northampton', ['Vertrag von Troyes', 'Act of Union', 'Vertrag von Paris']],
              ['Wann regierte Eduard II.?', '1307–1327', ['1272–1307', '1327–1377', '1216–1272']],
              ['Woher stammte Isabella, die Frau Eduards II.?', 'Aus Frankreich', ['Aus Schottland', 'Aus Spanien', 'Aus Wales']],
              ['Wann wurde Eduard II. gestürzt?', '1327', ['1314', '1307', '1330']],
            ],
            schwer: [
              ['Warum ließ man Eduard I. in Schottland entscheiden?', 'Als Schiedsrichter in einem Thronstreit', ['Weil er König von Schottland war', 'Weil der Papst es befahl', 'Weil er die Schotten besiegt hatte']],
              ['Was verlangte Eduard von John Balliol?', 'Unterwerfung', ['Geld', 'Eine Heirat', 'Nichts']],
              ['Was geschah mit Balliol 1296?', 'Er wurde gefangen genommen', ['Er wurde Kaiser', 'Er floh nach Norwegen', 'Er siegte']],
              ['Wie wurde Wallace 1305 gefasst?', 'Er wurde verraten', ['Er stellte sich', 'Er wurde in der Schlacht gefangen', 'Er wurde nie gefasst']],
              ['Wann erschien der Film „Braveheart“?', '1995', ['1985', '2005', '1975']],
              ['Wann starb Eduard I.?', '1307', ['1314', '1296', '1327']],
              ['Wofür kommt der Stein von Scone heute nach London?', 'Für Krönungen', ['Für Ausstellungen', 'Für Fußballspiele', 'Nie']],
              ['Worauf stützte sich Eduard II. vor allem?', 'Auf Günstlinge', ['Auf das Volk', 'Auf die Kirche', 'Auf Schottland']],
              ['Wie starb Eduard II.?', 'In Gefangenschaft kurz nach seinem Sturz', ['In der Schlacht von Bannockburn', 'Auf einem Kreuzzug', 'An der Pest in London']],
              ['Mit wem verbündete sich Isabella gegen Eduard II.?', 'Mit Roger Mortimer', ['Mit Robert the Bruce', 'Mit William Wallace', 'Mit dem König von Frankreich']],
              ['Welche Rolle hatte der Stein von Scone für Schottland?', 'Symbol des schottischen Königtums', ['Ein Grabstein Wallaces', 'Ein Meilenstein', 'Ein römischer Altar']],
              ['Wie lange blieb der Stein von Scone in Westminster?', 'Rund 700 Jahre', ['10 Jahre', '100 Jahre', '2000 Jahre']],
              ['Was ließ Eduard zur Sicherung von Wales bauen?', 'Gewaltige Burgen', ['Klöster', 'Kanäle', 'Universitäten']],
              ['Was ist die „Auld Alliance“ wörtlich?', 'Das alte Bündnis', ['Das goldene Bündnis', 'Das heilige Bündnis', 'Das neue Bündnis']],
              ['Wie viele Jahre nach Bannockburn erkannte England Schottlands Unabhängigkeit an?', '14 Jahre', ['1 Jahr', '50 Jahre', '100 Jahre']],
              ['Welcher englische König verlor bei Bannockburn?', 'Eduard II.', ['Eduard I.', 'Heinrich III.', 'Richard II.']],
              ['Welche Burg in Wales trägt heute den Titel des Thronfolgers ins Zentrum?', 'Caernarfon (Ort der Investitur)', ['Windsor', 'Balmoral', 'Holyrood']],
              ['Wer war Llywelyn ap Gruffudd?', 'Fürst von Wales', ['König von Schottland', 'Englischer Bischof', 'Wikingerführer']],
              ['In welchem Jahr ließ sich Robert the Bruce krönen?', '1306', ['1314', '1297', '1328']],
              ['Welches Ereignis folgte direkt auf Eduards I. Tod?', 'Bruces Siegeszug bis Bannockburn', ['Die Magna Carta', 'Die Pest', 'Die Rosenkriege']],
            ],
          },
        },
      ],
    },
    {
      id: 'spaetmittelalter-gb',
      title: 'Hundertjähriger Krieg, Pest und Rosenkriege',
      date: '1327–1485',
      text: [
        'Im Spätmittelalter kämpfte England über hundert Jahre um die französische Krone, die Pest raffte einen großen Teil der Menschen dahin, und die Bauern erhoben sich. Am Ende rangen die Häuser Lancaster und York in den Rosenkriegen um den Thron – bis die Tudors siegten.',
      ],
      subtopics: [
        {
          id: 'krieg-pest-bauern',
          title: 'Eduard III., die Pest und der Bauernaufstand',
          date: '1327–1422',
          text: [
            'Eduard III. (1327–1377) beanspruchte über seine Mutter Isabella die französische Krone und begann 1337 den Hundertjährigen Krieg. Seine Langbogenschützen siegten 1346 bei Crécy, und 1347 eroberte er Calais, das bis 1558 englisch blieb. Sein Sohn Eduard, der „Schwarze Prinz“, nahm 1356 bei Poitiers den französischen König gefangen. Um 1348 gründete Eduard III. den Hosenbandorden (Order of the Garter), den bis heute höchsten Ritterorden, mit dem Wahlspruch „Honi soit qui mal y pense“ („Ein Schelm, wer Böses dabei denkt“).',
            '1348/49 erreichte die Pest England. Der „Schwarze Tod“ tötete ein Drittel bis die Hälfte der Bevölkerung. Danach fehlten Arbeitskräfte, und die Bauern verlangten höhere Löhne. Das Parlament versuchte, die Löhne gesetzlich niedrig zu halten.',
            'Als 1381 eine neue Kopfsteuer (poll tax) erhoben wurde, kam es zum großen Bauernaufstand. Unter Wat Tyler zogen Tausende nach London, plünderten und töteten den Erzbischof von Canterbury. Der Priester John Ball predigte: „Als Adam grub und Eva spann, wer war da der Edelmann?“ Der erst 14-jährige König Richard II. traf die Aufständischen in Smithfield; Tyler wurde dort vom Bürgermeister von London niedergestochen. Der König versprach den Bauern Freiheit, brach sein Versprechen aber.',
            'In dieser Zeit wurde Englisch wieder Sprache von Hof und Recht: 1362 bestimmte ein Gesetz, dass vor Gericht Englisch gesprochen werden musste. Geoffrey Chaucer schrieb um 1387–1400 die „Canterbury-Erzählungen“ (The Canterbury Tales), in denen Pilger auf dem Weg nach Canterbury Geschichten erzählen – eines der ersten großen Werke der englischen Literatur. Der Theologe John Wyclif kritisierte die Kirche; seine Anhänger, die Lollarden, übersetzten die Bibel ins Englische.',
            'Richard II. wurde 1399 von seinem Vetter Heinrich Bolingbroke gestürzt, der als Heinrich IV. das Haus Lancaster begründete. Dessen Sohn Heinrich V. (1413–1422) besiegte am 25. Oktober 1415 bei Agincourt mit seinen Langbogenschützen ein viel größeres französisches Heer. Im Vertrag von Troyes 1420 wurde er Erbe Frankreichs, starb aber schon 1422. Shakespeare machte ihn in „Heinrich V.“ zum Helden. Sein Sohn Heinrich VI. war noch ein Baby; unter ihm gingen die französischen Gebiete bis 1453 fast alle verloren.',
          ],
          quiz: {
            leicht: [
              ['Welcher englische König begann den Hundertjährigen Krieg?', 'Eduard III.', ['Heinrich V.', 'Richard II.', 'Eduard I.']],
              ['Wann begann der Hundertjährige Krieg?', '1337', ['1066', '1415', '1453']],
              ['Welche Waffe machte die Engländer bei Crécy stark?', 'Der Langbogen', ['Die Kanone', 'Das Gewehr', 'Der Speer']],
              ['Welche Stadt eroberte Eduard III. 1347?', 'Calais', ['Paris', 'Rouen', 'Bordeaux']],
              ['Wie nannte man Eduards Sohn?', 'Den Schwarzen Prinzen', ['Den Roten Prinzen', 'Prinz Löwenherz', 'Den Weißen Ritter']],
              ['Welchen Orden gründete Eduard III.?', 'Den Hosenbandorden', ['Den Templerorden', 'Das Eiserne Kreuz', 'Die Ehrenlegion']],
              ['Welche Seuche erreichte England 1348?', 'Die Pest', ['Die Cholera', 'Die Grippe', 'Die Pocken']],
              ['Wie viel der Bevölkerung tötete die Pest?', 'Ein Drittel bis die Hälfte', ['Ein Hundertstel', 'Fast niemanden', 'Alle']],
              ['Was verlangten die Bauern nach der Pest?', 'Höhere Löhne', ['Mehr Steuern', 'Einen neuen König', 'Mehr Kirchen']],
              ['Was löste 1381 den Bauernaufstand aus?', 'Eine Kopfsteuer', ['Die Pest', 'Ein Krieg mit Schottland', 'Eine Hungersnot']],
              ['Wer führte den Bauernaufstand an?', 'Wat Tyler', ['Robin Hood', 'William Wallace', 'Jack Cade']],
              ['Welcher Satz stammt aus dem Bauernaufstand?', '„Als Adam grub und Eva spann, wer war da der Edelmann?“', ['„Gott will es“', '„Wehe den Besiegten“', '„Der Staat bin ich“']],
              ['Wie alt war König Richard II. beim Bauernaufstand?', '14 Jahre', ['4 Jahre', '40 Jahre', '24 Jahre']],
              ['Hielt Richard II. sein Versprechen an die Bauern?', 'Nein', ['Ja', 'Teilweise', 'Er gab keines']],
              ['Wer schrieb die „Canterbury-Erzählungen“?', 'Geoffrey Chaucer', ['William Shakespeare', 'Thomas Morus', 'John Milton']],
              ['Wohin reisen die Pilger in Chaucers Werk?', 'Nach Canterbury', ['Nach Rom', 'Nach Jerusalem', 'Nach York']],
              ['Wo siegte Heinrich V. 1415?', 'Bei Agincourt', ['Bei Crécy', 'Bei Hastings', 'Bei Bosworth']],
              ['Welcher Dichter machte Heinrich V. zum Helden?', 'Shakespeare', ['Chaucer', 'Dickens', 'Milton']],
              ['Welche Sprache wurde 1362 Gerichtssprache?', 'Englisch', ['Französisch', 'Latein', 'Walisisch']],
              ['Bis wann blieb Calais englisch?', '1558', ['1453', '1347', '1600']],
            ],
            mittel: [
              ['Über wen beanspruchte Eduard III. die französische Krone?', 'Über seine Mutter Isabella', ['Über seine Frau', 'Über seinen Großvater Wilhelm', 'Über den Papst']],
              ['Wann siegten die Engländer bei Crécy?', '1346', ['1337', '1356', '1415']],
              ['Wann nahm der Schwarze Prinz den französischen König gefangen?', '1356 bei Poitiers', ['1346 bei Crécy', '1415 bei Agincourt', '1347 bei Calais']],
              ['Wie lautet der Wahlspruch des Hosenbandordens?', '„Honi soit qui mal y pense“', ['„Dieu et mon droit“', '„Semper fidelis“', '„God save the King“']],
              ['Wann wurde der Hosenbandorden etwa gegründet?', 'Um 1348', ['Um 1066', 'Um 1215', 'Um 1500']],
              ['Was versuchte das Parlament nach der Pest?', 'Die Löhne gesetzlich niedrig zu halten', ['Die Löhne zu verdoppeln', 'Die Pest zu verbieten', 'Den König abzusetzen']],
              ['Wann fand der große Bauernaufstand statt?', '1381', ['1348', '1399', '1415']],
              ['Wie heißt die Kopfsteuer auf Englisch?', 'Poll tax', ['Income tax', 'Danegeld', 'Tithe']],
              ['Wen töteten die Aufständischen in London?', 'Den Erzbischof von Canterbury', ['Den König', 'Wat Tyler', 'Chaucer']],
              ['Welcher Priester predigte für die Bauern?', 'John Ball', ['John Wyclif', 'Thomas Becket', 'John Knox']],
              ['Wo traf Richard II. die Aufständischen?', 'In Smithfield', ['In Westminster', 'In Canterbury', 'Im Tower']],
              ['Wer erstach Wat Tyler?', 'Der Bürgermeister von London', ['Der König selbst', 'John Ball', 'Ein Bauer']],
              ['Wann schrieb Chaucer die Canterbury-Erzählungen?', 'Um 1387–1400', ['Um 1200', 'Um 1500', 'Um 1600']],
              ['Welcher Theologe kritisierte die Kirche im 14. Jahrhundert?', 'John Wyclif', ['Martin Luther', 'Jan Hus', 'Thomas Becket']],
              ['Was übersetzten Wyclifs Anhänger ins Englische?', 'Die Bibel', ['Den Koran', 'Die Magna Carta', 'Homer']],
              ['Wer stürzte Richard II. 1399?', 'Heinrich Bolingbroke', ['Heinrich V.', 'Eduard IV.', 'Wat Tyler']],
              ['Welches Haus begründete Heinrich IV.?', 'Das Haus Lancaster', ['Das Haus York', 'Das Haus Tudor', 'Das Haus Stuart']],
              ['Wann siegte Heinrich V. bei Agincourt?', '25. Oktober 1415', ['14. Oktober 1066', '26. August 1346', '22. August 1485']],
              ['Welcher Vertrag machte Heinrich V. 1420 zum Erben Frankreichs?', 'Vertrag von Troyes', ['Vertrag von Brétigny', 'Vertrag von Paris', 'Vertrag von Arras']],
              ['Wann starb Heinrich V.?', '1422', ['1415', '1420', '1453']],
            ],
            schwer: [
              ['Was bedeutet „Honi soit qui mal y pense“?', '„Ein Schelm, wer Böses dabei denkt“', ['„Gott und mein Recht“', '„Immer treu“', '„Für König und Vaterland“']],
              ['Wie alt war Heinrich VI. beim Tod seines Vaters?', 'Ein Baby', ['Zehn Jahre', 'Zwanzig Jahre', 'Erwachsen']],
              ['Bis wann gingen die französischen Gebiete fast alle verloren?', '1453', ['1422', '1415', '1558']],
              ['Was machten die Bauern 1381 in London?', 'Sie plünderten und töteten', ['Sie feierten ein Fest', 'Sie wählten einen König', 'Sie bauten eine Kirche']],
              ['Welches Gesetz von 1362 stärkte die englische Sprache?', 'Englisch wurde Gerichtssprache', ['Französisch wurde verboten', 'Latein wurde Pflicht', 'Walisisch wurde Amtssprache']],
              ['Warum gilt Chaucers Werk als bedeutend?', 'Als eines der ersten großen Werke englischer Literatur', ['Als erstes Gesetzbuch', 'Als Kriegsbericht', 'Als Bibelübersetzung']],
              ['Wie war das französische Heer bei Agincourt im Vergleich?', 'Viel größer', ['Kleiner', 'Gleich groß', 'Es gab keines']],
              ['Wessen Vetter war Heinrich Bolingbroke?', 'Richards II.', ['Eduards III.', 'Heinrichs V.', 'Wat Tylers']],
              ['Welche Folge hatte die Pest für die Bauern langfristig?', 'Sie konnten bessere Bedingungen fordern', ['Sie wurden alle Sklaven', 'Sie wanderten aus', 'Nichts']],
              ['Was ist der Hosenbandorden heute?', 'Der höchste Ritterorden Englands', ['Ein Sportverein', 'Eine Kirche', 'Abgeschafft']],
              ['Wann regierte Eduard III.?', '1327–1377', ['1272–1307', '1377–1399', '1413–1422']],
              ['Wann regierte Heinrich V.?', '1413–1422', ['1399–1413', '1422–1461', '1377–1399']],
              ['Was beanspruchte Heinrich V. in Frankreich?', 'Die französische Krone', ['Nur Calais', 'Nur die Normandie', 'Nichts']],
              ['Welcher Teil der Kirche wurde 1381 Opfer der Bauern?', 'Der Erzbischof von Canterbury', ['Der Papst', 'Der Bischof von York', 'Ein Abt in Wales']],
              ['Welche Gruppe kritisierte John Wyclif?', 'Die Kirche', ['Die Bauern', 'Die Juden', 'Die Wikinger']],
              ['Wie nennt man Wyclifs Anhänger?', 'Lollarden', ['Hussiten', 'Puritaner', 'Quäker']],
              ['Welches Ereignis fiel zeitlich mit dem Hosenbandorden zusammen?', 'Die Ankunft der Pest', ['Die Magna Carta', 'Die Schlacht von Hastings', 'Die Rosenkriege']],
              ['Welches Ergebnis brachte der Bauernaufstand kurzfristig?', 'Die Niederschlagung und gebrochene Versprechen', ['Die Abschaffung des Adels', 'Eine Republik', 'Höhere Steuern für Adlige']],
              ['Wie heißt Shakespeares Drama über den Sieger von Agincourt?', '„Heinrich V.“', ['„Richard III.“', '„Macbeth“', '„Hamlet“']],
              ['Wann erreichte die Pest England?', '1348/49', ['1337', '1381', '1415']],
            ],
          },
        },
        {
          id: 'rosenkriege',
          title: 'Die Rosenkriege',
          date: '1455–1485',
          text: [
            'Heinrich VI. (1422–1461, 1470–1471) war fromm, aber schwach und litt an Phasen geistiger Umnachtung. Zwei Zweige der Königsfamilie stritten um die Macht: das Haus Lancaster, dessen Zeichen später als rote Rose dargestellt wurde, und das Haus York mit der weißen Rose. Nach diesen Zeichen nennt man die Bürgerkriege von 1455 bis 1485 „Rosenkriege“ – der Name kam allerdings erst viel später auf, etwa durch Shakespeare und den Schriftsteller Walter Scott.',
            'Die Kämpfe begannen 1455 mit der ersten Schlacht von St Albans. 1461 wurde der Yorkist Eduard IV. König. Im selben Jahr fand bei Towton im Schneesturm die vermutlich blutigste Schlacht auf englischem Boden statt, mit Zehntausenden Toten. Der mächtige Graf von Warwick, der „Königsmacher“, wechselte die Seiten und setzte 1470 Heinrich VI. noch einmal kurz auf den Thron. Doch Eduard IV. siegte 1471 bei Barnet, wo Warwick fiel, und bei Tewkesbury. Heinrich VI. wurde danach im Tower getötet.',
            'Als Eduard IV. 1483 starb, wurde sein zwölfjähriger Sohn als Eduard V. König. Doch dessen Onkel Richard, Herzog von Gloucester, ließ ihn und seinen jüngeren Bruder in den Tower bringen und sich selbst als Richard III. krönen. Die beiden „Prinzen im Tower“ verschwanden spurlos; viele glauben, Richard habe sie ermorden lassen. Shakespeare stellte ihn in „Richard III.“ als buckligen Bösewicht dar („Ein Pferd! Ein Pferd! Mein Königreich für ein Pferd!“).',
            'Am 22. August 1485 trat Heinrich Tudor, ein Erbe des Hauses Lancaster, in der Schlacht von Bosworth gegen Richard III. an. Richard fiel als letzter englischer König auf einem Schlachtfeld. Heinrich wurde als Heinrich VII. König und heiratete 1486 Elizabeth von York, die Tochter Eduards IV. So vereinte er beide Häuser; die „Tudor-Rose“ verbindet die rote und die weiße Rose. Mit 1485 lässt man oft das englische Mittelalter enden.',
            '2012 fanden Archäologen Richards Skelett unter einem Parkplatz in Leicester; eine verkrümmte Wirbelsäule bestätigte eine Skoliose. Er wurde 2015 in der Kathedrale von Leicester feierlich neu bestattet. Schon 1476 hatte William Caxton in Westminster die erste Druckerpresse Englands aufgestellt.',
          ],
          quiz: {
            leicht: [
              ['Wie nennt man die Bürgerkriege von 1455 bis 1485?', 'Rosenkriege', ['Hundertjähriger Krieg', 'Bauernkrieg', 'Anarchie']],
              ['Welches Haus hatte die rote Rose?', 'Lancaster', ['York', 'Tudor', 'Stuart']],
              ['Welches Haus hatte die weiße Rose?', 'York', ['Lancaster', 'Tudor', 'Windsor']],
              ['Wie war König Heinrich VI.?', 'Fromm, aber schwach', ['Grausam und stark', 'Ein großer Feldherr', 'Ein Wikinger']],
              ['Wer wurde 1461 König aus dem Haus York?', 'Eduard IV.', ['Richard III.', 'Heinrich VII.', 'Heinrich VI.']],
              ['Wie nannte man den Grafen von Warwick?', '„Königsmacher“', ['„Löwenherz“', '„Schwarzer Prinz“', '„Eroberer“']],
              ['Wohin brachte Richard die beiden Prinzen?', 'In den Tower', ['Nach Frankreich', 'Nach Schottland', 'In ein Kloster']],
              ['Was geschah mit den Prinzen im Tower?', 'Sie verschwanden spurlos', ['Sie wurden Könige', 'Sie flohen nach Amerika', 'Sie wurden Mönche']],
              ['Wer wurde 1483 König Richard III.?', 'Der Onkel der Prinzen', ['Ihr Vater', 'Ihr Bruder', 'Heinrich Tudor']],
              ['Welcher Dichter stellte Richard III. als Bösewicht dar?', 'Shakespeare', ['Chaucer', 'Dickens', 'Scott']],
              ['Was ruft Richard bei Shakespeare?', '„Mein Königreich für ein Pferd!“', ['„Sein oder Nichtsein!“', '„Gott will es!“', '„Et tu, Brute?“']],
              ['In welcher Schlacht fiel Richard III.?', 'Bei Bosworth', ['Bei Hastings', 'Bei Towton', 'Bei Agincourt']],
              ['Wer siegte 1485 bei Bosworth?', 'Heinrich Tudor', ['Richard III.', 'Eduard IV.', 'Warwick']],
              ['Als wer wurde Heinrich Tudor König?', 'Als Heinrich VII.', ['Als Heinrich VIII.', 'Als Heinrich VI.', 'Als Eduard V.']],
              ['Wen heiratete Heinrich VII.?', 'Elizabeth von York', ['Anne Boleyn', 'Katharina von Aragon', 'Margarete von Anjou']],
              ['Welche Rose verbindet Rot und Weiß?', 'Die Tudor-Rose', ['Die Lancaster-Rose', 'Die York-Rose', 'Die Windsor-Rose']],
              ['Wo wurde Richards Skelett 2012 gefunden?', 'Unter einem Parkplatz in Leicester', ['Im Tower', 'In Westminster Abbey', 'In der Themse']],
              ['Wo wurde Richard III. 2015 neu bestattet?', 'In der Kathedrale von Leicester', ['In Westminster Abbey', 'In York', 'In Windsor']],
              ['Wer stellte die erste Druckerpresse Englands auf?', 'William Caxton', ['Gutenberg', 'Chaucer', 'Shakespeare']],
              ['Mit welchem Jahr lässt man oft das englische Mittelalter enden?', '1485', ['1066', '1215', '1600']],
            ],
            mittel: [
              ['Woran litt Heinrich VI.?', 'An Phasen geistiger Umnachtung', ['An der Pest', 'An Blindheit', 'An nichts']],
              ['Wann begannen die Rosenkriege?', '1455', ['1415', '1461', '1485']],
              ['Mit welcher Schlacht begannen sie?', 'Mit der ersten Schlacht von St Albans', ['Mit Towton', 'Mit Bosworth', 'Mit Barnet']],
              ['Wo fand 1461 die vermutlich blutigste Schlacht auf englischem Boden statt?', 'Bei Towton', ['Bei Bosworth', 'Bei Hastings', 'Bei Tewkesbury']],
              ['Bei welchem Wetter wurde bei Towton gekämpft?', 'Im Schneesturm', ['In großer Hitze', 'Im Nebel', 'Bei Sonnenschein']],
              ['Wann setzte Warwick Heinrich VI. noch einmal auf den Thron?', '1470', ['1461', '1471', '1483']],
              ['Wo fiel Warwick?', 'Bei Barnet', ['Bei Towton', 'Bei Bosworth', 'Bei St Albans']],
              ['Wann siegte Eduard IV. bei Barnet und Tewkesbury?', '1471', ['1461', '1470', '1485']],
              ['Was geschah danach mit Heinrich VI.?', 'Er wurde im Tower getötet', ['Er floh nach Frankreich', 'Er wurde Mönch', 'Er regierte weiter']],
              ['Wann starb Eduard IV.?', '1483', ['1471', '1485', '1461']],
              ['Wie alt war Eduard V.?', 'Zwölf Jahre', ['Zwei Jahre', 'Zwanzig Jahre', 'Dreißig Jahre']],
              ['Welchen Titel hatte Richard vor seiner Krönung?', 'Herzog von Gloucester', ['Herzog von York', 'Graf von Warwick', 'Prinz von Wales']],
              ['An welchem Tag war die Schlacht von Bosworth?', '22. August 1485', ['14. Oktober 1066', '25. Oktober 1415', '29. März 1461']],
              ['Zu welchem Haus gehörte Heinrich Tudor als Erbe?', 'Zu Lancaster', ['Zu York', 'Zu Stuart', 'Zu Hannover']],
              ['Wann heiratete Heinrich VII. Elizabeth von York?', '1486', ['1485', '1483', '1500']],
              ['Wessen Tochter war Elizabeth von York?', 'Eduards IV.', ['Richards III.', 'Heinrichs VI.', 'Warwicks']],
              ['Was ist besonders an Richards Tod?', 'Er war der letzte englische König, der in einer Schlacht fiel', ['Er starb im Bett', 'Er wurde hingerichtet', 'Er ertrank']],
              ['Was bestätigte Richards Skelett?', 'Eine verkrümmte Wirbelsäule (Skoliose)', ['Dass er sehr groß war', 'Dass er Engländer war', 'Nichts']],
              ['Wann wurde Richards Skelett gefunden?', '2012', ['1485', '1900', '2020']],
              ['Wann stellte Caxton die Druckerpresse auf?', '1476', ['1450', '1485', '1500']],
            ],
            schwer: [
              ['Wann kam der Name „Rosenkriege“ auf?', 'Erst viel später, etwa durch Shakespeare und Walter Scott', ['Schon 1455', 'Im 20. Jahrhundert', 'Nie']],
              ['Wann regierte Heinrich VI.?', '1422–1461 und 1470–1471', ['1413–1422', '1461–1483', '1485–1509']],
              ['Wie viele Tote forderte Towton etwa?', 'Zehntausende', ['Dutzende', 'Hunderte', 'Millionen']],
              ['Warum hieß Warwick „Königsmacher“?', 'Er setzte Könige ein und wechselte die Seiten', ['Er war selbst König', 'Er krönte Könige als Bischof', 'Er baute Kronen']],
              ['Was glauben viele über die Prinzen im Tower?', 'Richard habe sie ermorden lassen', ['Sie wurden Könige in Frankreich', 'Sie lebten bis 1600', 'Sie wurden Papst']],
              ['Wie stellte Shakespeare Richard dar?', 'Als buckligen Bösewicht', ['Als Helden', 'Als Heiligen', 'Als Narren']],
              ['Wo wurde Caxtons Druckerpresse aufgestellt?', 'In Westminster', ['In Canterbury', 'In Oxford', 'In York']],
              ['Wo liegt Bosworth?', 'In Mittelengland bei Leicester', ['In Kent', 'In Schottland', 'In Wales']],
              ['Was symbolisierte die Heirat Heinrichs VII.?', 'Die Vereinigung von Lancaster und York', ['Ein Bündnis mit Frankreich', 'Die Trennung von Rom', 'Den Frieden mit Schottland']],
              ['Welcher Schriftsteller prägte den Begriff „Rosenkriege“ im 19. Jahrhundert mit?', 'Walter Scott', ['Charles Dickens', 'Jane Austen', 'Lord Byron']],
              ['Wann wurde Richard III. neu bestattet?', '2015', ['2012', '1485', '2000']],
              ['Wer war der Vater der Prinzen im Tower?', 'Eduard IV.', ['Richard III.', 'Heinrich VI.', 'Heinrich VII.']],
              ['Wo starb Heinrich VI. 1471?', 'Im Tower', ['In Barnet', 'In Frankreich', 'In York']],
              ['Welche Schlacht beendete die Rosenkriege praktisch?', 'Bosworth', ['Towton', 'Barnet', 'St Albans']],
              ['Wie heißt die Dynastie ab 1485?', 'Tudor', ['Stuart', 'York', 'Hannover']],
              ['Welches Leiden hatte Richard III. laut Skelett?', 'Skoliose', ['Gicht', 'Pest', 'Blindheit']],
              ['Welches Ereignis begann die Neuzeit in England?', 'Der Sieg der Tudors 1485', ['Die Magna Carta', 'Die Pest', 'Die Schlacht von Hastings']],
              ['Wie lange dauerten die Rosenkriege?', 'Rund 30 Jahre', ['Rund 100 Jahre', 'Ein Jahr', 'Zehn Tage']],
              ['Wer war Elizabeth von York für die Prinzen im Tower?', 'Ihre Schwester', ['Ihre Mutter', 'Ihre Tante', 'Ihre Cousine']],
              ['Welcher König regierte nur wenige Wochen 1483?', 'Eduard V.', ['Eduard IV.', 'Richard III.', 'Heinrich VI.']],
            ],
          },
        },
      ],
    },
  ],
};
