import type { Epoch } from '../types';

export const E3: Epoch = {
  id: 'neuzeit',
  name: 'Tudors und Stuarts',
  period: '1485–1714',
  events: [
    {
      id: 'tudors',
      title: 'Die Tudors',
      date: '1485–1603',
      text: [
        'Unter den Tudors löste sich England von der katholischen Kirche, stieg zur Seemacht auf und erlebte unter Elisabeth I. ein goldenes Zeitalter mit Shakespeare.',
      ],
      subtopics: [
        {
          id: 'heinrich-viii',
          title: 'Heinrich VIII. und die Kirche von England',
          date: '1485–1558',
          text: [
            'Heinrich VII. (1485–1509) festigte die Macht der Tudors und füllte die Staatskasse. Sein ältester Sohn Arthur heiratete 1501 die spanische Prinzessin Katharina von Aragón, starb aber schon 1502. Der jüngere Sohn wurde 1509 als Heinrich VIII. König und heiratete die Witwe seines Bruders.',
            'Heinrich VIII. (1509–1547) war gebildet, sportlich und prunkliebend. Doch Katharina gebar ihm nur eine überlebende Tochter, Maria. Heinrich wollte einen Sohn als Erben und verliebte sich in Anne Boleyn. Papst Clemens VII. verweigerte die Annullierung der Ehe – auch weil Katharinas Neffe Kaiser Karl V. ihn unter Druck setzte. Kardinal Wolsey, Heinrichs mächtiger Minister, scheiterte und stürzte 1529.',
            'Heinrich brach daraufhin mit Rom. Erzbischof Thomas Cranmer erklärte die Ehe 1533 für ungültig, Heinrich heiratete Anne Boleyn, und im September 1533 wurde ihre Tochter Elisabeth geboren. Mit dem Suprematsakt von 1534 machte sich der König zum Oberhaupt der Kirche von England (Church of England). Wer das nicht anerkannte, wurde hingerichtet – so 1535 der frühere Lordkanzler Thomas Morus, Autor der „Utopia“. Unter Heinrichs Minister Thomas Cromwell wurden von 1536 bis 1541 alle Klöster aufgelöst und ihr Besitz eingezogen; einen Aufstand im Norden, die „Pilgerfahrt der Gnade“ (1536), schlug Heinrich nieder.',
            'Heinrich war sechsmal verheiratet. Ein englischer Merkvers fasst das Schicksal seiner Frauen zusammen: „geschieden, geköpft, gestorben, geschieden, geköpft, überlebt“. Katharina von Aragón wurde verstoßen, Anne Boleyn 1536 wegen angeblichen Ehebruchs enthauptet, Jane Seymour starb 1537 kurz nach der Geburt des ersehnten Sohnes Eduard, die Ehe mit Anna von Kleve wurde 1540 nach wenigen Monaten aufgelöst, Catherine Howard 1542 enthauptet, und Catherine Parr überlebte ihn. Der Maler Hans Holbein der Jüngere schuf die berühmten Porträts des Königs.',
            'Heinrich baute eine starke Kriegsflotte auf; sein Flaggschiff „Mary Rose“ sank 1545 vor Portsmouth und wurde 1982 gehoben. Wales wurde 1535/1542 rechtlich mit England vereinigt. Nach Heinrichs Tod 1547 wurde sein Sohn Eduard VI. König, unter dem England protestantisch wurde (Book of Common Prayer, 1549). Nach dessen frühem Tod 1553 – er wurde nur 15 Jahre alt – regierte Lady Jane Grey nur neun Tage. Dann wurde Heinrichs katholische Tochter Maria I. Königin.',
            'Maria I. (1553–1558) führte das Land zum Katholizismus zurück und heiratete Philipp II. von Spanien. Rund 280 Protestanten ließ sie verbrennen, darunter 1556 Erzbischof Cranmer – daher ihr Beiname „Bloody Mary“ (die blutige Maria). 1558 verlor England Calais, seinen letzten Besitz in Frankreich. Maria starb noch im selben Jahr kinderlos.',
          ],
          quiz: {
            leicht: [
              ['Wie oft war Heinrich VIII. verheiratet?', 'Sechsmal', ['Zweimal', 'Dreimal', 'Zehnmal']],
              ['Warum wollte Heinrich VIII. sich scheiden lassen?', 'Er wollte einen Sohn als Erben', ['Er wollte Papst werden', 'Er wollte nach Spanien', 'Er hasste Musik']],
              ['Mit wem brach Heinrich VIII.?', 'Mit der Kirche in Rom', ['Mit Frankreich', 'Mit Schottland', 'Mit seinem Volk']],
              ['Wie heißt die englische Staatskirche?', 'Church of England', ['Katholische Kirche', 'Orthodoxe Kirche', 'Lutherische Kirche']],
              ['Wer wurde Oberhaupt der Church of England?', 'Der König', ['Der Papst', 'Der Erzbischof von York', 'Das Parlament']],
              ['Welche Frau Heinrichs war die Mutter von Elisabeth I.?', 'Anne Boleyn', ['Katharina von Aragón', 'Jane Seymour', 'Catherine Parr']],
              ['Was geschah mit Anne Boleyn?', 'Sie wurde enthauptet', ['Sie überlebte', 'Sie wurde Königin von Frankreich', 'Sie floh']],
              ['Welche Frau gebar Heinrich den Sohn Eduard?', 'Jane Seymour', ['Anne Boleyn', 'Katharina von Aragón', 'Anna von Kleve']],
              ['Welche Frau überlebte Heinrich?', 'Catherine Parr', ['Catherine Howard', 'Anne Boleyn', 'Jane Seymour']],
              ['Woher stammte Katharina von Aragón?', 'Aus Spanien', ['Aus Frankreich', 'Aus Deutschland', 'Aus Schottland']],
              ['Woher stammte Anna von Kleve?', 'Aus Deutschland', ['Aus Spanien', 'Aus England', 'Aus Frankreich']],
              ['Was ließ Heinrich mit den Klöstern geschehen?', 'Er ließ sie auflösen', ['Er baute neue', 'Er schenkte sie dem Papst', 'Nichts']],
              ['Welcher Gelehrte wurde 1535 hingerichtet?', 'Thomas Morus', ['Thomas Cromwell', 'Erasmus', 'Thomas Cranmer']],
              ['Welches Buch schrieb Thomas Morus?', '„Utopia“', ['„Hamlet“', '„Leviathan“', '„Robinson Crusoe“']],
              ['Welcher Maler porträtierte Heinrich VIII.?', 'Hans Holbein', ['Rembrandt', 'Dürer', 'Leonardo']],
              ['Wie hieß Heinrichs berühmtes Kriegsschiff?', 'Mary Rose', ['Victory', 'Titanic', 'Golden Hind']],
              ['Wie nennt man Maria I.?', '„Bloody Mary“', ['„Virgin Queen“', '„Good Queen Mary“', '„Mary of the Scots“']],
              ['Welcher Religion gehörte Maria I. an?', 'Sie war katholisch', ['Sie war protestantisch', 'Sie war Muslimin', 'Sie war Jüdin']],
              ['Wen heiratete Maria I.?', 'Philipp II. von Spanien', ['Karl V.', 'Franz I.', 'Heinrich II.']],
              ['Welchen letzten Besitz in Frankreich verlor England 1558?', 'Calais', ['Bordeaux', 'Rouen', 'Paris']],
            ],
            mittel: [
              ['Wen heiratete Heinrichs Bruder Arthur 1501?', 'Katharina von Aragón', ['Anne Boleyn', 'Maria Stuart', 'Margarete Tudor']],
              ['Wann wurde Heinrich VIII. König?', '1509', ['1485', '1533', '1547']],
              ['Welcher Papst verweigerte die Annullierung?', 'Clemens VII.', ['Leo X.', 'Paul III.', 'Pius V.']],
              ['Wessen Neffe übte Druck auf den Papst aus?', 'Kaiser Karl V.', ['Franz I.', 'Philipp II.', 'Maximilian I.']],
              ['Welcher Kardinal und Minister stürzte 1529?', 'Wolsey', ['Cromwell', 'Cranmer', 'Morus']],
              ['Wer erklärte die Ehe mit Katharina 1533 für ungültig?', 'Erzbischof Thomas Cranmer', ['Der Papst', 'Thomas Morus', 'Wolsey']],
              ['Wann wurde Elisabeth geboren?', 'September 1533', ['Januar 1536', 'Oktober 1537', 'März 1547']],
              ['Mit welchem Gesetz wurde der König Oberhaupt der Kirche?', 'Mit dem Suprematsakt 1534', ['Mit der Magna Carta', 'Mit der Bill of Rights', 'Mit dem Act of Union']],
              ['Welches Amt hatte Thomas Morus früher?', 'Lordkanzler', ['Erzbischof', 'General', 'Bürgermeister']],
              ['Welcher Minister leitete die Auflösung der Klöster?', 'Thomas Cromwell', ['Oliver Cromwell', 'Thomas Wolsey', 'Thomas Cranmer']],
              ['Wann wurden die Klöster aufgelöst?', '1536–1541', ['1509–1515', '1547–1553', '1558–1603']],
              ['Wie hieß der Aufstand im Norden 1536?', 'Pilgerfahrt der Gnade', ['Bauernaufstand', 'Rosenkrieg', 'Pulververschwörung']],
              ['Wann wurde Anne Boleyn hingerichtet?', '1536', ['1533', '1542', '1547']],
              ['Wann starb Jane Seymour?', '1537', ['1536', '1540', '1547']],
              ['Wann sank die Mary Rose?', '1545', ['1588', '1509', '1982']],
              ['Wann wurde die Mary Rose gehoben?', '1982', ['1545', '1900', '2002']],
              ['Unter welchem König wurde England protestantisch?', 'Eduard VI.', ['Heinrich VII.', 'Maria I.', 'Jakob I.']],
              ['Wie lange regierte Lady Jane Grey?', 'Neun Tage', ['Neun Monate', 'Neun Jahre', 'Einen Tag']],
              ['Wie viele Protestanten ließ Maria I. etwa verbrennen?', 'Rund 280', ['Rund 28', 'Rund 2800', 'Keinen']],
              ['Wann starb Maria I.?', '1558', ['1553', '1547', '1603']],
            ],
            schwer: [
              ['Wie lautet der Merkvers zu Heinrichs Frauen?', '„Geschieden, geköpft, gestorben, geschieden, geköpft, überlebt“', ['„Geliebt, verloren, geheiratet, vergessen“', '„Eins, zwei, drei, vier, fünf, sechs“', '„Rot, weiß, rot, weiß“']],
              ['Wann wurde die Ehe mit Anna von Kleve aufgelöst?', '1540', ['1536', '1542', '1537']],
              ['Wann wurde Catherine Howard enthauptet?', '1542', ['1536', '1540', '1547']],
              ['Vor welcher Stadt sank die Mary Rose?', 'Vor Portsmouth', ['Vor Dover', 'Vor Plymouth', 'Vor London']],
              ['Wann wurde Wales rechtlich mit England vereinigt?', '1535/1542', ['1282', '1707', '1801']],
              ['Welches Gebetbuch erschien 1549?', 'Das Book of Common Prayer', ['Die King-James-Bibel', 'Das Domesday Book', 'Utopia']],
              ['Wann wurde Cranmer verbrannt?', '1556', ['1533', '1553', '1558']],
              ['Wann regierte Heinrich VII.?', '1485–1509', ['1509–1547', '1461–1483', '1547–1553']],
              ['Wann starb Arthur, Heinrichs Bruder?', '1502', ['1501', '1509', '1485']],
              ['Wie hieß Heinrichs Tochter mit Katharina von Aragón?', 'Maria', ['Elisabeth', 'Anne', 'Jane']],
              ['Wessen Witwe heiratete Heinrich VIII. zuerst?', 'Die seines Bruders Arthur', ['Die seines Vaters', 'Die eines Herzogs', 'Die Witwe Karls V.']],
              ['Welcher Vorwurf führte zur Hinrichtung Anne Boleyns?', 'Angeblicher Ehebruch', ['Diebstahl', 'Hexerei', 'Verrat an Spanien']],
              ['Wann regierte Eduard VI.?', '1547–1553', ['1537–1547', '1553–1558', '1509–1547']],
              ['Wie alt wurde Eduard VI. etwa?', 'Etwa 15 Jahre', ['Etwa 50 Jahre', 'Etwa 5 Jahre', 'Etwa 30 Jahre']],
              ['Wer wurde 1553 nach Lady Jane Grey Königin?', 'Maria I.', ['Elisabeth I.', 'Maria Stuart', 'Katharina Parr']],
              ['Warum verweigerte der Papst die Annullierung auch?', 'Weil Karl V. Katharinas Neffe war', ['Weil Heinrich Protestant war', 'Weil Anne Spanierin war', 'Weil der Papst Heinrich hasste']],
              ['Wie stand Thomas Morus zum Suprematsakt?', 'Er erkannte ihn nicht an', ['Er schrieb ihn', 'Er unterstützte ihn', 'Er war schon tot']],
              ['Wohin floss der Besitz der Klöster?', 'An die Krone', ['An den Papst', 'An die Bauern', 'An Spanien']],
              ['Welcher König war Philipp II. außerdem durch die Heirat?', 'König von England (an Marias Seite)', ['Kaiser', 'König von Frankreich', 'Herzog von Wales']],
              ['Welcher Teil von Heinrichs Politik betraf die Seemacht?', 'Er baute eine starke Kriegsflotte auf', ['Er schaffte die Flotte ab', 'Er verkaufte Schiffe an Spanien', 'Gar keiner']],
            ],
          },
        },
        {
          id: 'elisabeth-i',
          title: 'Elisabeth I. und das goldene Zeitalter',
          date: '1558–1603',
          text: [
            'Elisabeth I. (1558–1603), die Tochter Heinrichs VIII. und Anne Boleyns, gilt als eine der bedeutendsten Herrscherinnen Englands. Sie heiratete nie und wurde deshalb „die jungfräuliche Königin“ (Virgin Queen) genannt. 1559 machte sie England endgültig protestantisch, gestaltete die Kirche aber so, dass auch viele Katholiken sie hinnehmen konnten. Ihr wichtigster Berater war William Cecil.',
            'Eine Gefahr war ihre katholische Cousine Maria Stuart, Königin von Schottland, die selbst Anspruch auf den englischen Thron hatte. Nach einem Aufstand gegen sie floh Maria 1568 nach England, wo Elisabeth sie 19 Jahre lang gefangen hielt. Als man Maria die Beteiligung an einer Verschwörung gegen Elisabeth nachwies, wurde sie im Februar 1587 auf Schloss Fotheringhay enthauptet.',
            'Daraufhin schickte der spanische König Philipp II. 1588 die „Armada“, eine Flotte von rund 130 Schiffen unter dem Herzog von Medina Sidonia, um England zu erobern. Die wendigeren englischen Schiffe griffen an, und vor Gravelines trieben die Engländer brennende Schiffe (Brander) gegen die Spanier. Auf der Flucht um Schottland und Irland zerschellten viele Schiffe in Stürmen. Vor ihren Truppen in Tilbury sagte Elisabeth: „Ich weiß, ich habe den Leib eines schwachen Weibes, aber ich habe das Herz und den Mut eines Königs.“',
            'Seefahrer wie Francis Drake machten England zur Seemacht. Drake umsegelte von 1577 bis 1580 als erster Engländer die Welt und wurde auf seinem Schiff „Golden Hind“ zum Ritter geschlagen. Er überfiel auch spanische Silberschiffe – für Spanien war er ein Pirat. Walter Raleigh versuchte, in Nordamerika eine Kolonie zu gründen, die er zu Ehren der jungfräulichen Königin „Virginia“ nannte (Roanoke, 1585). 1600 wurde die Ostindien-Kompanie gegründet.',
            'Das Theater blühte. William Shakespeare (1564–1616), in Stratford-upon-Avon geboren, schrieb Dramen wie „Romeo und Julia“, „Hamlet“, „Macbeth“ und „Ein Sommernachtstraum“, die im 1599 eröffneten Globe Theatre in London gespielt wurden. Auch Christopher Marlowe schrieb erfolgreiche Stücke. 1601 regelten die Armengesetze erstmals die Unterstützung der Armen durch die Gemeinden.',
            'Elisabeth starb am 24. März 1603 als letzte Tudor. Ihr Nachfolger wurde der Sohn Maria Stuarts: König Jakob VI. von Schottland.',
          ],
          quiz: {
            leicht: [
              ['Wessen Tochter war Elisabeth I.?', 'Heinrichs VIII. und Anne Boleyns', ['Heinrichs VII.', 'Marias I.', 'Jakobs I.']],
              ['Wie nannte man Elisabeth I.?', '„Die jungfräuliche Königin“', ['„Die blutige Königin“', '„Die Kaiserin“', '„Die Königin der Schotten“']],
              ['Heiratete Elisabeth I.?', 'Nein, nie', ['Ja, Philipp II.', 'Ja, dreimal', 'Ja, einen Franzosen']],
              ['Welche Religion setzte Elisabeth endgültig durch?', 'Den Protestantismus', ['Den Katholizismus', 'Den Islam', 'Das Judentum']],
              ['Welche Cousine war eine Gefahr für Elisabeth?', 'Maria Stuart', ['Maria I.', 'Lady Jane Grey', 'Anne Boleyn']],
              ['Wo war Maria Stuart Königin?', 'In Schottland', ['In Frankreich', 'In Spanien', 'In Irland']],
              ['Was geschah mit Maria Stuart 1587?', 'Sie wurde enthauptet', ['Sie wurde Königin von England', 'Sie floh nach Spanien', 'Sie wurde Nonne']],
              ['Wie hieß die spanische Flotte von 1588?', 'Armada', ['Invincible', 'Golden Hind', 'Mayflower']],
              ['Welcher spanische König schickte die Armada?', 'Philipp II.', ['Karl V.', 'Ferdinand', 'Philipp V.']],
              ['Wie endete der Angriff der Armada?', 'Mit einer Niederlage der Spanier', ['Mit der Eroberung Londons', 'Mit einem Frieden', 'Mit einem Bündnis']],
              ['Was zerstörte viele spanische Schiffe auf der Flucht?', 'Stürme', ['Eisberge', 'Haie', 'Ein Erdbeben']],
              ['Welcher Seefahrer umsegelte als erster Engländer die Welt?', 'Francis Drake', ['Walter Raleigh', 'James Cook', 'Christoph Kolumbus']],
              ['Wie hieß Drakes Schiff?', 'Golden Hind', ['Mary Rose', 'Mayflower', 'Victory']],
              ['Wie nannten die Spanier Drake?', 'Einen Piraten', ['Einen Heiligen', 'Einen König', 'Einen Freund']],
              ['Welche Kolonie benannte Raleigh nach der Königin?', 'Virginia', ['Georgia', 'Maryland', 'Elizabethtown']],
              ['Welcher berühmte Dichter lebte zur Zeit Elisabeths?', 'William Shakespeare', ['Charles Dickens', 'Geoffrey Chaucer', 'Lord Byron']],
              ['Wo wurde Shakespeare geboren?', 'In Stratford-upon-Avon', ['In London', 'In Oxford', 'In Edinburgh']],
              ['Welches Drama schrieb Shakespeare?', '„Hamlet“', ['„Faust“', '„Don Quijote“', '„Die Räuber“']],
              ['In welchem Theater wurden Shakespeares Stücke gespielt?', 'Im Globe Theatre', ['In der Royal Albert Hall', 'Im Old Vic', 'Im Covent Garden']],
              ['Wer wurde 1603 Nachfolger Elisabeths?', 'Jakob VI. von Schottland', ['Philipp II.', 'Karl I.', 'Oliver Cromwell']],
            ],
            mittel: [
              ['Wann regierte Elisabeth I.?', '1558–1603', ['1533–1558', '1603–1625', '1509–1547']],
              ['Wann machte Elisabeth England endgültig protestantisch?', '1559', ['1534', '1588', '1603']],
              ['Wer war Elisabeths wichtigster Berater?', 'William Cecil', ['Thomas Cromwell', 'Francis Drake', 'Walter Raleigh']],
              ['Wann floh Maria Stuart nach England?', '1568', ['1558', '1587', '1603']],
              ['Wie lange hielt Elisabeth Maria Stuart gefangen?', '19 Jahre', ['1 Jahr', '9 Jahre', '30 Jahre']],
              ['Wo wurde Maria Stuart enthauptet?', 'Auf Schloss Fotheringhay', ['Im Tower', 'In Edinburgh', 'In Windsor']],
              ['Warum wurde Maria Stuart hingerichtet?', 'Wegen Beteiligung an einer Verschwörung', ['Wegen Hexerei', 'Wegen Diebstahls', 'Wegen Ketzerei']],
              ['Wie viele Schiffe hatte die Armada etwa?', 'Rund 130', ['Rund 13', 'Rund 1300', 'Rund 30']],
              ['Wer führte die Armada?', 'Der Herzog von Medina Sidonia', ['Francis Drake', 'Philipp II. selbst', 'Don Juan de Austria']],
              ['Wo trieben die Engländer Brander gegen die Spanier?', 'Vor Gravelines', ['Vor Plymouth', 'Vor Cádiz', 'Vor Dover']],
              ['Was sind Brander?', 'Brennende Schiffe, die gegen Feinde getrieben werden', ['Kanonen', 'Spione', 'Leuchttürme']],
              ['Wo sprach Elisabeth zu ihren Truppen?', 'In Tilbury', ['In London', 'In Windsor', 'In Plymouth']],
              ['Was hatte Elisabeth laut ihrer Rede?', 'Das Herz und den Mut eines Königs', ['Die Krone Spaniens', 'Eine Flotte aus Gold', 'Einen Ehemann']],
              ['Wann umsegelte Drake die Welt?', '1577–1580', ['1588', '1600', '1519–1522']],
              ['Wo wurde Drake zum Ritter geschlagen?', 'Auf seinem Schiff Golden Hind', ['In Westminster', 'In Tilbury', 'Im Tower']],
              ['Wann versuchte Raleigh, Roanoke zu gründen?', '1585', ['1607', '1620', '1600']],
              ['Wann wurde die Ostindien-Kompanie gegründet?', '1600', ['1588', '1620', '1700']],
              ['Wann wurde Shakespeare geboren?', '1564', ['1558', '1588', '1616']],
              ['Wann wurde das Globe Theatre eröffnet?', '1599', ['1564', '1603', '1613']],
              ['Welcher Dramatiker war Shakespeares Zeitgenosse?', 'Christopher Marlowe', ['Molière', 'Goethe', 'Ibsen']],
            ],
            schwer: [
              ['An welchem Tag starb Elisabeth I.?', '24. März 1603', ['8. Februar 1587', '17. November 1558', '5. November 1605']],
              ['Wie gestaltete Elisabeth die Kirche?', 'Protestantisch, aber annehmbar für viele Katholiken', ['Streng katholisch', 'Streng puritanisch', 'Gar nicht']],
              ['In welchem Monat 1587 wurde Maria Stuart enthauptet?', 'Februar', ['August', 'Dezember', 'Juni']],
              ['Um welche Inseln flüchtete die Armada?', 'Um Schottland und Irland', ['Um Island', 'Um die Kanaren', 'Um Sizilien']],
              ['Was waren die Vorteile der englischen Schiffe?', 'Sie waren wendiger', ['Sie waren größer', 'Sie hatten Ruder', 'Sie waren aus Eisen']],
              ['Welche Schiffe überfiel Drake?', 'Spanische Silberschiffe', ['Englische Handelsschiffe', 'Wikingerschiffe', 'Chinesische Dschunken']],
              ['Was regelten die Armengesetze von 1601?', 'Die Unterstützung der Armen durch die Gemeinden', ['Den Kriegsdienst', 'Den Theaterbesuch', 'Die Steuern des Adels']],
              ['Welches Shakespeare-Stück handelt von einem schottischen König?', '„Macbeth“', ['„Hamlet“', '„Othello“', '„König Lear“']],
              ['Wer war Elisabeths Nachfolger in Bezug auf Maria Stuart?', 'Marias Sohn', ['Marias Bruder', 'Marias Mann', 'Marias Vater']],
              ['Welcher Name ehrt die jungfräuliche Königin in Amerika?', 'Virginia', ['Carolina', 'Maryland', 'Georgia']],
              ['Welche Dynastie endete mit Elisabeth?', 'Die Tudors', ['Die Stuarts', 'Die Plantagenets', 'Die Hannoveraner']],
              ['Welche Stadt in Nordamerika versuchte Raleigh zu besiedeln?', 'Roanoke', ['Jamestown', 'Plymouth', 'Boston']],
              ['Welche Handelsgesellschaft entstand 1600?', 'Die Ostindien-Kompanie', ['Die Hanse', 'Die Hudson’s Bay Company', 'Die Bank of England']],
              ['Wie nannte man Elisabeths Herrschaftszeit?', 'Goldenes Zeitalter', ['Dunkles Zeitalter', 'Eisenzeit', 'Zeitalter der Pest']],
              ['Welcher spanische Plan scheiterte 1588?', 'Die Eroberung Englands', ['Die Eroberung Frankreichs', 'Ein Bündnis mit England', 'Die Eroberung Amerikas']],
              ['Warum hatte Maria Stuart Anspruch auf den englischen Thron?', 'Sie stammte von den Tudors ab', ['Sie war Elisabeths Tochter', 'Der Papst gab ihn ihr', 'Sie war Spanierin']],
              ['Wann erreichte Drake England nach der Weltumsegelung?', '1580', ['1577', '1588', '1600']],
              ['Welche Ehre erhielt Drake von Elisabeth?', 'Den Ritterschlag', ['Die Krone', 'Ein Bistum', 'Den Titel Herzog von Wales']],
              ['Welche Stücke Shakespeares sind Komödien?', '„Ein Sommernachtstraum“', ['„Hamlet“', '„Macbeth“', '„Othello“']],
              ['Wie alt wurde Shakespeare etwa?', 'Etwa 52 Jahre (1564–1616)', ['Etwa 30 Jahre', 'Etwa 80 Jahre', 'Etwa 100 Jahre']],
            ],
          },
        },
      ],
    },
    {
      id: 'stuarts',
      title: 'Die Stuarts: Bürgerkrieg und Glorreiche Revolution',
      date: '1603–1714',
      text: [
        'Die Stuarts herrschten über England und Schottland. Ihr Streit mit dem Parlament führte zum Bürgerkrieg, zur Hinrichtung eines Königs und zur einzigen Republik der englischen Geschichte – und schließlich zur Glorreichen Revolution, die das Parlament zum mächtigsten Organ machte.',
      ],
      subtopics: [
        {
          id: 'buergerkrieg-cromwell',
          title: 'Jakob I., Bürgerkrieg und Cromwell',
          date: '1603–1660',
          text: [
            'Als Jakob VI. von Schottland 1603 als Jakob I. auch König von England wurde, waren beide Kronen in einer Person vereint („Union der Kronen“), die Länder blieben aber getrennt. Katholische Verschwörer um Robert Catesby wollten den protestantischen König am 5. November 1605 bei der Parlamentseröffnung in die Luft sprengen (Pulververschwörung). Guy Fawkes wurde im Keller unter dem Oberhaus mit 36 Fässern Schießpulver ertappt. Bis heute feiern die Briten am 5. November die „Bonfire Night“ mit Feuerwerk. 1611 erschien die „King-James-Bibel“, die einflussreichste englische Bibelübersetzung.',
            'In Amerika entstand 1607 mit Jamestown in Virginia die erste dauerhafte englische Siedlung. 1620 brachen die „Pilgerväter“, streng protestantische Puritaner, mit der „Mayflower“ auf und gründeten Plymouth in Massachusetts.',
            'Karl I. (1625–1649) glaubte wie sein Vater an das „Gottesgnadentum“: Der König sei nur Gott verantwortlich. 1628 musste er der „Petition of Right“ zustimmen, regierte aber ab 1629 elf Jahre ohne Parlament und trieb eigenmächtig Steuern ein, etwa das „Schiffsgeld“. Als er den Schotten ein neues Gebetbuch aufzwang, erhoben sie sich 1637. Für den Krieg brauchte er Geld und berief 1640 das „Lange Parlament“ ein, das ihm aber die Macht beschneiden wollte. 1642 versuchte er, fünf Abgeordnete im Parlament verhaften zu lassen – vergeblich.',
            'Im August 1642 begann der Bürgerkrieg zwischen den Königstreuen („Kavaliere“) und den Anhängern des Parlaments („Rundköpfe“, nach den kurz geschnittenen Haaren vieler Puritaner). Der Abgeordnete Oliver Cromwell, ein Puritaner aus Ostengland, schuf mit der „New Model Army“ ein diszipliniertes Heer. Die Parlamentstruppen siegten 1644 bei Marston Moor und 1645 bei Naseby. Karl wurde gefangen genommen, wegen Hochverrats angeklagt und am 30. Januar 1649 vor dem Banqueting House in Whitehall enthauptet – der einzige englische König, der nach einem Prozess hingerichtet wurde.',
            'England wurde eine Republik, das „Commonwealth“. Cromwell schlug Aufstände in Irland brutal nieder; bei der Eroberung von Drogheda 1649 wurden Tausende getötet. 1653 löste er das Parlament auf und regierte als „Lordprotektor“ fast wie ein Monarch. Die Puritaner schlossen Theater und verboten zeitweise die Weihnachtsfeiern. 1656 durften Juden wieder in England leben. Cromwell starb 1658; sein Sohn Richard konnte sich nicht halten.',
          ],
          quiz: {
            leicht: [
              ['Welcher schottische König wurde 1603 auch König von England?', 'Jakob VI. (Jakob I.)', ['Karl I.', 'Robert the Bruce', 'Wilhelm III.']],
              ['Wie nennt man die Vereinigung beider Kronen 1603?', 'Union der Kronen', ['Act of Union', 'Commonwealth', 'Glorreiche Revolution']],
              ['Was wollten die Verschwörer 1605?', 'Den König in die Luft sprengen', ['Den Papst wählen', 'Nach Amerika fliehen', 'Schottland erobern']],
              ['Wer wurde mit dem Schießpulver ertappt?', 'Guy Fawkes', ['Oliver Cromwell', 'Robin Hood', 'Francis Drake']],
              ['Wie heißt der Gedenktag am 5. November?', 'Bonfire Night', ['Boxing Day', 'Guy Day', 'Halloween']],
              ['Welche Bibelübersetzung erschien 1611?', 'Die King-James-Bibel', ['Die Lutherbibel', 'Die Vulgata', 'Das Book of Common Prayer']],
              ['Welche Siedlung war die erste dauerhafte englische in Amerika?', 'Jamestown', ['Plymouth', 'Boston', 'New York']],
              ['Mit welchem Schiff fuhren die Pilgerväter 1620?', 'Mayflower', ['Golden Hind', 'Mary Rose', 'Victory']],
              ['Woran glaubte Karl I.?', 'An das Gottesgnadentum', ['An die Demokratie', 'An die Republik', 'An das Parlament']],
              ['Wie nannte man die Königstreuen im Bürgerkrieg?', 'Kavaliere', ['Rundköpfe', 'Puritaner', 'Whigs']],
              ['Wie nannte man die Anhänger des Parlaments?', 'Rundköpfe', ['Kavaliere', 'Tories', 'Jakobiten']],
              ['Wer führte die Parlamentstruppen an?', 'Oliver Cromwell', ['Thomas Cromwell', 'Guy Fawkes', 'Karl II.']],
              ['Wie hieß Cromwells Heer?', 'New Model Army', ['Grande Armée', 'Royal Navy', 'Rote Armee']],
              ['Was geschah mit Karl I. 1649?', 'Er wurde enthauptet', ['Er floh nach Frankreich', 'Er wurde Kaiser', 'Er dankte freiwillig ab']],
              ['Was wurde England nach 1649?', 'Eine Republik', ['Ein Kaiserreich', 'Ein Teil Frankreichs', 'Eine absolute Monarchie']],
              ['Welchen Titel trug Cromwell ab 1653?', 'Lordprotektor', ['König', 'Präsident', 'Kaiser']],
              ['Welche Gruppe schloss Theater und verbot Weihnachtsfeiern?', 'Die Puritaner', ['Die Katholiken', 'Die Kavaliere', 'Die Quäker']],
              ['Wann begann der Englische Bürgerkrieg?', '1642', ['1605', '1649', '1688']],
              ['Wann starb Oliver Cromwell?', '1658', ['1649', '1660', '1688']],
              ['Wann durften Juden wieder in England leben?', '1656', ['1290', '1700', '1800']],
            ],
            mittel: [
              ['Wer führte die Pulververschwörung an?', 'Robert Catesby', ['Thomas Cranmer', 'Thomas Morus', 'Walter Raleigh']],
              ['Wie viele Fässer Schießpulver fand man?', '36', ['3', '360', '1']],
              ['Wo lag das Schießpulver?', 'Im Keller unter dem Oberhaus', ['Im Tower', 'In der Westminster Abbey', 'In einem Schiff']],
              ['Wann sollte die Pulververschwörung stattfinden?', '5. November 1605', ['30. Januar 1649', '1. Mai 1605', '25. Dezember 1605']],
              ['Wann wurde Jamestown gegründet?', '1607', ['1585', '1620', '1600']],
              ['Welche Siedlung gründeten die Pilgerväter?', 'Plymouth in Massachusetts', ['Jamestown', 'New Amsterdam', 'Charleston']],
              ['Welcher Glaubensrichtung gehörten die Pilgerväter an?', 'Den Puritanern', ['Den Katholiken', 'Den Anglikanern', 'Den Lutheranern']],
              ['Welchem Dokument musste Karl I. 1628 zustimmen?', 'Der Petition of Right', ['Der Magna Carta', 'Der Bill of Rights', 'Dem Act of Union']],
              ['Wie lange regierte Karl I. ohne Parlament?', 'Elf Jahre', ['Ein Jahr', 'Dreißig Jahre', 'Nie']],
              ['Welche eigenmächtige Steuer trieb Karl ein?', 'Das Schiffsgeld', ['Die Kopfsteuer', 'Das Danegeld', 'Den Zehnt']],
              ['Was löste 1637 den schottischen Aufstand aus?', 'Ein aufgezwungenes Gebetbuch', ['Eine neue Steuer', 'Eine Hungersnot', 'Ein Mord']],
              ['Wann berief Karl das Lange Parlament ein?', '1640', ['1629', '1642', '1649']],
              ['Wie viele Abgeordnete wollte Karl 1642 verhaften lassen?', 'Fünf', ['Einen', 'Hundert', 'Alle']],
              ['Woher kommt der Name „Rundköpfe“?', 'Von den kurz geschnittenen Haaren vieler Puritaner', ['Von runden Helmen', 'Von runden Schilden', 'Von Kanonenkugeln']],
              ['Wo siegten die Parlamentstruppen 1644?', 'Bei Marston Moor', ['Bei Naseby', 'Bei Bosworth', 'Bei Worcester']],
              ['Wo siegten sie 1645?', 'Bei Naseby', ['Bei Marston Moor', 'Bei Edgehill', 'Bei Culloden']],
              ['An welchem Tag wurde Karl I. enthauptet?', '30. Januar 1649', ['5. November 1649', '29. Mai 1660', '14. Juni 1645']],
              ['Vor welchem Gebäude wurde Karl I. enthauptet?', 'Vor dem Banqueting House in Whitehall', ['Vor dem Tower', 'Vor Westminster Abbey', 'Vor St Paul’s']],
              ['Wie hieß die englische Republik?', 'Commonwealth', ['Empire', 'Dominion', 'Kingdom']],
              ['Wo ließ Cromwell 1649 Tausende töten?', 'In Drogheda in Irland', ['In Edinburgh', 'In London', 'In Wales']],
            ],
            schwer: [
              ['Was ist besonders an Karls I. Hinrichtung?', 'Er ist der einzige englische König, der nach einem Prozess hingerichtet wurde', ['Er wurde vom Papst verurteilt', 'Er starb in der Schlacht', 'Er wurde begnadigt']],
              ['Wann löste Cromwell das Parlament auf?', '1653', ['1649', '1658', '1642']],
              ['Wie regierte Cromwell als Lordprotektor?', 'Fast wie ein Monarch', ['Als gewählter Präsident', 'Ohne Macht', 'Als Papst']],
              ['Was geschah mit Cromwells Sohn Richard?', 'Er konnte sich nicht halten', ['Er wurde König', 'Er regierte 30 Jahre', 'Er eroberte Frankreich']],
              ['Woher stammte Oliver Cromwell?', 'Aus Ostengland', ['Aus Schottland', 'Aus Irland', 'Aus London']],
              ['Wann begann der Bürgerkrieg genau?', 'August 1642', ['Januar 1642', 'Januar 1649', 'November 1605']],
              ['Was bedeutet „Gottesgnadentum“?', 'Der König ist nur Gott verantwortlich', ['Der König wird gewählt', 'Gott ist König', 'Der Papst ernennt Könige']],
              ['Wofür steht die King-James-Bibel?', 'Die einflussreichste englische Bibelübersetzung', ['Eine katholische Bibel', 'Eine Kinderbibel', 'Eine lateinische Bibel']],
              ['Wann erhoben sich die Schotten wegen des Gebetbuchs?', '1637', ['1640', '1603', '1649']],
              ['Was wollte das Lange Parlament?', 'Die Macht des Königs beschneiden', ['Den König stärken', 'Krieg mit Spanien', 'Die Republik sofort']],
              ['Welcher Glaubensgruppe gehörte Cromwell an?', 'Den Puritanern', ['Den Katholiken', 'Den Quäkern', 'Den Juden']],
              ['Was verband die Union der Kronen nicht?', 'Die beiden Länder selbst', ['Die Kronen', 'Die Person des Königs', 'Nichts']],
              ['Welche Rolle hatte Guy Fawkes?', 'Er bewachte das Schießpulver', ['Er war der König', 'Er war der Erzbischof', 'Er verriet die Verschwörung']],
              ['Gegen welche Religion des Königs richtete sich die Pulververschwörung?', 'Gegen den protestantischen König', ['Gegen einen katholischen König', 'Gegen den Papst', 'Gegen die Juden']],
              ['Was ist das „Lange Parlament“?', 'Das 1640 einberufene Parlament, das lange tagte', ['Ein Parlament mit langen Bänken', 'Das Parlament von 1295', 'Das schottische Parlament']],
              ['Was war die Folge von Naseby?', 'Die entscheidende Niederlage der Königstreuen', ['Ein Sieg des Königs', 'Ein Frieden mit Spanien', 'Die Pest']],
              ['Wann regierte Karl I.?', '1625–1649', ['1603–1625', '1649–1660', '1660–1685']],
              ['Welches Fest verboten die Puritaner zeitweise?', 'Weihnachten', ['Ostern', 'Neujahr', 'Halloween']],
              ['Was feiert man am 5. November mit Feuerwerk?', 'Die Vereitelung der Pulververschwörung', ['Den Sieg über die Armada', 'Die Hinrichtung Karls I.', 'Die Krönung Elisabeths']],
              ['Wann regierte Jakob I. in England?', '1603–1625', ['1567–1603', '1625–1649', '1660–1685']],
            ],
          },
        },
        {
          id: 'glorreiche-revolution',
          title: 'Restauration und Glorreiche Revolution',
          date: '1660–1714',
          text: [
            '1660 holte das Parlament den Sohn des hingerichteten Königs aus dem Exil zurück: Karl II. (1660–1685), den lebenslustigen „Merry Monarch“. Theater öffneten wieder, und 1660 entstand die Royal Society, eine der ältesten Wissenschaftsakademien der Welt. Isaac Newton veröffentlichte 1687 seine „Principia“ mit dem Gravitationsgesetz.',
            '1665 tötete die Große Pest in London rund 100.000 Menschen. Am 2. September 1666 brach in einer Bäckerei in der Pudding Lane ein Feuer aus. Der Große Brand von London wütete vier Tage und zerstörte große Teile der Stadt, darunter die alte St Paul’s Cathedral. Der Architekt Christopher Wren baute danach über 50 Kirchen und die neue St Paul’s Cathedral mit ihrer gewaltigen Kuppel (vollendet 1710).',
            'Im Parlament bildeten sich zwei Gruppen, aus denen die ersten Parteien wurden – beide Namen waren ursprünglich Spottnamen der Gegner: die Whigs, die die Macht des Parlaments stärken wollten, und die Tories, die eher den König unterstützten. 1679 schützte der „Habeas-Corpus-Akt“ Menschen vor willkürlicher Verhaftung: Jeder Gefangene musste rasch vor einen Richter gebracht werden.',
            'Karls Bruder Jakob II. (1685–1688) war katholisch und begünstigte Katholiken. Als ihm 1688 ein Sohn geboren wurde und eine katholische Dynastie drohte, riefen führende Politiker den protestantischen Wilhelm von Oranien, den Statthalter der Niederlande und Ehemann von Jakobs Tochter Maria, zu Hilfe. Wilhelm landete am 5. November 1688 in Torbay; Jakob floh nach Frankreich. Weil der Umsturz fast ohne Blutvergießen gelang, nennt man ihn „Glorreiche Revolution“.',
            'Wilhelm III. und Maria II. wurden 1689 gemeinsam gekrönt, mussten aber zuvor die „Bill of Rights“ annehmen: Der König durfte ohne Zustimmung des Parlaments keine Steuern erheben, keine Gesetze aufheben und kein stehendes Heer im Frieden halten; das Parlament sollte frei gewählt werden und Redefreiheit haben. Damit begann die parlamentarische Monarchie. 1690 besiegte Wilhelm Jakob in der Schlacht am Boyne in Irland – bis heute erinnern die protestantischen „Oranier“ in Nordirland daran. 1694 wurde die Bank of England gegründet.',
            'Unter Königin Anna (1702–1714) wurden England und Schottland mit dem „Act of Union“ von 1707 zum Königreich Großbritannien vereinigt, mit einem gemeinsamen Parlament in London. Anna starb 1714 ohne überlebende Kinder. Nach einem Gesetz von 1701 (Act of Settlement) durfte nur ein Protestant König werden; so kam der deutsche Kurfürst Georg von Hannover als Georg I. auf den Thron.',
          ],
          quiz: {
            leicht: [
              ['Wer wurde 1660 König?', 'Karl II.', ['Karl I.', 'Jakob II.', 'Oliver Cromwell']],
              ['Wie nannte man Karl II.?', '„Merry Monarch“ (fröhlicher König)', ['„Bloody King“', '„Virgin King“', '„Lionheart“']],
              ['Welche Akademie entstand 1660?', 'Die Royal Society', ['Die Académie française', 'Die Sorbonne', 'Oxford']],
              ['Welcher Forscher veröffentlichte das Gravitationsgesetz?', 'Isaac Newton', ['Galileo Galilei', 'Albert Einstein', 'Charles Darwin']],
              ['Welche Seuche wütete 1665 in London?', 'Die Pest', ['Die Cholera', 'Die Grippe', 'Die Pocken']],
              ['Wann brannte London?', '1666', ['1665', '1605', '1688']],
              ['Wo brach das Feuer aus?', 'In einer Bäckerei in der Pudding Lane', ['Im Tower', 'In St Paul’s', 'Im Parlament']],
              ['Wie lange wütete der Große Brand?', 'Vier Tage', ['Ein Tag', 'Ein Monat', 'Ein Jahr']],
              ['Welcher Architekt baute die neue St Paul’s Cathedral?', 'Christopher Wren', ['Inigo Jones', 'Norman Foster', 'Isaac Newton']],
              ['Wie hießen die ersten Parteien?', 'Whigs und Tories', ['Labour und Conservatives', 'Demokraten und Republikaner', 'Kavaliere und Rundköpfe']],
              ['Welcher Religion gehörte Jakob II. an?', 'Er war katholisch', ['Er war protestantisch', 'Er war Muslim', 'Er war Puritaner']],
              ['Wen riefen die Politiker 1688 zu Hilfe?', 'Wilhelm von Oranien', ['Ludwig XIV.', 'Karl XII.', 'Peter den Großen']],
              ['Woher kam Wilhelm von Oranien?', 'Aus den Niederlanden', ['Aus Frankreich', 'Aus Schottland', 'Aus Deutschland']],
              ['Wie nennt man den Umsturz von 1688?', 'Glorreiche Revolution', ['Englischer Bürgerkrieg', 'Französische Revolution', 'Restauration']],
              ['Warum heißt sie „glorreich“?', 'Sie gelang fast ohne Blutvergießen', ['Sie war sehr blutig', 'Sie dauerte hundert Jahre', 'Der Papst segnete sie']],
              ['Welches Dokument mussten Wilhelm und Maria annehmen?', 'Die Bill of Rights', ['Die Magna Carta', 'Die Petition of Right', 'Den Act of Union']],
              ['Welche Staatsform begann mit der Bill of Rights?', 'Die parlamentarische Monarchie', ['Die absolute Monarchie', 'Die Republik', 'Die Diktatur']],
              ['Welche Bank wurde 1694 gegründet?', 'Die Bank of England', ['Die Banque de France', 'Die Deutsche Bank', 'Die Weltbank']],
              ['Welche Länder wurden 1707 zu Großbritannien vereinigt?', 'England und Schottland', ['England und Irland', 'England und Wales', 'Schottland und Irland']],
              ['Wer wurde 1714 König von Großbritannien?', 'Georg I. von Hannover', ['Wilhelm III.', 'Jakob III.', 'Karl III.']],
            ],
            mittel: [
              ['Wer holte Karl II. zurück?', 'Das Parlament', ['Der Papst', 'Frankreich', 'Cromwell']],
              ['Wie nennt man die Rückkehr der Monarchie 1660?', 'Restauration', ['Reformation', 'Revolution', 'Renaissance']],
              ['Wann veröffentlichte Newton die „Principia“?', '1687', ['1660', '1666', '1705']],
              ['Wie viele Menschen tötete die Pest 1665 in London etwa?', 'Rund 100.000', ['Rund 1000', 'Rund 10.000', 'Rund 1 Million']],
              ['Wann brach der Große Brand aus?', '2. September 1666', ['5. November 1666', '30. Januar 1666', '14. Oktober 1666']],
              ['Welche Kathedrale zerstörte der Brand?', 'Die alte St Paul’s Cathedral', ['Westminster Abbey', 'Canterbury Cathedral', 'York Minster']],
              ['Wie viele Kirchen baute Wren etwa?', 'Über 50', ['Fünf', 'Über 500', 'Eine']],
              ['Wann wurde die neue St Paul’s Cathedral vollendet?', '1710', ['1666', '1688', '1750']],
              ['Was wollten die Whigs?', 'Die Macht des Parlaments stärken', ['Den König stärken', 'Die Kirche abschaffen', 'Den Papst zurück']],
              ['Wen unterstützten die Tories eher?', 'Den König', ['Das Parlament', 'Die Puritaner', 'Frankreich']],
              ['Was garantierte der Habeas-Corpus-Akt?', 'Schutz vor willkürlicher Verhaftung', ['Freie Wahlen', 'Religionsfreiheit', 'Pressefreiheit']],
              ['Wann wurde der Habeas-Corpus-Akt erlassen?', '1679', ['1689', '1660', '1701']],
              ['Wann regierte Jakob II.?', '1685–1688', ['1660–1685', '1689–1702', '1702–1714']],
              ['Was löste 1688 die Krise aus?', 'Die Geburt eines Sohnes von Jakob II.', ['Ein Krieg mit Frankreich', 'Eine Pest', 'Ein Brand']],
              ['Mit wem war Wilhelm von Oranien verheiratet?', 'Mit Maria, Jakobs Tochter', ['Mit Anna', 'Mit Elisabeth', 'Mit Katharina']],
              ['Wo landete Wilhelm 1688?', 'In Torbay', ['In Dover', 'In London', 'In Plymouth']],
              ['Wohin floh Jakob II.?', 'Nach Frankreich', ['Nach Spanien', 'Nach Irland dauerhaft', 'Nach Schottland']],
              ['Was durfte der König nach der Bill of Rights nicht?', 'Ohne Parlament Steuern erheben', ['Heiraten', 'Reisen', 'Beten']],
              ['Wo besiegte Wilhelm Jakob 1690?', 'In der Schlacht am Boyne', ['Bei Culloden', 'Bei Naseby', 'Bei Sedgemoor']],
              ['Wann wurde der Act of Union beschlossen?', '1707', ['1603', '1689', '1801']],
            ],
            schwer: [
              ['An welchem Tag landete Wilhelm in Torbay?', '5. November 1688', ['2. September 1688', '30. Januar 1689', '1. Juli 1690']],
              ['Was verbot die Bill of Rights im Frieden?', 'Ein stehendes Heer ohne Zustimmung des Parlaments', ['Theater', 'Kirchen', 'Handel']],
              ['Welche Freiheit garantierte die Bill of Rights dem Parlament?', 'Redefreiheit', ['Glaubensfreiheit für Katholiken', 'Steuerfreiheit', 'Reisefreiheit']],
              ['Wann wurden Wilhelm III. und Maria II. gekrönt?', '1689', ['1688', '1690', '1702']],
              ['Wer erinnert in Nordirland an die Schlacht am Boyne?', 'Die protestantischen Oranier', ['Die katholische IRA', 'Die Schotten', 'Die Engländer in London']],
              ['Wann regierte Königin Anna?', '1702–1714', ['1689–1702', '1714–1727', '1685–1688']],
              ['Was legte der Act of Settlement 1701 fest?', 'Nur ein Protestant darf König werden', ['Schottland wird unabhängig', 'Das Parlament wird abgeschafft', 'Frauen dürfen nicht regieren']],
              ['Wo tagte nach 1707 das gemeinsame Parlament?', 'In London', ['In Edinburgh', 'In York', 'Abwechselnd']],
              ['Welches Gesetz schützt bis heute vor willkürlicher Haft?', 'Habeas Corpus', ['Act of Settlement', 'Toleration Act', 'Act of Union']],
              ['Welcher Titel hatte Georg von Hannover vorher?', 'Kurfürst', ['König von Preußen', 'Kaiser', 'Herzog von Bayern']],
              ['Welche Rolle hatte Wilhelm in den Niederlanden?', 'Statthalter', ['König', 'Bürgermeister', 'Admiral']],
              ['Wo brach der Große Brand aus?', 'In der Pudding Lane', ['In der Baker Street', 'In der Downing Street', 'In der Fleet Street']],
              ['Welche Rolle spielte die Royal Society?', 'Eine der ältesten Wissenschaftsakademien', ['Eine Bank', 'Eine Kirche', 'Ein Theater']],
              ['Wie starb Königin Anna in Bezug auf Erben?', 'Ohne überlebende Kinder', ['Mit zwölf Kindern', 'Mit einem Sohn, der König wurde', 'Unverheiratet']],
              ['Was folgte auf Jakobs Flucht in Irland?', 'Kämpfe, die 1690 am Boyne entschieden wurden', ['Frieden', 'Die Unabhängigkeit Irlands', 'Nichts']],
              ['Welche Kuppelkirche prägt die Londoner Skyline seit 1710?', 'St Paul’s Cathedral', ['Westminster Abbey', 'Westminster Cathedral', 'Southwark Cathedral']],
              ['Was bedeutet „Whig“ und „Tory“ ursprünglich?', 'Spottnamen für die Gegner', ['Namen von Königen', 'Namen von Städten', 'Namen von Kirchen']],
              ['Welches Herrscherhaus begann 1714?', 'Das Haus Hannover', ['Das Haus Stuart', 'Das Haus Windsor', 'Das Haus Tudor']],
              ['Wie lange regierte Jakob II.?', 'Nur etwa drei Jahre', ['Dreißig Jahre', 'Einen Tag', 'Zehn Jahre']],
              ['Was ist das Ergebnis der Glorreichen Revolution langfristig?', 'Das Parlament wurde zum mächtigsten Organ', ['Der König wurde absolut', 'England wurde katholisch', 'England wurde Republik']],
            ],
          },
        },
      ],
    },
  ],
};
