import type { Epoch } from '../types';

export const E5: Epoch = {
  id: 'weltkriege',
  name: 'Zwei Weltkriege',
  period: '1914–1945',
  events: [
    {
      id: 'erster-weltkrieg-gb',
      title: 'Erster Weltkrieg, Irland und Frauenwahlrecht',
      date: '1903–1939',
      text: [
        'Der Erste Weltkrieg kostete Großbritannien fast eine Million Tote. Gleichzeitig kämpften Frauen um das Wahlrecht, und Irland erkämpfte sich die Unabhängigkeit. Die Zwischenkriegszeit brachte Generalstreik, Wirtschaftskrise und eine Abdankung.',
      ],
      subtopics: [
        {
          id: 'grosser-krieg',
          title: 'Der „Große Krieg“',
          date: '1914–1918',
          text: [
            'Als deutsche Truppen am 4. August 1914 in das neutrale Belgien einmarschierten, erklärte Großbritannien Deutschland den Krieg; es hatte Belgiens Neutralität 1839 garantiert. Hunderttausende meldeten sich freiwillig; Plakate mit Kriegsminister Lord Kitchener und dem Spruch „Your country needs you“ warben um Soldaten. Ganze „Pals Battalions“ aus Freunden, Kollegen und Nachbarn einer Stadt zogen gemeinsam los. Ab 1916 gab es erstmals die Wehrpflicht.',
            'Am Weihnachtsabend 1914 legten an manchen Frontabschnitten britische und deutsche Soldaten spontan die Waffen nieder, sangen Lieder, tauschten Geschenke und spielten der Überlieferung nach sogar Fußball (Weihnachtsfrieden). 1915 scheiterte auf der türkischen Halbinsel Gallipoli im Kampf gegen das Osmanische Reich eine Landung britischer, australischer und neuseeländischer Truppen mit schweren Verlusten; Australien und Neuseeland gedenken bis heute am „Anzac Day“ ihrer Gefallenen.',
            'Am 1. Juli 1916, dem ersten Tag der Schlacht an der Somme, fielen über 19.000 britische Soldaten, insgesamt gab es an diesem Tag fast 60.000 Tote und Verwundete – der verlustreichste Tag der britischen Militärgeschichte. Im September 1916 setzten die Briten dort die ersten Panzer ein. 1917 versanken bei Passchendaele in Flandern Soldaten und Pferde im Schlamm.',
            'Die Seeschlacht am Skagerrak (britisch: Battle of Jutland) 1916 brachte keine Entscheidung, aber die britische Flotte hielt die Seeblockade gegen Deutschland aufrecht. Deutsche Zeppeline und später Flugzeuge bombardierten erstmals englische Städte. Frauen arbeiteten in großer Zahl in Munitionsfabriken; wegen der giftigen Chemikalien färbte sich ihre Haut gelb, man nannte sie „Kanarienvögel“.',
            'Ab 1916 führte David Lloyd George als Premierminister das Land. Am 11. November 1918 endete der Krieg. Großbritannien hatte rund 880.000 Soldaten verloren, das ganze Empire fast eine Million. Seither tragen die Briten im November rote Mohnblumen (Poppies) zur Erinnerung – inspiriert vom Gedicht „In Flanders Fields“ des kanadischen Arztes John McCrae, in dem Mohn auf den Gräbern blüht. Am „Remembrance Day“, dem 11. November, wird um 11 Uhr zwei Minuten geschwiegen, und in London erinnert das Ehrenmal „Cenotaph“ (griechisch für „leeres Grab“) an die Gefallenen.',
          ],
          quiz: {
            leicht: [
              ['Wann erklärte Großbritannien Deutschland den Krieg?', '4. August 1914', ['1. August 1914', '1. September 1939', '11. November 1918']],
              ['Welches neutrale Land überfielen die Deutschen 1914?', 'Belgien', ['Holland', 'Dänemark', 'Schweiz']],
              ['Welcher Spruch stand auf Kitcheners Werbeplakaten?', '„Your country needs you“', ['„Keep calm and carry on“', '„God save the King“', '„Rule Britannia“']],
              ['Was geschah Weihnachten 1914 an manchen Frontabschnitten?', 'Ein spontaner Waffenstillstand', ['Eine große Schlacht', 'Ein Gasangriff', 'Nichts']],
              ['Was spielten Soldaten beim Weihnachtsfrieden der Überlieferung nach?', 'Fußball', ['Kricket', 'Rugby', 'Schach']],
              ['Wo scheiterte 1915 eine Landung?', 'In Gallipoli', ['In der Normandie', 'In Dünkirchen', 'In Belgien']],
              ['Welche Länder gedenken am Anzac Day?', 'Australien und Neuseeland', ['Kanada und Indien', 'Irland und Schottland', 'USA und Kanada']],
              ['Welche Schlacht begann am 1. Juli 1916?', 'Die Schlacht an der Somme', ['Die Schlacht bei Verdun', 'Die Schlacht von Waterloo', 'Die Schlacht von Hastings']],
              ['Welche neue Waffe setzten die Briten 1916 erstmals ein?', 'Panzer', ['Atombomben', 'Raketen', 'Drohnen']],
              ['Wo versanken Soldaten 1917 im Schlamm?', 'Bei Passchendaele', ['Bei Hastings', 'Bei London', 'Bei Gallipoli']],
              ['Was bombardierte englische Städte?', 'Zeppeline und Flugzeuge', ['Kanonen aus Frankreich', 'U-Boote', 'Raketen']],
              ['Wo arbeiteten viele Frauen im Krieg?', 'In Munitionsfabriken', ['In Schützengräben', 'Auf Kriegsschiffen', 'Gar nicht']],
              ['Wie nannte man Arbeiterinnen mit gelber Haut?', '„Kanarienvögel“', ['„Sonnenblumen“', '„Zitronen“', '„Butterblumen“']],
              ['Welcher Premierminister führte das Land ab 1916?', 'David Lloyd George', ['Winston Churchill', 'Neville Chamberlain', 'Arthur Balfour']],
              ['Wann endete der Erste Weltkrieg?', '11. November 1918', ['8. Mai 1918', '4. August 1918', '28. Juni 1919']],
              ['Welche Blume tragen die Briten zur Erinnerung?', 'Die rote Mohnblume (Poppy)', ['Die Rose', 'Die Lilie', 'Die Tulpe']],
              ['Wie heißt der Gedenktag im November?', 'Remembrance Day', ['Boxing Day', 'Bonfire Night', 'Armistice Party']],
              ['Wie lange wird am Remembrance Day geschwiegen?', 'Zwei Minuten', ['Zwei Stunden', 'Eine Sekunde', 'Einen Tag']],
              ['Welches Ehrenmal in London erinnert an die Gefallenen?', 'Der Cenotaph', ['Die Nelsonsäule', 'Big Ben', 'Der Tower']],
              ['Ab wann gab es in Großbritannien Wehrpflicht?', 'Ab 1916', ['Ab 1914', 'Ab 1939', 'Schon immer']],
            ],
            mittel: [
              ['Seit wann hatte Großbritannien Belgiens Neutralität garantiert?', 'Seit 1839', ['Seit 1914', 'Seit 1815', 'Seit 1066']],
              ['Wer war der Kriegsminister auf den Werbeplakaten?', 'Lord Kitchener', ['Lloyd George', 'Churchill', 'Haig']],
              ['Was waren „Pals Battalions“?', 'Einheiten aus Freunden, Kollegen und Nachbarn', ['Einheiten aus Frauen', 'Einheiten aus Indern', 'Marineeinheiten']],
              ['Wer landete in Gallipoli?', 'Britische, australische und neuseeländische Truppen', ['Nur Franzosen', 'Nur Amerikaner', 'Deutsche und Türken']],
              ['Wofür steht „Anzac“?', 'Australisch-neuseeländisches Armeekorps', ['Alliierte Nordarmee', 'Armee der Kolonien', 'Englische Marine']],
              ['Wann scheiterte die Gallipoli-Landung?', '1915', ['1914', '1916', '1918']],
              ['Auf welcher Halbinsel liegt Gallipoli?', 'Auf einer türkischen Halbinsel', ['Auf einer griechischen Insel', 'In Belgien', 'In Frankreich']],
              ['Wie viele britische Soldaten fielen am ersten Somme-Tag?', 'Über 19.000', ['Rund 190', 'Rund 1900', 'Über 190.000']],
              ['Wie viele Tote und Verwundete gab es am ersten Somme-Tag fast?', '60.000', ['6000', '600.000', '600']],
              ['Was ist der 1. Juli 1916 für Großbritannien?', 'Der verlustreichste Tag seiner Militärgeschichte', ['Ein Siegestag', 'Ein Feiertag', 'Der Kriegsbeginn']],
              ['Wann wurden die ersten Panzer eingesetzt?', 'September 1916', ['Juli 1916', 'August 1914', 'November 1918']],
              ['Wann war die Schlacht von Passchendaele?', '1917', ['1915', '1916', '1918']],
              ['In welcher Region liegt Passchendaele?', 'In Flandern (Belgien)', ['In Nordfrankreich', 'In der Türkei', 'In Deutschland']],
              ['Wie nennen die Briten die Skagerrakschlacht?', 'Battle of Jutland', ['Battle of Britain', 'Battle of the Atlantic', 'Battle of the Nile']],
              ['Was hielt die britische Flotte aufrecht?', 'Die Seeblockade gegen Deutschland', ['Die Herrschaft über Russland', 'Den Handel mit Deutschland', 'Nichts']],
              ['Warum färbte sich die Haut der Arbeiterinnen gelb?', 'Wegen giftiger Chemikalien', ['Wegen Sonne', 'Wegen Kälte', 'Wegen Farbe für Uniformen']],
              ['Wie viele Soldaten verlor Großbritannien etwa?', 'Rund 880.000', ['Rund 88.000', 'Rund 8,8 Millionen', 'Rund 8800']],
              ['Welches Gedicht inspirierte die Mohnblume als Symbol?', '„In Flanders Fields“', ['„If“', '„The Charge of the Light Brigade“', '„Rule Britannia“']],
              ['Um welche Uhrzeit schweigt man am Remembrance Day?', 'Um 11 Uhr', ['Um 12 Uhr', 'Um 18 Uhr', 'Um Mitternacht']],
              ['Wer warb 1914 mit seinem Bild um Soldaten?', 'Lord Kitchener', ['König Georg V.', 'Lloyd George', 'Churchill']],
            ],
            schwer: [
              ['Wie viele Tote verlor das ganze Empire fast?', 'Eine Million', ['Hunderttausend', 'Zehn Millionen', 'Zehntausend']],
              ['Was tauschten Soldaten beim Weihnachtsfrieden?', 'Geschenke', ['Waffen', 'Gefangene', 'Uniformen']],
              ['Welche Wirkung hatte die Skagerrakschlacht?', 'Keine Entscheidung', ['Vernichtung der britischen Flotte', 'Kriegsende', 'Eroberung Deutschlands']],
              ['Was blüht im Gedicht „In Flanders Fields“?', 'Mohn auf den Gräbern', ['Rosen am Fluss', 'Lilien im Garten', 'Tulpen in Holland']],
              ['Was ist ein Cenotaph?', 'Ein leeres Grabmal zum Gedenken', ['Ein Museum', 'Ein Friedhof mit Gräbern', 'Ein Siegestor']],
              ['Wann wurde Lloyd George Premierminister?', '1916', ['1914', '1918', '1922']],
              ['Welcher Teil des Empire beteiligte sich in Gallipoli?', 'Australien und Neuseeland', ['Jamaika', 'Kanada', 'Südafrika']],
              ['Gegen wen kämpften die Truppen in Gallipoli?', 'Gegen das Osmanische Reich', ['Gegen Deutschland direkt', 'Gegen Russland', 'Gegen Italien']],
              ['Welche Neuerung brachte 1916 im Militärdienst?', 'Die Wehrpflicht', ['Die Abschaffung der Armee', 'Frauen als Soldatinnen an der Front', 'Die Luftwaffe']],
              ['Welche Rolle spielte Belgien beim Kriegseintritt?', 'Sein Überfall war der Anlass', ['Es griff Großbritannien an', 'Es war Verbündeter Deutschlands', 'Keine']],
              ['Wann begann die Somme-Schlacht?', '1. Juli 1916', ['21. Februar 1916', '4. August 1914', '6. Juni 1916']],
              ['Was erschwerte die Kämpfe in Passchendaele?', 'Schlamm', ['Schnee', 'Wüste', 'Gebirge']],
              ['Woraus bestanden die Pals Battalions?', 'Aus Männern einer Stadt oder eines Betriebs', ['Aus Söldnern', 'Aus Kolonialtruppen', 'Aus Gefangenen']],
              ['Welche Luftangriffe erlebte England erstmals?', 'Angriffe durch Zeppeline', ['Raketenangriffe', 'Atomangriffe', 'Drohnenangriffe']],
              ['Wer schrieb „In Flanders Fields“?', 'Der Kanadier John McCrae', ['Rudyard Kipling', 'Wilfred Owen', 'Siegfried Sassoon']],
              ['Wann ist Remembrance Day?', 'Am 11. November', ['Am 1. Juli', 'Am 4. August', 'Am 25. Dezember']],
              ['Was veränderte der Krieg für Frauen?', 'Sie arbeiteten in großer Zahl in Industrie und Diensten', ['Nichts', 'Sie durften nicht mehr arbeiten', 'Sie wurden alle Soldaten']],
              ['Welche Schlacht fand 1916 auf See statt?', 'Die Skagerrakschlacht', ['Trafalgar', 'Die Schlacht im Atlantik', 'Midway']],
              ['Wie viele Freiwillige meldeten sich 1914?', 'Hunderttausende', ['Einige Dutzend', 'Keine', 'Zehn']],
              ['Welches Land erklärte wegen des Überfalls auf Belgien Deutschland den Krieg?', 'Großbritannien', ['Spanien', 'Schweden', 'Schweiz']],
            ],
          },
        },
        {
          id: 'irland-frauen',
          title: 'Suffragetten, Irland und Zwischenkriegszeit',
          date: '1903–1939',
          text: [
            '1903 gründete Emmeline Pankhurst in Manchester die „Women’s Social and Political Union“, deren Mitglieder man „Suffragetten“ nannte. Unter dem Motto „Taten statt Worte“ zerschlugen sie Schaufenster, ketteten sich an Gitter und traten im Gefängnis in Hungerstreik; man fütterte sie gewaltsam zwangsweise. 1913 lief Emily Davison beim Pferderennen in Epsom vor das Pferd des Königs und starb an ihren Verletzungen.',
            'Nach dem Krieg, in dem Frauen wichtige Arbeit geleistet hatten, erhielten 1918 Frauen ab 30 Jahren das Wahlrecht, gleichzeitig alle Männer ab 21. 1928 durften Frauen wie Männer ab 21 Jahren wählen. 1919 zog mit Nancy Astor die erste Frau ins Unterhaus ein.',
            'In Irland wuchs der Wunsch nach Selbstverwaltung („Home Rule“). Am Ostermontag 1916 besetzten irische Republikaner in Dublin das Hauptpostamt und riefen die Irische Republik aus (Osteraufstand). Der Aufstand wurde niedergeschlagen, und die Hinrichtung von 16 Anführern brachte viele Iren gegen Großbritannien auf. 1919–1921 führte die Irisch-Republikanische Armee (IRA) unter Michael Collins einen Unabhängigkeitskrieg.',
            'Im Anglo-Irischen Vertrag von 1921 wurde der Süden 1922 als „Irischer Freistaat“ weitgehend selbstständig; die sechs Grafschaften im Nordosten mit protestantischer Mehrheit blieben als Nordirland beim Vereinigten Königreich. Ein Teil der Republikaner lehnte den Vertrag ab, und es brach in Irland ein Bürgerkrieg aus, in dem Collins 1922 getötet wurde. 1949 wurde der Süden zur Republik Irland. Das Vereinigte Königreich heißt seit 1927 „Vereinigtes Königreich Großbritannien und Nordirland“.',
            'Zwischen den Kriegen kam die Labour-Partei 1924 unter Ramsay MacDonald erstmals an die Regierung, wenn auch nur für einige Monate. 1926 legten im Generalstreik neun Tage lang Millionen Arbeiter die Arbeit nieder, um Bergarbeiter zu unterstützen. Die Weltwirtschaftskrise brachte hohe Arbeitslosigkeit; 1936 marschierten Arbeitslose von Jarrow nach London („Jarrow Crusade“). 1931 wurden Kanada, Australien und die anderen Dominions im Statut von Westminster gleichberechtigt im „British Commonwealth“, einem Verbund von Staaten des früheren Empire.',
            '1936 wollte König Eduard VIII. die zweimal geschiedene Amerikanerin Wallis Simpson heiraten. Weil Regierung und Kirche das ablehnten, dankte er im Dezember 1936 ab, nach weniger als einem Jahr Regierung. Sein Bruder wurde als Georg VI. König – der Vater der späteren Königin Elisabeth II.; sein Kampf gegen das Stottern wurde im Film „The King’s Speech“ erzählt. Premierminister Neville Chamberlain versuchte, Hitler durch Zugeständnisse zu besänftigen (Appeasement). Nach dem Münchner Abkommen 1938 verkündete er: „Frieden für unsere Zeit.“',
          ],
          quiz: {
            leicht: [
              ['Wie nannte man die kämpferischen Frauenrechtlerinnen?', 'Suffragetten', ['Ladys', 'Pankhurstinnen', 'Chartistinnen']],
              ['Wer gründete 1903 die Frauenbewegung?', 'Emmeline Pankhurst', ['Florence Nightingale', 'Queen Victoria', 'Nancy Astor']],
              ['Wie lautete das Motto der Suffragetten?', '„Taten statt Worte“', ['„Gott schütze die Königin“', '„Frieden für unsere Zeit“', '„Keep calm“']],
              ['Was taten Suffragetten im Gefängnis?', 'Sie traten in Hungerstreik', ['Sie flohen', 'Sie schliefen', 'Sie schrieben Romane']],
              ['Wann erhielten Frauen ab 30 das Wahlrecht?', '1918', ['1928', '1900', '1945']],
              ['Ab wann durften Frauen wie Männer ab 21 wählen?', '1928', ['1918', '1945', '1969']],
              ['Wer war die erste Frau im Unterhaus?', 'Nancy Astor', ['Emmeline Pankhurst', 'Margaret Thatcher', 'Emily Davison']],
              ['Was geschah Ostern 1916 in Dublin?', 'Ein Aufstand für die Irische Republik', ['Ein Fußballspiel', 'Eine Krönung', 'Ein Erdbeben']],
              ['Welches Gebäude besetzten die Aufständischen in Dublin?', 'Das Hauptpostamt', ['Das Parlament', 'Die Kathedrale', 'Die Bank']],
              ['Wie hieß die irische Untergrundarmee?', 'IRA', ['RAF', 'SAS', 'BBC']],
              ['Welcher Teil Irlands blieb beim Vereinigten Königreich?', 'Nordirland', ['Dublin', 'Der Süden', 'Ganz Irland']],
              ['Wie hieß der Süden Irlands ab 1922?', 'Irischer Freistaat', ['Republik Ulster', 'Königreich Irland', 'Dominion Dublin']],
              ['Wann wurde der Süden Irlands Republik?', '1949', ['1922', '1916', '1998']],
              ['Welche Partei kam 1924 erstmals an die Regierung?', 'Labour', ['Die Liberalen', 'Die Grünen', 'Die Kommunisten']],
              ['Wie lange dauerte der Generalstreik von 1926?', 'Neun Tage', ['Neun Monate', 'Neun Jahre', 'Einen Tag']],
              ['Wen unterstützte der Generalstreik?', 'Die Bergarbeiter', ['Den König', 'Die Bankiers', 'Die Kirche']],
              ['Welcher König dankte 1936 ab?', 'Eduard VIII.', ['Georg V.', 'Georg VI.', 'Eduard VII.']],
              ['Wen wollte Eduard VIII. heiraten?', 'Wallis Simpson', ['Nancy Astor', 'Elisabeth Bowes-Lyon', 'Diana']],
              ['Welcher Film erzählt von Georg VI. und seinem Stottern?', '„The King’s Speech“', ['„The Crown“', '„Darkest Hour“', '„Dunkirk“']],
              ['Was verkündete Chamberlain 1938?', '„Frieden für unsere Zeit“', ['„Blut, Schweiß und Tränen“', '„Wir werden niemals kapitulieren“', '„Your country needs you“']],
            ],
            mittel: [
              ['In welcher Stadt gründete Pankhurst ihre Bewegung?', 'Manchester', ['London', 'Liverpool', 'Leeds']],
              ['Wie hieß Pankhursts Organisation?', 'Women’s Social and Political Union', ['Labour Party', 'Women’s Institute', 'Fabian Society']],
              ['Wie wurden hungerstreikende Suffragetten behandelt?', 'Sie wurden zwangsernährt', ['Sie wurden freigelassen', 'Sie wurden belohnt', 'Sie wurden ignoriert']],
              ['Welche Suffragette starb 1913 beim Pferderennen?', 'Emily Davison', ['Emmeline Pankhurst', 'Christabel Pankhurst', 'Nancy Astor']],
              ['Bei welchem Rennen starb Emily Davison?', 'In Epsom', ['In Ascot', 'In Aintree', 'In Wimbledon']],
              ['Vor wessen Pferd lief Davison?', 'Vor das Pferd des Königs', ['Vor das Pferd des Premierministers', 'Vor ein Rennauto', 'Vor eine Kutsche']],
              ['Ab welchem Alter durften Männer 1918 wählen?', 'Ab 21', ['Ab 18', 'Ab 30', 'Ab 25']],
              ['Wann zog Nancy Astor ins Unterhaus ein?', '1919', ['1918', '1928', '1945']],
              ['Wie nannte man die irische Forderung nach Selbstverwaltung?', 'Home Rule', ['Self Rule', 'Free Ireland', 'Ulster Rule']],
              ['Wie viele Anführer des Osteraufstands wurden hingerichtet?', '16', ['1', '160', '3']],
              ['Welche Folge hatten die Hinrichtungen?', 'Viele Iren wandten sich gegen Großbritannien', ['Die Iren wurden ruhiger', 'Irland wurde britischer', 'Nichts']],
              ['Wer führte die IRA im Unabhängigkeitskrieg?', 'Michael Collins', ['Wolfe Tone', 'Gerry Adams', 'Charles Parnell']],
              ['Wann fand der irische Unabhängigkeitskrieg statt?', '1919–1921', ['1916', '1922–1923', '1949']],
              ['Welcher Vertrag schuf 1921 den Irischen Freistaat?', 'Der Anglo-Irische Vertrag', ['Der Vertrag von Versailles', 'Das Karfreitagsabkommen', 'Der Act of Union']],
              ['Wie viele Grafschaften bildeten Nordirland?', 'Sechs', ['Vier', 'Neun', 'Zwölf']],
              ['Was geschah mit Michael Collins 1922?', 'Er wurde im Bürgerkrieg getötet', ['Er wurde Premierminister Großbritanniens', 'Er floh nach Amerika', 'Er wurde König']],
              ['Seit wann heißt der Staat „Vereinigtes Königreich Großbritannien und Nordirland“?', '1927', ['1801', '1922', '1949']],
              ['Woher marschierten Arbeitslose 1936 nach London?', 'Von Jarrow', ['Von Manchester', 'Von Glasgow', 'Von Cardiff']],
              ['Welches Statut machte die Dominions 1931 gleichberechtigt?', 'Das Statut von Westminster', ['Der Act of Union', 'Die Magna Carta', 'Das Statut von Dublin']],
              ['Wann dankte Eduard VIII. ab?', 'Dezember 1936', ['Januar 1936', 'Mai 1937', 'September 1939']],
            ],
            schwer: [
              ['Welche Taten verübten Suffragetten?', 'Sie zerschlugen Schaufenster und ketteten sich an Gitter', ['Sie raubten Banken', 'Sie entführten Minister', 'Sie gründeten eine Armee']],
              ['Woher stammte Wallis Simpson?', 'Aus den USA', ['Aus Frankreich', 'Aus Irland', 'Aus Kanada']],
              ['Warum war Wallis Simpson als Königin unerwünscht?', 'Sie war zweimal geschieden', ['Sie war Katholikin', 'Sie war zu jung', 'Sie war Schauspielerin']],
              ['Wie lange regierte Eduard VIII.?', 'Weniger als ein Jahr', ['Zehn Jahre', 'Einen Tag', 'Dreißig Jahre']],
              ['Wessen Vater war Georg VI.?', 'Elisabeths II.', ['Eduards VIII.', 'Victorias', 'Charles’ III.']],
              ['Wie nennt man Chamberlains Politik?', 'Appeasement', ['Containment', 'Blitzkrieg', 'Isolation']],
              ['Nach welchem Abkommen sprach Chamberlain von „Frieden für unsere Zeit“?', 'Nach dem Münchner Abkommen', ['Nach dem Versailler Vertrag', 'Nach Locarno', 'Nach dem Hitler-Stalin-Pakt']],
              ['Wie nennt man den Marsch der Arbeitslosen 1936?', 'Jarrow Crusade', ['Hunger March of Wales', 'Long March', 'Peterloo']],
              ['Wann wurde der Irische Freistaat gegründet?', '1922', ['1921', '1916', '1949']],
              ['Was brach in Irland über den Vertrag von 1921 aus?', 'Ein Bürgerkrieg', ['Ein Fest', 'Eine Hungersnot', 'Nichts']],
              ['Welche Konfession hatte die Mehrheit in Nordirland?', 'Protestanten', ['Katholiken', 'Muslime', 'Juden']],
              ['Wie viele Arbeiter legten 1926 die Arbeit nieder?', 'Millionen', ['Einige Hundert', 'Einige Tausend', 'Niemand']],
              ['Was ist das British Commonwealth?', 'Ein Verbund gleichberechtigter Staaten des früheren Empire', ['Eine Armee', 'Eine Kirche', 'Ein Fußballverband']],
              ['Wofür kämpfte Georg VI. persönlich?', 'Gegen sein Stottern', ['Gegen eine Krankheit des Herzens', 'Gegen seinen Bruder', 'Gegen den Premierminister']],
              ['Was riefen die Aufständischen 1916 aus?', 'Die Irische Republik', ['Ein Königreich Irland', 'Den Anschluss an die USA', 'Einen Freistaat Ulster']],
              ['In welcher Stadt fand der Osteraufstand statt?', 'Dublin', ['Belfast', 'Cork', 'London']],
              ['Wie lange regierte Labour 1924?', 'Nur kurz (unter Ramsay MacDonald)', ['Zehn Jahre', 'Gar nicht', 'Bis 1945']],
              ['Wer war Ramsay MacDonald?', 'Erster Labour-Premierminister', ['Ein Suffragettenführer', 'Ein irischer Rebell', 'Ein König']],
              ['Welche Gruppe erhielt 1918 erstmals ein allgemeines Wahlrecht?', 'Alle Männer ab 21', ['Alle Frauen ab 18', 'Kinder', 'Nur Adlige']],
              ['Welche Gruppe in Irland lehnte den Vertrag von 1921 ab?', 'Ein Teil der Republikaner', ['Alle Protestanten', 'Die britische Regierung', 'Niemand']],
            ],
          },
        },
      ],
    },
    {
      id: 'churchill-krieg',
      title: 'Churchill und der Zweite Weltkrieg',
      date: '1939–1945',
      text: [
        '1940 stand Großbritannien allein gegen Hitlers Deutschland. Unter Winston Churchill hielt es stand – in der Luftschlacht um England und unter den Bomben des „Blitz“ – und half, Europa zu befreien.',
      ],
      subtopics: [
        {
          id: 'their-finest-hour',
          title: 'Dünkirchen, Luftschlacht und Blitz',
          date: '1939–1941',
          text: [
            'Nach dem deutschen Überfall auf Polen erklärte Großbritannien Deutschland am 3. September 1939 den Krieg. Kinder aus den Städten wurden aufs Land evakuiert, Lebensmittel wurden rationiert. Als Hitler im Frühjahr 1940 Norwegen, die Niederlande, Belgien und Frankreich angriff, trat Chamberlain zurück. Am 10. Mai 1940 wurde Winston Churchill Premierminister. Er versprach den Briten nichts als „Blut, Mühsal, Tränen und Schweiß“.',
            'Vom 26. Mai bis 4. Juni 1940 wurden bei Dünkirchen über 338.000 britische und französische Soldaten aus der deutschen Umklammerung über den Ärmelkanal nach England gerettet – mit Kriegsschiffen und Hunderten kleiner ziviler Boote („Little Ships“). Churchill erklärte: „Wir werden an den Stränden kämpfen … wir werden niemals kapitulieren.“ Der Zusammenhalt in der Not wurde als „Dunkirk spirit“ sprichwörtlich.',
            'Nach dem Fall Frankreichs stand Großbritannien mit seinem Empire allein. Hitler plante eine Invasion („Unternehmen Seelöwe“), musste dafür aber die Luftherrschaft erringen. In der Luftschlacht um England (Battle of Britain) von Juli bis Oktober 1940 besiegten die Piloten der Royal Air Force mit ihren Spitfire- und Hurricane-Jägern die deutsche Luftwaffe mit ihren Messerschmitt-Jägern; geholfen hat ihnen das neue Radar, das frühzeitig vor anfliegenden Verbänden warnte. Hitler verschob daraufhin die Invasion. Churchill sagte über die Piloten: „Nie zuvor verdankten so viele so wenigen so viel.“ Seitdem heißen die Piloten „The Few“ (die Wenigen). Bis zum deutschen Angriff auf die Sowjetunion im Juni 1941 stand Großbritannien rund ein Jahr allein.',
            'Von September 1940 bis Mai 1941 bombardierte die Luftwaffe britische Städte im „Blitz“. Über 40.000 Zivilisten starben; in Coventry wurde im November 1940 die Kathedrale zerstört; neben ihrer Ruine entstand später die neue Coventry Cathedral. Die Londoner suchten Schutz in den U-Bahn-Stationen. König Georg VI. und Königin Elisabeth blieben trotz Bombentreffern am Buckingham Palace in London. Plakate riefen auf: „Keep Calm and Carry On“.',
            'Im geheimen Codeknacker-Zentrum Bletchley Park entschlüsselten Mathematiker wie Alan Turing die deutsche Verschlüsselungsmaschine „Enigma“, unter anderem mit einer von Turing entworfenen Maschine namens „Bombe“. Ihre Arbeit blieb noch Jahrzehnte nach dem Krieg geheim. Ihre Erkenntnisse halfen besonders in der „Schlacht im Atlantik“ gegen die deutschen U-Boote, die die lebenswichtigen Versorgungsschiffe aus Amerika versenkten. Im August 1941 verkündeten Churchill und US-Präsident Franklin D. Roosevelt die Atlantik-Charta mit gemeinsamen Zielen für die Nachkriegsordnung. Erst der japanische Angriff auf Pearl Harbor im Dezember 1941 brachte die USA in den Krieg.',
          ],
          quiz: {
            leicht: [
              ['Wann erklärte Großbritannien 1939 Deutschland den Krieg?', '3. September 1939', ['1. September 1939', '10. Mai 1940', '7. Dezember 1941']],
              ['Wer wurde am 10. Mai 1940 Premierminister?', 'Winston Churchill', ['Neville Chamberlain', 'Clement Attlee', 'Anthony Eden']],
              ['Was versprach Churchill den Briten?', '„Blut, Mühsal, Tränen und Schweiß“', ['„Frieden für unsere Zeit“', '„Brot und Spiele“', '„Wohlstand für alle“']],
              ['Wo wurden 1940 Hunderttausende Soldaten gerettet?', 'Bei Dünkirchen', ['Bei Calais', 'In der Normandie', 'In Norwegen']],
              ['Womit wurden die Soldaten auch gerettet?', 'Mit kleinen zivilen Booten', ['Mit Flugzeugen', 'Mit Zügen', 'Mit U-Booten']],
              ['Was erklärte Churchill nach Dünkirchen?', '„Wir werden niemals kapitulieren“', ['„Wir geben auf“', '„Frieden für unsere Zeit“', '„Gott schütze den König“']],
              ['Wie heißt die Luftschlacht von 1940?', 'Luftschlacht um England (Battle of Britain)', ['Blitzkrieg', 'Operation Overlord', 'Schlacht im Atlantik']],
              ['Welche britischen Jagdflugzeuge waren berühmt?', 'Spitfire und Hurricane', ['Messerschmitt und Stuka', 'Mustang und Zero', 'Concorde und Harrier']],
              ['Welche Erfindung half den britischen Piloten?', 'Das Radar', ['Das Telefon', 'Die Atombombe', 'Das Internet']],
              ['Was sagte Churchill über die Piloten?', '„Nie zuvor verdankten so viele so wenigen so viel“', ['„Sie sind Helden ohne Namen“', '„Fliegt zum Mond“', '„Wir sehen uns in Berlin“']],
              ['Wie nennt man die Bombardierung britischer Städte 1940/41?', 'Blitz', ['Storm', 'Thunder', 'Flash']],
              ['Wo suchten Londoner Schutz vor Bomben?', 'In U-Bahn-Stationen', ['In Kirchen', 'Auf Booten', 'Auf Dachböden']],
              ['Welche Stadt verlor 1940 ihre Kathedrale?', 'Coventry', ['York', 'Canterbury', 'Liverpool']],
              ['Welcher Spruch stand auf Plakaten?', '„Keep Calm and Carry On“', ['„Your country needs you“', '„Make love not war“', '„Yes we can“']],
              ['Blieb die Königsfamilie während des Blitz in London?', 'Ja', ['Nein, sie floh nach Kanada', 'Nein, nach Schottland', 'Nein, nach Australien']],
              ['Wo wurde der Enigma-Code geknackt?', 'In Bletchley Park', ['In Oxford', 'Im Tower', 'In Downing Street']],
              ['Welcher Mathematiker half, Enigma zu knacken?', 'Alan Turing', ['Isaac Newton', 'Stephen Hawking', 'Charles Babbage']],
              ['Was war Enigma?', 'Eine deutsche Verschlüsselungsmaschine', ['Ein Flugzeug', 'Ein Panzer', 'Ein Schiff']],
              ['Was versenkten deutsche U-Boote?', 'Versorgungsschiffe aus Amerika', ['Nur Kriegsschiffe', 'Nur Fischerboote', 'Nichts']],
              ['Mit welchem US-Präsidenten verkündete Churchill die Atlantik-Charta?', 'Franklin D. Roosevelt', ['Harry Truman', 'Dwight Eisenhower', 'John F. Kennedy']],
            ],
            mittel: [
              ['Wohin wurden Kinder aus den Städten evakuiert?', 'Aufs Land', ['In die Großstädte', 'Nach Deutschland', 'Nach Frankreich']],
              ['Was wurde im Krieg rationiert?', 'Lebensmittel', ['Bücher', 'Luft', 'Sonnenlicht']],
              ['Warum trat Chamberlain 1940 zurück?', 'Nach den deutschen Angriffen im Westen und in Norwegen', ['Wegen eines Skandals', 'Weil er Wahlen verlor', 'Weil er König wurde']],
              ['Von wann bis wann dauerte die Evakuierung von Dünkirchen?', '26. Mai bis 4. Juni 1940', ['10. bis 20. Mai 1940', '6. Juni 1944', 'Juli bis Oktober 1940']],
              ['Wie viele Soldaten wurden in Dünkirchen gerettet?', 'Über 338.000', ['Rund 33.800', 'Rund 3,38 Millionen', 'Rund 3380']],
              ['Wie hießen die kleinen zivilen Boote?', '„Little Ships“', ['„Spitfires“', '„Dreadnoughts“', '„Mayflowers“']],
              ['Wie hieß Hitlers geplante Invasion Englands?', 'Unternehmen Seelöwe', ['Unternehmen Barbarossa', 'Operation Overlord', 'Fall Gelb']],
              ['Was musste Hitler für die Invasion erringen?', 'Die Luftherrschaft', ['Die Herrschaft über Afrika', 'Die Herrschaft über Russland', 'Den Frieden mit den USA']],
              ['Wann fand die Luftschlacht um England statt?', 'Juli bis Oktober 1940', ['September 1939', 'Juni 1944', 'Mai 1945']],
              ['Wie heißt die britische Luftwaffe?', 'Royal Air Force', ['Royal Navy', 'Luftwaffe', 'Army Air Corps']],
              ['Von wann bis wann dauerte der Blitz?', 'September 1940 bis Mai 1941', ['1939 bis 1940', '1943 bis 1945', 'Juni bis August 1944']],
              ['Wie viele Zivilisten starben im Blitz etwa?', 'Über 40.000', ['Rund 400', 'Rund 4000', 'Über 400.000']],
              ['Wann wurde die Kathedrale von Coventry zerstört?', 'November 1940', ['September 1939', 'Juni 1944', 'Mai 1941']],
              ['Wo wurde der Buckingham Palace getroffen?', 'Bei Bombenangriffen auf London', ['Bei einem Brand 1666', 'Nie', 'Bei einem Aufstand']],
              ['In welcher Schlacht halfen die Enigma-Erkenntnisse besonders?', 'In der Schlacht im Atlantik', ['Bei Dünkirchen', 'Im Burenkrieg', 'Bei Stalingrad']],
              ['Wann wurde die Atlantik-Charta verkündet?', 'August 1941', ['Dezember 1941', 'Mai 1940', 'Juni 1944']],
              ['Was enthielt die Atlantik-Charta?', 'Gemeinsame Ziele für die Nachkriegsordnung', ['Einen Angriffsplan auf Japan', 'Ein Handelsverbot', 'Einen Friedensvertrag mit Deutschland']],
              ['Welche Länder griff Hitler im Frühjahr 1940 an?', 'Norwegen, die Niederlande, Belgien und Frankreich', ['Polen und Russland', 'Spanien und Portugal', 'Schweden und die Schweiz']],
              ['Welche Rolle hatte Bletchley Park?', 'Geheimes Codeknacker-Zentrum', ['Militärflughafen', 'Königsresidenz', 'Waffenfabrik']],
              ['Wer stand nach dem Fall Frankreichs allein gegen Hitler?', 'Großbritannien mit seinem Empire', ['Die USA', 'Die Sowjetunion', 'Italien']],
            ],
            schwer: [
              ['Wie viele Monate stand Großbritannien allein, bis die Sowjetunion angegriffen wurde?', 'Rund ein Jahr (Juni 1940 bis Juni 1941)', ['Einen Monat', 'Fünf Jahre', 'Gar nicht']],
              ['Wie nennt man Churchills Rede über die Piloten oft?', '„The Few“ (die Wenigen)', ['„The Many“', '„Iron Lady“', '„Iron Curtain“']],
              ['Welches deutsche Flugzeug kämpfte in der Luftschlacht?', 'Messerschmitt', ['Spitfire', 'Hurricane', 'Lancaster']],
              ['Welche Kathedrale wurde später neben der Ruine neu gebaut?', 'Coventry Cathedral', ['St Paul’s', 'Westminster Abbey', 'York Minster']],
              ['Was zeigt das Beispiel Coventry?', 'Die Zerstörung durch Bomben auf zivile Ziele', ['Einen Sieg der Luftwaffe ohne Folgen', 'Eine Seeschlacht', 'Eine Krönung']],
              ['Welcher Teil der Bevölkerung wurde 1939 zuerst evakuiert?', 'Kinder', ['Soldaten', 'Bauern', 'Politiker']],
              ['Wann wurde Alan Turings Arbeit bekannt?', 'Erst Jahrzehnte nach dem Krieg', ['Sofort 1940', 'Nie', '1945 im Radio']],
              ['Welche Folge hatte der Sieg in der Luftschlacht?', 'Hitler verschob die Invasion', ['Großbritannien kapitulierte', 'Frankreich wurde befreit', 'Der Krieg endete']],
              ['Welches Ziel hatten die U-Boote im Atlantik?', 'Großbritannien von Nachschub abzuschneiden', ['Amerika zu erobern', 'Fische zu fangen', 'Kanada zu besetzen']],
              ['Wofür steht der Blitz im Gedächtnis der Briten?', 'Für Durchhaltewillen unter Bomben', ['Für eine Niederlage', 'Für eine Revolution', 'Für Wohlstand']],
              ['Welche Stadt außer London wurde im Blitz schwer getroffen?', 'Coventry', ['Paris', 'Dublin', 'Rom']],
              ['Wer war König während des Zweiten Weltkriegs?', 'Georg VI.', ['Eduard VIII.', 'Georg V.', 'Elisabeth II.']],
              ['Was war „Unternehmen Seelöwe“?', 'Hitlers Plan zur Invasion Englands', ['Ein britischer Angriff', 'Eine Rettungsaktion', 'Ein U-Boot']],
              ['Welche Truppen wurden außer Briten in Dünkirchen gerettet?', 'Französische', ['Amerikanische', 'Russische', 'Deutsche']],
              ['Wie nennt man den Geist von Dünkirchen?', '„Dunkirk spirit“ – Zusammenhalt in der Not', ['„Splendid Isolation“', '„Stiff upper lip“ als Niederlage', '„Rule Britannia“']],
              ['Welches Ereignis brachte die USA 1941 in den Krieg?', 'Der Angriff auf Pearl Harbor', ['Die Atlantik-Charta', 'Der Blitz', 'Dünkirchen']],
              ['Wie viele Tage dauerte die Evakuierung von Dünkirchen etwa?', 'Rund zehn Tage', ['Einen Tag', 'Hundert Tage', 'Ein Jahr']],
              ['Welche Rolle spielte Radar in der Luftschlacht?', 'Es warnte frühzeitig vor Angriffen', ['Es schoss Flugzeuge ab', 'Es baute Flugzeuge', 'Keine']],
              ['Welche Maschine entschlüsselte Turing mit?', 'Die „Bombe“', ['Die „Enigma“ selbst', 'Einer Schreibmaschine', 'Den Telegrafen']],
              ['Was symbolisierte das Bleiben der Königsfamilie in London?', 'Solidarität mit der Bevölkerung', ['Angst', 'Gleichgültigkeit', 'Flucht']],
            ],
          },
        },
        {
          id: 'sieg-1945',
          title: 'Weltkrieg, D-Day und Sieg',
          date: '1941–1945',
          text: [
            'Nach dem deutschen Angriff auf die Sowjetunion im Juni 1941 und dem japanischen Angriff auf Pearl Harbor im Dezember 1941 hatte Großbritannien mächtige Verbündete. Doch im Pazifik erlitt es schwere Niederlagen: Im Februar 1942 kapitulierte die Festung Singapur vor den Japanern – Churchill nannte es die schlimmste Katastrophe der britischen Militärgeschichte. In Nordafrika siegte die britische 8. Armee unter General Bernard Montgomery im Herbst 1942 bei El Alamein über das deutsch-italienische Afrikakorps unter Rommel. Churchill sagte: „Das ist nicht das Ende … aber es ist vielleicht das Ende des Anfangs.“',
            'Britische Bomber griffen deutsche Städte an. Unter Luftmarschall Arthur Harris („Bomber Harris“) zerstörten Flächenbombardements Städte wie Hamburg 1943 und Dresden im Februar 1945; bis heute ist umstritten, wie sinnvoll und moralisch vertretbar diese Angriffe auf Zivilisten waren.',
            'Am 6. Juni 1944 („D-Day“) landeten alliierte Truppen in der Normandie – die größte Landungsoperation der Geschichte (Operation Overlord). Briten und Kanadier landeten an den Strandabschnitten „Gold“, „Juno“ und „Sword“, Amerikaner an „Utah“ und „Omaha“, wo sie die schwersten Verluste erlitten. Oberbefehlshaber war der Amerikaner Dwight D. Eisenhower, die Landstreitkräfte führte zunächst Montgomery. Künstliche Häfen („Mulberry“) wurden über den Kanal geschleppt.',
            'Ab Juni 1944 schlugen deutsche „Vergeltungswaffen“ in London ein: die Flugbombe V1 und die Rakete V2. Im April 1945 befreiten britische Truppen das Konzentrationslager Bergen-Belsen; die Bilder der Leichenberge erschütterten die Welt. Am 8. Mai 1945, dem „VE Day“ (Victory in Europe), feierten Menschenmassen in London, Churchill und die Königsfamilie zeigten sich auf dem Balkon des Buckingham Palace. Mit der Kapitulation Japans im August 1945 endete der Krieg.',
            'Rund 380.000 britische Soldaten und 67.000 Zivilisten waren gestorben. Obwohl Churchill als Kriegsheld galt, verlor er die Unterhauswahl im Juli 1945 deutlich gegen die Labour-Partei unter Clement Attlee, die einen Sozialstaat versprach. Churchill wurde 1951 noch einmal Premierminister, erhielt 1953 den Literaturnobelpreis und starb 1965; er erhielt ein Staatsbegräbnis.',
          ],
          quiz: {
            leicht: [
              ['Welche Festung im Pazifik kapitulierte 1942?', 'Singapur', ['Hongkong', 'Gibraltar', 'Malta']],
              ['Vor wem kapitulierte Singapur?', 'Vor den Japanern', ['Vor den Deutschen', 'Vor den Italienern', 'Vor den Russen']],
              ['Wo siegten die Briten 1942 in Nordafrika?', 'Bei El Alamein', ['Bei Dünkirchen', 'Bei Gallipoli', 'Bei Kairo']],
              ['Welcher britische General siegte bei El Alamein?', 'Bernard Montgomery', ['Arthur Harris', 'Alan Brooke', 'Douglas Haig']],
              ['Gegen welchen deutschen General kämpfte Montgomery?', 'Rommel', ['Guderian', 'Paulus', 'Manstein']],
              ['Was griffen britische Bomber an?', 'Deutsche Städte', ['Amerikanische Städte', 'Schweizer Städte', 'Nichts']],
              ['Welche deutschen Städte wurden zerstört?', 'Hamburg und Dresden', ['München und Wien', 'Zürich und Basel', 'Prag und Krakau']],
              ['Wann fand der D-Day statt?', '6. Juni 1944', ['8. Mai 1945', '1. September 1939', '10. Mai 1940']],
              ['Wo landeten die Alliierten am D-Day?', 'In der Normandie', ['In Dünkirchen', 'In Italien', 'In Norwegen']],
              ['Wie hieß die Landungsoperation?', 'Operation Overlord', ['Unternehmen Seelöwe', 'Operation Barbarossa', 'Operation Dynamo']],
              ['An welchen Strandabschnitten landeten die Briten?', 'Gold und Sword', ['Utah und Omaha', 'Juno und Omaha', 'Brighton und Dover']],
              ['Welche Waffen schlugen ab 1944 in London ein?', 'V1 und V2', ['Atombomben', 'Panzer', 'Gasgranaten']],
              ['Welches Lager befreiten britische Truppen 1945?', 'Bergen-Belsen', ['Auschwitz', 'Dachau', 'Buchenwald']],
              ['Was ist der „VE Day“?', 'Der Tag des Sieges in Europa', ['Der Tag des D-Day', 'Der Tag der Kriegserklärung', 'Der Tag der Befreiung von Paris']],
              ['Wann war VE Day?', '8. Mai 1945', ['6. Juni 1944', '15. August 1945', '11. November 1945']],
              ['Wo zeigten sich Churchill und die Königsfamilie am VE Day?', 'Auf dem Balkon des Buckingham Palace', ['Im Parlament', 'Am Tower', 'In Windsor']],
              ['Wer gewann die Wahl im Juli 1945?', 'Labour unter Clement Attlee', ['Churchills Konservative', 'Die Liberalen', 'Die Kommunisten']],
              ['Was versprach Labour 1945?', 'Einen Sozialstaat', ['Mehr Krieg', 'Die Monarchie abzuschaffen', 'Nichts']],
              ['Welchen Nobelpreis erhielt Churchill?', 'Den Literaturnobelpreis', ['Den Friedensnobelpreis', 'Den Physiknobelpreis', 'Keinen']],
              ['Wann starb Churchill?', '1965', ['1945', '1955', '1975']],
            ],
            mittel: [
              ['Wann kapitulierte Singapur?', 'Februar 1942', ['Dezember 1941', 'August 1945', 'Juni 1940']],
              ['Wie nannte Churchill den Fall Singapurs?', 'Schlimmste Katastrophe der britischen Militärgeschichte', ['Kleiner Rückschlag', 'Großer Sieg', 'Ehrenvolle Niederlage']],
              ['Welche Armee siegte bei El Alamein?', 'Die 8. Armee', ['Die 6. Armee', 'Die 1. Armee', 'Die Royal Navy']],
              ['Was sagte Churchill nach El Alamein?', '„… vielleicht das Ende des Anfangs“', ['„Der Krieg ist gewonnen“', '„Wir kapitulieren“', '„Frieden für unsere Zeit“']],
              ['Wie nannte man Luftmarschall Arthur Harris?', '„Bomber Harris“', ['„Iron Harris“', '„Monty“', '„The Few“']],
              ['Wann wurde Hamburg schwer bombardiert?', '1943', ['1940', '1945', '1941']],
              ['Wann wurde Dresden bombardiert?', 'Februar 1945', ['Juni 1944', 'Mai 1945', 'November 1940']],
              ['Was ist bis heute umstritten?', 'Die Flächenbombardements auf Zivilisten', ['Der D-Day', 'Die Luftschlacht um England', 'Dünkirchen']],
              ['Welcher Strandabschnitt war kanadisch?', 'Juno', ['Gold', 'Sword', 'Omaha']],
              ['An welchen Abschnitten landeten die Amerikaner?', 'Utah und Omaha', ['Gold und Sword', 'Juno und Gold', 'Dover und Calais']],
              ['Wer war Oberbefehlshaber am D-Day?', 'Dwight D. Eisenhower', ['Montgomery', 'Churchill', 'Patton']],
              ['Wie hießen die künstlichen Häfen?', 'Mulberry', ['Overlord', 'Seelöwe', 'Spitfire']],
              ['Was war die V1?', 'Eine Flugbombe', ['Ein Panzer', 'Ein U-Boot', 'Ein Gewehr']],
              ['Was war die V2?', 'Eine Rakete', ['Ein Flugzeug', 'Ein Schiff', 'Ein Bunker']],
              ['Wann befreiten Briten Bergen-Belsen?', 'April 1945', ['Januar 1945', 'Juni 1944', 'Mai 1945']],
              ['Wann endete der Krieg mit Japan?', 'August 1945', ['Mai 1945', 'Dezember 1945', 'Juni 1944']],
              ['Wie viele britische Soldaten starben etwa?', 'Rund 380.000', ['Rund 38.000', 'Rund 3,8 Millionen', 'Rund 880.000']],
              ['Wie viele britische Zivilisten starben etwa?', 'Rund 67.000', ['Rund 6700', 'Rund 670.000', 'Rund 670']],
              ['Wann wurde Churchill erneut Premierminister?', '1951', ['1945', '1955', '1964']],
              ['Wann erhielt Churchill den Literaturnobelpreis?', '1953', ['1945', '1965', '1940']],
            ],
            schwer: [
              ['Was bedeutet „VE Day“?', 'Victory in Europe Day', ['Victory Everywhere Day', 'Veterans’ Day', 'Volunteers’ Exit Day']],
              ['Welche Art Begräbnis erhielt Churchill?', 'Ein Staatsbegräbnis', ['Ein privates Begräbnis', 'Ein Seebegräbnis', 'Keines']],
              ['Wer führte die Landstreitkräfte am D-Day zunächst?', 'Montgomery', ['Eisenhower', 'Patton', 'Bradley']],
              ['Was war die größte Landungsoperation der Geschichte?', 'Operation Overlord', ['Gallipoli', 'Dünkirchen', 'Operation Torch']],
              ['Wogegen richteten sich V1 und V2?', 'Gegen London', ['Gegen Paris', 'Gegen Moskau', 'Gegen New York']],
              ['Was zeigten die Bilder aus Bergen-Belsen?', 'Leichenberge, die die Welt erschütterten', ['Feiernde Soldaten', 'Zerstörte Panzer', 'Einen Friedensvertrag']],
              ['Wann verlor Churchill die Wahl?', 'Juli 1945', ['Mai 1945', 'August 1945', 'Juni 1944']],
              ['Wie deutlich verlor Churchill 1945?', 'Deutlich', ['Mit einer Stimme', 'Er gewann', 'Unentschieden']],
              ['Wer war Labour-Premierminister ab 1945?', 'Clement Attlee', ['Harold Wilson', 'Ramsay MacDonald', 'Tony Blair']],
              ['Gegen welches Korps siegte Montgomery bei El Alamein?', 'Das deutsch-italienische Afrikakorps', ['Die japanische Armee', 'Die französische Armee', 'Die russische Armee']],
              ['Wann siegte Montgomery bei El Alamein?', 'Herbst 1942', ['Frühjahr 1941', 'Sommer 1944', 'Winter 1940']],
              ['Welche Strategie verfolgte Harris?', 'Flächenbombardements von Städten', ['Nur Angriffe auf Brücken', 'Keine Bomben', 'Nur Flugblätter']],
              ['Was waren die „Mulberry“-Häfen?', 'Künstliche Häfen, über den Kanal geschleppt', ['Feste Häfen in England', 'U-Boot-Stützpunkte', 'Flugplätze']],
              ['Welcher Abschnitt war besonders verlustreich für die Amerikaner?', 'Omaha', ['Utah', 'Gold', 'Sword']],
              ['Was markierte die Wende in Nordafrika?', 'El Alamein', ['Singapur', 'Dünkirchen', 'Pearl Harbor']],
              ['Welche Gefahr brachte der Pazifikkrieg für das Empire?', 'Schwere Niederlagen gegen Japan', ['Einen Sieg über China', 'Keine', 'Den Verlust Kanadas']],
              ['Was war Churchills Bild in der Bevölkerung 1945?', 'Kriegsheld', ['Verräter', 'Unbekannt', 'Feigling']],
              ['Warum wählten viele 1945 Labour?', 'Wegen des Versprechens eines Sozialstaats', ['Weil Churchill tot war', 'Weil der König es befahl', 'Wegen der Atombombe']],
              ['In welchem Monat 1944 begannen die V1-Angriffe?', 'Juni', ['Januar', 'Dezember', 'März']],
              ['Wann wurde Churchill mit dem Nobelpreis ausgezeichnet, und wofür?', '1953 für Literatur', ['1945 für Frieden', '1940 für Physik', '1965 für Medizin']],
            ],
          },
        },
      ],
    },
  ],
};
