import type { Epoch } from '../types';

export const E4: Epoch = {
  id: 'russland-heute',
  name: 'Russland seit 1991',
  period: 'seit 1991',
  events: [
    {
      id: 'russland-heute',
      title: 'Von Jelzin zu Putin',
      date: '1991–heute',
      text: [
        'Nach dem Ende der Sowjetunion erlebte Russland chaotische Jahre mit Armut und Oligarchen. Unter Wladimir Putin wurde es wieder autoritär, führte Kriege in Tschetschenien, Georgien und der Ukraine und geriet in scharfen Gegensatz zum Westen.',
      ],
      subtopics: [
        {
          id: 'jelzin-90er',
          title: 'Die wilden Neunziger unter Jelzin',
          date: '1991–1999',
          text: [
            'Boris Jelzin führte als Präsident Russlands ab 1992 mit einer „Schocktherapie“ die Marktwirtschaft ein: Preise wurden freigegeben, die Inflation stieg 1992 auf über 2500 Prozent, und die Ersparnisse vieler Menschen wurden wertlos. Rentner verkauften ihre Habseligkeiten auf der Straße, die Lebenserwartung sank.',
            'Bei der Privatisierung erhielten Bürger Anteilsscheine („Voucher“), doch große Staatsbetriebe wie Öl- und Gasfirmen gingen oft billig an wenige Geschäftsleute, die „Oligarchen“, die unermesslich reich und politisch mächtig wurden. Die organisierte Kriminalität blühte; man spricht von den „wilden Neunzigern“.',
            'Im Herbst 1993 eskalierte ein Machtkampf zwischen Jelzin und dem Parlament: Jelzin ließ das Parlamentsgebäude, das „Weiße Haus“ in Moskau, von Panzern beschießen. Danach setzte er eine neue Verfassung mit einem starken Präsidenten durch. 1994 begann der Krieg gegen die nach Unabhängigkeit strebende Teilrepublik Tschetschenien im Kaukasus; die Hauptstadt Grosny wurde zerstört, Zehntausende Zivilisten starben.',
            '1996 gewann Jelzin, obwohl schwer krank und unbeliebt, mit Hilfe der Oligarchen und ihrer Fernsehsender die Wiederwahl gegen den Kommunisten Gennadi Sjuganow. Im August 1998 war Russland zahlungsunfähig, der Rubel verlor zwei Drittel seines Wertes. Gleichzeitig entstanden erstmals freie Medien, Parteien und Reisefreiheit; Russland trat dem Europarat bei und arbeitete mit der NATO zusammen.',
            'Am 31. Dezember 1999 trat Jelzin überraschend im Fernsehen zurück und bat die Russen um Verzeihung. Sein Nachfolger wurde der bis dahin kaum bekannte Ministerpräsident Wladimir Putin, ein früherer Offizier des Geheimdienstes KGB, der in der DDR in Dresden gedient hatte. Er war im Herbst 1999 durch einen zweiten Tschetschenienkrieg nach Bombenanschlägen auf Moskauer Wohnhäuser populär geworden.',
          ],
          quiz: {
            leicht: [
              ['Wer war in den 1990ern Präsident Russlands?', 'Boris Jelzin', ['Wladimir Putin', 'Michail Gorbatschow', 'Dmitri Medwedew']],
              ['Wie hieß Jelzins Wirtschaftsreform?', 'Schocktherapie', ['Perestroika', 'New Deal', 'Fünfjahresplan']],
              ['Auf wie viel Prozent stieg die Inflation 1992?', 'Über 2500 Prozent', ['Rund 25 Prozent', 'Rund 2 Prozent', 'Über 25.000 Prozent']],
              ['Was wurde für viele Menschen wertlos?', 'Ihre Ersparnisse', ['Ihre Pässe', 'Ihre Häuser', 'Ihre Bücher']],
              ['Wie nannte man die reichen Geschäftsleute?', 'Oligarchen', ['Bojaren', 'Kulaken', 'Nomenklatura']],
              ['Welche Betriebe gingen oft billig an Oligarchen?', 'Öl- und Gasfirmen', ['Bäckereien', 'Schulen', 'Kirchen']],
              ['Wie nennt man die 1990er-Jahre in Russland?', 'Die wilden Neunziger', ['Die goldenen Neunziger', 'Die Stagnation', 'Das Tauwetter']],
              ['Was ließ Jelzin 1993 beschießen?', 'Das Parlamentsgebäude', ['Den Kreml', 'Die Börse', 'Eine Kirche']],
              ['Wie heißt das Moskauer Parlamentsgebäude?', 'Das Weiße Haus', ['Der Kreml', 'Die Duma-Burg', 'Das Rote Haus']],
              ['Welche Teilrepublik strebte nach Unabhängigkeit?', 'Tschetschenien', ['Tatarstan', 'Sibirien', 'Kaliningrad']],
              ['Wann begann der erste Tschetschenienkrieg?', '1994', ['1991', '1999', '2008']],
              ['Welche Stadt wurde im Tschetschenienkrieg zerstört?', 'Grosny', ['Tiflis', 'Baku', 'Kasan']],
              ['Gegen wen gewann Jelzin 1996 die Wahl?', 'Gegen den Kommunisten Sjuganow', ['Gegen Putin', 'Gegen Gorbatschow', 'Gegen Nawalny']],
              ['Wann war Russland zahlungsunfähig?', 'August 1998', ['Dezember 1991', 'Oktober 1993', 'Januar 2000']],
              ['Wie viel Wert verlor der Rubel 1998?', 'Zwei Drittel', ['Ein Zehntel', 'Nichts', 'Alles']],
              ['Wann trat Jelzin zurück?', '31. Dezember 1999', ['25. Dezember 1991', '1. Januar 2000', '7. Mai 2000']],
              ['Wer wurde Jelzins Nachfolger?', 'Wladimir Putin', ['Dmitri Medwedew', 'Gennadi Sjuganow', 'Boris Nemzow']],
              ['Für welchen Geheimdienst hatte Putin gearbeitet?', 'Den KGB', ['Die CIA', 'Die Stasi', 'Den MI6']],
              ['In welcher Stadt der DDR diente Putin?', 'In Dresden', ['In Berlin', 'In Leipzig', 'In Rostock']],
              ['Worum bat Jelzin bei seinem Rücktritt?', 'Um Verzeihung', ['Um Geld', 'Um Hilfe der NATO', 'Um einen Krieg']],
            ],
            mittel: [
              ['Was geschah mit den Preisen 1992?', 'Sie wurden freigegeben', ['Sie wurden eingefroren', 'Sie sanken', 'Sie wurden vom Staat festgelegt']],
              ['Was taten viele Rentner in den 1990ern?', 'Sie verkauften Habseligkeiten auf der Straße', ['Sie reisten viel', 'Sie gründeten Firmen', 'Sie wurden Oligarchen']],
              ['Was sank in den 1990ern?', 'Die Lebenserwartung', ['Die Inflation', 'Die Kriminalität', 'Die Zahl der Oligarchen']],
              ['Was erhielten Bürger bei der Privatisierung?', 'Anteilsscheine (Voucher)', ['Land', 'Gold', 'Autos']],
              ['Was blühte in den 1990ern?', 'Die organisierte Kriminalität', ['Die Landwirtschaft', 'Die Raumfahrt', 'Die Zarenfamilie']],
              ['Zwischen wem eskalierte 1993 der Machtkampf?', 'Zwischen Jelzin und dem Parlament', ['Zwischen Jelzin und Putin', 'Zwischen Russland und der Ukraine', 'Zwischen Oligarchen']],
              ['Was setzte Jelzin nach 1993 durch?', 'Eine Verfassung mit starkem Präsidenten', ['Eine Monarchie', 'Den Kommunismus', 'Ein Parlament ohne Präsident']],
              ['Wo liegt Tschetschenien?', 'Im Kaukasus', ['In Sibirien', 'Am Ural', 'An der Ostsee']],
              ['Wie viele Zivilisten starben im ersten Tschetschenienkrieg?', 'Zehntausende', ['Einige Dutzend', 'Keine', 'Millionen']],
              ['Wie war Jelzins Zustand 1996?', 'Schwer krank und unbeliebt', ['Gesund und beliebt', 'Jung und unbekannt', 'Im Ausland']],
              ['Wer half Jelzin 1996 zur Wiederwahl?', 'Die Oligarchen und ihre Fernsehsender', ['Die Kommunisten', 'Die Kirche', 'Die UNO']],
              ['Was entstand in den 1990ern erstmals?', 'Freie Medien, Parteien und Reisefreiheit', ['Eine Diktatur', 'Der Gulag', 'Die Zensur']],
              ['Welchem Gremium trat Russland bei?', 'Dem Europarat', ['Der EU', 'Der NATO', 'Der OPEC']],
              ['Mit wem arbeitete Russland in den 1990ern zusammen?', 'Mit der NATO', ['Mit dem Warschauer Pakt', 'Mit Nordkorea', 'Mit niemandem']],
              ['Welches Amt hatte Putin vor der Präsidentschaft?', 'Ministerpräsident', ['Bürgermeister von Moskau', 'Außenminister', 'General']],
              ['Wie wurde Putin 1999 populär?', 'Durch den zweiten Tschetschenienkrieg', ['Durch eine Fernsehshow', 'Durch Sport', 'Durch Kunst']],
              ['Was ging dem zweiten Tschetschenienkrieg voraus?', 'Bombenanschläge auf Moskauer Wohnhäuser', ['Ein Erdbeben', 'Eine Wahl', 'Ein Fußballspiel']],
              ['Wann begann der zweite Tschetschenienkrieg?', 'Herbst 1999', ['1994', '2004', '2008']],
              ['Wie war Putin vor 1999 bekannt?', 'Kaum bekannt', ['Sehr berühmt', 'Als Sänger', 'Als Oligarch']],
              ['Welche Wirtschaftsform führte Jelzin ein?', 'Die Marktwirtschaft', ['Die Planwirtschaft', 'Den Feudalismus', 'Die Tauschwirtschaft']],
            ],
            schwer: [
              ['Warum wurden die Oligarchen so reich?', 'Sie erwarben Staatsbetriebe billig bei der Privatisierung', ['Durch Lotto', 'Durch Erbe aus der Zarenzeit', 'Durch Kolonien']],
              ['Was zeigt der Beschuss des Weißen Hauses 1993?', 'Die Gewalt im Machtkampf der jungen Demokratie', ['Einen Angriff der USA', 'Einen Unfall', 'Nichts']],
              ['Welche Folge hatte die Schocktherapie sozial?', 'Massenarmut und sinkende Lebenserwartung', ['Allgemeiner Wohlstand', 'Vollbeschäftigung', 'Keine']],
              ['Welche Rolle spielten Fernsehsender 1996?', 'Sie verhalfen Jelzin zur Wiederwahl', ['Sie stürzten Jelzin', 'Sie waren verboten', 'Keine']],
              ['Was war der Rubelkrach 1998?', 'Zahlungsunfähigkeit und Währungsverfall', ['Ein Bankraub', 'Ein Wirtschaftsboom', 'Eine neue Währung']],
              ['Was ist das Positive an den 1990ern laut Text?', 'Freie Medien, Parteien und Reisefreiheit', ['Hohe Renten', 'Niedrige Kriminalität', 'Stabile Preise']],
              ['Woher stammt Putins Geheimdiensterfahrung?', 'Aus dem KGB, auch in Dresden', ['Aus der CIA', 'Aus der Armee in Afghanistan', 'Aus der Stasi direkt']],
              ['Was war ungewöhnlich an Jelzins Rücktritt?', 'Überraschend am Silvesterabend im Fernsehen', ['Er wurde abgewählt', 'Er wurde ermordet', 'Er floh']],
              ['Welche Verfassungsform entstand 1993?', 'Präsidialsystem mit starkem Präsidenten', ['Parlamentarische Monarchie', 'Rätesystem', 'Einparteienstaat']],
              ['Welcher Krieg zerstörte Grosny?', 'Der erste Tschetschenienkrieg', ['Der Zweite Weltkrieg', 'Der Afghanistankrieg', 'Der Georgienkrieg']],
              ['Welches Verhältnis hatte Russland in den 1990ern zum Westen?', 'Zusammenarbeit', ['Offener Krieg', 'Völlige Abschottung', 'Bündnis gegen die EU']],
              ['Wer war Gennadi Sjuganow?', 'Kommunistischer Präsidentschaftskandidat', ['Oligarch', 'Tschetschenenführer', 'Geheimdienstchef']],
              ['Warum wurde Putin in Tschetschenien als stark gesehen?', 'Er führte nach Anschlägen hart den Krieg', ['Er schloss Frieden', 'Er gab Tschetschenien frei', 'Er war Tschetschene']],
              ['Was sind Voucher?', 'Privatisierungsanteilsscheine', ['Lebensmittelmarken', 'Pässe', 'Wahlzettel']],
              ['Welches Jahr brachte die Zahlungsunfähigkeit?', '1998', ['1992', '1993', '1996']],
              ['Welche Gruppe gewann politisch Macht?', 'Die Oligarchen', ['Die Bauern', 'Die Kommunisten', 'Die Kirche']],
              ['Was beschreibt den Übergang von Jelzin zu Putin?', 'Ein geordneter Rücktritt mit Nachfolgeregelung', ['Ein Putsch', 'Eine Revolution', 'Eine Wahl gegen Jelzin']],
              ['Wann wurde das Weiße Haus beschossen?', 'Herbst 1993', ['August 1991', 'Dezember 1999', 'Frühjahr 1996']],
              ['Wie wirkte die Inflation auf Ersparnisse?', 'Sie wurden wertlos', ['Sie wuchsen', 'Sie blieben gleich', 'Sie wurden verdoppelt']],
              ['Welches Ereignis machte den „wilden“ Charakter der 1990er aus?', 'Kriminalität und Machtkämpfe', ['Ruhe und Ordnung', 'Planwirtschaft', 'Monarchie']],
            ],
          },
        },
        {
          id: 'putin',
          title: 'Putins Russland',
          date: '2000–heute',
          text: [
            'Wladimir Putin wurde im März 2000 zum Präsidenten gewählt. Dank hoher Öl- und Gaspreise wuchs die Wirtschaft, Löhne und Renten stiegen, und viele Russen schätzten die neue Stabilität. Putin stärkte die „Machtvertikale“: Er brachte die großen Fernsehsender unter Kontrolle, Gouverneure wurden zeitweise ernannt statt gewählt. Der Ölmagnat Michail Chodorkowski, der Oppositionsparteien unterstützte, wurde 2003 verhaftet und saß zehn Jahre in Haft.',
            'Der zweite Tschetschenienkrieg endete mit einem moskautreuen Regime unter Ramsan Kadyrow. Tschetschenische Terroristen verübten schwere Anschläge: 2002 nahmen sie im Moskauer Dubrowka-Theater 850 Geiseln, 2004 in einer Schule in Beslan über 1100; bei der Erstürmung starben über 330 Menschen, darunter 186 Kinder. Kritische Journalisten wie Anna Politkowskaja (2006) und der Oppositionspolitiker Boris Nemzow (2015, vor dem Kreml) wurden ermordet.',
            'Weil die Verfassung nur zwei Amtszeiten in Folge erlaubte, wurde 2008 Dmitri Medwedew Präsident und Putin Ministerpräsident; 2012 tauschten sie wieder. Im selben Jahr protestierten Zehntausende gegen Wahlfälschungen. 2008 führte Russland einen kurzen Krieg gegen Georgien. 2014 richtete es in Sotschi die Olympischen Winterspiele aus.',
            'Nach dem Sturz des russlandfreundlichen Präsidenten der Ukraine annektierte Russland im März 2014 die Krim und unterstützte Separatisten im Donbass. Am 24. Februar 2022 begann Russland einen umfassenden Angriffskrieg gegen die Ukraine. Der Westen verhängte harte Sanktionen, Hunderttausende Russen verließen das Land. Eine Verfassungsänderung von 2020 erlaubt Putin, theoretisch bis 2036 zu regieren.',
            'Kritik wird immer härter verfolgt: Den Oppositionsführer Alexei Nawalny, der Korruption aufdeckte, überlebte 2020 nur knapp einen Giftanschlag mit dem Nervenkampfstoff Nowitschok; nach seiner Rückkehr wurde er inhaftiert und starb im Februar 2024 in einem Straflager in der Arktis. Russland ist heute mit über 17 Millionen Quadratkilometern das größte Land der Erde, hat rund 146 Millionen Einwohner, die meisten Atomwaffen der Welt und einen ständigen Sitz im UN-Sicherheitsrat.',
          ],
          quiz: {
            leicht: [
              ['Wann wurde Putin zum Präsidenten gewählt?', 'März 2000', ['Dezember 1999', 'Mai 2008', 'März 2012']],
              ['Wodurch wuchs die Wirtschaft unter Putin?', 'Durch hohe Öl- und Gaspreise', ['Durch Autoexporte', 'Durch Tourismus', 'Durch Fischfang']],
              ['Was schätzten viele Russen?', 'Die neue Stabilität', ['Die Inflation', 'Die Oligarchen', 'Den Krieg']],
              ['Was brachte Putin unter Kontrolle?', 'Die großen Fernsehsender', ['Das Internet ganz', 'Die NATO', 'Die Zarenfamilie']],
              ['Welcher Ölmagnat wurde 2003 verhaftet?', 'Michail Chodorkowski', ['Roman Abramowitsch', 'Boris Beresowski', 'Alexei Nawalny']],
              ['Wer regiert Tschetschenien moskautreu?', 'Ramsan Kadyrow', ['Dschochar Dudajew', 'Boris Nemzow', 'Dmitri Medwedew']],
              ['Wo nahmen Terroristen 2002 Geiseln?', 'Im Moskauer Dubrowka-Theater', ['Im Bolschoi', 'In der Metro', 'Im Kreml']],
              ['Wo nahmen Terroristen 2004 Geiseln in einer Schule?', 'In Beslan', ['In Grosny', 'In Moskau', 'In Sotschi']],
              ['Welche kritische Journalistin wurde 2006 ermordet?', 'Anna Politkowskaja', ['Swetlana Alexijewitsch', 'Julia Nawalnaja', 'Maria Sacharowa']],
              ['Welcher Oppositionspolitiker wurde 2015 vor dem Kreml ermordet?', 'Boris Nemzow', ['Alexei Nawalny', 'Michail Chodorkowski', 'Garri Kasparow']],
              ['Wer war 2008–2012 Präsident?', 'Dmitri Medwedew', ['Wladimir Putin', 'Boris Jelzin', 'Sergei Lawrow']],
              ['Gegen welches Land führte Russland 2008 Krieg?', 'Georgien', ['Ukraine', 'Estland', 'Kasachstan']],
              ['Wo fanden 2014 Olympische Winterspiele statt?', 'In Sotschi', ['In Moskau', 'In Kasan', 'In Sankt Petersburg']],
              ['Welche Halbinsel annektierte Russland 2014?', 'Die Krim', ['Kamtschatka', 'Die Kola-Halbinsel', 'Jamal']],
              ['Wann begann der umfassende Angriff auf die Ukraine?', '24. Februar 2022', ['1. März 2014', '8. August 2008', '9. Mai 2022']],
              ['Was verhängte der Westen?', 'Harte Sanktionen', ['Ein Bündnis mit Russland', 'Nichts', 'Einen Handelsvertrag']],
              ['Welcher Oppositionsführer starb 2024 im Straflager?', 'Alexei Nawalny', ['Boris Nemzow', 'Michail Chodorkowski', 'Sergei Skripal']],
              ['Mit welchem Gift wurde Nawalny 2020 angegriffen?', 'Nowitschok', ['Polonium', 'Arsen', 'Sarin']],
              ['Was ist Russland flächenmäßig?', 'Das größte Land der Erde', ['Das zweitgrößte Land', 'Das kleinste Land Europas', 'Mittelgroß']],
              ['Wie viele Einwohner hat Russland etwa?', 'Rund 146 Millionen', ['Rund 46 Millionen', 'Rund 246 Millionen', 'Rund 1 Milliarde']],
            ],
            mittel: [
              ['Was stieg mit dem Wirtschaftswachstum?', 'Löhne und Renten', ['Die Arbeitslosigkeit', 'Die Inflation auf 2500 Prozent', 'Die Kriminalität']],
              ['Wie nennt man Putins Machtzentralisierung?', 'Machtvertikale', ['Perestroika', 'Glasnost', 'Schocktherapie']],
              ['Wie wurden Gouverneure zeitweise bestimmt?', 'Ernannt statt gewählt', ['Durch Los', 'Durch den Papst', 'Durch Volksabstimmung im Ausland']],
              ['Wen unterstützte Chodorkowski?', 'Oppositionsparteien', ['Putins Partei', 'Die Monarchisten', 'Niemanden']],
              ['Wie lange saß Chodorkowski in Haft?', 'Zehn Jahre', ['Ein Jahr', 'Lebenslang', 'Zwei Monate']],
              ['Wie viele Geiseln gab es im Dubrowka-Theater?', '850', ['85', '8500', '50']],
              ['Wie viele Menschen starben in Beslan?', 'Über 330, darunter 186 Kinder', ['Rund 30', 'Keiner', 'Über 3000']],
              ['Wie viele Geiseln gab es in Beslan?', 'Über 1100', ['Rund 110', 'Rund 11.000', 'Rund 50']],
              ['Warum wurde 2008 Medwedew Präsident?', 'Die Verfassung erlaubte nur zwei Amtszeiten in Folge', ['Putin war krank', 'Putin verlor die Wahl', 'Medwedew putschte']],
              ['Welches Amt hatte Putin 2008–2012?', 'Ministerpräsident', ['Außenminister', 'Bürgermeister', 'Keines']],
              ['Wogegen protestierten 2012 Zehntausende?', 'Gegen Wahlfälschungen', ['Gegen Olympia', 'Gegen die NATO', 'Gegen hohe Mieten']],
              ['Wie lange dauerte der Krieg gegen Georgien?', 'Kurz (wenige Tage)', ['Zehn Jahre', 'Zwei Jahre', 'Er dauert noch an']],
              ['Was geschah vor der Annexion der Krim in der Ukraine?', 'Der russlandfreundliche Präsident wurde gestürzt', ['Ein Erdbeben', 'Ein EU-Beitritt', 'Ein Wahlsieg Putins']],
              ['Wen unterstützte Russland im Donbass?', 'Separatisten', ['Die ukrainische Regierung', 'Die NATO', 'Niemanden']],
              ['Was taten Hunderttausende Russen nach 2022?', 'Sie verließen das Land', ['Sie zogen auf die Krim', 'Sie wurden Oligarchen', 'Nichts']],
              ['Bis wann erlaubt die Verfassungsänderung Putin theoretisch zu regieren?', '2036', ['2024', '2030', 'Lebenslang ohne Grenze']],
              ['Wann wurde die Verfassung geändert?', '2020', ['2012', '2000', '2024']],
              ['Was deckte Nawalny auf?', 'Korruption', ['Spionage für die USA', 'Ölfunde', 'Nichts']],
              ['Wo starb Nawalny?', 'In einem Straflager in der Arktis', ['In Berlin', 'In Moskau im Krankenhaus', 'In Sibirien am Baikal']],
              ['Wie groß ist Russland?', 'Über 17 Millionen Quadratkilometer', ['Über 7 Millionen', 'Über 27 Millionen', 'Über 1 Million']],
            ],
            schwer: [
              ['Was zeigt der Fall Chodorkowski?', 'Wer politisch opponierte, riskierte Verfolgung', ['Die Freiheit der Wirtschaft', 'Einen fairen Prozess', 'Nichts']],
              ['Warum tauschten Putin und Medwedew die Ämter?', 'Um die Amtszeitbegrenzung zu umgehen', ['Aus Freundschaft', 'Weil Putin krank war', 'Wegen eines Wahlsieges der Opposition']],
              ['Was beweist der Mord an Nemzow?', 'Die Gefahr für Oppositionelle', ['Die Sicherheit der Opposition', 'Einen Unfall', 'Nichts']],
              ['Welche Folge hatte 2022 für das Verhältnis zum Westen?', 'Tiefer Bruch mit harten Sanktionen', ['Engere Zusammenarbeit', 'NATO-Beitritt Russlands', 'Keine']],
              ['Welche Stellung hat Russland in der UNO?', 'Ständiger Sitz im Sicherheitsrat', ['Kein Mitglied', 'Beobachterstatus', 'Ausgeschlossen']],
              ['Welche Militärmacht hat Russland bei Atomwaffen?', 'Die meisten Atomwaffen der Welt', ['Keine Atomwaffen', 'Nur wenige', 'Nach Frankreich die meisten']],
              ['Was zeigt die Ernennung von Gouverneuren?', 'Zentralisierung der Macht', ['Mehr Demokratie', 'Föderalismus', 'Nichts']],
              ['Was folgte auf Nawalnys Rückkehr nach Russland?', 'Er wurde inhaftiert', ['Er wurde Präsident', 'Er wurde gefeiert', 'Er ging nach Sotschi']],
              ['Was bezeichnet „Machtvertikale“?', 'Zentral gesteuerte Befehlskette von oben nach unten', ['Ein Hochhaus', 'Eine Partei', 'Ein Wahlsystem']],
              ['Welche Tragödie forderte 186 Kinder als Opfer?', 'Beslan 2004', ['Dubrowka 2002', 'Grosny 1994', 'Sotschi 2014']],
              ['Wann wurde die Krim annektiert?', 'März 2014', ['Februar 2022', 'August 2008', 'Dezember 1991']],
              ['Was bedeutet die Verfassungsänderung 2020?', 'Putin kann theoretisch bis 2036 regieren', ['Putin musste sofort gehen', 'Russland wurde Monarchie', 'Die Duma wurde abgeschafft']],
              ['Wann wurde Politkowskaja ermordet?', '2006', ['2004', '2015', '2020']],
              ['Was stärkte Putins Popularität in den 2000ern?', 'Wirtschaftswachstum und Stabilität', ['Inflation', 'Kriegsniederlagen', 'Oligarchenherrschaft']],
              ['Welche Region kontrolliert Kadyrow?', 'Tschetschenien', ['Die Krim', 'Dagestan', 'Georgien']],
              ['Welches Gift nutzte man gegen Nawalny?', 'Den Nervenkampfstoff Nowitschok', ['Polonium-210', 'Rizin', 'Zyankali']],
              ['Wie reagierten Russen 2012 auf Wahlfälschungen?', 'Mit Massenprotesten', ['Mit Gleichgültigkeit', 'Mit einem Putsch', 'Mit Feiern']],
              ['Welches Großereignis fand 2014 statt?', 'Olympische Winterspiele in Sotschi', ['Fußball-WM in Moskau', 'Weltausstellung', 'G20 in Kasan']],
              ['Wann starb Nawalny?', 'Februar 2024', ['August 2020', 'Februar 2022', 'Januar 2021']],
              ['Wer überlebte 2020 knapp einen Giftanschlag?', 'Alexei Nawalny', ['Boris Nemzow', 'Anna Politkowskaja', 'Michail Chodorkowski']],
            ],
          },
        },
      ],
    },
  ],
};
