import type { HistEvent } from '../types';

export const OTTONEN: HistEvent = {
  id: 'ottonen',
  title: 'Die Ottonen',
  date: '919–1024',
  text: [
    'Mit Heinrich I. kam ein Sachse auf den Thron. Seine Familie, nach ihrem bedeutendsten Mitglied Ottonen genannt, wehrte die Ungarn ab, erneuerte das Kaisertum Karls des Großen und machte das Ostfrankenreich zur stärksten Macht Europas.',
  ],
  subtopics: [
    {
      id: 'heinrich-otto',
      title: 'Heinrich I. und Otto der Große',
      date: '919–955',
      text: [
        '919 wählten Franken und Sachsen in Fritzlar den Sachsenherzog Heinrich zum König. Die Salbung, die ihm Erzbischof Heriger von Mainz anbot, lehnte er ab – er wollte nicht als König der Kirche erscheinen, sondern als Erster unter den Herzögen. Eine spätere Sage nennt ihn „Heinrich den Vogler“: Die Nachricht von seiner Wahl habe ihn erreicht, als er gerade Vögel fing. Seine Familie heißt nach ihrem Ahnherrn Liudolf auch Liudolfinger, meist aber Ottonen.',
        'Heinrich gewann die Herzöge durch Verhandlungen statt durch Krieg: 919 unterwarf sich Burchard von Schwaben, 921 Arnulf von Bayern. Im Bonner Vertrag von 921 erkannte ihn der westfränkische König Karl der Einfältige als gleichrangigen König an, und 925 band Heinrich Lothringen wieder an sein Reich. 929 legte er in einer Hausordnung fest, dass das Reich nicht mehr geteilt werden und sein Sohn Otto allein erben sollte. Seine Frau Mathilde gründete nach seinem Tod das Damenstift Quedlinburg.',
        'Gegen die Ungarn half zunächst nur eine List: 926 geriet ein ungarischer Fürst in Heinrichs Gefangenschaft, und Heinrich tauschte ihn gegen einen Waffenstillstand von neun Jahren ein, für den er zusätzlich Tribut zahlte. Die Zeit nutzte er, um Burgen zu bauen und ein schlagkräftiges Reiterheer auszubilden. Im Winter 928/929 eroberte er die slawische Burg Brandenburg (Brennabor) und gründete die Burg Meißen an der Elbe. 933 verweigerte er den Tribut und besiegte die Ungarn bei Riade, wohl an der Unstrut. Heinrich starb am 2. Juli 936 in Memleben und wurde in Quedlinburg begraben.',
        'Am 7. August 936 wurde sein Sohn Otto in Aachen gekrönt. Er setzte sich auf den Thron Karls des Großen und ließ sich von Erzbischof Hildebert von Mainz salben. Beim Krönungsmahl bedienten ihn die Herzöge als Kämmerer, Truchsess, Mundschenk und Marschall – ein Zeichen, dass sie ihm unterstanden. Otto wollte strenger regieren als sein Vater, und so musste er viele Aufstände niederschlagen: Sein Halbbruder Thankmar fiel 938 auf der Eresburg, sein Bruder Heinrich rebellierte mehrfach und wurde später Herzog von Bayern, und 939 kamen die Herzöge Eberhard von Franken und Giselbert von Lothringen bei Andernach ums Leben. Ein anderer Bruder, Brun, wurde Erzbischof von Köln und Herzog von Lothringen.',
        'Ottos erste Frau war die englische Prinzessin Edgith. Nach ihrem Tod heiratete er 951 Adelheid von Burgund, die Witwe König Lothars von Italien, und wurde in Pavia König von Italien. Sein Sohn Liudolf fühlte sich zurückgesetzt und erhob sich 953 gegen ihn. In Magdeburg gründete Otto schon 937 das Moritzkloster; die Stadt wurde sein Lieblingsort, und dort liegt er neben Edgith im Dom begraben.',
        '955 fielen die Ungarn mit einem riesigen Heer in Bayern ein und belagerten Augsburg, das Bischof Ulrich verteidigte. Am 10. August 955 besiegte Otto sie auf dem Lechfeld bei Augsburg; er soll dabei die Heilige Lanze getragen haben. Sein Schwiegersohn Konrad der Rote fiel. Die Ungarnführer Bulcsú und Lehel wurden in Regensburg hingerichtet. Das Heer rief Otto nach Widukind von Corvey, der eine „Sachsengeschichte“ schrieb, zum „Vater des Vaterlandes und Imperator“ aus. Die Raubzüge der Ungarn hörten danach auf; sie wurden sesshaft und bald christlich. Noch im selben Jahr, am 16. Oktober 955, besiegte Otto an der Recknitz die Slawen. Seither heißt er „Otto der Große“.',
        'Im Südosten entstand zum Schutz gegen die Ungarn eine Mark, deren Name 996 zum ersten Mal als „Ostarrichi“ belegt ist – daraus wurde Österreich.',
      ],
      quiz: {
        leicht: [
          ['Wer wurde 919 König im Ostfrankenreich?', 'Heinrich I.', ['Otto I.', 'Konrad I.', 'Karl der Große']],
          ['Aus welchem Stamm kam Heinrich I.?', 'Aus dem Stamm der Sachsen', ['Aus dem Stamm der Franken', 'Aus dem Stamm der Bayern', 'Aus dem Stamm der Schwaben']],
          ['Wie heißt die Herrscherfamilie Heinrichs I.?', 'Ottonen', ['Karolinger', 'Salier', 'Staufer']],
          ['Welchen Beinamen gibt eine Sage Heinrich I.?', 'Der Vogler', ['Der Löwe', 'Der Fromme', 'Der Heilige']],
          ['Was tat Heinrich laut Sage, als man ihm seine Wahl meldete?', 'Er fing gerade Vögel', ['Er betete in der Kirche', 'Er kämpfte gegen Ungarn', 'Er schlief']],
          ['Welches Reitervolk bedrohte das Reich unter Heinrich und Otto?', 'Die Ungarn', ['Die Mongolen', 'Die Hunnen', 'Die Wikinger']],
          ['Was ließ Heinrich zum Schutz vor den Ungarn bauen?', 'Burgen', ['Eine große Mauer', 'Kanäle', 'Leuchttürme']],
          ['Wer folgte Heinrich I. 936 als König?', 'Sein Sohn Otto', ['Sein Bruder Konrad', 'Der Papst', 'Ein Bayernherzog']],
          ['In welcher Stadt wurde Otto 936 gekrönt?', 'Aachen', ['Rom', 'Magdeburg', 'Frankfurt']],
          ['Auf wessen Thron setzte sich Otto in Aachen?', 'Auf den Thron Karls des Großen', ['Auf den Thron des Papstes', 'Auf den Thron Chlodwigs', 'Auf den Thron Caesars']],
          ['Wo besiegte Otto 955 die Ungarn?', 'Auf dem Lechfeld', ['Im Teutoburger Wald', 'Bei Tours und Poitiers', 'Bei Tannenberg']],
          ['Bei welcher Stadt liegt das Lechfeld?', 'Augsburg', ['München', 'Regensburg', 'Nürnberg']],
          ['Welchen Beinamen erhielt Otto I.?', 'Der Große', ['Der Rote', 'Der Kahle', 'Der Löwe']],
          ['Was endete nach der Schlacht auf dem Lechfeld?', 'Die Raubzüge der Ungarn', ['Die Wikingerzeit', 'Das Frankenreich', 'Das Papsttum']],
          ['Welcher Bischof verteidigte 955 Augsburg?', 'Ulrich', ['Bonifatius', 'Bernward', 'Brun']],
          ['Welche Königin aus Burgund heiratete Otto 951?', 'Adelheid', ['Theophanu', 'Mathilde', 'Kunigunde']],
          ['Welches Königreich gewann Otto durch diese Heirat?', 'Italien', ['England', 'Ungarn', 'Polen']],
          ['Wo ist Heinrich I. begraben?', 'In Quedlinburg', ['In Aachen', 'In Magdeburg', 'In Speyer']],
          ['In welcher Stadt ist Otto der Große begraben?', 'Magdeburg', ['Aachen', 'Rom', 'Quedlinburg']],
          ['Wer bediente den König beim Krönungsmahl 936?', 'Die Herzöge', ['Mönche', 'Bauern', 'Kaufleute']],
        ],
        mittel: [
          ['Wo wurde Heinrich I. 919 zum König gewählt?', 'In Fritzlar', ['In Aachen', 'In Forchheim', 'In Quedlinburg']],
          ['Was lehnte Heinrich I. bei seiner Erhebung ab?', 'Die Salbung durch den Erzbischof', ['Die Krone', 'Den Königstitel', 'Die Wahl durch die Sachsen']],
          ['Wie lange dauerte der Waffenstillstand mit den Ungarn ab 926?', 'Neun Jahre', ['Ein Jahr', 'Zwanzig Jahre', 'Hundert Jahre']],
          ['Wodurch erreichte Heinrich 926 den Waffenstillstand?', 'Er hatte einen Ungarnfürsten gefangen genommen', ['Er heiratete eine Ungarin', 'Er besiegte sie auf dem Lechfeld', 'Der Papst vermittelte']],
          ['Wo besiegte Heinrich I. die Ungarn 933?', 'Bei Riade', ['Auf dem Lechfeld', 'Bei Pressburg', 'Bei Merseburg']],
          ['Welche slawische Burg eroberte Heinrich im Winter 928/929?', 'Brandenburg', ['Meißen', 'Berlin', 'Stettin']],
          ['Welche Burg gründete Heinrich 929 an der Elbe?', 'Meißen', ['Dresden', 'Magdeburg', 'Wittenberg']],
          ['Was legte Heinrichs Hausordnung von 929 fest?', 'Das Reich bleibt ungeteilt, Otto erbt allein', ['Alle Söhne erben gleich', 'Der Papst wählt den Nachfolger', 'Sachsen wird selbstständig']],
          ['Wann band Heinrich I. Lothringen wieder an sein Reich?', '925', ['911', '936', '955']],
          ['Wie hieß die Frau Heinrichs I.?', 'Mathilde', ['Adelheid', 'Edgith', 'Theophanu']],
          ['Welche Ämter übernahmen die Herzöge beim Krönungsmahl?', 'Kämmerer, Truchsess, Mundschenk und Marschall', ['Kanzler, Richter, Bischof und Abt', 'Graf, Vogt, Schultheiß und Bürgermeister', 'Koch, Bäcker, Schmied und Jäger']],
          ['Welcher Halbbruder Ottos kam 938 bei einem Aufstand ums Leben?', 'Thankmar', ['Heinrich', 'Brun', 'Liudolf']],
          ['Welche Herzöge starben 939 bei Andernach?', 'Eberhard von Franken und Giselbert von Lothringen', ['Arnulf von Bayern und Burchard von Schwaben', 'Konrad der Rote und Liudolf', 'Hermann Billung und Gero']],
          ['Welcher Sohn Ottos erhob sich 953 gegen ihn?', 'Liudolf', ['Otto II.', 'Brun', 'Heinrich']],
          ['An welchem Tag war die Schlacht auf dem Lechfeld?', '10. August 955', ['7. August 936', '2. Februar 962', '16. Oktober 955']],
          ['Welcher Herzog fiel auf dem Lechfeld?', 'Konrad der Rote', ['Liudolf', 'Heinrich von Bayern', 'Hermann Billung']],
          ['Wen besiegte Otto 955 auch an der Recknitz?', 'Slawen', ['Ungarn', 'Dänen', 'Franzosen']],
          ['Wer war Ottos erste Frau?', 'Die englische Prinzessin Edgith', ['Adelheid von Burgund', 'Theophanu aus Byzanz', 'Mathilde von Sachsen']],
          ['Wo starb Heinrich I.?', 'In Memleben', ['In Quedlinburg', 'In Fritzlar', 'In Magdeburg']],
          ['Wer schrieb die „Sachsengeschichte“?', 'Widukind von Corvey', ['Thietmar von Merseburg', 'Einhard', 'Roswitha von Gandersheim']],
        ],
        schwer: [
          ['Welcher Erzbischof bot Heinrich I. die Salbung an?', 'Heriger von Mainz', ['Hildebert von Mainz', 'Brun von Köln', 'Hatto von Mainz']],
          ['In welchem Vertrag wurde Heinrich I. 921 als gleichrangiger König anerkannt?', 'Im Bonner Vertrag', ['Im Vertrag von Verdun', 'Im Vertrag von Meerssen', 'Im Vertrag von Ribemont']],
          ['Welche Herzöge unterwarfen sich Heinrich 919 und 921?', 'Burchard von Schwaben und Arnulf von Bayern', ['Eberhard und Giselbert', 'Konrad und Liudolf', 'Hermann und Gero']],
          ['An welchem Fluss lag Riade wohl?', 'An der Unstrut', ['Am Lech', 'An der Elbe', 'An der Donau']],
          ['An welchem Tag starb Heinrich I.?', '2. Juli 936', ['7. August 936', '23. Dezember 918', '10. August 955']],
          ['An welchem Tag wurde Otto in Aachen gekrönt?', '7. August 936', ['2. Juli 936', '2. Februar 962', '25. Dezember 936']],
          ['Wer salbte Otto 936?', 'Erzbischof Hildebert von Mainz', ['Erzbischof Heriger von Mainz', 'Papst Johannes XII.', 'Bischof Ulrich von Augsburg']],
          ['Wo fiel Thankmar 938?', 'Auf der Eresburg', ['Bei Andernach', 'Auf dem Lechfeld', 'In Magdeburg']],
          ['Wessen Witwe war Adelheid von Burgund?', 'König Lothars von Italien', ['Kaiser Ottos II.', 'König Konrads I.', 'Herzog Arnulfs von Bayern']],
          ['In welcher Stadt wurde Otto 951 König von Italien?', 'Pavia', ['Rom', 'Mailand', 'Ravenna']],
          ['Welcher Bruder Ottos rebellierte mehrfach und wurde später Herzog von Bayern?', 'Heinrich', ['Brun', 'Thankmar', 'Liudolf']],
          ['Welcher Bruder Ottos wurde Erzbischof von Köln und Herzog von Lothringen?', 'Brun', ['Heinrich', 'Wilhelm', 'Thankmar']],
          ['Welches Heiligtum soll Otto auf dem Lechfeld getragen haben?', 'Die Heilige Lanze', ['Die Reichskrone', 'Das Turiner Grabtuch', 'Den Mantel des heiligen Martin']],
          ['An welchem Tag war die Schlacht an der Recknitz?', '16. Oktober 955', ['10. August 955', '2. Februar 962', '7. Mai 973']],
          ['Wessen Schwiegersohn war Konrad der Rote?', 'Ottos des Großen', ['Heinrichs I.', 'Arnulfs von Bayern', 'Lothars von Italien']],
          ['Was geschah mit den Ungarnführern Bulcsú und Lehel?', 'Sie wurden in Regensburg hingerichtet', ['Sie wurden getauft und Herzöge', 'Sie flohen nach Byzanz', 'Sie fielen auf dem Lechfeld']],
          ['Wozu rief das Heer Otto nach dem Lechfeld laut Widukind aus?', 'Zum Vater des Vaterlandes und Imperator', ['Zum König der Ungarn', 'Zum Papst', 'Zum Herzog von Bayern']],
          ['Welcher Name für Österreich ist 996 erstmals belegt?', 'Ostarrichi', ['Austrasien', 'Noricum', 'Pannonia']],
          ['Was gründete Heinrichs Witwe Mathilde?', 'Das Damenstift Quedlinburg', ['Das Kloster Fulda', 'Das Erzbistum Magdeburg', 'Den Dom zu Speyer']],
          ['Welches Kloster gründete Otto 937 in Magdeburg?', 'Das Moritzkloster', ['Das Kloster Unser Lieben Frauen', 'Das Kloster Corvey', 'Das Kloster Memleben']],
        ],
      },
    },
    {
      id: 'kaisertum',
      title: 'Kaiserkrone und Reichskirche',
      date: '962–1024',
      text: [
        'Am 2. Februar 962 krönte Papst Johannes XII. Otto den Großen in Rom zum Kaiser. Im „Ottonianum“ bestätigte Otto dem Papst den Besitz des Kirchenstaats, behielt sich aber ein Mitspracherecht bei der Papstwahl vor. Mit dieser Krönung beginnt man oft die Geschichte des Heiligen Römischen Reiches, das bis 1806 bestand. Der Name entstand allerdings erst nach und nach: „Heiliges Reich“ (sacrum imperium) taucht 1157 unter Friedrich Barbarossa auf, „Heiliges Römisches Reich“ 1254, der Zusatz „Deutscher Nation“ im 15. Jahrhundert. Zum Zeichen des Reiches wurde die Reichskrone, eine achteckige Krone aus acht Platten, die wohl in der zweiten Hälfte des 10. Jahrhunderts entstand und heute in der Schatzkammer der Wiener Hofburg liegt.',
        'Otto stützte seine Herrschaft vor allem auf die Kirche: Bischöfe und Äbte erhielten Land, Zölle, Münzrecht und Gerichtsrechte und mussten dafür dem König dienen und Truppen stellen. Weil sie keine Kinder hatten, die ihre Ämter erben konnten, setzte der König nach ihrem Tod einfach neue, treue Männer ein. Dieses Reichskirchensystem machte Bischöfe zu mächtigen Reichsfürsten. 968 gründete Otto das Erzbistum Magdeburg, erster Erzbischof wurde Adalbert; es sollte die Mission unter den Slawen leiten. Otto starb am 7. Mai 973 in Memleben.',
        'Sein Sohn Otto II. hatte 972 die byzantinische Prinzessin Theophanu geheiratet, eine Nichte des Kaisers Johannes Tzimiskes. 982 erlitt er am Kap Colonna in Kalabrien eine schwere Niederlage gegen die Sarazenen. 983 erhoben sich die Slawen östlich der Elbe, vor allem die Liutizen, im großen Slawenaufstand; die Bistümer Brandenburg und Havelberg gingen für lange Zeit verloren. Otto II. starb noch 983 in Rom und ist als einziger deutscher Kaiser im Petersdom begraben.',
        'Otto III. war beim Tod seines Vaters erst drei Jahre alt. Für ihn regierten seine Mutter Theophanu, die 991 starb, und dann seine Großmutter Adelheid. Sein Lehrer war der berühmte Gelehrte Gerbert von Aurillac, den Otto 999 als Silvester II. zum Papst machte. Otto III. träumte unter dem Motto „Renovatio imperii Romanorum“ von einer Erneuerung des Römischen Reiches und wollte am liebsten in Rom residieren.',
        'Im Jahr 1000 pilgerte Otto III. zum Grab des heiligen Adalbert von Prag in Gnesen. Dort traf er den polnischen Herzog Bolesław Chrobry und errichtete das Erzbistum Gnesen mit den Bistümern Krakau, Breslau und Kolberg – Polen erhielt so eine eigene Kirchenorganisation. Auf dem Rückweg ließ er in Aachen das Grab Karls des Großen öffnen. Otto III. starb 1002 mit nur 21 Jahren in Paterno bei Rom und wurde in Aachen begraben.',
        'Letzter Ottone war Heinrich II. (1002–1024). 1007 gründete er das Bistum Bamberg, wo er mit seiner Frau Kunigunde im Dom begraben liegt. Beide wurden heiliggesprochen, Heinrich 1146 und Kunigunde 1200. Mit Heinrichs Tod 1024 endete die Herrschaft der Ottonen.',
        'Die Ottonenzeit brachte großartige Kunst hervor: Im Kloster Reichenau entstanden prachtvolle Bücher wie das Evangeliar Ottos III., in Köln das Gero-Kreuz, die älteste erhaltene große Christusfigur des Abendlandes, und in Hildesheim ließ Bischof Bernward um 1015 die Bernwardstür gießen, eine Bronzetür mit Szenen aus dem Alten und Neuen Testament. Die Stiftsdame Roswitha von Gandersheim schrieb als erste deutsche Dichterin lateinische Dramen, und Bischof Thietmar von Merseburg verfasste eine wichtige Chronik.',
      ],
      quiz: {
        leicht: [
          ['Wann wurde Otto der Große zum Kaiser gekrönt?', '962', ['800', '936', '1024']],
          ['In welcher Stadt wurde Otto zum Kaiser gekrönt?', 'Rom', ['Aachen', 'Magdeburg', 'Konstantinopel']],
          ['Wer krönte Otto 962 zum Kaiser?', 'Der Papst', ['Der Erzbischof von Mainz', 'Der Kaiser von Byzanz', 'Die Fürsten']],
          ['Welches Reich lässt man oft mit Ottos Kaiserkrönung beginnen?', 'Das Heilige Römische Reich', ['Das Frankenreich', 'Das Deutsche Kaiserreich', 'Das Byzantinische Reich']],
          ['Bis wann bestand das Heilige Römische Reich?', '1806', ['1648', '1871', '1918']],
          ['Welches Erzbistum gründete Otto 968?', 'Magdeburg', ['Mainz', 'Köln', 'Hamburg']],
          ['Auf wen stützte sich Otto vor allem?', 'Auf Bischöfe und Äbte', ['Auf Kaufleute', 'Auf die Bauern', 'Auf Söldner aus Byzanz']],
          ['Warum vertraute Otto Bischöfen mehr als Herzögen?', 'Sie konnten ihre Ämter nicht vererben', ['Sie hatten größere Heere', 'Sie sprachen Griechisch', 'Sie waren alle seine Brüder']],
          ['Welche Prinzessin aus Byzanz heiratete Otto II.?', 'Theophanu', ['Adelheid', 'Kunigunde', 'Irene']],
          ['Wie alt war Otto III., als sein Vater starb?', 'Drei Jahre', ['Zehn Jahre', 'Zwanzig Jahre', 'Ein Monat']],
          ['Wer regierte für den jungen Otto III.?', 'Seine Mutter und seine Großmutter', ['Der Papst', 'Ein Bayernherzog', 'Der Kaiser von Byzanz']],
          ['In welcher Stadt wollte Otto III. am liebsten residieren?', 'Rom', ['Aachen', 'Magdeburg', 'Paris']],
          ['Wer war der letzte Kaiser aus der Familie der Ottonen?', 'Heinrich II.', ['Otto III.', 'Konrad II.', 'Otto II.']],
          ['Welches Bistum gründete Heinrich II.?', 'Bamberg', ['Würzburg', 'Passau', 'Magdeburg']],
          ['Wo liegen Heinrich II. und Kunigunde begraben?', 'Im Bamberger Dom', ['Im Aachener Dom', 'Im Speyerer Dom', 'Im Petersdom']],
          ['Was ist besonders an Heinrich II. und Kunigunde?', 'Beide wurden heiliggesprochen', ['Beide wurden Päpste', 'Beide starben auf einem Kreuzzug', 'Beide waren Geschwister']],
          ['Welche berühmte Bronzetür entstand in Hildesheim?', 'Die Bernwardstür', ['Die Paradiestür', 'Die Goldene Pforte', 'Die Porta Nigra']],
          ['Wo hängt das Gero-Kreuz?', 'In Köln', ['In Aachen', 'In Bamberg', 'In Hildesheim']],
          ['Welche Krone wurde zum Zeichen des Reiches?', 'Die Reichskrone', ['Die Eiserne Krone', 'Die Stephanskrone', 'Die Wenzelskrone']],
          ['Wo befindet sich die Reichskrone heute?', 'In Wien', ['In Aachen', 'In Berlin', 'In Rom']],
        ],
        mittel: [
          ['Welcher Papst krönte Otto den Großen?', 'Johannes XII.', ['Leo III.', 'Gregor VII.', 'Silvester II.']],
          ['An welchem Tag wurde Otto zum Kaiser gekrönt?', '2. Februar 962', ['25. Dezember 962', '7. August 936', '10. August 955']],
          ['Was bestätigte Otto dem Papst im „Ottonianum“?', 'Den Besitz des Kirchenstaats', ['Die Herrschaft über Deutschland', 'Das Recht, Könige zu wählen', 'Die Unabhängigkeit von Byzanz']],
          ['Wie nennt man Ottos Herrschaft mit Hilfe der Bischöfe?', 'Reichskirchensystem', ['Lehnswesen', 'Investiturstreit', 'Feudalismus']],
          ['Wo erlitt Otto II. 982 eine schwere Niederlage?', 'Am Kap Colonna in Kalabrien', ['Auf dem Lechfeld', 'Bei Andernach', 'Vor Konstantinopel']],
          ['Was geschah 983 östlich der Elbe?', 'Ein großer Slawenaufstand', ['Ein Wikingerüberfall', 'Eine Pestwelle', 'Die Gründung Polens']],
          ['Wo ist Otto II. begraben?', 'Im Petersdom in Rom', ['In Magdeburg', 'In Aachen', 'In Quedlinburg']],
          ['Wann starb Theophanu?', '991', ['983', '1002', '973']],
          ['Welches Motto hatte Otto III.?', 'Renovatio imperii Romanorum', ['Ora et labora', 'Gott mit uns', 'Translatio imperii']],
          ['Was errichtete Otto III. im Jahr 1000 in Gnesen?', 'Ein Erzbistum', ['Eine Universität', 'Eine Kaiserpfalz', 'Ein Ritterorden']],
          ['Welchen polnischen Herzog traf Otto III. in Gnesen?', 'Bolesław Chrobry', ['Mieszko I.', 'Kasimir der Große', 'Władysław Jagiełło']],
          ['Wessen Grab ließ Otto III. im Jahr 1000 öffnen?', 'Das Karls des Großen', ['Das Ottos des Großen', 'Das des heiligen Petrus', 'Das Chlodwigs']],
          ['Wie alt wurde Otto III.?', '21 Jahre', ['16 Jahre', '35 Jahre', '50 Jahre']],
          ['Wann gründete Heinrich II. das Bistum Bamberg?', '1007', ['968', '1024', '1046']],
          ['Wann endete die Herrschaft der Ottonen?', '1024', ['1002', '1056', '1125']],
          ['Welche Stiftsdame schrieb als erste deutsche Dichterin Dramen?', 'Roswitha von Gandersheim', ['Hildegard von Bingen', 'Mathilde von Quedlinburg', 'Theophanu']],
          ['Welcher Bischof von Merseburg schrieb eine wichtige Chronik?', 'Thietmar', ['Widukind', 'Bernward', 'Adalbert']],
          ['Wer ließ die Bernwardstür gießen?', 'Bischof Bernward von Hildesheim', ['Kaiser Otto III.', 'Papst Silvester II.', 'Bischof Ulrich von Augsburg']],
          ['Wann taucht die Bezeichnung „Heiliges Reich“ erstmals auf?', '1157', ['962', '800', '1356']],
          ['Welcher Zusatz kam im 15. Jahrhundert zum Reichsnamen hinzu?', '„Deutscher Nation“', ['„der Franken“', '„von Gottes Gnaden“', '„und Italiens“']],
        ],
        schwer: [
          ['Wer wurde der erste Erzbischof von Magdeburg?', 'Adalbert', ['Brun', 'Thietmar', 'Bernward']],
          ['Wann heiratete Otto II. Theophanu?', '972', ['962', '983', '955']],
          ['Wessen Nichte war Theophanu?', 'Des Kaisers Johannes Tzimiskes', ['Der Kaiserin Irene', 'Des Kalifen von Bagdad', 'Des Papstes Johannes XII.']],
          ['Welche Bistümer gingen 983 für lange Zeit verloren?', 'Brandenburg und Havelberg', ['Magdeburg und Merseburg', 'Meißen und Zeitz', 'Hamburg und Bremen']],
          ['Welches slawische Volk führte den Aufstand von 983 vor allem an?', 'Die Liutizen', ['Die Sorben', 'Die Abodriten', 'Die Pomoranen']],
          ['Wann starb Otto der Große?', 'Am 7. Mai 973', ['Am 2. Februar 962', 'Am 2. Juli 936', 'Am 10. August 955']],
          ['Wo starb Otto III.?', 'In Paterno bei Rom', ['In Aachen', 'In Gnesen', 'In Ravenna']],
          ['Wo ist Otto III. begraben?', 'In Aachen', ['In Rom', 'In Magdeburg', 'In Bamberg']],
          ['Zu wessen Grab pilgerte Otto III. im Jahr 1000?', 'Zum Grab Adalberts von Prag', ['Zum Grab des Bonifatius', 'Zum Grab des heiligen Petrus', 'Zum Grab Ottos des Großen']],
          ['Welche Bistümer gehörten zum neuen Erzbistum Gnesen?', 'Krakau, Breslau und Kolberg', ['Prag, Olmütz und Brünn', 'Posen, Danzig und Thorn', 'Meißen, Merseburg und Zeitz']],
          ['Wann wurde Heinrich II. heiliggesprochen?', '1146', ['1024', '1200', '1007']],
          ['Wann wurde Kunigunde heiliggesprochen?', '1200', ['1146', '1033', '1250']],
          ['Um welches Jahr entstand die Bernwardstür?', 'Um 1015', ['Um 950', 'Um 1150', 'Um 1250']],
          ['Was zeigt die Bernwardstür?', 'Szenen aus dem Alten und Neuen Testament', ['Die Schlacht auf dem Lechfeld', 'Die Taten Karls des Großen', 'Das Leben des heiligen Bernward']],
          ['In welchem Kloster entstand das Evangeliar Ottos III.?', 'Auf der Reichenau', ['In Fulda', 'In Corvey', 'In Lorsch']],
          ['Wann entstand die Reichskrone wahrscheinlich?', 'In der zweiten Hälfte des 10. Jahrhunderts', ['Um 800 unter Karl dem Großen', 'Um 1200 unter den Staufern', 'Um 1500 unter Maximilian']],
          ['Welche Form hat die Reichskrone?', 'Achteckig aus acht Platten', ['Rund wie ein Reif', 'Viereckig mit vier Bügeln', 'Kegelförmig wie eine Mitra']],
          ['Welcher Gelehrte war Lehrer Ottos III. und wurde 999 Papst?', 'Gerbert von Aurillac', ['Alkuin von York', 'Bernward von Hildesheim', 'Thietmar von Merseburg']],
          ['Welchen Papstnamen trug Gerbert von Aurillac?', 'Silvester II.', ['Gregor V.', 'Johannes XII.', 'Leo IX.']],
          ['Seit wann ist „Heiliges Römisches Reich“ als Name belegt?', '1254', ['962', '1157', '1512']],
        ],
      },
    },
  ],
};

export const SALIER: HistEvent = {
  id: 'salier',
  title: 'Die Salier und der Investiturstreit',
  date: '1024–1125',
  text: [
    'Auf die Ottonen folgten die Salier, eine Familie aus der Gegend von Worms und Speyer. Unter ihnen stand das Kaisertum zunächst auf dem Höhepunkt seiner Macht – bis der Streit mit dem Papst um die Einsetzung der Bischöfe das Reich erschütterte und Heinrich IV. nach Canossa zog.',
  ],
  subtopics: [
    {
      id: 'salier-kaiser',
      title: 'Die salischen Kaiser',
      date: '1024–1075',
      text: [
        'Nach dem Tod Heinrichs II. wählten die Fürsten 1024 in Kamba am Rhein, bei Oppenheim, den Franken Konrad II.; sein Rivale war sein gleichnamiger Vetter, Konrad der Jüngere. Konrads Frau war Gisela von Schwaben, sein Biograf der Kaplan Wipo. Die Familie stammte aus der Gegend um Worms und Speyer; den Namen „Salier“ erhielt sie erst später. Ostern 1027 wurde Konrad in Rom zum Kaiser gekrönt, in Anwesenheit König Knuts des Großen von England und Dänemark.',
        '1033 erbte Konrad das Königreich Burgund, das ihm der letzte burgundische König Rudolf III. vermacht hatte. Seitdem bestand das Reich aus drei Königreichen: Deutschland, Italien und Burgund. 1037 erließ Konrad ein Lehnsgesetz, das in Italien auch kleine Lehen erblich machte. Um 1030 ließ er mit dem Bau des Doms zu Speyer beginnen, der Grablege der Salier. 1061 geweiht, ist er die größte erhaltene romanische Kirche der Welt und seit 1981 UNESCO-Welterbe. Typisch für die Romanik sind Rundbögen, dicke Mauern und kleine Fenster. In seiner Krypta liegen acht Kaiser und Könige, darunter auch der Habsburger Rudolf I.',
        'Unter Heinrich III. (1039–1056) erreichte die Macht der Kaiser über die Kirche ihren Höhepunkt. In Rom stritten damals drei Päpste – Silvester III., Benedikt IX. und Gregor VI. – um ihr Amt. Auf der Synode von Sutri 1046 ließ Heinrich alle drei absetzen und machte Bischof Suidger von Bamberg als Clemens II. zum Papst; dessen Grab im Bamberger Dom ist das einzige Papstgrab in Deutschland. Später setzte Heinrich den Elsässer Bruno von Egisheim-Dagsburg als Leo IX. ein, der die Kirchenreform vorantrieb. Heinrich III. förderte den Gottesfrieden, der Fehden an bestimmten Tagen verbot.',
        'Heinrichs liebste Pfalz lag in Goslar am Harz, reich durch das Silber aus dem nahen Rammelsberg. Dort ist sein Herz begraben, sein Leichnam dagegen in Speyer. Er starb 1056 in der Pfalz Bodfeld im Harz, als sein Sohn Heinrich IV. erst sechs Jahre alt war. Für den Jungen regierte seine Mutter Agnes von Poitou.',
        '1062 lockte Erzbischof Anno von Köln den elfjährigen König in Kaiserswerth am Rhein auf ein Schiff und entführte ihn, um selbst die Regierung zu übernehmen. Heinrich sprang in den Rhein und wurde von Graf Ekbert von Braunschweig aus dem Wasser gezogen. Danach beeinflusste auch Erzbischof Adalbert von Bremen den jungen König. 1065 wurde Heinrich mit der Schwertleite für mündig erklärt; seine Frau wurde Bertha von Turin.',
        'Heinrich IV. wollte vor allem in Sachsen die Königsrechte stärken und ließ dort Burgen bauen, darunter die Harzburg. 1073 erhoben sich die Sachsen, angeführt unter anderem von Otto von Northeim. 1074 zerstörten sie die Harzburg und schändeten dabei die Gräber der Königsfamilie – das brachte viele Fürsten gegen sie auf. Am 9. Juni 1075 besiegte Heinrich die Sachsen bei Homburg an der Unstrut. Der Mönch Lampert von Hersfeld schrieb eine ausführliche, aber Heinrich sehr feindlich gesinnte Chronik dieser Jahre. Vier Salier wurden Kaiser: Konrad II., Heinrich III., Heinrich IV. und Heinrich V.; mit dem Tod Heinrichs V. 1125 endete die Familie.',
      ],
      quiz: {
        leicht: [
          ['Welche Familie folgte 1024 auf die Ottonen?', 'Die Salier', ['Die Staufer', 'Die Habsburger', 'Die Karolinger']],
          ['Wer war der erste Kaiser aus der Familie der Salier?', 'Konrad II.', ['Heinrich IV.', 'Otto III.', 'Friedrich I.']],
          ['Welcher Dom ist die Grablege der Salier?', 'Der Dom zu Speyer', ['Der Kölner Dom', 'Der Aachener Dom', 'Der Bamberger Dom']],
          ['In welchem Baustil ist der Speyerer Dom gebaut?', 'Romanik', ['Gotik', 'Barock', 'Renaissance']],
          ['Woran erkennt man romanische Kirchen?', 'An Rundbögen und dicken Mauern', ['An Spitzbögen und großen Fenstern', 'An Zwiebeltürmen', 'An Glasfassaden']],
          ['Was ist das Besondere am Speyerer Dom?', 'Er ist die größte erhaltene romanische Kirche der Welt', ['Er ist die älteste Kirche der Welt', 'Er ist komplett aus Holz', 'Er hat den höchsten Turm der Welt']],
          ['Welches Königreich kam 1033 zum Reich hinzu?', 'Burgund', ['Böhmen', 'Ungarn', 'Polen']],
          ['Aus wie vielen Königreichen bestand das Reich danach?', 'Drei', ['Zwei', 'Vier', 'Sieben']],
          ['Welcher Salier ließ 1046 Päpste absetzen?', 'Heinrich III.', ['Konrad II.', 'Heinrich IV.', 'Heinrich V.']],
          ['Wie viele Päpste wurden 1046 abgesetzt?', 'Drei', ['Einer', 'Zwei', 'Fünf']],
          ['In welcher Stadt am Harz hatte Heinrich III. seine liebste Pfalz?', 'Goslar', ['Quedlinburg', 'Magdeburg', 'Halberstadt']],
          ['Welches Metall wurde am Rammelsberg bei Goslar abgebaut?', 'Silber', ['Gold', 'Kupfer', 'Zinn']],
          ['Wie alt war Heinrich IV. beim Tod seines Vaters?', 'Sechs Jahre', ['Zwei Jahre', 'Sechzehn Jahre', 'Dreißig Jahre']],
          ['Wer regierte zuerst für den jungen Heinrich IV.?', 'Seine Mutter Agnes', ['Der Papst', 'Sein Onkel', 'Ein Herzog aus Sachsen']],
          ['Was tat Heinrich IV. 1062, um seinen Entführern zu entkommen?', 'Er sprang in den Rhein', ['Er kletterte aus einem Turm', 'Er versteckte sich in einer Truhe', 'Er bestach die Wachen']],
          ['Welcher Erzbischof entführte Heinrich IV. 1062?', 'Anno von Köln', ['Adalbert von Bremen', 'Siegfried von Mainz', 'Bernward von Hildesheim']],
          ['Gegen welchen Stamm kämpfte Heinrich IV. ab 1073?', 'Die Sachsen', ['Die Bayern', 'Die Ungarn', 'Die Friesen']],
          ['Was ließ Heinrich IV. in Sachsen bauen?', 'Burgen', ['Klöster', 'Häfen', 'Universitäten']],
          ['Aus welcher Gegend stammten die Salier?', 'Aus der Gegend von Worms und Speyer', ['Aus Sachsen', 'Aus Bayern', 'Aus Lothringen']],
          ['Wann endete die Herrschaft der Salier?', '1125', ['1024', '1077', '1250']],
        ],
        mittel: [
          ['Wo wurde Konrad II. 1024 zum König gewählt?', 'In Kamba am Rhein', ['In Aachen', 'In Frankfurt', 'In Forchheim']],
          ['Wer schrieb eine Biografie Konrads II.?', 'Wipo', ['Widukind', 'Thietmar', 'Lampert']],
          ['Wann begann der Bau des Speyerer Doms?', 'Um 1030', ['Um 950', 'Um 1150', 'Um 1250']],
          ['Wann wurde der Speyerer Dom geweiht?', '1061', ['1030', '1125', '1006']],
          ['Seit wann ist der Speyerer Dom UNESCO-Welterbe?', '1981', ['1950', '2001', '1990']],
          ['Was regelte Konrads Lehnsgesetz von 1037?', 'Die Erblichkeit kleiner Lehen in Italien', ['Die Wahl des Papstes', 'Die Teilung des Reiches', 'Den Bau von Burgen']],
          ['Auf welcher Synode setzte Heinrich III. 1046 die Päpste ab?', 'Auf der Synode von Sutri', ['Auf der Synode von Worms', 'Auf dem Konzil von Konstanz', 'Auf der Synode von Frankfurt']],
          ['Welcher deutsche Papst wurde 1046 eingesetzt?', 'Clemens II.', ['Leo IX.', 'Gregor VII.', 'Viktor II.']],
          ['Wo ist Papst Clemens II. begraben?', 'Im Bamberger Dom', ['Im Petersdom', 'Im Speyerer Dom', 'Im Kölner Dom']],
          ['Welcher Papst aus dem Elsass trieb die Kirchenreform voran?', 'Leo IX.', ['Clemens II.', 'Silvester III.', 'Urban II.']],
          ['Wo ist das Herz Heinrichs III. begraben?', 'In Goslar', ['In Speyer', 'In Rom', 'In Aachen']],
          ['Wann starb Heinrich III.?', '1056', ['1039', '1077', '1046']],
          ['Wo wurde Heinrich IV. 1062 entführt?', 'In Kaiserswerth', ['In Goslar', 'In Speyer', 'In Mainz']],
          ['Wann begann der Aufstand der Sachsen?', '1073', ['1062', '1077', '1080']],
          ['Wann besiegte Heinrich IV. die Sachsen bei Homburg?', '1075', ['1073', '1080', '1066']],
          ['Welche Burg zerstörten die Sachsen 1074?', 'Die Harzburg', ['Die Wartburg', 'Die Eresburg', 'Die Reichsburg Cochem']],
          ['Was empörte an der Zerstörung der Harzburg besonders?', 'Die Gräber der Königsfamilie wurden geschändet', ['Eine Kirche wurde zur Moschee', 'Der König war gerade darin', 'Der Papst hatte sie geweiht']],
          ['Wie nennt man das Verbot von Fehden an bestimmten Tagen?', 'Gottesfrieden', ['Landfrieden', 'Burgfrieden', 'Kirchenbann']],
          ['Aus welcher Familie stammte Kaiserin Agnes?', 'Aus dem Haus Poitou', ['Aus dem Haus Wittelsbach', 'Aus dem Haus der Welfen', 'Aus dem Haus Savoyen']],
          ['Wie viele Salier wurden Kaiser?', 'Vier', ['Zwei', 'Drei', 'Sechs']],
        ],
        schwer: [
          ['In der Nähe welcher Stadt lag Kamba?', 'Oppenheim', ['Mainz', 'Speyer', 'Worms']],
          ['Wer war Konrads Rivale bei der Wahl 1024?', 'Sein Vetter Konrad der Jüngere', ['Heinrich II.', 'Herzog Ernst von Schwaben', 'Rudolf III. von Burgund']],
          ['Wie hieß die Frau Konrads II.?', 'Gisela von Schwaben', ['Agnes von Poitou', 'Bertha von Turin', 'Kunigunde']],
          ['Welche drei Päpste wurden 1046 abgesetzt?', 'Silvester III., Benedikt IX. und Gregor VI.', ['Leo IX., Clemens II. und Viktor II.', 'Johannes XII., Leo VIII. und Benedikt V.', 'Gregor VII., Urban II. und Paschalis II.']],
          ['Welcher Bischof wurde Papst Clemens II.?', 'Suidger von Bamberg', ['Bruno von Toul', 'Gebhard von Eichstätt', 'Poppo von Brixen']],
          ['Was ist das Besondere am Grab von Clemens II.?', 'Es ist das einzige Papstgrab in Deutschland', ['Es ist leer', 'Es liegt unter dem Rhein', 'Es ist das älteste Papstgrab']],
          ['Wie hieß Leo IX. vor seiner Wahl?', 'Bruno von Egisheim-Dagsburg', ['Hildebrand', 'Suidger', 'Wibert von Ravenna']],
          ['Wo starb Heinrich III.?', 'In der Pfalz Bodfeld im Harz', ['In Goslar', 'In Rom', 'In Speyer']],
          ['Wer zog Heinrich IV. 1062 aus dem Rhein?', 'Graf Ekbert von Braunschweig', ['Otto von Northeim', 'Anno von Köln', 'Rudolf von Rheinfelden']],
          ['Wann wurde Heinrich IV. mit der Schwertleite für mündig erklärt?', '1065', ['1056', '1062', '1073']],
          ['Welcher Erzbischof von Bremen beeinflusste den jungen Heinrich IV.?', 'Adalbert', ['Anno', 'Hatto', 'Ansgar']],
          ['An welchem Tag war die Schlacht bei Homburg an der Unstrut?', '9. Juni 1075', ['28. Januar 1077', '15. Oktober 1080', '23. September 1122']],
          ['Wer war einer der Anführer des Sachsenaufstands?', 'Otto von Northeim', ['Anno von Köln', 'Rudolf von Rheinfelden', 'Welf IV.']],
          ['Wie viele Kaiser und Könige sind in der Krypta des Speyerer Doms begraben?', 'Acht', ['Vier', 'Zwölf', 'Zwei']],
          ['Welcher Habsburger liegt ebenfalls im Speyerer Dom?', 'Rudolf I.', ['Maximilian I.', 'Karl V.', 'Friedrich III.']],
          ['Wann wurde Konrad II. zum Kaiser gekrönt?', '1027', ['1024', '1033', '1039']],
          ['Welcher König von England und Dänemark war bei Konrads Kaiserkrönung dabei?', 'Knut der Große', ['Wilhelm der Eroberer', 'Harald Blauzahn', 'Eduard der Bekenner']],
          ['Welcher König vermachte Konrad II. Burgund?', 'Rudolf III.', ['Lothar III.', 'Konrad von Burgund', 'Boso']],
          ['Wie hieß die Frau Heinrichs IV.?', 'Bertha von Turin', ['Agnes von Poitou', 'Gisela von Schwaben', 'Mathilde von Tuszien']],
          ['Welcher Chronist schrieb sehr feindselig über Heinrich IV.?', 'Lampert von Hersfeld', ['Wipo', 'Otto von Freising', 'Thietmar von Merseburg']],
        ],
      },
    },
    {
      id: 'canossa',
      title: 'Investiturstreit und Canossa',
      date: '1075–1122',
      text: [
        'Seit dem 10. Jahrhundert forderten Reformer, ausgehend vom 910 gegründeten Kloster Cluny in Burgund, eine bessere Kirche: Kirchenämter sollten nicht mehr gekauft werden (das nannte man Simonie), und Priester sollten nicht heiraten. 1059 bestimmte ein Papstwahldekret, dass künftig die Kardinäle den Papst wählen. Bald stellten die Reformer auch die Frage, ob ein weltlicher Herrscher Bischöfe einsetzen dürfe. Diese Einsetzung, bei der der König dem Bischof Ring und Stab überreichte, hieß Investitur.',
        '1073 wurde der Mönch Hildebrand als Gregor VII. Papst. 1075 hielt er im „Dictatus Papae“ fest, dass der Papst über allen stehe und sogar Kaiser absetzen dürfe. Als Heinrich IV. trotzdem einen Erzbischof für Mailand einsetzte, kam es zum offenen Streit, dem Investiturstreit. Im Januar 1076 erklärten deutsche Bischöfe auf einer Synode in Worms Gregor für abgesetzt. Heinrich schrieb ihm: „Heinrich, nicht durch Anmaßung, sondern durch Gottes gerechte Anordnung König, an Hildebrand, jetzt nicht mehr Papst, sondern falscher Mönch“ – und schloss mit „Steig herab, steig herab!“.',
        'Gregor antwortete im Februar 1076 mit dem Kirchenbann: Heinrich war aus der Kirche ausgeschlossen, und seine Untertanen waren von ihrem Treueeid befreit. Viele Fürsten wandten sich nun gegen den König. Im Oktober 1076 beschlossen sie in Tribur, einen neuen König zu wählen, wenn Heinrich nicht binnen eines Jahres vom Bann gelöst sei.',
        'Im bitterkalten Winter 1076/77 zog Heinrich mit seiner Frau Bertha und seinem kleinen Sohn über den Alpenpass Mont Cenis nach Italien. Gregor hatte sich auf die Burg Canossa der Markgräfin Mathilde von Tuszien zurückgezogen. Vom 25. bis 27. Januar 1077 stand Heinrich im Büßergewand und barfuß vor dem Burgtor. Mathilde und Abt Hugo von Cluny, Heinrichs Taufpate, vermittelten, und am 28. Januar 1077 löste Gregor ihn vom Bann. „Nach Canossa gehen“ bedeutet heute, sich demütigen und um Verzeihung bitten zu müssen. Doch Heinrich hatte damit auch politisch gewonnen: Er war wieder handlungsfähig.',
        'Trotzdem wählten die Fürsten im März 1077 in Forchheim Rudolf von Rheinfelden zum Gegenkönig. Es folgte ein Bürgerkrieg. 1080 verlor Rudolf in der Schlacht bei Hohenmölsen an der Weißen Elster seine rechte Hand – die Schwurhand – und starb daran; er ist im Merseburger Dom begraben. Gregor bannte Heinrich 1080 ein zweites Mal. 1084 eroberte Heinrich Rom und ließ sich vom Gegenpapst Clemens III. (Wibert von Ravenna) zum Kaiser krönen. Gregor wurde von den Normannen unter Robert Guiscard befreit, die Rom dabei plünderten. Er starb 1085 im Exil in Salerno mit den Worten: „Ich habe die Gerechtigkeit geliebt und das Unrecht gehasst, darum sterbe ich in der Verbannung.“',
        'Auch Heinrichs Söhne wandten sich gegen ihn, zuerst 1093 Konrad, dann Heinrich V., der den Vater 1105/06 stürzte. Heinrich IV. starb 1106 in Lüttich. Weil er im Bann gestorben war, blieb sein Sarg fünf Jahre unbestattet in einer Kapelle des Speyerer Doms, bis 1111.',
        'Am 23. September 1122 schlossen Heinrich V. und Papst Calixt II. das Wormser Konkordat. Man unterschied nun die geistlichen Rechte eines Bischofs (Spiritualia) von seinen weltlichen Rechten (Temporalia). Die Kirche wählte und weihte die Bischöfe und übergab Ring und Stab; der König verlieh die weltlichen Rechte mit dem Zepter – in Deutschland vor der Weihe, in Italien und Burgund innerhalb von sechs Monaten danach. Heinrich V. starb 1125 als letzter Salier. Noch 1872, im Kulturkampf gegen die katholische Kirche, erklärte Reichskanzler Bismarck: „Nach Canossa gehen wir nicht.“',
      ],
      quiz: {
        leicht: [
          ['Wie heißt der Streit zwischen Kaiser und Papst im 11. Jahrhundert?', 'Investiturstreit', ['Dreißigjähriger Krieg', 'Kulturkampf', 'Schisma']],
          ['Was bedeutet Investitur?', 'Die Einsetzung von Bischöfen', ['Die Krönung eines Kaisers', 'Die Wahl des Papstes', 'Ein Kreuzzug']],
          ['Welcher König stritt mit Papst Gregor VII.?', 'Heinrich IV.', ['Otto der Große', 'Friedrich Barbarossa', 'Karl der Große']],
          ['Welcher Papst stritt mit Heinrich IV.?', 'Gregor VII.', ['Leo III.', 'Innozenz III.', 'Urban II.']],
          ['Was verhängte der Papst 1076 gegen Heinrich?', 'Den Kirchenbann', ['Eine Geldstrafe', 'Eine Pilgerreise', 'Ein Kreuzzugsgelübde']],
          ['Wohin zog Heinrich im Winter 1076/77?', 'Nach Canossa', ['Nach Jerusalem', 'Nach Konstantinopel', 'Nach Aachen']],
          ['In welchem heutigen Land liegt Canossa?', 'Italien', ['Frankreich', 'Österreich', 'Schweiz']],
          ['Wie zeigte Heinrich vor Canossa seine Reue?', 'Er stand drei Tage barfuß im Büßergewand', ['Er schenkte dem Papst eine Krone', 'Er ließ sich auspeitschen', 'Er trat in ein Kloster ein']],
          ['In welchem Jahr war der Gang nach Canossa?', '1077', ['1066', '1122', '1190']],
          ['Was bedeutet „nach Canossa gehen“ heute?', 'Sich demütigen und um Verzeihung bitten', ['Eine lange Reise machen', 'In den Krieg ziehen', 'Urlaub in Italien machen']],
          ['Welche Zeichen übergab man bei der Einsetzung eines Bischofs?', 'Ring und Stab', ['Schwert und Schild', 'Krone und Zepter', 'Buch und Kerze']],
          ['Welcher Vertrag beendete den Investiturstreit?', 'Das Wormser Konkordat', ['Der Westfälische Frieden', 'Die Goldene Bulle', 'Der Vertrag von Verdun']],
          ['In welchem Jahr wurde das Wormser Konkordat geschlossen?', '1122', ['1077', '1155', '1356']],
          ['Welches Gebirge überquerte Heinrich auf dem Weg nach Canossa?', 'Die Alpen', ['Die Pyrenäen', 'Den Harz', 'Die Karpaten']],
          ['Wem gehörte die Burg Canossa?', 'Markgräfin Mathilde von Tuszien', ['Dem Papst', 'Kaiserin Agnes', 'Dem Abt von Cluny']],
          ['Was bedeutete der Kirchenbann für Heinrichs Untertanen?', 'Sie waren von ihrem Treueeid befreit', ['Sie mussten mehr Steuern zahlen', 'Sie durften nicht mehr beten', 'Sie mussten nach Rom ziehen']],
          ['Wer wählte 1077 einen Gegenkönig?', 'Die Fürsten', ['Der Papst', 'Die Bauern', 'Die Bürger von Rom']],
          ['Wie nannte man den Kauf von Kirchenämtern?', 'Simonie', ['Investitur', 'Ablass', 'Zehnt']],
          ['Welches Kloster in Burgund war Zentrum der Kirchenreform?', 'Cluny', ['Monte Cassino', 'Fulda', 'Cîteaux']],
          ['Welcher Reichskanzler sagte 1872 „Nach Canossa gehen wir nicht“?', 'Otto von Bismarck', ['Konrad Adenauer', 'Wilhelm II.', 'Gustav Stresemann']],
        ],
        mittel: [
          ['Wie hieß Gregor VII. vor seiner Wahl?', 'Hildebrand', ['Wibert', 'Bruno', 'Suidger']],
          ['Wann wurde Gregor VII. Papst?', '1073', ['1059', '1077', '1085']],
          ['Welches Schriftstück erklärte 1075 den Papst zum Herrn über die Kaiser?', 'Der Dictatus Papae', ['Das Wormser Konkordat', 'Die Konstantinische Schenkung', 'Das Ottonianum']],
          ['Wo erklärten deutsche Bischöfe Gregor 1076 für abgesetzt?', 'In Worms', ['In Mainz', 'In Tribur', 'In Rom']],
          ['Wie nannte Heinrich den Papst in seinem Brief?', 'Nicht mehr Papst, sondern falscher Mönch', ['Heiliger Vater', 'Bruder in Christus', 'Bischof von Rom']],
          ['Um welchen Bischofssitz entbrannte der Streit?', 'Mailand', ['Köln', 'Rom', 'Ravenna']],
          ['Wo trafen sich die Fürsten im Oktober 1076?', 'In Tribur', ['In Forchheim', 'In Worms', 'In Canossa']],
          ['Welche Frist setzten die Fürsten Heinrich?', 'Ein Jahr, um vom Bann gelöst zu werden', ['Einen Monat für einen Kreuzzug', 'Zehn Jahre bis zur Abdankung', 'Eine Woche für eine Entschuldigung']],
          ['Über welchen Alpenpass zog Heinrich 1076/77?', 'Über den Mont Cenis', ['Über den Brenner', 'Über den Gotthard', 'Über den Großen St. Bernhard']],
          ['Welcher Abt vermittelte in Canossa?', 'Hugo von Cluny', ['Bernhard von Clairvaux', 'Benedikt von Aniane', 'Wilhelm von Hirsau']],
          ['Wer wurde 1077 zum Gegenkönig gewählt?', 'Rudolf von Rheinfelden', ['Hermann von Salm', 'Otto von Northeim', 'Konrad']],
          ['Woran starb Gegenkönig Rudolf 1080?', 'Er verlor in der Schlacht seine rechte Hand', ['An der Pest', 'Er ertrank', 'Er wurde vergiftet']],
          ['Wann bannte Gregor Heinrich zum zweiten Mal?', '1080', ['1077', '1084', '1076']],
          ['Wer krönte Heinrich 1084 zum Kaiser?', 'Gegenpapst Clemens III.', ['Gregor VII.', 'Urban II.', 'Calixt II.']],
          ['Wer befreite Gregor 1084 und plünderte dabei Rom?', 'Die Normannen unter Robert Guiscard', ['Die Sarazenen', 'Die Byzantiner', 'Die Sachsen']],
          ['Wo starb Gregor VII.?', 'In Salerno', ['In Rom', 'In Canossa', 'In Cluny']],
          ['Wer stürzte Heinrich IV.?', 'Sein Sohn Heinrich V.', ['Gregor VII.', 'Rudolf von Rheinfelden', 'Mathilde von Tuszien']],
          ['Mit welchem Papst schloss Heinrich V. das Wormser Konkordat?', 'Calixt II.', ['Gregor VII.', 'Urban II.', 'Paschalis II.']],
          ['Womit verlieh der König nach 1122 die weltlichen Rechte?', 'Mit dem Zepter', ['Mit Ring und Stab', 'Mit dem Schwert', 'Mit der Krone']],
          ['Wer wählt den Papst seit dem Dekret von 1059?', 'Die Kardinäle', ['Der Kaiser', 'Das Volk von Rom', 'Alle Bischöfe']],
        ],
        schwer: [
          ['An welchen Tagen stand Heinrich vor Canossa?', '25. bis 27. Januar 1077', ['24. bis 26. Dezember 1076', '1. bis 3. März 1077', '10. bis 12. Februar 1076']],
          ['Wann wurde Heinrich vom Bann gelöst?', 'Am 28. Januar 1077', ['Am 25. Dezember 1076', 'Am 15. März 1077', 'Am 23. September 1122']],
          ['Mit welchen Worten soll Gregor VII. gestorben sein?', '„Ich habe die Gerechtigkeit geliebt und das Unrecht gehasst …“', ['„Steig herab, steig herab!“', '„Gott will es!“', '„Nach Canossa gehen wir nicht.“']],
          ['Wann wurde das Kloster Cluny gegründet?', '910', ['800', '1098', '1046']],
          ['Wo wurde Rudolf von Rheinfelden zum Gegenkönig gewählt?', 'In Forchheim', ['In Tribur', 'In Worms', 'In Goslar']],
          ['In welcher Schlacht verlor Rudolf seine Hand?', 'Bei Hohenmölsen an der Weißen Elster', ['Bei Homburg an der Unstrut', 'Auf dem Lechfeld', 'Bei Legnano']],
          ['Wo ist Rudolf von Rheinfelden begraben?', 'Im Merseburger Dom', ['Im Speyerer Dom', 'Im Kloster Hirsau', 'Im Bamberger Dom']],
          ['Wo starb Heinrich IV.?', 'In Lüttich', ['In Speyer', 'In Canossa', 'In Rom']],
          ['Wie lange blieb Heinrich IV. unbestattet?', 'Fünf Jahre', ['Fünf Tage', 'Ein Jahr', 'Fünfzig Jahre']],
          ['Wer begleitete Heinrich nach Canossa?', 'Seine Frau Bertha und sein kleiner Sohn', ['Rudolf von Rheinfelden', 'Erzbischof Anno', 'Otto von Northeim']],
          ['In welcher Beziehung stand Hugo von Cluny zu Heinrich IV.?', 'Er war sein Taufpate', ['Er war sein Onkel', 'Er war sein Lehrer', 'Er war sein Kanzler']],
          ['Wie hieß Gegenpapst Clemens III. eigentlich?', 'Wibert von Ravenna', ['Hildebrand', 'Bruno von Toul', 'Odo von Châtillon']],
          ['An welchem Tag wurde das Wormser Konkordat geschlossen?', '23. September 1122', ['28. Januar 1077', '2. Februar 962', '25. Dezember 1122']],
          ['Wann erhielt ein Bischof in Italien seine weltlichen Rechte nach 1122?', 'Innerhalb von sechs Monaten nach der Weihe', ['Vor der Weihe', 'Nie', 'Erst nach seinem Tod']],
          ['Wann erhielt ein Bischof in Deutschland seine weltlichen Rechte nach 1122?', 'Vor der Weihe', ['Sechs Monate nach der Weihe', 'Erst nach einem Jahr', 'Nur mit Zustimmung des Papstes']],
          ['Wie nennt man die geistlichen und die weltlichen Rechte eines Bischofs?', 'Spiritualia und Temporalia', ['Regalia und Insignia', 'Sacramenta und Beneficia', 'Officia und Feuda']],
          ['Wann starb Heinrich V.?', '1125', ['1106', '1122', '1138']],
          ['Welcher Sohn Heinrichs IV. rebellierte schon 1093?', 'Konrad', ['Heinrich V.', 'Friedrich', 'Rudolf']],
          ['Womit endete Heinrichs Brief an Gregor 1076?', '„Steig herab, steig herab!“', ['„Gott will es!“', '„Ora et labora!“', '„Nach Canossa gehen wir nicht!“']],
          ['In welchem Konflikt sagte Bismarck „Nach Canossa gehen wir nicht“?', 'Im Kulturkampf gegen die katholische Kirche', ['Im Deutsch-Französischen Krieg', 'Im Streit mit Österreich', 'Im Konflikt mit den Sozialdemokraten']],
        ],
      },
    },
  ],
};

export const STAUFER: HistEvent = {
  id: 'staufer',
  title: 'Die Staufer',
  date: '1138–1268',
  text: [
    'Die Staufer, benannt nach ihrer Burg Hohenstaufen in Schwaben, stellten über hundert Jahre die Könige und Kaiser. Friedrich Barbarossa und sein Enkel Friedrich II. gehören zu den berühmtesten Herrschern des Mittelalters – doch am Ende ging die Familie im Kampf mit dem Papsttum unter.',
  ],
  subtopics: [
    {
      id: 'barbarossa',
      title: 'Friedrich Barbarossa',
      date: '1138–1197',
      text: [
        'Nach dem Ende der Salier wählten die Fürsten 1125 den Sachsen Lothar III. von Supplinburg. Nach seinem Tod wurde 1138 Konrad III. König, der erste Staufer. Die Familie hatte ihren Namen von der Burg Hohenstaufen bei Göppingen. Ihre großen Rivalen waren die Welfen, etwa Herzog Heinrich der Stolze. 1140 belagerte Konrad die welfische Burg Weinsberg; der Sage nach durften die Frauen mitnehmen, was sie tragen konnten – und trugen ihre Männer auf dem Rücken heraus („Weiber von Weinsberg“). In Italien hießen die Anhänger der Staufer später Ghibellinen, die der Welfen Guelfen.',
        '1152 wählten die Fürsten in Frankfurt Konrads Neffen Friedrich I. zum König. Die Italiener nannten ihn wegen seines rötlichen Bartes „Barbarossa“, Rotbart. Seine Mutter Judith war eine Welfin, und so sollte er den Streit der Familien beenden. Seinem Vetter Heinrich dem Löwen, Sohn Heinrichs des Stolzen und schon Herzog von Sachsen, gab er 1156 auch Bayern. Im selben Jahr machte er Österreich mit dem „Privilegium minus“ zu einem eigenen Herzogtum. 1155 krönte ihn Papst Hadrian IV., der einzige Engländer auf dem Papstthron, zum Kaiser.',
        'Barbarossa wollte die Kaiserrechte in Italien durchsetzen, wo reiche Städte wie Mailand selbstständig geworden waren. Auf dem Reichstag von Roncaglia 1158 ließ er seine Rechte, etwa Zölle und Münzrecht, festschreiben. 1162 ließ er Mailand zerstören. Die Städte schlossen sich zum Lombardischen Bund zusammen. Auch mit dem Papst gab es Streit: 1157 sorgte in Besançon ein Brief des Papstes für Empörung, der die Kaiserkrone ein „beneficium“ nannte – das konnte „Wohltat“, aber auch „Lehen“ heißen. Im selben Jahr tauchte erstmals die Bezeichnung „Heiliges Reich“ auf.',
        '1176 bat Barbarossa Heinrich den Löwen in Chiavenna um Hilfe, doch der verweigerte sie. Kurz darauf unterlag der Kaiser dem Lombardischen Bund bei Legnano. 1177 schloss er in Venedig Frieden mit Papst Alexander III., 1183 in Konstanz mit den lombardischen Städten.',
        'Heinrich der Löwe war der mächtigste Fürst des Reiches. Er gründete 1158 München, gründete 1159 Lübeck neu und machte Braunschweig mit der Burg Dankwarderode zu seiner Residenz, wo er 1166 ein Löwenstandbild aufstellen ließ. Seine Frau war eine Tochter König Heinrichs II. von England. Nach einem Prozess verlor er 1180 seine Herzogtümer (Urkunde von Gelnhausen). Bayern erhielt Otto von Wittelsbach – die Wittelsbacher regierten Bayern bis 1918. Heinrich musste ins Exil nach England.',
        'Pfingsten 1184 feierte Barbarossa das prächtige Mainzer Hoffest, auf dem seine Söhne zu Rittern erhoben wurden. 1189 brach er zum Dritten Kreuzzug auf. Am 10. Juni 1190 ertrank er im Fluss Saleph in Kleinasien, in der heutigen Türkei. Später entstand die Sage, er schlafe im Kyffhäuser-Berg in Thüringen; sein Bart wachse durch den Tisch, und wenn keine Raben mehr um den Berg fliegen, werde er erwachen und das Reich erneuern. 1896 wurde dort das Kyffhäuserdenkmal eingeweiht.',
        'Barbarossas Sohn Heinrich VI. heiratete 1186 Konstanze von Sizilien und eroberte 1194 das Königreich Sizilien. Den englischen König Richard Löwenherz, der auf der Rückkehr vom Kreuzzug in Österreich gefangen genommen und auf Burg Dürnstein festgehalten worden war, ließ er erst gegen ein Lösegeld von 150.000 Mark Silber frei. Heinrich VI. starb 1197 in Messina.',
      ],
      quiz: {
        leicht: [
          ['Welche Familie stellte ab 1138 die Könige?', 'Die Staufer', ['Die Salier', 'Die Habsburger', 'Die Welfen']],
          ['Nach welcher Burg sind die Staufer benannt?', 'Hohenstaufen', ['Hohenzollern', 'Wartburg', 'Habsburg']],
          ['Wer ist der berühmteste Staufer?', 'Friedrich Barbarossa', ['Heinrich der Löwe', 'Otto der Große', 'Karl der Große']],
          ['Was bedeutet „Barbarossa“?', 'Rotbart', ['Großer Bär', 'Roter Löwe', 'Starker Arm']],
          ['Aus welcher Sprache kommt „Barbarossa“?', 'Aus dem Italienischen', ['Aus dem Lateinischen', 'Aus dem Französischen', 'Aus dem Griechischen']],
          ['In welchem Jahr wurde Barbarossa König?', '1152', ['1077', '1190', '1250']],
          ['Welche Familie war der große Rivale der Staufer?', 'Die Welfen', ['Die Ottonen', 'Die Wittelsbacher', 'Die Karolinger']],
          ['Welcher Welfe war der mächtigste Fürst unter Barbarossa?', 'Heinrich der Löwe', ['Heinrich der Vogler', 'Heinrich der Fromme', 'Heinrich der Seefahrer']],
          ['Welche Stadt gründete Heinrich der Löwe 1158?', 'München', ['Berlin', 'Hamburg', 'Nürnberg']],
          ['Welches Tierstandbild ließ Heinrich in Braunschweig aufstellen?', 'Einen Löwen', ['Einen Adler', 'Einen Bären', 'Ein Pferd']],
          ['Mit wem stritt Barbarossa in Italien besonders?', 'Mit den reichen Städten Oberitaliens', ['Mit den Wikingern', 'Mit den Byzantinern', 'Mit den Arabern in Spanien']],
          ['Welche Stadt ließ Barbarossa 1162 zerstören?', 'Mailand', ['Rom', 'Venedig', 'Florenz']],
          ['Auf welchem Kreuzzug starb Barbarossa?', 'Auf dem Dritten Kreuzzug', ['Auf dem Ersten Kreuzzug', 'Auf dem Zweiten Kreuzzug', 'Auf dem Kinderkreuzzug']],
          ['Wie starb Barbarossa?', 'Er ertrank in einem Fluss', ['Er fiel in einer Schlacht', 'Er wurde vergiftet', 'Er starb an der Pest']],
          ['In welchem Berg soll Barbarossa der Sage nach schlafen?', 'Im Kyffhäuser', ['Im Brocken', 'Im Untersberg', 'In der Zugspitze']],
          ['Was wächst der Sage nach durch den Tisch?', 'Barbarossas Bart', ['Ein Baum', 'Seine Fingernägel', 'Ein Schwert']],
          ['Welche Vögel fliegen der Sage nach um den Kyffhäuser?', 'Raben', ['Adler', 'Tauben', 'Falken']],
          ['Welche Familie erhielt 1180 Bayern?', 'Die Wittelsbacher', ['Die Habsburger', 'Die Welfen', 'Die Hohenzollern']],
          ['Bis wann regierten die Wittelsbacher in Bayern?', '1918', ['1806', '1871', '1945']],
          ['Welchen englischen König nahm Heinrich VI. gefangen?', 'Richard Löwenherz', ['Wilhelm den Eroberer', 'Heinrich VIII.', 'Johann Ohneland']],
        ],
        mittel: [
          ['Wer war König zwischen den Saliern und den Staufern?', 'Lothar III. von Supplinburg', ['Heinrich der Löwe', 'Rudolf von Rheinfelden', 'Otto IV.']],
          ['Wer war der erste König aus der Familie der Staufer?', 'Konrad III.', ['Friedrich I.', 'Heinrich VI.', 'Philipp von Schwaben']],
          ['Was trugen die „Weiber von Weinsberg“ aus der Burg?', 'Ihre Männer', ['Ihren Schmuck', 'Ihre Kinder', 'Den Burgschatz']],
          ['Wann wurde Weinsberg belagert?', '1140', ['1077', '1180', '1212']],
          ['Wie hießen die Anhänger der Staufer und der Welfen in Italien?', 'Ghibellinen und Guelfen', ['Patrizier und Plebejer', 'Optimaten und Popularen', 'Blaue und Grüne']],
          ['Wo wurde Barbarossa 1152 gewählt?', 'In Frankfurt', ['In Aachen', 'In Mainz', 'In Rom']],
          ['Wann wurde Barbarossa zum Kaiser gekrönt?', '1155', ['1152', '1162', '1177']],
          ['Welches neue Herzogtum entstand 1156?', 'Österreich', ['Bayern', 'Sachsen', 'Böhmen']],
          ['Wo ließ Barbarossa 1158 seine Rechte in Italien festschreiben?', 'Auf dem Reichstag von Roncaglia', ['Auf dem Hoftag in Mainz', 'In Canossa', 'In Venedig']],
          ['Wie hieß der Zusammenschluss der oberitalienischen Städte?', 'Lombardischer Bund', ['Hanse', 'Rheinischer Städtebund', 'Schwäbischer Bund']],
          ['Wo unterlag Barbarossa 1176?', 'Bei Legnano', ['Bei Mailand', 'Bei Bouvines', 'Bei Benevent']],
          ['Mit welchem Papst schloss Barbarossa 1177 Frieden?', 'Alexander III.', ['Hadrian IV.', 'Innozenz III.', 'Gregor VII.']],
          ['Wo verweigerte Heinrich der Löwe 1176 dem Kaiser die Hilfe?', 'In Chiavenna', ['In Roncaglia', 'In Legnano', 'In Mainz']],
          ['Wann verlor Heinrich der Löwe seine Herzogtümer?', '1180', ['1156', '1176', '1190']],
          ['Wohin ging Heinrich der Löwe ins Exil?', 'Nach England', ['Nach Dänemark', 'Nach Frankreich', 'Nach Jerusalem']],
          ['Welches große Fest feierte Barbarossa Pfingsten 1184?', 'Das Mainzer Hoffest', ['Das Aachener Krönungsfest', 'Den Kölner Karneval', 'Das Wormser Reichsfest']],
          ['In welchem Fluss ertrank Barbarossa?', 'Im Saleph', ['Im Jordan', 'Im Euphrat', 'Im Nil']],
          ['In welchem Jahr starb Barbarossa?', '1190', ['1180', '1197', '1152']],
          ['Wen heiratete Barbarossas Sohn Heinrich VI.?', 'Konstanze von Sizilien', ['Adelheid von Burgund', 'Beatrix von Burgund', 'Theophanu']],
          ['Auf welcher Burg wurde Richard Löwenherz festgehalten?', 'Dürnstein', ['Trifels', 'Wartburg', 'Hohenstaufen']],
        ],
        schwer: [
          ['Welcher Papst krönte Barbarossa zum Kaiser?', 'Hadrian IV.', ['Alexander III.', 'Eugen III.', 'Innozenz II.']],
          ['Was ist das Besondere an Papst Hadrian IV.?', 'Er war der einzige englische Papst', ['Er war der jüngste Papst', 'Er war vorher Kaiser', 'Er war der erste deutsche Papst']],
          ['An welchem Tag ertrank Barbarossa?', '10. Juni 1190', ['15. August 1190', '26. Dezember 1194', '28. Januar 1189']],
          ['In welchem heutigen Land liegt der Fluss Saleph?', 'In der Türkei', ['In Syrien', 'In Griechenland', 'In Israel']],
          ['Wie heißt die Urkunde, die Österreich 1156 zum Herzogtum machte?', 'Privilegium minus', ['Goldene Bulle', 'Constitutio de feudis', 'Dictatus Papae']],
          ['In welcher Urkunde wurde Heinrich der Löwe 1180 entmachtet?', 'In der Gelnhäuser Urkunde', ['Im Wormser Konkordat', 'Im Privilegium minus', 'Im Mainzer Landfrieden']],
          ['Wer war Heinrichs des Löwen Schwiegervater?', 'König Heinrich II. von England', ['Kaiser Lothar III.', 'König Ludwig VII. von Frankreich', 'König Waldemar von Dänemark']],
          ['Welches Wort im Papstbrief sorgte 1157 in Besançon für Empörung?', '„beneficium“', ['„imperium“', '„sacrum“', '„investitura“']],
          ['Wann gründete Heinrich der Löwe Lübeck neu?', '1159', ['1143', '1180', '1226']],
          ['Wie heißt Heinrichs des Löwen Burg in Braunschweig?', 'Dankwarderode', ['Wolfenbüttel', 'Harzburg', 'Lichtenberg']],
          ['Wann ließ Heinrich der Löwe das Löwenstandbild aufstellen?', '1166', ['1158', '1180', '1190']],
          ['Wie hoch war das Lösegeld für Richard Löwenherz?', '150.000 Mark Silber', ['1.000 Mark Silber', '1 Million Goldgulden', '15.000 Mark Silber']],
          ['Wann eroberte Heinrich VI. das Königreich Sizilien?', '1194', ['1186', '1190', '1212']],
          ['Wo starb Heinrich VI.?', 'In Messina', ['In Palermo', 'In Rom', 'In Speyer']],
          ['Wann wurde das Kyffhäuserdenkmal eingeweiht?', '1896', ['1871', '1813', '1913']],
          ['Wer war der Vater Heinrichs des Löwen?', 'Heinrich der Stolze', ['Welf VI.', 'Lothar III.', 'Konrad III.']],
          ['Aus welcher Familie stammte Barbarossas Mutter Judith?', 'Aus der Familie der Welfen', ['Aus der Familie der Salier', 'Aus der Familie der Babenberger', 'Aus der Familie der Zähringer']],
          ['Wann ließ Barbarossa Mailand zerstören?', '1162', ['1158', '1176', '1183']],
          ['Wann schloss Barbarossa Frieden mit den lombardischen Städten?', '1183 in Konstanz', ['1177 in Venedig', '1158 in Roncaglia', '1190 in Mainz']],
          ['Wann heiratete Heinrich VI. Konstanze von Sizilien?', '1186', ['1176', '1194', '1197']],
        ],
      },
    },
    {
      id: 'friedrich-ii',
      title: 'Friedrich II. und das Ende der Staufer',
      date: '1194–1268',
      text: [
        'Friedrich II. wurde am 26. Dezember 1194 in Jesi bei Ancona geboren – der Überlieferung nach in einem Zelt auf dem Marktplatz, damit niemand an seiner Herkunft zweifeln konnte. Er war ein Enkel Barbarossas; seine Mutter war Konstanze von Sizilien. Früh verlor er beide Eltern, und Papst Innozenz III. wurde sein Vormund. Er wuchs in Palermo auf Sizilien auf, wo sich lateinische, griechische und arabische Kultur mischten.',
        'In Deutschland stritten nach dem Tod Heinrichs VI. ab 1198 zwei Könige um die Krone: der Staufer Philipp von Schwaben und der Welfe Otto IV. Philipp wurde 1208 in Bamberg vom Pfalzgrafen Otto von Wittelsbach ermordet. Otto IV. verlor 1214 die Schlacht von Bouvines gegen Frankreich. Inzwischen war der junge Friedrich, das „Kind von Apulien“, 1212 nach Deutschland gekommen und zum König gewählt worden; 1215 wurde er in Aachen gekrönt, 1220 in Rom zum Kaiser.',
        'Friedrich lebte meist in Italien. Um in Deutschland Ruhe zu haben, überließ er den Fürsten wichtige Rechte: 1220 den geistlichen Fürsten (Confoederatio cum principibus ecclesiasticis), 1231/32 allen Fürsten (Statutum in favorem principum). So wurden die Landesherren immer mächtiger. Sein Sohn Heinrich (VII.), der in Deutschland regierte, rebellierte gegen ihn, wurde 1235 abgesetzt und starb 1242 in Gefangenschaft. Im selben Jahr 1235 erließ Friedrich den Mainzer Landfrieden, das erste Reichsgesetz, das auch in deutscher Sprache verkündet wurde.',
        'Friedrich galt als einer der gebildetsten Herrscher seiner Zeit. Man nannte ihn „Stupor mundi“, das Staunen der Welt. 1224 gründete er die Universität Neapel, die erste staatliche Universität Europas. 1231 erließ er für Sizilien die Konstitutionen von Melfi, ein großes Gesetzbuch. Er schrieb selbst ein Buch über die Falkenjagd, „De arte venandi cum avibus“, an seinem Hof entstand die Sizilianische Dichterschule, und seine Leibwache bestand aus Sarazenen aus Lucera. In Apulien ließ er das achteckige Castel del Monte bauen.',
        'Mit den Päpsten lag Friedrich fast ständig im Streit. Weil er einen versprochenen Kreuzzug aufgeschoben hatte, bannte ihn Papst Gregor IX. 1227. Trotzdem brach er 1228 auf – als Gebannter. Ohne Schlacht handelte er mit Sultan al-Kamil von Ägypten einen Vertrag für zehn Jahre aus, der den Christen Jerusalem zurückgab, und krönte sich 1229 dort selbst zum König von Jerusalem. Sein Berater war Hermann von Salza, der Hochmeister des Deutschen Ordens.',
        '1245 erklärte Papst Innozenz IV. Friedrich auf dem Konzil von Lyon für abgesetzt. In Deutschland wurden Gegenkönige gewählt: 1246 Heinrich Raspe, 1247 Wilhelm von Holland. Friedrich starb am 13. Dezember 1250 in Castel Fiorentino in Apulien und wurde im Dom von Palermo begraben.',
        'Danach brach die Macht der Staufer zusammen. Sein Sohn Konrad IV. starb 1254, sein Sohn Manfred fiel 1266 bei Benevent gegen Karl von Anjou, dem der Papst Sizilien gegeben hatte. Der letzte Staufer, der 16-jährige Konradin, wurde 1268 bei Tagliacozzo besiegt und auf Befehl Karls von Anjou in Neapel enthauptet. In Deutschland folgte die „kaiserlose, schreckliche Zeit“, das Interregnum, bis 1273 Rudolf von Habsburg zum König gewählt wurde.',
      ],
      quiz: {
        leicht: [
          ['Welcher Staufer wurde „Staunen der Welt“ genannt?', 'Friedrich II.', ['Friedrich Barbarossa', 'Konrad III.', 'Heinrich VI.']],
          ['Wessen Enkel war Friedrich II.?', 'Barbarossas', ['Heinrichs des Löwen', 'Ottos des Großen', 'Karls des Großen']],
          ['Auf welcher Insel wuchs Friedrich II. auf?', 'Sizilien', ['Sardinien', 'Korsika', 'Zypern']],
          ['In welcher Stadt wuchs Friedrich II. auf?', 'Palermo', ['Rom', 'Neapel', 'Venedig']],
          ['Wie bekam Friedrich II. Jerusalem?', 'Durch Verhandlungen', ['Durch eine große Schlacht', 'Durch Heirat', 'Durch Kauf von den Venezianern']],
          ['Mit wem verhandelte Friedrich II. über Jerusalem?', 'Mit dem Sultan von Ägypten', ['Mit dem Kaiser von Byzanz', 'Mit dem Papst', 'Mit dem König von Frankreich']],
          ['Worüber schrieb Friedrich II. ein Buch?', 'Über die Jagd mit Falken', ['Über die Seefahrt', 'Über den Weinbau', 'Über Sterne']],
          ['Welche Universität gründete Friedrich II. 1224?', 'Neapel', ['Bologna', 'Paris', 'Heidelberg']],
          ['In welchem Jahr starb Friedrich II.?', '1250', ['1190', '1268', '1273']],
          ['Wo ist Friedrich II. begraben?', 'Im Dom von Palermo', ['Im Speyerer Dom', 'In Jerusalem', 'Im Petersdom']],
          ['Wie stand das Papsttum zu Friedrich II.?', 'Die Päpste bannten ihn mehrfach', ['Sie verehrten ihn als Heiligen', 'Sie machten ihn zum Papst', 'Sie wählten ihn zum Kardinal']],
          ['Welche achteckige Burg ließ Friedrich II. in Apulien bauen?', 'Castel del Monte', ['Castel Sant’Angelo', 'Neuschwanstein', 'Burg Hohenzollern']],
          ['Wie hieß der letzte Staufer?', 'Konradin', ['Konrad III.', 'Manfred', 'Heinrich VII.']],
          ['Was geschah mit Konradin?', 'Er wurde in Neapel enthauptet', ['Er wurde Kaiser', 'Er ging ins Kloster', 'Er floh nach England']],
          ['In welchem Jahr starb Konradin?', '1268', ['1250', '1254', '1273']],
          ['Wie nennt man die königslose Zeit nach den Staufern?', 'Interregnum', ['Investiturstreit', 'Reformation', 'Restauration']],
          ['Wer wurde 1273 König und beendete das Interregnum?', 'Rudolf von Habsburg', ['Karl IV.', 'Heinrich der Löwe', 'Ludwig der Bayer']],
          ['Welches Reichsgesetz wurde 1235 auch auf Deutsch verkündet?', 'Der Mainzer Landfriede', ['Die Goldene Bulle', 'Das Wormser Konkordat', 'Der Sachsenspiegel']],
          ['In welchem Land wurde Friedrich II. geboren?', 'In Italien', ['In Deutschland', 'In Frankreich', 'In Spanien']],
          ['Wer wurde durch Friedrichs Gesetze in Deutschland stärker?', 'Die Fürsten', ['Die Bauern', 'Der Papst', 'Die Städte in Italien']],
        ],
        mittel: [
          ['An welchem Tag wurde Friedrich II. geboren?', '26. Dezember 1194', ['25. Dezember 1200', '1. Januar 1194', '13. Dezember 1250']],
          ['Wer war Friedrichs II. Mutter?', 'Konstanze von Sizilien', ['Beatrix von Burgund', 'Adelheid', 'Mathilde von Tuszien']],
          ['Welcher Papst war Friedrichs Vormund?', 'Innozenz III.', ['Gregor IX.', 'Innozenz IV.', 'Alexander III.']],
          ['Welche zwei Könige stritten ab 1198 um die Krone?', 'Philipp von Schwaben und Otto IV.', ['Konrad III. und Heinrich der Stolze', 'Friedrich II. und Heinrich (VII.)', 'Rudolf von Habsburg und Ottokar']],
          ['Was geschah 1208 mit Philipp von Schwaben?', 'Er wurde in Bamberg ermordet', ['Er starb auf einem Kreuzzug', 'Er wurde Kaiser', 'Er ging nach England']],
          ['Welche Schlacht verlor Otto IV. 1214?', 'Bouvines', ['Legnano', 'Benevent', 'Tagliacozzo']],
          ['Wann wurde Friedrich II. Kaiser?', '1220', ['1212', '1215', '1229']],
          ['Welches Gesetzbuch erließ Friedrich 1231 für Sizilien?', 'Die Konstitutionen von Melfi', ['Den Sachsenspiegel', 'Die Goldene Bulle', 'Den Mainzer Landfrieden']],
          ['Wann brach Friedrich zum Kreuzzug auf?', '1228', ['1189', '1215', '1245']],
          ['Was war am Kreuzzug Friedrichs II. unerhört?', 'Er war dabei vom Papst gebannt', ['Er nahm keine Soldaten mit', 'Er zog nach Spanien', 'Er wurde dabei Muslim']],
          ['Welcher Sohn Friedrichs rebellierte gegen ihn?', 'Heinrich (VII.)', ['Konrad IV.', 'Manfred', 'Enzio']],
          ['Wann erließ Friedrich den Mainzer Landfrieden?', '1235', ['1220', '1250', '1212']],
          ['Welches Gesetz von 1220 stärkte die geistlichen Fürsten?', 'Confoederatio cum principibus ecclesiasticis', ['Statutum in favorem principum', 'Constitutio de feudis', 'Privilegium minus']],
          ['Welches Gesetz von 1231/32 stärkte alle Fürsten?', 'Statutum in favorem principum', ['Confoederatio cum principibus ecclesiasticis', 'Dictatus Papae', 'Goldene Bulle']],
          ['Auf welchem Konzil wurde Friedrich 1245 abgesetzt?', 'Auf dem Konzil von Lyon', ['Auf dem Konzil von Konstanz', 'Auf dem Laterankonzil', 'Auf dem Konzil von Trient']],
          ['Welcher Papst setzte Friedrich 1245 ab?', 'Innozenz IV.', ['Innozenz III.', 'Gregor IX.', 'Honorius III.']],
          ['Was bedeutet „Stupor mundi“?', 'Staunen der Welt', ['Herr der Welt', 'Licht der Welt', 'Schrecken der Welt']],
          ['Welchen Spitznamen trug der junge Friedrich?', 'Kind von Apulien', ['Löwe von Sizilien', 'Sohn der Wölfin', 'Rotbart der Jüngere']],
          ['Wer ließ Konradin hinrichten?', 'Karl von Anjou', ['Rudolf von Habsburg', 'Papst Innozenz IV.', 'Wilhelm von Holland']],
          ['Wann starb Konrad IV.?', '1254', ['1250', '1268', '1242']],
        ],
        schwer: [
          ['Wo starb Friedrich II.?', 'In Castel Fiorentino', ['In Palermo', 'In Castel del Monte', 'In Jerusalem']],
          ['An welchem Tag starb Friedrich II.?', '13. Dezember 1250', ['26. Dezember 1250', '10. Juni 1250', '29. Oktober 1268']],
          ['Wann wurde Friedrich II. erstmals zum deutschen König gewählt?', '1212', ['1198', '1220', '1208']],
          ['Wo wurde Friedrich II. 1215 gekrönt?', 'In Aachen', ['In Frankfurt', 'In Mainz', 'In Rom']],
          ['Wer ermordete Philipp von Schwaben?', 'Pfalzgraf Otto von Wittelsbach', ['Otto IV.', 'Heinrich der Löwe', 'Karl von Anjou']],
          ['Welcher Hochmeister des Deutschen Ordens beriet Friedrich II.?', 'Hermann von Salza', ['Winrich von Kniprode', 'Ulrich von Jungingen', 'Albrecht von Brandenburg']],
          ['Wie heißt Friedrichs Buch über die Falkenjagd auf Lateinisch?', 'De arte venandi cum avibus', ['De bello Gallico', 'Speculum Saxonum', 'De civitate Dei']],
          ['Wann krönte sich Friedrich in Jerusalem zum König?', '1229', ['1228', '1220', '1244']],
          ['Wo genau soll Friedrich II. geboren worden sein?', 'In einem Zelt auf dem Marktplatz von Jesi', ['Im Palast von Palermo', 'In der Burg Hohenstaufen', 'In einem Kloster bei Rom']],
          ['Wann starb Friedrichs Sohn Heinrich (VII.)?', '1242', ['1235', '1250', '1254']],
          ['Für wie lange galt Friedrichs Vertrag mit Sultan al-Kamil?', 'Zehn Jahre', ['Ein Jahr', 'Hundert Jahre', 'Für immer']],
          ['Woher stammte Friedrichs Leibwache?', 'Es waren Sarazenen aus Lucera', ['Es waren Wikinger aus Norwegen', 'Es waren Schweizer Söldner', 'Es waren Ritter des Templerordens']],
          ['Welcher Papst bannte Friedrich 1227?', 'Gregor IX.', ['Innozenz IV.', 'Innozenz III.', 'Honorius III.']],
          ['Wie alt war Konradin bei seiner Hinrichtung?', '16 Jahre', ['10 Jahre', '25 Jahre', '30 Jahre']],
          ['Wo wurde Konradin 1268 besiegt?', 'Bei Tagliacozzo', ['Bei Benevent', 'Bei Legnano', 'Bei Bouvines']],
          ['Welcher Sohn Friedrichs fiel 1266 bei Benevent?', 'Manfred', ['Konrad IV.', 'Enzio', 'Heinrich (VII.)']],
          ['Wann begann das Interregnum?', '1250/1254', ['1197', '1268', '1273']],
          ['Welcher Gegenkönig wurde 1246 gegen Friedrich gewählt?', 'Heinrich Raspe', ['Wilhelm von Holland', 'Richard von Cornwall', 'Otto IV.']],
          ['Welcher Gegenkönig wurde 1247 gewählt?', 'Wilhelm von Holland', ['Heinrich Raspe', 'Alfons von Kastilien', 'Ottokar von Böhmen']],
          ['Welche Dichterschule entstand an Friedrichs Hof?', 'Die Sizilianische Dichterschule', ['Die Schule von Chartres', 'Der Göttinger Hainbund', 'Die Meistersinger von Nürnberg']],
        ],
      },
    },
  ],
};
