import type { HistEvent } from '../types';

export const REFORMATION: HistEvent = {
  id: 'reformation',
  title: 'Die Reformation',
  date: '1517–1555',
  text: [
    'Mit den 95 Thesen Martin Luthers begann 1517 eine Bewegung, die die abendländische Kirche spaltete. Sie veränderte Glauben, Sprache und Politik in Deutschland, löste den Bauernkrieg aus und endete vorläufig im Augsburger Religionsfrieden.',
  ],
  subtopics: [
    {
      id: 'luther',
      title: 'Martin Luther: Thesen, Worms und Wartburg',
      date: '1483–1522',
      text: [
        'Martin Luther wurde am 10. November 1483 in Eisleben geboren; sein Vater arbeitete im Kupferbergbau. In Erfurt studierte er zunächst Jura. Am 2. Juli 1505 geriet er bei Stotternheim in ein schweres Gewitter und gelobte: „Hilf du, heilige Anna, ich will ein Mönch werden!“ Kurz darauf trat er in das Kloster der Augustiner-Eremiten in Erfurt ein. Ab 1512 lehrte er als Doktor der Theologie an der Universität Wittenberg.',
        'Luther quälte die Frage, wie der Mensch vor Gott bestehen könne. Beim Lesen der Bibel – später sprach man vom „Turmerlebnis“ – erkannte er, dass der Mensch nicht durch gute Werke, sondern allein durch Gottes Gnade (sola gratia) und durch den Glauben (sola fide) gerettet werde; Maßstab sei allein die Heilige Schrift (sola scriptura).',
        'Zur selben Zeit verkaufte die Kirche Ablassbriefe, die Sündenstrafen im Fegefeuer verkürzen sollten. Das Geld floss in den Neubau des Petersdoms in Rom und an Albrecht von Brandenburg, Erzbischof von Mainz und Magdeburg, der damit seine Schulden bei den Fuggern bezahlte. Der Dominikaner Johann Tetzel warb angeblich mit dem Spruch: „Sobald das Geld im Kasten klingt, die Seele aus dem Fegefeuer springt.“ Am 31. Oktober 1517 schickte Luther 95 lateinische Thesen gegen den Ablass an Albrecht. Ob er sie auch an die Tür der Wittenberger Schlosskirche schlug, ist umstritten. Der 31. Oktober wird als Reformationstag gefeiert. Dank des Buchdrucks verbreiteten sich die Thesen in wenigen Wochen in ganz Deutschland.',
        '1518 wurde Luther in Augsburg von Kardinal Cajetan verhört, widerrief aber nicht. 1519 stritt er in der Leipziger Disputation mit dem Theologen Johannes Eck und erklärte, auch Konzilien könnten irren – sogar Jan Hus habe manches richtig gesagt. 1520 erschienen seine drei großen Schriften: „An den christlichen Adel deutscher Nation“, „Von der babylonischen Gefangenschaft der Kirche“ und „Von der Freiheit eines Christenmenschen“. Der Papst drohte ihm mit der Bulle „Exsurge Domine“ den Bann an; Luther verbrannte sie am 10. Dezember 1520 öffentlich vor dem Elstertor in Wittenberg. Im Januar 1521 wurde er gebannt.',
        'Im April 1521 musste Luther vor dem jungen Kaiser Karl V. auf dem Reichstag zu Worms erscheinen. Er weigerte sich zu widerrufen, solange man ihn nicht aus der Bibel widerlege. Der berühmte Satz „Hier stehe ich, ich kann nicht anders“ ist wohl später hinzugefügt worden; überliefert ist „Gott helfe mir, Amen“. Im Wormser Edikt verhängte der Kaiser die Reichsacht über ihn: Jeder durfte ihn töten, seine Schriften wurden verboten.',
        'Sein Landesherr, Kurfürst Friedrich der Weise von Sachsen, ließ ihn auf dem Heimweg zum Schein überfallen und auf die Wartburg bei Eisenach bringen. Dort lebte Luther als „Junker Jörg“ und übersetzte in nur rund elf Wochen das Neue Testament aus dem Griechischen ins Deutsche. Im September 1522 erschien es als „Septembertestament“; die ganze Bibel folgte 1534. Luthers Bibel prägte die deutsche Schriftsprache bis heute. Viele Redewendungen stammen von ihm, etwa „ein Buch mit sieben Siegeln“ oder „sein Licht unter den Scheffel stellen“.',
        '1525 heiratete Luther die ehemalige Nonne Katharina von Bora; sie bekamen sechs Kinder. Er dichtete Kirchenlieder wie „Ein feste Burg ist unser Gott“. Sein wichtigster Mitstreiter war der Gelehrte Philipp Melanchthon. Andere Reformatoren gingen eigene Wege: Ulrich Zwingli in Zürich und Johannes Calvin in Genf. Luther starb am 18. Februar 1546 in seiner Geburtsstadt Eisleben und ist in der Wittenberger Schlosskirche begraben.',
      ],
      quiz: {
        leicht: [
          ['Wer veröffentlichte 1517 die 95 Thesen?', 'Martin Luther', ['Johann Tetzel', 'Thomas Müntzer', 'Karl V.']],
          ['In welchem Jahr veröffentlichte Luther seine Thesen?', '1517', ['1415', '1555', '1618']],
          ['Wie viele Thesen veröffentlichte Luther?', '95', ['10', '42', '100']],
          ['Wogegen richteten sich Luthers Thesen?', 'Gegen den Ablasshandel', ['Gegen den Kaiser', 'Gegen die Juden', 'Gegen die Bauern']],
          ['An welchem Tag wird der Reformationstag gefeiert?', '31. Oktober', ['1. November', '24. Dezember', '6. Januar']],
          ['In welcher Stadt lehrte Luther an der Universität?', 'Wittenberg', ['Erfurt', 'Leipzig', 'Worms']],
          ['In welcher Stadt wurde Luther geboren?', 'Eisleben', ['Wittenberg', 'Eisenach', 'Erfurt']],
          ['Was wurde Luther, nachdem er in ein Gewitter geraten war?', 'Mönch', ['Ritter', 'Kaufmann', 'Bischof']],
          ['Welche Heilige rief Luther im Gewitter an?', 'Die heilige Anna', ['Die heilige Elisabeth', 'Die heilige Barbara', 'Maria Magdalena']],
          ['Auf welchem Reichstag musste Luther 1521 erscheinen?', 'In Worms', ['In Augsburg', 'In Speyer', 'In Regensburg']],
          ['Vor welchem Kaiser stand Luther 1521?', 'Karl V.', ['Maximilian I.', 'Friedrich III.', 'Ferdinand I.']],
          ['Auf welcher Burg versteckte sich Luther?', 'Auf der Wartburg', ['Auf der Burg Hohenzollern', 'Auf der Veste Coburg', 'Auf dem Trifels']],
          ['Welchen Decknamen trug Luther auf der Wartburg?', 'Junker Jörg', ['Ritter Kunz', 'Bruder Martin', 'Herr Hans']],
          ['Was übersetzte Luther auf der Wartburg?', 'Das Neue Testament', ['Die Odyssee', 'Den Koran', 'Das Nibelungenlied']],
          ['Welche Sprache prägte Luthers Bibelübersetzung stark?', 'Die deutsche Schriftsprache', ['Die englische Sprache', 'Das Latein', 'Das Französische']],
          ['Wen heiratete Luther 1525?', 'Katharina von Bora', ['Katharina von Aragon', 'Anna Boleyn', 'Elisabeth von Thüringen']],
          ['Was war Katharina von Bora vorher?', 'Eine Nonne', ['Eine Fürstin', 'Eine Bäuerin', 'Eine Ärztin']],
          ['Welches berühmte Kirchenlied dichtete Luther?', '„Ein feste Burg ist unser Gott“', ['„Stille Nacht“', '„Großer Gott, wir loben dich“', '„O Tannenbaum“']],
          ['Welcher Erfindung verdankte die Reformation ihre schnelle Verbreitung?', 'Dem Buchdruck', ['Der Eisenbahn', 'Dem Fernrohr', 'Der Dampfmaschine']],
          ['Was versprach ein Ablassbrief?', 'Kürzere Strafen im Fegefeuer', ['Ewiges Leben auf Erden', 'Steuerfreiheit', 'Einen Adelstitel']],
        ],
        mittel: [
          ['Wann wurde Luther geboren?', '10. November 1483', ['31. Oktober 1483', '18. Februar 1483', '1. Januar 1500']],
          ['Was studierte Luther zuerst in Erfurt?', 'Jura', ['Medizin', 'Theologie', 'Mathematik']],
          ['Bei welchem Ort geriet Luther 1505 ins Gewitter?', 'Stotternheim', ['Wittenberg', 'Eisleben', 'Worms']],
          ['In welchen Orden trat Luther ein?', 'Die Augustiner-Eremiten', ['Die Dominikaner', 'Die Franziskaner', 'Die Jesuiten']],
          ['Wofür sammelte der Ablasshandel unter anderem Geld?', 'Für den Neubau des Petersdoms', ['Für einen Kreuzzug nach Amerika', 'Für die Universität Wittenberg', 'Für den Kölner Dom']],
          ['Welcher Erzbischof erhielt Luthers Thesen?', 'Albrecht von Brandenburg', ['Friedrich der Weise', 'Kardinal Cajetan', 'Johannes Eck']],
          ['Welcher Ablassprediger ist durch einen Spruch berühmt?', 'Johann Tetzel', ['Johannes Eck', 'Philipp Melanchthon', 'Thomas Müntzer']],
          ['Wie lautet der Ablassspruch?', '„Sobald das Geld im Kasten klingt, die Seele aus dem Fegefeuer springt“', ['„Hier stehe ich, ich kann nicht anders“', '„Gott will es“', '„Ora et labora“']],
          ['In welcher Sprache verfasste Luther die 95 Thesen?', 'Latein', ['Deutsch', 'Griechisch', 'Hebräisch']],
          ['Mit wem stritt Luther 1519 in Leipzig?', 'Mit Johannes Eck', ['Mit Johann Tetzel', 'Mit Erasmus', 'Mit Zwingli']],
          ['Welcher Kardinal verhörte Luther 1518 in Augsburg?', 'Cajetan', ['Albrecht', 'Richelieu', 'Wolsey']],
          ['Wie heißt die Bannandrohungsbulle gegen Luther?', '„Exsurge Domine“', ['„Unam Sanctam“', '„Dictatus Papae“', '„Rerum Novarum“']],
          ['Was tat Luther im Dezember 1520 mit dieser Bulle?', 'Er verbrannte sie öffentlich', ['Er unterschrieb sie', 'Er schickte sie zurück', 'Er versteckte sie']],
          ['Welche Strafe verhängte das Wormser Edikt über Luther?', 'Die Reichsacht', ['Die Todesstrafe durch das Schwert', 'Eine Geldstrafe', 'Die Verbannung nach Rom']],
          ['Welcher Kurfürst schützte Luther?', 'Friedrich der Weise von Sachsen', ['Joachim von Brandenburg', 'Albrecht von Mainz', 'Ludwig von der Pfalz']],
          ['Wie lange brauchte Luther für die Übersetzung des Neuen Testaments?', 'Rund elf Wochen', ['Rund elf Jahre', 'Rund elf Tage', 'Rund elf Monate']],
          ['Wann erschien das „Septembertestament“?', '1522', ['1517', '1521', '1534']],
          ['Wann erschien Luthers vollständige Bibel?', '1534', ['1522', '1546', '1517']],
          ['Wer war Luthers wichtigster Mitstreiter?', 'Philipp Melanchthon', ['Johannes Calvin', 'Ulrich Zwingli', 'Thomas Müntzer']],
          ['Wann starb Luther?', '1546', ['1525', '1555', '1534']],
        ],
        schwer: [
          ['An welchem Tag geriet Luther ins Gewitter bei Stotternheim?', '2. Juli 1505', ['31. Oktober 1505', '10. November 1505', '18. Februar 1505']],
          ['Seit wann lehrte Luther als Doktor der Theologie in Wittenberg?', '1512', ['1505', '1517', '1521']],
          ['Wie nennt man Luthers Erkenntnis über Gottes Gnade?', 'Turmerlebnis', ['Damaskuserlebnis', 'Gewittererlebnis', 'Wartburgerlebnis']],
          ['Was bedeutet „sola fide“?', 'Allein durch den Glauben', ['Allein durch die Werke', 'Allein durch die Schrift', 'Allein durch den Papst']],
          ['Was bedeutet „sola scriptura“?', 'Allein die Schrift', ['Allein die Gnade', 'Allein der Glaube', 'Allein Christus']],
          ['Bei wem hatte Albrecht von Brandenburg Schulden?', 'Bei den Fuggern', ['Bei den Medici', 'Bei den Welsern', 'Beim Papst']],
          ['Welche These vertrat Luther 1519 in Leipzig über Konzilien?', 'Auch Konzilien können irren', ['Nur Konzilien sind unfehlbar', 'Konzilien wählen den Kaiser', 'Konzilien sind abzuschaffen']],
          ['Welche Schrift Luthers von 1520 richtet sich an die Fürsten?', '„An den christlichen Adel deutscher Nation“', ['„Von der Freiheit eines Christenmenschen“', '„Von der babylonischen Gefangenschaft der Kirche“', '„Wider die räuberischen Rotten der Bauern“']],
          ['Vor welchem Tor in Wittenberg verbrannte Luther die Bulle?', 'Vor dem Elstertor', ['Vor dem Brandenburger Tor', 'Vor der Schlosskirche', 'Vor dem Rathaus']],
          ['An welchem Tag verbrannte Luther die Bulle?', '10. Dezember 1520', ['31. Oktober 1517', '18. April 1521', '25. Juni 1530']],
          ['Welche Worte Luthers in Worms sind sicher überliefert?', '„Gott helfe mir, Amen“', ['„Hier stehe ich, ich kann nicht anders“', '„Ich widerrufe“', '„Es lebe der Kaiser“']],
          ['In welchem Monat 1521 stand Luther in Worms vor dem Kaiser?', 'April', ['Januar', 'Oktober', 'Dezember']],
          ['Aus welcher Sprache übersetzte Luther das Neue Testament?', 'Aus dem Griechischen', ['Aus dem Lateinischen', 'Aus dem Hebräischen', 'Aus dem Aramäischen']],
          ['Welche Redewendung stammt von Luther?', '„Ein Buch mit sieben Siegeln“', ['„Alea iacta est“', '„Der Apfel fällt nicht weit vom Stamm“', '„Zeit ist Geld“']],
          ['Wie viele Kinder hatten Luther und Katharina von Bora?', 'Sechs', ['Zwei', 'Zehn', 'Keine']],
          ['In welcher Stadt wirkte der Reformator Zwingli?', 'Zürich', ['Genf', 'Basel', 'Straßburg']],
          ['In welcher Stadt wirkte Johannes Calvin?', 'Genf', ['Zürich', 'Paris', 'Bern']],
          ['Wo ist Luther begraben?', 'In der Schlosskirche Wittenberg', ['In Eisleben', 'Auf der Wartburg', 'Im Erfurter Dom']],
          ['Wo starb Luther?', 'In Eisleben', ['In Wittenberg', 'In Eisenach', 'In Worms']],
          ['Welchem Orden gehörte der Ablassprediger Tetzel an?', 'Den Dominikanern', ['Den Augustinern', 'Den Franziskanern', 'Den Jesuiten']],
        ],
      },
    },
    {
      id: 'bauernkrieg',
      title: 'Der Bauernkrieg und die Täufer',
      date: '1524–1535',
      text: [
        'Die Lage vieler Bauern hatte sich um 1500 verschlechtert: Grundherren verlangten höhere Abgaben und mehr Frondienste, schränkten die Nutzung von Wald, Wasser und Weiden ein und machten Bauern zu Leibeigenen. Schon vorher hatte es Aufstände gegeben, etwa den „Bundschuh“ ab 1493 im Elsass und am Oberrhein – benannt nach dem geschnürten Bauernschuh als Zeichen – mit dem Anführer Joß Fritz, und 1514 den „Armen Konrad“ in Württemberg. Ein alter Spruch fragte: „Als Adam grub und Eva spann, wer war da der Edelmann?“',
        'Luthers Lehre von der „Freiheit eines Christenmenschen“ verstanden viele Bauern auch als Freiheit von ungerechter Herrschaft. 1524 begannen Unruhen im Südschwarzwald, 1525 erfassten sie große Teile Süd- und Mitteldeutschlands. Im März 1525 verfassten der Kürschner Sebastian Lotzer und der Prediger Christoph Schappeler in Memmingen die „Zwölf Artikel“. Die Bauern forderten unter anderem, ihre Pfarrer selbst zu wählen, die Abschaffung der Leibeigenschaft, das Recht auf Jagd und Fischfang, weniger Frondienste und einen gerechteren Zehnt – alles mit der Bibel begründet. Die Zwölf Artikel gelten als eine der ersten Erklärungen von Freiheitsrechten in Europa.',
        'Die Bauern sammelten sich in „Haufen“. Den Odenwälder Haufen führte zeitweise der Reichsritter Götz von Berlichingen, bekannt durch seine eiserne Handprothese; Florian Geyer führte den „Schwarzen Haufen“. Zu Ostern 1525 töteten Bauern in Weinsberg Graf Ludwig von Helfenstein und seine Begleiter, indem sie sie durch die Spieße laufen ließen (Weinsberger Bluttat).',
        'In Thüringen predigte Thomas Müntzer, ein radikaler Theologe, dass die Gottlosen mit dem Schwert vernichtet werden müssten. Er wirkte in Mühlhausen. Am 15. Mai 1525 wurde sein Bauernheer in der Schlacht bei Frankenhausen von den Fürsten vernichtet; Müntzer wurde gefangen, gefoltert und am 27. Mai 1525 hingerichtet. Im Süden schlug das Heer des Schwäbischen Bundes unter Georg Truchsess von Waldburg, genannt „Bauernjörg“, die Aufständischen, etwa im Mai 1525 bei Böblingen.',
        'Luther stellte sich scharf gegen die Aufständischen. In seiner Schrift „Wider die räuberischen und mörderischen Rotten der Bauern“ forderte er die Fürsten auf, sie niederzuschlagen. Insgesamt kamen im Bauernkrieg etwa 70.000 bis 75.000 Bauern ums Leben. Die Lage der Bauern blieb hart, und die Landesfürsten gingen gestärkt aus dem Krieg hervor. In Bad Frankenhausen erinnert das Panoramagemälde von Werner Tübke an den Bauernkrieg.',
        'Eine weitere radikale Bewegung waren die Täufer. Sie lehnten die Kindertaufe ab und tauften nur Erwachsene, die sich bewusst zum Glauben bekannten. Sie wurden von Katholiken und Lutheranern gleichermaßen verfolgt. 1534/35 errichteten Täufer in Münster ein „Königreich Zion“ unter Jan van Leiden. Nach der Eroberung der Stadt wurden die Anführer hingerichtet und ihre Leichen in drei eisernen Käfigen am Turm der Lambertikirche aufgehängt – die Käfige hängen dort bis heute.',
      ],
      quiz: {
        leicht: [
          ['In welchem Jahr erreichte der Bauernkrieg seinen Höhepunkt?', '1525', ['1517', '1555', '1618']],
          ['Wogegen wehrten sich die Bauern?', 'Gegen hohe Abgaben und Leibeigenschaft', ['Gegen die Erfindung des Buchdrucks', 'Gegen die Türken', 'Gegen die Reformation']],
          ['Wie heißen die Forderungen der Bauern von 1525?', 'Die Zwölf Artikel', ['Die 95 Thesen', 'Die Zehn Gebote', 'Die Goldene Bulle']],
          ['In welcher Stadt entstanden die Zwölf Artikel?', 'Memmingen', ['Wittenberg', 'Worms', 'Augsburg']],
          ['Welcher radikale Prediger führte Bauern in Thüringen an?', 'Thomas Müntzer', ['Martin Luther', 'Philipp Melanchthon', 'Johann Tetzel']],
          ['Wie endete der Bauernkrieg?', 'Mit einer Niederlage der Bauern', ['Mit einem Sieg der Bauern', 'Mit der Abschaffung des Adels', 'Mit einer Bauernrepublik']],
          ['Wie stellte sich Luther zum Bauernaufstand?', 'Er verurteilte ihn scharf', ['Er führte ihn an', 'Er schwieg', 'Er floh ins Ausland']],
          ['Welcher Ritter mit eiserner Hand führte zeitweise Bauern an?', 'Götz von Berlichingen', ['Franz von Sickingen', 'Florian Geyer', 'Ulrich von Hutten']],
          ['Was war der „Bundschuh“?', 'Ein Zeichen früherer Bauernaufstände', ['Ein Ritterorden', 'Eine Steuer', 'Ein Gesetz des Kaisers']],
          ['Wie nannte man die Gruppen der aufständischen Bauern?', 'Haufen', ['Kohorten', 'Regimenter', 'Zünfte']],
          ['Wo wurde Müntzers Bauernheer 1525 vernichtet?', 'Bei Frankenhausen', ['Bei Worms', 'Bei Mühlberg', 'Bei Lützen']],
          ['Was geschah mit Thomas Müntzer?', 'Er wurde hingerichtet', ['Er wurde Fürst', 'Er floh nach Amerika', 'Er wurde Papst']],
          ['Wer ging gestärkt aus dem Bauernkrieg hervor?', 'Die Landesfürsten', ['Die Bauern', 'Der Papst', 'Die Ritter']],
          ['Etwa wie viele Bauern starben im Bauernkrieg?', 'Rund 70.000 bis 75.000', ['Rund 700', 'Rund 7 Millionen', 'Niemand']],
          ['Was lehnten die Täufer ab?', 'Die Kindertaufe', ['Die Bibel', 'Das Gebet', 'Die Taufe überhaupt']],
          ['In welcher Stadt errichteten Täufer 1534 ein „Königreich“?', 'Münster', ['Köln', 'Mühlhausen', 'Zürich']],
          ['Was hängt bis heute am Turm der Lambertikirche in Münster?', 'Drei eiserne Käfige', ['Eine Glocke der Täufer', 'Ein Bauernschuh', 'Eine Fahne']],
          ['Wen wollten die Bauern laut den Zwölf Artikeln selbst wählen?', 'Ihren Pfarrer', ['Den Kaiser', 'Den Papst', 'Den Grundherrn']],
          ['Womit begründeten die Bauern ihre Forderungen?', 'Mit der Bibel', ['Mit dem römischen Recht', 'Mit der Goldenen Bulle', 'Mit Wissenschaft']],
          ['Wie lautet der alte Spruch gegen den Adel?', '„Als Adam grub und Eva spann, wer war da der Edelmann?“', ['„Wer nicht arbeitet, soll nicht essen“', '„Gott mit uns“', '„Ora et labora“']],
        ],
        mittel: [
          ['Wo begannen 1524 die ersten Unruhen?', 'Im Südschwarzwald', ['In Ostpreußen', 'In Holstein', 'In Tirol']],
          ['Wer verfasste die Zwölf Artikel?', 'Sebastian Lotzer und Christoph Schappeler', ['Martin Luther und Melanchthon', 'Thomas Müntzer und Heinrich Pfeiffer', 'Götz von Berlichingen und Florian Geyer']],
          ['Welchen Beruf hatte Sebastian Lotzer?', 'Kürschner', ['Bauer', 'Pfarrer', 'Ritter']],
          ['Wann entstanden die Zwölf Artikel?', 'Im März 1525', ['Im Oktober 1517', 'Im Mai 1525', 'Im Juni 1524']],
          ['Wofür gelten die Zwölf Artikel heute?', 'Als frühe Erklärung von Freiheitsrechten', ['Als erstes Kochbuch', 'Als erstes Gesetz des Kaisers', 'Als Glaubensbekenntnis der Katholiken']],
          ['Wann fand die Schlacht bei Frankenhausen statt?', '15. Mai 1525', ['31. Oktober 1517', '25. September 1555', '8. November 1620']],
          ['In welcher Stadt wirkte Thomas Müntzer zuletzt?', 'Mühlhausen', ['Memmingen', 'Wittenberg', 'Münster']],
          ['Wer führte das Heer des Schwäbischen Bundes?', 'Georg Truchsess von Waldburg', ['Götz von Berlichingen', 'Albrecht von Wallenstein', 'Franz von Sickingen']],
          ['Welchen Spitznamen hatte Georg Truchsess von Waldburg?', 'Bauernjörg', ['Bauernkönig', 'Eisenhand', 'Schwarzer Ritter']],
          ['Welcher Anführer führte den „Schwarzen Haufen“?', 'Florian Geyer', ['Götz von Berlichingen', 'Joß Fritz', 'Thomas Müntzer']],
          ['Was geschah Ostern 1525 in Weinsberg?', 'Bauern töteten einen Grafen und seine Begleiter', ['Luther predigte dort', 'Der Kaiser wurde gewählt', 'Ein Frieden wurde geschlossen']],
          ['Wie heißt Luthers Schrift gegen die aufständischen Bauern?', '„Wider die räuberischen und mörderischen Rotten der Bauern“', ['„Von der Freiheit eines Christenmenschen“', '„An den christlichen Adel“', '„Ein feste Burg“']],
          ['Wer führte den Bundschuh an?', 'Joß Fritz', ['Thomas Müntzer', 'Hans Böhm', 'Jan van Leiden']],
          ['Wo begann der Bundschuh 1493?', 'Im Elsass', ['In Thüringen', 'In Sachsen', 'In Westfalen']],
          ['Wie hieß der Aufstand von 1514 in Württemberg?', 'Armer Konrad', ['Bundschuh', 'Schwarzer Haufen', 'Pfeifer von Niklashausen']],
          ['Wer führte das Täuferreich in Münster an?', 'Jan van Leiden', ['Thomas Müntzer', 'Menno Simons', 'Jan Hus']],
          ['Wann bestand das Täuferreich in Münster?', '1534/35', ['1525', '1555', '1618']],
          ['Wer verfolgte die Täufer?', 'Katholiken und Lutheraner gleichermaßen', ['Nur Katholiken', 'Nur Lutheraner', 'Niemand']],
          ['Was forderten die Bauern unter anderem beim Wald?', 'Das Recht auf Jagd und Holz', ['Seine vollständige Rodung', 'Ein Verbot des Betretens', 'Den Verkauf an die Städte']],
          ['Was erinnert in Bad Frankenhausen an den Bauernkrieg?', 'Ein riesiges Panoramagemälde', ['Ein Bauerndenkmal aus Gold', 'Ein Bauernkriegsmuseum in einer Burg in Bayern', 'Eine Kopie der Wartburg']],
        ],
        schwer: [
          ['An welchem Tag wurde Thomas Müntzer hingerichtet?', '27. Mai 1525', ['15. Mai 1525', '31. Oktober 1525', '1. April 1525']],
          ['Wie hieß der Graf, der in Weinsberg getötet wurde?', 'Ludwig von Helfenstein', ['Georg von Waldburg', 'Albrecht von Mansfeld', 'Ulrich von Württemberg']],
          ['Wie wurden die Opfer in Weinsberg getötet?', 'Man ließ sie durch die Spieße laufen', ['Man verbrannte sie', 'Man ertränkte sie', 'Man vergiftete sie']],
          ['Welche Prothese machte Götz von Berlichingen berühmt?', 'Eine eiserne Hand', ['Ein Holzbein', 'Ein Glasauge', 'Ein Eisenkiefer']],
          ['Welchen Haufen führte Götz von Berlichingen?', 'Den Odenwälder Haufen', ['Den Schwarzen Haufen', 'Den Baltringer Haufen', 'Den Allgäuer Haufen']],
          ['Wo besiegte der Schwäbische Bund im Mai 1525 die Bauern?', 'Bei Böblingen', ['Bei Frankenhausen', 'Bei Memmingen', 'Bei Worms']],
          ['Welcher Maler schuf das Panorama in Bad Frankenhausen?', 'Werner Tübke', ['Albrecht Dürer', 'Lucas Cranach', 'Adolph Menzel']],
          ['Was war der Bundschuh ursprünglich?', 'Ein geschnürter Bauernschuh', ['Ein Ritterstiefel', 'Ein Kirchenschatz', 'Ein Zunftzeichen']],
          ['Welchen Beruf hatte Christoph Schappeler?', 'Prediger', ['Kürschner', 'Bauer', 'Ritter']],
          ['Was predigte Müntzer über die Gottlosen?', 'Sie müssten mit dem Schwert vernichtet werden', ['Man solle sie bekehren', 'Man solle für sie beten', 'Man solle sie ignorieren']],
          ['Wie nannten die Täufer ihr Reich in Münster?', '„Königreich Zion“', ['„Freies Westfalen“', '„Gottesstaat“', '„Freistaat Münster“']],
          ['Wie viele Käfige hängen an der Lambertikirche?', 'Drei', ['Einer', 'Fünf', 'Zwölf']],
          ['Wann begann der Bundschuh?', '1493', ['1514', '1524', '1476']],
          ['Wann war der Aufstand des Armen Konrad?', '1514', ['1493', '1525', '1534']],
          ['Welche Schrift Luthers verstanden viele Bauern als Aufruf zur Freiheit?', '„Von der Freiheit eines Christenmenschen“', ['„Wider die räuberischen Rotten“', '„Der kleine Katechismus“', '„Tischreden“']],
          ['Welcher Bund kämpfte im Süden gegen die Bauern?', 'Der Schwäbische Bund', ['Der Schmalkaldische Bund', 'Die Katholische Liga', 'Der Rheinbund']],
          ['Was forderten die Bauern beim Zehnt?', 'Einen gerechteren Zehnt', ['Den doppelten Zehnt', 'Einen Zehnt an den Kaiser', 'Gar nichts']],
          ['Wie hießen die Gegner der Kindertaufe auch abwertend?', 'Wiedertäufer', ['Bilderstürmer', 'Schwärmer', 'Ketzer von Böhmen']],
          ['In welcher Region verbreitete sich der Bauernkrieg kaum?', 'In Norddeutschland', ['In Franken', 'In Schwaben', 'In Thüringen']],
          ['Wo spielte sich der Bundschuh vor allem ab?', 'Im Elsass und am Oberrhein', ['In Holstein', 'In Pommern', 'In Böhmen']],
        ],
      },
    },
    {
      id: 'religionsfrieden',
      title: 'Karl V. und der Augsburger Religionsfrieden',
      date: '1519–1563',
      text: [
        'Karl V. wurde 1500 in Gent geboren. Als Enkel Kaiser Maximilians und der spanischen Könige Ferdinand und Isabella erbte er die Niederlande, Spanien mit seinen Gebieten in Amerika, Süditalien und die habsburgischen Länder. Man sagte, in seinem Reich gehe die Sonne nie unter. 1519 wurde er mit dem Geld der Fugger zum König gewählt, 1520 in Aachen gekrönt. 1530 krönte ihn der Papst in Bologna zum Kaiser – es war die letzte Kaiserkrönung durch einen Papst.',
        'Karl war ein überzeugter Katholik, doch er konnte die Reformation nicht aufhalten: Er führte immer wieder Krieg gegen den französischen König Franz I., und 1529 belagerten die Osmanen unter Sultan Süleyman dem Prächtigen sogar Wien. Dafür brauchte er die Hilfe der Reichsfürsten, auch der evangelischen.',
        '1529 beschloss der Reichstag zu Speyer, das Wormser Edikt wieder durchzusetzen. Die evangelischen Fürsten und Städte legten dagegen eine „Protestation“ ein – seitdem nennt man sie Protestanten. 1530 legten sie auf dem Reichstag zu Augsburg ihr Glaubensbekenntnis vor, die von Melanchthon verfasste „Confessio Augustana“ (Augsburger Bekenntnis). 1531 schlossen sie sich im Schmalkaldischen Bund zusammen, angeführt vom Kurfürsten von Sachsen und dem Landgrafen Philipp von Hessen.',
        'Im Schmalkaldischen Krieg 1546/47 besiegte Karl die Protestanten in der Schlacht bei Mühlberg an der Elbe; der Maler Tizian hielt ihn als siegreichen Reiter fest. Doch 1552 erhoben sich die Fürsten unter Moritz von Sachsen, der vorher auf Karls Seite gestanden hatte, gegen den Kaiser (Fürstenaufstand), und Karl musste fliehen.',
        'Am 25. September 1555 wurde der Augsburger Religionsfrieden geschlossen. Die Landesherren durften nun selbst entscheiden, ob ihr Land katholisch oder lutherisch war; die Untertanen mussten der Religion ihres Herrn folgen oder auswandern. Später fasste man das in der Formel „cuius regio, eius religio“ zusammen – wessen Land, dessen Religion. Die Calvinisten waren ausgeschlossen. Nach dem „geistlichen Vorbehalt“ sollte ein geistlicher Fürst, der evangelisch wurde, sein Amt verlieren. Karl V. war enttäuscht: 1556 dankte er ab, sein Bruder Ferdinand I. wurde Kaiser, sein Sohn Philipp II. König von Spanien. Karl starb 1558 im Kloster Yuste in Spanien.',
        'Die katholische Kirche erneuerte sich in der Gegenreformation. Auf dem Konzil von Trient (1545–1563) legte sie ihre Lehre fest und bekämpfte Missstände. Der 1540 vom Papst bestätigte Jesuitenorden des Ignatius von Loyola gründete Schulen und Universitäten; in Deutschland wirkte vor allem Petrus Canisius. So blieben oder wurden Bayern, Österreich und die geistlichen Fürstentümer katholisch, während der Norden und Osten überwiegend evangelisch wurde.',
      ],
      quiz: {
        leicht: [
          ['Welcher Kaiser regierte zur Zeit der Reformation?', 'Karl V.', ['Karl der Große', 'Maximilian I.', 'Friedrich III.']],
          ['Was sagte man über das Reich Karls V.?', 'Die Sonne geht darin nie unter', ['Es ist das kleinste Reich Europas', 'Es liegt ganz in Asien', 'Es hat keine Städte']],
          ['Welches große Land in Westeuropa gehörte zu Karls Erbe?', 'Spanien', ['Frankreich', 'England', 'Portugal']],
          ['Wie entstand der Name „Protestanten“?', 'Durch eine Protestation auf dem Reichstag 1529', ['Durch einen Protestmarsch nach Rom', 'Durch Luthers Thesen', 'Durch eine Schlacht']],
          ['In welchem Jahr wurde der Augsburger Religionsfrieden geschlossen?', '1555', ['1517', '1648', '1525']],
          ['Wer durfte nach 1555 die Religion eines Landes bestimmen?', 'Der Landesherr', ['Jeder Untertan selbst', 'Der Papst', 'Der Kaiser']],
          ['Was bedeutet „cuius regio, eius religio“?', 'Wessen Land, dessen Religion', ['Jeder nach seiner Façon', 'Ein Gott, ein Reich', 'Bete und arbeite']],
          ['Welche Konfession war 1555 ausgeschlossen?', 'Die Calvinisten', ['Die Lutheraner', 'Die Katholiken', 'Keine']],
          ['Was konnten Untertanen tun, die nicht die Religion ihres Herrn teilten?', 'Auswandern', ['Den Fürsten absetzen', 'Ihren eigenen Gott wählen', 'Nichts, sie mussten sterben']],
          ['Welche Stadt belagerten die Osmanen 1529?', 'Wien', ['Berlin', 'Rom', 'Prag']],
          ['Wie nennt man die Erneuerung der katholischen Kirche?', 'Gegenreformation', ['Aufklärung', 'Renaissance', 'Restauration']],
          ['Welcher Orden war für die Gegenreformation besonders wichtig?', 'Die Jesuiten', ['Die Templer', 'Die Zisterzienser', 'Der Deutsche Orden']],
          ['Wer gründete den Jesuitenorden?', 'Ignatius von Loyola', ['Franz von Assisi', 'Martin Luther', 'Petrus Canisius']],
          ['Welches Konzil legte die katholische Lehre neu fest?', 'Das Konzil von Trient', ['Das Konzil von Konstanz', 'Das Konzil von Nicäa', 'Das Zweite Vatikanische Konzil']],
          ['Was tat Karl V. 1556?', 'Er dankte ab', ['Er wurde evangelisch', 'Er eroberte Paris', 'Er wurde Papst']],
          ['Wo starb Karl V.?', 'In einem Kloster in Spanien', ['In Wien', 'In Aachen', 'In Rom']],
          ['Welche Teile Deutschlands blieben überwiegend katholisch?', 'Bayern und Österreich', ['Sachsen und Brandenburg', 'Holstein und Mecklenburg', 'Pommern und Preußen']],
          ['Gegen welchen König führte Karl V. immer wieder Krieg?', 'Den König von Frankreich', ['Den König von England', 'Den König von Polen', 'Den König von Schweden']],
          ['Wie hieß das Bündnis der protestantischen Fürsten ab 1531?', 'Schmalkaldischer Bund', ['Katholische Liga', 'Rheinbund', 'Hanse']],
          ['In welcher Stadt wurde Karl V. geboren?', 'Gent', ['Madrid', 'Wien', 'Brüssel']],
        ],
        mittel: [
          ['Wann wurde Karl V. geboren?', '1500', ['1483', '1519', '1459']],
          ['Wann wurde Karl V. zum König gewählt?', '1519', ['1500', '1530', '1555']],
          ['Wo wurde Karl V. 1530 vom Papst zum Kaiser gekrönt?', 'In Bologna', ['In Rom', 'In Aachen', 'In Madrid']],
          ['Was war besonders an der Krönung von 1530?', 'Es war die letzte Kaiserkrönung durch einen Papst', ['Es war die erste in Deutschland', 'Karl krönte sich selbst', 'Sie fand in Amerika statt']],
          ['Welcher Sultan belagerte 1529 Wien?', 'Süleyman der Prächtige', ['Mehmed II.', 'Selim I.', 'Osman I.']],
          ['Welcher französische König war Karls Gegner?', 'Franz I.', ['Ludwig XIV.', 'Heinrich IV.', 'Karl VIII.']],
          ['Auf welchem Reichstag protestierten die evangelischen Stände 1529?', 'In Speyer', ['In Worms', 'In Augsburg', 'In Regensburg']],
          ['Wie heißt das evangelische Bekenntnis von 1530?', 'Confessio Augustana', ['Confessio Helvetica', 'Heidelberger Katechismus', 'Konkordienformel']],
          ['Wer verfasste das Augsburger Bekenntnis?', 'Philipp Melanchthon', ['Martin Luther', 'Johannes Calvin', 'Ulrich Zwingli']],
          ['Welcher Landgraf führte den Schmalkaldischen Bund mit an?', 'Philipp von Hessen', ['Moritz von Sachsen', 'Albrecht von Brandenburg', 'Ulrich von Württemberg']],
          ['Wann fand der Schmalkaldische Krieg statt?', '1546/47', ['1525', '1552', '1618']],
          ['Wo besiegte Karl V. die Protestanten 1547?', 'Bei Mühlberg an der Elbe', ['Bei Frankenhausen', 'Bei Lützen', 'Bei Nördlingen']],
          ['Welcher Maler malte Karl V. als Sieger von Mühlberg?', 'Tizian', ['Dürer', 'Rubens', 'Cranach']],
          ['Welcher Fürst führte 1552 den Aufstand gegen Karl V. an?', 'Moritz von Sachsen', ['Philipp von Hessen', 'Friedrich der Weise', 'Johann Friedrich von Sachsen']],
          ['An welchem Tag wurde der Augsburger Religionsfrieden geschlossen?', '25. September 1555', ['31. Oktober 1555', '24. Oktober 1648', '15. Mai 1555']],
          ['Was regelte der „geistliche Vorbehalt“?', 'Ein evangelisch gewordener geistlicher Fürst verlor sein Amt', ['Geistliche durften heiraten', 'Bischöfe wählten den Kaiser', 'Klöster wurden aufgelöst']],
          ['Wer wurde nach Karl V. Kaiser?', 'Sein Bruder Ferdinand I.', ['Sein Sohn Philipp II.', 'Moritz von Sachsen', 'Maximilian II.']],
          ['Wer wurde nach Karl V. König von Spanien?', 'Philipp II.', ['Ferdinand I.', 'Karl VI.', 'Philipp der Schöne']],
          ['Wann tagte das Konzil von Trient?', '1545–1563', ['1414–1418', '1517–1521', '1600–1618']],
          ['Welcher Jesuit wirkte vor allem in Deutschland?', 'Petrus Canisius', ['Franz Xaver', 'Ignatius von Loyola', 'Friedrich Spee']],
        ],
        schwer: [
          ['Wer waren Karls V. spanische Großeltern?', 'Ferdinand und Isabella', ['Philipp und Johanna', 'Karl und Maria', 'Alfons und Kastilia']],
          ['Wann wurde Karl V. in Aachen gekrönt?', '1520', ['1519', '1530', '1500']],
          ['In welchem Kloster starb Karl V.?', 'Yuste', ['El Escorial', 'Montserrat', 'Santiago']],
          ['Wann starb Karl V.?', '1558', ['1556', '1555', '1564']],
          ['Wann wurde der Jesuitenorden vom Papst bestätigt?', '1540', ['1517', '1555', '1563']],
          ['Wann wurde der Schmalkaldische Bund gegründet?', '1531', ['1529', '1546', '1555']],
          ['Welcher Kurfürst führte den Schmalkaldischen Bund mit an?', 'Der Kurfürst von Sachsen', ['Der Kurfürst von Brandenburg', 'Der Kurfürst von der Pfalz', 'Der Erzbischof von Köln']],
          ['Auf wessen Seite stand Moritz von Sachsen zuerst?', 'Auf der Seite Karls V.', ['Auf der Seite der Bauern', 'Auf der Seite Frankreichs', 'Auf der Seite der Osmanen']],
          ['Wann fand der Fürstenaufstand gegen Karl V. statt?', '1552', ['1547', '1555', '1529']],
          ['Was beschloss der Reichstag zu Speyer 1529, wogegen protestiert wurde?', 'Das Wormser Edikt wieder durchzusetzen', ['Luther zum Papst zu machen', 'Die Bauern zu befreien', 'Einen Kreuzzug nach Amerika']],
          ['Wann wurde das Augsburger Bekenntnis vorgelegt?', '1530', ['1529', '1555', '1521']],
          ['Wer prägte die Formel „cuius regio, eius religio“?', 'Sie wurde erst später geprägt, nicht im Vertrag selbst', ['Martin Luther', 'Karl V.', 'Papst Paul III.']],
          ['Welche Länder erbte Karl V. von seiner Großmutter Maria von Burgund?', 'Die Niederlande', ['Spanien', 'Österreich', 'Neapel']],
          ['Welche Länder erbte Karl V. über seine Großmutter Isabella?', 'Kastilien mit den Gebieten in Amerika', ['Die Niederlande', 'Tirol', 'Böhmen']],
          ['Welche Länder blieben bei der Teilung 1556 bei Ferdinand I.?', 'Die österreichischen Länder', ['Spanien', 'Die Niederlande', 'Amerika']],
          ['Welche Folge hatte die Gegenreformation in Bayern?', 'Bayern blieb fest katholisch', ['Bayern wurde calvinistisch', 'Bayern wurde lutherisch', 'Bayern trat aus dem Reich aus']],
          ['Was gründeten die Jesuiten vor allem?', 'Schulen und Universitäten', ['Burgen', 'Banken', 'Bauernhöfe']],
          ['Wie hießen die Gebiete, die nach dem geistlichen Vorbehalt katholisch bleiben sollten?', 'Die geistlichen Fürstentümer', ['Die Reichsstädte', 'Die Kurfürstentümer', 'Die Hansestädte']],
          ['Welcher Kaiser war Ferdinand I. für Karl V.?', 'Sein jüngerer Bruder', ['Sein Sohn', 'Sein Onkel', 'Sein Vetter']],
          ['Welche Länder gehörten außerdem zu Karls Erbe in Italien?', 'Neapel und Sizilien', ['Venedig und Genua', 'Florenz und Siena', 'Der Kirchenstaat']],
        ],
      },
    },
  ],
};

export const DREISSIGJAEHRIGER: HistEvent = {
  id: 'dreissigjaehriger-krieg',
  title: 'Der Dreißigjährige Krieg',
  date: '1618–1648',
  text: [
    'Was 1618 in Prag als Streit um Glauben und Rechte begann, wurde zu einem europäischen Krieg, der dreißig Jahre lang vor allem auf deutschem Boden ausgetragen wurde. Am Ende hatte Deutschland vielerorts ein Drittel seiner Menschen verloren, und der Westfälische Frieden ordnete Europa neu.',
  ],
  subtopics: [
    {
      id: 'krieg',
      title: 'Vom Prager Fenstersturz bis Lützen',
      date: '1618–1635',
      text: [
        'Der Augsburger Religionsfrieden hatte die Spannungen nicht beseitigt. 1608 schlossen sich protestantische Fürsten zur Union zusammen, 1609 katholische unter Herzog Maximilian I. von Bayern zur Liga. In Böhmen fürchteten die meist protestantischen Stände um ihre Religionsfreiheit. Am 23. Mai 1618 warfen sie in Prag die kaiserlichen Statthalter Martinitz und Slawata sowie einen Schreiber aus einem Fenster der Burg – der Zweite Prager Fenstersturz. Alle drei überlebten, angeblich weil sie auf einem Misthaufen landeten.',
        'Die Böhmen wählten den Calvinisten Friedrich V. von der Pfalz zu ihrem König. Doch am 8. November 1620 besiegte das Heer des Kaisers und der Liga unter dem Feldherrn Tilly die Böhmen in der Schlacht am Weißen Berg bei Prag. Friedrich floh nach nur einem Winter – man verspottete ihn als „Winterkönig“. Maximilian von Bayern erhielt 1623 die pfälzische Kurwürde und die Oberpfalz. In den Jahren 1621–1623 litten die Menschen zudem unter einer großen Geldentwertung, der Kipper- und Wipperzeit.',
        '1625 griff König Christian IV. von Dänemark auf Seiten der Protestanten ein, wurde aber 1626 bei Lutter am Barenberge von Tilly geschlagen. Inzwischen hatte Albrecht von Wallenstein, ein böhmischer Adliger und Herzog von Friedland, für den Kaiser ein riesiges eigenes Söldnerheer aufgestellt. Sein Grundsatz war: „Der Krieg ernährt den Krieg“ – die Truppen lebten von den Abgaben der besetzten Gebiete. 1629 musste Dänemark im Frieden von Lübeck aufgeben. Im selben Jahr verlangte der Kaiser im Restitutionsedikt alle seit 1552 eingezogenen Kirchengüter zurück. Aus Angst vor Wallensteins Macht erzwangen die Fürsten 1630 in Regensburg seine Entlassung.',
        '1630 landete König Gustav II. Adolf von Schweden mit seinem Heer auf Usedom, um den Protestanten zu helfen – und um die Ostsee zu beherrschen. Am 20. Mai 1631 eroberten Truppen Tillys und Pappenheims Magdeburg; die Stadt brannte nieder, rund 20.000 Menschen starben. „Magdeburgisieren“ wurde zum Wort für völlige Zerstörung. Im September 1631 siegte Gustav Adolf bei Breitenfeld bei Leipzig über Tilly, der 1632 bei Rain am Lech tödlich verwundet wurde. Die Schweden zogen bis nach München.',
        'Der Kaiser rief Wallenstein zurück. Am 16. November 1632 trafen beide Heere bei Lützen aufeinander. Die Schweden behaupteten das Schlachtfeld, doch Gustav Adolf fiel, ebenso der kaiserliche General Pappenheim. Wallenstein verhandelte danach eigenmächtig mit den Gegnern. Der Kaiser ließ ihn absetzen, und am 25. Februar 1634 wurde er in Eger von eigenen Offizieren ermordet.',
        '1634 siegten kaiserliche und spanische Truppen bei Nördlingen über die Schweden. 1635 schloss der Kaiser mit Sachsen und den meisten evangelischen Fürsten den Prager Frieden. Der Krieg hätte nun enden können – doch Frankreich trat offen in den Krieg ein, und die Kämpfe gingen noch dreizehn Jahre weiter.',
      ],
      quiz: {
        leicht: [
          ['Wie lange dauerte der Dreißigjährige Krieg?', 'Dreißig Jahre', ['Sieben Jahre', 'Hundert Jahre', 'Drei Jahre']],
          ['Wann begann der Dreißigjährige Krieg?', '1618', ['1517', '1555', '1648']],
          ['Welches Ereignis in Prag löste den Krieg aus?', 'Der Prager Fenstersturz', ['Die Verbrennung von Jan Hus', 'Die Gründung der Universität', 'Ein Erdbeben']],
          ['Was geschah beim Prager Fenstersturz?', 'Kaiserliche Beamte wurden aus einem Fenster geworfen', ['Ein Kaiser fiel aus dem Fenster', 'Fenster wurden eingeschlagen', 'Ein Brief wurde aus dem Fenster geworfen']],
          ['Überlebten die Opfer des Fenstersturzes?', 'Ja, alle drei', ['Nein, alle starben', 'Nur einer', 'Man weiß es nicht']],
          ['Wie nannte man Friedrich V. von der Pfalz spöttisch?', 'Winterkönig', ['Sommerkönig', 'Schneekönig', 'Schattenkönig']],
          ['Wie lange war Friedrich V. König von Böhmen?', 'Nur etwa einen Winter', ['Dreißig Jahre', 'Zehn Jahre', 'Sein ganzes Leben']],
          ['Welcher Feldherr stellte für den Kaiser ein riesiges Söldnerheer auf?', 'Wallenstein', ['Tilly', 'Gustav Adolf', 'Pappenheim']],
          ['Welcher schwedische König griff 1630 in den Krieg ein?', 'Gustav II. Adolf', ['Christian IV.', 'Karl XII.', 'Gustav Wasa']],
          ['Welche Stadt wurde 1631 völlig zerstört?', 'Magdeburg', ['Leipzig', 'Dresden', 'Berlin']],
          ['Wo fiel Gustav Adolf 1632?', 'Bei Lützen', ['Bei Breitenfeld', 'Am Weißen Berg', 'Bei Nördlingen']],
          ['Was geschah mit Wallenstein 1634?', 'Er wurde ermordet', ['Er wurde Kaiser', 'Er wurde König von Schweden', 'Er starb an der Pest']],
          ['Welches Land trat 1635 offen in den Krieg ein?', 'Frankreich', ['England', 'Russland', 'Italien']],
          ['Welche beiden Bündnisse standen sich vor dem Krieg gegenüber?', 'Union und Liga', ['Hanse und Bund', 'Entente und Achse', 'NATO und Warschauer Pakt']],
          ['Welche Konfession hatte die Liga?', 'Katholisch', ['Evangelisch', 'Calvinistisch', 'Orthodox']],
          ['Wer führte die katholische Liga an?', 'Maximilian I. von Bayern', ['Friedrich V. von der Pfalz', 'Gustav Adolf', 'Christian IV.']],
          ['Welcher Feldherr der Liga siegte am Weißen Berg?', 'Tilly', ['Wallenstein', 'Pappenheim', 'Gustav Adolf']],
          ['Auf welcher Insel landeten die Schweden 1630?', 'Usedom', ['Rügen', 'Sylt', 'Fehmarn']],
          ['Wie lautete Wallensteins Grundsatz?', '„Der Krieg ernährt den Krieg“', ['„Gott mit uns“', '„Teile und herrsche“', '„Frieden um jeden Preis“']],
          ['Wovon lebten Wallensteins Truppen?', 'Von Abgaben der besetzten Gebiete', ['Vom Sold des Papstes', 'Von Spenden', 'Von eigener Landwirtschaft']],
        ],
        mittel: [
          ['An welchem Tag war der Zweite Prager Fenstersturz?', '23. Mai 1618', ['8. November 1620', '31. Oktober 1618', '24. Oktober 1648']],
          ['Wie hießen die beiden Statthalter, die aus dem Fenster geworfen wurden?', 'Martinitz und Slawata', ['Tilly und Pappenheim', 'Wallenstein und Piccolomini', 'Ferdinand und Maximilian']],
          ['Worauf sollen die Opfer gelandet sein?', 'Auf einem Misthaufen', ['In einem Wassergraben', 'Auf einem Heuwagen', 'In einem Baum']],
          ['Wann wurde die protestantische Union gegründet?', '1608', ['1555', '1618', '1631']],
          ['Wann fand die Schlacht am Weißen Berg statt?', '8. November 1620', ['23. Mai 1618', '16. November 1632', '20. Mai 1631']],
          ['Welche Konfession hatte Friedrich V. von der Pfalz?', 'Er war Calvinist', ['Er war Katholik', 'Er war Lutheraner', 'Er war orthodox']],
          ['Was erhielt Maximilian von Bayern 1623?', 'Die pfälzische Kurwürde', ['Die Kaiserkrone', 'Das Königreich Böhmen', 'Die Stadt Wien']],
          ['Welcher dänische König griff 1625 ein?', 'Christian IV.', ['Friedrich II.', 'Waldemar IV.', 'Christian X.']],
          ['Wo wurde Christian IV. 1626 geschlagen?', 'Bei Lutter am Barenberge', ['Bei Lützen', 'Bei Breitenfeld', 'Bei Nördlingen']],
          ['Wie hieß Wallensteins Herzogtum?', 'Friedland', ['Sachsen-Lauenburg', 'Kleve', 'Teschen']],
          ['Was verlangte der Kaiser im Restitutionsedikt 1629?', 'Die Rückgabe eingezogener Kirchengüter', ['Die Abschaffung der Leibeigenschaft', 'Frieden mit Schweden', 'Neue Steuern für Wallenstein']],
          ['Wo wurde Wallenstein 1630 entlassen?', 'Auf dem Kurfürstentag in Regensburg', ['In Wien', 'In Prag', 'In Eger']],
          ['Wann wurde Magdeburg zerstört?', '20. Mai 1631', ['16. November 1632', '23. Mai 1618', '25. Februar 1634']],
          ['Wie viele Menschen starben bei der Zerstörung Magdeburgs etwa?', 'Rund 20.000', ['Rund 200', 'Rund 2000', 'Rund 200.000']],
          ['Wo siegte Gustav Adolf im September 1631 über Tilly?', 'Bei Breitenfeld', ['Bei Lützen', 'Bei Nördlingen', 'Am Weißen Berg']],
          ['Wann fand die Schlacht bei Lützen statt?', '16. November 1632', ['8. November 1620', '20. Mai 1631', '6. September 1634']],
          ['Welcher kaiserliche General fiel ebenfalls bei Lützen?', 'Pappenheim', ['Tilly', 'Wallenstein', 'Piccolomini']],
          ['Wo wurde Wallenstein ermordet?', 'In Eger', ['In Prag', 'In Wien', 'In Lützen']],
          ['Wo siegten Kaiserliche und Spanier 1634 über die Schweden?', 'Bei Nördlingen', ['Bei Breitenfeld', 'Bei Lützen', 'Bei Rain am Lech']],
          ['Welcher Frieden wurde 1635 geschlossen?', 'Der Prager Frieden', ['Der Westfälische Frieden', 'Der Lübecker Frieden', 'Der Augsburger Religionsfrieden']],
        ],
        schwer: [
          ['Wann wurde die katholische Liga gegründet?', '1609', ['1608', '1618', '1555']],
          ['Wie nennt man die Geldentwertung von 1621–1623?', 'Kipper- und Wipperzeit', ['Gründerkrise', 'Große Inflation', 'Tulpenkrise']],
          ['Welches Gebiet erhielt Maximilian von Bayern zusätzlich?', 'Die Oberpfalz', ['Die Rheinpfalz', 'Böhmen', 'Tirol']],
          ['Wann schied Dänemark im Frieden von Lübeck aus dem Krieg aus?', '1629', ['1626', '1630', '1635']],
          ['Ab welchem Jahr eingezogene Kirchengüter forderte das Restitutionsedikt zurück?', 'Seit 1552', ['Seit 1517', 'Seit 1618', 'Seit 1648']],
          ['Welcher Feldherr eroberte Magdeburg gemeinsam mit Tilly?', 'Pappenheim', ['Wallenstein', 'Piccolomini', 'Mansfeld']],
          ['Was bedeutet „magdeburgisieren“?', 'Völlig zerstören', ['Eine Stadt befestigen', 'Frieden schließen', 'Den Glauben wechseln']],
          ['Wo wurde Tilly 1632 tödlich verwundet?', 'Bei Rain am Lech', ['Bei Lützen', 'Bei Breitenfeld', 'Bei Nördlingen']],
          ['Bis zu welcher Stadt zogen die Schweden 1632?', 'Bis München', ['Bis Wien', 'Bis Rom', 'Bis Paris']],
          ['An welchem Tag wurde Wallenstein ermordet?', '25. Februar 1634', ['16. November 1632', '23. Mai 1618', '6. September 1634']],
          ['Wer ermordete Wallenstein?', 'Eigene Offiziere', ['Schwedische Soldaten', 'Ein französischer Spion', 'Bauern']],
          ['Weshalb wurde Wallenstein abgesetzt?', 'Er verhandelte eigenmächtig mit den Gegnern', ['Er hatte alle Schlachten verloren', 'Er wurde evangelisch', 'Er war zu alt']],
          ['Welches Ziel verfolgte Gustav Adolf neben der Hilfe für die Protestanten?', 'Die Herrschaft über die Ostsee', ['Die Eroberung Spaniens', 'Die Kaiserkrone für Dänemark', 'Den Handel mit Indien']],
          ['Wie viele Jahre dauerte der Krieg nach dem Prager Frieden noch?', 'Dreizehn Jahre', ['Drei Jahre', 'Dreißig Jahre', 'Ein Jahr']],
          ['Was war Wallenstein von Herkunft?', 'Ein böhmischer Adliger', ['Ein schwedischer Prinz', 'Ein bayerischer Bauer', 'Ein spanischer Graf']],
          ['Mit welchem Fürsten vor allem schloss der Kaiser 1635 den Prager Frieden?', 'Mit dem Kurfürsten von Sachsen', ['Mit dem König von Schweden', 'Mit dem König von Frankreich', 'Mit dem Papst']],
          ['Wer gewann die Schlacht bei Lützen militärisch?', 'Die Schweden behaupteten das Schlachtfeld', ['Wallenstein siegte klar', 'Die Franzosen', 'Niemand kam']],
          ['Wann wurde Wallenstein vom Kaiser zurückgerufen?', 'Ende 1631/1632', ['1618', '1635', '1640']],
          ['Welches Land unterstützte den Kaiser bei Nördlingen?', 'Spanien', ['Frankreich', 'England', 'Schweden']],
          ['Welche Stadt war 1618 Ort des Fenstersturzes?', 'Prag', ['Wien', 'Pilsen', 'Brünn']],
        ],
      },
    },
    {
      id: 'westfaelischer-frieden',
      title: 'Not, Hexenwahn und Westfälischer Frieden',
      date: '1635–1648',
      text: [
        'Ab 1635 kämpfte das katholische Frankreich unter Kardinal Richelieu gemeinsam mit dem protestantischen Schweden gegen den Kaiser – es ging nun vor allem um die Macht in Europa, nicht mehr um den Glauben. Heere zogen kreuz und quer durch Deutschland, plünderten, verwüsteten Felder und schleppten Seuchen ein. Hunger und Pest töteten mehr Menschen als die Schlachten. Insgesamt ging die Bevölkerung im Reich von etwa 16 auf rund 10 Millionen zurück; manche Gegenden verloren mehr als die Hälfte ihrer Einwohner.',
        'Das Grauen dieser Zeit schildert der Roman „Der abenteuerliche Simplicissimus Teutsch“ von Hans Jakob Christoffel von Grimmelshausen (1668/69), der selbst als Junge in den Krieg geraten war. Später schrieb Friedrich Schiller die „Wallenstein“-Trilogie (1799), und Bertolt Brecht verarbeitete den Krieg in „Mutter Courage und ihre Kinder“ (1939).',
        'In dieser Zeit voller Angst erreichten auch die Hexenverfolgungen ihren Höhepunkt, besonders zwischen 1560 und 1630. Grundlage war unter anderem der „Hexenhammer“ des Dominikaners Heinrich Kramer von 1486. Menschen, meist Frauen, wurden beschuldigt, mit dem Teufel im Bund zu stehen und Unwetter, Krankheiten oder Missernten verursacht zu haben. Unter der Folter gestanden sie und nannten weitere „Hexen“. Im Reich wurden etwa 25.000 Menschen hingerichtet, besonders viele in geistlichen Fürstentümern wie Bamberg und Würzburg. Der Jesuit Friedrich Spee wandte sich 1631 in seiner Schrift „Cautio criminalis“ mutig gegen die Folter.',
        'Ab 1643/44 verhandelten Gesandte aus ganz Europa jahrelang in zwei westfälischen Städten: in Münster (der Kaiser mit Frankreich und den katholischen Ständen) und in Osnabrück (der Kaiser mit Schweden und den evangelischen Ständen). Schon am 15. Mai 1648 schlossen Spanien und die Niederlande in Münster Frieden; die Niederlande wurden als unabhängig anerkannt. Daran erinnert der Friedenssaal im Rathaus von Münster. Am 24. Oktober 1648 wurde der Westfälische Frieden unterzeichnet.',
        'Die Niederlande und die Schweiz schieden endgültig aus dem Reich aus. Frankreich erhielt habsburgische Gebiete im Elsass, und sein Besitz der Bistümer Metz, Toul und Verdun wurde bestätigt. Schweden bekam Vorpommern sowie die Bistümer Bremen und Verden und damit Sitze im Reichstag. Bayern behielt die Kurwürde; für die Pfalz wurde eine achte Kurwürde geschaffen.',
        'Neben Lutheranern und Katholiken wurden nun auch die Calvinisten anerkannt. Für den Besitz von Kirchengütern galt der Stand von 1624 (Normaljahr). Die Reichsstände erhielten die Landeshoheit und durften Bündnisse schließen, solange sie sich nicht gegen Kaiser und Reich richteten. Damit wurde die Macht des Kaisers dauerhaft begrenzt; das Reich bestand aus rund 300 weitgehend selbstständigen Territorien. Der Westfälische Frieden gilt als Grundstein einer europäischen Ordnung gleichberechtigter Staaten.',
      ],
      quiz: {
        leicht: [
          ['Wann endete der Dreißigjährige Krieg?', '1648', ['1618', '1700', '1555']],
          ['Wie heißt der Frieden, der den Dreißigjährigen Krieg beendete?', 'Der Westfälische Frieden', ['Der Augsburger Religionsfrieden', 'Der Prager Frieden', 'Der Frieden von Versailles']],
          ['In welchen beiden Städten wurde verhandelt?', 'In Münster und Osnabrück', ['In Köln und Bonn', 'In Wien und Prag', 'In Paris und Berlin']],
          ['In welchem heutigen Bundesland liegt Münster?', 'Nordrhein-Westfalen', ['Niedersachsen', 'Hessen', 'Bayern']],
          ['Welches katholische Land kämpfte ab 1635 gegen den Kaiser?', 'Frankreich', ['Spanien', 'Polen', 'Bayern']],
          ['Was tötete im Krieg mehr Menschen als die Schlachten?', 'Hunger und Seuchen', ['Erdbeben', 'Kälte', 'Überschwemmungen']],
          ['Etwa welcher Teil der Bevölkerung starb im Reich?', 'Etwa ein Drittel', ['Etwa ein Hundertstel', 'Fast niemand', 'Fast alle']],
          ['Welcher Roman schildert das Grauen des Krieges?', '„Simplicissimus“', ['„Faust“', '„Werther“', '„Robinson Crusoe“']],
          ['Welche Länder schieden 1648 endgültig aus dem Reich aus?', 'Die Niederlande und die Schweiz', ['Bayern und Sachsen', 'Österreich und Böhmen', 'Polen und Ungarn']],
          ['Welche Konfession wurde 1648 zusätzlich anerkannt?', 'Die Calvinisten', ['Die Täufer', 'Die Orthodoxen', 'Die Muslime']],
          ['Welches Land erhielt Gebiete im Elsass?', 'Frankreich', ['Schweden', 'Spanien', 'Schweiz']],
          ['Welches Land erhielt Vorpommern?', 'Schweden', ['Dänemark', 'Polen', 'Brandenburg']],
          ['Wessen Macht wurde durch den Frieden dauerhaft begrenzt?', 'Die des Kaisers', ['Die der Fürsten', 'Die Frankreichs', 'Die Schwedens']],
          ['Wann erreichten die Hexenverfolgungen ihren Höhepunkt?', 'Zwischen 1560 und 1630', ['Um 800', 'Um 1900', 'Um 1200']],
          ['Wer wurde meist als Hexe beschuldigt?', 'Frauen', ['Kinder', 'Könige', 'Ritter']],
          ['Wodurch wurden Geständnisse in Hexenprozessen erzwungen?', 'Durch Folter', ['Durch Bestechung', 'Durch Zeugen', 'Durch Beweise']],
          ['Wie heißt das berüchtigte Buch gegen Hexen von 1486?', '„Hexenhammer“', ['„Hexenbibel“', '„Teufelsbuch“', '„Hexenspiegel“']],
          ['Welcher Jesuit schrieb gegen die Folter in Hexenprozessen?', 'Friedrich Spee', ['Petrus Canisius', 'Ignatius von Loyola', 'Heinrich Kramer']],
          ['Welcher Raum in Münster erinnert an den Frieden?', 'Der Friedenssaal im Rathaus', ['Die Friedenskirche', 'Das Friedenstor', 'Der Friedensturm']],
          ['Welches Land wurde 1648 in Münster als unabhängig anerkannt?', 'Die Niederlande', ['Portugal', 'Belgien', 'Dänemark']],
        ],
        mittel: [
          ['Welcher Kardinal lenkte Frankreichs Politik ab 1635?', 'Richelieu', ['Mazarin', 'Cajetan', 'Wolsey']],
          ['Worum ging es im Krieg nach 1635 vor allem?', 'Um die Macht in Europa', ['Nur um den Glauben', 'Um Kolonien in Amerika', 'Um den Papst']],
          ['Wie stark ging die Bevölkerung im Reich etwa zurück?', 'Von etwa 16 auf rund 10 Millionen', ['Von 100 auf 90 Millionen', 'Von 5 auf 4 Millionen', 'Von 30 auf 29 Millionen']],
          ['Wer schrieb den „Simplicissimus“?', 'Grimmelshausen', ['Schiller', 'Goethe', 'Lessing']],
          ['Wann erschien der „Simplicissimus“?', '1668/69', ['1618', '1648', '1799']],
          ['Wer schrieb die „Wallenstein“-Trilogie?', 'Friedrich Schiller', ['Johann Wolfgang von Goethe', 'Bertolt Brecht', 'Heinrich von Kleist']],
          ['Welches Theaterstück von Brecht spielt im Dreißigjährigen Krieg?', '„Mutter Courage und ihre Kinder“', ['„Die Dreigroschenoper“', '„Leben des Galilei“', '„Der gute Mensch von Sezuan“']],
          ['Wer verfasste den „Hexenhammer“?', 'Heinrich Kramer', ['Friedrich Spee', 'Martin Luther', 'Johann Tetzel']],
          ['Wie viele Menschen wurden im Reich etwa als Hexen hingerichtet?', 'Rund 25.000', ['Rund 250', 'Rund 2,5 Millionen', 'Rund 2500']],
          ['In welchen Fürstentümern gab es besonders viele Hexenprozesse?', 'In Bamberg und Würzburg', ['In Hamburg und Bremen', 'In Brandenburg und Pommern', 'In Venedig und Genua']],
          ['Wie heißt Friedrich Spees Schrift gegen die Folter?', '„Cautio criminalis“', ['„Malleus maleficarum“', '„Constitutio Carolina“', '„Summa theologiae“']],
          ['Wann erschien Spees „Cautio criminalis“?', '1631', ['1486', '1648', '1700']],
          ['Wer verhandelte in Osnabrück?', 'Der Kaiser mit Schweden und den evangelischen Ständen', ['Der Kaiser mit Frankreich', 'Spanien mit den Niederlanden', 'Der Papst mit dem Kaiser']],
          ['Wer verhandelte in Münster?', 'Der Kaiser mit Frankreich und den katholischen Ständen', ['Der Kaiser mit Schweden', 'Dänemark mit Schweden', 'Polen mit Russland']],
          ['An welchem Tag wurde der Westfälische Frieden unterzeichnet?', '24. Oktober 1648', ['15. Mai 1648', '25. September 1555', '23. Mai 1618']],
          ['Wann schlossen Spanien und die Niederlande Frieden?', '15. Mai 1648', ['24. Oktober 1648', '1609', '1635']],
          ['Welche Bistümer erhielt Schweden?', 'Bremen und Verden', ['Metz und Toul', 'Münster und Osnabrück', 'Magdeburg und Halberstadt']],
          ['Welche drei Bistümer wurden Frankreich bestätigt?', 'Metz, Toul und Verdun', ['Straßburg, Basel und Konstanz', 'Köln, Trier und Mainz', 'Lüttich, Utrecht und Cambrai']],
          ['Was wurde für die Pfalz neu geschaffen?', 'Eine achte Kurwürde', ['Ein Königreich', 'Ein Bistum', 'Eine Universität']],
          ['Welche Rechte erhielten die Reichsstände?', 'Landeshoheit und Bündnisrecht', ['Das Recht, den Papst zu wählen', 'Eigene Kaiserkronen', 'Keine neuen Rechte']],
        ],
        schwer: [
          ['Wann begannen die Friedensverhandlungen in Westfalen?', '1643/44', ['1635', '1618', '1647']],
          ['Welches Jahr galt als „Normaljahr“ für Kirchenbesitz?', '1624', ['1555', '1618', '1648']],
          ['Welche Einschränkung galt für das Bündnisrecht der Reichsstände?', 'Bündnisse durften sich nicht gegen Kaiser und Reich richten', ['Nur Bündnisse mit dem Papst', 'Keine Bündnisse mit Schweden', 'Nur Bündnisse unter Katholiken']],
          ['Aus etwa wie vielen Territorien bestand das Reich nach 1648?', 'Rund 300', ['Rund 30', 'Rund 3000', 'Genau 7']],
          ['Was erhielt Schweden mit seinen neuen Gebieten zusätzlich?', 'Sitze im Reichstag', ['Die Kaiserkrone', 'Eine Kurwürde', 'Das Elsass']],
          ['Welche Stadt im Elsass blieb 1648 zunächst noch beim Reich?', 'Straßburg', ['Colmar', 'Mülhausen', 'Hagenau']],
          ['Welcher Teil des Elsass ging 1648 an Frankreich?', 'Habsburgische Gebiete', ['Das ganze Elsass mit Straßburg', 'Nur Straßburg', 'Kein Teil']],
          ['Wofür gilt der Westfälische Frieden in der Geschichte?', 'Als Grundstein einer Ordnung gleichberechtigter Staaten', ['Als erste Verfassung Deutschlands', 'Als Beginn der Reformation', 'Als Gründung der UNO']],
          ['Wie alt war Grimmelshausen etwa, als er in den Krieg geriet?', 'Er war noch ein Junge', ['Er war schon Greis', 'Er war erwachsener Offizier', 'Er war nie im Krieg']],
          ['Wann schrieb Schiller die „Wallenstein“-Trilogie?', '1799', ['1648', '1774', '1832']],
          ['Wann entstand Brechts „Mutter Courage“?', '1939', ['1899', '1919', '1959']],
          ['Welchem Orden gehörte Heinrich Kramer an?', 'Den Dominikanern', ['Den Jesuiten', 'Den Franziskanern', 'Den Augustinern']],
          ['Welchem Orden gehörte Friedrich Spee an?', 'Den Jesuiten', ['Den Dominikanern', 'Den Benediktinern', 'Den Kapuzinern']],
          ['Wessen wurden Hexen typischerweise beschuldigt?', 'Unwetter, Krankheiten und Missernten verursacht zu haben', ['Steuern hinterzogen zu haben', 'Bücher gedruckt zu haben', 'Den Kaiser beleidigt zu haben']],
          ['Was geschah oft, wenn Angeklagte unter Folter verhört wurden?', 'Sie nannten weitere angebliche Hexen', ['Sie wurden sofort freigelassen', 'Sie wurden zu Priestern', 'Sie wurden Zeugen der Anklage gegen den Richter']],
          ['Wie hieß der vollständige Titel des Simplicissimus?', '„Der abenteuerliche Simplicissimus Teutsch“', ['„Simplicius in Amerika“', '„Simplicissimus oder der Krieg“', '„Die Reisen des Simplicius“']],
          ['Mit welchem Land kämpfte Frankreich ab 1635 gemeinsam gegen den Kaiser?', 'Mit Schweden', ['Mit Spanien', 'Mit Bayern', 'Mit dem Papst']],
          ['Wer behielt 1648 die alte pfälzische Kurwürde?', 'Bayern', ['Die Pfalz', 'Sachsen', 'Schweden']],
          ['Welche Gegenden verloren teils mehr als die Hälfte ihrer Einwohner?', 'Manche Gegenden im Reich', ['Nur England', 'Nur Spanien', 'Keine']],
          ['Seit wann war die Schweiz praktisch schon unabhängig, bevor es 1648 anerkannt wurde?', 'Seit dem Schwabenkrieg 1499', ['Seit 1291', 'Seit 1618', 'Seit 1815']],
        ],
      },
    },
  ],
};
