import type { HistEvent } from '../types';

export const INDUSTRIALISIERUNG: HistEvent = {
  id: 'industrialisierung',
  title: 'Industrialisierung und soziale Frage',
  date: '1834–1890',
  text: [
    'Im 19. Jahrhundert wurde Deutschland von einem Agrarland zu einer der führenden Industrienationen der Welt. Eisenbahnen, Fabriken und Erfindungen veränderten das Leben – aber auch die Not der Arbeiter wuchs, und es entstanden Arbeiterbewegung und Sozialversicherung.',
  ],
  subtopics: [
    {
      id: 'industrie',
      title: 'Zollverein, Eisenbahn und Fabriken',
      date: '1834–1873',
      text: [
        'In Großbritannien hatte die Industrialisierung schon im 18. Jahrhundert begonnen. In Deutschland behinderten anfangs viele Grenzen den Handel: Jeder Staat erhob eigene Zölle. Am 1. Januar 1834 trat der Deutsche Zollverein unter der Führung Preußens in Kraft, ein gemeinsamer Wirtschaftsraum der meisten deutschen Staaten – Österreich blieb draußen. Der Ökonom Friedrich List warb für den Zollverein und für ein deutsches Eisenbahnnetz.',
        'Am 7. Dezember 1835 fuhr die erste deutsche Eisenbahn, die Ludwigsbahn, rund sechs Kilometer von Nürnberg nach Fürth. Die Lokomotive „Adler“ stammte aus der Werkstatt von Robert Stephenson in England, ebenso ihr Lokführer William Wilson. 1839 folgte mit Leipzig–Dresden die erste Fernstrecke. Die Eisenbahn wurde zum Motor der Industrialisierung: Sie brauchte Kohle, Eisen und Stahl und transportierte Waren und Menschen schnell und billig. In Berlin baute August Borsig ab 1841 Lokomotiven und machte sein Werk zu einem der größten Lokomotivhersteller der Welt.',
        'Im Ruhrgebiet entstanden riesige Kohlezechen und Hüttenwerke. In Essen machte Alfred Krupp die Gussstahlfabrik seines Vaters zum größten Unternehmen Europas; wegen seiner Geschütze nannte man ihn den „Kanonenkönig“. Werner von Siemens entdeckte 1866 das dynamoelektrische Prinzip, mit dem man Strom in großen Mengen erzeugen konnte; seine Firma baute Telegrafenleitungen, und 1881 fuhr in Berlin-Lichterfelde die erste elektrische Straßenbahn der Welt. Die chemische Industrie wuchs mit Firmen wie Bayer und Hoechst (beide 1863) und BASF (1865).',
        'Millionen Menschen zogen vom Land in die Städte, um in den Fabriken zu arbeiten (Landflucht). Die Arbeitstage dauerten zwölf bis sechzehn Stunden, die Löhne waren niedrig, Unfälle häufig, und auch Kinder mussten arbeiten. In Preußen verbot ein Regulativ von 1839 erstmals die Fabrikarbeit von Kindern unter neun Jahren. In den Städten lebten Arbeiterfamilien zusammengedrängt in Mietskasernen mit dunklen Hinterhöfen. Die Massenarmut dieser Zeit nennt man Pauperismus, die Frage nach der Lage der Arbeiter die „soziale Frage“.',
        'Rund fünf Millionen Deutsche wanderten im 19. Jahrhundert aus, vor allem in die USA. Andere suchten Hilfe in Genossenschaften, wie sie Friedrich Wilhelm Raiffeisen für Bauern gründete, oder in kirchlichen Vereinen: Der katholische Priester Adolph Kolping gründete Gesellenvereine, und Bischof Wilhelm Emmanuel von Ketteler setzte sich für die Arbeiter ein.',
        'Nach der Reichsgründung 1871 strömten französische Kriegsentschädigungen ins Land, und überall wurden neue Firmen gegründet – die „Gründerzeit“. 1873 platzte die Spekulationsblase im „Gründerkrach“. Dennoch überholte Deutschland bis 1900 in vielen Bereichen Großbritannien.',
      ],
      quiz: {
        leicht: [
          ['In welchem Land begann die Industrialisierung?', 'In Großbritannien', ['In Deutschland', 'In Frankreich', 'In Russland']],
          ['Was war der Deutsche Zollverein?', 'Ein gemeinsamer Wirtschaftsraum ohne Zölle untereinander', ['Ein Sportverein', 'Eine Armee', 'Eine Partei']],
          ['Welcher Staat führte den Zollverein?', 'Preußen', ['Österreich', 'Bayern', 'Sachsen']],
          ['Welches Land gehörte nicht zum Zollverein?', 'Österreich', ['Preußen', 'Bayern', 'Württemberg']],
          ['Zwischen welchen Städten fuhr die erste deutsche Eisenbahn?', 'Nürnberg und Fürth', ['Berlin und Potsdam', 'Leipzig und Dresden', 'Köln und Bonn']],
          ['In welchem Jahr fuhr die erste deutsche Eisenbahn?', '1835', ['1815', '1871', '1900']],
          ['Wie hieß die erste deutsche Lokomotive?', 'Adler', ['Falke', 'Rakete', 'Blitz']],
          ['Woher kam die Lokomotive „Adler“?', 'Aus England', ['Aus Amerika', 'Aus Frankreich', 'Aus Bayern']],
          ['Welches Gebiet wurde zum Zentrum von Kohle und Stahl?', 'Das Ruhrgebiet', ['Der Schwarzwald', 'Die Lüneburger Heide', 'Das Allgäu']],
          ['In welcher Stadt stand die Gussstahlfabrik Krupp?', 'Essen', ['Dortmund', 'Duisburg', 'Berlin']],
          ['Welchen Spitznamen hatte Alfred Krupp?', 'Kanonenkönig', ['Kohlebaron', 'Eisenkanzler', 'Stahlkaiser']],
          ['Welcher Erfinder gründete eine große Elektrofirma?', 'Werner von Siemens', ['Carl Benz', 'Gottlieb Daimler', 'Robert Bosch']],
          ['Wo fuhr 1881 die erste elektrische Straßenbahn der Welt?', 'In Berlin', ['In London', 'In Paris', 'In New York']],
          ['Wie nennt man den Zug der Menschen vom Land in die Stadt?', 'Landflucht', ['Stadtflucht', 'Völkerwanderung', 'Auswanderung']],
          ['Wie lange dauerte ein Arbeitstag in der Fabrik oft?', '12 bis 16 Stunden', ['4 Stunden', '8 Stunden', '24 Stunden']],
          ['Mussten damals auch Kinder in Fabriken arbeiten?', 'Ja', ['Nein, nie', 'Nur in England', 'Nur am Wochenende']],
          ['Wie nennt man die großen Arbeiterwohnhäuser mit Hinterhöfen?', 'Mietskasernen', ['Villen', 'Burgen', 'Reihenhäuser']],
          ['Wie nennt man die Frage nach der Lage der Arbeiter?', 'Soziale Frage', ['Deutsche Frage', 'Orientalische Frage', 'Gretchenfrage']],
          ['Wohin wanderten viele Deutsche im 19. Jahrhundert aus?', 'In die USA', ['Nach China', 'Nach Russland', 'Nach Afrika']],
          ['Was brauchte die Eisenbahn in großen Mengen?', 'Kohle, Eisen und Stahl', ['Gold und Silber', 'Holz und Stroh', 'Wolle und Baumwolle']],
        ],
        mittel: [
          ['Wann trat der Deutsche Zollverein in Kraft?', '1. Januar 1834', ['7. Dezember 1835', '18. Januar 1871', '1. Mai 1848']],
          ['Welcher Ökonom warb für Zollverein und Eisenbahn?', 'Friedrich List', ['Karl Marx', 'Adam Smith', 'Friedrich Engels']],
          ['Wie hieß die erste deutsche Eisenbahnstrecke?', 'Ludwigsbahn', ['Adlerbahn', 'Kaiserbahn', 'Frankenbahn']],
          ['Wie lang war die erste Strecke etwa?', 'Rund sechs Kilometer', ['Rund 60 Kilometer', 'Rund 600 Kilometer', 'Rund 600 Meter']],
          ['Welche Strecke war 1839 die erste deutsche Fernbahn?', 'Leipzig–Dresden', ['Berlin–Hamburg', 'Köln–Aachen', 'München–Augsburg']],
          ['Aus wessen Werkstatt stammte der „Adler“?', 'Robert Stephenson', ['August Borsig', 'James Watt', 'Werner von Siemens']],
          ['Wer baute in Berlin Lokomotiven?', 'August Borsig', ['Alfred Krupp', 'Carl Benz', 'Emil Rathenau']],
          ['Seit wann baute Borsig Lokomotiven?', '1841', ['1835', '1871', '1820']],
          ['Was entdeckte Werner von Siemens 1866?', 'Das dynamoelektrische Prinzip', ['Die Röntgenstrahlen', 'Den Viertaktmotor', 'Das Telefon']],
          ['Welche Chemiefirmen wurden 1863 gegründet?', 'Bayer und Hoechst', ['BASF und Siemens', 'Krupp und Thyssen', 'Daimler und Benz']],
          ['Wann wurde die BASF gegründet?', '1865', ['1835', '1883', '1900']],
          ['Was verbot das preußische Regulativ von 1839?', 'Fabrikarbeit von Kindern unter neun Jahren', ['Jede Kinderarbeit', 'Sonntagsarbeit', 'Nachtarbeit für Männer']],
          ['Wie nennt man die Massenarmut im frühen 19. Jahrhundert?', 'Pauperismus', ['Kapitalismus', 'Merkantilismus', 'Feudalismus']],
          ['Wie viele Deutsche wanderten im 19. Jahrhundert etwa aus?', 'Rund fünf Millionen', ['Rund 50.000', 'Rund 50 Millionen', 'Rund 500']],
          ['Wer gründete Genossenschaften für Bauern?', 'Friedrich Wilhelm Raiffeisen', ['Adolph Kolping', 'Ferdinand Lassalle', 'Robert Owen']],
          ['Welcher Priester gründete Gesellenvereine?', 'Adolph Kolping', ['Wilhelm von Ketteler', 'Friedrich Raiffeisen', 'Johann Hinrich Wichern']],
          ['Welcher Bischof setzte sich für die Arbeiter ein?', 'Wilhelm Emmanuel von Ketteler', ['Adolph Kolping', 'Clemens August von Galen', 'Bonifatius']],
          ['Wie nennt man die Zeit vieler Firmengründungen nach 1871?', 'Gründerzeit', ['Biedermeier', 'Vormärz', 'Wirtschaftswunder']],
          ['Wann kam es zum „Gründerkrach“?', '1873', ['1871', '1890', '1929']],
          ['Wann fuhr die erste elektrische Straßenbahn in Berlin-Lichterfelde?', '1881', ['1866', '1900', '1835']],
        ],
        schwer: [
          ['An welchem Tag fuhr die Ludwigsbahn zum ersten Mal?', '7. Dezember 1835', ['1. Januar 1834', '24. Dezember 1839', '18. Januar 1871']],
          ['Wie hieß der englische Lokführer des „Adler“?', 'William Wilson', ['George Stephenson', 'James Watt', 'John Smith']],
          ['In welchem Stadtteil Berlins fuhr die erste elektrische Straßenbahn?', 'Lichterfelde', ['Charlottenburg', 'Spandau', 'Kreuzberg']],
          ['Was wurde Krupps Firma unter Alfred Krupp?', 'Das größte Unternehmen Europas', ['Eine Bank', 'Eine Eisenbahngesellschaft', 'Ein Staatsbetrieb']],
          ['Was ermöglichte das dynamoelektrische Prinzip?', 'Strom in großen Mengen zu erzeugen', ['Bilder zu übertragen', 'Autos zu bauen', 'Flugzeuge zu fliegen']],
          ['Was baute Siemens’ Firma unter anderem?', 'Telegrafenleitungen', ['Kanonen', 'Schiffe', 'Flugzeuge']],
          ['Was strömte nach 1871 als Geld nach Deutschland?', 'Französische Kriegsentschädigungen', ['Amerikanisches Gold', 'Russische Kredite', 'Britische Hilfe']],
          ['Was platzte 1873?', 'Eine Spekulationsblase', ['Ein Staudamm', 'Eine Gasleitung', 'Ein Bündnis']],
          ['Welches Land überholte Deutschland bis 1900 in vielen Industriebereichen?', 'Großbritannien', ['Die USA', 'Japan', 'China']],
          ['Welche Stadt wurde 1835 durch die Ludwigsbahn mit Nürnberg verbunden?', 'Fürth', ['Erlangen', 'Bamberg', 'Ansbach']],
          ['Wie groß wurde Borsigs Werk?', 'Einer der größten Lokomotivhersteller der Welt', ['Ein kleiner Handwerksbetrieb', 'Die einzige Fabrik Berlins', 'Ein Staatsbetrieb ohne Bedeutung']],
          ['Für wen setzten sich Kolping und Ketteler ein?', 'Für Arbeiter und Handwerksgesellen', ['Für die Adligen', 'Für die Fabrikbesitzer', 'Für die Offiziere']],
          ['Seit wann gab es in Großbritannien Industrialisierung?', 'Seit dem 18. Jahrhundert', ['Seit dem 20. Jahrhundert', 'Seit dem Mittelalter', 'Seit 1871']],
          ['Welche Folge hatte die Landflucht für die Städte?', 'Sie wuchsen sehr schnell', ['Sie schrumpften', 'Sie wurden verlassen', 'Sie wurden zu Dörfern']],
          ['Wie hießen die Hinterhofwohnungen in Berlin abwertend?', 'Mietskasernen', ['Gartenhäuser', 'Stadtvillen', 'Plattenbauten']],
          ['Wofür steht die Abkürzung BASF?', 'Badische Anilin- und Soda-Fabrik', ['Berliner Allgemeine Stahl-Fabrik', 'Bayerische Auto- und Schiffs-Fabrik', 'Bremer Anker- und Seil-Fabrik']],
          ['In welchem Fluss-Gebiet lag das Zentrum von Kohle und Stahl?', 'An der Ruhr', ['An der Isar', 'An der Oder', 'An der Weser']],
          ['Welche Fabrik übernahm Alfred Krupp von seinem Vater?', 'Die Gussstahlfabrik in Essen', ['Ein Bergwerk in Schlesien', 'Eine Werft in Kiel', 'Eine Bank in Frankfurt']],
          ['Welche Bedeutung hatte die Eisenbahn für die Industrialisierung?', 'Sie war ihr Motor', ['Sie bremste sie', 'Sie war unwichtig', 'Sie kam erst nach 1900']],
          ['Welcher Ort war der Startpunkt der ersten deutschen Fernbahn?', 'Leipzig', ['Berlin', 'Nürnberg', 'München']],
        ],
      },
    },
    {
      id: 'erfindungen-arbeiter',
      title: 'Erfindungen, Arbeiterbewegung und Sozialgesetze',
      date: '1848–1895',
      text: [
        'Deutsche Erfinder und Forscher veränderten die Welt. Schon 1817 hatte Karl Drais in Mannheim die Laufmaschine erfunden, den Vorläufer des Fahrrads. Philipp Reis führte 1861 ein frühes Telefon vor. Nicolaus August Otto baute 1876 den Viertaktmotor. Gottlieb Daimler und Wilhelm Maybach entwickelten in Cannstatt einen schnell laufenden Benzinmotor und bauten 1885 den „Reitwagen“, das erste Motorrad. Carl Benz meldete am 29. Januar 1886 in Mannheim seinen Patent-Motorwagen an, das erste Automobil. 1888 fuhr seine Frau Bertha Benz damit ohne sein Wissen mit ihren Söhnen rund 106 Kilometer von Mannheim nach Pforzheim – die erste Fernfahrt mit einem Auto. Rudolf Diesel entwickelte in den 1890er Jahren den nach ihm benannten Motor.',
        'Auch die Wissenschaft blühte. Robert Koch entdeckte 1882 den Erreger der Tuberkulose und 1883/84 den der Cholera. Wilhelm Conrad Röntgen entdeckte am 8. November 1895 in Würzburg die Strahlen, mit denen man in den Körper sehen kann; 1901 erhielt er dafür den ersten Nobelpreis für Physik.',
        'Karl Marx, 1818 in Trier geboren, und Friedrich Engels veröffentlichten im Februar 1848 in London das „Kommunistische Manifest“, das mit den Worten „Proletarier aller Länder, vereinigt euch!“ endet. Sie meinten, die Arbeiter (Proletarier) würden die Fabrikbesitzer (Kapitalisten) eines Tages stürzen. 1867 erschien der erste Band von Marx’ Hauptwerk „Das Kapital“.',
        'Am 23. Mai 1863 gründete Ferdinand Lassalle in Leipzig den Allgemeinen Deutschen Arbeiterverein (ADAV). 1869 gründeten August Bebel und Wilhelm Liebknecht in Eisenach die Sozialdemokratische Arbeiterpartei. 1875 schlossen sich beide in Gotha zusammen; seit 1890 heißt die Partei SPD. Arbeiter organisierten sich auch in Gewerkschaften, um für höhere Löhne und kürzere Arbeitszeiten zu kämpfen.',
        'Reichskanzler Otto von Bismarck sah in den Sozialdemokraten „Reichsfeinde“. Nach zwei Attentaten auf Kaiser Wilhelm I. ließ er 1878 das Sozialistengesetz beschließen, das sozialdemokratische Vereine, Versammlungen und Zeitungen verbot; es galt bis 1890. Die Partei wurde trotzdem immer stärker.',
        'Gleichzeitig wollte Bismarck die Arbeiter durch soziale Sicherheit für den Staat gewinnen – man spricht von „Zuckerbrot und Peitsche“. So entstanden die ersten Sozialversicherungen der Welt: 1883 die Krankenversicherung, 1884 die Unfallversicherung und 1889 die Invaliditäts- und Altersversicherung. Die Rente gab es damals erst ab 70 Jahren. Dieses System wurde zum Vorbild für viele Länder.',
      ],
      quiz: {
        leicht: [
          ['Wer baute das erste Automobil?', 'Carl Benz', ['Henry Ford', 'Rudolf Diesel', 'Werner von Siemens']],
          ['In welchem Jahr meldete Benz sein Automobil an?', '1886', ['1835', '1900', '1918']],
          ['Welche Frau machte 1888 die erste Fernfahrt mit dem Auto?', 'Bertha Benz', ['Clara Schumann', 'Marie Curie', 'Königin Luise']],
          ['Wer entdeckte die Röntgenstrahlen?', 'Wilhelm Conrad Röntgen', ['Robert Koch', 'Albert Einstein', 'Max Planck']],
          ['Wofür benutzt man Röntgenstrahlen?', 'Um in den Körper zu sehen', ['Um Strom zu erzeugen', 'Um Autos anzutreiben', 'Um Musik zu machen']],
          ['Welchen Preis bekam Röntgen 1901 als Erster?', 'Den Nobelpreis für Physik', ['Den Friedensnobelpreis', 'Einen Oscar', 'Den Karlspreis']],
          ['Welcher Arzt entdeckte den Erreger der Tuberkulose?', 'Robert Koch', ['Rudolf Virchow', 'Röntgen', 'Paul Ehrlich']],
          ['Nach wem ist der Dieselmotor benannt?', 'Nach seinem Erfinder Rudolf Diesel', ['Nach einem Fluss', 'Nach einem englischen Ingenieur', 'Nach einem Rennfahrer']],
          ['Was erfand Karl Drais?', 'Die Laufmaschine, den Vorläufer des Fahrrads', ['Das Auto', 'Das Telefon', 'Die Glühbirne']],
          ['Wer schrieb mit Friedrich Engels das „Kommunistische Manifest“?', 'Karl Marx', ['Ferdinand Lassalle', 'August Bebel', 'Lenin']],
          ['Mit welchem Satz endet das Kommunistische Manifest?', '„Proletarier aller Länder, vereinigt euch!“', ['„Wir sind das Volk!“', '„Freiheit, Gleichheit, Brüderlichkeit!“', '„Arbeit macht frei!“']],
          ['Wie heißt das Hauptwerk von Karl Marx?', '„Das Kapital“', ['„Der Staat“', '„Mein Kampf“', '„Der Fürst“']],
          ['Welche Partei entstand aus der Arbeiterbewegung?', 'Die SPD', ['Die CDU', 'Die FDP', 'Die Grünen']],
          ['Wie nannte Bismarck die Sozialdemokraten?', '„Reichsfeinde“', ['„Freunde des Reiches“', '„Patrioten“', '„Kaisertreue“']],
          ['Welches Gesetz verbot 1878 sozialdemokratische Vereine?', 'Das Sozialistengesetz', ['Das Grundgesetz', 'Das Ermächtigungsgesetz', 'Die Goldene Bulle']],
          ['Welche Versicherung führte Bismarck 1883 ein?', 'Die Krankenversicherung', ['Die Autoversicherung', 'Die Haftpflichtversicherung', 'Die Pflegeversicherung']],
          ['Ab welchem Alter gab es damals Rente?', 'Ab 70 Jahren', ['Ab 50 Jahren', 'Ab 60 Jahren', 'Ab 80 Jahren']],
          ['Wie nennt man Bismarcks Politik gegenüber den Arbeitern?', '„Zuckerbrot und Peitsche“', ['„Brot und Spiele“', '„Teile und herrsche“', '„Blut und Eisen“']],
          ['Wie nennt man Zusammenschlüsse von Arbeitern für höhere Löhne?', 'Gewerkschaften', ['Zünfte', 'Gilden', 'Kartelle']],
          ['In welcher Stadt wurde Karl Marx geboren?', 'Trier', ['Berlin', 'London', 'Köln']],
        ],
        mittel: [
          ['Wann meldete Carl Benz sein Patent an?', '29. Januar 1886', ['8. November 1895', '7. Dezember 1835', '18. Januar 1871']],
          ['In welcher Stadt baute Benz sein Auto?', 'Mannheim', ['Stuttgart', 'München', 'Köln']],
          ['Wohin fuhr Bertha Benz 1888?', 'Von Mannheim nach Pforzheim', ['Von Berlin nach Potsdam', 'Von Stuttgart nach München', 'Von Köln nach Bonn']],
          ['Wer baute 1885 das erste Motorrad?', 'Daimler und Maybach', ['Benz und Diesel', 'Otto und Langen', 'Siemens und Halske']],
          ['Wie hieß das erste Motorrad?', 'Reitwagen', ['Laufmaschine', 'Motorrad 1', 'Feuerross']],
          ['Wer baute 1876 den Viertaktmotor?', 'Nicolaus August Otto', ['Rudolf Diesel', 'Gottlieb Daimler', 'Carl Benz']],
          ['Wer führte 1861 ein frühes Telefon vor?', 'Philipp Reis', ['Alexander Graham Bell', 'Werner von Siemens', 'Thomas Edison']],
          ['Wann erfand Karl Drais die Laufmaschine?', '1817', ['1886', '1835', '1900']],
          ['Wann entdeckte Röntgen seine Strahlen?', '8. November 1895', ['29. Januar 1886', '1. Januar 1900', '24. März 1882']],
          ['In welcher Stadt entdeckte Röntgen die Strahlen?', 'Würzburg', ['Berlin', 'München', 'Göttingen']],
          ['Welchen Erreger entdeckte Koch 1883/84 außerdem?', 'Den der Cholera', ['Den der Pest', 'Den der Grippe', 'Den der Masern']],
          ['Wann erschien das Kommunistische Manifest?', 'Februar 1848', ['März 1848', '1867', '1875']],
          ['Wann erschien der erste Band von „Das Kapital“?', '1867', ['1848', '1883', '1818']],
          ['Wer gründete 1863 den ADAV?', 'Ferdinand Lassalle', ['August Bebel', 'Karl Marx', 'Wilhelm Liebknecht']],
          ['Wer gründete 1869 in Eisenach die Sozialdemokratische Arbeiterpartei?', 'Bebel und Liebknecht', ['Marx und Engels', 'Lassalle und Bebel', 'Ebert und Scheidemann']],
          ['In welcher Stadt vereinigten sich die Arbeiterparteien 1875?', 'Gotha', ['Erfurt', 'Eisenach', 'Leipzig']],
          ['Seit wann heißt die Partei SPD?', '1890', ['1863', '1875', '1918']],
          ['Was ging dem Sozialistengesetz voraus?', 'Zwei Attentate auf Kaiser Wilhelm I.', ['Ein Generalstreik', 'Ein Krieg gegen Frankreich', 'Eine Revolution in Berlin']],
          ['Wann wurde die Unfallversicherung eingeführt?', '1884', ['1883', '1889', '1878']],
          ['Wann wurde die Alters- und Invaliditätsversicherung eingeführt?', '1889', ['1883', '1884', '1900']],
        ],
        schwer: [
          ['Wie weit fuhr Bertha Benz 1888 etwa?', 'Rund 106 Kilometer', ['Rund 10 Kilometer', 'Rund 1000 Kilometer', 'Rund 50 Kilometer']],
          ['Wen nahm Bertha Benz auf ihre Fahrt mit?', 'Ihre Söhne', ['Ihren Mann', 'Gottlieb Daimler', 'Den Kaiser']],
          ['Wusste Carl Benz von Berthas Fahrt?', 'Nein, sie fuhr ohne sein Wissen', ['Ja, er saß daneben', 'Ja, er hatte sie geplant', 'Er fuhr hinterher']],
          ['In welchem Ort arbeiteten Daimler und Maybach?', 'In Cannstatt', ['In Mannheim', 'In Deutz', 'In Augsburg']],
          ['In welchem Jahrzehnt entwickelte Diesel seinen Motor?', 'In den 1890er Jahren', ['In den 1850er Jahren', 'In den 1920er Jahren', 'In den 1870er Jahren']],
          ['Wann entdeckte Robert Koch den Tuberkuloseerreger?', '1882', ['1895', '1876', '1866']],
          ['Wann wurde Karl Marx geboren?', '1818', ['1848', '1789', '1835']],
          ['In welcher Stadt veröffentlichten Marx und Engels das Manifest?', 'London', ['Paris', 'Berlin', 'Brüssel']],
          ['An welchem Tag wurde der ADAV gegründet?', '23. Mai 1863', ['1. Mai 1890', '18. März 1848', '9. November 1918']],
          ['In welcher Stadt wurde der ADAV gegründet?', 'Leipzig', ['Berlin', 'Gotha', 'Eisenach']],
          ['Bis wann galt das Sozialistengesetz?', '1890', ['1878', '1918', '1900']],
          ['Was verbot das Sozialistengesetz nicht?', 'Die Wahl von Sozialdemokraten in den Reichstag', ['Sozialdemokratische Zeitungen', 'Sozialdemokratische Versammlungen', 'Sozialdemokratische Vereine']],
          ['Wie wollte Bismarck mit den Sozialgesetzen die Arbeiter gewinnen?', 'Durch soziale Sicherheit für den Staat', ['Durch höhere Löhne per Gesetz', 'Durch ein Wahlrecht für Frauen', 'Durch Enteignung der Fabriken']],
          ['Was galt Deutschlands Sozialversicherung für viele Länder?', 'Als Vorbild', ['Als abschreckendes Beispiel', 'Als unbekannt', 'Als verboten']],
          ['Wie nannten Marx und Engels die Arbeiter?', 'Proletarier', ['Bourgeois', 'Patrizier', 'Plebejer']],
          ['Wie nannten sie die Fabrikbesitzer?', 'Kapitalisten', ['Proletarier', 'Aristokraten', 'Bauern']],
          ['Welches Prinzip nutzt der Ottomotor?', 'Das Viertaktprinzip', ['Das Zweitaktprinzip', 'Das Dampfprinzip', 'Das Elektroprinzip']],
          ['In welcher Stadt erfand Karl Drais die Laufmaschine?', 'In Mannheim', ['In Karlsruhe', 'In Stuttgart', 'In Heidelberg']],
          ['Wer war außer Marx Verfasser des Kommunistischen Manifests?', 'Friedrich Engels', ['Ferdinand Lassalle', 'Wilhelm Liebknecht', 'Moses Hess']],
          ['Welcher Nobelpreis wurde 1901 zum ersten Mal vergeben, den Röntgen erhielt?', 'Physik', ['Chemie', 'Medizin', 'Literatur']],
        ],
      },
    },
  ],
};

export const REICHSGRUENDUNG: HistEvent = {
  id: 'reichsgruendung',
  title: 'Reichsgründung und Kaiserreich',
  date: '1862–1914',
  text: [
    'Was 1848 nicht gelungen war, erreichte Otto von Bismarck mit „Blut und Eisen“: In drei Kriegen einigte Preußen Deutschland ohne Österreich. 1871 wurde in Versailles das Deutsche Kaiserreich ausgerufen, das unter Wilhelm II. nach Weltgeltung strebte.',
  ],
  subtopics: [
    {
      id: 'einigungskriege',
      title: 'Bismarck und die Einigungskriege',
      date: '1862–1871',
      text: [
        'Wilhelm I., seit 1861 König von Preußen, wollte das Heer vergrößern, doch das Parlament verweigerte das Geld. In diesem Verfassungskonflikt berief er am 23. September 1862 Otto von Bismarck zum Ministerpräsidenten. Bismarck erklärte wenige Tage später: Die großen Fragen der Zeit würden „nicht durch Reden und Majoritätsbeschlüsse … sondern durch Eisen und Blut“ entschieden. Er regierte einfach ohne genehmigten Haushalt weiter.',
        '1864 kämpften Preußen und Österreich gemeinsam gegen Dänemark um Schleswig und Holstein. Nach der Erstürmung der Düppeler Schanzen am 18. April 1864 musste Dänemark die Herzogtümer abtreten. Preußen verwaltete Schleswig, Österreich Holstein.',
        'Über die Herzogtümer und die Führung in Deutschland kam es 1866 zum Deutschen Krieg zwischen Preußen und Österreich, auf dessen Seite die meisten deutschen Mittelstaaten standen. Am 3. Juli 1866 siegte das preußische Heer unter Generalstabschef Helmuth von Moltke in der Schlacht bei Königgrätz in Böhmen. Im Prager Frieden schied Österreich aus Deutschland aus, der Deutsche Bund wurde aufgelöst. Preußen annektierte Hannover, Kurhessen, Nassau, Frankfurt und Schleswig-Holstein. Mit den Staaten nördlich des Mains gründete es 1867 den Norddeutschen Bund; die süddeutschen Staaten verbanden sich mit ihm durch geheime Schutz- und Trutzbündnisse.',
        '1870 wurde ein Prinz aus einer Nebenlinie der Hohenzollern, Leopold von Hohenzollern-Sigmaringen, für den spanischen Thron vorgeschlagen. Frankreich protestierte, und der Kandidat verzichtete. Als der französische Botschafter in Bad Ems von König Wilhelm eine Garantie für alle Zukunft verlangte, lehnte dieser höflich ab. Bismarck kürzte den Bericht darüber, die „Emser Depesche“, so, dass er für Frankreich beleidigend klang, und ließ ihn veröffentlichen. Am 19. Juli 1870 erklärte Frankreich Preußen den Krieg – und die süddeutschen Staaten kämpften an Preußens Seite.',
        'Am 1. und 2. September 1870 wurde die französische Armee bei Sedan eingeschlossen; Kaiser Napoleon III. geriet in Gefangenschaft, und in Paris wurde die Republik ausgerufen. Deutsche Truppen belagerten Paris. Am 18. Januar 1871 wurde im Spiegelsaal des Schlosses Versailles König Wilhelm I. zum Deutschen Kaiser proklamiert; der Maler Anton von Werner hielt die Szene fest. Wilhelm hatte lieber „Kaiser von Deutschland“ heißen wollen und war darüber verstimmt. Den bayerischen König Ludwig II. hatte Bismarck mit geheimen Geldzahlungen für den „Kaiserbrief“ gewonnen, in dem er Wilhelm die Kaiserwürde antrug.',
        'Im Frieden von Frankfurt am 10. Mai 1871 musste Frankreich Elsass-Lothringen abtreten und fünf Milliarden Francs zahlen – eine Demütigung, die das Verhältnis beider Länder lange vergiftete. Das neue Reich war ein Bundesstaat aus 25 Staaten (22 Monarchien und drei freien Städten) und dem Reichsland Elsass-Lothringen. Der Reichstag wurde von allen Männern ab 25 Jahren gleich und geheim gewählt; der Reichskanzler aber war nur dem Kaiser verantwortlich. Es war die „kleindeutsche Lösung“ – ohne Österreich.',
      ],
      quiz: {
        leicht: [
          ['Wer war der Baumeister der deutschen Einigung?', 'Otto von Bismarck', ['Wilhelm II.', 'Metternich', 'Friedrich der Große']],
          ['Welchen Beinamen hatte Bismarck?', 'Der Eiserne Kanzler', ['Der Alte Fritz', 'Der Soldatenkönig', 'Der Große Kurfürst']],
          ['Wodurch sollten nach Bismarck die großen Fragen entschieden werden?', 'Durch Eisen und Blut', ['Durch Reden', 'Durch Abstimmungen', 'Durch Gebete']],
          ['Wie viele Kriege führte Preußen zur Einigung Deutschlands?', 'Drei', ['Einen', 'Zwei', 'Sieben']],
          ['Gegen welches Land kämpften Preußen und Österreich 1864?', 'Dänemark', ['Frankreich', 'Russland', 'Schweden']],
          ['Um welche Herzogtümer ging es 1864?', 'Schleswig und Holstein', ['Bayern und Baden', 'Sachsen und Thüringen', 'Elsass und Lothringen']],
          ['Gegen wen kämpfte Preußen 1866?', 'Österreich', ['Frankreich', 'Dänemark', 'England']],
          ['Wo siegte Preußen 1866?', 'Bei Königgrätz', ['Bei Sedan', 'Bei Leipzig', 'Bei Waterloo']],
          ['Gegen welches Land kämpfte Deutschland 1870/71?', 'Frankreich', ['Österreich', 'Russland', 'Dänemark']],
          ['In welchem Jahr wurde das Deutsche Kaiserreich gegründet?', '1871', ['1848', '1815', '1918']],
          ['Wo wurde der Deutsche Kaiser proklamiert?', 'Im Spiegelsaal von Versailles', ['In der Paulskirche', 'Im Berliner Schloss', 'Im Aachener Dom']],
          ['Wer wurde 1871 Deutscher Kaiser?', 'Wilhelm I.', ['Wilhelm II.', 'Friedrich III.', 'Bismarck']],
          ['Welches Gebiet musste Frankreich 1871 abtreten?', 'Elsass-Lothringen', ['Burgund', 'Savoyen', 'Normandie']],
          ['Welches Land gehörte nicht zum neuen Kaiserreich?', 'Österreich', ['Bayern', 'Sachsen', 'Württemberg']],
          ['Wie nennt man die Einigung ohne Österreich?', 'Kleindeutsche Lösung', ['Großdeutsche Lösung', 'Wiener Lösung', 'Rheinische Lösung']],
          ['Wie heißt die gekürzte Nachricht, die 1870 den Krieg auslöste?', 'Emser Depesche', ['Zimmermann-Telegramm', 'Krüger-Depesche', 'Kaiserbrief']],
          ['Welcher französische Kaiser geriet bei Sedan in Gefangenschaft?', 'Napoleon III.', ['Napoleon I.', 'Ludwig XVIII.', 'Karl X.']],
          ['Welcher Generalstabschef führte Preußens Heer?', 'Helmuth von Moltke', ['Blücher', 'Scharnhorst', 'Hindenburg']],
          ['Welcher bayerische König bot Wilhelm die Kaiserkrone an?', 'Ludwig II.', ['Ludwig I.', 'Maximilian II.', 'Otto I.']],
          ['Wer durfte den Reichstag wählen?', 'Alle Männer ab 25 Jahren', ['Alle Menschen ab 18', 'Nur Adlige', 'Nur Reiche']],
        ],
        mittel: [
          ['Wann wurde Bismarck preußischer Ministerpräsident?', '23. September 1862', ['18. Januar 1871', '1. April 1815', '20. März 1890']],
          ['Welcher Konflikt führte zu Bismarcks Berufung?', 'Der Verfassungskonflikt um die Heeresreform', ['Der Krieg gegen Dänemark', 'Der Kulturkampf', 'Der Weberaufstand']],
          ['Wie regierte Bismarck im Verfassungskonflikt?', 'Ohne genehmigten Haushalt', ['Mit Zustimmung des Parlaments', 'Gar nicht', 'Als Diktator mit Kaisertitel']],
          ['Welche Stellung wurde 1864 erstürmt?', 'Die Düppeler Schanzen', ['Die Festung Rastatt', 'Die Festung Metz', 'Das Danewerk']],
          ['Wann wurden die Düppeler Schanzen erstürmt?', '18. April 1864', ['3. Juli 1866', '2. September 1870', '18. Januar 1871']],
          ['Wer verwaltete nach 1864 Schleswig, wer Holstein?', 'Preußen Schleswig, Österreich Holstein', ['Österreich Schleswig, Preußen Holstein', 'Dänemark beide', 'Bayern beide']],
          ['Wann war die Schlacht bei Königgrätz?', '3. Juli 1866', ['18. April 1864', '1. September 1870', '18. Januar 1871']],
          ['In welchem Land liegt Königgrätz?', 'In Böhmen (heute Tschechien)', ['In Sachsen', 'In Schlesien', 'In Österreich']],
          ['Was geschah mit dem Deutschen Bund 1866?', 'Er wurde aufgelöst', ['Er wurde Kaiserreich', 'Er zog nach Wien', 'Er wurde vergrößert']],
          ['Welche Staaten annektierte Preußen 1866 unter anderem?', 'Hannover, Kurhessen, Nassau und Frankfurt', ['Bayern, Baden und Württemberg', 'Sachsen, Thüringen und Anhalt', 'Mecklenburg, Oldenburg und Lippe']],
          ['Welcher Bund wurde 1867 gegründet?', 'Der Norddeutsche Bund', ['Der Deutsche Bund', 'Der Rheinbund', 'Der Zollverein']],
          ['Wie waren die süddeutschen Staaten mit Preußen verbunden?', 'Durch geheime Schutz- und Trutzbündnisse', ['Gar nicht', 'Durch eine gemeinsame Krone', 'Durch einen Kirchenvertrag']],
          ['Welcher Thron löste 1870 die Krise aus?', 'Der spanische Thron', ['Der französische Thron', 'Der österreichische Thron', 'Der polnische Thron']],
          ['In welchem Kurort lehnte Wilhelm die französische Forderung ab?', 'Bad Ems', ['Baden-Baden', 'Bad Kissingen', 'Karlsbad']],
          ['Wann erklärte Frankreich Preußen den Krieg?', '19. Juli 1870', ['1. September 1870', '18. Januar 1871', '3. Juli 1866']],
          ['Wann wurde die französische Armee bei Sedan eingeschlossen?', '1. und 2. September 1870', ['18. Januar 1871', '19. Juli 1870', '10. Mai 1871']],
          ['An welchem Tag wurde das Kaiserreich proklamiert?', '18. Januar 1871', ['10. Mai 1871', '2. September 1870', '1. Januar 1871']],
          ['Welcher Maler hielt die Kaiserproklamation fest?', 'Anton von Werner', ['Adolph Menzel', 'Max Liebermann', 'Caspar David Friedrich']],
          ['Wie viel musste Frankreich 1871 zahlen?', 'Fünf Milliarden Francs', ['Fünf Millionen Francs', 'Fünfzig Milliarden Francs', 'Nichts']],
          ['Wem war der Reichskanzler verantwortlich?', 'Nur dem Kaiser', ['Dem Reichstag', 'Dem Volk', 'Dem Bundesrat']],
        ],
        schwer: [
          ['Seit wann war Wilhelm I. König von Preußen?', '1861', ['1858', '1862', '1871']],
          ['Wie lautet Bismarcks Satz vollständiger?', '„Nicht durch Reden und Majoritätsbeschlüsse … sondern durch Eisen und Blut“', ['„Wir Deutsche fürchten Gott, sonst nichts auf der Welt“', '„Politik ist die Kunst des Möglichen“', '„Der Lotse geht von Bord“']],
          ['Wie hieß der Hohenzollernprinz, der spanischer König werden sollte?', 'Leopold von Hohenzollern-Sigmaringen', ['Friedrich Karl von Preußen', 'Karl von Hohenzollern', 'Albrecht von Preußen']],
          ['Was verlangte der französische Botschafter in Bad Ems?', 'Eine Garantie für alle Zukunft', ['Die Abtretung der Pfalz', 'Geld', 'Die Auflösung des Norddeutschen Bundes']],
          ['Was tat Bismarck mit dem Bericht aus Ems?', 'Er kürzte ihn, sodass er beleidigend klang', ['Er verbrannte ihn', 'Er hielt ihn geheim', 'Er schickte ihn an den Papst']],
          ['Was geschah in Paris nach Sedan?', 'Die Republik wurde ausgerufen', ['Der Kaiser kehrte zurück', 'Der König von Preußen zog ein', 'Nichts']],
          ['Welchen Titel hätte Wilhelm I. lieber gehabt?', '„Kaiser von Deutschland“', ['„Deutscher Kaiser“', '„König der Deutschen“', '„Kaiser der Franken“']],
          ['Womit gewann Bismarck Ludwig II. für den Kaiserbrief?', 'Mit geheimen Geldzahlungen', ['Mit einem neuen Schloss', 'Mit dem Elsass', 'Mit einer Heirat']],
          ['An welchem Tag wurde der Frieden von Frankfurt geschlossen?', '10. Mai 1871', ['18. Januar 1871', '28. Juni 1871', '1. September 1871']],
          ['Aus wie vielen Staaten bestand das Kaiserreich?', '25', ['39', '16', '7']],
          ['Wie viele freie Städte gehörten zum Kaiserreich?', 'Drei', ['Vier', 'Sechs', 'Keine']],
          ['Welchen Status hatte Elsass-Lothringen im Kaiserreich?', 'Reichsland', ['Königreich', 'Freie Stadt', 'Kolonie']],
          ['Wie wurde der Reichstag gewählt?', 'Gleich und geheim von Männern ab 25', ['Nach Dreiklassenwahlrecht', 'Vom Kaiser ernannt', 'Von den Fürsten gewählt']],
          ['Was annektierte Preußen 1866 im Norden?', 'Schleswig-Holstein', ['Mecklenburg', 'Oldenburg', 'Bremen']],
          ['Welche Folge hatte der Frieden von Frankfurt für das deutsch-französische Verhältnis?', 'Er vergiftete es lange', ['Er machte beide zu Freunden', 'Er hatte keine Folgen', 'Er führte zu einem Bündnis']],
          ['Wo wurde der Frieden von 1866 zwischen Preußen und Österreich geschlossen?', 'In Prag', ['In Wien', 'In Berlin', 'In Dresden']],
          ['Welche Staaten standen 1866 auf Österreichs Seite?', 'Die meisten Mittelstaaten wie Bayern, Sachsen und Hannover', ['Keine', 'Nur Italien', 'Nur Dänemark']],
          ['Welcher Fluss trennte den Norddeutschen Bund von Süddeutschland?', 'Der Main', ['Die Donau', 'Der Rhein', 'Die Elbe']],
          ['Wie hieß das Schreiben Ludwigs II. an Wilhelm I.?', 'Kaiserbrief', ['Emser Depesche', 'Bayerischer Brief', 'Krönungsurkunde']],
          ['Welche Stadt belagerten deutsche Truppen 1870/71?', 'Paris', ['Brüssel', 'Lyon', 'Marseille']],
        ],
      },
    },
    {
      id: 'kaiserreich',
      title: 'Das Kaiserreich unter Bismarck und Wilhelm II.',
      date: '1871–1914',
      text: [
        'Bismarck sah in den Katholiken, die der Kirche in Rom folgten, eine Gefahr. Im Kulturkampf (ab 1871) verbot er Predigten mit politischem Inhalt (Kanzelparagraph), wies die Jesuiten aus (1872) und führte 1875 die Zivilehe auf dem Standesamt ein. Die katholische Zentrumspartei wurde dadurch nur stärker, und Bismarck beendete den Streit nach 1878 schrittweise.',
        'In der Außenpolitik wollte Bismarck das neue Reich schützen und Frankreich isolieren. 1878 vermittelte er auf dem Berliner Kongress als „ehrlicher Makler“ zwischen den Großmächten. Er schuf ein kunstvolles Bündnissystem: 1873 das Dreikaiserabkommen mit Österreich-Ungarn und Russland, 1879 den Zweibund mit Österreich-Ungarn, 1882 den Dreibund mit Österreich-Ungarn und Italien und 1887 den geheimen Rückversicherungsvertrag mit Russland.',
        'Zunächst lehnte Bismarck Kolonien ab, doch 1884/85 stellte das Reich Gebiete in Afrika und im Pazifik unter seinen „Schutz“: Deutsch-Südwestafrika (heute Namibia), Togo, Kamerun, Deutsch-Ostafrika (heute vor allem Tansania), Deutsch-Neuguinea und später Samoa sowie das Pachtgebiet Kiautschou mit Tsingtau in China. Auf der Berliner Kongokonferenz 1884/85 verständigten sich die Kolonialmächte über die Aufteilung Afrikas. In Deutsch-Südwestafrika erhoben sich 1904 die Herero und Nama gegen Landraub und Unterdrückung. Nach der Schlacht am Waterberg trieb General Lothar von Trotha die Herero in die Wüste und befahl ihre Vernichtung; Zehntausende starben. 2021 hat die Bundesregierung dies als Völkermord anerkannt. In Deutsch-Ostafrika schlug die Kolonialmacht 1905–1907 den Maji-Maji-Aufstand brutal nieder.',
        '1888 war das „Dreikaiserjahr“: Wilhelm I. starb am 9. März, sein Sohn Friedrich III. regierte, schwer an Kehlkopfkrebs erkrankt, nur 99 Tage, und dann wurde dessen 29-jähriger Sohn Wilhelm II. Kaiser. Wilhelm II. wollte selbst regieren und entließ Bismarck am 20. März 1890. Eine berühmte britische Karikatur zeigte das als „Der Lotse geht von Bord“. Der Rückversicherungsvertrag mit Russland wurde nicht verlängert – Russland näherte sich darauf Frankreich an. Bismarck starb 1898 in Friedrichsruh.',
        'Unter Wilhelm II. strebte Deutschland nach „Weltpolitik“. Staatssekretär Bernhard von Bülow forderte 1897 einen „Platz an der Sonne“. Admiral Alfred von Tirpitz ließ mit den Flottengesetzen ab 1898 eine große Kriegsflotte bauen – das führte zu einem Wettrüsten mit Großbritannien, das sich daraufhin Frankreich und Russland zuwandte. In den Marokkokrisen 1905 und 1911 stand Deutschland zunehmend isoliert da. Der Kaiser selbst sorgte mit unbedachten Äußerungen für Ärger, etwa 1908 in einem Interview mit der britischen Zeitung „Daily Telegraph“.',
        'Im Inneren wuchsen Wirtschaft, Städte und Wissenschaft rasant, aber Militär und Uniform genossen höchstes Ansehen. Das zeigte der Schuster Wilhelm Voigt, der am 16. Oktober 1906 in einer gebrauchten Hauptmannsuniform mit Soldaten das Rathaus von Köpenick besetzte und die Stadtkasse beschlagnahmte – der „Hauptmann von Köpenick“. 1894 wurde das Reichstagsgebäude von Paul Wallot fertig; die Inschrift „Dem deutschen Volke“ kam erst 1916 hinzu. Bei der Reichstagswahl 1912 wurde die SPD stärkste Partei.',
      ],
      quiz: {
        leicht: [
          ['Wie heißt Bismarcks Streit mit der katholischen Kirche?', 'Kulturkampf', ['Investiturstreit', 'Reformation', 'Kirchenkrieg']],
          ['Welche Ehe führte Bismarck 1875 ein?', 'Die Zivilehe auf dem Standesamt', ['Die Kirchenehe', 'Die Ehe für alle', 'Die Fernehe']],
          ['Welche Partei vertrat die Katholiken?', 'Das Zentrum', ['Die SPD', 'Die Konservativen', 'Die Liberalen']],
          ['Wie nannte man Bismarck auf dem Berliner Kongress?', '„Ehrlicher Makler“', ['„Eiserner Händler“', '„Kaiser Europas“', '„Friedensfürst“']],
          ['Welches Land wollte Bismarck isolieren?', 'Frankreich', ['England', 'Russland', 'Österreich']],
          ['Mit welchem Land schloss Deutschland 1879 den Zweibund?', 'Mit Österreich-Ungarn', ['Mit Russland', 'Mit Italien', 'Mit England']],
          ['Welches Land kam 1882 im Dreibund hinzu?', 'Italien', ['Russland', 'Frankreich', 'Spanien']],
          ['Wie hieß die größte deutsche Kolonie in Afrika im Südwesten?', 'Deutsch-Südwestafrika', ['Deutsch-Kongo', 'Deutsch-Marokko', 'Deutsch-Ägypten']],
          ['Wie heißt Deutsch-Südwestafrika heute?', 'Namibia', ['Südafrika', 'Angola', 'Botswana']],
          ['Welche Völker erhoben sich 1904 in Deutsch-Südwestafrika?', 'Die Herero und Nama', ['Die Zulu und Massai', 'Die Bantu und Pygmäen', 'Die Tuareg und Berber']],
          ['Wie nennt die Bundesregierung heute die Verbrechen an den Herero und Nama?', 'Völkermord', ['Einen Unfall', 'Einen fairen Krieg', 'Eine Expedition']],
          ['Wie nennt man das Jahr 1888?', 'Dreikaiserjahr', ['Revolutionsjahr', 'Gründerjahr', 'Kriegsjahr']],
          ['Welcher Kaiser entließ Bismarck?', 'Wilhelm II.', ['Wilhelm I.', 'Friedrich III.', 'Ludwig II.']],
          ['In welchem Jahr wurde Bismarck entlassen?', '1890', ['1871', '1888', '1914']],
          ['Wie heißt die berühmte Karikatur zu Bismarcks Entlassung?', '„Der Lotse geht von Bord“', ['„Der Kapitän geht unter“', '„Der Kanzler fällt“', '„Der Alte geht“']],
          ['Was forderte Bülow 1897 für Deutschland?', 'Einen „Platz an der Sonne“', ['Einen Platz im Schatten', 'Frieden mit allen', 'Die Abschaffung der Flotte']],
          ['Welcher Admiral ließ eine große Kriegsflotte bauen?', 'Alfred von Tirpitz', ['Horatio Nelson', 'Karl Dönitz', 'Graf Spee']],
          ['Mit welchem Land kam es zu einem Wettrüsten der Flotten?', 'Großbritannien', ['Frankreich', 'Russland', 'Italien']],
          ['Wer war der „Hauptmann von Köpenick“?', 'Ein Schuster in Uniform', ['Ein echter Offizier', 'Der Kaiser', 'Ein Bürgermeister']],
          ['Welche Inschrift trägt das Reichstagsgebäude?', '„Dem deutschen Volke“', ['„Einigkeit und Recht und Freiheit“', '„Gott mit uns“', '„Alle Macht dem Volke“']],
        ],
        mittel: [
          ['Was verbot der Kanzelparagraph?', 'Politische Predigten', ['Kirchenglocken', 'Gottesdienste', 'Prozessionen']],
          ['Welcher Orden wurde 1872 aus Deutschland ausgewiesen?', 'Die Jesuiten', ['Die Benediktiner', 'Die Franziskaner', 'Die Diakonissen']],
          ['Wie wirkte sich der Kulturkampf auf das Zentrum aus?', 'Es wurde stärker', ['Es wurde verboten', 'Es löste sich auf', 'Es wurde evangelisch']],
          ['Wann fand der Berliner Kongress statt?', '1878', ['1871', '1884', '1890']],
          ['Welches Abkommen schloss Deutschland 1873 mit Österreich-Ungarn und Russland?', 'Das Dreikaiserabkommen', ['Den Dreibund', 'Den Zweibund', 'Die Entente']],
          ['Welcher geheime Vertrag mit Russland wurde 1887 geschlossen?', 'Der Rückversicherungsvertrag', ['Der Zweibund', 'Der Vertrag von Rapallo', 'Der Hitler-Stalin-Pakt']],
          ['Wann erwarb das Reich seine ersten Kolonien?', '1884/85', ['1871', '1900', '1914']],
          ['Welche Konferenz über die Aufteilung Afrikas fand in Berlin statt?', 'Die Kongokonferenz', ['Die Afrikakonferenz von Wien', 'Die Wannseekonferenz', 'Die Potsdamer Konferenz']],
          ['Welche Kolonie lag im heutigen Tansania?', 'Deutsch-Ostafrika', ['Kamerun', 'Togo', 'Deutsch-Südwestafrika']],
          ['Welches Pachtgebiet hatte Deutschland in China?', 'Kiautschou mit Tsingtau', ['Hongkong', 'Macau', 'Shanghai']],
          ['Welcher General befahl die Vernichtung der Herero?', 'Lothar von Trotha', ['Paul von Lettow-Vorbeck', 'Erich Ludendorff', 'Hermann von Wissmann']],
          ['Nach welcher Schlacht wurden die Herero in die Wüste getrieben?', 'Nach der Schlacht am Waterberg', ['Nach der Schlacht bei Sedan', 'Nach der Schlacht bei Tanga', 'Nach der Schlacht am Kilimandscharo']],
          ['Welcher Aufstand fand 1905–1907 in Deutsch-Ostafrika statt?', 'Der Maji-Maji-Aufstand', ['Der Boxeraufstand', 'Der Mau-Mau-Aufstand', 'Der Herero-Aufstand']],
          ['Wann starb Wilhelm I.?', '9. März 1888', ['18. Januar 1888', '20. März 1890', '15. Juni 1888']],
          ['Wie lange regierte Friedrich III.?', '99 Tage', ['99 Jahre', '9 Jahre', '9 Tage']],
          ['Woran litt Friedrich III.?', 'An Kehlkopfkrebs', ['An Tuberkulose', 'An der Pest', 'An einer Kriegsverletzung']],
          ['Wann wurde Bismarck entlassen?', '20. März 1890', ['9. März 1888', '18. Januar 1890', '1. April 1890']],
          ['Welche Folge hatte die Nichtverlängerung des Rückversicherungsvertrags?', 'Russland näherte sich Frankreich an', ['Russland wurde Deutschlands Verbündeter', 'Frankreich wurde isoliert', 'Nichts']],
          ['Ab wann gab es die Flottengesetze?', '1898', ['1871', '1910', '1888']],
          ['Wann besetzte der Hauptmann von Köpenick das Rathaus?', '16. Oktober 1906', ['9. November 1918', '18. Januar 1906', '1. Mai 1906']],
        ],
        schwer: [
          ['Wann wurde die Zivilehe eingeführt?', '1875', ['1871', '1878', '1890']],
          ['Wann wurden die Jesuiten ausgewiesen?', '1872', ['1875', '1871', '1880']],
          ['Ab wann beendete Bismarck den Kulturkampf schrittweise?', 'Nach 1878', ['Nach 1871', 'Nach 1890', 'Nie']],
          ['Wie hieß der Pazifik-Besitz Deutschlands neben Neuguinea später auch?', 'Samoa', ['Hawaii', 'Tahiti', 'Fidschi']],
          ['Wann hat die Bundesregierung den Völkermord an Herero und Nama anerkannt?', '2021', ['1990', '2004', '1949']],
          ['Wie alt war Wilhelm II. bei seinem Regierungsantritt?', '29 Jahre', ['19 Jahre', '49 Jahre', '59 Jahre']],
          ['Wo starb Bismarck?', 'In Friedrichsruh', ['In Berlin', 'In Schönhausen', 'In Varzin']],
          ['Wann starb Bismarck?', '1898', ['1890', '1888', '1914']],
          ['Wann fanden die Marokkokrisen statt?', '1905 und 1911', ['1871 und 1878', '1898 und 1900', '1912 und 1913']],
          ['Mit welcher Zeitung gab Wilhelm II. 1908 ein umstrittenes Interview?', 'Daily Telegraph', ['The Times', 'Le Monde', 'New York Times']],
          ['Wer war der Hauptmann von Köpenick wirklich?', 'Der Schuster Wilhelm Voigt', ['Der Offizier Max von Köpenick', 'Der Bürgermeister von Köpenick', 'Der Schauspieler Heinz Rühmann']],
          ['Was beschlagnahmte der Hauptmann von Köpenick?', 'Die Stadtkasse', ['Die Kanonen', 'Das Rathaus für immer', 'Einen Zug']],
          ['Wer entwarf das Reichstagsgebäude?', 'Paul Wallot', ['Karl Friedrich Schinkel', 'Norman Foster', 'Albert Speer']],
          ['Wann wurde das Reichstagsgebäude fertig?', '1894', ['1871', '1916', '1933']],
          ['Wann kam die Inschrift „Dem deutschen Volke“ hinzu?', '1916', ['1894', '1871', '1919']],
          ['Welche Partei wurde 1912 stärkste Kraft im Reichstag?', 'Die SPD', ['Das Zentrum', 'Die Konservativen', 'Die Nationalliberalen']],
          ['Welchen Posten hatte Bülow 1897?', 'Staatssekretär des Auswärtigen', ['Reichskanzler', 'Kriegsminister', 'Admiral']],
          ['Welche Kolonien lagen in Westafrika?', 'Togo und Kamerun', ['Namibia und Tansania', 'Samoa und Neuguinea', 'Kiautschou und Tsingtau']],
          ['Welche Staaten wandten sich wegen der deutschen Flotte einander zu?', 'Großbritannien, Frankreich und Russland', ['Italien, Spanien und Portugal', 'Österreich, Italien und Türkei', 'USA, Japan und China']],
          ['Mit welchem Land stand Bismarck durch den Rückversicherungsvertrag geheim im Bunde?', 'Russland', ['Frankreich', 'Großbritannien', 'Italien']],
        ],
      },
    },
  ],
};
