import type { HistEvent } from '../types';

export const NAPOLEON: HistEvent = {
  id: 'napoleon',
  title: 'Napoleon und das Ende des alten Reiches',
  date: '1789–1815',
  text: [
    'Die Französische Revolution und die Kriege Napoleons wirbelten Deutschland durcheinander: Das tausendjährige Heilige Römische Reich ging unter, viele kleine Herrschaften verschwanden, Preußen wurde gedemütigt und erneuerte sich – bis Napoleon in den Befreiungskriegen besiegt wurde.',
  ],
  subtopics: [
    {
      id: 'ende-des-reiches',
      title: 'Napoleon und das Ende des Reiches',
      date: '1789–1810',
      text: [
        '1789 begann in Paris die Französische Revolution mit dem Sturm auf die Bastille am 14. Juli. Ihre Ideen – Freiheit, Gleichheit, Brüderlichkeit – begeisterten auch viele Deutsche. Ab 1792 führten die europäischen Monarchien Krieg gegen das revolutionäre Frankreich, und französische Truppen besetzten das linke Rheinufer. 1793 entstand in Mainz kurzzeitig die „Mainzer Republik“, die erste Republik auf deutschem Boden. Der junge General Napoleon Bonaparte stieg zum mächtigsten Mann Frankreichs auf und krönte sich 1804 selbst zum Kaiser der Franzosen.',
        'Die deutschen Fürsten, die links des Rheins Land verloren hatten, wurden rechts des Rheins entschädigt. Im Reichsdeputationshauptschluss vom 25. Februar 1803 wurden fast alle geistlichen Fürstentümer aufgelöst (Säkularisation) und die meisten Reichsstädte und kleinen Herrschaften größeren Staaten zugeschlagen (Mediatisierung). Nur sechs Reichsstädte blieben übrig: Hamburg, Bremen, Lübeck, Frankfurt, Augsburg und Nürnberg. Gewinner waren vor allem Baden, Württemberg und Bayern.',
        'In der Dreikaiserschlacht bei Austerlitz am 2. Dezember 1805 besiegte Napoleon Österreich und Russland. Mit seiner Unterstützung wurden Bayern und Württemberg am 1. Januar 1806 Königreiche, Baden ein Großherzogtum. Am 12. Juli 1806 gründeten 16 deutsche Staaten unter Napoleons Schutz den Rheinbund und traten aus dem Reich aus. Daraufhin legte Kaiser Franz II. am 6. August 1806 die Kaiserkrone nieder – das Heilige Römische Reich hörte nach rund 850 Jahren auf zu bestehen. Franz hatte sich schon 1804 zum Kaiser von Österreich (als Franz I.) erklärt.',
        'Preußen, das seit dem Frieden von Basel 1795 neutral geblieben war, erklärte Napoleon 1806 den Krieg und wurde am 14. Oktober 1806 in der Doppelschlacht bei Jena und Auerstedt vernichtend geschlagen. Am 27. Oktober zog Napoleon in Berlin ein und ließ die Quadriga vom Brandenburger Tor nach Paris bringen. Königin Luise traf Napoleon 1807 in Tilsit und bat vergeblich um mildere Bedingungen. Im Frieden von Tilsit verlor Preußen etwa die Hälfte seines Gebiets: Aus dem Land westlich der Elbe entstand das Königreich Westphalen mit der Hauptstadt Kassel für Napoleons Bruder Jérôme, aus den polnischen Gebieten das Herzogtum Warschau. Luise starb 1810 und wurde zur verehrten Symbolfigur Preußens.',
        'Napoleon brachte auch Neuerungen. In den Rheinbundstaaten und den französisch beherrschten Gebieten führte er den „Code civil“ (Code Napoléon) ein, ein modernes Gesetzbuch mit Gleichheit vor dem Gesetz. Juden erhielten dort oft erstmals gleiche Rechte, Zünfte und Adelsvorrechte wurden eingeschränkt. Gleichzeitig mussten die Verbündeten Soldaten für Napoleons Kriege stellen und hohe Abgaben zahlen. Die Kontinentalsperre von 1806, die den Handel mit Großbritannien verbot, schadete vielen Kaufleuten.',
        'In dieser Zeit wuchs ein neues Nationalgefühl. Der Philosoph Johann Gottlieb Fichte hielt 1807/08 in Berlin seine „Reden an die deutsche Nation“, und Friedrich Ludwig Jahn, der „Turnvater“, eröffnete 1811 in der Berliner Hasenheide den ersten Turnplatz, um die Jugend für den Kampf gegen Napoleon zu stärken.',
      ],
      quiz: {
        leicht: [
          ['In welchem Jahr begann die Französische Revolution?', '1789', ['1806', '1815', '1848']],
          ['Welche drei Ideen verbreitete die Französische Revolution?', 'Freiheit, Gleichheit, Brüderlichkeit', ['Gott, König, Vaterland', 'Ordnung, Fleiß, Gehorsam', 'Einigkeit und Recht und Freiheit']],
          ['Welcher französische Herrscher eroberte große Teile Europas?', 'Napoleon', ['Ludwig XIV.', 'Karl der Große', 'Robespierre']],
          ['In welchem Jahr krönte sich Napoleon zum Kaiser?', '1804', ['1789', '1815', '1799']],
          ['In welchem Jahr endete das Heilige Römische Reich?', '1806', ['1648', '1815', '1871']],
          ['Welcher Kaiser legte 1806 die Krone nieder?', 'Franz II.', ['Joseph II.', 'Karl VI.', 'Wilhelm I.']],
          ['Wie hieß der Bund deutscher Staaten unter Napoleons Schutz?', 'Rheinbund', ['Deutscher Bund', 'Norddeutscher Bund', 'Hanse']],
          ['Welche Staaten wurden 1806 Königreiche?', 'Bayern und Württemberg', ['Baden und Hessen', 'Sachsen und Hannover', 'Preußen und Österreich']],
          ['Wo wurde Preußen 1806 vernichtend geschlagen?', 'Bei Jena und Auerstedt', ['Bei Leipzig', 'Bei Waterloo', 'Bei Austerlitz']],
          ['Welche Figur ließ Napoleon vom Brandenburger Tor nach Paris bringen?', 'Die Quadriga', ['Die Siegessäule', 'Den Berliner Bären', 'Die Germania']],
          ['Welche preußische Königin traf Napoleon in Tilsit?', 'Königin Luise', ['Königin Sophie Charlotte', 'Kaiserin Augusta', 'Maria Theresia']],
          ['Wie viel seines Gebiets verlor Preußen 1807 etwa?', 'Die Hälfte', ['Nichts', 'Ein Zehntel', 'Alles']],
          ['Welches Gesetzbuch führte Napoleon ein?', 'Den Code civil', ['Die Goldene Bulle', 'Das BGB', 'Den Sachsenspiegel']],
          ['Was verbot die Kontinentalsperre?', 'Den Handel mit Großbritannien', ['Reisen nach Amerika', 'Den Bau von Burgen', 'Die Religion']],
          ['Wer war der „Turnvater“?', 'Friedrich Ludwig Jahn', ['Johann Gottlieb Fichte', 'Freiherr vom Stein', 'Theodor Körner']],
          ['Wo wurde Kaiser Napoleon zuerst politisch berühmt?', 'In Frankreich', ['In England', 'In Russland', 'In Spanien']],
          ['Welche Stadt war Hauptstadt des Königreichs Westphalen?', 'Kassel', ['Münster', 'Hannover', 'Köln']],
          ['Wer wurde König von Westphalen?', 'Napoleons Bruder Jérôme', ['Napoleon selbst', 'Königin Luise', 'Ein Hohenzoller']],
          ['Welche Stadt besetzte Napoleon im Oktober 1806?', 'Berlin', ['Wien', 'Moskau', 'London']],
          ['Welche Gruppe erhielt im Code civil oft erstmals gleiche Rechte?', 'Die Juden', ['Die Adligen', 'Die Bischöfe', 'Die Könige']],
        ],
        mittel: [
          ['Mit welchem Ereignis begann die Französische Revolution?', 'Mit dem Sturm auf die Bastille', ['Mit der Krönung Napoleons', 'Mit der Hinrichtung des Königs', 'Mit der Schlacht bei Valmy']],
          ['Welche Republik entstand 1793 als erste auf deutschem Boden?', 'Die Mainzer Republik', ['Die Kölner Republik', 'Die Badische Republik', 'Die Hamburger Republik']],
          ['Wann wurde der Reichsdeputationshauptschluss beschlossen?', '1803', ['1806', '1789', '1815']],
          ['Wie nennt man die Auflösung der geistlichen Fürstentümer?', 'Säkularisation', ['Mediatisierung', 'Reformation', 'Restauration']],
          ['Wie nennt man die Eingliederung kleiner Herrschaften in größere Staaten?', 'Mediatisierung', ['Säkularisation', 'Annexion', 'Kolonisierung']],
          ['Wie viele Reichsstädte blieben 1803 übrig?', 'Sechs', ['Keine', 'Sechzig', 'Drei']],
          ['Welche Staaten gewannen 1803 besonders?', 'Baden, Württemberg und Bayern', ['Preußen, Sachsen und Hannover', 'Österreich, Tirol und Salzburg', 'Mainz, Köln und Trier']],
          ['Wie nennt man die Schlacht bei Austerlitz auch?', 'Dreikaiserschlacht', ['Völkerschlacht', 'Doppelschlacht', 'Schlacht der Nationen']],
          ['Wann fand die Schlacht bei Austerlitz statt?', '2. Dezember 1805', ['14. Oktober 1806', '18. Juni 1815', '16. Oktober 1813']],
          ['Was wurde Baden 1806?', 'Ein Großherzogtum', ['Ein Königreich', 'Eine Republik', 'Ein Teil Frankreichs']],
          ['Wann wurde der Rheinbund gegründet?', '12. Juli 1806', ['6. August 1806', '1. Januar 1806', '14. Oktober 1806']],
          ['Wie viele Staaten gründeten den Rheinbund?', '16', ['39', '6', '100']],
          ['An welchem Tag legte Franz II. die Kaiserkrone nieder?', '6. August 1806', ['12. Juli 1806', '2. Dezember 1805', '1. Januar 1806']],
          ['Welchen Titel hatte Franz schon 1804 angenommen?', 'Kaiser von Österreich', ['König von Böhmen', 'Kaiser der Deutschen', 'König von Ungarn']],
          ['Wann war die Doppelschlacht bei Jena und Auerstedt?', '14. Oktober 1806', ['2. Dezember 1805', '16. Oktober 1813', '7. Juli 1807']],
          ['Was entstand aus den polnischen Gebieten Preußens 1807?', 'Das Herzogtum Warschau', ['Das Königreich Polen', 'Das Königreich Galizien', 'Das Großherzogtum Posen']],
          ['Wann starb Königin Luise?', '1810', ['1807', '1813', '1815']],
          ['Wann verhängte Napoleon die Kontinentalsperre?', '1806', ['1803', '1812', '1789']],
          ['Wer hielt die „Reden an die deutsche Nation“?', 'Johann Gottlieb Fichte', ['Friedrich Ludwig Jahn', 'Ernst Moritz Arndt', 'Hegel']],
          ['Wo eröffnete Jahn 1811 den ersten Turnplatz?', 'In der Berliner Hasenheide', ['Im Leipziger Rosental', 'Im Englischen Garten', 'Auf der Wartburg']],
        ],
        schwer: [
          ['An welchem Tag wurde der Reichsdeputationshauptschluss beschlossen?', '25. Februar 1803', ['6. August 1806', '14. Juli 1789', '12. Juli 1806']],
          ['Welche sechs Reichsstädte blieben 1803 bestehen?', 'Hamburg, Bremen, Lübeck, Frankfurt, Augsburg und Nürnberg', ['Köln, Aachen, Mainz, Worms, Speyer und Ulm', 'Berlin, Dresden, München, Wien, Prag und Kassel', 'Regensburg, Nürnberg, Augsburg, Ulm, Köln und Frankfurt']],
          ['Wie lange hatte das Heilige Römische Reich etwa bestanden?', 'Rund 850 Jahre (seit 962)', ['Rund 150 Jahre', 'Rund 2000 Jahre', 'Rund 300 Jahre']],
          ['Wann zog Napoleon in Berlin ein?', '27. Oktober 1806', ['14. Oktober 1806', '1. Januar 1807', '6. August 1806']],
          ['In welchem Jahr wurde der Frieden von Tilsit geschlossen?', '1807', ['1806', '1809', '1812']],
          ['Wann wurde die Mainzer Republik ausgerufen?', '1793', ['1789', '1803', '1806']],
          ['Welches Gebiet besetzten die Franzosen in den Revolutionskriegen?', 'Das linke Rheinufer', ['Ganz Preußen', 'Bayern', 'Ostpreußen']],
          ['Wie hießen Bayern und Württemberg ab dem 1. Januar 1806?', 'Königreiche', ['Kurfürstentümer', 'Großherzogtümer', 'Republiken']],
          ['Wie heißt der Code civil auch?', 'Code Napoléon', ['Code Louis', 'Code Rhénan', 'Code Bonaparte']],
          ['Was wurde durch den Code civil eingeschränkt?', 'Zünfte und Adelsvorrechte', ['Die Gleichheit vor dem Gesetz', 'Die Rechte der Juden', 'Der Handel mit Frankreich']],
          ['Wer gewann Land rechts des Rheins als Entschädigung?', 'Fürsten, die links des Rheins Land verloren hatten', ['Die Reichsstädte', 'Die Bischöfe', 'Napoleon selbst']],
          ['Welche Länder besiegte Napoleon bei Austerlitz?', 'Österreich und Russland', ['Preußen und England', 'Spanien und Portugal', 'Schweden und Dänemark']],
          ['Wie lange war Preußen vor 1806 im Krieg gegen Napoleon neutral geblieben?', 'Seit 1795, also über zehn Jahre', ['Gar nicht', 'Nur einen Monat', 'Seit 1648']],
          ['Welche Pflicht hatten die Rheinbundstaaten gegenüber Napoleon?', 'Sie mussten Soldaten stellen', ['Sie mussten katholisch werden', 'Sie mussten Französisch sprechen', 'Sie durften keine Steuern erheben']],
          ['Welcher Fluss bildete die Grenze, westlich derer Preußen 1807 alles verlor?', 'Die Elbe', ['Die Oder', 'Der Rhein', 'Die Weser']],
          ['Wann eröffnete Jahn den ersten Turnplatz?', '1811', ['1806', '1813', '1817']],
          ['Wann hielt Fichte seine „Reden an die deutsche Nation“?', '1807/08', ['1789', '1813', '1817']],
          ['Wann stürmten die Pariser die Bastille?', '14. Juli 1789', ['14. Oktober 1806', '18. Juni 1815', '1. Januar 1789']],
          ['Wann begannen die Kriege der Monarchien gegen das revolutionäre Frankreich?', '1792', ['1789', '1799', '1804']],
          ['Wozu wurde Königin Luise nach ihrem Tod?', 'Zu einer verehrten Symbolfigur Preußens', ['Zu einer Heiligen der Kirche', 'Zur Kaiserin', 'Zur Namensgeberin Westphalens']],
        ],
      },
    },
    {
      id: 'befreiungskriege',
      title: 'Reformen, Befreiungskriege und Wiener Kongress',
      date: '1807–1815',
      text: [
        'Nach der Niederlage von 1806 erneuerte sich Preußen in den Preußischen Reformen. Freiherr vom Stein hob im Oktoberedikt vom 9. Oktober 1807 die Erbuntertänigkeit der Bauern auf („Bauernbefreiung“) und gab 1808 mit der Städteordnung den Städten Selbstverwaltung. Staatskanzler Karl August von Hardenberg führte 1810/11 die Gewerbefreiheit ein und gab 1812 mit dem Judenedikt den Juden weitgehende Bürgerrechte. Scharnhorst und Gneisenau reformierten das Heer: Prügelstrafen wurden abgeschafft, Offiziersstellen auch Bürgerlichen geöffnet, und 1813/14 wurde die allgemeine Wehrpflicht eingeführt. Wilhelm von Humboldt erneuerte das Bildungswesen mit dem humanistischen Gymnasium und gründete 1810 die Berliner Universität.',
        '1812 zog Napoleon mit der „Grande Armée“ von rund 600.000 Soldaten gegen Russland. Er erreichte Moskau, doch die Stadt brannte, und im eisigen Winter musste er sich zurückziehen; beim Übergang über die Beresina starben Zehntausende. Nur ein Bruchteil des Heeres kam zurück. Am 30. Dezember 1812 schloss der preußische General Yorck in der Konvention von Tauroggen eigenmächtig einen Waffenstillstand mit den Russen.',
        'Im März 1813 rief König Friedrich Wilhelm III. mit dem Aufruf „An mein Volk“ zum Kampf gegen Napoleon auf und stiftete am 10. März das Eiserne Kreuz. Freiwillige meldeten sich, etwa im Lützowschen Freikorps, dessen Uniformen schwarz mit roten Aufschlägen und goldenen Knöpfen waren – darauf gehen die Farben Schwarz-Rot-Gold zurück. Zu den Freiwilligen gehörte der Dichter Theodor Körner.',
        'Vom 16. bis 19. Oktober 1813 besiegten Preußen, Russen, Österreicher und Schweden Napoleon in der Völkerschlacht bei Leipzig, der bis dahin größten Schlacht der Geschichte mit rund 600.000 Soldaten und mehr als 90.000 Toten und Verwundeten. Hundert Jahre später, 1913, wurde dort das Völkerschlachtdenkmal eingeweiht. 1814 zogen die Verbündeten in Paris ein, und Napoleon wurde auf die Insel Elba verbannt. 1815 kehrte er für „hundert Tage“ zurück, wurde aber am 18. Juni 1815 bei Waterloo von den Briten unter Wellington und den Preußen unter Blücher endgültig geschlagen. Er starb 1821 in der Verbannung auf St. Helena.',
        'Von September 1814 bis Juni 1815 ordneten die Großmächte auf dem Wiener Kongress Europa neu. Gastgeber war der österreichische Staatskanzler Fürst Metternich. Ziel war die Restauration, die Wiederherstellung der alten Ordnung, mit den Grundsätzen der Legitimität der Fürsten und des Gleichgewichts der Mächte. Wegen der vielen Bälle spottete man: „Der Kongress tanzt.“ Preußen erhielt das Rheinland, Westfalen und einen großen Teil Sachsens.',
        'Statt eines neuen Reiches entstand am 8. Juni 1815 der Deutsche Bund, ein lockerer Zusammenschluss von 39 souveränen Staaten (anfangs 41), darunter vier freie Städte. Seine Bundesversammlung tagte in Frankfurt am Main unter dem Vorsitz Österreichs. Viele, die gegen Napoleon gekämpft hatten, waren enttäuscht: Sie hatten auf einen deutschen Nationalstaat mit Verfassung gehofft. Im September 1815 schlossen Russland, Österreich und Preußen außerdem die „Heilige Allianz“ zum Schutz der monarchischen Ordnung.',
      ],
      quiz: {
        leicht: [
          ['Welcher preußische Reformer befreite die Bauern?', 'Freiherr vom Stein', ['Fürst Metternich', 'Napoleon', 'Bismarck']],
          ['Welcher Reformer gründete die Berliner Universität?', 'Wilhelm von Humboldt', ['Alexander von Humboldt', 'Hardenberg', 'Scharnhorst']],
          ['Welche Pflicht wurde 1813/14 in Preußen eingeführt?', 'Die allgemeine Wehrpflicht', ['Die Schulpflicht', 'Die Steuerpflicht', 'Die Kirchenpflicht']],
          ['Gegen welches Land zog Napoleon 1812?', 'Russland', ['England', 'Spanien', 'Österreich']],
          ['Welche Stadt erreichte Napoleon 1812?', 'Moskau', ['Sankt Petersburg', 'Kiew', 'Warschau']],
          ['Was zwang Napoleon zum Rückzug aus Russland?', 'Der Brand Moskaus und der Winter', ['Eine Pest', 'Ein Erdbeben', 'Ein Aufstand in Paris']],
          ['Welcher Orden wurde 1813 gestiftet?', 'Das Eiserne Kreuz', ['Der Pour le Mérite', 'Der Schwarze Adlerorden', 'Das Bundesverdienstkreuz']],
          ['Wo wurde Napoleon 1813 besiegt?', 'In der Völkerschlacht bei Leipzig', ['Bei Waterloo', 'Bei Austerlitz', 'Bei Jena']],
          ['Wo wurde Napoleon 1815 endgültig besiegt?', 'Bei Waterloo', ['Bei Leipzig', 'Bei Moskau', 'Bei Sedan']],
          ['Welcher preußische General kämpfte bei Waterloo?', 'Blücher', ['Moltke', 'Yorck', 'Clausewitz']],
          ['Welcher britische Feldherr siegte bei Waterloo?', 'Wellington', ['Nelson', 'Churchill', 'Marlborough']],
          ['Auf welche Insel wurde Napoleon zuerst verbannt?', 'Elba', ['Korsika', 'St. Helena', 'Sizilien']],
          ['Wo starb Napoleon?', 'Auf St. Helena', ['Auf Elba', 'In Paris', 'Auf Korsika']],
          ['In welcher Stadt wurde Europa 1814/15 neu geordnet?', 'Wien', ['Paris', 'Berlin', 'London']],
          ['Wer war Gastgeber des Wiener Kongresses?', 'Fürst Metternich', ['Bismarck', 'Napoleon', 'Freiherr vom Stein']],
          ['Was spottete man über den Wiener Kongress?', '„Der Kongress tanzt“', ['„Der Kongress schläft“', '„Der Kongress streitet“', '„Der Kongress isst“']],
          ['Welcher Bund entstand 1815?', 'Der Deutsche Bund', ['Der Rheinbund', 'Der Norddeutsche Bund', 'Der Zollverein']],
          ['Worauf gehen die Farben Schwarz-Rot-Gold zurück?', 'Auf die Uniformen des Lützowschen Freikorps', ['Auf die Flagge Napoleons', 'Auf das Wappen Bayerns', 'Auf die Farben der Hanse']],
          ['Was bedeutet Restauration?', 'Wiederherstellung der alten Ordnung', ['Bau von Restaurants', 'Revolution', 'Gründung eines Nationalstaats']],
          ['Welches Denkmal steht in Leipzig?', 'Das Völkerschlachtdenkmal', ['Das Hermannsdenkmal', 'Die Siegessäule', 'Die Walhalla']],
        ],
        mittel: [
          ['Wie heißt Steins Erlass zur Bauernbefreiung?', 'Oktoberedikt', ['Märzedikt', 'Judenedikt', 'Toleranzedikt']],
          ['Was gab die Städteordnung von 1808 den Städten?', 'Selbstverwaltung', ['Eigene Armeen', 'Das Münzrecht', 'Unabhängigkeit vom König']],
          ['Welcher Staatskanzler führte die Gewerbefreiheit ein?', 'Hardenberg', ['Stein', 'Metternich', 'Humboldt']],
          ['Was gab das Judenedikt von 1812 den Juden?', 'Weitgehende Bürgerrechte', ['Eine eigene Stadt', 'Steuerfreiheit', 'Das Recht, König zu werden']],
          ['Welche Generäle reformierten das preußische Heer?', 'Scharnhorst und Gneisenau', ['Blücher und Yorck', 'Moltke und Roon', 'Tilly und Pappenheim']],
          ['Was wurde in der Heeresreform abgeschafft?', 'Die Prügelstrafe', ['Die Kavallerie', 'Die Uniform', 'Das Gewehr']],
          ['Wann wurde die Berliner Universität gegründet?', '1810', ['1806', '1815', '1848']],
          ['Wie groß war Napoleons „Grande Armée“ etwa?', 'Rund 600.000 Soldaten', ['Rund 60.000 Soldaten', 'Rund 6 Millionen Soldaten', 'Rund 6000 Soldaten']],
          ['An welchem Fluss starben auf dem Rückzug Zehntausende?', 'An der Beresina', ['An der Wolga', 'An der Elbe', 'An der Weichsel']],
          ['Welcher General schloss in Tauroggen einen Waffenstillstand mit Russland?', 'Yorck', ['Blücher', 'Gneisenau', 'Scharnhorst']],
          ['Wie heißt der Aufruf Friedrich Wilhelms III. von 1813?', '„An mein Volk“', ['„An die Nation“', '„An die Waffen“', '„An meine Soldaten“']],
          ['Welcher Dichter kämpfte im Lützowschen Freikorps?', 'Theodor Körner', ['Heinrich Heine', 'Goethe', 'Schiller']],
          ['Von wann bis wann dauerte die Völkerschlacht?', '16. bis 19. Oktober 1813', ['14. Oktober 1806', '18. Juni 1815', '1. bis 3. September 1870']],
          ['Wann wurde das Völkerschlachtdenkmal eingeweiht?', '1913', ['1815', '1871', '1933']],
          ['Wie lange dauerte Napoleons Rückkehr 1815?', 'Etwa hundert Tage', ['Ein Jahr', 'Zehn Tage', 'Drei Jahre']],
          ['Welche Gebiete erhielt Preußen auf dem Wiener Kongress?', 'Das Rheinland, Westfalen und einen Teil Sachsens', ['Bayern und Württemberg', 'Böhmen und Mähren', 'Hannover und Holstein']],
          ['Aus wie vielen Staaten bestand der Deutsche Bund?', '39', ['16', '300', '7']],
          ['Wo tagte die Bundesversammlung des Deutschen Bundes?', 'In Frankfurt am Main', ['In Berlin', 'In Wien', 'In Regensburg']],
          ['Welcher Staat führte den Vorsitz im Deutschen Bund?', 'Österreich', ['Preußen', 'Bayern', 'Sachsen']],
          ['Welche drei Mächte schlossen 1815 die Heilige Allianz?', 'Russland, Österreich und Preußen', ['England, Frankreich und Spanien', 'Bayern, Sachsen und Hannover', 'Preußen, Schweden und Dänemark']],
        ],
        schwer: [
          ['An welchem Tag wurde das Oktoberedikt erlassen?', '9. Oktober 1807', ['14. Oktober 1806', '16. Oktober 1813', '9. November 1807']],
          ['Wann führte Hardenberg die Gewerbefreiheit ein?', '1810/11', ['1807', '1815', '1834']],
          ['Wann wurde das Eiserne Kreuz gestiftet?', '10. März 1813', ['16. Oktober 1813', '18. Juni 1815', '9. Oktober 1807']],
          ['An welchem Tag wurde die Konvention von Tauroggen geschlossen?', '30. Dezember 1812', ['10. März 1813', '1. Januar 1813', '14. Oktober 1812']],
          ['Wie viele Tote und Verwundete forderte die Völkerschlacht etwa?', 'Mehr als 90.000', ['Rund 9000', 'Rund 900', 'Über eine Million']],
          ['Wie viele Soldaten kämpften in der Völkerschlacht etwa?', 'Rund 600.000', ['Rund 60.000', 'Rund 6 Millionen', 'Rund 6000']],
          ['Welche Länder kämpften bei Leipzig gegen Napoleon?', 'Preußen, Russland, Österreich und Schweden', ['England, Spanien und Portugal', 'Bayern, Sachsen und Württemberg', 'Dänemark, Norwegen und Polen']],
          ['An welchem Tag war die Schlacht bei Waterloo?', '18. Juni 1815', ['16. Oktober 1813', '8. Juni 1815', '2. Dezember 1805']],
          ['Wann starb Napoleon?', '1821', ['1815', '1830', '1840']],
          ['Von wann bis wann tagte der Wiener Kongress?', 'September 1814 bis Juni 1815', ['Januar bis März 1815', '1812 bis 1813', '1815 bis 1820']],
          ['An welchem Tag wurde der Deutsche Bund gegründet?', '8. Juni 1815', ['18. Juni 1815', '6. August 1806', '18. Januar 1871']],
          ['Aus wie vielen Staaten bestand der Deutsche Bund anfangs?', '41', ['39', '16', '25']],
          ['Wie viele freie Städte gehörten zum Deutschen Bund?', 'Vier', ['Sechs', 'Keine', 'Zwölf']],
          ['Welche zwei Grundsätze bestimmten den Wiener Kongress?', 'Legitimität und Gleichgewicht der Mächte', ['Volkssouveränität und Gleichheit', 'Freihandel und Demokratie', 'Nationalismus und Revolution']],
          ['Wem wurden in der Heeresreform Offiziersstellen geöffnet?', 'Auch Bürgerlichen', ['Nur Adligen', 'Nur Ausländern', 'Nur Frauen']],
          ['Welche Schulform förderte Wilhelm von Humboldt?', 'Das humanistische Gymnasium', ['Die Realschule', 'Die Gesamtschule', 'Die Hauptschule']],
          ['Welche Farben hatten die Uniformen der Lützower?', 'Schwarz mit roten Aufschlägen und goldenen Knöpfen', ['Blau mit weißen Aufschlägen', 'Grün mit gelben Knöpfen', 'Rot mit schwarzen Knöpfen']],
          ['Wann zogen die Verbündeten in Paris ein?', '1814', ['1813', '1815', '1812']],
          ['Wann wurde die Heilige Allianz geschlossen?', 'September 1815', ['Juni 1815', 'März 1813', 'Januar 1814']],
          ['Worauf hatten viele Kämpfer gegen Napoleon gehofft?', 'Auf einen Nationalstaat mit Verfassung', ['Auf die Rückkehr Napoleons', 'Auf einen Anschluss an Russland', 'Auf ein neues Heiliges Reich unter dem Papst']],
        ],
      },
    },
  ],
};

export const VORMAERZ_1848: HistEvent = {
  id: 'vormaerz-1848',
  title: 'Vormärz und Revolution 1848/49',
  date: '1815–1849',
  text: [
    'Nach 1815 wollten die Fürsten die alte Ordnung bewahren und unterdrückten liberale und nationale Bestrebungen. Doch der Wunsch nach Einheit und Freiheit wuchs – bis er 1848 in einer Revolution ausbrach, die zum ersten frei gewählten deutschen Parlament in der Frankfurter Paulskirche führte.',
  ],
  subtopics: [
    {
      id: 'vormaerz',
      title: 'Vormärz und Biedermeier',
      date: '1815–1847',
      text: [
        'Die Zeit zwischen dem Wiener Kongress und der Märzrevolution von 1848 nennt man Vormärz. Studenten, die gegen Napoleon gekämpft hatten, gründeten 1815 in Jena die Urburschenschaft mit den Farben Schwarz-Rot-Gold. Am 18. Oktober 1817 trafen sich rund 500 Studenten zum Wartburgfest – zur Erinnerung an 300 Jahre Reformation und an die Völkerschlacht. Am Rande verbrannten sie Bücher und Symbole, die sie für reaktionär hielten.',
        'Am 23. März 1819 ermordete der Student Karl Ludwig Sand in Mannheim den Schriftsteller August von Kotzebue, der als russischer Spitzel galt. Metternich nutzte das: Mit den Karlsbader Beschlüssen von 1819 wurden Zeitungen und Bücher zensiert, die Universitäten überwacht, die Burschenschaften verboten und „Demagogen“ verfolgt; auch Turnvater Jahn kam in Haft.',
        'Nach der Julirevolution 1830 in Paris flammten die Hoffnungen wieder auf. Am 27. Mai 1832 kamen beim Hambacher Fest auf dem Hambacher Schloss bei Neustadt an der Weinstraße rund 30.000 Menschen zusammen und forderten Einheit, Freiheit und Volkssouveränität. Überall wehten schwarz-rot-goldene Fahnen. Organisiert hatten das Fest die Journalisten Philipp Jakob Siebenpfeiffer und Johann Georg August Wirth. Der Deutsche Bund reagierte mit neuen Verboten.',
        '1837 hob König Ernst August von Hannover die Verfassung seines Landes auf. Sieben Göttinger Professoren protestierten dagegen und wurden entlassen, drei sogar ausgewiesen. Zu diesen „Göttinger Sieben“ gehörten die Brüder Jacob und Wilhelm Grimm, die schon 1812 ihre „Kinder- und Hausmärchen“ mit Geschichten wie „Rotkäppchen“ und „Hänsel und Gretel“ herausgegeben hatten und später als Sprachforscher das „Deutsche Wörterbuch“ begannen.',
        'Viele Bürger zogen sich ins Private zurück, in die gemütliche Wohnstube mit Hausmusik und Familienleben. Diese Lebensart und ihren Stil nennt man Biedermeier; ein bekanntes Bild ist Carl Spitzwegs „Der arme Poet“ (1839), der mit aufgespanntem Regenschirm in einer kalten Dachkammer im Bett liegt. In der Romantik malte Caspar David Friedrich Bilder wie den „Wanderer über dem Nebelmeer“. Der Dichter Heinrich Heine lebte wegen der Zensur in Paris und spottete 1844 in „Deutschland. Ein Wintermärchen“ über die deutschen Zustände. 1841 schrieb August Heinrich Hoffmann von Fallersleben auf der damals britischen Insel Helgoland „Das Lied der Deutschen“, dessen dritte Strophe heute unsere Nationalhymne ist.',
        'Zugleich wuchs die Armut. Im Juni 1844 erhoben sich in Schlesien, in Peterswaldau und Langenbielau, die Weber, die wegen der Konkurrenz durch Maschinen und niedriger Löhne hungerten. Preußisches Militär schlug den Weberaufstand nieder. Heine schrieb darüber das Gedicht „Die schlesischen Weber“, Gerhart Hauptmann 1892 das Drama „Die Weber“. 1846/47 kamen Missernten und eine Hungerkrise hinzu – der Boden für die Revolution war bereitet.',
      ],
      quiz: {
        leicht: [
          ['Wie nennt man die Zeit zwischen 1815 und der Revolution 1848?', 'Vormärz', ['Gründerzeit', 'Kaiserzeit', 'Nachkriegszeit']],
          ['Welche Farben hatte die Urburschenschaft?', 'Schwarz-Rot-Gold', ['Schwarz-Weiß-Rot', 'Blau-Weiß', 'Rot-Weiß']],
          ['Auf welcher Burg trafen sich Studenten 1817?', 'Auf der Wartburg', ['Auf der Burg Hohenzollern', 'Auf dem Hambacher Schloss', 'Auf der Marienburg']],
          ['Wer verbreitete nach 1815 Zensur und Unterdrückung im Deutschen Bund?', 'Metternich', ['Bismarck', 'Napoleon', 'Freiherr vom Stein']],
          ['Was wurde durch die Karlsbader Beschlüsse eingeführt?', 'Zensur', ['Die Pressefreiheit', 'Das Wahlrecht', 'Die Wehrpflicht']],
          ['Wo fand 1832 ein großes Fest für Einheit und Freiheit statt?', 'Auf dem Hambacher Schloss', ['Auf der Wartburg', 'In der Paulskirche', 'In Versailles']],
          ['Wie viele Menschen kamen etwa zum Hambacher Fest?', 'Rund 30.000', ['Rund 300', 'Rund 3 Millionen', 'Rund 3000']],
          ['Welche Brüder gehörten zu den Göttinger Sieben?', 'Die Brüder Grimm', ['Die Brüder Humboldt', 'Die Brüder Mann', 'Die Brüder Wright']],
          ['Wofür sind die Brüder Grimm berühmt?', 'Für ihre Märchensammlung', ['Für ihre Gemälde', 'Für ihre Erfindungen', 'Für ihre Symphonien']],
          ['Wie nennt man die gemütliche bürgerliche Lebensart dieser Zeit?', 'Biedermeier', ['Barock', 'Rokoko', 'Jugendstil']],
          ['Welcher Maler malte „Der arme Poet“?', 'Carl Spitzweg', ['Caspar David Friedrich', 'Adolph Menzel', 'Albrecht Dürer']],
          ['Welcher Maler schuf den „Wanderer über dem Nebelmeer“?', 'Caspar David Friedrich', ['Carl Spitzweg', 'Franz Marc', 'Max Liebermann']],
          ['Welcher Dichter lebte wegen der Zensur in Paris?', 'Heinrich Heine', ['Goethe', 'Schiller', 'Theodor Fontane']],
          ['Wer schrieb „Das Lied der Deutschen“?', 'Hoffmann von Fallersleben', ['Heinrich Heine', 'Friedrich Schiller', 'Joseph Haydn']],
          ['Welche Strophe des Liedes ist heute Nationalhymne?', 'Die dritte', ['Die erste', 'Die zweite', 'Alle drei']],
          ['Welche Arbeiter erhoben sich 1844 in Schlesien?', 'Die Weber', ['Die Bergleute', 'Die Eisenbahner', 'Die Bäcker']],
          ['Warum hungerten die schlesischen Weber?', 'Wegen Maschinenkonkurrenz und niedriger Löhne', ['Wegen eines Krieges', 'Wegen eines Erdbebens', 'Weil sie zu viel verdienten']],
          ['Wer schlug den Weberaufstand nieder?', 'Preußisches Militär', ['Französische Truppen', 'Die Polizei Wiens', 'Niemand']],
          ['Welches Ereignis in Paris weckte 1830 neue Hoffnungen?', 'Die Julirevolution', ['Die Kaiserkrönung', 'Die Weltausstellung', 'Der Bau des Eiffelturms']],
          ['Was forderten die Menschen beim Hambacher Fest?', 'Einheit und Freiheit', ['Einen neuen König', 'Mehr Steuern', 'Krieg gegen Frankreich']],
        ],
        mittel: [
          ['Wo wurde 1815 die Urburschenschaft gegründet?', 'In Jena', ['In Göttingen', 'In Heidelberg', 'In Berlin']],
          ['Wann fand das Wartburgfest statt?', '18. Oktober 1817', ['27. Mai 1832', '23. März 1819', '18. März 1848']],
          ['Woran erinnerte das Wartburgfest?', 'An 300 Jahre Reformation und die Völkerschlacht', ['An die Kaiserkrönung Karls', 'An den Westfälischen Frieden', 'An den Bau der Wartburg']],
          ['Was taten Studenten am Rande des Wartburgfests?', 'Sie verbrannten Bücher und Symbole', ['Sie wählten einen Kaiser', 'Sie gründeten eine Partei', 'Sie stürmten Berlin']],
          ['Wen ermordete Karl Ludwig Sand 1819?', 'August von Kotzebue', ['Metternich', 'Friedrich Wilhelm III.', 'Goethe']],
          ['In welcher Stadt geschah der Mord an Kotzebue?', 'Mannheim', ['Jena', 'Karlsbad', 'Weimar']],
          ['Wann wurden die Karlsbader Beschlüsse gefasst?', '1819', ['1815', '1832', '1848']],
          ['Was geschah mit den Burschenschaften 1819?', 'Sie wurden verboten', ['Sie wurden Staatsorgane', 'Sie zogen nach Amerika', 'Sie bekamen Geld vom König']],
          ['Wie nannte man die verfolgten Oppositionellen?', 'Demagogen', ['Jakobiner', 'Revolutionäre Garde', 'Bolschewiken']],
          ['An welchem Tag fand das Hambacher Fest statt?', '27. Mai 1832', ['18. Oktober 1817', '18. Mai 1848', '14. Juli 1832']],
          ['Bei welcher Stadt liegt das Hambacher Schloss?', 'Neustadt an der Weinstraße', ['Heidelberg', 'Mainz', 'Kaiserslautern']],
          ['Wer organisierte das Hambacher Fest?', 'Siebenpfeiffer und Wirth', ['Heine und Börne', 'Marx und Engels', 'Hecker und Struve']],
          ['Welcher König hob 1837 eine Verfassung auf?', 'Ernst August von Hannover', ['Friedrich Wilhelm IV.', 'Ludwig I. von Bayern', 'Wilhelm I.']],
          ['Wann erschienen die „Kinder- und Hausmärchen“ zuerst?', '1812', ['1837', '1800', '1850']],
          ['Wann malte Spitzweg „Der arme Poet“?', '1839', ['1818', '1848', '1871']],
          ['Welches Werk Heines spottet über Deutschland?', '„Deutschland. Ein Wintermärchen“', ['„Buch der Lieder“', '„Die Weber“', '„Faust“']],
          ['Wo schrieb Hoffmann von Fallersleben das Lied der Deutschen?', 'Auf Helgoland', ['Auf Rügen', 'In Weimar', 'In Berlin']],
          ['Wann schrieb Hoffmann von Fallersleben das Lied der Deutschen?', '1841', ['1815', '1848', '1871']],
          ['Wann fand der Weberaufstand statt?', 'Juni 1844', ['März 1848', 'Oktober 1817', 'Mai 1832']],
          ['Wer schrieb das Drama „Die Weber“?', 'Gerhart Hauptmann', ['Heinrich Heine', 'Georg Büchner', 'Bertolt Brecht']],
        ],
        schwer: [
          ['Wie viele Studenten kamen etwa zum Wartburgfest?', 'Rund 500', ['Rund 50', 'Rund 30.000', 'Rund 5000']],
          ['An welchem Tag wurde Kotzebue ermordet?', '23. März 1819', ['18. Oktober 1817', '27. Mai 1832', '18. März 1848']],
          ['Als was galt Kotzebue bei den Studenten?', 'Als russischer Spitzel', ['Als französischer General', 'Als Revolutionär', 'Als Freund der Burschenschaft']],
          ['Welcher Turnvater wurde nach 1819 verhaftet?', 'Friedrich Ludwig Jahn', ['Ernst Moritz Arndt', 'Theodor Körner', 'Johann Gottlieb Fichte']],
          ['Wie viele der Göttinger Sieben wurden ausgewiesen?', 'Drei', ['Alle sieben', 'Einer', 'Keiner']],
          ['In welchem Jahr protestierten die Göttinger Sieben?', '1837', ['1819', '1832', '1844']],
          ['In welchen Orten erhoben sich die schlesischen Weber?', 'Peterswaldau und Langenbielau', ['Breslau und Görlitz', 'Liegnitz und Glogau', 'Oppeln und Ratibor']],
          ['Wann schrieb Gerhart Hauptmann „Die Weber“?', '1892', ['1844', '1871', '1913']],
          ['Welches Gedicht schrieb Heine über den Weberaufstand?', '„Die schlesischen Weber“', ['„Die Loreley“', '„Nachtgedanken“', '„Der Erlkönig“']],
          ['Zu welchem Land gehörte Helgoland 1841?', 'Zu Großbritannien', ['Zu Dänemark', 'Zu Preußen', 'Zu Hannover']],
          ['Wann erschien „Deutschland. Ein Wintermärchen“?', '1844', ['1832', '1848', '1827']],
          ['Welche Krise bereitete die Revolution unmittelbar vor?', 'Missernten und Hunger 1846/47', ['Eine Pest 1847', 'Ein Krieg gegen Dänemark 1846', 'Ein Börsenkrach 1847']],
          ['Welche Forderung des Hambacher Festes bedeutet „Herrschaft des Volkes“?', 'Volkssouveränität', ['Gottesgnadentum', 'Legitimität', 'Restauration']],
          ['Wovon handelt das Bild „Der arme Poet“?', 'Ein Dichter liegt mit Regenschirm in einer kalten Dachkammer', ['Ein König auf dem Thron', 'Eine Schlacht', 'Ein Bauer bei der Ernte']],
          ['Welche Märchen stammen aus der Sammlung der Brüder Grimm?', '„Rotkäppchen“ und „Hänsel und Gretel“', ['„Die kleine Meerjungfrau“ und „Das hässliche Entlein“', '„Pinocchio“ und „Heidi“', '„Aladin“ und „Sindbad“']],
          ['Welche Stadt war Ort der Karlsbader Beschlüsse?', 'Karlsbad in Böhmen', ['Karlsruhe', 'Karlsbad bei Berlin', 'Karl-Marx-Stadt']],
          ['Wie reagierte der Deutsche Bund auf das Hambacher Fest?', 'Mit neuen Verboten', ['Mit einer Verfassung', 'Mit der Wahl eines Kaisers', 'Gar nicht']],
          ['Wofür war Wilhelm Grimm neben den Märchen bekannt?', 'Als Sprachforscher (Deutsches Wörterbuch)', ['Als Maler', 'Als General', 'Als Komponist']],
          ['Welche Strophe des Liedes der Deutschen beginnt mit „Einigkeit und Recht und Freiheit“?', 'Die dritte', ['Die erste', 'Die zweite', 'Die vierte']],
          ['Welcher Bewegung gehörten Caspar David Friedrich und die Brüder Grimm an?', 'Der Romantik', ['Dem Realismus', 'Dem Barock', 'Dem Expressionismus']],
        ],
      },
    },
    {
      id: 'revolution-1848',
      title: 'Die Revolution von 1848/49',
      date: '1848–1849',
      text: [
        'Im Februar 1848 stürzten die Pariser ihren König. Die Nachricht löste in ganz Deutschland Versammlungen und Proteste aus. Die Menschen stellten die „Märzforderungen“: Pressefreiheit, Schwurgerichte, Volksbewaffnung und ein gesamtdeutsches Parlament. Viele Fürsten gaben nach und setzten liberale „Märzministerien“ ein. In Wien floh Metternich am 13. März.',
        'In Berlin kam es am 18. März 1848 zu heftigen Barrikadenkämpfen mit rund 300 Toten, den „Märzgefallenen“. König Friedrich Wilhelm IV. zog das Militär ab, verneigte sich vor den Toten und ritt am 21. März mit einer schwarz-rot-goldenen Armbinde durch die Stadt. Er erklärte: „Preußen geht fortan in Deutschland auf.“ In Baden versuchte Friedrich Hecker schon im April 1848 mit dem „Heckerzug“, eine Republik zu erzwingen, scheiterte aber.',
        'Nach Vorbereitung durch ein Vorparlament wurde in allen Staaten des Deutschen Bundes eine Nationalversammlung gewählt. Am 18. Mai 1848 trat sie in der Frankfurter Paulskirche zusammen; Präsident wurde Heinrich von Gagern. Weil so viele Gelehrte und Juristen darin saßen, nannte man sie „Professorenparlament“. Als vorläufiges Staatsoberhaupt wählte sie Erzherzog Johann von Österreich zum Reichsverweser. Es bildeten sich erste Gruppen, aus denen später Parteien wurden, benannt nach den Gasthäusern, in denen sie sich trafen.',
        'Lange stritt man über die Grenzen des neuen Deutschland: Die „großdeutsche Lösung“ wollte Österreich einschließen, die „kleindeutsche Lösung“ ein Deutschland ohne Österreich unter Führung Preußens. Im Dezember 1848 beschloss die Versammlung die Grundrechte des deutschen Volkes, etwa Gleichheit vor dem Gesetz, Meinungs-, Presse- und Religionsfreiheit sowie die Abschaffung der Todesstrafe. Am 28. März 1849 verabschiedete sie die Reichsverfassung: eine konstitutionelle Monarchie mit einem erblichen Kaiser. Am selben Tag wählte sie König Friedrich Wilhelm IV. von Preußen zum „Kaiser der Deutschen“ – die kleindeutsche Lösung hatte sich durchgesetzt.',
        'Doch im April 1849 lehnte der König die Krone ab. Eine Krone, die ihm das Volk und nicht Gott verleihe, nannte er verächtlich einen „Reif aus Dreck und Letten“ und ein „Hundehalsband“. Inzwischen hatten die Fürsten wieder Oberwasser: In Wien war schon am 9. November 1848 der aus Köln stammende Abgeordnete Robert Blum hingerichtet worden. Die meisten Staaten zogen ihre Abgeordneten zurück; das „Rumpfparlament“ wich nach Stuttgart aus und wurde im Juni 1849 von Soldaten aufgelöst.',
        'In der Reichsverfassungskampagne kämpften Demokraten im Mai 1849 in Sachsen (beim Dresdner Maiaufstand waren der Komponist Richard Wagner und der Architekt Gottfried Semper beteiligt, ebenso der russische Anarchist Michail Bakunin), in der Pfalz und in Baden für die Verfassung. Preußische Truppen unter Prinz Wilhelm, dem späteren Kaiser, den man deshalb „Kartätschenprinz“ nannte, schlugen die Aufstände nieder; am 23. Juli 1849 ergab sich die Festung Rastatt. Viele Revolutionäre flohen, besonders in die USA, wo man sie „Forty-Eighters“ nannte, etwa Carl Schurz.',
        'Die Revolution war gescheitert, doch sie hinterließ Spuren: Die Bauernbefreiung wurde abgeschlossen, Preußen erhielt eine (vom König erlassene) Verfassung, allerdings mit dem ungleichen Dreiklassenwahlrecht, und die Grundrechte der Paulskirche wurden Vorbild für spätere Verfassungen wie die Weimarer Verfassung und das Grundgesetz. Schwarz-Rot-Gold wurde zum Symbol der Demokratie in Deutschland.',
      ],
      quiz: {
        leicht: [
          ['In welchem Jahr brach in Deutschland eine Revolution aus?', '1848', ['1789', '1871', '1918']],
          ['In welchem Monat begann die Revolution in Deutschland vor allem?', 'Im März', ['Im Dezember', 'Im August', 'Im Oktober']],
          ['Wo tagte das erste frei gewählte deutsche Parlament?', 'In der Frankfurter Paulskirche', ['Im Berliner Reichstag', 'In der Wiener Hofburg', 'Im Bonner Bundeshaus']],
          ['Welche Freiheit forderten die Menschen im März 1848 unter anderem?', 'Pressefreiheit', ['Reisefreiheit nach Amerika', 'Steuerfreiheit für Adlige', 'Die Freiheit, Waffen zu verkaufen']],
          ['In welcher Stadt kam es am 18. März 1848 zu Barrikadenkämpfen?', 'Berlin', ['Frankfurt', 'München', 'Hamburg']],
          ['Welcher preußische König ritt mit schwarz-rot-goldener Armbinde durch Berlin?', 'Friedrich Wilhelm IV.', ['Wilhelm I.', 'Friedrich der Große', 'Friedrich Wilhelm III.']],
          ['Welcher Staatsmann floh im März 1848 aus Wien?', 'Metternich', ['Bismarck', 'Hardenberg', 'Radetzky']],
          ['Wie nannte man die Nationalversammlung wegen der vielen Gelehrten?', 'Professorenparlament', ['Bauernparlament', 'Arbeiterrat', 'Fürstentag']],
          ['Welche Lösung wollte ein Deutschland ohne Österreich?', 'Die kleindeutsche Lösung', ['Die großdeutsche Lösung', 'Die Wiener Lösung', 'Die Rheinbund-Lösung']],
          ['Welche Lösung wollte Österreich einschließen?', 'Die großdeutsche Lösung', ['Die kleindeutsche Lösung', 'Die Berliner Lösung', 'Die preußische Lösung']],
          ['Wen wählte die Nationalversammlung 1849 zum Kaiser?', 'Friedrich Wilhelm IV.', ['Franz Joseph', 'Wilhelm I.', 'Erzherzog Johann']],
          ['Nahm Friedrich Wilhelm IV. die Kaiserkrone an?', 'Nein, er lehnte ab', ['Ja, sofort', 'Ja, nach einem Jahr', 'Er wurde nie gefragt']],
          ['Wie nannte der König die angebotene Krone verächtlich?', '„Hundehalsband“', ['„Goldreif“', '„Heilige Krone“', '„Narrenkappe“']],
          ['Ist die Revolution von 1848/49 gelungen?', 'Nein, sie scheiterte', ['Ja, Deutschland wurde Republik', 'Ja, Österreich wurde Teil Preußens', 'Es gab keine Revolution']],
          ['Wohin flohen viele Revolutionäre?', 'In die USA', ['Nach Russland', 'Nach China', 'Nach Australien']],
          ['Welche Farben wurden Symbol der Demokratie?', 'Schwarz-Rot-Gold', ['Schwarz-Weiß-Rot', 'Blau-Weiß', 'Grün-Weiß']],
          ['Welche Festung ergab sich 1849 als letzte?', 'Rastatt', ['Koblenz', 'Ulm', 'Mainz']],
          ['Welcher berühmte Komponist kämpfte 1849 in Dresden mit?', 'Richard Wagner', ['Johann Strauss', 'Felix Mendelssohn', 'Johannes Brahms']],
          ['Welche Grundrechte beschloss die Nationalversammlung unter anderem?', 'Meinungs- und Religionsfreiheit', ['Das Recht auf ein Auto', 'Das Recht auf Krieg', 'Das Recht auf Steuerfreiheit']],
          ['Was forderten die Menschen 1848 für ganz Deutschland?', 'Ein gemeinsames Parlament', ['Einen Papst', 'Mehr Könige', 'Die Rückkehr Napoleons']],
        ],
        mittel: [
          ['Welche Revolution im Februar 1848 löste die Unruhen aus?', 'Die Februarrevolution in Paris', ['Die Revolution in Wien', 'Die Revolution in London', 'Die Revolution in Moskau']],
          ['Welche vier Märzforderungen gab es?', 'Pressefreiheit, Schwurgerichte, Volksbewaffnung, Parlament', ['Kaiser, Papst, König, Fürst', 'Brot, Bier, Wein, Fleisch', 'Krieg, Kolonien, Flotte, Heer']],
          ['Wann trat die Nationalversammlung zusammen?', '18. Mai 1848', ['18. März 1848', '28. März 1849', '18. Januar 1871']],
          ['Wer war Präsident der Nationalversammlung?', 'Heinrich von Gagern', ['Robert Blum', 'Friedrich Hecker', 'Carl Schurz']],
          ['Wer wurde Reichsverweser?', 'Erzherzog Johann von Österreich', ['Friedrich Wilhelm IV.', 'Heinrich von Gagern', 'Metternich']],
          ['Wie viele Menschen starben bei den Berliner Barrikadenkämpfen etwa?', 'Rund 300', ['Rund 30', 'Rund 3000', 'Rund 30.000']],
          ['Wie nennt man die Toten der Berliner Märzkämpfe?', 'Märzgefallene', ['Märtyrer der Freiheit', 'Barrikadenhelden', 'Paulskirchler']],
          ['Was erklärte Friedrich Wilhelm IV. am 21. März 1848?', '„Preußen geht fortan in Deutschland auf“', ['„Ich bin der Staat“', '„Wir sind das Volk“', '„Nach Canossa gehen wir nicht“']],
          ['Wer versuchte im April 1848 in Baden eine Republik zu erzwingen?', 'Friedrich Hecker', ['Robert Blum', 'Carl Schurz', 'Heinrich von Gagern']],
          ['Wann wurden die Grundrechte des deutschen Volkes beschlossen?', 'Im Dezember 1848', ['Im März 1848', 'Im Mai 1848', 'Im Juli 1849']],
          ['Welche Strafe sollte nach den Grundrechten abgeschafft werden?', 'Die Todesstrafe', ['Die Geldstrafe', 'Die Gefängnisstrafe', 'Die Prügelstrafe']],
          ['Wann wurde die Reichsverfassung verabschiedet?', '28. März 1849', ['18. Mai 1848', '18. März 1848', '23. Juli 1849']],
          ['Welche Staatsform sah die Reichsverfassung vor?', 'Eine konstitutionelle Monarchie mit erblichem Kaiser', ['Eine Republik', 'Eine absolute Monarchie', 'Eine Diktatur']],
          ['Welcher Abgeordnete wurde im November 1848 in Wien hingerichtet?', 'Robert Blum', ['Friedrich Hecker', 'Heinrich von Gagern', 'Gustav Struve']],
          ['Wohin wich das Rumpfparlament aus?', 'Nach Stuttgart', ['Nach Berlin', 'Nach Wien', 'Nach Paris']],
          ['Welcher Prinz schlug die Aufstände in Baden nieder?', 'Prinz Wilhelm von Preußen', ['Prinz Albert', 'Erzherzog Johann', 'Prinz Friedrich Karl']],
          ['Wie nannte man die nach Amerika geflohenen Revolutionäre?', 'Forty-Eighters', ['Pilgrims', 'Yankees', 'Pioneers']],
          ['Welcher bekannte Forty-Eighter machte in den USA Karriere?', 'Carl Schurz', ['Robert Blum', 'Richard Wagner', 'Heinrich von Gagern']],
          ['Welches Wahlrecht führte Preußen nach der Revolution ein?', 'Das Dreiklassenwahlrecht', ['Das Frauenwahlrecht', 'Das gleiche Wahlrecht für alle', 'Gar keines']],
          ['Welcher Architekt beteiligte sich am Dresdner Maiaufstand?', 'Gottfried Semper', ['Karl Friedrich Schinkel', 'Leo von Klenze', 'Walter Gropius']],
        ],
        schwer: [
          ['An welchem Tag floh Metternich?', '13. März 1848', ['18. März 1848', '18. Mai 1848', '9. November 1848']],
          ['An welchem Tag ritt Friedrich Wilhelm IV. mit der Armbinde durch Berlin?', '21. März 1848', ['18. März 1848', '1. Mai 1848', '28. März 1849']],
          ['Was ging der Nationalversammlung voraus?', 'Ein Vorparlament', ['Ein Kaiserwahltag', 'Ein Krieg gegen Dänemark', 'Ein Fürstenkongress in Wien']],
          ['Wonach waren die ersten Fraktionen der Paulskirche benannt?', 'Nach Gasthäusern, in denen sie sich trafen', ['Nach ihren Farben', 'Nach Städten', 'Nach ihren Anführern']],
          ['Welchen Titel sollte Friedrich Wilhelm IV. tragen?', '„Kaiser der Deutschen“', ['„Kaiser von Deutschland“', '„König der Deutschen“', '„Deutscher Kaiser“']],
          ['Mit welchen Worten bezeichnete der König die Krone außerdem?', '„Reif aus Dreck und Letten“', ['„Krone der Schande“', '„Papierkrone“', '„Krone des Pöbels“']],
          ['Warum lehnte der König die Krone ab?', 'Sie kam vom Volk und nicht von Gott und den Fürsten', ['Sie war ihm zu schwer', 'Er wollte Papst werden', 'Er war schwer krank']],
          ['An welchem Tag wurde Robert Blum hingerichtet?', '9. November 1848', ['18. März 1848', '28. März 1849', '23. Juli 1849']],
          ['Wann wurde das Rumpfparlament aufgelöst?', 'Im Juni 1849', ['Im März 1849', 'Im Dezember 1848', 'Im Juli 1850']],
          ['An welchem Tag ergab sich die Festung Rastatt?', '23. Juli 1849', ['18. Juni 1849', '9. November 1848', '18. Mai 1849']],
          ['In welchen Regionen kämpften Demokraten 1849 für die Reichsverfassung?', 'Sachsen, Pfalz und Baden', ['Ostpreußen, Pommern und Posen', 'Tirol, Kärnten und Krain', 'Holstein, Hamburg und Bremen']],
          ['Welcher Abgeordnete stammte aus Köln und wurde in Wien erschossen?', 'Robert Blum', ['Friedrich Hecker', 'Carl Schurz', 'Gustav Struve']],
          ['Wie nannte man den späteren Kaiser Wilhelm I. wegen 1848/49 spöttisch?', '„Kartätschenprinz“', ['„Barrikadenkönig“', '„Bürgerprinz“', '„Revolutionsprinz“']],
          ['Wie hieß der badische Aufstand von Hecker?', 'Heckerzug', ['Badischer Bauernkrieg', 'Freiburger Aufstand', 'Schwarzwaldmarsch']],
          ['Wie hießen die neuen liberalen Regierungen 1848?', 'Märzministerien', ['Volkskomitees', 'Reichsräte', 'Paulskirchenkabinette']],
          ['Welche Folge der Revolution betraf die Landbevölkerung?', 'Die Bauernbefreiung wurde abgeschlossen', ['Die Leibeigenschaft wurde eingeführt', 'Die Bauern verloren alles Land', 'Die Bauern bekamen eigene Fürsten']],
          ['Wie entstand die preußische Verfassung von 1848?', 'Sie wurde vom König erlassen (oktroyiert)', ['Sie wurde vom Volk abgestimmt', 'Sie kam aus Frankfurt', 'Sie wurde von Österreich diktiert']],
          ['Für welche späteren Verfassungen waren die Grundrechte Vorbild?', 'Für die Weimarer Verfassung und das Grundgesetz', ['Für die US-Verfassung von 1787', 'Für die Goldene Bulle', 'Für den Code civil']],
          ['Wer wurde 1849 neben Wagner wegen des Dresdner Aufstands bekannt?', 'Der russische Anarchist Bakunin', ['Karl Marx', 'Lenin', 'Ferdinand Lassalle']],
          ['Welche Gruppen waren in der Paulskirche besonders stark vertreten?', 'Juristen, Professoren und Beamte', ['Bauern und Arbeiter', 'Adlige Offiziere', 'Geistliche und Mönche']],
        ],
      },
    },
  ],
};
