import type { HistEvent } from '../types';

export const ERSTER_WELTKRIEG: HistEvent = {
  id: 'erster-weltkrieg',
  title: 'Der Erste Weltkrieg',
  date: '1914–1919',
  text: [
    'Ein Attentat in Sarajevo löste 1914 einen Krieg aus, der Europa verwüstete. In den Schützengräben starben Millionen Soldaten, in der Heimat hungerten die Menschen. Am Ende stürzte das Kaiserreich, und der Vertrag von Versailles belastete die junge Republik schwer.',
  ],
  subtopics: [
    {
      id: 'kriegsbeginn',
      title: 'Kriegsbeginn und Stellungskrieg',
      date: '1914–1916',
      text: [
        'Am 28. Juni 1914 erschoss der bosnisch-serbische Nationalist Gavrilo Princip in Sarajevo den österreichischen Thronfolger Erzherzog Franz Ferdinand und seine Frau Sophie. Österreich-Ungarn wollte Serbien bestrafen. Deutschland sicherte ihm Anfang Juli bedingungslose Unterstützung zu – den „Blankoscheck“. Am 23. Juli stellte Österreich Serbien ein scharfes Ultimatum und erklärte ihm am 28. Juli den Krieg. Durch die Bündnisse weitete sich der Konflikt in der „Julikrise“ rasch aus: Am 1. August erklärte Deutschland Russland den Krieg, am 3. August Frankreich. Als deutsche Truppen in das neutrale Belgien einmarschierten, trat am 4. August Großbritannien in den Krieg ein.',
        'Deutschland und Österreich-Ungarn (die Mittelmächte, später mit dem Osmanischen Reich und Bulgarien) kämpften gegen die Entente aus Frankreich, Russland und Großbritannien, zu der später Italien (1915) und die USA (1917) kamen. Viele Menschen zogen anfangs begeistert in den Krieg und glaubten, Weihnachten wieder zu Hause zu sein. Der Kaiser rief: „Ich kenne keine Parteien mehr, ich kenne nur noch Deutsche“, und am 4. August 1914 stimmte auch die SPD den Kriegskrediten zu – der „Burgfrieden“.',
        'Nach dem Schlieffen-Plan sollte das deutsche Heer Frankreich in wenigen Wochen durch Belgien umgehen und besiegen, bevor sich Russland ganz gerüstet hätte. Doch im September 1914 wurde der Vormarsch an der Marne gestoppt. Danach erstarrte die Westfront zum Stellungskrieg: Von der Nordsee bis zur Schweiz zogen sich Schützengräben durch Schlamm und Stacheldraht. Im Osten siegten Paul von Hindenburg und Erich Ludendorff im August 1914 bei Tannenberg über eine russische Armee; Hindenburg wurde zum Volkshelden.',
        'Der Krieg wurde zum ersten industriellen Massenkrieg mit Maschinengewehren, schwerer Artillerie, Flugzeugen und Giftgas. Am 22. April 1915 setzten deutsche Truppen bei Ypern erstmals in großem Stil Chlorgas ein; entwickelt hatte es unter Leitung des Chemikers Fritz Haber. Die Briten setzten im September 1916 an der Somme die ersten Panzer ein.',
        '1916 wollte die deutsche Führung Frankreich bei Verdun „ausbluten“ lassen. Die Schlacht dauerte von Februar bis Dezember 1916 und kostete rund 300.000 Soldaten das Leben, ohne dass sich die Front wesentlich verschob. In der Schlacht an der Somme von Juli bis November 1916 gab es über eine Million Tote, Verwundete und Vermisste. Auf See trafen sich die deutsche und die britische Flotte am 31. Mai 1916 in der Skagerrakschlacht, ohne dass eine Seite die Seeherrschaft gewann.',
        'Deutsche U-Boote versenkten Handelsschiffe, um Großbritannien vom Nachschub abzuschneiden. Am 7. Mai 1915 versenkte ein U-Boot den britischen Passagierdampfer „Lusitania“; rund 1200 Menschen starben, darunter 128 Amerikaner. Die Empörung in den USA war groß.',
      ],
      quiz: {
        leicht: [
          ['In welchem Jahr begann der Erste Weltkrieg?', '1914', ['1870', '1918', '1939']],
          ['Welches Attentat löste den Krieg aus?', 'Das Attentat von Sarajevo', ['Das Attentat auf Bismarck', 'Das Attentat auf Lincoln', 'Das Attentat von München']],
          ['Wer wurde in Sarajevo ermordet?', 'Der österreichische Thronfolger Franz Ferdinand', ['Kaiser Wilhelm II.', 'Der Zar', 'Der König von Serbien']],
          ['Wer verübte das Attentat von Sarajevo?', 'Gavrilo Princip', ['Lee Harvey Oswald', 'Georg Elser', 'Karl Ludwig Sand']],
          ['Wie hießen Deutschland und Österreich-Ungarn im Krieg zusammen?', 'Mittelmächte', ['Alliierte', 'Achsenmächte', 'Entente']],
          ['Welche Länder bildeten die Entente?', 'Frankreich, Russland und Großbritannien', ['Deutschland, Österreich und Italien', 'Spanien, Portugal und Schweden', 'USA, Japan und China']],
          ['Durch welches neutrale Land marschierten deutsche Truppen 1914?', 'Belgien', ['Schweiz', 'Niederlande', 'Dänemark']],
          ['Wie nennt man den Krieg in Schützengräben?', 'Stellungskrieg', ['Blitzkrieg', 'Bewegungskrieg', 'Seekrieg']],
          ['An welchem Fluss wurde der deutsche Vormarsch 1914 gestoppt?', 'An der Marne', ['Am Rhein', 'An der Somme', 'An der Seine']],
          ['Welcher General wurde nach Tannenberg zum Volkshelden?', 'Paul von Hindenburg', ['Erich Ludendorff', 'Helmuth von Moltke', 'Erwin Rommel']],
          ['Welche Waffe wurde 1915 erstmals in großem Stil eingesetzt?', 'Giftgas', ['Atombombe', 'Raketen', 'Drohnen']],
          ['Um welche Stadt in Frankreich tobte 1916 eine monatelange Schlacht?', 'Verdun', ['Paris', 'Lyon', 'Marseille']],
          ['Welches Land setzte 1916 die ersten Panzer ein?', 'Großbritannien', ['Deutschland', 'Frankreich', 'Russland']],
          ['Welches Passagierschiff versenkte ein deutsches U-Boot 1915?', 'Die Lusitania', ['Die Titanic', 'Die Bismarck', 'Die Queen Mary']],
          ['Was glaubten viele Soldaten am Anfang des Krieges?', 'Dass sie Weihnachten wieder zu Hause sind', ['Dass der Krieg 30 Jahre dauert', 'Dass sie verlieren', 'Dass es keinen Krieg gibt']],
          ['Wie nennt man den politischen Waffenstillstand der Parteien 1914?', 'Burgfrieden', ['Landfrieden', 'Gottesfrieden', 'Religionsfrieden']],
          ['Welcher Plan sollte Frankreich schnell besiegen?', 'Der Schlieffen-Plan', ['Der Marshallplan', 'Der Dawes-Plan', 'Der Morgenthau-Plan']],
          ['Gegen welches Land erklärte Deutschland am 1. August 1914 den Krieg?', 'Russland', ['Frankreich', 'England', 'Serbien']],
          ['In welchem Land liegt Sarajevo heute?', 'In Bosnien und Herzegowina', ['In Serbien', 'In Kroatien', 'In Österreich']],
          ['Was zog sich von der Nordsee bis zur Schweiz?', 'Die Westfront mit Schützengräben', ['Eine Eisenbahnlinie', 'Ein Kanal', 'Eine Mauer']],
        ],
        mittel: [
          ['An welchem Tag fand das Attentat von Sarajevo statt?', '28. Juni 1914', ['1. August 1914', '11. November 1918', '28. Juli 1914']],
          ['Wie nennt man Deutschlands Unterstützungszusage an Österreich?', 'Blankoscheck', ['Emser Depesche', 'Zimmermann-Telegramm', 'Rückversicherung']],
          ['Wann erklärte Österreich-Ungarn Serbien den Krieg?', '28. Juli 1914', ['28. Juni 1914', '1. August 1914', '4. August 1914']],
          ['Wann trat Großbritannien in den Krieg ein?', '4. August 1914', ['1. August 1914', '3. August 1914', '6. April 1917']],
          ['Wann erklärte Deutschland Frankreich den Krieg?', '3. August 1914', ['1. August 1914', '4. August 1914', '28. Juli 1914']],
          ['Welche Länder traten später an die Seite der Mittelmächte?', 'Das Osmanische Reich und Bulgarien', ['Italien und Rumänien', 'Spanien und Portugal', 'Schweden und Norwegen']],
          ['Wann trat Italien in den Krieg ein?', '1915', ['1914', '1917', '1918']],
          ['Wann stimmte die SPD den Kriegskrediten zu?', '4. August 1914', ['28. Juni 1914', '9. November 1918', '1. Mai 1915']],
          ['Welcher Satz des Kaisers steht für den Burgfrieden?', '„Ich kenne keine Parteien mehr, ich kenne nur noch Deutsche“', ['„Ich habe es nicht gewollt“', '„Der Lotse geht von Bord“', '„Wir sind das Volk“']],
          ['Wo siegten Hindenburg und Ludendorff im August 1914?', 'Bei Tannenberg', ['An der Marne', 'Bei Verdun', 'An der Somme']],
          ['Wo setzten deutsche Truppen 1915 Chlorgas ein?', 'Bei Ypern', ['Bei Verdun', 'An der Somme', 'An der Marne']],
          ['Welcher Chemiker leitete die Entwicklung des Giftgases?', 'Fritz Haber', ['Otto Hahn', 'Robert Koch', 'Carl Bosch']],
          ['Wie viele Soldaten starben in der Schlacht um Verdun etwa?', 'Rund 300.000', ['Rund 30.000', 'Rund 3 Millionen', 'Rund 3000']],
          ['Was wollte die deutsche Führung bei Verdun erreichen?', 'Frankreich „ausbluten“ lassen', ['Paris erobern', 'Frieden schließen', 'Belgien befreien']],
          ['Wann fand die Schlacht an der Somme statt?', 'Juli bis November 1916', ['Februar bis Dezember 1916', 'August 1914', 'März 1918']],
          ['Wie hieß die große Seeschlacht von 1916?', 'Skagerrakschlacht', ['Schlacht bei Trafalgar', 'Schlacht im Atlantik', 'Schlacht bei Midway']],
          ['Wann wurde die Lusitania versenkt?', '7. Mai 1915', ['15. April 1912', '6. April 1917', '22. April 1915']],
          ['Wie viele Menschen starben auf der Lusitania etwa?', 'Rund 1200', ['Rund 120', 'Rund 12.000', 'Rund 50']],
          ['Wofür setzte Deutschland U-Boote vor allem ein?', 'Um Handelsschiffe zu versenken', ['Um Truppen zu transportieren', 'Um Post zu befördern', 'Um Fische zu fangen']],
          ['Wann trat die USA in den Krieg ein?', '1917', ['1914', '1915', '1918']],
        ],
        schwer: [
          ['Wann stellte Österreich Serbien das Ultimatum?', '23. Juli 1914', ['28. Juni 1914', '28. Juli 1914', '5. Juli 1914']],
          ['Wie hieß die Frau von Franz Ferdinand, die ebenfalls starb?', 'Sophie', ['Elisabeth', 'Maria', 'Zita']],
          ['Welcher Herkunft war Gavrilo Princip?', 'Bosnischer Serbe', ['Österreicher', 'Kroate', 'Russe']],
          ['Wie nennt man die diplomatische Krise im Juli 1914?', 'Julikrise', ['Sarajevokrise', 'Balkankrise', 'Marokkokrise']],
          ['Wann wurde der deutsche Vormarsch an der Marne gestoppt?', 'Im September 1914', ['Im August 1914', 'Im Dezember 1914', 'Im Mai 1915']],
          ['An welchem Tag setzten Deutsche erstmals Chlorgas in großem Stil ein?', '22. April 1915', ['7. Mai 1915', '1. Juli 1916', '31. Mai 1916']],
          ['Wann setzten die Briten an der Somme die ersten Panzer ein?', 'September 1916', ['Juli 1916', 'April 1917', 'August 1918']],
          ['Wie viele Tote, Verwundete und Vermisste gab es an der Somme?', 'Über eine Million', ['Rund 100.000', 'Rund 10.000', 'Rund 10 Millionen']],
          ['An welchem Tag fand die Skagerrakschlacht statt?', '31. Mai 1916', ['7. Mai 1915', '1. Juli 1916', '28. Juni 1914']],
          ['Wie endete die Skagerrakschlacht?', 'Keine Seite gewann die Seeherrschaft', ['Die deutsche Flotte wurde vernichtet', 'Die britische Flotte wurde vernichtet', 'Sie fand gar nicht statt']],
          ['Wie viele Amerikaner starben auf der Lusitania?', '128', ['12', '1200', '500']],
          ['Wie lange dauerte die Schlacht um Verdun?', 'Von Februar bis Dezember 1916', ['Eine Woche', 'Drei Jahre', 'Von Juli bis November 1916']],
          ['Welche Länder gehörten zur Entente, als sie später erweitert wurde?', 'Italien und die USA', ['Bulgarien und die Türkei', 'Spanien und Schweden', 'Japan']],
          ['Welche Idee lag dem Schlieffen-Plan zugrunde?', 'Frankreich schnell besiegen, bevor Russland gerüstet war', ['Russland zuerst besiegen', 'England durch eine Invasion besiegen', 'Nur zu verteidigen']],
          ['Wofür steht der Name Tannenberg auch?', 'Für eine Schlacht des Deutschen Ordens 1410', ['Für einen Friedensvertrag', 'Für eine Festung in Frankreich', 'Für einen Kaiser']],
          ['Wann sicherte Deutschland Österreich den Blankoscheck zu?', 'Anfang Juli 1914', ['Im Juni 1913', 'Im August 1914', 'Im Mai 1915']],
          ['Welche neue Art von Krieg brachte der Erste Weltkrieg?', 'Den industriellen Massenkrieg', ['Den Ritterkrieg', 'Den Kabinettskrieg', 'Den Atomkrieg']],
          ['Welche Waffe beherrschte die Schützengräben besonders?', 'Das Maschinengewehr', ['Die Armbrust', 'Die Kanone mit Vorderlader', 'Der Säbel']],
          ['Wozu wurde Hindenburg nach Tannenberg?', 'Zum Volkshelden', ['Zum Kaiser', 'Zum Kanzler sofort', 'Zum Gefangenen']],
          ['Was brachte Großbritannien 1914 in den Krieg?', 'Der deutsche Einmarsch in das neutrale Belgien', ['Die Versenkung der Lusitania', 'Ein Angriff auf London', 'Das Zimmermann-Telegramm']],
        ],
      },
    },
    {
      id: 'kriegsende-versailles',
      title: 'Kriegsende, Revolution und Versailles',
      date: '1916–1919',
      text: [
        'In der Heimat wurde das Leben immer härter. Die britische Seeblockade schnitt Deutschland von Lebensmitteleinfuhren ab. Im „Steckrübenwinter“ 1916/17 gab es kaum noch Kartoffeln, und die Menschen mussten sich von Steckrüben ernähren; Hunderttausende starben an Hunger und Krankheiten. Frauen arbeiteten in Rüstungsfabriken. Die Oberste Heeresleitung unter Hindenburg und Ludendorff bestimmte ab 1916 auch die Politik weitgehend selbst.',
        'Im Februar 1917 begann Deutschland den uneingeschränkten U-Boot-Krieg und versenkte nun alle Schiffe in den Gewässern um Großbritannien. Außerdem bot der Staatssekretär Arthur Zimmermann im „Zimmermann-Telegramm“ Mexiko ein Bündnis gegen die USA an. Am 6. April 1917 traten die USA in den Krieg ein. In Russland stürzte dagegen 1917 die Revolution den Zaren; die Bolschewiki unter Lenin schlossen am 3. März 1918 mit Deutschland den Frieden von Brest-Litowsk.',
        'Die deutsche Frühjahrsoffensive 1918 im Westen scheiterte. Am 8. August 1918, dem „schwarzen Tag des deutschen Heeres“, durchbrachen alliierte Panzer die Front. Ende September 1918 verlangte Ludendorff plötzlich einen sofortigen Waffenstillstand. Anfang Oktober 1918 wurde Prinz Max von Baden Reichskanzler, und das Reich wurde parlamentarisiert.',
        'Als die Marineleitung Ende Oktober 1918 die Flotte zu einer aussichtslosen letzten Schlacht auslaufen lassen wollte, meuterten die Matrosen. Am 3. November 1918 begann in Kiel der Matrosenaufstand, und überall bildeten sich Arbeiter- und Soldatenräte. Am 9. November 1918 verkündete Max von Baden eigenmächtig die Abdankung des Kaisers und übergab die Regierung an den SPD-Vorsitzenden Friedrich Ebert. Philipp Scheidemann rief vom Reichstag aus die Republik aus, Karl Liebknecht wenig später vom Berliner Schloss eine „freie sozialistische Republik“. Wilhelm II. ging ins Exil in die Niederlande, wo er bis zu seinem Tod 1941 in Doorn lebte.',
        'Am 11. November 1918 unterzeichnete Matthias Erzberger im Wald von Compiègne den Waffenstillstand. Im Ersten Weltkrieg waren rund 17 Millionen Menschen gestorben, darunter etwa zwei Millionen deutsche Soldaten. Die Heeresführung, die den Krieg verloren hatte, schob die Schuld bald anderen zu: Nach der „Dolchstoßlegende“ war das „im Felde unbesiegte“ Heer von Revolutionären in der Heimat verraten worden – eine Lüge, die die Republik schwer belastete.',
        'Am 28. Juni 1919 – genau fünf Jahre nach Sarajevo – musste Deutschland im Spiegelsaal von Versailles den Friedensvertrag unterschreiben, über den es nicht mitverhandeln durfte. Deutschland verlor etwa ein Siebtel seines Gebiets: Elsass-Lothringen an Frankreich, Posen und Westpreußen (den „Polnischen Korridor“) an Polen, Eupen-Malmedy an Belgien, später Nordschleswig an Dänemark; Danzig wurde Freie Stadt, das Memelland kam unter alliierte Verwaltung. Alle Kolonien gingen verloren. Das Heer wurde auf 100.000 Mann begrenzt, eine Luftwaffe verboten und das Rheinland entmilitarisiert und besetzt. Nach Artikel 231 trugen Deutschland und seine Verbündeten die Verantwortung für den Krieg; daraus leiteten die Sieger hohe Reparationen ab, 1921 auf 132 Milliarden Goldmark festgesetzt. Viele Deutsche sprachen vom „Schandfrieden“ oder „Diktatfrieden“.',
      ],
      quiz: {
        leicht: [
          ['In welchem Jahr endete der Erste Weltkrieg?', '1918', ['1914', '1919', '1945']],
          ['Wie nennt man den Hungerwinter 1916/17?', 'Steckrübenwinter', ['Kartoffelwinter', 'Kohlwinter', 'Brotwinter']],
          ['Welches Land trat 1917 an der Seite der Entente in den Krieg ein?', 'Die USA', ['Japan', 'Spanien', 'Schweden']],
          ['In welchem Land stürzte 1917 eine Revolution den Herrscher?', 'In Russland', ['In England', 'In Frankreich', 'In Italien']],
          ['Wer führte die Bolschewiki an?', 'Lenin', ['Stalin', 'Rasputin', 'Der Zar']],
          ['Wo begann im November 1918 der Matrosenaufstand?', 'In Kiel', ['In Hamburg', 'In Berlin', 'In München']],
          ['An welchem Tag wurde in Deutschland die Republik ausgerufen?', '9. November 1918', ['11. November 1918', '18. Januar 1871', '28. Juni 1919']],
          ['Wer rief vom Reichstag die Republik aus?', 'Philipp Scheidemann', ['Friedrich Ebert', 'Karl Liebknecht', 'Rosa Luxemburg']],
          ['Wohin ging Kaiser Wilhelm II. ins Exil?', 'In die Niederlande', ['Nach England', 'Nach Amerika', 'Nach Russland']],
          ['Wann trat der Waffenstillstand in Kraft?', '11. November 1918', ['9. November 1918', '28. Juni 1919', '1. Januar 1919']],
          ['Wie viele Menschen starben im Ersten Weltkrieg etwa?', 'Rund 17 Millionen', ['Rund 1,7 Millionen', 'Rund 170.000', 'Rund 70 Millionen']],
          ['Welcher Friedensvertrag beendete den Krieg für Deutschland?', 'Der Vertrag von Versailles', ['Der Westfälische Frieden', 'Der Frieden von Frankfurt', 'Der Zwei-plus-Vier-Vertrag']],
          ['Welches Gebiet bekam Frankreich zurück?', 'Elsass-Lothringen', ['Bayern', 'Das Saarland für immer', 'Die Pfalz für immer']],
          ['Was verlor Deutschland in Übersee?', 'Alle Kolonien', ['Nichts', 'Nur Togo', 'Nur Samoa']],
          ['Wie groß durfte das deutsche Heer nach Versailles höchstens sein?', '100.000 Mann', ['1 Million Mann', '10.000 Mann', 'Unbegrenzt']],
          ['Was durfte Deutschland nach Versailles nicht mehr haben?', 'Eine Luftwaffe', ['Eine Polizei', 'Eine Eisenbahn', 'Eine Regierung']],
          ['Wie nennt man die Zahlungen an die Siegermächte?', 'Reparationen', ['Subventionen', 'Dividenden', 'Spenden']],
          ['Wie nannten viele Deutsche den Vertrag von Versailles?', '„Schandfrieden“', ['„Gerechter Frieden“', '„Ewiger Frieden“', '„Glücksfrieden“']],
          ['Welche Lüge sollte die Schuld an der Niederlage anderen zuschieben?', 'Die Dolchstoßlegende', ['Die Nibelungensage', 'Die Kyffhäusersage', 'Die Loreley']],
          ['Wer wurde am 9. November 1918 Regierungschef?', 'Friedrich Ebert', ['Paul von Hindenburg', 'Gustav Stresemann', 'Wilhelm II.']],
        ],
        mittel: [
          ['Was schnitt Deutschland von Lebensmitteln ab?', 'Die britische Seeblockade', ['Ein Erdbeben', 'Die Pest', 'Ein Streik der Bauern']],
          ['Wer bestimmte ab 1916 weitgehend die Politik?', 'Die Oberste Heeresleitung', ['Der Reichstag', 'Der Kaiser', 'Die SPD']],
          ['Wann begann der uneingeschränkte U-Boot-Krieg?', 'Februar 1917', ['August 1914', 'Mai 1915', 'November 1918']],
          ['Welches Telegramm bot Mexiko ein Bündnis gegen die USA an?', 'Das Zimmermann-Telegramm', ['Die Emser Depesche', 'Die Krüger-Depesche', 'Der Blankoscheck']],
          ['An welchem Tag traten die USA in den Krieg ein?', '6. April 1917', ['7. Mai 1915', '11. November 1918', '3. März 1918']],
          ['Welcher Frieden wurde 1918 mit Russland geschlossen?', 'Der Frieden von Brest-Litowsk', ['Der Frieden von Versailles', 'Der Frieden von Rapallo', 'Der Frieden von Tilsit']],
          ['Wie nennt man den 8. August 1918?', 'Den schwarzen Tag des deutschen Heeres', ['Den Tag der Befreiung', 'Den Tag der Republik', 'Den Tag der Einheit']],
          ['Wer verlangte Ende September 1918 einen sofortigen Waffenstillstand?', 'Ludendorff', ['Ebert', 'Scheidemann', 'Erzberger']],
          ['Wer wurde im Oktober 1918 Reichskanzler?', 'Prinz Max von Baden', ['Friedrich Ebert', 'Bethmann Hollweg', 'Gustav Stresemann']],
          ['Was bildete sich nach dem Matrosenaufstand überall?', 'Arbeiter- und Soldatenräte', ['Bürgerwehren der Kaisertreuen', 'Neue Monarchien', 'Kirchengemeinden']],
          ['Was rief Karl Liebknecht am 9. November aus?', 'Eine „freie sozialistische Republik“', ['Die Monarchie', 'Den Krieg', 'Den Frieden mit Frankreich']],
          ['Wo lebte Wilhelm II. im Exil?', 'In Doorn', ['In Amsterdam', 'In London', 'In Wien']],
          ['Wer unterzeichnete den Waffenstillstand für Deutschland?', 'Matthias Erzberger', ['Friedrich Ebert', 'Paul von Hindenburg', 'Walther Rathenau']],
          ['Wo wurde der Waffenstillstand unterzeichnet?', 'Im Wald von Compiègne', ['In Versailles', 'In Berlin', 'In Spa']],
          ['Wie viele deutsche Soldaten starben etwa?', 'Rund zwei Millionen', ['Rund 200.000', 'Rund 20 Millionen', 'Rund 20.000']],
          ['An welchem Tag wurde der Vertrag von Versailles unterschrieben?', '28. Juni 1919', ['11. November 1918', '9. November 1918', '18. Januar 1919']],
          ['Welcher Artikel des Vertrags gab Deutschland die Verantwortung für den Krieg?', 'Artikel 231', ['Artikel 48', 'Artikel 1', 'Artikel 146']],
          ['Welches Gebiet erhielt Polen?', 'Posen und Westpreußen', ['Ostpreußen', 'Schlesien ganz', 'Pommern']],
          ['Was wurde aus Danzig?', 'Eine Freie Stadt', ['Eine polnische Stadt', 'Eine deutsche Stadt', 'Eine russische Stadt']],
          ['Wie hoch wurden die Reparationen 1921 festgesetzt?', '132 Milliarden Goldmark', ['13 Millionen Goldmark', '1 Billion Goldmark', '5 Milliarden Francs']],
        ],
        schwer: [
          ['Wer war 1917 Staatssekretär des Auswärtigen und schrieb das Telegramm an Mexiko?', 'Arthur Zimmermann', ['Bernhard von Bülow', 'Walther Rathenau', 'Gustav Stresemann']],
          ['An welchem Tag wurde der Frieden von Brest-Litowsk geschlossen?', '3. März 1918', ['6. April 1917', '11. November 1918', '9. November 1918']],
          ['Was wollte die Marineleitung Ende Oktober 1918?', 'Die Flotte zu einer letzten Schlacht auslaufen lassen', ['Die Flotte versenken', 'Mit den Briten verhandeln', 'Nach Amerika fahren']],
          ['An welchem Tag begann der Kieler Matrosenaufstand?', '3. November 1918', ['9. November 1918', '11. November 1918', '28. Oktober 1918']],
          ['Wer verkündete eigenmächtig die Abdankung Wilhelms II.?', 'Prinz Max von Baden', ['Friedrich Ebert', 'Philipp Scheidemann', 'Hindenburg']],
          ['Von wo rief Liebknecht die sozialistische Republik aus?', 'Vom Berliner Schloss', ['Vom Reichstag', 'Vom Brandenburger Tor', 'Vom Roten Rathaus']],
          ['Wann starb Wilhelm II.?', '1941', ['1918', '1933', '1945']],
          ['Welchen Anteil seines Gebiets verlor Deutschland durch Versailles etwa?', 'Etwa ein Siebtel', ['Die Hälfte', 'Ein Hundertstel', 'Gar nichts']],
          ['Welches Gebiet erhielt Belgien?', 'Eupen-Malmedy', ['Aachen', 'Luxemburg', 'Das Saarland']],
          ['Welches Gebiet kam später an Dänemark?', 'Nordschleswig', ['Holstein', 'Helgoland', 'Rügen']],
          ['Was geschah mit dem Memelland?', 'Es kam unter alliierte Verwaltung', ['Es blieb deutsch', 'Es wurde russisch', 'Es wurde Freie Stadt wie Danzig']],
          ['Wie nannte man den Landstreifen, der Ostpreußen vom Reich trennte?', 'Polnischer Korridor', ['Danziger Gang', 'Weichselbrücke', 'Ostmark']],
          ['Was war mit dem Rheinland vorgesehen?', 'Es wurde entmilitarisiert und besetzt', ['Es wurde französisch', 'Es wurde selbstständig', 'Es wurde geteilt']],
          ['Warum wurde der 28. Juni 1919 bewusst gewählt?', 'Es war der fünfte Jahrestag von Sarajevo', ['Es war Wilhelms Geburtstag', 'Es war der Tag der Reichsgründung', 'Zufall']],
          ['Durfte Deutschland über den Versailler Vertrag mitverhandeln?', 'Nein', ['Ja, gleichberechtigt', 'Ja, aber nur über Kolonien', 'Ja, mit Vetorecht']],
          ['Welche Formulierung benutzte die Dolchstoßlegende für das Heer?', '„Im Felde unbesiegt“', ['„Ehrenvoll geschlagen“', '„Von Gott verlassen“', '„Für den Kaiser gefallen“']],
          ['Wie nennt man auch den Vertrag von Versailles abwertend außer „Schandfrieden“?', '„Diktatfrieden“', ['„Siegfrieden“', '„Verständigungsfrieden“', '„Burgfrieden“']],
          ['Welche Folge hatte die Seeblockade für viele Menschen in Deutschland?', 'Hunderttausende starben an Hunger und Krankheiten', ['Keine', 'Die Preise sanken', 'Mehr Exporte']],
          ['Wann wurde das Reich parlamentarisiert?', 'Im Oktober 1918', ['Im August 1914', 'Im Januar 1919', 'Im November 1917']],
          ['In welchem Jahr wurde die Höhe der Reparationen festgesetzt?', '1921', ['1919', '1923', '1929']],
        ],
      },
    },
  ],
};

export const WEIMAR: HistEvent = {
  id: 'weimarer-republik',
  title: 'Die Weimarer Republik',
  date: '1918–1933',
  text: [
    'Die erste deutsche Demokratie hatte einen schweren Start: Aufstände von links und rechts, politische Morde und eine riesige Inflation. Nach wenigen „goldenen“ Jahren stürzte die Weltwirtschaftskrise sie ins Chaos – und die Nationalsozialisten kamen an die Macht.',
  ],
  subtopics: [
    {
      id: 'krisenjahre',
      title: 'Gründung und Krisenjahre',
      date: '1918–1923',
      text: [
        'Nach der Revolution regierte zunächst der Rat der Volksbeauftragten unter Friedrich Ebert. Um Ruhe und Ordnung zu sichern, verbündete sich Ebert am 10. November 1918 mit General Wilhelm Groener von der Obersten Heeresleitung (Ebert-Groener-Pakt). Im Januar 1919 versuchten radikale Linke im Spartakusaufstand in Berlin, eine Räterepublik zu erzwingen. Regierungstruppen und Freikorps schlugen den Aufstand nieder; am 15. Januar 1919 ermordeten Freikorpsoffiziere Rosa Luxemburg und Karl Liebknecht, die zum Jahreswechsel 1918/19 die KPD gegründet hatten.',
        'Am 19. Januar 1919 wählten die Deutschen eine Nationalversammlung – zum ersten Mal durften auch Frauen wählen (das Frauenwahlrecht galt seit dem 12. November 1918). Weil Berlin zu unruhig war, trat sie im ruhigen Weimar zusammen; daher der Name „Weimarer Republik“. Sie wählte am 11. Februar 1919 Friedrich Ebert zum ersten Reichspräsidenten. SPD, Zentrum und die liberale DDP bildeten die „Weimarer Koalition“.',
        'Die Weimarer Verfassung trat im August 1919 in Kraft. Sie gab allen Bürgern Grundrechte und ein demokratisches Wahlrecht. Der Reichspräsident wurde direkt vom Volk für sieben Jahre gewählt und war sehr mächtig: Nach Artikel 48 konnte er im Notfall Notverordnungen ohne das Parlament erlassen und den Reichstag auflösen. Das reine Verhältniswahlrecht ohne Sperrklausel führte zu vielen kleinen Parteien und instabilen Regierungen.',
        'Viele Gegner der Republik griffen zur Gewalt. Im März 1920 versuchten rechte Freikorps wie die Marinebrigade Ehrhardt im Kapp-Putsch, die Regierung zu stürzen. Die Reichswehr griff nicht ein („Truppe schießt nicht auf Truppe“), doch ein Generalstreik der Arbeiter ließ den Putsch nach wenigen Tagen scheitern. Rechtsradikale ermordeten Politiker: 1921 Matthias Erzberger, der den Waffenstillstand unterschrieben hatte, und am 24. Juni 1922 Außenminister Walther Rathenau.',
        'Als Deutschland mit Reparationen in Rückstand geriet, besetzten französische und belgische Truppen im Januar 1923 das Ruhrgebiet. Die Regierung rief zum passiven Widerstand auf und bezahlte die streikenden Arbeiter, indem sie immer mehr Geld druckte. Es kam zur Hyperinflation: Im November 1923 kostete ein US-Dollar 4,2 Billionen Mark, ein Brot Milliarden. Ersparnisse wurden wertlos, viele Mittelschichtfamilien verarmten. Am 15. November 1923 beendete die Rentenmark die Inflation; eine Rentenmark entsprach einer Billion Papiermark.',
        'Am 8. und 9. November 1923 versuchte Adolf Hitler mit seiner NSDAP, die aus der kleinen Deutschen Arbeiterpartei (DAP) hervorgegangen war, in München, vom Bürgerbräukeller aus die Macht zu ergreifen und nach Berlin zu marschieren (Hitlerputsch). Die bayerische Polizei stoppte den Marsch an der Feldherrnhalle. Hitler wurde zu fünf Jahren Festungshaft verurteilt, aber schon im Dezember 1924 entlassen. In der Haft in Landsberg schrieb er sein Buch „Mein Kampf“.',
      ],
      quiz: {
        leicht: [
          ['Wie heißt die erste deutsche Demokratie?', 'Weimarer Republik', ['Bonner Republik', 'Berliner Republik', 'Frankfurter Republik']],
          ['Warum heißt sie „Weimarer“ Republik?', 'Die Nationalversammlung tagte in Weimar', ['Der Präsident kam aus Weimar', 'Goethe gründete sie', 'Sie endete in Weimar']],
          ['Wer war der erste Reichspräsident?', 'Friedrich Ebert', ['Paul von Hindenburg', 'Gustav Stresemann', 'Philipp Scheidemann']],
          ['Wann durften Frauen in Deutschland erstmals wählen?', '1919', ['1871', '1949', '1900']],
          ['Welche Kommunistin wurde im Januar 1919 ermordet?', 'Rosa Luxemburg', ['Clara Zetkin', 'Käthe Kollwitz', 'Sophie Scholl']],
          ['Für wie viele Jahre wurde der Reichspräsident gewählt?', 'Sieben', ['Vier', 'Fünf', 'Zehn']],
          ['Welcher Artikel erlaubte dem Präsidenten Notverordnungen?', 'Artikel 48', ['Artikel 1', 'Artikel 231', 'Artikel 20']],
          ['Welcher Putsch scheiterte 1920 an einem Generalstreik?', 'Der Kapp-Putsch', ['Der Hitlerputsch', 'Der Spartakusaufstand', 'Der Röhm-Putsch']],
          ['Welcher Außenminister wurde 1922 ermordet?', 'Walther Rathenau', ['Gustav Stresemann', 'Matthias Erzberger', 'Friedrich Ebert']],
          ['Welches Gebiet besetzten Frankreich und Belgien 1923?', 'Das Ruhrgebiet', ['Das Saarland', 'Bayern', 'Berlin']],
          ['Was geschah 1923 mit dem Geld?', 'Es verlor durch Inflation fast seinen ganzen Wert', ['Es wurde abgeschafft', 'Es wurde mehr wert', 'Es wurde durch Gold ersetzt']],
          ['Wie nennt man eine extreme Geldentwertung?', 'Hyperinflation', ['Deflation', 'Rezession', 'Boom']],
          ['Welche neue Währung beendete die Inflation 1923?', 'Die Rentenmark', ['Die D-Mark', 'Der Euro', 'Die Goldmark']],
          ['In welcher Stadt versuchte Hitler 1923 einen Putsch?', 'München', ['Berlin', 'Nürnberg', 'Weimar']],
          ['Welches Buch schrieb Hitler in der Haft?', '„Mein Kampf“', ['„Das Kapital“', '„Der Untertan“', '„Im Westen nichts Neues“']],
          ['Welche Parteien bildeten die „Weimarer Koalition“?', 'SPD, Zentrum und DDP', ['NSDAP, KPD und DNVP', 'CDU, CSU und FDP', 'SPD, KPD und USPD']],
          ['Welche Folge hatte das Verhältniswahlrecht ohne Sperrklausel?', 'Viele kleine Parteien', ['Nur zwei Parteien', 'Gar keine Parteien', 'Ein Einparteienstaat']],
          ['Wer wurde von der Inflation besonders hart getroffen?', 'Sparer aus der Mittelschicht', ['Menschen mit Schulden', 'Besitzer von Sachwerten', 'Niemand']],
          ['Wo wurde der Hitlerputsch von der Polizei gestoppt?', 'An der Feldherrnhalle', ['Am Brandenburger Tor', 'Am Reichstag', 'Am Hofbräuhaus']],
          ['Welcher Aufstand fand im Januar 1919 in Berlin statt?', 'Der Spartakusaufstand', ['Der Kapp-Putsch', 'Der Hitlerputsch', 'Der Volksaufstand']],
        ],
        mittel: [
          ['Wie hieß die Revolutionsregierung unter Ebert?', 'Rat der Volksbeauftragten', ['Reichsregierung', 'Zentralkomitee', 'Volksrat']],
          ['Mit welchem General verbündete sich Ebert am 10. November 1918?', 'Wilhelm Groener', ['Erich Ludendorff', 'Paul von Hindenburg', 'Hans von Seeckt']],
          ['Wann wurden Luxemburg und Liebknecht ermordet?', '15. Januar 1919', ['9. November 1918', '19. Januar 1919', '11. August 1919']],
          ['Wer ermordete Luxemburg und Liebknecht?', 'Freikorpsoffiziere', ['Kommunisten', 'Die Polizei Münchens', 'Französische Soldaten']],
          ['Wann wurde die Nationalversammlung gewählt?', '19. Januar 1919', ['9. November 1918', '11. August 1919', '1. Januar 1920']],
          ['Seit wann galt das Frauenwahlrecht?', '12. November 1918', ['1. Januar 1919', '19. Januar 1919', '11. August 1919']],
          ['Wann wurde Ebert zum Reichspräsidenten gewählt?', '11. Februar 1919', ['9. November 1918', '19. Januar 1919', '28. Juni 1919']],
          ['Welche Partei war die DDP?', 'Eine liberale Partei', ['Eine kommunistische Partei', 'Eine katholische Partei', 'Eine nationalsozialistische Partei']],
          ['Wann trat die Weimarer Verfassung in Kraft?', 'August 1919', ['Januar 1919', 'November 1918', 'März 1920']],
          ['Was konnte der Reichspräsident außer Notverordnungen tun?', 'Den Reichstag auflösen', ['Den Papst ernennen', 'Kriege ohne Grund führen', 'Gesetze rückwirkend aufheben']],
          ['Wann fand der Kapp-Putsch statt?', 'März 1920', ['Januar 1919', 'November 1923', 'Juni 1922']],
          ['Mit welchem Satz blieb die Reichswehr beim Kapp-Putsch untätig?', '„Truppe schießt nicht auf Truppe“', ['„Für Kaiser und Reich“', '„Wir sind das Volk“', '„Befehl ist Befehl“']],
          ['Wann wurde Matthias Erzberger ermordet?', '1921', ['1919', '1922', '1923']],
          ['Wann wurde Walther Rathenau ermordet?', '24. Juni 1922', ['15. Januar 1919', '9. November 1923', '28. Juni 1919']],
          ['Wann begann die Ruhrbesetzung?', 'Januar 1923', ['November 1918', 'März 1920', 'Oktober 1929']],
          ['Wozu rief die Regierung während der Ruhrbesetzung auf?', 'Zum passiven Widerstand', ['Zum Krieg', 'Zur Flucht', 'Zur Zusammenarbeit']],
          ['Wie viel kostete ein US-Dollar im November 1923?', '4,2 Billionen Mark', ['4,20 Mark', '42.000 Mark', '4,2 Millionen Mark']],
          ['Wann wurde die Rentenmark eingeführt?', '15. November 1923', ['9. November 1923', '1. Januar 1924', '20. Juni 1948']],
          ['Wie viel Papiermark entsprach einer Rentenmark?', 'Eine Billion', ['Eine Million', 'Tausend', 'Zehn']],
          ['Von wo aus startete der Hitlerputsch?', 'Vom Bürgerbräukeller', ['Vom Hofbräuhaus', 'Von der Feldherrnhalle', 'Vom Braunen Haus']],
        ],
        schwer: [
          ['Wie nennt man Eberts Bündnis mit der Heeresleitung?', 'Ebert-Groener-Pakt', ['Stinnes-Legien-Abkommen', 'Burgfrieden', 'Rapallo-Vertrag']],
          ['Wann wurde die KPD gegründet?', 'Zum Jahreswechsel 1918/19', ['1914', '1923', '1929']],
          ['Wer gründete die KPD unter anderem?', 'Rosa Luxemburg und Karl Liebknecht', ['Ebert und Scheidemann', 'Thälmann und Ulbricht', 'Marx und Engels']],
          ['In welcher Stadt war es 1919 zu unruhig für die Nationalversammlung?', 'Berlin', ['Weimar', 'München', 'Frankfurt']],
          ['Wie lange dauerte der Kapp-Putsch etwa?', 'Wenige Tage', ['Ein Jahr', 'Ein Monat', 'Eine Stunde']],
          ['Was ließ den Kapp-Putsch scheitern?', 'Ein Generalstreik der Arbeiter', ['Der Einsatz der Reichswehr', 'Französische Truppen', 'Ein Unwetter']],
          ['Wer schoss Rathenau nieder?', 'Rechtsradikale Attentäter', ['Kommunisten', 'Französische Agenten', 'Die Polizei']],
          ['Wie bezahlte die Regierung die streikenden Arbeiter im Ruhrkampf?', 'Indem sie immer mehr Geld druckte', ['Mit Krediten aus den USA', 'Mit Gold aus der Reichsbank', 'Gar nicht']],
          ['Was kostete ein Brot im Herbst 1923 etwa?', 'Milliarden Mark', ['Ein paar Pfennig', 'Zehn Mark', 'Tausend Mark']],
          ['Zu welcher Strafe wurde Hitler 1924 verurteilt?', 'Fünf Jahre Festungshaft', ['Todesstrafe', 'Lebenslang', 'Freispruch']],
          ['Wann wurde Hitler aus der Haft entlassen?', 'Dezember 1924', ['November 1928', 'Januar 1933', 'Juni 1923']],
          ['Wo saß Hitler in Haft?', 'In Landsberg am Lech', ['In Dachau', 'In Spandau', 'In Stadelheim']],
          ['Wann fand der Hitlerputsch statt?', '8. und 9. November 1923', ['9. November 1918', '30. Januar 1933', '1. September 1923']],
          ['Welche Länder besetzten das Ruhrgebiet?', 'Frankreich und Belgien', ['England und Frankreich', 'Polen und Russland', 'Die USA und England']],
          ['Weshalb wurde das Ruhrgebiet besetzt?', 'Deutschland war mit Reparationen in Rückstand', ['Wegen eines Aufstands', 'Wegen des Hitlerputsches', 'Wegen Kohlemangels in Frankreich']],
          ['Wie lange war die Amtszeit des Reichspräsidenten?', 'Sieben Jahre', ['Vier Jahre', 'Fünf Jahre', 'Lebenslang']],
          ['Wie wurde der Reichspräsident gewählt?', 'Direkt vom Volk', ['Vom Reichstag', 'Vom Bundesrat', 'Von den Ländern']],
          ['Welche Freikorps-Einheiten waren beim Kapp-Putsch dabei?', 'Die Marinebrigade Ehrhardt', ['Die SS', 'Die Reichswehr', 'Die Volksmarinedivision']],
          ['Welche Partei gründete Hitler nicht, sondern übernahm er?', 'Die NSDAP (aus der DAP)', ['Die SPD', 'Das Zentrum', 'Die DNVP']],
          ['Welcher Politiker hatte den Waffenstillstand unterschrieben und wurde 1921 ermordet?', 'Matthias Erzberger', ['Walther Rathenau', 'Kurt Eisner', 'Hugo Haase']],
        ],
      },
    },
    {
      id: 'goldene-zwanziger-ende',
      title: 'Goldene Zwanziger und das Ende der Republik',
      date: '1924–1933',
      text: [
        'Gustav Stresemann, 1923 kurz Reichskanzler und danach bis zu seinem Tod Außenminister, führte Deutschland aus der Isolation. Der Dawes-Plan von 1924 ordnete die Reparationen neu und brachte amerikanische Kredite ins Land. 1925 erkannte Deutschland im Vertrag von Locarno seine Westgrenze an, 1926 wurde es in den Völkerbund aufgenommen. Stresemann und der französische Außenminister Aristide Briand erhielten dafür den Friedensnobelpreis. 1925 wurde der frühere Feldmarschall Paul von Hindenburg zum Reichspräsidenten gewählt.',
        'In den „Goldenen Zwanzigern“ blühte vor allem in Berlin die Kultur. 1919 gründete Walter Gropius in Weimar das Bauhaus, das 1925 nach Dessau zog und modernes Design prägte. Fritz Lang drehte 1927 den Film „Metropolis“, Bertolt Brecht und Kurt Weill schufen 1928 die „Dreigroschenoper“, Marlene Dietrich wurde 1930 mit „Der blaue Engel“ berühmt. Albert Einstein erhielt 1921 den Nobelpreis für Physik, Thomas Mann 1929 den für Literatur. Erich Maria Remarque beschrieb 1929 in „Im Westen nichts Neues“ den Krieg aus Sicht eines einfachen Soldaten.',
        'Am 24. Oktober 1929 brach die New Yorker Börse zusammen („Schwarzer Donnerstag“; in Deutschland sprach man vom „Schwarzen Freitag“). Amerikanische Banken zogen ihre Kredite zurück, Firmen gingen pleite, und Anfang 1932 waren in Deutschland rund sechs Millionen Menschen arbeitslos. Kurz zuvor, am 3. Oktober 1929, war Stresemann gestorben; im selben Jahr hatte der Young-Plan die Reparationen erneut geregelt.',
        'Im März 1930 zerbrach die Große Koalition am Streit über die Arbeitslosenversicherung. Hindenburg ernannte Heinrich Brüning vom Zentrum zum Kanzler, der ohne Mehrheit im Reichstag mit Notverordnungen nach Artikel 48 regierte (Präsidialkabinett). Seine harte Sparpolitik verschärfte die Not. Bei der Wahl im September 1930 sprang die NSDAP von 2,6 auf 18,3 Prozent; auch die KPD wuchs. Auf den Straßen kämpften SA und Rotfrontkämpfer.',
        '1932 wurde Hindenburg wiedergewählt, Hitler erreichte als Gegenkandidat 36,8 Prozent. Brüning wurde entlassen; sein Nachfolger Franz von Papen setzte am 20. Juli 1932 die preußische Regierung ab („Preußenschlag“). Bei der Reichstagswahl im Juli 1932 wurde die NSDAP mit 37,3 Prozent stärkste Partei, im November sank sie auf 33,1 Prozent. Nach dem kurzen Kabinett Kurt von Schleichers überredete ein Kreis um Papen den 85-jährigen Hindenburg, Hitler zum Kanzler zu machen – sie glaubten, ihn „einrahmen“ und lenken zu können. Am 30. Januar 1933 ernannte Hindenburg Adolf Hitler zum Reichskanzler.',
      ],
      quiz: {
        leicht: [
          ['Wie nennt man die Jahre um 1925 in der Weimarer Republik?', 'Goldene Zwanziger', ['Wilde Dreißiger', 'Graue Zehner', 'Wirtschaftswunder']],
          ['Welcher Politiker führte Deutschland aus der Isolation?', 'Gustav Stresemann', ['Heinrich Brüning', 'Franz von Papen', 'Kurt von Schleicher']],
          ['Welchen Preis erhielt Stresemann?', 'Den Friedensnobelpreis', ['Den Karlspreis', 'Den Oscar', 'Den Pulitzerpreis']],
          ['In welche Organisation wurde Deutschland 1926 aufgenommen?', 'In den Völkerbund', ['In die UNO', 'In die NATO', 'In die EU']],
          ['Welche Kunstschule gründete Walter Gropius?', 'Das Bauhaus', ['Die Kunstakademie Düsseldorf', 'Die Brücke', 'Den Blauen Reiter']],
          ['Welcher berühmte Film von Fritz Lang erschien 1927?', '„Metropolis“', ['„Der blaue Engel“', '„Nosferatu“', '„M“']],
          ['Welcher Physiker erhielt 1921 den Nobelpreis?', 'Albert Einstein', ['Max Planck', 'Werner Heisenberg', 'Röntgen']],
          ['Welcher Antikriegsroman erschien 1929?', '„Im Westen nichts Neues“', ['„Der Untertan“', '„Die Blechtrommel“', '„Der Zauberberg“']],
          ['Welche Schauspielerin wurde mit „Der blaue Engel“ berühmt?', 'Marlene Dietrich', ['Greta Garbo', 'Romy Schneider', 'Leni Riefenstahl']],
          ['Wo brach 1929 die Börse zusammen?', 'In New York', ['In Berlin', 'In London', 'In Paris']],
          ['Wie viele Menschen waren Anfang 1932 in Deutschland arbeitslos?', 'Rund sechs Millionen', ['Rund 60.000', 'Rund 600.000', 'Rund 60 Millionen']],
          ['Welche Partei wurde 1932 stärkste Partei?', 'Die NSDAP', ['Die SPD', 'Die KPD', 'Das Zentrum']],
          ['Wer wurde 1925 Reichspräsident?', 'Paul von Hindenburg', ['Friedrich Ebert', 'Adolf Hitler', 'Gustav Stresemann']],
          ['Wann wurde Hitler Reichskanzler?', '30. Januar 1933', ['9. November 1923', '1. September 1939', '27. Februar 1933']],
          ['Wer ernannte Hitler zum Reichskanzler?', 'Reichspräsident Hindenburg', ['Das Volk direkt', 'Der Reichstag', 'Franz von Papen']],
          ['Wie nennt man die Weltwirtschaftskrise ab 1929 auch?', 'Große Depression', ['Gründerkrach', 'Ölkrise', 'Finanzkrise 2008']],
          ['Welche Kampftruppe der NSDAP kämpfte auf den Straßen?', 'Die SA', ['Die Bundeswehr', 'Die Polizei', 'Die Reichswehr']],
          ['Wie regierte Kanzler Brüning ohne Mehrheit?', 'Mit Notverordnungen des Präsidenten', ['Mit Hilfe der Armee', 'Mit Volksabstimmungen', 'Gar nicht']],
          ['Welche Stadt war Zentrum der Kultur der Zwanziger?', 'Berlin', ['München', 'Wien', 'Hamburg']],
          ['Welches Theaterstück schufen Brecht und Weill 1928?', 'Die „Dreigroschenoper“', ['„Mutter Courage“', '„Faust“', '„Die Weber“']],
        ],
        mittel: [
          ['Welcher Plan regelte 1924 die Reparationen neu?', 'Der Dawes-Plan', ['Der Young-Plan', 'Der Marshallplan', 'Der Schlieffen-Plan']],
          ['Was brachte der Dawes-Plan ins Land?', 'Amerikanische Kredite', ['Französisches Gold', 'Russisches Getreide', 'Britische Soldaten']],
          ['Was erkannte Deutschland im Vertrag von Locarno an?', 'Seine Westgrenze', ['Seine Ostgrenze', 'Die Teilung Deutschlands', 'Die Kriegsschuld']],
          ['Wann wurde der Vertrag von Locarno geschlossen?', '1925', ['1919', '1929', '1933']],
          ['Mit welchem Franzosen erhielt Stresemann den Friedensnobelpreis?', 'Aristide Briand', ['Georges Clemenceau', 'Charles de Gaulle', 'Raymond Poincaré']],
          ['Wann zog das Bauhaus nach Dessau?', '1925', ['1919', '1933', '1929']],
          ['Wann erhielt Thomas Mann den Nobelpreis?', '1929', ['1921', '1933', '1955']],
          ['Wann brach die New Yorker Börse zusammen?', '24. Oktober 1929', ['30. Januar 1933', '3. Oktober 1929', '1. September 1929']],
          ['Wann starb Stresemann?', '3. Oktober 1929', ['24. Oktober 1929', '30. Januar 1933', '1926']],
          ['Welcher Plan regelte 1929 die Reparationen erneut?', 'Der Young-Plan', ['Der Dawes-Plan', 'Der Morgenthau-Plan', 'Der Vierjahresplan']],
          ['Woran zerbrach die Große Koalition im März 1930?', 'Am Streit über die Arbeitslosenversicherung', ['Am Streit über die Flagge', 'Am Kapp-Putsch', 'An der Ruhrbesetzung']],
          ['Wie nennt man Regierungen, die nur durch den Präsidenten getragen wurden?', 'Präsidialkabinette', ['Volksfrontregierungen', 'Große Koalitionen', 'Räteregierungen']],
          ['Welcher Partei gehörte Heinrich Brüning an?', 'Dem Zentrum', ['Der SPD', 'Der NSDAP', 'Der DNVP']],
          ['Wie stark wurde die NSDAP bei der Wahl im September 1930?', '18,3 Prozent', ['2,6 Prozent', '37,3 Prozent', '43,9 Prozent']],
          ['Wie viel Prozent erhielt die NSDAP im Juli 1932?', '37,3 Prozent', ['18,3 Prozent', '33,1 Prozent', '51 Prozent']],
          ['Wie viel Prozent erhielt die NSDAP im November 1932?', '33,1 Prozent', ['37,3 Prozent', '43,9 Prozent', '18,3 Prozent']],
          ['Was geschah beim „Preußenschlag“ 1932?', 'Die preußische Regierung wurde abgesetzt', ['Preußen wurde aufgelöst', 'Preußen erklärte die Unabhängigkeit', 'Der König kehrte zurück']],
          ['Wer folgte Brüning als Kanzler?', 'Franz von Papen', ['Kurt von Schleicher', 'Adolf Hitler', 'Gustav Stresemann']],
          ['Wer war der letzte Kanzler vor Hitler?', 'Kurt von Schleicher', ['Franz von Papen', 'Heinrich Brüning', 'Hermann Müller']],
          ['Was glaubten Papen und andere über Hitler?', 'Sie könnten ihn „einrahmen“ und lenken', ['Er würde bald zurücktreten', 'Er sei Kommunist', 'Er sei ungefährlich, weil er keine Partei hatte']],
        ],
        schwer: [
          ['Wie viel Prozent erreichte Hitler 1932 bei der Präsidentenwahl?', '36,8 Prozent', ['53 Prozent', '18,3 Prozent', '43,9 Prozent']],
          ['An welchem Tag fand der Preußenschlag statt?', '20. Juli 1932', ['30. Januar 1933', '27. Februar 1933', '20. Juli 1944']],
          ['Wie stark war die NSDAP vor der Wahl 1930?', '2,6 Prozent', ['18,3 Prozent', '10 Prozent', '0,5 Prozent']],
          ['Wann war Stresemann Reichskanzler?', '1923', ['1925', '1929', '1919']],
          ['Welches Amt hatte Stresemann ab 1923 bis zu seinem Tod?', 'Außenminister', ['Reichskanzler', 'Reichspräsident', 'Finanzminister']],
          ['Wie hieß der „Schwarze Donnerstag“ in Deutschland wegen der Zeitverschiebung?', '„Schwarzer Freitag“', ['„Schwarzer Montag“', '„Blauer Montag“', '„Roter Donnerstag“']],
          ['Welche Kampftruppe der KPD kämpfte gegen die SA?', 'Der Rotfrontkämpferbund', ['Das Reichsbanner', 'Der Stahlhelm', 'Die Freikorps']],
          ['Welche Politik verfolgte Brüning in der Krise?', 'Eine harte Sparpolitik', ['Hohe Staatsausgaben', 'Gelddrucken', 'Verstaatlichung aller Firmen']],
          ['Welche Folge hatte Brünings Sparpolitik?', 'Sie verschärfte die Not', ['Sie beendete die Krise sofort', 'Sie hatte keine Folgen', 'Sie führte zu Vollbeschäftigung']],
          ['Wann wurde Hindenburg wiedergewählt?', '1932', ['1925', '1930', '1933']],
          ['Wer drehte „Metropolis“?', 'Fritz Lang', ['Friedrich Wilhelm Murnau', 'Leni Riefenstahl', 'Billy Wilder']],
          ['Wer komponierte die Musik zur „Dreigroschenoper“?', 'Kurt Weill', ['Hanns Eisler', 'Richard Strauss', 'Paul Hindemith']],
          ['Wann erschien „Der blaue Engel“?', '1930', ['1927', '1933', '1925']],
          ['Wann wurde das Bauhaus gegründet?', '1919', ['1925', '1909', '1933']],
          ['Wer schrieb „Im Westen nichts Neues“?', 'Erich Maria Remarque', ['Ernst Jünger', 'Thomas Mann', 'Kurt Tucholsky']],
          ['Wann wurde Deutschland in den Völkerbund aufgenommen?', '1926', ['1919', '1925', '1933']],
          ['In welcher Stadt war das Bauhaus zuerst?', 'Weimar', ['Dessau', 'Berlin', 'Stuttgart']],
          ['Wie alt war Hindenburg 1933 etwa?', '85 Jahre', ['55 Jahre', '65 Jahre', '95 Jahre']],
          ['Wodurch kamen die amerikanischen Kredite nach 1929 in Gefahr?', 'US-Banken zogen sie nach dem Börsenkrach zurück', ['Deutschland zahlte sie sofort zurück', 'Die USA schenkten sie', 'Sie waren nie da']],
          ['Welche Partei wuchs 1930 neben der NSDAP ebenfalls?', 'Die KPD', ['Die DDP', 'Die DVP', 'Das Zentrum']],
        ],
      },
    },
  ],
};
