import type { HistEvent } from '../types';

export const NS_ZEIT: HistEvent = {
  id: 'nationalsozialismus',
  title: 'Nationalsozialismus und Zweiter Weltkrieg',
  date: '1933–1945',
  text: [
    'In wenigen Monaten verwandelten die Nationalsozialisten die Demokratie in eine Diktatur. Sie verfolgten politische Gegner, entrechteten die Juden und ermordeten schließlich rund sechs Millionen von ihnen. Der von Deutschland begonnene Zweite Weltkrieg kostete über 60 Millionen Menschen das Leben. Nur wenige wagten Widerstand.',
  ],
  subtopics: [
    {
      id: 'diktatur',
      title: 'Machtübernahme und Diktatur',
      date: '1933–1939',
      text: [
        'In der Nacht zum 28. Februar 1933 – genauer am Abend des 27. Februar – brannte der Reichstag. Festgenommen wurde der Niederländer Marinus van der Lubbe. Die Nationalsozialisten behaupteten, es sei der Beginn eines kommunistischen Aufstands. Schon am nächsten Tag hob die „Reichstagsbrandverordnung“ die wichtigsten Grundrechte auf; Tausende Kommunisten und Sozialdemokraten wurden verhaftet. Bei der Reichstagswahl am 5. März 1933 erreichte die NSDAP trotz Terror nur 43,9 Prozent. Beim „Tag von Potsdam“ am 21. März inszenierte sich Hitler neben Hindenburg als Erbe Preußens.',
        'Am 23. März 1933 beschloss der Reichstag das Ermächtigungsgesetz, mit dem die Regierung Gesetze ohne das Parlament erlassen konnte. Die KPD-Abgeordneten waren bereits verhaftet oder geflohen. Nur die SPD stimmte dagegen; ihr Vorsitzender Otto Wels sagte: „Freiheit und Leben kann man uns nehmen, die Ehre nicht.“ Das Gesetz wurde mit 444 zu 94 Stimmen angenommen.',
        'Nun folgte die „Gleichschaltung“: Die Länder verloren ihre Selbstständigkeit, am 2. Mai 1933 wurden die Gewerkschaften zerschlagen, die Parteien verboten oder lösten sich auf; seit dem 14. Juli 1933 war die NSDAP die einzige erlaubte Partei. Am 10. Mai 1933 verbrannten Studenten in vielen Städten Bücher „undeutscher“ Autoren wie Heinrich Heine, Erich Kästner und Thomas Mann; Kästner sah in Berlin selbst zu, wie seine Bücher brannten. Schon im März 1933 entstand in Dachau eines der ersten Konzentrationslager.',
        'Am 30. Juni 1934 ließ Hitler die Führung der SA um Ernst Röhm und weitere Gegner ermorden („Röhm-Putsch“ oder „Nacht der langen Messer“). Als Hindenburg am 2. August 1934 starb, vereinigte Hitler die Ämter des Reichspräsidenten und des Kanzlers und nannte sich „Führer und Reichskanzler“. Die Soldaten mussten nun einen Eid auf ihn persönlich schwören.',
        'Propagandaminister Joseph Goebbels kontrollierte Presse, Radio und Film; der billige „Volksempfänger“ brachte die Reden Hitlers in jede Wohnung. Kinder und Jugendliche sollten in der Hitlerjugend (HJ) und dem Bund Deutscher Mädel (BDM) im Sinne der Partei erzogen werden. Die Geheime Staatspolizei (Gestapo) und die SS unter Heinrich Himmler verfolgten Gegner. Durch Aufrüstung und Projekte wie den Autobahnbau sank die Arbeitslosigkeit. Bei den Olympischen Spielen 1936 in Berlin präsentierte sich das Regime der Welt als friedlich; der afroamerikanische Sprinter Jesse Owens gewann vier Goldmedaillen.',
        'Außenpolitisch brach Hitler Schritt für Schritt den Versailler Vertrag: 1935 führte er die Wehrpflicht wieder ein, 1936 marschierten deutsche Truppen ins entmilitarisierte Rheinland. Am 12./13. März 1938 wurde Österreich „angeschlossen“ und nun „Ostmark“ genannt. Im Münchner Abkommen vom 29./30. September 1938 überließen Großbritannien (Neville Chamberlain), Frankreich (Édouard Daladier) und Italien (Benito Mussolini) Deutschland das Sudetenland – man nennt diese Nachgiebigkeit „Appeasement“. Im März 1939 besetzte Deutschland die übrige Tschechoslowakei („Rest-Tschechei“). Am 23. August 1939 schlossen Hitler und Stalin einen Nichtangriffspakt mit einem geheimen Zusatzprotokoll, das Osteuropa aufteilte.',
      ],
      quiz: {
        leicht: [
          ['Welches Gebäude brannte im Februar 1933?', 'Der Reichstag', ['Das Brandenburger Tor', 'Das Berliner Schloss', 'Der Kölner Dom']],
          ['Welches Gesetz gab Hitler 1933 die Macht, Gesetze ohne Parlament zu erlassen?', 'Das Ermächtigungsgesetz', ['Das Grundgesetz', 'Die Goldene Bulle', 'Das Sozialistengesetz']],
          ['Welche Partei stimmte als einzige gegen das Ermächtigungsgesetz?', 'Die SPD', ['Das Zentrum', 'Die NSDAP', 'Die DNVP']],
          ['Wie nennt man die Unterwerfung aller Bereiche unter die NSDAP?', 'Gleichschaltung', ['Reformation', 'Entnazifizierung', 'Restauration']],
          ['Was verbrannten Studenten am 10. Mai 1933?', 'Bücher', ['Fahnen', 'Kirchen', 'Geld']],
          ['Wo entstand eines der ersten Konzentrationslager?', 'In Dachau', ['In Auschwitz', 'In Treblinka', 'In Bergen-Belsen']],
          ['Wer war Propagandaminister?', 'Joseph Goebbels', ['Hermann Göring', 'Heinrich Himmler', 'Rudolf Heß']],
          ['Wie hieß das billige Radio der NS-Zeit?', 'Volksempfänger', ['Volkswagen', 'Volksradio', 'Führerfunk']],
          ['Wie hieß die Jugendorganisation für Jungen?', 'Hitlerjugend', ['Pfadfinder', 'Junge Union', 'FDJ']],
          ['Wie hieß die Organisation für Mädchen?', 'Bund Deutscher Mädel', ['Mädchenbund', 'Junge Pionierinnen', 'Deutscher Frauenbund']],
          ['Wie hieß die Geheimpolizei der Nationalsozialisten?', 'Gestapo', ['Stasi', 'KGB', 'Tscheka']],
          ['Wer führte die SS?', 'Heinrich Himmler', ['Ernst Röhm', 'Joseph Goebbels', 'Hermann Göring']],
          ['Wo fanden 1936 die Olympischen Spiele statt?', 'In Berlin', ['In München', 'In Hamburg', 'In London']],
          ['Welcher Sportler gewann 1936 vier Goldmedaillen?', 'Jesse Owens', ['Carl Lewis', 'Max Schmeling', 'Usain Bolt']],
          ['Welches Land wurde 1938 „angeschlossen“?', 'Österreich', ['Schweiz', 'Polen', 'Dänemark']],
          ['Welches Gebiet erhielt Deutschland im Münchner Abkommen?', 'Das Sudetenland', ['Das Elsass', 'Danzig', 'Südtirol']],
          ['Wie nennt man die Nachgiebigkeit Großbritanniens gegenüber Hitler?', 'Appeasement', ['Blitzkrieg', 'Containment', 'Détente']],
          ['Mit wem schloss Hitler im August 1939 einen Pakt?', 'Mit Stalin', ['Mit Churchill', 'Mit Roosevelt', 'Mit Franco']],
          ['Welchen Titel gab sich Hitler 1934?', '„Führer und Reichskanzler“', ['„Kaiser“', '„König“', '„Präsident“']],
          ['Wodurch sank die Arbeitslosigkeit unter anderem?', 'Durch Aufrüstung und Autobahnbau', ['Durch Kurzarbeit', 'Durch Auswanderung', 'Durch die Weltwirtschaftskrise']],
        ],
        mittel: [
          ['Wann brannte der Reichstag?', '27. Februar 1933', ['30. Januar 1933', '23. März 1933', '10. Mai 1933']],
          ['Wer wurde nach dem Reichstagsbrand festgenommen?', 'Marinus van der Lubbe', ['Ernst Thälmann', 'Georg Elser', 'Otto Wels']],
          ['Was hob die Reichstagsbrandverordnung auf?', 'Die wichtigsten Grundrechte', ['Die Monarchie', 'Den Versailler Vertrag', 'Die Wehrpflicht']],
          ['Wie viel Prozent erhielt die NSDAP am 5. März 1933?', '43,9 Prozent', ['37,3 Prozent', '51 Prozent', '99 Prozent']],
          ['Wann wurde das Ermächtigungsgesetz beschlossen?', '23. März 1933', ['27. Februar 1933', '30. Januar 1933', '2. August 1934']],
          ['Wer sagte: „Freiheit und Leben kann man uns nehmen, die Ehre nicht“?', 'Otto Wels', ['Kurt Schumacher', 'Friedrich Ebert', 'Willy Brandt']],
          ['Wann wurden die Gewerkschaften zerschlagen?', '2. Mai 1933', ['1. Mai 1933', '10. Mai 1933', '14. Juli 1933']],
          ['Seit wann war die NSDAP einzige erlaubte Partei?', '14. Juli 1933', ['30. Januar 1933', '23. März 1933', '2. August 1934']],
          ['Wessen Bücher wurden 1933 unter anderem verbrannt?', 'Heinrich Heines und Erich Kästners', ['Goethes und Schillers', 'Luthers', 'Hitlers']],
          ['Wann fand der „Röhm-Putsch“ statt?', '30. Juni 1934', ['2. August 1934', '9. November 1938', '27. Februar 1933']],
          ['Wer war Anführer der SA, der 1934 ermordet wurde?', 'Ernst Röhm', ['Heinrich Himmler', 'Hermann Göring', 'Reinhard Heydrich']],
          ['Wann starb Hindenburg?', '2. August 1934', ['30. Januar 1933', '30. Juni 1934', '1. September 1939']],
          ['Auf wen mussten die Soldaten ab 1934 schwören?', 'Auf Hitler persönlich', ['Auf die Verfassung', 'Auf den Kaiser', 'Auf das Volk']],
          ['Was inszenierte Hitler am „Tag von Potsdam“?', 'Sich als Erbe Preußens neben Hindenburg', ['Einen Krieg gegen Polen', 'Die Bücherverbrennung', 'Die Olympischen Spiele']],
          ['Wann führte Hitler die Wehrpflicht wieder ein?', '1935', ['1933', '1938', '1939']],
          ['Wann marschierten deutsche Truppen ins Rheinland?', '1936', ['1935', '1938', '1933']],
          ['Wann wurde Österreich angeschlossen?', 'März 1938', ['September 1938', 'März 1939', 'Januar 1933']],
          ['Welcher britische Premierminister unterzeichnete das Münchner Abkommen?', 'Neville Chamberlain', ['Winston Churchill', 'Clement Attlee', 'Stanley Baldwin']],
          ['Wann besetzte Deutschland die übrige Tschechoslowakei?', 'März 1939', ['September 1938', 'März 1938', 'September 1939']],
          ['Wann schlossen Hitler und Stalin den Nichtangriffspakt?', '23. August 1939', ['1. September 1939', '22. Juni 1941', '30. September 1938']],
        ],
        schwer: [
          ['Aus welchem Land stammte Marinus van der Lubbe?', 'Aus den Niederlanden', ['Aus Polen', 'Aus Österreich', 'Aus Russland']],
          ['Wann war der „Tag von Potsdam“?', '21. März 1933', ['23. März 1933', '5. März 1933', '30. Januar 1933']],
          ['Mit wie vielen Stimmen wurde das Ermächtigungsgesetz angenommen?', '444 zu 94', ['288 zu 196', '500 zu 0', '300 zu 200']],
          ['Warum fehlten die KPD-Abgeordneten bei der Abstimmung?', 'Sie waren verhaftet oder geflohen', ['Sie boykottierten freiwillig', 'Sie waren krank', 'Sie stimmten zu']],
          ['Welcher Schriftsteller sah selbst zu, wie seine Bücher verbrannt wurden?', 'Erich Kästner', ['Thomas Mann', 'Heinrich Heine', 'Bertolt Brecht']],
          ['Wann entstand das KZ Dachau?', 'März 1933', ['Januar 1933', 'November 1938', 'Juni 1941']],
          ['Welche Ämter vereinigte Hitler 1934?', 'Reichspräsident und Reichskanzler', ['Kanzler und Papst', 'Kanzler und Kaiser', 'Präsident und Bürgermeister']],
          ['Wie nennt man den Röhm-Putsch auch?', 'Nacht der langen Messer', ['Reichskristallnacht', 'Nacht der Republik', 'Bartholomäusnacht']],
          ['Welcher französische Ministerpräsident unterzeichnete das Münchner Abkommen?', 'Édouard Daladier', ['Charles de Gaulle', 'Léon Blum', 'Philippe Pétain']],
          ['Wann wurde das Münchner Abkommen geschlossen?', '29./30. September 1938', ['12./13. März 1938', '9./10. November 1938', '23. August 1939']],
          ['Was regelte das geheime Zusatzprotokoll des Hitler-Stalin-Pakts?', 'Die Aufteilung Osteuropas', ['Den Handel mit Öl', 'Einen Angriff auf England', 'Die Rückgabe des Elsass']],
          ['Welcher italienische Diktator war am Münchner Abkommen beteiligt?', 'Benito Mussolini', ['Italo Balbo', 'Victor Emmanuel III.', 'Francisco Franco']],
          ['Welches Großprojekt der NS-Zeit diente der Propaganda und Arbeitsbeschaffung?', 'Der Autobahnbau', ['Der Bau des Panamakanals', 'Die Elbphilharmonie', 'Der Mauerbau']],
          ['Wie präsentierte sich das Regime bei den Olympischen Spielen?', 'Als friedlich und weltoffen', ['Als kriegerisch', 'Gar nicht', 'Als kommunistisch']],
          ['Wie nannten die Nationalsozialisten die besetzte übrige Tschechoslowakei?', '„Rest-Tschechei“', ['„Sudetenland“', '„Ostmark“', '„Generalgouvernement“']],
          ['Welche Behauptung verbreiteten die Nationalsozialisten zum Reichstagsbrand?', 'Es sei der Beginn eines kommunistischen Aufstands', ['Es sei ein Unfall gewesen', 'Die Franzosen seien schuld', 'Es sei ein Blitzschlag gewesen']],
          ['Welche Bezeichnung erhielt Österreich nach dem Anschluss?', 'Ostmark', ['Westmark', 'Südmark', 'Reichsland']],
          ['Welcher Vertrag wurde durch Wehrpflicht und Rheinlandbesetzung gebrochen?', 'Der Versailler Vertrag', ['Das Münchner Abkommen', 'Der Hitler-Stalin-Pakt', 'Der Westfälische Frieden']],
          ['Was geschah am 2. Mai 1933?', 'Die Gewerkschaften wurden zerschlagen', ['Der Reichstag brannte', 'Hindenburg starb', 'Die Olympischen Spiele begannen']],
          ['Wie viele Goldmedaillen gewann Jesse Owens 1936?', 'Vier', ['Eine', 'Zwei', 'Sieben']],
        ],
      },
    },
    {
      id: 'holocaust',
      title: 'Verfolgung der Juden und Holocaust',
      date: '1933–1945',
      text: [
        'Der Judenhass (Antisemitismus) war Kern der nationalsozialistischen Weltanschauung. Am 1. April 1933 riefen die Nationalsozialisten zum Boykott jüdischer Geschäfte, Ärzte und Anwälte auf; SA-Männer standen vor den Läden. Mit dem „Gesetz zur Wiederherstellung des Berufsbeamtentums“ im April 1933 wurden jüdische Beamte entlassen.',
        'Die „Nürnberger Gesetze“ vom 15. September 1935 – das Reichsbürgergesetz und das „Blutschutzgesetz“ – machten Juden zu Bürgern zweiter Klasse ohne politische Rechte und verboten Ehen zwischen Juden und „Deutschblütigen“. Nach und nach wurden Juden aus Berufen, Schulen, Vereinen und dem öffentlichen Leben ausgeschlossen und zur Auswanderung gedrängt; viele mussten dabei ihr Vermögen zurücklassen.',
        'In der Nacht vom 9. auf den 10. November 1938 steckten SA- und SS-Männer im ganzen Reich Synagogen in Brand, zerstörten jüdische Geschäfte und Wohnungen und misshandelten Menschen (Novemberpogrom, von den Nationalsozialisten verharmlosend „Reichskristallnacht“ genannt). Vorwand war das Attentat des jungen Herschel Grynszpan auf den Diplomaten Ernst vom Rath in Paris. Rund 1400 Synagogen und Betstuben wurden zerstört, etwa 30.000 jüdische Männer in Konzentrationslager verschleppt, Hunderte starben.',
        'Nach dem Überfall auf die Sowjetunion 1941 erschossen Einsatzgruppen der SS und Polizei hinter der Front Hunderttausende Juden, etwa in der Schlucht von Babyn Jar bei Kiew, wo im September 1941 in zwei Tagen über 33.000 Menschen ermordet wurden. Ab September 1941 mussten Juden in Deutschland einen gelben „Judenstern“ tragen, ab Oktober wurden sie in den Osten deportiert. Am 20. Januar 1942 besprachen hohe Beamte unter Reinhard Heydrich auf der Wannseekonferenz in Berlin die Organisation der „Endlösung der Judenfrage“, also des Mordes an allen europäischen Juden; Adolf Eichmann schrieb das Protokoll.',
        'In Vernichtungslagern im besetzten Polen – Auschwitz-Birkenau, Treblinka, Sobibor, Belzec, Majdanek und Kulmhof (Chełmno) – wurden Menschen in Gaskammern ermordet. Allein in Auschwitz starben rund 1,1 Millionen Menschen. Am 27. Januar 1945 befreite die Rote Armee Auschwitz; der Tag ist heute internationaler Holocaust-Gedenktag. Insgesamt ermordeten die Nationalsozialisten rund sechs Millionen Juden. Man nennt diesen Völkermord Holocaust oder hebräisch Shoah. Im April 1943 erhoben sich die Menschen im Warschauer Ghetto in einem verzweifelten Aufstand.',
        'Verfolgt und ermordet wurden auch Hunderttausende Sinti und Roma (ihr Völkermord heißt Porajmos), Homosexuelle, Zeugen Jehovas, politische Gegner und Kriegsgefangene, vor allem aus der Sowjetunion. In der „Euthanasie“-Aktion „T4“ wurden ab 1939 Kranke und Menschen mit Behinderung ermordet; nach Protesten wie der Predigt des Bischofs Clemens August von Galen 1941 wurde die Aktion offiziell gestoppt, aber heimlich fortgesetzt. Das Tagebuch der Anne Frank, eines in Frankfurt geborenen jüdischen Mädchens, das sich in Amsterdam versteckte und 1945 im KZ Bergen-Belsen starb, ist eines der bekanntesten Zeugnisse dieser Zeit.',
      ],
      quiz: {
        leicht: [
          ['Wie nennt man den Völkermord an den europäischen Juden?', 'Holocaust oder Shoah', ['Reformation', 'Inquisition', 'Kulturkampf']],
          ['Wie viele Juden wurden im Holocaust etwa ermordet?', 'Rund sechs Millionen', ['Rund 600.000', 'Rund 60.000', 'Rund 60 Millionen']],
          ['Was ist Antisemitismus?', 'Judenhass', ['Liebe zur Heimat', 'Ein Glaube', 'Eine Partei']],
          ['Wozu riefen die Nationalsozialisten am 1. April 1933 auf?', 'Zum Boykott jüdischer Geschäfte', ['Zu einer Wahl', 'Zum Krieg', 'Zu einem Fest']],
          ['Welche Gesetze von 1935 entrechteten die Juden?', 'Die Nürnberger Gesetze', ['Die Münchner Gesetze', 'Die Berliner Gesetze', 'Die Weimarer Gesetze']],
          ['Was geschah in der Nacht vom 9. auf den 10. November 1938?', 'Synagogen brannten im ganzen Reich', ['Der Krieg begann', 'Die Mauer fiel', 'Hitler wurde Kanzler']],
          ['Was mussten Juden ab 1941 auf der Kleidung tragen?', 'Einen gelben Stern', ['Ein rotes Kreuz', 'Ein blaues Band', 'Eine weiße Rose']],
          ['Auf welcher Konferenz wurde 1942 der Mord an den Juden organisiert?', 'Auf der Wannseekonferenz', ['Auf der Potsdamer Konferenz', 'Auf der Konferenz von Jalta', 'Auf dem Wiener Kongress']],
          ['Welches war das größte Vernichtungslager?', 'Auschwitz-Birkenau', ['Dachau', 'Buchenwald', 'Theresienstadt']],
          ['In welchem heutigen Land lag Auschwitz?', 'In Polen', ['In Deutschland', 'In Tschechien', 'In Österreich']],
          ['Wann wurde Auschwitz befreit?', '27. Januar 1945', ['8. Mai 1945', '9. November 1938', '1. September 1939']],
          ['Wer befreite Auschwitz?', 'Die Rote Armee', ['Die US-Armee', 'Die britische Armee', 'Die Häftlinge selbst']],
          ['Welcher Tag ist heute Holocaust-Gedenktag?', 'Der 27. Januar', ['Der 8. Mai', 'Der 9. November', 'Der 3. Oktober']],
          ['Welches Mädchen schrieb ein berühmtes Tagebuch im Versteck?', 'Anne Frank', ['Sophie Scholl', 'Hannah Arendt', 'Rosa Luxemburg']],
          ['Wo versteckte sich Anne Frank?', 'In Amsterdam', ['In Berlin', 'In Paris', 'In Frankfurt']],
          ['Welche Volksgruppe wurde ebenfalls verfolgt und ermordet?', 'Sinti und Roma', ['Die Schweizer', 'Die Dänen', 'Die Bayern']],
          ['Wen ermordeten die Nationalsozialisten in der „Euthanasie“-Aktion?', 'Kranke und Menschen mit Behinderung', ['Soldaten', 'Bauern', 'Adlige']],
          ['Wo erhoben sich 1943 Juden in einem Aufstand?', 'Im Warschauer Ghetto', ['In Berlin', 'In Auschwitz', 'In Paris']],
          ['Was ist das hebräische Wort für den Holocaust?', 'Shoah', ['Schalom', 'Tora', 'Kibbuz']],
          ['Wie wurden in den Vernichtungslagern viele Menschen ermordet?', 'In Gaskammern', ['Durch Hitze', 'Gar nicht', 'Durch Erdbeben']],
        ],
        mittel: [
          ['Welches Gesetz entließ im April 1933 jüdische Beamte?', 'Das Gesetz zur Wiederherstellung des Berufsbeamtentums', ['Das Ermächtigungsgesetz', 'Das Reichsbürgergesetz', 'Das Blutschutzgesetz']],
          ['Wann wurden die Nürnberger Gesetze erlassen?', '15. September 1935', ['1. April 1933', '9. November 1938', '20. Januar 1942']],
          ['Was verboten die Nürnberger Gesetze unter anderem?', 'Ehen zwischen Juden und Nichtjuden', ['Das Autofahren', 'Das Wählen für alle', 'Das Reisen ins Ausland']],
          ['Wie nannten die Nationalsozialisten das Novemberpogrom verharmlosend?', '„Reichskristallnacht“', ['„Nacht der langen Messer“', '„Walpurgisnacht“', '„Kristallfest“']],
          ['Wer verübte das Attentat, das als Vorwand für das Pogrom diente?', 'Herschel Grynszpan', ['Georg Elser', 'Marinus van der Lubbe', 'Stauffenberg']],
          ['Auf wen schoss Grynszpan?', 'Auf den Diplomaten Ernst vom Rath', ['Auf Hitler', 'Auf Goebbels', 'Auf den französischen Präsidenten']],
          ['Wie viele Synagogen und Betstuben wurden 1938 etwa zerstört?', 'Rund 1400', ['Rund 14', 'Rund 140', 'Rund 14.000']],
          ['Wie viele jüdische Männer wurden 1938 in KZ verschleppt?', 'Rund 30.000', ['Rund 300', 'Rund 3000', 'Rund 300.000']],
          ['Wer ermordete hinter der Ostfront Hunderttausende Juden durch Erschießungen?', 'Die Einsatzgruppen', ['Die Kriegsmarine', 'Die Hitlerjugend', 'Die Feuerwehr']],
          ['In welcher Schlucht bei Kiew wurden 1941 über 33.000 Juden ermordet?', 'Babyn Jar', ['Katyn', 'Lidice', 'Oradour']],
          ['Ab wann wurden Juden aus Deutschland in den Osten deportiert?', 'Ab Oktober 1941', ['Ab Januar 1933', 'Ab November 1938', 'Ab Mai 1945']],
          ['Wann fand die Wannseekonferenz statt?', '20. Januar 1942', ['9. November 1938', '27. Januar 1945', '1. September 1939']],
          ['Wer leitete die Wannseekonferenz?', 'Reinhard Heydrich', ['Heinrich Himmler', 'Adolf Eichmann', 'Hermann Göring']],
          ['Wer schrieb das Protokoll der Wannseekonferenz?', 'Adolf Eichmann', ['Reinhard Heydrich', 'Joseph Goebbels', 'Martin Bormann']],
          ['Wie viele Menschen wurden allein in Auschwitz ermordet?', 'Rund 1,1 Millionen', ['Rund 110.000', 'Rund 11 Millionen', 'Rund 11.000']],
          ['Welches Vernichtungslager lag neben Auschwitz im besetzten Polen?', 'Treblinka', ['Dachau', 'Buchenwald', 'Sachsenhausen']],
          ['Wann erhoben sich die Menschen im Warschauer Ghetto?', 'April 1943', ['September 1939', 'August 1944', 'Januar 1945']],
          ['Wie hieß die „Euthanasie“-Mordaktion?', 'Aktion T4', ['Aktion Reinhardt', 'Operation Walküre', 'Unternehmen Barbarossa']],
          ['Welcher Bischof protestierte 1941 gegen die Krankenmorde?', 'Clemens August von Galen', ['Michael von Faulhaber', 'Dietrich Bonhoeffer', 'Martin Niemöller']],
          ['In welchem Lager starb Anne Frank?', 'Bergen-Belsen', ['Auschwitz', 'Dachau', 'Theresienstadt']],
        ],
        schwer: [
          ['Wann begannen die Mordaktionen an Kranken (T4)?', '1939', ['1933', '1942', '1945']],
          ['Wurde die Aktion T4 nach den Protesten wirklich beendet?', 'Nein, sie wurde heimlich fortgesetzt', ['Ja, vollständig', 'Sie begann erst danach', 'Es gab keine Proteste']],
          ['In welcher Stadt wurde Anne Frank geboren?', 'Frankfurt am Main', ['Amsterdam', 'Berlin', 'Hamburg']],
          ['Wann starb Anne Frank?', '1945', ['1942', '1944', '1950']],
          ['Welches Vernichtungslager hieß auf Polnisch Chełmno?', 'Kulmhof', ['Belzec', 'Sobibor', 'Majdanek']],
          ['Welche Lager gehörten zu den Vernichtungslagern?', 'Treblinka, Sobibor und Belzec', ['Dachau, Buchenwald und Neuengamme', 'Theresienstadt, Ravensbrück und Flossenbürg', 'Bergen-Belsen, Sachsenhausen und Esterwegen']],
          ['Ab wann mussten Juden im Reich den gelben Stern tragen?', 'September 1941', ['April 1933', 'November 1938', 'Januar 1942']],
          ['Wie verharmlosten die Täter den geplanten Mord an allen Juden?', 'Als „Endlösung der Judenfrage“', ['Als „Umsiedlung nach Amerika“', 'Als „Arbeitsdienst“', 'Als „Kulturkampf“']],
          ['In welcher Stadt wurde Ernst vom Rath 1938 erschossen?', 'In Paris', ['In Berlin', 'In Warschau', 'In Wien']],
          ['In welchem Stadtteil Berlins fand die Wannseekonferenz statt?', 'Am Wannsee', ['In Spandau', 'In Kreuzberg', 'In Charlottenburg']],
          ['Wie viele Menschen wurden in Babyn Jar in zwei Tagen ermordet?', 'Über 33.000', ['Rund 3300', 'Rund 330.000', 'Rund 330']],
          ['Wann wurden die Morde in Babyn Jar verübt?', 'September 1941', ['Juni 1941', 'Januar 1942', 'April 1943']],
          ['Welche Gruppen gehörten außerdem zu den Verfolgten?', 'Homosexuelle und Zeugen Jehovas', ['Nur Kommunisten', 'Nur Ausländer', 'Nur Katholiken']],
          ['Welche Kriegsgefangenen starben in besonders großer Zahl?', 'Sowjetische Kriegsgefangene', ['Amerikanische Kriegsgefangene', 'Britische Kriegsgefangene', 'Französische Kriegsgefangene']],
          ['Wie nennt man den Völkermord an den Sinti und Roma?', 'Porajmos', ['Shoah', 'Holodomor', 'Nakba']],
          ['Wer stand am 1. April 1933 vor jüdischen Geschäften?', 'SA-Männer', ['Polizisten aus England', 'Bauern', 'Priester']],
          ['Was mussten viele Juden bei der Auswanderung zurücklassen?', 'Ihr Vermögen', ['Ihre Kinder', 'Nichts', 'Ihre Sprache']],
          ['Wie hieß das Gesetz der Nürnberger Gesetze über die Staatsbürgerschaft?', 'Reichsbürgergesetz', ['Blutschutzgesetz', 'Staatsangehörigkeitsgesetz von 1913', 'Ermächtigungsgesetz']],
          ['Wie hieß das Gesetz, das Ehen verbot?', 'Blutschutzgesetz', ['Reichsbürgergesetz', 'Ehegesetz von 1900', 'Rassengesetz von Weimar']],
          ['Wie viele Menschen starben beim Novemberpogrom direkt etwa?', 'Hunderte', ['Niemand', 'Zehntausende', 'Millionen']],
        ],
      },
    },
    {
      id: 'zweiter-weltkrieg',
      title: 'Der Zweite Weltkrieg',
      date: '1939–1945',
      text: [
        'Am 1. September 1939 überfiel Deutschland Polen. Als Vorwand diente ein von der SS inszenierter „polnischer“ Überfall auf den Sender Gleiwitz; in Danzig beschoss das Schiff „Schleswig-Holstein“ die polnische Stellung auf der Westerplatte. Am 3. September erklärten Großbritannien und Frankreich Deutschland den Krieg. Am 17. September marschierte auch die Sowjetunion in Polen ein, das zwischen beiden aufgeteilt wurde.',
        'Im April 1940 besetzte Deutschland Dänemark und Norwegen. Am 10. Mai 1940 begann der Angriff im Westen: In einem schnellen „Blitzkrieg“ durch die Ardennen umgingen deutsche Panzer die französischen Befestigungen. Die britischen Truppen retteten sich über Dünkirchen. Frankreich kapitulierte am 22. Juni 1940 – im selben Eisenbahnwagen in Compiègne, in dem Deutschland 1918 den Waffenstillstand unterschrieben hatte. In der „Luftschlacht um England“ 1940 scheiterte der Versuch, Großbritannien unter Premierminister Winston Churchill zu bezwingen. In Nordafrika kämpfte ab 1941 das Afrikakorps unter Erwin Rommel.',
        'Am 22. Juni 1941 überfiel Deutschland im „Unternehmen Barbarossa“ die Sowjetunion. Es war ein Vernichtungskrieg gegen „Bolschewismus“ und „Untermenschen“, in dem Millionen Zivilisten und Kriegsgefangene starben. Leningrad wurde fast 900 Tage belagert, rund eine Million Menschen verhungerten. Im Dezember 1941 blieb die Wehrmacht vor Moskau stecken. Nach dem japanischen Angriff auf Pearl Harbor erklärte Hitler am 11. Dezember 1941 auch den USA den Krieg.',
        'Die Wende kam 1942/43. Im November 1942 schlossen sowjetische Truppen die 6. Armee in Stalingrad ein; Ende Januar und Anfang Februar 1943 kapitulierten die Reste unter General Friedrich Paulus. In Nordafrika siegten die Briten bei El Alamein. Am 18. Februar 1943 fragte Goebbels im Berliner Sportpalast: „Wollt ihr den totalen Krieg?“ Alliierte Bomber zerstörten nun deutsche Städte; beim Angriff auf Hamburg im Juli 1943 starben rund 34.000 Menschen, in Dresden im Februar 1945 rund 25.000.',
        'Am 6. Juni 1944 („D-Day“) landeten alliierte Truppen in der Normandie und eröffneten eine zweite Front im Westen. Von Osten rückte die Rote Armee vor. Millionen Deutsche flohen aus den Ostgebieten oder wurden nach dem Krieg vertrieben; insgesamt waren es 12 bis 14 Millionen Menschen. Im letzten Aufgebot, dem „Volkssturm“, mussten auch Jugendliche und alte Männer kämpfen.',
        'Am 30. April 1945 nahm sich Hitler im Bunker unter der Reichskanzlei das Leben. Am 2. Mai kapitulierte Berlin. Am 7. Mai unterzeichnete die Wehrmacht in Reims die bedingungslose Kapitulation, die am 8. Mai in Kraft trat und in der Nacht zum 9. Mai in Berlin-Karlshorst wiederholt wurde. Der 8. Mai gilt heute als Tag der Befreiung vom Nationalsozialismus. Im Zweiten Weltkrieg starben über 60 Millionen Menschen, allein in der Sowjetunion rund 27 Millionen.',
      ],
      quiz: {
        leicht: [
          ['Wann begann der Zweite Weltkrieg?', '1. September 1939', ['1. September 1914', '30. Januar 1933', '22. Juni 1941']],
          ['Welches Land überfiel Deutschland zuerst?', 'Polen', ['Frankreich', 'Russland', 'England']],
          ['Welche Länder erklärten Deutschland am 3. September 1939 den Krieg?', 'Großbritannien und Frankreich', ['Die USA und Japan', 'Russland und Polen', 'Italien und Spanien']],
          ['Wie nennt man die schnellen Panzervorstöße der Wehrmacht?', 'Blitzkrieg', ['Stellungskrieg', 'Grabenkrieg', 'Kalter Krieg']],
          ['Welches Land kapitulierte im Juni 1940?', 'Frankreich', ['Großbritannien', 'Russland', 'Polen']],
          ['Wer war ab 1940 britischer Premierminister?', 'Winston Churchill', ['Neville Chamberlain', 'Clement Attlee', 'Margaret Thatcher']],
          ['Welcher General führte das Afrikakorps?', 'Erwin Rommel', ['Friedrich Paulus', 'Erich von Manstein', 'Heinz Guderian']],
          ['Wann überfiel Deutschland die Sowjetunion?', '22. Juni 1941', ['1. September 1939', '6. Juni 1944', '8. Mai 1945']],
          ['Wie hieß der Angriffsplan gegen die Sowjetunion?', 'Unternehmen Barbarossa', ['Unternehmen Seelöwe', 'Operation Walküre', 'Operation Overlord']],
          ['Welche Stadt wurde fast 900 Tage belagert?', 'Leningrad', ['Moskau', 'Stalingrad', 'Kiew']],
          ['Welcher Schlacht gilt als Wende des Krieges im Osten?', 'Stalingrad', ['Dünkirchen', 'El Alamein', 'Verdun']],
          ['Welches Land erklärte Hitler im Dezember 1941 den Krieg?', 'Die USA', ['Japan', 'Italien', 'Spanien']],
          ['Was geschah am 6. Juni 1944?', 'Die Alliierten landeten in der Normandie', ['Hitler starb', 'Berlin kapitulierte', 'Der Krieg begann']],
          ['Wie nennt man den 6. Juni 1944?', 'D-Day', ['V-Day', 'Tag X', 'Stunde null']],
          ['Wann starb Hitler?', '30. April 1945', ['8. Mai 1945', '20. Juli 1944', '1. September 1939']],
          ['Wann endete der Krieg in Europa?', '8. Mai 1945', ['1. September 1945', '11. November 1918', '9. November 1945']],
          ['Wie nennt man den 8. Mai heute?', 'Tag der Befreiung', ['Tag der Einheit', 'Tag der Arbeit', 'Tag der Republik']],
          ['Wie viele Menschen starben im Zweiten Weltkrieg?', 'Über 60 Millionen', ['Rund 6 Millionen', 'Rund 600.000', 'Rund 17 Millionen']],
          ['Welches Land hatte die meisten Toten?', 'Die Sowjetunion', ['Deutschland', 'Frankreich', 'Die USA']],
          ['Wie nannte man das letzte Aufgebot aus Jugendlichen und Alten?', 'Volkssturm', ['Landsturm', 'Hitlerjugend', 'Reichswehr']],
        ],
        mittel: [
          ['Welcher Sender wurde für den Vorwand des Krieges inszeniert überfallen?', 'Der Sender Gleiwitz', ['Der Sender Königs Wusterhausen', 'Der Deutschlandsender', 'Radio Danzig']],
          ['Welche polnische Stellung beschoss die „Schleswig-Holstein“?', 'Die Westerplatte', ['Die Marienburg', 'Warschau', 'Krakau']],
          ['Wann marschierte die Sowjetunion in Polen ein?', '17. September 1939', ['1. September 1939', '22. Juni 1941', '3. September 1939']],
          ['Welche Länder besetzte Deutschland im April 1940?', 'Dänemark und Norwegen', ['Belgien und Holland', 'Griechenland und Jugoslawien', 'Schweden und Finnland']],
          ['Wann begann der Angriff im Westen?', '10. Mai 1940', ['1. September 1939', '22. Juni 1940', '6. Juni 1944']],
          ['Durch welches Gebiet stießen die Panzer überraschend vor?', 'Durch die Ardennen', ['Durch die Alpen', 'Durch die Pyrenäen', 'Durch das Elsass']],
          ['Wo retteten sich die britischen Truppen 1940?', 'Über Dünkirchen', ['Über Calais', 'Über Le Havre', 'Über Brest']],
          ['Wann kapitulierte Frankreich?', '22. Juni 1940', ['10. Mai 1940', '14. Juni 1940', '6. Juni 1944']],
          ['Wo unterschrieb Frankreich die Kapitulation?', 'Im Eisenbahnwagen von Compiègne', ['In Versailles', 'In Paris', 'In Vichy']],
          ['Wie hieß der Luftkrieg gegen Großbritannien 1940?', 'Luftschlacht um England', ['Operation Gomorrha', 'Operation Overlord', 'Unternehmen Seelöwe']],
          ['Wie viele Menschen verhungerten in Leningrad etwa?', 'Rund eine Million', ['Rund 10.000', 'Rund 100.000', 'Rund 10 Millionen']],
          ['Wo blieb die Wehrmacht im Dezember 1941 stecken?', 'Vor Moskau', ['Vor London', 'Vor Stalingrad', 'Vor Kiew']],
          ['Welcher japanische Angriff ging der Kriegserklärung an die USA voraus?', 'Pearl Harbor', ['Hiroshima', 'Midway', 'Iwo Jima']],
          ['Welche Armee wurde in Stalingrad eingeschlossen?', 'Die 6. Armee', ['Die 1. Armee', 'Das Afrikakorps', 'Die 3. Panzerarmee']],
          ['Welcher General kapitulierte in Stalingrad?', 'Friedrich Paulus', ['Erwin Rommel', 'Erich von Manstein', 'Wilhelm Keitel']],
          ['Wo siegten die Briten 1942 in Nordafrika?', 'Bei El Alamein', ['Bei Tobruk', 'Bei Kairo', 'Bei Tunis']],
          ['Was fragte Goebbels 1943 im Sportpalast?', '„Wollt ihr den totalen Krieg?“', ['„Wollt ihr Frieden?“', '„Wer ist schuld?“', '„Wollt ihr den Kaiser?“']],
          ['Wie viele Menschen starben beim Bombenangriff auf Hamburg 1943 etwa?', 'Rund 34.000', ['Rund 3400', 'Rund 340.000', 'Rund 340']],
          ['Wo unterzeichnete die Wehrmacht am 7. Mai 1945 die Kapitulation?', 'In Reims', ['In Berlin', 'In Paris', 'In Moskau']],
          ['Wie viele Deutsche flohen oder wurden vertrieben?', '12 bis 14 Millionen', ['1 bis 2 Millionen', '100.000', '30 Millionen']],
        ],
        schwer: [
          ['Wann kapitulierten die Reste der 6. Armee?', 'Ende Januar / Anfang Februar 1943', ['November 1942', 'Juni 1944', 'Mai 1945']],
          ['Wann wurde die 6. Armee eingeschlossen?', 'November 1942', ['Juni 1941', 'Februar 1943', 'Juli 1943']],
          ['Wann hielt Goebbels die Sportpalastrede?', '18. Februar 1943', ['30. Januar 1943', '20. Juli 1944', '1. September 1939']],
          ['Wie viele Menschen starben beim Angriff auf Dresden etwa?', 'Rund 25.000', ['Rund 2500', 'Rund 250.000', 'Rund 250']],
          ['Wann wurde Dresden bombardiert?', 'Februar 1945', ['Juli 1943', 'Mai 1945', 'Dezember 1944']],
          ['Wann erklärte Hitler den USA den Krieg?', '11. Dezember 1941', ['7. Dezember 1941', '22. Juni 1941', '6. Juni 1944']],
          ['Wie lange wurde Leningrad belagert?', 'Fast 900 Tage', ['90 Tage', '9 Tage', '9 Jahre']],
          ['Wo wurde die Kapitulation in der Nacht zum 9. Mai wiederholt?', 'In Berlin-Karlshorst', ['In Reims', 'In Flensburg', 'In Potsdam']],
          ['Wann kapitulierte Berlin?', '2. Mai 1945', ['30. April 1945', '8. Mai 1945', '16. April 1945']],
          ['Wo nahm sich Hitler das Leben?', 'Im Bunker unter der Reichskanzlei', ['Auf dem Obersalzberg', 'In der Wolfsschanze', 'In München']],
          ['Wie viele Menschen starben in der Sowjetunion etwa?', 'Rund 27 Millionen', ['Rund 2,7 Millionen', 'Rund 270.000', 'Rund 70 Millionen']],
          ['Welches deutsche Kriegsschiff eröffnete in Danzig den Krieg?', 'Die „Schleswig-Holstein“', ['Die „Bismarck“', 'Die „Tirpitz“', 'Die „Graf Spee“']],
          ['Wer inszenierte den Überfall auf den Sender Gleiwitz?', 'Die SS', ['Polnische Soldaten', 'Die Wehrmacht offen', 'Britische Agenten']],
          ['Warum wählte Hitler 1940 den Eisenbahnwagen von Compiègne?', 'Dort hatte Deutschland 1918 den Waffenstillstand unterschrieben', ['Er war besonders bequem', 'Er stand in Paris', 'Zufall']],
          ['Wie nannte die NS-Propaganda den Krieg gegen die Sowjetunion ideologisch?', 'Kampf gegen „Bolschewismus“ und „Untermenschen“', ['Befreiungskrieg', 'Friedensmission', 'Handelskrieg']],
          ['Welcher Art war der Krieg gegen die Sowjetunion?', 'Ein Vernichtungskrieg', ['Ein Kabinettskrieg', 'Ein Grenzkonflikt', 'Ein Handelskrieg']],
          ['Welche Front eröffnete der D-Day?', 'Eine zweite Front im Westen', ['Eine Front in Afrika', 'Eine Front in Asien', 'Eine Front in Skandinavien']],
          ['Wann trat die bedingungslose Kapitulation in Kraft?', 'Am 8. Mai 1945', ['Am 7. Mai 1945', 'Am 30. April 1945', 'Am 2. September 1945']],
          ['Wann begann die Luftschlacht um England?', '1940', ['1939', '1941', '1943']],
          ['Seit wann kämpfte das Afrikakorps in Nordafrika?', '1941', ['1939', '1943', '1944']],
        ],
      },
    },
    {
      id: 'widerstand',
      title: 'Widerstand gegen Hitler',
      date: '1933–1945',
      text: [
        'Gegen die Diktatur leisteten nur wenige Menschen Widerstand – unter Lebensgefahr. Kommunisten und Sozialdemokraten verteilten im Untergrund Flugblätter, viele landeten in Konzentrationslagern. Die Widerstandsgruppe „Rote Kapelle“ in Berlin sammelte Informationen und half Verfolgten. Jugendliche wie die „Edelweißpiraten“ verweigerten sich der Hitlerjugend.',
        'Auch aus den Kirchen kam Widerspruch. Der evangelische Pfarrer Martin Niemöller gründete den Pfarrernotbund, aus dem die Bekennende Kirche hervorging, und saß von 1937 bis 1945 im KZ. Der Theologe Dietrich Bonhoeffer gehörte zum Widerstand und wurde am 9. April 1945 im KZ Flossenbürg hingerichtet. Der katholische Bischof von Münster, Clemens August Graf von Galen, der „Löwe von Münster“, prangerte 1941 öffentlich die Morde an Kranken an.',
        'Am 8. November 1939 versuchte der schwäbische Schreiner Georg Elser ganz allein, Hitler zu töten: Er hatte eine Bombe in einer Säule des Münchner Bürgerbräukellers versteckt. Doch Hitler verließ den Saal 13 Minuten vor der Explosion. Elser wurde verhaftet und im April 1945 im KZ Dachau ermordet.',
        'In München verteilte die studentische Gruppe „Weiße Rose“ 1942/43 sechs Flugblätter gegen das Regime. Zu ihr gehörten die Geschwister Hans und Sophie Scholl, Christoph Probst, Alexander Schmorell, Willi Graf und der Professor Kurt Huber. Am 18. Februar 1943 warfen Hans und Sophie Scholl Flugblätter in den Lichthof der Münchner Universität; der Hausmeister entdeckte sie. Schon am 22. Februar 1943 verurteilte der Volksgerichtshof unter Roland Freisler sie und Christoph Probst zum Tod; sie wurden am selben Tag hingerichtet. Alexander Schmorell, Willi Graf und Kurt Huber wurden später ebenfalls hingerichtet.',
        'Offiziere und Beamte planten im Verborgenen einen Umsturz. Der Kreisauer Kreis um Helmuth James Graf von Moltke und Peter Graf Yorck von Wartenburg entwarf Pläne für ein Deutschland nach Hitler. Am 20. Juli 1944 brachte Oberst Claus Schenk Graf von Stauffenberg eine Bombe in Hitlers Hauptquartier „Wolfsschanze“ bei Rastenburg in Ostpreußen. Zu den Verschwörern gehörte auch Generalmajor Henning von Tresckow. Sie explodierte, doch Hitler überlebte nur leicht verletzt, weil die Aktentasche hinter einen massiven Tischsockel geschoben worden war. Der Umsturzplan „Walküre“ scheiterte. Stauffenberg und andere wurden noch in derselben Nacht im Berliner Bendlerblock erschossen; danach wurden Hunderte Beteiligte und Verdächtige hingerichtet.',
        'Andere retteten Leben, indem sie Juden versteckten oder ihnen zur Flucht verhalfen. Der Unternehmer Oskar Schindler bewahrte rund 1200 jüdische Zwangsarbeiter vor dem Tod. In der Berliner Rosenstraße protestierten 1943 nichtjüdische Ehefrauen tagelang erfolgreich für die Freilassung ihrer verhafteten jüdischen Männer. Die Gedenkstätte Yad Vashem in Israel ehrt Retter als „Gerechte unter den Völkern“.',
      ],
      quiz: {
        leicht: [
          ['Wie hieß die Münchner Studentengruppe gegen Hitler?', 'Weiße Rose', ['Rote Kapelle', 'Edelweißpiraten', 'Kreisauer Kreis']],
          ['Welche Geschwister gehörten zur Weißen Rose?', 'Hans und Sophie Scholl', ['Jacob und Wilhelm Grimm', 'Thomas und Heinrich Mann', 'Alexander und Wilhelm von Humboldt']],
          ['Womit kämpfte die Weiße Rose gegen das Regime?', 'Mit Flugblättern', ['Mit Bomben', 'Mit Waffen', 'Mit Radiosendungen']],
          ['Wer verübte am 20. Juli 1944 ein Attentat auf Hitler?', 'Claus Schenk Graf von Stauffenberg', ['Georg Elser', 'Hans Scholl', 'Erwin Rommel']],
          ['Überlebte Hitler das Attentat vom 20. Juli 1944?', 'Ja, leicht verletzt', ['Nein, er starb', 'Er war nicht da', 'Es gab kein Attentat']],
          ['Wie hieß Hitlers Hauptquartier in Ostpreußen?', 'Wolfsschanze', ['Adlerhorst', 'Berghof', 'Führerbunker']],
          ['Welcher Schreiner versuchte 1939 allein, Hitler zu töten?', 'Georg Elser', ['Claus von Stauffenberg', 'Willi Graf', 'Kurt Huber']],
          ['Wo versteckte Elser seine Bombe?', 'Im Münchner Bürgerbräukeller', ['Im Reichstag', 'In der Wolfsschanze', 'In einem Zug']],
          ['Warum überlebte Hitler Elsers Anschlag?', 'Er verließ den Saal vorher', ['Die Bombe explodierte nicht', 'Er war gepanzert', 'Er war gar nicht in München']],
          ['Welcher Bischof wurde „Löwe von Münster“ genannt?', 'Clemens August Graf von Galen', ['Martin Niemöller', 'Dietrich Bonhoeffer', 'Michael von Faulhaber']],
          ['Welcher evangelische Theologe wurde 1945 hingerichtet?', 'Dietrich Bonhoeffer', ['Martin Niemöller', 'Karl Barth', 'Martin Luther King']],
          ['Welcher Unternehmer rettete rund 1200 Juden?', 'Oskar Schindler', ['Alfred Krupp', 'Gottlieb Daimler', 'Ferdinand Porsche']],
          ['Wie nennt Yad Vashem die Retter von Juden?', '„Gerechte unter den Völkern“', ['„Helden der Nation“', '„Freunde Israels“', '„Weise der Welt“']],
          ['Wo liegt die Gedenkstätte Yad Vashem?', 'In Israel', ['In Deutschland', 'In Polen', 'In den USA']],
          ['Was riskierten Menschen im Widerstand?', 'Ihr Leben', ['Nur eine Geldstrafe', 'Nichts', 'Ihren Führerschein']],
          ['Welche Jugendlichen verweigerten sich der Hitlerjugend?', 'Die Edelweißpiraten', ['Die Pfadfinder des Führers', 'Die Wandervögel des BDM', 'Die Jungen Pioniere']],
          ['In welcher Stadt wirkte die Weiße Rose?', 'München', ['Berlin', 'Hamburg', 'Köln']],
          ['Wie hieß der Umsturzplan vom 20. Juli 1944?', 'Walküre', ['Barbarossa', 'Seelöwe', 'Overlord']],
          ['Welche Widerstandsgruppe hieß „Rote Kapelle“?', 'Eine Gruppe in Berlin, die Informationen sammelte', ['Ein Orchester', 'Eine Kirche', 'Eine Partei der Nazis']],
          ['In welchem Jahr wurden die Geschwister Scholl hingerichtet?', '1943', ['1939', '1944', '1945']],
        ],
        mittel: [
          ['Wann verübte Georg Elser sein Attentat?', '8. November 1939', ['20. Juli 1944', '9. November 1938', '1. September 1939']],
          ['Wie viele Minuten vor der Explosion verließ Hitler den Saal?', '13', ['1', '30', '60']],
          ['Wo wurde Elser 1945 ermordet?', 'Im KZ Dachau', ['Im KZ Flossenbürg', 'In Berlin-Plötzensee', 'In Auschwitz']],
          ['Wie viele Flugblätter verteilte die Weiße Rose?', 'Sechs', ['Eines', 'Zwanzig', 'Hundert']],
          ['Welcher Professor gehörte zur Weißen Rose?', 'Kurt Huber', ['Martin Heidegger', 'Karl Jaspers', 'Max Weber']],
          ['Wann wurden Hans und Sophie Scholl an der Universität entdeckt?', '18. Februar 1943', ['22. Februar 1943', '20. Juli 1944', '30. Januar 1943']],
          ['Wann wurden Hans und Sophie Scholl hingerichtet?', '22. Februar 1943', ['18. Februar 1943', '20. Juli 1944', '9. April 1945']],
          ['Welches Gericht verurteilte die Scholls?', 'Der Volksgerichtshof', ['Das Reichsgericht', 'Ein Militärgericht', 'Das Landgericht München']],
          ['Wer war Präsident des Volksgerichtshofs?', 'Roland Freisler', ['Heinrich Himmler', 'Reinhard Heydrich', 'Hans Frank']],
          ['Wer wurde mit den Geschwistern Scholl am selben Tag hingerichtet?', 'Christoph Probst', ['Willi Graf', 'Alexander Schmorell', 'Kurt Huber']],
          ['Welche Widerstandsgruppe entwarf Pläne für ein Deutschland nach Hitler?', 'Der Kreisauer Kreis', ['Die Rote Kapelle', 'Die Weiße Rose', 'Die Edelweißpiraten']],
          ['Wer gehörte zum Kreisauer Kreis?', 'Helmuth James Graf von Moltke', ['Georg Elser', 'Sophie Scholl', 'Oskar Schindler']],
          ['Warum überlebte Hitler die Bombe vom 20. Juli?', 'Die Tasche stand hinter einem massiven Tischsockel', ['Die Bombe war zu klein', 'Er war nicht im Raum', 'Er trug eine Panzerweste']],
          ['Wo wurden Stauffenberg und andere erschossen?', 'Im Berliner Bendlerblock', ['In der Wolfsschanze', 'In Plötzensee', 'Im Reichstag']],
          ['Wann wurde Dietrich Bonhoeffer hingerichtet?', '9. April 1945', ['20. Juli 1944', '22. Februar 1943', '8. Mai 1945']],
          ['Wo wurde Bonhoeffer hingerichtet?', 'Im KZ Flossenbürg', ['Im KZ Dachau', 'In Berlin-Plötzensee', 'Im KZ Buchenwald']],
          ['Welchen Bund gründete Martin Niemöller?', 'Den Pfarrernotbund', ['Den CVJM', 'Den Weltkirchenrat', 'Die Innere Mission']],
          ['Wie lange war Niemöller im KZ?', 'Von 1937 bis 1945', ['Ein Jahr', 'Von 1933 bis 1934', 'Gar nicht']],
          ['Wo protestierten 1943 Ehefrauen erfolgreich für ihre jüdischen Männer?', 'In der Berliner Rosenstraße', ['Auf dem Münchner Marienplatz', 'Vor dem Reichstag', 'In Hamburg']],
          ['Wogegen protestierte Bischof von Galen 1941 öffentlich?', 'Gegen die Morde an Kranken', ['Gegen den Autobahnbau', 'Gegen die Olympischen Spiele', 'Gegen den Papst']],
        ],
        schwer: [
          ['Woher stammte Georg Elser?', 'Aus Schwaben (Württemberg)', ['Aus Berlin', 'Aus Bayern', 'Aus Ostpreußen']],
          ['Wo genau versteckte Elser die Bombe?', 'In einer Säule', ['Unter dem Rednerpult', 'Im Keller', 'In einem Bierfass']],
          ['Wann wurde Elser ermordet?', 'Im April 1945', ['Im November 1939', 'Im Juli 1944', 'Im Mai 1945']],
          ['Wer entdeckte die Scholls in der Universität?', 'Der Hausmeister', ['Ein Professor', 'Ein Student', 'Die Gestapo direkt']],
          ['Wohin warfen die Scholls die Flugblätter?', 'In den Lichthof der Universität', ['Aus einem Flugzeug', 'In Briefkästen', 'In die Isar']],
          ['Welche Mitglieder der Weißen Rose wurden später hingerichtet?', 'Alexander Schmorell, Willi Graf und Kurt Huber', ['Hans und Sophie Scholl', 'Niemand weiter', 'Georg Elser']],
          ['Wer gehörte neben Moltke zum Kreisauer Kreis?', 'Peter Graf Yorck von Wartenburg', ['Claus von Stauffenberg', 'Roland Freisler', 'Wilhelm Canaris']],
          ['Welchen Rang hatte Stauffenberg?', 'Oberst', ['General', 'Leutnant', 'Feldmarschall']],
          ['Wo lag die Wolfsschanze?', 'In Ostpreußen bei Rastenburg', ['In Bayern bei Berchtesgaden', 'In Berlin', 'In Polen bei Krakau']],
          ['Was geschah nach dem 20. Juli mit vielen Beteiligten?', 'Hunderte wurden hingerichtet', ['Sie wurden begnadigt', 'Sie flohen alle ins Ausland', 'Sie wurden befördert']],
          ['Wie hieß der Volksgerichtshof-Präsident, der viele Widerständler verurteilte?', 'Roland Freisler', ['Otto Thierack', 'Hans Frank', 'Ernst Kaltenbrunner']],
          ['Welche Konfession hatte Bischof von Galen?', 'Katholisch', ['Evangelisch', 'Jüdisch', 'Orthodox']],
          ['In welchem Jahr predigte Galen gegen die Krankenmorde?', '1941', ['1933', '1939', '1944']],
          ['Wie viele Juden rettete Oskar Schindler etwa?', 'Rund 1200', ['Rund 12', 'Rund 12.000', 'Rund 120']],
          ['Was erreichten die Frauen in der Rosenstraße?', 'Die Freilassung ihrer Männer', ['Gar nichts', 'Den Sturz Hitlers', 'Die Auswanderung nach Amerika']],
          ['In welchem Jahr fand der Rosenstraße-Protest statt?', '1943', ['1938', '1941', '1945']],
          ['Welcher Bund ging aus dem Pfarrernotbund hervor?', 'Die Bekennende Kirche', ['Die Deutschen Christen', 'Der Lutherische Weltbund', 'Die Evangelische Allianz']],
          ['Was verteilten Kommunisten und Sozialdemokraten im Untergrund?', 'Flugblätter', ['Waffen an die SS', 'Wahlplakate der NSDAP', 'Orden']],
          ['Wann erhielten die Mitglieder der Weißen Rose ihre Urteile?', 'Am 22. Februar 1943', ['Am 18. Februar 1943', 'Am 20. Juli 1944', 'Am 1. Mai 1943']],
          ['Welche Widerständler waren unter den Offizieren des 20. Juli bekannt?', 'Henning von Tresckow', ['Erwin Rommel als Täter', 'Wilhelm Keitel', 'Alfred Jodl']],
        ],
      },
    },
  ],
};
