import type { HistEvent } from '../types';

export const DDR: HistEvent = {
  id: 'ddr',
  title: 'Die DDR und die friedliche Revolution',
  date: '1949–1989',
  text: [
    'Die DDR verstand sich als sozialistischer „Arbeiter- und Bauernstaat“, war aber eine Diktatur der SED, die ihre Bürger überwachte und einsperrte. 1989 brachten mutige Menschen sie in einer friedlichen Revolution zu Fall.',
  ],
  subtopics: [
    {
      id: 'ddr-staat',
      title: 'Leben in der DDR, 17. Juni und Mauerbau',
      date: '1949–1989',
      text: [
        'In der DDR bestimmte die SED alles. Die Wirtschaft war eine Planwirtschaft: Der Staat legte in Fünfjahrplänen fest, was produziert wurde. Fabriken wurden zu „Volkseigenen Betrieben“ (VEB), Bauern mussten bis 1960 in Landwirtschaftliche Produktionsgenossenschaften (LPG) eintreten. Viele Waren waren knapp; auf ein Auto wie den Trabant aus Zwickau wartete man oft über zehn Jahre.',
        '1952 verkündete Ulbricht den „Aufbau des Sozialismus“. Als die Regierung 1953 die Arbeitsnormen erhöhte – also mehr Arbeit für den gleichen Lohn verlangte –, legten am 16. Juni Bauarbeiter in der Ost-Berliner Stalinallee die Arbeit nieder. Am 17. Juni 1953 protestierten in rund 700 Orten etwa eine Million Menschen gegen die Regierung und forderten freie Wahlen. Sowjetische Panzer schlugen den Volksaufstand nieder; mindestens 55 Menschen starben. In der Bundesrepublik war der 17. Juni bis 1990 Feiertag („Tag der deutschen Einheit“).',
        'Das 1950 gegründete Ministerium für Staatssicherheit, die „Stasi“, überwachte die Bevölkerung, ab 1957 unter Minister Erich Mielke. 1989 hatte sie rund 91.000 hauptamtliche und etwa 189.000 inoffizielle Mitarbeiter (IM), die Freunde, Nachbarn und sogar Familienangehörige bespitzelten. Kritiker kamen ins Gefängnis, etwa nach Berlin-Hohenschönhausen oder Bautzen. Der Liedermacher Wolf Biermann wurde 1976 ausgebürgert.',
        'Bis 1961 flohen rund 2,7 Millionen Menschen aus der DDR in den Westen, vor allem junge und gut ausgebildete. Noch am 15. Juni 1961 sagte Ulbricht: „Niemand hat die Absicht, eine Mauer zu errichten.“ Doch in der Nacht zum 13. August 1961 sperrten Soldaten und Polizisten die Grenze nach West-Berlin ab, und bald entstand die Berliner Mauer, die die SED „antifaschistischen Schutzwall“ nannte. Sie umschloss West-Berlin auf rund 155 Kilometern. An der innerdeutschen Grenze (rund 1400 Kilometer) galt der Schießbefehl. Mindestens 140 Menschen starben allein an der Berliner Mauer, etwa der 18-jährige Peter Fechter, der 1962 im Grenzstreifen verblutete. Am 26. Juni 1963 sagte US-Präsident John F. Kennedy in West-Berlin: „Ich bin ein Berliner.“',
        '1971 löste Erich Honecker Ulbricht als SED-Chef ab. Er versprach die „Einheit von Wirtschafts- und Sozialpolitik“, ließ viele Plattenbauwohnungen bauen und hielt Mieten und Grundnahrungsmittel billig – auf Kosten wachsender Schulden. Die DDR gehörte seit 1955 zum Warschauer Pakt, 1956 entstand die Nationale Volksarmee (NVA).',
        'Kinder waren meist bei den Jungen Pionieren, Jugendliche in der Freien Deutschen Jugend (FDJ); statt der Konfirmation feierten die meisten die staatliche Jugendweihe. Im Sport war die DDR sehr erfolgreich, auch durch systematisches Doping. 1978 flog Sigmund Jähn als erster Deutscher ins All. Bekannt sind bis heute das Sandmännchen und das Ampelmännchen.',
      ],
      quiz: {
        leicht: [
          ['Welche Partei herrschte in der DDR?', 'Die SED', ['Die SPD', 'Die CDU', 'Die NSDAP']],
          ['Welches Wirtschaftssystem hatte die DDR?', 'Planwirtschaft', ['Soziale Marktwirtschaft', 'Freie Marktwirtschaft', 'Feudalismus']],
          ['Welches Auto war typisch für die DDR?', 'Der Trabant', ['Der VW Käfer', 'Der Mercedes', 'Der Opel Kadett']],
          ['Was geschah am 17. Juni 1953?', 'Ein Volksaufstand in der DDR', ['Der Mauerbau', 'Die Gründung der DDR', 'Der Mauerfall']],
          ['Wer schlug den Aufstand vom 17. Juni nieder?', 'Sowjetische Panzer', ['Amerikanische Soldaten', 'Die Bundeswehr', 'Niemand']],
          ['Wie hieß die Geheimpolizei der DDR?', 'Stasi', ['Gestapo', 'KGB', 'BND']],
          ['Wann wurde die Berliner Mauer gebaut?', '13. August 1961', ['17. Juni 1953', '9. November 1989', '7. Oktober 1949']],
          ['Wer sagte: „Niemand hat die Absicht, eine Mauer zu errichten“?', 'Walter Ulbricht', ['Erich Honecker', 'Konrad Adenauer', 'John F. Kennedy']],
          ['Wie nannte die SED die Mauer?', '„Antifaschistischer Schutzwall“', ['„Friedensmauer“', '„Eiserner Vorhang“', '„Volksmauer“']],
          ['Was galt an der innerdeutschen Grenze?', 'Der Schießbefehl', ['Freie Ausreise', 'Visumfreiheit', 'Gar nichts']],
          ['Welcher US-Präsident sagte „Ich bin ein Berliner“?', 'John F. Kennedy', ['Ronald Reagan', 'Richard Nixon', 'Bill Clinton']],
          ['Wer löste 1971 Ulbricht ab?', 'Erich Honecker', ['Egon Krenz', 'Willi Stoph', 'Erich Mielke']],
          ['Welche Wohnhäuser ließ Honecker in großer Zahl bauen?', 'Plattenbauten', ['Fachwerkhäuser', 'Villen', 'Hochhäuser aus Glas']],
          ['Wie hieß die Jugendorganisation der DDR?', 'FDJ', ['HJ', 'Junge Union', 'Jusos']],
          ['Welche Feier ersetzte in der DDR oft die Konfirmation?', 'Die Jugendweihe', ['Die Firmung', 'Die Taufe', 'Der Abiball']],
          ['Wie hieß die Armee der DDR?', 'Nationale Volksarmee (NVA)', ['Bundeswehr', 'Rote Armee', 'Reichswehr']],
          ['Welchem Militärbündnis gehörte die DDR an?', 'Dem Warschauer Pakt', ['Der NATO', 'Der EU', 'Dem Völkerbund']],
          ['Wer flog 1978 als erster Deutscher ins All?', 'Sigmund Jähn', ['Ulf Merbold', 'Alexander Gerst', 'Juri Gagarin']],
          ['Welche Figur an Fußgängerampeln stammt aus der DDR?', 'Das Ampelmännchen', ['Der Ampelbär', 'Das Sandmännchen', 'Der Ampelmax']],
          ['Wie viele Menschen flohen bis 1961 etwa aus der DDR?', 'Rund 2,7 Millionen', ['Rund 27.000', 'Rund 270.000', 'Rund 27 Millionen']],
        ],
        mittel: [
          ['Wie hießen die verstaatlichten Fabriken der DDR?', 'Volkseigene Betriebe (VEB)', ['Aktiengesellschaften', 'Treuhandbetriebe', 'Kombinate des Westens']],
          ['In welche Genossenschaften mussten Bauern eintreten?', 'In LPG', ['In VEB', 'In Raiffeisenbanken', 'In Zünfte']],
          ['Bis wann wurde die Landwirtschaft kollektiviert?', '1960', ['1949', '1953', '1971']],
          ['Wo wurde der Trabant gebaut?', 'In Zwickau', ['In Eisenach', 'In Leipzig', 'In Wolfsburg']],
          ['Wie lange wartete man oft auf ein Auto?', 'Über zehn Jahre', ['Eine Woche', 'Ein Jahr', 'Gar nicht']],
          ['Was löste den Aufstand von 1953 aus?', 'Die Erhöhung der Arbeitsnormen', ['Der Mauerbau', 'Ein Fußballspiel', 'Die Ermordung eines Politikers']],
          ['Wo legten Bauarbeiter am 16. Juni 1953 die Arbeit nieder?', 'In der Stalinallee in Ost-Berlin', ['In Leipzig', 'Am Alexanderplatz', 'In Dresden']],
          ['Wie viele Menschen protestierten am 17. Juni 1953 etwa?', 'Rund eine Million', ['Rund 1000', 'Rund 100.000', 'Rund 10 Millionen']],
          ['Wie hieß der 17. Juni in der Bundesrepublik bis 1990?', '„Tag der deutschen Einheit“', ['„Tag der Arbeit“', '„Tag der Republik“', '„Tag der Befreiung“']],
          ['Wann wurde die Stasi gegründet?', '1950', ['1945', '1961', '1971']],
          ['Wer war ab 1957 Minister für Staatssicherheit?', 'Erich Mielke', ['Markus Wolf', 'Erich Honecker', 'Egon Krenz']],
          ['Wie nannte man die heimlichen Spitzel der Stasi?', 'Inoffizielle Mitarbeiter (IM)', ['V-Leute des BND', 'Agenten 007', 'Blockwarte']],
          ['Welcher Liedermacher wurde 1976 ausgebürgert?', 'Wolf Biermann', ['Udo Lindenberg', 'Nina Hagen', 'Manfred Krug']],
          ['Wie lang war die Mauer um West-Berlin etwa?', 'Rund 155 Kilometer', ['Rund 15 Kilometer', 'Rund 1500 Kilometer', 'Rund 50 Kilometer']],
          ['Wie lang war die innerdeutsche Grenze etwa?', 'Rund 1400 Kilometer', ['Rund 140 Kilometer', 'Rund 14.000 Kilometer', 'Rund 400 Kilometer']],
          ['Welcher junge Mann verblutete 1962 an der Mauer?', 'Peter Fechter', ['Chris Gueffroy', 'Benno Ohnesorg', 'Günter Litfin']],
          ['Wann sagte Kennedy „Ich bin ein Berliner“?', '26. Juni 1963', ['13. August 1961', '9. November 1989', '17. Juni 1953']],
          ['Was versprach Honecker mit der „Einheit von Wirtschafts- und Sozialpolitik“?', 'Mehr Konsum und billige Mieten', ['Freie Wahlen', 'Reisefreiheit', 'Die Wiedervereinigung']],
          ['Wann trat die DDR dem Warschauer Pakt bei?', '1955', ['1949', '1961', '1968']],
          ['Wie hieß die Organisation für Kinder in der DDR?', 'Junge Pioniere', ['Pfadfinder', 'Jungvolk', 'Wölflinge']],
        ],
        schwer: [
          ['Wann verkündete Ulbricht den „Aufbau des Sozialismus“?', '1952', ['1949', '1961', '1971']],
          ['In wie vielen Orten wurde am 17. Juni 1953 protestiert?', 'In rund 700', ['In rund 7', 'In rund 70', 'In rund 7000']],
          ['Wie viele Menschen starben mindestens beim Aufstand 1953?', '55', ['5', '555', '5000']],
          ['Wie viele hauptamtliche Mitarbeiter hatte die Stasi 1989 etwa?', 'Rund 91.000', ['Rund 9100', 'Rund 910.000', 'Rund 910']],
          ['Wie viele inoffizielle Mitarbeiter hatte die Stasi 1989 etwa?', 'Rund 189.000', ['Rund 18.900', 'Rund 1,89 Millionen', 'Rund 1890']],
          ['In welchem Stasi-Gefängnis saßen viele politische Gefangene in Berlin?', 'Hohenschönhausen', ['Moabit', 'Tegel', 'Spandau']],
          ['Wann sagte Ulbricht, niemand wolle eine Mauer bauen?', '15. Juni 1961', ['13. August 1961', '17. Juni 1953', '1. Mai 1961']],
          ['Wie viele Menschen starben mindestens an der Berliner Mauer?', '140', ['14', '1400', '4']],
          ['Wie alt war Peter Fechter?', '18', ['8', '28', '48']],
          ['Wann wurde die NVA gegründet?', '1956', ['1949', '1961', '1952']],
          ['Wodurch erzielte die DDR im Sport auch Erfolge?', 'Durch systematisches Doping', ['Durch Wetten', 'Durch Bestechung der Schiedsrichter', 'Durch Zufall']],
          ['Was wuchs unter Honeckers Sozialpolitik?', 'Die Staatsschulden', ['Die Reisefreiheit', 'Die Pressefreiheit', 'Die Zahl der Parteien']],
          ['In welcher Stadt lag ein berüchtigtes Gefängnis für politische Häftlinge in Sachsen?', 'Bautzen', ['Leipzig', 'Chemnitz', 'Görlitz']],
          ['Wer bespitzelte in der DDR oft sogar Familienangehörige?', 'Inoffizielle Mitarbeiter der Stasi', ['Die Volkspolizei offen', 'Der BND', 'Die Kirchen']],
          ['Wann wurde Biermann ausgebürgert?', '1976', ['1961', '1989', '1971']],
          ['Welche beliebte Kinderfigur stammt aus dem DDR-Fernsehen?', 'Das Sandmännchen', ['Die Maus', 'Das Sams', 'Pumuckl']],
          ['Welche Gruppe floh besonders häufig in den Westen?', 'Junge und gut ausgebildete Menschen', ['Nur Rentner', 'Nur Bauern', 'Niemand']],
          ['Seit wann gab es in der DDR die Stasi unter Mielke?', 'Seit 1957', ['Seit 1950', 'Seit 1971', 'Seit 1945']],
          ['Wie nannte man in der Bundesrepublik den 17. Juni als Gedenktag?', 'Tag der deutschen Einheit', ['Tag des Mauerbaus', 'Volkstrauertag', 'Tag der Republik']],
          ['Was bedeutete die Normerhöhung von 1953?', 'Mehr Arbeit für den gleichen Lohn', ['Weniger Arbeit', 'Mehr Lohn', 'Längerer Urlaub']],
        ],
      },
    },
    {
      id: 'friedliche-revolution',
      title: 'Die friedliche Revolution und der Mauerfall',
      date: '1985–1990',
      text: [
        'Seit 1985 führte Michail Gorbatschow die Sowjetunion. Mit „Glasnost“ (Offenheit) und „Perestroika“ (Umbau) wollte er sein Land reformieren und ließ den Ostblockstaaten mehr Freiheit. Die SED-Führung lehnte Reformen ab und verbot 1988 sogar die sowjetische Zeitschrift „Sputnik“. Bei der Kommunalwahl am 7. Mai 1989 wiesen Bürgerrechtler Wahlfälschung nach.',
        'Ab Mai 1989 begann Ungarn, seinen Grenzzaun zu Österreich abzubauen. Beim „Paneuropäischen Picknick“ am 19. August 1989 flohen Hunderte DDR-Bürger über die Grenze, und am 11. September öffnete Ungarn die Grenze ganz. Tausende flüchteten in die bundesdeutsche Botschaft in Prag. Am 30. September 1989 verkündete Außenminister Hans-Dietrich Genscher vom Balkon der Botschaft ihre Ausreise; der Rest seines Satzes ging im Jubel unter.',
        'In der DDR gründeten sich Bürgerbewegungen wie das „Neue Forum“. In Leipzig trafen sich Menschen nach den Friedensgebeten in der Nikolaikirche zu den Montagsdemonstrationen und riefen „Wir sind das Volk!“. Am 7. Oktober 1989 feierte die SED den 40. Jahrestag der DDR, während Polizei Demonstranten verprügelte. Am 9. Oktober demonstrierten in Leipzig rund 70.000 Menschen – und die Staatsmacht griff nicht ein. Das war der Durchbruch; Leipzig gilt seither als „Heldenstadt“ der friedlichen Revolution. Am 18. Oktober trat Honecker zurück, sein Nachfolger wurde Egon Krenz. Am 4. November 1989 demonstrierten auf dem Ost-Berliner Alexanderplatz rund eine halbe Million Menschen für Meinungs- und Reisefreiheit.',
        'Am Abend des 9. November 1989 verlas SED-Politbüromitglied Günter Schabowski auf einer Pressekonferenz eine neue Reiseregelung. Auf die Frage, ab wann sie gelte, sagte er: „Das tritt nach meiner Kenntnis … ist das sofort, unverzüglich.“ Tausende Ost-Berliner strömten an die Grenzübergänge. Gegen 23:30 Uhr öffnete der Stasi-Offizier Harald Jäger am Übergang Bornholmer Straße den Schlagbaum – die Mauer war gefallen. Menschen aus Ost und West lagen sich weinend in den Armen und tanzten auf der Mauer am Brandenburger Tor.',
        'Am „Runden Tisch“ verhandelten ab Dezember 1989 Vertreter der alten Macht und der Bürgerbewegung über die Zukunft. Bürger besetzten Stasi-Dienststellen, um die Vernichtung von Akten zu verhindern; am 15. Januar 1990 stürmten sie die Stasi-Zentrale in Berlin-Lichtenberg. Auf den Demonstrationen hieß es nun immer öfter: „Wir sind ein Volk!“ Weil kein Schuss fiel, spricht man von der „friedlichen Revolution“.',
      ],
      quiz: {
        leicht: [
          ['Wann fiel die Berliner Mauer?', '9. November 1989', ['3. Oktober 1990', '13. August 1961', '17. Juni 1953']],
          ['Welcher sowjetische Politiker ermöglichte Reformen im Ostblock?', 'Michail Gorbatschow', ['Leonid Breschnew', 'Josef Stalin', 'Wladimir Putin']],
          ['Was bedeutet „Glasnost“?', 'Offenheit', ['Umbau', 'Frieden', 'Freiheit']],
          ['Was bedeutet „Perestroika“?', 'Umbau', ['Offenheit', 'Einheit', 'Revolution']],
          ['Welches Land öffnete 1989 seine Grenze zu Österreich?', 'Ungarn', ['Polen', 'Tschechoslowakei', 'Rumänien']],
          ['In welcher Stadt fanden die Montagsdemonstrationen statt?', 'Leipzig', ['Dresden', 'Berlin', 'Rostock']],
          ['Was riefen die Demonstranten zuerst?', '„Wir sind das Volk!“', ['„Freiheit für alle!“', '„Nieder mit dem Kaiser!“', '„Deutschland den Deutschen!“']],
          ['Was riefen sie später immer öfter?', '„Wir sind ein Volk!“', ['„Wir sind das Volk!“', '„Wir wollen raus!“', '„Es lebe die SED!“']],
          ['In welcher Kirche fanden in Leipzig Friedensgebete statt?', 'In der Nikolaikirche', ['In der Thomaskirche', 'In der Frauenkirche', 'Im Dom']],
          ['Wer verkündete 1989 in Prag die Ausreise der Flüchtlinge?', 'Hans-Dietrich Genscher', ['Helmut Kohl', 'Willy Brandt', 'Erich Honecker']],
          ['Wer verlas am 9. November 1989 die neue Reiseregelung?', 'Günter Schabowski', ['Erich Honecker', 'Egon Krenz', 'Helmut Kohl']],
          ['Was sagte Schabowski, ab wann die Regelung gelte?', '„Sofort, unverzüglich“', ['„Ab nächstem Jahr“', '„Nie“', '„Ab morgen früh um acht“']],
          ['Wer folgte Honecker im Oktober 1989?', 'Egon Krenz', ['Walter Ulbricht', 'Erich Mielke', 'Lothar de Maizière']],
          ['Wie nennt man die Ereignisse von 1989 in der DDR?', 'Friedliche Revolution', ['Märzrevolution', 'Oktoberrevolution', 'Novemberrevolution']],
          ['Warum heißt sie „friedliche“ Revolution?', 'Weil kein Schuss fiel', ['Weil sie im Frieden begann', 'Weil der Papst sie segnete', 'Weil sie nur einen Tag dauerte']],
          ['Wo tanzten Menschen auf der Mauer?', 'Am Brandenburger Tor', ['Am Reichstag', 'Am Alexanderplatz', 'In Leipzig']],
          ['Welche Bürgerbewegung gründete sich 1989?', 'Das Neue Forum', ['Die RAF', 'Die APO', 'Die FDJ']],
          ['Welches Jubiläum feierte die DDR am 7. Oktober 1989?', '40 Jahre DDR', ['50 Jahre DDR', '10 Jahre DDR', '100 Jahre DDR']],
          ['In welche Botschaft flüchteten Tausende DDR-Bürger?', 'In die bundesdeutsche Botschaft in Prag', ['In die US-Botschaft in Moskau', 'In die französische Botschaft in Berlin', 'In die Schweizer Botschaft in Wien']],
          ['Wo verhandelten ab Dezember 1989 alte Macht und Bürgerbewegung?', 'Am Runden Tisch', ['Im Bundestag', 'In der UNO', 'Im Kreml']],
        ],
        mittel: [
          ['Seit wann führte Gorbatschow die Sowjetunion?', '1985', ['1979', '1989', '1991']],
          ['Welche sowjetische Zeitschrift verbot die SED 1988?', '„Sputnik“', ['„Prawda“', '„Iswestija“', '„Krokodil“']],
          ['Wann fand die gefälschte Kommunalwahl statt?', '7. Mai 1989', ['9. November 1989', '18. März 1990', '7. Oktober 1989']],
          ['Wann fand das Paneuropäische Picknick statt?', '19. August 1989', ['11. September 1989', '9. Oktober 1989', '13. August 1989']],
          ['Wann öffnete Ungarn seine Grenze ganz?', '11. September 1989', ['19. August 1989', '9. November 1989', '2. Mai 1989']],
          ['Wann verkündete Genscher in Prag die Ausreise?', '30. September 1989', ['9. November 1989', '7. Oktober 1989', '3. Oktober 1990']],
          ['Wann demonstrierten in Leipzig rund 70.000 Menschen friedlich?', '9. Oktober 1989', ['9. November 1989', '4. November 1989', '7. Oktober 1989']],
          ['Was geschah am 9. Oktober 1989 Entscheidendes?', 'Die Staatsmacht griff nicht ein', ['Die Mauer fiel', 'Honecker trat zurück', 'Panzer schossen']],
          ['Wann trat Honecker zurück?', '18. Oktober 1989', ['9. November 1989', '7. Oktober 1989', '3. Oktober 1990']],
          ['Wann fand die große Demonstration auf dem Alexanderplatz statt?', '4. November 1989', ['9. November 1989', '9. Oktober 1989', '17. Juni 1989']],
          ['Wie viele Menschen demonstrierten auf dem Alexanderplatz etwa?', 'Rund eine halbe Million', ['Rund 5000', 'Rund 50.000', 'Rund 5 Millionen']],
          ['An welchem Übergang wurde der Schlagbaum zuerst geöffnet?', 'Bornholmer Straße', ['Checkpoint Charlie', 'Brandenburger Tor', 'Glienicker Brücke']],
          ['Wer öffnete den Schlagbaum an der Bornholmer Straße?', 'Harald Jäger', ['Günter Schabowski', 'Egon Krenz', 'Erich Mielke']],
          ['Um wie viel Uhr wurde der Übergang Bornholmer Straße geöffnet?', 'Gegen 23:30 Uhr', ['Um 12 Uhr mittags', 'Um 6 Uhr morgens', 'Um 18 Uhr']],
          ['Wann stürmten Bürger die Stasi-Zentrale in Berlin?', '15. Januar 1990', ['9. November 1989', '3. Oktober 1990', '18. März 1990']],
          ['Warum besetzten Bürger Stasi-Dienststellen?', 'Um die Vernichtung von Akten zu verhindern', ['Um dort zu wohnen', 'Um Geld zu finden', 'Um Waffen zu holen']],
          ['In welchem Berliner Bezirk lag die Stasi-Zentrale?', 'Lichtenberg', ['Mitte', 'Spandau', 'Pankow']],
          ['Was geschah am 7. Oktober 1989 in Ost-Berlin neben den Feiern?', 'Polizei verprügelte Demonstranten', ['Die Mauer fiel', 'Gorbatschow trat zurück', 'Es gab freie Wahlen']],
          ['Was ging den Montagsdemonstrationen in Leipzig voraus?', 'Friedensgebete', ['Fußballspiele', 'Konzerte', 'Parteitage']],
          ['Was hatten Bürgerrechtler bei der Kommunalwahl 1989 nachgewiesen?', 'Wahlfälschung', ['Eine hohe Wahlbeteiligung', 'Einen Sieg der Opposition', 'Nichts']],
        ],
        schwer: [
          ['Wann begann Ungarn mit dem Abbau des Grenzzauns?', 'Im Mai 1989', ['Im November 1989', 'Im Januar 1989', 'Im Dezember 1988']],
          ['Wie viele DDR-Bürger flohen beim Paneuropäischen Picknick?', 'Hunderte', ['Zwei', 'Hunderttausende', 'Niemand']],
          ['Wovon sprach Genscher in Prag?', 'Vom Balkon der Botschaft', ['Aus einem Fernsehstudio', 'Vom Reichstag', 'Aus dem Zug']],
          ['Was geschah mit dem Rest von Genschers Satz?', 'Er ging im Jubel unter', ['Er wurde nie ausgesprochen', 'Er wurde übersetzt', 'Er wurde verboten']],
          ['Welchem Gremium gehörte Schabowski an?', 'Dem Politbüro der SED', ['Dem Bundestag', 'Der Volkskammer', 'Dem Runden Tisch']],
          ['Welchen Rang hatte Harald Jäger?', 'Er war Stasi-Offizier an der Grenze', ['Er war General der NVA', 'Er war Bürgermeister', 'Er war Journalist']],
          ['Wann begann der Runde Tisch?', 'Im Dezember 1989', ['Im Oktober 1989', 'Im März 1990', 'Im August 1989']],
          ['Welche Freiheiten forderten die Menschen auf dem Alexanderplatz?', 'Meinungs- und Reisefreiheit', ['Steuerfreiheit', 'Waffenfreiheit', 'Den Kommunismus']],
          ['Welche Reaktion hatte die SED-Führung auf Gorbatschows Reformen?', 'Sie lehnte Reformen ab', ['Sie begrüßte sie', 'Sie trat sofort zurück', 'Sie bat um Hilfe aus Bonn']],
          ['Welcher sowjetische Begriff steht für den Umbau der Wirtschaft?', 'Perestroika', ['Glasnost', 'Sputnik', 'Prawda']],
          ['Wie viele Menschen demonstrierten am 9. Oktober 1989 in Leipzig?', 'Rund 70.000', ['Rund 7000', 'Rund 700.000', 'Rund 700']],
          ['Was geschah im Herbst 1989 mit der Mauer am Brandenburger Tor?', 'Menschen tanzten auf ihr', ['Sie wurde gesprengt', 'Sie wurde höher gebaut', 'Sie wurde bewacht wie immer']],
          ['Was war das „Neue Forum“?', 'Eine Bürgerbewegung', ['Eine Zeitung der SED', 'Ein Fernsehsender', 'Eine Partei im Westen']],
          ['In welchem Monat 1989 trat Honecker zurück?', 'Oktober', ['November', 'September', 'Dezember']],
          ['Welche Stadt gilt als „Heldenstadt“ der friedlichen Revolution?', 'Leipzig', ['Dresden', 'Ost-Berlin', 'Erfurt']],
          ['Was war an Schabowskis Antwort überraschend?', 'Die Regelung sollte sofort gelten', ['Sie galt nur für Rentner', 'Sie war ein Scherz', 'Sie galt nur in Leipzig']],
          ['Wohin wollten die Flüchtlinge aus der Prager Botschaft?', 'In die Bundesrepublik', ['In die Sowjetunion', 'Nach Ungarn', 'Zurück in die DDR']],
          ['Welche Folge hatte Gorbatschows Politik für die Ostblockstaaten?', 'Sie erhielten mehr Freiheit', ['Sie wurden besetzt', 'Sie wurden aufgelöst', 'Nichts']],
          ['Wann wurden die Leipziger Friedensgebete regelmäßig zu Demonstrationen?', 'Im Herbst 1989', ['1953', '1961', '1971']],
          ['Welche Stasi-Zentrale stürmten Bürger im Januar 1990?', 'Die in Berlin-Lichtenberg', ['Die in Leipzig', 'Die in Dresden', 'Die in Bonn']],
        ],
      },
    },
  ],
};

export const EINHEIT: HistEvent = {
  id: 'einheit',
  title: 'Wiedervereinigung und Deutschland heute',
  date: 'seit 1990',
  text: [
    'Weniger als ein Jahr nach dem Mauerfall war Deutschland wiedervereinigt. Seitdem wuchs das Land zusammen, zog seine Hauptstadt nach Berlin, führte den Euro ein und stellte sich neuen Herausforderungen.',
  ],
  subtopics: [
    {
      id: 'wiedervereinigung',
      title: 'Der Weg zur Einheit',
      date: '1989–1991',
      text: [
        'Am 28. November 1989 legte Bundeskanzler Helmut Kohl ein Zehn-Punkte-Programm für den Weg zur deutschen Einheit vor. Am 18. März 1990 fand die erste und einzige freie Wahl zur DDR-Volkskammer statt. Es siegte die „Allianz für Deutschland“, ein Bündnis um die Ost-CDU, das eine schnelle Einheit wollte; Lothar de Maizière wurde Ministerpräsident.',
        'Am 1. Juli 1990 trat die Währungs-, Wirtschafts- und Sozialunion in Kraft: Die D-Mark wurde auch in der DDR Zahlungsmittel, Löhne und Renten wurden im Verhältnis 1:1 umgestellt. Am 31. August 1990 unterzeichneten beide Staaten in Ost-Berlin den Einigungsvertrag. Der schnelle 1:1-Umtausch der Löhne machte allerdings viele DDR-Betriebe auf einen Schlag nicht mehr konkurrenzfähig.',
        'Auch die vier Siegermächte mussten zustimmen. Am 12. September 1990 unterschrieben die Bundesrepublik, die DDR sowie die USA, die Sowjetunion, Großbritannien und Frankreich in Moskau den Zwei-plus-Vier-Vertrag. Deutschland erhielt die volle Souveränität, erkannte die Oder-Neiße-Grenze zu Polen endgültig an, begrenzte die Bundeswehr auf 370.000 Soldaten und verzichtete auf atomare, biologische und chemische Waffen. Die sowjetischen Truppen sollten bis 1994 abziehen. Das vereinte Deutschland blieb in der NATO.',
        'Am 3. Oktober 1990 trat die DDR nach Artikel 23 des Grundgesetzes der Bundesrepublik bei – der andere mögliche Weg, eine neue Verfassung nach Artikel 146, wurde nicht gewählt. Seitdem ist der 3. Oktober als „Tag der Deutschen Einheit“ Nationalfeiertag. Die fünf neuen Bundesländer sind Brandenburg, Mecklenburg-Vorpommern, Sachsen, Sachsen-Anhalt und Thüringen; Ost- und West-Berlin wurden zu einem Land vereinigt. Am 2. Dezember 1990 fand die erste gesamtdeutsche Bundestagswahl statt, die Kohl gewann; man nennt ihn deshalb auch „Kanzler der Einheit“.',
        'Die Treuhandanstalt sollte die rund 8500 volkseigenen Betriebe privatisieren. Viele waren nicht konkurrenzfähig und wurden geschlossen; Millionen Menschen in Ostdeutschland verloren ihre Arbeit. Treuhand-Chef Detlev Rohwedder wurde 1991 ermordet; seine Nachfolgerin wurde Birgit Breuel. Zur Finanzierung des Aufbaus Ost wurde 1991 der Solidaritätszuschlag eingeführt. Die Stasi-Akten wurden für die Betroffenen geöffnet; erster Leiter der Behörde war der Pfarrer Joachim Gauck, der später Bundespräsident wurde. Am 20. Juni 1991 beschloss der Bundestag mit 338 zu 320 Stimmen, nach Berlin umzuziehen.',
      ],
      quiz: {
        leicht: [
          ['An welchem Tag wurde Deutschland wiedervereinigt?', '3. Oktober 1990', ['9. November 1989', '1. Juli 1990', '12. September 1990']],
          ['Wie heißt der 3. Oktober?', 'Tag der Deutschen Einheit', ['Tag der Arbeit', 'Tag der Befreiung', 'Reformationstag']],
          ['Welcher Kanzler gilt als „Kanzler der Einheit“?', 'Helmut Kohl', ['Willy Brandt', 'Helmut Schmidt', 'Gerhard Schröder']],
          ['Welche Währung wurde 1990 in der DDR eingeführt?', 'Die D-Mark', ['Der Euro', 'Die Ostmark', 'Der Dollar']],
          ['Wie viele neue Bundesländer kamen 1990 hinzu?', 'Fünf', ['Drei', 'Sieben', 'Zehn']],
          ['Welches Land gehört zu den neuen Bundesländern?', 'Thüringen', ['Hessen', 'Bayern', 'Niedersachsen']],
          ['Welcher Vertrag regelte die Zustimmung der Siegermächte?', 'Der Zwei-plus-Vier-Vertrag', ['Der Versailler Vertrag', 'Der Élysée-Vertrag', 'Der Grundlagenvertrag']],
          ['Wie viele Siegermächte waren am Zwei-plus-Vier-Vertrag beteiligt?', 'Vier', ['Zwei', 'Sechs', 'Eine']],
          ['Welche Grenze zu Polen wurde endgültig anerkannt?', 'Die Oder-Neiße-Grenze', ['Die Elbe-Grenze', 'Die Weichsel-Grenze', 'Die Rhein-Grenze']],
          ['Welchem Bündnis gehörte das vereinte Deutschland an?', 'Der NATO', ['Dem Warschauer Pakt', 'Keinem', 'Der GUS']],
          ['Welche Stadt wurde Hauptstadt des vereinten Deutschlands?', 'Berlin', ['Bonn', 'Frankfurt', 'Leipzig']],
          ['Welche Behörde sollte die DDR-Betriebe privatisieren?', 'Die Treuhandanstalt', ['Die Bundesbank', 'Die Stasi', 'Das Kartellamt']],
          ['Welche Abgabe wurde 1991 für den Aufbau Ost eingeführt?', 'Der Solidaritätszuschlag', ['Die Kirchensteuer', 'Die Mehrwertsteuer', 'Der Zehnt']],
          ['Wer leitete zuerst die Behörde für die Stasi-Akten?', 'Joachim Gauck', ['Angela Merkel', 'Helmut Kohl', 'Wolfgang Schäuble']],
          ['Was verloren viele Menschen in Ostdeutschland nach der Einheit?', 'Ihre Arbeit', ['Ihre Sprache', 'Ihr Wahlrecht', 'Ihre Häuser durch Krieg']],
          ['Wann fand die erste freie Volkskammerwahl statt?', '18. März 1990', ['9. November 1989', '3. Oktober 1990', '2. Dezember 1990']],
          ['Welches Bündnis gewann die Volkskammerwahl 1990?', 'Die Allianz für Deutschland', ['Die SED', 'Das Neue Forum', 'Die SPD']],
          ['Wer wurde 1990 Ministerpräsident der DDR?', 'Lothar de Maizière', ['Egon Krenz', 'Hans Modrow', 'Erich Honecker']],
          ['In welchem Verhältnis wurden Löhne 1990 umgestellt?', '1:1', ['1:10', '2:1', '1:100']],
          ['Auf welche Waffen verzichtete Deutschland im Zwei-plus-Vier-Vertrag?', 'Auf atomare, biologische und chemische Waffen', ['Auf Panzer', 'Auf Flugzeuge', 'Auf Gewehre']],
        ],
        mittel: [
          ['Wann legte Kohl das Zehn-Punkte-Programm vor?', '28. November 1989', ['9. November 1989', '18. März 1990', '3. Oktober 1990']],
          ['Um welche Partei herum war die Allianz für Deutschland gebildet?', 'Die Ost-CDU', ['Die SED', 'Die SPD', 'Die FDP']],
          ['Wann trat die Währungsunion in Kraft?', '1. Juli 1990', ['3. Oktober 1990', '18. März 1990', '1. Januar 1991']],
          ['Wann wurde der Einigungsvertrag unterzeichnet?', '31. August 1990', ['12. September 1990', '3. Oktober 1990', '1. Juli 1990']],
          ['Wann wurde der Zwei-plus-Vier-Vertrag unterzeichnet?', '12. September 1990', ['31. August 1990', '3. Oktober 1990', '9. November 1990']],
          ['In welcher Stadt wurde der Zwei-plus-Vier-Vertrag unterzeichnet?', 'In Moskau', ['In Berlin', 'In Paris', 'In Washington']],
          ['Auf wie viele Soldaten wurde die Bundeswehr begrenzt?', '370.000', ['100.000', '1 Million', '37.000']],
          ['Bis wann sollten die sowjetischen Truppen abziehen?', '1994', ['1990', '1999', '2000']],
          ['Nach welchem Artikel des Grundgesetzes trat die DDR bei?', 'Artikel 23', ['Artikel 1', 'Artikel 146', 'Artikel 48']],
          ['Wann fand die erste gesamtdeutsche Bundestagswahl statt?', '2. Dezember 1990', ['3. Oktober 1990', '18. März 1990', '20. Juni 1991']],
          ['Wie viele volkseigene Betriebe sollte die Treuhand etwa privatisieren?', 'Rund 8500', ['Rund 85', 'Rund 85.000', 'Rund 850']],
          ['Welcher Treuhand-Chef wurde 1991 ermordet?', 'Detlev Rohwedder', ['Birgit Breuel', 'Alfred Herrhausen', 'Hanns Martin Schleyer']],
          ['Welches Amt hatte Joachim Gauck später?', 'Bundespräsident', ['Bundeskanzler', 'Bundestagspräsident', 'Papst']],
          ['Welchen Beruf hatte Joachim Gauck?', 'Pfarrer', ['Lehrer', 'Arzt', 'Ingenieur']],
          ['Wann beschloss der Bundestag den Umzug nach Berlin?', '20. Juni 1991', ['3. Oktober 1990', '9. November 1991', '1. Januar 1999']],
          ['Welche Länder unterzeichneten den Zwei-plus-Vier-Vertrag neben beiden deutschen Staaten?', 'USA, Sowjetunion, Großbritannien und Frankreich', ['Polen, Tschechien, Österreich und Schweiz', 'Italien, Spanien, Japan und China', 'Nur die USA']],
          ['Welche Länder wurden zu einem Bundesland vereinigt?', 'Ost- und West-Berlin', ['Sachsen und Thüringen', 'Brandenburg und Berlin', 'Mecklenburg und Vorpommern']],
          ['Wofür wurde der Solidaritätszuschlag verwendet?', 'Für den Aufbau Ost', ['Für die Bundeswehr', 'Für die Kirchen', 'Für die Olympischen Spiele']],
          ['Was bekam Deutschland durch den Zwei-plus-Vier-Vertrag?', 'Die volle Souveränität', ['Neue Kolonien', 'Ostpreußen zurück', 'Einen Sitz im UN-Sicherheitsrat']],
          ['Welches Land gehört nicht zu den neuen Bundesländern?', 'Schleswig-Holstein', ['Sachsen-Anhalt', 'Mecklenburg-Vorpommern', 'Brandenburg']],
        ],
        schwer: [
          ['Mit welchem Ergebnis entschied der Bundestag 1991 für Berlin?', '338 zu 320', ['400 zu 250', '320 zu 338', '500 zu 100']],
          ['War die Volkskammerwahl vom 18. März 1990 die erste freie Wahl in der DDR?', 'Ja, die erste und einzige', ['Nein, die zweite', 'Nein, es gab viele', 'Nein, sie war gefälscht']],
          ['Was regelte die Wirtschafts- und Sozialunion außer der Währung?', 'Die Übernahme der westdeutschen Wirtschafts- und Sozialordnung', ['Die Abschaffung der Renten', 'Die Teilung Berlins', 'Den Austritt aus der NATO']],
          ['Wann wurde Detlev Rohwedder ermordet?', '1991', ['1990', '1995', '1989']],
          ['Welches Ziel verfolgte die Allianz für Deutschland?', 'Eine schnelle Einheit', ['Eine eigenständige DDR', 'Einen Beitritt zur Sowjetunion', 'Eine Monarchie']],
          ['Welche Alternative zu Artikel 23 hätte eine neue Verfassung vorgesehen?', 'Artikel 146', ['Artikel 1', 'Artikel 20', 'Artikel 48']],
          ['Wie viele Punkte hatte Kohls Programm?', 'Zehn', ['Fünf', 'Zwölf', 'Zwanzig']],
          ['Wer wurde nach Rohwedder Treuhand-Chefin?', 'Birgit Breuel', ['Angela Merkel', 'Regine Hildebrandt', 'Rita Süssmuth']],
          ['In welchem Jahr verließen die letzten russischen Truppen Deutschland?', '1994', ['1990', '1991', '2000']],
          ['Welche Länder bilden die fünf neuen Bundesländer?', 'Brandenburg, Mecklenburg-Vorpommern, Sachsen, Sachsen-Anhalt, Thüringen', ['Berlin, Brandenburg, Sachsen, Thüringen, Bayern', 'Sachsen, Thüringen, Hessen, Niedersachsen, Brandenburg', 'Mecklenburg, Pommern, Sachsen, Anhalt, Thüringen']],
          ['Wer gewann die erste gesamtdeutsche Bundestagswahl?', 'Helmut Kohl', ['Oskar Lafontaine', 'Gerhard Schröder', 'Lothar de Maizière']],
          ['Welche Behörde öffnete die Stasi-Akten für Betroffene?', 'Die Stasi-Unterlagen-Behörde', ['Der BND', 'Das Kanzleramt', 'Die Treuhand']],
          ['Was bedeutete die Umstellung der Löhne 1:1 für die DDR-Betriebe?', 'Sie wurden oft nicht mehr konkurrenzfähig', ['Sie wurden reicher', 'Nichts', 'Sie zogen in den Westen']],
          ['Welcher Satz war auf den Demonstrationen 1990 typisch?', '„Wir sind ein Volk!“', ['„Keine Experimente!“', '„Nie wieder Krieg!“', '„Ich bin ein Berliner!“']],
          ['Wann trat die D-Mark in der DDR in Kraft?', '1. Juli 1990', ['3. Oktober 1990', '20. Juni 1948', '1. Januar 2002']],
          ['Welche Stadt war Ort der Unterzeichnung des Einigungsvertrags?', 'Berlin (Ost)', ['Bonn', 'Moskau', 'Paris']],
          ['Wie viele Stimmen gaben bei der Hauptstadtentscheidung den Ausschlag?', '18', ['2', '100', '1']],
          ['Wofür steht „Aufbau Ost“?', 'Für den wirtschaftlichen Wiederaufbau Ostdeutschlands', ['Für die Erweiterung der NATO', 'Für die Bebauung Polens', 'Für den Bau der Mauer']],
          ['Zu welchem Bündnis gehörte das vereinte Deutschland laut Vertrag weiterhin?', 'NATO', ['Warschauer Pakt', 'Neutralität', 'GUS']],
          ['Welche Folge hatte die Schließung vieler Betriebe?', 'Hohe Arbeitslosigkeit im Osten', ['Vollbeschäftigung', 'Sinkende Steuern', 'Wachsende Bevölkerung im Osten']],
        ],
      },
    },
    {
      id: 'seit-1990',
      title: 'Deutschland seit 1990',
      date: 'seit 1990',
      text: [
        '1998 verlor Helmut Kohl nach 16 Jahren die Wahl, und Gerhard Schröder (SPD) bildete die erste Koalition aus SPD und Grünen; Joschka Fischer wurde Außenminister. 1999 nahm die Bundeswehr im Kosovokrieg erstmals an Kampfeinsätzen teil. Im selben Jahr zog der Bundestag in das umgebaute Reichstagsgebäude in Berlin mit seiner gläsernen Kuppel von Norman Foster. 2003 lehnte Schröder eine Beteiligung am Irakkrieg ab und begann mit der „Agenda 2010“ umstrittene Sozial- und Arbeitsmarktreformen (Hartz-Reformen).',
        'Seit 1999 gab es den Euro als Buchgeld, am 1. Januar 2002 löste er auch als Bargeld die D-Mark ab. 2004 traten zehn Staaten, vor allem aus Osteuropa wie Polen und Tschechien, der Europäischen Union bei.',
        'Am 22. November 2005 wurde Angela Merkel (CDU) als erste Frau Bundeskanzlerin; sie regierte 16 Jahre lang bis Dezember 2021. In ihre Amtszeit fielen die Fußball-WM 2006 in Deutschland („Sommermärchen“), die weltweite Finanzkrise ab 2008 und die Eurokrise. Nach der Atomkatastrophe von Fukushima 2011 beschloss Deutschland den Ausstieg aus der Atomkraft; die letzten Kraftwerke gingen am 15. April 2023 vom Netz. 2011 wurde die Wehrpflicht ausgesetzt. 2014 wurde die Nationalmannschaft in Brasilien mit einem Finalsieg über Argentinien Weltmeister, nachdem sie im Halbfinale Gastgeber Brasilien mit 7:1 geschlagen hatte.',
        '2015 kamen rund 890.000 Geflüchtete, viele aus dem Bürgerkriegsland Syrien, nach Deutschland. Merkel sagte: „Wir schaffen das.“ Die Aufnahme wurde zu einem der meistdiskutierten Themen der folgenden Jahre. 2020 legte die Corona-Pandemie das öffentliche Leben mit Lockdowns lahm.',
        'Im Dezember 2021 wurde Olaf Scholz (SPD) Kanzler einer „Ampelkoalition“ aus SPD, Grünen und FDP. Nach dem russischen Großangriff auf die Ukraine am 24. Februar 2022 sprach er von einer „Zeitenwende“: Deutschland lieferte Waffen an die Ukraine und beschloss ein Sondervermögen von 100 Milliarden Euro für die Bundeswehr. Im November 2024 zerbrach die Ampelkoalition. Nach der vorgezogenen Bundestagswahl im Februar 2025 wurde Friedrich Merz (CDU) am 6. Mai 2025 Bundeskanzler einer Koalition aus CDU/CSU und SPD.',
      ],
      quiz: {
        leicht: [
          ['Welche Währung löste 2002 die D-Mark ab?', 'Der Euro', ['Der Dollar', 'Die Rentenmark', 'Der Franken']],
          ['Wer wurde 2005 erste Bundeskanzlerin?', 'Angela Merkel', ['Ursula von der Leyen', 'Annalena Baerbock', 'Hannelore Kraft']],
          ['Wie lange regierte Angela Merkel?', '16 Jahre', ['4 Jahre', '8 Jahre', '25 Jahre']],
          ['Welcher Partei gehört Angela Merkel an?', 'Der CDU', ['Der SPD', 'Den Grünen', 'Der FDP']],
          ['Wie nennt man die Fußball-WM 2006 in Deutschland?', '„Sommermärchen“', ['„Wunder von Bern“', '„Wintermärchen“', '„Weltwunder“']],
          ['Wann wurde Deutschland zuletzt Fußball-Weltmeister?', '2014', ['1990', '2006', '2018']],
          ['Mit welchem Ergebnis schlug Deutschland 2014 Brasilien?', '7:1', ['3:2', '1:0', '2:2']],
          ['In welches Gebäude zog der Bundestag 1999?', 'In das Reichstagsgebäude', ['In das Bundeshaus Bonn', 'In das Berliner Schloss', 'In das Kanzleramt']],
          ['Was ist das Besondere am Reichstagsgebäude heute?', 'Eine gläserne Kuppel', ['Ein goldenes Dach', 'Ein Turm aus Holz', 'Eine Mauer']],
          ['Welche Koalition bildete Gerhard Schröder 1998?', 'SPD und Grüne', ['CDU und FDP', 'SPD und CDU', 'SPD und Linke']],
          ['Welche Katastrophe führte 2011 zum Atomausstieg?', 'Fukushima', ['Tschernobyl', 'Harrisburg', 'Hiroshima']],
          ['Was sagte Merkel 2015 zu den Geflüchteten?', '„Wir schaffen das“', ['„Mehr Demokratie wagen“', '„Ich bin ein Berliner“', '„Wir sind das Volk“']],
          ['Aus welchem Land kamen 2015 viele Geflüchtete?', 'Aus Syrien', ['Aus Kanada', 'Aus Japan', 'Aus Norwegen']],
          ['Welche Pandemie legte 2020 das Leben lahm?', 'Corona', ['Pest', 'Spanische Grippe', 'Cholera']],
          ['Wer wurde 2021 Bundeskanzler?', 'Olaf Scholz', ['Friedrich Merz', 'Armin Laschet', 'Angela Merkel']],
          ['Wie nennt man die Koalition aus SPD, Grünen und FDP?', 'Ampelkoalition', ['Jamaika-Koalition', 'Große Koalition', 'Kenia-Koalition']],
          ['Welches Land wurde am 24. Februar 2022 von Russland angegriffen?', 'Die Ukraine', ['Polen', 'Georgien', 'Finnland']],
          ['Welchen Begriff prägte Scholz nach dem Angriff?', '„Zeitenwende“', ['„Wende“', '„Stunde null“', '„Neustart“']],
          ['Wer wurde 2025 Bundeskanzler?', 'Friedrich Merz', ['Olaf Scholz', 'Markus Söder', 'Robert Habeck']],
          ['Wann gingen die letzten deutschen Atomkraftwerke vom Netz?', '2023', ['2011', '2002', '2030']],
        ],
        mittel: [
          ['Wie lange regierte Helmut Kohl?', '16 Jahre', ['8 Jahre', '12 Jahre', '20 Jahre']],
          ['Wer wurde 1998 Außenminister?', 'Joschka Fischer', ['Hans-Dietrich Genscher', 'Frank-Walter Steinmeier', 'Guido Westerwelle']],
          ['In welchem Krieg nahm die Bundeswehr 1999 erstmals an Kampfeinsätzen teil?', 'Im Kosovokrieg', ['Im Irakkrieg', 'In Afghanistan', 'Im Golfkrieg']],
          ['Wer entwarf die Kuppel des Reichstags?', 'Norman Foster', ['Paul Wallot', 'Albert Speer', 'Frank Gehry']],
          ['An welchem Krieg wollte sich Schröder 2003 nicht beteiligen?', 'Am Irakkrieg', ['Am Kosovokrieg', 'Am Afghanistankrieg', 'Am Ukrainekrieg']],
          ['Wie heißen Schröders Reformen von 2003?', '„Agenda 2010“', ['„Vision 2020“', '„Plan 2000“', '„Zukunft 2030“']],
          ['Wie nennt man die Arbeitsmarktreformen auch?', 'Hartz-Reformen', ['Riester-Reformen', 'Bismarck-Reformen', 'Stein-Hardenberg-Reformen']],
          ['Seit wann gab es den Euro als Buchgeld?', '1999', ['2002', '1990', '2004']],
          ['Wann wurde der Euro Bargeld?', '1. Januar 2002', ['1. Januar 1999', '3. Oktober 1990', '1. Juli 1990']],
          ['Wie viele Staaten traten 2004 der EU bei?', 'Zehn', ['Zwei', 'Fünf', 'Zwanzig']],
          ['An welchem Tag wurde Merkel Kanzlerin?', '22. November 2005', ['3. Oktober 2005', '1. Januar 2006', '9. November 2005']],
          ['Welche Krise begann 2008 weltweit?', 'Die Finanzkrise', ['Die Ölkrise', 'Die Kubakrise', 'Die Corona-Krise']],
          ['Wann wurde die Wehrpflicht ausgesetzt?', '2011', ['1990', '2002', '2020']],
          ['An welchem Tag gingen die letzten Atomkraftwerke vom Netz?', '15. April 2023', ['11. März 2011', '1. Januar 2022', '3. Oktober 2020']],
          ['Wie viele Geflüchtete kamen 2015 etwa nach Deutschland?', 'Rund 890.000', ['Rund 89.000', 'Rund 8,9 Millionen', 'Rund 8900']],
          ['In welchem Land wurde Deutschland 2014 Weltmeister?', 'In Brasilien', ['In Südafrika', 'In Russland', 'In Deutschland']],
          ['Wie hoch war das Sondervermögen für die Bundeswehr 2022?', '100 Milliarden Euro', ['10 Milliarden Euro', '1 Billion Euro', '1 Milliarde Euro']],
          ['Wann zerbrach die Ampelkoalition?', 'November 2024', ['Dezember 2021', 'Februar 2022', 'Mai 2025']],
          ['Wann fand die vorgezogene Bundestagswahl statt?', 'Februar 2025', ['September 2024', 'Mai 2025', 'Dezember 2024']],
          ['Mit welcher Partei koaliert Merz’ CDU/CSU?', 'Mit der SPD', ['Mit den Grünen', 'Mit der FDP', 'Mit der AfD']],
        ],
        schwer: [
          ['An welchem Tag wurde Friedrich Merz Bundeskanzler?', '6. Mai 2025', ['23. Februar 2025', '8. Dezember 2021', '1. Januar 2025']],
          ['An welchem Tag begann Russlands Großangriff auf die Ukraine?', '24. Februar 2022', ['8. Dezember 2021', '24. Februar 2014', '1. September 2022']],
          ['Bis wann regierte Merkel?', 'Dezember 2021', ['September 2021', 'Dezember 2017', 'Mai 2025']],
          ['Wann wurde Olaf Scholz Kanzler?', 'Dezember 2021', ['September 2021', 'Februar 2022', 'Mai 2025']],
          ['Welche Länder traten 2004 unter anderem der EU bei?', 'Polen und Tschechien', ['Rumänien und Bulgarien', 'Schweden und Finnland', 'Kroatien und Rumänien']],
          ['Welche Krise folgte in Europa auf die Finanzkrise?', 'Die Eurokrise', ['Die Ölkrise', 'Die Hungerkrise', 'Die Kubakrise']],
          ['Wann ereignete sich die Katastrophe von Fukushima?', '2011', ['2006', '1986', '2015']],
          ['Wann zog der Bundestag nach Berlin?', '1999', ['1991', '1990', '2002']],
          ['Wann nahm die Bundeswehr erstmals an Kampfeinsätzen teil?', '1999', ['1990', '2001', '2014']],
          ['Wann begann Schröder die Agenda 2010?', '2003', ['1998', '2005', '2010']],
          ['Wann verlor Kohl die Bundestagswahl?', '1998', ['1994', '2002', '1990']],
          ['Wer war Kanzler vor Angela Merkel?', 'Gerhard Schröder', ['Helmut Kohl', 'Olaf Scholz', 'Helmut Schmidt']],
          ['Wer war Kanzler vor Friedrich Merz?', 'Olaf Scholz', ['Angela Merkel', 'Gerhard Schröder', 'Armin Laschet']],
          ['Welche Parteien bildeten die Ampelkoalition?', 'SPD, Grüne und FDP', ['CDU, Grüne und FDP', 'SPD, Linke und Grüne', 'CDU, CSU und SPD']],
          ['In welchem Jahr legte Corona das öffentliche Leben mit Lockdowns lahm?', '2020', ['2015', '2008', '2022']],
          ['Wofür wurde das Sondervermögen 2022 beschlossen?', 'Für die Bundeswehr', ['Für die Schulen', 'Für die Bahn', 'Für Corona-Hilfen']],
          ['Welches Land gewann Deutschland 2014 im WM-Finale?', 'Argentinien', ['Brasilien', 'Niederlande', 'Spanien']],
          ['Welcher Grünen-Politiker wurde 1998 Außenminister?', 'Joschka Fischer', ['Jürgen Trittin', 'Cem Özdemir', 'Robert Habeck']],
          ['Welcher Bürgerkrieg trieb 2015 viele Menschen zur Flucht?', 'Der syrische Bürgerkrieg', ['Der spanische Bürgerkrieg', 'Der amerikanische Bürgerkrieg', 'Der Bürgerkrieg in Irland']],
          ['Welcher Kanzler lehnte den Irakkrieg ab?', 'Gerhard Schröder', ['Angela Merkel', 'Helmut Kohl', 'Olaf Scholz']],
        ],
      },
    },
  ],
};
