import type { Epoch } from '../types';

export const E1: Epoch = {
  id: 'fruehzeit',
  name: 'Frühzeit und Kaiserhof',
  period: 'bis 1185',
  events: [
    {
      id: 'jomon-yayoi',
      title: 'Jōmon, Yayoi und Kofun',
      date: 'ca. 14.000 v. Chr. – 538 n. Chr.',
      text: [
        'Die ersten Bewohner Japans schufen eine der ältesten Töpferkulturen der Welt. Mit dem Reisanbau aus Korea und China entstanden Dörfer, Fürstentümer und riesige schlüssellochförmige Grabhügel – die Anfänge des japanischen Staates.',
      ],
      subtopics: [
        {
          id: 'jomon-kofun',
          title: 'Von der Jōmon- zur Kofun-Zeit',
          date: 'ca. 14.000 v. Chr. – 538 n. Chr.',
          text: [
            'Die Jōmon-Zeit (etwa 14.000–300 v. Chr.) ist nach dem „Schnurmuster“ benannt, das die Menschen in ihre Tongefäße drückten. Diese Keramik gehört zu den ältesten der Welt. Die Jōmon-Menschen lebten als Jäger, Fischer und Sammler in Grubenhäusern, oft an der Küste, wo riesige Muschelhaufen von ihren Mahlzeiten zeugen. Sie formten auch rätselhafte Tonfiguren, die „Dogū“.',
            'In der Yayoi-Zeit (etwa 300 v. Chr. – 250 n. Chr.) kamen Einwanderer vom asiatischen Festland, vor allem über Korea, und brachten den Nassreisanbau, Bronze und Eisen mit. Es entstanden befestigte Dörfer wie Yoshinogari auf Kyūshū. Chinesische Chroniken berichten vom Land „Wa“ und von der Königin Himiko, einer Schamanin, die um 240 n. Chr. Gesandte an den chinesischen Hof schickte.',
            'In der Kofun-Zeit (etwa 250–538) bauten mächtige Herrscher riesige Grabhügel, die „Kofun“, oft in Form eines Schlüssellochs. Der größte, der dem Kaiser Nintoku zugeschrieben wird, ist rund 486 Meter lang – eines der größten Gräber der Welt – und gehört zum UNESCO-Welterbe Mozu-Furuichi. Um die Gräber standen Tonfiguren, die „Haniwa“, in Form von Kriegern, Pferden und Häusern.',
            'In dieser Zeit einte das Herrscherhaus von Yamato in der Gegend des heutigen Nara große Teile Japans. Von ihm stammt das japanische Kaiserhaus ab – die älteste noch bestehende Erbmonarchie der Welt. Der Legende nach gründete Kaiser Jimmu, ein Nachfahre der Sonnengöttin Amaterasu, den Staat 660 v. Chr.; der 11. Februar ist daher Staatsgründungstag.',
            'Die ursprüngliche Religion Japans ist der Shintō („Weg der Götter“). Er verehrt unzählige „Kami“ – Götter und Geister in Bergen, Flüssen, Bäumen und Ahnen. Die Sonnengöttin Amaterasu wird im Großschrein von Ise verehrt. Erkennungszeichen der Shintō-Schreine ist das Tor „Torii“.',
          ],
          quiz: {
            leicht: [
              ['Wonach ist die Jōmon-Zeit benannt?', 'Nach dem Schnurmuster auf Tongefäßen', ['Nach einem Kaiser', 'Nach einem Vulkan', 'Nach einer Stadt']],
              ['Was ist an der Jōmon-Keramik besonders?', 'Sie gehört zu den ältesten der Welt', ['Sie ist aus Porzellan', 'Sie ist aus Gold', 'Sie stammt aus China']],
              ['Wie lebten die Jōmon-Menschen?', 'Als Jäger, Fischer und Sammler', ['Als Reisbauern', 'In Städten', 'Als Samurai']],
              ['Wie heißen die rätselhaften Jōmon-Tonfiguren?', 'Dogū', ['Haniwa', 'Kami', 'Torii']],
              ['Was brachten Einwanderer in der Yayoi-Zeit mit?', 'Den Nassreisanbau', ['Den Buddhismus', 'Feuerwaffen', 'Das Christentum']],
              ['Über welches Land kamen viele Yayoi-Einwanderer?', 'Über Korea', ['Über Russland', 'Über Taiwan', 'Über Amerika']],
              ['Welche Metalle kamen in der Yayoi-Zeit nach Japan?', 'Bronze und Eisen', ['Gold und Silber', 'Aluminium', 'Stahl und Titan']],
              ['Wie nannten chinesische Chroniken Japan?', 'Wa', ['Nippon', 'Yamato', 'Zipangu']],
              ['Welche Königin schickte um 240 Gesandte nach China?', 'Himiko', ['Amaterasu', 'Suiko', 'Murasaki']],
              ['Was war Himiko?', 'Eine Schamanin', ['Eine Kriegerin der Samurai', 'Eine Kaiserin von China', 'Eine Dichterin']],
              ['Wie heißen die riesigen Grabhügel?', 'Kofun', ['Haniwa', 'Dogū', 'Pagoden']],
              ['Welche Form haben viele Kofun?', 'Die eines Schlüssellochs', ['Die einer Pyramide', 'Die eines Sterns', 'Die eines Kreises']],
              ['Wie heißen die Tonfiguren um die Gräber?', 'Haniwa', ['Dogū', 'Kami', 'Netsuke']],
              ['Welches Herrscherhaus einte Japan?', 'Das Haus Yamato', ['Das Haus Tokugawa', 'Das Haus Minamoto', 'Das Haus Fujiwara']],
              ['Was stammt vom Yamato-Herrscherhaus ab?', 'Das japanische Kaiserhaus', ['Die Samurai', 'Die Shogune', 'Die Ainu']],
              ['Welche Göttin gilt als Ahnin des Kaiserhauses?', 'Amaterasu', ['Himiko', 'Izanami', 'Kannon']],
              ['Welcher Tag ist Staatsgründungstag?', 'Der 11. Februar', ['Der 3. Mai', 'Der 15. August', 'Der 1. Januar']],
              ['Wie heißt die ursprüngliche Religion Japans?', 'Shintō', ['Buddhismus', 'Konfuzianismus', 'Daoismus']],
              ['Was bedeutet „Shintō“?', 'Weg der Götter', ['Weg des Kriegers', 'Weg des Tees', 'Weg der Sonne']],
              ['Welches Tor kennzeichnet Shintō-Schreine?', 'Das Torii', ['Die Pagode', 'Das Minarett', 'Der Triumphbogen']],
            ],
            mittel: [
              ['Wann dauerte die Jōmon-Zeit etwa?', 'Etwa 14.000–300 v. Chr.', ['Etwa 300 v.–250 n. Chr.', 'Etwa 250–538', 'Etwa 710–794']],
              ['In welchen Häusern lebten die Jōmon-Menschen?', 'In Grubenhäusern', ['In Pfahlbauten aus Stein', 'In Burgen', 'In Zelten aus Leder']],
              ['Was zeugt von den Mahlzeiten der Jōmon?', 'Riesige Muschelhaufen', ['Pyramiden', 'Kochbücher', 'Kornspeicher']],
              ['Wann dauerte die Yayoi-Zeit etwa?', 'Etwa 300 v. Chr. – 250 n. Chr.', ['Etwa 14.000–300 v. Chr.', 'Etwa 538–710', 'Etwa 794–1185']],
              ['Welches befestigte Dorf liegt auf Kyūshū?', 'Yoshinogari', ['Nara', 'Kamakura', 'Edo']],
              ['Wann schickte Himiko Gesandte nach China?', 'Um 240 n. Chr.', ['Um 660 v. Chr.', 'Um 794', 'Um 1185']],
              ['Wann dauerte die Kofun-Zeit etwa?', 'Etwa 250–538', ['Etwa 710–794', 'Etwa 1185–1333', 'Etwa 300 v.–250 n. Chr.']],
              ['Welchem Kaiser wird der größte Kofun zugeschrieben?', 'Nintoku', ['Jimmu', 'Meiji', 'Shōmu']],
              ['Wie lang ist der größte Kofun etwa?', 'Rund 486 Meter', ['Rund 48 Meter', 'Rund 4,8 Kilometer', 'Rund 100 Meter']],
              ['Zu welchem Welterbe gehört der Nintoku-Kofun?', 'Mozu-Furuichi', ['Himeji', 'Nikko', 'Itsukushima']],
              ['Welche Formen haben Haniwa?', 'Krieger, Pferde und Häuser', ['Drachen und Phönixe', 'Buddhas', 'Samurai mit Gewehren']],
              ['In welcher Gegend lag das Yamato-Zentrum?', 'Im Gebiet des heutigen Nara', ['Im heutigen Tokio', 'Auf Hokkaidō', 'Auf Okinawa']],
              ['Was ist am japanischen Kaiserhaus besonders?', 'Älteste noch bestehende Erbmonarchie der Welt', ['Jüngste Monarchie', 'Wahlmonarchie', 'Es wurde 1945 abgeschafft']],
              ['Wer soll den Staat der Legende nach gegründet haben?', 'Kaiser Jimmu', ['Kaiser Meiji', 'Prinz Shōtoku', 'Himiko']],
              ['Wann soll Jimmu den Staat gegründet haben?', '660 v. Chr.', ['660 n. Chr.', '1185', '238 n. Chr.']],
              ['Was verehrt der Shintō?', 'Kami in Natur und Ahnen', ['Einen einzigen Gott', 'Nur Buddha', 'Nur den Kaiser']],
              ['Wo wohnen Kami laut Shintō?', 'In Bergen, Flüssen, Bäumen und Ahnen', ['Nur im Himmel', 'Nur in Tempeln', 'Nur im Meer']],
              ['Wo wird Amaterasu verehrt?', 'Im Großschrein von Ise', ['Im Tōdai-ji', 'Im Kinkaku-ji', 'In Kamakura']],
              ['Was bedeutet „Kami“?', 'Götter und Geister', ['Krieger', 'Kaiser', 'Mönche']],
              ['Wovon war Amaterasu Göttin?', 'Von der Sonne', ['Vom Meer', 'Vom Mond', 'Vom Krieg']],
            ],
            schwer: [
              ['Welche Zeit brachte den Nassreisanbau nach Japan?', 'Die Yayoi-Zeit', ['Die Jōmon-Zeit', 'Die Kofun-Zeit', 'Die Nara-Zeit']],
              ['Welches Welterbe umfasst riesige Schlüssellochgräber?', 'Mozu-Furuichi', ['Yoshinogari', 'Horyū-ji', 'Shirakawa-gō']],
              ['Welche Königin ist nur aus chinesischen Quellen bekannt?', 'Himiko', ['Suiko', 'Kōmyō', 'Jingū']],
              ['Welcher Kaiser gilt als legendärer Staatsgründer?', 'Jimmu', ['Nintoku', 'Kanmu', 'Tenmu']],
              ['Welches Herrscherhaus begründete den japanischen Staat?', 'Yamato', ['Soga', 'Taira', 'Hōjō']],
              ['Welche Jōmon-Funde zeigen Ernährung aus dem Meer?', 'Muschelhaufen', ['Reisspeicher', 'Bronzeglocken', 'Haniwa']],
              ['Welche Figuren standen um die Kofun-Gräber?', 'Haniwa', ['Dogū', 'Kokeshi', 'Daruma']],
              ['Welcher Schrein ist der heiligste des Shintō?', 'Ise', ['Itsukushima', 'Meiji-Schrein', 'Fushimi Inari']],
              ['Welches Datum feiert Japan als Staatsgründung?', '11. Februar', ['3. November', '29. April', '23. Dezember']],
              ['Welche Zeit ist nach einem Keramikmuster benannt?', 'Jōmon', ['Yayoi', 'Kofun', 'Asuka']],
              ['Welche Insel ist Fundort von Yoshinogari?', 'Kyūshū', ['Hokkaidō', 'Honshū bei Tokio', 'Shikoku']],
              ['Welcher Name Japans stammt aus chinesischen Quellen?', 'Wa', ['Nippon', 'Edo', 'Heian']],
              ['Welche Göttin wird als Ahnin der Kaiser verehrt?', 'Amaterasu', ['Inari', 'Benten', 'Izanami']],
              ['Welche Zeit ist nach Grabhügeln benannt?', 'Kofun', ['Jōmon', 'Yayoi', 'Heian']],
              ['Wie viele Jahre umfasste die Jōmon-Zeit etwa?', 'Über 13.000', ['Rund 500', 'Rund 1.000', 'Rund 100.000']],
              ['Welches Merkmal haben die größten Kofun?', 'Schlüssellochform', ['Stufenpyramide', 'Kuppel aus Stein', 'Turmform']],
              ['Welcher Begriff bezeichnet Shintō-Gottheiten?', 'Kami', ['Bodhisattva', 'Oni', 'Yōkai']],
              ['Welche Technik kam mit den Yayoi-Einwanderern?', 'Metallverarbeitung mit Bronze und Eisen', ['Porzellanherstellung', 'Buchdruck', 'Schießpulver']],
              ['Welche Art Monarchie hat Japan bis heute?', 'Die älteste ununterbrochene Erbmonarchie', ['Eine Wahlmonarchie', 'Eine absolute Monarchie', 'Keine Monarchie']],
              ['Welcher Kofun gilt als einer der größten der Welt?', 'Der Nintoku-Kofun', ['Der Jimmu-Kofun', 'Der Himiko-Kofun', 'Der Ise-Kofun']],
            ],
          },
        },
      ],
    },
    {
      id: 'heian',
      title: 'Kaiser, Shinto und das Heian-Zeitalter',
      date: '538–1185',
      text: [
        'Mit dem Buddhismus kamen chinesische Schrift, Verwaltung und Kunst nach Japan. In Nara und später in Heian-kyō (Kyōto) blühte eine höfische Kultur, die Meisterwerke wie das „Genji Monogatari“ hervorbrachte.',
      ],
      subtopics: [
        {
          id: 'asuka-nara',
          title: 'Buddhismus, Shōtoku und Nara',
          date: '538–794',
          text: [
            'Um 538 (oder 552) schickte ein koreanischer König eine Buddha-Statue und Schriften an den japanischen Hof. Der mächtige Soga-Clan förderte den Buddhismus. Mit ihm kamen chinesische Schriftzeichen (Kanji), Baukunst, Medizin und Konfuzianismus nach Japan.',
            'Prinz Shōtoku (574–622), Regent für Kaiserin Suiko, gilt als Vater der japanischen Kultur. Er erließ 604 die „Verfassung der 17 Artikel“, die Harmonie, Buddhismus und Gehorsam gegenüber dem Kaiser betonte, und schickte Gesandte an den Hof der chinesischen Sui-Dynastie. In einem Brief nannte er Japan das Land, „wo die Sonne aufgeht“ – daher „Nihon“ oder „Nippon“ („Ursprung der Sonne“). Er gründete den Tempel Hōryū-ji, dessen Holzbauten zu den ältesten der Welt zählen.',
            'Mit der „Taika-Reform“ von 645 begann der Hof, Japan nach chinesischem Vorbild zu ordnen: Alles Land gehörte dem Kaiser, Bauern erhielten Felder zugeteilt und zahlten Steuern. 710 entstand mit Nara (Heijō-kyō) die erste feste Hauptstadt, angelegt im Schachbrettmuster wie die chinesische Hauptstadt Chang’an.',
            'Kaiser Shōmu ließ im Tōdai-ji in Nara einen riesigen bronzenen Buddha errichten, der 752 eingeweiht wurde und rund 15 Meter hoch ist. Das „Kojiki“ (712) und das „Nihon Shoki“ (720) erzählten die Mythen und frühe Geschichte Japans, die Gedichtsammlung „Man’yōshū“ sammelte rund 4.500 Gedichte.',
            'Weil buddhistische Klöster in Nara zu viel politische Macht gewannen, verlegte Kaiser Kanmu die Hauptstadt – zuerst 784 nach Nagaoka und 794 nach Heian-kyō („Hauptstadt des Friedens“), dem heutigen Kyōto. Kyōto blieb über 1.000 Jahre bis 1868 die Kaiserstadt.',
          ],
          quiz: {
            leicht: [
              ['Welche Religion kam um 538 nach Japan?', 'Der Buddhismus', ['Das Christentum', 'Der Islam', 'Der Shintō']],
              ['Von wo wurde eine Buddha-Statue geschickt?', 'Aus Korea', ['Aus Indien', 'Aus China direkt', 'Aus Vietnam']],
              ['Welcher Clan förderte den Buddhismus?', 'Der Soga-Clan', ['Der Tokugawa-Clan', 'Der Minamoto-Clan', 'Der Taira-Clan']],
              ['Wie heißen die chinesischen Schriftzeichen in Japan?', 'Kanji', ['Kana', 'Hangul', 'Romaji']],
              ['Wer gilt als Vater der japanischen Kultur?', 'Prinz Shōtoku', ['Kaiser Meiji', 'Oda Nobunaga', 'Himiko']],
              ['Für welche Kaiserin war Shōtoku Regent?', 'Suiko', ['Himiko', 'Amaterasu', 'Kōmyō']],
              ['Welche Verfassung erließ Shōtoku 604?', 'Die Verfassung der 17 Artikel', ['Die Meiji-Verfassung', 'Die Taika-Verfassung', 'Die Verfassung der 10 Gebote']],
              ['Was betonte die Verfassung der 17 Artikel?', 'Harmonie und Gehorsam gegenüber dem Kaiser', ['Demokratie', 'Krieg', 'Freien Handel']],
              ['Wie nannte Shōtoku Japan in einem Brief?', 'Land, wo die Sonne aufgeht', ['Land des Mondes', 'Land der Drachen', 'Reich der Mitte']],
              ['Was bedeutet „Nippon“?', 'Ursprung der Sonne', ['Land der Inseln', 'Reich des Friedens', 'Weg der Götter']],
              ['Welchen Tempel gründete Shōtoku?', 'Hōryū-ji', ['Tōdai-ji', 'Kinkaku-ji', 'Sensō-ji']],
              ['Nach welchem Vorbild ordnete die Taika-Reform Japan?', 'Nach chinesischem Vorbild', ['Nach europäischem Vorbild', 'Nach amerikanischem Vorbild', 'Nach indischem Vorbild']],
              ['Wem gehörte nach der Taika-Reform alles Land?', 'Dem Kaiser', ['Den Bauern', 'Den Klöstern', 'Den Samurai']],
              ['Welche Stadt wurde 710 erste feste Hauptstadt?', 'Nara', ['Kyōto', 'Tokio', 'Kamakura']],
              ['Welche große Statue steht im Tōdai-ji?', 'Ein bronzener Buddha', ['Eine Samurai-Statue', 'Ein Drache', 'Eine Kaiserstatue']],
              ['Wie hoch ist der Buddha von Nara etwa?', 'Rund 15 Meter', ['Rund 1,5 Meter', 'Rund 150 Meter', 'Rund 50 Meter']],
              ['Welches Werk erzählt die Mythen Japans?', 'Das Kojiki', ['Das Genji Monogatari', 'Das Kopfkissenbuch', 'Das Hagakure']],
              ['Welcher Kaiser verlegte die Hauptstadt 794?', 'Kanmu', ['Shōmu', 'Meiji', 'Jimmu']],
              ['Was bedeutet „Heian-kyō“?', 'Hauptstadt des Friedens', ['Hauptstadt des Ostens', 'Stadt des Kaisers', 'Stadt der Sonne']],
              ['Wie heißt Heian-kyō heute?', 'Kyōto', ['Nara', 'Osaka', 'Tokio']],
            ],
            mittel: [
              ['Welches alternative Datum wird für die Ankunft des Buddhismus genannt?', '552', ['710', '794', '645']],
              ['Was kam mit dem Buddhismus nach Japan?', 'Schrift, Baukunst, Medizin und Konfuzianismus', ['Feuerwaffen und Uhren', 'Kartoffeln und Mais', 'Das Christentum']],
              ['Wann lebte Prinz Shōtoku?', '574–622', ['710–794', '1185–1220', '1543–1616']],
              ['An welchen chinesischen Hof schickte Shōtoku Gesandte?', 'An den Hof der Sui', ['An den Hof der Ming', 'An den Hof der Han', 'An den Hof der Qing']],
              ['Was ist am Hōryū-ji besonders?', 'Seine Holzbauten gehören zu den ältesten der Welt', ['Er ist aus Gold', 'Er ist der höchste Tempel', 'Er steht in China']],
              ['Wann fand die Taika-Reform statt?', '645', ['604', '710', '794']],
              ['Was erhielten Bauern nach der Taika-Reform?', 'Zugeteilte Felder gegen Steuern', ['Eigenes freies Land', 'Waffen', 'Nichts']],
              ['Wie hieß Nara als Hauptstadt?', 'Heijō-kyō', ['Heian-kyō', 'Edo', 'Nagaoka']],
              ['In welchem Muster wurde Nara angelegt?', 'Im Schachbrettmuster', ['Als Kreis', 'Als Stern', 'Ohne Plan']],
              ['Nach welcher Stadt wurde Nara gestaltet?', 'Nach Chang’an', ['Nach Rom', 'Nach Seoul', 'Nach Peking']],
              ['Welcher Kaiser ließ den großen Buddha errichten?', 'Shōmu', ['Kanmu', 'Tenmu', 'Jimmu']],
              ['Wann wurde der große Buddha eingeweiht?', '752', ['604', '794', '1052']],
              ['Wann entstand das Kojiki?', '712', ['720', '604', '1008']],
              ['Wann entstand das Nihon Shoki?', '720', ['712', '794', '645']],
              ['Wie heißt die große Gedichtsammlung der Nara-Zeit?', 'Man’yōshū', ['Kokinshū', 'Genji Monogatari', 'Hōjōki']],
              ['Wie viele Gedichte enthält das Man’yōshū etwa?', 'Rund 4.500', ['Rund 45', 'Rund 450', 'Rund 45.000']],
              ['Warum verlegte Kanmu die Hauptstadt?', 'Die Klöster in Nara wurden zu mächtig', ['Ein Erdbeben', 'Ein Krieg mit China', 'Eine Flut']],
              ['Wohin wurde die Hauptstadt 784 zuerst verlegt?', 'Nach Nagaoka', ['Nach Kamakura', 'Nach Osaka', 'Nach Edo']],
              ['Bis wann blieb Kyōto Kaiserstadt?', 'Bis 1868', ['Bis 1185', 'Bis 1603', 'Bis 1945']],
              ['Wie lange war Kyōto Kaiserstadt etwa?', 'Über 1.000 Jahre', ['Rund 100 Jahre', 'Rund 50 Jahre', 'Rund 300 Jahre']],
            ],
            schwer: [
              ['Welcher Prinz prägte den Namen „Nippon“?', 'Shōtoku', ['Naka no Ōe', 'Fujiwara no Michinaga', 'Genji']],
              ['Welche Reform von 645 verstaatlichte das Land?', 'Die Taika-Reform', ['Die Meiji-Reform', 'Die Kenmu-Restauration', 'Die Kyōhō-Reform']],
              ['Welche Stadt war 784–794 kurz Hauptstadt?', 'Nagaoka', ['Nara', 'Kamakura', 'Edo']],
              ['Welcher Tempel beherbergt den großen Bronze-Buddha?', 'Tōdai-ji', ['Hōryū-ji', 'Kiyomizu-dera', 'Byōdō-in']],
              ['Welche zwei Werke berichten die frühe Geschichte Japans?', 'Kojiki und Nihon Shoki', ['Genji und Heike', 'Man’yōshū und Kokinshū', 'Hagakure und Gorin no Sho']],
              ['Welcher Clan stand hinter der Einführung des Buddhismus?', 'Soga', ['Mononobe', 'Fujiwara', 'Taira']],
              ['Welches Dokument von 604 gilt als erste Verfassung Japans?', 'Die Verfassung der 17 Artikel', ['Das Taihō-Gesetz', 'Die Meiji-Verfassung', 'Das Goseibai Shikimoku']],
              ['Welche chinesische Hauptstadt war Vorbild für Nara?', 'Chang’an', ['Luoyang', 'Nanjing', 'Kaifeng']],
              ['Welche Gedichtsammlung ist die älteste Japans?', 'Man’yōshū', ['Kokinshū', 'Shin Kokinshū', 'Hyakunin Isshu']],
              ['Welches Jahr markiert die Gründung von Heian-kyō?', '794', ['710', '784', '1185']],
              ['Welcher Tempel enthält einige der ältesten Holzbauten der Welt?', 'Hōryū-ji', ['Tōdai-ji', 'Kinkaku-ji', 'Ginkaku-ji']],
              ['Welches Land vermittelte den Buddhismus nach Japan?', 'Korea', ['Indien', 'Tibet', 'Thailand']],
              ['Welche Kaiserin regierte mit Shōtoku als Regent?', 'Suiko', ['Jitō', 'Genmei', 'Kōken']],
              ['Welches Problem führte zur Verlegung der Hauptstadt aus Nara?', 'Die politische Macht buddhistischer Klöster', ['Überbevölkerung', 'Ein Vulkanausbruch', 'Ein Krieg mit Korea']],
              ['Welches Jahr ist mit der Gründung Naras als Hauptstadt verbunden?', '710', ['645', '794', '604']],
              ['Welche Dynastie Chinas empfing Shōtokus Gesandte?', 'Sui', ['Tang', 'Han', 'Song']],
              ['Welcher Kaiser gründete Kyōto als Hauptstadt?', 'Kanmu', ['Shōmu', 'Daigo', 'Go-Daigo']],
              ['Welcher Name trug Nara als Hauptstadt?', 'Heijō-kyō', ['Heian-kyō', 'Fujiwara-kyō', 'Naniwa-kyō']],
              ['Welches Werk wurde 720 vollendet?', 'Nihon Shoki', ['Kojiki', 'Man’yōshū', 'Genji Monogatari']],
              ['Wann wurde der große Buddha von Nara eingeweiht?', '752', ['710', '794', '645']],
            ],
          },
        },
        {
          id: 'heian-zeit',
          title: 'Die Heian-Zeit und die Hofkultur',
          date: '794–1185',
          text: [
            'In der Heian-Zeit erreichte die Hofkultur in Kyōto ihren Höhepunkt. Die eigentliche Macht lag aber bald bei der Familie Fujiwara, die ihre Töchter mit Kaisern verheiratete und als Regenten herrschte. Am mächtigsten war Fujiwara no Michinaga (966–1028), dessen Töchter vier Kaiser heirateten.',
            'Japan löste sich von China: 894 wurden die Gesandtschaften an den Tang-Hof eingestellt. Aus den Kanji entwickelten sich die Silbenschriften „Kana“ – Hiragana und Katakana –, mit denen man Japanisch einfacher schreiben konnte. Besonders Frauen am Hof nutzten Hiragana.',
            'So entstanden Meisterwerke der Weltliteratur: Um 1008 schrieb die Hofdame Murasaki Shikibu das „Genji Monogatari“ („Die Geschichte vom Prinzen Genji“), das oft als erster Roman der Welt bezeichnet wird. Ihre Rivalin Sei Shōnagon verfasste das „Kopfkissenbuch“ mit Listen und Beobachtungen aus dem Hofleben.',
            'Am Hof zählten Schönheit, Dichtkunst und guter Geschmack: Adlige wechselten Gedichte, Frauen schwärzten ihre Zähne und trugen bis zu zwölf Lagen farbiger Seidengewänder („Jūnihitoe“). Der buddhistische Glaube an das „Reine Land“ des Amida-Buddha verbreitete sich; der Phönix-Pavillon des Byōdō-in (1053) zeigt dieses Paradies – er ist heute auf der 10-Yen-Münze abgebildet.',
            'Während der Hof feierte, sicherten auf dem Land Kriegerfamilien ihre Güter mit eigenen Truppen – die Anfänge der Samurai. Die beiden mächtigsten Clans, die Taira und die Minamoto, kämpften im Genpei-Krieg (1180–1185) um die Macht. 1185 vernichteten die Minamoto die Taira in der Seeschlacht von Dan-no-ura; die Heian-Zeit endete.',
          ],
          quiz: {
            leicht: [
              ['Wo erreichte die Hofkultur ihren Höhepunkt?', 'In Kyōto', ['In Nara', 'In Edo', 'In Kamakura']],
              ['Welche Familie hatte in der Heian-Zeit die eigentliche Macht?', 'Die Fujiwara', ['Die Tokugawa', 'Die Soga', 'Die Oda']],
              ['Wie sicherten die Fujiwara ihre Macht?', 'Sie verheirateten ihre Töchter mit Kaisern', ['Durch Kriege', 'Durch Handel mit China', 'Durch Wahlen']],
              ['Wer war der mächtigste Fujiwara?', 'Fujiwara no Michinaga', ['Fujiwara no Kamatari', 'Minamoto no Yoritomo', 'Taira no Kiyomori']],
              ['Wann wurden die Gesandtschaften nach China eingestellt?', '894', ['794', '1185', '645']],
              ['Wie heißen die japanischen Silbenschriften?', 'Kana', ['Kanji', 'Hangul', 'Pinyin']],
              ['Welche zwei Kana-Schriften gibt es?', 'Hiragana und Katakana', ['Kanji und Romaji', 'Hangul und Kana', 'Man’yōgana und Pinyin']],
              ['Wer nutzte Hiragana besonders?', 'Frauen am Hof', ['Samurai', 'Mönche in China', 'Bauern']],
              ['Wer schrieb das Genji Monogatari?', 'Murasaki Shikibu', ['Sei Shōnagon', 'Prinz Shōtoku', 'Bashō']],
              ['Als was wird das Genji Monogatari oft bezeichnet?', 'Als erster Roman der Welt', ['Als erstes Gesetzbuch', 'Als erste Zeitung', 'Als erstes Kochbuch']],
              ['Wann entstand das Genji Monogatari etwa?', 'Um 1008', ['Um 712', 'Um 1603', 'Um 1868']],
              ['Wer schrieb das „Kopfkissenbuch“?', 'Sei Shōnagon', ['Murasaki Shikibu', 'Kaiserin Suiko', 'Himiko']],
              ['Was zählte am Heian-Hof?', 'Schönheit, Dichtkunst und guter Geschmack', ['Kampfkraft', 'Reichtum aus Handel', 'Seefahrt']],
              ['Was taten adlige Frauen mit ihren Zähnen?', 'Sie schwärzten sie', ['Sie vergoldeten sie', 'Sie zogen sie', 'Sie färbten sie rot']],
              ['Wie viele Lagen Seide trugen Hofdamen bis zu?', 'Zwölf', ['Zwei', 'Hundert', 'Fünf']],
              ['Welcher Buddha versprach das „Reine Land“?', 'Amida', ['Maitreya', 'Hotei', 'Kannon']],
              ['Auf welcher Münze ist der Phönix-Pavillon?', 'Auf der 10-Yen-Münze', ['Auf der 100-Yen-Münze', 'Auf dem 1.000-Yen-Schein', 'Auf keiner']],
              ['Wer sicherte auf dem Land die Güter mit Truppen?', 'Kriegerfamilien', ['Mönche', 'Hofdamen', 'Chinesen']],
              ['Welche zwei Clans kämpften im Genpei-Krieg?', 'Taira und Minamoto', ['Tokugawa und Toyotomi', 'Soga und Mononobe', 'Fujiwara und Oda']],
              ['Wer gewann den Genpei-Krieg?', 'Die Minamoto', ['Die Taira', 'Die Fujiwara', 'Der Kaiser']],
            ],
            mittel: [
              ['Wann lebte Fujiwara no Michinaga?', '966–1028', ['574–622', '1147–1199', '1534–1582']],
              ['Wie viele Kaiser heirateten Töchter Michinagas?', 'Vier', ['Einer', 'Zehn', 'Keiner']],
              ['Als was herrschten die Fujiwara?', 'Als Regenten', ['Als Kaiser', 'Als Shogune', 'Als Mönche']],
              ['An welchen chinesischen Hof gingen die Gesandtschaften bis 894?', 'An den Tang-Hof', ['An den Ming-Hof', 'An den Han-Hof', 'An den Song-Hof']],
              ['Woraus entwickelten sich die Kana?', 'Aus den Kanji', ['Aus dem lateinischen Alphabet', 'Aus Hangul', 'Aus Sanskrit']],
              ['Wozu dienten die Kana?', 'Japanisch einfacher zu schreiben', ['Chinesisch zu schreiben', 'Zahlen zu schreiben', 'Geheimbotschaften']],
              ['Was bedeutet „Genji Monogatari“?', 'Die Geschichte vom Prinzen Genji', ['Das Buch der Krieger', 'Die Reise nach Westen', 'Das Buch der Götter']],
              ['Was war Murasaki Shikibu?', 'Eine Hofdame', ['Eine Kaiserin', 'Eine Nonne', 'Eine Kriegerin']],
              ['Was enthält das Kopfkissenbuch?', 'Listen und Beobachtungen aus dem Hofleben', ['Kriegsberichte', 'Gesetze', 'Rezepte für Sake']],
              ['In welchem Verhältnis standen Murasaki und Sei Shōnagon?', 'Sie waren Rivalinnen', ['Sie waren Schwestern', 'Sie waren Mutter und Tochter', 'Sie kannten sich nicht']],
              ['Was wechselten Adlige am Hof aus?', 'Gedichte', ['Waffen', 'Pferde', 'Münzen']],
              ['Wie heißt das Gewand mit zwölf Lagen?', 'Jūnihitoe', ['Kimono', 'Hakama', 'Yukata']],
              ['Welcher Glaube verbreitete sich in der Heian-Zeit?', 'Der Glaube an das Reine Land', ['Das Christentum', 'Zen', 'Der Islam']],
              ['Wann wurde der Phönix-Pavillon gebaut?', '1053', ['794', '1185', '1603']],
              ['Zu welchem Tempel gehört der Phönix-Pavillon?', 'Byōdō-in', ['Tōdai-ji', 'Hōryū-ji', 'Kinkaku-ji']],
              ['Was zeigt der Phönix-Pavillon?', 'Das Paradies des Reinen Landes', ['Eine Schlacht', 'Den Kaiserpalast', 'Den Berg Fuji']],
              ['Wovon waren die ländlichen Kriegerfamilien die Anfänge?', 'Der Samurai', ['Der Fujiwara', 'Der Mönche', 'Der Ainu']],
              ['Wann dauerte der Genpei-Krieg?', '1180–1185', ['794–894', '1274–1281', '1467–1477']],
              ['Wo vernichteten die Minamoto die Taira?', 'In der Seeschlacht von Dan-no-ura', ['Bei Sekigahara', 'Bei Nagashino', 'Bei Kyōto']],
              ['Welche Zeit endete 1185?', 'Die Heian-Zeit', ['Die Nara-Zeit', 'Die Edo-Zeit', 'Die Kamakura-Zeit']],
            ],
            schwer: [
              ['Welche Schrift entstand als Vereinfachung der Kanji für Japanisch?', 'Kana', ['Hangul', 'Romaji', 'Bopomofo']],
              ['Welche Familie beherrschte Kaiser durch Heiratspolitik?', 'Fujiwara', ['Minamoto', 'Taira', 'Ashikaga']],
              ['Welches Jahr beendete die offiziellen Gesandtschaften nach China?', '894', ['838', '960', '1185']],
              ['Welches Werk gilt als erster Roman der Welt?', 'Genji Monogatari', ['Kopfkissenbuch', 'Heike Monogatari', 'Kojiki']],
              ['Welche Seeschlacht beendete den Genpei-Krieg?', 'Dan-no-ura', ['Tsushima', 'Lepanto', 'Midway']],
              ['Welcher Tempel mit Phönix-Pavillon ist auf einer Münze?', 'Byōdō-in', ['Kinkaku-ji', 'Hōryū-ji', 'Tōdai-ji']],
              ['Welche Hofdame schrieb das Kopfkissenbuch?', 'Sei Shōnagon', ['Murasaki Shikibu', 'Izumi Shikibu', 'Ono no Komachi']],
              ['Welcher Fujiwara gilt als Höhepunkt der Familienmacht?', 'Michinaga', ['Kamatari', 'Yorimichi', 'Fuhito']],
              ['Welcher Krieg brachte die Samurai an die Macht?', 'Der Genpei-Krieg', ['Der Ōnin-Krieg', 'Der Boshin-Krieg', 'Der Imjin-Krieg']],
              ['Welche Schönheitssitte gab es für adlige Frauen?', 'Geschwärzte Zähne', ['Tätowierte Gesichter', 'Rasierte Köpfe', 'Goldene Fingernägel']],
              ['Welcher buddhistische Glaube versprach Wiedergeburt im Paradies?', 'Der Glaube an das Reine Land Amidas', ['Zen', 'Shintō-Ahnenkult', 'Nichiren']],
              ['Welcher Clan unterlag im Genpei-Krieg?', 'Die Taira', ['Die Minamoto', 'Die Hōjō', 'Die Fujiwara']],
              ['Wie viele Kaiser hatten Schwiegerväter aus Michinagas Haus?', 'Vier', ['Zwei', 'Sechs', 'Acht']],
              ['Welche Silbenschrift nutzten Hofdamen besonders?', 'Hiragana', ['Katakana', 'Kanji', 'Man’yōgana']],
              ['Welches Gewand trugen Hofdamen?', 'Jūnihitoe', ['Hakama', 'Haori', 'Kesa']],
              ['Welche Gruppe gewann auf dem Land an Macht, während der Hof feierte?', 'Kriegerfamilien', ['Händler aus China', 'Klöster in Korea', 'Hofdamen']],
              ['Wann wurde der Phönix-Pavillon errichtet?', '1053', ['1008', '1185', '894']],
              ['Welche Zeit gilt als Blüte der japanischen Hofkultur?', 'Die Heian-Zeit', ['Die Kamakura-Zeit', 'Die Edo-Zeit', 'Die Meiji-Zeit']],
              ['Welche Rolle hatten die Fujiwara formal?', 'Regenten', ['Shogune', 'Kaiser', 'Daimyō']],
              ['Wann schrieb Murasaki Shikibu ihr Werk etwa?', 'Um 1008', ['Um 794', 'Um 1185', 'Um 900']],
            ],
          },
        },
      ],
    },
  ],
};
