import type { Epoch } from '../types';

export const E2: Epoch = {
  id: 'samurai-zeit',
  name: 'Samurai und Shogune',
  period: '1185–1853',
  events: [
    {
      id: 'samurai',
      title: 'Samurai und Shogune',
      date: '1185–1853',
      text: [
        'Ab 1185 regierten Militärherrscher, die Shogune, während der Kaiser nur noch symbolische Macht hatte. Nach einem Jahrhundert der Bürgerkriege einten drei Feldherren das Land, und die Tokugawa-Shogune hielten Japan über 250 Jahre in Frieden – und weitgehend abgeschlossen von der Welt.',
      ],
      subtopics: [
        {
          id: 'kamakura-muromachi',
          title: 'Kamakura, Mongolen und Muromachi',
          date: '1185–1467',
          text: [
            'Nach dem Sieg im Genpei-Krieg errichtete Minamoto no Yoritomo in Kamakura eine Militärregierung, das „Bakufu“ („Zeltregierung“). 1192 ernannte ihn der Kaiser zum „Shōgun“ („Oberbefehlshaber“). Der Kaiser blieb in Kyōto, hatte aber kaum noch Macht. Nach Yoritomos Tod regierte die Familie Hōjō, die Familie seiner Frau Masako, als Regenten der Shogune.',
            'Die Samurai („Dienende“) bildeten einen Kriegerstand. Sie waren ihren Herren zu Treue verpflichtet und kämpften mit Bogen und dem gekrümmten Schwert „Katana“. Ihr Ehrenkodex wurde später „Bushidō“ („Weg des Kriegers“) genannt. Wer seine Ehre verlor, beging oft rituellen Selbstmord („Seppuku“). Der Zen-Buddhismus mit Meditation und Selbstdisziplin wurde bei den Samurai beliebt.',
            '1274 und 1281 versuchten die Mongolen unter Kublai Khan, Japan zu erobern. Beide Male zerstörten Taifune ihre Flotten vor Kyūshū; die Japaner nannten sie „Kamikaze“ („Göttlicher Wind“) und glaubten, die Götter schützten Japan. Die Kosten der Verteidigung schwächten jedoch das Kamakura-Shogunat.',
            '1333 stürzte Kaiser Go-Daigo die Hōjō und wollte selbst regieren, doch sein General Ashikaga Takauji wandte sich gegen ihn und wurde 1338 Shogun in Kyōto. Unter den Ashikaga (Muromachi-Zeit) gab es zeitweise zwei rivalisierende Kaiserhöfe. Shogun Ashikaga Yoshimitsu ließ den „Goldenen Pavillon“ (Kinkaku-ji) bauen.',
            'In der Muromachi-Zeit blühte die Kultur: das Nō-Theater mit Masken, die Teezeremonie, Steingärten wie im Ryōan-ji, Tuschmalerei und Blumenstecken (Ikebana). Doch die Macht der Shogune schwand, und regionale Fürsten, die „Daimyō“, wurden immer unabhängiger.',
          ],
          quiz: {
            leicht: [
              ['Wer errichtete 1185 eine Militärregierung?', 'Minamoto no Yoritomo', ['Oda Nobunaga', 'Tokugawa Ieyasu', 'Prinz Shōtoku']],
              ['In welcher Stadt war die erste Militärregierung?', 'In Kamakura', ['In Kyōto', 'In Edo', 'In Nara']],
              ['Wie heißt die Militärregierung?', 'Bakufu', ['Daimyō', 'Taika', 'Shintō']],
              ['Was bedeutet „Shōgun“?', 'Oberbefehlshaber', ['Kaiser', 'Mönch', 'Händler']],
              ['Wann wurde Yoritomo Shogun?', '1192', ['1185', '1338', '1603']],
              ['Welche Macht hatte der Kaiser nun?', 'Kaum noch Macht', ['Alle Macht', 'Die Macht über die Armee', 'Er wurde abgeschafft']],
              ['Welche Familie regierte nach Yoritomos Tod als Regenten?', 'Die Hōjō', ['Die Taira', 'Die Fujiwara', 'Die Tokugawa']],
              ['Was bedeutet „Samurai“?', 'Dienende', ['Herrscher', 'Mönche', 'Bauern']],
              ['Welches Schwert trugen Samurai?', 'Das Katana', ['Den Säbel', 'Das Rapier', 'Die Machete']],
              ['Wie heißt der Ehrenkodex der Samurai?', 'Bushidō', ['Shintō', 'Zen', 'Ikebana']],
              ['Was bedeutet „Bushidō“?', 'Weg des Kriegers', ['Weg des Tees', 'Weg der Götter', 'Weg der Blumen']],
              ['Wie heißt der rituelle Selbstmord der Samurai?', 'Seppuku', ['Kamikaze', 'Bushidō', 'Sumo']],
              ['Welche Form des Buddhismus wurde bei Samurai beliebt?', 'Der Zen-Buddhismus', ['Der tibetische Buddhismus', 'Der Shintō', 'Der Islam']],
              ['Wer versuchte 1274 und 1281, Japan zu erobern?', 'Die Mongolen', ['Die Chinesen der Ming', 'Die Portugiesen', 'Die Inder']],
              ['Was zerstörte die Mongolenflotten?', 'Taifune', ['Japanische Kanonen', 'Eisberge', 'Ein Vulkan']],
              ['Wie nannten die Japaner die Stürme?', 'Kamikaze', ['Tsunami', 'Bushidō', 'Shōgun']],
              ['Welcher Kaiser stürzte 1333 die Hōjō?', 'Go-Daigo', ['Meiji', 'Jimmu', 'Kanmu']],
              ['Wer wurde 1338 Shogun?', 'Ashikaga Takauji', ['Minamoto no Yoritomo', 'Oda Nobunaga', 'Toyotomi Hideyoshi']],
              ['Welchen Pavillon ließ Yoshimitsu bauen?', 'Den Goldenen Pavillon', ['Den Phönix-Pavillon', 'Die Burg Himeji', 'Den Tōdai-ji']],
              ['Wie hießen die regionalen Fürsten?', 'Daimyō', ['Shogune', 'Samurai', 'Ninja']],
            ],
            mittel: [
              ['Was bedeutet „Bakufu“?', 'Zeltregierung', ['Kaiserhof', 'Kriegerrat', 'Göttliche Regierung']],
              ['Wer war Yoritomos Frau, deren Familie später regierte?', 'Masako', ['Murasaki', 'Himiko', 'Suiko']],
              ['Als was regierten die Hōjō?', 'Als Regenten der Shogune', ['Als Kaiser', 'Als Mönche', 'Als Daimyō']],
              ['Wozu waren Samurai ihren Herren verpflichtet?', 'Zu Treue', ['Zu Steuern', 'Zu Gebeten', 'Zu nichts']],
              ['Womit kämpften Samurai außer dem Schwert?', 'Mit dem Bogen', ['Mit Gewehren', 'Mit Kanonen', 'Mit Speerwerfern']],
              ['Wann beging ein Samurai oft Seppuku?', 'Wenn er seine Ehre verlor', ['Bei jeder Hochzeit', 'Zu Neujahr', 'Nie']],
              ['Was betont der Zen-Buddhismus?', 'Meditation und Selbstdisziplin', ['Gesang und Tanz', 'Reichtum', 'Bilderverehrung']],
              ['Unter welchem Khan griffen die Mongolen an?', 'Kublai Khan', ['Dschingis Khan', 'Ögedei', 'Tamerlan']],
              ['Vor welcher Insel wurden die Mongolenflotten zerstört?', 'Vor Kyūshū', ['Vor Hokkaidō', 'Vor Shikoku', 'Vor Okinawa']],
              ['Was glaubten die Japaner wegen der Kamikaze?', 'Die Götter schützten Japan', ['Die Mongolen waren schwach', 'China half Japan', 'Nichts']],
              ['Was schwächte das Kamakura-Shogunat?', 'Die Kosten der Verteidigung', ['Ein Sieg über China', 'Zu viel Handel', 'Der Buddhismus']],
              ['Wann stürzte Go-Daigo die Hōjō?', '1333', ['1185', '1281', '1467']],
              ['Was tat Ashikaga Takauji?', 'Er wandte sich gegen Go-Daigo', ['Er unterstützte Go-Daigo bis zum Tod', 'Er floh nach China', 'Er wurde Mönch']],
              ['Wo regierten die Ashikaga-Shogune?', 'In Kyōto', ['In Kamakura', 'In Edo', 'In Osaka']],
              ['Wie heißt die Zeit der Ashikaga?', 'Muromachi-Zeit', ['Kamakura-Zeit', 'Edo-Zeit', 'Heian-Zeit']],
              ['Was gab es zeitweise in der Muromachi-Zeit?', 'Zwei rivalisierende Kaiserhöfe', ['Zwei Shogune in Edo', 'Keinen Kaiser', 'Einen Kaiser aus China']],
              ['Welches Theater entstand in der Muromachi-Zeit?', 'Nō-Theater', ['Musical', 'Oper', 'Puppentheater aus Europa']],
              ['Welcher Garten ist für Steine bekannt?', 'Ryōan-ji', ['Tōdai-ji', 'Byōdō-in', 'Hōryū-ji']],
              ['Wie heißt das japanische Blumenstecken?', 'Ikebana', ['Bonsai', 'Origami', 'Haiku']],
              ['Was geschah mit der Macht der Ashikaga-Shogune?', 'Sie schwand', ['Sie wuchs stark', 'Sie blieb gleich', 'Sie ging an China']],
            ],
            schwer: [
              ['Welcher Begriff bezeichnet die Militärregierung der Shogune?', 'Bakufu', ['Ritsuryō', 'Daijō-kan', 'Han']],
              ['Welche Familie regierte als Shogunatsregenten in Kamakura?', 'Hōjō', ['Ashikaga', 'Taira', 'Fujiwara']],
              ['Welcher Kaiser versuchte 1333 eine Restauration der Kaisermacht?', 'Go-Daigo', ['Go-Toba', 'Go-Shirakawa', 'Kōmei']],
              ['Welcher Shogun baute den Goldenen Pavillon?', 'Ashikaga Yoshimitsu', ['Ashikaga Takauji', 'Ashikaga Yoshimasa', 'Minamoto no Yoritomo']],
              ['Welches Jahr gilt als Beginn des Ashikaga-Shogunats?', '1338', ['1333', '1392', '1185']],
              ['Welche Theaterform mit Masken entstand in der Muromachi-Zeit?', 'Nō', ['Kabuki', 'Bunraku', 'Butoh']],
              ['Welche Kunstformen blühten in der Muromachi-Zeit?', 'Teezeremonie, Steingärten und Tuschmalerei', ['Holzschnitte und Romane', 'Fotografie', 'Ölmalerei']],
              ['Welche Folge hatten die Mongoleninvasionen für Kamakura?', 'Finanzielle Schwächung', ['Eroberung Koreas', 'Mehr Macht', 'Ende des Shintō']],
              ['Welcher Titel wurde Yoritomo 1192 verliehen?', 'Shōgun', ['Tennō', 'Kampaku', 'Daimyō']],
              ['Welches Schwert gilt als Symbol der Samurai?', 'Katana', ['Rapier', 'Naginata', 'Tantō']],
              ['Welche Religion prägte die Samurai-Geisteshaltung?', 'Zen', ['Christentum', 'Hinduismus', 'Daoismus']],
              ['Welche Gruppe wurde in der Muromachi-Zeit immer unabhängiger?', 'Die Daimyō', ['Die Kaiser', 'Die Hofdamen', 'Die Mongolen']],
              ['Welches Ereignis erklärte man mit göttlichem Schutz Japans?', 'Die Taifune gegen die Mongolen', ['Das Erdbeben von Kantō', 'Die Ankunft Perrys', 'Der Sieg von Sekigahara']],
              ['Welcher Ort war Hauptstadt der ersten Shogune?', 'Kamakura', ['Kyōto', 'Edo', 'Nara']],
              ['Welche Folge hatte Ashikaga Takaujis Verrat?', 'Spaltung in zwei Kaiserhöfe', ['Einigung Japans', 'Ende des Shogunats', 'Krieg mit China']],
              ['Welcher Garten ist berühmt für 15 Steine im Kies?', 'Ryōan-ji', ['Kenroku-en', 'Kōraku-en', 'Kairaku-en']],
              ['Welcher Shogun regierte als erster aus dem Haus Minamoto?', 'Yoritomo', ['Yoshitsune', 'Yoriie', 'Sanetomo']],
              ['Welche Zeit folgte auf die Kamakura-Zeit?', 'Die Muromachi-Zeit', ['Die Edo-Zeit', 'Die Heian-Zeit', 'Die Meiji-Zeit']],
              ['In welchen Jahren griffen die Mongolen Japan an?', '1274 und 1281', ['1185 und 1192', '1592 und 1597', '1333 und 1338']],
              ['Wie nennt man die Muromachi-Zeit nach der Familie der Shogune?', 'Ashikaga-Zeit', ['Hōjō-Zeit', 'Minamoto-Zeit', 'Tokugawa-Zeit']],
            ],
          },
        },
        {
          id: 'sengoku-einigung',
          title: 'Sengoku-Zeit und die drei Reichseiniger',
          date: '1467–1603',
          text: [
            'Der Ōnin-Krieg (1467–1477) zerstörte große Teile Kyōtos und leitete die „Sengoku-Zeit“ („Zeit der streitenden Reiche“) ein. Über ein Jahrhundert lang bekämpften sich Daimyō aus Burgen; Ninja dienten als Spione. 1543 strandeten Portugiesen auf der Insel Tanegashima und brachten Feuerwaffen mit, die Japaner schnell nachbauten. 1549 kam der Jesuit Franz Xaver und begann die Mission; Hunderttausende wurden Christen.',
            'Der erste Reichseiniger war Oda Nobunaga. 1560 besiegte er bei Okehazama ein viel größeres Heer, 1573 vertrieb er den letzten Ashikaga-Shogun. In der Schlacht von Nagashino 1575 setzte er Tausende Musketenschützen in Salven ein. Er bekämpfte mächtige buddhistische Klöster und brannte 1571 den Tempelberg Hiei nieder. 1582 wurde er von seinem General Akechi Mitsuhide im Tempel Honnō-ji verraten und beging Seppuku.',
            'Sein General Toyotomi Hideyoshi, der als Sohn eines einfachen Soldaten aufgestiegen war, rächte ihn und einte bis 1590 ganz Japan. Er ließ die Bauern entwaffnen („Schwertjagd“ 1588) und trennte die Stände streng. 1587 verbot er die christliche Mission, 1597 ließ er in Nagasaki 26 Christen kreuzigen. Er baute die Burg Osaka.',
            'Hideyoshi wollte auch China erobern und fiel 1592 und 1597 in Korea ein. Der koreanische Admiral Yi Sun-sin besiegte die japanische Flotte mit gepanzerten „Schildkrötenschiffen“, und chinesische Truppen halfen Korea. Nach Hideyoshis Tod 1598 zogen die Japaner ab.',
            'Danach kämpften die Daimyō um die Nachfolge. Am 21. Oktober 1600 siegte Tokugawa Ieyasu in der Schlacht von Sekigahara, einer der größten Schlachten der japanischen Geschichte. 1603 ernannte ihn der Kaiser zum Shogun; 1615 eroberte er die Burg Osaka und vernichtete die Toyotomi. Ein Sprichwort sagt: „Nobunaga mischte den Reiskuchen, Hideyoshi backte ihn, und Ieyasu aß ihn.“',
          ],
          quiz: {
            leicht: [
              ['Welcher Krieg leitete die Sengoku-Zeit ein?', 'Der Ōnin-Krieg', ['Der Genpei-Krieg', 'Der Boshin-Krieg', 'Der Pazifikkrieg']],
              ['Was bedeutet „Sengoku-Zeit“?', 'Zeit der streitenden Reiche', ['Zeit des Friedens', 'Zeit der Kaiser', 'Zeit der Blüte']],
              ['Wer kämpfte in der Sengoku-Zeit gegeneinander?', 'Die Daimyō', ['Kaiser und Papst', 'China und Korea', 'Mönche und Bauern']],
              ['Wer diente als Spione?', 'Ninja', ['Geishas', 'Sumo-Ringer', 'Kaiser']],
              ['Welche Europäer strandeten 1543 in Japan?', 'Portugiesen', ['Engländer', 'Niederländer', 'Russen']],
              ['Was brachten die Portugiesen mit?', 'Feuerwaffen', ['Kartoffeln', 'Tee', 'Seide']],
              ['Welcher Jesuit kam 1549 nach Japan?', 'Franz Xaver', ['Matteo Ricci', 'Ignatius von Loyola', 'Marco Polo']],
              ['Wer war der erste Reichseiniger?', 'Oda Nobunaga', ['Tokugawa Ieyasu', 'Toyotomi Hideyoshi', 'Minamoto no Yoritomo']],
              ['Was setzte Nobunaga bei Nagashino ein?', 'Musketenschützen in Salven', ['Kriegselefanten', 'Kanonenschiffe', 'Kampfhunde']],
              ['Was brannte Nobunaga 1571 nieder?', 'Den Tempelberg Hiei', ['Kyōto', 'Die Burg Osaka', 'Edo']],
              ['Wer verriet Nobunaga 1582?', 'Akechi Mitsuhide', ['Toyotomi Hideyoshi', 'Tokugawa Ieyasu', 'Takeda Shingen']],
              ['Wer einte bis 1590 ganz Japan?', 'Toyotomi Hideyoshi', ['Oda Nobunaga', 'Tokugawa Ieyasu', 'Kaiser Go-Daigo']],
              ['Wie heißt die Entwaffnung der Bauern?', 'Schwertjagd', ['Bauernkrieg', 'Kamikaze', 'Seppuku']],
              ['Was verbot Hideyoshi 1587?', 'Die christliche Mission', ['Den Buddhismus', 'Den Reisanbau', 'Den Handel mit China']],
              ['Welche Burg baute Hideyoshi?', 'Die Burg Osaka', ['Die Verbotene Stadt', 'Die Burg Edo', 'Die Burg Nijō']],
              ['Welches Land überfiel Hideyoshi 1592?', 'Korea', ['China direkt', 'Russland', 'Philippinen']],
              ['Welcher koreanische Admiral besiegte die japanische Flotte?', 'Yi Sun-sin', ['Sejong', 'Kim Il-sung', 'Wang Geon']],
              ['Mit welchen Schiffen siegte Yi Sun-sin?', 'Mit Schildkrötenschiffen', ['Mit Dampfschiffen', 'Mit U-Booten', 'Mit Drachenbooten']],
              ['Wer siegte 1600 bei Sekigahara?', 'Tokugawa Ieyasu', ['Toyotomi Hideyoshi', 'Oda Nobunaga', 'Ishida Mitsunari']],
              ['Wann wurde Ieyasu Shogun?', '1603', ['1600', '1615', '1590']],
            ],
            mittel: [
              ['Wann dauerte der Ōnin-Krieg?', '1467–1477', ['1180–1185', '1592–1598', '1868–1869']],
              ['Welche Stadt zerstörte der Ōnin-Krieg?', 'Kyōto', ['Edo', 'Nagasaki', 'Kamakura']],
              ['Wie lange dauerte die Sengoku-Zeit etwa?', 'Über ein Jahrhundert', ['Zehn Jahre', 'Drei Jahrhunderte', 'Ein Jahr']],
              ['Auf welcher Insel strandeten die Portugiesen?', 'Tanegashima', ['Okinawa', 'Hokkaidō', 'Sado']],
              ['Was taten die Japaner mit den Feuerwaffen?', 'Sie bauten sie schnell nach', ['Sie verboten sie sofort', 'Sie warfen sie ins Meer', 'Sie verkauften sie nach China']],
              ['Wie viele Japaner wurden Christen?', 'Hunderttausende', ['Niemand', 'Rund hundert', 'Alle']],
              ['Wo siegte Nobunaga 1560?', 'Bei Okehazama', ['Bei Sekigahara', 'Bei Nagashino', 'Bei Dan-no-ura']],
              ['Wen vertrieb Nobunaga 1573?', 'Den letzten Ashikaga-Shogun', ['Den Kaiser', 'Die Portugiesen', 'Hideyoshi']],
              ['Wann war die Schlacht von Nagashino?', '1575', ['1560', '1600', '1543']],
              ['Wen bekämpfte Nobunaga außer Daimyō?', 'Mächtige buddhistische Klöster', ['Die Portugiesen', 'Den Kaiser', 'Die Mongolen']],
              ['Wo wurde Nobunaga verraten?', 'Im Tempel Honnō-ji', ['In der Burg Osaka', 'In Edo', 'In Kamakura']],
              ['Woher stammte Hideyoshi?', 'Sohn eines einfachen Soldaten', ['Sohn des Kaisers', 'Sohn eines Shoguns', 'Sohn eines Portugiesen']],
              ['Wann fand die Schwertjagd statt?', '1588', ['1600', '1543', '1615']],
              ['Was ließ Hideyoshi 1597 in Nagasaki tun?', '26 Christen kreuzigen', ['Eine Kirche bauen', 'Eine Universität gründen', 'Einen Hafen schließen']],
              ['Was wollte Hideyoshi eigentlich erobern?', 'China', ['Indien', 'Russland', 'Australien']],
              ['Wer half Korea gegen Japan?', 'Chinesische Truppen', ['Die Mongolen', 'Die Portugiesen', 'Die Russen']],
              ['Wann zogen die Japaner aus Korea ab?', 'Nach Hideyoshis Tod 1598', ['1592', '1610', '1543']],
              ['An welchem Datum war die Schlacht von Sekigahara?', 'Am 21. Oktober 1600', ['Am 1. Januar 1603', 'Am 3. Juli 1853', 'Am 15. August 1600']],
              ['Wann vernichtete Ieyasu die Toyotomi?', '1615', ['1600', '1603', '1590']],
              ['Was sagt das Sprichwort über Ieyasu?', 'Er aß den Reiskuchen', ['Er backte ihn', 'Er mischte ihn', 'Er warf ihn weg']],
            ],
            schwer: [
              ['Welche Insel brachte Japan 1543 die Feuerwaffen?', 'Tanegashima', ['Dejima', 'Hirado', 'Iki']],
              ['Welche Schlacht von 1575 zeigte die Macht der Musketen?', 'Nagashino', ['Okehazama', 'Sekigahara', 'Kawanakajima']],
              ['In welchem Tempel starb Nobunaga 1582?', 'Honnō-ji', ['Enryaku-ji', 'Kinkaku-ji', 'Tōdai-ji']],
              ['Welcher General verriet Nobunaga?', 'Akechi Mitsuhide', ['Shibata Katsuie', 'Ishida Mitsunari', 'Uesugi Kenshin']],
              ['Welche Maßnahme Hideyoshis trennte Bauern und Krieger?', 'Die Schwertjagd', ['Die Taika-Reform', 'Die Sakoku-Politik', 'Die Meiji-Reform']],
              ['Welcher Admiral nutzte Schildkrötenschiffe?', 'Yi Sun-sin', ['Zheng He', 'Tōgō Heihachirō', 'Koxinga']],
              ['Welche Schlacht gilt als Entscheidung für die Tokugawa?', 'Sekigahara 1600', ['Nagashino 1575', 'Dan-no-ura 1185', 'Okehazama 1560']],
              ['Welcher Tempelberg wurde 1571 zerstört?', 'Hiei', ['Kōya', 'Fuji', 'Takao']],
              ['Welcher Jesuit begann 1549 die Mission?', 'Franz Xaver', ['Luís Fróis', 'Alessandro Valignano', 'Francisco Cabral']],
              ['Wie viele Christen wurden 1597 in Nagasaki gekreuzigt?', '26', ['6', '260', '2.600']],
              ['Welches Sprichwort beschreibt die drei Reichseiniger?', 'Nobunaga mischte, Hideyoshi backte, Ieyasu aß den Reiskuchen', ['Drei Brüder bauten eine Burg', 'Drei Samurai, ein Schwert', 'Drei Kaiser, ein Thron']],
              ['Welcher Reichseiniger stieg aus einfachen Verhältnissen auf?', 'Hideyoshi', ['Nobunaga', 'Ieyasu', 'Takeda Shingen']],
              ['In welchen Jahren fiel Japan in Korea ein?', '1592 und 1597', ['1274 und 1281', '1894 und 1904', '1543 und 1549']],
              ['Welche Burg war Stammsitz der Toyotomi?', 'Osaka', ['Edo', 'Himeji', 'Azuchi']],
              ['Welcher Shogun wurde 1573 abgesetzt?', 'Der letzte Ashikaga', ['Der letzte Tokugawa', 'Yoritomo', 'Der erste Hōjō']],
              ['Welche Zeit folgte auf die Sengoku-Zeit?', 'Die Edo-Zeit', ['Die Muromachi-Zeit', 'Die Heian-Zeit', 'Die Meiji-Zeit']],
              ['Welche Religion verbot Hideyoshi 1587?', 'Das Christentum', ['Den Buddhismus', 'Den Shintō', 'Den Konfuzianismus']],
              ['Welches Ereignis beendete die Toyotomi-Familie?', 'Die Eroberung der Burg Osaka 1615', ['Die Schlacht von Nagashino', 'Hideyoshis Tod', 'Der Ōnin-Krieg']],
              ['Welche Gruppe half Korea gegen Hideyoshi?', 'Die Ming-Chinesen', ['Die Mongolen', 'Die Mandschu', 'Die Portugiesen']],
              ['Welche Schlacht von 1560 machte Nobunaga bekannt?', 'Okehazama', ['Nagashino', 'Sekigahara', 'Mikatagahara']],
            ],
          },
        },
        {
          id: 'edo-zeit',
          title: 'Die Edo-Zeit',
          date: '1603–1853',
          text: [
            'Die Tokugawa-Shogune regierten von Edo (dem heutigen Tokio) aus über 250 Jahre lang, bis 1867. Diese Zeit war die längste Friedenszeit der japanischen Geschichte. Die Gesellschaft war streng in Stände geteilt: Samurai, Bauern, Handwerker und Kaufleute. Die Daimyō mussten im System des „Sankin-kōtai“ jedes zweite Jahr in Edo leben und ihre Familien dort als Geiseln lassen – teuer für sie, aber gut für Straßen und Handel.',
            'Ab 1633 isolierte sich Japan („Sakoku“, „abgeschlossenes Land“). Japaner durften das Land nicht verlassen, das Christentum wurde blutig unterdrückt – etwa nach dem Shimabara-Aufstand 1637/38 –, und Christen mussten auf Bilder von Jesus und Maria treten („Fumie“). Nur Chinesen und Niederländer durften handeln; die Niederländer auf der kleinen künstlichen Insel Dejima in Nagasaki. Über sie kam westliches Wissen („Rangaku“, „Hollandkunde“) ins Land.',
            'Edo wuchs um 1720 zu einer der größten Städte der Welt mit über einer Million Einwohnern. Die Kaufleute wurden reich und schufen eine eigene Stadtkultur: das Kabuki-Theater, das Puppentheater Bunraku, die Geishas und die Holzschnitte („Ukiyo-e“, „Bilder der fließenden Welt“). Hokusais „Die große Welle vor Kanagawa“ (um 1831) ist eines der bekanntesten Kunstwerke der Welt.',
            'Der Dichter Matsuo Bashō (1644–1694) machte das kurze Gedicht „Haiku“ mit 5-7-5 Silben berühmt, etwa sein Gedicht über den Frosch, der in den alten Teich springt. Die Samurai wurden in Friedenszeiten zu Beamten. Die Geschichte der „47 Rōnin“, die 1703 ihren Herrn rächten und dann Seppuku begingen, wurde zum Sinnbild der Treue.',
            'Im 19. Jahrhundert geriet das System in die Krise: Hungersnöte, Bauernaufstände und Schulden der Samurai schwächten das Shogunat. Gleichzeitig tauchten immer öfter westliche Schiffe vor der Küste auf. Im Juli 1853 lief der US-Kommodore Matthew Perry mit vier „Schwarzen Schiffen“ in die Bucht von Edo ein und verlangte die Öffnung Japans.',
          ],
          quiz: {
            leicht: [
              ['Von welcher Stadt aus regierten die Tokugawa?', 'Von Edo', ['Von Kyōto', 'Von Osaka', 'Von Nagasaki']],
              ['Wie heißt Edo heute?', 'Tokio', ['Kyōto', 'Osaka', 'Yokohama']],
              ['Wie lange regierten die Tokugawa etwa?', 'Über 250 Jahre', ['50 Jahre', '1.000 Jahre', '15 Jahre']],
              ['Was war die Edo-Zeit?', 'Die längste Friedenszeit Japans', ['Eine Zeit ständiger Kriege', 'Eine Zeit unter China', 'Eine Zeit unter Mongolen']],
              ['Welcher Stand stand ganz oben?', 'Die Samurai', ['Die Kaufleute', 'Die Bauern', 'Die Handwerker']],
              ['Wie heißt Japans Abschließung?', 'Sakoku', ['Bushidō', 'Sankin-kōtai', 'Meiji']],
              ['Was bedeutet „Sakoku“?', 'Abgeschlossenes Land', ['Offenes Land', 'Land der Sonne', 'Reich des Friedens']],
              ['Welche Religion wurde blutig unterdrückt?', 'Das Christentum', ['Der Buddhismus', 'Der Shintō', 'Der Konfuzianismus']],
              ['Welche Europäer durften als einzige handeln?', 'Die Niederländer', ['Die Portugiesen', 'Die Engländer', 'Die Spanier']],
              ['Auf welcher Insel handelten die Niederländer?', 'Dejima', ['Okinawa', 'Tanegashima', 'Hokkaidō']],
              ['In welcher Stadt lag Dejima?', 'In Nagasaki', ['In Edo', 'In Osaka', 'In Kyōto']],
              ['Wie viele Einwohner hatte Edo um 1720?', 'Über eine Million', ['Rund 10.000', 'Rund 100.000', 'Rund 10 Millionen']],
              ['Welches Theater entstand in der Edo-Zeit?', 'Kabuki', ['Oper aus Italien', 'Oper', 'Ballett']],
              ['Wie heißen die Holzschnitte der Edo-Zeit?', 'Ukiyo-e', ['Ikebana', 'Origami', 'Kanji']],
              ['Welches berühmte Bild schuf Hokusai?', '„Die große Welle vor Kanagawa“', ['„Die Sternennacht“', '„Mona Lisa“', '„Der Schrei“']],
              ['Welcher Dichter machte das Haiku berühmt?', 'Matsuo Bashō', ['Murasaki Shikibu', 'Hokusai', 'Yukio Mishima']],
              ['Wie viele Silben hat ein Haiku?', '5-7-5', ['7-7-7', '3-5-3', '10-10']],
              ['Wofür wurden die 47 Rōnin zum Sinnbild?', 'Für Treue', ['Für Verrat', 'Für Reichtum', 'Für Frieden']],
              ['Welcher US-Kommodore kam 1853?', 'Matthew Perry', ['Douglas MacArthur', 'George Dewey', 'Ulysses Grant']],
              ['Wie nannte man Perrys Schiffe?', 'Schwarze Schiffe', ['Weiße Schiffe', 'Rote Schiffe', 'Goldene Schiffe']],
            ],
            mittel: [
              ['Bis wann regierten die Tokugawa?', '1867', ['1853', '1603', '1912']],
              ['In welche Stände war die Gesellschaft geteilt?', 'Samurai, Bauern, Handwerker und Kaufleute', ['Kaiser, Mönche und Bauern', 'Adel und Bürger', 'Nur Krieger und Händler']],
              ['Wie heißt das System, das Daimyō nach Edo zwang?', 'Sankin-kōtai', ['Sakoku', 'Bakufu', 'Rangaku']],
              ['Wie oft mussten Daimyō in Edo leben?', 'Jedes zweite Jahr', ['Nie', 'Immer', 'Einmal im Leben']],
              ['Wen mussten die Daimyō in Edo lassen?', 'Ihre Familien als Geiseln', ['Ihre Pferde', 'Ihr Gold', 'Ihre Tempel']],
              ['Ab wann isolierte sich Japan?', 'Ab 1633', ['Ab 1543', 'Ab 1853', 'Ab 1603']],
              ['Welcher Aufstand 1637/38 war christlich geprägt?', 'Der Shimabara-Aufstand', ['Der Ōnin-Krieg', 'Der Satsuma-Aufstand', 'Der Boxeraufstand']],
              ['Was mussten Christen bei „Fumie“ tun?', 'Auf Bilder von Jesus und Maria treten', ['Beten', 'Eine Kirche bauen', 'Steuern zahlen']],
              ['Welche Asiaten durften außer den Niederländern handeln?', 'Die Chinesen', ['Die Inder', 'Die Russen', 'Die Thai']],
              ['Wie hieß das westliche Wissen über die Niederländer?', 'Rangaku', ['Kokugaku', 'Bushidō', 'Zen']],
              ['Was bedeutet „Rangaku“?', 'Hollandkunde', ['Kriegskunst', 'Teekunst', 'Götterkunde']],
              ['Was durften Japaner während Sakoku nicht?', 'Das Land verlassen', ['Reis essen', 'Tempel besuchen', 'Heiraten']],
              ['Welche Gruppe wurde in der Edo-Zeit reich?', 'Die Kaufleute', ['Die Bauern', 'Die Samurai', 'Die Mönche']],
              ['Welches Puppentheater entstand?', 'Bunraku', ['Nō', 'Kabuki', 'Kyōgen']],
              ['Was bedeutet „Ukiyo-e“?', 'Bilder der fließenden Welt', ['Bilder des Krieges', 'Bilder der Götter', 'Bilder des Kaisers']],
              ['Wann entstand Hokusais „Große Welle“ etwa?', 'Um 1831', ['Um 1631', 'Um 1931', 'Um 1731']],
              ['Wann lebte Bashō?', '1644–1694', ['1544–1594', '1744–1794', '1844–1894']],
              ['Worum geht es in Bashōs berühmtem Haiku?', 'Um einen Frosch und einen alten Teich', ['Um einen Samurai', 'Um den Berg Fuji', 'Um eine Seeschlacht']],
              ['Was wurden Samurai in Friedenszeiten?', 'Beamte', ['Bauern', 'Händler', 'Seeleute']],
              ['Wann rächten die 47 Rōnin ihren Herrn?', '1703', ['1603', '1853', '1600']],
            ],
            schwer: [
              ['Welcher Aufstand führte zur verschärften Christenverfolgung?', 'Der Shimabara-Aufstand', ['Der Ōnin-Krieg', 'Der Taiping-Aufstand', 'Der Ikkō-Aufstand']],
              ['Welche Insel in Nagasaki war Tor zum Westen?', 'Dejima', ['Hirado', 'Tsushima', 'Gotō']],
              ['Welches System schwächte die Daimyō finanziell?', 'Sankin-kōtai', ['Sakoku', 'Rangaku', 'Fumie']],
              ['Welcher Künstler schuf „Die große Welle vor Kanagawa“?', 'Hokusai', ['Picasso', 'Utamaro', 'Sharaku']],
              ['Welche Geschichte von 1703 symbolisiert Samurai-Treue?', 'Die 47 Rōnin', ['Die sieben Samurai', 'Die Heike-Geschichte', 'Das Genji Monogatari']],
              ['Welche Stadt war um 1720 eine der größten der Welt?', 'Edo', ['Kyōto', 'Osaka', 'Nagasaki']],
              ['Welche Silbenzahl hat ein Haiku insgesamt?', '17', ['31', '14', '21']],
              ['Welche Praxis diente der Entlarvung von Christen?', 'Fumie', ['Seppuku', 'Sankin-kōtai', 'Ikebana']],
              ['Welches Wissen gelangte über Dejima nach Japan?', 'Rangaku', ['Kokugaku', 'Shingaku', 'Mitogaku']],
              ['Welche Theaterform der Kaufleute entstand in der Edo-Zeit?', 'Kabuki', ['Nō', 'Gagaku', 'Sarugaku']],
              ['In welchem Jahr kam Perry?', '1853', ['1854', '1868', '1633']],
              ['Welche Probleme schwächten das Shogunat im 19. Jahrhundert?', 'Hungersnöte, Bauernaufstände und Samurai-Schulden', ['Ein Krieg mit China', 'Zu viel Silber', 'Die Mongolen']],
              ['In welche Bucht lief Perry ein?', 'In die Bucht von Edo', ['In die Bucht von Nagasaki', 'In die Bucht von Osaka', 'In die Bucht von Kobe']],
              ['Mit wie vielen Schiffen kam Perry 1853?', 'Vier', ['Eines', 'Zehn', 'Zwanzig']],
              ['Welche Nation war die einzige europäische Handelspartnerin Japans?', 'Die Niederlande', ['Portugal', 'England', 'Frankreich']],
              ['Welche Dichtform machte Bashō berühmt?', 'Haiku', ['Tanka', 'Sonett', 'Waka']],
              ['Welches Jahr markiert den Beginn von Sakoku etwa?', '1633', ['1603', '1868', '1543']],
              ['Welche Rolle hatten Geishas in der Edo-Kultur?', 'Unterhaltungskünstlerinnen der Stadtkultur', ['Kriegerinnen', 'Priesterinnen', 'Beamtinnen']],
              ['Welche Rolle spielten Samurai im Frieden?', 'Beamte', ['Händler', 'Bauern', 'Piraten']],
              ['Welche Familie regierte die Edo-Zeit?', 'Tokugawa', ['Toyotomi', 'Ashikaga', 'Minamoto']],
            ],
          },
        },
      ],
    },
  ],
};
