import type { Epoch, HistEvent } from '../types';
import { MEIJI } from './e3-meiji-event';

const KRIEG: HistEvent = {
  id: 'zweiter-weltkrieg',
  title: 'Militarismus und Zweiter Weltkrieg',
  date: '1926–1952',
  text: [
    'In den 1930er-Jahren übernahm das Militär die Macht. Japan eroberte große Teile Chinas und Südostasiens und griff 1941 Pearl Harbor an. Der Krieg endete 1945 mit den Atombomben auf Hiroshima und Nagasaki und der Besetzung Japans durch die USA.',
  ],
  subtopics: [
    {
      id: 'militarismus',
      title: 'Militarismus und Krieg in China',
      date: '1926–1941',
      text: [
        '1926 bestieg Kaiser Hirohito den Thron; seine Regierungszeit heißt „Shōwa“ („Erleuchteter Frieden“) und dauerte bis 1989. Die Weltwirtschaftskrise traf Japan ab 1929 hart, besonders die Bauern und die Seidenexporte. Viele Japaner verloren das Vertrauen in Parteien und Politiker, die als korrupt galten.',
        'Junge Offiziere und Nationalisten glaubten, Japan brauche Rohstoffe und Land auf dem Festland. 1931 sprengten Offiziere der Kwantung-Armee eine Eisenbahnlinie bei Mukden und gaben China die Schuld („Mukden-Zwischenfall“). Danach besetzte Japan die Mandschurei und gründete 1932 den Marionettenstaat Mandschukuo mit dem letzten chinesischen Kaiser Puyi. Als der Völkerbund das verurteilte, trat Japan 1933 aus.',
        'Im Inland ermordeten Militärs Politiker: 1932 wurde Premierminister Inukai Tsuyoshi erschossen. Beim Putschversuch vom 26. Februar 1936 töteten junge Offiziere mehrere Minister; der Putsch scheiterte, doch das Militär gewann danach noch mehr Einfluss. Die Parteien verloren ihre Macht, und Schulen lehrten absolute Treue zum göttlichen Kaiser.',
        'Nach einem Gefecht an der Marco-Polo-Brücke bei Peking im Juli 1937 begann der Krieg gegen ganz China. Japan eroberte Shanghai und die Hauptstadt Nanjing, wo seine Soldaten ab Dezember 1937 ein Massaker an Zivilisten und Gefangenen verübten. Die chinesische Regierung zog sich ins Landesinnere nach Chongqing zurück, und der Krieg wurde zu einem langen Zermürbungskrieg.',
        '1936 schloss Japan den Antikominternpakt mit Deutschland, 1940 den Dreimächtepakt mit Deutschland und Italien („Achse“). Japan verkündete eine „Großostasiatische Wohlstandssphäre“ unter seiner Führung und besetzte 1940/41 Französisch-Indochina. Daraufhin verhängten die USA 1941 ein Ölembargo – Japan bezog den Großteil seines Öls aus den USA. Die Führung unter Premier Tōjō Hideki entschied sich für den Krieg.',
      ],
      quiz: {
        leicht: [
          ['Wann bestieg Hirohito den Thron?', '1926', ['1912', '1945', '1868']],
          ['Wie heißt Hirohitos Regierungszeit?', 'Shōwa', ['Meiji', 'Taishō', 'Heisei']],
          ['Bis wann dauerte die Shōwa-Zeit?', '1989', ['1945', '1952', '2019']],
          ['Welche Krise traf Japan ab 1929?', 'Die Weltwirtschaftskrise', ['Die Ölkrise', 'Eine Hungersnot durch Krieg', 'Die Asienkrise']],
          ['Wer glaubte, Japan brauche Land auf dem Festland?', 'Junge Offiziere und Nationalisten', ['Die Bauern', 'Die Kaufleute in Osaka', 'Die Amerikaner']],
          ['Was sprengten Offiziere 1931 bei Mukden?', 'Eine Eisenbahnlinie', ['Eine Brücke in Tokio', 'Ein Schiff', 'Einen Palast']],
          ['Wem gaben sie die Schuld?', 'China', ['Russland', 'Korea', 'Den USA']],
          ['Welches Gebiet besetzte Japan 1931?', 'Die Mandschurei', ['Korea', 'Taiwan', 'Shanghai']],
          ['Welchen Marionettenstaat gründete Japan 1932?', 'Mandschukuo', ['Mongolei', 'Taiwan', 'Indochina']],
          ['Wer wurde Herrscher von Mandschukuo?', 'Puyi', ['Hirohito', 'Chiang Kai-shek', 'Mao']],
          ['Aus welcher Organisation trat Japan 1933 aus?', 'Aus dem Völkerbund', ['Aus der UNO', 'Aus der NATO', 'Aus dem Commonwealth']],
          ['Welcher Premierminister wurde 1932 erschossen?', 'Inukai Tsuyoshi', ['Tōjō Hideki', 'Itō Hirobumi', 'Yoshida Shigeru']],
          ['Wann scheiterte ein Putschversuch junger Offiziere?', 'Am 26. Februar 1936', ['Am 7. Dezember 1941', 'Am 15. August 1945', 'Am 1. September 1923']],
          ['Was lehrten Schulen in den 1930ern?', 'Absolute Treue zum göttlichen Kaiser', ['Demokratie', 'Pazifismus', 'Englisch als Hauptsprache']],
          ['Wo begann 1937 der Krieg gegen ganz China?', 'An der Marco-Polo-Brücke', ['In Shanghai', 'In Pearl Harbor', 'In Mukden']],
          ['Welche Hauptstadt eroberte Japan 1937?', 'Nanjing', ['Peking', 'Chongqing', 'Kanton']],
          ['Wohin zog sich Chinas Regierung zurück?', 'Nach Chongqing', ['Nach Taiwan', 'Nach Shanghai', 'Nach Hongkong']],
          ['Mit welchen Ländern schloss Japan 1940 den Dreimächtepakt?', 'Mit Deutschland und Italien', ['Mit den USA und Großbritannien', 'Mit China und Korea', 'Mit Russland und Frankreich']],
          ['Welches Embargo verhängten die USA 1941?', 'Ein Ölembargo', ['Ein Reisembargo', 'Ein Seidenembargo', 'Ein Teeembargo']],
          ['Welcher Premier entschied sich für den Krieg?', 'Tōjō Hideki', ['Inukai Tsuyoshi', 'Itō Hirobumi', 'Yoshida Shigeru']],
        ],
        mittel: [
          ['Was bedeutet „Shōwa“?', 'Erleuchteter Frieden', ['Großer Krieg', 'Neue Morgenröte', 'Ewige Sonne']],
          ['Wer litt besonders unter der Weltwirtschaftskrise?', 'Die Bauern und die Seidenexporte', ['Die Samurai', 'Die Kaiserfamilie', 'Die Ölindustrie']],
          ['Wie galten Parteien und Politiker?', 'Als korrupt', ['Als Helden', 'Als Götter', 'Als Militärs']],
          ['Welche Armee führte den Mukden-Zwischenfall herbei?', 'Die Kwantung-Armee', ['Die Kaiserliche Marine', 'Die chinesische Armee', 'Die US-Armee']],
          ['Wann trat Japan aus dem Völkerbund aus?', '1933', ['1931', '1937', '1941']],
          ['Warum trat Japan aus dem Völkerbund aus?', 'Er verurteilte die Besetzung der Mandschurei', ['Er wollte Japan beitreten lassen', 'Wegen hoher Beiträge', 'Wegen der Olympischen Spiele']],
          ['Was geschah nach dem Putschversuch 1936?', 'Das Militär gewann noch mehr Einfluss', ['Die Demokratie wurde gestärkt', 'Der Kaiser dankte ab', 'Japan wurde Republik']],
          ['Was verloren die Parteien in den 1930ern?', 'Ihre Macht', ['Ihre Namen', 'Ihre Mitglieder in China', 'Nichts']],
          ['Wann begann der Krieg gegen ganz China?', 'Im Juli 1937', ['Im September 1931', 'Im Dezember 1941', 'Im August 1945']],
          ['Welche Stadt eroberte Japan außer Nanjing?', 'Shanghai', ['Chongqing', 'Lhasa', 'Ürümqi']],
          ['Was geschah ab Dezember 1937 in Nanjing?', 'Ein Massaker an Zivilisten und Gefangenen', ['Ein Friedensschluss', 'Die Olympischen Spiele', 'Eine Volksabstimmung']],
          ['Was wurde der Krieg in China?', 'Ein langer Zermürbungskrieg', ['Ein schneller Sieg', 'Ein Bürgerkrieg in Japan', 'Ein Seekrieg']],
          ['Welchen Pakt schloss Japan 1936 mit Deutschland?', 'Den Antikominternpakt', ['Den Hitler-Stalin-Pakt', 'Den Warschauer Pakt', 'Den Dreimächtepakt']],
          ['Wie nannte man das Bündnis Deutschland–Italien–Japan?', 'Achse', ['Entente', 'Alliierte', 'Dreibund']],
          ['Welche Ordnung verkündete Japan für Asien?', 'Großostasiatische Wohlstandssphäre', ['Asiatische Union', 'Pazifische Gemeinschaft', 'Neue Seidenstraße']],
          ['Welches Gebiet besetzte Japan 1940/41?', 'Französisch-Indochina', ['Indien', 'Australien', 'Neuseeland']],
          ['Woher bezog Japan den Großteil seines Öls?', 'Aus den USA', ['Aus China', 'Aus Russland', 'Aus eigenen Quellen']],
          ['Wann wurde Mandschukuo gegründet?', '1932', ['1931', '1937', '1945']],
          ['Wann wurde der Dreimächtepakt geschlossen?', '1940', ['1936', '1941', '1933']],
          ['Wann wurde Premier Inukai ermordet?', '1932', ['1936', '1941', '1926']],
        ],
        schwer: [
          ['Welcher Zwischenfall von 1931 diente als Vorwand?', 'Mukden-Zwischenfall', ['Marco-Polo-Brücke', 'Tonkin-Zwischenfall', 'Gleiwitz']],
          ['Welcher Zwischenfall von 1937 löste den Krieg mit China aus?', 'Marco-Polo-Brücke', ['Mukden', 'Pearl Harbor', 'Nomonhan']],
          ['Welche Armee in der Mandschurei handelte eigenmächtig?', 'Kwantung-Armee', ['Kaiserliche Garde', 'Chinesische Nationalarmee', 'Rote Armee']],
          ['Welcher Putschversuch stärkte 1936 das Militär?', 'Der Februar-Putsch (26. Februar)', ['Der Mukden-Zwischenfall', 'Der Kyūjō-Zwischenfall', 'Der Satsuma-Aufstand']],
          ['Welcher Pakt von 1936 richtete sich gegen den Kommunismus?', 'Antikominternpakt', ['Dreimächtepakt', 'Nichtangriffspakt', 'Stahlpakt']],
          ['Welche Ideologie rechtfertigte Japans Expansion in Asien?', 'Großostasiatische Wohlstandssphäre', ['Panslawismus', 'Manifest Destiny', 'Lebensraum im Westen']],
          ['Welche Maßnahme der USA trieb Japan 1941 in den Krieg?', 'Das Ölembargo', ['Ein Reisboykott', 'Die Schließung des Panamakanals', 'Ein Krieg gegen Korea']],
          ['Welche Kolonie besetzte Japan vor Pearl Harbor in Südostasien?', 'Französisch-Indochina', ['Britisch-Indien', 'Niederländisch-Indien', 'Philippinen']],
          ['Welcher Premierminister wurde 1932 von Offizieren ermordet?', 'Inukai Tsuyoshi', ['Hara Takashi', 'Hamaguchi Osachi', 'Konoe Fumimaro']],
          ['Welche Stadt war Chinas Kriegshauptstadt?', 'Chongqing', ['Nanjing', 'Wuhan', 'Xi’an']],
          ['Welcher Kaiser regierte von 1926 bis 1989?', 'Hirohito', ['Yoshihito', 'Akihito', 'Mutsuhito']],
          ['Welche Organisation verurteilte die Besetzung der Mandschurei?', 'Der Völkerbund', ['Die UNO', 'Die NATO', 'Die Komintern']],
          ['Welcher Premier führte Japan 1941 in den Krieg?', 'Tōjō Hideki', ['Konoe Fumimaro', 'Inukai Tsuyoshi', 'Suzuki Kantarō']],
          ['Welcher letzte chinesische Kaiser wurde japanische Marionette?', 'Puyi', ['Guangxu', 'Yuan Shikai', 'Tongzhi']],
          ['Welches Bündnis bildete Japan 1940?', 'Die Achse mit Deutschland und Italien', ['Die Entente mit Frankreich', 'Ein Bündnis mit den USA', 'Ein Bündnis mit China']],
          ['Welche Exportbranche litt in der Krise besonders?', 'Seide', ['Autos', 'Elektronik', 'Öl']],
          ['Welche Folge hatte der Austritt aus dem Völkerbund?', 'Japans internationale Isolation', ['Japans Aufnahme in die NATO', 'Frieden mit China', 'Keine']],
          ['Was lehrte die Schule über den Kaiser?', 'Er sei göttlich und verdiene absolute Treue', ['Er sei ein gewählter Beamter', 'Er sei abzuschaffen', 'Er sei unwichtig']],
          ['Welches Ereignis machte den Krieg in China zum Großkrieg?', 'Der Zwischenfall 1937', ['Die Ölkrise', 'Der Tod Puyis', 'Die Olympiade 1940']],
          ['Welche Stadt am Jangtse wurde 1937 Schauplatz eines Massakers?', 'Nanjing', ['Wuhan', 'Chongqing', 'Shanghai']],
        ],
      },
    },
    {
      id: 'pazifikkrieg',
      title: 'Pazifikkrieg, Atombomben und Besatzung',
      date: '1941–1952',
      text: [
        'Am 7. Dezember 1941 griffen japanische Trägerflugzeuge unter dem Plan von Admiral Yamamoto Isoroku den US-Flottenstützpunkt Pearl Harbor auf Hawaii an; über 2.400 Amerikaner starben. Die USA traten in den Krieg ein. In wenigen Monaten eroberte Japan die Philippinen, Malaya, Singapur, Niederländisch-Indien (Indonesien) und Burma.',
        'Im Juni 1942 verlor Japan in der Seeschlacht bei Midway vier Flugzeugträger – die Wende im Pazifik. Die USA eroberten danach Insel um Insel („Inselspringen“), etwa Guadalcanal, Saipan, Iwo Jima und Okinawa. Ab 1944 flogen japanische „Kamikaze“-Piloten Selbstmordangriffe auf Schiffe. In den besetzten Gebieten verübte Japan schwere Verbrechen; Hunderttausende Frauen wurden als „Trostfrauen“ zur Prostitution gezwungen – ein Thema, das bis heute die Beziehungen zu Korea belastet.',
        'Ab 1944 bombardierten US-Flugzeuge japanische Städte; beim Brandangriff auf Tokio im März 1945 starben in einer Nacht rund 100.000 Menschen. Bei der Schlacht um Okinawa starben über 100.000 Zivilisten. Am 6. August 1945 warf ein US-Bomber die erste Atombombe auf Hiroshima, am 9. August die zweite auf Nagasaki. Insgesamt starben bis Ende 1945 über 200.000 Menschen. Am 8. August erklärte auch die Sowjetunion Japan den Krieg.',
        'Am 15. August 1945 verkündete Kaiser Hirohito im Radio die Kapitulation – die Menschen hörten zum ersten Mal seine Stimme. Am 2. September 1945 wurde sie auf dem US-Schlachtschiff Missouri in der Bucht von Tokio unterzeichnet. Rund drei Millionen Japaner waren im Krieg gestorben.',
        'Die USA unter General Douglas MacArthur besetzten Japan bis 1952. Der Kaiser erklärte 1946, er sei kein Gott, blieb aber im Amt. Die neue Verfassung von 1947 machte ihn zum „Symbol des Staates und der Einheit des Volkes“, gab Frauen das Wahlrecht und verbot in Artikel 9 den Krieg und eine Armee. Im Tokioter Prozess wurden Kriegsverbrecher wie Tōjō verurteilt und hingerichtet. Mit dem Friedensvertrag von San Francisco wurde Japan 1952 wieder souverän.',
      ],
      quiz: {
        leicht: [
          ['Wann griff Japan Pearl Harbor an?', 'Am 7. Dezember 1941', ['Am 6. August 1945', 'Am 1. September 1939', 'Am 15. August 1945']],
          ['Wo liegt Pearl Harbor?', 'Auf Hawaii', ['In Kalifornien', 'Auf den Philippinen', 'In Japan']],
          ['Welcher Admiral plante den Angriff?', 'Yamamoto Isoroku', ['Tōgō Heihachirō', 'Tōjō Hideki', 'Nimitz']],
          ['Was taten die USA nach Pearl Harbor?', 'Sie traten in den Krieg ein', ['Sie kapitulierten', 'Sie blieben neutral', 'Sie verbündeten sich mit Japan']],
          ['Welche britische Festung eroberte Japan?', 'Singapur', ['Gibraltar', 'Malta', 'Kapstadt']],
          ['Wo verlor Japan im Juni 1942 vier Flugzeugträger?', 'Bei Midway', ['Bei Pearl Harbor', 'Bei Tsushima', 'Bei Okinawa']],
          ['Was war Midway?', 'Die Wende im Pazifik', ['Japans größter Sieg', 'Ein Friedensvertrag', 'Eine Insel Japans']],
          ['Wie nennt man die US-Strategie, Insel um Insel zu erobern?', 'Inselspringen', ['Blitzkrieg', 'Grabenkrieg', 'Bodenoffensive']],
          ['Wie hießen die Selbstmordpiloten?', 'Kamikaze', ['Samurai', 'Ninja', 'Rōnin']],
          ['Wie nannte man zur Prostitution gezwungene Frauen?', 'Trostfrauen', ['Geishas', 'Hofdamen', 'Krankenschwestern']],
          ['Wann fiel die erste Atombombe?', 'Am 6. August 1945', ['Am 9. August 1945', 'Am 7. Dezember 1941', 'Am 15. August 1945']],
          ['Auf welche Stadt fiel die erste Atombombe?', 'Hiroshima', ['Nagasaki', 'Tokio', 'Kyōto']],
          ['Auf welche Stadt fiel die zweite Atombombe?', 'Nagasaki', ['Hiroshima', 'Osaka', 'Kobe']],
          ['Welches Land erklärte Japan am 8. August 1945 den Krieg?', 'Die Sowjetunion', ['China', 'Frankreich', 'Deutschland']],
          ['Wann verkündete Hirohito die Kapitulation?', 'Am 15. August 1945', ['Am 2. September 1945', 'Am 6. August 1945', 'Am 7. Dezember 1945']],
          ['Wie verkündete der Kaiser die Kapitulation?', 'Im Radio', ['Im Fernsehen', 'Durch Flugblätter', 'Im Parlament persönlich']],
          ['Auf welchem Schiff wurde die Kapitulation unterzeichnet?', 'Auf der USS Missouri', ['Auf der Yamato', 'Auf der Titanic', 'Auf der Bismarck']],
          ['Welcher US-General leitete die Besatzung?', 'Douglas MacArthur', ['Dwight Eisenhower', 'George Patton', 'Chester Nimitz']],
          ['Was erklärte der Kaiser 1946?', 'Er sei kein Gott', ['Er sei Präsident', 'Er trete zurück', 'Er sei unsterblich']],
          ['Was verbietet Artikel 9 der Verfassung?', 'Krieg und eine Armee', ['Den Kaiser', 'Wahlen', 'Den Buddhismus']],
        ],
        mittel: [
          ['Wie viele Amerikaner starben in Pearl Harbor?', 'Über 2.400', ['Rund 24', 'Rund 240', 'Über 24.000']],
          ['Welche Gebiete eroberte Japan in wenigen Monaten?', 'Philippinen, Malaya, Singapur, Indonesien und Burma', ['Indien und Australien', 'Hawaii und Alaska', 'China ganz']],
          ['Wie hieß Indonesien damals?', 'Niederländisch-Indien', ['Französisch-Indochina', 'Britisch-Malaya', 'Siam']],
          ['Wann war die Schlacht bei Midway?', 'Im Juni 1942', ['Im Dezember 1941', 'Im August 1945', 'Im Mai 1905']],
          ['Welche Inseln eroberten die USA?', 'Guadalcanal, Saipan, Iwo Jima und Okinawa', ['Kuba und Jamaika', 'Taiwan und Hainan', 'Sachalin und Kurilen']],
          ['Ab wann flogen Kamikaze-Piloten?', 'Ab 1944', ['Ab 1941', 'Ab 1942', 'Ab 1945 August']],
          ['Wie viele Trostfrauen gab es?', 'Hunderttausende', ['Einige Dutzend', 'Keine', 'Zehn Millionen']],
          ['Wann war der große Brandangriff auf Tokio?', 'Im März 1945', ['Im August 1945', 'Im Dezember 1941', 'Im Juni 1942']],
          ['Wie viele Menschen starben beim Brandangriff auf Tokio?', 'Rund 100.000', ['Rund 1.000', 'Rund 10.000', 'Rund eine Million']],
          ['Wie viele Zivilisten starben auf Okinawa?', 'Über 100.000', ['Rund 1.000', 'Rund 10.000', 'Niemand']],
          ['Wann fiel die Bombe auf Nagasaki?', 'Am 9. August 1945', ['Am 6. August 1945', 'Am 15. August 1945', 'Am 2. September 1945']],
          ['Wie viele Menschen starben bis Ende 1945 durch die Atombomben?', 'Über 200.000', ['Rund 2.000', 'Rund 20.000', 'Über zwei Millionen']],
          ['Was war besonders an der Radioansprache des Kaisers?', 'Die Menschen hörten zum ersten Mal seine Stimme', ['Sie war auf Englisch', 'Sie dauerte zehn Stunden', 'Sie war gefälscht']],
          ['Wann wurde die Kapitulation unterzeichnet?', 'Am 2. September 1945', ['Am 15. August 1945', 'Am 8. Mai 1945', 'Am 1. Januar 1946']],
          ['Wie viele Japaner starben im Krieg etwa?', 'Rund drei Millionen', ['Rund 300.000', 'Rund 30 Millionen', 'Rund 30.000']],
          ['Bis wann besetzten die USA Japan?', '1952', ['1945', '1972', '1960']],
          ['Wann trat die neue Verfassung in Kraft?', '1947', ['1945', '1952', '1889']],
          ['Was ist der Kaiser laut Verfassung von 1947?', 'Symbol des Staates', ['Oberbefehlshaber', 'Gott', 'Präsident']],
          ['Wer wurde im Tokioter Prozess hingerichtet?', 'Tōjō', ['Hirohito', 'MacArthur', 'Yamamoto']],
          ['Mit welchem Vertrag wurde Japan 1952 souverän?', 'Friedensvertrag von San Francisco', ['Vertrag von Portsmouth', 'Vertrag von Versailles', 'Vertrag von Kanagawa']],
        ],
        schwer: [
          ['Welche Schlacht kostete Japan 1942 vier Flugzeugträger?', 'Midway', ['Korallenmeer', 'Leyte', 'Guadalcanal']],
          ['Welcher Admiral plante Pearl Harbor?', 'Yamamoto Isoroku', ['Nagumo Chūichi', 'Tōgō Heihachirō', 'Halsey']],
          ['Welcher Artikel der Verfassung verbietet den Krieg?', 'Artikel 9', ['Artikel 1', 'Artikel 20', 'Artikel 99']],
          ['Welcher Luftangriff tötete in einer Nacht rund 100.000 Menschen?', 'Der Brandangriff auf Tokio im März 1945', ['Die Bombe auf Nagasaki', 'Pearl Harbor', 'Der Angriff auf Osaka 1944']],
          ['Welcher Prozess verurteilte japanische Kriegsverbrecher?', 'Der Tokioter Prozess', ['Die Nürnberger Prozesse', 'Der Dreyfus-Prozess', 'Der Prozess von Den Haag']],
          ['Welches Schiff war Ort der Kapitulationsunterzeichnung?', 'USS Missouri', ['USS Arizona', 'Yamato', 'USS Enterprise']],
          ['Welches Ereignis am 8. August 1945 verschlimmerte Japans Lage?', 'Die Kriegserklärung der Sowjetunion', ['Die Kapitulation Deutschlands', 'Pearl Harbor', 'Ein Erdbeben']],
          ['Welche Schlacht forderte über 100.000 zivile Opfer auf japanischem Boden?', 'Okinawa', ['Iwo Jima', 'Midway', 'Saipan']],
          ['Welche Erklärung gab der Kaiser 1946 ab?', 'Er sei kein lebender Gott', ['Er trete zurück', 'Er werde Präsident', 'Er führe neuen Krieg']],
          ['Welches Recht erhielten Frauen mit der Verfassung von 1947?', 'Das Wahlrecht', ['Das Recht auf Waffen', 'Das Recht, Kaiserin zu werden', 'Keines']],
          ['Welcher Vertrag beendete die Besatzung 1952?', 'Friedensvertrag von San Francisco', ['Vertrag von Tokio', 'Potsdamer Abkommen', 'Vertrag von Washington']],
          ['Welche Kampfweise setzte Japan ab 1944 gegen Schiffe ein?', 'Kamikaze-Selbstmordangriffe', ['U-Boot-Rudel', 'Atombomben', 'Giftgas']],
          ['Welches Thema belastet bis heute die Beziehungen zu Korea?', 'Die Trostfrauen', ['Die Olympischen Spiele', 'Der Teehandel', 'Der Shintō']],
          ['Welche Strategie verfolgten die USA im Pazifik?', 'Inselspringen', ['Blitzkrieg', 'Grabenkrieg', 'Belagerung Tokios zu Land']],
          ['Wie viele Tage lagen zwischen den beiden Atombomben?', 'Drei', ['Einer', 'Zehn', 'Dreißig']],
          ['Welcher US-General wurde De-facto-Herrscher Japans?', 'MacArthur', ['Nimitz', 'Truman', 'Eisenhower']],
          ['Welche Stellung erhielt der Kaiser 1947?', 'Symbol des Staates und der Einheit des Volkes', ['Oberbefehlshaber', 'Premierminister', 'Keiner']],
          ['Welche Gebiete gehörten zu Japans Eroberungen 1942?', 'Malaya, Singapur und Burma', ['Indien und Ceylon', 'Australien und Neuseeland', 'Alaska und Hawaii']],
          ['Wann wurde Japan wieder souverän?', '1952', ['1947', '1945', '1956']],
          ['Wie viele Japaner kamen im Zweiten Weltkrieg insgesamt um?', 'Rund drei Millionen', ['Rund eine Million', 'Rund zehn Millionen', 'Rund 500.000']],
        ],
      },
    },
  ],
};

export const E3: Epoch = {
  id: 'modernisierung',
  name: 'Modernisierung und Krieg',
  period: '1853–1952',
  events: [MEIJI, KRIEG],
};
