import type { HistEvent } from '../types';

export const MEIJI: HistEvent = {
  id: 'meiji',
  title: 'Öffnung und Meiji-Restauration',
  date: '1853–1926',
  text: [
    'Nach Perrys Ankunft brach das Shogunat zusammen. Unter Kaiser Meiji modernisierte sich Japan in wenigen Jahrzehnten nach westlichem Vorbild und wurde die erste nicht-westliche Großmacht – mit Siegen über China und Russland und eigenen Kolonien.',
  ],
  subtopics: [
    {
      id: 'perry-meiji',
      title: 'Perry, Bakumatsu und Meiji-Restauration',
      date: '1853–1889',
      text: [
        'Perry kehrte 1854 mit einer größeren Flotte zurück und erzwang den Vertrag von Kanagawa, der zwei Häfen für amerikanische Schiffe öffnete. Bald folgten „ungleiche Verträge“ mit den USA, Großbritannien, Russland, den Niederlanden und Frankreich: Ausländer unterstanden nicht japanischen Gerichten, und Japan durfte seine Zölle nicht selbst festlegen.',
        'Viele Samurai waren empört, dass der Shogun nachgab. Unter dem Ruf „Ehrt den Kaiser, vertreibt die Barbaren!“ („Sonnō jōi“) griffen sie Ausländer an. Als die Fürstentümer Satsuma und Chōshū 1863/64 von westlichen Kriegsschiffen beschossen wurden, erkannten sie, dass Japan sich erst modernisieren musste. Sie verbündeten sich gegen das Shogunat.',
        '1867 gab der letzte Shogun Tokugawa Yoshinobu seine Macht an den Kaiser zurück. Am 3. Januar 1868 wurde die „Meiji-Restauration“ verkündet: Der 15-jährige Kaiser Mutsuhito, genannt Meiji („Aufgeklärte Herrschaft“), regierte nun dem Namen nach selbst. Im Boshin-Krieg (1868–1869) wurden die letzten Anhänger des Shogunats besiegt. Der Kaiser zog nach Edo, das in Tokio („Östliche Hauptstadt“) umbenannt wurde.',
        'Mit dem Motto „Reiches Land, starke Armee“ setzten die Reformer gewaltige Veränderungen durch: 1871 wurden die Fürstentümer durch Präfekturen ersetzt, 1872 die Schulpflicht eingeführt und die erste Eisenbahn zwischen Tokio und Yokohama eröffnet, 1873 die allgemeine Wehrpflicht. Die Samurai verloren ihre Vorrechte und durften ab 1876 keine Schwerter mehr tragen. 1877 rebellierte Saigō Takamori im Satsuma-Aufstand, doch die neue Wehrpflichtarmee siegte – das Ende der Samurai.',
        'Die „Iwakura-Mission“ bereiste 1871–1873 die USA und Europa, um von westlichen Staaten zu lernen. Japan holte Tausende ausländische Fachleute, baute Fabriken, Werften und ein Bankensystem auf. 1889 erhielt Japan nach preußischem Vorbild eine Verfassung mit Parlament (Reichstag), in der der Kaiser jedoch „heilig und unverletzlich“ war und den Oberbefehl über das Militär hatte.',
      ],
      quiz: {
        leicht: [
          ['Wann kehrte Perry mit größerer Flotte zurück?', '1854', ['1853', '1868', '1889']],
          ['Welcher Vertrag öffnete 1854 Häfen?', 'Der Vertrag von Kanagawa', ['Der Vertrag von Nanking', 'Der Vertrag von Portsmouth', 'Der Vertrag von Shimonoseki']],
          ['Für wessen Schiffe öffnete der Vertrag Häfen?', 'Für amerikanische', ['Für chinesische', 'Für indische', 'Für koreanische']],
          ['Wie nennt man die Verträge mit westlichen Mächten?', 'Ungleiche Verträge', ['Freundschaftsverträge', 'Friedensverträge', 'Bündnisverträge']],
          ['Wie lautete der Ruf der empörten Samurai?', '„Ehrt den Kaiser, vertreibt die Barbaren!“', ['„Reiches Land, starke Armee“', '„Banzai!“', '„Öffnet die Häfen!“']],
          ['Welche Fürstentümer verbündeten sich gegen das Shogunat?', 'Satsuma und Chōshū', ['Edo und Kyōto', 'Osaka und Nagasaki', 'Tosa und Mito']],
          ['Was erkannten Satsuma und Chōshū nach dem Beschuss?', 'Japan musste sich modernisieren', ['Japan war unbesiegbar', 'Der Westen war schwach', 'Man musste kapitulieren']],
          ['Wer war der letzte Shogun?', 'Tokugawa Yoshinobu', ['Tokugawa Ieyasu', 'Oda Nobunaga', 'Saigō Takamori']],
          ['Wann gab der letzte Shogun die Macht zurück?', '1867', ['1853', '1889', '1603']],
          ['Wie heißt die Wende von 1868?', 'Meiji-Restauration', ['Taika-Reform', 'Sengoku', 'Sakoku']],
          ['Was bedeutet „Meiji“?', 'Aufgeklärte Herrschaft', ['Großer Krieg', 'Sonnenkaiser', 'Neues Land']],
          ['Wie alt war Kaiser Meiji 1868?', '15', ['5', '35', '50']],
          ['In welchem Krieg wurden die Anhänger des Shogunats besiegt?', 'Im Boshin-Krieg', ['Im Genpei-Krieg', 'Im Ōnin-Krieg', 'Im Opiumkrieg']],
          ['Wie wurde Edo umbenannt?', 'Tokio', ['Kyōto', 'Osaka', 'Yokohama']],
          ['Was bedeutet „Tokio“?', 'Östliche Hauptstadt', ['Westliche Hauptstadt', 'Stadt des Kaisers', 'Stadt des Friedens']],
          ['Wie lautete das Motto der Reformer?', '„Reiches Land, starke Armee“', ['„Ehrt den Kaiser“', '„Land und Freiheit“', '„Ordnung und Fortschritt“']],
          ['Wodurch wurden die Fürstentümer 1871 ersetzt?', 'Durch Präfekturen', ['Durch Bundesländer', 'Durch Kolonien', 'Durch Klöster']],
          ['Welche erste Eisenbahn wurde 1872 eröffnet?', 'Tokio–Yokohama', ['Tokio–Osaka', 'Kyōto–Nara', 'Nagasaki–Kobe']],
          ['Was durften Samurai ab 1876 nicht mehr?', 'Schwerter tragen', ['Heiraten', 'Lesen', 'Reis essen']],
          ['Nach welchem Vorbild entstand die Verfassung von 1889?', 'Nach preußischem Vorbild', ['Nach amerikanischem Vorbild', 'Nach britischem Vorbild', 'Nach chinesischem Vorbild']],
        ],
        mittel: [
          ['Wie viele Häfen öffnete der Vertrag von Kanagawa?', 'Zwei', ['Fünf', 'Zehn', 'Einen']],
          ['Was durfte Japan wegen der ungleichen Verträge nicht?', 'Seine Zölle selbst festlegen', ['Handeln', 'Schiffe bauen', 'Einen Kaiser haben']],
          ['Wem unterstanden Ausländer nicht?', 'Japanischen Gerichten', ['Ihren Konsuln', 'Ihren Kapitänen', 'Ihren Kirchen']],
          ['Wie heißt der Ruf „Ehrt den Kaiser, vertreibt die Barbaren“ auf Japanisch?', 'Sonnō jōi', ['Fukoku kyōhei', 'Bushidō', 'Banzai']],
          ['Wann wurden Satsuma und Chōshū beschossen?', '1863/64', ['1853', '1877', '1894']],
          ['Wann wurde die Meiji-Restauration verkündet?', 'Am 3. Januar 1868', ['Am 1. Januar 1900', 'Am 15. August 1868', 'Am 3. Juli 1853']],
          ['Wie hieß Kaiser Meiji mit Vornamen?', 'Mutsuhito', ['Hirohito', 'Akihito', 'Yoshihito']],
          ['Wann dauerte der Boshin-Krieg?', '1868–1869', ['1877', '1894–1895', '1904–1905']],
          ['Wann wurde die Schulpflicht eingeführt?', '1872', ['1868', '1889', '1900']],
          ['Wann wurde die allgemeine Wehrpflicht eingeführt?', '1873', ['1868', '1889', '1904']],
          ['Wer rebellierte 1877?', 'Saigō Takamori', ['Tokugawa Yoshinobu', 'Itō Hirobumi', 'Perry']],
          ['Wie heißt der Aufstand von 1877?', 'Satsuma-Aufstand', ['Boshin-Krieg', 'Shimabara-Aufstand', 'Chōshū-Krieg']],
          ['Wer siegte 1877?', 'Die neue Wehrpflichtarmee', ['Die Samurai', 'Die Shogunatsanhänger', 'Die Amerikaner']],
          ['Was bedeutete der Sieg von 1877?', 'Das Ende der Samurai', ['Die Rückkehr des Shogunats', 'Die Unabhängigkeit Satsumas', 'Nichts']],
          ['Welche Mission bereiste den Westen 1871–1873?', 'Die Iwakura-Mission', ['Die Perry-Mission', 'Die Macartney-Mission', 'Die Marco-Polo-Mission']],
          ['Was holte Japan zum Lernen ins Land?', 'Tausende ausländische Fachleute', ['Keine Ausländer', 'Nur Missionare', 'Nur Soldaten']],
          ['Was erhielt Japan 1889?', 'Eine Verfassung mit Parlament', ['Eine Republik', 'Einen neuen Shogun', 'Eine Kolonie']],
          ['Wie war der Kaiser laut Verfassung?', '„Heilig und unverletzlich“', ['Gewählt', 'Machtlos ohne Titel', 'Abgeschafft']],
          ['Wer hatte den Oberbefehl über das Militär?', 'Der Kaiser', ['Das Parlament', 'Der Shogun', 'Die USA']],
          ['Wie hieß das japanische Parlament?', 'Reichstag', ['Senat', 'Duma', 'Kongress']],
        ],
        schwer: [
          ['Welche zwei Fürstentümer führten die Meiji-Restauration an?', 'Satsuma und Chōshū', ['Aizu und Mito', 'Ezo und Ryūkyū', 'Kaga und Owari']],
          ['Welcher Satsuma-Samurai führte 1877 den letzten Samurai-Aufstand?', 'Saigō Takamori', ['Ōkubo Toshimichi', 'Kido Takayoshi', 'Sakamoto Ryōma']],
          ['Welcher Vertrag von 1854 beendete Japans Abschließung?', 'Kanagawa', ['Nanking', 'Harris', 'Edo']],
          ['Welche Mission von 1871–1873 studierte den Westen?', 'Iwakura-Mission', ['Perry-Expedition', 'Tenshō-Gesandtschaft', 'Keichō-Gesandtschaft']],
          ['Welches Motto beschreibt die Meiji-Modernisierung?', 'Fukoku kyōhei – reiches Land, starke Armee', ['Sonnō jōi', 'Sakoku', 'Hakkō ichiu']],
          ['Welcher Krieg 1868/69 sicherte die Kaisermacht?', 'Boshin-Krieg', ['Satsuma-Aufstand', 'Genpei-Krieg', 'Ōnin-Krieg']],
          ['Welche Verwaltungseinheiten ersetzten 1871 die Han?', 'Präfekturen', ['Provinzen', 'Kantone', 'Bundesländer']],
          ['Welches Land war Vorbild der Meiji-Verfassung?', 'Preußen', ['Großbritannien', 'Frankreich', 'USA']],
          ['Welche Stellung hatte der Kaiser in der Verfassung von 1889?', 'Heilig, unverletzlich und Oberbefehlshaber', ['Symbol ohne Macht', 'Gewählter Präsident', 'Abgesetzt']],
          ['Welcher Shogun beendete 1867 die Tokugawa-Herrschaft?', 'Yoshinobu', ['Iemochi', 'Ieyasu', 'Iemitsu']],
          ['Welche zwei Städte verband die erste Eisenbahn?', 'Tokio und Yokohama', ['Kyōto und Osaka', 'Kobe und Osaka', 'Tokio und Kyōto']],
          ['Welche Reform entmachtete die Samurai als Krieger?', 'Die allgemeine Wehrpflicht 1873', ['Die Schulpflicht', 'Die Eisenbahn', 'Die Verfassung']],
          ['Welches Verbot von 1876 traf die Samurai symbolisch?', 'Das Schwertverbot', ['Das Zopfverbot', 'Das Teeverbot', 'Das Reisverbot']],
          ['Welcher Kaiser regierte ab 1868?', 'Meiji', ['Taishō', 'Shōwa', 'Kōmei']],
          ['Welche Folge hatten die ungleichen Verträge für die Wirtschaft?', 'Japan konnte Zölle nicht selbst bestimmen', ['Japan durfte nicht exportieren', 'Japan musste Gold zahlen', 'Keine']],
          ['Welche Stadt wurde 1868 kaiserliche Hauptstadt?', 'Tokio', ['Kyōto', 'Osaka', 'Kamakura']],
          ['Welches Ereignis überzeugte Satsuma und Chōshū von der Modernisierung?', 'Der Beschuss durch westliche Kriegsschiffe', ['Ein Erdbeben', 'Ein Sieg über China', 'Die Ankunft der Mongolen']],
          ['Welche Bildungsreform kam 1872?', 'Die Schulpflicht', ['Das Verbot aller Schulen', 'Die Abschaffung der Schrift', 'Das Englischverbot']],
          ['Wie lange dauerte es von Perry bis zur Verfassung?', 'Rund 36 Jahre', ['Rund 6 Jahre', 'Rund 100 Jahre', 'Rund 60 Jahre']],
          ['Welcher Begriff bezeichnet die Rückgabe der Macht an den Kaiser?', 'Restauration', ['Revolution', 'Reformation', 'Rebellion']],
        ],
      },
    },
    {
      id: 'imperialismus',
      title: 'Aufstieg zur Großmacht',
      date: '1894–1926',
      text: [
        'Japan wollte wie die westlichen Mächte Kolonien gewinnen. Im Ersten Japanisch-Chinesischen Krieg (1894–1895) ging es um Einfluss in Korea. Japans moderne Armee und Flotte besiegten China schnell. Im Vertrag von Shimonoseki erhielt Japan Taiwan und eine hohe Entschädigung; Korea wurde formal unabhängig von China.',
        'Russland, Frankreich und Deutschland zwangen Japan, die Halbinsel Liaodong mit Port Arthur zurückzugeben – Russland pachtete sie dann selbst. Japan fühlte sich durch diese „Tripel-Intervention“ gedemütigt. 1902 schloss es ein Bündnis mit Großbritannien, das erste gleichberechtigte Bündnis eines asiatischen Staates mit einer westlichen Großmacht.',
        'Im Russisch-Japanischen Krieg (1904–1905) eroberte Japan Port Arthur, und Admiral Tōgō Heihachirō vernichtete im Mai 1905 in der Seeschlacht von Tsushima die russische Ostseeflotte, die um die halbe Welt gesegelt war. Es war der erste Sieg einer asiatischen Macht über eine europäische Großmacht in der Neuzeit. Der Friede von Portsmouth, vermittelt von US-Präsident Theodore Roosevelt, der dafür den Friedensnobelpreis erhielt, gab Japan Südsachalin und Rechte in der Mandschurei.',
        '1910 annektierte Japan Korea und herrschte dort bis 1945 hart: Koreaner mussten später japanische Namen annehmen, und ihre Sprache wurde in Schulen unterdrückt. Inzwischen hatte Japan die ungleichen Verträge abgeschüttelt. Kaiser Meiji starb 1912; es folgte die „Taishō-Zeit“ (1912–1926) mit mehr Demokratie, Parteien und 1925 dem allgemeinen Wahlrecht für Männer.',
        'Im Ersten Weltkrieg trat Japan auf Seiten der Alliierten ein, eroberte 1914 die deutsche Kolonie Tsingtau (Qingdao) in China und deutsche Inseln im Pazifik wie die Marianen und Karolinen. 1919 saß Japan als Großmacht in Versailles. Am 1. September 1923 zerstörte das Große Kantō-Erdbeben Tokio und Yokohama; über 100.000 Menschen starben, und im Chaos wurden Tausende Koreaner ermordet.',
      ],
      quiz: {
        leicht: [
          ['Worum ging es im Krieg gegen China 1894–1895?', 'Um Einfluss in Korea', ['Um Indien', 'Um Hongkong', 'Um die Mongolei']],
          ['Wer gewann den Krieg 1894–1895?', 'Japan', ['China', 'Korea', 'Russland']],
          ['Welche Insel erhielt Japan 1895?', 'Taiwan', ['Hainan', 'Okinawa', 'Sachalin']],
          ['Welcher Vertrag beendete den Krieg 1895?', 'Der Vertrag von Shimonoseki', ['Der Vertrag von Portsmouth', 'Der Vertrag von Kanagawa', 'Der Vertrag von Nanking']],
          ['Welche Halbinsel musste Japan zurückgeben?', 'Liaodong', ['Korea', 'Kamtschatka', 'Shandong']],
          ['Welches Land pachtete Port Arthur danach selbst?', 'Russland', ['Deutschland', 'Frankreich', 'Großbritannien']],
          ['Mit welchem Land schloss Japan 1902 ein Bündnis?', 'Mit Großbritannien', ['Mit Russland', 'Mit Deutschland', 'Mit China']],
          ['Gegen welches Land kämpfte Japan 1904–1905?', 'Gegen Russland', ['Gegen China', 'Gegen die USA', 'Gegen Korea']],
          ['Welcher Admiral siegte bei Tsushima?', 'Tōgō Heihachirō', ['Yamamoto Isoroku', 'Perry', 'Yi Sun-sin']],
          ['Welche Flotte wurde bei Tsushima vernichtet?', 'Die russische Ostseeflotte', ['Die britische Flotte', 'Die chinesische Flotte', 'Die amerikanische Flotte']],
          ['Was war der Sieg über Russland historisch?', 'Erster Sieg einer asiatischen Macht über eine europäische Großmacht in der Neuzeit', ['Japans erste Niederlage', 'Ein Unentschieden', 'Ein Sieg Chinas']],
          ['Welcher US-Präsident vermittelte den Frieden 1905?', 'Theodore Roosevelt', ['Abraham Lincoln', 'Woodrow Wilson', 'Franklin D. Roosevelt']],
          ['Wann annektierte Japan Korea?', '1910', ['1895', '1905', '1945']],
          ['Bis wann herrschte Japan über Korea?', '1945', ['1919', '1950', '1910']],
          ['Was mussten Koreaner später annehmen?', 'Japanische Namen', ['Chinesische Namen', 'Christliche Namen', 'Nichts']],
          ['Wann starb Kaiser Meiji?', '1912', ['1889', '1926', '1945']],
          ['Welche Zeit folgte auf Meiji?', 'Die Taishō-Zeit', ['Die Shōwa-Zeit', 'Die Edo-Zeit', 'Die Heisei-Zeit']],
          ['Auf welcher Seite trat Japan in den Ersten Weltkrieg ein?', 'Auf Seiten der Alliierten', ['Auf Seiten Deutschlands', 'Es blieb neutral', 'Auf Seiten der Osmanen']],
          ['Welche deutsche Kolonie eroberte Japan 1914?', 'Tsingtau', ['Kamerun', 'Togo', 'Deutsch-Südwestafrika']],
          ['Was zerstörte 1923 Tokio und Yokohama?', 'Das Große Kantō-Erdbeben', ['Ein Bombenangriff', 'Ein Krieg', 'Ein Vulkan']],
        ],
        mittel: [
          ['Was erhielt Japan 1895 außer Taiwan?', 'Eine hohe Entschädigung', ['Shanghai', 'Peking', 'Nichts']],
          ['Was wurde Korea 1895 formal?', 'Unabhängig von China', ['Japanische Kolonie', 'Russische Provinz', 'Chinesische Provinz']],
          ['Welche drei Mächte zwangen Japan zur Rückgabe von Liaodong?', 'Russland, Frankreich und Deutschland', ['USA, Großbritannien und China', 'Italien, Spanien und Portugal', 'Korea, China und Russland']],
          ['Welche Hafenstadt lag auf Liaodong?', 'Port Arthur', ['Wladiwostok', 'Shanghai', 'Pusan']],
          ['Was war am Bündnis von 1902 besonders?', 'Erstes gleichberechtigtes Bündnis Asien–Westen', ['Es war ein ungleicher Vertrag', 'Es richtete sich gegen Großbritannien', 'Es war geheim']],
          ['Welche Stadt eroberte Japan 1904/05?', 'Port Arthur', ['Moskau', 'Wladiwostok', 'Harbin']],
          ['Wann war die Seeschlacht von Tsushima?', 'Im Mai 1905', ['Im Dezember 1941', 'Im Juni 1942', 'Im August 1894']],
          ['Wie weit war die russische Flotte gesegelt?', 'Um die halbe Welt', ['Nur von Wladiwostok', 'Gar nicht', 'Um Afrika und zurück nach Hause']],
          ['Wo wurde der Friede 1905 geschlossen?', 'In Portsmouth', ['In Tokio', 'In Moskau', 'In Paris']],
          ['Was erhielt Japan 1905?', 'Südsachalin und Rechte in der Mandschurei', ['Ganz Sibirien', 'Wladiwostok', 'Alaska']],
          ['Was wurde in Korea in Schulen unterdrückt?', 'Die koreanische Sprache', ['Die japanische Sprache', 'Mathematik', 'Sport']],
          ['Was hatte Japan bis etwa 1911 abgeschüttelt?', 'Die ungleichen Verträge', ['Den Kaiser', 'Die Verfassung', 'Die Armee']],
          ['Wann dauerte die Taishō-Zeit?', '1912–1926', ['1868–1912', '1926–1989', '1603–1868']],
          ['Was kennzeichnete die Taishō-Zeit?', 'Mehr Demokratie und Parteien', ['Militärdiktatur', 'Abschließung', 'Bürgerkrieg']],
          ['Wann erhielten alle Männer das Wahlrecht?', '1925', ['1889', '1945', '1912']],
          ['Welche Gebiete eroberte Japan im Ersten Weltkrieg außer Tsingtau?', 'Deutsche Inseln im Pazifik', ['Indien', 'Australien', 'Hawaii']],
          ['Wo saß Japan 1919 als Großmacht?', 'In Versailles', ['In Genf', 'In Washington', 'In Moskau']],
          ['Wann ereignete sich das Kantō-Erdbeben?', 'Am 1. September 1923', ['Am 1. Januar 1923', 'Am 11. März 2011', 'Am 17. Januar 1995']],
          ['Wie viele Menschen starben beim Kantō-Erdbeben?', 'Über 100.000', ['Rund 1.000', 'Rund 10.000', 'Über eine Million']],
          ['Wer wurde im Chaos nach dem Beben ermordet?', 'Tausende Koreaner', ['Tausende Amerikaner', 'Niemand', 'Tausende Samurai']],
        ],
        schwer: [
          ['Welcher Vertrag gab Japan 1895 Taiwan?', 'Shimonoseki', ['Portsmouth', 'Kanagawa', 'Versailles']],
          ['Welche Intervention von 1895 demütigte Japan?', 'Die Tripel-Intervention', ['Die Boxer-Intervention', 'Die Perry-Intervention', 'Die Washington-Konferenz']],
          ['Welche Seeschlacht machte Admiral Tōgō berühmt?', 'Tsushima', ['Midway', 'Dan-no-ura', 'Leyte']],
          ['Welcher Friedensvertrag brachte Roosevelt den Friedensnobelpreis?', 'Portsmouth 1905', ['Shimonoseki 1895', 'Versailles 1919', 'San Francisco 1951']],
          ['Welche Insel wurde 1905 teilweise japanisch?', 'Sachalin', ['Kamtschatka', 'Taiwan', 'Hainan']],
          ['Welches Land wurde 1910 annektiert?', 'Korea', ['Taiwan', 'Mandschurei', 'Philippinen']],
          ['Welches Bündnis machte Japan 1902 zum Partner einer Weltmacht?', 'Das britisch-japanische Bündnis', ['Der Dreibund', 'Die Achse', 'Die Entente']],
          ['Welche deutsche Kolonie in China fiel 1914 an Japan?', 'Tsingtau (Qingdao)', ['Shanghai', 'Port Arthur', 'Tianjin']],
          ['Welche Ära war von „Taishō-Demokratie“ geprägt?', '1912–1926', ['1868–1912', '1926–1945', '1945–1952']],
          ['Welches Jahr brachte das allgemeine Männerwahlrecht?', '1925', ['1919', '1889', '1946']],
          ['Welche Katastrophe von 1923 zerstörte Tokio?', 'Das Große Kantō-Erdbeben', ['Der Ausbruch des Fuji', 'Der Brand von Meireki', 'Ein Taifun']],
          ['Welche Gruppe wurde nach dem Kantō-Beben verfolgt?', 'Koreaner', ['Franzosen', 'Amerikaner', 'Ainu']],
          ['Welcher Krieg brachte Japan Rechte in der Mandschurei?', 'Der Russisch-Japanische Krieg', ['Der Erste Weltkrieg', 'Der Boshin-Krieg', 'Der Boxerkrieg']],
          ['Welche Festung fiel 1905 nach langer Belagerung?', 'Port Arthur', ['Sewastopol', 'Wladiwostok', 'Moskau']],
          ['Wie behandelte Japan die koreanische Kultur?', 'Es unterdrückte Sprache und Namen', ['Es förderte sie', 'Es ignorierte sie', 'Es übernahm sie']],
          ['Welches Ereignis von 1919 zeigte Japans Großmachtstatus?', 'Die Teilnahme in Versailles', ['Die Olympischen Spiele', 'Der Beitritt zur NATO', 'Die Annexion Chinas']],
          ['Welcher Kaiser starb 1912?', 'Meiji', ['Taishō', 'Kōmei', 'Shōwa']],
          ['Welches Kriegsziel hatte Japan 1894?', 'Einfluss in Korea', ['Eroberung Pekings', 'Eroberung Russlands', 'Öffnung Chinas für Europa']],
          ['Welche Pazifikgebiete gewann Japan von Deutschland?', 'Deutsche Inseln wie Marianen und Karolinen', ['Hawaii', 'Neuseeland', 'Philippinen']],
          ['Welche Flotte segelte bis Tsushima um die halbe Welt?', 'Die russische Ostseeflotte', ['Die britische Mittelmeerflotte', 'Die deutsche Hochseeflotte', 'Die US-Pazifikflotte']],
        ],
      },
    },
  ],
};
