import type { Epoch } from '../types';

export const E1: Epoch = {
  id: 'fruehzeit',
  name: 'Vorzeit und Svear',
  period: 'bis 800',
  events: [
    {
      id: 'vorzeit',
      title: 'Von der Eiszeit zu den Svear',
      date: '12.000 v. Chr.–800 n. Chr.',
      text: [
        'Nach der Eiszeit wanderten Jäger in das eisfreie Land, später kamen Ackerbau, Bronze und Eisen. Felsbilder, Großsteingräber und Bootgräber erzählen von dieser Zeit. Um Uppsala herrschten die Svear, nach denen Schweden benannt ist.',
      ],
      subtopics: [
        {
          id: 'steinzeit-bronzezeit',
          title: 'Eiszeit, Steinzeit und Bronzezeit',
          date: '12.000–500 v. Chr.',
          text: [
            'Während der letzten Eiszeit lag ganz Skandinavien unter einem kilometerdicken Eispanzer. Um 12.000 v. Chr. zog sich das Eis zurück, und die ersten Jäger folgten den Rentierherden in den Süden des heutigen Schweden, nach Schonen. Weil das schwere Eis verschwand, hob sich das Land – und es hebt sich bis heute, an der „Hohen Küste“ im Norden um fast einen Zentimeter pro Jahr.',
            'Um 4000 v. Chr. kamen Ackerbau und Viehzucht aus dem Süden nach Schweden. Die ersten Bauern töpferten Gefäße mit trichterförmigem Hals, weshalb man von der „Trichterbecherkultur“ spricht. Sie errichteten Großsteingräber aus riesigen Steinblöcken, Dolmen und Ganggräber, bei denen ein Gang in die Grabkammer führt, besonders viele davon in Västergötland. Um 2800 v. Chr. folgte die Streitaxtkultur, benannt nach ihren sorgfältig geschliffenen Steinäxten.',
            'Um 1700 v. Chr. begann die Bronzezeit. Bronze, eine Mischung aus Kupfer und Zinn, gab es in Schweden nicht; sie wurde im Tausch gegen Bernstein, versteinertes Baumharz, und Pelze eingeführt. Aus dieser Zeit stammen die Felsritzungen von Tanum in Bohuslän, die zum UNESCO-Welterbe gehören: Tausende Bilder von Schiffen, Menschen, Tieren und Sonnenscheiben. In Schonen liegt das Königsgrab von Kivik, ein riesiger Steinhügel mit bemalten Steinplatten.',
            'Schiffe spielten in der Religion eine große Rolle; vermutlich glaubten die Menschen, dass die Sonne in einem Schiff über den Himmel fuhr. Aus Bronze fertigten sie Luren, lange gebogene Blasinstrumente, die oft paarweise gefunden werden. Die Toten wurden zuerst unter großen Hügeln begraben, später verbrannt.',
            'Um 500 v. Chr. wurde das Klima kühler und feuchter, und die Eisenzeit begann. Eisen konnte man im Land selbst gewinnen, aus Raseneisenerz, das sich in Sümpfen bildet. Die Menschen lebten in Langhäusern, in denen Familie und Vieh unter einem Dach wohnten.',
          ],
          quiz: {
            leicht: [
              ['Was bedeckte Skandinavien während der Eiszeit?', 'Ein kilometerdicker Eispanzer', ['Ein großer Wald', 'Das Meer', 'Eine Wüste']],
              ['Um wann zog sich das Eis aus Südschweden zurück?', 'Um 12.000 v. Chr.', ['Um 1.200 v. Chr.', 'Um 120.000 v. Chr.', 'Um 500 n. Chr.']],
              ['Welchen Tieren folgten die ersten Jäger?', 'Rentieren', ['Elefanten', 'Kamelen', 'Pferden']],
              ['In welche Landschaft kamen die ersten Jäger?', 'Nach Schonen', ['Nach Lappland', 'Nach Gotland', 'Nach Uppland']],
              ['Was geschieht seit der Eiszeit mit dem Land in Schweden?', 'Es hebt sich', ['Es sinkt ins Meer', 'Es bleibt gleich', 'Es wandert nach Süden']],
              ['Wann kamen Ackerbau und Viehzucht nach Schweden?', 'Um 4000 v. Chr.', ['Um 12.000 v. Chr.', 'Um 500 v. Chr.', 'Um 800 n. Chr.']],
              ['Wie heißt die Kultur der ersten Bauern?', 'Trichterbecherkultur', ['Glockenbecherkultur', 'Wikingerkultur', 'Bronzekultur']],
              ['Woraus bauten die ersten Bauern ihre Gräber?', 'Aus riesigen Steinblöcken', ['Aus Holz', 'Aus Ziegeln', 'Aus Eis']],
              ['Wann begann in Schweden die Bronzezeit?', 'Um 1700 v. Chr.', ['Um 4000 v. Chr.', 'Um 500 v. Chr.', 'Um 800 n. Chr.']],
              ['Woraus besteht Bronze?', 'Aus Kupfer und Zinn', ['Aus Eisen und Kohle', 'Aus Gold und Silber', 'Aus Blei und Zink']],
              ['Wogegen tauschten die Menschen Bronze ein?', 'Gegen Bernstein und Pelze', ['Gegen Gold und Gewürze', 'Gegen Salz und Tee', 'Gegen Seide']],
              ['Wo gibt es berühmte Felsritzungen?', 'In Tanum', ['In Stockholm', 'In Uppsala', 'In Kiruna']],
              ['Was zeigen die Felsritzungen von Tanum oft?', 'Schiffe, Menschen, Tiere und Sonnen', ['Burgen und Ritter', 'Schrift und Zahlen', 'Landkarten']],
              ['Was sind Luren?', 'Blasinstrumente aus Bronze', ['Schwerter', 'Schiffe', 'Grabhügel']],
              ['Wie werden Luren oft gefunden?', 'Paarweise', ['Einzeln in Kirchen', 'In Hunderter-Gruppen', 'Nur in Seen']],
              ['Wann begann die Eisenzeit in Schweden?', 'Um 500 v. Chr.', ['Um 1700 v. Chr.', 'Um 4000 v. Chr.', 'Um 1000 n. Chr.']],
              ['Woraus gewann man in Schweden Eisen?', 'Aus Raseneisenerz aus Sümpfen', ['Aus Meteoriten', 'Aus Importen aus Rom', 'Aus Bernstein']],
              ['In welchen Häusern lebten die Menschen der Eisenzeit?', 'In Langhäusern', ['In Hochhäusern', 'In Iglus', 'In Burgen']],
              ['Wer wohnte im Langhaus unter einem Dach?', 'Familie und Vieh', ['Nur der König', 'Nur Krieger', 'Nur Priester']],
              ['Wo liegt das Königsgrab von Kivik?', 'In Schonen', ['In Lappland', 'Auf Gotland', 'In Stockholm']],
            ],
            mittel: [
              ['Wie stark hebt sich die „Hohe Küste“ heute noch?', 'Um fast einen Zentimeter pro Jahr', ['Um einen Meter pro Jahr', 'Gar nicht mehr', 'Um einen Kilometer pro Jahrhundert']],
              ['Warum hebt sich das Land in Schweden?', 'Das schwere Eis ist verschwunden', ['Vulkane drücken es hoch', 'Das Meer trocknet aus', 'Erdbeben schieben es an']],
              ['Woher kamen Ackerbau und Viehzucht nach Schweden?', 'Aus dem Süden', ['Aus dem Norden', 'Aus Amerika', 'Aus Island']],
              ['Woher hat die Trichterbecherkultur ihren Namen?', 'Von Gefäßen mit trichterförmigem Hals', ['Von einem Ort namens Trichter', 'Von Trinkhörnern', 'Von Grabformen']],
              ['Welche Gräber errichteten die ersten Bauern?', 'Dolmen und Ganggräber', ['Pyramiden', 'Katakomben', 'Mausoleen']],
              ['In welcher Landschaft gibt es besonders viele Großsteingräber?', 'In Västergötland', ['In Lappland', 'Auf Gotland', 'In Norrland']],
              ['Wann begann die Streitaxtkultur?', 'Um 2800 v. Chr.', ['Um 4000 v. Chr.', 'Um 1700 v. Chr.', 'Um 500 v. Chr.']],
              ['Wonach ist die Streitaxtkultur benannt?', 'Nach geschliffenen Steinäxten', ['Nach Bronzeäxten', 'Nach einem Kriegsgott', 'Nach einer Burg']],
              ['Warum musste Bronze eingeführt werden?', 'Es gab in Schweden kein Kupfer und Zinn', ['Bronze war verboten', 'Die Schweden konnten nicht schmieden', 'Bronze schmolz im Winter']],
              ['In welcher Landschaft liegt Tanum?', 'In Bohuslän', ['In Schonen', 'In Uppland', 'In Lappland']],
              ['Zu welchem Erbe gehören die Felsritzungen von Tanum?', 'Zum UNESCO-Welterbe', ['Zum Erbe der Wikinger in Norwegen', 'Zu einem Freilichtmuseum in Dänemark', 'Zu keinem']],
              ['Was ist das Königsgrab von Kivik?', 'Ein riesiger Steinhügel mit bemalten Platten', ['Eine Pyramide', 'Ein Schiffsgrab', 'Eine Burg']],
              ['Was glaubten die Menschen der Bronzezeit vermutlich über die Sonne?', 'Dass sie in einem Schiff über den Himmel fuhr', ['Dass sie ein Gott aus Eis war', 'Dass sie nie unterging', 'Dass sie aus Bronze bestand']],
              ['Welche Rolle spielten Schiffe in der Bronzezeit?', 'Eine große Rolle in der Religion', ['Gar keine', 'Nur im Krieg gegen Rom', 'Sie waren verboten']],
              ['Wie bestattete man die Toten zuerst?', 'Unter großen Hügeln', ['Im Meer', 'In Kirchen', 'In Höhlen im Eis']],
              ['Wie bestattete man die Toten später in der Bronzezeit?', 'Man verbrannte sie', ['Man mumifizierte sie', 'Man legte sie in Schiffe aufs Meer', 'Man begrub sie in Kirchen']],
              ['Wie veränderte sich das Klima um 500 v. Chr.?', 'Es wurde kühler und feuchter', ['Es wurde heißer und trockener', 'Es blieb gleich', 'Es kam eine neue Eiszeit']],
              ['Wo bildet sich Raseneisenerz?', 'In Sümpfen', ['In Vulkanen', 'Im Meer', 'In Wüsten']],
              ['Welche Form haben Luren?', 'Lang und gebogen', ['Kurz und gerade', 'Rund wie eine Trommel', 'Flach wie eine Harfe']],
              ['Was ist ein Dolmen?', 'Ein Großsteingrab', ['Ein Bronzeschild', 'Ein Blasinstrument', 'Ein Langhaus']],
            ],
            schwer: [
              ['Wie heißt die Küste im Norden, die sich besonders stark hebt?', 'Hohe Küste', ['Goldküste', 'Westküste', 'Bernsteinküste']],
              ['Wie dick war das Eis während der Eiszeit?', 'Kilometerdick', ['Einen Meter dick', 'Zehn Zentimeter dick', 'So dünn wie Papier']],
              ['Welche Kultur folgte auf die Trichterbecherkultur?', 'Die Streitaxtkultur', ['Die Wikingerkultur', 'Die Vendelkultur', 'Die Bronzekultur der Römer']],
              ['Was ist ein Ganggrab?', 'Ein Großsteingrab mit Gang zur Grabkammer', ['Ein Gang unter einer Burg', 'Ein Bergwerk', 'Eine Straße der Wikinger']],
              ['Woher kamen die Rohstoffe für Bronze?', 'Aus dem Ausland', ['Aus Lappland', 'Aus Gotland', 'Aus Stockholm']],
              ['Was sind Sonnenscheiben auf den Felsbildern?', 'Zeichen der Sonne', ['Münzen', 'Schilde der Römer', 'Mühlsteine']],
              ['Was ist das Besondere am Grab von Kivik?', 'Bemalte Steinplatten', ['Ein goldenes Dach', 'Eine Schrift in Latein', 'Ein Schiff aus Eisen']],
              ['Welche Tiere jagten die ersten Menschen in Südschweden vor allem?', 'Rentiere', ['Bären auf Gotland', 'Wale', 'Mammuts in Lappland']],
              ['Welche Folge hatte das kühlere Klima um 500 v. Chr.?', 'Die Eisenzeit begann', ['Die Menschen verließen Schweden', 'Die Bronzezeit begann', 'Das Land versank']],
              ['Was ist Raseneisenerz?', 'Eisenerz, das sich in Sümpfen bildet', ['Eisen aus Meteoriten', 'Eisen aus dem Meer', 'Ein Bronzeerz']],
              ['Was war an Eisen anders als an Bronze?', 'Man konnte es im Land selbst gewinnen', ['Es war teurer', 'Es kam aus Rom', 'Es war weicher']],
              ['Welche Gegenstände sind aus der Bronzezeit besonders bekannt?', 'Luren', ['Runensteine', 'Wikingerschiffe', 'Münzen']],
              ['Wie wurden die Toten in der frühen Bronzezeit begraben?', 'Unter großen Hügeln', ['In Booten', 'In Mooren', 'Auf Bäumen']],
              ['Welche Wirtschaftsform kam um 4000 v. Chr. neu?', 'Ackerbau und Viehzucht', ['Handel mit Rom', 'Bergbau', 'Fischerei']],
              ['Welches Material ist Bernstein?', 'Versteinertes Baumharz', ['Ein Metall', 'Ein Edelstein aus Afrika', 'Getrocknetes Salz']],
              ['Was folgte der Eiszeit in Schweden zuerst?', 'Die Einwanderung von Jägern', ['Der Bau von Städten', 'Die Ankunft der Römer', 'Die Wikingerzeit']],
              ['Wie viele Felsbilder gibt es in Tanum ungefähr?', 'Tausende', ['Zehn', 'Hundert', 'Millionen']],
              ['Was vermischte man für Bronze?', 'Kupfer und Zinn', ['Eisen und Zinn', 'Gold und Kupfer', 'Silber und Blei']],
              ['Wo wohnte das Vieh in der Eisenzeit?', 'Mit der Familie im Langhaus', ['In eigenen Steinställen', 'Im Wald', 'Auf Inseln']],
              ['Was zeigen die Großsteingräber über die ersten Bauern?', 'Sie bauten Monumente aus riesigen Steinen', ['Sie lebten in Höhlen', 'Sie kannten das Eisen', 'Sie fuhren zur See nach Amerika']],
            ],
          },
        },
        {
          id: 'eisenzeit-svear',
          title: 'Römer, Gold und die Svear',
          date: '500 v. Chr.–800 n. Chr.',
          text: [
            'In der Römischen Eisenzeit hatten die Völker Skandinaviens Kontakt zum Römischen Reich; sie tauschten Waren gegen Glas, Bronzegefäße und römische Silbermünzen, Denare. Um 98 n. Chr. erwähnte der römische Geschichtsschreiber Tacitus in seinem Werk „Germania“ die „Suionen“, die mit ihren Flotten mächtig seien – gemeint waren die Svear. Von ihnen hat Schweden seinen Namen: „Svea rike“, das „Reich der Svear“, wurde zu „Sverige“.',
            'In der Völkerwanderungszeit (um 400–550), als viele Völker in Europa wanderten, gelangte viel Gold nach Skandinavien. Man fand Goldschätze, Goldbrakteaten (Amulette) und prachtvolle Halskragen aus Gold. Auf der Insel Öland entstanden Ringburgen wie Eketorp und Ismantorp. Um 536 verdunkelte vermutlich ein gewaltiger Vulkanausbruch den Himmel; es folgten kalte Sommer, Hungersnöte, und viele Höfe wurden verlassen.',
            'Im Land lebten zwei große Völker: die Svear um den Mälarsee in Uppland und die Götar im Süden, in Väster- und Östergötland. Die Insel Gotland hatte eine eigene Kultur mit Bildsteinen, auf denen Schiffe, Kämpfe und Götterszenen dargestellt sind. Auch das altenglische Heldenepos „Beowulf“ erzählt von Kriegen zwischen Schweden und ihren Nachbarn.',
            'Die Zeit von etwa 550 bis 800 heißt Vendelzeit, benannt nach Bootgräbern bei Vendel und Valsgärde in Uppland. Dort wurden vornehme Krieger in Booten bestattet, mit Helmen, Schwertern, Schilden und sogar Pferden. Die prachtvollen Helme ähneln dem berühmten Helm aus dem englischen Schiffsgrab von Sutton Hoo.',
            'Zentrum der Svear war Gamla Uppsala mit drei großen Königshügeln aus dem 6. Jahrhundert. Der Geschichtsschreiber Adam von Bremen beschrieb um 1070 einen Tempel mit Statuen von Thor, Odin und Frey, in dem alle neun Jahre Menschen und Tiere geopfert wurden. Nach der Sage herrschte hier das Königsgeschlecht der Ynglinger. Bei Ystad in Schonen steht Ales stenar, eine Schiffssetzung aus 59 großen Steinen, die 67 Meter lang ist.',
          ],
          quiz: {
            leicht: [
              ['Nach welchem Volk ist Schweden benannt?', 'Nach den Svear', ['Nach den Götar', 'Nach den Wikingern', 'Nach den Römern']],
              ['Was bedeutet „Svea rike“?', 'Reich der Svear', ['Land des Eises', 'Königreich am Meer', 'Reich der Götter']],
              ['Wie heißt Schweden auf Schwedisch?', 'Sverige', ['Svealand', 'Norge', 'Suomi']],
              ['Mit welchem Reich hatten die Skandinavier in der Römischen Eisenzeit Kontakt?', 'Mit dem Römischen Reich', ['Mit dem Perserreich', 'Mit China', 'Mit dem Aztekenreich']],
              ['Welcher Römer erwähnte die Svear?', 'Tacitus', ['Caesar', 'Cicero', 'Augustus']],
              ['Wie heißt das Werk, in dem Tacitus die Svear erwähnte?', '„Germania“', ['„Aeneis“', '„Odyssee“', '„Gallischer Krieg“']],
              ['Wofür waren die Svear laut Tacitus mächtig?', 'Für ihre Flotten', ['Für ihre Reiterei', 'Für ihre Elefanten', 'Für ihre Burgen']],
              ['Welches Edelmetall kam in der Völkerwanderungszeit nach Skandinavien?', 'Gold', ['Platin', 'Bronze', 'Aluminium']],
              ['Auf welcher Insel liegen die Ringburgen Eketorp und Ismantorp?', 'Auf Öland', ['Auf Gotland', 'Auf Island', 'Auf Seeland']],
              ['Welches Volk lebte um den Mälarsee?', 'Die Svear', ['Die Götar', 'Die Samen', 'Die Dänen']],
              ['Welches Volk lebte im Süden Schwedens?', 'Die Götar', ['Die Svear', 'Die Finnen', 'Die Sachsen']],
              ['Was gibt es auf Gotland Besonderes aus dieser Zeit?', 'Bildsteine', ['Pyramiden', 'Römische Tempel', 'Burgen der Ritter']],
              ['Nach welchem Ort ist die Vendelzeit benannt?', 'Nach Vendel in Uppland', ['Nach Venedig', 'Nach Vendée in Frankreich', 'Nach Wenden in Polen']],
              ['Worin wurden vornehme Krieger in der Vendelzeit bestattet?', 'In Booten', ['In Pyramiden', 'In Kirchen', 'In Höhlen']],
              ['Welcher Ort war Zentrum der Svear?', 'Gamla Uppsala', ['Stockholm', 'Göteborg', 'Malmö']],
              ['Wie viele große Königshügel gibt es in Gamla Uppsala?', 'Drei', ['Einen', 'Sieben', 'Zwölf']],
              ['Welche Götter standen im Tempel von Uppsala?', 'Thor, Odin und Frey', ['Zeus, Hera und Apollon', 'Jupiter, Mars und Venus', 'Osiris, Isis und Horus']],
              ['Wer beschrieb den Tempel von Uppsala?', 'Adam von Bremen', ['Tacitus', 'Snorri Sturluson', 'Karl der Große']],
              ['Was ist Ales stenar?', 'Eine Schiffssetzung aus großen Steinen', ['Eine Burg', 'Ein Runenstein', 'Ein Königsgrab mit Gold']],
              ['Welches Heldenepos erzählt von Kriegen der Schweden?', '„Beowulf“', ['„Nibelungenlied“', '„Ilias“', '„Edda“']],
            ],
            mittel: [
              ['Was tauschten die Skandinavier mit den Römern ein?', 'Glas, Bronzegefäße und Münzen', ['Seide und Gewürze', 'Elfenbein und Gold aus Afrika', 'Papier und Tee']],
              ['Wie heißen die römischen Silbermünzen?', 'Denare', ['Drachmen', 'Dukaten', 'Taler']],
              ['Wann erwähnte Tacitus die Svear?', 'Um 98 n. Chr.', ['Um 98 v. Chr.', 'Um 500 n. Chr.', 'Um 800 n. Chr.']],
              ['Wie nannte Tacitus die Svear?', 'Suionen', ['Goten', 'Sueben', 'Sachsen']],
              ['Wann war die Völkerwanderungszeit in Skandinavien?', 'Um 400–550', ['Um 800–1050', 'Um 100–200', 'Um 1200–1300']],
              ['Was sind Goldbrakteaten?', 'Amulette aus Gold', ['Goldene Schwerter', 'Goldene Kronen', 'Goldmünzen aus Rom']],
              ['Was geschah vermutlich um 536?', 'Ein Vulkanausbruch verdunkelte den Himmel', ['Die Römer eroberten Schweden', 'Die Wikingerzeit begann', 'Ein Komet schlug ein']],
              ['Welche Folgen hatte die Katastrophe um 536?', 'Kalte Sommer und Hungersnöte', ['Eine Hitzewelle', 'Eine Flut über ganz Schweden', 'Reiche Ernten']],
              ['In welcher Landschaft lebten die Svear?', 'In Uppland', ['In Schonen', 'In Västergötland', 'In Lappland']],
              ['In welchen Landschaften lebten die Götar?', 'In Väster- und Östergötland', ['In Uppland und Södermanland', 'In Lappland', 'Auf Gotland und Öland']],
              ['Was zeigen die gotländischen Bildsteine?', 'Schiffe, Kämpfe und Götterszenen', ['Römische Kaiser', 'Landkarten', 'Christliche Heilige']],
              ['Welche Zeit umfasst die Vendelzeit?', 'Etwa 550–800', ['Etwa 800–1050', 'Etwa 400–550', 'Etwa 100–400']],
              ['Wo liegen neben Vendel berühmte Bootgräber?', 'In Valsgärde', ['In Birka', 'In Visby', 'In Kalmar']],
              ['Was gab man den Kriegern in den Bootgräbern mit?', 'Helme, Schwerter, Schilde und Pferde', ['Bücher und Kreuze', 'Münzen aus China', 'Nichts']],
              ['Welchem Helm ähneln die Vendelhelme?', 'Dem Helm von Sutton Hoo', ['Dem Helm Alexanders', 'Dem Helm der Samurai', 'Dem Helm des Tutanchamun']],
              ['Aus welchem Jahrhundert stammen die Königshügel von Gamla Uppsala?', 'Aus dem 6. Jahrhundert', ['Aus dem 1. Jahrhundert', 'Aus dem 10. Jahrhundert', 'Aus dem 13. Jahrhundert']],
              ['Wie oft wurde im Tempel von Uppsala geopfert?', 'Alle neun Jahre', ['Jeden Tag', 'Einmal in hundert Jahren', 'Jeden Sonntag']],
              ['Wann beschrieb Adam von Bremen den Tempel?', 'Um 1070', ['Um 98', 'Um 536', 'Um 1500']],
              ['Welches Königsgeschlecht herrschte nach der Sage in Uppsala?', 'Die Ynglinger', ['Die Wasa', 'Die Bernadotte', 'Die Merowinger']],
              ['Wo steht Ales stenar?', 'Bei Ystad in Schonen', ['Bei Stockholm', 'Auf Gotland', 'In Lappland']],
            ],
            schwer: [
              ['Aus wie vielen Steinen besteht Ales stenar?', 'Aus 59', ['Aus 12', 'Aus 300', 'Aus 7']],
              ['Wie lang ist Ales stenar?', '67 Meter', ['6 Meter', '670 Meter', '17 Meter']],
              ['Was wurde in Uppsala geopfert?', 'Menschen und Tiere', ['Nur Getreide', 'Gold und Silber', 'Bücher']],
              ['Welche Ringburgen entstanden auf Öland?', 'Eketorp und Ismantorp', ['Birka und Sigtuna', 'Visby und Kalmar', 'Vendel und Valsgärde']],
              ['Was ließen viele Menschen nach der Katastrophe um 536 zurück?', 'Ihre Höfe', ['Ihre Schiffe', 'Ihre Götter', 'Ihre Sprache']],
              ['Woraus bestanden prachtvolle Halskragen der Völkerwanderungszeit?', 'Aus Gold', ['Aus Bronze', 'Aus Bernstein', 'Aus Eisen']],
              ['Welches Volk ist mit den „Suionen“ gemeint?', 'Die Svear', ['Die Sueben', 'Die Sachsen', 'Die Samen']],
              ['Welche Insel hatte eine eigene Kultur mit Bildsteinen?', 'Gotland', ['Öland', 'Bornholm', 'Island']],
              ['In welchem Land liegt Sutton Hoo?', 'In England', ['In Schweden', 'In Norwegen', 'In Dänemark']],
              ['Aus welcher Sprache stammt das Epos „Beowulf“?', 'Aus dem Altenglischen', ['Aus dem Altnordischen', 'Aus dem Lateinischen', 'Aus dem Gotischen']],
              ['Welcher Gott stand neben Thor und Odin im Tempel?', 'Frey', ['Loki', 'Baldur', 'Tyr']],
              ['Woher stammt das Wort „Sverige“?', 'Von „Svea rike“', ['Von „Svart rike“', 'Von „Sven“', 'Vom lateinischen „Suecia“']],
              ['Was bedeutet die Zeitangabe „Römische Eisenzeit“?', 'Die Eisenzeit mit Kontakt zu Rom', ['Die Zeit, als Rom Schweden regierte', 'Die Zeit der römischen Kaiser in Uppsala', 'Die Zeit nach dem Ende Roms']],
              ['Wer war Adam von Bremen?', 'Ein Geschichtsschreiber', ['Ein schwedischer König', 'Ein römischer Kaiser', 'Ein Wikinger']],
              ['Was sind Bootgräber?', 'Gräber, in denen Tote in Booten bestattet wurden', ['Gräber für ertrunkene Seeleute', 'Häfen für Totenschiffe', 'Steinkreise in Bootform']],
              ['Wofür steht der Name „Völkerwanderungszeit“?', 'Für die Wanderungen vieler Völker in Europa', ['Für die Auswanderung nach Amerika', 'Für die Reisen der Wikinger', 'Für die Flucht vor der Eiszeit']],
              ['Was beschrieb Adam von Bremen in Uppsala?', 'Einen heidnischen Tempel', ['Eine Kathedrale', 'Eine Universität', 'Eine Burg']],
              ['Welcher Ort lag am Mälarsee?', 'Das Gebiet der Svear', ['Das Gebiet der Götar', 'Das Gebiet der Römer', 'Das Gebiet der Dänen']],
              ['Was stellte man in Ales stenar nach?', 'Ein Schiff', ['Eine Sonne', 'Einen Drachen', 'Ein Haus']],
              ['Wann endete die Vendelzeit?', 'Um 800', ['Um 550', 'Um 1050', 'Um 400']],
            ],
          },
        },
      ],
    },
  ],
};
