import type { Epoch } from '../types';

export const E2: Epoch = {
  id: 'mittelalter',
  name: 'Wikinger und Wasa',
  period: '800–1560',
  events: [
    {
      id: 'wikinger',
      title: 'Wikinger und Kalmarer Union',
      date: '800–1520',
      text: [
        'Schwedische Wikinger fuhren über die Ostsee und die russischen Flüsse bis nach Konstantinopel. Um das Jahr 1000 entstand ein christliches Königreich, das Finnland einschloss. Ab 1397 war Schweden in der Kalmarer Union mit Dänemark und Norwegen verbunden – bis zum Stockholmer Blutbad 1520.',
      ],
      subtopics: [
        {
          id: 'wikinger-waraeger',
          title: 'Wikinger, Waräger und Runensteine',
          date: '800–1050',
          text: [
            'Um 800 begann die Wikingerzeit. Wikinger waren Seefahrer, Händler und Krieger aus Skandinavien. Während Dänen und Norweger vor allem nach Westen fuhren, zogen die schwedischen Wikinger nach Osten: über die Ostsee und auf den Flüssen Russlands wie Dnepr und Wolga bis nach Konstantinopel, das sie „Miklagard“ („große Stadt“) nannten, und bis zum Kaspischen Meer. Dort nannte man sie „Waräger“ oder „Rus“. Zwischen den Flüssen schleppten sie ihre Boote über Land.',
            'Nach der altrussischen Nestorchronik riefen die Slawen 862 den Waräger Rurik nach Nowgorod, damit er über sie herrsche; von den „Rus“ leitet sich der Name Russland ab. In Konstantinopel dienten Waräger als Leibwache des Kaisers, die „Warägergarde“. Ein Wikinger namens Halfdan ritzte sogar seinen Namen in Runen in eine Brüstung der Hagia Sophia.',
            'Die wichtigste Handelsstadt war Birka auf der Insel Björkö im Mälarsee, heute UNESCO-Welterbe. 829/830 besuchte der Mönch Ansgar Birka als erster christlicher Missionar in Schweden, allerdings mit wenig Erfolg. Die Wikinger brachten arabische Silbermünzen, Dirham, aus dem Osten mit. Auf Gotland wurden mehr Silberschätze gefunden als irgendwo sonst; der Spillings-Schatz wiegt rund 67 Kilogramm.',
            'Schweden hat mehr Runensteine als jedes andere Land, über 2.500, die meisten in Uppland. Die Wikinger schrieben mit dem Runenalphabet „Futhark“, benannt nach seinen ersten sechs Zeichen. Viele Steine erinnern an Verstorbene; die Ingvar-Steine nennen Männer, die um 1040 mit Ingvar nach Osten zogen und kaum je zurückkehrten. Der Rök-Stein in Östergötland aus dem 9. Jahrhundert trägt die längste bekannte Runeninschrift der Welt.',
            'Die meisten Wikinger waren Bauern. Wichtige Fragen entschied das „Thing“, die Versammlung der freien Männer. Die Gesellschaft bestand aus Jarlen (Adligen), freien Bauern und Unfreien, den Thralen. Die Frauen führten den Hof und trugen als Zeichen dafür die Schlüssel am Gürtel. Die Menschen verehrten Götter wie Odin, Thor und Frey und glaubten, dass im Kampf Gefallene nach Walhall kommen. Mit der Christianisierung endete um 1050 die Wikingerzeit.',
          ],
          quiz: {
            leicht: [
              ['Um wann begann die Wikingerzeit?', 'Um 800', ['Um 500', 'Um 1200', 'Um 1500']],
              ['In welche Richtung fuhren die schwedischen Wikinger vor allem?', 'Nach Osten', ['Nach Westen', 'Nach Süden nach Afrika', 'Nach Norden zum Nordpol']],
              ['Wie nannte man die schwedischen Wikinger im Osten?', 'Waräger oder Rus', ['Normannen', 'Sachsen', 'Goten']],
              ['Welches Land ist nach den „Rus“ benannt?', 'Russland', ['Rumänien', 'Ruanda', 'Rügen']],
              ['Bis zu welcher großen Stadt fuhren die Wikinger im Süden?', 'Bis Konstantinopel', ['Bis Rom', 'Bis Kairo', 'Bis Jerusalem']],
              ['Wie nannten die Wikinger Konstantinopel?', 'Miklagard', ['Walhall', 'Asgard', 'Birka']],
              ['Was taten die Wikinger zwischen zwei Flüssen?', 'Sie schleppten ihre Boote über Land', ['Sie bauten neue Schiffe', 'Sie gaben auf', 'Sie gruben Kanäle']],
              ['Wer war Leibwache des Kaisers in Konstantinopel?', 'Die Warägergarde', ['Die Prätorianer', 'Die Janitscharen', 'Die Schweizergarde']],
              ['Wie hieß die wichtigste Handelsstadt der schwedischen Wikinger?', 'Birka', ['Stockholm', 'Haithabu', 'Visby']],
              ['In welchem See liegt Birka?', 'Im Mälarsee', ['Im Vänernsee', 'Im Bodensee', 'Im Ladogasee']],
              ['Wer war der erste christliche Missionar in Schweden?', 'Ansgar', ['Bonifatius', 'Patrick', 'Olaf']],
              ['Welche Münzen brachten die Wikinger aus dem Osten mit?', 'Arabische Silbermünzen', ['Römische Goldmünzen', 'Chinesisches Papiergeld', 'Euro']],
              ['Auf welcher Insel wurden die meisten Silberschätze gefunden?', 'Auf Gotland', ['Auf Öland', 'Auf Island', 'Auf Seeland']],
              ['Welches Land hat die meisten Runensteine?', 'Schweden', ['Norwegen', 'Dänemark', 'Island']],
              ['Wie heißt das Runenalphabet?', 'Futhark', ['Alphabet', 'Kyrillisch', 'Ogham']],
              ['Wie hieß die Versammlung der freien Männer?', 'Thing', ['Senat', 'Parlament', 'Reichstag']],
              ['Was trugen Wikingerfrauen als Zeichen ihrer Macht am Gürtel?', 'Die Schlüssel', ['Ein Schwert', 'Eine Krone', 'Einen Geldbeutel des Königs']],
              ['Wohin kamen nach dem Glauben der Wikinger im Kampf Gefallene?', 'Nach Walhall', ['Nach Miklagard', 'In den Olymp', 'In den Hades']],
              ['Welche Götter verehrten die Wikinger?', 'Odin, Thor und Frey', ['Zeus, Ares und Hermes', 'Jupiter und Mars', 'Ra und Osiris']],
              ['Womit endete die Wikingerzeit?', 'Mit der Christianisierung', ['Mit einer Eiszeit', 'Mit der Pest', 'Mit der Eroberung durch Rom']],
            ],
            mittel: [
              ['Wohin fuhren Dänen und Norweger vor allem?', 'Nach Westen', ['Nach Osten', 'Nach Russland', 'Zum Kaspischen Meer']],
              ['Auf welchen Flüssen fuhren die Waräger?', 'Auf Dnepr und Wolga', ['Auf Rhein und Donau', 'Auf Nil und Euphrat', 'Auf Themse und Seine']],
              ['Was bedeutet „Miklagard“?', 'Große Stadt', ['Heilige Stadt', 'Goldene Stadt', 'Stadt am Meer']],
              ['Bis zu welchem Meer gelangten die Waräger?', 'Bis zum Kaspischen Meer', ['Bis zum Roten Meer', 'Bis zum Japanischen Meer', 'Bis zur Karibik']],
              ['Welche Chronik erzählt von Rurik?', 'Die Nestorchronik', ['Die Edda', 'Die Germania', 'Die Ilias']],
              ['Wann soll Rurik nach Nowgorod gerufen worden sein?', '862', ['800', '1050', '988']],
              ['Wer rief Rurik nach Nowgorod?', 'Die Slawen', ['Der Kaiser von Byzanz', 'Der Papst', 'Die Araber']],
              ['Wo ritzte ein Wikinger namens Halfdan Runen ein?', 'In der Hagia Sophia', ['Im Kolosseum', 'In Birka', 'Auf dem Rök-Stein']],
              ['Auf welcher Insel liegt Birka?', 'Auf Björkö', ['Auf Gotland', 'Auf Öland', 'Auf Bornholm']],
              ['Wann besuchte Ansgar Birka?', '829/830', ['862', '1008', '1164']],
              ['Wie erfolgreich war Ansgars Mission?', 'Wenig erfolgreich', ['Ganz Schweden wurde christlich', 'Er wurde König', 'Er gründete Stockholm']],
              ['Wie heißen die arabischen Silbermünzen?', 'Dirham', ['Denar', 'Dukat', 'Rubel']],
              ['Wie schwer ist der Spillings-Schatz etwa?', 'Rund 67 Kilogramm', ['Rund 6 Kilogramm', 'Rund 670 Kilogramm', 'Rund 1 Kilogramm']],
              ['Wie viele Runensteine gibt es in Schweden?', 'Über 2.500', ['Rund 25', 'Rund 250', 'Über 250.000']],
              ['In welcher Landschaft stehen die meisten Runensteine?', 'In Uppland', ['In Schonen', 'In Lappland', 'Auf Gotland']],
              ['Woher hat das Futhark seinen Namen?', 'Von seinen ersten sechs Zeichen', ['Von einem Gott', 'Von einem König', 'Von einer Stadt']],
              ['Woran erinnern die Ingvar-Steine?', 'An Männer, die mit Ingvar nach Osten zogen', ['An einen Sieg über Dänemark', 'An die Taufe des Königs', 'An die Gründung Birkas']],
              ['Was ist besonders am Rök-Stein?', 'Er trägt die längste bekannte Runeninschrift', ['Er ist aus Gold', 'Er steht in Konstantinopel', 'Er ist der jüngste Runenstein']],
              ['Wie hießen die Unfreien in der Wikingerzeit?', 'Thrale', ['Jarle', 'Karle', 'Waräger']],
              ['Wer waren die Jarle?', 'Adlige', ['Sklaven', 'Priester', 'Händler aus Arabien']],
            ],
            schwer: [
              ['In welcher Landschaft steht der Rök-Stein?', 'In Östergötland', ['In Uppland', 'In Schonen', 'Auf Gotland']],
              ['Aus welchem Jahrhundert stammt der Rök-Stein?', 'Aus dem 9. Jahrhundert', ['Aus dem 6. Jahrhundert', 'Aus dem 12. Jahrhundert', 'Aus dem 15. Jahrhundert']],
              ['Um wann zogen die Männer mit Ingvar nach Osten?', 'Um 1040', ['Um 800', 'Um 862', 'Um 1164']],
              ['Was geschah mit den meisten Männern Ingvars?', 'Sie kehrten kaum je zurück', ['Sie wurden Könige in Russland', 'Sie kehrten reich zurück', 'Sie gründeten Birka']],
              ['Welche Stadt in Russland wurde mit Rurik verbunden?', 'Nowgorod', ['Moskau', 'Kiew', 'Sankt Petersburg']],
              ['Zu welchem Welterbe gehört Birka?', 'Zum UNESCO-Welterbe', ['Zum Erbe der Hanse', 'Zum Erbe Roms', 'Zu keinem']],
              ['Wie viele Zeichen gaben dem Futhark den Namen?', 'Die ersten sechs', ['Die ersten drei', 'Alle sechzehn', 'Die letzten vier']],
              ['Was war Ansgar von Beruf?', 'Mönch', ['König', 'Händler', 'Krieger']],
              ['Wann endete die Wikingerzeit etwa?', 'Um 1050', ['Um 900', 'Um 1200', 'Um 1397']],
              ['Woran glaubten die Wikinger über den Tod im Kampf?', 'Gefallene kommen nach Walhall', ['Sie werden wiedergeboren', 'Sie werden zu Steinen', 'Sie fahren nach Miklagard']],
              ['Woraus bestand der Spillings-Schatz vor allem?', 'Aus Silber', ['Aus Gold', 'Aus Bronze', 'Aus Bernstein']],
              ['Wo fand man den Spillings-Schatz?', 'Auf Gotland', ['In Birka', 'In Uppsala', 'In Konstantinopel']],
              ['Woran erinnern viele Runensteine?', 'An Verstorbene', ['An Wetterereignisse', 'An Gesetze des Königs', 'An Bibelverse']],
              ['Was waren die meisten Wikinger im Alltag?', 'Bauern', ['Krieger auf Raubzug', 'Mönche', 'Händler in Bagdad']],
              ['Welche Völker nannten die Schweden „Rus“?', 'Die Menschen im Osten', ['Die Engländer', 'Die Franzosen', 'Die Römer']],
              ['Was ist eine Warägergarde?', 'Eine Leibwache aus Skandinaviern', ['Eine Flotte', 'Ein Kloster', 'Eine Burg in Birka']],
              ['Wer herrschte nach der Nestorchronik ab 862 über Nowgorod?', 'Rurik', ['Ingvar', 'Halfdan', 'Ansgar']],
              ['Wie gelangten die Waräger vom Ostseeraum zum Schwarzen Meer?', 'Über die russischen Flüsse', ['Über den Atlantik', 'Durch das Mittelmeer', 'Über die Alpen']],
              ['Wie hieß der Wikinger, der in der Hagia Sophia Runen ritzte?', 'Halfdan', ['Rurik', 'Ingvar', 'Olof']],
              ['Welche Rolle hatten freie Männer im Thing?', 'Sie entschieden wichtige Fragen', ['Sie hatten keine Rolle', 'Sie dienten als Sklaven', 'Sie wählten den Papst']],
            ],
          },
        },
        {
          id: 'christentum-reich',
          title: 'Christentum, Stockholm und die Hanse',
          date: '1000–1389',
          text: [
            'Olof Skötkonung (um 995–1022) war der erste König, der über Svear und Götar zugleich herrschte. Um 1008 ließ er sich taufen, und in Sigtuna, das um 980 als Nachfolgerin Birkas gegründet worden war, ließ er die ersten schwedischen Münzen prägen. Das Heidentum hielt sich in Uppsala noch bis etwa 1080. 1164 wurde Uppsala Sitz eines Erzbischofs.',
            'König Erik der Heilige soll um 1155 einen Kreuzzug nach Finnland unternommen haben; 1160 wurde er in Uppsala ermordet. Er wurde Schwedens Schutzheiliger, und seine Reliquien liegen im Dom von Uppsala. Ab dem 12. und 13. Jahrhundert wurde Finnland Schritt für Schritt ein Teil Schwedens – und blieb es bis 1809.',
            'Der mächtigste Mann des 13. Jahrhunderts war Birger Jarl. Er gilt als Gründer Stockholms, das 1252 zum ersten Mal erwähnt wird, und erließ Gesetze, die den Frieden von Frauen, Haus, Kirche und Thing schützten. Sein Sohn Magnus Ladulås („Scheunenschloss“) soll die Bauern vor dem Adel geschützt haben. 1280 befreite er den Adel von Steuern, wenn dieser dafür als Reiter Kriegsdienst leistete.',
            'Den Handel beherrschten deutsche Kaufleute der Hanse. Visby auf Gotland wurde eine reiche Hansestadt mit einer Stadtmauer, die bis heute steht und zum UNESCO-Welterbe gehört. 1361 eroberte der dänische König Valdemar Atterdag Gotland; vor den Toren Visbys wurden die gotländischen Bauern niedergemacht. Im Kupferbergwerk von Falun wurde schon im Mittelalter Erz abgebaut; das Bergbauunternehmen Stora Kopparberg ist durch eine Urkunde von 1288 belegt und gilt als eines der ältesten Unternehmen der Welt.',
            'Um 1350 schuf König Magnus Eriksson das erste Landrecht für das ganze Reich. Im selben Jahr erreichte die Pest, der „Digerdöden“ („große Tod“), Schweden und tötete etwa ein Drittel der Menschen. Die heilige Birgitta (1303–1373) hatte Visionen, gründete den Birgittenorden und das Kloster Vadstena; seit 1999 ist sie eine der Schutzpatroninnen Europas.',
          ],
          quiz: {
            leicht: [
              ['Wer herrschte als erster König über Svear und Götar?', 'Olof Skötkonung', ['Gustav Wasa', 'Erik der Heilige', 'Birger Jarl']],
              ['Um wann ließ sich Olof Skötkonung taufen?', 'Um 1008', ['Um 800', 'Um 1164', 'Um 1523']],
              ['In welcher Stadt wurden die ersten schwedischen Münzen geprägt?', 'In Sigtuna', ['In Stockholm', 'In Birka', 'In Visby']],
              ['Welche Stadt wurde 1164 Sitz eines Erzbischofs?', 'Uppsala', ['Stockholm', 'Lund', 'Visby']],
              ['Wer ist Schwedens Schutzheiliger?', 'Erik der Heilige', ['Ansgar', 'Olof Skötkonung', 'Birger Jarl']],
              ['Welches Land wurde ab dem 12./13. Jahrhundert ein Teil Schwedens?', 'Finnland', ['Norwegen', 'Dänemark', 'Estland']],
              ['Bis wann gehörte Finnland zu Schweden?', 'Bis 1809', ['Bis 1397', 'Bis 1523', 'Bis 1905']],
              ['Wer gilt als Gründer Stockholms?', 'Birger Jarl', ['Gustav Wasa', 'Olof Skötkonung', 'Erik der Heilige']],
              ['Wann wurde Stockholm zum ersten Mal erwähnt?', '1252', ['1008', '1397', '1523']],
              ['Was bedeutet „Ladulås“?', 'Scheunenschloss', ['Starker Arm', 'Goldener König', 'Bauernfreund']],
              ['Welche Kaufleute beherrschten den Handel?', 'Die deutschen Kaufleute der Hanse', ['Venezianische Kaufleute', 'Arabische Händler', 'Englische Kaufleute']],
              ['Welche reiche Hansestadt liegt auf Gotland?', 'Visby', ['Birka', 'Sigtuna', 'Lübeck']],
              ['Was ist in Visby bis heute erhalten?', 'Die Stadtmauer', ['Der Tempel der Wikinger', 'Ein römisches Theater', 'Ein Königsschloss aus Gold']],
              ['Welcher dänische König eroberte 1361 Gotland?', 'Valdemar Atterdag', ['Christian II.', 'Knut der Große', 'Erich von Pommern']],
              ['Welches Metall wurde in Falun abgebaut?', 'Kupfer', ['Gold', 'Silber', 'Uran']],
              ['Wie heißt die Pest auf Schwedisch?', 'Digerdöden', ['Svartdöden', 'Pestilens', 'Smittan']],
              ['Wie viele Menschen tötete die Pest etwa?', 'Ein Drittel', ['Ein Zehntel', 'Neun Zehntel', 'Niemanden']],
              ['Welche Heilige gründete das Kloster Vadstena?', 'Birgitta', ['Lucia', 'Katharina', 'Elisabeth']],
              ['Was ist Birgitta seit 1999?', 'Eine der Schutzpatroninnen Europas', ['Königin von Schweden', 'Päpstin', 'Nobelpreisträgerin']],
              ['Wo wurde Erik der Heilige ermordet?', 'In Uppsala', ['In Stockholm', 'In Finnland', 'In Visby']],
            ],
            mittel: [
              ['Wann regierte Olof Skötkonung?', 'Um 995–1022', ['Um 800–862', 'Um 1250–1266', 'Um 1523–1560']],
              ['Wann wurde Sigtuna gegründet?', 'Um 980', ['Um 800', 'Um 1252', 'Um 1164']],
              ['Wessen Nachfolgerin war Sigtuna?', 'Birkas', ['Stockholms', 'Visbys', 'Uppsalas']],
              ['Bis wann hielt sich das Heidentum in Uppsala?', 'Bis etwa 1080', ['Bis etwa 800', 'Bis etwa 1523', 'Bis etwa 1008']],
              ['Wohin soll Erik der Heilige einen Kreuzzug unternommen haben?', 'Nach Finnland', ['Nach Jerusalem', 'Nach Russland', 'Nach Dänemark']],
              ['Wann wurde Erik der Heilige ermordet?', '1160', ['1008', '1252', '1361']],
              ['Wo liegen die Reliquien Eriks des Heiligen?', 'Im Dom von Uppsala', ['In der Storkyrkan von Stockholm', 'In Vadstena', 'In Rom']],
              ['Welchen Frieden schützten Birger Jarls Gesetze?', 'Den von Frauen, Haus, Kirche und Thing', ['Den der Hanse', 'Den des Papstes', 'Den der Wikinger auf See']],
              ['Wessen Sohn war Magnus Ladulås?', 'Der Sohn Birger Jarls', ['Der Sohn Olof Skötkonungs', 'Der Sohn Eriks des Heiligen', 'Der Sohn Valdemars']],
              ['Wen soll Magnus Ladulås geschützt haben?', 'Die Bauern vor dem Adel', ['Den Adel vor den Bauern', 'Die Hanse vor Dänemark', 'Die Kirche vor dem Papst']],
              ['Was verlangte Magnus Ladulås 1280 vom Adel für die Steuerfreiheit?', 'Kriegsdienst als Reiter', ['Den Bau von Kirchen', 'Geld für die Hanse', 'Einen Kreuzzug']],
              ['Was geschah 1361 vor den Toren Visbys?', 'Gotländische Bauern wurden niedergemacht', ['Die Hanse wurde gegründet', 'Visby wurde Hauptstadt', 'Birgitta hatte eine Vision']],
              ['Zu welchem Erbe gehört Visby?', 'Zum UNESCO-Welterbe', ['Zum dänischen Kronschatz', 'Zum Erbe der Wikinger in Norwegen', 'Zu keinem']],
              ['Wie heißt das Bergbauunternehmen in Falun?', 'Stora Kopparberg', ['Ericsson', 'Volvo', 'IKEA']],
              ['Wann ist Stora Kopparberg durch eine Urkunde belegt?', '1288', ['1008', '1361', '1523']],
              ['Was schuf Magnus Eriksson um 1350?', 'Das erste Landrecht für das ganze Reich', ['Die erste Universität', 'Die Kalmarer Union', 'Die erste Bibel auf Schwedisch']],
              ['Wann erreichte die Pest Schweden?', 'Um 1350', ['Um 1008', 'Um 1520', 'Um 1700']],
              ['Was bedeutet „Digerdöden“?', 'Der große Tod', ['Der schwarze Tod', 'Die rote Krankheit', 'Das Ende der Welt']],
              ['Welchen Orden gründete Birgitta?', 'Den Birgittenorden', ['Den Jesuitenorden', 'Den Templerorden', 'Den Franziskanerorden']],
              ['Wann lebte die heilige Birgitta?', '1303–1373', ['995–1022', '1496–1560', '1626–1689']],
            ],
            schwer: [
              ['Seit wann ist Birgitta Schutzpatronin Europas?', 'Seit 1999', ['Seit 1373', 'Seit 1523', 'Seit 1950']],
              ['Was hatte Birgitta?', 'Visionen', ['Ein Heer', 'Eine Krone', 'Eine Flotte']],
              ['Wann befreite Magnus Ladulås den Adel von Steuern?', '1280', ['1252', '1350', '1160']],
              ['Wann eroberte Valdemar Atterdag Gotland?', '1361', ['1252', '1397', '1520']],
              ['Wann wurde Uppsala Sitz eines Erzbischofs?', '1164', ['1008', '1080', '1252']],
              ['Wann soll Erik der Heilige seinen Kreuzzug unternommen haben?', 'Um 1155', ['Um 1008', 'Um 1252', 'Um 1350']],
              ['Welcher König schuf das erste Landrecht für ganz Schweden?', 'Magnus Eriksson', ['Magnus Ladulås', 'Olof Skötkonung', 'Erik der Heilige']],
              ['Was ist das Besondere an Stora Kopparberg?', 'Es gilt als eines der ältesten Unternehmen der Welt', ['Es war die erste Bank', 'Es gehörte der Hanse', 'Es baute Schiffe für die Wikinger']],
              ['Wo liegt das Kloster Vadstena?', 'In Schweden', ['In Rom', 'In Dänemark', 'In Finnland']],
              ['Was war Olof Skötkonung als Herrscher?', 'Der erste König über Svear und Götar zugleich', ['Der letzte Wikingerkönig', 'Der Gründer Stockholms', 'Ein dänischer König']],
              ['Welche Stellung hatte Birger Jarl?', 'Er war der mächtigste Mann des 13. Jahrhunderts', ['Er war Erzbischof', 'Er war Kaufmann der Hanse', 'Er war dänischer König']],
              ['Welche Insel eroberte Dänemark 1361?', 'Gotland', ['Öland', 'Björkö', 'Seeland']],
              ['Welche Gemeinschaft beherrschte den Ostseehandel?', 'Die Hanse', ['Die Templer', 'Die Wikinger', 'Die Ostindien-Kompanie']],
              ['Welche Stadt war Sitz des ersten Erzbischofs Schwedens?', 'Uppsala', ['Sigtuna', 'Stockholm', 'Visby']],
              ['Was ließ Olof Skötkonung in Sigtuna prägen?', 'Die ersten schwedischen Münzen', ['Die ersten Runensteine', 'Die ersten Bücher', 'Die ersten Kronen']],
              ['Was für Gesetze erließ Birger Jarl?', 'Friedensgesetze', ['Steuergesetze für die Hanse', 'Gesetze gegen das Christentum', 'Gesetze zur Auswanderung']],
              ['Was wird in Falun schon seit dem Mittelalter gefördert?', 'Kupfererz', ['Erdöl', 'Salz', 'Diamanten']],
              ['Was war Visby für die Hanse?', 'Eine reiche Hansestadt', ['Ein Gefängnis', 'Ein Kloster', 'Ein Fischerdorf ohne Bedeutung']],
              ['Wie lange gehörte Finnland ungefähr zu Schweden?', 'Rund 600 Jahre', ['Rund 60 Jahre', 'Rund 6 Jahre', 'Rund 1000 Jahre']],
              ['Wie wurde Finnland ein Teil Schwedens?', 'Schritt für Schritt', ['Durch einen einzigen Vertrag 1809', 'Durch Kauf von Dänemark', 'Durch Heirat']],
            ],
          },
        },
        {
          id: 'kalmarer-union',
          title: 'Die Kalmarer Union und das Stockholmer Blutbad',
          date: '1389–1520',
          text: [
            'Margarete I., Tochter des dänischen Königs Valdemar Atterdag, herrschte über Dänemark und Norwegen. Schwedische Adlige riefen sie gegen ihren unbeliebten König Albrecht von Mecklenburg zu Hilfe. 1389 siegten ihre Truppen bei Falköping, und Albrecht geriet in Gefangenschaft. 1397 wurde in Kalmar ihr Großneffe Erich von Pommern zum König aller drei Reiche gekrönt – das war die Kalmarer Union.',
            'In der Union hatten die Dänen das Sagen. Erich setzte dänische und deutsche Vögte ein, erhob hohe Steuern und führte Krieg gegen die Hanse, was den schwedischen Erzexport schädigte. 1434 erhob sich der Bergwerksbesitzer Engelbrekt Engelbrektsson aus Bergslagen. 1435 versammelte sich in Arboga ein Reichstag, an dem auch Bürger und Bauern teilnahmen. 1436 wurde Engelbrekt ermordet; er gilt bis heute als Freiheitsheld.',
            'Danach regierten oft „Reichsverweser“ statt Könige. 1471 besiegte der Reichsverweser Sten Sture der Ältere die Dänen am Brunkeberg in Stockholm. Als Dank stiftete er die Skulptur „Sankt Göran und der Drache“ für die Stockholmer Storkyrkan. 1477 wurde die Universität Uppsala gegründet, die älteste Universität Skandinaviens.',
            'Der Reichsverweser Sten Sture der Jüngere stritt mit dem unionsfreundlichen Erzbischof Gustav Trolle. 1520 eroberte der dänische König Christian II. Schweden; Sten Sture wurde in der Schlacht tödlich verwundet. Seine Witwe Christina Gyllenstierna verteidigte Stockholm noch monatelang.',
            'Im November 1520 ließ sich Christian II. in Stockholm zum König krönen. Wenige Tage später, am 8. und 9. November, ließ er rund 80 Adlige, Bischöfe und Bürger, die er als Ketzer anklagen ließ, auf dem Stortorget hinrichten – das „Stockholmer Blutbad“. In Schweden nennt man ihn seitdem „Christian den Tyrannen“. Das Blutbad wurde zum Auslöser des Befreiungskrieges.',
          ],
          quiz: {
            leicht: [
              ['Welche drei Reiche vereinte die Kalmarer Union?', 'Dänemark, Norwegen und Schweden', ['Schweden, Finnland und Russland', 'Dänemark, England und Schweden', 'Schweden, Polen und Litauen']],
              ['In welchem Jahr entstand die Kalmarer Union?', '1397', ['1389', '1523', '1250']],
              ['In welcher Stadt wurde die Union geschlossen?', 'In Kalmar', ['In Stockholm', 'In Kopenhagen', 'In Oslo']],
              ['Welche Herrscherin stand hinter der Kalmarer Union?', 'Margarete I.', ['Christina', 'Birgitta', 'Elisabeth I.']],
              ['Wer wurde 1397 König aller drei Reiche?', 'Erich von Pommern', ['Albrecht von Mecklenburg', 'Christian II.', 'Gustav Wasa']],
              ['Welches Land hatte in der Union das Sagen?', 'Dänemark', ['Schweden', 'Norwegen', 'Deutschland']],
              ['Wer erhob sich 1434 gegen die Union?', 'Engelbrekt Engelbrektsson', ['Sten Sture', 'Gustav Trolle', 'Christian II.']],
              ['Was war Engelbrekt von Beruf?', 'Bergwerksbesitzer', ['Bischof', 'König', 'Fischer']],
              ['Als was gilt Engelbrekt bis heute?', 'Als Freiheitsheld', ['Als Verräter', 'Als Heiliger', 'Als dänischer König']],
              ['Wie nannte man die Regenten ohne Königstitel?', 'Reichsverweser', ['Kaiser', 'Jarle', 'Kurfürsten']],
              ['Wo besiegte Sten Sture der Ältere 1471 die Dänen?', 'Am Brunkeberg in Stockholm', ['Bei Kalmar', 'In Uppsala', 'Bei Falköping']],
              ['Welche Skulptur stiftete Sten Sture als Dank?', '„Sankt Göran und der Drache“', ['„Der Denker“', '„David“', '„Die kleine Meerjungfrau“']],
              ['Welche Universität wurde 1477 gegründet?', 'Die Universität Uppsala', ['Die Universität Stockholm', 'Die Universität Lund', 'Die Universität Kopenhagen']],
              ['Welcher dänische König eroberte 1520 Schweden?', 'Christian II.', ['Christian IV.', 'Erich von Pommern', 'Valdemar Atterdag']],
              ['Wie heißen die Hinrichtungen von 1520?', 'Stockholmer Blutbad', ['Bartholomäusnacht', 'Sizilianische Vesper', 'Blutiger Sonntag']],
              ['Wie nennen die Schweden Christian II.?', 'Christian den Tyrannen', ['Christian den Großen', 'Christian den Guten', 'Christian den Heiligen']],
              ['Wo fanden die Hinrichtungen statt?', 'Auf dem Stortorget in Stockholm', ['In Kalmar', 'In Kopenhagen', 'In Uppsala']],
              ['Was löste das Stockholmer Blutbad aus?', 'Den Befreiungskrieg', ['Die Kalmarer Union', 'Die Pest', 'Die Wikingerzeit']],
              ['Wer verteidigte Stockholm 1520 monatelang?', 'Christina Gyllenstierna', ['Margarete I.', 'Birgitta', 'Königin Christina']],
              ['Welche Universität ist die älteste Skandinaviens?', 'Uppsala', ['Kopenhagen', 'Oslo', 'Helsinki']],
            ],
            mittel: [
              ['Wessen Tochter war Margarete I.?', 'Valdemar Atterdags', ['Albrechts von Mecklenburg', 'Erichs von Pommern', 'Christians II.']],
              ['Gegen welchen König riefen schwedische Adlige Margarete zu Hilfe?', 'Albrecht von Mecklenburg', ['Christian II.', 'Gustav Wasa', 'Erich von Pommern']],
              ['Wo siegten Margaretes Truppen 1389?', 'Bei Falköping', ['Am Brunkeberg', 'Bei Arboga', 'Bei Kalmar']],
              ['Was geschah 1389 mit Albrecht von Mecklenburg?', 'Er geriet in Gefangenschaft', ['Er wurde König der Union', 'Er floh nach Finnland', 'Er wurde ermordet']],
              ['Was war Erich von Pommern für Margarete?', 'Ihr Großneffe', ['Ihr Sohn', 'Ihr Ehemann', 'Ihr Bruder']],
              ['Wen setzte Erich als Vögte ein?', 'Dänen und Deutsche', ['Schweden und Finnen', 'Norweger', 'Russen']],
              ['Was schädigte Erichs Krieg gegen die Hanse?', 'Den schwedischen Erzexport', ['Den Fischfang', 'Den Weinhandel', 'Die Wikingerfahrten']],
              ['Woher stammte Engelbrekt?', 'Aus Bergslagen', ['Aus Schonen', 'Aus Gotland', 'Aus Finnland']],
              ['Wo versammelte sich 1435 ein Reichstag?', 'In Arboga', ['In Stockholm', 'In Kalmar', 'In Uppsala']],
              ['Wer nahm am Reichstag 1435 außer dem Adel teil?', 'Bürger und Bauern', ['Nur Bischöfe', 'Dänische Vögte', 'Hansekaufleute']],
              ['Wann wurde Engelbrekt ermordet?', '1436', ['1434', '1471', '1520']],
              ['Wann siegte Sten Sture der Ältere am Brunkeberg?', '1471', ['1389', '1477', '1520']],
              ['Für welche Kirche stiftete Sten Sture „Sankt Göran und der Drache“?', 'Für die Storkyrkan in Stockholm', ['Für den Dom von Uppsala', 'Für Vadstena', 'Für den Petersdom']],
              ['Mit welchem Erzbischof stritt Sten Sture der Jüngere?', 'Mit Gustav Trolle', ['Mit Laurentius Petri', 'Mit Ansgar', 'Mit Olaus Petri']],
              ['Wie stand Gustav Trolle zur Union?', 'Er war unionsfreundlich', ['Er war gegen die Union', 'Er war neutral', 'Er wollte die Republik']],
              ['Was geschah mit Sten Sture dem Jüngeren 1520?', 'Er wurde in der Schlacht tödlich verwundet', ['Er wurde König', 'Er floh nach Lübeck', 'Er wurde Erzbischof']],
              ['Wann ließ sich Christian II. in Stockholm krönen?', 'Im November 1520', ['Im Juni 1523', 'Im Jahr 1397', 'Im Jahr 1471']],
              ['Wie viele Menschen ließ Christian II. hinrichten?', 'Rund 80', ['Rund 8', 'Rund 800', 'Rund 8.000']],
              ['Als was ließ Christian II. die Opfer anklagen?', 'Als Ketzer', ['Als Diebe', 'Als Spione Englands', 'Als Mörder']],
              ['Wer gehörte zu den Opfern des Blutbads?', 'Adlige, Bischöfe und Bürger', ['Nur Bauern', 'Nur Dänen', 'Hanseatische Kaufleute aus Lübeck']],
            ],
            schwer: [
              ['An welchen Tagen fand das Stockholmer Blutbad statt?', 'Am 8. und 9. November 1520', ['Am 6. Juni 1523', 'Am 24. Dezember 1520', 'Am 1. Mai 1397']],
              ['Wann war die Schlacht bei Falköping?', '1389', ['1397', '1434', '1471']],
              ['In welchem Jahr erhob sich Engelbrekt?', '1434', ['1436', '1397', '1471']],
              ['Wann tagte der Reichstag in Arboga?', '1435', ['1434', '1477', '1520']],
              ['Wann wurde die Universität Uppsala gegründet?', '1477', ['1471', '1397', '1527']],
              ['Wann eroberte Christian II. Schweden?', '1520', ['1397', '1471', '1523']],
              ['Wie lange verteidigte Christina Gyllenstierna Stockholm?', 'Monatelang', ['Einen Tag', 'Zehn Jahre', 'Gar nicht']],
              ['Wessen Witwe war Christina Gyllenstierna?', 'Die Witwe Sten Stures des Jüngeren', ['Die Witwe Engelbrekts', 'Die Witwe Christians II.', 'Die Witwe Gustav Wasas']],
              ['Woher stammte Albrecht, der unbeliebte König Schwedens?', 'Aus Mecklenburg', ['Aus Pommern', 'Aus Dänemark', 'Aus Holstein']],
              ['Welches Gebiet ist Bergslagen?', 'Ein Bergbaugebiet in Mittelschweden', ['Eine Insel', 'Ein Gebiet in Dänemark', 'Ein Teil Finnlands']],
              ['Welcher Reichsverweser trug den Zusatz „der Ältere“?', 'Sten Sture', ['Engelbrekt', 'Gustav Trolle', 'Erich von Pommern']],
              ['Was war das Besondere am Reichstag von Arboga?', 'Auch Bürger und Bauern nahmen teil', ['Er wählte einen Papst', 'Er fand in Dänemark statt', 'Er beschloss die Union']],
              ['Wie wurde Sten Sture der Jüngere tödlich verwundet?', 'In einer Schlacht gegen Christian II.', ['Bei einem Attentat in Uppsala', 'Bei einem Unfall', 'Im Duell mit Trolle']],
              ['Was tat Christian II. kurz vor dem Blutbad?', 'Er ließ sich krönen', ['Er verließ Schweden', 'Er heiratete', 'Er schloss Frieden']],
              ['Wer regierte oft in Schweden statt eines Königs?', 'Reichsverweser', ['Erzbischöfe', 'Hansekaufleute', 'Dänische Vögte']],
              ['Was symbolisiert „Sankt Göran und der Drache“?', 'Den Sieg über die Dänen', ['Die Gründung Stockholms', 'Die Pest', 'Die Taufe des Königs']],
              ['Wie hieß der Ort, an dem die Union 1397 begann?', 'Kalmar', ['Falköping', 'Arboga', 'Brunkeberg']],
              ['Welche Rolle hatte Valdemar Atterdag für die Union?', 'Er war Margaretes Vater', ['Er gründete die Union', 'Er war ihr erster König', 'Er löste sie auf']],
              ['Wer stiftete die Skulptur „Sankt Göran und der Drache“?', 'Sten Sture der Ältere', ['Gustav Wasa', 'Christian II.', 'Engelbrekt']],
              ['Was folgte auf das Stockholmer Blutbad?', 'Der Befreiungskrieg', ['Die Pest', 'Die Gründung der Union', 'Die Wikingerzeit']],
            ],
          },
        },
      ],
    },
    {
      id: 'wasa',
      title: 'Gustav Wasa und die Reformation',
      date: '1520–1560',
      text: [
        'Gustav Wasa befreite Schweden von der dänischen Herrschaft, wurde 1523 König und machte das Land lutherisch. Er schuf einen starken Zentralstaat und eine erbliche Monarchie und gilt als Vater des modernen Schweden.',
      ],
      subtopics: [
        {
          id: 'gustav-wasa',
          title: 'Gustav Wasa und die Reformation',
          date: '1520–1560',
          text: [
            'Unter den Opfern des Stockholmer Blutbads war der Vater des jungen Adligen Gustav Eriksson aus dem Geschlecht Wasa. Gustav floh nach Dalarna und versuchte, die Bauern zum Aufstand zu bewegen. Zuerst wiesen sie ihn ab, und er floh auf Skiern Richtung Norwegen. Als die Bauern von den Grausamkeiten Christians hörten, schickten sie zwei Skiläufer hinterher, die ihn in Sälen einholten. Daran erinnert der Wasalauf, ein 90 Kilometer langer Skilanglauf von Sälen nach Mora, den es seit 1922 gibt.',
            'Mit den Bauern aus Dalarna und der Hilfe der Hansestadt Lübeck führte Gustav einen Befreiungskrieg. Am 6. Juni 1523 wählte ihn ein Reichstag in Strängnäs zum König; der 6. Juni ist heute Schwedens Nationalfeiertag. Kurz danach zog er in Stockholm ein. Die Kalmarer Union war damit für Schweden zu Ende. Doch Gustav hatte hohe Schulden bei Lübeck.',
            'Um sie zu bezahlen, griff er nach dem Reichtum der Kirche. Auf dem Reichstag von Västerås 1527 wurden die Kirchengüter der Krone übertragen. Die Brüder Olaus und Laurentius Petri verbreiteten die Lehre Martin Luthers; Laurentius wurde 1531 der erste lutherische Erzbischof. 1541 erschien die erste vollständige Bibel auf Schwedisch, die „Gustav-Wasa-Bibel“, die die schwedische Schriftsprache prägte.',
            'Gustav baute einen starken Zentralstaat auf, mit Vögten im ganzen Land, und kümmerte sich um vieles selbst. 1544 machte der Reichstag von Västerås Schweden zur Erbmonarchie. Gegen seine harte Herrschaft gab es Aufstände; der größte war die Dacke-Fehde 1542/43, ein Bauernaufstand in Småland unter Nils Dacke.',
            'Gustav Wasa starb 1560. Er gilt als „Landesvater“ und Gründer des modernen Schweden; sein Wappen, die Wasa-Garbe, ist eine Getreidegarbe. Auf ihn folgten nacheinander seine Söhne Erik XIV., Johann III. und Karl IX. Erik XIV. wurde abgesetzt und starb in Gefangenschaft – der Legende nach an vergifteter Erbsensuppe.',
          ],
          quiz: {
            leicht: [
              ['Wer befreite Schweden von der dänischen Herrschaft?', 'Gustav Wasa', ['Christian II.', 'Sten Sture', 'Engelbrekt']],
              ['Wann wurde Gustav Wasa König?', '1523', ['1520', '1397', '1560']],
              ['Welcher Tag ist Schwedens Nationalfeiertag?', 'Der 6. Juni', ['Der 1. Mai', 'Der 13. Dezember', 'Der 17. Mai']],
              ['Wohin floh Gustav nach dem Blutbad?', 'Nach Dalarna', ['Nach Dänemark', 'Nach Gotland', 'Nach Finnland']],
              ['Womit floh Gustav Richtung Norwegen?', 'Auf Skiern', ['Mit dem Schiff', 'Auf einem Pferd', 'Mit einem Schlitten voller Gold']],
              ['Welcher Skilauf erinnert an Gustav Wasa?', 'Der Wasalauf', ['Der Engadiner', 'Der Birkebeiner', 'Der Holmenkollen']],
              ['Wie lang ist der Wasalauf?', '90 Kilometer', ['9 Kilometer', '900 Kilometer', '42 Kilometer']],
              ['Welche Hansestadt half Gustav Wasa?', 'Lübeck', ['Hamburg', 'Bremen', 'Danzig']],
              ['Welche Union endete für Schweden 1523?', 'Die Kalmarer Union', ['Die Hanse', 'Die Iberische Union', 'Die Union mit Norwegen']],
              ['Welche Lehre führte Gustav Wasa in Schweden ein?', 'Die Lehre Luthers', ['Die Lehre Calvins', 'Den Katholizismus', 'Den Islam']],
              ['Was nahm Gustav Wasa der Kirche?', 'Ihre Güter', ['Ihre Glocken', 'Ihre Sprache', 'Nichts']],
              ['Warum brauchte Gustav Wasa Geld?', 'Er hatte Schulden bei Lübeck', ['Er wollte Amerika entdecken', 'Er baute ein Schloss in Paris', 'Er bezahlte Dänemark']],
              ['Wie heißt die erste vollständige Bibel auf Schwedisch?', 'Gustav-Wasa-Bibel', ['Lutherbibel', 'Gutenbergbibel', 'Silberbibel']],
              ['Wann erschien die Gustav-Wasa-Bibel?', '1541', ['1523', '1611', '1397']],
              ['Was ist das Wappen der Wasa?', 'Eine Getreidegarbe', ['Ein Löwe', 'Drei Kronen', 'Ein Drache']],
              ['Als was gilt Gustav Wasa heute?', 'Als Landesvater', ['Als Tyrann', 'Als Heiliger', 'Als Wikinger']],
              ['Wann starb Gustav Wasa?', '1560', ['1523', '1611', '1544']],
              ['Wie wurde die Königswürde ab 1544 vergeben?', 'Durch Erbe', ['Durch Wahl', 'Durch den Papst', 'Durch Los']],
              ['Wie hieß der größte Bauernaufstand gegen Gustav Wasa?', 'Dacke-Fehde', ['Engelbrekt-Aufstand', 'Stockholmer Blutbad', 'Bauernkrieg von Dalarna']],
              ['Welcher Sohn folgte Gustav Wasa zuerst?', 'Erik XIV.', ['Karl IX.', 'Gustav II. Adolf', 'Johann III.']],
            ],
            mittel: [
              ['Wie hieß Gustav Wasa mit Geburtsnamen?', 'Gustav Eriksson', ['Gustav Sture', 'Gustav Trolle', 'Gustav Petri']],
              ['Was geschah mit Gustavs Vater?', 'Er wurde beim Stockholmer Blutbad hingerichtet', ['Er wurde König', 'Er fiel bei Brunkeberg', 'Er floh nach Lübeck']],
              ['Wie reagierten die Bauern in Dalarna zuerst auf Gustav?', 'Sie wiesen ihn ab', ['Sie krönten ihn sofort', 'Sie lieferten ihn aus', 'Sie zogen mit ihm nach Dänemark']],
              ['Wo holten die Skiläufer Gustav ein?', 'In Sälen', ['In Mora', 'In Stockholm', 'In Strängnäs']],
              ['Wo endet der Wasalauf?', 'In Mora', ['In Sälen', 'In Stockholm', 'In Uppsala']],
              ['Seit wann gibt es den Wasalauf?', 'Seit 1922', ['Seit 1523', 'Seit 1800', 'Seit 1972']],
              ['Wo wurde Gustav Wasa zum König gewählt?', 'In Strängnäs', ['In Stockholm', 'In Uppsala', 'In Kalmar']],
              ['Welcher Reichstag übertrug 1527 die Kirchengüter an die Krone?', 'Der Reichstag von Västerås', ['Der Reichstag von Arboga', 'Der Reichstag von Worms', 'Der Reichstag von Strängnäs']],
              ['Welche Brüder verbreiteten Luthers Lehre in Schweden?', 'Olaus und Laurentius Petri', ['Kyrill und Method', 'Jacob und Wilhelm Grimm', 'Sten und Svante Sture']],
              ['Wer wurde 1531 der erste lutherische Erzbischof?', 'Laurentius Petri', ['Olaus Petri', 'Gustav Trolle', 'Martin Luther']],
              ['Was prägte die Gustav-Wasa-Bibel?', 'Die schwedische Schriftsprache', ['Die dänische Sprache', 'Die Runenschrift', 'Die lateinische Messe']],
              ['Was baute Gustav Wasa auf?', 'Einen starken Zentralstaat', ['Ein Kolonialreich in Amerika', 'Eine Republik', 'Eine Hanse']],
              ['Wen setzte Gustav im ganzen Land ein?', 'Vögte', ['Bischöfe aus Rom', 'Dänische Beamte', 'Hansekaufleute']],
              ['Welcher Reichstag machte Schweden 1544 zur Erbmonarchie?', 'Der Reichstag von Västerås', ['Der Reichstag von Arboga', 'Der Reichstag von Strängnäs', 'Der Reichstag von Uppsala']],
              ['In welcher Landschaft fand die Dacke-Fehde statt?', 'In Småland', ['In Dalarna', 'In Lappland', 'In Uppland']],
              ['Wer führte die Dacke-Fehde an?', 'Nils Dacke', ['Engelbrekt', 'Sten Sture', 'Olaus Petri']],
              ['Wann fand die Dacke-Fehde statt?', '1542/43', ['1520/21', '1560/61', '1434/35']],
              ['Welche Söhne Gustav Wasas wurden König?', 'Erik XIV., Johann III. und Karl IX.', ['Gustav II. Adolf und Karl X.', 'Karl XI. und Karl XII.', 'Christian und Friedrich']],
              ['Was geschah mit Erik XIV.?', 'Er wurde abgesetzt und starb in Gefangenschaft', ['Er fiel in der Schlacht', 'Er wurde Papst', 'Er floh nach Amerika']],
              ['Woran soll Erik XIV. gestorben sein?', 'An vergifteter Erbsensuppe', ['An der Pest', 'An einem Sturz vom Pferd', 'An Kälte auf Skiern']],
            ],
            schwer: [
              ['Was war die Wasa-Familie?', 'Ein Adelsgeschlecht', ['Eine Bauernfamilie aus Dalarna', 'Eine dänische Königsfamilie', 'Eine Kaufmannsfamilie aus Lübeck']],
              ['Warum schickten die Bauern Gustav doch Skiläufer hinterher?', 'Sie hörten von den Grausamkeiten Christians', ['Sie wollten ihn ausliefern', 'Er hatte ihnen Gold versprochen', 'Der Papst befahl es']],
              ['Wie viele Skiläufer holten Gustav zurück?', 'Zwei', ['Einer', 'Zehn', 'Hundert']],
              ['Wann zog Gustav Wasa in Stockholm ein?', 'Kurz nach seiner Wahl 1523', ['1520', '1527', '1544']],
              ['Wann wurden die Kirchengüter der Krone übertragen?', '1527', ['1523', '1531', '1541']],
              ['Wann wurde Laurentius Petri Erzbischof?', '1531', ['1527', '1541', '1523']],
              ['Wann wurde Schweden Erbmonarchie?', '1544', ['1523', '1560', '1527']],
              ['Wer folgte nach Erik XIV. als König?', 'Johann III.', ['Karl IX.', 'Gustav II. Adolf', 'Christian II.']],
              ['Welcher Sohn Gustav Wasas wurde als dritter König?', 'Karl IX.', ['Erik XIV.', 'Johann III.', 'Gustav II. Adolf']],
              ['Wie kümmerte sich Gustav Wasa um die Regierung?', 'Er kümmerte sich um vieles selbst', ['Er überließ alles den Dänen', 'Er regierte vom Ausland aus', 'Er ließ den Reichstag allein entscheiden']],
              ['Wofür nutzte Gustav Wasa die Kirchengüter?', 'Um seine Schulden bei Lübeck zu bezahlen', ['Um Klöster zu bauen', 'Um Rom zu unterstützen', 'Um Amerika zu entdecken']],
              ['Was war das Ziel der Dacke-Fehde?', 'Ein Aufstand gegen Gustavs harte Herrschaft', ['Die Rückkehr der Union', 'Die Eroberung Dänemarks', 'Die Wahl eines neuen Papstes']],
              ['Von welchem Ort startet der Wasalauf?', 'Von Sälen', ['Von Mora', 'Von Strängnäs', 'Von Stockholm']],
              ['Was ist die Wasa-Garbe?', 'Das Wappen der Wasa', ['Eine Skimarke', 'Eine Bibel', 'Eine Münze aus Lübeck']],
              ['Welche Rolle spielte Lübeck für Gustav Wasa?', 'Es half im Befreiungskrieg und verlangte Geld', ['Es kämpfte für Dänemark', 'Es war seine Hauptstadt', 'Es lieferte die Bibel']],
              ['Was erschien 1541 erstmals vollständig auf Schwedisch?', 'Die Bibel', ['Das Landrecht', 'Eine Zeitung', 'Eine Landkarte']],
              ['Welcher Bruder Petri war nicht Erzbischof?', 'Olaus Petri', ['Laurentius Petri', 'Beide waren Erzbischöfe', 'Keiner war Prediger']],
              ['Mit wem führte Gustav seinen Befreiungskrieg?', 'Mit den Bauern aus Dalarna', ['Mit dänischen Rittern', 'Mit russischen Truppen', 'Mit dem Papst']],
              ['Wovon war der 6. Juni 1523 der Tag?', 'Von Gustav Wasas Wahl zum König', ['Vom Stockholmer Blutbad', 'Von der Gründung Stockholms', 'Von der Reformation']],
              ['Wen hatte Christian II. hingerichtet, was Gustav antrieb?', 'Gustavs Vater', ['Gustavs Lehrer', 'Gustavs Frau', 'Gustavs König Erik']],
            ],
          },
        },
      ],
    },
  ],
};
