import type { Epoch } from '../types';

export const E3: Epoch = {
  id: 'grossmacht',
  name: 'Großmacht und Neutralität',
  period: '1611–1914',
  events: [
    {
      id: 'grossmacht',
      title: 'Schweden als Großmacht',
      date: '1611–1809',
      text: [
        'Im 17. Jahrhundert wurde Schweden unter Gustav II. Adolf zur Großmacht, die die Ostsee beherrschte. Nach der Niederlage Karls XII. bei Poltawa ging diese Stellung 1721 verloren. Es folgten die parlamentarische „Freiheitszeit“, eine Blüte der Wissenschaften und 1809 der Verlust Finnlands.',
      ],
      subtopics: [
        {
          id: 'gustav-adolf',
          title: 'Gustav II. Adolf, die Vasa und Königin Christina',
          date: '1611–1654',
          text: [
            '1611 wurde Gustav II. Adolf mit 16 Jahren König. Sein Kanzler Axel Oxenstierna baute eine moderne Verwaltung mit Fachbehörden auf. Gustav Adolf führte Kriege gegen Dänemark, Russland und Polen: Im Frieden von Stolbovo 1617 erhielt Schweden Ingermanland und schnitt Russland von der Ostsee ab, 1621 eroberte es Riga. Ziel war die Herrschaft über die Ostsee, das „Dominium maris Baltici“.',
            '1628 sollte das prächtige Kriegsschiff „Vasa“ die Macht des Königs zeigen. Doch auf seiner Jungfernfahrt im Stockholmer Hafen kenterte es nach nur rund 1300 Metern, weil es zu schmal und mit zwei Kanonendecks zu kopflastig war. 1961 wurde das Wrack gehoben; heute steht es im Vasa-Museum in Stockholm und ist zu über 95 Prozent original erhalten.',
            '1630 landete Gustav Adolf in Pommern und griff in den Dreißigjährigen Krieg ein, um den Protestanten zu helfen und Schwedens Macht an der Ostsee zu sichern; Frankreich unterstützte ihn mit Geld. 1631 siegte er bei Breitenfeld über die kaiserlichen Truppen, und man nannte ihn den „Löwen aus Mitternacht“. Seine Armee war modern: Soldaten wurden im eigenen Land ausgehoben, leichte Kanonen machten sie beweglich. 1632 fiel Gustav Adolf in der Schlacht bei Lützen.',
            'Seine Tochter Christina war erst sechs Jahre alt; für sie regierte Oxenstierna. Im Westfälischen Frieden 1648 erhielt Schweden Vorpommern, Wismar sowie Bremen und Verden und damit Sitz und Stimme im Reichstag des Heiligen Römischen Reiches. Christina war sehr gebildet und holte den französischen Philosophen René Descartes nach Stockholm, der dort 1650 an einer Lungenentzündung starb. 1654 dankte sie ab, trat zum katholischen Glauben über und lebte in Rom; sie ist im Petersdom begraben.',
            'Von 1638 bis 1655 besaß Schweden eine Kolonie in Nordamerika, Neuschweden am Delaware-Fluss, mit dem Fort Christina im heutigen Wilmington. Das Kupferbergwerk von Falun machte Schweden zum größten Kupferproduzenten Europas. Der niederländische Unternehmer Louis De Geer baute mit Fachleuten aus Wallonien die schwedische Eisenindustrie auf.',
          ],
          quiz: {
            leicht: [
              ['Welcher König machte Schweden zur Großmacht?', 'Gustav II. Adolf', ['Gustav Wasa', 'Karl XII.', 'Gustav III.']],
              ['Mit wie vielen Jahren wurde Gustav II. Adolf König?', 'Mit 16', ['Mit 6', 'Mit 30', 'Mit 45']],
              ['Wer war Gustav Adolfs Kanzler?', 'Axel Oxenstierna', ['Louis De Geer', 'René Descartes', 'Carl von Linné']],
              ['Welches Meer wollte Schweden beherrschen?', 'Die Ostsee', ['Die Nordsee', 'Das Mittelmeer', 'Das Schwarze Meer']],
              ['Wie hieß das Kriegsschiff, das 1628 sank?', 'Vasa', ['Titanic', 'Mary Rose', 'Victory']],
              ['Wann kenterte die Vasa?', '1628', ['1611', '1632', '1961']],
              ['Wann wurde die Vasa gehoben?', '1961', ['1628', '1900', '2001']],
              ['Wo steht die Vasa heute?', 'Im Vasa-Museum in Stockholm', ['Im Hafen von Göteborg', 'Auf dem Meeresgrund', 'In London']],
              ['In welchen großen Krieg griff Gustav Adolf ein?', 'In den Dreißigjährigen Krieg', ['In den Hundertjährigen Krieg', 'In den Siebenjährigen Krieg', 'In den Ersten Weltkrieg']],
              ['Wem wollte Gustav Adolf im Dreißigjährigen Krieg helfen?', 'Den Protestanten', ['Den Katholiken', 'Dem Kaiser', 'Den Osmanen']],
              ['Wie nannte man Gustav Adolf?', 'Löwe aus Mitternacht', ['Eiserner König', 'Sonnenkönig', 'Löwenherz']],
              ['Wo fiel Gustav Adolf 1632?', 'Bei Lützen', ['Bei Breitenfeld', 'Bei Poltawa', 'Bei Narva']],
              ['Wer folgte Gustav Adolf auf den Thron?', 'Seine Tochter Christina', ['Sein Sohn Karl', 'Sein Kanzler Oxenstierna', 'Sein Bruder Johann']],
              ['Welcher Frieden beendete 1648 den Dreißigjährigen Krieg?', 'Der Westfälische Frieden', ['Der Frieden von Roskilde', 'Der Frieden von Nystad', 'Der Frieden von Stolbovo']],
              ['Welches Gebiet erhielt Schweden 1648 unter anderem?', 'Vorpommern', ['Bayern', 'Sachsen', 'Böhmen']],
              ['Welchen Philosophen holte Christina nach Stockholm?', 'René Descartes', ['Voltaire', 'Immanuel Kant', 'Platon']],
              ['Zu welchem Glauben trat Christina über?', 'Zum katholischen', ['Zum jüdischen', 'Zum islamischen', 'Zum orthodoxen']],
              ['Wo ist Königin Christina begraben?', 'Im Petersdom in Rom', ['In Stockholm', 'In Uppsala', 'In Paris']],
              ['Wie hieß Schwedens Kolonie in Nordamerika?', 'Neuschweden', ['Neu-Amsterdam', 'Neufrankreich', 'Neuengland']],
              ['Welches Metall machte Schweden reich?', 'Kupfer', ['Gold', 'Silber', 'Uran']],
            ],
            mittel: [
              ['Was baute Oxenstierna auf?', 'Eine moderne Verwaltung mit Fachbehörden', ['Eine Kolonie in Afrika', 'Eine Universität in Rom', 'Ein Kanalnetz']],
              ['Gegen welche Länder führte Gustav Adolf Krieg?', 'Gegen Dänemark, Russland und Polen', ['Gegen England, Frankreich und Spanien', 'Gegen Norwegen und Finnland', 'Gegen die Niederlande']],
              ['Was erhielt Schweden im Frieden von Stolbovo?', 'Ingermanland', ['Finnland', 'Schonen', 'Pommern']],
              ['Wovon schnitt Schweden Russland 1617 ab?', 'Von der Ostsee', ['Vom Schwarzen Meer', 'Von Sibirien', 'Vom Kaspischen Meer']],
              ['Welche Stadt eroberte Schweden 1621?', 'Riga', ['Danzig', 'Moskau', 'Kopenhagen']],
              ['Wie heißt Schwedens Ziel der Ostseeherrschaft auf Lateinisch?', 'Dominium maris Baltici', ['Mare nostrum', 'Pax Romana', 'Imperium Sueciae']],
              ['Wie weit fuhr die Vasa, bevor sie kenterte?', 'Rund 1300 Meter', ['Rund 13 Kilometer', 'Rund 130 Kilometer', 'Bis nach Finnland']],
              ['Warum kenterte die Vasa?', 'Sie war zu schmal und kopflastig', ['Ein Feind versenkte sie', 'Ein Eisberg traf sie', 'Ein Feuer brach aus']],
              ['Wie viel der Vasa ist original erhalten?', 'Über 95 Prozent', ['Rund 10 Prozent', 'Rund 50 Prozent', 'Nichts, sie ist nachgebaut']],
              ['Wo landete Gustav Adolf 1630?', 'In Pommern', ['In Bayern', 'In Dänemark', 'In Russland']],
              ['Welches Land unterstützte Gustav Adolf mit Geld?', 'Frankreich', ['Spanien', 'England', 'Polen']],
              ['Wo siegte Gustav Adolf 1631?', 'Bei Breitenfeld', ['Bei Lützen', 'Bei Narva', 'Bei Poltawa']],
              ['Was machte Gustav Adolfs Armee beweglich?', 'Leichte Kanonen', ['Kriegselefanten', 'Eisenbahnen', 'Luftschiffe']],
              ['Wie alt war Christina beim Tod ihres Vaters?', 'Sechs Jahre', ['Sechzehn Jahre', 'Zwei Jahre', 'Dreißig Jahre']],
              ['Was erhielt Schweden 1648 außer Vorpommern?', 'Wismar sowie Bremen und Verden', ['Hamburg und Lübeck', 'Berlin und Potsdam', 'Prag und Wien']],
              ['Was bekam Schweden 1648 im Reichstag des Heiligen Römischen Reiches?', 'Sitz und Stimme', ['Die Kaiserkrone', 'Gar nichts', 'Ein Verbot']],
              ['Woran starb Descartes in Stockholm?', 'An einer Lungenentzündung', ['An der Pest', 'In einem Duell', 'Bei einem Schiffsunglück']],
              ['Wann dankte Christina ab?', '1654', ['1648', '1632', '1689']],
              ['An welchem Fluss lag Neuschweden?', 'Am Delaware', ['Am Hudson', 'Am Mississippi', 'Am Sankt-Lorenz-Strom']],
              ['Wer baute die schwedische Eisenindustrie mit auf?', 'Louis De Geer', ['Axel Oxenstierna', 'René Descartes', 'Gustav Wasa']],
            ],
            schwer: [
              ['Wann schloss Schweden den Frieden von Stolbovo?', '1617', ['1611', '1621', '1648']],
              ['Wie viele Kanonendecks hatte die Vasa?', 'Zwei', ['Eines', 'Drei', 'Fünf']],
              ['Wann landete Gustav Adolf in Pommern?', '1630', ['1628', '1632', '1618']],
              ['Gegen wessen Truppen siegte Gustav Adolf bei Breitenfeld?', 'Gegen die kaiserlichen Truppen', ['Gegen die Dänen', 'Gegen die Russen', 'Gegen die Franzosen']],
              ['Wann starb Descartes in Stockholm?', '1650', ['1648', '1654', '1632']],
              ['Wann bestand Neuschweden?', '1638–1655', ['1611–1632', '1700–1721', '1809–1905']],
              ['Wie hieß das Fort in Neuschweden?', 'Fort Christina', ['Fort Gustav', 'Fort Stockholm', 'Fort Oxenstierna']],
              ['In welcher heutigen Stadt lag Fort Christina?', 'In Wilmington', ['In New York', 'In Boston', 'In Chicago']],
              ['Woher kamen die Fachleute für die Eisenindustrie?', 'Aus Wallonien', ['Aus Schottland', 'Aus Italien', 'Aus Russland']],
              ['Woher stammte Louis De Geer?', 'Aus den Niederlanden', ['Aus Frankreich', 'Aus Deutschland', 'Aus England']],
              ['Was machte Falun Schweden?', 'Zum größten Kupferproduzenten Europas', ['Zum größten Goldproduzenten der Welt', 'Zum größten Salzproduzenten', 'Zum größten Weinproduzenten']],
              ['Wie wurden Gustav Adolfs Soldaten gewonnen?', 'Sie wurden im eigenen Land ausgehoben', ['Es waren nur Söldner aus Italien', 'Es waren Freiwillige aus Amerika', 'Es waren Gefangene']],
              ['Wer regierte für die junge Christina?', 'Axel Oxenstierna', ['Gustav Wasa', 'Louis De Geer', 'Karl X. Gustav']],
              ['Was tat Christina nach ihrer Abdankung?', 'Sie lebte in Rom', ['Sie ging nach Neuschweden', 'Sie heiratete den Zaren', 'Sie wurde Nonne in Vadstena']],
              ['Wofür nutzte Gustav Adolf das Geld aus Frankreich?', 'Für seinen Krieg in Deutschland', ['Für den Bau der Vasa', 'Für die Kolonie', 'Für die Universität']],
              ['Was sollte die Vasa zeigen?', 'Die Macht des Königs', ['Die Armut Schwedens', 'Den Frieden mit Polen', 'Den neuen Glauben']],
              ['Welche Stadt im Baltikum gehörte ab 1621 zu Schweden?', 'Riga', ['Tallinn', 'Vilnius', 'Königsberg']],
              ['Mit welchem Land kämpfte Schweden um Livland und Riga?', 'Mit Polen', ['Mit England', 'Mit Spanien', 'Mit Norwegen']],
              ['Wo kenterte die Vasa?', 'Im Stockholmer Hafen', ['Vor Göteborg', 'In der Nordsee', 'Vor Riga']],
              ['Was wurde 1632 in der Schlacht bei Lützen entschieden?', 'Gustav Adolf fiel', ['Schweden verlor Pommern', 'Der Krieg endete', 'Christina wurde gekrönt']],
            ],
          },
        },
        {
          id: 'karl-xii',
          title: 'Höhepunkt und Ende der Großmacht',
          date: '1654–1721',
          text: [
            'Karl X. Gustav führte 1658 sein Heer im Winter über das zugefrorene Meer, den Kleinen und den Großen Belt, bis auf die dänische Insel Seeland. Im Frieden von Roskilde musste Dänemark Schonen, Halland, Blekinge und Bohuslän abtreten. Damit erreichte Schweden im Süden seine heutigen Grenzen und seine größte Ausdehnung.',
            'Sein Sohn Karl XI. verlor 1675 bei Fehrbellin gegen Brandenburg, besiegte aber 1676 die Dänen in der Schlacht von Lund, der blutigsten Schlacht Skandinaviens. Ab 1680 regierte er absolutistisch und holte in der „Reduktion“ viele Güter, die der Adel erhalten hatte, an die Krone zurück. Im „Einteilungswerk“ mussten Gruppen von Bauernhöfen je einen Soldaten stellen und ihm ein kleines Haus geben.',
            '1697 wurde Karl XII. mit nur 15 Jahren König. 1700 griffen Dänemark, Sachsen-Polen und Russland Schweden gemeinsam an – der Große Nordische Krieg begann. Karl XII. siegte im selben Jahr bei Narva in einem Schneesturm über ein viel größeres russisches Heer. Danach kämpfte er jahrelang in Polen.',
            '1708 zog er gegen Russland. Nach dem harten Winter 1708/09 erlitt sein erschöpftes Heer 1709 bei Poltawa in der heutigen Ukraine eine vernichtende Niederlage gegen Zar Peter den Großen. Karl floh ins Osmanische Reich und blieb fünf Jahre in Bender. 1714 ritt er in nur 15 Tagen quer durch Europa nach Stralsund.',
            '1718 wurde Karl XII. bei der Belagerung der Festung Fredriksten in Norwegen durch einen Kopfschuss getötet; ob die Kugel vom Feind oder aus den eigenen Reihen kam, ist bis heute umstritten. Im Frieden von Nystad 1721 musste Schweden Livland, Estland, Ingermanland und Teile Kareliens an Russland abtreten. Damit war Schwedens Zeit als Großmacht vorbei, und Russland wurde die neue Macht an der Ostsee.',
          ],
          quiz: {
            leicht: [
              ['Über welches zugefrorene Meer führte Karl X. Gustav sein Heer?', 'Über den Belt', ['Über den Bodensee', 'Über die Nordsee', 'Über das Schwarze Meer']],
              ['Auf welche dänische Insel zog Karl X. Gustav 1658?', 'Seeland', ['Bornholm', 'Gotland', 'Island']],
              ['Welcher Frieden brachte Schweden 1658 Schonen?', 'Der Frieden von Roskilde', ['Der Frieden von Nystad', 'Der Westfälische Frieden', 'Der Kieler Frieden']],
              ['Welche Landschaft musste Dänemark 1658 abtreten?', 'Schonen', ['Jütland', 'Seeland', 'Holstein']],
              ['Was erreichte Schweden 1658 im Süden?', 'Seine heutigen Grenzen', ['Das Mittelmeer', 'Die Alpen', 'Den Rhein']],
              ['Wo verlor Karl XI. 1675?', 'Bei Fehrbellin', ['Bei Lund', 'Bei Poltawa', 'Bei Narva']],
              ['Welche Schlacht von 1676 war die blutigste Skandinaviens?', 'Die Schlacht von Lund', ['Die Schlacht von Narva', 'Die Schlacht von Lützen', 'Die Schlacht von Fehrbellin']],
              ['Wie regierte Karl XI. ab 1680?', 'Absolutistisch', ['Demokratisch', 'Als Republik', 'Gar nicht']],
              ['Mit wie vielen Jahren wurde Karl XII. König?', 'Mit 15', ['Mit 5', 'Mit 30', 'Mit 50']],
              ['Wann begann der Große Nordische Krieg?', '1700', ['1658', '1709', '1721']],
              ['Wo siegte Karl XII. 1700 über die Russen?', 'Bei Narva', ['Bei Poltawa', 'Bei Lund', 'Bei Stralsund']],
              ['Bei welchem Wetter fand die Schlacht von Narva statt?', 'In einem Schneesturm', ['In großer Hitze', 'Bei Nebel auf See', 'Im Regen am Meer']],
              ['Wo verlor Karl XII. 1709?', 'Bei Poltawa', ['Bei Narva', 'Bei Lund', 'Bei Breitenfeld']],
              ['Gegen welchen Zaren verlor Karl XII. bei Poltawa?', 'Peter den Großen', ['Iwan den Schrecklichen', 'Katharina die Große', 'Nikolaus II.']],
              ['In welchem heutigen Land liegt Poltawa?', 'In der Ukraine', ['In Polen', 'In Finnland', 'In Schweden']],
              ['Wohin floh Karl XII. nach Poltawa?', 'Ins Osmanische Reich', ['Nach Frankreich', 'Nach England', 'Nach Amerika']],
              ['Wo wurde Karl XII. 1718 getötet?', 'In Norwegen', ['In Russland', 'In Stockholm', 'In Polen']],
              ['Welcher Frieden beendete 1721 die Großmachtzeit?', 'Der Frieden von Nystad', ['Der Frieden von Roskilde', 'Der Frieden von Kiel', 'Der Westfälische Frieden']],
              ['Welches Land wurde nach 1721 die neue Macht an der Ostsee?', 'Russland', ['Dänemark', 'Polen', 'England']],
              ['Welches Gebiet musste Schweden 1721 abtreten?', 'Estland', ['Schonen', 'Gotland', 'Finnland ganz']],
            ],
            mittel: [
              ['Wann zog Karl X. Gustav über den zugefrorenen Belt?', '1658', ['1700', '1648', '1676']],
              ['Welche Landschaften gab Dänemark 1658 außer Schonen ab?', 'Halland, Blekinge und Bohuslän', ['Jütland und Fünen', 'Holstein und Schleswig', 'Norwegen und Island']],
              ['Wann erreichte Schweden seine größte Ausdehnung?', 'Nach dem Frieden von Roskilde 1658', ['Nach dem Frieden von Nystad 1721', 'Unter Gustav Wasa', 'Im Jahr 1905']],
              ['Gegen wen verlor Karl XI. bei Fehrbellin?', 'Gegen Brandenburg', ['Gegen Dänemark', 'Gegen Russland', 'Gegen Polen']],
              ['Gegen wen siegte Karl XI. bei Lund?', 'Gegen die Dänen', ['Gegen die Russen', 'Gegen die Brandenburger', 'Gegen die Polen']],
              ['Was war die „Reduktion“?', 'Die Rückholung von Adelsgütern an die Krone', ['Eine Verkleinerung der Armee', 'Eine Steuersenkung', 'Die Abschaffung der Monarchie']],
              ['Was mussten Bauernhöfe im Einteilungswerk stellen?', 'Einen Soldaten mit kleinem Haus', ['Ein Pferd für den König', 'Ein Schiff', 'Einen Priester']],
              ['Welche Länder griffen Schweden 1700 an?', 'Dänemark, Sachsen-Polen und Russland', ['England, Frankreich und Spanien', 'Preußen und Österreich', 'Norwegen und Finnland']],
              ['Wie groß war das russische Heer bei Narva im Vergleich?', 'Viel größer', ['Viel kleiner', 'Gleich groß', 'Es gab keines']],
              ['Wo kämpfte Karl XII. nach Narva jahrelang?', 'In Polen', ['In Frankreich', 'In Norwegen', 'In England']],
              ['Wann zog Karl XII. gegen Russland?', '1708', ['1700', '1718', '1721']],
              ['Was schwächte Karls Heer vor Poltawa?', 'Der harte Winter 1708/09', ['Eine Seuche in Stockholm', 'Ein Erdbeben', 'Ein Bündnis mit Dänemark']],
              ['Wo blieb Karl XII. im Osmanischen Reich?', 'In Bender', ['In Istanbul', 'In Bagdad', 'In Kairo']],
              ['Wie lange blieb Karl XII. im Osmanischen Reich?', 'Fünf Jahre', ['Fünf Wochen', 'Zwanzig Jahre', 'Bis zu seinem Tod']],
              ['Wohin ritt Karl XII. 1714 in 15 Tagen?', 'Nach Stralsund', ['Nach Stockholm', 'Nach Moskau', 'Nach Paris']],
              ['Welche Festung belagerte Karl XII. 1718?', 'Fredriksten', ['Narva', 'Kronborg', 'Stralsund']],
              ['Wie wurde Karl XII. getötet?', 'Durch einen Kopfschuss', ['Durch Gift', 'Durch einen Sturz vom Pferd', 'Durch Ertrinken']],
              ['Was ist an Karls Tod bis heute umstritten?', 'Ob die Kugel aus den eigenen Reihen kam', ['Ob er überhaupt starb', 'In welchem Jahr er starb', 'Ob er König war']],
              ['Welche Gebiete verlor Schweden 1721 außer Estland?', 'Livland, Ingermanland und Teile Kareliens', ['Schonen und Halland', 'Pommern und Bremen', 'Finnland und Gotland']],
              ['An wen gingen die Gebiete 1721?', 'An Russland', ['An Dänemark', 'An Preußen', 'An Polen']],
            ],
            schwer: [
              ['Wann siegte Karl XI. bei Lund?', '1676', ['1675', '1658', '1680']],
              ['Wann verlor Karl XI. bei Fehrbellin?', '1675', ['1676', '1658', '1700']],
              ['Ab wann regierte Karl XI. absolutistisch?', 'Ab 1680', ['Ab 1658', 'Ab 1697', 'Ab 1721']],
              ['Wann wurde Karl XII. König?', '1697', ['1700', '1680', '1718']],
              ['Wann wurde Karl XII. getötet?', '1718', ['1709', '1721', '1714']],
              ['Wann schloss Schweden den Frieden von Nystad?', '1721', ['1718', '1709', '1658']],
              ['Wann ritt Karl XII. nach Stralsund?', '1714', ['1709', '1718', '1700']],
              ['Welche beiden Meerengen überquerte Karl X. Gustav auf dem Eis?', 'Den Kleinen und den Großen Belt', ['Den Bosporus und die Dardanellen', 'Den Öresund und das Kattegat', 'Den Ärmelkanal und die Irische See']],
              ['Wer war der Vater Karls XI.?', 'Karl X. Gustav', ['Karl XII.', 'Gustav II. Adolf', 'Karl IX.']],
              ['Wie nennt man das System, in dem Bauern Soldaten stellten?', 'Einteilungswerk', ['Reduktion', 'Kalmarer Union', 'Freiheitszeit']],
              ['Was erhielt der Soldat im Einteilungswerk von den Bauern?', 'Ein kleines Haus', ['Ein Schiff', 'Ein Schloss', 'Einen Adelstitel']],
              ['Gegen wen kämpfte Schweden bei Narva?', 'Gegen Russland', ['Gegen Dänemark', 'Gegen Sachsen', 'Gegen Preußen']],
              ['Wo lag Bender?', 'Im Osmanischen Reich', ['In Polen', 'In Norwegen', 'In Russland']],
              ['Was war Schweden nach 1721 nicht mehr?', 'Eine Großmacht', ['Ein Königreich', 'Lutherisch', 'Unabhängig']],
              ['Was holte die Reduktion an die Krone zurück?', 'Güter, die der Adel erhalten hatte', ['Die Kolonie Neuschweden', 'Die Vasa', 'Finnland']],
              ['Welcher König zog über das Eis nach Dänemark?', 'Karl X. Gustav', ['Karl XII.', 'Karl XI.', 'Gustav II. Adolf']],
              ['Gegen wen gewann Karl XII. als Erstes im Großen Nordischen Krieg den Ruhm eines Feldherrn?', 'Gegen Russland bei Narva', ['Gegen Dänemark bei Lund', 'Gegen Polen bei Lützen', 'Gegen Norwegen bei Fredriksten']],
              ['Welche Region der heutigen Ukraine ist mit Schwedens Niederlage verbunden?', 'Poltawa', ['Krim', 'Donbass', 'Lwiw']],
              ['Woher kam der Angriff 1700?', 'Von drei Nachbarn gleichzeitig', ['Nur von Dänemark', 'Nur von England', 'Von den Osmanen']],
              ['Welche Festung liegt in Norwegen?', 'Fredriksten', ['Narva', 'Poltawa', 'Bender']],
            ],
          },
        },
        {
          id: 'freiheitszeit',
          title: 'Freiheitszeit, Linné und Gustav III.',
          date: '1719–1809',
          text: [
            'Nach dem Tod Karls XII. erhielt Schweden 1719 eine Verfassung, die die Macht des Königs stark beschränkte. Die Macht lag beim Reichstag mit seinen vier Ständen: Adel, Geistliche, Bürger und Bauern. Diese Zeit bis 1772 heißt „Freiheitszeit“. Zwei Parteien stritten miteinander: die „Hüte“, die Krieg gegen Russland und eine starke Wirtschaft wollten, und die vorsichtigeren „Mützen“. 1766 beschloss der Reichstag das erste Pressefreiheitsgesetz der Welt, das auch jedem das Recht gab, staatliche Akten einzusehen.',
            'Die Wissenschaft blühte. Carl von Linné (1707–1778) aus Uppsala ordnete Pflanzen und Tiere in ein System und gab jeder Art zwei lateinische Namen, etwa „Homo sapiens“ für den Menschen. Anders Celsius entwickelte 1742 eine Temperaturskala – ursprünglich war 0 der Siedepunkt und 100 der Gefrierpunkt. 1739 wurde die Königliche Akademie der Wissenschaften gegründet. Die Ostindien-Kompanie in Göteborg brachte ab 1731 Tee, Seide und Porzellan aus China.',
            '1772 riss König Gustav III. mit einem Staatsstreich wieder mehr Macht an sich. Er war ein Freund der Aufklärung und förderte die Künste: 1782 eröffnete er die Oper in Stockholm, und 1786 gründete er die Schwedische Akademie, die heute den Literaturnobelpreis vergibt. Im Krieg gegen Russland 1788–1790 siegte die schwedische Flotte 1790 in der Seeschlacht bei Svensksund.',
            'Viele Adlige hassten Gustav III. 1792 wurde er auf einem Maskenball in der Stockholmer Oper von dem Adligen Jacob Johan Anckarström angeschossen und starb an der Wunde. Giuseppe Verdi machte daraus später die Oper „Ein Maskenball“.',
            'Sein Sohn Gustav IV. Adolf war ein entschiedener Gegner Napoleons. Im Krieg gegen Russland 1808/09 verlor Schweden Finnland, rund ein Drittel seines Gebietes; Finnland wurde ein Großfürstentum unter dem Zaren. 1809 wurde Gustav IV. Adolf abgesetzt, und Schweden erhielt eine neue Verfassung mit Gewaltenteilung, die bis 1974 galt.',
          ],
          quiz: {
            leicht: [
              ['Wie heißt die Zeit von 1719 bis 1772?', 'Freiheitszeit', ['Großmachtzeit', 'Wikingerzeit', 'Volksheimzeit']],
              ['Wer hatte in der Freiheitszeit die Macht?', 'Der Reichstag', ['Der König', 'Der Zar', 'Die Kirche']],
              ['Wie viele Stände hatte der Reichstag?', 'Vier', ['Zwei', 'Drei', 'Sieben']],
              ['Wie hießen die beiden Parteien der Freiheitszeit?', 'Hüte und Mützen', ['Rote und Weiße', 'Whigs und Tories', 'Löwen und Adler']],
              ['Welches Gesetz beschloss Schweden 1766 als erstes Land der Welt?', 'Ein Pressefreiheitsgesetz', ['Ein Frauenwahlrecht', 'Ein Verbot der Sklaverei', 'Eine Schulpflicht']],
              ['Welcher Forscher ordnete Pflanzen und Tiere in ein System?', 'Carl von Linné', ['Anders Celsius', 'Alfred Nobel', 'Charles Darwin']],
              ['Wie viele lateinische Namen gab Linné jeder Art?', 'Zwei', ['Einen', 'Drei', 'Zehn']],
              ['Welchen lateinischen Namen gab Linné dem Menschen?', 'Homo sapiens', ['Homo erectus', 'Homo faber', 'Homo ludens']],
              ['Wer entwickelte eine Temperaturskala?', 'Anders Celsius', ['Carl von Linné', 'Gabriel Fahrenheit', 'Alfred Nobel']],
              ['Woher brachte die Ostindien-Kompanie Tee und Porzellan?', 'Aus China', ['Aus Amerika', 'Aus Afrika', 'Aus Australien']],
              ['In welcher Stadt saß die schwedische Ostindien-Kompanie?', 'In Göteborg', ['In Stockholm', 'In Malmö', 'In Uppsala']],
              ['Welcher König riss 1772 mit einem Staatsstreich Macht an sich?', 'Gustav III.', ['Karl XII.', 'Gustav IV. Adolf', 'Karl XIV. Johan']],
              ['Was gründete Gustav III. 1786?', 'Die Schwedische Akademie', ['Die Universität Uppsala', 'Die Nobelstiftung', 'Die Ostindien-Kompanie']],
              ['Welchen Preis vergibt die Schwedische Akademie heute?', 'Den Literaturnobelpreis', ['Den Friedensnobelpreis', 'Den Oscar', 'Den Grammy']],
              ['Wo wurde Gustav III. angeschossen?', 'Auf einem Maskenball in der Oper', ['In der Kirche', 'Auf einem Schiff', 'Auf der Jagd']],
              ['Welcher Komponist schrieb die Oper „Ein Maskenball“?', 'Giuseppe Verdi', ['Mozart', 'Wagner', 'Beethoven']],
              ['Welches Land verlor Schweden 1809?', 'Finnland', ['Norwegen', 'Estland', 'Pommern']],
              ['An wen fiel Finnland 1809?', 'An Russland', ['An Dänemark', 'An Deutschland', 'An Norwegen']],
              ['Wessen Gegner war Gustav IV. Adolf?', 'Napoleons', ['Peters des Großen', 'Linnés', 'Bernadottes']],
              ['Bis wann galt die Verfassung von 1809?', 'Bis 1974', ['Bis 1810', 'Bis 1905', 'Bis heute']],
            ],
            mittel: [
              ['Welche Stände gab es im Reichstag?', 'Adel, Geistliche, Bürger und Bauern', ['Könige, Ritter, Mönche und Sklaven', 'Arbeiter und Unternehmer', 'Nur Adel und Kirche']],
              ['Was wollten die „Hüte“?', 'Krieg gegen Russland und eine starke Wirtschaft', ['Frieden um jeden Preis', 'Die Rückkehr des Absolutismus', 'Den Anschluss an Dänemark']],
              ['Wie waren die „Mützen“ im Vergleich zu den „Hüten“?', 'Vorsichtiger', ['Kriegerischer', 'Königstreuer', 'Katholisch']],
              ['Welches Recht gab das Gesetz von 1766 außerdem?', 'Staatliche Akten einzusehen', ['Wählen zu gehen', 'Waffen zu tragen', 'Steuern zu verweigern']],
              ['Wann lebte Carl von Linné?', '1707–1778', ['1611–1632', '1833–1896', '1858–1940']],
              ['In welcher Stadt wirkte Linné?', 'In Uppsala', ['In Stockholm', 'In Göteborg', 'In Lund']],
              ['Wann entwickelte Celsius seine Temperaturskala?', '1742', ['1766', '1700', '1809']],
              ['Wie war die Celsius-Skala ursprünglich?', '0 war der Siedepunkt, 100 der Gefrierpunkt', ['0 war die Körpertemperatur', 'Sie ging bis 1000', 'Sie war genau wie heute']],
              ['Wann wurde die Königliche Akademie der Wissenschaften gegründet?', '1739', ['1786', '1477', '1901']],
              ['Ab wann handelte die Ostindien-Kompanie mit China?', 'Ab 1731', ['Ab 1638', 'Ab 1809', 'Ab 1866']],
              ['Was brachte die Ostindien-Kompanie außer Tee?', 'Seide und Porzellan', ['Kaffee und Kakao', 'Gold und Silber', 'Gewürze aus Amerika']],
              ['Wann eröffnete Gustav III. die Oper in Stockholm?', '1782', ['1772', '1792', '1809']],
              ['Wofür war Gustav III. bekannt?', 'Er förderte die Künste', ['Er verbot das Theater', 'Er war ein großer Seefahrer', 'Er war ein Gegner der Aufklärung']],
              ['Wo siegte die schwedische Flotte 1790?', 'Bei Svensksund', ['Bei Poltawa', 'Bei Narva', 'Bei Trafalgar']],
              ['Gegen wen führte Gustav III. 1788–1790 Krieg?', 'Gegen Russland', ['Gegen Dänemark', 'Gegen England', 'Gegen Frankreich']],
              ['Wer schoss auf Gustav III.?', 'Jacob Johan Anckarström', ['Axel von Fersen', 'Carl von Linné', 'Anders Celsius']],
              ['Wer hasste Gustav III. besonders?', 'Viele Adlige', ['Die Bauern', 'Die Künstler', 'Die Russen']],
              ['Wie viel Gebiet verlor Schweden mit Finnland?', 'Rund ein Drittel', ['Rund ein Zehntel', 'Rund die Hälfte', 'Fast alles']],
              ['Was wurde Finnland unter dem Zaren?', 'Ein Großfürstentum', ['Eine Republik', 'Ein Königreich', 'Eine Provinz Dänemarks']],
              ['Was erhielt Schweden 1809 mit der neuen Verfassung?', 'Gewaltenteilung', ['Eine Republik', 'Einen Zaren', 'Ein Einparteiensystem']],
            ],
            schwer: [
              ['Wann erhielt Schweden die Verfassung der Freiheitszeit?', '1719', ['1772', '1809', '1680']],
              ['Wann endete die Freiheitszeit?', '1772', ['1719', '1792', '1809']],
              ['Wann wurde Gustav III. angeschossen?', '1792', ['1772', '1786', '1809']],
              ['Wann wurde Gustav IV. Adolf abgesetzt?', '1809', ['1792', '1814', '1772']],
              ['Wann siegte Schweden bei Svensksund?', '1790', ['1788', '1809', '1721']],
              ['Wann war der Krieg, in dem Schweden Finnland verlor?', '1808/09', ['1788–1790', '1700–1721', '1814']],
              ['Woher stammte Linné?', 'Aus Uppsala', ['Aus Göteborg', 'Aus Stockholm', 'Aus Lund']],
              ['Was war 1742 auf der Celsius-Skala 100?', 'Der Gefrierpunkt', ['Der Siedepunkt', 'Die Körpertemperatur', 'Die Sommerhitze']],
              ['Welche Art von Herrscher war Gustav III.?', 'Ein Freund der Aufklärung', ['Ein Gegner jeder Kunst', 'Ein Wikinger', 'Ein Diktator ohne Reichstag']],
              ['Woran starb Gustav III.?', 'An einer Schusswunde', ['An der Pest', 'An Altersschwäche', 'Durch Ertrinken']],
              ['Welche Rolle hat die Schwedische Akademie heute?', 'Sie vergibt den Literaturnobelpreis', ['Sie wählt den König', 'Sie leitet die Oper', 'Sie verwaltet die Kirche']],
              ['Was war 1766 weltweit einzigartig?', 'Das Pressefreiheitsgesetz', ['Das Frauenwahlrecht', 'Die Schulpflicht', 'Die Abschaffung des Adels']],
              ['Unter wem stand Finnland nach 1809?', 'Unter dem Zaren', ['Unter dem schwedischen König', 'Unter dem Papst', 'Unter Napoleon']],
              ['Welche Partei der Freiheitszeit wollte Krieg?', 'Die Hüte', ['Die Mützen', 'Die Sozialdemokraten', 'Die Royalisten']],
              ['Wie lange galt die Verfassung von 1809?', 'Rund 165 Jahre', ['Ein Jahr', 'Rund 50 Jahre', 'Rund 500 Jahre']],
              ['Wofür steht „Homo sapiens“ bei Linné?', 'Für den Menschen', ['Für den Affen', 'Für den Hund', 'Für eine Pflanze']],
              ['Welche Einrichtung gründete Gustav III. 1782?', 'Die Oper in Stockholm', ['Die Schwedische Akademie', 'Die Akademie der Wissenschaften', 'Die Ostindien-Kompanie']],
              ['Welche Einrichtung entstand 1739?', 'Die Königliche Akademie der Wissenschaften', ['Die Schwedische Akademie', 'Die Oper', 'Die Universität Uppsala']],
              ['Welche Macht beschränkte die Verfassung von 1719 stark?', 'Die Macht des Königs', ['Die Macht des Reichstags', 'Die Macht der Bauern', 'Die Macht der Presse']],
              ['Welches Land war Ziel der „Hüte“-Politik?', 'Russland als Gegner', ['Dänemark als Verbündeter', 'England als Kolonie', 'China als Feind']],
            ],
          },
        },
      ],
    },
    {
      id: 'nobel',
      title: 'Bernadotte, Nobel und Auswanderung',
      date: '1809–1914',
      text: [
        'Ein französischer Marschall wurde als Karl XIV. Johan König und begründete das Haus Bernadotte. Seit 1814 hat Schweden keinen Krieg mehr geführt. Im 19. Jahrhundert wanderten über eine Million Schweden nach Amerika aus, während Erfinder wie Alfred Nobel und neue Industrien das Land veränderten.',
      ],
      subtopics: [
        {
          id: 'bernadotte-union',
          title: 'Bernadotte, Frieden und die Union mit Norwegen',
          date: '1809–1905',
          text: [
            'Der neue König Karl XIII. war alt und kinderlos. 1810 wählte der Reichstag überraschend den französischen Marschall Jean-Baptiste Bernadotte zum Kronprinzen, der als Karl Johan nach Schweden kam. Er hatte einst schwedische Kriegsgefangene gut behandelt. Statt Napoleon zu folgen, wandte er sich gegen ihn und kämpfte 1813 in der Völkerschlacht bei Leipzig auf Seiten der Verbündeten.',
            'Im Kieler Frieden 1814 musste Dänemark Norwegen an Schweden abtreten. Die Norweger gaben sich jedoch am 17. Mai 1814 in Eidsvoll eine eigene Verfassung. Nach einem kurzen Krieg einigte man sich: Norwegen behielt seine Verfassung, hatte aber denselben König wie Schweden. Dieser Krieg von 1814 war der letzte Krieg Schwedens – seitdem lebt das Land seit über 200 Jahren in Frieden.',
            '1818 wurde Bernadotte als Karl XIV. Johan König; das Haus Bernadotte regiert bis heute. Schweden verfolgte nun eine Politik der Neutralität. 1832 wurde der Göta-Kanal fertig, der Göteborg über Seen mit der Ostsee verbindet; rund 58.000 Soldaten hatten ihn gegraben.',
            '1842 führte Schweden die allgemeine Schulpflicht ein. 1866 ersetzte ein Parlament mit zwei Kammern den alten Ständereichstag. Auch Frauen erhielten mehr Rechte: Seit 1845 erbten Töchter genauso viel wie Söhne, und ab 1858 durften unverheiratete Frauen mit 25 Jahren selbst über ihr Leben bestimmen.',
            'Norwegen wollte immer mehr Selbstständigkeit, zum Beispiel eigene Konsulate im Ausland. Am 7. Juni 1905 erklärte das norwegische Parlament, das Storting, die Union für aufgelöst; in einer Volksabstimmung stimmten 99,95 Prozent der Norweger dafür. Schweden nahm die Trennung friedlich hin, und im Vertrag von Karlstad wurde ein Krieg vermieden. Norwegen wählte den dänischen Prinzen Carl als Haakon VII. zum König.',
          ],
          quiz: {
            leicht: [
              ['Welcher französische Marschall wurde schwedischer Kronprinz?', 'Jean-Baptiste Bernadotte', ['Joachim Murat', 'Michel Ney', 'Napoleon Bonaparte']],
              ['Wann wurde Bernadotte zum Kronprinzen gewählt?', '1810', ['1809', '1818', '1905']],
              ['Welchen Namen nahm Bernadotte in Schweden an?', 'Karl Johan', ['Gustav Adolf', 'Erik', 'Oskar']],
              ['Gegen wen wandte sich Bernadotte?', 'Gegen Napoleon', ['Gegen Russland', 'Gegen England', 'Gegen Preußen']],
              ['Welches Land musste Dänemark 1814 an Schweden abtreten?', 'Norwegen', ['Finnland', 'Island', 'Grönland']],
              ['Wo gaben sich die Norweger 1814 eine Verfassung?', 'In Eidsvoll', ['In Oslo', 'In Bergen', 'In Stockholm']],
              ['Welcher Tag ist mit der norwegischen Verfassung verbunden?', 'Der 17. Mai', ['Der 6. Juni', 'Der 7. Juni', 'Der 1. Mai']],
              ['Wann führte Schweden seinen letzten Krieg?', '1814', ['1809', '1905', '1945']],
              ['Wie lange lebt Schweden schon in Frieden?', 'Seit über 200 Jahren', ['Seit 20 Jahren', 'Seit 50 Jahren', 'Seit 1000 Jahren']],
              ['Welches Königshaus regiert Schweden bis heute?', 'Das Haus Bernadotte', ['Das Haus Wasa', 'Das Haus Windsor', 'Das Haus Oranien']],
              ['Welche Politik verfolgte Schweden nach 1814?', 'Neutralität', ['Eroberung', 'Kolonialismus', 'Bündnis mit Frankreich']],
              ['Welcher Kanal wurde 1832 fertig?', 'Der Göta-Kanal', ['Der Suezkanal', 'Der Nord-Ostsee-Kanal', 'Der Panamakanal']],
              ['Welche Stadt verbindet der Göta-Kanal mit der Ostsee?', 'Göteborg', ['Stockholm', 'Malmö', 'Kiruna']],
              ['Wann führte Schweden die allgemeine Schulpflicht ein?', '1842', ['1766', '1905', '1921']],
              ['Wann löste Norwegen die Union mit Schweden?', '1905', ['1814', '1866', '1945']],
              ['Wie reagierte Schweden auf die Trennung Norwegens?', 'Es nahm sie friedlich hin', ['Es erklärte Krieg', 'Es besetzte Oslo', 'Es trat aus der UNO aus']],
              ['Wie heißt das norwegische Parlament?', 'Storting', ['Riksdag', 'Folketing', 'Althing']],
              ['Wie viel Prozent der Norweger stimmten 1905 für die Trennung?', '99,95 Prozent', ['51 Prozent', '75 Prozent', '60 Prozent']],
              ['Wen wählte Norwegen 1905 zum König?', 'Den dänischen Prinzen Carl', ['Einen schwedischen Prinzen', 'Einen deutschen Fürsten', 'Niemanden']],
              ['Welchen Namen nahm der neue norwegische König an?', 'Haakon VII.', ['Olav V.', 'Harald I.', 'Oskar II.']],
            ],
            mittel: [
              ['Warum suchte Schweden 1810 einen Kronprinzen?', 'Karl XIII. war alt und kinderlos', ['Der König war gestorben', 'Napoleon verlangte es', 'Die Bauern wollten einen Franzosen']],
              ['Warum war Bernadotte bei Schweden beliebt?', 'Er hatte schwedische Kriegsgefangene gut behandelt', ['Er sprach Schwedisch', 'Er war mit dem König verwandt', 'Er war reich']],
              ['In welcher Schlacht kämpfte Bernadotte 1813?', 'In der Völkerschlacht bei Leipzig', ['Bei Waterloo', 'Bei Austerlitz', 'Bei Borodino']],
              ['In welchem Frieden erhielt Schweden Norwegen?', 'Im Kieler Frieden', ['Im Frieden von Nystad', 'Im Frieden von Roskilde', 'Im Wiener Frieden']],
              ['Was behielt Norwegen in der Union?', 'Seine eigene Verfassung', ['Seinen eigenen König', 'Seine eigene Armee unter Dänemark', 'Gar nichts']],
              ['Was hatten Schweden und Norwegen ab 1814 gemeinsam?', 'Denselben König', ['Dieselbe Verfassung', 'Dasselbe Parlament', 'Dieselbe Hauptstadt']],
              ['Wann wurde Bernadotte König?', '1818', ['1810', '1814', '1832']],
              ['Unter welchem Namen regierte Bernadotte?', 'Karl XIV. Johan', ['Karl XIII.', 'Gustav V.', 'Oskar I.']],
              ['Wie viele Soldaten gruben den Göta-Kanal?', 'Rund 58.000', ['Rund 580', 'Rund 5.800', 'Rund 580.000']],
              ['Was ersetzte 1866 den Ständereichstag?', 'Ein Parlament mit zwei Kammern', ['Eine Diktatur', 'Ein Rat der Bischöfe', 'Ein König ohne Parlament']],
              ['Was galt ab 1845 für Töchter?', 'Sie erbten genauso viel wie Söhne', ['Sie durften wählen', 'Sie mussten heiraten', 'Sie durften nicht erben']],
              ['Was durften unverheiratete Frauen ab 1858 mit 25 Jahren?', 'Selbst über ihr Leben bestimmen', ['Wählen gehen', 'König werden', 'In die Armee eintreten']],
              ['Was wollte Norwegen zum Beispiel haben?', 'Eigene Konsulate im Ausland', ['Eine eigene Kolonie', 'Eine eigene Ostseeflotte gegen Schweden', 'Einen Kanal nach Stockholm']],
              ['An welchem Tag erklärte das Storting die Union für aufgelöst?', 'Am 7. Juni 1905', ['Am 17. Mai 1905', 'Am 6. Juni 1905', 'Am 1. Januar 1905']],
              ['In welchem Vertrag wurde 1905 ein Krieg vermieden?', 'Im Vertrag von Karlstad', ['Im Kieler Frieden', 'Im Vertrag von Eidsvoll', 'Im Vertrag von Versailles']],
              ['Aus welchem Land stammte Haakon VII.?', 'Aus Dänemark', ['Aus Schweden', 'Aus Deutschland', 'Aus England']],
              ['Wer hatte Norwegen vor 1814 regiert?', 'Dänemark', ['Russland', 'England', 'Finnland']],
              ['Über welche Gewässer verbindet der Göta-Kanal Göteborg mit der Ostsee?', 'Über Seen', ['Über die Nordsee', 'Über Flüsse in Norwegen', 'Über einen Tunnel']],
              ['Wer war Karl XIII.?', 'Der alte, kinderlose König vor Bernadotte', ['Bernadottes Sohn', 'Ein dänischer König', 'Ein Zar']],
              ['Welche Haltung nahm Bernadotte zu Napoleon ein?', 'Er stellte sich gegen ihn', ['Er blieb sein treuester Marschall', 'Er wurde sein Schwiegersohn', 'Er war neutral']],
            ],
            schwer: [
              ['Was ist am Haus Bernadotte besonders?', 'Es stammt von einem französischen Marschall ab', ['Es stammt von den Wikingern ab', 'Es ist das älteste Haus Europas', 'Es stammt aus Norwegen']],
              ['Wann wurde der Göta-Kanal fertig?', '1832', ['1810', '1866', '1905']],
              ['Seit wann erbten Töchter genauso viel wie Söhne?', 'Seit 1845', ['Seit 1858', 'Seit 1921', 'Seit 1809']],
              ['Wann wurde der Ständereichstag ersetzt?', '1866', ['1842', '1809', '1905']],
              ['Wann erhielt Norwegen seine Verfassung?', '1814', ['1905', '1809', '1866']],
              ['Welcher Krieg war Schwedens letzter?', 'Der Krieg gegen Norwegen 1814', ['Der Krieg gegen Russland 1809', 'Der Erste Weltkrieg', 'Der Krieg gegen Dänemark 1864']],
              ['Wer erklärte 1905 die Union für aufgelöst?', 'Das Storting', ['Der schwedische König', 'Der Riksdag', 'Der dänische König']],
              ['Welcher Streitpunkt führte zur Trennung 1905?', 'Eigene norwegische Konsulate', ['Ein Grenzstreit um Lappland', 'Die Religion', 'Der Göta-Kanal']],
              ['Wie hieß Haakon VII. vor seiner Wahl?', 'Prinz Carl von Dänemark', ['Prinz Oskar von Schweden', 'Prinz Harald von Norwegen', 'Prinz Albert von England']],
              ['Mit welchen Truppen kämpfte Bernadotte 1813?', 'Mit den Verbündeten gegen Napoleon', ['Mit Napoleon gegen Russland', 'Mit Dänemark gegen Norwegen', 'Allein gegen England']],
              ['Wer grub den Göta-Kanal?', 'Soldaten', ['Kriegsgefangene aus Russland', 'Maschinen', 'Bauern aus Dänemark']],
              ['Wie wählte Schweden 1810 seinen Kronprinzen?', 'Durch den Reichstag', ['Durch Los', 'Durch Napoleon', 'Durch den Zaren']],
              ['Welches Ergebnis hatte die norwegische Volksabstimmung 1905?', 'Fast einstimmig für die Trennung', ['Knapp gegen die Trennung', 'Unentschieden', 'Sie fand nicht statt']],
              ['Was gab Dänemark 1814 auf?', 'Norwegen', ['Island', 'Schleswig', 'Grönland']],
              ['Was für eine Union bestand zwischen Schweden und Norwegen?', 'Eine Union mit gemeinsamem König', ['Ein einziger Staat', 'Ein Militärbündnis ohne König', 'Eine Kolonie']],
              ['Welches Prinzip galt für Schwedens Außenpolitik nach 1814?', 'Neutralität', ['Expansion', 'Kolonialismus', 'Bündnis mit Russland']],
              ['Was war Bernadotte vor 1810?', 'Ein französischer Marschall', ['Ein russischer General', 'Ein dänischer Prinz', 'Ein englischer Admiral']],
              ['Was erhielten Frauen 1858?', 'Unverheiratete wurden mit 25 mündig', ['Das Wahlrecht', 'Das Recht auf Militärdienst', 'Das Recht, König zu werden']],
              ['Was entstand 1866 in Schweden?', 'Ein Zweikammerparlament', ['Eine Republik', 'Die Schulpflicht', 'Der Göta-Kanal']],
              ['Wer durfte ab 1858 mit 25 Jahren selbst über sein Leben bestimmen?', 'Unverheiratete Frauen', ['Kinder', 'Soldaten', 'Norweger']],
            ],
          },
        },
        {
          id: 'industrie-nobel',
          title: 'Auswanderung, Industrie und Alfred Nobel',
          date: '1850–1914',
          text: [
            'Im 19. Jahrhundert wuchs die Bevölkerung schnell, und viele Menschen auf dem Land waren arm. Nach Missernten kam es 1867–1869 zu einer Hungersnot. Zwischen 1850 und 1930 wanderten rund 1,3 Millionen Schweden nach Nordamerika aus – etwa ein Fünftel der Bevölkerung. Viele siedelten in Minnesota oder in Chicago. Der Schriftsteller Vilhelm Moberg erzählte ihre Geschichte in seinen Romanen über „Die Auswanderer“.',
            'Die Industrialisierung kam spät, dann aber schnell. Sägewerke in Norrland verarbeiteten Holz, und in Kiruna wurde Eisenerz abgebaut, das ab 1902 mit der Erzbahn zum norwegischen Hafen Narvik gebracht wurde. Ab den 1850er-Jahren baute der Staat große Eisenbahnlinien. Schwedische Erfindungen gründeten Weltfirmen: Lars Magnus Ericsson baute ab 1876 Telefone, und 1907 wurde der Kugellagerhersteller SKF gegründet.',
            'Der bekannteste Erfinder war Alfred Nobel (1833–1896). Er experimentierte mit dem gefährlichen Sprengstoff Nitroglycerin; 1864 kam sein jüngerer Bruder Emil bei einer Explosion ums Leben. 1867 erfand Nobel das Dynamit, indem er Nitroglycerin mit einer Erde namens Kieselgur mischte und es so sicherer machte. Er besaß über 350 Patente und Fabriken in vielen Ländern. Als 1888 sein Bruder Ludvig starb, hielt eine Zeitung ihn selbst für tot und nannte ihn im Nachruf einen „Händler des Todes“.',
            'In seinem Testament von 1895 bestimmte Nobel, dass sein Vermögen in eine Stiftung fließen sollte. Aus ihren Zinsen werden jedes Jahr Preise für Physik, Chemie, Medizin, Literatur und Frieden vergeben. Die ersten Nobelpreise wurden 1901 verliehen, und zwar an Nobels Todestag, dem 10. Dezember. Den Friedensnobelpreis vergibt ein Komitee in Oslo, die anderen Preise werden in Stockholm verliehen. Seit 1969 gibt es zusätzlich einen Preis für Wirtschaftswissenschaften, gestiftet von der schwedischen Reichsbank.',
            'Große Volksbewegungen veränderten das Land: Freikirchen, die Abstinenzbewegung gegen den Alkohol und die Arbeiterbewegung. 1889 wurde die Sozialdemokratische Partei gegründet, die Hjalmar Branting prägte, 1898 der Gewerkschaftsbund LO. August Strindberg schrieb Dramen wie „Fräulein Julie“. Selma Lagerlöf schrieb „Nils Holgerssons wunderbare Reise“, ein Erdkundebuch für Schulkinder, und erhielt 1909 als erste Frau den Literaturnobelpreis.',
          ],
          quiz: {
            leicht: [
              ['Wohin wanderten im 19. Jahrhundert viele Schweden aus?', 'Nach Nordamerika', ['Nach Australien', 'Nach Afrika', 'Nach China']],
              ['Wie viele Schweden wanderten zwischen 1850 und 1930 aus?', 'Rund 1,3 Millionen', ['Rund 13.000', 'Rund 130.000', 'Rund 13 Millionen']],
              ['In welchen US-Bundesstaat zogen viele Schweden?', 'Nach Minnesota', ['Nach Texas', 'Nach Florida', 'Nach Kalifornien']],
              ['Wer schrieb Romane über „Die Auswanderer“?', 'Vilhelm Moberg', ['August Strindberg', 'Astrid Lindgren', 'Selma Lagerlöf']],
              ['Wo wird in Schweden Eisenerz abgebaut?', 'In Kiruna', ['In Malmö', 'In Göteborg', 'Auf Gotland']],
              ['Zu welchem norwegischen Hafen führt die Erzbahn?', 'Nach Narvik', ['Nach Oslo', 'Nach Bergen', 'Nach Trondheim']],
              ['Was baute Lars Magnus Ericsson?', 'Telefone', ['Autos', 'Flugzeuge', 'Kugellager']],
              ['Was stellt die Firma SKF her?', 'Kugellager', ['Telefone', 'Möbel', 'Dynamit']],
              ['Welcher Schwede erfand das Dynamit?', 'Alfred Nobel', ['Anders Celsius', 'Lars Magnus Ericsson', 'Carl von Linné']],
              ['Wann erfand Nobel das Dynamit?', '1867', ['1901', '1833', '1896']],
              ['Welchen gefährlichen Sprengstoff machte Nobel sicherer?', 'Nitroglycerin', ['Schwarzpulver', 'TNT', 'Uran']],
              ['Wie nannte eine Zeitung Nobel irrtümlich im Nachruf?', 'Händler des Todes', ['Vater des Friedens', 'König der Erfinder', 'Freund der Menschheit']],
              ['Was bestimmte Nobel in seinem Testament?', 'Jährliche Preise aus seinem Vermögen', ['Ein Denkmal für sich', 'Den Bau einer Kirche', 'Eine Fabrik für Dynamit']],
              ['Wann wurden die ersten Nobelpreise verliehen?', '1901', ['1867', '1896', '1969']],
              ['An welchem Tag werden die Nobelpreise verliehen?', 'Am 10. Dezember', ['Am 6. Juni', 'Am 1. Januar', 'Am 13. Dezember']],
              ['In welcher Stadt wird der Friedensnobelpreis vergeben?', 'In Oslo', ['In Stockholm', 'In Genf', 'In Uppsala']],
              ['Welche Partei wurde 1889 gegründet?', 'Die Sozialdemokratische Partei', ['Die Moderaten', 'Die Grünen', 'Die Liberalen']],
              ['Wer schrieb „Fräulein Julie“?', 'August Strindberg', ['Henrik Ibsen', 'Selma Lagerlöf', 'Astrid Lindgren']],
              ['Wer schrieb „Nils Holgerssons wunderbare Reise“?', 'Selma Lagerlöf', ['Astrid Lindgren', 'August Strindberg', 'Vilhelm Moberg']],
              ['Wer erhielt 1909 als erste Frau den Literaturnobelpreis?', 'Selma Lagerlöf', ['Marie Curie', 'Astrid Lindgren', 'Bertha von Suttner']],
            ],
            mittel: [
              ['Wann gab es in Schweden eine Hungersnot nach Missernten?', '1867–1869', ['1809–1811', '1901–1903', '1930–1932']],
              ['Welcher Anteil der Bevölkerung wanderte aus?', 'Etwa ein Fünftel', ['Etwa die Hälfte', 'Etwa ein Hundertstel', 'Fast alle']],
              ['In welche Stadt zogen viele schwedische Auswanderer?', 'Nach Chicago', ['Nach Miami', 'Nach Los Angeles', 'Nach New Orleans']],
              ['Was verarbeiteten die Sägewerke in Norrland?', 'Holz', ['Eisen', 'Fisch', 'Kupfer']],
              ['Ab wann fuhr die Erzbahn nach Narvik?', 'Ab 1902', ['Ab 1850', 'Ab 1876', 'Ab 1930']],
              ['Ab wann baute der Staat große Eisenbahnlinien?', 'Ab den 1850er-Jahren', ['Ab den 1750er-Jahren', 'Ab 1950', 'Ab 1902']],
              ['Ab wann baute Ericsson Telefone?', 'Ab 1876', ['Ab 1907', 'Ab 1850', 'Ab 1901']],
              ['Wann wurde SKF gegründet?', '1907', ['1876', '1901', '1889']],
              ['Wann lebte Alfred Nobel?', '1833–1896', ['1707–1778', '1858–1940', '1901–1969']],
              ['Wer starb 1864 bei einer Explosion?', 'Nobels Bruder Emil', ['Nobel selbst', 'Nobels Vater', 'Nobels Bruder Ludvig']],
              ['Womit mischte Nobel Nitroglycerin?', 'Mit Kieselgur', ['Mit Wasser', 'Mit Salz', 'Mit Zucker']],
              ['Wie viele Patente besaß Nobel?', 'Über 350', ['Rund 10', 'Rund 35', 'Über 3.500']],
              ['Warum erschien 1888 ein falscher Nachruf auf Nobel?', 'Sein Bruder Ludvig war gestorben', ['Nobel hatte einen Unfall', 'Er war verschwunden', 'Er hatte es selbst verlangt']],
              ['Wann schrieb Nobel sein Testament?', '1895', ['1867', '1888', '1901']],
              ['Woraus werden die Nobelpreise bezahlt?', 'Aus den Zinsen einer Stiftung', ['Aus Steuern', 'Aus Spenden des Königs', 'Aus dem Verkauf von Dynamit heute']],
              ['In welchen Bereichen stiftete Nobel Preise?', 'Physik, Chemie, Medizin, Literatur und Frieden', ['Musik, Malerei und Sport', 'Nur Physik und Chemie', 'Wirtschaft und Mathematik']],
              ['Seit wann gibt es den Preis für Wirtschaftswissenschaften?', 'Seit 1969', ['Seit 1901', 'Seit 1945', 'Seit 2000']],
              ['Wer stiftete den Wirtschaftspreis?', 'Die schwedische Reichsbank', ['Alfred Nobel', 'Der König', 'Die UNO']],
              ['Wogegen kämpfte die Abstinenzbewegung?', 'Gegen den Alkohol', ['Gegen den König', 'Gegen die Kirche', 'Gegen die Eisenbahn']],
              ['Welcher Politiker prägte die frühe Sozialdemokratie?', 'Hjalmar Branting', ['Olof Palme', 'Per Albin Hansson', 'Tage Erlander']],
            ],
            schwer: [
              ['Wann wurde der Gewerkschaftsbund LO gegründet?', '1898', ['1889', '1907', '1921']],
              ['Was war „Nils Holgerssons wunderbare Reise“ ursprünglich?', 'Ein Erdkundebuch für Schulkinder', ['Ein Märchen für Erwachsene', 'Ein Reiseführer für Touristen', 'Ein Roman über Auswanderer']],
              ['Was war Kieselgur für Nobel?', 'Eine Erde, die Nitroglycerin sicherer machte', ['Ein Metall für Waffen', 'Ein Kunststoff', 'Ein Gas']],
              ['Wann starb Alfred Nobel?', '1896', ['1901', '1888', '1867']],
              ['Warum werden die Nobelpreise am 10. Dezember verliehen?', 'Es ist Nobels Todestag', ['Es ist Nobels Geburtstag', 'Es ist ein Feiertag der Kirche', 'Es ist der Tag der Dynamit-Erfindung']],
              ['Welche Volksbewegungen gab es im 19. Jahrhundert?', 'Freikirchen, Abstinenzbewegung und Arbeiterbewegung', ['Wikingerbünde und Ritterorden', 'Monarchisten und Jakobiner', 'Hippies und Punks']],
              ['Wo werden außer dem Friedensnobelpreis die Preise verliehen?', 'In Stockholm', ['In Oslo', 'In Kopenhagen', 'In Göteborg']],
              ['In welchem Zeitraum wanderten 1,3 Millionen Schweden aus?', '1850–1930', ['1700–1750', '1945–1990', '1600–1650']],
              ['Was förderte die Auswanderung?', 'Armut und Hungersnot', ['Krieg mit Norwegen', 'Ein Erdbeben', 'Ein Verbot des Christentums']],
              ['Wie kam die Industrialisierung nach Schweden?', 'Spät, aber dann schnell', ['Früher als in England', 'Gar nicht', 'Nur auf Gotland']],
              ['Welcher Bruder Nobels starb 1888?', 'Ludvig', ['Emil', 'Robert', 'Immanuel']],
              ['Was war Alfred Nobel von Beruf?', 'Chemiker und Erfinder', ['Arzt und Dichter', 'Kaufmann und Bankier', 'Offizier']],
              ['Wo hatte Nobel Fabriken?', 'In vielen Ländern', ['Nur in Stockholm', 'Nur in Norwegen', 'Gar keine']],
              ['Was schrieb Strindberg vor allem?', 'Dramen', ['Kinderbücher', 'Gesetzestexte', 'Kochbücher']],
              ['Was förderte die Eisenbahn in Schweden?', 'Die Industrialisierung', ['Die Auswanderung nach Asien', 'Den Wikingerhandel', 'Den Kolonialismus']],
              ['Welches Gremium vergibt den Friedensnobelpreis?', 'Ein Komitee in Oslo', ['Die Schwedische Akademie', 'Die UNO', 'Der schwedische König']],
              ['Wie wurde der Friedensnobelpreis von den anderen Preisen getrennt?', 'Er wird in Norwegen vergeben', ['Er wird nie vergeben', 'Er wird in Amerika vergeben', 'Er wird nur alle zehn Jahre vergeben']],
              ['In welchem Jahr bestimmte Nobel seine Stiftung testamentarisch?', '1895', ['1896', '1901', '1888']],
              ['Woher stammte das Erz, das über Narvik verschifft wurde?', 'Aus Kiruna', ['Aus Falun', 'Aus Göteborg', 'Aus Gotland']],
              ['Wie viele Nobelpreisbereiche gab es bei der ersten Verleihung?', 'Fünf', ['Drei', 'Sechs', 'Zehn']],
            ],
          },
        },
      ],
    },
  ],
};
