import type { Epoch } from '../types';

export const E1: Epoch = {
  id: 'antike',
  name: 'Frühzeit, Rom und Westgoten',
  period: 'bis 711',
  events: [
    {
      id: 'hispania',
      title: 'Von Altamira bis zu den Westgoten',
      date: '35.000 v. Chr. – 711 n. Chr.',
      text: [
        'Die Iberische Halbinsel war früh besiedelt. Phöniker, Griechen und Karthager gründeten Handelsstädte, dann machte Rom sie für 600 Jahre zur Provinz „Hispania“. Nach Rom herrschten die Westgoten, bis 711 die Araber kamen.',
      ],
      subtopics: [
        {
          id: 'altamira-iberer',
          title: 'Altamira, Iberer und Karthager',
          date: '35.000–206 v. Chr.',
          text: [
            'In der Höhle von Altamira in Kantabrien malten Steinzeitmenschen vor rund 36.000 bis 13.000 Jahren Bisons, Pferde und Hirsche an die Decke – so lebendig, dass man die Bilder bei ihrer Entdeckung 1879 zunächst für Fälschungen hielt. Ein Mädchen, die achtjährige Tochter des Entdeckers Marcelino Sanz de Sautuola, soll die Bilder zuerst gesehen haben. Altamira wird die „Sixtinische Kapelle der Steinzeit“ genannt.',
            'Im Osten und Süden lebten die Iberer, im Norden und in der Mitte Kelten; wo sie sich mischten, sprach man von „Keltiberern“. Die „Dame von Elche“, eine rund 2400 Jahre alte iberische Steinbüste mit großen Radscheiben am Kopf, ist heute ein Schatz des Archäologischen Nationalmuseums in Madrid. Im Baskenland hat sich mit dem Baskischen eine Sprache erhalten, die mit keiner anderen Sprache der Welt verwandt ist und älter als alle indoeuropäischen Sprachen Europas sein dürfte.',
            'Um 1100 v. Chr. gründeten phönikische Seefahrer aus dem heutigen Libanon die Handelsstadt Gadir – das heutige Cádiz, eine der ältesten Städte Westeuropas. Sie suchten Silber, Kupfer und Zinn. Im Südwesten lag das sagenhaft reiche Reich Tartessos, das die Bibel vielleicht als „Tarschisch“ erwähnt. Griechen gründeten an der Mittelmeerküste Kolonien wie Emporion (Empúries in Katalonien).',
            'Im 3. Jahrhundert v. Chr. eroberte Karthago große Teile Südspaniens. Der Feldherr Hasdrubal gründete um 227 v. Chr. Carthago Nova – das heutige Cartagena. Von hier aus zog Hannibal 219 v. Chr. gegen die mit Rom verbündete Stadt Sagunt, eroberte sie nach acht Monaten Belagerung und löste damit den Zweiten Punischen Krieg aus. 218 v. Chr. brach er mit Heer und Elefanten von Spanien aus über Pyrenäen und Alpen nach Italien auf.',
            'Rom schlug zurück: Scipio eroberte 209 v. Chr. Carthago Nova, und 206 v. Chr. waren die Karthager aus Spanien vertrieben. Damit begann die römische Herrschaft auf der Iberischen Halbinsel. Der Name „Hispania“ stammt wahrscheinlich aus dem Phönikischen; daraus wurde später „España“.',
          ],
          quiz: {
            leicht: [
              ['In welcher Höhle gibt es berühmte Steinzeitmalereien?', 'Altamira', ['Lascaux', 'Covadonga', 'Montserrat']],
              ['Welche Tiere sind in Altamira gemalt?', 'Bisons, Pferde und Hirsche', ['Löwen und Elefanten', 'Hunde und Katzen', 'Fische und Vögel']],
              ['Wann wurde Altamira entdeckt?', '1879', ['1492', '1940', '1800']],
              ['Wofür hielt man die Bilder zunächst?', 'Für Fälschungen', ['Für Kinderzeichnungen', 'Für römische Kunst', 'Für Landkarten']],
              ['Wie nennt man Altamira?', '„Sixtinische Kapelle der Steinzeit“', ['„Louvre der Antike“', '„Wunder Spaniens“', '„Höhle der Könige“']],
              ['Welches Volk lebte im Osten und Süden der Halbinsel?', 'Die Iberer', ['Die Germanen', 'Die Wikinger', 'Die Hunnen']],
              ['Welches Volk lebte im Norden und in der Mitte?', 'Die Kelten', ['Die Iberer', 'Die Araber', 'Die Griechen']],
              ['Wie nannte man die Mischung aus Kelten und Iberern?', 'Keltiberer', ['Iberokelten', 'Hispanier', 'Basken']],
              ['Was ist die „Dame von Elche“?', 'Eine iberische Steinbüste', ['Eine Königin', 'Ein Gemälde', 'Ein Schiff']],
              ['Welche Sprache ist mit keiner anderen verwandt?', 'Baskisch', ['Katalanisch', 'Galicisch', 'Spanisch']],
              ['Welche Seefahrer gründeten Gadir?', 'Die Phöniker', ['Die Griechen', 'Die Römer', 'Die Wikinger']],
              ['Wie heißt Gadir heute?', 'Cádiz', ['Cartagena', 'Málaga', 'Sevilla']],
              ['Was suchten die Phöniker in Spanien?', 'Silber, Kupfer und Zinn', ['Gewürze', 'Seide', 'Öl']],
              ['Welches sagenhaft reiche Reich lag im Südwesten?', 'Tartessos', ['Atlantis', 'Karthago', 'Troja']],
              ['Welche Stadt gründeten die Griechen in Katalonien?', 'Emporion (Empúries)', ['Barcelona', 'Valencia', 'Tarragona']],
              ['Welche Macht eroberte im 3. Jh. v. Chr. Südspanien?', 'Karthago', ['Rom', 'Ägypten', 'Persien']],
              ['Wie heißt Carthago Nova heute?', 'Cartagena', ['Cádiz', 'Córdoba', 'Murcia']],
              ['Welche Stadt belagerte Hannibal 219 v. Chr.?', 'Sagunt', ['Numantia', 'Rom', 'Cádiz']],
              ['Welchen Krieg löste die Eroberung Sagunts aus?', 'Den Zweiten Punischen Krieg', ['Den Ersten Punischen Krieg', 'Den Gallischen Krieg', 'Den Trojanischen Krieg']],
              ['Woraus wurde später „España“?', 'Aus „Hispania“', ['Aus „Iberia“', 'Aus „Gadir“', 'Aus „Tartessos“']],
            ],
            mittel: [
              ['In welcher Region liegt Altamira?', 'In Kantabrien', ['In Andalusien', 'In Katalonien', 'In Galicien']],
              ['Wie alt sind die Malereien von Altamira?', 'Rund 36.000 bis 13.000 Jahre', ['Rund 2000 Jahre', 'Rund 500 Jahre', 'Rund eine Million Jahre']],
              ['Wer soll die Bilder zuerst gesehen haben?', 'Die achtjährige Tochter des Entdeckers', ['Ein Hirte', 'Ein Priester', 'Ein Hund']],
              ['Wie hieß der Entdecker von Altamira?', 'Marcelino Sanz de Sautuola', ['Howard Carter', 'Heinrich Schliemann', 'Francisco Franco']],
              ['Wie alt ist die Dame von Elche etwa?', 'Rund 2400 Jahre', ['Rund 400 Jahre', 'Rund 10.000 Jahre', 'Rund 1000 Jahre']],
              ['Was trägt die Dame von Elche am Kopf?', 'Große Radscheiben', ['Eine Krone', 'Einen Helm', 'Federn']],
              ['Wo steht die Dame von Elche heute?', 'Im Archäologischen Nationalmuseum in Madrid', ['Im Louvre', 'Im Prado', 'In Elche im Rathaus']],
              ['Wie alt dürfte das Baskische sein?', 'Älter als alle indoeuropäischen Sprachen Europas', ['Jünger als Spanisch', 'Aus dem Mittelalter', 'Aus dem 19. Jahrhundert']],
              ['Wann gründeten die Phöniker Gadir?', 'Um 1100 v. Chr.', ['Um 100 v. Chr.', 'Um 711 n. Chr.', 'Um 3000 v. Chr.']],
              ['Woher kamen die Phöniker?', 'Aus dem heutigen Libanon', ['Aus Griechenland', 'Aus Ägypten', 'Aus Italien']],
              ['Als was gilt Cádiz?', 'Als eine der ältesten Städte Westeuropas', ['Als jüngste Stadt Spaniens', 'Als Hauptstadt der Römer', 'Als arabische Gründung']],
              ['Wie nennt die Bibel vielleicht Tartessos?', 'Tarschisch', ['Babylon', 'Ninive', 'Jericho']],
              ['Wer gründete Carthago Nova?', 'Hasdrubal', ['Hannibal', 'Scipio', 'Pyrrhus']],
              ['Wann wurde Carthago Nova gegründet?', 'Um 227 v. Chr.', ['Um 1100 v. Chr.', 'Um 711 n. Chr.', 'Um 19 v. Chr.']],
              ['Mit wem war Sagunt verbündet?', 'Mit Rom', ['Mit Karthago', 'Mit den Griechen', 'Mit den Kelten']],
              ['Wie lange belagerte Hannibal Sagunt?', 'Acht Monate', ['Acht Tage', 'Acht Jahre', 'Einen Tag']],
              ['Wann brach Hannibal nach Italien auf?', '218 v. Chr.', ['219 v. Chr.', '206 v. Chr.', '146 v. Chr.']],
              ['Welche Gebirge überquerte Hannibal?', 'Pyrenäen und Alpen', ['Nur den Apennin', 'Den Atlas', 'Den Kaukasus']],
              ['Wer eroberte 209 v. Chr. Carthago Nova?', 'Scipio', ['Hannibal', 'Caesar', 'Augustus']],
              ['Wann waren die Karthager aus Spanien vertrieben?', '206 v. Chr.', ['219 v. Chr.', '146 v. Chr.', '19 v. Chr.']],
            ],
            schwer: [
              ['Aus welcher Sprache stammt der Name „Hispania“ wahrscheinlich?', 'Aus dem Phönikischen', ['Aus dem Lateinischen', 'Aus dem Griechischen', 'Aus dem Baskischen']],
              ['Was begann 206 v. Chr.?', 'Die römische Herrschaft auf der Halbinsel', ['Die arabische Herrschaft', 'Die Westgotenzeit', 'Die Reconquista']],
              ['Warum war Sagunt Anlass für den Krieg?', 'Es war mit Rom verbündet', ['Es war die Hauptstadt Karthagos', 'Es lag in Italien', 'Dort lebte Scipio']],
              ['Welche Rolle hatte Carthago Nova für Hannibal?', 'Ausgangsbasis gegen Sagunt', ['Sein Geburtsort in Afrika', 'Sein Grab', 'Eine römische Festung']],
              ['Was macht die Malereien von Altamira besonders?', 'Sie sind sehr lebendig gemalt', ['Sie sind farblos', 'Sie zeigen Menschen in Städten', 'Sie sind modern']],
              ['Welche Völker gründeten an der Küste Handelsstädte?', 'Phöniker, Griechen und Karthager', ['Römer, Goten und Araber', 'Kelten und Iberer', 'Wikinger und Normannen']],
              ['Wo gründeten die Griechen Kolonien?', 'An der Mittelmeerküste', ['An der Atlantikküste Galiciens', 'Im Landesinneren', 'Auf den Kanaren']],
              ['Wo lebten die Keltiberer?', 'Wo sich Kelten und Iberer mischten', ['Nur auf Inseln', 'In Nordafrika', 'In Frankreich']],
              ['Welches Metall machte Tartessos sagenhaft reich?', 'Unter anderem Silber', ['Öl', 'Uran', 'Kohle']],
              ['Wo hat sich die vorindoeuropäische Sprache erhalten?', 'Im Baskenland', ['In Katalonien', 'In Andalusien', 'In Galicien']],
              ['Welche Stadt ist älter: Cádiz oder Cartagena?', 'Cádiz', ['Cartagena', 'Beide gleich alt', 'Keine ist antik']],
              ['Was folgte auf Scipios Eroberung von Carthago Nova?', 'Die Vertreibung der Karthager', ['Hannibals Sieg in Spanien', 'Die Gründung Sagunts', 'Die Ankunft der Phöniker']],
              ['Wer war Hasdrubal?', 'Karthagischer Feldherr', ['Römischer Konsul', 'Iberischer König', 'Phönikischer Händler']],
              ['Wie lange herrschte Rom etwa über Hispanien?', 'Rund 600 Jahre', ['Rund 60 Jahre', 'Rund 2000 Jahre', 'Rund 100 Jahre']],
              ['Welche Stadt ist eine phönikische Gründung?', 'Cádiz', ['Cartagena', 'Empúries', 'Madrid']],
              ['Welche Stadt ist eine karthagische Gründung?', 'Cartagena', ['Cádiz', 'Empúries', 'Toledo']],
              ['Welche Stadt ist eine griechische Gründung?', 'Empúries', ['Cádiz', 'Cartagena', 'Sevilla']],
              ['Was zeigt die Dame von Elche?', 'Eine Frau mit Schmuck und Radscheiben', ['Einen Krieger', 'Ein Pferd', 'Einen Gott mit Hörnern']],
              ['Welche Völker lebten vor Rom auf der Halbinsel?', 'Iberer und Kelten', ['Westgoten und Sueben', 'Araber und Berber', 'Franken und Sachsen']],
              ['Wann zog Hannibal gegen Sagunt?', '219 v. Chr.', ['218 v. Chr.', '227 v. Chr.', '209 v. Chr.']],
            ],
          },
        },
        {
          id: 'roemisches-hispanien',
          title: 'Das römische Hispanien',
          date: '206 v. Chr. – 409 n. Chr.',
          text: [
            'Die Eroberung der Halbinsel dauerte fast 200 Jahre. Besonders zäh wehrten sich die Keltiberer: Die Stadt Numantia hielt sich gegen Rom zwanzig Jahre lang. 133 v. Chr. hungerte Scipio Aemilianus sie aus; die letzten Bewohner zündeten ihre Stadt an und töteten sich lieber selbst, als sich zu ergeben. Im Westen führte der Hirte Viriatus die Lusitaner jahrelang gegen Rom, bis er 139 v. Chr. von bestochenen Gefährten ermordet wurde.',
            'Erst Kaiser Augustus unterwarf 19 v. Chr. nach den Kantabrischen Kriegen den Norden. Danach blühte Hispanien auf: Es lieferte Rom Silber, Gold aus den Minen von Las Médulas, Olivenöl, Wein und „Garum“, eine Fischsauce. Hunderte Städte entstanden, darunter Emerita Augusta (Mérida), Caesaraugusta (Zaragoza) und Tarraco (Tarragona).',
            'Römische Bauwerke stehen bis heute: Das Aquädukt von Segovia, ohne Mörtel aus rund 20.000 Granitblöcken gebaut, brachte bis ins 20. Jahrhundert Wasser in die Stadt. In Mérida stehen ein Theater, in dem heute noch gespielt wird, und eine lange Römerbrücke; die Brücke von Alcántara überspannt den Tajo. Der „Herkulesturm“ in A Coruña ist der älteste noch betriebene Leuchtturm der Welt.',
            'Hispanien brachte berühmte Römer hervor: Die Kaiser Trajan und Hadrian stammten aus Italica bei Sevilla – Trajan war der erste Kaiser, der nicht aus Italien kam. Der Philosoph Seneca, Lehrer Neros, kam aus Córdoba, ebenso der Dichter Lucanus; der Spötter Martial stammte aus Bilbilis bei Calatayud. Aus dem Latein der Hispanier entwickelten sich später Spanisch, Katalanisch, Galicisch und Portugiesisch.',
            'Das Christentum verbreitete sich früh. Der Legende nach predigte der Apostel Jakobus in Spanien, und Paulus wollte dorthin reisen. Im 4. Jahrhundert war Hispanien weitgehend christlich. Kaiser Theodosius I., der 380 das Christentum zur Staatsreligion machte, stammte ebenfalls aus Hispanien, aus Cauca (Coca bei Segovia).',
          ],
          quiz: {
            leicht: [
              ['Welche Stadt hielt sich zwanzig Jahre gegen Rom?', 'Numantia', ['Sagunt', 'Cádiz', 'Mérida']],
              ['Was taten die letzten Bewohner Numantias?', 'Sie zündeten ihre Stadt an', ['Sie ergaben sich', 'Sie flohen nach Afrika', 'Sie wurden Römer']],
              ['Welcher Hirte führte die Lusitaner gegen Rom?', 'Viriatus', ['Vercingetorix', 'Arminius', 'Spartacus']],
              ['Welcher Kaiser unterwarf den Norden Spaniens?', 'Augustus', ['Caesar', 'Nero', 'Trajan']],
              ['Welche Fischsauce lieferte Hispanien?', 'Garum', ['Sushi', 'Pesto', 'Ketchup']],
              ['Was lieferte Hispanien außerdem an Rom?', 'Olivenöl, Wein, Silber und Gold', ['Seide und Tee', 'Kaffee', 'Kartoffeln']],
              ['Wie hieß Mérida bei den Römern?', 'Emerita Augusta', ['Caesaraugusta', 'Tarraco', 'Italica']],
              ['Welche Stadt hieß Caesaraugusta?', 'Zaragoza', ['Mérida', 'Tarragona', 'Sevilla']],
              ['In welcher Stadt steht ein berühmtes römisches Aquädukt?', 'Segovia', ['Madrid', 'Valencia', 'Bilbao']],
              ['Woraus ist das Aquädukt von Segovia gebaut?', 'Aus Granitblöcken ohne Mörtel', ['Aus Ziegeln mit Zement', 'Aus Holz', 'Aus Marmor mit Mörtel']],
              ['Wo steht ein römisches Theater, in dem noch gespielt wird?', 'In Mérida', ['In Madrid', 'In Bilbao', 'In Granada']],
              ['Wie heißt der römische Leuchtturm in A Coruña?', 'Herkulesturm', ['Leuchtturm von Alexandria', 'Torre del Oro', 'Giralda']],
              ['Welche Kaiser stammten aus Italica?', 'Trajan und Hadrian', ['Augustus und Nero', 'Caesar und Pompeius', 'Konstantin und Diokletian']],
              ['Bei welcher Stadt lag Italica?', 'Bei Sevilla', ['Bei Madrid', 'Bei Barcelona', 'Bei Bilbao']],
              ['Welcher Philosoph stammte aus Córdoba?', 'Seneca', ['Cicero', 'Platon', 'Mark Aurel']],
              ['Wessen Lehrer war Seneca?', 'Neros', ['Caesars', 'Trajans', 'Augustus’']],
              ['Welche Sprachen entwickelten sich aus dem Latein Hispaniens?', 'Spanisch, Katalanisch, Galicisch, Portugiesisch', ['Baskisch', 'Arabisch', 'Englisch']],
              ['Welcher Apostel soll laut Legende in Spanien gepredigt haben?', 'Jakobus', ['Petrus', 'Johannes', 'Thomas']],
              ['Welcher Kaiser, der das Christentum zur Staatsreligion machte, kam aus Hispanien?', 'Theodosius I.', ['Konstantin', 'Nero', 'Augustus']],
              ['War Hispanien im 4. Jahrhundert christlich?', 'Weitgehend ja', ['Nein, muslimisch', 'Nein, jüdisch', 'Nein, keltisch-heidnisch']],
            ],
            mittel: [
              ['Wie lange dauerte die römische Eroberung der Halbinsel?', 'Fast 200 Jahre', ['Zwei Jahre', '20 Jahre', '600 Jahre']],
              ['Wann fiel Numantia?', '133 v. Chr.', ['206 v. Chr.', '19 v. Chr.', '409 n. Chr.']],
              ['Wer eroberte Numantia?', 'Scipio Aemilianus', ['Scipio Africanus', 'Caesar', 'Augustus']],
              ['Wie eroberte Scipio Numantia?', 'Er hungerte die Stadt aus', ['Mit Elefanten', 'Durch Verrat am ersten Tag', 'Mit Schiffen']],
              ['Welches Volk führte Viriatus?', 'Die Lusitaner', ['Die Kantabrer', 'Die Basken', 'Die Westgoten']],
              ['Wie starb Viriatus?', 'Bestochene Gefährten ermordeten ihn', ['In der Schlacht', 'An Altersschwäche', 'Durch Hinrichtung in Rom']],
              ['Wann starb Viriatus?', '139 v. Chr.', ['133 v. Chr.', '19 v. Chr.', '206 v. Chr.']],
              ['Wann unterwarf Augustus den Norden?', '19 v. Chr.', ['133 v. Chr.', '206 v. Chr.', '44 v. Chr.']],
              ['Nach welchen Kriegen unterwarf Augustus den Norden?', 'Den Kantabrischen Kriegen', ['Den Punischen Kriegen', 'Den Gallischen Kriegen', 'Den Bürgerkriegen']],
              ['Woher kam das römische Gold?', 'Aus den Minen von Las Médulas', ['Aus Toledo', 'Aus Cádiz', 'Aus Altamira']],
              ['Wie hieß Tarragona bei den Römern?', 'Tarraco', ['Emerita', 'Italica', 'Corduba']],
              ['Aus wie vielen Granitblöcken besteht das Aquädukt von Segovia etwa?', 'Rund 20.000', ['Rund 200', 'Rund 2 Millionen', 'Rund 2000']],
              ['Bis wann brachte das Aquädukt von Segovia Wasser?', 'Bis ins 20. Jahrhundert', ['Bis 409', 'Bis 711', 'Bis heute täglich']],
              ['Welchen Fluss überspannt die Brücke von Alcántara?', 'Den Tajo', ['Den Ebro', 'Den Guadalquivir', 'Den Duero']],
              ['Was ist besonders am Herkulesturm?', 'Ältester noch betriebener Leuchtturm der Welt', ['Höchster Turm Spaniens', 'Ältester Kirchturm', 'Er ist aus Gold']],
              ['Was war Trajan als Kaiser als Erster?', 'Erster Kaiser, der nicht aus Italien kam', ['Erster christlicher Kaiser', 'Erster Kaiser aus Afrika', 'Erster Kaiser überhaupt']],
              ['Welcher Dichter kam ebenfalls aus Córdoba?', 'Lucanus', ['Martial', 'Vergil', 'Ovid']],
              ['Woher stammte Martial?', 'Aus Bilbilis bei Calatayud', ['Aus Córdoba', 'Aus Rom', 'Aus Italica']],
              ['Wer wollte laut Bibel nach Spanien reisen?', 'Paulus', ['Petrus', 'Judas', 'Lukas']],
              ['Woher stammte Theodosius I.?', 'Aus Cauca (Coca bei Segovia)', ['Aus Italica', 'Aus Córdoba', 'Aus Konstantinopel']],
            ],
            schwer: [
              ['Warum zündeten die Numantiner ihre Stadt an?', 'Um sich nicht ergeben zu müssen', ['Aus Versehen', 'Als Signal an Karthago', 'Um Rom anzulocken']],
              ['Welches Volk wehrte sich besonders zäh gegen Rom?', 'Die Keltiberer', ['Die Phöniker', 'Die Griechen', 'Die Karthager']],
              ['Was war Martial?', 'Ein Spötter (Dichter von Spottgedichten)', ['Ein Kaiser', 'Ein Feldherr', 'Ein Bischof']],
              ['Welcher Teil Spaniens wurde zuletzt erobert?', 'Der Norden', ['Der Süden', 'Die Ostküste', 'Die Mitte']],
              ['Was entstand nach der Eroberung in großer Zahl?', 'Städte', ['Burgen der Westgoten', 'Moscheen', 'Klöster']],
              ['Welche Sprache entwickelte sich nicht aus dem Latein?', 'Baskisch', ['Galicisch', 'Katalanisch', 'Portugiesisch']],
              ['Wo liegt das Theater, das noch genutzt wird?', 'In Mérida', ['In Segovia', 'In A Coruña', 'In Alcántara']],
              ['In welcher Stadt steht der Herkulesturm?', 'A Coruña', ['Cádiz', 'Gijón', 'Santander']],
              ['Woher stammten zwei Kaiser des 2. Jahrhunderts?', 'Aus Italica', ['Aus Mérida', 'Aus Rom', 'Aus Tarraco']],
              ['Was verbindet Seneca und Nero?', 'Seneca war Neros Lehrer', ['Nero war Senecas Vater', 'Sie waren Brüder', 'Keine Verbindung']],
              ['Was machte Theodosius I. 380?', 'Christentum zur Staatsreligion', ['Spanien unabhängig', 'Die Westgoten zu Herren', 'Den Islam erlaubt']],
              ['Wer führte die Belagerung Numantias?', 'Scipio Aemilianus', ['Hannibal', 'Viriatus', 'Augustus']],
              ['Woher stammt der Name Mérida?', 'Von Emerita Augusta', ['Von Merida in Mexiko', 'Vom Arabischen', 'Von den Westgoten']],
              ['Wie lange hielt Numantia stand?', 'Zwanzig Jahre', ['Zwei Monate', 'Zweihundert Jahre', 'Zwei Jahre']],
              ['Was stand hinter Viriatus’ Tod?', 'Rom bestach seine Gefährten', ['Ein Unfall', 'Eine Krankheit', 'Ein Duell mit Scipio']],
              ['Welche Rolle spielte Hispanien für Rom wirtschaftlich?', 'Lieferant von Metallen und Lebensmitteln', ['Keine', 'Nur Soldatenreservoir', 'Nur Urlaubsort']],
              ['Wie heißt Zaragoza auf Latein?', 'Caesaraugusta', ['Emerita Augusta', 'Tarraco', 'Hispalis']],
              ['Was war Garum?', 'Eine Fischsauce', ['Ein Wein', 'Ein Käse', 'Ein Brot']],
              ['Welche Brücke führt über den Tajo?', 'Die Brücke von Alcántara', ['Die Römerbrücke von Córdoba', 'Die Brücke von Mérida', 'Die Brücke von Segovia']],
              ['Was gilt seit der Römerzeit für Spaniens Sprache?', 'Sie stammt vom Latein ab', ['Sie stammt vom Baskischen ab', 'Sie stammt vom Arabischen ab', 'Sie stammt vom Gotischen ab']],
            ],
          },
        },
        {
          id: 'westgoten',
          title: 'Das Westgotenreich',
          date: '409–711',
          text: [
            '409 überquerten die germanischen Vandalen, Sueben und Alanen die Pyrenäen. Die Vandalen zogen weiter durch Südspanien – vielleicht stammt der Name „Andalusien“ von ihnen – und setzten 429 nach Nordafrika über. Die Sueben gründeten in Galicien ein eigenes Königreich, das bis 585 bestand.',
            'Die Westgoten, die 410 Rom geplündert hatten, kamen zunächst im Auftrag Roms nach Spanien. Nach ihrer Niederlage gegen die Franken bei Vouillé 507 verloren sie Südfrankreich und verlegten ihren Schwerpunkt ganz nach Spanien. König Leovigild machte Toledo zur Hauptstadt und eroberte 585 das Suebenreich. Rund 200.000 Westgoten herrschten über mehrere Millionen Hispano-Römer.',
            'Die Westgoten waren Arianer, eine christliche Richtung, die die Römer als Ketzerei ansahen. 589 trat König Rekkared auf dem Dritten Konzil von Toledo zum katholischen Glauben über; damit wuchsen Goten und Römer zusammen, Mischehen wurden erlaubt. Die Konzile von Toledo wurden zu wichtigen Versammlungen, auf denen Bischöfe und Adel auch politische Fragen entschieden. Das Gesetzbuch „Liber Iudiciorum“ (654) galt für alle Bewohner gleichermaßen.',
            'Der Bischof Isidor von Sevilla (um 560–636) schrieb die „Etymologien“, eine Enzyklopädie des gesamten damaligen Wissens in 20 Büchern, die das ganze Mittelalter hindurch gelesen wurde. Er ist heute Schutzpatron des Internets. Kunstvolle westgotische Goldkronen, wie der Schatz von Guarrazar, zeigen den Reichtum der Könige. Die Juden wurden unter manchen Königen hart verfolgt und zur Taufe gezwungen.',
            'Das Königtum war schwach, weil der König gewählt wurde und Adelsfamilien ständig um den Thron kämpften. Nach dem Tod König Witizas stritten seine Anhänger mit König Roderich. 711 setzte ein muslimisches Heer aus Arabern und Berbern unter Tariq ibn Ziyad aus Nordafrika über die Meerenge. In der Schlacht am Guadalete wurde Roderich besiegt und getötet; das Westgotenreich brach innerhalb weniger Jahre zusammen.',
          ],
          quiz: {
            leicht: [
              ['Welche Völker überquerten 409 die Pyrenäen?', 'Vandalen, Sueben und Alanen', ['Westgoten und Franken', 'Araber und Berber', 'Römer und Griechen']],
              ['Wohin zogen die Vandalen 429 weiter?', 'Nach Nordafrika', ['Nach Italien', 'Nach Frankreich', 'Nach England']],
              ['Welcher Name stammt vielleicht von den Vandalen?', 'Andalusien', ['Galicien', 'Kastilien', 'Katalonien']],
              ['Wo gründeten die Sueben ein Königreich?', 'In Galicien', ['In Andalusien', 'In Katalonien', 'In Madrid']],
              ['Welche Stadt machte Leovigild zur Hauptstadt?', 'Toledo', ['Madrid', 'Sevilla', 'Barcelona']],
              ['Welches Volk hatte 410 Rom geplündert?', 'Die Westgoten', ['Die Vandalen', 'Die Sueben', 'Die Franken']],
              ['Welcher christlichen Richtung gehörten die Westgoten an?', 'Dem Arianismus', ['Dem Katholizismus', 'Dem Protestantismus', 'Der Orthodoxie']],
              ['Welcher König trat 589 zum katholischen Glauben über?', 'Rekkared', ['Roderich', 'Leovigild', 'Witiza']],
              ['Wo trat Rekkared über?', 'Auf dem Dritten Konzil von Toledo', ['In Rom', 'In Sevilla', 'In Konstantinopel']],
              ['Welcher Bischof schrieb die „Etymologien“?', 'Isidor von Sevilla', ['Augustinus', 'Jakobus', 'Leander']],
              ['Was sind die „Etymologien“?', 'Eine Enzyklopädie', ['Ein Roman', 'Ein Gesetzbuch', 'Eine Bibel']],
              ['Wessen Schutzpatron ist Isidor heute?', 'Des Internets', ['Der Seefahrer', 'Der Bauern', 'Der Ärzte']],
              ['Welcher Schatz zeigt westgotische Goldkronen?', 'Der Schatz von Guarrazar', ['Der Nibelungenschatz', 'Der Schatz von Troja', 'Der Schatz der Templer']],
              ['Wie wurde der westgotische König bestimmt?', 'Er wurde gewählt', ['Er erbte immer', 'Der Papst ernannte ihn', 'Der Kaiser setzte ihn ein']],
              ['Welcher König war der letzte der Westgoten?', 'Roderich', ['Rekkared', 'Leovigild', 'Pelayo']],
              ['Wann setzte ein muslimisches Heer nach Spanien über?', '711', ['409', '589', '1492']],
              ['Wer führte das muslimische Heer 711?', 'Tariq ibn Ziyad', ['Abd ar-Rahman', 'Saladin', 'Mohammed']],
              ['Aus welchen Völkern bestand das Heer von 711?', 'Araber und Berber', ['Türken und Perser', 'Vandalen und Alanen', 'Franken und Sachsen']],
              ['In welcher Schlacht fiel Roderich?', 'Am Guadalete', ['Bei Covadonga', 'Bei Poitiers', 'Bei Vouillé']],
              ['Wie schnell brach das Westgotenreich zusammen?', 'In wenigen Jahren', ['In hundert Jahren', 'Gar nicht', 'In einem Tag']],
            ],
            mittel: [
              ['Bis wann bestand das Suebenreich?', '585', ['409', '711', '507']],
              ['Wer eroberte das Suebenreich?', 'Leovigild', ['Rekkared', 'Roderich', 'Tariq']],
              ['In wessen Auftrag kamen die Westgoten zunächst?', 'Im Auftrag Roms', ['Im Auftrag der Franken', 'Im Auftrag der Vandalen', 'Im Auftrag des Papstes']],
              ['Gegen wen verloren die Westgoten 507?', 'Gegen die Franken', ['Gegen die Römer', 'Gegen die Araber', 'Gegen die Sueben']],
              ['Wo verloren die Westgoten 507?', 'Bei Vouillé', ['Am Guadalete', 'Bei Toledo', 'Bei Poitiers']],
              ['Was verloren die Westgoten 507?', 'Südfrankreich', ['Galicien', 'Toledo', 'Nordafrika']],
              ['Wie viele Westgoten herrschten etwa?', 'Rund 200.000', ['Rund 2000', 'Rund 2 Millionen', 'Rund 20 Millionen']],
              ['Über wen herrschten die Westgoten?', 'Über mehrere Millionen Hispano-Römer', ['Über Araber', 'Über Franken', 'Nur über Goten']],
              ['Wie sahen die Römer den Arianismus?', 'Als Ketzerei', ['Als wahre Lehre', 'Als Islam', 'Gar nicht']],
              ['Was wurde nach 589 erlaubt?', 'Mischehen zwischen Goten und Römern', ['Der Islam', 'Die Scheidung', 'Die Vielehe']],
              ['Was entschieden die Konzile von Toledo auch?', 'Politische Fragen', ['Nur Bauregeln', 'Sportregeln', 'Nichts']],
              ['Wie heißt das westgotische Gesetzbuch?', 'Liber Iudiciorum', ['Code Napoléon', 'Zwölftafelgesetz', 'Sachsenspiegel']],
              ['Wann entstand das Liber Iudiciorum?', '654', ['589', '711', '409']],
              ['Für wen galt das Liber Iudiciorum?', 'Für alle Bewohner gleichermaßen', ['Nur für Goten', 'Nur für Römer', 'Nur für Juden']],
              ['Wann lebte Isidor von Sevilla?', 'Um 560–636', ['Um 400–450', 'Um 711–780', 'Um 1000–1050']],
              ['Aus wie vielen Büchern bestehen die „Etymologien“?', '20', ['2', '100', '7']],
              ['Wie lange wurden die „Etymologien“ gelesen?', 'Das ganze Mittelalter hindurch', ['Nur zehn Jahre', 'Gar nicht', 'Erst seit 2000']],
              ['Wie wurden die Juden unter manchen Königen behandelt?', 'Hart verfolgt und zur Taufe gezwungen', ['Sie regierten mit', 'Sie waren gleichberechtigt', 'Sie wurden Könige']],
              ['Wessen Anhänger stritten mit Roderich?', 'Die Witizas', ['Die Rekkareds', 'Die Leovigilds', 'Die Tariqs']],
              ['Woher setzte Tariq über?', 'Aus Nordafrika über die Meerenge', ['Aus Frankreich über die Pyrenäen', 'Aus Italien', 'Aus Portugal']],
            ],
            schwer: [
              ['Warum war das westgotische Königtum schwach?', 'Wahlkönigtum und ständige Adelskämpfe', ['Zu viele Könige gleichzeitig', 'Der Papst regierte', 'Es gab keine Armee']],
              ['Was bewirkte Rekkareds Übertritt?', 'Goten und Römer wuchsen zusammen', ['Die Araber kamen', 'Die Juden wurden Herrscher', 'Toledo wurde zerstört']],
              ['Warum verlegten die Westgoten ihren Schwerpunkt nach Spanien?', 'Nach dem Verlust Südfrankreichs 507', ['Wegen der Pest', 'Wegen der Araber', 'Wegen des Papstes']],
              ['Was zeigt der Schatz von Guarrazar?', 'Den Reichtum der westgotischen Könige', ['Arabische Kunst', 'Römische Münzen', 'Keltische Waffen']],
              ['Wie lange dauerte die westgotische Herrschaft in Spanien etwa?', 'Rund 300 Jahre', ['Rund 30 Jahre', 'Rund 1000 Jahre', 'Rund 10 Jahre']],
              ['Wann war das Dritte Konzil von Toledo?', '589', ['654', '711', '507']],
              ['Was folgte auf die Schlacht am Guadalete?', 'Der Zusammenbruch des Westgotenreichs', ['Rekkareds Bekehrung', 'Die Gründung Toledos', 'Die Ankunft der Vandalen']],
              ['Welches Volk zog nach Afrika und gründete dort ein Reich?', 'Die Vandalen', ['Die Sueben', 'Die Alanen', 'Die Westgoten']],
              ['Wer war König Witiza?', 'Ein Vorgänger Roderichs', ['Ein Araberführer', 'Ein Bischof', 'Ein Suebenkönig']],
              ['Wovon handelt Isidors Werk?', 'Vom gesamten damaligen Wissen', ['Nur von Toledo', 'Nur von der Bibel', 'Von Seefahrt']],
              ['Warum ist Isidor Patron des Internets?', 'Er sammelte das Wissen seiner Zeit in einer Enzyklopädie', ['Er erfand Computer', 'Er war Briefträger', 'Zufällig']],
              ['Welche Stadt war Hauptstadt der Westgoten?', 'Toledo', ['Sevilla', 'Barcelona', 'Mérida']],
              ['Welches Ereignis brachte den Islam nach Spanien?', 'Die Landung Tariqs 711', ['Rekkareds Konzil', 'Die Ankunft der Vandalen', 'Die Plünderung Roms']],
              ['Was unterschied Westgoten und Römer religiös vor 589?', 'Arianer gegen Katholiken', ['Muslime gegen Christen', 'Juden gegen Christen', 'Heiden gegen Christen']],
              ['Wann überquerten Vandalen und Sueben die Pyrenäen?', '409', ['429', '507', '711']],
              ['Wie behandelte das Liber Iudiciorum Goten und Römer?', 'Gleich', ['Goten bevorzugt', 'Römer bevorzugt', 'Gar nicht']],
              ['Wer starb am Guadalete?', 'König Roderich', ['Tariq', 'Witiza', 'Isidor']],
              ['Welcher König eroberte Galicien?', 'Leovigild', ['Rekkared', 'Witiza', 'Roderich']],
              ['Woher kam der Streit um den Thron 711?', 'Nach dem Tod König Witizas', ['Nach Isidors Tod', 'Nach Rekkareds Tod', 'Nach dem Tod Tariqs']],
              ['Welche Gruppe hatte der König auf den Konzilen neben sich?', 'Bischöfe und Adel', ['Bauern', 'Kaufleute', 'Araber']],
            ],
          },
        },
      ],
    },
  ],
};
