import type { Epoch } from '../types';

export const E2: Epoch = {
  id: 'mittelalter',
  name: 'Al-Andalus und Reconquista',
  period: '711–1492',
  events: [
    {
      id: 'al-andalus',
      title: 'Al-Andalus: Das muslimische Spanien',
      date: '711–1492',
      text: [
        'Fast 800 Jahre lang war ein großer Teil Spaniens muslimisch. Córdoba wurde zur größten und gebildetsten Stadt Westeuropas; Muslime, Christen und Juden lebten zeitweise friedlich nebeneinander. Prachtbauten wie die Mezquita und die Alhambra zeugen davon.',
      ],
      subtopics: [
        {
          id: 'emirat-kalifat',
          title: 'Eroberung, Emirat und Kalifat von Córdoba',
          date: '711–1031',
          text: [
            'Nach dem Sieg am Guadalete 711 eroberten die Muslime in nur sieben Jahren fast die ganze Halbinsel. Der Felsen, an dem Tariq landete, heißt nach ihm „Dschabal Tariq“ (Berg des Tariq) – daraus wurde „Gibraltar“. Das muslimische Spanien nannten die Araber „al-Andalus“. Erst 732 stoppten die Franken unter Karl Martell bei Tours und Poitiers den Vormarsch nach Norden.',
            'Im äußersten Norden, in den Bergen Asturiens, besiegte der westgotische Adlige Pelayo um 722 bei Covadonga ein muslimisches Heer. Spanier sehen darin den Beginn der Reconquista, der christlichen Rückeroberung. Aus Asturien gingen später die Königreiche León und Kastilien hervor.',
            '750 wurde in Damaskus die Kalifenfamilie der Umayyaden von den Abbasiden fast vollständig ermordet. Der junge Prinz Abd ar-Rahman entkam, floh quer durch Nordafrika und gründete 756 in Córdoba ein unabhängiges Emirat. Er begann den Bau der Großen Moschee (Mezquita) mit ihrem „Wald“ aus über 850 Säulen und rot-weiß gestreiften Doppelbögen. Im 16. Jahrhundert wurde mitten in die Moschee eine Kathedrale gebaut.',
            '929 rief sich Abd ar-Rahman III. zum Kalifen aus – zum geistlichen und weltlichen Oberhaupt aller Muslime, gleichrangig mit dem Kalifen in Bagdad. Córdoba hatte damals vielleicht 500.000 Einwohner, gepflasterte und beleuchtete Straßen, Hunderte Moscheen und öffentliche Bäder. Die Bibliothek des Kalifen al-Hakam II. soll 400.000 Bücher umfasst haben. Vor der Stadt ließ Abd ar-Rahman III. die prächtige Palaststadt Medina Azahara errichten.',
            'Gegen Ende des 10. Jahrhunderts führte der Heerführer Almansor („der Siegreiche“) über 50 Feldzüge gegen die christlichen Reiche; 997 plünderte er Santiago de Compostela und ließ die Glocken der Kathedrale nach Córdoba tragen. Nach seinem Tod zerfiel das Kalifat in Bürgerkriegen und wurde 1031 aufgelöst.',
          ],
          quiz: {
            leicht: [
              ['Wie nannten die Araber das muslimische Spanien?', 'al-Andalus', ['Hispania', 'Iberia', 'Kastilien']],
              ['Wie lange brauchten die Muslime für die Eroberung fast der ganzen Halbinsel?', 'Sieben Jahre', ['Siebzig Jahre', 'Sieben Monate', 'Siebenhundert Jahre']],
              ['Wovon kommt der Name „Gibraltar“?', 'Von „Dschabal Tariq“ (Berg des Tariq)', ['Von einem Gott', 'Von einem römischen Kaiser', 'Von einem Fluss']],
              ['Wer stoppte 732 die Muslime in Frankreich?', 'Karl Martell', ['Karl der Große', 'Pelayo', 'El Cid']],
              ['Wo siegte Pelayo um 722?', 'Bei Covadonga', ['Bei Toledo', 'Bei Granada', 'Bei Córdoba']],
              ['Wie nennt man die christliche Rückeroberung?', 'Reconquista', ['Inquisition', 'Conquista', 'Revolución']],
              ['In welchem Gebirge lag Covadonga?', 'In den Bergen Asturiens', ['In der Sierra Nevada', 'In den Alpen', 'In den Pyrenäen Kataloniens']],
              ['Welche Kalifenfamilie wurde 750 fast ausgelöscht?', 'Die Umayyaden', ['Die Abbasiden', 'Die Nasriden', 'Die Almohaden']],
              ['Welcher Prinz entkam und gründete ein Emirat in Córdoba?', 'Abd ar-Rahman', ['Almansor', 'Tariq', 'Boabdil']],
              ['Wann gründete Abd ar-Rahman das Emirat von Córdoba?', '756', ['711', '929', '1031']],
              ['Welches berühmte Bauwerk steht in Córdoba?', 'Die Mezquita', ['Die Alhambra', 'Die Sagrada Família', 'Der Escorial']],
              ['Was ist besonders an der Mezquita?', 'Ein „Wald“ aus über 850 Säulen', ['Ein goldenes Dach', 'Ein hoher Turm aus Glas', 'Unterirdische Gänge']],
              ['Welche Farben haben die Bögen der Mezquita?', 'Rot-weiß gestreift', ['Blau-gelb', 'Schwarz-weiß', 'Grün-gold']],
              ['Was wurde im 16. Jahrhundert in die Mezquita gebaut?', 'Eine Kathedrale', ['Ein Palast', 'Ein Gefängnis', 'Ein Markt']],
              ['Wer rief sich 929 zum Kalifen aus?', 'Abd ar-Rahman III.', ['Almansor', 'Abd ar-Rahman I.', 'Tariq']],
              ['Wie viele Einwohner hatte Córdoba damals vielleicht?', '500.000', ['5000', '50.000', '5 Millionen']],
              ['Welche Palaststadt ließ Abd ar-Rahman III. bauen?', 'Medina Azahara', ['Alhambra', 'Alcázar von Sevilla', 'Escorial']],
              ['Wie viele Bücher soll die Bibliothek al-Hakams II. gehabt haben?', '400.000', ['400', '4000', '4 Millionen']],
              ['Was bedeutet „Almansor“?', 'Der Siegreiche', ['Der Weise', 'Der Fromme', 'Der Löwe']],
              ['Wann wurde das Kalifat von Córdoba aufgelöst?', '1031', ['929', '1085', '1492']],
            ],
            mittel: [
              ['Wo stoppten die Franken die Muslime 732?', 'Bei Tours und Poitiers', ['Bei Covadonga', 'Bei Roncesvalles', 'Bei Paris']],
              ['Welcher Herkunft war Pelayo?', 'Westgotischer Adliger', ['Arabischer Prinz', 'Fränkischer König', 'Römischer Bischof']],
              ['Welche Königreiche gingen aus Asturien hervor?', 'León und Kastilien', ['Aragón und Navarra', 'Portugal und Galicien', 'Granada und Murcia']],
              ['Von wem wurden die Umayyaden 750 ermordet?', 'Von den Abbasiden', ['Von den Franken', 'Von den Byzantinern', 'Von den Westgoten']],
              ['In welcher Stadt wurden die Umayyaden gestürzt?', 'In Damaskus', ['In Bagdad', 'In Kairo', 'In Mekka']],
              ['Wie floh Abd ar-Rahman nach Spanien?', 'Quer durch Nordafrika', ['Über Italien', 'Über Frankreich', 'Mit einem Schiff aus Indien']],
              ['Mit wem war der Kalif von Córdoba gleichrangig?', 'Mit dem Kalifen in Bagdad', ['Mit dem Papst', 'Mit dem Kaiser in Aachen', 'Mit dem König von Asturien']],
              ['Was war der Kalif?', 'Geistliches und weltliches Oberhaupt der Muslime', ['Ein General', 'Ein Bischof', 'Ein Kaufmann']],
              ['Was hatten Córdobas Straßen?', 'Pflaster und Beleuchtung', ['Straßenbahnen', 'Nichts davon', 'Kanäle wie Venedig']],
              ['Was gab es in Córdoba in großer Zahl?', 'Moscheen und öffentliche Bäder', ['Burgen', 'Fabriken', 'Theater']],
              ['Welcher Kalif hatte die große Bibliothek?', 'al-Hakam II.', ['Abd ar-Rahman I.', 'Almansor', 'Boabdil']],
              ['Wo lag Medina Azahara?', 'Vor Córdoba', ['In Granada', 'In Toledo', 'In Sevilla']],
              ['Wie viele Feldzüge führte Almansor?', 'Über 50', ['Zwei', 'Fünf', 'Über 500']],
              ['Welche Stadt plünderte Almansor 997?', 'Santiago de Compostela', ['Toledo', 'Barcelona', 'Oviedo']],
              ['Was ließ Almansor nach Córdoba tragen?', 'Die Glocken der Kathedrale', ['Das Grab des Jakobus', 'Den König', 'Die Bibliothek']],
              ['Was geschah nach Almansors Tod?', 'Das Kalifat zerfiel in Bürgerkriegen', ['Das Kalifat wurde stärker', 'Córdoba wurde christlich', 'Almansor wurde Kalif']],
              ['Wann siegte Pelayo bei Covadonga?', 'Um 722', ['711', '756', '1085']],
              ['Wann war die Schlacht bei Tours und Poitiers?', '732', ['711', '722', '756']],
              ['Wann zog Almansor gegen Santiago?', '997', ['929', '1031', '711']],
              ['Wann rief sich Abd ar-Rahman III. zum Kalifen aus?', '929', ['756', '1031', '997']],
            ],
            schwer: [
              ['Was sehen Spanier in Covadonga?', 'Den Beginn der Reconquista', ['Das Ende der Reconquista', 'Die Gründung Córdobas', 'Die Landung Tariqs']],
              ['Was war die Mezquita ursprünglich?', 'Die Große Moschee von Córdoba', ['Ein römischer Tempel ohne Umbau', 'Ein Königspalast', 'Eine Synagoge']],
              ['Was war an Córdoba im 10. Jahrhundert besonders?', 'Größte und gebildetste Stadt Westeuropas', ['Kleinste Hauptstadt', 'Christliche Hauptstadt', 'Hafen am Atlantik']],
              ['Was war Abd ar-Rahman I. ursprünglich?', 'Ein geflohener Umayyadenprinz', ['Ein Berberkrieger', 'Ein Westgote', 'Ein Kalif aus Bagdad']],
              ['Was ist ein Emirat?', 'Ein von einem Emir regiertes Fürstentum', ['Ein Kalifat', 'Eine Republik', 'Ein Kloster']],
              ['Was änderte sich 929 in Córdoba?', 'Aus dem Emirat wurde ein Kalifat', ['Córdoba wurde christlich', 'Die Stadt wurde zerstört', 'Die Hauptstadt zog nach Toledo']],
              ['Was zeigt Almansors Raubzug nach Santiago?', 'Die militärische Stärke Córdobas', ['Die Schwäche Córdobas', 'Eine Freundschaft mit León', 'Eine Pilgerreise']],
              ['Woher stammte die Umayyadenfamilie zuvor?', 'Aus Damaskus', ['Aus Córdoba', 'Aus Bagdad', 'Aus Marokko']],
              ['Welche Gefahr bestand für das Kalifat nach 1002?', 'Bürgerkriege', ['Wikingerangriffe', 'Eine Pest', 'Ein Erdbeben']],
              ['Wie reagierten die Christen im Norden auf 711?', 'In Asturien leisteten sie Widerstand', ['Sie wurden alle Muslime', 'Sie flohen nach Amerika', 'Sie ergaben sich ganz']],
              ['Welche Stadt war Hauptstadt von al-Andalus?', 'Córdoba', ['Toledo', 'Granada', 'Sevilla']],
              ['Was symbolisiert die Kathedrale in der Mezquita?', 'Die christliche Eroberung', ['Die arabische Herrschaft', 'Die römische Zeit', 'Die Westgotenzeit']],
              ['Wie viele Jahre lag die Gründung des Emirats nach 711?', '45', ['5', '100', '218']],
              ['Was entschied sich bei Tours und Poitiers?', 'Der Vormarsch nach Norden wurde gestoppt', ['Die Eroberung Spaniens begann', 'Die Reconquista endete', 'Córdoba wurde Kalifat']],
              ['Welche Stadt war die Basis des christlichen Widerstands?', 'Asturien', ['Córdoba', 'Sevilla', 'Granada']],
              ['Wer war al-Hakam II.?', 'Kalif mit riesiger Bibliothek', ['Heerführer', 'Christlicher König', 'Bischof von Toledo']],
              ['Was entstand nach 1031 aus dem Kalifat?', 'Es zerfiel', ['Es wurde ein Königreich Kastilien', 'Es wurde ein Teil Frankreichs', 'Es blieb unverändert']],
              ['Was war Medina Azahara?', 'Eine prächtige Palaststadt', ['Eine Moschee in Mekka', 'Ein Hafen', 'Ein Kloster']],
              ['Wo landete Tariq?', 'An einem Felsen, der heute Gibraltar heißt', ['In Cádiz', 'In Barcelona', 'In Valencia']],
              ['Wie lange dauerte die muslimische Herrschaft in Spanien insgesamt?', 'Fast 800 Jahre', ['80 Jahre', '300 Jahre', '1500 Jahre']],
            ],
          },
        },
        {
          id: 'kultur-taifas',
          title: 'Kultur, Taifas und Alhambra',
          date: '900–1492',
          text: [
            'In al-Andalus lebten Muslime, Christen und Juden zeitweise friedlich nebeneinander – man spricht von „Convivencia“ (Zusammenleben). Christen und Juden durften ihren Glauben behalten, zahlten aber eine Sondersteuer. Christen, die arabische Sprache und Kultur annahmen, hießen „Mozaraber“. Gleichberechtigt waren sie nicht, und es gab auch Zeiten der Verfolgung.',
            'Die Wissenschaft blühte: Ärzte, Astronomen und Mathematiker brachten Wissen aus dem Orient mit, etwa die indisch-arabischen Ziffern mit der Null. Der Philosoph Averroes (Ibn Ruschd) aus Córdoba kommentierte die Werke des Aristoteles und beeinflusste so die europäische Philosophie. Der jüdische Gelehrte Maimonides, ebenfalls aus Córdoba, wurde zum größten jüdischen Denker des Mittelalters.',
            'Die Araber brachten neue Pflanzen und Techniken: Reis, Zitrusfrüchte, Safran, Zuckerrohr, Auberginen und Bewässerungsanlagen. Rund 4000 spanische Wörter stammen aus dem Arabischen, viele beginnen mit „al-“ wie „aceite“ (Öl), „azúcar“ (Zucker), „almohada“ (Kissen) oder „alcalde“ (Bürgermeister). Selbst „ojalá“ (hoffentlich) kommt von „so Gott will“. Nach der Eroberung Toledos übersetzte die „Übersetzerschule von Toledo“ arabische Werke ins Lateinische und machte sie für Europa zugänglich.',
            'Nach 1031 zerfiel al-Andalus in über 20 kleine Königreiche, die „Taifas“. Sie bekämpften einander und zahlten den Christen sogar Tribut. Gegen die christliche Bedrohung riefen sie strenggläubige Berberreiche aus Nordafrika zu Hilfe: zuerst die Almoraviden (1086), dann die Almohaden. Unter den Almohaden wurde Sevilla Hauptstadt, wo das Minarett der Moschee, die „Giralda“, entstand – heute Glockenturm der Kathedrale.',
            'Nach der Niederlage der Almohaden 1212 blieb nur das Emirat Granada unter den Nasriden übrig. Es überlebte noch 250 Jahre, indem es Kastilien Tribut zahlte. Die Nasriden bauten auf einem Hügel über Granada die Alhambra („die Rote“), einen Palast mit Wasserbecken, Gärten und kunstvollen Stuckornamenten; berühmt ist der Löwenhof mit seinem von zwölf Steinlöwen getragenen Brunnen. Die Alhambra ist heute eines der meistbesuchten Bauwerke Spaniens.',
          ],
          quiz: {
            leicht: [
              ['Wie nennt man das Zusammenleben in al-Andalus?', 'Convivencia', ['Reconquista', 'Inquisition', 'Siesta']],
              ['Welche Religionen lebten in al-Andalus zusammen?', 'Islam, Christentum und Judentum', ['Islam und Buddhismus', 'Nur der Islam', 'Christentum und Hinduismus']],
              ['Wie hießen Christen, die arabische Kultur annahmen?', 'Mozaraber', ['Mudéjares', 'Moriscos', 'Conversos']],
              ['Welche Ziffern kamen über al-Andalus nach Europa?', 'Die indisch-arabischen Ziffern mit der Null', ['Die römischen Ziffern', 'Die chinesischen Zeichen', 'Die Maya-Ziffern']],
              ['Welcher Philosoph aus Córdoba kommentierte Aristoteles?', 'Averroes', ['Maimonides', 'Seneca', 'Isidor']],
              ['Welcher jüdische Gelehrte stammte aus Córdoba?', 'Maimonides', ['Averroes', 'Spinoza', 'Raschi']],
              ['Welche Pflanze brachten die Araber nach Spanien?', 'Reis', ['Kartoffeln', 'Tomaten', 'Mais']],
              ['Wie viele spanische Wörter stammen etwa aus dem Arabischen?', 'Rund 4000', ['Rund 40', 'Rund 400.000', 'Keines']],
              ['Was bedeutet „azúcar“?', 'Zucker', ['Salz', 'Öl', 'Kissen']],
              ['Was bedeutet „ojalá“ ursprünglich?', '„So Gott will“', ['„Guten Tag“', '„Danke“', '„Auf Wiedersehen“']],
              ['Wo übersetzte man arabische Werke ins Lateinische?', 'In der Übersetzerschule von Toledo', ['In Rom', 'In Paris', 'In Granada']],
              ['Wie hießen die kleinen Königreiche nach 1031?', 'Taifas', ['Emirate', 'Kalifate', 'Grafschaften']],
              ['Wie viele Taifas gab es etwa?', 'Über 20', ['Zwei', 'Über 200', 'Fünf']],
              ['Welche Berberdynastie kam 1086 zu Hilfe?', 'Die Almoraviden', ['Die Umayyaden', 'Die Nasriden', 'Die Abbasiden']],
              ['Welches berühmte Minarett steht in Sevilla?', 'Die Giralda', ['Die Alhambra', 'Die Mezquita', 'Der Herkulesturm']],
              ['Was ist die Giralda heute?', 'Glockenturm der Kathedrale', ['Ein Minarett mit Gebetsruf', 'Ein Leuchtturm', 'Ein Gefängnis']],
              ['Welches Emirat blieb nach 1212 übrig?', 'Granada', ['Córdoba', 'Sevilla', 'Toledo']],
              ['Welche Dynastie herrschte in Granada?', 'Die Nasriden', ['Die Almohaden', 'Die Umayyaden', 'Die Habsburger']],
              ['Welchen Palast bauten die Nasriden?', 'Die Alhambra', ['Die Mezquita', 'Den Escorial', 'Die Giralda']],
              ['Was bedeutet „Alhambra“?', 'Die Rote', ['Die Weiße', 'Die Große', 'Die Heilige']],
            ],
            mittel: [
              ['Was zahlten Christen und Juden in al-Andalus?', 'Eine Sondersteuer', ['Keine Steuern', 'Doppelte Kirchensteuer an Rom', 'Tribut an Kastilien']],
              ['Waren Christen und Juden gleichberechtigt?', 'Nein', ['Ja, völlig', 'Ja, sie herrschten', 'Nur die Juden']],
              ['Wie heißt Averroes auf Arabisch?', 'Ibn Ruschd', ['Ibn Sina', 'Ibn Battuta', 'Ibn Chaldun']],
              ['Wen beeinflusste Averroes?', 'Die europäische Philosophie', ['Nur die arabische Medizin', 'Die chinesische Kunst', 'Niemanden']],
              ['Als was gilt Maimonides?', 'Größter jüdischer Denker des Mittelalters', ['Größter Feldherr', 'Erster Kalif', 'Gründer Toledos']],
              ['Welche Gewürzpflanze brachten die Araber mit?', 'Safran', ['Kakao', 'Vanille', 'Zimt aus Amerika']],
              ['Welche Technik brachten die Araber in die Landwirtschaft?', 'Bewässerungsanlagen', ['Traktoren', 'Gewächshäuser aus Glas', 'Pflüge aus Stahl']],
              ['Was bedeutet „alcalde“?', 'Bürgermeister', ['Burg', 'König', 'Bischof']],
              ['Was bedeutet „almohada“?', 'Kissen', ['Moschee', 'Mandel', 'Markt']],
              ['Was bedeutet „aceite“?', 'Öl', ['Essig', 'Salz', 'Wasser']],
              ['Womit beginnen viele arabische Lehnwörter?', 'Mit „al-“', ['Mit „es-“', 'Mit „ex-“', 'Mit „gu-“']],
              ['Was taten die Taifas untereinander?', 'Sie bekämpften einander', ['Sie bildeten ein Reich', 'Sie lebten in Frieden', 'Sie zogen nach Afrika']],
              ['Wem zahlten die Taifas sogar Tribut?', 'Den Christen', ['Dem Papst', 'Bagdad', 'Den Wikingern']],
              ['Woher kamen Almoraviden und Almohaden?', 'Aus Nordafrika', ['Aus Arabien', 'Aus der Türkei', 'Aus Persien']],
              ['Wie waren Almoraviden und Almohaden religiös?', 'Strenggläubig', ['Christlich', 'Tolerant gegenüber allen', 'Heidnisch']],
              ['Welche Stadt wurde unter den Almohaden Hauptstadt?', 'Sevilla', ['Córdoba', 'Granada', 'Toledo']],
              ['Wann verloren die Almohaden ihre entscheidende Schlacht?', '1212', ['1031', '1086', '1492']],
              ['Wie überlebte Granada so lange?', 'Durch Tributzahlungen an Kastilien', ['Durch eine große Armee', 'Durch Hilfe der Türken', 'Durch Bündnis mit Frankreich']],
              ['Wie lange bestand Granada nach 1212 noch?', 'Rund 250 Jahre', ['25 Jahre', '500 Jahre', '5 Jahre']],
              ['Wie viele Steinlöwen tragen den Brunnen im Löwenhof?', 'Zwölf', ['Vier', 'Acht', 'Zwanzig']],
            ],
            schwer: [
              ['Gab es in al-Andalus auch Verfolgung?', 'Ja, zeitweise', ['Nein, nie', 'Nur von Muslimen durch Christen', 'Nur im Jahr 711']],
              ['Wie gelangte arabisches Wissen ins christliche Europa?', 'Über Übersetzungen ins Lateinische in Toledo', ['Über Kreuzzüge in Spanien', 'Über den Buchdruck', 'Gar nicht']],
              ['Wessen Werke kommentierte Averroes?', 'Die des Aristoteles', ['Die Platons', 'Die Senecas', 'Die Bibel']],
              ['Wo liegt die Alhambra?', 'Auf einem Hügel über Granada', ['In Córdoba', 'Am Meer bei Málaga', 'In Sevilla']],
              ['Welche Elemente prägen die Alhambra?', 'Wasserbecken, Gärten und Stuckornamente', ['Glasfenster und Türme', 'Fresken mit Heiligen', 'Mosaiken mit Kaisern']],
              ['Was folgte nach den Almoraviden?', 'Die Almohaden', ['Die Umayyaden', 'Die Nasriden direkt', 'Die Habsburger']],
              ['Warum riefen die Taifas die Almoraviden?', 'Gegen die christliche Bedrohung', ['Gegen die Wikinger', 'Gegen Frankreich', 'Für den Handel']],
              ['Was war die Giralda ursprünglich?', 'Das Minarett der Moschee von Sevilla', ['Ein römischer Turm', 'Ein westgotischer Palast', 'Ein Leuchtturm']],
              ['Welche Pflanzen brachten die Araber außer Reis?', 'Zitrusfrüchte, Zuckerrohr und Auberginen', ['Kartoffeln und Tomaten', 'Mais und Kakao', 'Tabak und Kaffee']],
              ['Woher stammen die Ziffern mit der Null ursprünglich?', 'Aus Indien, über die Araber', ['Aus Rom', 'Aus China über Russland', 'Aus Kastilien']],
              ['Was war Granada nach 1212?', 'Das letzte muslimische Reich in Spanien', ['Eine christliche Stadt', 'Teil Portugals', 'Hauptstadt der Almohaden']],
              ['Was ist am Löwenhof besonders?', 'Ein von Steinlöwen getragener Brunnen', ['Ein lebender Löwe', 'Ein Löwengemälde', 'Ein Löwengrab']],
              ['Wann zerfiel al-Andalus in Taifas?', 'Nach 1031', ['Nach 711', 'Nach 1492', 'Nach 929']],
              ['Welche Stadt ist Heimat von Averroes und Maimonides?', 'Córdoba', ['Granada', 'Toledo', 'Sevilla']],
              ['Was war die Übersetzerschule?', 'Eine Gelehrtengruppe in Toledo, die Arabisch ins Latein übersetzte', ['Eine Sprachschule für Kinder', 'Eine Moschee', 'Eine Universität in Córdoba']],
              ['Was beweisen arabische Lehnwörter im Spanischen?', 'Den tiefen kulturellen Einfluss von al-Andalus', ['Eine Eroberung Arabiens', 'Nichts', 'Englischen Einfluss']],
              ['Wie behandelten die Nasriden Kastilien?', 'Sie zahlten Tribut', ['Sie eroberten es', 'Sie ignorierten es', 'Sie heirateten seinen König']],
              ['Welches Wort bedeutet „Bürgermeister“ und kommt aus dem Arabischen?', 'Alcalde', ['Alcázar', 'Almohada', 'Aceite']],
              ['Welche Stellung hatten Mozaraber?', 'Christen mit arabischer Kultur', ['Muslime in Kastilien', 'Juden in Granada', 'Berberkrieger']],
              ['Welche Dynastie regierte Sevilla als Hauptstadt?', 'Die Almohaden', ['Die Nasriden', 'Die Umayyaden', 'Die Westgoten']],
            ],
          },
        },
      ],
    },
    {
      id: 'reconquista',
      title: 'Reconquista und Katholische Könige',
      date: '722–1492',
      text: [
        'In fast acht Jahrhunderten eroberten die christlichen Reiche des Nordens die Halbinsel zurück. 1492 fiel Granada an die Katholischen Könige Isabella und Ferdinand – im selben Jahr wurden die Juden vertrieben und Kolumbus erreichte Amerika.',
      ],
      subtopics: [
        {
          id: 'cid-kastilien',
          title: 'Jakobsweg, El Cid und die christlichen Reiche',
          date: '800–1252',
          text: [
            'Um 820 soll in Galicien das Grab des Apostels Jakobus (Santiago) entdeckt worden sein. Santiago de Compostela wurde neben Rom und Jerusalem zum wichtigsten Pilgerziel der Christenheit. Pilger aus ganz Europa wanderten auf dem Jakobsweg dorthin, ihr Zeichen ist die Jakobsmuschel. Jakobus wurde als „Matamoros“ (Maurentöter) zum Schutzheiligen der Reconquista, „Santiago y cierra, España!“ war ihr Schlachtruf.',
            'Im Norden entstanden mehrere christliche Reiche: Asturien-León, Kastilien (benannt nach den vielen Burgen, „castillos“), Navarra, Aragón und die Grafschaft Barcelona. Aragón und Katalonien vereinten sich 1137 durch Heirat zur „Krone Aragón“, die später Mallorca, Valencia, Sizilien und Neapel beherrschte. Portugal löste sich 1139/1143 von León und wurde ein eigenes Königreich.',
            'Rodrigo Díaz de Vivar, genannt „El Cid“ (vom arabischen „Sayyid“, Herr), war ein kastilischer Ritter, der um 1043–1099 lebte. Er diente christlichen wie muslimischen Herrschern, wurde vom König verbannt und eroberte 1094 auf eigene Faust Valencia. Das Heldenepos „Cantar de mio Cid“ ist eines der ältesten Werke der spanischen Literatur. Der Legende nach band man ihn nach seinem Tod tot auf sein Pferd, um die Feinde noch einmal zu erschrecken.',
            '1085 eroberte König Alfons VI. von Kastilien Toledo, die alte Hauptstadt der Westgoten. 1212 besiegten die vereinten Heere von Kastilien, Aragón und Navarra die Almohaden in der Schlacht von Las Navas de Tolosa – die Wende der Reconquista. Danach eroberte Ferdinand III. von Kastilien („der Heilige“) 1236 Córdoba und 1248 Sevilla; Jakob I. von Aragón („der Eroberer“) nahm Mallorca (1229) und Valencia (1238).',
            'Ritterorden wie die von Santiago, Calatrava und Alcántara verteidigten die Grenzgebiete. Die Eroberer siedelten Christen aus dem Norden an („Repoblación“). Muslime, die unter christlicher Herrschaft blieben, hießen „Mudéjares“; ihr Baustil mit Ziegeln und Ornamenten, der „Mudéjar-Stil“, prägt viele Kirchen und den Alcázar von Sevilla. Alfons X. „der Weise“ (1252–1284) förderte Wissenschaft und Dichtung und machte Kastilisch statt Latein zur Sprache der Gesetze.',
          ],
          quiz: {
            leicht: [
              ['Wessen Grab soll in Galicien entdeckt worden sein?', 'Das des Apostels Jakobus', ['Das des Petrus', 'Das von El Cid', 'Das des Pelayo']],
              ['Wie heißt Jakobus auf Spanisch?', 'Santiago', ['San José', 'San Juan', 'San Pedro']],
              ['Wie heißt der Pilgerweg nach Santiago?', 'Jakobsweg', ['Via Appia', 'Seidenstraße', 'Pilgerpfad von Rom']],
              ['Was ist das Zeichen der Jakobspilger?', 'Die Jakobsmuschel', ['Ein Kreuz aus Gold', 'Ein Schlüssel', 'Ein Fisch']],
              ['Wie nannte man Jakobus als Schutzheiligen der Reconquista?', '„Matamoros“ (Maurentöter)', ['„El Sabio“', '„El Cid“', '„El Santo“']],
              ['Wonach ist Kastilien benannt?', 'Nach den vielen Burgen', ['Nach einem König', 'Nach einem Fluss', 'Nach einer Heiligen']],
              ['Welches Land löste sich im 12. Jahrhundert von León?', 'Portugal', ['Navarra', 'Aragón', 'Galicien']],
              ['Wie nannte man Rodrigo Díaz de Vivar?', 'El Cid', ['El Greco', 'El Sabio', 'El Santo']],
              ['Woher kommt „Cid“?', 'Vom arabischen „Sayyid“ (Herr)', ['Vom lateinischen „Caesar“', 'Vom gotischen „König“', 'Vom Namen seines Pferdes']],
              ['Welche Stadt eroberte El Cid 1094?', 'Valencia', ['Toledo', 'Granada', 'Sevilla']],
              ['Wie heißt das Heldenepos über El Cid?', '„Cantar de mio Cid“', ['„Don Quijote“', '„Rolandslied“', '„Nibelungenlied“']],
              ['Welche Stadt eroberte Alfons VI. 1085?', 'Toledo', ['Córdoba', 'Sevilla', 'Granada']],
              ['Welche Schlacht 1212 war die Wende der Reconquista?', 'Las Navas de Tolosa', ['Covadonga', 'Guadalete', 'Lepanto']],
              ['Wer eroberte Córdoba und Sevilla?', 'Ferdinand III.', ['Alfons VI.', 'El Cid', 'Jakob I.']],
              ['Wann fiel Sevilla an Kastilien?', '1248', ['1085', '1212', '1492']],
              ['Wer eroberte Mallorca und Valencia?', 'Jakob I. von Aragón', ['Ferdinand III.', 'Alfons X.', 'El Cid']],
              ['Wie hießen Muslime unter christlicher Herrschaft?', 'Mudéjares', ['Mozaraber', 'Moriscos', 'Conversos']],
              ['Welcher Baustil verbindet christliche und islamische Elemente?', 'Mudéjar-Stil', ['Gotik', 'Barock', 'Romanik']],
              ['Welcher König hieß „der Weise“?', 'Alfons X.', ['Ferdinand III.', 'Alfons VI.', 'Jakob I.']],
              ['Welche Sprache machte Alfons X. zur Sprache der Gesetze?', 'Kastilisch', ['Latein', 'Arabisch', 'Katalanisch']],
            ],
            mittel: [
              ['Wann soll das Jakobusgrab entdeckt worden sein?', 'Um 820', ['Um 711', 'Um 1085', 'Um 1492']],
              ['Welche Pilgerziele waren wichtiger oder gleichrangig?', 'Rom und Jerusalem', ['Mekka und Medina', 'Paris und London', 'Toledo und Córdoba']],
              ['Wie lautete der Schlachtruf der Reconquista?', '„Santiago y cierra, España!“', ['„Viva la Libertad!“', '„Vive le roi!“', '„No pasarán!“']],
              ['Welche Reiche vereinten sich 1137 zur Krone Aragón?', 'Aragón und Katalonien', ['Kastilien und León', 'Navarra und Portugal', 'Galicien und Asturien']],
              ['Wie vereinten sich Aragón und Katalonien?', 'Durch Heirat', ['Durch Krieg', 'Durch Kauf', 'Durch Papstbeschluss']],
              ['Was beherrschte die Krone Aragón später?', 'Mallorca, Valencia, Sizilien und Neapel', ['Portugal und Galicien', 'Frankreich', 'Granada']],
              ['Wann wurde Portugal eigenes Königreich?', '1139/1143', ['1085', '1212', '1492']],
              ['Wann lebte El Cid?', 'Um 1043–1099', ['Um 711–780', 'Um 1200–1250', 'Um 1450–1500']],
              ['Wem diente El Cid?', 'Christlichen und muslimischen Herrschern', ['Nur dem Papst', 'Nur dem Kalifen', 'Nur Frankreich']],
              ['Was geschah mit El Cid unter dem König?', 'Er wurde verbannt', ['Er wurde König', 'Er wurde Bischof', 'Er wurde hingerichtet']],
              ['Was erzählt die Legende über El Cids Tod?', 'Man band ihn tot aufs Pferd, um Feinde zu erschrecken', ['Er wurde im Schlaf ermordet', 'Er wurde Mönch', 'Er floh nach Afrika']],
              ['Welche Reiche kämpften 1212 gemeinsam?', 'Kastilien, Aragón und Navarra', ['Portugal und Frankreich', 'León und Granada', 'Kastilien und die Almohaden']],
              ['Wen besiegten sie 1212?', 'Die Almohaden', ['Die Almoraviden', 'Die Nasriden', 'Die Umayyaden']],
              ['Wann eroberte Ferdinand III. Córdoba?', '1236', ['1085', '1248', '1212']],
              ['Wie nannte man Ferdinand III.?', '„Der Heilige“', ['„Der Weise“', '„Der Eroberer“', '„Der Kühne“']],
              ['Wie nannte man Jakob I.?', '„Der Eroberer“', ['„Der Heilige“', '„Der Weise“', '„Der Grausame“']],
              ['Wann eroberte Jakob I. Mallorca?', '1229', ['1238', '1085', '1248']],
              ['Welche Ritterorden verteidigten die Grenzen?', 'Santiago, Calatrava und Alcántara', ['Die Franziskaner', 'Deutscher Orden', 'Jesuiten']],
              ['Wie nennt man die Neubesiedlung eroberter Gebiete?', 'Repoblación', ['Reconquista', 'Convivencia', 'Conquista']],
              ['Wann regierte Alfons X.?', '1252–1284', ['1065–1109', '1217–1252', '1474–1504']],
            ],
            schwer: [
              ['Welcher Palast in Sevilla zeigt den Mudéjar-Stil?', 'Der Alcázar von Sevilla', ['Die Alhambra', 'Der Escorial', 'Die Mezquita']],
              ['Was förderte Alfons X.?', 'Wissenschaft und Dichtung', ['Nur Kriege', 'Die Inquisition', 'Die Seefahrt nach Amerika']],
              ['Warum war Toledo 1085 symbolisch wichtig?', 'Es war die alte Hauptstadt der Westgoten', ['Es war die Hauptstadt der Römer', 'Dort lag das Jakobusgrab', 'Dort lebte El Cid']],
              ['Was bedeutete Las Navas de Tolosa?', 'Die Wende der Reconquista', ['Das Ende der Westgoten', 'Den Beginn von al-Andalus', 'Den Fall Granadas']],
              ['Was tat El Cid in Valencia?', 'Er eroberte es auf eigene Faust', ['Er gründete es', 'Er verlor es an Kastilien', 'Er starb dort im Kampf 1094']],
              ['Welche Stellung hat der „Cantar de mio Cid“?', 'Eines der ältesten Werke der spanischen Literatur', ['Das jüngste Werk', 'Ein arabisches Gedicht', 'Ein Gesetzbuch']],
              ['Welches Reich entstand aus Asturien zuerst?', 'León', ['Aragón', 'Navarra', 'Portugal']],
              ['Was charakterisiert den Mudéjar-Stil?', 'Ziegel und Ornamente', ['Glas und Stahl', 'Marmorsäulen', 'Holzbauten']],
              ['Was war die Aufgabe der Ritterorden?', 'Grenzgebiete verteidigen', ['Handel treiben', 'Bücher übersetzen', 'Kathedralen bauen']],
              ['Wen siedelte man in eroberten Gebieten an?', 'Christen aus dem Norden', ['Araber aus Bagdad', 'Juden aus Rom', 'Franken']],
              ['Wann eroberte Jakob I. Valencia?', '1238', ['1094', '1229', '1248']],
              ['Wer hat El Cid verbannt?', 'Der König (von Kastilien)', ['Der Papst', 'Der Kalif', 'Die Almoraviden']],
              ['Warum wurde Jakobus „Matamoros“ genannt?', 'Er galt als Schutzheiliger im Kampf gegen die Mauren', ['Er war Arzt', 'Er hatte die Mauren bekehrt', 'Er war maurischer Herkunft']],
              ['Was bezeichnet „Repoblación“?', 'Neubesiedlung eroberter Gebiete', ['Vertreibung der Christen', 'Gründung von Klöstern', 'Bau von Burgen']],
              ['Welche Rolle spielte die Krone Aragón im Mittelmeer?', 'Sie beherrschte Inseln und Süditalien', ['Keine', 'Sie war Teil von Granada', 'Sie war eine Kolonie Genuas']],
              ['Wie wurde Jakobus’ Grab berühmt?', 'Als Pilgerziel der Christenheit', ['Als Festung', 'Als Marktplatz', 'Als Moschee']],
              ['Wann fiel Córdoba an die Christen?', '1236', ['1031', '1085', '1492']],
              ['Woher stammen die Wörter „Kastilien“ und „castillo“?', 'Beide meinen Burg(en)', ['Beide meinen Kirche', 'Beide meinen König', 'Beide meinen Fluss']],
              ['Was machte Alfons X. statt Latein zur Sprache der Gesetze?', 'Kastilisch', ['Arabisch', 'Französisch', 'Galicisch']],
              ['Welches Ereignis war 1212?', 'Sieg bei Las Navas de Tolosa', ['Eroberung Toledos', 'Fall Granadas', 'Tod El Cids']],
            ],
          },
        },
        {
          id: 'katholische-koenige',
          title: 'Isabella, Ferdinand und das Jahr 1492',
          date: '1469–1504',
          text: [
            '1469 heirateten Isabella von Kastilien und Ferdinand von Aragón heimlich in Valladolid. Nach einem Erbfolgekrieg wurde Isabella 1474 Königin von Kastilien, Ferdinand 1479 König von Aragón. Beide Reiche blieben formal getrennt, wurden aber gemeinsam regiert – der Beginn des modernen Spanien. Ihr Motto lautete „Tanto monta, monta tanto“ (das eine gilt so viel wie das andere). Papst Alexander VI. verlieh ihnen 1496 den Titel „Katholische Könige“.',
            '1478 gründeten sie mit Erlaubnis des Papstes die Spanische Inquisition, die dem König unterstand. Sie sollte „Conversos“ verfolgen – getaufte Juden, die verdächtigt wurden, heimlich ihren alten Glauben zu leben. Der erste Großinquisitor Tomás de Torquemada wurde zum Symbol religiöser Unduldsamkeit. Bei öffentlichen „Autos de fe“ (Glaubensakten) wurden Verurteilte bestraft, Tausende auf Scheiterhaufen verbrannt.',
            'Nach zehnjährigem Krieg übergab der letzte Emir Boabdil am 2. Januar 1492 Granada den Katholischen Königen. Der Legende nach blickte er auf der Flucht ein letztes Mal zurück und weinte, worauf seine Mutter sagte: „Weine wie eine Frau um das, was du nicht wie ein Mann verteidigen konntest.“ Die Stelle heißt bis heute „Seufzer des Mauren“. Die Reconquista war nach fast 800 Jahren beendet.',
            'Am 31. März 1492 befahlen die Könige im Alhambra-Edikt allen Juden, sich taufen zu lassen oder Spanien bis Ende Juli zu verlassen. Zehntausende gingen nach Portugal, Nordafrika, Italien und ins Osmanische Reich. Ihre Nachfahren, die „Sepharden“, sprachen jahrhundertelang weiter ein altes Spanisch (Ladino). 1502 wurden auch die Muslime Kastiliens zur Taufe gezwungen; die getauften Muslime hießen „Moriscos“ und wurden 1609 ebenfalls vertrieben. Erst 2015 bot Spanien den Nachfahren der Sepharden die Staatsbürgerschaft an.',
            'Im selben Jahr 1492 unterstützte Isabella den Genuesen Christoph Kolumbus, der Indien über den Westweg erreichen wollte. Am 12. Oktober 1492 erreichte er eine Insel der Bahamas – der Beginn der Eroberung Amerikas. Der 12. Oktober ist heute Spaniens Nationalfeiertag. Ebenfalls 1492 veröffentlichte Antonio de Nebrija die erste Grammatik der kastilischen Sprache. Isabella starb 1504; ihre Tochter Johanna („die Wahnsinnige“) heiratete Philipp den Schönen von Habsburg – so kam Spanien an die Habsburger.',
          ],
          quiz: {
            leicht: [
              ['Wer heiratete 1469?', 'Isabella von Kastilien und Ferdinand von Aragón', ['Karl V. und Isabella von Portugal', 'Philipp II. und Maria Tudor', 'Johanna und Philipp']],
              ['Wie nennt man Isabella und Ferdinand?', 'Die Katholischen Könige', ['Die Heiligen Könige', 'Die Großen Könige', 'Die Spanischen Kaiser']],
              ['Welcher Papst verlieh den Titel?', 'Alexander VI.', ['Julius II.', 'Gregor XIII.', 'Leo X.']],
              ['Welche Einrichtung gründeten sie 1478?', 'Die Spanische Inquisition', ['Die Universität Salamanca', 'Die Armada', 'Den Jesuitenorden']],
              ['Wer war der erste Großinquisitor?', 'Tomás de Torquemada', ['Ignatius von Loyola', 'Kolumbus', 'Boabdil']],
              ['Wie hießen die öffentlichen Glaubensakte?', 'Autos de fe', ['Corridas', 'Fiestas', 'Cortes']],
              ['Wann fiel Granada?', '2. Januar 1492', ['12. Oktober 1492', '31. März 1492', '1. Januar 1500']],
              ['Wer war der letzte Emir von Granada?', 'Boabdil', ['Almansor', 'Abd ar-Rahman', 'Tariq']],
              ['Wie heißt die Stelle, an der Boabdil zurückblickte?', '„Seufzer des Mauren“', ['„Tränen der Alhambra“', '„Blick des Kalifen“', '„Abschied von Spanien“']],
              ['Wie lange dauerte die Reconquista?', 'Fast 800 Jahre', ['80 Jahre', '200 Jahre', '1000 Jahre']],
              ['Was befahl das Alhambra-Edikt den Juden?', 'Taufe oder Ausreise', ['Steuern zahlen', 'In Granada wohnen', 'Kriegsdienst']],
              ['Wie nennt man die Nachfahren der spanischen Juden?', 'Sepharden', ['Aschkenasim', 'Mozaraber', 'Moriscos']],
              ['Welche Sprache sprachen die Sepharden?', 'Ladino (altes Spanisch)', ['Jiddisch', 'Arabisch', 'Portugiesisch']],
              ['Wie hießen die getauften Muslime?', 'Moriscos', ['Mudéjares', 'Mozaraber', 'Conversos']],
              ['Wen unterstützte Isabella 1492?', 'Christoph Kolumbus', ['Vasco da Gama', 'Magellan', 'Amerigo Vespucci']],
              ['Woher stammte Kolumbus?', 'Aus Genua', ['Aus Sevilla', 'Aus Lissabon', 'Aus Venedig']],
              ['Wann erreichte Kolumbus Amerika?', '12. Oktober 1492', ['2. Januar 1492', '31. März 1492', '12. Oktober 1500']],
              ['Was ist der 12. Oktober in Spanien?', 'Nationalfeiertag', ['Tag der Arbeit', 'Weihnachten', 'Tag der Verfassung']],
              ['Wer schrieb 1492 die erste kastilische Grammatik?', 'Antonio de Nebrija', ['Cervantes', 'Torquemada', 'Alfons X.']],
              ['An welche Dynastie kam Spanien durch Johannas Heirat?', 'An die Habsburger', ['An die Bourbonen', 'An die Tudors', 'An die Medici']],
            ],
            mittel: [
              ['Wo heirateten Isabella und Ferdinand?', 'Heimlich in Valladolid', ['Im Petersdom', 'In Granada', 'In Toledo öffentlich']],
              ['Wann wurde Isabella Königin von Kastilien?', '1474', ['1469', '1479', '1492']],
              ['Wann wurde Ferdinand König von Aragón?', '1479', ['1469', '1474', '1492']],
              ['Waren Kastilien und Aragón formal vereint?', 'Nein, sie blieben getrennt, aber gemeinsam regiert', ['Ja, völlig verschmolzen', 'Nein, sie kämpften gegeneinander', 'Nur auf dem Papier des Papstes']],
              ['Wie lautete das Motto der Katholischen Könige?', '„Tanto monta, monta tanto“', ['„Plus ultra“', '„Dios, patria, rey“', '„Viva España“']],
              ['Wann erhielten sie den Titel „Katholische Könige“?', '1496', ['1469', '1478', '1504']],
              ['Wem unterstand die Spanische Inquisition?', 'Dem König', ['Dem Papst direkt', 'Den Bischöfen', 'Den Städten']],
              ['Wer waren die „Conversos“?', 'Getaufte Juden', ['Getaufte Muslime', 'Christen in Granada', 'Protestanten']],
              ['Wofür wurde Torquemada zum Symbol?', 'Für religiöse Unduldsamkeit', ['Für Toleranz', 'Für Seefahrt', 'Für Kunst']],
              ['Wie lange dauerte der Krieg um Granada?', 'Zehn Jahre', ['Ein Jahr', '100 Jahre', 'Zehn Tage']],
              ['Was sagte Boabdils Mutter?', '„Weine wie eine Frau um das, was du nicht wie ein Mann verteidigen konntest“', ['„Gott ist groß“', '„Kehre nie zurück“', '„Granada ist ewig“']],
              ['Wann wurde das Alhambra-Edikt erlassen?', '31. März 1492', ['2. Januar 1492', '12. Oktober 1492', '1478']],
              ['Bis wann mussten die Juden Spanien verlassen?', 'Bis Ende Juli 1492', ['Bis Weihnachten 1492', 'Bis 1500', 'Sofort am selben Tag']],
              ['Wohin gingen die vertriebenen Juden?', 'Nach Portugal, Nordafrika, Italien und ins Osmanische Reich', ['Nach Amerika und England', 'Nach Russland', 'Nach China']],
              ['Wann wurden die Muslime Kastiliens zur Taufe gezwungen?', '1502', ['1492', '1609', '1478']],
              ['Wann wurden die Moriscos vertrieben?', '1609', ['1502', '1492', '1700']],
              ['Wann bot Spanien den Sepharden die Staatsbürgerschaft an?', '2015', ['1975', '1992', '1950']],
              ['Was wollte Kolumbus erreichen?', 'Indien über den Westweg', ['Amerika', 'China über Afrika', 'Den Nordpol']],
              ['Wo landete Kolumbus 1492?', 'Auf einer Insel der Bahamas', ['In Brasilien', 'In Mexiko', 'In Florida']],
              ['Wann starb Isabella?', '1504', ['1492', '1516', '1479']],
            ],
            schwer: [
              ['Wie nannte man Isabellas Tochter Johanna?', '„Die Wahnsinnige“', ['„Die Heilige“', '„Die Schöne“', '„Die Katholische“']],
              ['Wen heiratete Johanna?', 'Philipp den Schönen von Habsburg', ['Heinrich VIII.', 'Karl VIII.', 'Manuel von Portugal']],
              ['Was bedeutet „Tanto monta, monta tanto“?', 'Das eine gilt so viel wie das andere', ['Gott mit uns', 'Immer weiter', 'Für Kastilien']],
              ['Was ging dem Thron Isabellas voraus?', 'Ein Erbfolgekrieg', ['Eine Revolution', 'Eine Pest', 'Ein Krieg gegen Frankreich']],
              ['Welche drei Ereignisse machen 1492 berühmt?', 'Fall Granadas, Vertreibung der Juden, Kolumbus', ['Gründung der Inquisition, Hochzeit, Isabellas Tod', 'Armada, Lepanto, Escorial', 'El Cid, Toledo, Las Navas']],
              ['Was verdächtigte man die Conversos?', 'Heimlich ihren alten Glauben zu leben', ['Spionage für Frankreich', 'Diebstahl', 'Hexerei']],
              ['Wie wurden viele Verurteilte der Inquisition bestraft?', 'Tausende wurden verbrannt', ['Nur mit Geldstrafen', 'Gar nicht', 'Mit Verbannung nach Amerika']],
              ['Was bezeichnet der Beginn des modernen Spanien?', 'Die gemeinsame Regierung von Kastilien und Aragón', ['Die Ankunft der Römer', 'Die Landung Tariqs', 'Der Tod Francos']],
              ['Wie lange sprachen Sepharden Ladino?', 'Jahrhundertelang', ['Nur ein Jahr', 'Gar nicht', 'Bis 1500']],
              ['Mit wessen Erlaubnis entstand die Inquisition?', 'Mit Erlaubnis des Papstes', ['Ohne Erlaubnis', 'Mit Erlaubnis des Kaisers', 'Mit Erlaubnis der Kalifen']],
              ['Welche Bedeutung hat Nebrijas Werk?', 'Erste Grammatik der kastilischen Sprache', ['Erste spanische Bibel', 'Erste Landkarte Amerikas', 'Erstes Gesetzbuch']],
              ['Wann wurde die Inquisition gegründet?', '1478', ['1492', '1469', '1502']],
              ['Was war Boabdil?', 'Letzter Emir von Granada', ['Erster Kalif von Córdoba', 'Ein Berberkrieger', 'Ein Inquisitor']],
              ['Was erhielt Isabella durch den Fall Granadas?', 'Das letzte muslimische Reich in Spanien', ['Portugal', 'Neapel', 'Amerika']],
              ['Wie wurden die Moriscos schließlich behandelt?', 'Sie wurden 1609 vertrieben', ['Sie wurden gleichberechtigt', 'Sie regierten Granada', 'Sie gingen nach Amerika']],
              ['Was war Kolumbus’ Irrtum?', 'Er glaubte, Indien erreicht zu haben', ['Er glaubte, in Afrika zu sein', 'Er hielt Amerika für Spanien', 'Er hatte keinen']],
              ['In welcher Stadt wurde das Edikt gegen die Juden erlassen?', 'In Granada (in der Alhambra)', ['In Toledo', 'In Madrid', 'In Sevilla']],
              ['Welche Haltung prägte die Katholischen Könige gegenüber Minderheiten?', 'Religiöse Einheit durch Zwang', ['Toleranz', 'Gleichgültigkeit', 'Förderung des Islam']],
              ['Wie kamen die Habsburger nach Spanien?', 'Durch die Heirat Johannas mit Philipp', ['Durch Eroberung', 'Durch Wahl der Cortes', 'Durch Kauf']],
              ['Wohin zogen viele Sepharden im Osten?', 'Ins Osmanische Reich', ['Nach Russland', 'Nach Persien', 'Nach Indien']],
            ],
          },
        },
      ],
    },
  ],
};
