import type { Epoch } from '../types';

export const E3: Epoch = {
  id: 'weltreich',
  name: 'Weltreich und Niedergang',
  period: '1492–1700',
  events: [
    {
      id: 'weltreich',
      title: 'Das Weltreich der Habsburger',
      date: '1492–1598',
      text: [
        'Nach 1492 eroberte Spanien ein Weltreich in Amerika. Unter Karl V. und Philipp II. war es die mächtigste Macht Europas – ein Reich, „in dem die Sonne nie untergeht“, bezahlt mit Silber aus Amerika und dem Leid der Ureinwohner.',
      ],
      subtopics: [
        {
          id: 'conquista',
          title: 'Die Eroberung Amerikas',
          date: '1492–1572',
          text: [
            'Nach Kolumbus’ Fahrt teilten Spanien und Portugal 1494 im Vertrag von Tordesillas die Welt entlang einer Linie im Atlantik: Der Westen sollte spanisch, der Osten portugiesisch sein – deshalb spricht man in Brasilien heute Portugiesisch. Kolumbus unternahm vier Reisen und starb 1506 im Glauben, er habe Asien erreicht. Benannt wurde der Kontinent nach dem Florentiner Amerigo Vespucci.',
            'Die Eroberer hießen „Conquistadores“. 1519 landete Hernán Cortés mit rund 500 Mann in Mexiko. Er verbündete sich mit Völkern, die von den Azteken unterdrückt wurden, und zog in die Hauptstadt Tenochtitlan, eine Stadt auf einem See mit rund 200.000 Einwohnern. Herrscher Moctezuma wurde gefangen genommen und starb 1520. 1521 fiel die Stadt nach monatelanger Belagerung; auf ihren Ruinen entstand Mexiko-Stadt. Eine Indigene namens Malinche diente Cortés als Übersetzerin.',
            '1532 nahm Francisco Pizarro mit nur 168 Mann in Cajamarca den Inka-Herrscher Atahualpa gefangen. Atahualpa versprach als Lösegeld, einen Raum einmal mit Gold und zweimal mit Silber zu füllen – Pizarro ließ ihn trotzdem 1533 hinrichten. Die Spanier siegten auch dank Pferden, Stahlwaffen und Feuerwaffen, vor allem aber, weil eingeschleppte Krankheiten wie Pocken Millionen Ureinwohner töteten.',
            'Die Spanier schufen Vizekönigreiche wie Neuspanien (Mexiko) und Peru. Im „Encomienda“-System mussten Ureinwohner für spanische Herren arbeiten. Der Dominikanermönch Bartolomé de las Casas klagte die Grausamkeiten an und erreichte 1542 die „Neuen Gesetze“, die die Indigenen schützen sollten. Um sie zu ersetzen, wurden bald Millionen Afrikaner als Sklaven nach Amerika verschleppt.',
            'Aus dem „Silberberg“ von Potosí (heute Bolivien) und aus Mexiko kamen riesige Mengen Silber. Jedes Jahr segelte die Silberflotte nach Sevilla, das das Monopol auf den Amerikahandel hatte und zur reichsten Stadt Spaniens wurde. Aus Amerika kamen Kartoffeln, Tomaten, Mais, Kakao und Tabak nach Europa. 1519–1522 umrundete eine spanische Expedition unter Ferdinand Magellan erstmals die Erde; Magellan selbst starb auf den Philippinen, die später nach König Philipp II. benannt wurden.',
          ],
          quiz: {
            leicht: [
              ['Wie teilten Spanien und Portugal 1494 die Welt?', 'Im Vertrag von Tordesillas', ['Im Vertrag von Versailles', 'Im Westfälischen Frieden', 'Im Vertrag von Granada']],
              ['Warum spricht man in Brasilien Portugiesisch?', 'Wegen des Vertrags von Tordesillas', ['Wegen Kolumbus', 'Wegen Napoleon', 'Zufällig']],
              ['Wie viele Reisen unternahm Kolumbus?', 'Vier', ['Eine', 'Zwei', 'Zehn']],
              ['Nach wem ist Amerika benannt?', 'Nach Amerigo Vespucci', ['Nach Kolumbus', 'Nach einem König', 'Nach einem Indianerstamm']],
              ['Wie nannte man die spanischen Eroberer?', 'Conquistadores', ['Inquisitoren', 'Kreuzritter', 'Hugenotten']],
              ['Wer eroberte das Aztekenreich?', 'Hernán Cortés', ['Francisco Pizarro', 'Kolumbus', 'Magellan']],
              ['Wie hieß die Hauptstadt der Azteken?', 'Tenochtitlan', ['Cusco', 'Machu Picchu', 'Lima']],
              ['Wie hieß der Aztekenherrscher?', 'Moctezuma', ['Atahualpa', 'Montezuma von Peru', 'Tupac Amaru']],
              ['Welche Stadt entstand auf den Ruinen Tenochtitlans?', 'Mexiko-Stadt', ['Lima', 'Havanna', 'Bogotá']],
              ['Wer eroberte das Inkareich?', 'Francisco Pizarro', ['Hernán Cortés', 'Magellan', 'Las Casas']],
              ['Wie hieß der Inka-Herrscher, den Pizarro gefangen nahm?', 'Atahualpa', ['Moctezuma', 'Pachacútec', 'Malinche']],
              ['Was tötete die meisten Ureinwohner?', 'Eingeschleppte Krankheiten wie Pocken', ['Erdbeben', 'Hunger durch Dürre', 'Kriege untereinander']],
              ['Welcher Mönch klagte die Grausamkeiten an?', 'Bartolomé de las Casas', ['Torquemada', 'Ignatius von Loyola', 'Franz Xaver']],
              ['Woher kam viel Silber?', 'Aus Potosí', ['Aus Toledo', 'Aus Brasilien', 'Aus Kuba']],
              ['Welche Stadt hatte das Monopol auf den Amerikahandel?', 'Sevilla', ['Madrid', 'Barcelona', 'Valencia']],
              ['Welche Pflanze kam aus Amerika nach Europa?', 'Die Kartoffel', ['Der Reis', 'Der Weizen', 'Die Olive']],
              ['Wer leitete die erste Weltumsegelung?', 'Ferdinand Magellan', ['Kolumbus', 'Vasco da Gama', 'Cortés']],
              ['Wo starb Magellan?', 'Auf den Philippinen', ['In Sevilla', 'In Südamerika', 'Im Atlantik']],
              ['Nach wem sind die Philippinen benannt?', 'Nach König Philipp II.', ['Nach Philipp dem Schönen', 'Nach einem Heiligen', 'Nach Magellan']],
              ['Wer diente Cortés als Übersetzerin?', 'Malinche', ['Pocahontas', 'Isabella', 'Johanna']],
            ],
            mittel: [
              ['Welcher Teil der Welt sollte laut Tordesillas spanisch sein?', 'Der Westen der Linie', ['Der Osten der Linie', 'Der Norden', 'Afrika']],
              ['Wann starb Kolumbus?', '1506', ['1492', '1519', '1500']],
              ['Was glaubte Kolumbus bis zu seinem Tod?', 'Er habe Asien erreicht', ['Er habe Amerika entdeckt', 'Die Erde sei flach', 'Er sei in Afrika gewesen']],
              ['Woher stammte Amerigo Vespucci?', 'Aus Florenz', ['Aus Genua', 'Aus Sevilla', 'Aus Lissabon']],
              ['Wann landete Cortés in Mexiko?', '1519', ['1492', '1532', '1521']],
              ['Mit wie vielen Männern landete Cortés etwa?', 'Rund 500', ['Rund 50', 'Rund 5000', 'Rund 50.000']],
              ['Mit wem verbündete sich Cortés?', 'Mit Völkern, die von den Azteken unterdrückt wurden', ['Mit den Inka', 'Mit Portugal', 'Mit den Franzosen']],
              ['Wie viele Einwohner hatte Tenochtitlan etwa?', 'Rund 200.000', ['Rund 2000', 'Rund 20.000', 'Rund 2 Millionen']],
              ['Wo lag Tenochtitlan?', 'Auf einem See', ['Auf einem Berg', 'Am Meer', 'In der Wüste']],
              ['Wann fiel Tenochtitlan?', '1521', ['1519', '1532', '1492']],
              ['Wann nahm Pizarro Atahualpa gefangen?', '1532', ['1521', '1519', '1542']],
              ['Mit wie vielen Männern nahm Pizarro Atahualpa gefangen?', '168', ['1680', '16', '16.800']],
              ['Wo nahm Pizarro Atahualpa gefangen?', 'In Cajamarca', ['In Cusco', 'In Lima', 'In Quito']],
              ['Welches Lösegeld bot Atahualpa?', 'Einen Raum mit Gold und zweimal mit Silber zu füllen', ['Sein Reich', 'Seine Tochter', 'Tausend Lamas']],
              ['Was geschah mit Atahualpa 1533?', 'Er wurde hingerichtet', ['Er wurde freigelassen', 'Er wurde Christ und König', 'Er floh']],
              ['Welche Vizekönigreiche schufen die Spanier?', 'Neuspanien und Peru', ['Kanada und Florida', 'Brasilien und Chile', 'Kuba und Jamaika']],
              ['Was mussten Ureinwohner im Encomienda-System?', 'Für spanische Herren arbeiten', ['Steuern an Inka zahlen', 'Nach Spanien ziehen', 'Kriegsdienst in Europa leisten']],
              ['Was erreichte Las Casas 1542?', 'Die „Neuen Gesetze“ zum Schutz der Indigenen', ['Die Abschaffung der Inquisition', 'Die Unabhängigkeit Mexikos', 'Die Rückkehr nach Spanien']],
              ['Wer wurde nach Amerika verschleppt, um Indigene zu ersetzen?', 'Afrikaner als Sklaven', ['Spanische Bauern', 'Chinesen', 'Iren']],
              ['Wann fand die erste Weltumsegelung statt?', '1519–1522', ['1492–1494', '1532–1535', '1588–1590']],
            ],
            schwer: [
              ['In welchem heutigen Land liegt Potosí?', 'Bolivien', ['Peru', 'Mexiko', 'Chile']],
              ['Wie nannte man Potosí?', '„Silberberg“', ['„Goldstadt“', '„El Dorado“', '„Stadt der Könige“']],
              ['Wohin segelte die Silberflotte?', 'Nach Sevilla', ['Nach Lissabon', 'Nach Madrid', 'Nach London']],
              ['Was wurde Sevilla dadurch?', 'Die reichste Stadt Spaniens', ['Hauptstadt', 'Ein Dorf', 'Portugiesisch']],
              ['Welche Vorteile hatten die Spanier militärisch?', 'Pferde, Stahl- und Feuerwaffen', ['Panzer und Flugzeuge', 'Mehr Soldaten', 'Keine']],
              ['Wann starb Moctezuma?', '1520', ['1519', '1521', '1532']],
              ['Welchem Orden gehörte Las Casas an?', 'Den Dominikanern', ['Den Jesuiten', 'Den Franziskanern', 'Den Benediktinern']],
              ['Welche Waren außer Kartoffeln kamen aus Amerika?', 'Tomaten, Mais, Kakao und Tabak', ['Reis und Zucker', 'Tee und Seide', 'Kaffee und Pfeffer']],
              ['Hat Magellan die Weltumsegelung beendet?', 'Nein, er starb unterwegs', ['Ja, er kam nach Sevilla zurück', 'Er segelte nie', 'Ja, als König']],
              ['Was war das Ziel der „Neuen Gesetze“?', 'Den Schutz der Indigenen', ['Mehr Silber', 'Die Vertreibung der Juden', 'Die Gründung neuer Städte']],
              ['Was entstand auf Tenochtitlans Ruinen?', 'Mexiko-Stadt', ['Lima', 'Cusco', 'Panama']],
              ['Wofür war Malinche wichtig?', 'Als Übersetzerin für Cortés', ['Als Aztekenkönigin', 'Als Inka-Prinzessin', 'Als spanische Königin']],
              ['Wer war Atahualpa?', 'Inka-Herrscher', ['Aztekenkönig', 'Mayapriester', 'Spanischer Hauptmann']],
              ['Wer wollte mit „Neuen Gesetzen“ Grausamkeiten stoppen?', 'Las Casas', ['Pizarro', 'Cortés', 'Kolumbus']],
              ['Welches Vizekönigreich umfasste Mexiko?', 'Neuspanien', ['Peru', 'Neugranada', 'Río de la Plata']],
              ['Was bedeutete Tordesillas für Portugal?', 'Den Osten der Linie, später Brasilien', ['Ganz Amerika', 'Nichts', 'Die Philippinen']],
              ['Wie lange dauerte die Belagerung Tenochtitlans?', 'Monatelang', ['Einen Tag', 'Zehn Jahre', 'Eine Woche']],
              ['Was war Encomienda?', 'Ein Zwangsarbeitssystem für Ureinwohner', ['Ein Schiffstyp', 'Eine Kirche', 'Ein Handelsvertrag']],
              ['In welchem Jahr wurde Tordesillas geschlossen?', '1494', ['1492', '1506', '1519']],
              ['Woher kam Silber neben Potosí?', 'Aus Mexiko', ['Aus Kuba', 'Aus Spanien', 'Aus Florida']],
            ],
          },
        },
        {
          id: 'karl-philipp',
          title: 'Karl V. und Philipp II.',
          date: '1516–1598',
          text: [
            'Karl, Enkel der Katholischen Könige und Kaiser Maximilians, erbte 1516 als Karl I. Spanien mit seinen Kolonien und Neapel, dazu von seinem Vater die Niederlande und Burgund. 1519 wurde er als Karl V. zum Kaiser des Heiligen Römischen Reiches gewählt. Er herrschte über ein Reich, „in dem die Sonne nie untergeht“. Sein Wahlspruch „Plus ultra“ (Noch weiter) steht bis heute im spanischen Wappen.',
            'Anfangs sprach Karl kaum Spanisch und brachte flämische Berater mit. 1520–1521 erhoben sich die kastilischen Städte im Aufstand der „Comuneros“, der bei Villalar niedergeschlagen wurde. Karl kämpfte gegen Frankreich, die Osmanen und gegen Luthers Reformation; 1521 stand Luther vor ihm auf dem Reichstag zu Worms. Erschöpft dankte er 1556 ab und zog sich ins Kloster Yuste in der Extremadura zurück, wo er 1558 starb.',
            'Sein Sohn Philipp II. (1556–1598) erbte Spanien, die Niederlande und Italien; das Kaisertum ging an Karls Bruder Ferdinand. 1561 machte Philipp Madrid zur Hauptstadt. Bei Madrid ließ er den riesigen Klosterpalast El Escorial bauen, von wo aus er als „Papierkönig“ unzählige Akten selbst bearbeitete. Er sah sich als Verteidiger des Katholizismus.',
            '1571 siegte eine Flotte Spaniens, Venedigs und des Papstes bei Lepanto über die Osmanen; der Schriftsteller Cervantes verlor dort die Bewegung seiner linken Hand. 1580 erbte Philipp auch Portugal mit seinen Kolonien. Doch 1568 begann der Aufstand der protestantischen Niederlande, der 80 Jahre dauerte und mit ihrer Unabhängigkeit endete.',
            '1588 schickte Philipp die „Unbesiegbare Armada“ mit rund 130 Schiffen gegen das protestantische England unter Elisabeth I. Englische Schiffe, Brander (Feuerschiffe) und Stürme vernichteten sie, nur etwa die Hälfte kehrte heim. Trotz des Silbers aus Amerika war Spanien wegen der vielen Kriege mehrfach zahlungsunfähig – Philipp II. erklärte viermal den Staatsbankrott. Gegner verbreiteten die „Schwarze Legende“ vom grausamen, fanatischen Spanien.',
          ],
          quiz: {
            leicht: [
              ['Wessen Enkel war Karl V.?', 'Der Katholischen Könige', ['Napoleons', 'Philipps II.', 'Heinrichs VIII.']],
              ['Wann erbte Karl Spanien?', '1516', ['1492', '1519', '1556']],
              ['Wozu wurde Karl 1519 gewählt?', 'Zum Kaiser des Heiligen Römischen Reiches', ['Zum Papst', 'Zum König von Frankreich', 'Zum Großinquisitor']],
              ['Wie beschrieb man Karls Reich?', 'Ein Reich, in dem die Sonne nie untergeht', ['Ein Reich ohne Kriege', 'Das kleinste Reich Europas', 'Ein Reich aus Inseln']],
              ['Wie lautete Karls Wahlspruch?', '„Plus ultra“', ['„Tanto monta“', '„Veni, vidi, vici“', '„Dios y patria“']],
              ['Wo steht „Plus ultra“ heute?', 'Im spanischen Wappen', ['Auf dem Euro', 'Auf dem Kolosseum', 'Auf der Flagge Mexikos']],
              ['Wie hieß der Aufstand der kastilischen Städte?', 'Aufstand der Comuneros', ['Aufstand der Moriscos', 'Aufstand der Niederlande', 'Bauernkrieg']],
              ['Welcher Reformator stand 1521 vor Karl?', 'Martin Luther', ['Calvin', 'Zwingli', 'Erasmus']],
              ['Wohin zog sich Karl nach seiner Abdankung zurück?', 'Ins Kloster Yuste', ['Nach Wien', 'Nach Brüssel', 'In den Escorial']],
              ['Wer war Karls Sohn und Nachfolger in Spanien?', 'Philipp II.', ['Ferdinand', 'Karl II.', 'Philipp der Schöne']],
              ['Welche Stadt machte Philipp II. 1561 zur Hauptstadt?', 'Madrid', ['Toledo', 'Sevilla', 'Valladolid']],
              ['Welchen Klosterpalast ließ Philipp II. bauen?', 'El Escorial', ['Die Alhambra', 'Den Prado', 'Den Alcázar']],
              ['Wie nannte man Philipp II. wegen seiner Aktenarbeit?', '„Papierkönig“', ['„Sonnenkönig“', '„Eiserner König“', '„König der Meere“']],
              ['Wo siegte Spanien 1571 über die Osmanen?', 'Bei Lepanto', ['Bei Trafalgar', 'Bei Pavia', 'Bei Villalar']],
              ['Welcher Schriftsteller kämpfte bei Lepanto?', 'Cervantes', ['Lope de Vega', 'Quevedo', 'Calderón']],
              ['Welches Land erbte Philipp 1580?', 'Portugal', ['Frankreich', 'England', 'Österreich']],
              ['Welches Land erhob sich 1568 gegen Spanien?', 'Die Niederlande', ['Portugal', 'Mexiko', 'Neapel']],
              ['Gegen welches Land schickte Philipp 1588 die Armada?', 'England', ['Frankreich', 'Die Niederlande', 'Die Türkei']],
              ['Wie hieß die Flotte von 1588?', '„Unbesiegbare Armada“', ['„Goldene Flotte“', '„Heilige Liga“', '„Silberflotte“']],
              ['Wer regierte England 1588?', 'Elisabeth I.', ['Heinrich VIII.', 'Maria Stuart', 'Jakob I.']],
            ],
            mittel: [
              ['Was erbte Karl von seinem Vater?', 'Die Niederlande und Burgund', ['Kastilien', 'Portugal', 'Sizilien']],
              ['Wer war Karls Großvater väterlicherseits?', 'Kaiser Maximilian', ['Ferdinand von Aragón', 'Karl der Kühne', 'Heinrich VIII.']],
              ['Wie hieß Karl als König von Spanien?', 'Karl I.', ['Karl V.', 'Karl II.', 'Karl III.']],
              ['Was bedeutet „Plus ultra“?', 'Noch weiter', ['Nie zurück', 'Gott mit uns', 'Für immer']],
              ['Wen brachte Karl anfangs mit?', 'Flämische Berater', ['Arabische Gelehrte', 'Französische Soldaten', 'Englische Händler']],
              ['Wann erhoben sich die Comuneros?', '1520–1521', ['1556', '1568', '1492']],
              ['Wo wurden die Comuneros besiegt?', 'Bei Villalar', ['Bei Lepanto', 'Bei Pavia', 'Bei Toledo']],
              ['Gegen wen kämpfte Karl V.?', 'Frankreich, Osmanen und die Reformation', ['England und Portugal', 'Russland', 'Die Azteken in Europa']],
              ['Wo stand Luther vor Karl?', 'Auf dem Reichstag zu Worms', ['In Rom', 'In Madrid', 'In Augsburg 1555']],
              ['Wann dankte Karl ab?', '1556', ['1519', '1558', '1598']],
              ['Wann starb Karl V.?', '1558', ['1556', '1598', '1519']],
              ['In welcher Region liegt Yuste?', 'In der Extremadura', ['In Andalusien', 'In Katalonien', 'In Galicien']],
              ['Wer erhielt nach Karl das Kaisertum?', 'Sein Bruder Ferdinand', ['Philipp II.', 'Maximilian', 'Rudolf']],
              ['Wann regierte Philipp II.?', '1556–1598', ['1516–1556', '1598–1621', '1665–1700']],
              ['Als was sah sich Philipp II.?', 'Als Verteidiger des Katholizismus', ['Als Reformator', 'Als Freund der Osmanen', 'Als Kaiser']],
              ['Was verlor Cervantes bei Lepanto?', 'Die Bewegung seiner linken Hand', ['Ein Auge', 'Ein Bein', 'Sein Schiff']],
              ['Wie lange dauerte der niederländische Aufstand?', '80 Jahre', ['8 Jahre', '30 Jahre', '100 Jahre']],
              ['Wie viele Schiffe hatte die Armada etwa?', 'Rund 130', ['Rund 13', 'Rund 1300', 'Rund 30']],
              ['Was vernichtete die Armada?', 'Englische Schiffe, Brander und Stürme', ['Ein Vulkan', 'Die Osmanen', 'Holländische U-Boote']],
              ['Wie oft erklärte Philipp II. den Staatsbankrott?', 'Viermal', ['Nie', 'Einmal', 'Zwanzigmal']],
            ],
            schwer: [
              ['Was ist die „Schwarze Legende“?', 'Das Bild vom grausamen, fanatischen Spanien', ['Eine Sage über Piraten', 'Ein Roman von Cervantes', 'Eine Pestgeschichte']],
              ['Warum war Spanien trotz Silber zahlungsunfähig?', 'Wegen der vielen Kriege', ['Weil das Silber unecht war', 'Weil es keine Steuern gab', 'Wegen der Pest']],
              ['Wie viele Schiffe der Armada kehrten etwa heim?', 'Etwa die Hälfte', ['Alle', 'Keines', 'Fast alle']],
              ['Was sind Brander?', 'Feuerschiffe', ['Kanonen', 'Soldaten', 'Briefe']],
              ['Wie endete der niederländische Aufstand?', 'Mit der Unabhängigkeit der Niederlande', ['Mit einem spanischen Sieg', 'Mit der Teilung Spaniens', 'Mit einem Bündnis gegen England']],
              ['Woher kam Karls Problem anfangs in Kastilien?', 'Er sprach kaum Spanisch und brachte fremde Berater', ['Er war Muslim', 'Er war zu alt', 'Er wohnte in Amerika']],
              ['Was tat Philipp II. im Escorial?', 'Er bearbeitete selbst unzählige Akten', ['Er malte', 'Er komponierte', 'Er schrieb Romane']],
              ['Welches Erbe teilte Karl auf?', 'Spanien an Philipp, Kaisertum an Ferdinand', ['Alles an Philipp', 'Alles an Ferdinand', 'Spanien an Frankreich']],
              ['Wer kämpfte bei Lepanto neben Spanien?', 'Venedig und der Papst', ['England und Frankreich', 'Portugal', 'Die Osmanen']],
              ['Welche Religion hatte England 1588?', 'Protestantisch', ['Katholisch', 'Orthodox', 'Muslimisch']],
              ['Welche Religion hatten die aufständischen Niederlande?', 'Protestantisch', ['Katholisch', 'Muslimisch', 'Jüdisch']],
              ['Wann begann der niederländische Aufstand?', '1568', ['1556', '1588', '1648']],
              ['Was brachte das Erbe Portugals 1580?', 'Portugal mit seinen Kolonien', ['Nur Lissabon', 'Brasilien allein ohne Portugal', 'Nichts']],
              ['Wo starb Karl V.?', 'Im Kloster Yuste', ['In Madrid', 'In Brüssel', 'In Wien']],
              ['Was ist El Escorial?', 'Ein Klosterpalast bei Madrid', ['Eine Moschee in Córdoba', 'Ein Hafen', 'Ein Gefängnis in Sevilla']],
              ['Was zeigt der Aufstand der Comuneros?', 'Widerstand gegen den fremden König', ['Unterstützung für Karl', 'Einen Krieg gegen Portugal', 'Einen Bauernaufstand in Amerika']],
              ['Wie viele Reiche erbte Karl insgesamt?', 'Spanien, Kolonien, Neapel, Niederlande, Burgund und das Habsburgererbe', ['Nur Kastilien', 'Nur Aragón', 'Nur die Niederlande']],
              ['Wofür steht das Jahr 1561?', 'Madrid wird Hauptstadt', ['Armada', 'Lepanto', 'Karls Tod']],
              ['Wann war die Armada?', '1588', ['1571', '1580', '1598']],
              ['Gegen wen kämpfte Spanien bei Lepanto?', 'Gegen die Osmanen', ['Gegen England', 'Gegen Frankreich', 'Gegen Venedig']],
            ],
          },
        },
      ],
    },
    {
      id: 'niedergang',
      title: 'Goldenes Zeitalter und Niedergang',
      date: '1550–1700',
      text: [
        'Während Spaniens Macht schwand, blühten Literatur und Kunst im „Siglo de Oro“: Cervantes schrieb den Don Quijote, Velázquez malte „Las Meninas“. Unter den späten Habsburgern verlor Spanien Portugal und die Niederlande, bis 1700 die Dynastie ausstarb.',
      ],
      subtopics: [
        {
          id: 'siglo-de-oro',
          title: 'Das Goldene Zeitalter',
          date: '1550–1680',
          text: [
            'Miguel de Cervantes (1547–1616) hatte ein abenteuerliches Leben: Er kämpfte bei Lepanto, war fünf Jahre Gefangener in Algier und saß als Steuereintreiber im Gefängnis. 1605 erschien der erste Teil von „Don Quijote“: Ein verarmter Edelmann aus der Mancha liest so viele Ritterromane, dass er selbst als Ritter auszieht, begleitet vom Bauern Sancho Panza. Er kämpft gegen Windmühlen, die er für Riesen hält. Der Roman gilt als erster moderner Roman der Weltliteratur.',
            'Cervantes starb 1616, im selben Jahr wie Shakespeare. Der Dramatiker Lope de Vega schrieb angeblich über 1500 Theaterstücke und wurde „Wunder der Natur“ genannt. Pedro Calderón de la Barca schrieb „Das Leben ist ein Traum“. Die Mystikerin Teresa von Ávila reformierte den Karmeliterorden. Die Universität Salamanca war eine der berühmtesten Europas.',
            'Der auf Kreta geborene Maler Domenikos Theotokopoulos, genannt „El Greco“ (der Grieche), lebte in Toledo und malte langgezogene, flackernde Gestalten wie im „Begräbnis des Grafen Orgaz“. Diego Velázquez (1599–1660), Hofmaler Philipps IV., malte 1656 „Las Meninas“ (Die Hoffräulein): die kleine Infantin Margarita mit ihren Hofdamen, im Hintergrund das Königspaar in einem Spiegel – und Velázquez selbst an der Staffelei.',
            'Weitere große Maler waren Bartolomé Esteban Murillo aus Sevilla, bekannt für Madonnen und Straßenkinder, und Francisco de Zurbarán mit Bildern von Mönchen. Viele dieser Werke hängen heute im Prado-Museum in Madrid.',
            'Doch der Reichtum aus Amerika kam kaum der Wirtschaft zugute. Er floss in Kriege und Luxus, Preise stiegen stark („Preisrevolution“), und Adlige hielten Arbeit für unehrenhaft. Der Schelmenroman „Lazarillo de Tormes“ (1554) zeigt das andere Spanien: Ein armer Junge kämpft sich mit Tricks durchs Leben und dient einem verarmten Edelmann, der lieber hungert, als zu arbeiten.',
          ],
          quiz: {
            leicht: [
              ['Wer schrieb „Don Quijote“?', 'Miguel de Cervantes', ['Lope de Vega', 'Calderón', 'Velázquez']],
              ['Wann erschien der erste Teil von „Don Quijote“?', '1605', ['1492', '1588', '1700']],
              ['Wer ist Don Quijotes Begleiter?', 'Sancho Panza', ['Lazarillo', 'Rocinante', 'Dulcinea']],
              ['Woher stammt Don Quijote?', 'Aus der Mancha', ['Aus Andalusien', 'Aus Galicien', 'Aus Amerika']],
              ['Wogegen kämpft Don Quijote?', 'Gegen Windmühlen', ['Gegen Drachen', 'Gegen Piraten', 'Gegen Engländer']],
              ['Wofür hält Don Quijote die Windmühlen?', 'Für Riesen', ['Für Burgen', 'Für Schiffe', 'Für Kirchen']],
              ['Als was gilt „Don Quijote“?', 'Erster moderner Roman der Weltliteratur', ['Erstes Theaterstück', 'Erstes Gedicht', 'Erste Zeitung']],
              ['Wer starb im selben Jahr wie Cervantes?', 'Shakespeare', ['Goethe', 'Dante', 'Molière']],
              ['Welcher Dramatiker wurde „Wunder der Natur“ genannt?', 'Lope de Vega', ['Calderón', 'Cervantes', 'Quevedo']],
              ['Wer schrieb „Das Leben ist ein Traum“?', 'Calderón de la Barca', ['Lope de Vega', 'Cervantes', 'Teresa von Ávila']],
              ['Welche Mystikerin reformierte den Karmeliterorden?', 'Teresa von Ávila', ['Isabella', 'Johanna', 'Hildegard von Bingen']],
              ['Welche Universität war eine der berühmtesten Europas?', 'Salamanca', ['Madrid', 'Barcelona', 'Sevilla']],
              ['Wie nannte man den Maler aus Kreta?', 'El Greco', ['El Cid', 'El Sabio', 'El Moro']],
              ['In welcher Stadt lebte El Greco?', 'Toledo', ['Madrid', 'Sevilla', 'Barcelona']],
              ['Wer malte „Las Meninas“?', 'Diego Velázquez', ['El Greco', 'Goya', 'Murillo']],
              ['Wer steht im Mittelpunkt von „Las Meninas“?', 'Die kleine Infantin Margarita', ['Der König', 'Velázquez', 'Ein Papst']],
              ['Wo malt sich Velázquez in „Las Meninas“?', 'An der Staffelei', ['Gar nicht', 'Im Spiegel', 'Auf einem Pferd']],
              ['Wo hängen viele Werke des Siglo de Oro heute?', 'Im Prado in Madrid', ['Im Louvre', 'In der Alhambra', 'Im Vatikan']],
              ['Wie heißt das „Goldene Zeitalter“ auf Spanisch?', 'Siglo de Oro', ['Edad Media', 'Reconquista', 'Ilustración']],
              ['Wie heißt der berühmte Schelmenroman von 1554?', '„Lazarillo de Tormes“', ['„Don Quijote“', '„La Celestina“', '„El Buscón“']],
            ],
            mittel: [
              ['Wann lebte Cervantes?', '1547–1616', ['1599–1660', '1492–1550', '1616–1681']],
              ['Wo war Cervantes fünf Jahre gefangen?', 'In Algier', ['In London', 'In Istanbul', 'In Rom']],
              ['Als was saß Cervantes im Gefängnis?', 'Als Steuereintreiber', ['Als Pirat', 'Als Priester', 'Als Spion']],
              ['Was liest Don Quijote zu viel?', 'Ritterromane', ['Die Bibel', 'Zeitungen', 'Liebesgedichte']],
              ['Was ist Sancho Panza von Beruf?', 'Bauer', ['Ritter', 'Priester', 'König']],
              ['Wie viele Stücke soll Lope de Vega geschrieben haben?', 'Über 1500', ['Rund 15', 'Rund 150', 'Über 15.000']],
              ['Wie hieß El Greco eigentlich?', 'Domenikos Theotokopoulos', ['Diego Velázquez', 'Francisco de Zurbarán', 'Bartolomé Murillo']],
              ['Was bedeutet „El Greco“?', 'Der Grieche', ['Der Große', 'Der Graue', 'Der Gerechte']],
              ['Welches berühmte Bild malte El Greco?', '„Das Begräbnis des Grafen Orgaz“', ['„Las Meninas“', '„Guernica“', '„Die Übergabe von Breda“']],
              ['Wie malte El Greco seine Gestalten?', 'Langgezogen und flackernd', ['Rund und fröhlich', 'Abstrakt in Würfeln', 'Als Fotografie']],
              ['Wann lebte Velázquez?', '1599–1660', ['1547–1616', '1746–1828', '1881–1973']],
              ['Wessen Hofmaler war Velázquez?', 'Philipps IV.', ['Philipps II.', 'Karls V.', 'Karls III.']],
              ['Wann malte Velázquez „Las Meninas“?', '1656', ['1605', '1700', '1588']],
              ['Was bedeutet „Las Meninas“?', 'Die Hoffräulein', ['Die Mädchen vom Lande', 'Die Königinnen', 'Die Malerinnen']],
              ['Wo erscheint das Königspaar in „Las Meninas“?', 'In einem Spiegel', ['Im Vordergrund', 'Gar nicht', 'Auf einem Thron']],
              ['Woher stammte Murillo?', 'Aus Sevilla', ['Aus Toledo', 'Aus Madrid', 'Aus Kreta']],
              ['Was malte Murillo?', 'Madonnen und Straßenkinder', ['Schlachten', 'Landschaften', 'Seeschlachten']],
              ['Was malte Zurbarán vor allem?', 'Mönche', ['Könige', 'Pferde', 'Schiffe']],
              ['Wie heißt der starke Preisanstieg durch das Silber?', 'Preisrevolution', ['Silberkrise', 'Inflation von Toledo', 'Goldrausch']],
              ['Was hielten Adlige für unehrenhaft?', 'Arbeit', ['Krieg', 'Religion', 'Kunst']],
            ],
            schwer: [
              ['Wem dient Lazarillo unter anderem?', 'Einem verarmten Edelmann', ['Dem König', 'Einem Piraten', 'Cervantes']],
              ['Was zeigt der „Lazarillo“?', 'Das arme, andere Spanien', ['Das Leben am Hof', 'Die Eroberung Amerikas', 'Die Reconquista']],
              ['Was tat der verarmte Edelmann im Lazarillo?', 'Er hungerte lieber, als zu arbeiten', ['Er arbeitete hart', 'Er wurde reich', 'Er ging nach Amerika']],
              ['Wohin floss der Reichtum aus Amerika?', 'In Kriege und Luxus', ['In Fabriken', 'In Schulen', 'In die Landwirtschaft']],
              ['Welches Leben führte Cervantes?', 'Ein abenteuerliches', ['Ein ruhiges am Hof', 'Ein Leben als Mönch', 'Ein Leben in Amerika']],
              ['Was ist Teresa von Ávila?', 'Mystikerin und Ordensreformerin', ['Königin', 'Malerin', 'Dichterin am Hof']],
              ['Wo wurde El Greco geboren?', 'Auf Kreta', ['In Toledo', 'In Athen', 'In Venedig']],
              ['Was zeigt der Spiegel in „Las Meninas“?', 'Das Königspaar', ['Velázquez', 'Die Infantin', 'Einen Hund']],
              ['Welches Werk ist von Calderón?', '„Das Leben ist ein Traum“', ['„Don Quijote“', '„Lazarillo“', '„Fuenteovejuna“']],
              ['Warum gilt „Don Quijote“ als modern?', 'Erster moderner Roman der Weltliteratur', ['Er war kurz', 'Er war ein Gedicht', 'Er spielte in der Zukunft']],
              ['Was verbindet Cervantes und Lepanto?', 'Er kämpfte dort', ['Er schrieb dort', 'Er wurde dort geboren', 'Er starb dort']],
              ['Welche Rolle spielte die Universität Salamanca?', 'Eine der berühmtesten Europas', ['Eine Kaserne', 'Ein Kloster', 'Ein Hafen']],
              ['Warum war das Siglo de Oro paradox?', 'Kultur blühte, während die Macht schwand', ['Kultur und Macht blühten', 'Nichts blühte', 'Es gab keine Kunst']],
              ['Welcher Maler war Hofmaler und malte sich selbst ins Bild?', 'Velázquez', ['El Greco', 'Murillo', 'Zurbarán']],
              ['Welches Museum besitzt viele dieser Werke?', 'Der Prado', ['Der Louvre', 'Die Uffizien', 'Die Tate']],
              ['In welchem Jahr starben Cervantes und Shakespeare?', '1616', ['1605', '1588', '1660']],
              ['Was folgte aus der Haltung der Adligen zur Arbeit?', 'Die Wirtschaft profitierte kaum', ['Ein Wirtschaftsboom', 'Die Industrialisierung', 'Eine Agrarrevolution']],
              ['Welches Genre ist „Lazarillo de Tormes“?', 'Schelmenroman', ['Ritterroman', 'Liebesroman', 'Kriminalroman']],
              ['Welche Infantin zeigt „Las Meninas“?', 'Margarita', ['Isabella', 'Johanna', 'Maria Theresia']],
              ['Wofür steht Lope de Vega?', 'Für ungeheure Produktivität als Dramatiker', ['Für Malerei', 'Für Seefahrt', 'Für die Inquisition']],
            ],
          },
        },
        {
          id: 'spaete-habsburger',
          title: 'Die späten Habsburger',
          date: '1598–1700',
          text: [
            'Unter Philipp III. (1598–1621) regierten Günstlinge wie der Herzog von Lerma. 1609 wurden rund 300.000 Moriscos vertrieben – ein schwerer Verlust für Landwirtschaft und Handwerk, besonders in Valencia und Aragón. Pest und Hungersnöte ließen die Bevölkerung schrumpfen.',
            'Philipp IV. (1621–1665) überließ die Politik dem Grafen-Herzog von Olivares, der Spaniens Vorherrschaft mit aller Kraft verteidigen wollte. Spanien kämpfte im Dreißigjährigen Krieg an der Seite der österreichischen Habsburger. Um die Lasten gleichmäßiger zu verteilen, wollte Olivares die anderen Reiche stärker an Kosten und Soldaten beteiligen.',
            '1640 erhoben sich gleichzeitig Katalonien im „Aufstand der Schnitter“ (Els Segadors, heute Hymne Kataloniens) und Portugal. Portugal wurde unter dem Haus Braganza wieder unabhängig, was Spanien 1668 anerkennen musste. Katalonien kehrte 1652 zurück. 1643 besiegte Frankreich die gefürchtete spanische Infanterie, die „Tercios“, bei Rocroi.',
            'Im Westfälischen Frieden 1648 erkannte Spanien die Unabhängigkeit der Niederlande an. Im Pyrenäenfrieden 1659 verlor es das Roussillon an Frankreich, wo die Grenze seitdem auf dem Kamm der Pyrenäen verläuft. Der Friede wurde mit der Heirat der Infantin Maria Theresia mit König Ludwig XIV. von Frankreich besiegelt – was später den Bourbonen den Weg nach Spanien öffnete.',
            'Der letzte spanische Habsburger, Karl II. (1665–1700), war durch Verwandtenehen seiner Familie schwer krank und konnte kaum sprechen und essen; man nannte ihn „den Verhexten“ (el Hechizado). Er blieb kinderlos. Als er 1700 starb, setzte er Philipp von Anjou, einen Enkel Ludwigs XIV., als Erben ein – das löste den Spanischen Erbfolgekrieg aus.',
          ],
          quiz: {
            leicht: [
              ['Wann wurden die Moriscos vertrieben?', '1609', ['1492', '1502', '1700']],
              ['Wie viele Moriscos wurden vertrieben etwa?', 'Rund 300.000', ['Rund 3000', 'Rund 3 Millionen', 'Rund 30']],
              ['Wer regierte für Philipp III.?', 'Günstlinge wie der Herzog von Lerma', ['Seine Mutter', 'Der Papst', 'Ein Parlament']],
              ['Wer regierte für Philipp IV.?', 'Der Graf-Herzog von Olivares', ['Der Herzog von Lerma', 'Torquemada', 'Velázquez']],
              ['In welchem großen Krieg kämpfte Spanien ab 1618?', 'Im Dreißigjährigen Krieg', ['Im Hundertjährigen Krieg', 'Im Siebenjährigen Krieg', 'Im Ersten Weltkrieg']],
              ['Welche Region erhob sich 1640 mit dem „Aufstand der Schnitter“?', 'Katalonien', ['Andalusien', 'Galicien', 'Kastilien']],
              ['Was ist „Els Segadors“ heute?', 'Die Hymne Kataloniens', ['Ein Fußballclub', 'Ein Gericht', 'Ein Fest']],
              ['Welches Land wurde 1640 wieder unabhängig?', 'Portugal', ['Katalonien', 'Die Niederlande', 'Neapel']],
              ['Unter welchem Haus wurde Portugal unabhängig?', 'Braganza', ['Habsburg', 'Bourbon', 'Tudor']],
              ['Wo verlor die spanische Infanterie 1643?', 'Bei Rocroi', ['Bei Lepanto', 'Bei Pavia', 'Bei Trafalgar']],
              ['Wie hieß die spanische Infanterie?', 'Tercios', ['Legionen', 'Janitscharen', 'Musketiere']],
              ['Welche Unabhängigkeit erkannte Spanien 1648 an?', 'Die der Niederlande', ['Die Portugals', 'Die Kataloniens', 'Die Mexikos']],
              ['Welcher Frieden wurde 1648 geschlossen?', 'Der Westfälische Frieden', ['Der Pyrenäenfrieden', 'Der Frieden von Utrecht', 'Der Frieden von Tordesillas']],
              ['Welches Gebiet verlor Spanien 1659 an Frankreich?', 'Das Roussillon', ['Katalonien', 'Navarra', 'Elsass']],
              ['Wo verläuft seitdem die Grenze zu Frankreich?', 'Auf dem Kamm der Pyrenäen', ['Am Ebro', 'An der Loire', 'Am Rhein']],
              ['Wen heiratete Maria Theresia von Spanien?', 'Ludwig XIV.', ['Ludwig XVI.', 'Karl II.', 'Philipp IV.']],
              ['Wer war der letzte spanische Habsburger?', 'Karl II.', ['Philipp IV.', 'Philipp V.', 'Karl V.']],
              ['Wie nannte man Karl II.?', '„Den Verhexten“', ['„Den Großen“', '„Den Weisen“', '„Den Kühnen“']],
              ['Hatte Karl II. Kinder?', 'Nein', ['Ja, viele', 'Einen Sohn', 'Eine Tochter']],
              ['Wann starb Karl II.?', '1700', ['1665', '1714', '1648']],
            ],
            mittel: [
              ['Wann regierte Philipp III.?', '1598–1621', ['1621–1665', '1665–1700', '1556–1598']],
              ['Wann regierte Philipp IV.?', '1621–1665', ['1598–1621', '1665–1700', '1700–1746']],
              ['Wo traf die Vertreibung der Moriscos besonders?', 'In Valencia und Aragón', ['In Kastilien und León', 'In Galicien', 'In Amerika']],
              ['Was war die Folge der Morisco-Vertreibung?', 'Ein schwerer Verlust für Landwirtschaft und Handwerk', ['Ein Wirtschaftsboom', 'Mehr Steuern', 'Keine Folgen']],
              ['Was ließ die Bevölkerung schrumpfen?', 'Pest und Hungersnöte', ['Auswanderung nach Asien', 'Ein Erdbeben', 'Ein Vulkanausbruch']],
              ['Was wollte Olivares verteidigen?', 'Spaniens Vorherrschaft', ['Den Frieden um jeden Preis', 'Die Republik', 'Den Protestantismus']],
              ['An wessen Seite kämpfte Spanien im Dreißigjährigen Krieg?', 'An der der österreichischen Habsburger', ['An der Frankreichs', 'An der Schwedens', 'An der Englands']],
              ['Was wollte Olivares bei den anderen Reichen?', 'Sie stärker an Kosten und Soldaten beteiligen', ['Sie unabhängig machen', 'Sie an Frankreich verkaufen', 'Ihnen Steuern erlassen']],
              ['Wann erkannte Spanien Portugals Unabhängigkeit an?', '1668', ['1640', '1659', '1700']],
              ['Wann kehrte Katalonien zurück?', '1652', ['1640', '1714', '1668']],
              ['Wer besiegte die Tercios bei Rocroi?', 'Frankreich', ['England', 'Die Niederlande', 'Schweden']],
              ['Wann war die Schlacht bei Rocroi?', '1643', ['1640', '1648', '1588']],
              ['Wann war der Pyrenäenfrieden?', '1659', ['1648', '1668', '1700']],
              ['Womit wurde der Pyrenäenfrieden besiegelt?', 'Mit einer Heirat', ['Mit Gold', 'Mit einem Krieg', 'Mit einer Krönung']],
              ['Woran litt Karl II.?', 'An Folgen der Verwandtenehen seiner Familie', ['An der Pest', 'An einer Kriegsverletzung', 'An Altersschwäche']],
              ['Was konnte Karl II. kaum?', 'Sprechen und essen', ['Reiten', 'Lesen', 'Malen']],
              ['Wann regierte Karl II.?', '1665–1700', ['1621–1665', '1700–1746', '1598–1621']],
              ['Wen setzte Karl II. als Erben ein?', 'Philipp von Anjou', ['Karl von Österreich', 'Ludwig XIV.', 'Wilhelm von Oranien']],
              ['Wessen Enkel war Philipp von Anjou?', 'Ludwigs XIV.', ['Karls II.', 'Philipps IV.', 'Leopolds I.']],
              ['Welchen Krieg löste Karls Testament aus?', 'Den Spanischen Erbfolgekrieg', ['Den Dreißigjährigen Krieg', 'Den Siebenjährigen Krieg', 'Den Erbfolgekrieg um Österreich']],
            ],
            schwer: [
              ['Was öffnete den Bourbonen den Weg nach Spanien?', 'Die Heirat Maria Theresias mit Ludwig XIV.', ['Die Armada', 'Lepanto', 'Rocroi']],
              ['Was bedeutet „el Hechizado“?', 'Der Verhexte', ['Der Heilige', 'Der Kranke', 'Der Letzte']],
              ['Wie gelang Portugal die Unabhängigkeit?', 'Durch einen Aufstand 1640', ['Durch Kauf', 'Durch Heirat', 'Durch Papstbeschluss']],
              ['Welche Bedeutung hat Rocroi?', 'Niederlage der gefürchteten Tercios', ['Großer spanischer Sieg', 'Friedensvertrag', 'Seeschlacht']],
              ['Warum regierten unter den späten Habsburgern Günstlinge?', 'Die Könige überließen ihnen die Politik', ['Die Könige waren im Ausland', 'Es gab keine Könige', 'Der Papst befahl es']],
              ['Welche beiden Aufstände geschahen 1640 gleichzeitig?', 'Katalonien und Portugal', ['Niederlande und Neapel', 'Mexiko und Peru', 'Andalusien und Galicien']],
              ['Was symbolisiert „Els Segadors“?', 'Den katalanischen Aufstand von 1640', ['Die Reconquista', 'Den Bürgerkrieg', 'Die Unabhängigkeit Portugals']],
              ['Welche Folge hatte der Westfälische Frieden für Spanien?', 'Es verlor die Niederlande', ['Es gewann Frankreich', 'Es verlor Portugal', 'Es gewann Schweden']],
              ['Welche Gebiete waren nach 1648 und 1668 verloren?', 'Die Niederlande und Portugal', ['Katalonien und Valencia', 'Mexiko und Peru', 'Neapel und Sizilien']],
              ['Welcher König war Velázquez’ Dienstherr und Olivares’ König?', 'Philipp IV.', ['Philipp III.', 'Karl II.', 'Philipp II.']],
              ['Warum war Karl II. kinderlos ein Problem?', 'Die Erbfolge war offen', ['Er wollte abdanken', 'Er war zu jung', 'Es gab kein Problem']],
              ['Wer war der Herzog von Lerma?', 'Günstling Philipps III.', ['Feldherr bei Rocroi', 'Maler', 'Erzbischof']],
              ['Welche Bevölkerungsgruppe verlor Spanien 1609?', 'Die Moriscos', ['Die Juden', 'Die Basken', 'Die Katalanen']],
              ['Wie entwickelte sich die Bevölkerung im 17. Jh.?', 'Sie schrumpfte', ['Sie wuchs stark', 'Sie blieb gleich', 'Sie verdoppelte sich']],
              ['Warum erhoben sich Katalanen und Portugiesen?', 'Gegen Olivares’ Forderungen nach Geld und Soldaten', ['Für mehr Inquisition', 'Gegen Frankreich', 'Für die Moriscos']],
              ['Welche Dynastie folgte auf die Habsburger in Spanien?', 'Die Bourbonen', ['Die Tudors', 'Die Braganza', 'Die Savoyer']],
              ['Wann erkannte Spanien die Niederlande an?', '1648', ['1609', '1659', '1700']],
              ['Was trennt seit 1659 Spanien und Frankreich?', 'Der Kamm der Pyrenäen', ['Der Ebro', 'Das Mittelmeer', 'Die Rhône']],
              ['Wie viele Habsburger regierten Spanien nach Philipp II.?', 'Drei', ['Einer', 'Zehn', 'Keiner']],
              ['Wer war Maria Theresia von Spanien?', 'Infantin, Frau Ludwigs XIV.', ['Kaiserin von Österreich', 'Königin von Portugal', 'Mutter Karls V.']],
            ],
          },
        },
      ],
    },
  ],
};
