import type { Epoch } from '../types';

export const E6: Epoch = {
  id: 'demokratie',
  name: 'Demokratie',
  period: 'seit 1975',
  events: [
    {
      id: 'transicion',
      title: 'Die Rückkehr zur Demokratie',
      date: '1975–2025',
      text: [
        'Nach Francos Tod gelang Spanien ohne Bürgerkrieg der Übergang zur Demokratie – die „Transición“ gilt weltweit als Vorbild. Spanien trat der EG bei, wurde modern und weltoffen, erlebte aber auch Terror, Wirtschaftskrisen und den Streit um Katalonien.',
      ],
      subtopics: [
        {
          id: 'transicion-1978',
          title: 'Transición, Verfassung und Putschversuch',
          date: '1975–1982',
          text: [
            'Am 22. November 1975 wurde Juan Carlos I. zum König ausgerufen. Viele erwarteten, er werde Francos System fortsetzen, doch er wollte eine Demokratie. 1976 ernannte er den jungen Adolfo Suárez zum Regierungschef. Suárez brachte das Franco-Parlament dazu, sich mit dem „Gesetz für die politische Reform“ selbst abzuschaffen („Harakiri der Cortes“) – ein Volksentscheid bestätigte das mit großer Mehrheit.',
            'Parteien und Gewerkschaften wurden erlaubt, im April 1977 überraschend sogar die Kommunistische Partei. Am 15. Juni 1977 fanden die ersten freien Wahlen seit 1936 statt; Suárez’ Partei UCD gewann. Im „Pakt von Moncloa“ einigten sich die Parteien auf Wirtschaftsreformen. Ein Amnestiegesetz 1977 ließ politische Gefangene frei, verhinderte aber auch die Verfolgung von Verbrechen der Diktatur – der „Pakt des Schweigens“.',
            'Am 6. Dezember 1978 nahmen die Spanier in einem Referendum die neue Verfassung an; der 6. Dezember ist heute Verfassungstag. Sie macht Spanien zu einer parlamentarischen Monarchie und erkennt das Recht der „Nationalitäten und Regionen“ auf Autonomie an. Es entstanden 17 Autonome Gemeinschaften mit eigenen Parlamenten; Katalanisch, Baskisch und Galicisch wurden dort Amtssprachen neben Kastilisch.',
            'Am 23. Februar 1981 („23-F“) stürmte Oberstleutnant Antonio Tejero mit Guardia-Civil-Beamten das Parlament während der Wahl eines neuen Regierungschefs und rief „¡Quieto todo el mundo!“ (Alle stillhalten!). Panzer rollten in Valencia durch die Straßen. In der Nacht stellte sich König Juan Carlos in Uniform im Fernsehen hinter die Verfassung, und der Putsch brach zusammen. Das sicherte ihm großes Ansehen.',
            'Parallel blühte die Kultur auf: In Madrid entstand die „Movida“, eine bunte Jugend- und Kunstszene, aus der der Regisseur Pedro Almodóvar hervorging. Die Zensur war abgeschafft. Doch die ETA verübte gerade in diesen Jahren die meisten Anschläge; die Transición war keineswegs friedlich für alle. 1982 gewann die sozialistische PSOE unter Felipe González die Wahl mit absoluter Mehrheit – der friedliche Machtwechsel bewies, dass die Demokratie stabil war.',
          ],
          quiz: {
            leicht: [
              ['Wie nennt man den Übergang zur Demokratie?', 'Transición', ['Reconquista', 'Movida', 'Restauración']],
              ['Wer wurde 1975 König?', 'Juan Carlos I.', ['Felipe VI.', 'Alfons XIII.', 'Carlos IV.']],
              ['Wen ernannte Juan Carlos 1976 zum Regierungschef?', 'Adolfo Suárez', ['Felipe González', 'Carrero Blanco', 'José María Aznar']],
              ['Wann fanden die ersten freien Wahlen seit 1936 statt?', '15. Juni 1977', ['20. November 1975', '6. Dezember 1978', '23. Februar 1981']],
              ['Welche Partei gewann 1977?', 'Die UCD von Suárez', ['Die PSOE', 'Die Kommunisten', 'Die Falange']],
              ['Welche Partei wurde im April 1977 überraschend erlaubt?', 'Die Kommunistische Partei', ['Die Falange', 'Die ETA', 'Die Karlisten']],
              ['Wann wurde die Verfassung angenommen?', '6. Dezember 1978', ['15. Juni 1977', '14. April 1931', '19. März 1812']],
              ['Was ist der 6. Dezember in Spanien?', 'Verfassungstag', ['Nationalfeiertag', 'Tag der Arbeit', 'Königstag']],
              ['Welche Staatsform hat Spanien laut Verfassung?', 'Parlamentarische Monarchie', ['Republik', 'Absolute Monarchie', 'Diktatur']],
              ['Wie viele Autonome Gemeinschaften gibt es?', '17', ['5', '50', '10']],
              ['Welche Sprachen wurden regionale Amtssprachen?', 'Katalanisch, Baskisch und Galicisch', ['Englisch und Französisch', 'Latein und Arabisch', 'Portugiesisch']],
              ['Was geschah am 23. Februar 1981?', 'Ein Putschversuch im Parlament', ['Die Verfassung trat in Kraft', 'Franco starb', 'Spanien trat der EG bei']],
              ['Wer stürmte 1981 das Parlament?', 'Oberstleutnant Antonio Tejero', ['Adolfo Suárez', 'Juan Carlos', 'Felipe González']],
              ['Was rief Tejero?', '„¡Quieto todo el mundo!“', ['„¡No pasarán!“', '„¡Viva la muerte!“', '„¡Plus ultra!“']],
              ['Wer stellte sich gegen den Putsch?', 'König Juan Carlos', ['General Tejero', 'Die ETA', 'Franco']],
              ['Wie nennt man die Kulturszene in Madrid?', 'Movida', ['Transición', 'Siglo de Oro', 'Renaixença']],
              ['Welcher Regisseur ging aus der Movida hervor?', 'Pedro Almodóvar', ['Luis Buñuel', 'Carlos Saura', 'Steven Spielberg']],
              ['Welche Partei gewann 1982?', 'Die PSOE', ['Die UCD', 'Die PP', 'Podemos']],
              ['Wer führte die PSOE 1982?', 'Felipe González', ['Adolfo Suárez', 'Pedro Sánchez', 'José Luis Zapatero']],
              ['Welche Organisation verübte in der Transición viele Anschläge?', 'Die ETA', ['Die Falange', 'Die IRA', 'Die Rote Armee Fraktion']],
            ],
            mittel: [
              ['Wann wurde Juan Carlos zum König ausgerufen?', '22. November 1975', ['20. November 1975', '6. Dezember 1978', '1. Januar 1976']],
              ['Was erwarteten viele von Juan Carlos?', 'Dass er Francos System fortsetzt', ['Dass er abdankt', 'Dass er eine Republik ausruft', 'Dass er auswandert']],
              ['Wie schaffte sich das Franco-Parlament selbst ab?', 'Mit dem Gesetz für die politische Reform', ['Durch einen Putsch', 'Durch Auflösung durch die UNO', 'Durch Krieg']],
              ['Wie nannte man die Selbstabschaffung der Cortes?', '„Harakiri der Cortes“', ['„Tod des Senats“', '„Pakt des Schweigens“', '„23-F“']],
              ['Wie wurde die politische Reform bestätigt?', 'Durch einen Volksentscheid', ['Durch den Papst', 'Durch die Armee', 'Gar nicht']],
              ['Worauf einigten sich die Parteien im Pakt von Moncloa?', 'Auf Wirtschaftsreformen', ['Auf einen Krieg', 'Auf die Republik', 'Auf Francos Erbe']],
              ['Was bewirkte das Amnestiegesetz 1977?', 'Freilassung politischer Gefangener, keine Verfolgung von Diktaturverbrechen', ['Verurteilung aller Franquisten', 'Verbot der Kommunisten', 'Rückkehr der Inquisition']],
              ['Wie nennt man das Schweigen über die Diktatur?', '„Pakt des Schweigens“', ['„Pakt von Moncloa“', '„Omertà“', '„Turno pacífico“']],
              ['Was erkennt die Verfassung an?', 'Das Recht der Nationalitäten und Regionen auf Autonomie', ['Die Unabhängigkeit Kataloniens', 'Die Macht der Kirche', 'Francos Erbe']],
              ['Was haben die Autonomen Gemeinschaften?', 'Eigene Parlamente', ['Eigene Armeen', 'Eigene Währungen', 'Eigene Könige']],
              ['Mit wem stürmte Tejero das Parlament?', 'Mit Guardia-Civil-Beamten', ['Mit ETA-Kämpfern', 'Mit Studenten', 'Mit der Marine']],
              ['Was geschah im Parlament am 23-F?', 'Die Wahl eines neuen Regierungschefs', ['Die Abstimmung über die Verfassung', 'Eine Königskrönung', 'Ein Konzert']],
              ['Wo rollten Panzer durch die Straßen?', 'In Valencia', ['In Barcelona', 'In Sevilla', 'In Bilbao']],
              ['Wie trat Juan Carlos im Fernsehen auf?', 'In Uniform', ['Im Pyjama', 'Im Anzug mit Krone', 'Gar nicht']],
              ['Was gewann Juan Carlos durch sein Verhalten am 23-F?', 'Großes Ansehen', ['Die Diktatur', 'Nichts', 'Die Republik']],
              ['Was wurde in der Movida-Zeit abgeschafft?', 'Die Zensur', ['Die Monarchie', 'Die Kirche', 'Die Wahlen']],
              ['Mit welcher Mehrheit gewann die PSOE 1982?', 'Mit absoluter Mehrheit', ['Knapp', 'Gar nicht', 'Mit einer Koalition']],
              ['Was bewies der Machtwechsel 1982?', 'Dass die Demokratie stabil war', ['Dass die Monarchie endete', 'Dass Franco zurückkam', 'Nichts']],
              ['Wie wurde Suárez bei seiner Ernennung beschrieben?', 'Als junger Politiker', ['Als greiser General', 'Als Kommunist', 'Als Bischof']],
              ['Wann wurde die Kommunistische Partei erlaubt?', 'April 1977', ['Juni 1977', 'November 1975', 'Dezember 1978']],
            ],
            schwer: [
              ['Warum gilt die Transición als Vorbild?', 'Übergang zur Demokratie ohne Bürgerkrieg', ['Weil sie militärisch war', 'Weil sie schnell eine Republik brachte', 'Weil Franco sie leitete']],
              ['War die Transición für alle friedlich?', 'Nein, die ETA verübte viele Anschläge', ['Ja, völlig', 'Ja, außer in Madrid', 'Es gab gar keine Gewalt']],
              ['Was war das „Harakiri der Cortes“?', 'Die Selbstabschaffung des Franco-Parlaments', ['Ein Massaker', 'Ein Putschversuch', 'Eine Wahlfälschung']],
              ['Welche Kritik gibt es am Amnestiegesetz?', 'Verbrechen der Diktatur blieben ungesühnt', ['Es war zu streng', 'Es betraf nur Basken', 'Es gab keine Kritik']],
              ['Was bedeutete die Zulassung der Kommunisten?', 'Ein mutiger Schritt zur echten Demokratie', ['Ein Rückfall in die Diktatur', 'Ein Krieg', 'Nichts']],
              ['Wie scheiterte der Putsch vom 23-F?', 'Der König stellte sich hinter die Verfassung', ['Die Putschisten wurden erschossen', 'Die USA griffen ein', 'Er war erfolgreich']],
              ['Welche Rolle spielt der 23-F für die Monarchie?', 'Er sicherte Juan Carlos großes Ansehen', ['Er beendete die Monarchie', 'Er schwächte den König', 'Keine']],
              ['Was ist die Movida?', 'Eine bunte Jugend- und Kunstszene in Madrid', ['Eine Partei', 'Ein Putsch', 'Ein Tanz der Franco-Zeit']],
              ['Was unterscheidet Autonome Gemeinschaften von Staaten?', 'Sie gehören zu Spanien, haben aber eigene Parlamente', ['Sie sind unabhängig', 'Sie haben eigene Könige', 'Sie haben keine Rechte']],
              ['Welches Gesetz machte 1977 freie Wahlen möglich?', 'Das Gesetz für die politische Reform', ['Die Verfassung von 1812', 'Das Amnestiegesetz', 'Der Pakt von Moncloa']],
              ['Welche Parteien gewannen 1977 und 1982?', 'UCD, dann PSOE', ['PSOE, dann UCD', 'PP, dann PSOE', 'Falange, dann PCE']],
              ['Wann wurde Franco-Spanien zur parlamentarischen Monarchie?', 'Mit der Verfassung von 1978', ['Mit Francos Tod 1975', 'Mit dem 23-F', 'Mit dem EG-Beitritt']],
              ['Wann waren die ersten freien Wahlen davor gewesen?', '1936', ['1931', '1975', '1812']],
              ['Was war Tejero?', 'Oberstleutnant der Guardia Civil', ['Regierungschef', 'König', 'ETA-Chef']],
              ['Wie erkennt die Verfassung Regionen an?', 'Mit Recht auf Autonomie', ['Mit Recht auf Austritt', 'Gar nicht', 'Mit eigenen Armeen']],
              ['Wer schuf die Grundlage für Wirtschaftsreformen 1977?', 'Der Pakt von Moncloa', ['Die ETA', 'Die Movida', 'Das Opus Dei']],
              ['Was bestätigte der Volksentscheid 1976?', 'Die politische Reform', ['Francos Erbe', 'Die Republik', 'Den EG-Beitritt']],
              ['Was ist der „23-F“?', 'Der Putschversuch vom 23. Februar 1981', ['Ein Gesetz', 'Ein Fußballspiel', 'Eine Partei']],
              ['Wie lange hatte Spanien keine freien Wahlen?', 'Rund 41 Jahre', ['Rund 4 Jahre', 'Rund 100 Jahre', 'Rund 10 Jahre']],
              ['Welche Regionalsprache ist in Galicien Amtssprache?', 'Galicisch', ['Baskisch', 'Katalanisch', 'Portugiesisch']],
            ],
          },
        },
        {
          id: 'modernes-spanien',
          title: 'Europa, Krisen und das heutige Spanien',
          date: '1986–heute',
          text: [
            'Am 1. Januar 1986 trat Spanien zusammen mit Portugal der Europäischen Gemeinschaft bei, im selben Jahr bestätigte ein Referendum die NATO-Mitgliedschaft. Mit EU-Geldern entstanden Autobahnen und 1992 die erste Hochgeschwindigkeitsbahn AVE von Madrid nach Sevilla. 1992 war Spaniens großes Jahr: Olympische Spiele in Barcelona, Weltausstellung in Sevilla und Madrid Kulturhauptstadt Europas. 2002 führte Spanien den Euro ein und gab die Peseta auf.',
            'Unter dem Konservativen José María Aznar (PP, 1996–2004) wuchs die Wirtschaft stark, angetrieben von einem Bauboom. Am 11. März 2004 („11-M“) explodierten in Madrider Vorortzügen zehn Bomben islamistischer Terroristen; 193 Menschen starben – der schwerste Anschlag in Europa seit dem Zweiten Weltkrieg. Drei Tage später gewann die PSOE unter José Luis Rodríguez Zapatero die Wahl. Er zog die Truppen aus dem Irak ab und führte 2005 als eines der ersten Länder der Welt die gleichgeschlechtliche Ehe ein.',
            'Die Finanzkrise ab 2008 traf Spanien hart, als die Immobilienblase platzte: Die Arbeitslosigkeit stieg auf 26 Prozent, bei Jugendlichen auf über 50 Prozent. 2011 besetzten Tausende als „Empörte“ (Indignados, Bewegung 15-M) die Puerta del Sol in Madrid; daraus ging die Partei Podemos hervor. Im Sport erlebte Spanien dagegen eine goldene Zeit: Europameister 2008 und 2012, Weltmeister 2010 in Südafrika, dazu Tennisstar Rafael Nadal.',
            '2011 erklärte die ETA das Ende ihres bewaffneten Kampfes, 2018 löste sie sich auf; sie hatte über 800 Menschen getötet. 2014 dankte Juan Carlos nach Skandalen ab, sein Sohn wurde König Felipe VI. In Katalonien wuchs die Unabhängigkeitsbewegung: Am 1. Oktober 2017 hielt die Regionalregierung ein vom Verfassungsgericht verbotenes Referendum ab, Polizisten gingen gewaltsam gegen Wähler vor. Nach der Unabhängigkeitserklärung setzte Madrid die katalanische Autonomie vorübergehend außer Kraft, Anführer wurden verurteilt oder flohen ins Ausland wie Carles Puigdemont.',
            '2019 wurden Francos Gebeine aus dem Tal der Gefallenen umgebettet, das heute „Valle de Cuelgamuros“ heißt. Seit 2018 regiert der Sozialist Pedro Sánchez. 2020 traf die Corona-Pandemie Spanien besonders hart. Spanien hat heute rund 48 Millionen Einwohner, ist eines der meistbesuchten Länder der Welt und weltweit führend bei Organspenden und Solarenergie. Spanisch ist mit fast 500 Millionen Muttersprachlern die zweitgrößte Muttersprache der Welt.',
          ],
          quiz: {
            leicht: [
              ['Wann trat Spanien der EG bei?', '1986', ['1975', '1992', '2002']],
              ['Mit welchem Land trat Spanien der EG bei?', 'Mit Portugal', ['Mit Italien', 'Mit Griechenland', 'Mit Frankreich']],
              ['Wie heißt Spaniens Hochgeschwindigkeitszug?', 'AVE', ['TGV', 'ICE', 'Shinkansen']],
              ['Wo fanden 1992 Olympische Spiele statt?', 'In Barcelona', ['In Madrid', 'In Sevilla', 'In Valencia']],
              ['Wo war 1992 die Weltausstellung?', 'In Sevilla', ['In Barcelona', 'In Madrid', 'In Bilbao']],
              ['Wann führte Spanien den Euro ein?', '2002', ['1992', '1986', '2008']],
              ['Welche Währung gab Spanien auf?', 'Die Peseta', ['Den Peso', 'Den Franc', 'Die Lira']],
              ['Was geschah am 11. März 2004 in Madrid?', 'Islamistische Bombenanschläge auf Züge', ['Ein Putsch', 'Ein Erdbeben', 'Ein Fußballsieg']],
              ['Wie viele Menschen starben beim 11-M?', '193', ['19', '1930', '3']],
              ['Wer gewann 2004 die Wahl?', 'Zapatero (PSOE)', ['Aznar', 'Rajoy', 'Sánchez']],
              ['Was führte Spanien 2005 ein?', 'Die gleichgeschlechtliche Ehe', ['Den Euro', 'Die Monarchie', 'Die Wehrpflicht']],
              ['Auf wie viel Prozent stieg die Arbeitslosigkeit?', '26 Prozent', ['2 Prozent', '6 Prozent', '60 Prozent']],
              ['Wie nannte man die Protestbewegung 2011?', '„Empörte“ (Indignados, 15-M)', ['„Movida“', '„Comuneros“', '„Rothemden“']],
              ['Welche Partei ging aus der 15-M-Bewegung hervor?', 'Podemos', ['PP', 'Vox', 'UCD']],
              ['Wann wurde Spanien Fußballweltmeister?', '2010', ['1982', '2014', '2006']],
              ['Welcher Tennisstar wurde berühmt?', 'Rafael Nadal', ['Roger Federer', 'Novak Djokovic', 'Andre Agassi']],
              ['Wann löste sich die ETA auf?', '2018', ['1981', '2004', '1995']],
              ['Wer wurde 2014 König?', 'Felipe VI.', ['Juan Carlos II.', 'Alfons XIV.', 'Carlos V.']],
              ['Wann hielt Katalonien ein verbotenes Referendum ab?', '1. Oktober 2017', ['11. September 2014', '6. Dezember 2018', '15. Mai 2011']],
              ['Welcher katalanische Anführer floh ins Ausland?', 'Carles Puigdemont', ['Pedro Sánchez', 'Felipe González', 'Jordi Pujol']],
            ],
            mittel: [
              ['Wann trat Spanien der EG am genauen Tag bei?', '1. Januar 1986', ['1. Januar 1992', '23. Februar 1981', '1. Mai 2004']],
              ['Was bestätigte 1986 ein Referendum?', 'Die NATO-Mitgliedschaft', ['Die Monarchie', 'Den Euro', 'Die Verfassung']],
              ['Wohin fuhr der erste AVE?', 'Von Madrid nach Sevilla', ['Von Madrid nach Barcelona', 'Von Barcelona nach Paris', 'Von Bilbao nach Madrid']],
              ['Welche Stadt war 1992 Kulturhauptstadt Europas?', 'Madrid', ['Barcelona', 'Sevilla', 'Salamanca']],
              ['Wann regierte Aznar?', '1996–2004', ['1982–1996', '2004–2011', '2018–heute']],
              ['Welcher Partei gehörte Aznar an?', 'PP', ['PSOE', 'UCD', 'Podemos']],
              ['Was trieb das Wachstum unter Aznar an?', 'Ein Bauboom', ['Die Fischerei', 'Der Ölexport', 'Die Waffenindustrie']],
              ['Wie viele Bomben explodierten am 11-M?', 'Zehn', ['Eine', 'Hundert', 'Drei']],
              ['Als was gilt der 11-M?', 'Schwerster Anschlag in Europa seit dem Zweiten Weltkrieg', ['Kleiner Anschlag', 'ETA-Anschlag', 'Unfall']],
              ['Woraus zog Zapatero Truppen ab?', 'Aus dem Irak', ['Aus Afghanistan', 'Aus Marokko', 'Aus Kuba']],
              ['Was platzte in der Finanzkrise?', 'Die Immobilienblase', ['Die Ölblase', 'Die Internetblase', 'Nichts']],
              ['Wie hoch war die Jugendarbeitslosigkeit?', 'Über 50 Prozent', ['5 Prozent', '15 Prozent', '90 Prozent']],
              ['Welchen Platz besetzten die Empörten?', 'Die Puerta del Sol', ['Die Plaza Mayor', 'Die Rambla', 'Die Alhambra']],
              ['Wann wurde Spanien Europameister?', '2008 und 2012', ['1964 und 1984', '2010 und 2014', '2016']],
              ['Wo fand die WM 2010 statt?', 'In Südafrika', ['In Brasilien', 'In Deutschland', 'In Spanien']],
              ['Wann erklärte die ETA das Ende ihres Kampfes?', '2011', ['2018', '1975', '2004']],
              ['Wie viele Menschen hatte die ETA getötet?', 'Über 800', ['Rund 80', 'Rund 8000', 'Rund 8']],
              ['Warum dankte Juan Carlos ab?', 'Nach Skandalen', ['Wegen eines Krieges', 'Wegen der ETA', 'Wegen eines Referendums']],
              ['Wie reagierte Madrid auf die Unabhängigkeitserklärung Kataloniens?', 'Es setzte die Autonomie vorübergehend außer Kraft', ['Es erkannte sie an', 'Es ignorierte sie', 'Es schickte die Armee in einen Krieg']],
              ['Wer hatte das Referendum 2017 verboten?', 'Das Verfassungsgericht', ['Der König', 'Die EU', 'Die UNO']],
            ],
            schwer: [
              ['Wie heißt das Tal der Gefallenen heute?', 'Valle de Cuelgamuros', ['Valle de la Paz', 'Valle de Franco', 'Valle de los Reyes']],
              ['Wann wurden Francos Gebeine umgebettet?', '2019', ['1975', '2004', '2014']],
              ['Seit wann regiert Pedro Sánchez?', '2018', ['2011', '2004', '2014']],
              ['Wie viele Einwohner hat Spanien etwa?', 'Rund 48 Millionen', ['Rund 20 Millionen', 'Rund 80 Millionen', 'Rund 100 Millionen']],
              ['Worin ist Spanien weltweit führend?', 'Organspenden und Solarenergie', ['Ölförderung', 'Autoproduktion', 'Kohleabbau']],
              ['Wie viele Menschen haben Spanisch als Muttersprache etwa?', 'Fast 500 Millionen', ['50 Millionen', '5 Milliarden', '100 Millionen']],
              ['Welchen Rang hat Spanisch als Muttersprache?', 'Zweitgrößte der Welt', ['Größte', 'Zehntgrößte', 'Fünftgrößte']],
              ['Was folgte drei Tage nach dem 11-M?', 'Die Wahl, die die PSOE gewann', ['Ein Putsch', 'Der EU-Austritt', 'Neue Anschläge']],
              ['Welche Rolle spielte Spanien bei der Homoehe 2005?', 'Eines der ersten Länder der Welt', ['Das letzte Land Europas', 'Gar keine', 'Es verbot sie']],
              ['Wie verlief das Referendum am 1. Oktober 2017?', 'Polizisten gingen gewaltsam gegen Wähler vor', ['Völlig friedlich mit Erlaubnis', 'Es fiel aus', 'Die Armee wählte mit']],
              ['Was geschah mit katalanischen Anführern?', 'Sie wurden verurteilt oder flohen', ['Sie wurden Minister in Madrid', 'Sie wurden geehrt', 'Nichts']],
              ['Was ermöglichten EU-Gelder?', 'Autobahnen und Schnellbahnen', ['Neue Kolonien', 'Eine Armee', 'Die Monarchie']],
              ['Warum war 1992 Spaniens großes Jahr?', 'Olympia, Weltausstellung und Kulturhauptstadt', ['EG-Beitritt', 'Euro-Einführung', 'Neue Verfassung']],
              ['Wer war Zapatero?', 'Sozialistischer Regierungschef ab 2004', ['König', 'ETA-Führer', 'Konservativer Präsident']],
              ['Welche Folge hatte die Krise ab 2008 politisch?', 'Proteste und neue Parteien wie Podemos', ['Rückkehr der Diktatur', 'Ende der Monarchie', 'Keine']],
              ['Was ist der 15-M?', 'Die Protestbewegung der Empörten 2011', ['Ein Putsch', 'Ein Gesetz', 'Ein Feiertag']],
              ['Welche Sportnation war Spanien 2008–2012?', 'Fußballmeister Europas und der Welt', ['Ohne Erfolge', 'Nur im Radsport', 'Nur im Handball']],
              ['Was ist Felipe VI. für Juan Carlos?', 'Sein Sohn', ['Sein Bruder', 'Sein Enkel', 'Sein Neffe']],
              ['Was traf Spanien 2020 besonders hart?', 'Die Corona-Pandemie', ['Ein Erdbeben', 'Ein Krieg', 'Ein Vulkan in Madrid']],
              ['Mit welchem Ereignis endete der ETA-Terror endgültig?', 'Auflösung 2018', ['Francos Tod', 'Der 23-F', 'Der EG-Beitritt']],
            ],
          },
        },
      ],
    },
  ],
};
