import type { Epoch } from '../types';

export const E1: Epoch = {
  id: 'kolonie',
  name: 'Ureinwohner und Kolonie',
  period: 'bis 1810',
  events: [
    {
      id: 'kolonie',
      title: 'Die Kolonie am Río de la Plata',
      date: 'bis 1810',
      text: [
        'Lange vor den Spaniern lebten im heutigen Argentinien viele indigene Völker. Ab 1516 erkundeten Spanier den Río de la Plata; Buenos Aires wurde zweimal gegründet. Lange war die Region ein armer Rand des spanischen Weltreichs, bis sie 1776 ein eigenes Vizekönigreich wurde.',
      ],
      subtopics: [
        {
          id: 'ureinwohner',
          title: 'Die Ureinwohner',
          date: 'bis 1500',
          text: [
            'Menschen leben im heutigen Argentinien seit mindestens 11.000 Jahren. In Patagonien liegt die „Cueva de las Manos“ („Höhle der Hände“): Dort hinterließen Jäger vor rund 9.000 Jahren Hunderte Handabdrücke in Rot, Schwarz und Weiß an den Felswänden, indem sie Farbe um ihre Hände sprühten. Die Höhle ist UNESCO-Welterbe.',
            'Im trockenen Nordwesten lebten die Diaguita in Dörfern, bauten auf Terrassen Mais, Bohnen und Kürbis an, hielten Lamas und stellten schöne Keramik und Metallarbeiten her. Im 15. Jahrhundert eroberte das Inkareich den Nordwesten; ein Zweig der Inkastraße reichte bis in die Gegend des heutigen Mendoza. Auf dem Gipfel des Llullaillaco, eines über 6.700 Meter hohen Vulkans, fand man 1999 drei Kindermumien, die die Inka geopfert hatten.',
            'Im feuchten Nordosten lebten die Guaraní, die in Wäldern Maniok und Mais anbauten. Ihre Sprache wird bis heute in der Region gesprochen. In der Pampa und in Patagonien zogen Jäger und Sammler wie die Tehuelche umher, die Guanakos und Nandus jagten; Nandus fingen sie mit der „Boleadora“, einer Wurfschleuder aus Lederriemen mit Steinkugeln.',
            'Im Süden und auf der anderen Seite der Anden lebten die Mapuche, die sich später lange gegen Spanier und Argentinier wehrten. Ganz im Süden, auf Feuerland, lebten Völker wie die Selk’nam, die sich in Guanakofelle hüllten, und die Yaghan, die trotz Kälte kaum Kleidung trugen und sich mit Fett und Feuer wärmten. Der Name „Feuerland“ stammt von den vielen Feuern, die Magellans Seeleute 1520 an der Küste sahen.',
            'Insgesamt lebten im heutigen Argentinien wohl einige Hunderttausend Menschen, deutlich weniger als in Mexiko oder Peru. Es gab keine großen Städte oder Reiche außer dem Inkagebiet im Nordwesten.',
          ],
          quiz: {
            leicht: [
              ['Seit wann leben Menschen mindestens im heutigen Argentinien?', 'Seit rund 11.000 Jahren', ['Seit 500 Jahren', 'Seit 2.000 Jahren', 'Seit einer Million Jahren']],
              ['Wie heißt die Höhle mit den Handabdrücken?', 'Cueva de las Manos', ['Cueva de los Pies', 'Altamira', 'Lascaux']],
              ['Was bedeutet „Cueva de las Manos“?', 'Höhle der Hände', ['Höhle der Füße', 'Höhle der Tiere', 'Höhle der Könige']],
              ['In welcher Region liegt die Cueva de las Manos?', 'In Patagonien', ['In Buenos Aires', 'In den Anden Perus', 'In Feuerland']],
              ['Wie entstanden die Handabdrücke?', 'Man sprühte Farbe um die Hände', ['Man ritzte sie in Stein', 'Man malte mit Pinseln', 'Man brannte sie ein']],
              ['Welches Volk lebte im Nordwesten?', 'Die Diaguita', ['Die Guaraní', 'Die Tehuelche', 'Die Yaghan']],
              ['Was bauten die Diaguita an?', 'Mais, Bohnen und Kürbis', ['Weizen und Roggen', 'Reis', 'Kaffee']],
              ['Welche Tiere hielten die Diaguita?', 'Lamas', ['Pferde', 'Kühe', 'Schafe']],
              ['Welches Reich eroberte im 15. Jahrhundert den Nordwesten?', 'Das Inkareich', ['Das Aztekenreich', 'Das Mayareich', 'Spanien']],
              ['Was fand man 1999 auf dem Llullaillaco?', 'Drei Kindermumien', ['Gold der Spanier', 'Einen Dinosaurier', 'Eine Stadt']],
              ['Welches Volk lebte im feuchten Nordosten?', 'Die Guaraní', ['Die Diaguita', 'Die Mapuche', 'Die Selk’nam']],
              ['Wird die Sprache der Guaraní noch gesprochen?', 'Ja, bis heute', ['Nein, sie ist ausgestorben', 'Nur in Spanien', 'Nur in Büchern']],
              ['Welches Volk zog durch Pampa und Patagonien?', 'Die Tehuelche', ['Die Inka', 'Die Guaraní', 'Die Diaguita']],
              ['Welche Tiere jagten die Tehuelche?', 'Guanakos und Nandus', ['Bisons und Hirsche', 'Elefanten', 'Kängurus']],
              ['Wie heißt die Wurfschleuder mit Steinkugeln?', 'Boleadora', ['Bumerang', 'Lasso', 'Speer']],
              ['Welches Volk wehrte sich lange im Süden?', 'Die Mapuche', ['Die Guaraní', 'Die Diaguita', 'Die Inka']],
              ['Welche Insel liegt ganz im Süden?', 'Feuerland', ['Grönland', 'Madagaskar', 'Island']],
              ['Woher stammt der Name „Feuerland“?', 'Von Feuern, die Magellans Seeleute sahen', ['Von Vulkanen', 'Von einem Waldbrand 1900', 'Von einem König namens Feuer']],
              ['Gab es außer im Inkagebiet große Städte?', 'Nein', ['Ja, viele', 'Ja, Buenos Aires', 'Ja, eine Hauptstadt der Guaraní']],
              ['Wie viele Menschen lebten wohl im heutigen Argentinien vor den Spaniern?', 'Einige Hunderttausend', ['Einige Dutzend', 'Hundert Millionen', 'Gar keine']],
            ],
            mittel: [
              ['Wie alt sind die Handabdrücke der Cueva de las Manos etwa?', 'Rund 9.000 Jahre', ['Rund 900 Jahre', 'Rund 90.000 Jahre', 'Rund 200 Jahre']],
              ['Welche Farben haben die Handabdrücke?', 'Rot, Schwarz und Weiß', ['Blau und Grün', 'Gold', 'Nur Gelb']],
              ['Welchen Status hat die Cueva de las Manos?', 'UNESCO-Welterbe', ['Nationalstadion', 'Königsgrab', 'Militärzone']],
              ['Wer hinterließ die Handabdrücke?', 'Jäger', ['Spanier', 'Inka', 'Mönche']],
              ['Wie bauten die Diaguita ihre Felder an?', 'Auf Terrassen', ['Auf schwimmenden Inseln', 'In Wüstensand ohne Wasser', 'Unter der Erde']],
              ['Wofür waren die Diaguita bekannt?', 'Für Keramik und Metallarbeiten', ['Für Pyramiden', 'Für Schiffe', 'Für Schrift']],
              ['Wie weit reichte ein Zweig der Inkastraße?', 'Bis in die Gegend von Mendoza', ['Bis Feuerland', 'Bis Buenos Aires', 'Bis Brasilien']],
              ['Wie hoch ist der Llullaillaco?', 'Über 6.700 Meter', ['Rund 2.000 Meter', 'Rund 4.000 Meter', 'Über 8.800 Meter']],
              ['Was ist der Llullaillaco?', 'Ein Vulkan', ['Ein Fluss', 'Ein See', 'Eine Stadt']],
              ['Wer opferte die Kinder auf dem Llullaillaco?', 'Die Inka', ['Die Spanier', 'Die Guaraní', 'Die Tehuelche']],
              ['Was bauten die Guaraní an?', 'Maniok und Mais', ['Weizen', 'Reis', 'Trauben']],
              ['Wo lebten die Guaraní?', 'In Wäldern im Nordosten', ['In der Wüste', 'Auf Feuerland', 'Im Hochgebirge']],
              ['Wie lebten die Tehuelche?', 'Als Jäger und Sammler', ['In Städten', 'Als Bauern auf Terrassen', 'Als Fischer auf Inseln']],
              ['Woraus bestand die Boleadora?', 'Aus Lederriemen mit Steinkugeln', ['Aus Holz', 'Aus Eisen', 'Aus Gold']],
              ['Wo lebten die Mapuche außer im Süden Argentiniens?', 'Auf der anderen Seite der Anden', ['In Brasilien', 'In Mexiko', 'In Spanien']],
              ['Welche Völker lebten auf Feuerland?', 'Die Selk’nam und die Yaghan', ['Die Diaguita und die Inka', 'Die Guaraní und die Tupi', 'Die Azteken']],
              ['Wie wärmten sich die Yaghan?', 'Mit Fett und Feuer', ['Mit dicken Pelzmänteln aus Europa', 'In Steinhäusern mit Heizung', 'Gar nicht']],
              ['Wann sahen Magellans Seeleute die Feuer?', '1520', ['1492', '1580', '1776']],
              ['Mit welchen Regionen verglichen war die Bevölkerung klein?', 'Mit Mexiko und Peru', ['Mit Feuerland', 'Mit der Antarktis', 'Mit Grönland']],
              ['Welche Region gehörte zum Inkareich?', 'Der Nordwesten', ['Patagonien', 'Feuerland', 'Die Pampa']],
            ],
            schwer: [
              ['Mit welcher Technik entstanden die Handabdrücke?', 'Farbe wurde um die Hand gesprüht', ['Die Hand wurde eingebrannt', 'Die Hand wurde eingemeißelt', 'Die Hand wurde mit Gold belegt']],
              ['Welcher Vulkan ist Fundort von Inka-Kindermumien?', 'Llullaillaco', ['Aconcagua', 'Cotopaxi', 'Popocatépetl']],
              ['Wann wurden die Kindermumien gefunden?', '1999', ['1911', '1950', '2015']],
              ['Wie viele Kindermumien fand man auf dem Llullaillaco?', 'Drei', ['Eine', 'Zehn', 'Hundert']],
              ['Welches Tier fingen die Tehuelche mit der Boleadora?', 'Nandus', ['Pinguine', 'Pumas', 'Wale']],
              ['Welches Volk ist mit der Keramik des Nordwestens verbunden?', 'Die Diaguita', ['Die Tehuelche', 'Die Yaghan', 'Die Selk’nam']],
              ['Welcher Seefahrer gab indirekt Feuerland seinen Namen?', 'Magellan', ['Kolumbus', 'Vespucci', 'Drake']],
              ['Welches Volk ist für seine Sprache in der Region bis heute bekannt?', 'Die Guaraní', ['Die Diaguita', 'Die Selk’nam', 'Die Tehuelche']],
              ['Welches Volk leistete später lange Widerstand gegen Spanier und Argentinier?', 'Die Mapuche', ['Die Guaraní', 'Die Inka', 'Die Diaguita']],
              ['Was war an der Kleidung der Yaghan auffällig?', 'Sie trugen trotz Kälte kaum Kleidung', ['Sie trugen Rüstungen', 'Sie trugen Seide', 'Sie trugen Federmäntel']],
              ['Welches Tier jagten die Tehuelche außer Nandus?', 'Guanakos', ['Bisons', 'Elche', 'Zebras']],
              ['Welcher Teil Argentiniens ist trocken und lag im Inkagebiet?', 'Der Nordwesten', ['Der Nordosten', 'Die Pampa', 'Feuerland']],
              ['Welche Feldfrüchte verbinden Diaguita und Guaraní?', 'Mais', ['Weizen', 'Reis', 'Kaffee']],
              ['Wie viele Jahre alt sind die ältesten Spuren von Menschen mindestens?', 'Rund 11.000', ['Rund 1.100', 'Rund 110.000', 'Rund 500']],
              ['Welche Lebensweise hatten die Völker der Pampa?', 'Sie waren nicht sesshaft', ['Sie lebten in Großstädten', 'Sie waren Seefahrer', 'Sie waren Bergleute']],
              ['Was zeigt die Cueva de las Manos vor allem?', 'Hunderte Handabdrücke', ['Pyramiden', 'Schriftzeichen', 'Goldschmuck']],
              ['Zu welcher Zeit eroberten die Inka den Nordwesten?', 'Im 15. Jahrhundert', ['Im 10. Jahrhundert', 'Im 18. Jahrhundert', 'Vor 9.000 Jahren']],
              ['Welches Tier ist mit den Diaguita verbunden?', 'Das Lama', ['Das Pferd', 'Das Rind', 'Das Kamel']],
              ['Welche Insel bewohnten die Yaghan?', 'Feuerland', ['Die Falklandinseln', 'Chiloé', 'Kuba']],
              ['Wie unterschied sich Argentinien vor 1500 von Mexiko?', 'Es hatte weniger Menschen und keine großen Reiche', ['Es hatte mehr Städte', 'Es hatte Pyramiden', 'Es war ein Kaiserreich']],
            ],
          },
        },
        {
          id: 'eroberung-buenos-aires',
          title: 'Entdeckung, Eroberung und Gründung von Buenos Aires',
          date: '1516–1700',
          text: [
            '1516 erreichte der spanische Seefahrer Juan Díaz de Solís die breite Mündung eines Flusses, den er für ein „Süßwassermeer“ hielt; er wurde dort von Einheimischen getötet. 1520 fuhr Ferdinand Magellan an der Küste Patagoniens entlang. Der Name „Río de la Plata“ („Silberfluss“) entstand, weil die Spanier hofften, über den Fluss zu sagenhaften Silberbergen zu gelangen; daher kommt auch der Name „Argentinien“ vom lateinischen „argentum“ (Silber).',
            '1536 gründete Pedro de Mendoza die erste Siedlung Buenos Aires („Gute Winde“). Mendoza selbst starb 1537 auf der Rückfahrt nach Spanien. Hunger und Angriffe der Einheimischen zwangen die Spanier, sie 1541 aufzugeben; viele zogen nach Asunción im heutigen Paraguay. 1580 gründete Juan de Garay Buenos Aires ein zweites Mal, diesmal dauerhaft.',
            'Die ersten großen Städte entstanden aber von Norden aus, über Peru: Santiago del Estero (1553) ist die älteste noch bestehende Stadt Argentiniens, später folgten Tucumán, Córdoba (1573) und Salta. In Córdoba gründeten die Jesuiten 1613 eine der ältesten Universitäten Amerikas. Mendoza wurde 1561 von Chile aus gegründet.',
            'Im Nordosten errichteten die Jesuiten ab 1609 „Reduktionen“, Missionsdörfer für die Guaraní, in denen diese vor Sklavenjägern geschützt waren, Landwirtschaft betrieben und europäische Musik und Handwerk lernten. Ruinen wie San Ignacio Miní sind heute UNESCO-Welterbe. 1767 wurden die Jesuiten aus dem spanischen Reich vertrieben, und die Reduktionen verfielen.',
            'Buenos Aires blieb lange arm, weil Spanien den Handel nur über Lima und Panama erlaubte. Daher blühte der Schmuggel, etwa mit Portugiesen. In der Pampa vermehrten sich verwilderte Rinder und Pferde, die die Spanier mitgebracht hatten; daraus entstanden der Handel mit Leder und die Kultur der Gauchos.',
          ],
          quiz: {
            leicht: [
              ['Wer erreichte 1516 den Río de la Plata?', 'Juan Díaz de Solís', ['Kolumbus', 'Magellan', 'Pizarro']],
              ['Was geschah mit Solís?', 'Er wurde von Einheimischen getötet', ['Er wurde König', 'Er fand Silber', 'Er gründete Buenos Aires']],
              ['Wer fuhr 1520 an Patagonien entlang?', 'Ferdinand Magellan', ['Vasco da Gama', 'Kolumbus', 'Cortés']],
              ['Was bedeutet „Río de la Plata“?', 'Silberfluss', ['Goldfluss', 'Großer Fluss', 'Blauer Fluss']],
              ['Woher stammt der Name „Argentinien“?', 'Vom lateinischen Wort für Silber', ['Von einem König', 'Von einem Indigenen-Wort für Pampa', 'Vom Wort für Rind']],
              ['Wer gründete 1536 Buenos Aires zum ersten Mal?', 'Pedro de Mendoza', ['Juan de Garay', 'Solís', 'San Martín']],
              ['Was bedeutet „Buenos Aires“?', 'Gute Winde', ['Schöne Stadt', 'Großer Hafen', 'Silberstadt']],
              ['Warum wurde die erste Siedlung aufgegeben?', 'Wegen Hunger und Angriffen', ['Wegen eines Vulkans', 'Wegen eines Erdbebens', 'Wegen der Pest']],
              ['Wer gründete Buenos Aires 1580 dauerhaft?', 'Juan de Garay', ['Pedro de Mendoza', 'Solís', 'Magellan']],
              ['Wann wurde Buenos Aires dauerhaft gegründet?', '1580', ['1536', '1516', '1776']],
              ['Welche ist die älteste bestehende Stadt Argentiniens?', 'Santiago del Estero', ['Buenos Aires', 'Córdoba', 'Rosario']],
              ['Von wo aus entstanden die ersten großen Städte?', 'Von Norden über Peru', ['Von Brasilien aus', 'Von der Antarktis', 'Von Feuerland']],
              ['Welcher Orden gründete in Córdoba eine Universität?', 'Die Jesuiten', ['Die Franziskaner', 'Die Benediktiner', 'Die Templer']],
              ['Wie hießen die Missionsdörfer der Jesuiten?', 'Reduktionen', ['Haciendas', 'Quilombos', 'Encomiendas']],
              ['Für welches Volk errichteten die Jesuiten Reduktionen?', 'Für die Guaraní', ['Für die Mapuche', 'Für die Inka', 'Für die Diaguita']],
              ['Wovor schützten die Reduktionen die Guaraní?', 'Vor Sklavenjägern', ['Vor Vulkanen', 'Vor dem Meer', 'Vor Kälte']],
              ['Wann wurden die Jesuiten vertrieben?', '1767', ['1609', '1810', '1580']],
              ['Warum blieb Buenos Aires lange arm?', 'Spanien erlaubte Handel nur über Lima und Panama', ['Es gab dort kein Wasser', 'Es war eine Insel', 'Es gehörte Portugal']],
              ['Was blühte deshalb in Buenos Aires?', 'Der Schmuggel', ['Der Goldbergbau', 'Der Weinbau', 'Der Tourismus']],
              ['Welche Kultur entstand aus verwilderten Rindern und Pferden?', 'Die Kultur der Gauchos', ['Die Kultur der Samurai', 'Die Kultur der Wikinger', 'Die Kultur der Inka']],
            ],
            mittel: [
              ['Wofür hielt Solís den Río de la Plata?', 'Für ein Süßwassermeer', ['Für einen See', 'Für den Amazonas', 'Für einen Seeweg nach Indien']],
              ['Worauf hofften die Spanier am Río de la Plata?', 'Auf sagenhafte Silberberge', ['Auf Gewürze', 'Auf Zucker', 'Auf Pelze']],
              ['Wann wurde die erste Siedlung Buenos Aires aufgegeben?', '1541', ['1536', '1580', '1600']],
              ['Wohin zogen viele Siedler 1541?', 'Nach Asunción', ['Nach Lima', 'Nach Spanien', 'Nach Santiago de Chile']],
              ['In welchem heutigen Land liegt Asunción?', 'Paraguay', ['Uruguay', 'Bolivien', 'Chile']],
              ['Wann wurde Santiago del Estero gegründet?', '1553', ['1536', '1580', '1610']],
              ['Wann wurde Córdoba gegründet?', '1573', ['1553', '1613', '1580']],
              ['Wann gründeten die Jesuiten die Universität in Córdoba?', '1613', ['1573', '1767', '1810']],
              ['Von wo aus wurde Mendoza gegründet?', 'Von Chile aus', ['Von Buenos Aires aus', 'Von Brasilien aus', 'Von Spanien direkt']],
              ['Wann wurde Mendoza gegründet?', '1561', ['1536', '1580', '1776']],
              ['Ab wann errichteten die Jesuiten Reduktionen?', 'Ab 1609', ['Ab 1516', 'Ab 1767', 'Ab 1700']],
              ['Was lernten die Guaraní in den Reduktionen?', 'Musik und Handwerk', ['Fechten', 'Seefahrt', 'Bergbau']],
              ['Welche Reduktionsruine ist UNESCO-Welterbe?', 'San Ignacio Miní', ['Machu Picchu', 'Teotihuacán', 'Tikal']],
              ['Was geschah nach der Vertreibung der Jesuiten mit den Reduktionen?', 'Sie verfielen', ['Sie wurden Städte', 'Sie blühten auf', 'Sie wurden portugiesisch']],
              ['Mit wem schmuggelte man in Buenos Aires etwa?', 'Mit Portugiesen', ['Mit Chinesen', 'Mit Russen', 'Mit Inka']],
              ['Woher kamen die Rinder und Pferde der Pampa?', 'Die Spanier hatten sie mitgebracht', ['Sie lebten dort schon immer', 'Aus Afrika geschwommen', 'Von den Inka']],
              ['Welcher Handel entstand aus den Rinderherden?', 'Der Handel mit Leder', ['Der Handel mit Seide', 'Der Handel mit Tee', 'Der Handel mit Elfenbein']],
              ['Über welche Städte musste der Handel offiziell laufen?', 'Über Lima und Panama', ['Über Buenos Aires direkt', 'Über Rio', 'Über Asunción']],
              ['In welcher Stadt wurde eine der ältesten Universitäten Amerikas gegründet?', 'Córdoba', ['Buenos Aires', 'Salta', 'Mendoza']],
              ['Welche Städte entstanden außer Córdoba von Norden aus?', 'Tucumán und Salta', ['Buenos Aires und Rosario', 'Ushuaia und Bariloche', 'La Plata und Mar del Plata']],
            ],
            schwer: [
              ['Welches lateinische Wort steckt in „Argentinien“?', 'Argentum', ['Aurum', 'Ferrum', 'Plumbum']],
              ['Wie oft wurde Buenos Aires gegründet?', 'Zweimal', ['Einmal', 'Dreimal', 'Viermal']],
              ['Welcher Gründer von Buenos Aires war erfolgreich?', 'Juan de Garay', ['Pedro de Mendoza', 'Sebastian Cabot', 'Solís']],
              ['Warum war Santiago del Estero früher als Buenos Aires dauerhaft?', 'Die Besiedlung kam zuerst von Peru im Norden', ['Es lag am Meer', 'Es war eine Inkastadt', 'Es wurde von Portugal gegründet']],
              ['Welches Jahr markiert die Vertreibung der Jesuiten aus dem spanischen Reich?', '1767', ['1759', '1773', '1810']],
              ['Welcher Zweck der Reduktionen war zentral?', 'Schutz und Missionierung der Guaraní', ['Silberabbau', 'Sklavenhandel', 'Pferdezucht für Spanien']],
              ['Welche Handelsbeschränkung förderte den Schmuggel?', 'Das Handelsverbot außer über Lima und Panama', ['Ein Verbot von Rindern', 'Ein Verbot von Silber', 'Ein Verbot von Booten']],
              ['Welcher Seefahrer starb 1516 am Río de la Plata?', 'Juan Díaz de Solís', ['Magellan', 'Pedro de Mendoza', 'Juan de Garay']],
              ['Welcher Gründer von Buenos Aires starb 1537 auf der Rückfahrt nach Spanien?', 'Pedro de Mendoza', ['Juan de Garay', 'San Martín', 'Belgrano']],
              ['Welche Stadt wurde zur Zuflucht der Siedler von 1541?', 'Asunción', ['Lima', 'Montevideo', 'Córdoba']],
              ['Welche Wirtschaftsgrundlage hatte die Pampa im 17. Jahrhundert?', 'Verwilderte Rinder und Leder', ['Zuckerplantagen', 'Silberminen', 'Kaffee']],
              ['Woher kam die Gründung Mendozas?', 'Aus Chile', ['Aus Peru direkt', 'Aus Buenos Aires', 'Aus Paraguay']],
              ['Welche Musikkultur blühte in den Reduktionen?', 'Europäische Musik mit Guaraní-Musikern', ['Tango', 'Samba', 'Flamenco']],
              ['Wofür steht San Ignacio Miní?', 'Für die Jesuitenreduktionen', ['Für die Inkastraße', 'Für die erste Gründung von Buenos Aires', 'Für die Gauchos']],
              ['Welche Gruppe schmuggelte mit Buenos Aires?', 'Portugiesen', ['Inka', 'Mapuche', 'Jesuiten']],
              ['Welcher Name galt dem Fluss wegen der Silberhoffnungen?', 'Río de la Plata', ['Río Paraná', 'Río Uruguay', 'Río Colorado']],
              ['Welches Ziel verfolgte Garay 1580?', 'Eine dauerhafte Hafenstadt', ['Eine Jesuitenmission', 'Eine Silbermine', 'Eine Festung gegen die Inka']],
              ['Welche Universität zählt zu den ältesten Amerikas?', 'Die Universität von Córdoba', ['Die Universität von Buenos Aires', 'Die Universität von Mendoza', 'Die Universität von Rosario']],
              ['Wie entstanden die Gauchos?', 'Aus dem Leben mit verwilderten Herden in der Pampa', ['Aus spanischen Adelsfamilien', 'Aus Jesuitenschulen', 'Aus Inka-Kriegern']],
              ['Wann fuhr Magellan an Patagonien entlang?', '1520', ['1516', '1536', '1492']],
            ],
          },
        },
        {
          id: 'vizekoenigreich',
          title: 'Vizekönigreich und britische Invasionen',
          date: '1776–1810',
          text: [
            '1776 schuf Spanien das Vizekönigreich des Río de la Plata mit der Hauptstadt Buenos Aires. Es umfasste das heutige Argentinien, Uruguay, Paraguay und Bolivien mit den Silberminen von Potosí. Ziel war es, die Region gegen Portugal und Großbritannien zu sichern. 1778 erlaubte Spanien den freien Handel innerhalb seines Reiches, und Buenos Aires wuchs zum wichtigen Hafen.',
            'Die Gesellschaft war gespalten: Oben standen die in Spanien geborenen „Peninsulares“, darunter die in Amerika geborenen „Criollos“, dann Mestizen mit spanischen und indigenen Vorfahren, Indigene und afrikanische Sklaven. In Buenos Aires lebten um 1800 viele Afrikaner und ihre Nachkommen; ihr Anteil ging später stark zurück, sodass sie heute kaum sichtbar sind. Die Criollos waren oft reich, wurden aber von hohen Ämtern ferngehalten.',
            '1806 besetzte eine kleine britische Truppe Buenos Aires, während der spanische Vizekönig Sobremonte floh. Unter dem Franzosen in spanischen Diensten Santiago de Liniers vertrieben Milizen und Bürger die Briten nach etwa sechs Wochen. 1807 griffen die Briten mit einer größeren Armee erneut an, doch die Einwohner wehrten sie in Straßenkämpfen ab; Frauen gossen von den Dächern heißes Öl auf die Soldaten.',
            'Diese „Reconquista“ und „Defensa“ machten die Criollos selbstbewusst: Sie hatten ohne Hilfe aus Spanien gesiegt, und die Bürger setzten Liniers an Sobremontes Stelle als Vizekönig ein. Die neuen Milizen, wie das Regiment der „Patricios“, wurden zu einer politischen Macht.',
            '1808 besetzte Napoleon Spanien und setzte König Ferdinand VII. ab. Damit fehlte in Madrid eine rechtmäßige Regierung, und in ganz Spanisch-Amerika stellte sich die Frage, wer nun herrschen solle. In Buenos Aires führte das 1810 zur Mairevolution.',
          ],
          quiz: {
            leicht: [
              ['Wann schuf Spanien das Vizekönigreich des Río de la Plata?', '1776', ['1580', '1810', '1700']],
              ['Welche Stadt war Hauptstadt des Vizekönigreichs?', 'Buenos Aires', ['Lima', 'Córdoba', 'Asunción']],
              ['Welche Silberminen gehörten zum Vizekönigreich?', 'Potosí', ['Zacatecas', 'Ouro Preto', 'Guanajuato']],
              ['Gegen wen sollte das Vizekönigreich die Region sichern?', 'Gegen Portugal und Großbritannien', ['Gegen die Inka', 'Gegen Japan', 'Gegen die USA']],
              ['Welche heutigen Länder gehörten dazu?', 'Argentinien, Uruguay, Paraguay und Bolivien', ['Chile und Peru', 'Brasilien und Venezuela', 'Mexiko und Kuba']],
              ['Wie hießen die in Spanien Geborenen?', 'Peninsulares', ['Criollos', 'Mestizen', 'Gauchos']],
              ['Wie hießen die in Amerika geborenen Spanier?', 'Criollos', ['Peninsulares', 'Mestizen', 'Mapuche']],
              ['Wovon wurden die Criollos ferngehalten?', 'Von hohen Ämtern', ['Vom Handel', 'Von Kirchen', 'Vom Reiten']],
              ['Welches Land besetzte 1806 Buenos Aires?', 'Großbritannien', ['Frankreich', 'Portugal', 'Spanien']],
              ['Was tat Vizekönig Sobremonte 1806?', 'Er floh', ['Er kämpfte heldenhaft', 'Er wurde König', 'Er ergab sich den Franzosen']],
              ['Wer führte die Vertreibung der Briten an?', 'Santiago de Liniers', ['San Martín', 'Belgrano', 'Sobremonte']],
              ['Wie lange hielten die Briten Buenos Aires 1806 etwa?', 'Etwa sechs Wochen', ['Zehn Jahre', 'Einen Tag', 'Zwei Jahre']],
              ['Wann griffen die Briten erneut an?', '1807', ['1806', '1810', '1816']],
              ['Wie wehrten die Einwohner die Briten 1807 ab?', 'In Straßenkämpfen', ['Mit einer Flotte', 'Durch Bestechung', 'Gar nicht']],
              ['Was gossen Frauen von den Dächern?', 'Heißes Öl', ['Wein', 'Milch', 'Farbe']],
              ['Wie wirkten die Siege auf die Criollos?', 'Sie wurden selbstbewusst', ['Sie wurden ängstlich', 'Sie flohen nach Spanien', 'Sie wurden britisch']],
              ['Wer wurde nach Sobremonte Vizekönig?', 'Liniers', ['Belgrano', 'San Martín', 'Garay']],
              ['Wer besetzte 1808 Spanien?', 'Napoleon', ['Großbritannien', 'Portugal', 'Russland']],
              ['Welcher spanische König wurde abgesetzt?', 'Ferdinand VII.', ['Karl V.', 'Philipp II.', 'Juan Carlos']],
              ['Wozu führte die Krise 1810 in Buenos Aires?', 'Zur Mairevolution', ['Zur Monarchie', 'Zur Rückkehr der Briten', 'Zum Bau der Pyramiden']],
            ],
            mittel: [
              ['Wann erlaubte Spanien freien Handel innerhalb des Reiches?', '1778', ['1776', '1806', '1810']],
              ['Was wurde Buenos Aires nach 1778?', 'Ein wichtiger Hafen', ['Ein Dorf', 'Eine Festung ohne Handel', 'Eine portugiesische Stadt']],
              ['Wer stand in der Gesellschaft ganz oben?', 'Die Peninsulares', ['Die Criollos', 'Die Mestizen', 'Die Gauchos']],
              ['Wer lebte um 1800 zahlreich in Buenos Aires?', 'Afrikaner und ihre Nachkommen', ['Chinesen', 'Inder', 'Japaner']],
              ['Wie waren die Criollos oft wirtschaftlich?', 'Reich', ['Arm', 'Versklavt', 'Ohne Besitz']],
              ['Wie nennt man die Rückeroberung von 1806?', 'Reconquista', ['Defensa', 'Revolución', 'Abertura']],
              ['Wie nennt man die Abwehr von 1807?', 'Defensa', ['Reconquista', 'Grito', 'Independencia']],
              ['Was war an den Siegen von 1806/07 besonders?', 'Sie gelangen ohne Hilfe aus Spanien', ['Spanien schickte eine große Armee', 'Portugal half', 'Frankreich half']],
              ['Wer setzte Liniers als Vizekönig ein?', 'Die Bürger', ['Der spanische König', 'Napoleon', 'Die Briten']],
              ['Welches Regiment wurde zu einer politischen Macht?', 'Die Patricios', ['Die Gauchos', 'Die Jesuiten', 'Die Granaderos']],
              ['Was entstand durch die britischen Invasionen?', 'Neue Milizen', ['Eine britische Kolonie', 'Eine Universität', 'Eine Kirche']],
              ['Wie groß war die britische Truppe 1806?', 'Klein', ['Riesig', 'Sie bestand nur aus Schiffen', 'Es gab keine']],
              ['Wie groß war die Armee 1807?', 'Größer als 1806', ['Kleiner als 1806', 'Gleich groß', 'Es gab keine']],
              ['Was fehlte in Madrid nach 1808?', 'Eine rechtmäßige Regierung', ['Eine Kirche', 'Ein Hafen', 'Eine Armee']],
              ['Welche Frage stellte sich in Spanisch-Amerika ab 1808?', 'Wer nun herrschen solle', ['Wo das Silber hinkommt', 'Welche Sprache man spricht', 'Wer die Rinder besitzt']],
              ['Wer waren Mestizen?', 'Menschen mit spanischen und indigenen Vorfahren', ['In Spanien Geborene', 'Briten', 'Jesuiten']],
              ['Welche Gruppe stand ganz unten in der Gesellschaft?', 'Afrikanische Sklaven', ['Die Criollos', 'Die Peninsulares', 'Die Vizekönige']],
              ['Woher stammte das Silber von Potosí?', 'Aus dem heutigen Bolivien', ['Aus Mexiko', 'Aus Peru an der Küste', 'Aus Brasilien']],
              ['Was tat Liniers 1806?', 'Er vertrieb die Briten', ['Er floh', 'Er lud die Briten ein', 'Er wurde Brite']],
              ['Wann war die Mairevolution?', '1810', ['1806', '1816', '1776']],
            ],
            schwer: [
              ['Welche zwei Begriffe bezeichnen die Siege 1806 und 1807?', 'Reconquista und Defensa', ['Grito und Fico', 'Abertura und Diretas', 'Estado Novo und Década Infame']],
              ['Warum wurde Sobremonte abgelöst?', 'Er war 1806 geflohen', ['Er war zu alt', 'Er war Brite', 'Er starb im Kampf']],
              ['Welche Folge hatten die Invasionen für die Machtverhältnisse?', 'Die Criollo-Milizen wurden politisch mächtig', ['Spanien wurde gestärkt', 'Die Briten blieben', 'Die Jesuiten kehrten zurück']],
              ['Welches Ereignis in Europa löste die Krise 1808 aus?', 'Napoleons Besetzung Spaniens', ['Die Französische Revolution 1789', 'Der Wiener Kongress', 'Die Schlacht bei Trafalgar']],
              ['Welche Silberstadt gab dem Vizekönigreich Reichtum?', 'Potosí', ['Córdoba', 'Montevideo', 'Salta']],
              ['Welche Reform machte Buenos Aires ab 1778 zu einem wichtigen Hafen?', 'Der freie Handel im spanischen Reich', ['Ein Hafen für Briten', 'Die Vertreibung der Jesuiten', 'Der Bau eines Kanals']],
              ['Welches Problem hatten die Criollos trotz Reichtums?', 'Sie bekamen keine hohen Ämter', ['Sie durften nicht handeln', 'Sie durften kein Land besitzen', 'Sie durften keine Kirche besuchen']],
              ['Welcher Franzose in spanischen Diensten wurde Held von Buenos Aires?', 'Santiago de Liniers', ['Napoleon', 'Lafayette', 'Sobremonte']],
              ['Welches Jahr markiert die erste britische Besetzung?', '1806', ['1807', '1776', '1810']],
              ['Welche Taktik nutzten die Einwohner 1807?', 'Straßenkampf von Häusern und Dächern', ['Seeschlacht', 'Belagerung Londons', 'Kapitulation']],
              ['Welche Gruppe bildete die Spitze der Kolonialgesellschaft?', 'Die Peninsulares', ['Die Criollos', 'Die Patricios', 'Die Gauchos']],
              ['Welcher König fehlte ab 1808 in Madrid?', 'Ferdinand VII.', ['Karl III.', 'Philipp V.', 'Alfons XIII.']],
              ['Welche Rolle spielten die Patricios?', 'Eine Criollo-Miliz mit politischer Macht', ['Eine spanische Adelsfamilie', 'Ein Jesuitenorden', 'Eine britische Einheit']],
              ['Wie wurde der Vizekönig nach 1806 bestimmt?', 'Die Bürger setzten Liniers ein', ['Der König ernannte Sobremonte neu', 'Napoleon ernannte ihn', 'Es gab keinen mehr']],
              ['Welche Länder umfasste das Vizekönigreich nicht?', 'Chile und Peru', ['Uruguay und Paraguay', 'Bolivien', 'Argentinien']],
              ['Warum fürchtete Spanien um die Region?', 'Wegen Portugal und Großbritannien', ['Wegen der Inka', 'Wegen Japans', 'Wegen der Azteken']],
              ['Welches Ereignis folgte direkt aus der Krise von 1808 in Buenos Aires?', 'Die Mairevolution 1810', ['Die Gründung von Buenos Aires', 'Die Vertreibung der Jesuiten', 'Der Paraguaykrieg']],
              ['Welche Bevölkerungsgruppe war in Buenos Aires um 1800 zahlreich, ist heute aber kaum sichtbar?', 'Afrikaner und ihre Nachkommen', ['Italiener', 'Deutsche', 'Briten']],
              ['Wie lange nach der Gründung des Vizekönigreichs kamen die Briten?', 'Rund 30 Jahre', ['Rund 300 Jahre', 'Ein Jahr', 'Rund 100 Jahre']],
              ['Was zeigten die Siege über die Briten den Criollos?', 'Dass sie sich selbst verteidigen konnten', ['Dass sie Spanien brauchten', 'Dass sie britisch werden wollten', 'Nichts']],
            ],
          },
        },
      ],
    },
  ],
};
