import type { Epoch } from '../types';

export const E3: Epoch = {
  id: 'aufstieg',
  name: 'Aufstieg und Peronismus',
  period: '1880–1955',
  events: [
    {
      id: 'einwanderung',
      title: 'Einwanderung, Fleisch und Tango',
      date: '1880–1943',
      text: [
        'Um 1900 zählte Argentinien dank Getreide und Fleisch zu den reichsten Ländern der Welt. Millionen Europäer wanderten ein, Buenos Aires wurde eine Weltstadt, und in seinen Vierteln entstand der Tango. Politisch folgten auf die Herrschaft der Oligarchie die Radikalen und 1930 der erste Militärputsch.',
      ],
      subtopics: [
        {
          id: 'einwanderung-tango',
          title: 'Kornkammer der Welt, Einwanderung und Tango',
          date: '1880–1914',
          text: [
            'Zwischen 1880 und 1914 wurde Argentinien zur „Kornkammer der Welt“. Auf der fruchtbaren Pampa wuchsen Weizen und Mais, und riesige Rinderherden lieferten Fleisch. Mit Kühlschiffen, die ab 1877 gefrorenes Fleisch über den Atlantik bringen konnten, wurde Rindfleisch zum großen Exportgut nach Großbritannien. Um 1910 gehörte Argentinien beim Einkommen pro Kopf zu den zehn reichsten Ländern der Welt.',
            'Von 1880 bis 1930 kamen rund sechs Millionen Einwanderer, vor allem aus Italien und Spanien, aber auch aus Frankreich, Deutschland, Osteuropa (darunter viele Juden) und dem Nahen Osten. Um 1914 war in Buenos Aires etwa die Hälfte der Einwohner im Ausland geboren. Viele Italiener prägten die Sprache: Das Spanisch von Buenos Aires klingt bis heute italienisch, und der Slang „Lunfardo“ enthält viele italienische Wörter.',
            'Die Einwanderer lebten oft dicht gedrängt in „Conventillos“, Mietskasernen mit vielen Familien um einen Hof, etwa im Hafenviertel La Boca. In diesen Vierteln entstand Ende des 19. Jahrhunderts der Tango, eine Mischung aus europäischen, afrikanischen und kreolischen Einflüssen. Das typische Instrument ist das „Bandoneon“, ein Handzuginstrument aus Deutschland. Der Sänger Carlos Gardel wurde in den 1920er- und 1930er-Jahren zum Weltstar; er starb 1935 bei einem Flugzeugabsturz.',
            'Politisch herrschte bis 1916 eine kleine Oberschicht reicher Großgrundbesitzer, die „Oligarchie“, die Wahlen durch Betrug gewann. Arbeiter organisierten sich in anarchistischen und sozialistischen Gewerkschaften; Streiks wurden hart unterdrückt. Zur Hundertjahrfeier 1910 präsentierte sich Buenos Aires mit Prachtbauten wie dem Teatro Colón (1908) als „Paris Südamerikas“; 1913 eröffnete die erste U-Bahn Lateinamerikas.',
            'Auch die Gauchos wurden zum Nationalsymbol: José Hernández schrieb 1872 das Versepos „Martín Fierro“ über einen verfolgten Gaucho, das als Nationalepos gilt. Der Fußball, von Briten eingeführt, wurde zur Leidenschaft; die Vereine Boca Juniors (1905) und River Plate (1901) wurden gegründet.',
          ],
          quiz: {
            leicht: [
              ['Wie nannte man Argentinien um 1900?', 'Kornkammer der Welt', ['Silberland', 'Kaffeeland', 'Zuckerinsel']],
              ['Was wuchs auf der Pampa?', 'Weizen und Mais', ['Kaffee und Kakao', 'Reis und Tee', 'Bananen']],
              ['Welches Exportgut lieferten die Rinderherden?', 'Fleisch', ['Kaffee', 'Seide', 'Gold']],
              ['Welche Erfindung machte den Fleischexport möglich?', 'Kühlschiffe', ['Flugzeuge', 'Flugboote', 'Konservendosen aus Gold']],
              ['Wohin wurde das Fleisch vor allem exportiert?', 'Nach Großbritannien', ['Nach China', 'Nach Brasilien', 'Nach Russland']],
              ['Wie reich war Argentinien um 1910?', 'Unter den zehn reichsten Ländern pro Kopf', ['Eines der ärmsten Länder', 'Durchschnittlich', 'Das reichste Land der Welt']],
              ['Wie viele Einwanderer kamen 1880–1930 etwa?', 'Rund sechs Millionen', ['Rund 60.000', 'Rund 600.000', 'Rund 60 Millionen']],
              ['Woher kamen die meisten Einwanderer?', 'Aus Italien und Spanien', ['Aus China und Japan', 'Aus Afrika', 'Aus den USA']],
              ['Wie klingt das Spanisch von Buenos Aires?', 'Italienisch', ['Französisch', 'Deutsch', 'Englisch']],
              ['Wie heißt der Slang von Buenos Aires?', 'Lunfardo', ['Spanglish', 'Portuñol', 'Guaraní']],
              ['Wie hießen die Mietskasernen der Einwanderer?', 'Conventillos', ['Favelas', 'Haciendas', 'Estancias']],
              ['In welchem Hafenviertel lebten viele Einwanderer?', 'La Boca', ['Recoleta', 'Palermo', 'Copacabana']],
              ['Welcher Tanz entstand in Buenos Aires?', 'Der Tango', ['Die Samba', 'Der Flamenco', 'Der Walzer']],
              ['Welches Instrument ist typisch für den Tango?', 'Das Bandoneon', ['Die Harfe', 'Die Trompete', 'Der Dudelsack']],
              ['Aus welchem Land stammt das Bandoneon?', 'Aus Deutschland', ['Aus Italien', 'Aus Spanien', 'Aus Argentinien']],
              ['Welcher Tango-Sänger wurde Weltstar?', 'Carlos Gardel', ['Astor Piazzolla', 'Julio Iglesias', 'Pelé']],
              ['Wie starb Carlos Gardel?', 'Bei einem Flugzeugabsturz', ['Im Krieg', 'Im Duell', 'An Altersschwäche']],
              ['Welches berühmte Opernhaus eröffnete 1908?', 'Das Teatro Colón', ['Die Scala', 'Das Opernhaus Manaus', 'Die Met']],
              ['Wie nannte sich Buenos Aires gern?', '„Paris Südamerikas“', ['„Rom Amerikas“', '„London des Südens“', '„Venedig der Anden“']],
              ['Wer führte den Fußball in Argentinien ein?', 'Die Briten', ['Die Spanier', 'Die Italiener', 'Die Deutschen']],
            ],
            mittel: [
              ['Ab wann konnten Kühlschiffe gefrorenes Fleisch transportieren?', 'Ab 1877', ['Ab 1810', 'Ab 1930', 'Ab 1950']],
              ['Welcher Anteil der Einwohner von Buenos Aires war um 1914 im Ausland geboren?', 'Etwa die Hälfte', ['Etwa ein Zehntel', 'Fast niemand', 'Alle']],
              ['Welche religiöse Gruppe kam aus Osteuropa?', 'Viele Juden', ['Viele Buddhisten', 'Viele Hindus', 'Keine']],
              ['Woher kamen weitere Einwanderer außer Europa?', 'Aus dem Nahen Osten', ['Aus Australien', 'Aus Kanada', 'Aus Grönland']],
              ['Welche Sprache prägte das Lunfardo besonders?', 'Italienisch', ['Englisch', 'Deutsch', 'Russisch']],
              ['Wie war ein Conventillo aufgebaut?', 'Viele Familien um einen Hof', ['Ein Einfamilienhaus', 'Ein Hochhaus mit Aufzug', 'Eine Burg']],
              ['Wann entstand der Tango?', 'Ende des 19. Jahrhunderts', ['Im 16. Jahrhundert', 'Nach 1950', 'Im Mittelalter']],
              ['Welche Einflüsse mischen sich im Tango?', 'Europäische, afrikanische und kreolische', ['Nur spanische', 'Nur indigene', 'Asiatische']],
              ['Wann starb Carlos Gardel?', '1935', ['1910', '1955', '1945']],
              ['Wer herrschte politisch bis 1916?', 'Die Oligarchie', ['Die Gewerkschaften', 'Das Militär', 'Die Kirche']],
              ['Wie gewann die Oligarchie Wahlen?', 'Durch Betrug', ['Durch faire Wahlen', 'Durch Losentscheid', 'Durch Volksabstimmungen']],
              ['Welche Gewerkschaften gab es?', 'Anarchistische und sozialistische', ['Nur katholische', 'Nur faschistische', 'Keine']],
              ['Wie reagierte der Staat auf Streiks?', 'Er unterdrückte sie hart', ['Er unterstützte sie', 'Er ignorierte sie', 'Er bezahlte die Streikenden']],
              ['Welches Jubiläum feierte Argentinien 1910?', 'Die Hundertjahrfeier der Mairevolution', ['Die Entdeckung Amerikas', 'Die Verfassung', 'Den Tod San Martíns']],
              ['Wann eröffnete die erste U-Bahn Lateinamerikas in Buenos Aires?', '1913', ['1890', '1950', '1930']],
              ['Wer schrieb „Martín Fierro“?', 'José Hernández', ['Jorge Luis Borges', 'Sarmiento', 'Julio Cortázar']],
              ['Worum geht es in „Martín Fierro“?', 'Um einen verfolgten Gaucho', ['Um einen Tango-Sänger', 'Um einen Präsidenten', 'Um einen Fußballer']],
              ['Wann erschien „Martín Fierro“?', '1872', ['1910', '1845', '1935']],
              ['Wann wurde Boca Juniors gegründet?', '1905', ['1901', '1930', '1880']],
              ['Wann wurde River Plate gegründet?', '1901', ['1905', '1920', '1880']],
            ],
            schwer: [
              ['Was gilt als Nationalepos Argentiniens?', '„Martín Fierro“', ['„Facundo“', '„Don Quijote“', '„Ficciones“']],
              ['Welche technische Neuerung verband die Pampa mit britischen Märkten?', 'Kühlschiffe für gefrorenes Fleisch', ['Brieftauben', 'Pipelines', 'Luftschiffe']],
              ['Woher stammt das Bandoneon ursprünglich?', 'Aus Deutschland', ['Aus Frankreich', 'Aus Uruguay', 'Aus Italien']],
              ['Welches Viertel gilt als Tango-Wiege?', 'La Boca', ['Recoleta', 'Belgrano', 'Puerto Madero']],
              ['Welcher Slang enthält viele italienische Wörter?', 'Lunfardo', ['Caló', 'Voseo', 'Quechua']],
              ['Welche Gruppe herrschte vor 1916 durch Wahlbetrug?', 'Die Oligarchie der Großgrundbesitzer', ['Die Gewerkschaften', 'Die Einwanderer', 'Die Militärjunta']],
              ['Welches Gebäude von 1908 steht für das reiche Buenos Aires?', 'Teatro Colón', ['Kathedrale von Córdoba', 'Obelisco', 'Kongress von 1810']],
              ['Welche Stadt hatte die erste U-Bahn Lateinamerikas?', 'Buenos Aires', ['Mexiko-Stadt', 'São Paulo', 'Santiago']],
              ['Welche politischen Richtungen prägten frühe Gewerkschaften?', 'Anarchismus und Sozialismus', ['Monarchismus und Liberalismus', 'Faschismus und Kommunismus', 'Peronismus']],
              ['Wann war die Blütezeit der Kornkammer?', '1880–1914', ['1810–1850', '1946–1955', '1976–1983']],
              ['Welcher Sänger ist Symbol des Tangos der 1920er/30er?', 'Carlos Gardel', ['Astor Piazzolla', 'Mercedes Sosa', 'Atahualpa Yupanqui']],
              ['Welche Folge hatte die Einwanderung für Buenos Aires um 1914?', 'Rund die Hälfte war im Ausland geboren', ['Es gab keine Ausländer', 'Es wurde italienisch regiert', 'Es schrumpfte']],
              ['Welches Land war der wichtigste Kunde argentinischen Fleisches?', 'Großbritannien', ['Frankreich', 'Deutschland', 'Spanien']],
              ['Welche Wohnform war für arme Einwanderer typisch?', 'Conventillos', ['Estancias', 'Villas de lujo', 'Iglus']],
              ['Welcher Verein wurde 1905 in La Boca gegründet?', 'Boca Juniors', ['River Plate', 'Independiente', 'Racing']],
              ['Welches Ereignis feierte Buenos Aires mit Prachtbauten 1910?', 'Hundert Jahre Mairevolution', ['Die Fußball-WM', 'Die Unabhängigkeit 1816', 'Den Sieg über Paraguay']],
              ['Wie hoch war die Einwanderung 1880–1930 etwa?', 'Rund sechs Millionen', ['Rund eine Million', 'Rund 20 Millionen', 'Rund 100.000']],
              ['Welches Symbol wurde durch „Martín Fierro“ zum Nationalbild?', 'Der Gaucho', ['Der Tango-Tänzer', 'Der Hafenarbeiter', 'Der Inka']],
              ['Welcher Typ von Instrument ist das Bandoneon?', 'Ein Handzuginstrument', ['Ein Saiteninstrument', 'Ein Schlaginstrument', 'Ein Blechblasinstrument']],
              ['Welche Bevölkerungsgruppe prägte Argentinien um 1900 am stärksten?', 'Italienische Einwanderer', ['Britische Siedler', 'Indigene Völker', 'Chinesische Händler']],
            ],
          },
        },
        {
          id: 'radikale-dekade',
          title: 'Wahlrecht, Radikale und Década Infame',
          date: '1912–1943',
          text: [
            '1912 führte das „Sáenz-Peña-Gesetz“ das allgemeine, geheime und verpflichtende Wahlrecht für Männer ein. Bei der ersten freien Wahl 1916 siegte Hipólito Yrigoyen von der „Radikalen Bürgerunion“ (UCR), die vor allem die Mittelschicht und die Kinder der Einwanderer vertrat.',
            'In Yrigoyens Amtszeit kam es zu harten Arbeitskonflikten: In der „Tragischen Woche“ im Januar 1919 schlugen Polizei und Militär einen Streik in Buenos Aires blutig nieder, und 1920–1922 wurden in Patagonien streikende Landarbeiter erschossen („Patagonia rebelde“). 1918 erkämpften Studenten in Córdoba die Universitätsreform mit Selbstverwaltung, die in ganz Lateinamerika Vorbild wurde.',
            'Im Ersten Weltkrieg blieb Argentinien neutral und verdiente gut. 1928 wurde Yrigoyen, inzwischen sehr alt, erneut gewählt. Als die Weltwirtschaftskrise 1929 die Exporte einbrechen ließ, stürzte General José Félix Uriburu ihn am 6. September 1930 – der erste von vielen Militärputschen im 20. Jahrhundert.',
            'Die 1930er-Jahre heißen „Década Infame“ („Schändliches Jahrzehnt“): Konservative regierten durch Wahlbetrug, und 1933 sicherte der Roca-Runciman-Vertrag Großbritannien Vorteile beim Fleischhandel. Korruptionsskandale erschütterten das Land. Zugleich wuchs die Industrie, und viele Menschen zogen vom Land in die Städte.',
            '1936 wurde der Obelisk von Buenos Aires zur 400-Jahr-Feier der ersten Stadtgründung errichtet. Im Zweiten Weltkrieg blieb Argentinien lange neutral. Am 4. Juni 1943 putschten nationalistische Offiziere der „Gruppe vereinigter Offiziere“ (GOU); einer von ihnen war Oberst Juan Domingo Perón.',
          ],
          quiz: {
            leicht: [
              ['Welches Gesetz brachte 1912 das geheime Wahlrecht?', 'Das Sáenz-Peña-Gesetz', ['Die Lei Áurea', 'Das Roca-Gesetz', 'Das Perón-Gesetz']],
              ['Für wen galt das Wahlrecht von 1912?', 'Für Männer', ['Für Frauen und Männer', 'Nur für Großgrundbesitzer', 'Nur für Einwanderer']],
              ['Welche drei Eigenschaften hatte das Wahlrecht?', 'Allgemein, geheim und verpflichtend', ['Öffentlich, freiwillig und teuer', 'Nur mündlich', 'Nur für Adlige']],
              ['Wer gewann 1916 die erste freie Wahl?', 'Hipólito Yrigoyen', ['Juan Perón', 'Julio Roca', 'Uriburu']],
              ['Welche Partei führte Yrigoyen?', 'Die Radikale Bürgerunion (UCR)', ['Die Peronisten', 'Die Sozialisten', 'Die Konservativen']],
              ['Wen vertrat die UCR vor allem?', 'Die Mittelschicht und Einwandererkinder', ['Die Großgrundbesitzer', 'Das Militär', 'Die Kirche']],
              ['Wie heißt der blutige Streik von 1919?', 'Tragische Woche', ['Década Infame', 'Cordobazo', 'Mairevolution']],
              ['Wo wurden 1920–1922 streikende Landarbeiter erschossen?', 'In Patagonien', ['In Buenos Aires', 'In Córdoba', 'In Mendoza']],
              ['Wo erkämpften Studenten 1918 eine Universitätsreform?', 'In Córdoba', ['In Buenos Aires', 'In La Plata', 'In Rosario']],
              ['Wie verhielt sich Argentinien im Ersten Weltkrieg?', 'Neutral', ['Es kämpfte für Deutschland', 'Es kämpfte für die Alliierten', 'Es wurde besetzt']],
              ['Wann wurde Yrigoyen erneut gewählt?', '1928', ['1922', '1930', '1916']],
              ['Wer stürzte Yrigoyen 1930?', 'General Uriburu', ['Perón', 'Roca', 'Alvear']],
              ['Was war der Putsch von 1930?', 'Der erste von vielen Militärputschen', ['Der einzige Putsch', 'Eine Revolution der Arbeiter', 'Eine Wahl']],
              ['Welche Krise ließ 1929 die Exporte einbrechen?', 'Die Weltwirtschaftskrise', ['Die Ölkrise', 'Die Schuldenkrise 2001', 'Der Erste Weltkrieg']],
              ['Wie heißen die 1930er-Jahre in Argentinien?', 'Década Infame', ['Goldene Jahre', 'Belle Époque', 'Proceso']],
              ['Was bedeutet „Década Infame“?', 'Schändliches Jahrzehnt', ['Goldenes Jahrzehnt', 'Verlorenes Jahrzehnt', 'Neues Jahrzehnt']],
              ['Wie regierten die Konservativen in den 1930ern?', 'Durch Wahlbetrug', ['Durch faire Wahlen', 'Als Monarchie', 'Durch Losentscheid']],
              ['Welches Wahrzeichen entstand 1936 in Buenos Aires?', 'Der Obelisk', ['Das Teatro Colón', 'Die Casa Rosada', 'Der Cabildo']],
              ['Wie verhielt sich Argentinien lange im Zweiten Weltkrieg?', 'Neutral', ['Es kämpfte für Japan', 'Es kämpfte von Anfang an für die Alliierten', 'Es wurde besetzt']],
              ['Welcher Oberst war am Putsch 1943 beteiligt?', 'Juan Domingo Perón', ['Uriburu', 'Videla', 'Galtieri']],
            ],
            mittel: [
              ['Wann wurde das Sáenz-Peña-Gesetz erlassen?', '1912', ['1916', '1853', '1930']],
              ['Wann war die erste freie Wahl?', '1916', ['1912', '1880', '1930']],
              ['Wofür steht UCR?', 'Radikale Bürgerunion', ['Union der Arbeiter', 'Republikanische Union', 'Vereinigte Kirchen']],
              ['Wann war die Tragische Woche?', 'Im Januar 1919', ['Im Mai 1810', 'Im Juni 1943', 'Im Oktober 1945']],
              ['Wer schlug den Streik 1919 nieder?', 'Polizei und Militär', ['Die Gewerkschaften', 'Die Kirche', 'Die Briten']],
              ['Wie heißen die Ereignisse in Patagonien 1920–1922?', 'Patagonia rebelde', ['Conquista del Desierto', 'Tragische Woche', 'Cordobazo']],
              ['Was erreichten die Studenten 1918?', 'Selbstverwaltung der Universitäten', ['Kostenlose Autos', 'Das Frauenwahlrecht', 'Die Abschaffung der Universitäten']],
              ['Wofür wurde die Universitätsreform von Córdoba?', 'Vorbild in ganz Lateinamerika', ['Ein Misserfolg', 'Ein Verbot', 'Eine Kirchenreform']],
              ['Wie ging es Argentinien wirtschaftlich im Ersten Weltkrieg?', 'Es verdiente gut', ['Es verarmte', 'Es wurde blockiert', 'Es exportierte nichts']],
              ['Wie war Yrigoyen 1928?', 'Sehr alt', ['Sehr jung', 'Ein General', 'Ein Einwanderer aus Italien']],
              ['An welchem Tag putschte Uriburu?', 'Am 6. September 1930', ['Am 25. Mai 1930', 'Am 4. Juni 1943', 'Am 17. Oktober 1945']],
              ['Welcher Vertrag von 1933 betraf den Fleischhandel?', 'Der Roca-Runciman-Vertrag', ['Der Vertrag von Versailles', 'Der Vertrag von Tordesillas', 'Der Pacto de Olivos']],
              ['Wem sicherte der Vertrag Vorteile?', 'Großbritannien', ['Den USA', 'Deutschland', 'Brasilien']],
              ['Was erschütterte das Land in der Década Infame?', 'Korruptionsskandale', ['Ein Krieg mit Chile', 'Ein Vulkanausbruch', 'Die Rückkehr der Monarchie']],
              ['Was wuchs in den 1930er-Jahren?', 'Die Industrie', ['Die Zahl der Gauchos', 'Die Monarchie', 'Der Wald']],
              ['Wohin zogen viele Menschen in den 1930ern?', 'Vom Land in die Städte', ['Von den Städten aufs Land', 'Nach Europa', 'Nach Patagonien']],
              ['Woran erinnert der Obelisk?', 'An 400 Jahre erste Stadtgründung', ['An die Unabhängigkeit', 'An Perón', 'An den Falklandkrieg']],
              ['Wann putschten die Offiziere 1943?', 'Am 4. Juni 1943', ['Am 6. September 1943', 'Am 17. Oktober 1943', 'Am 25. Mai 1943']],
              ['Wie hieß die Offiziersgruppe von 1943?', 'GOU', ['UCR', 'PJ', 'CGT']],
              ['Welche politische Richtung hatten die Putschisten 1943?', 'Nationalistisch', ['Sozialistisch', 'Liberal', 'Monarchistisch']],
            ],
            schwer: [
              ['Wofür steht GOU?', 'Gruppe vereinigter Offiziere', ['Generalunion der Arbeiter', 'Große Oligarchie-Union', 'Gesellschaft für Unabhängigkeit']],
              ['Welcher Präsident war der erste frei gewählte nach dem Gesetz von 1912?', 'Yrigoyen', ['Sáenz Peña', 'Alvear', 'Justo']],
              ['Welcher General führte den ersten Militärputsch des 20. Jahrhunderts?', 'José Félix Uriburu', ['Agustín Justo', 'Pedro Ramírez', 'Perón']],
              ['Was war das Ziel der Reform von 1918?', 'Selbstverwaltung der Universitäten', ['Abschaffung des Militärs', 'Verbot von Streiks', 'Kirchliche Kontrolle der Schulen']],
              ['Welcher Vertrag gilt als Symbol der Abhängigkeit von Großbritannien?', 'Roca-Runciman-Vertrag', ['Sáenz-Peña-Gesetz', 'Pacto de Olivos', 'Vertrag von Tordesillas']],
              ['Welche Arbeiter wurden in der Patagonia rebelde erschossen?', 'Streikende Landarbeiter', ['Studenten', 'Hafenarbeiter in Buenos Aires', 'Soldaten']],
              ['Welches Ereignis im Januar 1919 endete blutig?', 'Die Tragische Woche', ['Der Putsch von Uriburu', 'Die Universitätsreform', 'Die Wahl von 1916']],
              ['Welche Wirkung hatte die Weltwirtschaftskrise auf Yrigoyen?', 'Sie trug zu seinem Sturz bei', ['Sie stärkte ihn', 'Sie machte ihn reich', 'Sie hatte keine']],
              ['Welche Merkmale hatte die Wahl in der Década Infame?', 'Wahlbetrug durch Konservative', ['Faire Wahlen mit Frauenwahlrecht', 'Keine Wahlen', 'Elektronische Wahlen']],
              ['Welche gesellschaftliche Bewegung prägte die 1930er?', 'Landflucht in die Städte', ['Auswanderung nach Europa', 'Rückkehr zur Landwirtschaft', 'Bau neuer Hauptstädte']],
              ['Welcher Oberst begann 1943 seinen Aufstieg?', 'Perón', ['Videla', 'Onganía', 'Uriburu']],
              ['Welches Jahr ist mit dem ersten Militärputsch verbunden?', '1930', ['1943', '1955', '1916']],
              ['Welches Wahrzeichen erinnert an 1536?', 'Der Obelisk', ['Das Teatro Colón', 'Die Casa Rosada', 'Die Kathedrale']],
              ['Welche Wählergruppe stieg mit der UCR auf?', 'Die Mittelschicht', ['Die Oligarchie', 'Die Indigenen', 'Die Briten']],
              ['Wann wurde Yrigoyen zum zweiten Mal gewählt?', '1928', ['1916', '1922', '1930']],
              ['Wie lange war Argentinien im Zweiten Weltkrieg neutral?', 'Lange', ['Gar nicht', 'Nur einen Tag', 'Es war nie im Krieg']],
              ['Welches Jahr markiert den Beginn der Década Infame?', '1930', ['1920', '1943', '1916']],
              ['Welcher Putsch ebnete Perón den Weg?', 'Der Putsch vom 4. Juni 1943', ['Der Putsch von 1930', 'Der Putsch von 1955', 'Der Putsch von 1976']],
              ['Welche Universität war Ausgangspunkt der Reform von 1918?', 'Córdoba', ['Buenos Aires', 'La Plata', 'Tucumán']],
              ['Welches Gesetz machte das Wählen zur Pflicht?', 'Das Sáenz-Peña-Gesetz', ['Das Roca-Gesetz', 'Die Verfassung von 1853', 'Das Perón-Gesetz von 1947']],
            ],
          },
        },
      ],
    },
    {
      id: 'peron',
      title: 'Perón und Evita',
      date: '1943–1955',
      text: [
        'Juan Domingo Perón stieg als Arbeitsminister zum Idol der Arbeiter auf und regierte von 1946 bis 1955 als Präsident. Mit seiner Frau Eva „Evita“ prägte er den Peronismus, der Argentiniens Politik bis heute bestimmt.',
      ],
      subtopics: [
        {
          id: 'peron-aufstieg',
          title: 'Perón, der 17. Oktober und Evita',
          date: '1943–1952',
          text: [
            'Nach dem Putsch 1943 wurde Oberst Perón Leiter des Arbeitsamtes, dann Kriegsminister und Vizepräsident. Er führte Mindestlöhne, bezahlten Urlaub, Renten und Arbeitsgerichte ein und stärkte die Gewerkschaften. So wurde er zum Idol der Arbeiter, der „Descamisados“ („Hemdlosen“). 1944 lernte er bei einer Spendengala für die Opfer eines Erdbebens in San Juan die Schauspielerin Eva Duarte kennen.',
            'Im Oktober 1945 setzten rivalisierende Offiziere Perón ab und verhafteten ihn. Am 17. Oktober 1945 strömten Hunderttausende Arbeiter auf die Plaza de Mayo vor dem Präsidentenpalast „Casa Rosada“ und forderten seine Freilassung. Abends sprach Perón befreit vom Balkon. Der 17. Oktober gilt als Geburtstag des Peronismus und wird von Peronisten als „Tag der Loyalität“ gefeiert; kurz darauf heirateten Perón und Eva.',
            'Im Februar 1946 gewann Perón die Präsidentenwahl. Seine Lehre hieß „Justicialismo“ und versprach „soziale Gerechtigkeit, wirtschaftliche Unabhängigkeit und politische Souveränität“ – ein „dritter Weg“ zwischen Kapitalismus und Kommunismus. Er verstaatlichte die Eisenbahnen, die Briten gehörten, und zahlte die Auslandsschulden zurück. Seine Partei hieß später „Partido Justicialista“.',
            'Eva Perón, „Evita“, kam aus armen Verhältnissen. Mit ihrer Stiftung baute sie Schulen, Krankenhäuser und Heime und verteilte Hilfe an Arme. Sie setzte 1947 das Frauenwahlrecht durch; 1951 wählten Frauen erstmals. Die Armen verehrten sie fast wie eine Heilige, die Oberschicht hasste sie.',
            '1951 wollte Evita Vizepräsidentin werden, verzichtete aber auf Druck des Militärs. Sie war schwer an Krebs erkrankt und starb am 26. Juli 1952 mit nur 33 Jahren. Millionen trauerten. Ihr Leben wurde später durch das Musical „Evita“ mit dem Lied „Don’t Cry for Me Argentina“ weltbekannt.',
          ],
          quiz: {
            leicht: [
              ['Welches Amt übernahm Perón nach 1943 zuerst?', 'Leiter des Arbeitsamtes', ['Präsident', 'Papst', 'Bürgermeister']],
              ['Was führte Perón für Arbeiter ein?', 'Mindestlöhne und bezahlten Urlaub', ['Längere Arbeitszeiten', 'Kinderarbeit', 'Höhere Steuern für Arbeiter']],
              ['Wie nannte man Peróns Anhänger unter den Arbeitern?', 'Descamisados', ['Gauchos', 'Montoneros', 'Unitarier']],
              ['Was bedeutet „Descamisados“?', 'Hemdlose', ['Barfüßige', 'Hutlose', 'Arbeitslose']],
              ['Wen lernte Perón 1944 kennen?', 'Eva Duarte', ['Isabel Martínez', 'Cristina Fernández', 'Mercedes Sosa']],
              ['Was war Eva Duarte von Beruf?', 'Schauspielerin', ['Ärztin', 'Lehrerin', 'Soldatin']],
              ['Was geschah im Oktober 1945 mit Perón?', 'Er wurde abgesetzt und verhaftet', ['Er wurde Präsident', 'Er floh nach Spanien', 'Er starb']],
              ['Wohin strömten am 17. Oktober 1945 die Arbeiter?', 'Auf die Plaza de Mayo', ['In das Stadion', 'Nach Córdoba', 'Zum Hafen']],
              ['Wie heißt der Präsidentenpalast in Buenos Aires?', 'Casa Rosada', ['Casa Blanca', 'Palacio Real', 'Catete']],
              ['Was gilt als Geburtstag des Peronismus?', 'Der 17. Oktober 1945', ['Der 25. Mai 1810', 'Der 9. Juli 1816', 'Der 4. Juni 1943']],
              ['Wann gewann Perón die Präsidentenwahl?', '1946', ['1943', '1955', '1973']],
              ['Wie hieß Peróns Lehre?', 'Justicialismo', ['Positivismo', 'Radicalismo', 'Liberalismo']],
              ['Welchen Weg wollte der Peronismus gehen?', 'Einen dritten Weg zwischen Kapitalismus und Kommunismus', ['Reinen Kapitalismus', 'Reinen Kommunismus', 'Die Monarchie']],
              ['Was verstaatlichte Perón?', 'Die Eisenbahnen', ['Die Kirchen', 'Die Fußballvereine', 'Die Tango-Bars']],
              ['Wie wird Eva Perón genannt?', 'Evita', ['Isabelita', 'La Reina', 'Cristina']],
              ['Aus welchen Verhältnissen kam Evita?', 'Aus armen', ['Aus dem Adel', 'Aus einer Militärfamilie', 'Aus einer Kaffeebaronfamilie']],
              ['Welches Recht setzte Evita 1947 durch?', 'Das Frauenwahlrecht', ['Das Recht auf Waffen', 'Die Pressefreiheit', 'Das Streikverbot']],
              ['Woran starb Evita?', 'An Krebs', ['Bei einem Unfall', 'Bei einem Attentat', 'An Altersschwäche']],
              ['Wie alt wurde Evita?', '33 Jahre', ['53 Jahre', '23 Jahre', '73 Jahre']],
              ['Welches Lied aus dem Musical „Evita“ ist weltbekannt?', '„Don’t Cry for Me Argentina“', ['„La Cumparsita“', '„Despacito“', '„Imagine“']],
            ],
            mittel: [
              ['Welche Ämter hatte Perón außer dem Arbeitsamt?', 'Kriegsminister und Vizepräsident', ['Papst und Bischof', 'Gouverneur von Córdoba', 'Botschafter in Rom']],
              ['Was führte Perón außer Löhnen und Urlaub ein?', 'Renten und Arbeitsgerichte', ['Die Wehrpflicht für Frauen', 'Die Kirchensteuer', 'Die Monarchie']],
              ['Wen stärkte Perón?', 'Die Gewerkschaften', ['Die Oligarchie', 'Die Briten', 'Die Großgrundbesitzer']],
              ['Bei welchem Anlass lernten sich Perón und Eva kennen?', 'Bei einer Spendengala für Erdbebenopfer', ['Bei einem Tangoball', 'Bei einem Fußballspiel', 'Bei einer Militärparade']],
              ['Wo war das Erdbeben von 1944?', 'In San Juan', ['In Mendoza', 'In Buenos Aires', 'In Salta']],
              ['Wer setzte Perón 1945 ab?', 'Rivalisierende Offiziere', ['Die Arbeiter', 'Die USA', 'Evita']],
              ['Wie viele Arbeiter kamen am 17. Oktober?', 'Hunderttausende', ['Ein paar Dutzend', 'Hundert', 'Zehn Millionen']],
              ['Was tat Perón am Abend des 17. Oktober?', 'Er sprach vom Balkon', ['Er floh ins Exil', 'Er trat zurück', 'Er heiratete']],
              ['In welchem Monat 1946 gewann Perón die Wahl?', 'Im Februar', ['Im Oktober', 'Im Juni', 'Im Dezember']],
              ['Was versprach der Justicialismo?', 'Soziale Gerechtigkeit, wirtschaftliche Unabhängigkeit, politische Souveränität', ['Freiheit, Gleichheit, Brüderlichkeit', 'Ordnung und Fortschritt', 'Land und Freiheit']],
              ['Wem gehörten die Eisenbahnen vor der Verstaatlichung?', 'Den Briten', ['Den Spaniern', 'Den USA', 'Der Kirche']],
              ['Was tat Perón mit den Auslandsschulden?', 'Er zahlte sie zurück', ['Er verdoppelte sie', 'Er ignorierte sie', 'Er verkaufte das Land']],
              ['Wie hieß Peróns Partei später?', 'Partido Justicialista', ['UCR', 'Partido Socialista', 'PRO']],
              ['Was baute Evitas Stiftung?', 'Schulen, Krankenhäuser und Heime', ['Kasernen', 'Gefängnisse', 'Pferderennbahnen']],
              ['Wann wählten Frauen erstmals?', '1951', ['1947', '1916', '1912']],
              ['Wie sah die Oberschicht Evita?', 'Sie hasste sie', ['Sie verehrte sie', 'Sie kannte sie nicht', 'Sie wählte sie']],
              ['Welches Amt wollte Evita 1951?', 'Vizepräsidentin', ['Präsidentin', 'Ministerin', 'Bürgermeisterin']],
              ['Warum verzichtete Evita auf die Kandidatur?', 'Auf Druck des Militärs', ['Weil sie Präsidentin werden wollte', 'Weil sie nach Europa zog', 'Weil Perón verlor']],
              ['Wann starb Evita?', 'Am 26. Juli 1952', ['Am 17. Oktober 1952', 'Am 1. Juli 1974', 'Am 16. September 1955']],
              ['Wie reagierten die Menschen auf Evitas Tod?', 'Millionen trauerten', ['Niemand bemerkte es', 'Man feierte', 'Es gab einen Krieg']],
            ],
            schwer: [
              ['Welche Formel beschreibt die drei Ziele des Justicialismo?', 'Soziale Gerechtigkeit, wirtschaftliche Unabhängigkeit, politische Souveränität', ['Gott, Vaterland, Familie', 'Arbeit, Familie, Vaterland', 'Freiheit, Gleichheit, Brüderlichkeit']],
              ['Welcher Platz ist Symbol des 17. Oktober 1945?', 'Plaza de Mayo', ['Plaza San Martín', 'Plaza Italia', 'Plaza de Armas']],
              ['Welche Naturkatastrophe führte zum Treffen von Perón und Eva?', 'Das Erdbeben von San Juan 1944', ['Eine Flut in Buenos Aires', 'Ein Vulkanausbruch', 'Eine Dürre in der Pampa']],
              ['Welche Wirtschaftsmaßnahme richtete sich gegen britische Interessen?', 'Die Verstaatlichung der Eisenbahnen', ['Die Senkung der Zölle', 'Der Roca-Runciman-Vertrag', 'Der Verkauf von Land an Briten']],
              ['Welche Gruppe nannte Perón „Descamisados“?', 'Die Arbeiter', ['Die Soldaten', 'Die Großgrundbesitzer', 'Die Studenten']],
              ['Welches politische Recht ist eng mit Evita verbunden?', 'Das Frauenwahlrecht', ['Die Pressefreiheit', 'Das Recht auf Waffen', 'Die Wehrpflicht']],
              ['Zwischen welchen Systemen sah sich der Peronismus?', 'Kapitalismus und Kommunismus', ['Monarchie und Republik', 'Faschismus und Monarchie', 'Liberalismus und Anarchie']],
              ['Wann heirateten Perón und Eva?', 'Kurz nach dem 17. Oktober 1945', ['1930', '1952', '1973']],
              ['Welche Funktion hatte Evitas Stiftung?', 'Sozialhilfe für Arme', ['Militärausbildung', 'Kunstförderung für Reiche', 'Fußballvereine']],
              ['Wann setzte Evita das Frauenwahlrecht durch?', '1947', ['1951', '1912', '1946']],
              ['Welche Rolle wollte Evita 1951 übernehmen?', 'Vizepräsidentin', ['Präsidentin des Senats', 'Gouverneurin', 'Botschafterin']],
              ['Welche Institution verhinderte Evitas Kandidatur?', 'Das Militär', ['Die Kirche', 'Die Gewerkschaften', 'Die Briten']],
              ['Welches Musical machte Evita weltbekannt?', '„Evita“', ['„Les Misérables“', '„Cats“', '„West Side Story“']],
              ['Welches Gebäude ist mit Peróns Balkonrede verbunden?', 'Die Casa Rosada', ['Das Teatro Colón', 'Der Kongress', 'Der Cabildo']],
              ['Welches Ministerium machte Perón bei Arbeitern populär?', 'Das Arbeitsamt bzw. Arbeitsressort', ['Das Außenministerium', 'Das Finanzministerium', 'Das Kirchenministerium']],
              ['Welcher Tag ist im Peronismus der „Tag der Loyalität“?', 'Der 17. Oktober', ['Der 26. Juli', 'Der 1. Mai', 'Der 4. Juni']],
              ['Mit welchem Alter starb Evita?', '33', ['43', '28', '50']],
              ['Welche Gruppe verehrte Evita fast wie eine Heilige?', 'Die Armen', ['Die Oberschicht', 'Das Militär', 'Die Briten']],
              ['Welche Haltung hatte Perón zu Auslandsschulden?', 'Er zahlte sie zurück', ['Er nahm neue auf', 'Er erklärte den Bankrott', 'Er ignorierte sie']],
              ['Welche Partei ist heute Erbe des Peronismus?', 'Partido Justicialista', ['UCR', 'La Libertad Avanza', 'PRO']],
            ],
          },
        },
        {
          id: 'peron-sturz',
          title: 'Krise und Sturz Peróns',
          date: '1949–1955',
          text: [
            'Ab etwa 1949 geriet die Wirtschaft in Schwierigkeiten: Die Exportpreise sanken, Dürren trafen die Landwirtschaft, und die Inflation stieg. Peróns Regierung wurde autoritärer. 1949 ließ er die Verfassung ändern, damit er wiedergewählt werden konnte; 1951 wurde er mit großer Mehrheit bestätigt.',
            'Die Presse wurde kontrolliert, die unabhängige Zeitung „La Prensa“ 1951 enteignet und den Gewerkschaften übergeben. Opposition, Universitäten und Teile des Militärs wurden unterdrückt. Schulbücher priesen Perón und Evita; Kinder lernten mit Fibeln, in denen „Evita“ zu den ersten Wörtern gehörte.',
            'Nach dem Zweiten Weltkrieg nahm Argentinien auch Tausende Nationalsozialisten und Kriegsverbrecher auf, etwa Adolf Eichmann und Josef Mengele, die über sogenannte „Rattenlinien“ entkamen. Eichmann wurde 1960 vom israelischen Geheimdienst in Buenos Aires entführt und in Israel verurteilt.',
            '1954 geriet Perón in Streit mit der katholischen Kirche: Er legalisierte die Scheidung und schaffte den Religionsunterricht ab. Bei einem Putschversuch im Juni 1955 bombardierten Marineflugzeuge die Plaza de Mayo; über 300 Menschen starben. In der Nacht danach zündeten Peronisten Kirchen an.',
            'Im September 1955 stürzte die „Revolución Libertadora“ („Befreiende Revolution“) Perón. Er floh auf einem Kanonenboot nach Paraguay und ging später nach Spanien unter Franco ins Exil. Der Peronismus wurde verboten, sogar sein Name durfte nicht genannt werden. Evitas einbalsamierter Leichnam wurde heimlich nach Italien gebracht und erst 1971 an Perón zurückgegeben.',
          ],
          quiz: {
            leicht: [
              ['Ab wann geriet die Wirtschaft unter Perón in Schwierigkeiten?', 'Ab etwa 1949', ['Ab 1930', 'Ab 1943', 'Ab 1960']],
              ['Was stieg in der Krise?', 'Die Inflation', ['Die Exportpreise', 'Die Ernten', 'Die Pressefreiheit']],
              ['Wie wurde Peróns Regierung?', 'Autoritärer', ['Demokratischer', 'Schwächer und freier', 'Monarchistisch']],
              ['Warum änderte Perón 1949 die Verfassung?', 'Um wiedergewählt werden zu können', ['Um zurückzutreten', 'Um einen König einzusetzen', 'Um die Wahlen abzuschaffen']],
              ['Wann wurde Perón wiedergewählt?', '1951', ['1949', '1955', '1946']],
              ['Welche Zeitung wurde enteignet?', '„La Prensa“', ['„La Nación“', '„Clarín“', '„El País“']],
              ['Wer wurde unterdrückt?', 'Opposition und Universitäten', ['Nur Ausländer', 'Niemand', 'Nur die Gewerkschaften']],
              ['Wen priesen die Schulbücher?', 'Perón und Evita', ['Die Gewerkschaftsgegner', 'Die Briten', 'Den Papst']],
              ['Welche Menschen nahm Argentinien nach 1945 auf?', 'Auch Nationalsozialisten und Kriegsverbrecher', ['Nur Flüchtlinge aus Asien', 'Niemanden', 'Nur Briten']],
              ['Welcher NS-Verbrecher lebte in Buenos Aires?', 'Adolf Eichmann', ['Hermann Göring', 'Heinrich Himmler', 'Rudolf Heß']],
              ['Wer entführte Eichmann 1960?', 'Der israelische Geheimdienst', ['Die CIA', 'Die argentinische Polizei', 'Der KGB']],
              ['Mit wem geriet Perón 1954 in Streit?', 'Mit der katholischen Kirche', ['Mit den Gewerkschaften', 'Mit Brasilien', 'Mit Uruguay']],
              ['Was legalisierte Perón 1954?', 'Die Scheidung', ['Die Sklaverei', 'Den Drogenhandel', 'Die Monarchie']],
              ['Was wurde 1955 bombardiert?', 'Die Plaza de Mayo', ['Das Teatro Colón', 'Die Falklandinseln', 'Córdoba']],
              ['Wer bombardierte die Plaza de Mayo?', 'Marineflugzeuge', ['Britische Bomber', 'Die Luftwaffe Chiles', 'Peronisten']],
              ['Was zündeten Peronisten danach an?', 'Kirchen', ['Fabriken', 'Schiffe', 'Banken']],
              ['Wie hieß der Putsch, der Perón 1955 stürzte?', 'Revolución Libertadora', ['Mairevolution', 'Proceso', 'Década Infame']],
              ['Wohin floh Perón zuerst?', 'Nach Paraguay', ['Nach Brasilien', 'Nach Chile', 'Nach Uruguay']],
              ['In welchem Land lebte Perón später im Exil?', 'In Spanien', ['In Italien', 'In Deutschland', 'In den USA']],
              ['Was geschah mit dem Peronismus nach 1955?', 'Er wurde verboten', ['Er regierte weiter', 'Er wurde Staatsreligion', 'Er wurde vergessen']],
            ],
            mittel: [
              ['Was traf die Landwirtschaft in der Krise?', 'Dürren', ['Vulkanausbrüche', 'Erdbeben in der Pampa', 'Schnee']],
              ['Was sank in der Krise?', 'Die Exportpreise', ['Die Inflation', 'Die Steuern', 'Die Zahl der Arbeiter']],
              ['Mit welcher Mehrheit wurde Perón 1951 bestätigt?', 'Mit großer Mehrheit', ['Knapp', 'Er verlor', 'Ohne Gegenkandidat']],
              ['Wann wurde „La Prensa“ enteignet?', '1951', ['1949', '1955', '1946']],
              ['Wem wurde „La Prensa“ übergeben?', 'Den Gewerkschaften', ['Der Kirche', 'Dem Militär', 'Evita']],
              ['Welches Wort gehörte zu den ersten in Schulfibeln?', '„Evita“', ['„Inka“', '„Fútbol“', '„Tango“']],
              ['Welcher KZ-Arzt floh nach Argentinien?', 'Josef Mengele', ['Rudolf Höß', 'Karl Brandt', 'Klaus Barbie']],
              ['Wie hießen die Fluchtwege der Nationalsozialisten?', 'Rattenlinien', ['Seidenstraßen', 'Panamericana', 'Eisenbahnlinien']],
              ['Wo wurde Eichmann verurteilt?', 'In Israel', ['In Argentinien', 'In Deutschland', 'In den USA']],
              ['Was schaffte Perón 1954 ab?', 'Den Religionsunterricht', ['Die Schulen', 'Den Fußball', 'Das Militär']],
              ['Wann bombardierten Marineflugzeuge die Plaza de Mayo?', 'Im Juni 1955', ['Im Oktober 1945', 'Im September 1955', 'Im April 1982']],
              ['Wie viele Menschen starben beim Bombardement?', 'Über 300', ['Rund 3', 'Über 30.000', 'Keiner']],
              ['Wann stürzte die Revolución Libertadora Perón?', 'Im September 1955', ['Im Juni 1955', 'Im Juli 1952', 'Im März 1976']],
              ['Was bedeutet „Revolución Libertadora“?', 'Befreiende Revolution', ['Mairevolution', 'Nationale Revolution', 'Rote Revolution']],
              ['Womit floh Perón nach Paraguay?', 'Auf einem Kanonenboot', ['Im Flugzeug', 'Zu Pferd', 'Mit dem Zug']],
              ['Wer regierte Spanien während Peróns Exil?', 'Franco', ['Juan Carlos', 'Primo de Rivera', 'Alfons XIII.']],
              ['Was durfte nach 1955 nicht genannt werden?', 'Peróns Name', ['San Martíns Name', 'Der Name Argentiniens', 'Der Name des Papstes']],
              ['Wohin wurde Evitas Leichnam gebracht?', 'Heimlich nach Italien', ['Nach Spanien', 'Nach Paraguay', 'In die USA']],
              ['Wann wurde Evitas Leichnam zurückgegeben?', '1971', ['1955', '1983', '1952']],
              ['In welchem Zustand war Evitas Leichnam?', 'Einbalsamiert', ['Verbrannt', 'Verschollen bis heute', 'In einer Pyramide']],
            ],
            schwer: [
              ['Wann wurde Eichmann aus Buenos Aires entführt?', '1960', ['1945', '1955', '1975']],
              ['Welche Verfassungsänderung ließ Perón 1949 durchführen?', 'Die Erlaubnis zur Wiederwahl', ['Die Abschaffung des Präsidentenamts', 'Die Einführung der Monarchie', 'Das Frauenwahlrecht']],
              ['Welche Institution verlor Peróns Unterstützung 1954?', 'Die katholische Kirche', ['Die Gewerkschaften', 'Die Partei', 'Die Arbeiter']],
              ['Welcher Angriff im Juni 1955 forderte über 300 Tote?', 'Das Bombardement der Plaza de Mayo', ['Der Sturm auf die Casa Rosada', 'Der Anschlag auf die AMIA', 'Der Falklandkrieg']],
              ['Welche zwei Gesetze verärgerten 1954 die Kirche?', 'Scheidung und Abschaffung des Religionsunterrichts', ['Frauenwahlrecht und Mindestlohn', 'Verstaatlichung und Zölle', 'Pressefreiheit und Streikrecht']],
              ['Welcher Diktator gewährte Perón Exil?', 'Franco', ['Pinochet', 'Salazar', 'Mussolini']],
              ['Welcher Geheimdienst fasste Eichmann?', 'Der israelische', ['Der amerikanische', 'Der britische', 'Der deutsche']],
              ['Wie lange war Evitas Leichnam verschollen bzw. im Ausland?', 'Von 1955 bis 1971', ['Von 1952 bis 1955', 'Bis heute', 'Von 1976 bis 1983']],
              ['Welche Zeitung wurde Symbol der Pressekontrolle unter Perón?', '„La Prensa“', ['„La Nación“', '„Clarín“', '„Crítica“']],
              ['Welche Fluchtroute nutzten NS-Verbrecher?', 'Rattenlinien', ['Die Burma-Straße', 'Die Ho-Chi-Minh-Pfade', 'Die Route 40']],
              ['Welche Waffengattung führte den Putschversuch im Juni 1955 an?', 'Die Marine', ['Die Gendarmerie', 'Die Polizei', 'Die Gewerkschaften']],
              ['Wofür steht das Verbot nach 1955?', 'Den Peronismus aus der Politik zu tilgen', ['Den Tango zu verbieten', 'Die Kirche zu schließen', 'Den Fußball zu verbieten']],
              ['Welches Land war Peróns erstes Fluchtziel?', 'Paraguay', ['Spanien', 'Venezuela', 'Panama']],
              ['Welche wirtschaftlichen Probleme begannen um 1949?', 'Sinkende Exportpreise, Dürren und Inflation', ['Ölboom und Vollbeschäftigung', 'Goldfund und Reichtum', 'Industrieboom ohne Inflation']],
              ['Was zeigte die Propaganda in Schulbüchern?', 'Personenkult um Perón und Evita', ['Kritik an Perón', 'Nur San Martín', 'Kirchliche Lehren']],
              ['Welcher KZ-Arzt entkam der Justiz in Südamerika?', 'Josef Mengele', ['Adolf Eichmann', 'Hermann Göring', 'Rudolf Heß']],
              ['Welche Reaktion folgte in der Nacht nach dem Bombardement?', 'Peronisten zündeten Kirchen an', ['Perón trat zurück', 'Die Armee ergab sich', 'Es blieb ruhig']],
              ['Welches Jahr beendete Peróns erste Herrschaft?', '1955', ['1952', '1949', '1946']],
              ['Wann wurde Perón zum zweiten Mal gewählt?', '1951', ['1946', '1955', '1973']],
              ['In welches Land brachte man Evitas Leichnam heimlich?', 'Italien', ['Spanien', 'Frankreich', 'Deutschland']],
            ],
          },
        },
      ],
    },
  ],
};
