import type { Epoch, HistEvent } from '../types';
import { DIKTATUR } from './e4-diktatur-event';

const DEMOKRATIE: HistEvent = {
  id: 'demokratie-ar',
  title: 'Demokratie, Krisen und Neuanfänge',
  date: 'seit 1983',
  text: [
    'Seit 1983 ist Argentinien eine Demokratie. Es arbeitete die Verbrechen der Diktatur auf wie kaum ein anderes Land, erlebte aber immer wieder schwere Wirtschaftskrisen – von der Hyperinflation 1989 über den Staatsbankrott 2001 bis zur Inflation der 2020er-Jahre.',
  ],
  subtopics: [
    {
      id: 'alfonsin-menem',
      title: 'Alfonsín, Menem und die Dollar-Bindung',
      date: '1983–1999',
      text: [
        'Raúl Alfonsín von der UCR wurde am 10. Dezember 1983 Präsident; dieser Tag – zugleich internationaler Tag der Menschenrechte – ist heute Tag der Demokratie. Eine Kommission unter dem Schriftsteller Ernesto Sabato dokumentierte die Verbrechen der Diktatur im Bericht „Nunca más“ („Nie wieder“). 1985 wurden im „Prozess gegen die Juntas“ Videla und Massera zu lebenslanger Haft verurteilt – ein Gericht eines demokratischen Landes verurteilte damit erstmals in Lateinamerika eine eigene Militärjunta.',
        'Unter dem Druck aufständischer Offiziere, der „Carapintadas“ („Bemalten Gesichter“), erließ Alfonsín 1986/87 Gesetze, die weitere Prozesse stoppten („Schlusspunkt“ und „Befehlsnotstand“) und später „Straflosigkeitsgesetze“ genannt wurden. 1986 wurde Argentinien in Mexiko mit Diego Maradona Fußballweltmeister; im Viertelfinale gegen England erzielte er das Tor mit der „Hand Gottes“ und das „Tor des Jahrhunderts“.',
        '1989 stieg die Inflation auf über 3.000 Prozent im Jahr; Supermärkte wurden geplündert, und Alfonsín übergab das Amt vorzeitig an den gewählten Peronisten Carlos Menem. Menem begnadigte 1989/90 die verurteilten Junta-Generäle und Guerillaführer, was viele empörte.',
        'Mit Wirtschaftsminister Domingo Cavallo führte Menem 1991 die „Convertibilidad“ ein: Ein Peso war gesetzlich einen US-Dollar wert. Die Inflation verschwand. Menem privatisierte Staatsbetriebe wie die Telefongesellschaft, die Fluggesellschaft und den Ölkonzern YPF. Die Wirtschaft wuchs zunächst, aber Arbeitslosigkeit und Schulden stiegen.',
        '1992 und 1994 erschütterten Bombenanschläge Buenos Aires: Zuerst auf die israelische Botschaft, dann auf das jüdische Gemeindezentrum AMIA, wobei 85 Menschen starben – der schwerste Terroranschlag der Landesgeschichte. Die Justiz macht den Iran und die Hisbollah verantwortlich. 1994 wurde die Verfassung reformiert, sodass Menem 1995 wiedergewählt werden konnte.',
      ],
      quiz: {
        leicht: [
          ['Wer wurde 1983 Präsident?', 'Raúl Alfonsín', ['Carlos Menem', 'Néstor Kirchner', 'Galtieri']],
          ['Welcher Partei gehörte Alfonsín an?', 'UCR', ['Peronisten', 'PRO', 'Kommunisten']],
          ['Welcher Tag ist Tag der Demokratie?', 'Der 10. Dezember', ['Der 24. März', 'Der 2. April', 'Der 25. Mai']],
          ['Wie heißt der Bericht über die Verbrechen der Diktatur?', '„Nunca más“', ['„Facundo“', '„Martín Fierro“', '„Proceso“']],
          ['Was bedeutet „Nunca más“?', 'Nie wieder', ['Immer weiter', 'Noch einmal', 'Für immer']],
          ['Welcher Schriftsteller leitete die Kommission?', 'Ernesto Sabato', ['Jorge Luis Borges', 'Julio Cortázar', 'José Hernández']],
          ['Wann fand der Prozess gegen die Juntas statt?', '1985', ['1983', '1990', '2005']],
          ['Wozu wurde Videla 1985 verurteilt?', 'Zu lebenslanger Haft', ['Zu einer Geldstrafe', 'Zu einem Jahr', 'Er wurde freigesprochen']],
          ['Wie hießen die aufständischen Offiziere?', 'Carapintadas', ['Montoneros', 'Descamisados', 'Madres']],
          ['Wann wurde Argentinien mit Maradona Weltmeister?', '1986', ['1978', '1990', '2022']],
          ['Wo fand die WM 1986 statt?', 'In Mexiko', ['In Argentinien', 'In Italien', 'In Spanien']],
          ['Wie heißt Maradonas berühmtes Handtor?', '„Hand Gottes“', ['„Hand des Teufels“', '„Goldene Hand“', '„Hand des Jahrhunderts“']],
          ['Gegen wen erzielte Maradona die „Hand Gottes“?', 'Gegen England', ['Gegen Brasilien', 'Gegen Deutschland', 'Gegen Italien']],
          ['Wie hoch stieg die Inflation 1989?', 'Auf über 3.000 Prozent', ['Auf 3 Prozent', 'Auf 30 Prozent', 'Auf 300.000 Prozent']],
          ['Wer folgte Alfonsín 1989?', 'Carlos Menem', ['Néstor Kirchner', 'Fernando de la Rúa', 'Mauricio Macri']],
          ['Wen begnadigte Menem?', 'Die verurteilten Junta-Generäle', ['Niemanden', 'Nur Diebe', 'Die Madres']],
          ['Was war die „Convertibilidad“?', 'Ein Peso war einen US-Dollar wert', ['Ein neuer Fußballverein', 'Die Abschaffung des Geldes', 'Ein Vertrag mit Brasilien']],
          ['Was verschwand durch die Convertibilidad?', 'Die Inflation', ['Die Arbeitslosigkeit', 'Die Schulden', 'Der Peso']],
          ['Welchen Ölkonzern privatisierte Menem?', 'YPF', ['Petrobras', 'Pemex', 'Shell']],
          ['Welches jüdische Zentrum wurde 1994 angegriffen?', 'Die AMIA', ['Die ESMA', 'Die Casa Rosada', 'Das Teatro Colón']],
        ],
        mittel: [
          ['Wann trat Alfonsín sein Amt an?', 'Am 10. Dezember 1983', ['Am 30. Oktober 1983', 'Am 24. März 1983', 'Am 1. Januar 1984']],
          ['Welche zwei Junta-Mitglieder wurden zu lebenslanger Haft verurteilt?', 'Videla und Massera', ['Galtieri und Perón', 'Onganía und Videla', 'Menem und Alfonsín']],
          ['Was war am Prozess gegen die Juntas historisch?', 'Erstmals verurteilte ein demokratisches Land Lateinamerikas eine eigene Junta', ['Es war der erste Prozess der Welt', 'Er fand in Spanien statt', 'Die Junta wurde freigesprochen']],
          ['Was bedeutet „Carapintadas“?', 'Bemalte Gesichter', ['Rote Hemden', 'Weiße Kopftücher', 'Hemdlose']],
          ['Was bewirkten die Gesetze von 1986/87?', 'Sie stoppten weitere Prozesse', ['Sie verschärften die Prozesse', 'Sie verboten den Fußball', 'Sie schafften die Armee ab']],
          ['Wie heißen die Gesetze von 1986/87?', '„Schlusspunkt“ und „Befehlsnotstand“', ['„Nunca más“ und „Proceso“', '„Convertibilidad“ und „Corralito“', '„Sáenz Peña“ und „Roca“']],
          ['In welcher Runde traf Argentinien 1986 auf England?', 'Im Viertelfinale', ['Im Finale', 'Im Halbfinale', 'In der Gruppenphase']],
          ['Welches andere berühmte Tor schoss Maradona gegen England?', 'Das „Tor des Jahrhunderts“', ['Das „Wembley-Tor“', 'Das „Tor der Tore“ im Finale', 'Ein Eigentor']],
          ['Was geschah 1989 in Supermärkten?', 'Sie wurden geplündert', ['Sie verschenkten Waren', 'Sie wurden verstaatlicht', 'Sie schlossen für immer']],
          ['Wie übergab Alfonsín das Amt?', 'Vorzeitig', ['Nach drei Amtszeiten', 'Gar nicht', 'Nach einem Putsch']],
          ['Welcher Partei gehörte Menem an?', 'Den Peronisten', ['Der UCR', 'Der PRO', 'Den Sozialisten']],
          ['Wen begnadigte Menem außer den Generälen?', 'Guerillaführer', ['Die Madres', 'Die Briten', 'Maradona']],
          ['Welcher Wirtschaftsminister schuf die Convertibilidad?', 'Domingo Cavallo', ['Martínez de Hoz', 'Axel Kicillof', 'Luis Caputo']],
          ['Wann wurde die Convertibilidad eingeführt?', '1991', ['1989', '1995', '2001']],
          ['Was privatisierte Menem außer YPF?', 'Telefongesellschaft und Fluggesellschaft', ['Die Armee', 'Die Kirche', 'Die Polizei']],
          ['Was stieg trotz Wachstum unter Menem?', 'Arbeitslosigkeit und Schulden', ['Die Inflation auf 3.000 %', 'Die Zahl der Putsche', 'Die Zahl der Diktatoren']],
          ['Welches Ziel hatte der Anschlag von 1992?', 'Die israelische Botschaft', ['Die US-Botschaft', 'Die Casa Rosada', 'Die AMIA']],
          ['Wie viele Menschen starben beim AMIA-Anschlag?', '85', ['8', '850', '30.000']],
          ['Wen macht die Justiz für den AMIA-Anschlag verantwortlich?', 'Iran und Hisbollah', ['Großbritannien', 'Chile', 'Die Montoneros']],
          ['Warum wurde die Verfassung 1994 reformiert?', 'Damit Menem wiedergewählt werden konnte', ['Um die Monarchie einzuführen', 'Um die Provinzen abzuschaffen', 'Um Spanisch zu verbieten']],
        ],
        schwer: [
          ['Welche Kommission veröffentlichte „Nunca más“?', 'Die Kommission unter Ernesto Sabato', ['Die Junta', 'Der Vatikan', 'Die FIFA']],
          ['Welche Folge hatte der Druck der Carapintadas?', 'Gesetze stoppten weitere Prozesse', ['Alfonsín trat sofort zurück', 'Ein neuer Putsch gelang', 'Die Junta kam zurück']],
          ['Welche zwei Tore Maradonas sind von 1986 berühmt?', '„Hand Gottes“ und „Tor des Jahrhunderts“', ['Zwei Elfmeter', 'Zwei Kopfballtore', 'Zwei Eigentore']],
          ['Welches Jahr markiert die Hyperinflation über 3.000 Prozent?', '1989', ['1983', '2001', '2023']],
          ['Welches Wechselkurssystem prägte die 1990er?', 'Ein Peso gleich ein US-Dollar', ['Ein Peso gleich ein Euro', 'Freier Goldstandard', 'Kein Geld']],
          ['Welcher Konzern steht für Menems Privatisierungen?', 'YPF', ['Petrobras', 'Aerolíneas Brasil', 'Embraer']],
          ['Welcher Anschlag ist der schwerste der Landesgeschichte?', 'Der Anschlag auf die AMIA 1994', ['Der Anschlag auf die Botschaft 1992', 'Das Bombardement 1955', 'Der Anschlag auf Ezeiza']],
          ['Welche Begnadigung empörte viele?', 'Menems Begnadigung der Junta-Generäle', ['Alfonsíns Begnadigung Peróns', 'Die Begnadigung Maradonas', 'Keine']],
          ['Wann wurde die Verfassung reformiert?', '1994', ['1983', '1991', '2001']],
          ['Wann wurde Menem wiedergewählt?', '1995', ['1989', '1999', '1994']],
          ['Welche Institution verurteilte 1985 die Junta?', 'Ein ziviles Gericht in Argentinien', ['Der Internationale Strafgerichtshof', 'Ein spanisches Gericht', 'Ein Militärgericht der Junta']],
          ['Welche Rolle spielte Domingo Cavallo?', 'Wirtschaftsminister und Vater der Convertibilidad', ['Junta-General', 'Fußballtrainer', 'Präsident 1989']],
          ['Welche Gruppe war Ziel beider Anschläge 1992/1994?', 'Israelische bzw. jüdische Einrichtungen', ['Britische Einrichtungen', 'Die Kirche', 'Die Regierung']],
          ['Welche Länder bzw. Gruppen gelten als Urheber des AMIA-Anschlags?', 'Iran und Hisbollah', ['Libyen und IRA', 'ETA und FARC', 'Montoneros und ERP']],
          ['Welche Folge hatte die Hyperinflation für Alfonsín?', 'Er übergab das Amt vorzeitig', ['Er wurde wiedergewählt', 'Er wurde gestürzt vom Militär', 'Er floh ins Exil']],
          ['Welches Datum ist sowohl Tag der Demokratie als auch Tag der Menschenrechte?', '10. Dezember', ['24. März', '9. Juli', '2. April']],
          ['Welche Schattenseite hatte die Dollar-Bindung?', 'Steigende Arbeitslosigkeit und Schulden', ['Hyperinflation', 'Militärputsche', 'Keine']],
          ['Welches Land war Gastgeber von Argentiniens zweitem WM-Titel?', 'Mexiko', ['Italien', 'Spanien', 'Katar']],
          ['Welche zwei Gesetze nannte man später Straflosigkeitsgesetze?', 'Schlusspunkt und Befehlsnotstand', ['Nunca más und Convertibilidad', 'Sáenz Peña und AMIA', 'Lei Áurea und Corralito']],
          ['Welcher Schriftsteller ist mit „Nunca más“ verbunden?', 'Ernesto Sabato', ['Borges', 'Cortázar', 'Bioy Casares']],
        ],
      },
    },
    {
      id: 'krise-kirchner',
      title: 'Krise 2001, die Kirchners und Macri',
      date: '1999–2019',
      text: [
        'Ende der 1990er-Jahre geriet Argentinien in eine Rezession; die feste Dollar-Bindung machte Exporte zu teuer. Präsident Fernando de la Rúa (ab 1999) ließ im Dezember 2001 Bankkonten einfrieren, den „Corralito“. Daraufhin brachen Unruhen aus, Menschen schlugen auf Töpfe („Cacerolazo“) und riefen „¡Que se vayan todos!“ („Alle sollen gehen!“). Über 30 Menschen starben, und de la Rúa floh am 20. Dezember 2001 im Hubschrauber aus der Casa Rosada.',
        'In zwei Wochen hatte das Land fünf Präsidenten. Argentinien erklärte den größten Staatsbankrott der Geschichte bis dahin (rund 100 Milliarden Dollar), und Anfang 2002 wurde die Dollar-Bindung aufgegeben; der Peso verlor drei Viertel seines Wertes. Über die Hälfte der Bevölkerung fiel unter die Armutsgrenze.',
        '2003 wurde der Peronist Néstor Kirchner Präsident. Dank hoher Preise für Soja, das zum wichtigsten Exportgut wurde, wuchs die Wirtschaft schnell. Kirchner ließ die Straflosigkeitsgesetze aufheben; ab 2006 wurden Hunderte Täter der Diktatur verurteilt, und die ESMA wurde zu einer Gedenkstätte. 2007 folgte ihm seine Frau Cristina Fernández de Kirchner, die bis 2015 regierte; Néstor starb 2010.',
        'Unter Cristina wurde 2010 die gleichgeschlechtliche Ehe als erstes Land Lateinamerikas erlaubt, 2012 YPF wieder verstaatlicht. Zugleich stiegen Inflation und Staatsausgaben, und die Regierung schönte Statistiken. 2013 wurde der Erzbischof von Buenos Aires, Jorge Mario Bergoglio, als Franziskus erster Papst aus Amerika.',
        '2015 gewann der liberal-konservative Mauricio Macri die Wahl. Er hob Devisenkontrollen auf, doch 2018 musste er wegen einer Währungskrise den Internationalen Währungsfonds (IWF) um den größten Kredit seiner Geschichte (57 Milliarden Dollar) bitten. 2019 verlor Macri gegen den Peronisten Alberto Fernández, mit Cristina als Vizepräsidentin. 2020 wurde die Abtreibung legalisiert.',
      ],
      quiz: {
        leicht: [
          ['Was machte argentinische Exporte Ende der 1990er zu teuer?', 'Die feste Dollar-Bindung', ['Hohe Zölle in Europa', 'Ein Krieg', 'Schlechtes Wetter']],
          ['Wie hieß das Einfrieren der Bankkonten 2001?', 'Corralito', ['Cacerolazo', 'Convertibilidad', 'Proceso']],
          ['Worauf schlugen die Menschen bei Protesten?', 'Auf Töpfe', ['Auf Trommeln', 'Auf Autos', 'Auf Glocken']],
          ['Wie heißt dieser Protest?', 'Cacerolazo', ['Cordobazo', 'Corralito', 'Bogotazo']],
          ['Was riefen die Protestierenden?', '„¡Que se vayan todos!“', ['„¡Libertad!“', '„¡Viva Perón!“', '„¡Nunca más!“']],
          ['Wie floh de la Rúa aus der Casa Rosada?', 'Im Hubschrauber', ['Zu Pferd', 'Mit dem Zug', 'Mit dem Schiff']],
          ['Wie viele Präsidenten hatte das Land in zwei Wochen?', 'Fünf', ['Einen', 'Zwei', 'Zehn']],
          ['Was erklärte Argentinien 2001?', 'Den Staatsbankrott', ['Den Krieg', 'Die Monarchie', 'Den Sieg']],
          ['Was geschah 2002 mit der Dollar-Bindung?', 'Sie wurde aufgegeben', ['Sie wurde verstärkt', 'Sie wurde auf den Euro übertragen', 'Sie wurde erfunden']],
          ['Wie viel der Bevölkerung fiel unter die Armutsgrenze?', 'Über die Hälfte', ['Ein Zehntel', 'Niemand', 'Alle']],
          ['Wer wurde 2003 Präsident?', 'Néstor Kirchner', ['Cristina Kirchner', 'Mauricio Macri', 'Carlos Menem']],
          ['Welches Produkt wurde zum wichtigsten Exportgut?', 'Soja', ['Kaffee', 'Gold', 'Bananen']],
          ['Was wurde aus der ESMA?', 'Eine Gedenkstätte', ['Ein Stadion', 'Ein Gefängnis', 'Ein Hotel']],
          ['Wer folgte Néstor Kirchner 2007?', 'Seine Frau Cristina Fernández de Kirchner', ['Mauricio Macri', 'Alberto Fernández', 'Javier Milei']],
          ['Was erlaubte Argentinien 2010 als erstes Land Lateinamerikas?', 'Die gleichgeschlechtliche Ehe', ['Das Frauenwahlrecht', 'Die Scheidung', 'Die Sklaverei']],
          ['Wer wurde 2013 Papst?', 'Jorge Mario Bergoglio', ['Ernesto Sabato', 'Néstor Kirchner', 'Lionel Messi']],
          ['Welchen Namen wählte Bergoglio als Papst?', 'Franziskus', ['Johannes Paul III.', 'Benedikt XVII.', 'Pius XIII.']],
          ['Wer gewann 2015 die Wahl?', 'Mauricio Macri', ['Cristina Kirchner', 'Alberto Fernández', 'Javier Milei']],
          ['Welche Organisation lieh Argentinien 2018 Geld?', 'Der Internationale Währungsfonds', ['Die FIFA', 'Die NATO', 'Der Vatikan']],
          ['Was wurde 2020 legalisiert?', 'Die Abtreibung', ['Die Monarchie', 'Der Dollar als Währung', 'Die Todesstrafe']],
        ],
        mittel: [
          ['Seit wann war de la Rúa Präsident?', 'Seit 1999', ['Seit 1995', 'Seit 2001', 'Seit 1989']],
          ['Wann wurde der Corralito verhängt?', 'Im Dezember 2001', ['Im Januar 2002', 'Im Mai 2003', 'Im Juli 1989']],
          ['Was bedeutet „¡Que se vayan todos!“?', 'Alle sollen gehen!', ['Alle sollen bleiben!', 'Es lebe die Freiheit!', 'Nie wieder!']],
          ['Wie viele Menschen starben bei den Unruhen 2001?', 'Über 30', ['Keiner', 'Über 3.000', 'Über 300']],
          ['An welchem Tag floh de la Rúa?', 'Am 20. Dezember 2001', ['Am 10. Dezember 2001', 'Am 1. Januar 2002', 'Am 25. Mai 2003']],
          ['Wie hoch war der Staatsbankrott etwa?', 'Rund 100 Milliarden Dollar', ['Rund 1 Milliarde', 'Rund 10 Millionen', 'Rund 1 Billion']],
          ['Wie viel Wert verlor der Peso 2002?', 'Drei Viertel', ['Nichts', 'Ein Zehntel', 'Er gewann an Wert']],
          ['Welcher Partei gehörte Néstor Kirchner an?', 'Den Peronisten', ['Der UCR', 'Der PRO', 'Der Libertären Partei']],
          ['Was ermöglichte das schnelle Wachstum nach 2003?', 'Hohe Sojapreise', ['Ein Goldfund', 'Ein Ölfund in Patagonien', 'Die Dollar-Bindung']],
          ['Was ließ Kirchner aufheben?', 'Die Straflosigkeitsgesetze', ['Die Verfassung', 'Die Wahlen', 'Den Peso']],
          ['Ab wann wurden Hunderte Täter der Diktatur verurteilt?', 'Ab 2006', ['Ab 1985', 'Ab 1995', 'Ab 2020']],
          ['Bis wann regierte Cristina Kirchner?', '2015', ['2011', '2019', '2023']],
          ['Wann starb Néstor Kirchner?', '2010', ['2007', '2015', '2003']],
          ['Was verstaatlichte Cristina 2012?', 'YPF', ['Die Banken', 'Die Fußballvereine', 'Petrobras']],
          ['Was stieg unter Cristina?', 'Inflation und Staatsausgaben', ['Die Exporte von Kaffee', 'Die Zahl der Putsche', 'Der Dollarkurs fest bei eins']],
          ['Was tat die Regierung mit Statistiken?', 'Sie schönte sie', ['Sie veröffentlichte sie ehrlich', 'Sie schaffte sie ab', 'Sie verkaufte sie']],
          ['Welches Amt hatte Bergoglio vor 2013?', 'Erzbischof von Buenos Aires', ['Präsident', 'Fußballtrainer', 'Bürgermeister von Rosario']],
          ['Was war Franziskus als Papst als Erster?', 'Erster Papst aus Amerika', ['Erster Papst aus Europa', 'Erster Papst überhaupt', 'Erster Papst aus Afrika']],
          ['Wie hoch war der IWF-Kredit 2018?', '57 Milliarden Dollar', ['5,7 Milliarden', '570 Millionen', '570 Milliarden']],
          ['Wer wurde 2019 Präsident?', 'Alberto Fernández', ['Cristina Kirchner', 'Macri', 'Milei']],
        ],
        schwer: [
          ['Welcher Präsident floh 2001 im Hubschrauber?', 'Fernando de la Rúa', ['Carlos Menem', 'Eduardo Duhalde', 'Adolfo Rodríguez Saá']],
          ['Was war 2001 der größte Staatsbankrott bis dahin?', 'Der Argentiniens', ['Der Griechenlands', 'Der Russlands', 'Der Mexikos']],
          ['Welche zwei Maßnahmen lösten die Krise 2001/02 mit aus?', 'Corralito und Ende der Dollar-Bindung', ['Convertibilidad und Nunca más', 'Proceso und Cordobazo', 'Soja und Tango']],
          ['Welches Rohstoffprodukt trug den Boom der 2000er?', 'Soja', ['Kupfer', 'Kaffee', 'Silber']],
          ['Welche Rolle spielte Kirchner für die Aufarbeitung?', 'Er ließ die Straflosigkeitsgesetze aufheben', ['Er begnadigte alle Täter', 'Er verbot die Madres', 'Keine']],
          ['Welcher Präsident ließ YPF wieder verstaatlichen?', 'Cristina Fernández de Kirchner', ['Macri', 'Menem', 'Milei']],
          ['Welcher Erzbischof wurde 2013 Papst?', 'Bergoglio', ['Sabato', 'Pérez Esquivel', 'Quarracino']],
          ['Welches Gesellschaftsgesetz von 2010 war ein Vorreiter?', 'Die Ehe für alle', ['Das Rauchverbot', 'Die Wehrpflicht', 'Das Tangoverbot']],
          ['Welche Politik verfolgte Macri?', 'Liberal-konservativ', ['Peronistisch', 'Kommunistisch', 'Monarchistisch']],
          ['Welche Kontrollen hob Macri auf?', 'Devisenkontrollen', ['Grenzkontrollen', 'Pressekontrollen', 'Waffenkontrollen']],
          ['Warum bat Macri 2018 den IWF um Hilfe?', 'Wegen einer Währungskrise', ['Wegen eines Krieges', 'Wegen der WM', 'Wegen eines Erdbebens']],
          ['Welche Vizepräsidentin hatte Alberto Fernández?', 'Cristina Fernández de Kirchner', ['Isabel Perón', 'Victoria Villarruel', 'Gabriela Michetti']],
          ['Wann wurde die Abtreibung legalisiert?', '2020', ['2010', '2015', '2001']],
          ['Welcher Protestruf wurde zum Symbol von 2001?', '„¡Que se vayan todos!“', ['„¡Nunca más!“', '„¡Volveremos!“', '„¡Viva la libertad, carajo!“']],
          ['Wie lange regierte das Ehepaar Kirchner zusammen gerechnet?', '2003–2015', ['1999–2011', '2007–2019', '2003–2023']],
          ['Welcher IWF-Kredit war der größte der Geschichte des Fonds?', 'Der Kredit an Argentinien 2018', ['Der Kredit an Griechenland 2010', 'Der Kredit an Mexiko 1995', 'Der Kredit an Brasilien 2002']],
          ['Welches Ereignis machte Argentinien 2013 weltweit bekannt?', 'Die Wahl eines argentinischen Papstes', ['Ein WM-Sieg', 'Ein Krieg', 'Eine Olympiade']],
          ['Wie viel Prozent der Bevölkerung fielen 2002 etwa unter die Armutsgrenze?', 'Über 50 Prozent', ['Rund 5 Prozent', 'Rund 20 Prozent', 'Rund 90 Prozent']],
          ['Welcher Ort der Diktatur wurde unter Kirchner Gedenkstätte?', 'Die ESMA', ['Die Casa Rosada', 'Ezeiza', 'Die AMIA']],
          ['Welche Krise prägte Argentinien Ende der 1990er?', 'Eine Rezession', ['Ein Boom', 'Eine Hungersnot durch Krieg', 'Eine Monarchie']],
        ],
      },
    },
    {
      id: 'milei',
      title: 'Messi, Inflation und Milei',
      date: 'seit 2019',
      text: [
        'Die Regierung von Alberto Fernández (2019–2023) erlebte die Covid-19-Pandemie mit einem der längsten Lockdowns der Welt. Danach stieg die Inflation immer weiter, Ende 2023 auf über 200 Prozent im Jahr; rund 40 Prozent der Menschen lebten in Armut. 2022 entging Cristina Kirchner knapp einem Attentat, als die Pistole eines Angreifers versagte, und wurde im selben Jahr wegen Korruption verurteilt.',
        'Im Dezember 2022 gewann Argentinien in Katar mit Lionel Messi zum dritten Mal die Fußball-Weltmeisterschaft, nach einem dramatischen Finale gegen Frankreich im Elfmeterschießen. Millionen feierten in Buenos Aires um den Obelisken – eine der größten Menschenansammlungen der Landesgeschichte.',
        'Im November 2023 gewann der libertäre Ökonom Javier Milei die Stichwahl gegen den Peronisten Sergio Massa mit rund 56 Prozent. Milei war als Fernsehkommentator bekannt geworden, trat im Wahlkampf mit einer Kettensäge als Symbol für Kürzungen auf und rief „¡Viva la libertad, carajo!“. Er bezeichnete sich als „Anarchokapitalist“.',
        'Milei kürzte die Staatsausgaben drastisch, halbierte die Zahl der Ministerien, wertete den Peso ab und erreichte 2024 erstmals seit über zehn Jahren einen Haushaltsüberschuss. Die Inflation sank stark, auf rund 30 Prozent im Jahr 2025. Zunächst stieg aber die Armut, und Rentner, Universitäten und Gewerkschaften protestierten gegen die Kürzungen. Im Juni 2025 bestätigte das Oberste Gericht Cristina Kirchners Urteil; sie kam in Hausarrest.',
        'Im April 2025 starb Papst Franziskus, der Argentinier. Im Oktober 2025 gewann Mileis Partei „La Libertad Avanza“ mit Unterstützung der USA unter Donald Trump überraschend deutlich die Parlamentswahlen. Mit über 46 Millionen Einwohnern ist Argentinien heute das achtgrößte Land der Erde nach Fläche und bleibt ein Land großer Chancen und wiederkehrender Krisen.',
      ],
      quiz: {
        leicht: [
          ['Wer war 2019–2023 Präsident?', 'Alberto Fernández', ['Mauricio Macri', 'Javier Milei', 'Néstor Kirchner']],
          ['Wofür war Argentiniens Covid-Politik bekannt?', 'Für einen der längsten Lockdowns der Welt', ['Für gar keine Maßnahmen', 'Für den ersten Impfstoff', 'Für offene Grenzen']],
          ['Wie hoch stieg die Inflation Ende 2023?', 'Auf über 200 Prozent', ['Auf 2 Prozent', 'Auf 20 Prozent', 'Auf 2.000 Prozent']],
          ['Wer entging 2022 knapp einem Attentat?', 'Cristina Kirchner', ['Javier Milei', 'Lionel Messi', 'Alberto Fernández']],
          ['Warum scheiterte das Attentat?', 'Die Pistole versagte', ['Die Polizei schoss zuerst', 'Der Täter verfehlte', 'Sie trug eine Schutzweste']],
          ['Wo gewann Argentinien 2022 die WM?', 'In Katar', ['In Russland', 'In Brasilien', 'In Deutschland']],
          ['Welcher Spieler führte Argentinien 2022 zum Titel?', 'Lionel Messi', ['Diego Maradona', 'Mario Kempes', 'Gabriel Batistuta']],
          ['Gegen wen spielte Argentinien im WM-Finale 2022?', 'Gegen Frankreich', ['Gegen Deutschland', 'Gegen Brasilien', 'Gegen Kroatien']],
          ['Wie wurde das Finale 2022 entschieden?', 'Im Elfmeterschießen', ['In der regulären Spielzeit', 'Durch Losentscheid', 'Durch ein Golden Goal']],
          ['Der wievielte WM-Titel war 2022 für Argentinien?', 'Der dritte', ['Der erste', 'Der zweite', 'Der vierte']],
          ['Wo feierten Millionen in Buenos Aires?', 'Um den Obelisken', ['Am Hafen', 'In der ESMA', 'Am Flughafen']],
          ['Wer gewann 2023 die Präsidentenwahl?', 'Javier Milei', ['Sergio Massa', 'Cristina Kirchner', 'Mauricio Macri']],
          ['Welchen Beruf hatte Milei?', 'Ökonom', ['Fußballer', 'General', 'Priester']],
          ['Welches Werkzeug war Mileis Wahlkampfsymbol?', 'Eine Kettensäge', ['Ein Hammer', 'Eine Schere', 'Ein Besen']],
          ['Wofür stand die Kettensäge?', 'Für Kürzungen', ['Für Waldarbeit', 'Für Bauprojekte', 'Für Krieg']],
          ['Welchen Ruf machte Milei bekannt?', '„¡Viva la libertad, carajo!“', ['„¡Que se vayan todos!“', '„¡Nunca más!“', '„¡Viva Perón!“']],
          ['Was kürzte Milei drastisch?', 'Die Staatsausgaben', ['Die Exporte', 'Die Zahl der Provinzen', 'Die Fußballliga']],
          ['Was sank unter Milei stark?', 'Die Inflation', ['Die Zahl der Einwohner', 'Die Exporte auf null', 'Die Fläche des Landes']],
          ['Wann starb Papst Franziskus?', 'Im April 2025', ['Im März 2013', 'Im Dezember 2022', 'Im Oktober 2025']],
          ['Wie heißt Mileis Partei?', 'La Libertad Avanza', ['Partido Justicialista', 'UCR', 'PRO']],
        ],
        mittel: [
          ['Wie viele Menschen lebten Ende 2023 etwa in Armut?', 'Rund 40 Prozent', ['Rund 4 Prozent', 'Rund 90 Prozent', 'Niemand']],
          ['Wofür wurde Cristina Kirchner 2022 verurteilt?', 'Wegen Korruption', ['Wegen Mordes', 'Wegen Hochverrats', 'Wegen Steuerhinterziehung im Fußball']],
          ['In welchem Monat 2022 war das WM-Finale?', 'Im Dezember', ['Im Juli', 'Im Juni', 'Im November']],
          ['Was war die Feier nach der WM 2022?', 'Eine der größten Menschenansammlungen der Landesgeschichte', ['Eine kleine Feier', 'Verboten', 'Nur im Fernsehen']],
          ['Gegen wen gewann Milei die Stichwahl?', 'Gegen Sergio Massa', ['Gegen Cristina Kirchner', 'Gegen Macri', 'Gegen Alberto Fernández']],
          ['Mit wie viel Prozent gewann Milei?', 'Rund 56 Prozent', ['Rund 36 Prozent', 'Rund 76 Prozent', 'Rund 51 Prozent']],
          ['Wann war die Stichwahl?', 'Im November 2023', ['Im Oktober 2019', 'Im Dezember 2022', 'Im Oktober 2025']],
          ['Wodurch wurde Milei bekannt?', 'Als Fernsehkommentator', ['Als Fußballer', 'Als General', 'Als Tango-Sänger']],
          ['Wie bezeichnete sich Milei?', 'Als Anarchokapitalist', ['Als Peronist', 'Als Kommunist', 'Als Monarchist']],
          ['Was tat Milei mit den Ministerien?', 'Er halbierte ihre Zahl', ['Er verdoppelte sie', 'Er schaffte alle ab', 'Er benannte sie nur um']],
          ['Was tat Milei mit dem Peso?', 'Er wertete ihn ab', ['Er schaffte ihn sofort ab', 'Er band ihn an den Euro', 'Er wertete ihn stark auf']],
          ['Was erreichte Milei 2024 erstmals seit über zehn Jahren?', 'Einen Haushaltsüberschuss', ['Einen WM-Titel', 'Eine Inflation von null', 'Die Rückgabe der Falklandinseln']],
          ['Auf wie viel sank die Inflation 2025 etwa?', 'Rund 30 Prozent', ['Rund 300 Prozent', 'Null Prozent', 'Rund 3 Prozent']],
          ['Was stieg unter Milei zunächst?', 'Die Armut', ['Die Staatsausgaben', 'Die Zahl der Ministerien', 'Die Inflation auf 1.000 %']],
          ['Wer protestierte gegen Mileis Kürzungen?', 'Rentner, Universitäten und Gewerkschaften', ['Nur Banken', 'Niemand', 'Nur das Militär']],
          ['Was geschah im Juni 2025 mit Cristina Kirchner?', 'Ihr Urteil wurde bestätigt, sie kam in Hausarrest', ['Sie wurde Präsidentin', 'Sie wurde freigesprochen', 'Sie floh ins Ausland']],
          ['Wann gewann Mileis Partei die Parlamentswahlen?', 'Im Oktober 2025', ['Im November 2023', 'Im Juni 2025', 'Im Dezember 2024']],
          ['Welches Land unterstützte Milei 2025?', 'Die USA', ['China', 'Russland', 'Brasilien']],
          ['Wie viele Einwohner hat Argentinien etwa?', 'Über 46 Millionen', ['Rund 4,6 Millionen', 'Über 146 Millionen', 'Rund 460 Millionen']],
          ['Das wievieltgrößte Land der Erde nach Fläche ist Argentinien?', 'Das achtgrößte', ['Das größte', 'Das dritte', 'Das zwanzigste']],
        ],
        schwer: [
          ['Welcher politische Begriff beschreibt Milei?', 'Libertär', ['Peronistisch', 'Sozialdemokratisch', 'Monarchistisch']],
          ['Welche Symbolik hatte die Kettensäge?', 'Radikale Kürzung des Staates', ['Schutz des Regenwaldes', 'Bau neuer Straßen', 'Kampf gegen Briten']],
          ['Welche Erfolge erzielte Milei bis 2025 wirtschaftlich?', 'Haushaltsüberschuss und sinkende Inflation', ['Hyperinflation und Bankrott', 'Vollbeschäftigung ohne Kürzungen', 'Keine']],
          ['Welche soziale Folge hatten die Kürzungen anfangs?', 'Mehr Armut', ['Weniger Armut sofort', 'Keine', 'Mehr Ministerien']],
          ['Wer war Mileis Gegner in der Stichwahl 2023?', 'Sergio Massa', ['Patricia Bullrich', 'Axel Kicillof', 'Horacio Rodríguez Larreta']],
          ['Wie endete das WM-Finale 2022?', 'Argentinien siegte im Elfmeterschießen gegen Frankreich', ['Argentinien verlor gegen Frankreich', 'Argentinien siegte 1:0 gegen Deutschland', 'Unentschieden ohne Sieger']],
          ['Welche drei WM-Titel hat Argentinien?', '1978, 1986, 2022', ['1978, 1990, 2014', '1986, 1990, 2022', '1930, 1978, 1986']],
          ['Welches Gericht bestätigte 2025 Cristina Kirchners Urteil?', 'Das Oberste Gericht', ['Der IWF', 'Ein Militärgericht', 'Der Vatikan']],
          ['Welche Strafe verbüßt Cristina Kirchner?', 'Hausarrest', ['Exil in Spanien', 'Keine', 'Militärhaft in der ESMA']],
          ['Welcher berühmte Argentinier starb im April 2025?', 'Papst Franziskus', ['Javier Milei', 'Lionel Messi', 'Mauricio Macri']],
          ['Welcher US-Präsident unterstützte Milei 2025?', 'Donald Trump', ['Joe Biden', 'Barack Obama', 'George W. Bush']],
          ['Welche Wahl im Oktober 2025 stärkte Milei?', 'Die Parlamentswahlen', ['Die Präsidentenwahl', 'Die Papstwahl', 'Ein Referendum über die Falklandinseln']],
          ['Welche Maßnahme ergriff Milei für die Staatsstruktur?', 'Halbierung der Ministerien', ['Gründung neuer Provinzen', 'Einführung der Monarchie', 'Verlegung der Hauptstadt']],
          ['Welche Pandemiepolitik verfolgte Alberto Fernández?', 'Einen sehr langen Lockdown', ['Gar keine Maßnahmen', 'Herdenimmunität ohne Regeln', 'Grenzöffnung']],
          ['Wie hoch war die Inflation, als Milei antrat?', 'Über 200 Prozent', ['Unter 10 Prozent', 'Rund 50 Prozent', 'Über 5.000 Prozent']],
          ['Welche Schusswaffe versagte 2022?', 'Die Pistole des Angreifers auf Cristina Kirchner', ['Ein Gewehr bei der WM', 'Eine Kanone am Obelisken', 'Eine Waffe beim Papst']],
          ['Welche Bewertung trifft auf Argentinien seit 1983 zu?', 'Demokratie mit wiederkehrenden Wirtschaftskrisen', ['Ständige Militärherrschaft', 'Monarchie', 'Krisenfreie Stabilität']],
          ['Welcher Ort war Mittelpunkt der WM-Feier 2022?', 'Der Obelisk', ['Die ESMA', 'Die Plaza San Martín', 'Der Hafen von La Boca']],
          ['Welchen Rang hat Argentinien nach Fläche weltweit?', 'Achter', ['Erster', 'Zweiter', 'Zwanzigster']],
          ['Welche Partei stellte den unterlegenen Kandidaten 2023?', 'Die Peronisten', ['Die UCR', 'La Libertad Avanza', 'Die Grünen']],
        ],
      },
    },
  ],
};

export const E4: Epoch = {
  id: 'gegenwart',
  name: 'Diktatur und Demokratie',
  period: 'seit 1955',
  events: [DIKTATUR, DEMOKRATIE],
};
