import type { Epoch } from '../types';

export const E3: Epoch = {
  id: 'niedergang',
  name: 'Niedergang und Neubeginn',
  period: '1566–1938',
  events: [
    {
      id: 'weltkrieg',
      title: 'Niedergang, Weltkrieg und Völkermord an den Armeniern',
      date: '1566–1920',
      text: [
        'Nach Süleyman verlor das Osmanische Reich langsam an Macht. Reformen im 19. Jahrhundert konnten den Niedergang des „kranken Mannes am Bosporus“ nicht aufhalten. Im Ersten Weltkrieg kämpfte das Reich an der Seite Deutschlands; 1915 verübte die jungtürkische Regierung den Völkermord an den Armeniern. Nach der Niederlage sollte das Reich aufgeteilt werden.',
      ],
      subtopics: [
        {
          id: 'stagnation-reformen',
          title: 'Wien 1683, Tulpenzeit und Tanzimat',
          date: '1566–1876',
          text: [
            'Nach Süleymans Tod regierten oft schwache Sultane, und im Palast gewannen Frauen des Harems und Wesire großen Einfluss; man spricht vom „Sultanat der Frauen“. 1683 belagerte der Großwesir Kara Mustafa zum zweiten Mal Wien, doch ein Entsatzheer unter dem polnischen König Jan III. Sobieski schlug die Osmanen. Im Frieden von Karlowitz 1699 verlor das Reich zum ersten Mal große Gebiete, vor allem Ungarn.',
            'Unter Sultan Ahmed III. erlebte Istanbul die „Tulpenzeit“ (1718–1730): Die Oberschicht feierte prächtige Feste in Gärten voller Tulpen, und 1727 druckte İbrahim Müteferrika die ersten türkischen Bücher. Die Tulpe war schon lange ein Symbol der Osmanen; von hier kam sie nach Holland. Auch der Kaffee verbreitete sich über Istanbul nach Europa.',
            'Im 18. und 19. Jahrhundert verlor das Reich Kriege gegen Russland, 1783 die Krim. Die Janitscharen, einst die Elite, wehrten sich gegen jede Modernisierung; 1826 ließ Sultan Mahmud II. sie gewaltsam auflösen. Griechenland wurde 1830 unabhängig, später auch Serbien, Rumänien und Bulgarien.',
            '1839 begannen die „Tanzimat“-Reformen („Neuordnungen“): Alle Untertanen sollten unabhängig von ihrer Religion gleich vor dem Gesetz sein, Verwaltung, Armee und Schulen wurden nach europäischem Vorbild modernisiert. Im Krimkrieg (1853–1856) kämpften Großbritannien und Frankreich an der Seite der Osmanen gegen Russland; die Krankenschwester Florence Nightingale pflegte Verwundete in Üsküdar in Istanbul.',
            'Trotzdem wurde das Reich immer schwächer und hoch verschuldet; Zar Nikolaus I. nannte es den „kranken Mann am Bosporus“. 1876 erhielt es eine erste Verfassung und ein Parlament. Im Dolmabahçe-Palast am Bosporus, ab 1856 Sitz der Sultane, zeigte sich der neue europäische Stil.',
          ],
          quiz: {
            leicht: [
              ['Welche Stadt belagerten die Osmanen 1683 zum zweiten Mal?', 'Wien', ['Rom', 'Prag', 'Budapest']],
              ['Wer führte das Entsatzheer vor Wien 1683?', 'Jan III. Sobieski', ['Prinz Eugen', 'Karl V.', 'Peter der Große']],
              ['Welches Land verlor das Reich im Frieden von Karlowitz vor allem?', 'Ungarn', ['Ägypten', 'Griechenland', 'Syrien']],
              ['Wie nennt man die Zeit von 1718 bis 1730 in Istanbul?', 'Tulpenzeit', ['Rosenzeit', 'Goldene Zeit', 'Tanzimat']],
              ['Welche Blume war ein Symbol der Osmanen?', 'Die Tulpe', ['Die Rose', 'Die Lilie', 'Die Sonnenblume']],
              ['Welches Land übernahm die Tulpe von den Osmanen?', 'Holland', ['Spanien', 'Russland', 'Japan']],
              ['Welches Getränk verbreitete sich über Istanbul nach Europa?', 'Kaffee', ['Tee', 'Bier', 'Kakao']],
              ['Wer druckte 1727 die ersten türkischen Bücher?', 'İbrahim Müteferrika', ['Mimar Sinan', 'Gutenberg', 'Piri Reis']],
              ['Welche Halbinsel verlor das Reich 1783 an Russland?', 'Die Krim', ['Gallipoli', 'Den Peloponnes', 'Die Arabische Halbinsel']],
              ['Welcher Sultan löste 1826 die Janitscharen auf?', 'Mahmud II.', ['Süleyman', 'Mehmed II.', 'Abdülhamid II.']],
              ['Welches Land wurde 1830 unabhängig?', 'Griechenland', ['Ägypten', 'Ungarn', 'Armenien']],
              ['Wie heißen die Reformen ab 1839?', 'Tanzimat', ['Perestroika', 'Glasnost', 'Reconquista']],
              ['Was bedeutet „Tanzimat“?', 'Neuordnungen', ['Tulpenzeit', 'Eroberungen', 'Gesetzgeber']],
              ['Gegen wen kämpften die Osmanen im Krimkrieg?', 'Gegen Russland', ['Gegen Frankreich', 'Gegen England', 'Gegen Österreich']],
              ['Welche Krankenschwester pflegte im Krimkrieg Verwundete in Istanbul?', 'Florence Nightingale', ['Marie Curie', 'Mutter Teresa', 'Clara Barton']],
              ['Wie nannte der Zar das Osmanische Reich?', 'Den kranken Mann am Bosporus', ['Den Löwen des Ostens', 'Den Riesen Asiens', 'Den Bären am Meer']],
              ['Wann erhielt das Reich eine erste Verfassung?', '1876', ['1839', '1923', '1453']],
              ['Welcher Palast wurde ab 1856 Sitz der Sultane?', 'Der Dolmabahçe-Palast', ['Der Topkapı-Palast', 'Der Kreml', 'Der Yıldız-Palast zuerst']],
              ['Wer gewann im 17. Jahrhundert im Palast großen Einfluss?', 'Frauen des Harems und Wesire', ['Die Kreuzfahrer', 'Die Mongolen', 'Ausländische Könige']],
              ['Wogegen wehrten sich die Janitscharen?', 'Gegen jede Modernisierung', ['Gegen Kaffee', 'Gegen die Tulpen', 'Gegen den Islam']],
            ],
            mittel: [
              ['Welcher Großwesir belagerte 1683 Wien?', 'Kara Mustafa', ['Sokollu Mehmed', 'Ibrahim Pascha', 'Köprülü Mehmed']],
              ['Wann wurde der Frieden von Karlowitz geschlossen?', '1699', ['1683', '1718', '1774']],
              ['Was war am Frieden von Karlowitz neu?', 'Das Reich verlor zum ersten Mal große Gebiete', ['Das Reich gewann Wien', 'Das Reich wurde Republik', 'Das Reich verlor Istanbul']],
              ['Unter welchem Sultan war die Tulpenzeit?', 'Ahmed III.', ['Mahmud II.', 'Selim III.', 'Murad IV.']],
              ['Wann druckte Müteferrika die ersten türkischen Bücher?', '1727', ['1453', '1839', '1928']],
              ['Wie feierte die Oberschicht in der Tulpenzeit?', 'Mit prächtigen Festen in Tulpengärten', ['Mit Kriegen', 'Mit Fasten', 'Mit Pilgerreisen']],
              ['Wie nennt man den Einfluss der Frauen im Palast?', 'Sultanat der Frauen', ['Tulpenzeit', 'Tanzimat', 'Harem-Republik']],
              ['Wann löste Mahmud II. die Janitscharen auf?', '1826', ['1699', '1839', '1876']],
              ['Wie wurden die Janitscharen aufgelöst?', 'Gewaltsam', ['Durch eine Wahl', 'Freiwillig', 'Durch einen Vertrag mit Russland']],
              ['Welche Länder wurden nach Griechenland unabhängig?', 'Serbien, Rumänien und Bulgarien', ['Ägypten und Syrien', 'Persien und Irak', 'Ungarn und Polen']],
              ['Wann begannen die Tanzimat-Reformen?', '1839', ['1826', '1876', '1908']],
              ['Was sollten die Tanzimat-Reformen für alle Untertanen bringen?', 'Gleichheit vor dem Gesetz', ['Gleiche Kleidung', 'Gleiche Religion', 'Gleiche Sprache']],
              ['Wonach wurden Verwaltung, Armee und Schulen modernisiert?', 'Nach europäischem Vorbild', ['Nach chinesischem Vorbild', 'Nach persischem Vorbild', 'Gar nicht']],
              ['Wann fand der Krimkrieg statt?', '1853–1856', ['1683–1699', '1914–1918', '1768–1774']],
              ['Wer kämpfte im Krimkrieg an der Seite der Osmanen?', 'Großbritannien und Frankreich', ['Russland und Preußen', 'Österreich und Spanien', 'Persien und Ägypten']],
              ['Wo pflegte Florence Nightingale Verwundete?', 'In Üsküdar in Istanbul', ['In Sewastopol', 'In London', 'In Ankara']],
              ['Welcher Zar sprach vom „kranken Mann am Bosporus“?', 'Nikolaus I.', ['Peter der Große', 'Alexander II.', 'Nikolaus II.']],
              ['Was erhielt das Reich 1876 außer einer Verfassung?', 'Ein Parlament', ['Einen Kaiser', 'Eine Kolonie', 'Eine neue Hauptstadt']],
              ['Welchen Stil zeigte der Dolmabahçe-Palast?', 'Den europäischen Stil', ['Den byzantinischen Stil', 'Den chinesischen Stil', 'Den Stil der Seldschuken']],
              ['Wie stand das Reich im 19. Jahrhundert finanziell da?', 'Hoch verschuldet', ['Sehr reich', 'Schuldenfrei', 'Es hatte kein Geld']],
            ],
            schwer: [
              ['Wann war die Tulpenzeit?', '1718–1730', ['1683–1699', '1839–1876', '1520–1566']],
              ['Wann verlor das Reich die Krim?', '1783', ['1699', '1853', '1830']],
              ['Wann wurde Griechenland unabhängig?', '1830', ['1821', '1878', '1913']],
              ['Wann wurde der Dolmabahçe-Palast Sitz der Sultane?', 'Ab 1856', ['Ab 1453', 'Ab 1923', 'Ab 1699']],
              ['Was war das Entsatzheer 1683?', 'Ein Heer zur Befreiung Wiens', ['Ein osmanisches Heer', 'Eine russische Flotte', 'Ein Heer von Söldnern aus Persien']],
              ['Welches Volk führte das Entsatzheer an?', 'Die Polen unter Sobieski', ['Die Russen unter Peter', 'Die Franzosen unter Ludwig XIV.', 'Die Schweden']],
              ['Welche Erfindung kam 1727 in die osmanische Welt?', 'Der Buchdruck in türkischer Sprache', ['Die Dampfmaschine', 'Das Telefon', 'Die Kanone']],
              ['Welches Ziel hatten die Tanzimat-Reformen?', 'Die Modernisierung des Reiches', ['Die Rückkehr zu Süleymans Zeit', 'Die Abschaffung des Islam', 'Den Anschluss an Russland']],
              ['Was folgte auf die Niederlagen gegen Russland im 18. Jahrhundert?', 'Gebietsverluste wie die Krim', ['Die Eroberung Moskaus', 'Ein Bündnis mit Russland', 'Die Gründung Ankaras']],
              ['Welche Gruppe wurde 1826 beseitigt?', 'Die Janitscharen', ['Die Sipahi', 'Die Derwische', 'Die Wesire']],
              ['Welches Land wurde zuerst unabhängig vom Osmanischen Reich im 19. Jahrhundert?', 'Griechenland', ['Bulgarien', 'Rumänien', 'Albanien']],
              ['Welches Ereignis führte zum Einsatz von Florence Nightingale?', 'Der Krimkrieg', ['Der Erste Weltkrieg', 'Die Belagerung Wiens', 'Der Balkankrieg']],
              ['Woher kam die Tulpe nach Holland?', 'Aus dem Osmanischen Reich', ['Aus Amerika', 'Aus Japan', 'Aus Indien direkt']],
              ['Was beschreibt der Ausdruck „kranker Mann am Bosporus“?', 'Den Niedergang des Osmanischen Reiches', ['Einen kranken Sultan', 'Eine Seuche in Istanbul', 'Einen Arzt am Bosporus']],
              ['Welcher Sultan führte die Tulpenzeit?', 'Ahmed III.', ['Selim I.', 'Mahmud II.', 'Abdülmecid I.']],
              ['Wie wurde Ungarn 1699 politisch?', 'Es fiel an die Habsburger', ['Es wurde unabhängig', 'Es blieb osmanisch', 'Es fiel an Polen']],
              ['Was war 1876 neu im Osmanischen Reich?', 'Verfassung und Parlament', ['Republik', 'Lateinische Schrift', 'Frauenwahlrecht']],
              ['Wer war İbrahim Müteferrika?', 'Ein Buchdrucker', ['Ein Admiral', 'Ein Sultan', 'Ein Großwesir']],
              ['Was bedeutet „Sultanat der Frauen“?', 'Den großen Einfluss von Frauen im Palast', ['Eine Sultanin als Herrscherin über Europa', 'Ein Frauenwahlrecht', 'Eine Armee aus Frauen']],
              ['Welches Getränk wurde über Istanbul in Europa bekannt?', 'Kaffee', ['Ayran', 'Raki', 'Tee aus China']],
            ],
          },
        },
        {
          id: 'jungtuerken-weltkrieg',
          title: 'Jungtürken, Erster Weltkrieg und Völkermord',
          date: '1876–1920',
          text: [
            'Sultan Abdülhamid II. (1876–1909) setzte die Verfassung schon 1878 wieder außer Kraft und regierte mit Zensur und Geheimpolizei. Er ließ die Bagdadbahn bauen, mit deutscher Hilfe, und nannte sich Kalif aller Muslime. 1894–1896 wurden bei Massakern Zehntausende Armenier getötet.',
            '1908 erzwangen die „Jungtürken“, Offiziere und Beamte des „Komitees für Einheit und Fortschritt“, die Wiedereinführung der Verfassung; 1909 setzten sie Abdülhamid ab. In den Balkankriegen 1912/13 verlor das Reich fast alle Gebiete in Europa. Bald herrschte ein Dreigestirn aus Enver, Talât und Cemal Pascha.',
            'Im Ersten Weltkrieg trat das Reich 1914 an der Seite Deutschlands ein. 1915 versuchten britische, französische, australische und neuseeländische Truppen, die Dardanellen bei Gallipoli zu erobern, um Istanbul zu erreichen. Nach monatelangen Kämpfen mit über 100.000 Toten mussten sie abziehen; ein junger Offizier, Mustafa Kemal, wurde dort zum Helden.',
            'Ab April 1915 ließ die jungtürkische Regierung die Armenier verhaften, deportieren und in Todesmärschen in die syrische Wüste treiben. Zwischen 800.000 und 1,5 Millionen Armenier kamen ums Leben. Auch Assyrer und Griechen wurden Opfer. Viele Staaten, darunter seit 2016 Deutschland, erkennen dies als Völkermord an; die Türkei bestreitet das bis heute. Der 24. April ist der Gedenktag.',
            '1918 musste das Reich kapitulieren, alliierte Truppen besetzten Istanbul. Im Vertrag von Sèvres 1920 sollte das Reich aufgeteilt werden: Griechenland sollte Smyrna (Izmir) erhalten, es waren ein armenischer Staat und ein kurdisches Gebiet vorgesehen. Gegen diesen Vertrag erhob sich der türkische Widerstand.',
          ],
          quiz: {
            leicht: [
              ['Welcher Sultan setzte die Verfassung 1878 außer Kraft?', 'Abdülhamid II.', ['Mahmud II.', 'Mehmed VI.', 'Süleyman']],
              ['Welche Bahn ließ Abdülhamid mit deutscher Hilfe bauen?', 'Die Bagdadbahn', ['Den Orient-Express', 'Die Transsibirische Eisenbahn', 'Die Hedschasbahn zuerst']],
              ['Wie nennt man die Reformer, die 1908 die Verfassung erzwangen?', 'Jungtürken', ['Janitscharen', 'Kemalisten', 'Derwische']],
              ['Wann setzten die Jungtürken Abdülhamid ab?', '1909', ['1908', '1914', '1923']],
              ['Was verlor das Reich in den Balkankriegen?', 'Fast alle Gebiete in Europa', ['Ägypten', 'Anatolien', 'Istanbul']],
              ['An wessen Seite trat das Reich 1914 in den Krieg?', 'An der Seite Deutschlands', ['An der Seite Englands', 'An der Seite Russlands', 'An der Seite Frankreichs']],
              ['Wo versuchten alliierte Truppen 1915 die Dardanellen zu erobern?', 'Bei Gallipoli', ['Bei Ankara', 'Bei Izmir', 'Bei Trabzon']],
              ['Wer wurde bei Gallipoli zum Helden?', 'Mustafa Kemal', ['Enver Pascha', 'Abdülhamid II.', 'Talât Pascha']],
              ['Mussten die Alliierten bei Gallipoli abziehen?', 'Ja', ['Nein, sie eroberten Istanbul', 'Nein, sie blieben bis 1923', 'Es gab keinen Kampf']],
              ['Welches Volk wurde 1915 Opfer eines Völkermords?', 'Die Armenier', ['Die Japaner', 'Die Kurden', 'Die Araber']],
              ['Wohin wurden die Armenier in Todesmärschen getrieben?', 'In die syrische Wüste', ['Nach Sibirien', 'Nach Europa', 'Ans Schwarze Meer']],
              ['Welcher Tag ist Gedenktag des Völkermords an den Armeniern?', 'Der 24. April', ['Der 29. Oktober', 'Der 10. November', 'Der 19. Mai']],
              ['Wie steht die Türkei zur Einstufung als Völkermord?', 'Sie bestreitet sie bis heute', ['Sie erkennt sie an', 'Sie hat sich entschuldigt', 'Sie äußert sich nicht']],
              ['Seit wann erkennt Deutschland den Völkermord an?', 'Seit 2016', ['Seit 1915', 'Seit 1990', 'Seit 2023']],
              ['Wann kapitulierte das Osmanische Reich?', '1918', ['1915', '1920', '1923']],
              ['Welche Stadt besetzten alliierte Truppen 1918?', 'Istanbul', ['Ankara', 'Konya', 'Bursa']],
              ['Welcher Vertrag sollte 1920 das Reich aufteilen?', 'Der Vertrag von Sèvres', ['Der Vertrag von Lausanne', 'Der Vertrag von Versailles', 'Der Frieden von Karlowitz']],
              ['Welches Land sollte Smyrna erhalten?', 'Griechenland', ['Italien', 'Frankreich', 'Armenien']],
              ['Wie heißt Smyrna heute?', 'Izmir', ['Istanbul', 'Antalya', 'Mersin']],
              ['Wie regierte Abdülhamid II.?', 'Mit Zensur und Geheimpolizei', ['Demokratisch', 'Mit einem Parlament', 'Gar nicht']],
            ],
            mittel: [
              ['Wann regierte Abdülhamid II.?', '1876–1909', ['1839–1861', '1909–1918', '1808–1839']],
              ['Wann setzte Abdülhamid die Verfassung außer Kraft?', '1878', ['1876', '1908', '1909']],
              ['Wie nannte sich Abdülhamid?', 'Kalif aller Muslime', ['Kaiser von Europa', 'König der Türken', 'Präsident']],
              ['Wann wurden bei Massakern Zehntausende Armenier getötet, noch vor 1915?', '1894–1896', ['1876–1878', '1908–1909', '1853–1856']],
              ['Wie hieß die Organisation der Jungtürken?', 'Komitee für Einheit und Fortschritt', ['Republikanische Volkspartei', 'Partei der Gerechtigkeit', 'Bund der Janitscharen']],
              ['Wann erzwangen die Jungtürken die Verfassung?', '1908', ['1876', '1914', '1923']],
              ['Wann fanden die Balkankriege statt?', '1912/13', ['1853–1856', '1877/78', '1919–1922']],
              ['Wer bildete das herrschende Dreigestirn?', 'Enver, Talât und Cemal Pascha', ['Atatürk, İnönü und Bayar', 'Abdülhamid, Mehmed und Murad', 'Kara Mustafa, Sinan und Barbarossa']],
              ['Wann trat das Reich in den Ersten Weltkrieg ein?', '1914', ['1915', '1912', '1918']],
              ['Welche Truppen kämpften auf alliierter Seite bei Gallipoli?', 'Britische, französische, australische und neuseeländische', ['Russische und japanische', 'Deutsche und österreichische', 'Chinesische und japanische']],
              ['Was wollten die Alliierten bei Gallipoli erreichen?', 'Istanbul', ['Ankara', 'Bagdad', 'Jerusalem']],
              ['Wie viele Tote forderte die Schlacht von Gallipoli?', 'Über 100.000', ['Rund 1.000', 'Rund 10.000', 'Über eine Million']],
              ['Wann begann die Verfolgung der Armenier 1915?', 'Im April 1915', ['Im Januar 1915', 'Im Oktober 1915', 'Im Jahr 1918']],
              ['Wie viele Armenier kamen ums Leben?', 'Zwischen 800.000 und 1,5 Millionen', ['Rund 10.000', 'Rund 100.000', 'Rund fünf Millionen']],
              ['Welche weiteren Gruppen wurden Opfer?', 'Assyrer und Griechen', ['Deutsche und Österreicher', 'Juden in Spanien', 'Perser und Araber']],
              ['Wer ließ die Armenier deportieren?', 'Die jungtürkische Regierung', ['Der Sultan Abdülhamid', 'Die Alliierten', 'Die Russen']],
              ['Wann wurde der Vertrag von Sèvres unterzeichnet?', '1920', ['1918', '1923', '1915']],
              ['Was sah der Vertrag von Sèvres vor?', 'Einen armenischen Staat und ein kurdisches Gebiet', ['Die Unabhängigkeit der Türkei in alten Grenzen', 'Ein Großosmanisches Reich', 'Den Anschluss an Deutschland']],
              ['Was folgte auf den Vertrag von Sèvres?', 'Der türkische Widerstand', ['Ruhe und Frieden', 'Die Rückkehr der Janitscharen', 'Der Zweite Weltkrieg']],
              ['Welche Meerenge liegt bei Gallipoli?', 'Die Dardanellen', ['Der Bosporus', 'Die Straße von Gibraltar', 'Der Suezkanal']],
            ],
            schwer: [
              ['Wer war Talât Pascha?', 'Ein führender Jungtürke', ['Ein armenischer Bischof', 'Ein Sultan', 'Ein britischer General']],
              ['Mit welcher Hilfe wurde die Bagdadbahn gebaut?', 'Mit deutscher Hilfe', ['Mit britischer Hilfe', 'Mit russischer Hilfe', 'Ohne Hilfe']],
              ['Was erzwangen die Jungtürken 1908?', 'Die Wiedereinführung der Verfassung', ['Die Abschaffung des Sultanats', 'Die Republik', 'Den Kriegseintritt']],
              ['Wer erkannte 2016 den Völkermord an den Armeniern an?', 'Deutschland', ['Die Türkei', 'Pakistan', 'Aserbaidschan']],
              ['Wohin führten die Todesmärsche der Armenier?', 'In die syrische Wüste', ['In den Kaukasus', 'Nach Istanbul', 'Nach Persien']],
              ['Welche Folge hatten die Balkankriege 1912/13?', 'Fast alle Gebiete in Europa gingen verloren', ['Das Reich eroberte Griechenland', 'Istanbul fiel', 'Ägypten wurde zurückgewonnen']],
              ['Welche Stadt war Ziel der alliierten Offensive 1915?', 'Istanbul', ['Ankara', 'Bagdad', 'Kairo']],
              ['Welcher spätere Staatsgründer kämpfte bei Gallipoli?', 'Mustafa Kemal', ['İsmet İnönü', 'Enver Pascha', 'Cemal Pascha']],
              ['Wann begann die Deportation der Armenier?', '1915', ['1894', '1908', '1918']],
              ['Was war der Vertrag von Sèvres für die Türken?', 'Ein Diktat zur Aufteilung', ['Ein Sieg', 'Ein Bündnis', 'Ein Handelsvertrag']],
              ['Welche Regierung leitete 1915 das Reich?', 'Die Jungtürken', ['Abdülhamid II.', 'Atatürk', 'Die Alliierten']],
              ['Wie viele Menschen starben 1894–1896 bei Massakern an Armeniern?', 'Zehntausende', ['Einige Dutzend', 'Millionen', 'Keine']],
              ['Wann musste das Osmanische Reich kapitulieren?', '1918', ['1917', '1920', '1922']],
              ['Welches Gebiet sollte Griechenland laut Sèvres erhalten?', 'Smyrna (Izmir)', ['Istanbul', 'Ankara', 'Trabzon']],
              ['Welcher Pascha gehörte nicht zum Dreigestirn?', 'Kara Mustafa', ['Enver', 'Talât', 'Cemal']],
              ['Was bedeutet die Abkürzung „Jungtürken“ politisch?', 'Reformorientierte Offiziere und Beamte', ['Junge Sultane', 'Eine Fußballmannschaft', 'Eine Kinderarmee']],
              ['Welche Truppen aus dem Pazifik kämpften bei Gallipoli?', 'Australier und Neuseeländer', ['Japaner', 'Chinesen', 'Kanadier']],
              ['Was ist der 24. April für Armenier?', 'Gedenktag des Völkermords', ['Nationalfeiertag der Unabhängigkeit', 'Neujahr', 'Tag der Sprache']],
              ['Was ließ Abdülhamid gegen Kritiker einsetzen?', 'Geheimpolizei und Zensur', ['Wahlen', 'Ein freies Parlament', 'Zeitungen']],
              ['Welches Gebiet war im Vertrag von Sèvres für die Kurden vorgesehen?', 'Ein kurdisches Gebiet', ['Istanbul', 'Thrakien', 'Zypern']],
            ],
          },
        },
      ],
    },
    {
      id: 'atatuerk',
      title: 'Atatürk und die Republik',
      date: '1919–1938',
      text: [
        'Unter Mustafa Kemal erkämpften die Türken im Befreiungskrieg einen eigenen Staat. 1923 wurde die Republik Türkei mit der Hauptstadt Ankara gegründet. Atatürk schaffte Sultanat und Kalifat ab, führte die lateinische Schrift ein und machte die Türkei zu einem weltlichen Staat nach europäischem Vorbild.',
      ],
      subtopics: [
        {
          id: 'befreiungskrieg',
          title: 'Der Befreiungskrieg und die Gründung der Republik',
          date: '1919–1923',
          text: [
            'Am 19. Mai 1919 landete Mustafa Kemal in Samsun am Schwarzen Meer und organisierte den Widerstand gegen die Besatzung; der 19. Mai ist heute Feiertag der Jugend und des Sports. Wenige Tage zuvor waren griechische Truppen in Smyrna gelandet. Im April 1920 trat in Ankara eine eigene „Große Nationalversammlung“ zusammen, die die Regierung des Sultans in Istanbul nicht mehr anerkannte.',
            'Die griechische Armee stieß tief nach Anatolien vor. 1921 hielten die Türken sie in der Schlacht am Sakarya auf, die 22 Tage dauerte. Im August 1922 brach Mustafa Kemal mit der „Großen Offensive“ die griechische Front, und am 9. September 1922 zogen türkische Truppen in Izmir ein; die Stadt ging danach in Flammen auf. Mit Frankreich und Italien hatte er schon zuvor Frieden geschlossen, mit Sowjetrussland Verträge über die Grenzen im Osten.',
            'Im November 1922 schaffte die Nationalversammlung das Sultanat ab; der letzte Sultan Mehmed VI. floh auf einem britischen Kriegsschiff. Im Vertrag von Lausanne vom 24. Juli 1923 erkannten die Siegermächte die Türkei in ihren heutigen Grenzen weitgehend an; Sèvres war damit hinfällig. Vereinbart wurde auch ein Bevölkerungsaustausch: Rund 1,2 Millionen orthodoxe Christen mussten nach Griechenland, rund 400.000 Muslime in die Türkei.',
            'Am 13. Oktober 1923 wurde Ankara Hauptstadt, und am 29. Oktober 1923 rief die Nationalversammlung die Republik Türkei aus. Mustafa Kemal wurde ihr erster Präsident. Der 29. Oktober ist heute Nationalfeiertag, der „Tag der Republik“.',
            'Ankara war damals eine kleine Stadt in der Steppe, aber in der Mitte Anatoliens und weit weg vom besetzten Istanbul. Erster Ministerpräsident wurde İsmet Pascha, später İsmet İnönü genannt, der als Feldherr im Befreiungskrieg und als Verhandlungsführer in Lausanne bekannt geworden war.',
          ],
          quiz: {
            leicht: [
              ['Wer führte den türkischen Befreiungskrieg?', 'Mustafa Kemal', ['Enver Pascha', 'Mehmed VI.', 'Abdülhamid II.']],
              ['Wo landete Mustafa Kemal am 19. Mai 1919?', 'In Samsun', ['In Izmir', 'In Istanbul', 'In Ankara']],
              ['An welchem Meer liegt Samsun?', 'Am Schwarzen Meer', ['Am Mittelmeer', 'An der Ägäis', 'Am Roten Meer']],
              ['Was feiert die Türkei am 19. Mai?', 'Den Tag der Jugend und des Sports', ['Den Tag der Republik', 'Neujahr', 'Den Tag der Arbeit']],
              ['Wo trat 1920 die Große Nationalversammlung zusammen?', 'In Ankara', ['In Istanbul', 'In Izmir', 'In Bursa']],
              ['Gegen welche Armee kämpfte die Türkei im Befreiungskrieg vor allem?', 'Gegen die griechische', ['Gegen die deutsche', 'Gegen die russische', 'Gegen die persische']],
              ['Wo hielten die Türken 1921 die Griechen auf?', 'Am Sakarya', ['Bei Gallipoli', 'Bei Manzikert', 'Bei Ankara im Zentrum']],
              ['Welche Stadt eroberten türkische Truppen am 9. September 1922?', 'Izmir', ['Istanbul', 'Athen', 'Edirne']],
              ['Wann wurde das Sultanat abgeschafft?', 'Im November 1922', ['Im Oktober 1923', 'Im März 1924', 'Im Jahr 1918']],
              ['Wie floh der letzte Sultan?', 'Auf einem britischen Kriegsschiff', ['Mit dem Flugzeug', 'Zu Pferd nach Persien', 'Mit dem Orient-Express']],
              ['Wie hieß der letzte Sultan?', 'Mehmed VI.', ['Abdülhamid II.', 'Mahmud II.', 'Selim III.']],
              ['Welcher Vertrag erkannte 1923 die Türkei an?', 'Der Vertrag von Lausanne', ['Der Vertrag von Sèvres', 'Der Vertrag von Versailles', 'Der Vertrag von Karlowitz']],
              ['Was wurde in Lausanne außer den Grenzen vereinbart?', 'Ein Bevölkerungsaustausch mit Griechenland', ['Ein Bündnis mit Deutschland', 'Der Beitritt zur NATO', 'Die Rückgabe Ägyptens']],
              ['Welche Stadt wurde 1923 Hauptstadt der Türkei?', 'Ankara', ['Istanbul', 'Izmir', 'Konya']],
              ['Wann wurde die Republik Türkei ausgerufen?', 'Am 29. Oktober 1923', ['Am 19. Mai 1919', 'Am 24. Juli 1923', 'Am 10. November 1938']],
              ['Wer wurde erster Präsident der Türkei?', 'Mustafa Kemal', ['İsmet İnönü', 'Celal Bayar', 'Enver Pascha']],
              ['Wie heißt der 29. Oktober?', 'Tag der Republik', ['Tag der Jugend', 'Tag des Sieges', 'Tag der Sprache']],
              ['Wer wurde erster Ministerpräsident?', 'İsmet İnönü', ['Mustafa Kemal', 'Adnan Menderes', 'Celal Bayar']],
              ['Warum wählte man Ankara als Hauptstadt?', 'Es lag mitten in Anatolien, fern vom besetzten Istanbul', ['Es hatte den größten Hafen', 'Es war die größte Stadt', 'Es lag am Meer']],
              ['Was war Ankara damals?', 'Eine kleine Stadt in der Steppe', ['Eine Millionenstadt', 'Ein Hafen', 'Eine Insel']],
            ],
            mittel: [
              ['Wann landete Mustafa Kemal in Samsun?', 'Am 19. Mai 1919', ['Am 29. Oktober 1923', 'Am 9. September 1922', 'Am 23. April 1920']],
              ['Wer war kurz vor Mustafa Kemals Landung in Smyrna gelandet?', 'Griechische Truppen', ['Britische Truppen', 'Italienische Truppen', 'Russische Truppen']],
              ['Wann trat die Große Nationalversammlung in Ankara zusammen?', 'Im April 1920', ['Im Mai 1919', 'Im Oktober 1923', 'Im November 1922']],
              ['Welche Regierung erkannte die Nationalversammlung nicht mehr an?', 'Die des Sultans in Istanbul', ['Die griechische', 'Die französische', 'Die sowjetische']],
              ['Wie lange dauerte die Schlacht am Sakarya?', '22 Tage', ['2 Tage', '22 Monate', '2 Jahre']],
              ['Wann fand die Schlacht am Sakarya statt?', '1921', ['1919', '1922', '1923']],
              ['Wie nennt man den entscheidenden Angriff im August 1922?', 'Große Offensive', ['Blitzkrieg', 'Frühjahrsoffensive', 'Operation Anatolien']],
              ['Was geschah mit Izmir nach dem Einzug der Türken?', 'Die Stadt ging in Flammen auf', ['Sie wurde Hauptstadt', 'Sie wurde griechisch', 'Nichts']],
              ['Mit welchen Ländern schloss Mustafa Kemal früh Frieden?', 'Mit Frankreich und Italien', ['Mit Griechenland und England', 'Mit Deutschland und Österreich', 'Mit den USA']],
              ['Mit wem schloss die Türkei Verträge über die Ostgrenze?', 'Mit Sowjetrussland', ['Mit Persien', 'Mit Großbritannien', 'Mit Armenien unter den Alliierten']],
              ['Wann wurde der Vertrag von Lausanne unterzeichnet?', 'Am 24. Juli 1923', ['Am 29. Oktober 1923', 'Am 10. August 1920', 'Am 11. November 1918']],
              ['Welcher Vertrag wurde durch Lausanne hinfällig?', 'Der Vertrag von Sèvres', ['Der Vertrag von Karlowitz', 'Der Versailler Vertrag', 'Das Abkommen von Mudros']],
              ['Wie viele orthodoxe Christen mussten nach Griechenland?', 'Rund 1,2 Millionen', ['Rund 12.000', 'Rund 120.000', 'Rund 12 Millionen']],
              ['Wie viele Muslime kamen aus Griechenland in die Türkei?', 'Rund 400.000', ['Rund 40.000', 'Rund vier Millionen', 'Rund 4.000']],
              ['Wann wurde Ankara Hauptstadt?', 'Am 13. Oktober 1923', ['Am 29. Oktober 1923', 'Am 23. April 1920', 'Am 1. November 1922']],
              ['Wofür war İsmet Pascha bekannt geworden?', 'Als Feldherr und Verhandlungsführer in Lausanne', ['Als Sultan', 'Als Dichter', 'Als Architekt']],
              ['Wie hieß İsmet Pascha später?', 'İsmet İnönü', ['İsmet Atatürk', 'İsmet Bayar', 'İsmet Menderes']],
              ['Wo lag Ankara geographisch?', 'In der Mitte Anatoliens', ['Am Bosporus', 'An der Ägäis', 'Am Schwarzen Meer']],
              ['Wie weit erkannte Lausanne die Grenzen der Türkei an?', 'Weitgehend in den heutigen Grenzen', ['In den Grenzen von 1566', 'Nur Anatolien ohne Istanbul', 'Gar nicht']],
              ['Wie reagierte Mustafa Kemal auf die Besatzung 1919?', 'Er organisierte den Widerstand', ['Er floh nach Deutschland', 'Er wurde Sultan', 'Er schloss sich den Griechen an']],
            ],
            schwer: [
              ['Was entschied die Schlacht am Sakarya?', 'Sie stoppte den griechischen Vormarsch', ['Sie eroberte Istanbul', 'Sie beendete den Ersten Weltkrieg', 'Sie verlor Ankara']],
              ['Was symbolisiert der 19. Mai?', 'Den Beginn des Befreiungskampfes', ['Die Gründung der Republik', 'Den Tod Atatürks', 'Den Sieg bei Gallipoli']],
              ['Wann zogen türkische Truppen in Izmir ein?', 'Am 9. September 1922', ['Am 30. August 1922', 'Am 19. Mai 1919', 'Am 24. Juli 1923']],
              ['Welche Kriterien entschieden den Bevölkerungsaustausch?', 'Die Religion', ['Die Sprache', 'Der Wohnort', 'Das Vermögen']],
              ['Wann wurde die Nationalversammlung eröffnet?', 'Im April 1920', ['Im Mai 1919', 'Im Oktober 1923', 'Im Juli 1923']],
              ['Wie hieß der letzte osmanische Sultan?', 'Mehmed VI.', ['Mehmed V.', 'Abdülmecid II.', 'Murad V.']],
              ['Welches Land unterstützte die Flucht des Sultans?', 'Großbritannien', ['Frankreich', 'Griechenland', 'Deutschland']],
              ['Wann endete die Monarchie in der Türkei?', '1922 mit der Abschaffung des Sultanats', ['1908', '1938', '1918']],
              ['Wann genau wurde die Republik ausgerufen?', '29. Oktober 1923', ['13. Oktober 1923', '24. Juli 1923', '1. November 1922']],
              ['Welche Stadt war 1919–1923 von Alliierten besetzt?', 'Istanbul', ['Ankara', 'Samsun', 'Erzurum']],
              ['Mit welchem Nachbarn tauschte die Türkei Bevölkerung aus?', 'Mit Griechenland', ['Mit Bulgarien', 'Mit Armenien', 'Mit Persien']],
              ['Welche Rolle spielte İnönü in Lausanne?', 'Er war Verhandlungsführer', ['Er war Gegner des Vertrags', 'Er war britischer Gesandter', 'Er war nicht anwesend']],
              ['Was erkannten die Siegermächte in Lausanne an?', 'Die Türkei in weitgehend heutigen Grenzen', ['Einen armenischen Staat', 'Ein griechisches Smyrna', 'Ein Kalifat in Mekka']],
              ['Welches Ereignis nennt man „Große Offensive“?', 'Den entscheidenden Angriff im August 1922', ['Die Landung in Samsun', 'Den Angriff auf Gallipoli', 'Die Eroberung Konstantinopels']],
              ['In welcher Stadt wurde die neue Regierung gebildet?', 'In Ankara', ['In Istanbul', 'In Izmir', 'In Samsun']],
              ['Wer erkannte die Regierung in Ankara zuerst durch Verträge an?', 'Sowjetrussland', ['Großbritannien', 'Griechenland', 'Die USA']],
              ['Was beendete der Vertrag von Lausanne?', 'Den Befreiungskrieg', ['Den Ersten Weltkrieg in Europa', 'Den Zweiten Weltkrieg', 'Die Tanzimat-Reformen']],
              ['Wie wurde Smyrna nach 1922?', 'Türkisch', ['Griechisch', 'Italienisch', 'Britisch']],
              ['Wie lange dauerte der Befreiungskrieg ungefähr?', 'Von 1919 bis 1922', ['Von 1914 bis 1918', 'Von 1923 bis 1938', 'Ein Jahr']],
              ['Welcher Tag ist der wichtigste Nationalfeiertag der Türkei?', 'Der 29. Oktober', ['Der 19. Mai', 'Der 23. April', 'Der 30. August']],
            ],
          },
        },
        {
          id: 'atatuerk-reformen',
          title: 'Atatürks Reformen',
          date: '1924–1938',
          text: [
            '1924 schaffte die Türkei das Kalifat ab; die religiösen Gerichte und Schulen wurden geschlossen. Der Staat sollte „laizistisch“ sein, also Religion und Staat trennen. 1926 wurde nach Schweizer Vorbild ein neues Zivilgesetzbuch eingeführt, das die Vielehe verbot und Frauen mehr Rechte gab.',
            'Auch das Äußere sollte sich ändern: 1925 verbot das „Hutgesetz“ den traditionellen Fes für Männer, stattdessen sollten sie Hüte tragen. Der westliche Kalender und die Uhrzeit wurden übernommen, 1935 wurde der Sonntag Ruhetag.',
            '1928 ersetzte die lateinische Schrift die arabische. Mustafa Kemal reiste selbst mit einer Tafel durchs Land und brachte den Menschen die neuen Buchstaben bei; man nannte ihn deshalb auch „Oberlehrer der Nation“. In Volksschulen und Abendkursen lernten Millionen lesen. Später wurden viele arabische und persische Wörter durch türkische ersetzt.',
            'Frauen erhielten 1930 das Wahlrecht bei Kommunalwahlen und 1934 bei Parlamentswahlen – früher als in Frankreich oder Italien. 1934 mussten alle Türken einen Familiennamen annehmen; das Parlament gab Mustafa Kemal den Namen „Atatürk“, „Vater der Türken“. Im selben Jahr wurde die Hagia Sophia ein Museum.',
            'Es gab nur eine Partei, die Republikanische Volkspartei, und Aufstände, etwa der Kurden, wurden niedergeschlagen. Atatürk starb am 10. November 1938 um 9:05 Uhr im Dolmabahçe-Palast in Istanbul. Jedes Jahr steht die Türkei zu dieser Uhrzeit eine Minute still. Sein Mausoleum, das Anıtkabir, steht in Ankara. Sein Nachfolger wurde İsmet İnönü.',
          ],
          quiz: {
            leicht: [
              ['Was schaffte die Türkei 1924 ab?', 'Das Kalifat', ['Die Republik', 'Das Parlament', 'Den Islam']],
              ['Was bedeutet „laizistisch“?', 'Trennung von Religion und Staat', ['Herrschaft der Religion', 'Herrschaft des Militärs', 'Herrschaft des Sultans']],
              ['Nach welchem Vorbild wurde 1926 ein Zivilgesetzbuch eingeführt?', 'Nach Schweizer Vorbild', ['Nach britischem Vorbild', 'Nach persischem Vorbild', 'Nach sowjetischem Vorbild']],
              ['Was verbot das neue Zivilgesetzbuch?', 'Die Vielehe', ['Die Ehe', 'Das Erben', 'Die Arbeit von Männern']],
              ['Welche Kopfbedeckung verbot das Hutgesetz?', 'Den Fes', ['Den Hut', 'Das Kopftuch der Frauen', 'Den Helm']],
              ['Was sollten Männer stattdessen tragen?', 'Hüte', ['Turbane', 'Fese', 'Mützen der Janitscharen']],
              ['Welche Schrift wurde 1928 eingeführt?', 'Die lateinische', ['Die arabische', 'Die kyrillische', 'Die griechische']],
              ['Welche Schrift wurde 1928 abgelöst?', 'Die arabische', ['Die lateinische', 'Die kyrillische', 'Die Runenschrift']],
              ['Wie nannte man Mustafa Kemal wegen des Schriftunterrichts?', 'Oberlehrer der Nation', ['Vater der Schrift', 'Herr der Buchstaben', 'Großer Gelehrter']],
              ['Wann erhielten Frauen das Wahlrecht bei Parlamentswahlen?', '1934', ['1923', '1946', '1950']],
              ['Was mussten alle Türken 1934 annehmen?', 'Einen Familiennamen', ['Eine neue Religion', 'Einen Hut', 'Einen Pass']],
              ['Was bedeutet „Atatürk“?', 'Vater der Türken', ['Held der Türken', 'Herr der Türken', 'Freund der Türken']],
              ['Was wurde die Hagia Sophia 1934?', 'Ein Museum', ['Eine Kirche', 'Eine Moschee', 'Ein Parlament']],
              ['Wie viele Parteien gab es unter Atatürk?', 'Nur eine', ['Zwei', 'Viele', 'Keine']],
              ['Wie hieß Atatürks Partei?', 'Republikanische Volkspartei', ['Partei für Gerechtigkeit und Aufschwung', 'Demokratische Partei', 'Komitee für Einheit und Fortschritt']],
              ['Wann starb Atatürk?', 'Am 10. November 1938', ['Am 29. Oktober 1938', 'Am 19. Mai 1938', 'Am 10. November 1923']],
              ['Wo starb Atatürk?', 'Im Dolmabahçe-Palast in Istanbul', ['In Ankara', 'In Samsun', 'In Thessaloniki']],
              ['Was geschieht jedes Jahr um 9:05 Uhr am 10. November?', 'Die Türkei steht eine Minute still', ['Es wird ein Feuerwerk gezündet', 'Die Schulen haben frei', 'Der Präsident hält eine Wahl ab']],
              ['Wo steht Atatürks Mausoleum?', 'In Ankara', ['In Istanbul', 'In Samsun', 'In Izmir']],
              ['Wer wurde Atatürks Nachfolger?', 'İsmet İnönü', ['Celal Bayar', 'Adnan Menderes', 'Enver Pascha']],
            ],
            mittel: [
              ['Was wurde 1924 zusammen mit dem Kalifat geschlossen?', 'Religiöse Gerichte und Schulen', ['Alle Moscheen', 'Alle Fabriken', 'Die Universitäten']],
              ['Wann wurde das neue Zivilgesetzbuch eingeführt?', '1926', ['1924', '1928', '1934']],
              ['Wann wurde das Hutgesetz erlassen?', '1925', ['1928', '1934', '1923']],
              ['Welcher Tag wurde 1935 Ruhetag?', 'Der Sonntag', ['Der Freitag', 'Der Samstag', 'Der Montag']],
              ['Was übernahm die Türkei außer der Schrift aus dem Westen?', 'Kalender und Uhrzeit', ['Die Religion', 'Die Sprache', 'Die Monarchie']],
              ['Wie brachte Mustafa Kemal den Menschen die neuen Buchstaben bei?', 'Er reiste mit einer Tafel durchs Land', ['Per Radio', 'Mit Büchern aus Frankreich', 'Gar nicht']],
              ['Wo lernten Millionen Türken lesen?', 'In Volksschulen und Abendkursen', ['Im Ausland', 'In Kirchen', 'In der Armee ausschließlich']],
              ['Welche Wörter wurden später durch türkische ersetzt?', 'Arabische und persische Wörter', ['Englische Wörter', 'Chinesische Wörter', 'Deutsche Wörter']],
              ['Wann erhielten Frauen das Wahlrecht bei Kommunalwahlen?', '1930', ['1934', '1923', '1946']],
              ['In welchen Ländern erhielten Frauen das Wahlrecht später als in der Türkei?', 'In Frankreich und Italien', ['In Finnland und Neuseeland', 'In den USA und Großbritannien', 'In Norwegen und Dänemark']],
              ['Wer gab Mustafa Kemal den Namen Atatürk?', 'Das Parlament', ['Der Papst', 'Das Volk per Abstimmung', 'Er selbst ohne Beschluss']],
              ['Wann wurde die Hagia Sophia Museum?', '1934', ['1453', '1923', '2020']],
              ['Was geschah mit Aufständen, etwa der Kurden?', 'Sie wurden niedergeschlagen', ['Sie führten zur Unabhängigkeit', 'Sie wurden belohnt', 'Es gab keine']],
              ['Um wie viel Uhr starb Atatürk?', 'Um 9:05 Uhr', ['Um 12:00 Uhr', 'Um 19:19 Uhr', 'Um 6:30 Uhr']],
              ['Wie heißt Atatürks Mausoleum?', 'Anıtkabir', ['Topkapı', 'Dolmabahçe', 'Süleymaniye']],
              ['Was gab das Zivilgesetzbuch Frauen?', 'Mehr Rechte', ['Weniger Rechte', 'Keine Rechte', 'Das Recht auf Vielehe']],
              ['Was war die Folge des Hutgesetzes?', 'Der Fes wurde verboten', ['Der Hut wurde verboten', 'Frauen mussten Hüte tragen', 'Die Janitscharen kehrten zurück']],
              ['Was sollte die Schriftreform bewirken?', 'Dass mehr Menschen lesen lernen', ['Dass niemand mehr liest', 'Dass alle Arabisch sprechen', 'Dass Bücher verboten werden']],
              ['Welches Gesetz verlangte 1934 Familiennamen?', 'Das Familiennamengesetz', ['Das Hutgesetz', 'Das Zivilgesetzbuch', 'Die Verfassung von 1876']],
              ['Was bedeutete die Abschaffung des Kalifats?', 'Der türkische Staat war nicht mehr religiöses Oberhaupt der Muslime', ['Der Islam wurde verboten', 'Die Türkei wurde katholisch', 'Mekka wurde türkisch']],
            ],
            schwer: [
              ['Was ist das Anıtkabir?', 'Atatürks Mausoleum', ['Ein Palast in Istanbul', 'Eine Moschee in Edirne', 'Ein Museum in Izmir']],
              ['Welches Land diente als Vorbild für das Zivilgesetzbuch?', 'Die Schweiz', ['Frankreich', 'Deutschland', 'Italien']],
              ['In welchem Jahr wurde die Schriftreform eingeführt?', '1928', ['1924', '1926', '1934']],
              ['Welche Reform betraf 1935 den Wochenrhythmus?', 'Der Sonntag wurde Ruhetag', ['Der Freitag wurde Ruhetag', 'Die Fünftagewoche', 'Der Samstag wurde abgeschafft']],
              ['Wie lange steht die Türkei am 10. November still?', 'Eine Minute', ['Eine Stunde', 'Einen Tag', 'Zehn Sekunden']],
              ['Welche Folge hatte das Familiennamengesetz für Mustafa Kemal?', 'Er erhielt den Namen Atatürk', ['Er verlor seinen Namen', 'Er hieß nun Gazi', 'Er wurde Kalif']],
              ['Wann erhielten Frauen das kommunale Wahlrecht?', '1930', ['1934', '1926', '1924']],
              ['Was wurde 1924 abgeschafft?', 'Das Kalifat', ['Das Sultanat', 'Die Republik', 'Die Nationalversammlung']],
              ['Welche Gerichte wurden 1924 geschlossen?', 'Religiöse Gerichte', ['Alle Gerichte', 'Militärgerichte', 'Handelsgerichte']],
              ['Welche Partei regierte allein bis nach Atatürks Tod?', 'Die Republikanische Volkspartei', ['Die Demokratische Partei', 'Die Jungtürken', 'Die Partei der Gerechtigkeit']],
              ['Wer führte die Türkei nach 1938?', 'İsmet İnönü', ['Adnan Menderes', 'Celal Bayar', 'Turgut Özal']],
              ['Welcher Teil der Reformen betraf die Sprache?', 'Ersatz arabischer und persischer Wörter', ['Einführung des Englischen', 'Verbot des Türkischen', 'Einführung des Französischen']],
              ['Welcher Palast war Atatürks Sterbeort?', 'Dolmabahçe', ['Topkapı', 'Yıldız', 'Çankaya']],
              ['Was unterschied die Türkei 1934 im Frauenwahlrecht von Frankreich?', 'Türkische Frauen konnten früher wählen', ['Französische Frauen wählten früher', 'Beide gleichzeitig', 'In der Türkei gab es kein Wahlrecht']],
              ['Was war die Hagia Sophia vor 1934?', 'Eine Moschee', ['Ein Museum', 'Ein Bahnhof', 'Ein Palast']],
              ['Was verband Atatürk mit der Schriftreform persönlich?', 'Er unterrichtete selbst an der Tafel', ['Er schrieb nur Arabisch', 'Er war dagegen', 'Er überließ sie den Imamen']],
              ['Was bedeutete die Einführung des westlichen Kalenders?', 'Annäherung an Europa', ['Rückkehr zur Osmanenzeit', 'Einführung des chinesischen Kalenders', 'Abschaffung der Zeitrechnung']],
              ['Welcher Grundsatz trennte Religion und Staat?', 'Der Laizismus', ['Der Panturkismus', 'Der Panislamismus', 'Der Osmanismus']],
              ['Welche Volksgruppe erhob sich unter anderem gegen den neuen Staat?', 'Die Kurden', ['Die Griechen in Athen', 'Die Japaner', 'Die Franzosen']],
              ['Wann starb Atatürk?', '1938', ['1934', '1945', '1923']],
            ],
          },
        },
      ],
    },
  ],
};
