import type { Epoch } from '../types';

export const E4: Epoch = {
  id: 'moderne',
  name: 'Die moderne Türkei',
  period: 'seit 1938',
  events: [
    {
      id: 'gegenwart',
      title: 'NATO, Gastarbeiter und Gegenwart',
      date: 'seit 1938',
      text: [
        'Nach Atatürk wurde die Türkei eine Mehrparteiendemokratie und NATO-Mitglied, doch das Militär putschte mehrmals. Millionen Türken gingen als Gastarbeiter nach Europa. Seit 2003 prägt Recep Tayyip Erdoğan das Land, das 2017 ein Präsidialsystem einführte.',
      ],
      subtopics: [
        {
          id: 'inoenue-putsche',
          title: 'Mehrparteien, NATO und Militärputsche',
          date: '1938–1980',
          text: [
            'Unter Präsident İsmet İnönü blieb die Türkei im Zweiten Weltkrieg fast bis zum Ende neutral und erklärte Deutschland erst im Februar 1945 den Krieg, um Gründungsmitglied der Vereinten Nationen zu werden. In den 1930er- und 1940er-Jahren fanden viele deutsche Wissenschaftler, die vor den Nazis geflohen waren, Zuflucht an türkischen Universitäten, darunter der spätere Berliner Bürgermeister Ernst Reuter.',
            '1946 wurden andere Parteien zugelassen. Bei der Wahl 1950 siegte die Demokratische Partei, und Adnan Menderes wurde Ministerpräsident. Die Türkei schickte Soldaten in den Koreakrieg und trat 1952 der NATO bei. 1955 kam es in Istanbul zu einem Pogrom gegen Griechen, Armenier und Juden.',
            'Am 27. Mai 1960 putschte das Militär; Menderes wurde 1961 hingerichtet. Danach verstand sich die Armee als Wächterin von Atatürks Erbe und griff 1971 mit einem Memorandum und 1980 mit einem weiteren Putsch in die Politik ein.',
            '1961 schloss die Türkei mit der Bundesrepublik Deutschland ein Anwerbeabkommen. Hunderttausende Türken kamen als „Gastarbeiter“ nach Deutschland, viele blieben mit ihren Familien. Heute leben rund drei Millionen Menschen mit türkischen Wurzeln in Deutschland.',
            '1974 putschte die griechische Militärjunta auf Zypern, um die Insel an Griechenland anzuschließen. Daraufhin landeten türkische Truppen im Norden Zyperns; seitdem ist die Insel geteilt, und nur die Türkei erkennt die „Türkische Republik Nordzypern“ an. In den 1970er-Jahren kämpften linke und rechte Gruppen auf der Straße gegeneinander, Tausende starben. Am 12. September 1980 übernahm das Militär unter General Kenan Evren die Macht.',
          ],
          quiz: {
            leicht: [
              ['Wer war Präsident nach Atatürk?', 'İsmet İnönü', ['Adnan Menderes', 'Kenan Evren', 'Turgut Özal']],
              ['Wie verhielt sich die Türkei fast den ganzen Zweiten Weltkrieg?', 'Neutral', ['Sie kämpfte für Deutschland', 'Sie kämpfte für die Sowjetunion', 'Sie wurde besetzt']],
              ['Wann erklärte die Türkei Deutschland den Krieg?', 'Im Februar 1945', ['Im September 1939', 'Im Juni 1941', 'Nie']],
              ['Wer fand an türkischen Universitäten Zuflucht?', 'Deutsche Wissenschaftler auf der Flucht vor den Nazis', ['Russische Zaren', 'Britische Soldaten', 'Japanische Diplomaten']],
              ['Welcher spätere Berliner Bürgermeister lebte im türkischen Exil?', 'Ernst Reuter', ['Willy Brandt', 'Konrad Adenauer', 'Klaus Wowereit']],
              ['Welche Partei siegte bei der Wahl 1950?', 'Die Demokratische Partei', ['Die Republikanische Volkspartei', 'Die AKP', 'Die Kommunisten']],
              ['Wer wurde 1950 Ministerpräsident?', 'Adnan Menderes', ['İsmet İnönü', 'Turgut Özal', 'Süleyman Demirel']],
              ['Wann trat die Türkei der NATO bei?', '1952', ['1945', '1961', '1974']],
              ['In welchen Krieg schickte die Türkei Soldaten?', 'In den Koreakrieg', ['In den Vietnamkrieg', 'In den Golfkrieg', 'In den Falklandkrieg']],
              ['Wann putschte das Militär zum ersten Mal?', 'Am 27. Mai 1960', ['Am 12. September 1980', 'Am 15. Juli 2016', 'Am 29. Oktober 1923']],
              ['Was geschah 1961 mit Menderes?', 'Er wurde hingerichtet', ['Er wurde Präsident', 'Er floh nach Deutschland', 'Er gewann die Wahl']],
              ['Als was verstand sich die Armee?', 'Als Wächterin von Atatürks Erbe', ['Als Dienerin des Sultans', 'Als Truppe der UNO', 'Als Polizei Istanbuls']],
              ['Mit welchem Land schloss die Türkei 1961 ein Anwerbeabkommen?', 'Mit der Bundesrepublik Deutschland', ['Mit Frankreich', 'Mit den USA', 'Mit der DDR']],
              ['Wie nannte man die türkischen Arbeitskräfte in Deutschland?', 'Gastarbeiter', ['Grenzgänger', 'Saisonniers', 'Pendler']],
              ['Wie viele Menschen mit türkischen Wurzeln leben heute etwa in Deutschland?', 'Rund drei Millionen', ['Rund 30.000', 'Rund 300.000', 'Rund 30 Millionen']],
              ['Welche Insel ist seit 1974 geteilt?', 'Zypern', ['Kreta', 'Rhodos', 'Malta']],
              ['Wer erkennt die Türkische Republik Nordzypern an?', 'Nur die Türkei', ['Alle EU-Staaten', 'Die UNO', 'Griechenland']],
              ['Wann übernahm das Militär 1980 die Macht?', 'Am 12. September 1980', ['Am 27. Mai 1980', 'Am 15. Juli 1980', 'Am 1. Januar 1980']],
              ['Welcher General führte den Putsch 1980?', 'Kenan Evren', ['İsmet İnönü', 'Enver Pascha', 'Cemal Gürsel']],
              ['Wann wurden andere Parteien zugelassen?', '1946', ['1923', '1950', '1960']],
            ],
            mittel: [
              ['Warum erklärte die Türkei Deutschland 1945 den Krieg?', 'Um Gründungsmitglied der Vereinten Nationen zu werden', ['Weil Deutschland angriff', 'Um Zypern zu erhalten', 'Weil die NATO es verlangte']],
              ['Wann fanden deutsche Wissenschaftler Zuflucht in der Türkei?', 'In den 1930er- und 1940er-Jahren', ['In den 1960er-Jahren', 'Im 19. Jahrhundert', 'Nach 1990']],
              ['Was geschah 1955 in Istanbul?', 'Ein Pogrom gegen Griechen, Armenier und Juden', ['Ein Erdbeben', 'Die Olympischen Spiele', 'Ein Putsch']],
              ['Welche Haltung hatte das Militär nach 1960?', 'Es griff mehrmals in die Politik ein', ['Es blieb neutral', 'Es wurde abgeschafft', 'Es unterstützte das Kalifat']],
              ['Womit griff das Militär 1971 ein?', 'Mit einem Memorandum', ['Mit einem Bürgerkrieg', 'Mit einer Wahl', 'Mit einer Revolution der Bauern']],
              ['Wie viele Türken kamen als Gastarbeiter nach Deutschland?', 'Hunderttausende', ['Einige Dutzend', 'Einige Hundert', 'Keine']],
              ['Was taten viele Gastarbeiter auf Dauer?', 'Sie blieben mit ihren Familien', ['Sie kehrten alle nach einem Jahr zurück', 'Sie zogen nach Amerika', 'Sie wurden Beamte in Ankara']],
              ['Wer putschte 1974 auf Zypern?', 'Die griechische Militärjunta', ['Die türkische Armee', 'Großbritannien', 'Die UNO']],
              ['Was wollte die griechische Junta mit dem Putsch?', 'Zypern an Griechenland anschließen', ['Zypern teilen', 'Zypern der Türkei geben', 'Zypern unabhängig machen']],
              ['Wo landeten türkische Truppen 1974?', 'Im Norden Zyperns', ['Auf Kreta', 'In Athen', 'Im Süden Zyperns']],
              ['Was geschah in den 1970er-Jahren auf den Straßen?', 'Linke und rechte Gruppen kämpften gegeneinander', ['Es war völlig friedlich', 'Es gab Militärparaden', 'Es fanden Olympische Spiele statt']],
              ['Wie viele Menschen starben in den Straßenkämpfen der 1970er?', 'Tausende', ['Niemand', 'Zehn', 'Millionen']],
              ['Wann wurde Menderes hingerichtet?', '1961', ['1960', '1950', '1971']],
              ['Wann intervenierte das Militär per Memorandum?', '1971', ['1960', '1980', '1997']],
              ['Wie lange blieb die Türkei im Zweiten Weltkrieg neutral?', 'Fast bis zum Ende', ['Gar nicht', 'Nur ein Jahr', 'Bis 1940']],
              ['Welches Ereignis machte die Türkei 1952 zum westlichen Verbündeten?', 'Der NATO-Beitritt', ['Der EU-Beitritt', 'Der Warschauer Pakt', 'Der Zypernkrieg']],
              ['Wer war Ernst Reuter?', 'Ein deutscher Politiker im türkischen Exil', ['Ein türkischer General', 'Ein Gastarbeiter', 'Ein Sultan']],
              ['Welche Partei regierte vor 1950?', 'Die Republikanische Volkspartei', ['Die Demokratische Partei', 'Die AKP', 'Die MHP']],
              ['Wie heißt der Staat im Norden Zyperns?', 'Türkische Republik Nordzypern', ['Republik Zypern', 'Griechisch-Zypern', 'Zypriotisches Kalifat']],
              ['Welches Jahr markiert den Beginn der türkischen Migration nach Deutschland?', '1961', ['1945', '1974', '1990']],
            ],
            schwer: [
              ['Welche Gruppen waren Opfer des Pogroms von 1955?', 'Griechen, Armenier und Juden', ['Kurden und Araber', 'Deutsche und Briten', 'Russen und Georgier']],
              ['Welches Datum hatte der erste Militärputsch?', '27. Mai 1960', ['12. September 1980', '12. März 1971', '15. Juli 2016']],
              ['Wann erklärte die Türkei den Krieg, um UNO-Gründungsmitglied zu werden?', 'Februar 1945', ['Mai 1945', 'Dezember 1941', 'September 1939']],
              ['Welcher Krieg brachte die Türkei näher an die USA?', 'Der Koreakrieg', ['Der Vietnamkrieg', 'Der Irakkrieg', 'Der Krimkrieg']],
              ['Was folgte 1974 auf den Putsch auf Zypern?', 'Die Landung türkischer Truppen im Norden', ['Der Anschluss an Griechenland', 'Die Unabhängigkeit von Großbritannien', 'Ein Erdbeben']],
              ['Wie oft griff das Militär bis 1980 in die Politik ein?', 'Dreimal (1960, 1971, 1980)', ['Nie', 'Einmal', 'Zehnmal']],
              ['Wer erkennt Nordzypern nicht an?', 'Die meisten Staaten', ['Die Türkei', 'Nordzypern selbst', 'Keiner']],
              ['Welcher Ministerpräsident wurde nach dem Putsch 1960 hingerichtet?', 'Adnan Menderes', ['İsmet İnönü', 'Süleyman Demirel', 'Bülent Ecevit']],
              ['Was bezweckte das Anwerbeabkommen 1961?', 'Arbeitskräfte für Deutschland', ['Soldaten für die NATO', 'Studenten für Ankara', 'Touristen für Istanbul']],
              ['Woher stammte die Junta, die 1974 auf Zypern putschte?', 'Aus Griechenland', ['Aus der Türkei', 'Aus Großbritannien', 'Aus Zypern selbst unabhängig']],
              ['Was war die Folge der Wahl 1950?', 'Die erste Regierungsübernahme durch eine andere Partei', ['Die Rückkehr des Sultans', 'Ein Militärputsch', 'Der Austritt aus der UNO']],
              ['Wann endete der Einparteienstaat?', 'Mit der Zulassung anderer Parteien 1946', ['1923', '1960', '1980']],
              ['Welche Rolle spielten türkische Universitäten für Emigranten?', 'Sie boten verfolgten Deutschen Arbeit', ['Sie verboten Ausländer', 'Sie waren geschlossen', 'Sie bildeten Soldaten aus']],
              ['Welche Stadt war 1955 Schauplatz des Pogroms?', 'Istanbul', ['Ankara', 'Izmir', 'Nikosia']],
              ['Wie lange regierte Menderes etwa?', 'Von 1950 bis 1960', ['Von 1923 bis 1938', 'Von 1980 bis 1989', 'Von 2003 bis 2014']],
              ['Was bedeutet der Begriff „Gastarbeiter“?', 'Ausländische Arbeitskräfte, die eigentlich nur vorübergehend bleiben sollten', ['Hotelangestellte', 'Austauschstudenten', 'Diplomaten']],
              ['Welcher General wurde nach 1980 Staatschef?', 'Kenan Evren', ['Cemal Gürsel', 'İsmet İnönü', 'Fevzi Çakmak']],
              ['Wann wurde Zypern geteilt?', '1974', ['1960', '1983', '1955']],
              ['Was erhoffte sich die Türkei vom Kriegseintritt 1945?', 'Einen Sitz bei der Gründung der UNO', ['Gebiete in Deutschland', 'Die Rückgabe Griechenlands', 'Den NATO-Beitritt sofort']],
              ['Welche politische Lage führte zum Putsch 1980?', 'Straßenkämpfe zwischen linken und rechten Gruppen', ['Ein Krieg mit Griechenland', 'Der Tod Atatürks', 'Ein Erdbeben']],
            ],
          },
        },
        {
          id: 'oezal-pkk',
          title: 'Özal, PKK-Konflikt und Weg nach Europa',
          date: '1980–2002',
          text: [
            'Nach dem Putsch von 1980 trat 1982 eine neue Verfassung in Kraft. Ministerpräsident und später Präsident Turgut Özal (1983–1993) öffnete die Wirtschaft für den Weltmarkt; Exporte, Tourismus und Bauwirtschaft wuchsen stark. 1987 stellte die Türkei den Antrag auf Mitgliedschaft in der Europäischen Gemeinschaft.',
            '1984 begann die kurdische Untergrundorganisation „Arbeiterpartei Kurdistans“ (PKK) unter Abdullah Öcalan einen bewaffneten Kampf im Südosten. Der Konflikt forderte über 40.000 Tote, Tausende Dörfer wurden geräumt. 1999 wurde Öcalan in Kenia gefasst und zu lebenslanger Haft auf der Gefängnisinsel İmralı verurteilt. Kurdische Sprache und Kultur waren lange stark eingeschränkt.',
            '1996 trat die Zollunion mit der EU in Kraft, und 1999 erhielt die Türkei den Status eines Beitrittskandidaten. Im selben Jahr zerstörte am 17. August ein schweres Erdbeben bei İzmit Teile der Region um das Marmarameer; über 17.000 Menschen starben. Griechenland schickte Helfer, und beide Länder näherten sich an.',
            '1997 zwang das Militär die islamistisch geprägte Regierung von Necmettin Erbakan mit einem Memorandum zum Rücktritt; man spricht von einem „postmodernen Putsch“. 2001 erlebte die Türkei eine schwere Finanzkrise, die Lira verlor stark an Wert.',
            'Die Türkei wurde ein beliebtes Reiseziel, besonders die Küsten am Mittelmeer und an der Ägäis. Im Sport feierte sie Erfolge: 2002 wurde die Nationalmannschaft bei der Fußball-WM Dritte. Der Schriftsteller Orhan Pamuk wurde mit Romanen wie „Rot ist mein Name“ berühmt und erhielt 2006 als erster Türke den Literaturnobelpreis.',
          ],
          quiz: {
            leicht: [
              ['Wann trat nach dem Putsch eine neue Verfassung in Kraft?', '1982', ['1980', '1923', '2017']],
              ['Welcher Politiker öffnete die Wirtschaft für den Weltmarkt?', 'Turgut Özal', ['Recep Tayyip Erdoğan', 'Kenan Evren', 'Adnan Menderes']],
              ['Wann stellte die Türkei den Antrag auf EG-Mitgliedschaft?', '1987', ['1952', '1999', '2005']],
              ['Welche Organisation begann 1984 einen bewaffneten Kampf?', 'Die PKK', ['Die AKP', 'Die NATO', 'Die UNO']],
              ['Wer führte die PKK?', 'Abdullah Öcalan', ['Turgut Özal', 'Orhan Pamuk', 'Necmettin Erbakan']],
              ['In welcher Region kämpfte die PKK?', 'Im Südosten', ['In Istanbul', 'An der Ägäis', 'In Thrakien']],
              ['Wie viele Tote forderte der PKK-Konflikt?', 'Über 40.000', ['Rund 400', 'Rund 4.000', 'Über vier Millionen']],
              ['Wo wurde Öcalan 1999 gefasst?', 'In Kenia', ['In Syrien', 'In Deutschland', 'In Istanbul']],
              ['Auf welcher Gefängnisinsel sitzt Öcalan?', 'İmralı', ['Alcatraz', 'Robben Island', 'Büyükada']],
              ['Wann trat die Zollunion mit der EU in Kraft?', '1996', ['1987', '1999', '2005']],
              ['Wann erhielt die Türkei den Status eines EU-Beitrittskandidaten?', '1999', ['1987', '1996', '2005']],
              ['Wo ereignete sich 1999 ein schweres Erdbeben?', 'Bei İzmit', ['Bei Ankara', 'In Antalya', 'In Trabzon']],
              ['Wie viele Menschen starben beim Erdbeben 1999?', 'Über 17.000', ['Rund 170', 'Rund 1.700', 'Über 170.000']],
              ['Welches Land schickte 1999 Helfer und näherte sich an?', 'Griechenland', ['Russland', 'Armenien', 'Iran']],
              ['Wie nennt man den Eingriff des Militärs 1997?', 'Postmoderner Putsch', ['Samtene Revolution', 'Tulpenputsch', 'Februarumsturz']],
              ['Welcher Ministerpräsident musste 1997 zurücktreten?', 'Necmettin Erbakan', ['Turgut Özal', 'Bülent Ecevit', 'Tansu Çiller']],
              ['Wann erlebte die Türkei eine schwere Finanzkrise?', '2001', ['1996', '2008', '1980']],
              ['Welchen Platz erreichte die Türkei bei der Fußball-WM 2002?', 'Den dritten', ['Den ersten', 'Den zweiten', 'Den achten']],
              ['Welcher türkische Schriftsteller erhielt den Literaturnobelpreis?', 'Orhan Pamuk', ['Yaşar Kemal', 'Nazım Hikmet', 'Elif Şafak']],
              ['Wann erhielt Orhan Pamuk den Nobelpreis?', '2006', ['2002', '1999', '2016']],
            ],
            mittel: [
              ['Welche Ämter hatte Turgut Özal?', 'Ministerpräsident und später Präsident', ['General und Sultan', 'Bürgermeister von Istanbul', 'Nur Außenminister']],
              ['Wann prägte Özal die Politik?', '1983–1993', ['1950–1960', '2003–2014', '1923–1938']],
              ['Welche Bereiche wuchsen unter Özal stark?', 'Exporte, Tourismus und Bauwirtschaft', ['Landwirtschaft', 'Bergbau', 'Fischerei']],
              ['Was geschah mit Tausenden Dörfern im PKK-Konflikt?', 'Sie wurden geräumt', ['Sie wurden reich', 'Sie wurden zu Städten', 'Nichts']],
              ['Zu welcher Strafe wurde Öcalan verurteilt?', 'Zu lebenslanger Haft', ['Zu einer Geldstrafe', 'Zu zehn Jahren', 'Er wurde freigelassen']],
              ['Was war lange stark eingeschränkt?', 'Kurdische Sprache und Kultur', ['Der Tourismus', 'Der Fußball', 'Die Ausfuhr']],
              ['An welchem Tag ereignete sich das Erdbeben von İzmit?', 'Am 17. August 1999', ['Am 6. Februar 2023', 'Am 1. Januar 2000', 'Am 29. Oktober 1999']],
              ['Welches Meer umgibt die vom Erdbeben 1999 betroffene Region?', 'Das Marmarameer', ['Das Schwarze Meer', 'Das Mittelmeer', 'Der Van-See']],
              ['Was bewirkte die Hilfe Griechenlands 1999?', 'Eine Annäherung beider Länder', ['Einen Krieg', 'Den Abbruch der Beziehungen', 'Nichts']],
              ['Wie wurde die Erbakan-Regierung 1997 gestürzt?', 'Durch ein Memorandum des Militärs', ['Durch Panzer auf den Straßen', 'Durch eine Volksabstimmung', 'Durch die EU']],
              ['Wie war die Erbakan-Regierung geprägt?', 'Islamistisch', ['Kommunistisch', 'Monarchistisch', 'Liberal-westlich']],
              ['Was verlor in der Krise 2001 stark an Wert?', 'Die Lira', ['Das Gold', 'Der Euro', 'Der Dollar']],
              ['Welche Küsten wurden beliebte Reiseziele?', 'Mittelmeer und Ägäis', ['Nur das Schwarze Meer', 'Der Van-See', 'Die Küste Syriens']],
              ['Welchen Roman schrieb Orhan Pamuk?', '„Rot ist mein Name“', ['„Memed mein Falke“', '„Der Name der Rose“', '„Tausendundeine Nacht“']],
              ['Als wievielter Türke erhielt Pamuk den Literaturnobelpreis?', 'Als erster', ['Als dritter', 'Als zehnter', 'Als zweiter']],
              ['Was ist eine Zollunion?', 'Ein Abkommen ohne Zölle zwischen den Partnern', ['Ein Militärbündnis', 'Eine gemeinsame Währung', 'Eine Polizei']],
              ['Wann begann die PKK ihren bewaffneten Kampf?', '1984', ['1974', '1999', '1980']],
              ['Wann wurde Öcalan gefasst?', '1999', ['1984', '2005', '1993']],
              ['Mit welcher Organisation strebte die Türkei 1987 die Mitgliedschaft an?', 'Mit der Europäischen Gemeinschaft', ['Mit dem Warschauer Pakt', 'Mit der Arabischen Liga', 'Mit der OPEC']],
              ['Was folgte auf die neue Verfassung von 1982?', 'Die Wirtschaftsöffnung unter Özal', ['Die Rückkehr des Sultans', 'Der Beitritt zur EU', 'Ein Krieg mit Griechenland']],
            ],
            schwer: [
              ['Was ist İmralı?', 'Eine Gefängnisinsel', ['Ein Gebirge', 'Eine Stadt im Osten', 'Ein Palast']],
              ['Welches Ereignis nennt man „postmoderner Putsch“?', 'Den Druck des Militärs auf die Regierung 1997', ['Den Putsch 1960', 'Den Putsch 1980', 'Den Putschversuch 2016']],
              ['Welcher Status kam 1999 von der EU?', 'Beitrittskandidat', ['Vollmitglied', 'Beobachter', 'Partner ohne Status']],
              ['Welche Folge hatte das Erdbeben 1999 außenpolitisch?', 'Annäherung an Griechenland', ['Krieg mit Griechenland', 'Austritt aus der NATO', 'Bruch mit der EU']],
              ['Welche Organisation verlor 1999 ihren Anführer?', 'Die PKK', ['Die AKP', 'Die CHP', 'Die MHP']],
              ['Wer wurde 1989 Präsident, nachdem er Ministerpräsident gewesen war?', 'Turgut Özal', ['Kenan Evren', 'Süleyman Demirel', 'Bülent Ecevit']],
              ['Welche Zahl beschreibt die Toten des PKK-Konflikts?', 'Über 40.000', ['Unter 1.000', 'Genau 17.000', 'Über eine Million']],
              ['Wann wurde die Türkei bei der Fußball-WM Dritte?', '2002', ['2008', '1998', '2006']],
              ['Welche Währung hat die Türkei?', 'Die Lira', ['Den Euro', 'Den Dinar', 'Den Rubel']],
              ['Welches Ereignis fiel 2001 auf die türkische Wirtschaft?', 'Eine schwere Finanzkrise', ['Ein Wirtschaftswunder', 'Der Euro-Beitritt', 'Ein Ölboom']],
              ['Welche Stadt liegt im vom Erdbeben 1999 betroffenen Gebiet?', 'İzmit', ['Erzurum', 'Antalya', 'Diyarbakır']],
              ['In welchem Erdteil wurde Öcalan gefasst?', 'In Afrika', ['In Europa', 'In Asien', 'In Amerika']],
              ['Wofür steht die Abkürzung PKK sinngemäß?', 'Arbeiterpartei Kurdistans', ['Partei der Konservativen Kräfte', 'Präsidiale Koalition', 'Polizeikommando Kurdistan']],
              ['Welche Politik verfolgte Özal wirtschaftlich?', 'Öffnung für den Weltmarkt', ['Abschottung', 'Planwirtschaft', 'Rückkehr zum Osmanischen System']],
              ['Welcher türkische Roman stammt von Orhan Pamuk?', '„Rot ist mein Name“', ['„Der Gefangene“', '„Unterwerfung“', '„Die Pest“']],
              ['Wann trat die Zollunion in Kraft?', '1996', ['1987', '2001', '1999']],
              ['Was forderte das Militär 1997?', 'Den Rücktritt der Regierung', ['Neuwahlen in Zypern', 'Den NATO-Austritt', 'Die Rückkehr des Kalifats']],
              ['Welche Rolle spielte der Tourismus?', 'Er wurde ein wichtiger Wirtschaftszweig', ['Er wurde verboten', 'Er spielte keine Rolle', 'Er schrumpfte']],
              ['Wann regierte Özal etwa?', 'In den 1980er-Jahren', ['In den 1950er-Jahren', 'In den 2010er-Jahren', 'In den 1930er-Jahren']],
              ['Wie wurden kurdische Dörfer im Konflikt behandelt?', 'Tausende wurden geräumt', ['Sie wurden gefördert', 'Sie bekamen Autonomie', 'Sie blieben unberührt']],
            ],
          },
        },
        {
          id: 'erdogan',
          title: 'Erdoğan, Putschversuch und Gegenwart',
          date: 'seit 2002',
          text: [
            '2002 gewann die neu gegründete Partei für Gerechtigkeit und Aufschwung (AKP) die Wahl. Ihr Vorsitzender Recep Tayyip Erdoğan, zuvor Bürgermeister von Istanbul, wurde 2003 Ministerpräsident. In den ersten Jahren wuchs die Wirtschaft stark, Reformen wurden beschlossen, und 2005 begannen die Beitrittsverhandlungen mit der EU, die später ins Stocken gerieten.',
            '2013 protestierten Hunderttausende, ausgehend vom Gezi-Park in Istanbul, gegen die Regierung; die Polizei ging hart dagegen vor. 2014 wurde Erdoğan in der ersten direkten Wahl Präsident.',
            'In der Nacht zum 15. Juli 2016 versuchten Teile des Militärs zu putschen. Menschen gingen auf die Straßen, und der Putsch scheiterte; über 250 Menschen starben. Die Regierung machte die Bewegung des Predigers Fethullah Gülen verantwortlich. Danach wurden Zehntausende verhaftet und über 100.000 Beamte entlassen.',
            '2017 stimmte eine knappe Mehrheit in einer Volksabstimmung für ein Präsidialsystem, das dem Präsidenten große Macht gibt. 2020 wurde die Hagia Sophia wieder zur Moschee. Seit 2022 nennt sich das Land international „Türkiye“. Die Türkei nahm Millionen Flüchtlinge aus Syrien auf, mehr als jedes andere Land.',
            'Am 6. Februar 2023 erschütterten zwei schwere Erdbeben den Südosten der Türkei und Syrien; in der Türkei starben über 50.000 Menschen. Hohe Inflation belastet die Bevölkerung. Im Mai 2023 wurde Erdoğan wiedergewählt. 2025 wurde der Istanbuler Bürgermeister Ekrem İmamoğlu, ein wichtiger Oppositionspolitiker, festgenommen, was große Proteste auslöste.',
          ],
          quiz: {
            leicht: [
              ['Welche Partei gewann 2002 die Wahl?', 'Die AKP', ['Die CHP', 'Die PKK', 'Die Demokratische Partei']],
              ['Wer ist der Vorsitzende der AKP?', 'Recep Tayyip Erdoğan', ['Turgut Özal', 'Orhan Pamuk', 'Ekrem İmamoğlu']],
              ['Was war Erdoğan vorher?', 'Bürgermeister von Istanbul', ['General', 'Fußballspieler', 'Imam in Mekka']],
              ['Wann wurde Erdoğan Ministerpräsident?', '2003', ['2002', '2014', '2017']],
              ['Wann begannen die EU-Beitrittsverhandlungen?', '2005', ['1987', '1999', '2016']],
              ['Wo begannen die Proteste 2013?', 'Im Gezi-Park in Istanbul', ['In Ankara', 'In Brüssel', 'In Izmir']],
              ['Wann wurde Erdoğan zum ersten Mal Präsident?', '2014', ['2003', '2017', '2023']],
              ['Wann fand der Putschversuch statt?', 'In der Nacht zum 15. Juli 2016', ['Am 12. September 1980', 'Am 27. Mai 1960', 'Am 6. Februar 2023']],
              ['Hatte der Putschversuch 2016 Erfolg?', 'Nein, er scheiterte', ['Ja', 'Teilweise', 'Er fand nicht statt']],
              ['Wen machte die Regierung für den Putschversuch verantwortlich?', 'Die Bewegung von Fethullah Gülen', ['Die PKK', 'Die NATO', 'Die EU']],
              ['Welches System wurde 2017 eingeführt?', 'Ein Präsidialsystem', ['Eine Monarchie', 'Ein Kalifat', 'Eine parlamentarische Monarchie']],
              ['Was wurde die Hagia Sophia 2020?', 'Wieder eine Moschee', ['Ein Museum', 'Eine Kirche', 'Ein Hotel']],
              ['Wie nennt sich die Türkei international seit 2022?', 'Türkiye', ['Turkey', 'Anatolia', 'Osmania']],
              ['Aus welchem Land nahm die Türkei Millionen Flüchtlinge auf?', 'Aus Syrien', ['Aus Griechenland', 'Aus Deutschland', 'Aus Japan']],
              ['Wann erschütterten schwere Erdbeben den Südosten?', 'Am 6. Februar 2023', ['Am 17. August 1999', 'Am 15. Juli 2016', 'Am 29. Oktober 2023']],
              ['Wie viele Menschen starben 2023 in der Türkei durch die Erdbeben?', 'Über 50.000', ['Rund 500', 'Rund 5.000', 'Über eine Million']],
              ['Was belastet die Bevölkerung wirtschaftlich?', 'Hohe Inflation', ['Zu niedrige Preise', 'Zu viele Feiertage', 'Zu wenig Tourismus']],
              ['Wann wurde Erdoğan wiedergewählt?', 'Im Mai 2023', ['Im Juli 2016', 'Im Jahr 2005', 'Im Jahr 2014']],
              ['Welcher Istanbuler Bürgermeister wurde 2025 festgenommen?', 'Ekrem İmamoğlu', ['Recep Tayyip Erdoğan', 'Kemal Kılıçdaroğlu', 'Ahmet Davutoğlu']],
              ['Wie reagierte die Bevölkerung auf die Festnahme 2025?', 'Mit großen Protesten', ['Mit Jubel', 'Gar nicht', 'Mit einem Putsch']],
            ],
            mittel: [
              ['Wofür steht die Abkürzung AKP?', 'Partei für Gerechtigkeit und Aufschwung', ['Arbeiterpartei Kurdistans', 'Atatürk-Kemalistische Partei', 'Allgemeine Konservative Partei']],
              ['Was geschah in den ersten Jahren der AKP-Regierung mit der Wirtschaft?', 'Sie wuchs stark', ['Sie brach zusammen', 'Sie blieb gleich', 'Sie wurde verstaatlicht']],
              ['Was geschah später mit den EU-Beitrittsverhandlungen?', 'Sie gerieten ins Stocken', ['Sie führten 2010 zum Beitritt', 'Sie wurden nie begonnen', 'Sie wurden beschleunigt']],
              ['Wie viele Menschen protestierten 2013?', 'Hunderttausende', ['Einige Dutzend', 'Einige Hundert', 'Niemand']],
              ['Wie reagierte die Polizei 2013?', 'Sie ging hart vor', ['Sie schloss sich an', 'Sie blieb fern', 'Sie verteilte Blumen']],
              ['Wie wurde Erdoğan 2014 Präsident?', 'In der ersten direkten Wahl', ['Durch das Parlament', 'Durch einen Putsch', 'Durch Erbfolge']],
              ['Wer brachte den Putschversuch 2016 zum Scheitern?', 'Menschen auf den Straßen', ['Die NATO', 'Die EU', 'Die PKK']],
              ['Wie viele Menschen starben beim Putschversuch?', 'Über 250', ['Rund 25', 'Rund 2.500', 'Keiner']],
              ['Was folgte auf den Putschversuch?', 'Zehntausende Verhaftungen und Entlassungen', ['Neuwahlen sofort', 'Der EU-Beitritt', 'Die Abdankung Erdoğans']],
              ['Wie viele Beamte wurden nach 2016 entlassen?', 'Über 100.000', ['Rund 100', 'Rund 1.000', 'Keine']],
              ['Wie knapp war die Volksabstimmung 2017?', 'Eine knappe Mehrheit stimmte zu', ['Fast alle stimmten zu', 'Die Mehrheit lehnte ab', 'Es gab keine Abstimmung']],
              ['Was gibt das Präsidialsystem dem Präsidenten?', 'Große Macht', ['Keine Macht', 'Nur repräsentative Aufgaben', 'Macht nur über das Militär']],
              ['Was war die Hagia Sophia von 1934 bis 2020?', 'Ein Museum', ['Eine Moschee', 'Eine Kirche', 'Ein Gefängnis']],
              ['Wie viele syrische Flüchtlinge nahm die Türkei im Vergleich auf?', 'Mehr als jedes andere Land', ['Weniger als Deutschland', 'Keine', 'Genau tausend']],
              ['Welches Nachbarland traf das Erdbeben 2023 ebenfalls?', 'Syrien', ['Griechenland', 'Bulgarien', 'Georgien']],
              ['Wie viele schwere Erdbeben gab es am 6. Februar 2023?', 'Zwei', ['Eines', 'Zehn', 'Keines']],
              ['Welcher Teil der Türkei war 2023 vom Erdbeben betroffen?', 'Der Südosten', ['Der Nordwesten', 'Istanbul', 'Die Ägäisküste']],
              ['Welche Rolle hat Ekrem İmamoğlu?', 'Er ist ein wichtiger Oppositionspolitiker', ['Er ist AKP-Vorsitzender', 'Er ist General', 'Er ist Fußballtrainer']],
              ['Wer war Fethullah Gülen?', 'Ein Prediger', ['Ein General', 'Ein Sultan', 'Ein Fußballspieler']],
              ['Was war Erdoğans Amt vor 2014?', 'Ministerpräsident', ['Präsident', 'Bürgermeister von Ankara', 'Außenminister']],
            ],
            schwer: [
              ['Wann wurde die AKP gegründet?', 'Kurz vor der Wahl 2002 (2001)', ['1923', '1980', '2010']],
              ['Wann stimmte die Türkei für das Präsidialsystem?', '2017', ['2014', '2016', '2023']],
              ['Wann wurde die Hagia Sophia wieder zur Moschee?', '2020', ['2016', '1934', '2023']],
              ['Seit wann nennt sich das Land international „Türkiye“?', 'Seit 2022', ['Seit 1923', 'Seit 2017', 'Seit 2003']],
              ['Wie viele Menschen starben 2016 beim Putschversuch mindestens?', 'Über 250', ['Über 2.500', 'Unter 10', 'Über 25.000']],
              ['Welche Folge hatte das Präsidialsystem für das Parlament?', 'Es verlor an Macht gegenüber dem Präsidenten', ['Es wurde stärker', 'Es wurde abgeschafft', 'Es wählt nun den Sultan']],
              ['Woher stammen die meisten Flüchtlinge in der Türkei?', 'Aus Syrien', ['Aus Japan', 'Aus der Ukraine', 'Aus Griechenland']],
              ['Wann begannen die Proteste im Gezi-Park?', '2013', ['2016', '2007', '2019']],
              ['Welcher Park in Istanbul wurde zum Symbol der Proteste?', 'Gezi-Park', ['Gülhane-Park', 'Emirgan-Park', 'Yıldız-Park']],
              ['Was belastet die Türkei seit Jahren wirtschaftlich?', 'Hohe Inflation', ['Deflation', 'Ein Ölboom', 'Zu hohe Exporte']],
              ['Welche Wahl gewann Erdoğan im Mai 2023?', 'Die Präsidentschaftswahl', ['Die Bürgermeisterwahl in Istanbul', 'Die Wahl zum NATO-Generalsekretär', 'Keine']],
              ['In welchem Jahr wurde Ekrem İmamoğlu festgenommen?', '2025', ['2013', '2016', '2019']],
              ['Wen machte die Regierung 2016 verantwortlich?', 'Die Gülen-Bewegung', ['Die Opposition CHP', 'Die USA direkt', 'Die Kirche']],
              ['Welche Reformen gab es in den ersten AKP-Jahren?', 'Reformen im Zuge der EU-Annäherung', ['Die Abschaffung der Republik', 'Die Wiedereinführung des Fes', 'Keine']],
              ['Welches Amt hatte Erdoğan ab 2014?', 'Präsident', ['Ministerpräsident', 'Bürgermeister', 'Parteisekretär ohne Amt']],
              ['Welches Ereignis 2023 forderte über 50.000 Tote in der Türkei?', 'Die Erdbeben vom 6. Februar', ['Der Putschversuch', 'Die Gezi-Proteste', 'Ein Krieg mit Syrien']],
              ['Wie wird das Präsidialsystem von Kritikern beurteilt?', 'Es gebe dem Präsidenten zu viel Macht', ['Es sei zu schwach', 'Es sei eine Monarchie', 'Es sei kommunistisch']],
              ['Wann begann die AKP zu regieren?', '2002', ['1996', '2007', '2014']],
              ['Was wurde in der Nacht zum 15. Juli 2016 versucht?', 'Ein Militärputsch', ['Ein Terroranschlag', 'Ein Erdbeben', 'Eine Wahl']],
              ['Welches Gebäude wechselte 2020 seine Funktion?', 'Die Hagia Sophia', ['Der Topkapı-Palast', 'Das Anıtkabir', 'Die Blaue Moschee']],
            ],
          },
        },
      ],
    },
  ],
};
