import type { HistEvent } from '../types';

export const ERSTER_KAISER: HistEvent = {
  id: 'erster-kaiser',
  title: 'Der erste Kaiser und die Han',
  date: '221 v. Chr. – 220 n. Chr.',
  text: [
    '221 v. Chr. einte Qin Shi Huang China und wurde der erste Kaiser. Sein Reich zerfiel schnell, doch die folgende Han-Dynastie regierte über 400 Jahre und prägte China so stark, dass sich die Chinesen bis heute „Han“ nennen.',
  ],
  subtopics: [
    {
      id: 'qin-shi-huang',
      title: 'Qin Shi Huang, der erste Kaiser',
      date: '221–206 v. Chr.',
      text: [
        'König Ying Zheng von Qin eroberte zwischen 230 und 221 v. Chr. die sechs anderen Reiche und nannte sich „Qin Shi Huangdi“ – „Erster erhabener Kaiser von Qin“. Von „Qin“ stammt vermutlich auch der Name „China“. Er teilte das Reich in Kommandanturen ein, die von Beamten statt von Adligen verwaltet wurden.',
        'Er vereinheitlichte Schrift, Maße, Gewichte, Münzen und sogar die Achsbreite der Wagen, damit sie in dieselben Fahrspuren passten. Er ließ Straßen und Kanäle bauen und verband ältere Mauern im Norden zu einer langen Verteidigungslinie gegen die Steppenvölker der Xiongnu – einem Vorläufer der Großen Mauer. Hunderttausende Zwangsarbeiter starben dabei.',
        'Der Kaiser regierte nach den harten Regeln des Legalismus. Sein Kanzler Li Si riet ihm 213 v. Chr., Bücher verbrennen zu lassen, die nicht von Medizin, Landwirtschaft oder Wahrsagerei handelten; der Überlieferung nach ließ er auch Hunderte Gelehrte lebendig begraben.',
        'Qin Shi Huang suchte verzweifelt nach einem Mittel für ewiges Leben und schickte Expeditionen über das Meer. Er starb 210 v. Chr. auf einer Reise, vielleicht an Quecksilber, das er als Lebenselixier einnahm. Sein riesiges Grab bei Xi’an wird von der Terrakotta-Armee bewacht: über 7.000 lebensgroße Tonsoldaten, jeder mit eigenem Gesicht, die Bauern 1974 beim Brunnengraben entdeckten. Der Grabhügel selbst ist bis heute nicht geöffnet.',
        'Nach seinem Tod brachen Aufstände aus, denn die Menschen litten unter Zwangsarbeit und harten Strafen. 206 v. Chr. endete die Qin-Dynastie nach nur 15 Jahren. Im anschließenden Kampf siegte der Bauernsohn Liu Bang und gründete die Han-Dynastie.',
      ],
      quiz: {
        leicht: [
          ['Wer war der erste Kaiser Chinas?', 'Qin Shi Huang', ['Konfuzius', 'Liu Bang', 'Kublai Khan']],
          ['Wann einte Qin Shi Huang China?', '221 v. Chr.', ['1046 v. Chr.', '206 v. Chr.', '618 n. Chr.']],
          ['Was bedeutet „Qin Shi Huangdi“?', 'Erster erhabener Kaiser von Qin', ['Sohn des Himmels', 'König der Drachen', 'Herr der Mauer']],
          ['Woher stammt vermutlich der Name „China“?', 'Von „Qin“', ['Von „Han“', 'Von „Tang“', 'Von „Ming“']],
          ['Was vereinheitlichte der erste Kaiser?', 'Schrift, Maße, Gewichte und Münzen', ['Religion und Kleidung', 'Musik und Tanz', 'Nur die Sprache']],
          ['Warum vereinheitlichte er die Achsbreite der Wagen?', 'Damit sie in dieselben Fahrspuren passten', ['Damit sie schneller fuhren', 'Damit sie schöner aussahen', 'Für Wagenrennen']],
          ['Gegen wen baute er eine Mauer im Norden?', 'Gegen die Xiongnu', ['Gegen die Japaner', 'Gegen die Römer', 'Gegen die Inder']],
          ['Wovon war seine Mauer ein Vorläufer?', 'Von der Großen Mauer', ['Vom Kaiserkanal', 'Von der Verbotenen Stadt', 'Von der Seidenstraße']],
          ['Nach welcher Lehre regierte er?', 'Nach dem Legalismus', ['Nach dem Daoismus', 'Nach dem Buddhismus', 'Nach dem Christentum']],
          ['Was ließ der Kaiser 213 v. Chr. verbrennen?', 'Bücher', ['Städte', 'Schiffe', 'Wälder']],
          ['Wonach suchte Qin Shi Huang verzweifelt?', 'Nach ewigem Leben', ['Nach Gold', 'Nach einem Erben', 'Nach Rom']],
          ['Wann starb Qin Shi Huang?', '210 v. Chr.', ['221 v. Chr.', '206 v. Chr.', '100 v. Chr.']],
          ['Was nahm er vielleicht als Lebenselixier ein?', 'Quecksilber', ['Gold', 'Tee', 'Wein']],
          ['Was bewacht das Grab des ersten Kaisers?', 'Die Terrakotta-Armee', ['Echte Soldaten', 'Bronzelöwen', 'Mönche']],
          ['Bei welcher Stadt liegt das Grab?', 'Bei Xi’an', ['Bei Peking', 'Bei Shanghai', 'Bei Kanton']],
          ['Wie viele Tonsoldaten gibt es etwa?', 'Über 7.000', ['Rund 70', 'Rund 700.000', 'Rund 700']],
          ['Wer entdeckte die Terrakotta-Armee?', 'Bauern beim Brunnengraben', ['Britische Archäologen', 'Der Kaiser selbst', 'Mönche']],
          ['Wann wurde die Terrakotta-Armee entdeckt?', '1974', ['1900', '1949', '2000']],
          ['Wie lange bestand die Qin-Dynastie?', 'Nur 15 Jahre', ['400 Jahre', '800 Jahre', '100 Jahre']],
          ['Wer gründete die Han-Dynastie?', 'Liu Bang', ['Qin Shi Huang', 'Li Si', 'Kaiser Wu']],
        ],
        mittel: [
          ['Wie hieß Qin Shi Huang ursprünglich?', 'Ying Zheng', ['Liu Bang', 'Li Si', 'Zhu Yuanzhang']],
          ['Wie viele andere Reiche eroberte Qin?', 'Sechs', ['Zwei', 'Zehn', 'Zwölf']],
          ['Zwischen welchen Jahren eroberte Qin die anderen Reiche?', '230–221 v. Chr.', ['300–290 v. Chr.', '210–206 v. Chr.', '1046–1000 v. Chr.']],
          ['Wie teilte er das Reich ein?', 'In Kommandanturen unter Beamten', ['In Lehen für Adlige', 'In Klöster', 'In Stadtstaaten']],
          ['Wer verwaltete die Kommandanturen?', 'Beamte', ['Adlige', 'Priester', 'Generäle der Xiongnu']],
          ['Was ließ der erste Kaiser außer der Mauer bauen?', 'Straßen und Kanäle', ['Pyramiden', 'Kathedralen', 'Eisenbahnen']],
          ['Wer baute an der Mauer?', 'Hunderttausende Zwangsarbeiter', ['Freiwillige Mönche', 'Ausländische Ingenieure', 'Roboter']],
          ['Wer riet dem Kaiser zur Bücherverbrennung?', 'Kanzler Li Si', ['Konfuzius', 'Liu Bang', 'Sunzi']],
          ['Welche Bücher blieben von der Verbrennung verschont?', 'Bücher über Medizin, Landwirtschaft und Wahrsagerei', ['Gedichte', 'Konfuzianische Schriften', 'Geschichtsbücher anderer Staaten']],
          ['Was geschah der Überlieferung nach mit Gelehrten?', 'Hunderte wurden lebendig begraben', ['Sie wurden Minister', 'Sie wurden reich belohnt', 'Sie flohen nach Japan']],
          ['Wohin schickte er Expeditionen auf der Suche nach dem Elixier?', 'Über das Meer', ['Nach Indien zu Fuß', 'In die Wüste', 'Nach Europa']],
          ['Wo starb der erste Kaiser?', 'Auf einer Reise', ['In seinem Palast', 'In der Schlacht', 'Im Exil']],
          ['Was ist besonders an jedem Tonsoldaten?', 'Jeder hat ein eigenes Gesicht', ['Alle sind gleich', 'Sie sind aus Gold', 'Sie sind winzig']],
          ['Wie groß sind die Tonsoldaten?', 'Lebensgroß', ['Daumengroß', 'Zehn Meter hoch', 'Kniehoch']],
          ['Ist der Grabhügel des Kaisers geöffnet?', 'Nein, bis heute nicht', ['Ja, seit 1974', 'Ja, seit 1900', 'Er wurde zerstört']],
          ['Warum brachen nach seinem Tod Aufstände aus?', 'Wegen Zwangsarbeit und harter Strafen', ['Wegen zu niedriger Steuern', 'Wegen einer Mongoleninvasion', 'Wegen der Pest']],
          ['Wann endete die Qin-Dynastie?', '206 v. Chr.', ['210 v. Chr.', '221 v. Chr.', '220 n. Chr.']],
          ['Welche Herkunft hatte Liu Bang?', 'Bauernsohn', ['Kaisersohn', 'General der Qin', 'Kaufmann aus Rom']],
          ['Welches Steppenvolk bedrohte den Norden?', 'Die Xiongnu', ['Die Mongolen', 'Die Mandschu', 'Die Türken']],
          ['Welche Lehre verfolgte die Qin-Herrschaft?', 'Legalismus', ['Konfuzianismus', 'Daoismus', 'Mohismus']],
        ],
        schwer: [
          ['Welcher Kanzler war Architekt der Qin-Politik?', 'Li Si', ['Shang Yang', 'Xiao He', 'Zhang Liang']],
          ['Welches Jahr ist mit der Bücherverbrennung verbunden?', '213 v. Chr.', ['221 v. Chr.', '206 v. Chr.', '479 v. Chr.']],
          ['Welche Verwaltungseinheiten ersetzten die Adelslehen?', 'Kommandanturen', ['Provinzen der Mongolen', 'Fürstentümer', 'Bistümer']],
          ['Welche Substanz könnte den Tod des Kaisers verursacht haben?', 'Quecksilber', ['Arsen', 'Blei', 'Opium']],
          ['In welchem Jahr fanden Bauern die Terrakotta-Armee?', '1974', ['1949', '1987', '1912']],
          ['Welches Element der Wagen wurde vereinheitlicht?', 'Die Achsbreite', ['Die Farbe', 'Die Anzahl der Pferde', 'Das Material der Räder']],
          ['Welche Dynastie folgte auf die Qin?', 'Die Han', ['Die Tang', 'Die Zhou', 'Die Sui']],
          ['Welcher spätere Kaiser war ein Bauernsohn?', 'Liu Bang', ['Qin Shi Huang', 'Kangxi', 'Taizong']],
          ['Welche Folge hatte die Vereinheitlichung der Schrift?', 'Ein einheitliches Schriftsystem im ganzen Reich', ['Abschaffung der Schrift', 'Einführung des Alphabets', 'Mehrere neue Schriften']],
          ['Welches Volk war das Ziel der frühen Mauer?', 'Die Xiongnu', ['Die Japaner', 'Die Koreaner', 'Die Tibeter']],
          ['Welche Sache ist am Grab des Kaisers bis heute unerforscht?', 'Der Grabhügel selbst', ['Die Terrakotta-Armee', 'Die Pferde aus Ton', 'Die Waffen']],
          ['Wie lange regierte Qin Shi Huang als Kaiser?', 'Von 221 bis 210 v. Chr.', ['Von 300 bis 250 v. Chr.', 'Von 206 v. Chr. bis 9 n. Chr.', 'Nur ein Jahr']],
          ['Welche Herrschaftsform bereitete Qin für ganz China vor?', 'Ein zentral verwalteter Einheitsstaat', ['Ein Bund freier Städte', 'Ein Feudalsystem', 'Eine Demokratie']],
          ['Welche Arbeitskraft nutzte der Kaiser für seine Bauten?', 'Zwangsarbeiter', ['Bezahlte Ingenieure aus Persien', 'Sklaven aus Afrika', 'Soldaten aus Rom']],
          ['Welcher Titel war vor Qin Shi Huang für Herrscher üblich?', 'König', ['Kaiser', 'Khan', 'Sultan']],
          ['Welches Ereignis beendete die Qin-Dynastie?', 'Aufstände nach dem Tod des Kaisers', ['Eine Invasion der Römer', 'Ein Erdbeben', 'Ein Friedensvertrag']],
          ['Welche Stadt liegt nahe der Terrakotta-Armee?', 'Xi’an', ['Luoyang', 'Nanjing', 'Kaifeng']],
          ['Welche Expeditionen schickte der Kaiser aus?', 'Seefahrten auf der Suche nach dem Elixier', ['Feldzüge nach Rom', 'Reisen nach Afrika', 'Missionen nach Indien für Buddha']],
          ['Welche Gruppe traf die Härte der Qin besonders?', 'Gelehrte und Zwangsarbeiter', ['Die Händler aus Persien', 'Die Händler aus Rom', 'Die Mönche Tibets']],
          ['Wie viele Jahre nach der Einigung endete die Qin?', '15', ['50', '5', '150']],
        ],
      },
    },
    {
      id: 'han',
      title: 'Die Han-Dynastie und die Seidenstraße',
      date: '206 v. Chr. – 220 n. Chr.',
      text: [
        'Die Han-Dynastie regierte mit einer kurzen Unterbrechung über 400 Jahre und gilt neben der Tang-Zeit als goldenes Zeitalter. Bis heute nennt sich die größte Volksgruppe Chinas „Han-Chinesen“ und die chinesische Schrift „Han-Zeichen“. Die Han milderten die harten Qin-Gesetze und machten den Konfuzianismus zur Staatslehre.',
        'Kaiser Wu (Han Wudi, regierte 141–87 v. Chr.) dehnte das Reich weit aus, nach Korea, Vietnam und Zentralasien. Er führte Prüfungen ein, in denen Beamte nach ihrer Kenntnis der konfuzianischen Klassiker ausgewählt wurden – der Anfang des kaiserlichen Prüfungssystems, das bis 1905 bestand. 138 v. Chr. schickte er den Gesandten Zhang Qian nach Westen, um Verbündete gegen die Xiongnu zu suchen.',
        'Zhang Qian geriet zehn Jahre in Gefangenschaft, kehrte aber mit Wissen über Zentralasien zurück. Seine Reisen öffneten die Seidenstraße, über die Seide, Lack und Eisen nach Westen bis ins Römische Reich gingen und Pferde, Glas, Trauben und später der Buddhismus nach China kamen. Die Römer nannten die Chinesen „Serer“, das „Seidenvolk“.',
        'Unter den Han wurde um 105 n. Chr. das Papier verbessert – der Hofbeamte Cai Lun gilt als sein Erfinder. Weitere Erfindungen waren der Schubkarren, das Seismoskop des Gelehrten Zhang Heng zum Erkennen von Erdbeben und der Kompass aus Magnetstein. Der Historiker Sima Qian schrieb die „Aufzeichnungen des Großhistorikers“ (Shiji), das Vorbild aller späteren Geschichtsbücher.',
        'Von 9 bis 23 n. Chr. unterbrach der Usurpator Wang Mang die Han-Herrschaft. Am Ende schwächten Hofintrigen der Eunuchen und der Aufstand der „Gelben Turbane“ (184 n. Chr.) das Reich. 220 n. Chr. zerfiel es in die „Drei Reiche“ Wei, Shu und Wu, deren Kämpfe im Roman „Die Geschichte der Drei Reiche“ berühmt wurden. Erst 589 einte die Sui-Dynastie China wieder.',
      ],
      quiz: {
        leicht: [
          ['Wie lange regierte die Han-Dynastie etwa?', 'Über 400 Jahre', ['15 Jahre', '100 Jahre', '1.000 Jahre']],
          ['Wie nennt sich die größte Volksgruppe Chinas?', 'Han-Chinesen', ['Qin-Chinesen', 'Tang-Chinesen', 'Ming-Chinesen']],
          ['Welche Lehre machten die Han zur Staatslehre?', 'Den Konfuzianismus', ['Den Legalismus', 'Den Buddhismus', 'Den Daoismus']],
          ['Wie gingen die Han mit den Qin-Gesetzen um?', 'Sie milderten sie', ['Sie verschärften sie', 'Sie übernahmen sie unverändert', 'Sie schafften alle Gesetze ab']],
          ['Welcher Han-Kaiser dehnte das Reich weit aus?', 'Kaiser Wu', ['Liu Bang', 'Wang Mang', 'Qin Shi Huang']],
          ['Wonach wurden Beamte in Prüfungen ausgewählt?', 'Nach Kenntnis der konfuzianischen Klassiker', ['Nach Körperkraft', 'Nach Herkunft', 'Nach Reichtum']],
          ['Bis wann bestand das Prüfungssystem?', 'Bis 1905', ['Bis 220', 'Bis 1644', 'Bis heute']],
          ['Welchen Gesandten schickte Kaiser Wu nach Westen?', 'Zhang Qian', ['Marco Polo', 'Zheng He', 'Cai Lun']],
          ['Welche Handelsroute öffneten seine Reisen?', 'Die Seidenstraße', ['Die Gewürzroute', 'Die Bernsteinstraße', 'Den Kaiserkanal']],
          ['Welches Produkt ging über die Seidenstraße nach Westen?', 'Seide', ['Kartoffeln', 'Kaffee', 'Tabak']],
          ['Bis zu welchem Reich gelangte die Seide?', 'Bis ins Römische Reich', ['Bis nach Amerika', 'Bis nach Australien', 'Bis zu den Azteken']],
          ['Welche Religion kam über die Seidenstraße nach China?', 'Der Buddhismus', ['Das Christentum', 'Der Islam', 'Das Judentum']],
          ['Wie nannten die Römer die Chinesen?', 'Serer', ['Barbaren', 'Hunnen', 'Inder']],
          ['Welche Erfindung wird Cai Lun zugeschrieben?', 'Das Papier', ['Das Schießpulver', 'Der Buchdruck', 'Das Porzellan']],
          ['Was erkannte das Seismoskop von Zhang Heng?', 'Erdbeben', ['Gewitter', 'Sonnenfinsternisse', 'Feinde']],
          ['Welches Transportmittel erfanden die Han?', 'Den Schubkarren', ['Das Fahrrad', 'Das Auto', 'Die Eisenbahn']],
          ['Wer schrieb die „Aufzeichnungen des Großhistorikers“?', 'Sima Qian', ['Konfuzius', 'Cai Lun', 'Laozi']],
          ['Welcher Aufstand schwächte die Han 184 n. Chr.?', 'Der Aufstand der Gelben Turbane', ['Der Boxeraufstand', 'Der Taiping-Aufstand', 'Der Aufstand der Roten Turbane']],
          ['In welche Reiche zerfiel China 220 n. Chr.?', 'In die Drei Reiche', ['In die Zehn Reiche', 'In zwei Kaiserreiche', 'In hundert Staaten']],
          ['Welche Dynastie einte China 589 wieder?', 'Die Sui', ['Die Tang', 'Die Song', 'Die Han']],
        ],
        mittel: [
          ['Neben welcher Zeit gilt die Han-Zeit als goldenes Zeitalter?', 'Neben der Tang-Zeit', ['Neben der Qin-Zeit', 'Neben der Yuan-Zeit', 'Neben der Qing-Zeit']],
          ['Wie heißt die chinesische Schrift nach den Han?', 'Han-Zeichen', ['Qin-Zeichen', 'Shang-Zeichen', 'Orakelzeichen']],
          ['Wann regierte Kaiser Wu?', '141–87 v. Chr.', ['221–210 v. Chr.', '206–195 v. Chr.', '618–649']],
          ['Wohin dehnte Kaiser Wu das Reich aus?', 'Nach Korea, Vietnam und Zentralasien', ['Nach Japan und Indien', 'Nach Europa', 'Nach Sibirien und Alaska']],
          ['Wann schickte Kaiser Wu Zhang Qian los?', '138 v. Chr.', ['221 v. Chr.', '105 n. Chr.', '9 n. Chr.']],
          ['Wozu sollte Zhang Qian Verbündete suchen?', 'Gegen die Xiongnu', ['Gegen Rom', 'Gegen Japan', 'Gegen die Mongolen']],
          ['Wie lange war Zhang Qian in Gefangenschaft?', 'Zehn Jahre', ['Ein Jahr', 'Dreißig Jahre', 'Zehn Tage']],
          ['Was brachte Zhang Qian zurück?', 'Wissen über Zentralasien', ['Gold aus Rom', 'Den Buddhismus sofort', 'Eine Armee']],
          ['Was ging außer Seide nach Westen?', 'Lack und Eisen', ['Kartoffeln und Mais', 'Kaffee und Tee', 'Tabak und Zucker']],
          ['Was kam über die Seidenstraße nach China?', 'Pferde, Glas und Trauben', ['Papier und Porzellan', 'Seide und Tee', 'Reis und Hirse']],
          ['Was bedeutet „Serer“?', 'Seidenvolk', ['Bergvolk', 'Reitervolk', 'Drachenvolk']],
          ['Wann wurde das Papier verbessert?', 'Um 105 n. Chr.', ['Um 221 v. Chr.', 'Um 1000 n. Chr.', 'Um 1450 n. Chr.']],
          ['Welches Amt hatte Cai Lun?', 'Hofbeamter', ['Kaiser', 'General', 'Bauer']],
          ['Welcher Gelehrte baute das Seismoskop?', 'Zhang Heng', ['Zhang Qian', 'Sima Qian', 'Cai Lun']],
          ['Woraus bestand der frühe Kompass?', 'Aus Magnetstein', ['Aus Gold', 'Aus Glas', 'Aus Holz']],
          ['Wie heißt Sima Qians Werk auf Chinesisch?', 'Shiji', ['Lunyu', 'Daodejing', 'Sanguozhi']],
          ['Wer unterbrach die Han-Herrschaft von 9 bis 23 n. Chr.?', 'Wang Mang', ['Liu Bang', 'Cao Cao', 'Kaiser Wu']],
          ['Wer schwächte den Han-Hof durch Intrigen?', 'Die Eunuchen', ['Die Mönche', 'Die Bauern', 'Die Römer']],
          ['Wie hießen die Drei Reiche?', 'Wei, Shu und Wu', ['Qin, Han und Tang', 'Song, Yuan und Ming', 'Lu, Qi und Chu']],
          ['Welcher Roman machte die Drei Reiche berühmt?', '„Die Geschichte der Drei Reiche“', ['„Die Reise nach Westen“', '„Der Traum der roten Kammer“', '„Die Räuber vom Liangshan-Moor“']],
        ],
        schwer: [
          ['Welche Institution begann unter Kaiser Wu?', 'Das kaiserliche Prüfungssystem', ['Die Große Mauer', 'Der Kaiserkanal', 'Die Verbotene Stadt']],
          ['Welcher Gesandte gilt als Wegbereiter der Seidenstraße?', 'Zhang Qian', ['Ban Chao', 'Faxian', 'Xuanzang']],
          ['Welcher Herrscher regierte zwischen früher und später Han-Zeit?', 'Wang Mang', ['Cao Cao', 'Dong Zhuo', 'Liu Bei']],
          ['Welches Jahr markiert den Aufstand der Gelben Turbane?', '184 n. Chr.', ['220 n. Chr.', '9 n. Chr.', '105 n. Chr.']],
          ['Welches Werk gilt als Vorbild aller späteren chinesischen Geschichtsbücher?', 'Das Shiji des Sima Qian', ['Die Gespräche des Konfuzius', 'Das Daodejing', 'Das Buch der Lieder']],
          ['Welche Erfindung der Han diente der Erdbebenerkennung?', 'Das Seismoskop', ['Der Kompass', 'Die Wasseruhr', 'Das Astrolabium']],
          ['Welcher Gelehrte erfand das Seismoskop?', 'Zhang Heng', ['Shen Kuo', 'Bi Sheng', 'Su Song']],
          ['Welche Produkte führten die Römer aus China ein?', 'Seide', ['Kartoffeln', 'Porzellan aus der Ming-Zeit', 'Tee in Beuteln']],
          ['Wie lange war China nach den Han geteilt?', 'Bis 589', ['Bis 618', 'Bis 960', 'Bis 1279']],
          ['Welcher Kaiser machte den Konfuzianismus zur Staatslehre?', 'Kaiser Wu', ['Liu Bang', 'Qin Shi Huang', 'Wang Mang']],
          ['Welche Dynastie endete 220 n. Chr.?', 'Die Han', ['Die Qin', 'Die Sui', 'Die Tang']],
          ['Welche drei Reiche entstanden nach den Han?', 'Wei, Shu und Wu', ['Yan, Zhao und Qi', 'Liao, Jin und Song', 'Goguryeo, Baekje und Silla']],
          ['Welcher Roman über die Drei Reiche ist ein Klassiker?', '„Die Geschichte der Drei Reiche“', ['„Die Reise nach Westen“', '„Die Kunst des Krieges“', '„Shiji“']],
          ['Welche Gruppe am Hof trug zum Zerfall der Han bei?', 'Die Eunuchen', ['Die Mönche', 'Die Händler', 'Die Römer']],
          ['Welches Material verbesserte Cai Lun?', 'Papier', ['Bronze', 'Seide', 'Porzellan']],
          ['Welche Tiere kamen über die Seidenstraße nach China?', 'Pferde', ['Elefanten', 'Kängurus', 'Lamas']],
          ['Welches Land in Südostasien eroberte Kaiser Wu teilweise?', 'Vietnam', ['Thailand', 'Indonesien', 'Philippinen']],
          ['Bis wann wählte China Beamte durch Prüfungen?', '1905', ['1644', '1911', '1949']],
          ['Welche Dynastie beendete die Spaltung nach den Drei Reichen?', 'Die Sui', ['Die Jin', 'Die Tang', 'Die Song']],
          ['Welches Werkzeug zur Orientierung stammt aus der Han-Zeit?', 'Der Kompass aus Magnetstein', ['Der Sextant', 'Das Fernrohr', 'Die Seekarte aus Papier']],
        ],
      },
    },
  ],
};
