import type { Epoch } from '../types';

export const E2: Epoch = {
  id: 'mittelalter',
  name: 'Königreich und Entdeckungen',
  period: '1128–1580',
  events: [
    {
      id: 'gruendung',
      title: 'Die Gründung des Königreichs',
      date: '1128–1415',
      text: [
        'Afonso Henriques machte Portugal zum Königreich und eroberte Lissabon. 1249 war die Reconquista in Portugal abgeschlossen – über 240 Jahre früher als in Spanien. Mit dem Sieg von Aljubarrota sicherte das Haus Avis 1385 die Unabhängigkeit gegen Kastilien.',
      ],
      subtopics: [
        {
          id: 'afonso-henriques',
          title: 'Afonso Henriques und die Reconquista',
          date: '1128–1279',
          text: [
            'Nach seinem Sieg bei São Mamede kämpfte Afonso Henriques gegen die Mauren und gegen den König von León. 1139 besiegte er die Mauren in der Schlacht von Ourique und nannte sich danach König. Der Legende nach erschien ihm vor der Schlacht Christus; die fünf blauen Schilde im portugiesischen Wappen, die „Quinas“, sollen an fünf besiegte maurische Könige erinnern. 1143 erkannte ihn Alfons VII. von León im Vertrag von Zamora als König an. 1179 bestätigte Papst Alexander III. mit der Bulle „Manifestis probatum“ das Königreich, und Portugal versprach dem Papst dafür einen jährlichen Tribut.',
            '1147 eroberte Afonso Henriques nach viermonatiger Belagerung Lissabon – mit Hilfe von Kreuzfahrern aus England, Flandern und Deutschland, die im Zweiten Kreuzzug auf dem Weg ins Heilige Land waren. Im selben Jahr fiel auch Santarém. Seine Hauptstadt war Coimbra. Er erhielt den Beinamen „der Eroberer“, starb 1185 und ist im Kloster Santa Cruz in Coimbra begraben.',
            'Ritterorden halfen bei der Rückeroberung, vor allem die Templer, die in Tomar eine mächtige Burg mit Kloster errichteten, außerdem die Johanniter und die Orden von Avis und Santiago. 1153 gründete Afonso Henriques das Kloster Alcobaça und schenkte es den Zisterziensern; die Mönche machten weite Landstriche urbar.',
            'Sein Sohn Sancho I. hieß „der Besiedler“, weil er Siedler in die eroberten, oft entvölkerten Gebiete holte und Städte gründete. 1189 eroberte er mit Kreuzfahrern Silves, verlor die Stadt aber 1191 wieder an die Mauren. Afonso II. ließ 1211 auf einer Versammlung in Coimbra die ersten allgemeinen Gesetze des Königreichs erlassen.',
            '1249 eroberte Afonso III. Faro und damit die Algarve. Damit war die Reconquista in Portugal abgeschlossen – über 240 Jahre bevor Spanien 1492 Granada eroberte. Portugals Grenzen gehören deshalb zu den ältesten in Europa. Die Könige nannten sich nun „König von Portugal und der Algarve“. 1254 nahmen an der Ständeversammlung in Leiria, den „Cortes“, erstmals Vertreter der Städte teil, und um 1255 wurde Lissabon Hauptstadt.',
          ],
          quiz: {
            leicht: [
              ['Wer wurde der erste König Portugals?', 'Afonso Henriques', ['Sancho I.', 'Dinis', 'Manuel I.']],
              ['Nach welcher Schlacht nannte sich Afonso Henriques König?', 'Nach der Schlacht von Ourique', ['Nach der Schlacht von Aljubarrota', 'Nach der Schlacht von São Mamede', 'Nach der Schlacht von Alcácer-Quibir']],
              ['Wann siegte Afonso Henriques bei Ourique?', '1139', ['1128', '1147', '1249']],
              ['Was zeigen die „Quinas“ im portugiesischen Wappen?', 'Fünf blaue Schilde', ['Drei goldene Löwen', 'Einen schwarzen Adler', 'Sieben Burgen in Rot']],
              ['Welche Stadt eroberte Afonso Henriques 1147?', 'Lissabon', ['Porto', 'Faro', 'Granada']],
              ['Wer half 1147 bei der Eroberung Lissabons?', 'Kreuzfahrer', ['Wikinger', 'Mauren', 'Römer']],
              ['Welchen Beinamen erhielt Afonso Henriques?', 'Der Eroberer', ['Der Besiedler', 'Der Bauernkönig', 'Der Glückliche']],
              ['Welche Stadt war die Hauptstadt von Afonso Henriques?', 'Coimbra', ['Lissabon', 'Porto', 'Faro']],
              ['Welcher Ritterorden baute in Tomar eine Burg mit Kloster?', 'Die Templer', ['Der Deutsche Orden', 'Die Jesuiten', 'Die Franziskaner']],
              ['Welches Kloster gründete Afonso Henriques 1153?', 'Alcobaça', ['Batalha', 'Belém', 'Santa Cruz']],
              ['Wie hieß Sancho I. mit Beinamen?', 'Der Besiedler', ['Der Eroberer', 'Der Glückliche', 'Der Seefahrer']],
              ['Wann war die Reconquista in Portugal abgeschlossen?', '1249', ['1492', '1139', '1385']],
              ['Welche Region eroberte Afonso III. 1249?', 'Die Algarve', ['Den Minho', 'Galicien', 'Madeira']],
              ['Welche Stadt eroberte Spanien 1492 als letzte maurische Stadt?', 'Granada', ['Faro', 'Silves', 'Lissabon']],
              ['Welche Stadt wurde um 1255 Hauptstadt Portugals?', 'Lissabon', ['Coimbra', 'Porto', 'Guimarães']],
              ['Wer bestätigte 1179 das Königreich Portugal?', 'Der Papst', ['Der Kaiser', 'Der König von Frankreich', 'Der Kalif']],
              ['Was erschien Afonso Henriques der Legende nach vor Ourique?', 'Christus', ['Ein Drache', 'Der Papst', 'Ein Engel mit Schwert']],
              ['Wie heißt die Ständeversammlung in Portugal?', 'Cortes', ['Reichstag', 'Parlament von Paris', 'Senat']],
              ['Welche Stadt in der Algarve eroberte Afonso III.?', 'Faro', ['Silves', 'Lagos', 'Sagres']],
              ['Gegen wen kämpfte Afonso Henriques außer gegen die Mauren?', 'Gegen den König von León', ['Gegen den König von England', 'Gegen den Kaiser in Rom', 'Gegen die Wikinger']],
            ],
            mittel: [
              ['Wer erkannte Afonso Henriques 1143 als König an?', 'Alfons VII. von León', ['Papst Alexander III.', 'Alfons VI.', 'Der König von Frankreich']],
              ['In welchem Vertrag wurde Afonso Henriques 1143 anerkannt?', 'Im Vertrag von Zamora', ['Im Vertrag von Tordesillas', 'Im Vertrag von Windsor', 'Im Vertrag von Alcañices']],
              ['Wann bestätigte der Papst das Königreich?', '1179', ['1139', '1143', '1249']],
              ['Wie heißt die päpstliche Bulle von 1179?', '„Manifestis probatum“', ['„Unam sanctam“', '„Inter caetera“', '„Magna Carta“']],
              ['Was versprach Portugal dem Papst?', 'Einen jährlichen Tribut', ['Einen Kreuzzug nach Jerusalem', 'Die Stadt Lissabon', 'Ein Heer gegen Kastilien']],
              ['Woran sollen die fünf Schilde im Wappen erinnern?', 'An fünf besiegte maurische Könige', ['An fünf Söhne des Königs', 'An fünf Provinzen', 'An fünf Kreuzzüge']],
              ['Wie lange dauerte die Belagerung Lissabons 1147?', 'Vier Monate', ['Vier Tage', 'Vier Jahre', 'Vierzig Jahre']],
              ['Woher kamen die Kreuzfahrer, die bei Lissabon halfen?', 'Aus England, Flandern und Deutschland', ['Aus Venedig und Genua', 'Aus Ungarn und Polen', 'Aus Byzanz']],
              ['Wohin waren die Kreuzfahrer 1147 eigentlich unterwegs?', 'Ins Heilige Land', ['Nach Indien', 'Nach Amerika', 'Nach Rom']],
              ['Welche Stadt fiel 1147 ebenfalls an Afonso Henriques?', 'Santarém', ['Faro', 'Silves', 'Granada']],
              ['Wo ist Afonso Henriques begraben?', 'Im Kloster Santa Cruz in Coimbra', ['In Alcobaça', 'In Batalha', 'In Belém']],
              ['Wann starb Afonso Henriques?', '1185', ['1139', '1147', '1249']],
              ['Welchen Mönchen schenkte Afonso Henriques Alcobaça?', 'Den Zisterziensern', ['Den Jesuiten', 'Den Templern', 'Den Franziskanern']],
              ['Was taten die Mönche von Alcobaça?', 'Sie machten Land urbar', ['Sie bauten Schiffe', 'Sie führten Krieg', 'Sie prägten Münzen']],
              ['Warum hieß Sancho I. „der Besiedler“?', 'Er holte Siedler in die eroberten Gebiete', ['Er gründete Kolonien in Afrika', 'Er hatte sehr viele Kinder', 'Er baute Bauernhäuser für sich']],
              ['Welche Stadt eroberte Sancho I. 1189 mit Kreuzfahrern?', 'Silves', ['Lissabon', 'Faro', 'Ceuta']],
              ['Was geschah 1191 mit Silves?', 'Die Mauren eroberten es zurück', ['Es wurde Hauptstadt', 'Es wurde verkauft', 'Ein Erdbeben zerstörte es']],
              ['Was ließ Afonso II. 1211 erlassen?', 'Die ersten allgemeinen Gesetze', ['Die erste Verfassung', 'Ein Verbot des Christentums', 'Die erste Steuer auf Gewürze']],
              ['Wie nannten sich die Könige ab 1249?', 'König von Portugal und der Algarve', ['Kaiser von Iberien', 'König von León und Portugal', 'Herr von Afrika']],
              ['Wie viele Jahre früher als Spanien beendete Portugal die Reconquista?', 'Über 240 Jahre', ['Rund 10 Jahre', 'Rund 50 Jahre', 'Über 500 Jahre']],
            ],
            schwer: [
              ['Welcher Papst bestätigte 1179 das Königreich Portugal?', 'Alexander III.', ['Innozenz III.', 'Urban II.', 'Gregor VII.']],
              ['In welchem Kreuzzug halfen Kreuzfahrer bei Lissabon?', 'Im Zweiten Kreuzzug', ['Im Ersten Kreuzzug', 'Im Vierten Kreuzzug', 'Im Kinderkreuzzug']],
              ['Wann wurde das Kloster Alcobaça gegründet?', '1153', ['1147', '1185', '1385']],
              ['Welche Ritterorden halfen außer den Templern?', 'Die Johanniter und die Orden von Avis und Santiago', ['Der Deutsche Orden und die Jesuiten', 'Die Benediktiner und die Dominikaner', 'Der Hosenbandorden und der Bathorden']],
              ['Wann verlor Sancho I. Silves wieder?', '1191', ['1189', '1249', '1147']],
              ['Wo ließ Afonso II. 1211 die ersten Gesetze erlassen?', 'In Coimbra', ['In Lissabon', 'In Guimarães', 'In Tomar']],
              ['Wann nahmen erstmals Vertreter der Städte an den Cortes teil?', '1254', ['1139', '1211', '1385']],
              ['Wo tagten 1254 die Cortes mit Vertretern der Städte?', 'In Leiria', ['In Lissabon', 'In Porto', 'In Faro']],
              ['Wer eroberte 1249 die Algarve?', 'Afonso III.', ['Afonso Henriques', 'Sancho I.', 'Dinis']],
              ['Welche Besonderheit haben Portugals Grenzen?', 'Sie gehören zu den ältesten Europas', ['Sie änderten sich jedes Jahrhundert', 'Sie wurden erst 1974 festgelegt', 'Sie verlaufen nur entlang von Flüssen']],
              ['Wie hieß der König, der Afonso Henriques 1143 anerkannte?', 'Alfons VII.', ['Alfons VI.', 'Ferdinand III.', 'Sancho III.']],
              ['Was für Gebiete besiedelte Sancho I.?', 'Eroberte, oft entvölkerte Gebiete', ['Inseln im Atlantik', 'Gebiete in Brasilien', 'Städte in Kastilien']],
              ['Wann wurde Lissabon etwa Hauptstadt?', 'Um 1255', ['Um 1147', 'Um 1385', 'Um 1500']],
              ['Wie lange vor Spanien beendete Portugal die Reconquista?', 'Über 240 Jahre', ['Rund 100 Jahre', 'Rund 24 Jahre', 'Über 400 Jahre']],
              ['Wann erkannte León Portugal als Königreich an?', '1143', ['1128', '1139', '1179']],
              ['Was gründete Afonso Henriques in Alcobaça?', 'Ein Kloster', ['Eine Universität', 'Eine Festung der Templer', 'Einen Hafen']],
              ['Wer folgte auf Afonso Henriques als König?', 'Sein Sohn Sancho I.', ['Sein Bruder Dinis', 'Sein Enkel Afonso III.', 'Seine Mutter Teresa']],
              ['Welche Stadt war Lissabons Vorgängerin als Hauptstadt?', 'Coimbra', ['Porto', 'Braga', 'Évora']],
              ['Was erhielt Portugal für seinen Tribut vom Papst?', 'Die Bestätigung als Königreich', ['Die Stadt Rom', 'Einen Kardinal', 'Das Recht auf Indien']],
              ['Wie viele maurische Könige soll Afonso Henriques bei Ourique besiegt haben?', 'Fünf', ['Drei', 'Sieben', 'Zwölf']],
            ],
          },
        },
        {
          id: 'dinis-avis',
          title: 'König Dinis, Aljubarrota und das Haus Avis',
          date: '1279–1415',
          text: [
            'König Dinis (1279–1325) wurde „der Bauernkönig“ genannt, weil er die Landwirtschaft förderte. Er ließ den Pinienwald von Leiria pflanzen, der Wanderdünen aufhielt und später Holz für Schiffe lieferte. 1290 gründete er in Lissabon die erste Universität des Landes, die später nach Coimbra verlegt wurde. Er machte Portugiesisch statt Latein zur Amtssprache und dichtete selbst Lieder. 1297 legte er im Vertrag von Alcañices mit Kastilien eine Grenze fest, die bis heute fast unverändert gilt.',
            'Als der Papst 1312 den Templerorden auflöste, gründete Dinis 1319 den Christusorden, der den Besitz der Templer übernahm. Später finanzierte dieser Orden die Entdeckungsfahrten; sein rotes Kreuz prangte auf den Segeln der Schiffe. Dinis’ Frau, Königin Isabel aus Aragón, war für ihre Wohltätigkeit berühmt. Nach dem „Rosenwunder“ verwandelte sich das Brot, das sie heimlich an Arme verteilen wollte, in Rosen, als der König sie ertappte. Sie wurde heiliggesprochen.',
            'Kronprinz Pedro verliebte sich in die Hofdame Inês de Castro aus Galicien. Sein Vater, König Afonso IV., fürchtete den Einfluss ihrer kastilischen Familie und ließ sie 1355 ermorden. Als Pedro I. König wurde, ließ er zwei der Mörder grausam hinrichten. Der Legende nach ließ er die tote Inês krönen und den Hof ihre Hand küssen. Ihre Gräber stehen sich im Kloster Alcobaça gegenüber, damit sie sich am Jüngsten Tag als Erstes sehen.',
            '1348 tötete die Pest, der „Schwarze Tod“, etwa ein Drittel der Bevölkerung. 1383 starb König Ferdinand I. ohne Sohn; seine Tochter Beatriz war mit dem König von Kastilien verheiratet, und Portugal drohte an Kastilien zu fallen. In der Krise von 1383–1385 unterstützte das Volk von Lissabon Johann, den Großmeister des Ordens von Avis und unehelichen Sohn Pedros I. 1385 wählten ihn die Cortes in Coimbra als Johann I. zum König.',
            'Am 14. August 1385 besiegten Johann I. und sein Feldherr Nuno Álvares Pereira in der Schlacht von Aljubarrota mit Hilfe englischer Bogenschützen das viel größere kastilische Heer. Zum Dank ließ Johann das Kloster Batalha („Schlacht“) bauen. 1386 schloss er mit England den Vertrag von Windsor – das älteste noch gültige Bündnis der Welt. Johann heiratete Philippa von Lancaster; ihre Söhne nennt man die „erlauchte Generation“, zu ihnen gehörte Heinrich der Seefahrer.',
          ],
          quiz: {
            leicht: [
              ['Wie wurde König Dinis genannt?', 'Der Bauernkönig', ['Der Eroberer', 'Der Seefahrer', 'Der Glückliche']],
              ['Welchen Wald ließ Dinis pflanzen?', 'Den Pinienwald von Leiria', ['Den Schwarzwald', 'Den Korkeichenwald der Algarve', 'Den Lorbeerwald auf Madeira']],
              ['Was gründete Dinis 1290 in Lissabon?', 'Die erste Universität', ['Die erste Bank', 'Den ersten Hafen', 'Das erste Theater']],
              ['Wohin wurde die Universität später verlegt?', 'Nach Coimbra', ['Nach Porto', 'Nach Braga', 'Nach Évora']],
              ['Welche Sprache machte Dinis zur Amtssprache?', 'Portugiesisch', ['Latein', 'Spanisch', 'Arabisch']],
              ['Welcher Orden wurde 1312 vom Papst aufgelöst?', 'Der Templerorden', ['Der Christusorden', 'Der Jesuitenorden', 'Der Deutsche Orden']],
              ['Welchen Orden gründete Dinis 1319?', 'Den Christusorden', ['Den Templerorden', 'Den Orden von Avis', 'Den Johanniterorden']],
              ['Welches Zeichen trugen die Segel der Entdeckerschiffe?', 'Das rote Kreuz des Christusordens', ['Einen goldenen Löwen', 'Einen schwarzen Adler', 'Eine weiße Rose']],
              ['Wie heißt das Wunder der Königin Isabel?', 'Rosenwunder', ['Brotwunder', 'Weinwunder', 'Sternenwunder']],
              ['In wen verliebte sich Kronprinz Pedro?', 'In Inês de Castro', ['In Isabel von Aragón', 'In Philippa von Lancaster', 'In Beatriz']],
              ['Was geschah 1355 mit Inês de Castro?', 'Sie wurde ermordet', ['Sie wurde Königin von Kastilien', 'Sie floh nach England', 'Sie ging ins Kloster']],
              ['Wo stehen die Gräber von Pedro und Inês?', 'Im Kloster Alcobaça', ['Im Kloster Batalha', 'In der Kathedrale von Lissabon', 'In Coimbra']],
              ['Welche Seuche wütete 1348?', 'Die Pest', ['Die Cholera', 'Die Pocken', 'Die Grippe']],
              ['Welches Reich drohte Portugal 1383 zu übernehmen?', 'Kastilien', ['England', 'Frankreich', 'Marokko']],
              ['Wer wurde 1385 König?', 'Johann I.', ['Pedro I.', 'Ferdinand I.', 'Dinis']],
              ['Wo besiegte Portugal 1385 Kastilien?', 'Bei Aljubarrota', ['Bei Ourique', 'Bei São Mamede', 'Bei Alcácer-Quibir']],
              ['Was bedeutet „Batalha“?', 'Schlacht', ['Sieg', 'Kirche', 'Burg']],
              ['Mit welchem Land schloss Portugal 1386 ein Bündnis?', 'Mit England', ['Mit Frankreich', 'Mit Kastilien', 'Mit Venedig']],
              ['Was ist das Besondere am Vertrag von Windsor?', 'Er ist das älteste noch gültige Bündnis der Welt', ['Er beendete die Reconquista', 'Er teilte die Welt auf', 'Er wurde nach einem Jahr gebrochen']],
              ['Welcher berühmte Prinz war ein Sohn Johanns I.?', 'Heinrich der Seefahrer', ['Vasco da Gama', 'Afonso Henriques', 'Sebastian']],
            ],
            mittel: [
              ['Wann regierte König Dinis?', '1279–1325', ['1139–1185', '1385–1433', '1495–1521']],
              ['Wozu diente der Pinienwald von Leiria?', 'Er hielt Wanderdünen auf und lieferte Holz für Schiffe', ['Er war ein Jagdrevier', 'Er schützte vor den Mauren', 'Er lieferte Kork für Wein']],
              ['Was tat Dinis selbst als Künstler?', 'Er dichtete Lieder', ['Er malte Azulejos', 'Er baute Orgeln', 'Er schrieb Theaterstücke']],
              ['In welchem Vertrag legte Dinis die Grenze zu Kastilien fest?', 'Im Vertrag von Alcañices', ['Im Vertrag von Zamora', 'Im Vertrag von Windsor', 'Im Vertrag von Tordesillas']],
              ['Wann wurde der Vertrag von Alcañices geschlossen?', '1297', ['1143', '1385', '1494']],
              ['Wessen Besitz übernahm der Christusorden?', 'Den der Templer', ['Den der Jesuiten', 'Den des Papstes', 'Den der Mauren']],
              ['Was finanzierte der Christusorden später?', 'Die Entdeckungsfahrten', ['Den Bau von Universitäten', 'Kreuzzüge nach Jerusalem', 'Den Krieg gegen England']],
              ['Woher stammte Königin Isabel?', 'Aus Aragón', ['Aus Kastilien', 'Aus England', 'Aus Frankreich']],
              ['Was geschah beim Rosenwunder?', 'Brot für die Armen verwandelte sich in Rosen', ['Rosen blühten im Winter auf dem Schloss', 'Wein verwandelte sich in Wasser', 'Ein Rosenstrauch rettete den König']],
              ['Was wurde Königin Isabel nach ihrem Tod?', 'Eine Heilige', ['Eine Märtyrerin der Mauren', 'Eine Päpstin', 'Eine Kaiserin']],
              ['Woher stammte Inês de Castro?', 'Aus Galicien', ['Aus Aragón', 'Aus England', 'Aus Burgund']],
              ['Wer ließ Inês de Castro ermorden?', 'König Afonso IV.', ['Pedro I.', 'Johann I.', 'Dinis']],
              ['Warum ließ Afonso IV. Inês ermorden?', 'Er fürchtete den Einfluss ihrer kastilischen Familie', ['Sie hatte ihn bestohlen', 'Sie war eine Spionin Englands', 'Sie wollte Nonne werden']],
              ['Was soll Pedro I. mit der toten Inês getan haben?', 'Er ließ sie krönen', ['Er ließ sie nach Galicien bringen', 'Er ließ sie verbrennen', 'Er ließ sie im Meer bestatten']],
              ['Wie viel der Bevölkerung tötete die Pest 1348 etwa?', 'Ein Drittel', ['Ein Zehntel', 'Die Hälfte', 'Neun Zehntel']],
              ['Mit wem war Ferdinands Tochter Beatriz verheiratet?', 'Mit dem König von Kastilien', ['Mit dem König von England', 'Mit Johann I.', 'Mit dem Kaiser']],
              ['Welches Amt hatte Johann vor seiner Wahl zum König?', 'Großmeister des Ordens von Avis', ['Bischof von Lissabon', 'Admiral der Flotte', 'Kanzler von Kastilien']],
              ['Wer unterstützte Johann in der Krise 1383–1385?', 'Das Volk von Lissabon', ['Der König von Kastilien', 'Die Mauren', 'Der Adel von Galicien']],
              ['Welcher Feldherr siegte mit Johann I. bei Aljubarrota?', 'Nuno Álvares Pereira', ['Vasco da Gama', 'Afonso de Albuquerque', 'Bartolomeu Dias']],
              ['Wen heiratete Johann I.?', 'Philippa von Lancaster', ['Isabel von Aragón', 'Inês de Castro', 'Beatriz von Kastilien']],
            ],
            schwer: [
              ['Wann gründete Dinis die Universität in Lissabon?', '1290', ['1319', '1255', '1385']],
              ['Wann gründete Dinis den Christusorden?', '1319', ['1312', '1290', '1415']],
              ['Wann löste der Papst den Templerorden auf?', '1312', ['1319', '1297', '1179']],
              ['Wann wurde Inês de Castro ermordet?', '1355', ['1348', '1383', '1325']],
              ['Was ließ Pedro I. mit zwei der Mörder tun?', 'Er ließ sie grausam hinrichten', ['Er begnadigte sie', 'Er schickte sie nach Afrika', 'Er machte sie zu Rittern']],
              ['Warum stehen sich die Gräber von Pedro und Inês gegenüber?', 'Damit sie sich am Jüngsten Tag als Erstes sehen', ['Weil der Platz nicht reichte', 'Weil sie verfeindet waren', 'Weil es der Papst befahl']],
              ['Wann starb König Ferdinand I.?', '1383', ['1385', '1355', '1348']],
              ['Was fehlte Ferdinand I.?', 'Ein Sohn als Erbe', ['Eine Krone', 'Ein Heer', 'Eine Hauptstadt']],
              ['Wessen unehelicher Sohn war Johann I.?', 'Der Sohn Pedros I.', ['Der Sohn Ferdinands I.', 'Der Sohn von Dinis', 'Der Sohn Afonsos IV.']],
              ['Wo wählten die Cortes 1385 Johann zum König?', 'In Coimbra', ['In Lissabon', 'In Aljubarrota', 'In Batalha']],
              ['An welchem Tag fand die Schlacht von Aljubarrota statt?', 'Am 14. August 1385', ['Am 25. April 1385', 'Am 1. Dezember 1385', 'Am 4. August 1385']],
              ['Wer half Portugal bei Aljubarrota?', 'Englische Bogenschützen', ['Französische Ritter', 'Maurische Reiter', 'Venezianische Seeleute']],
              ['Wie groß war das kastilische Heer bei Aljubarrota?', 'Viel größer als das portugiesische', ['Viel kleiner', 'Genau gleich groß', 'Es kam gar nicht']],
              ['Wann wurde der Vertrag von Windsor geschlossen?', '1386', ['1385', '1415', '1297']],
              ['Wie nennt man die Söhne Johanns I. und Philippas?', 'Die erlauchte Generation', ['Die verlorene Generation', 'Die goldene Generation', 'Die Seefahrergeneration']],
              ['Wo sollte die Grenze von 1297 gelten?', 'Zwischen Portugal und Kastilien', ['Zwischen Portugal und den Mauren', 'Zwischen Portugal und England', 'Zwischen Spanien und Frankreich']],
              ['Welche Sprache verdrängte Dinis aus der Verwaltung?', 'Latein', ['Arabisch', 'Kastilisch', 'Französisch']],
              ['Was erinnert in Batalha an Aljubarrota?', 'Ein Kloster', ['Ein Leuchtturm', 'Eine Universität', 'Ein Königspalast']],
              ['Für was war Königin Isabel berühmt?', 'Für ihre Wohltätigkeit', ['Für ihre Feldzüge', 'Für ihre Gedichte', 'Für ihre Seefahrten']],
              ['Wer drohte 1383 durch Beatriz König von Portugal zu werden?', 'Der König von Kastilien', ['Der König von England', 'Der Großmeister von Avis', 'Der Papst']],
            ],
          },
        },
      ],
    },
    {
      id: 'entdeckungen',
      title: 'Das Zeitalter der Entdeckungen',
      date: '1415–1580',
      text: [
        'Portugal tastete sich Schritt für Schritt an der Küste Afrikas entlang, umrundete das Kap der Guten Hoffnung, fand den Seeweg nach Indien und erreichte Brasilien. So entstand das erste weltumspannende Seereich der Neuzeit – bis König Sebastian 1578 in Marokko fiel und Portugal an Spanien kam.',
      ],
      subtopics: [
        {
          id: 'heinrich-afrika',
          title: 'Heinrich der Seefahrer und der Weg um Afrika',
          date: '1415–1488',
          text: [
            '1415 eroberte Portugal die Stadt Ceuta in Nordafrika – der Beginn der Expansion. Die Portugiesen suchten Gold und Gewürze, wollten gegen die Muslime kämpfen, hofften auf den sagenhaften christlichen „Priesterkönig Johannes“ und schließlich auf einen Seeweg nach Indien. Treibende Kraft war Prinz Heinrich der Seefahrer (1394–1460). Er selbst fuhr kaum zur See, finanzierte aber als Leiter des Christusordens von der Algarve aus, von Sagres und Lagos, zahlreiche Fahrten.',
            'Das wichtigste Schiff war die Karavelle: leicht und wendig, mit dreieckigen Lateinersegeln, mit denen sie gegen den Wind kreuzen konnte. Die Seefahrer navigierten mit Kompass, Astrolabium und Quadrant und zeichneten genaue Seekarten. An neu erreichten Küsten errichteten sie „Padrões“, Steinsäulen mit Kreuz und Wappen, als Zeichen ihres Anspruchs.',
            'Um 1419/20 erreichten die Portugiesen Madeira, ab 1427 die Azoren; beide Inselgruppen waren unbewohnt und wurden besiedelt, auf Madeira baute man Zuckerrohr an. 1434 umrundete Gil Eanes das Kap Bojador, das als Ende der Welt galt – Seeleute fürchteten dahinter ein kochendes Meer und Ungeheuer. 1444 wurden in Lagos erstmals afrikanische Sklaven verkauft; damit begann der atlantische Sklavenhandel. Um 1456 wurden die Kapverdischen Inseln entdeckt.',
            'Nach Heinrichs Tod 1460 gingen die Fahrten weiter. 1471 erreichten die Portugiesen die Goldküste, 1482 bauten sie dort die Festung São Jorge da Mina (Elmina) für den Goldhandel. Diogo Cão erreichte 1482 die Mündung des Kongo. Der König des Kongoreiches nahm Kontakt zu Portugal auf und ließ sich taufen.',
            '1488 umsegelte Bartolomeu Dias als erster Europäer die Südspitze Afrikas. Er nannte sie „Kap der Stürme“, doch König Johann II. benannte sie in „Kap der Guten Hoffnung“ um – denn nun bestand Hoffnung auf den Seeweg nach Indien. Johann II. lehnte dagegen den Plan des Christoph Kolumbus ab, Indien im Westen zu erreichen; Kolumbus ging deshalb nach Spanien.',
          ],
          quiz: {
            leicht: [
              ['Welche Stadt in Nordafrika eroberte Portugal 1415?', 'Ceuta', ['Tanger', 'Kairo', 'Tunis']],
              ['Welcher Prinz trieb die Entdeckungsfahrten voran?', 'Heinrich der Seefahrer', ['Vasco da Gama', 'Johann I.', 'Sebastian']],
              ['Fuhr Heinrich der Seefahrer selbst viel zur See?', 'Nein, kaum', ['Ja, er umrundete Afrika', 'Ja, er erreichte Indien', 'Ja, er entdeckte Brasilien']],
              ['Von welcher Region aus ließ Heinrich die Fahrten starten?', 'Von der Algarve', ['Von Porto', 'Von Madeira', 'Von Galicien']],
              ['Wie hieß das wichtigste Schiff der Entdecker?', 'Karavelle', ['Galeere', 'Kogge', 'Drachenboot']],
              ['Welche Segel hatte die Karavelle?', 'Dreieckige Lateinersegel', ['Nur Ruder', 'Quadratische Rahsegel', 'Segel aus Metall']],
              ['Welches Navigationsgerät benutzten die Seefahrer?', 'Den Kompass', ['Das GPS', 'Das Radar', 'Das Fernglas mit Laser']],
              ['Welche Inselgruppe erreichten die Portugiesen um 1419/20?', 'Madeira', ['Die Kanaren', 'Die Azoren', 'Die Kapverden']],
              ['Was baute man auf Madeira an?', 'Zuckerrohr', ['Kaffee', 'Tee', 'Baumwolle']],
              ['Welches Kap galt als Ende der Welt?', 'Kap Bojador', ['Kap der Guten Hoffnung', 'Kap Hoorn', 'Kap Verde']],
              ['Wer umrundete 1434 das Kap Bojador?', 'Gil Eanes', ['Bartolomeu Dias', 'Diogo Cão', 'Vasco da Gama']],
              ['Was begann 1444 in Lagos?', 'Der atlantische Sklavenhandel', ['Der Gewürzhandel mit Indien', 'Der Bau der Karavellen', 'Die Reconquista']],
              ['Wer umsegelte 1488 als erster Europäer die Südspitze Afrikas?', 'Bartolomeu Dias', ['Vasco da Gama', 'Kolumbus', 'Magellan']],
              ['Wie nannte Bartolomeu Dias die Südspitze Afrikas?', 'Kap der Stürme', ['Kap der Guten Hoffnung', 'Kap des Teufels', 'Kap der Wunder']],
              ['Wie heißt die Südspitze Afrikas nach Johann II.?', 'Kap der Guten Hoffnung', ['Kap der Stürme', 'Kap Bojador', 'Kap Hoorn']],
              ['Wessen Plan lehnte Johann II. ab?', 'Den Plan von Kolumbus', ['Den Plan von Vasco da Gama', 'Den Plan von Heinrich', 'Den Plan von Magellan']],
              ['Für welches Land fuhr Kolumbus schließlich?', 'Für Spanien', ['Für Portugal', 'Für England', 'Für Frankreich']],
              ['Wonach suchten die Portugiesen in Afrika unter anderem?', 'Nach Gold', ['Nach Erdöl', 'Nach Kartoffeln', 'Nach Kohle']],
              ['Welches Ziel hatten die Portugiesen schließlich?', 'Einen Seeweg nach Indien', ['Den Weg nach Amerika', 'Den Nordpol', 'Australien']],
              ['Wann starb Heinrich der Seefahrer?', '1460', ['1415', '1488', '1498']],
            ],
            mittel: [
              ['Welchen sagenhaften Herrscher hofften die Portugiesen zu finden?', 'Den Priesterkönig Johannes', ['König Artus', 'Den Großkhan', 'König Salomo']],
              ['Als Leiter welches Ordens finanzierte Heinrich die Fahrten?', 'Des Christusordens', ['Des Templerordens', 'Des Jesuitenordens', 'Des Ordens von Avis']],
              ['Von welchen Orten der Algarve starteten die Fahrten?', 'Von Sagres und Lagos', ['Von Faro und Tavira', 'Von Silves und Albufeira', 'Von Portimão und Loulé']],
              ['Was konnte die Karavelle dank ihrer Segel?', 'Gegen den Wind kreuzen', ['Unter Wasser fahren', 'Ohne Mannschaft segeln', 'Fliegen']],
              ['Welche Geräte nutzte man außer dem Kompass?', 'Astrolabium und Quadrant', ['Teleskop und Radar', 'Barometer und Thermometer', 'Sextant und Chronometer']],
              ['Was waren „Padrões“?', 'Steinsäulen mit Kreuz und Wappen', ['Portugiesische Münzen', 'Seekarten', 'Schiffsanker']],
              ['Ab wann erreichten die Portugiesen die Azoren?', 'Ab 1427', ['Ab 1488', 'Ab 1500', 'Ab 1385']],
              ['Wer lebte auf Madeira und den Azoren, als die Portugiesen kamen?', 'Niemand', ['Mauren', 'Kelten', 'Ureinwohner aus Afrika']],
              ['Was fürchteten Seeleute hinter dem Kap Bojador?', 'Ein kochendes Meer und Ungeheuer', ['Eisberge', 'Piraten aus England', 'Einen Abgrund am Nordpol']],
              ['Wann wurden in Lagos erstmals afrikanische Sklaven verkauft?', '1444', ['1415', '1488', '1500']],
              ['Wann wurden die Kapverdischen Inseln entdeckt?', 'Um 1456', ['Um 1420', 'Um 1500', 'Um 1415']],
              ['Wann erreichten die Portugiesen die Goldküste?', '1471', ['1415', '1498', '1444']],
              ['Welche Festung bauten die Portugiesen 1482 an der Goldküste?', 'São Jorge da Mina', ['Ceuta', 'Sagres', 'Belém']],
              ['Wofür diente São Jorge da Mina?', 'Für den Goldhandel', ['Für den Gewürzhandel', 'Als Gefängnis', 'Als Kloster']],
              ['Wer erreichte 1482 die Mündung des Kongo?', 'Diogo Cão', ['Gil Eanes', 'Bartolomeu Dias', 'Vasco da Gama']],
              ['Was tat der König des Kongoreiches?', 'Er ließ sich taufen', ['Er führte Krieg gegen Portugal', 'Er verkaufte sein Land', 'Er floh nach Indien']],
              ['Welcher König benannte das Kap der Guten Hoffnung?', 'Johann II.', ['Johann I.', 'Manuel I.', 'Heinrich der Seefahrer']],
              ['Warum hieß das Kap nun „der Guten Hoffnung“?', 'Es gab Hoffnung auf den Seeweg nach Indien', ['Dort fand man Gold', 'Dort war das Wetter gut', 'Dort lebten Christen']],
              ['Wie wollte Kolumbus Indien erreichen?', 'Über den Westen', ['Über den Osten um Afrika', 'Über Land', 'Über den Nordpol']],
              ['Wann wurde Heinrich der Seefahrer geboren?', '1394', ['1415', '1460', '1350']],
            ],
            schwer: [
              ['Welche Motive hatten die Portugiesen außer Gold und Gewürzen?', 'Kampf gegen die Muslime und die Suche nach dem Priesterkönig Johannes', ['Die Suche nach Atlantis', 'Die Flucht vor Kastilien', 'Die Suche nach neuen Weinsorten']],
              ['Was markierten die Padrões?', 'Den Anspruch Portugals auf eine Küste', ['Die Grenze zu Kastilien', 'Gräber von Seeleuten', 'Den Weg nach Amerika']],
              ['Wie wurde Madeira genutzt, nachdem man es entdeckt hatte?', 'Es wurde besiedelt', ['Es blieb unbewohnt', 'Es wurde an Spanien verkauft', 'Es wurde Gefängnisinsel']],
              ['Wann eroberte Portugal Ceuta?', '1415', ['1385', '1444', '1488']],
              ['Wie hieß die Festung São Jorge da Mina auch?', 'Elmina', ['Ceuta', 'Sagres', 'Mombasa']],
              ['Wann erreichte Diogo Cão den Kongo?', '1482', ['1471', '1488', '1434']],
              ['Wann umsegelte Bartolomeu Dias die Südspitze Afrikas?', '1488', ['1498', '1482', '1434']],
              ['Wann umrundete Gil Eanes Kap Bojador?', '1434', ['1415', '1444', '1488']],
              ['Was geschah nach Heinrichs Tod mit den Fahrten?', 'Die Fahrten gingen weiter', ['Die Fahrten wurden verboten', 'Sie verloren Ceuta', 'Sie gaben Madeira auf']],
              ['Was ist ein Astrolabium?', 'Ein Gerät zur Navigation', ['Ein Segeltyp', 'Ein Anker', 'Eine Kanone']],
              ['Was zeichneten die portugiesischen Seefahrer?', 'Genaue Seekarten', ['Porträts der Könige', 'Azulejos', 'Wappen für Kastilien']],
              ['Welche Eigenschaft hatte die Karavelle?', 'Sie war leicht und wendig', ['Sie war das größte Schiff der Welt', 'Sie hatte 100 Ruderer', 'Sie war aus Eisen']],
              ['Mit welchem Ziel wurde Elmina gebaut?', 'Für den Goldhandel', ['Als Missionsschule', 'Als Werft', 'Als Sklavenmarkt für Brasilien']],
              ['Welches Reich in Afrika nahm Kontakt zu Portugal auf?', 'Das Kongoreich', ['Das Reich von Mali', 'Äthiopien', 'Ägypten']],
              ['Welche Inselgruppe wurde zuletzt der drei entdeckt?', 'Die Kapverden', ['Madeira', 'Die Azoren', 'Alle gleichzeitig']],
              ['Wie lebte Heinrich der Seefahrer?', 'Er fuhr kaum zur See und organisierte die Fahrten', ['Er segelte bis Indien', 'Er war Kapitän einer Karavelle', 'Er lebte als Mönch in Tomar']],
              ['Was war der atlantische Sklavenhandel?', 'Der Handel mit verschleppten Afrikanern über den Atlantik', ['Der Handel mit Zucker', 'Der Handel mit Gewürzen', 'Der Handel mit Gold aus Elmina']],
              ['Wer war König, als Dias das Kap umsegelte?', 'Johann II.', ['Johann I.', 'Manuel I.', 'Afonso V.']],
              ['Was hoffte Portugal am Kap der Guten Hoffnung?', 'Den Seeweg nach Indien zu finden', ['Gold zu finden', 'Christen zu treffen', 'Amerika zu erreichen']],
              ['Wohin wandte sich Kolumbus nach der Ablehnung?', 'Nach Spanien', ['Nach England', 'Nach Venedig', 'Nach Frankreich']],
            ],
          },
        },
        {
          id: 'da-gama-brasilien',
          title: 'Tordesillas, Vasco da Gama und Brasilien',
          date: '1492–1506',
          text: [
            'Nachdem Kolumbus 1492 für Spanien Amerika erreicht hatte, stritten Spanien und Portugal um die neuen Gebiete. 1493 zog der Papst eine Grenzlinie, doch Portugal setzte 1494 im Vertrag von Tordesillas durch, dass sie weiter westlich verlief: 370 Meilen westlich der Kapverden. Was westlich lag, sollte Spanien gehören, was östlich lag, Portugal. Dadurch lag später der Osten Brasiliens in Portugals Hälfte.',
            '1497 brach Vasco da Gama mit vier Schiffen von Lissabon auf. Er umrundete das Kap der Guten Hoffnung und segelte an der Ostküste Afrikas entlang über Mosambik und Mombasa nach Malindi, wo ein erfahrener Lotse an Bord kam. Mit ihm überquerte er den Indischen Ozean und erreichte im Mai 1498 Kalikut an der Malabarküste Indiens. Der Seeweg nach Indien war gefunden.',
            'Als Vasco da Gama 1499 zurückkehrte, war mehr als die Hälfte seiner Männer gestorben, viele an Skorbut, einer Krankheit durch Mangel an Vitamin C. Doch seine Ladung aus Pfeffer und anderen Gewürzen brachte ein Vielfaches der Kosten ein. König Manuel I., „der Glückliche“, ließ in Belém das prächtige Hieronymuskloster und den Turm von Belém bauen. Ihr Baustil, die „Manuelinik“, ist mit Seilen, Ankern, Muscheln und der Armillarsphäre, einem Himmelsmodell, verziert.',
            'Im Jahr 1500 segelte Pedro Álvares Cabral mit einer großen Flotte nach Indien und holte dabei weit nach Westen aus. Am 22. April 1500 erreichte er die Küste Brasiliens und nahm sie für Portugal in Besitz. Der Name des Landes stammt vom Brasilholz, aus dem man roten Farbstoff gewann. Der Brief des Pêro Vaz de Caminha an den König, der die erste Begegnung mit den Ureinwohnern beschreibt, gilt als „Geburtsurkunde Brasiliens“.',
            'Manuel I. wollte eine spanische Prinzessin heiraten, deren Eltern eine Bedingung stellten: die Vertreibung der Juden. 1496/97 ordnete er sie an, ließ aber die meisten Juden zwangstaufen, die nun „Neuchristen“ hießen. 1506 töteten aufgebrachte Menschenmengen in Lissabon Hunderte Neuchristen. Viele flohen später nach Amsterdam. 1536 führte Portugal die Inquisition ein.',
          ],
          quiz: {
            leicht: [
              ['Welcher Seefahrer fand den Seeweg nach Indien?', 'Vasco da Gama', ['Bartolomeu Dias', 'Kolumbus', 'Magellan']],
              ['Wann erreichte Vasco da Gama Indien?', '1498', ['1492', '1488', '1500']],
              ['Welche Stadt in Indien erreichte Vasco da Gama?', 'Kalikut', ['Goa', 'Bombay', 'Delhi']],
              ['Welches Land erreichte Cabral im Jahr 1500?', 'Brasilien', ['Indien', 'Mexiko', 'Argentinien']],
              ['Woher hat Brasilien seinen Namen?', 'Vom Brasilholz', ['Von einem Indianerstamm', 'Von einem König', 'Vom Wort für heiß']],
              ['In welchem Vertrag teilten Spanien und Portugal die Welt auf?', 'Im Vertrag von Tordesillas', ['Im Vertrag von Windsor', 'Im Vertrag von Zamora', 'Im Vertrag von Versailles']],
              ['Wann wurde der Vertrag von Tordesillas geschlossen?', '1494', ['1492', '1500', '1385']],
              ['Wem sollte das Land westlich der Linie gehören?', 'Spanien', ['Portugal', 'Dem Papst', 'England']],
              ['Woran starben viele Männer Vasco da Gamas?', 'An Skorbut', ['An der Pest', 'An Malaria', 'An Hunger durch Schiffbruch']],
              ['Welcher Mangel verursacht Skorbut?', 'Mangel an Vitamin C', ['Mangel an Salz', 'Mangel an Wasser', 'Mangel an Eisen']],
              ['Welches Gewürz brachte Vasco da Gama vor allem mit?', 'Pfeffer', ['Vanille', 'Safran aus Spanien', 'Zucker']],
              ['Wie wurde König Manuel I. genannt?', 'Der Glückliche', ['Der Eroberer', 'Der Bauernkönig', 'Der Seefahrer']],
              ['Welches Kloster ließ Manuel I. in Belém bauen?', 'Das Hieronymuskloster', ['Das Kloster Batalha', 'Das Kloster Alcobaça', 'Das Kloster Santa Cruz']],
              ['Welcher Turm steht in Lissabon am Tejo?', 'Der Turm von Belém', ['Der Eiffelturm', 'Der Torre del Oro', 'Der Tower of London']],
              ['Wie heißt der Baustil unter Manuel I.?', 'Manuelinik', ['Gotik', 'Barock', 'Jugendstil']],
              ['Womit ist die Manuelinik verziert?', 'Mit Seilen, Ankern und Muscheln', ['Mit Drachen und Löwen', 'Mit Blumen und Vögeln', 'Mit Säulen und Giebeln wie in Athen']],
              ['Was gilt als „Geburtsurkunde Brasiliens“?', 'Der Brief des Pêro Vaz de Caminha', ['Der Vertrag von Tordesillas', 'Ein Gemälde von Cabral', 'Eine Bulle des Papstes']],
              ['Welche Gruppe vertrieb Manuel I. 1496/97?', 'Die Juden', ['Die Mauren', 'Die Engländer', 'Die Jesuiten']],
              ['Wie nannte man zwangsgetaufte Juden?', 'Neuchristen', ['Mozaraber', 'Altchristen', 'Konvertiten aus Rom']],
              ['Wann führte Portugal die Inquisition ein?', '1536', ['1496', '1506', '1580']],
            ],
            mittel: [
              ['Wann zog der Papst die erste Grenzlinie?', '1493', ['1494', '1492', '1500']],
              ['Wo verlief die Linie von Tordesillas?', '370 Meilen westlich der Kapverden', ['Entlang des Äquators', 'Durch das Mittelmeer', 'Entlang des Nils']],
              ['Was bewirkte die Verschiebung der Linie für Portugal?', 'Der Osten Brasiliens lag in Portugals Hälfte', ['Portugal bekam Mexiko', 'Portugal verlor Afrika', 'Portugal bekam die Kanaren']],
              ['Mit wie vielen Schiffen brach Vasco da Gama auf?', 'Mit vier', ['Mit einem', 'Mit zwanzig', 'Mit hundert']],
              ['Wann brach Vasco da Gama auf?', '1497', ['1492', '1498', '1500']],
              ['Wo kam ein erfahrener Lotse an Bord?', 'In Malindi', ['In Lissabon', 'In Kalikut', 'Am Kap der Guten Hoffnung']],
              ['Über welche Orte segelte Vasco da Gama an Afrikas Ostküste?', 'Über Mosambik und Mombasa', ['Über Kairo und Alexandria', 'Über Ceuta und Tanger', 'Über Elmina und den Kongo']],
              ['An welcher Küste Indiens liegt Kalikut?', 'An der Malabarküste', ['An der Koromandelküste', 'Am Himalaya', 'Am Ganges']],
              ['Wann kehrte Vasco da Gama zurück?', '1499', ['1498', '1500', '1502']],
              ['Wie viele seiner Männer starben?', 'Mehr als die Hälfte', ['Keiner', 'Nur einer', 'Ein Zehntel']],
              ['Was brachte die Ladung Vasco da Gamas ein?', 'Ein Vielfaches der Kosten', ['Gerade die Kosten', 'Einen großen Verlust', 'Nichts, sie wurde geraubt']],
              ['Was ist eine Armillarsphäre?', 'Ein Himmelsmodell', ['Ein Anker', 'Eine Kanone', 'Ein Segeltyp']],
              ['Wann erreichte Cabral Brasilien?', 'Am 22. April 1500', ['Am 12. Oktober 1492', 'Am 20. Mai 1498', 'Am 25. April 1974']],
              ['Wohin war Cabral eigentlich unterwegs?', 'Nach Indien', ['Nach Brasilien', 'Nach China', 'Zum Nordpol']],
              ['Wie kam Cabral nach Brasilien?', 'Er holte weit nach Westen aus', ['Ein Sturm trieb ihn aus dem Mittelmeer', 'Er folgte Kolumbus', 'Er überquerte den Pazifik']],
              ['Was gewann man aus Brasilholz?', 'Roten Farbstoff', ['Zucker', 'Kautschuk', 'Gold']],
              ['Wen beschreibt der Brief des Pêro Vaz de Caminha?', 'Die Ureinwohner Brasiliens', ['Die Bewohner Indiens', 'Den König von Kongo', 'Die Mauren in Ceuta']],
              ['Warum vertrieb Manuel I. die Juden?', 'Um eine spanische Prinzessin zu heiraten', ['Auf Befehl Englands', 'Wegen einer Seuche', 'Weil sie Kolumbus unterstützten']],
              ['Was geschah 1506 in Lissabon?', 'Menschenmengen töteten Hunderte Neuchristen', ['Ein Erdbeben zerstörte die Stadt', 'Vasco da Gama kehrte zurück', 'Die Inquisition wurde abgeschafft']],
              ['Wohin flohen viele Neuchristen später?', 'Nach Amsterdam', ['Nach Rom', 'Nach Madrid', 'Nach Moskau']],
            ],
            schwer: [
              ['Wer erreichte 1492 für Spanien Amerika?', 'Kolumbus', ['Vasco da Gama', 'Cabral', 'Magellan']],
              ['Was gehörte nach Tordesillas Portugal?', 'Was östlich der Linie lag', ['Was westlich der Linie lag', 'Was nördlich des Äquators lag', 'Nur die Kapverden']],
              ['Wie hieß der Brief, der die Entdeckung Brasiliens beschreibt, nach seinem Verfasser?', 'Brief des Pêro Vaz de Caminha', ['Brief des Cabral', 'Brief des Kolumbus', 'Brief des Manuel I.']],
              ['An wen schrieb Pêro Vaz de Caminha seinen Brief?', 'An den König', ['An den Papst', 'An Cabral', 'An Vasco da Gama']],
              ['Wann ordnete Manuel I. die Vertreibung der Juden an?', '1496/97', ['1492', '1506', '1536']],
              ['Was tat Manuel I. mit den meisten Juden statt sie zu vertreiben?', 'Er ließ sie zwangstaufen', ['Er ließ sie nach Indien bringen', 'Er gab ihnen Land in Brasilien', 'Er machte sie zu Adligen']],
              ['Wann wurden in Lissabon Hunderte Neuchristen getötet?', '1506', ['1496', '1536', '1500']],
              ['In welchem Monat erreichte Vasco da Gama Kalikut?', 'Im Mai 1498', ['Im Januar 1498', 'Im Dezember 1497', 'Im April 1500']],
              ['Welchen Ozean überquerte Vasco da Gama nach Indien?', 'Den Indischen Ozean', ['Den Pazifik', 'Den Arktischen Ozean', 'Das Mittelmeer']],
              ['Wo in Lissabon stehen das Hieronymuskloster und der Turm?', 'In Belém', ['In Alfama', 'In Sintra', 'In Porto']],
              ['Welches Symbol der Manuelinik ist ein Himmelsmodell?', 'Die Armillarsphäre', ['Der Anker', 'Das Seil', 'Die Muschel']],
              ['Welche Besonderheit hatte Cabrals Flotte?', 'Sie war groß und unterwegs nach Indien', ['Sie bestand aus einem einzigen Boot', 'Sie fuhr für Spanien', 'Sie suchte den Nordpol']],
              ['Welche Rolle spielte der Lotse aus Malindi?', 'Er half bei der Überquerung des Indischen Ozeans', ['Er verriet die Portugiesen', 'Er war Vasco da Gamas Bruder', 'Er zeichnete die Karte von Brasilien']],
              ['Welches Gewürz war die Hauptladung aus Indien?', 'Pfeffer', ['Muskat', 'Zimt', 'Gewürznelken']],
              ['Wer gewann durch die Verschiebung der Linie später Land in Südamerika?', 'Portugal', ['Spanien', 'England', 'Frankreich']],
              ['Woher stammte die Bedingung zur Vertreibung der Juden?', 'Von den Eltern der spanischen Prinzessin', ['Vom Papst', 'Vom König von England', 'Von der Inquisition in Lissabon']],
              ['Was beschreibt der Brief des Caminha?', 'Die erste Begegnung mit den Ureinwohnern Brasiliens', ['Die Fahrt nach Indien', 'Das Erdbeben von Lissabon', 'Die Gründung Macaus']],
              ['Wie viele Meilen westlich der Kapverden lag die Tordesillas-Linie?', '370', ['37', '3.700', '100']],
              ['Wann zog der Papst die Linie, die Portugal verschieben ließ?', '1493', ['1494', '1500', '1488']],
              ['Unter welchem König wurde die Manuelinik gebaut?', 'Manuel I.', ['Johann II.', 'Johann I.', 'Sebastian']],
            ],
          },
        },
        {
          id: 'seereich-alcacer',
          title: 'Das Seereich und das Ende des Hauses Avis',
          date: '1500–1580',
          text: [
            'Portugal baute kein großes Landreich, sondern ein Handelsimperium aus Stützpunkten: Handelsniederlassungen und Festungen an den Küsten Afrikas und Asiens. Afonso de Albuquerque eroberte 1510 Goa, das Hauptstadt des „Estado da Índia“ wurde und bis 1961 portugiesisch blieb, 1511 Malakka und 1515 Hormus am Persischen Golf. Auch die Gewürzinseln, die Molukken, wurden erreicht. Lissabon wurde zum Zentrum des europäischen Gewürzhandels.',
            '1513 erreichte Jorge Álvares als erster Europäer auf dem Seeweg China. 1557 durften sich die Portugiesen in Macau niederlassen, das bis 1999 portugiesisch blieb. 1543 landeten Portugiesen als erste Europäer in Japan und brachten Feuerwaffen mit; das japanische Wort „pan“ für Brot stammt aus dem Portugiesischen. Jesuiten wie Franz Xaver missionierten in Asien.',
            'Der Portugiese Ferdinand Magellan stand im Dienst Spaniens, als er 1519 zur ersten Weltumsegelung aufbrach. Er selbst wurde 1521 auf den Philippinen getötet; nur eines seiner fünf Schiffe kehrte 1522 nach Spanien zurück.',
            'Ab den 1530er-Jahren wurde Brasilien systematisch besiedelt und in Kapitanien aufgeteilt, große Landstriche, die an Adlige vergeben wurden. Auf Zuckerrohrplantagen mussten afrikanische Sklaven arbeiten. 1549 wurde Salvador da Bahia Hauptstadt der Kolonie. Der Nationaldichter Luís de Camões schrieb das Epos „Os Lusíadas“ (1572) über Vasco da Gamas Fahrt; der Legende nach rettete er das Manuskript bei einem Schiffbruch schwimmend. Sein Todestag, der 10. Juni, ist heute Nationalfeiertag.',
            'Der junge König Sebastian zog 1578 mit 24 Jahren zu einem Kreuzzug nach Marokko. In der Schlacht von Alcácer-Quibir am 4. August 1578 wurde sein Heer vernichtet, der König blieb verschollen. Viele Portugiesen glaubten, er werde eines nebligen Morgens zurückkehren und das Land retten – diesen Glauben nennt man „Sebastianismus“. Sein Nachfolger, der alte Kardinal Heinrich, starb 1580 kinderlos. Daraufhin setzte König Philipp II. von Spanien, ein Enkel Manuels I., seinen Anspruch mit einer Armee durch: Portugal und Spanien hatten nun denselben König.',
          ],
          quiz: {
            leicht: [
              ['Welche Stadt in Indien eroberte Albuquerque 1510?', 'Goa', ['Kalikut', 'Delhi', 'Bombay']],
              ['Woraus bestand das portugiesische Handelsimperium?', 'Aus Stützpunkten an den Küsten', ['Aus riesigen Landgebieten', 'Aus Inseln im Pazifik', 'Aus Städten in Europa']],
              ['Welche Stadt wurde Zentrum des europäischen Gewürzhandels?', 'Lissabon', ['Venedig', 'Amsterdam', 'London']],
              ['Wie heißen die Gewürzinseln?', 'Molukken', ['Azoren', 'Kapverden', 'Kanaren']],
              ['Welche Stadt in China war bis 1999 portugiesisch?', 'Macau', ['Hongkong', 'Shanghai', 'Peking']],
              ['In welches Land kamen Portugiesen 1543 als erste Europäer?', 'Nach Japan', ['Nach Korea', 'Nach Australien', 'Nach Neuseeland']],
              ['Was brachten die Portugiesen nach Japan?', 'Feuerwaffen', ['Reis', 'Seide', 'Tee']],
              ['Welches japanische Wort stammt aus dem Portugiesischen?', '„pan“ für Brot', ['„sushi“', '„samurai“', '„kimono“']],
              ['Welcher Portugiese brach 1519 zur ersten Weltumsegelung auf?', 'Ferdinand Magellan', ['Vasco da Gama', 'Cabral', 'Bartolomeu Dias']],
              ['Für welches Land segelte Magellan?', 'Für Spanien', ['Für Portugal', 'Für England', 'Für Frankreich']],
              ['Wo wurde Magellan getötet?', 'Auf den Philippinen', ['In Brasilien', 'In Indien', 'In Japan']],
              ['Welche Pflanze wurde in Brasilien auf Plantagen angebaut?', 'Zuckerrohr', ['Tee', 'Reis', 'Weizen']],
              ['Wer musste auf den Plantagen Brasiliens arbeiten?', 'Afrikanische Sklaven', ['Portugiesische Adlige', 'Japanische Händler', 'Mönche']],
              ['Wer ist der Nationaldichter Portugals?', 'Luís de Camões', ['Fernando Pessoa', 'Pêro Vaz de Caminha', 'Vasco da Gama']],
              ['Wie heißt das Epos von Camões?', '„Os Lusíadas“', ['„Don Quijote“', '„Die Göttliche Komödie“', '„Odyssee“']],
              ['Wovon handelt „Os Lusíadas“?', 'Von Vasco da Gamas Fahrt', ['Von der Reconquista', 'Von Kolumbus', 'Von Magellans Weltumsegelung']],
              ['Welcher Tag ist Portugals Nationalfeiertag zu Ehren von Camões?', 'Der 10. Juni', ['Der 25. April', 'Der 5. Oktober', 'Der 1. Dezember']],
              ['Wohin zog König Sebastian 1578?', 'Nach Marokko', ['Nach Indien', 'Nach Brasilien', 'Nach Spanien']],
              ['Was geschah mit König Sebastian?', 'Er blieb in der Schlacht verschollen', ['Er wurde Kaiser von Marokko', 'Er kehrte als Sieger zurück', 'Er floh nach Brasilien']],
              ['Wer wurde 1580 auch König von Portugal?', 'Philipp II. von Spanien', ['Heinrich VIII. von England', 'Franz I. von Frankreich', 'Karl der Große']],
            ],
            mittel: [
              ['Wie hieß das portugiesische Gebiet in Asien mit der Hauptstadt Goa?', 'Estado da Índia', ['Lusitania', 'Nova Lisboa', 'Índia Portuguesa do Norte']],
              ['Bis wann blieb Goa portugiesisch?', 'Bis 1961', ['Bis 1580', 'Bis 1822', 'Bis 1999']],
              ['Welche Stadt eroberte Albuquerque 1511?', 'Malakka', ['Goa', 'Macau', 'Hormus']],
              ['Wo liegt Hormus?', 'Am Persischen Golf', ['In Japan', 'In Brasilien', 'In Ostafrika']],
              ['Wann eroberte Albuquerque Hormus?', '1515', ['1510', '1543', '1498']],
              ['Wer erreichte 1513 als erster Europäer auf dem Seeweg China?', 'Jorge Álvares', ['Franz Xaver', 'Magellan', 'Albuquerque']],
              ['Wann durften sich Portugiesen in Macau niederlassen?', '1557', ['1513', '1543', '1999']],
              ['Welcher Jesuit missionierte in Asien?', 'Franz Xaver', ['Franz von Assisi', 'Martin Luther', 'Thomas von Aquin']],
              ['Wann wurde Magellan getötet?', '1521', ['1519', '1522', '1498']],
              ['Wie viele von Magellans Schiffen kehrten zurück?', 'Eines von fünf', ['Alle fünf', 'Keines', 'Drei von fünf']],
              ['Wann kehrte das letzte Schiff Magellans zurück?', '1522', ['1521', '1519', '1543']],
              ['Was waren Kapitanien in Brasilien?', 'Große Landstriche, die an Adlige vergeben wurden', ['Kriegsschiffe', 'Missionsstationen', 'Goldminen']],
              ['Welche Stadt wurde 1549 Hauptstadt Brasiliens?', 'Salvador da Bahia', ['Rio de Janeiro', 'São Paulo', 'Brasília']],
              ['Wann erschien „Os Lusíadas“?', '1572', ['1498', '1500', '1640']],
              ['Was soll Camões bei einem Schiffbruch gerettet haben?', 'Sein Manuskript', ['Den König', 'Seine Gewürze', 'Eine Karte']],
              ['Wie alt war König Sebastian 1578?', '24 Jahre', ['14 Jahre', '44 Jahre', '64 Jahre']],
              ['In welcher Schlacht wurde Sebastians Heer vernichtet?', 'In der Schlacht von Alcácer-Quibir', ['In der Schlacht von Aljubarrota', 'In der Schlacht von Ourique', 'In der Schlacht von Lepanto']],
              ['Was ist der „Sebastianismus“?', 'Der Glaube, König Sebastian werde zurückkehren', ['Eine Kunstrichtung', 'Ein Kreuzzug nach Jerusalem', 'Eine Lehre der Jesuiten']],
              ['Wer folgte König Sebastian auf den Thron?', 'Kardinal Heinrich', ['Philipp II.', 'Johann IV.', 'Manuel I.']],
              ['Wessen Enkel war Philipp II. von Spanien?', 'Manuels I.', ['Sebastians', 'Johanns I.', 'Heinrichs des Seefahrers']],
            ],
            schwer: [
              ['Wann fand die Schlacht von Alcácer-Quibir statt?', 'Am 4. August 1578', ['Am 14. August 1385', 'Am 22. April 1500', 'Am 1. Dezember 1640']],
              ['Wann starb Kardinal Heinrich?', '1580', ['1578', '1640', '1557']],
              ['Wie setzte Philipp II. seinen Anspruch durch?', 'Mit einer Armee', ['Durch Heirat', 'Durch eine Volksabstimmung', 'Durch Kauf']],
              ['An welchem Morgen soll Sebastian zurückkehren?', 'An einem nebligen Morgen', ['An Ostern', 'Am Jahrestag der Schlacht', 'Bei Vollmond']],
              ['Welchen Zweck hatte Sebastians Feldzug?', 'Einen Kreuzzug gegen Marokko', ['Die Eroberung Spaniens', 'Den Handel mit Gewürzen', 'Die Suche nach dem Priesterkönig Johannes']],
              ['Was haben Portugal und Spanien ab 1580?', 'Denselben König', ['Dieselbe Hauptstadt', 'Dieselbe Sprache', 'Keine gemeinsame Grenze mehr']],
              ['Woran erinnert der 10. Juni?', 'An den Todestag von Camões', ['An die Entdeckung Brasiliens', 'An die Schlacht von Aljubarrota', 'An die Nelkenrevolution']],
              ['Was förderten die Jesuiten in Asien?', 'Die Mission', ['Den Sklavenhandel', 'Den Krieg gegen China', 'Den Bau von Plantagen']],
              ['Wie viele Schiffe hatte Magellan beim Aufbruch?', 'Fünf', ['Eines', 'Drei', 'Zehn']],
              ['Warum fuhr Magellan nicht für Portugal?', 'Er stand im Dienst Spaniens', ['Portugal hatte keine Schiffe', 'Er war Spanier', 'Er war verbannt worden']],
              ['Welche Stadt in Südostasien eroberten die Portugiesen?', 'Malakka', ['Singapur', 'Bangkok', 'Manila']],
              ['Was waren die Portugiesen, die 1543 in Japan landeten?', 'Die ersten Europäer dort', ['Die ersten Chinesen dort', 'Eroberer der Hauptstadt', 'Gefangene des Kaisers']],
              ['Woraus gewann Brasilien in der frühen Kolonialzeit vor allem Reichtum?', 'Aus Zuckerrohr', ['Aus Kaffee', 'Aus Erdöl', 'Aus Kautschuk']],
              ['Wann wurde Brasilien systematisch besiedelt?', 'Ab den 1530er-Jahren', ['Ab 1500 sofort', 'Ab 1700', 'Ab 1822']],
              ['Was war Goa für Portugals Asienreich?', 'Die Hauptstadt', ['Ein Gefängnis', 'Ein Kloster', 'Ein Hafen für Sklaven aus Brasilien']],
              ['Wer eroberte Goa, Malakka und Hormus?', 'Afonso de Albuquerque', ['Vasco da Gama', 'Magellan', 'Jorge Álvares']],
              ['Wie lange war Macau portugiesisch?', 'Von 1557 bis 1999', ['Von 1513 bis 1580', 'Von 1543 bis 1961', 'Von 1500 bis 1822']],
              ['Was für ein Werk ist „Os Lusíadas“?', 'Ein Epos', ['Ein Roman', 'Ein Drama', 'Eine Chronik in Prosa']],
              ['Welches Haus endete mit Kardinal Heinrich?', 'Das Haus Avis', ['Das Haus Burgund', 'Das Haus Braganza', 'Das Haus Habsburg']],
              ['Wer war in Asien Missionar unter den Jesuiten?', 'Franz Xaver', ['Albuquerque', 'Camões', 'Magellan']],
            ],
          },
        },
      ],
    },
  ],
};
