import { CatalogWord } from './vocab-catalog';

// ─── A1 → A2 starter path ───────────────────────────────────────────────────────
// A gentle, ordered on-ramp for complete beginners (A1 profiles). The Vocabulary "Learn"
// tab walks this array in order, so the ORDER here is the teaching order: start with
// greetings, courtesy, question words, pronouns and numbers — the things the main
// VOCAB_CATALOG lacks and that a true beginner needs first — then move through the
// most concrete everyday themes (family, food, house, city, travel…) before the
// lighter abstract words. German (`de`) side is the learner's L1.
//
// 700+ words, deduped at the bottom so an accidental repeat never produces a double
// flashcard. After the starter, app/vokabeln/page.tsx flows beginners into the rest
// of the full catalog, so they never run out.

const RAW: CatalogWord[] = [
  // ── Begrüßung & Höflichkeit ────────────────────────────────────────────────
  { de: 'hallo', es: 'hola', topic: 'begruessung' },
  { de: 'guten Morgen', es: 'buenos días', topic: 'begruessung' },
  { de: 'guten Tag / guten Nachmittag', es: 'buenas tardes', topic: 'begruessung' },
  { de: 'gute Nacht', es: 'buenas noches', topic: 'begruessung' },
  { de: 'tschüss', es: 'adiós', topic: 'begruessung' },
  { de: 'bis später', es: 'hasta luego', topic: 'begruessung' },
  { de: 'bis morgen', es: 'hasta mañana', topic: 'begruessung' },
  { de: 'willkommen', es: 'bienvenido', topic: 'begruessung' },
  { de: 'ja', es: 'sí', topic: 'begruessung' },
  { de: 'nein', es: 'no', topic: 'begruessung' },
  { de: 'vielleicht', es: 'quizás', topic: 'begruessung' },
  { de: 'bitte', es: 'por favor', topic: 'begruessung' },
  { de: 'danke', es: 'gracias', topic: 'begruessung' },
  { de: 'vielen Dank', es: 'muchas gracias', topic: 'begruessung' },
  { de: 'gern geschehen', es: 'de nada', topic: 'begruessung' },
  { de: 'entschuldigung', es: 'perdón', topic: 'begruessung' },
  { de: 'es tut mir leid', es: 'lo siento', topic: 'begruessung' },
  { de: 'Verzeihung (Aufmerksamkeit)', es: 'disculpe', topic: 'begruessung' },
  { de: 'wie geht es dir?', es: '¿cómo estás?', topic: 'begruessung' },
  { de: 'gut', es: 'bien', topic: 'begruessung' },
  { de: 'schlecht', es: 'mal', topic: 'begruessung' },
  { de: 'so lala', es: 'más o menos', topic: 'begruessung' },
  { de: 'sehr erfreut', es: 'mucho gusto', topic: 'begruessung' },
  { de: 'wie heißt du?', es: '¿cómo te llamas?', topic: 'begruessung' },
  { de: 'ich heiße …', es: 'me llamo', topic: 'begruessung' },
  { de: 'ich verstehe nicht', es: 'no entiendo', topic: 'begruessung' },
  { de: 'sprichst du Deutsch?', es: '¿hablas alemán?', topic: 'begruessung' },
  { de: 'Prost!', es: '¡salud!', topic: 'begruessung' },
  { de: 'herzlichen Glückwunsch', es: 'felicidades', topic: 'begruessung' },

  // ── Fragewörter ─────────────────────────────────────────────────────────────
  { de: 'was', es: 'qué', topic: 'grundwoerter' },
  { de: 'wer', es: 'quién', topic: 'grundwoerter' },
  { de: 'wo', es: 'dónde', topic: 'grundwoerter' },
  { de: 'wohin', es: 'adónde', topic: 'grundwoerter' },
  { de: 'wann', es: 'cuándo', topic: 'grundwoerter' },
  { de: 'wie', es: 'cómo', topic: 'grundwoerter' },
  { de: 'warum', es: 'por qué', topic: 'grundwoerter' },
  { de: 'wie viel', es: 'cuánto', topic: 'grundwoerter' },
  { de: 'welcher / welche', es: 'cuál', topic: 'grundwoerter' },

  // ── Personalpronomen & Possessiv ───────────────────────────────────────────────
  { de: 'ich', es: 'yo', topic: 'grundwoerter' },
  { de: 'du', es: 'tú', topic: 'grundwoerter' },
  { de: 'er', es: 'él', topic: 'grundwoerter' },
  { de: 'sie (Einzahl)', es: 'ella', topic: 'grundwoerter' },
  { de: 'Sie (höflich)', es: 'usted', topic: 'grundwoerter' },
  { de: 'wir', es: 'nosotros', topic: 'grundwoerter' },
  { de: 'ihr', es: 'vosotros', topic: 'grundwoerter' },
  { de: 'sie (Mehrzahl)', es: 'ellos', topic: 'grundwoerter' },
  { de: 'mein', es: 'mi', topic: 'grundwoerter' },
  { de: 'dein', es: 'tu', topic: 'grundwoerter' },
  { de: 'sein / ihr', es: 'su', topic: 'grundwoerter' },
  { de: 'unser', es: 'nuestro', topic: 'grundwoerter' },

  // ── Zahlen 0–20 ──────────────────────────────────────────────────────────────
  { de: 'null', es: 'cero', topic: 'zahlen' },
  { de: 'eins', es: 'uno', topic: 'zahlen' },
  { de: 'zwei', es: 'dos', topic: 'zahlen' },
  { de: 'drei', es: 'tres', topic: 'zahlen' },
  { de: 'vier', es: 'cuatro', topic: 'zahlen' },
  { de: 'fünf', es: 'cinco', topic: 'zahlen' },
  { de: 'sechs', es: 'seis', topic: 'zahlen' },
  { de: 'sieben', es: 'siete', topic: 'zahlen' },
  { de: 'acht', es: 'ocho', topic: 'zahlen' },
  { de: 'neun', es: 'nueve', topic: 'zahlen' },
  { de: 'zehn', es: 'diez', topic: 'zahlen' },
  { de: 'elf', es: 'once', topic: 'zahlen' },
  { de: 'zwölf', es: 'doce', topic: 'zahlen' },
  { de: 'dreizehn', es: 'trece', topic: 'zahlen' },
  { de: 'vierzehn', es: 'catorce', topic: 'zahlen' },
  { de: 'fünfzehn', es: 'quince', topic: 'zahlen' },
  { de: 'sechzehn', es: 'dieciséis', topic: 'zahlen' },
  { de: 'siebzehn', es: 'diecisiete', topic: 'zahlen' },
  { de: 'achtzehn', es: 'dieciocho', topic: 'zahlen' },
  { de: 'neunzehn', es: 'diecinueve', topic: 'zahlen' },
  { de: 'zwanzig', es: 'veinte', topic: 'zahlen' },
  // ── Zahlen 30–100 & Ordnungszahlen ─────────────────────────────────────────────
  { de: 'einundzwanzig', es: 'veintiuno', topic: 'zahlen' },
  { de: 'dreißig', es: 'treinta', topic: 'zahlen' },
  { de: 'vierzig', es: 'cuarenta', topic: 'zahlen' },
  { de: 'fünfzig', es: 'cincuenta', topic: 'zahlen' },
  { de: 'sechzig', es: 'sesenta', topic: 'zahlen' },
  { de: 'siebzig', es: 'setenta', topic: 'zahlen' },
  { de: 'achtzig', es: 'ochenta', topic: 'zahlen' },
  { de: 'neunzig', es: 'noventa', topic: 'zahlen' },
  { de: 'hundert', es: 'cien', topic: 'zahlen' },
  { de: 'tausend', es: 'mil', topic: 'zahlen' },
  { de: 'erster', es: 'primero', topic: 'zahlen' },
  { de: 'zweiter', es: 'segundo', topic: 'zahlen' },
  { de: 'dritter', es: 'tercero', topic: 'zahlen' },
  { de: 'letzter', es: 'último', topic: 'zahlen' },
  { de: 'die Hälfte', es: 'la mitad', topic: 'zahlen' },
  { de: 'das Doppelte', es: 'el doble', topic: 'zahlen' },

  // ── Zeit, Tage, Monate, Jahreszeiten ────────────────────────────────────────────
  { de: 'Montag', es: 'el lunes', topic: 'zeit' },
  { de: 'Dienstag', es: 'el martes', topic: 'zeit' },
  { de: 'Mittwoch', es: 'el miércoles', topic: 'zeit' },
  { de: 'Donnerstag', es: 'el jueves', topic: 'zeit' },
  { de: 'Freitag', es: 'el viernes', topic: 'zeit' },
  { de: 'Samstag', es: 'el sábado', topic: 'zeit' },
  { de: 'Sonntag', es: 'el domingo', topic: 'zeit' },
  { de: 'Januar', es: 'enero', topic: 'zeit' },
  { de: 'Februar', es: 'febrero', topic: 'zeit' },
  { de: 'März', es: 'marzo', topic: 'zeit' },
  { de: 'April', es: 'abril', topic: 'zeit' },
  { de: 'Mai', es: 'mayo', topic: 'zeit' },
  { de: 'Juni', es: 'junio', topic: 'zeit' },
  { de: 'Juli', es: 'julio', topic: 'zeit' },
  { de: 'August', es: 'agosto', topic: 'zeit' },
  { de: 'September', es: 'septiembre', topic: 'zeit' },
  { de: 'Oktober', es: 'octubre', topic: 'zeit' },
  { de: 'November', es: 'noviembre', topic: 'zeit' },
  { de: 'Dezember', es: 'diciembre', topic: 'zeit' },
  { de: 'der Frühling', es: 'la primavera', topic: 'zeit' },
  { de: 'der Sommer', es: 'el verano', topic: 'zeit' },
  { de: 'der Herbst', es: 'el otoño', topic: 'zeit' },
  { de: 'der Winter', es: 'el invierno', topic: 'zeit' },
  { de: 'heute', es: 'hoy', topic: 'zeit' },
  { de: 'morgen', es: 'mañana', topic: 'zeit' },
  { de: 'gestern', es: 'ayer', topic: 'zeit' },
  { de: 'jetzt', es: 'ahora', topic: 'zeit' },
  { de: 'später', es: 'más tarde', topic: 'zeit' },
  { de: 'früher / vorher', es: 'antes', topic: 'zeit' },
  { de: 'immer', es: 'siempre', topic: 'zeit' },
  { de: 'nie / niemals', es: 'nunca', topic: 'zeit' },
  { de: 'manchmal', es: 'a veces', topic: 'zeit' },
  { de: 'oft', es: 'a menudo', topic: 'zeit' },
  { de: 'bald', es: 'pronto', topic: 'zeit' },
  { de: 'schon / bereits', es: 'ya', topic: 'zeit' },
  { de: 'noch', es: 'todavía', topic: 'zeit' },
  { de: 'die Sekunde', es: 'el segundo', topic: 'zeit' },
  { de: 'die Minute', es: 'el minuto', topic: 'zeit' },
  { de: 'die Stunde', es: 'la hora', topic: 'zeit' },
  { de: 'der Tag', es: 'el día', topic: 'zeit' },
  { de: 'die Woche', es: 'la semana', topic: 'zeit' },
  { de: 'der Monat', es: 'el mes', topic: 'zeit' },
  { de: 'das Jahr', es: 'el año', topic: 'zeit' },
  { de: 'der Morgen', es: 'la mañana', topic: 'zeit' },
  { de: 'der Nachmittag', es: 'la tarde', topic: 'zeit' },
  { de: 'die Nacht', es: 'la noche', topic: 'zeit' },
  { de: 'das Wochenende', es: 'el fin de semana', topic: 'zeit' },

  // ── Farben ───────────────────────────────────────────────────────────────────
  { de: 'rot', es: 'rojo', topic: 'farben' },
  { de: 'blau', es: 'azul', topic: 'farben' },
  { de: 'grün', es: 'verde', topic: 'farben' },
  { de: 'gelb', es: 'amarillo', topic: 'farben' },
  { de: 'schwarz', es: 'negro', topic: 'farben' },
  { de: 'weiß', es: 'blanco', topic: 'farben' },
  { de: 'grau', es: 'gris', topic: 'farben' },
  { de: 'orange', es: 'naranja', topic: 'farben' },
  { de: 'lila / violett', es: 'morado', topic: 'farben' },
  { de: 'rosa', es: 'rosa', topic: 'farben' },
  { de: 'braun', es: 'marrón', topic: 'farben' },

  // ── Familie & Personen ─────────────────────────────────────────────────────────
  { de: 'die Mutter', es: 'la madre', topic: 'familie' },
  { de: 'der Vater', es: 'el padre', topic: 'familie' },
  { de: 'die Eltern', es: 'los padres', topic: 'familie' },
  { de: 'die Tochter', es: 'la hija', topic: 'familie' },
  { de: 'der Sohn', es: 'el hijo', topic: 'familie' },
  { de: 'die Kinder', es: 'los hijos', topic: 'familie' },
  { de: 'die Schwester', es: 'la hermana', topic: 'familie' },
  { de: 'der Bruder', es: 'el hermano', topic: 'familie' },
  { de: 'die Großmutter', es: 'la abuela', topic: 'familie' },
  { de: 'der Großvater', es: 'el abuelo', topic: 'familie' },
  { de: 'die Tante', es: 'la tía', topic: 'familie' },
  { de: 'der Onkel', es: 'el tío', topic: 'familie' },
  { de: 'die Cousine', es: 'la prima', topic: 'familie' },
  { de: 'der Cousin', es: 'el primo', topic: 'familie' },
  { de: 'die Ehefrau', es: 'la esposa', topic: 'familie' },
  { de: 'der Ehemann', es: 'el marido', topic: 'familie' },
  { de: 'der Freund / die Freundin (Partner)', es: 'el novio / la novia', topic: 'familie' },
  { de: 'der Freund / die Freundin', es: 'el amigo / la amiga', topic: 'familie' },
  { de: 'der Nachbar', es: 'el vecino', topic: 'familie' },
  { de: 'der Kollege', es: 'el compañero', topic: 'familie' },
  { de: 'das Baby', es: 'el bebé', topic: 'familie' },
  { de: 'das Kind', es: 'el niño', topic: 'familie' },
  { de: 'die Frau', es: 'la mujer', topic: 'familie' },
  { de: 'der Mann', es: 'el hombre', topic: 'familie' },
  { de: 'die Person', es: 'la persona', topic: 'familie' },
  { de: 'die Leute', es: 'la gente', topic: 'familie' },
  { de: 'der Name', es: 'el nombre', topic: 'familie' },

  // ── Körper ─────────────────────────────────────────────────────────────────────
  { de: 'der Kopf', es: 'la cabeza', topic: 'koerper' },
  { de: 'das Haar', es: 'el pelo', topic: 'koerper' },
  { de: 'das Gesicht', es: 'la cara', topic: 'koerper' },
  { de: 'das Auge', es: 'el ojo', topic: 'koerper' },
  { de: 'die Nase', es: 'la nariz', topic: 'koerper' },
  { de: 'der Mund', es: 'la boca', topic: 'koerper' },
  { de: 'das Ohr', es: 'la oreja', topic: 'koerper' },
  { de: 'der Zahn', es: 'el diente', topic: 'koerper' },
  { de: 'der Hals', es: 'el cuello', topic: 'koerper' },
  { de: 'der Arm', es: 'el brazo', topic: 'koerper' },
  { de: 'die Hand', es: 'la mano', topic: 'koerper' },
  { de: 'der Finger', es: 'el dedo', topic: 'koerper' },
  { de: 'das Bein', es: 'la pierna', topic: 'koerper' },
  { de: 'der Fuß', es: 'el pie', topic: 'koerper' },
  { de: 'der Bauch', es: 'el estómago', topic: 'koerper' },
  { de: 'der Rücken', es: 'la espalda', topic: 'koerper' },
  { de: 'das Herz', es: 'el corazón', topic: 'koerper' },
  { de: 'die Haut', es: 'la piel', topic: 'koerper' },

  // ── Essen & Trinken ────────────────────────────────────────────────────────────
  { de: 'das Essen', es: 'la comida', topic: 'essen' },
  { de: 'das Frühstück', es: 'el desayuno', topic: 'essen' },
  { de: 'das Mittagessen', es: 'el almuerzo', topic: 'essen' },
  { de: 'das Abendessen', es: 'la cena', topic: 'essen' },
  { de: 'das Wasser', es: 'el agua', topic: 'essen' },
  { de: 'der Kaffee', es: 'el café', topic: 'essen' },
  { de: 'der Tee', es: 'el té', topic: 'essen' },
  { de: 'der Saft', es: 'el zumo', topic: 'essen' },
  { de: 'die Milch', es: 'la leche', topic: 'essen' },
  { de: 'das Bier', es: 'la cerveza', topic: 'essen' },
  { de: 'der Wein', es: 'el vino', topic: 'essen' },
  { de: 'das Brot', es: 'el pan', topic: 'essen' },
  { de: 'die Butter', es: 'la mantequilla', topic: 'essen' },
  { de: 'der Käse', es: 'el queso', topic: 'essen' },
  { de: 'das Ei', es: 'el huevo', topic: 'essen' },
  { de: 'das Fleisch', es: 'la carne', topic: 'essen' },
  { de: 'der Fisch', es: 'el pescado', topic: 'essen' },
  { de: 'das Hühnchen', es: 'el pollo', topic: 'essen' },
  { de: 'der Schinken', es: 'el jamón', topic: 'essen' },
  { de: 'das Gemüse', es: 'las verduras', topic: 'essen' },
  { de: 'die Kartoffel', es: 'la patata', topic: 'essen' },
  { de: 'die Tomate', es: 'el tomate', topic: 'essen' },
  { de: 'die Zwiebel', es: 'la cebolla', topic: 'essen' },
  { de: 'der Salat', es: 'la ensalada', topic: 'essen' },
  { de: 'der Reis', es: 'el arroz', topic: 'essen' },
  { de: 'die Nudeln', es: 'la pasta', topic: 'essen' },
  { de: 'das Obst', es: 'la fruta', topic: 'essen' },
  { de: 'der Apfel', es: 'la manzana', topic: 'essen' },
  { de: 'die Banane', es: 'el plátano', topic: 'essen' },
  { de: 'die Orange', es: 'la naranja', topic: 'essen' },
  { de: 'die Zitrone', es: 'el limón', topic: 'essen' },
  { de: 'der Zucker', es: 'el azúcar', topic: 'essen' },
  { de: 'das Salz', es: 'la sal', topic: 'essen' },
  { de: 'das Öl', es: 'el aceite', topic: 'essen' },
  { de: 'die Suppe', es: 'la sopa', topic: 'essen' },
  { de: 'der Kuchen', es: 'el pastel', topic: 'essen' },
  { de: 'das Eis', es: 'el helado', topic: 'essen' },
  { de: 'die Schokolade', es: 'el chocolate', topic: 'essen' },

  // ── Zuhause, Möbel & Küche ─────────────────────────────────────────────────────
  { de: 'das Haus', es: 'la casa', topic: 'essen' },
  { de: 'die Wohnung', es: 'el piso', topic: 'essen' },
  { de: 'das Zimmer', es: 'la habitación', topic: 'essen' },
  { de: 'die Küche', es: 'la cocina', topic: 'essen' },
  { de: 'das Badezimmer', es: 'el baño', topic: 'essen' },
  { de: 'das Wohnzimmer', es: 'el salón', topic: 'essen' },
  { de: 'das Schlafzimmer', es: 'el dormitorio', topic: 'essen' },
  { de: 'der Garten', es: 'el jardín', topic: 'essen' },
  { de: 'die Tür', es: 'la puerta', topic: 'essen' },
  { de: 'das Fenster', es: 'la ventana', topic: 'essen' },
  { de: 'die Wand', es: 'la pared', topic: 'essen' },
  { de: 'der Boden', es: 'el suelo', topic: 'essen' },
  { de: 'der Tisch', es: 'la mesa', topic: 'essen' },
  { de: 'der Stuhl', es: 'la silla', topic: 'essen' },
  { de: 'das Sofa', es: 'el sofá', topic: 'essen' },
  { de: 'das Bett', es: 'la cama', topic: 'essen' },
  { de: 'der Schrank', es: 'el armario', topic: 'essen' },
  { de: 'die Lampe', es: 'la lámpara', topic: 'essen' },
  { de: 'der Schlüssel', es: 'la llave', topic: 'essen' },
  { de: 'der Teller', es: 'el plato', topic: 'essen' },
  { de: 'das Glas', es: 'el vaso', topic: 'essen' },
  { de: 'die Tasse', es: 'la taza', topic: 'essen' },
  { de: 'die Flasche', es: 'la botella', topic: 'essen' },
  { de: 'das Messer', es: 'el cuchillo', topic: 'essen' },
  { de: 'die Gabel', es: 'el tenedor', topic: 'essen' },
  { de: 'der Löffel', es: 'la cuchara', topic: 'essen' },

  // ── Stadt & Orte ───────────────────────────────────────────────────────────────
  { de: 'die Stadt', es: 'la ciudad', topic: 'stadt' },
  { de: 'das Dorf', es: 'el pueblo', topic: 'stadt' },
  { de: 'das Land', es: 'el país', topic: 'stadt' },
  { de: 'die Straße', es: 'la calle', topic: 'stadt' },
  { de: 'der Platz', es: 'la plaza', topic: 'stadt' },
  { de: 'das Geschäft / der Laden', es: 'la tienda', topic: 'stadt' },
  { de: 'der Supermarkt', es: 'el supermercado', topic: 'stadt' },
  { de: 'der Markt', es: 'el mercado', topic: 'stadt' },
  { de: 'das Restaurant', es: 'el restaurante', topic: 'stadt' },
  { de: 'die Bar / das Café', es: 'el bar', topic: 'stadt' },
  { de: 'das Hotel', es: 'el hotel', topic: 'stadt' },
  { de: 'der Bahnhof', es: 'la estación de tren', topic: 'stadt' },
  { de: 'der Flughafen', es: 'el aeropuerto', topic: 'stadt' },
  { de: 'das Krankenhaus', es: 'el hospital', topic: 'stadt' },
  { de: 'die Apotheke', es: 'la farmacia', topic: 'stadt' },
  { de: 'die Bank', es: 'el banco', topic: 'stadt' },
  { de: 'die Schule', es: 'el colegio', topic: 'stadt' },
  { de: 'die Kirche', es: 'la iglesia', topic: 'stadt' },
  { de: 'das Museum', es: 'el museo', topic: 'stadt' },
  { de: 'der Park', es: 'el parque', topic: 'stadt' },
  { de: 'der Strand', es: 'la playa', topic: 'stadt' },
  { de: 'das Kino', es: 'el cine', topic: 'stadt' },

  // ── Reisen & Transport ──────────────────────────────────────────────────────────
  { de: 'die Reise', es: 'el viaje', topic: 'reisen' },
  { de: 'der Koffer', es: 'la maleta', topic: 'reisen' },
  { de: 'der Pass', es: 'el pasaporte', topic: 'reisen' },
  { de: 'das Ticket / die Fahrkarte', es: 'el billete', topic: 'reisen' },
  { de: 'die Reservierung', es: 'la reserva', topic: 'reisen' },
  { de: 'der Tourist', es: 'el turista', topic: 'reisen' },
  { de: 'das Auto', es: 'el coche', topic: 'reisen' },
  { de: 'der Bus', es: 'el autobús', topic: 'reisen' },
  { de: 'die U-Bahn', es: 'el metro', topic: 'reisen' },
  { de: 'das Taxi', es: 'el taxi', topic: 'reisen' },
  { de: 'das Flugzeug', es: 'el avión', topic: 'reisen' },
  { de: 'der Zug', es: 'el tren', topic: 'reisen' },
  { de: 'das Fahrrad', es: 'la bicicleta', topic: 'reisen' },
  { de: 'rechts', es: 'a la derecha', topic: 'reisen' },
  { de: 'links', es: 'a la izquierda', topic: 'reisen' },
  { de: 'geradeaus', es: 'todo recto', topic: 'reisen' },
  { de: 'nah', es: 'cerca', topic: 'reisen' },
  { de: 'weit', es: 'lejos', topic: 'reisen' },

  // ── Kleidung ─────────────────────────────────────────────────────────────────────
  { de: 'die Kleidung', es: 'la ropa', topic: 'kleidung' },
  { de: 'das Hemd', es: 'la camisa', topic: 'kleidung' },
  { de: 'die Hose', es: 'los pantalones', topic: 'kleidung' },
  { de: 'das Kleid', es: 'el vestido', topic: 'kleidung' },
  { de: 'der Rock', es: 'la falda', topic: 'kleidung' },
  { de: 'die Jacke', es: 'la chaqueta', topic: 'kleidung' },
  { de: 'der Schuh', es: 'el zapato', topic: 'kleidung' },
  { de: 'die Socke', es: 'el calcetín', topic: 'kleidung' },
  { de: 'der Hut', es: 'el sombrero', topic: 'kleidung' },
  { de: 'die Brille', es: 'las gafas', topic: 'kleidung' },

  // ── Grundverben (regelmäßig) ─────────────────────────────────────────────────────
  { de: 'sprechen', es: 'hablar', topic: 'verben' },
  { de: 'arbeiten', es: 'trabajar', topic: 'verben' },
  { de: 'studieren / lernen', es: 'estudiar', topic: 'verben' },
  { de: 'kaufen', es: 'comprar', topic: 'verben' },
  { de: 'bezahlen', es: 'pagar', topic: 'verben' },
  { de: 'anschauen', es: 'mirar', topic: 'verben' },
  { de: 'hören / zuhören', es: 'escuchar', topic: 'verben' },
  { de: 'fragen', es: 'preguntar', topic: 'verben' },
  { de: 'antworten', es: 'contestar', topic: 'verben' },
  { de: 'anrufen / nennen', es: 'llamar', topic: 'verben' },
  { de: 'warten', es: 'esperar', topic: 'verben' },
  { de: 'helfen', es: 'ayudar', topic: 'verben' },
  { de: 'brauchen', es: 'necesitar', topic: 'verben' },
  { de: 'tragen / bringen', es: 'llevar', topic: 'verben' },
  { de: 'tanzen', es: 'bailar', topic: 'verben' },
  { de: 'singen', es: 'cantar', topic: 'verben' },
  { de: 'kochen', es: 'cocinar', topic: 'verben' },
  { de: 'reisen', es: 'viajar', topic: 'verben' },
  { de: 'lieben', es: 'amar', topic: 'verben' },
  { de: 'nehmen / trinken', es: 'tomar', topic: 'verben' },
  { de: 'essen', es: 'comer', topic: 'verben' },
  { de: 'trinken', es: 'beber', topic: 'verben' },
  { de: 'lernen / erfahren', es: 'aprender', topic: 'verben' },
  { de: 'lesen', es: 'leer', topic: 'verben' },
  { de: 'laufen / rennen', es: 'correr', topic: 'verben' },
  { de: 'verstehen', es: 'comprender', topic: 'verben' },
  { de: 'leben / wohnen', es: 'vivir', topic: 'verben' },
  { de: 'schreiben', es: 'escribir', topic: 'verben' },
  { de: 'öffnen', es: 'abrir', topic: 'verben' },
  { de: 'empfangen / bekommen', es: 'recibir', topic: 'verben' },

  // ── Grundverben (unregelmäßig & häufig) ──────────────────────────────────────────
  { de: 'sein (Eigenschaft)', es: 'ser', topic: 'verben' },
  { de: 'sein (Zustand/Ort)', es: 'estar', topic: 'verben' },
  { de: 'haben', es: 'tener', topic: 'verben' },
  { de: 'es gibt', es: 'haber', topic: 'verben' },
  { de: 'machen / tun', es: 'hacer', topic: 'verben' },
  { de: 'gehen', es: 'ir', topic: 'verben' },
  { de: 'kommen', es: 'venir', topic: 'verben' },
  { de: 'sagen', es: 'decir', topic: 'verben' },
  { de: 'sehen', es: 'ver', topic: 'verben' },
  { de: 'geben', es: 'dar', topic: 'verben' },
  { de: 'wissen', es: 'saber', topic: 'verben' },
  { de: 'kennen', es: 'conocer', topic: 'verben' },
  { de: 'können', es: 'poder', topic: 'verben' },
  { de: 'wollen / lieben', es: 'querer', topic: 'verben' },
  { de: 'müssen / schulden', es: 'deber', topic: 'verben' },
  { de: 'denken', es: 'pensar', topic: 'verben' },
  { de: 'glauben', es: 'creer', topic: 'verben' },
  { de: 'finden', es: 'encontrar', topic: 'verben' },
  { de: 'schlafen', es: 'dormir', topic: 'verben' },
  { de: 'spielen', es: 'jugar', topic: 'verben' },
  { de: 'beginnen', es: 'empezar', topic: 'verben' },
  { de: 'beenden / aufhören', es: 'terminar', topic: 'verben' },
  { de: 'heißen', es: 'llamarse', topic: 'verben' },
  { de: 'sich setzen', es: 'sentarse', topic: 'verben' },
  { de: 'aufstehen', es: 'levantarse', topic: 'verben' },

  // ── Einfache Adjektive ────────────────────────────────────────────────────────────
  { de: 'groß', es: 'grande', topic: 'adjektive' },
  { de: 'klein', es: 'pequeño', topic: 'adjektive' },
  { de: 'lang', es: 'largo', topic: 'adjektive' },
  { de: 'kurz', es: 'corto', topic: 'adjektive' },
  { de: 'hoch / groß (Person)', es: 'alto', topic: 'adjektive' },
  { de: 'niedrig / klein (Person)', es: 'bajo', topic: 'adjektive' },
  { de: 'gut', es: 'bueno', topic: 'adjektive' },
  { de: 'schlecht', es: 'malo', topic: 'adjektive' },
  { de: 'schön', es: 'bonito', topic: 'adjektive' },
  { de: 'hässlich', es: 'feo', topic: 'adjektive' },
  { de: 'neu', es: 'nuevo', topic: 'adjektive' },
  { de: 'alt', es: 'viejo', topic: 'adjektive' },
  { de: 'jung', es: 'joven', topic: 'adjektive' },
  { de: 'schnell', es: 'rápido', topic: 'adjektive' },
  { de: 'langsam', es: 'lento', topic: 'adjektive' },
  { de: 'einfach', es: 'fácil', topic: 'adjektive' },
  { de: 'schwierig', es: 'difícil', topic: 'adjektive' },
  { de: 'teuer', es: 'caro', topic: 'adjektive' },
  { de: 'günstig / billig', es: 'barato', topic: 'adjektive' },
  { de: 'warm / heiß', es: 'caliente', topic: 'adjektive' },
  { de: 'kalt', es: 'frío', topic: 'adjektive' },
  { de: 'sauber', es: 'limpio', topic: 'adjektive' },
  { de: 'schmutzig', es: 'sucio', topic: 'adjektive' },
  { de: 'voll', es: 'lleno', topic: 'adjektive' },
  { de: 'leer', es: 'vacío', topic: 'adjektive' },
  { de: 'glücklich', es: 'feliz', topic: 'adjektive' },
  { de: 'traurig', es: 'triste', topic: 'adjektive' },
  { de: 'müde', es: 'cansado', topic: 'adjektive' },
  { de: 'krank', es: 'enfermo', topic: 'adjektive' },
  { de: 'wichtig', es: 'importante', topic: 'adjektive' },
  { de: 'gleich', es: 'igual', topic: 'adjektive' },
  { de: 'anders / verschieden', es: 'diferente', topic: 'adjektive' },
  { de: 'viel', es: 'mucho', topic: 'adjektive' },
  { de: 'wenig', es: 'poco', topic: 'adjektive' },
  { de: 'mehr', es: 'más', topic: 'adjektive' },
  { de: 'weniger', es: 'menos', topic: 'adjektive' },

  // ── Natur & Wetter ──────────────────────────────────────────────────────────────
  { de: 'die Natur', es: 'la naturaleza', topic: 'natur' },
  { de: 'der Baum', es: 'el árbol', topic: 'natur' },
  { de: 'die Blume', es: 'la flor', topic: 'natur' },
  { de: 'der Berg', es: 'la montaña', topic: 'natur' },
  { de: 'der Fluss', es: 'el río', topic: 'natur' },
  { de: 'das Meer', es: 'el mar', topic: 'natur' },
  { de: 'der Himmel', es: 'el cielo', topic: 'natur' },
  { de: 'die Sonne', es: 'el sol', topic: 'natur' },
  { de: 'der Mond', es: 'la luna', topic: 'natur' },
  { de: 'der Stern', es: 'la estrella', topic: 'natur' },
  { de: 'die Wolke', es: 'la nube', topic: 'natur' },
  { de: 'der Regen', es: 'la lluvia', topic: 'natur' },
  { de: 'der Schnee', es: 'la nieve', topic: 'natur' },
  { de: 'der Wind', es: 'el viento', topic: 'natur' },
  { de: 'das Feuer', es: 'el fuego', topic: 'natur' },
  { de: 'die Erde', es: 'la tierra', topic: 'natur' },

  // ── Tiere ─────────────────────────────────────────────────────────────────────────
  { de: 'das Tier', es: 'el animal', topic: 'tiere' },
  { de: 'der Hund', es: 'el perro', topic: 'tiere' },
  { de: 'die Katze', es: 'el gato', topic: 'tiere' },
  { de: 'das Pferd', es: 'el caballo', topic: 'tiere' },
  { de: 'der Vogel', es: 'el pájaro', topic: 'tiere' },
  { de: 'die Kuh', es: 'la vaca', topic: 'tiere' },
  { de: 'das Schwein', es: 'el cerdo', topic: 'tiere' },
  { de: 'der Fisch (Tier)', es: 'el pez', topic: 'tiere' },

  // ── Schule & Bildung ──────────────────────────────────────────────────────────────
  { de: 'das Buch', es: 'el libro', topic: 'schule' },
  { de: 'das Heft', es: 'el cuaderno', topic: 'schule' },
  { de: 'der Stift', es: 'el bolígrafo', topic: 'schule' },
  { de: 'das Papier', es: 'el papel', topic: 'schule' },
  { de: 'der Schüler', es: 'el alumno', topic: 'schule' },
  { de: 'der Lehrer', es: 'el profesor', topic: 'schule' },
  { de: 'die Klasse / der Unterricht', es: 'la clase', topic: 'schule' },
  { de: 'die Prüfung', es: 'el examen', topic: 'schule' },
  { de: 'die Hausaufgabe', es: 'la tarea', topic: 'schule' },
  { de: 'die Sprache', es: 'el idioma', topic: 'schule' },
  { de: 'das Wort', es: 'la palabra', topic: 'schule' },
  { de: 'der Satz', es: 'la frase', topic: 'schule' },
  { de: 'die Frage', es: 'la pregunta', topic: 'schule' },
  { de: 'die Antwort', es: 'la respuesta', topic: 'schule' },

  // ── Arbeit & Berufe ───────────────────────────────────────────────────────────────
  { de: 'die Arbeit', es: 'el trabajo', topic: 'arbeit' },
  { de: 'der Beruf', es: 'la profesión', topic: 'arbeit' },
  { de: 'das Büro', es: 'la oficina', topic: 'arbeit' },
  { de: 'der Chef / die Chefin', es: 'el jefe', topic: 'arbeit' },
  { de: 'die Firma', es: 'la empresa', topic: 'arbeit' },
  { de: 'der Arzt / die Ärztin', es: 'el médico', topic: 'arbeit' },
  { de: 'der Lehrer (Beruf)', es: 'el maestro', topic: 'arbeit' },
  { de: 'der Koch', es: 'el cocinero', topic: 'arbeit' },
  { de: 'der Kellner', es: 'el camarero', topic: 'arbeit' },
  { de: 'der Verkäufer', es: 'el vendedor', topic: 'arbeit' },
  { de: 'der Urlaub / die Ferien', es: 'las vacaciones', topic: 'arbeit' },
  { de: 'der Termin', es: 'la cita', topic: 'arbeit' },

  // ── Gesundheit ─────────────────────────────────────────────────────────────────────
  { de: 'die Gesundheit', es: 'la salud', topic: 'gesundheit' },
  { de: 'der Schmerz', es: 'el dolor', topic: 'gesundheit' },
  { de: 'das Fieber', es: 'la fiebre', topic: 'gesundheit' },
  { de: 'die Krankheit', es: 'la enfermedad', topic: 'gesundheit' },
  { de: 'das Medikament', es: 'el medicamento', topic: 'gesundheit' },
  { de: 'die Tablette', es: 'la pastilla', topic: 'gesundheit' },
  { de: 'der Notfall', es: 'la emergencia', topic: 'gesundheit' },
  { de: 'der Schlaf', es: 'el sueño', topic: 'gesundheit' },

  // ── Technologie ─────────────────────────────────────────────────────────────────────
  { de: 'der Computer', es: 'el ordenador', topic: 'technik' },
  { de: 'das Handy', es: 'el móvil', topic: 'technik' },
  { de: 'das Internet', es: 'internet', topic: 'technik' },
  { de: 'die E-Mail', es: 'el correo electrónico', topic: 'technik' },
  { de: 'das Foto', es: 'la foto', topic: 'technik' },
  { de: 'das Video', es: 'el vídeo', topic: 'technik' },
  { de: 'das Passwort', es: 'la contraseña', topic: 'technik' },
  { de: 'der Bildschirm', es: 'la pantalla', topic: 'technik' },

  // ── Geld & Einkaufen ────────────────────────────────────────────────────────────────
  { de: 'das Geld', es: 'el dinero', topic: 'geld' },
  { de: 'der Preis', es: 'el precio', topic: 'geld' },
  { de: 'die Rechnung', es: 'la cuenta', topic: 'geld' },
  { de: 'die Kreditkarte', es: 'la tarjeta de crédito', topic: 'geld' },
  { de: 'das Bargeld', es: 'el efectivo', topic: 'geld' },
  { de: 'das Angebot', es: 'la oferta', topic: 'geld' },
  { de: 'der Rabatt', es: 'el descuento', topic: 'geld' },

  // ── Emotionen & Charakter ────────────────────────────────────────────────────────────
  { de: 'die Liebe', es: 'el amor', topic: 'gefuehle' },
  { de: 'die Freude', es: 'la alegría', topic: 'gefuehle' },
  { de: 'die Angst', es: 'el miedo', topic: 'gefuehle' },
  { de: 'die Hoffnung', es: 'la esperanza', topic: 'gefuehle' },
  { de: 'freundlich', es: 'amable', topic: 'gefuehle' },
  { de: 'nett / sympathisch', es: 'simpático', topic: 'gefuehle' },
  { de: 'höflich', es: 'educado', topic: 'gefuehle' },
  { de: 'ehrlich', es: 'honesto', topic: 'gefuehle' },
  { de: 'mutig', es: 'valiente', topic: 'gefuehle' },
  { de: 'schüchtern', es: 'tímido', topic: 'gefuehle' },
  { de: 'geduldig', es: 'paciente', topic: 'gefuehle' },
  { de: 'lustig / komisch', es: 'gracioso', topic: 'gefuehle' },
  { de: 'intelligent', es: 'inteligente', topic: 'gefuehle' },

  // ── Nützliche kleine Wörter (Adverbien, Präpositionen, Verbindungen) ──────────────────
  { de: 'und', es: 'y', topic: 'grundwoerter' },
  { de: 'oder', es: 'o', topic: 'grundwoerter' },
  { de: 'aber', es: 'pero', topic: 'grundwoerter' },
  { de: 'weil', es: 'porque', topic: 'grundwoerter' },
  { de: 'wenn / falls', es: 'si', topic: 'grundwoerter' },
  { de: 'auch', es: 'también', topic: 'grundwoerter' },
  { de: 'auch nicht', es: 'tampoco', topic: 'grundwoerter' },
  { de: 'sehr', es: 'muy', topic: 'grundwoerter' },
  { de: 'ein bisschen', es: 'un poco', topic: 'grundwoerter' },
  { de: 'gut / na gut', es: 'vale', topic: 'grundwoerter' },
  { de: 'natürlich / klar', es: 'claro', topic: 'grundwoerter' },
  { de: 'fast', es: 'casi', topic: 'grundwoerter' },
  { de: 'nur', es: 'solo', topic: 'grundwoerter' },
  { de: 'sogar', es: 'incluso', topic: 'grundwoerter' },
  { de: 'hier', es: 'aquí', topic: 'grundwoerter' },
  { de: 'dort', es: 'allí', topic: 'grundwoerter' },
  { de: 'oben', es: 'arriba', topic: 'grundwoerter' },
  { de: 'unten', es: 'abajo', topic: 'grundwoerter' },
  { de: 'drinnen', es: 'dentro', topic: 'grundwoerter' },
  { de: 'draußen', es: 'fuera', topic: 'grundwoerter' },
  { de: 'in / auf', es: 'en', topic: 'grundwoerter' },
  { de: 'von / aus', es: 'de', topic: 'grundwoerter' },
  { de: 'mit', es: 'con', topic: 'grundwoerter' },
  { de: 'ohne', es: 'sin', topic: 'grundwoerter' },
  { de: 'für', es: 'para', topic: 'grundwoerter' },
  { de: 'zwischen', es: 'entre', topic: 'grundwoerter' },
  { de: 'gegen', es: 'contra', topic: 'grundwoerter' },
  { de: 'unter', es: 'debajo de', topic: 'grundwoerter' },
  { de: 'über / auf', es: 'sobre', topic: 'grundwoerter' },
  { de: 'bis', es: 'hasta', topic: 'grundwoerter' },
  { de: 'während', es: 'durante', topic: 'grundwoerter' },
  { de: 'nach', es: 'después de', topic: 'grundwoerter' },
  { de: 'vor (zeitlich)', es: 'antes de', topic: 'grundwoerter' },
];

// Strip a leading article so "el día" and "día" are treated as the same word.
function key(es: string): string {
  return es
    .toLowerCase()
    .trim()
    .replace(/^(el|la|los|las|un|una|unos|unas)\s+/i, '')
    .trim();
}

// Dedupe by normalized Spanish so an accidental repeat never yields a double card.
const seen = new Set<string>();
export const STARTER_VOCAB: CatalogWord[] = RAW.filter(w => {
  const k = key(w.es);
  if (seen.has(k)) return false;
  seen.add(k);
  return true;
});
