import type { Epoch } from '../types';

export const E1: Epoch = {
  id: 'fruehzeit',
  name: 'Minoer, Mykener und Homer',
  period: '3000–700 v. Chr.',
  events: [
    {
      id: 'bronzezeit',
      title: 'Die ersten Hochkulturen Europas',
      date: '3000–700 v. Chr.',
      text: [
        'Auf Kreta entstand mit den Minoern die erste Hochkultur Europas, auf dem Festland folgten die kriegerischen Mykener. Nach ihrem Untergang kamen „Dunkle Jahrhunderte“, bis mit Alphabet, Homer und den Olympischen Spielen eine neue Blüte begann.',
      ],
      subtopics: [
        {
          id: 'minoer-mykener',
          title: 'Knossos, Mykene und Troja',
          date: '3000–1100 v. Chr.',
          text: [
            'Auf Kreta lebten ab etwa 3000 v. Chr. die „Minoer“, benannt nach dem sagenhaften König Minos. Ihr größter Palast in Knossos hatte über 1000 Räume, Wasserleitungen und farbenfrohe Wandmalereien mit Delfinen und jungen Menschen, die über Stiere springen. Das verwinkelte Gebäude könnte die Sage vom Labyrinth inspiriert haben, in dem der Minotaurus, halb Mensch, halb Stier, hauste, bis Theseus ihn mit Hilfe von Ariadnes Faden tötete.',
            'Die Minoer schrieben in einer Schrift namens „Linear A“, die bis heute nicht entziffert ist. Der Archäologe Arthur Evans grub Knossos ab 1900 aus. Um 1600 v. Chr. explodierte der Vulkan auf der Insel Thera (Santorin) in einem der gewaltigsten Ausbrüche der Menschheitsgeschichte; die Siedlung Akrotiri wurde unter Asche begraben. Manche sehen darin den Ursprung der Atlantis-Sage.',
            'Auf dem Festland entstand ab etwa 1600 v. Chr. die mykenische Kultur, benannt nach der Burg Mykene. Ihre Burgen hatten so riesige Mauern, dass man glaubte, einäugige Riesen, die Zyklopen, hätten sie gebaut. Durch das „Löwentor“ betrat man Mykene. Die Mykener eroberten um 1450 v. Chr. Kreta und schrieben in „Linear B“, einer frühen Form des Griechischen, die der Engländer Michael Ventris 1952 entzifferte.',
            'Der Kaufmann Heinrich Schliemann, der Homers Epen für wahr hielt, grub ab 1870 in Kleinasien (heute Türkei) den Hügel Hisarlık aus und fand die Stadt Troja. 1876 entdeckte er in Mykene Gräber mit Goldschätzen, darunter eine Goldmaske, die er für die des Königs Agamemnon hielt – tatsächlich ist sie Jahrhunderte älter. Der Trojanische Krieg, den Homer schildert, könnte auf Kämpfe um 1200 v. Chr. zurückgehen.',
            'Um 1200 v. Chr. brachen die mykenischen Paläste zusammen, ebenso andere Reiche im östlichen Mittelmeer. Ursachen könnten Erdbeben, Dürren, Aufstände und Angriffe der rätselhaften „Seevölker“ gewesen sein. Danach begannen die „Dunklen Jahrhunderte“: Die Schrift geriet in Vergessenheit, Städte schrumpften, der Handel brach ein.',
          ],
          quiz: {
            leicht: [
              ['Auf welcher Insel lebten die Minoer?', 'Auf Kreta', ['Auf Rhodos', 'Auf Zypern', 'Auf Sizilien']],
              ['Nach welchem König sind die Minoer benannt?', 'Minos', ['Agamemnon', 'Theseus', 'Priamos']],
              ['Wie heißt der größte Palast der Minoer?', 'Knossos', ['Mykene', 'Troja', 'Akrotiri']],
              ['Wie viele Räume hatte Knossos etwa?', 'Über 1000', ['Rund 10', 'Rund 100', 'Über 10.000']],
              ['Welche Tiere zeigen die Wandmalereien?', 'Delfine und Stiere', ['Löwen und Elefanten', 'Pferde und Hunde', 'Adler und Bären']],
              ['Wer hauste der Sage nach im Labyrinth?', 'Der Minotaurus', ['Medusa', 'Zerberus', 'Pegasus']],
              ['Wer tötete den Minotaurus?', 'Theseus', ['Herakles', 'Odysseus', 'Achilles']],
              ['Was half Theseus aus dem Labyrinth?', 'Ariadnes Faden', ['Ein Schwert', 'Eine Fackel', 'Ein Hund']],
              ['Wie heißt die Schrift der Minoer?', 'Linear A', ['Linear B', 'Hieroglyphen', 'Keilschrift']],
              ['Ist Linear A entziffert?', 'Nein', ['Ja, seit 1952', 'Ja, seit 1900', 'Teilweise von Evans']],
              ['Wer grub Knossos aus?', 'Arthur Evans', ['Heinrich Schliemann', 'Howard Carter', 'Michael Ventris']],
              ['Welcher Vulkan explodierte um 1600 v. Chr.?', 'Thera (Santorin)', ['Vesuv', 'Ätna', 'Stromboli']],
              ['Welche Sage sehen manche im Ausbruch von Thera?', 'Atlantis', ['Troja', 'Odyssee', 'Minotaurus']],
              ['Nach welcher Burg ist die mykenische Kultur benannt?', 'Mykene', ['Knossos', 'Troja', 'Athen']],
              ['Durch welches Tor betrat man Mykene?', 'Das Löwentor', ['Das Brandenburger Tor', 'Das Ischtar-Tor', 'Das Goldene Tor']],
              ['Wer soll laut Glauben die riesigen Mauern gebaut haben?', 'Die Zyklopen', ['Die Titanen', 'Die Römer', 'Die Ägypter']],
              ['Wie heißt die Schrift der Mykener?', 'Linear B', ['Linear A', 'Alphabet', 'Hieroglyphen']],
              ['Wer fand Troja?', 'Heinrich Schliemann', ['Arthur Evans', 'Michael Ventris', 'Homer']],
              ['Wessen Maske glaubte Schliemann gefunden zu haben?', 'Agamemnons', ['Priamos’', 'Minos’', 'Odysseus’']],
              ['Wie nennt man die Zeit nach 1200 v. Chr.?', 'Dunkle Jahrhunderte', ['Goldenes Zeitalter', 'Klassik', 'Hellenismus']],
            ],
            mittel: [
              ['Ab wann lebten die Minoer auf Kreta?', 'Ab etwa 3000 v. Chr.', ['Ab 1200 v. Chr.', 'Ab 776 v. Chr.', 'Ab 500 v. Chr.']],
              ['Was hatte der Palast von Knossos?', 'Wasserleitungen und Wandmalereien', ['Elektrisches Licht', 'Eine Kuppel aus Glas', 'Keine Fenster']],
              ['Was zeigen manche Malereien in Knossos?', 'Junge Menschen, die über Stiere springen', ['Schlachten', 'Schneeberge', 'Götter in Wolken']],
              ['Was könnte Knossos inspiriert haben?', 'Die Sage vom Labyrinth', ['Die Odyssee', 'Die Olympischen Spiele', 'Das Alphabet']],
              ['Was war der Minotaurus?', 'Halb Mensch, halb Stier', ['Halb Pferd, halb Mensch', 'Ein Riese mit einem Auge', 'Eine Schlange']],
              ['Ab wann grub Evans Knossos aus?', 'Ab 1900', ['Ab 1870', 'Ab 1952', 'Ab 1800']],
              ['Welche Siedlung wurde auf Thera unter Asche begraben?', 'Akrotiri', ['Knossos', 'Mykene', 'Pompeji']],
              ['Ab wann entstand die mykenische Kultur?', 'Ab etwa 1600 v. Chr.', ['Ab 3000 v. Chr.', 'Ab 800 v. Chr.', 'Ab 1200 v. Chr.']],
              ['Wann eroberten die Mykener Kreta?', 'Um 1450 v. Chr.', ['Um 3000 v. Chr.', 'Um 1200 v. Chr.', 'Um 776 v. Chr.']],
              ['Was ist Linear B?', 'Eine frühe Form des Griechischen', ['Eine ägyptische Schrift', 'Ein Zahlensystem', 'Eine unentzifferte Sprache']],
              ['Wer entzifferte Linear B?', 'Michael Ventris', ['Arthur Evans', 'Heinrich Schliemann', 'Champollion']],
              ['Wann wurde Linear B entziffert?', '1952', ['1900', '1870', '1876']],
              ['Woran glaubte Schliemann?', 'Dass Homers Epen wahr seien', ['An Atlantis', 'An die Zyklopen', 'An Minos']],
              ['Welchen Hügel grub Schliemann aus?', 'Hisarlık', ['Akropolis', 'Olymp', 'Knossos']],
              ['Ab wann grub Schliemann in Troja?', 'Ab 1870', ['Ab 1900', 'Ab 1952', 'Ab 1800']],
              ['Wann fand Schliemann die Gräber in Mykene?', '1876', ['1870', '1900', '1952']],
              ['Wie alt ist die Goldmaske wirklich?', 'Jahrhunderte älter als Agamemnon', ['Aus der Römerzeit', 'Eine Fälschung von 1876', 'Genau aus Agamemnons Zeit']],
              ['Auf welche Zeit könnte der Trojanische Krieg zurückgehen?', 'Um 1200 v. Chr.', ['Um 3000 v. Chr.', 'Um 500 v. Chr.', 'Um 776 v. Chr.']],
              ['Welche Völker griffen um 1200 v. Chr. an?', 'Die rätselhaften Seevölker', ['Die Römer', 'Die Perser', 'Die Kelten']],
              ['Was geriet in den Dunklen Jahrhunderten in Vergessenheit?', 'Die Schrift', ['Der Ackerbau', 'Die Sprache', 'Das Feuer']],
            ],
            schwer: [
              ['Warum ist die minoische Kultur besonders?', 'Sie gilt als erste Hochkultur Europas', ['Sie war die letzte', 'Sie war römisch', 'Sie hatte keine Paläste']],
              ['Was waren mögliche Ursachen des Zusammenbruchs um 1200 v. Chr.?', 'Erdbeben, Dürren, Aufstände, Seevölker', ['Die Römer', 'Die Pest von Athen', 'Alexander der Große']],
              ['Was bewies Ventris’ Entzifferung?', 'Die Mykener sprachen Griechisch', ['Die Minoer sprachen Latein', 'Troja war ägyptisch', 'Nichts']],
              ['Was ist am Namen „zyklopische Mauern“ interessant?', 'Man hielt sie für ein Werk einäugiger Riesen', ['Sie sind rund', 'Sie wurden von Zyklopen in Rom gebaut', 'Sie sind aus Gold']],
              ['Was zeigt der Irrtum um Agamemnons Maske?', 'Schliemann deutete Funde vorschnell nach Homer', ['Schliemann fälschte die Maske', 'Agamemnon lebte früher', 'Nichts']],
              ['Wo liegt Troja heute?', 'In der Türkei (Kleinasien)', ['In Griechenland', 'Auf Kreta', 'In Italien']],
              ['Welche Insel heißt heute Santorin?', 'Thera', ['Kreta', 'Rhodos', 'Delos']],
              ['Wer übernahm Kreta von den Minoern?', 'Die Mykener', ['Die Römer', 'Die Perser', 'Die Ägypter']],
              ['Was folgte auf den mykenischen Zusammenbruch?', 'Schrumpfende Städte und Handelseinbruch', ['Ein Goldenes Zeitalter', 'Die Demokratie', 'Das Römische Reich']],
              ['Welcher Held besiegte das Ungeheuer von Knossos?', 'Theseus', ['Perseus', 'Jason', 'Herakles']],
              ['Was ist das Löwentor?', 'Der Haupteingang der Burg Mykene', ['Ein Tor in Knossos', 'Ein Stadttor Athens', 'Ein Tempel']],
              ['Welche Schrift entstand zuerst?', 'Linear A', ['Linear B', 'Das Alphabet', 'Alle gleichzeitig']],
              ['Woher kommt der Begriff Labyrinth in der Sage?', 'Aus dem Palast des Minos auf Kreta', ['Aus Athen', 'Aus Ägypten', 'Aus Troja']],
              ['Wer war Agamemnon laut Homer?', 'König von Mykene', ['König von Troja', 'König von Kreta', 'Gott des Krieges']],
              ['Was beweist Akrotiri?', 'Eine reiche Siedlung unter Vulkanasche', ['Ein römisches Lager', 'Einen Tempel des Zeus', 'Nichts']],
              ['Was war der Beruf Schliemanns ursprünglich?', 'Kaufmann', ['Archäologe von Beruf', 'Priester', 'Soldat']],
              ['Welcher Forscher ist mit Kreta verbunden?', 'Arthur Evans', ['Schliemann', 'Ventris', 'Carter']],
              ['Was ist an Linear A bis heute rätselhaft?', 'Sie ist nicht entziffert', ['Sie ist aus Gold', 'Sie ist zu kurz', 'Nichts']],
              ['Welche Zeit nennt man Bronzezeit in Griechenland?', 'Minoer und Mykener (bis 1200 v. Chr.)', ['Die Klassik', 'Den Hellenismus', 'Die Römerzeit']],
              ['Warum könnte Thera mit Atlantis verbunden sein?', 'Eine reiche Inselkultur ging in einer Katastrophe unter', ['Weil dort Platon lebte', 'Weil sie versank ganz', 'Wegen einer Flut in Ägypten']],
            ],
          },
        },
        {
          id: 'homer-olympia',
          title: 'Alphabet, Homer und Olympia',
          date: '1100–700 v. Chr.',
          text: [
            'Nach den Dunklen Jahrhunderten übernahmen die Griechen im 8. Jahrhundert v. Chr. von den Phönikern deren Schrift und fügten Zeichen für Vokale hinzu. So entstand das griechische Alphabet, benannt nach den ersten Buchstaben Alpha und Beta. Aus ihm entwickelten sich später das lateinische und das kyrillische Alphabet.',
            'Um 700 v. Chr. entstanden die Epen, die man dem Dichter Homer zuschreibt: Die „Ilias“ erzählt vom Zorn des Achilles im Trojanischen Krieg, in dem die Griechen Troja zehn Jahre belagerten, weil der trojanische Prinz Paris die schöne Helena, Frau des Königs Menelaos, entführt hatte. Die „Odyssee“ schildert die zehnjährige Irrfahrt des listenreichen Odysseus, der mit dem hölzernen Pferd Troja eroberte – bis heute ein Bild für eine List, um einzudringen –, nach Hause zu seiner treuen Frau Penelope.',
            'Die Griechen verehrten viele Götter, die menschliche Gefühle hatten und auf dem Berg Olymp wohnten: Zeus, der Göttervater mit dem Blitz, seine Frau Hera, Poseidon, Gott des Meeres, Athene, Göttin der Weisheit, Apollon, Aphrodite und andere. Im Orakel von Delphi sprach eine Priesterin, die Pythia, rätselhafte Weissagungen im Namen Apollons.',
            '776 v. Chr. fanden der Überlieferung nach die ersten Olympischen Spiele in Olympia zu Ehren des Zeus statt. Zuerst gab es nur einen Wettlauf über ein „Stadion“ (rund 192 Meter; daher der Name für Sportstätten), später auch Ringen, Faustkampf, Wagenrennen und Fünfkampf. Während der Spiele herrschte ein heiliger Waffenstillstand. Teilnehmen durften nur freie griechische Männer, die nackt antraten; Sieger erhielten einen Kranz aus Olivenzweigen. Die Griechen zählten die Jahre nach Olympiaden.',
            'Die Griechen lebten in vielen unabhängigen Stadtstaaten („Poleis“), getrennt durch Gebirge und Meer. Was sie verband, waren Sprache, Götter, Homer und die Spiele; wer kein Griechisch sprach, galt als „Barbar“ (weil seine Sprache wie „bar-bar“ klang). Ab dem 8. Jahrhundert gründeten sie Kolonien rund ums Mittelmeer und Schwarze Meer, etwa Syrakus auf Sizilien, Neapel und Massalia (Marseille).',
          ],
          quiz: {
            leicht: [
              ['Von welchem Volk übernahmen die Griechen die Schrift?', 'Von den Phönikern', ['Von den Ägyptern', 'Von den Römern', 'Von den Persern']],
              ['Was fügten die Griechen hinzu?', 'Zeichen für Vokale', ['Zahlen', 'Bildzeichen', 'Nichts']],
              ['Woher kommt das Wort „Alphabet“?', 'Von Alpha und Beta', ['Von einem Gott', 'Von einer Stadt', 'Von Homer']],
              ['Welche Alphabete entwickelten sich aus dem griechischen?', 'Das lateinische und das kyrillische', ['Das arabische', 'Das chinesische', 'Die Hieroglyphen']],
              ['Welchem Dichter schreibt man Ilias und Odyssee zu?', 'Homer', ['Hesiod', 'Sophokles', 'Platon']],
              ['Wovon erzählt die Ilias?', 'Vom Zorn des Achilles im Trojanischen Krieg', ['Von der Irrfahrt des Odysseus', 'Von Alexander', 'Von Kreta']],
              ['Wie lange belagerten die Griechen Troja?', 'Zehn Jahre', ['Ein Jahr', 'Hundert Jahre', 'Zehn Tage']],
              ['Wen entführte Paris?', 'Helena', ['Penelope', 'Athene', 'Ariadne']],
              ['Wessen Frau war Helena?', 'Die des Königs Menelaos', ['Die des Odysseus', 'Die des Priamos', 'Die des Zeus']],
              ['Wovon erzählt die Odyssee?', 'Von der Irrfahrt des Odysseus', ['Vom Zorn des Achilles', 'Von den Olympischen Spielen', 'Von Sparta']],
              ['Womit eroberte Odysseus Troja?', 'Mit dem hölzernen Pferd', ['Mit einer Belagerungsmaschine', 'Mit Elefanten', 'Mit einem Tunnel']],
              ['Wer wartete treu auf Odysseus?', 'Penelope', ['Helena', 'Kirke', 'Kalypso']],
              ['Auf welchem Berg wohnten die Götter?', 'Auf dem Olymp', ['Auf dem Parnass', 'Auf dem Ätna', 'Auf der Akropolis']],
              ['Wer war der Göttervater?', 'Zeus', ['Poseidon', 'Apollon', 'Hades']],
              ['Wer war Gott des Meeres?', 'Poseidon', ['Zeus', 'Ares', 'Hermes']],
              ['Wer war Göttin der Weisheit?', 'Athene', ['Aphrodite', 'Hera', 'Artemis']],
              ['Wann fanden die ersten Olympischen Spiele statt?', '776 v. Chr.', ['1896', '490 v. Chr.', '1200 v. Chr.']],
              ['Zu Ehren welches Gottes fanden die Spiele statt?', 'Zeus', ['Apollon', 'Athene', 'Poseidon']],
              ['Was erhielten Olympiasieger?', 'Einen Kranz aus Olivenzweigen', ['Eine Goldmedaille', 'Geld', 'Ein Pferd']],
              ['Wie nannte man Nicht-Griechen?', 'Barbaren', ['Hellenen', 'Spartaner', 'Heloten']],
            ],
            mittel: [
              ['Wann übernahmen die Griechen die phönikische Schrift?', 'Im 8. Jahrhundert v. Chr.', ['Im 3. Jahrtausend v. Chr.', 'Im 1. Jahrhundert n. Chr.', 'Im 12. Jahrhundert v. Chr.']],
              ['Wann entstanden Homers Epen etwa?', 'Um 700 v. Chr.', ['Um 1200 v. Chr.', 'Um 300 v. Chr.', 'Um 100 n. Chr.']],
              ['Welcher Prinz entführte Helena?', 'Paris', ['Hektor', 'Achilles', 'Aeneas']],
              ['Wie lange dauerte die Irrfahrt des Odysseus?', 'Zehn Jahre', ['Ein Jahr', 'Zwanzig Tage', 'Hundert Jahre']],
              ['Wie wird Odysseus beschrieben?', 'Listenreich', ['Dumm', 'Feige', 'Grausam']],
              ['Welche Eigenschaft hatten die griechischen Götter?', 'Menschliche Gefühle', ['Keine Gefühle', 'Nur Tiergestalt', 'Unsichtbarkeit']],
              ['Wer war Zeus’ Frau?', 'Hera', ['Athene', 'Aphrodite', 'Demeter']],
              ['Welches Zeichen trägt Zeus?', 'Den Blitz', ['Den Dreizack', 'Den Bogen', 'Die Leier']],
              ['Wo befand sich ein berühmtes Orakel?', 'In Delphi', ['In Olympia', 'In Athen', 'In Sparta']],
              ['Wie hieß die Priesterin von Delphi?', 'Pythia', ['Kassandra', 'Medea', 'Medusa']],
              ['In wessen Namen sprach die Pythia?', 'Im Namen Apollons', ['Im Namen des Zeus', 'Im Namen Athenes', 'Im Namen des Hades']],
              ['Welcher Wettkampf war der erste in Olympia?', 'Ein Wettlauf über ein Stadion', ['Ringen', 'Wagenrennen', 'Speerwurf']],
              ['Wie lang war ein Stadion etwa?', 'Rund 192 Meter', ['Rund 42 Kilometer', 'Rund 19 Meter', 'Rund 1 Kilometer']],
              ['Welche Disziplinen kamen später hinzu?', 'Ringen, Faustkampf, Wagenrennen, Fünfkampf', ['Fußball und Tennis', 'Golf', 'Schach']],
              ['Was herrschte während der Spiele?', 'Ein heiliger Waffenstillstand', ['Krieg', 'Fasten', 'Ausgangssperre']],
              ['Wer durfte teilnehmen?', 'Nur freie griechische Männer', ['Alle Menschen', 'Nur Frauen', 'Auch Sklaven']],
              ['Wonach zählten die Griechen die Jahre?', 'Nach Olympiaden', ['Nach Königen', 'Nach Christi Geburt', 'Nach Kriegen']],
              ['Was trennte die Stadtstaaten?', 'Gebirge und Meer', ['Mauern aus Gold', 'Wüsten', 'Wälder voller Löwen']],
              ['Woher kommt das Wort „Barbar“?', 'Fremde Sprache klang wie „bar-bar“', ['Von Bart', 'Von einem Volk namens Barbaren', 'Von Barbara']],
              ['Welche Kolonie lag auf Sizilien?', 'Syrakus', ['Massalia', 'Byzanz', 'Milet']],
            ],
            schwer: [
              ['Was verband die zersplitterten Griechen?', 'Sprache, Götter, Homer und die Spiele', ['Ein gemeinsamer König', 'Eine Hauptstadt', 'Eine Armee']],
              ['Warum war die Vokalschrift bedeutend?', 'Erstes vollständiges Alphabet mit Vokalen', ['Sie war die älteste Schrift', 'Sie bestand aus Bildern', 'Sie war geheim']],
              ['Wie heißt Marseille als griechische Kolonie?', 'Massalia', ['Syrakus', 'Neapolis', 'Byzantion']],
              ['Was war die Polis?', 'Ein unabhängiger Stadtstaat', ['Ein Tempel', 'Ein Wettkampf', 'Ein Gott']],
              ['Wohin gründeten Griechen Kolonien?', 'Rund ums Mittelmeer und Schwarze Meer', ['Nach Amerika', 'Nach Japan', 'Nach Skandinavien']],
              ['Was bedeutet Homers Werk für die Griechen?', 'Gemeinsame Grundlage ihrer Kultur', ['Ein Gesetzbuch', 'Ein Kochbuch', 'Eine Landkarte']],
              ['Was war ein Vorteil des Waffenstillstands?', 'Sichere Anreise zu den Spielen', ['Höhere Steuern', 'Mehr Kriege danach', 'Nichts']],
              ['Wie traten Athleten in Olympia an?', 'Nackt', ['In Rüstung', 'In Togen', 'In Tierfellen']],
              ['Welche Götterin steht für Liebe?', 'Aphrodite', ['Athene', 'Hera', 'Artemis']],
              ['Welche Rolle hatte das Orakel von Delphi?', 'Weissagungen für Menschen und Staaten', ['Sportstätte', 'Gericht', 'Hafen']],
              ['Welche Stadt ist eine griechische Gründung in Italien?', 'Neapel', ['Rom', 'Mailand', 'Venedig']],
              ['Wann begann die Kolonisation?', 'Ab dem 8. Jahrhundert v. Chr.', ['Ab dem 2. Jahrhundert n. Chr.', 'Ab 1200 v. Chr.', 'Ab 500 n. Chr.']],
              ['Was ist das trojanische Pferd heute im übertragenen Sinn?', 'Eine List, um einzudringen', ['Ein Rennpferd', 'Ein Spielzeug', 'Eine Krankheit']],
              ['Wer war Menelaos?', 'König und Mann Helenas', ['Trojanischer Prinz', 'Gott des Krieges', 'Odysseus’ Sohn']],
              ['Welcher Gott wird mit Delphi verbunden?', 'Apollon', ['Ares', 'Hermes', 'Dionysos']],
              ['Was wurde aus dem Wort „Stadion“?', 'Ein Name für Sportstätten', ['Eine Münze', 'Ein Gott', 'Eine Stadt']],
              ['Was unterscheidet Ilias und Odyssee?', 'Krieg um Troja gegen Heimkehr des Odysseus', ['Kein Unterschied', 'Die Ilias ist römisch', 'Die Odyssee spielt in Ägypten']],
              ['Welcher Held ist Hauptfigur der Ilias?', 'Achilles', ['Odysseus', 'Herakles', 'Theseus']],
              ['Welcher Zeitraum wird mit dem Ende der Dunklen Jahrhunderte verbunden?', 'Das 8. Jahrhundert v. Chr.', ['Das 3. Jahrhundert v. Chr.', 'Das 12. Jahrhundert v. Chr.', 'Das 1. Jahrhundert n. Chr.']],
              ['Was war der Fünfkampf?', 'Eine olympische Disziplin aus mehreren Übungen', ['Ein Krieg', 'Ein Theaterstück', 'Ein Gericht']],
            ],
          },
        },
      ],
    },
  ],
};
