import type { Epoch } from '../types';

export const E2: Epoch = {
  id: 'antike',
  name: 'Das antike Griechenland',
  period: '800–30 v. Chr.',
  events: [
    {
      id: 'athen',
      title: 'Stadtstaaten, Demokratie und Philosophie',
      date: '800–338 v. Chr.',
      text: [
        'Griechenland zerfiel in Hunderte Stadtstaaten, von denen Sparta und Athen die mächtigsten wurden. Athen erfand die Demokratie, gemeinsam besiegten die Griechen die Perser, und im 5. Jahrhundert v. Chr. entstanden Theater, Geschichtsschreibung und Philosophie. Danach zerfleischten sich Athen und Sparta im Peloponnesischen Krieg.',
      ],
      subtopics: [
        {
          id: 'polis-sparta',
          title: 'Polis, Kolonien und Sparta',
          date: '800–500 v. Chr.',
          text: [
            'Nach den Dunklen Jahrhunderten bildeten sich in Griechenland Hunderte kleiner Stadtstaaten, griechisch „Polis“ (Mehrzahl „Poleis“). Eine Polis bestand aus einer Stadt mit ihrem Umland; oft lag auf einem Hügel eine Burg, die „Akropolis“, was „Oberstadt“ bedeutet. Mittelpunkt des Lebens war der Marktplatz, die „Agora“. Gebirge und Meer trennten die Poleis voneinander, deshalb entstand nie ein einheitlicher Staat. Trotzdem fühlten sich alle als „Hellenen“ und nannten Nichtgriechen „Barbaren“, weil deren Sprache für sie wie „bar-bar“ klang.',
            'Gemeinsam waren den Griechen Sprache, Götter und Heiligtümer. Die Götter wohnten nach ihrem Glauben auf dem Olymp, dem höchsten Berg Griechenlands; ihr Herrscher war Zeus. In Delphi befragten Menschen aus der ganzen griechischen Welt das Orakel des Gottes Apollon, dessen Priesterin Pythia rätselhafte Antworten gab. Auch die Olympischen Spiele zu Ehren des Zeus verbanden die Poleis.',
            'Weil das Ackerland knapp war und die Bevölkerung wuchs, gründeten die Griechen ab etwa 750 v. Chr. Kolonien rund um das Mittelmeer und das Schwarze Meer. So entstanden Syrakus auf Sizilien, Neapel („Neapolis“, die neue Stadt), Massalia (heute Marseille) und Byzantion am Bosporus. Der Philosoph Platon verglich die Griechen später mit Fröschen, die um einen Teich sitzen. Die Kolonien blieben selbstständig, waren aber durch Handel mit ihrer Mutterstadt verbunden. Um 600 v. Chr. kamen in Lydien in Kleinasien die ersten Münzen auf, die bald auch die Griechen prägten.',
            'Die mächtigste Polis auf der Halbinsel Peloponnes war Sparta. Die Spartaner hatten die Nachbarlandschaft Messenien erobert und deren Bewohner zu „Heloten“ gemacht, unfreien Staatssklaven, die das Land bestellen mussten. Weil die Heloten in der Überzahl waren und sich mehrmals erhoben, lebten die Spartaner wie in einem dauernden Kriegslager. Ihre Ordnung ging angeblich auf den Gesetzgeber Lykurg zurück. Sparta hatte zugleich zwei Könige, die das Heer führten, und einen Ältestenrat.',
            'Spartanische Jungen kamen mit sieben Jahren in die staatliche Erziehung, die „Agoge“, wo sie Hunger, Kälte und Schmerz ertragen lernten. Erwachsene Männer aßen in Speisegemeinschaften, wo es eine berüchtigte „schwarze Suppe“ aus Schweinefleisch, Blut und Essig gab. Spartanerinnen trieben Sport und hatten mehr Rechte als die Frauen in Athen. Weil die Spartaner wenig sprachen und knapp antworteten, nennt man eine kurze, treffende Ausdrucksweise bis heute „lakonisch“, nach ihrer Landschaft Lakonien. Als Kampfform setzte sich in ganz Griechenland die „Phalanx“ durch: eine dichte Reihe schwer bewaffneter Fußsoldaten, der „Hopliten“, die mit Rundschild und Speer kämpften.',
          ],
          quiz: {
            leicht: [
              ['Wie heißt ein griechischer Stadtstaat?', 'Polis', ['Imperium', 'Kanton', 'Gau']],
              ['Wie hieß die Burg auf dem Hügel einer Polis?', 'Akropolis', ['Agora', 'Nekropolis', 'Metropolis']],
              ['Wie hieß der Marktplatz einer Polis?', 'Agora', ['Akropolis', 'Forum', 'Basar']],
              ['Wie nannten sich die Griechen selbst?', 'Hellenen', ['Barbaren', 'Latiner', 'Phönizier']],
              ['Wie nannten die Griechen Nichtgriechen?', 'Barbaren', ['Heloten', 'Hopliten', 'Spartiaten']],
              ['Auf welchem Berg wohnten nach griechischem Glauben die Götter?', 'Auf dem Olymp', ['Auf dem Ätna', 'Auf dem Vesuv', 'Auf dem Sinai']],
              ['Wer war der Herrscher der griechischen Götter?', 'Zeus', ['Apollon', 'Poseidon', 'Hermes']],
              ['Wo befragten die Griechen ein berühmtes Orakel?', 'In Delphi', ['In Sparta', 'In Mykene', 'In Knossos']],
              ['Welche Stadt im heutigen Frankreich gründeten Griechen als Massalia?', 'Marseille', ['Paris', 'Lyon', 'Bordeaux']],
              ['Welche Polis war auf der Peloponnes am mächtigsten?', 'Sparta', ['Athen', 'Delphi', 'Byzantion']],
              ['Wie hießen die unfreien Staatssklaven Spartas?', 'Heloten', ['Hopliten', 'Hellenen', 'Ephoren']],
              ['Wie viele Könige hatte Sparta gleichzeitig?', 'Zwei', ['Einen', 'Drei', 'Fünf']],
              ['Wie nennt man eine knappe, treffende Ausdrucksweise nach Spartas Landschaft?', 'Lakonisch', ['Attisch', 'Dorisch', 'Ionisch']],
              ['Wie hießen die schwer bewaffneten griechischen Fußsoldaten?', 'Hopliten', ['Heloten', 'Legionäre', 'Samurai']],
              ['Wie hieß die dichte Schlachtreihe der Hopliten?', 'Phalanx', ['Legion', 'Kohorte', 'Schildkröte']],
              ['Mit wie vielen Jahren kamen spartanische Jungen in die staatliche Erziehung?', 'Mit sieben', ['Mit drei', 'Mit zwölf', 'Mit sechzehn']],
              ['Welche Speise war in Sparta berüchtigt?', 'Die schwarze Suppe', ['Der Honigkuchen', 'Die Fischsuppe', 'Der Linseneintopf']],
              ['Wo kamen die ersten Münzen auf?', 'In Lydien', ['In Ägypten', 'In Sparta', 'In Rom']],
              ['Welche Stadt in Italien hieß griechisch „neue Stadt“?', 'Neapel', ['Rom', 'Mailand', 'Venedig']],
              ['Zu Ehren welches Gottes fanden die Olympischen Spiele statt?', 'Zeus', ['Apollon', 'Ares', 'Dionysos']],
            ],
            mittel: [
              ['Warum entstand in Griechenland kein einheitlicher Staat?', 'Gebirge und Meer trennten die Poleis', ['Ein König verbot die Einigung', 'Die Römer verhinderten es', 'Es gab keine gemeinsame Sprache']],
              ['Woher kommt das Wort „Barbaren“?', 'Fremde Sprachen klangen für Griechen wie „bar-bar“', ['Von einem Volk namens Barbaren', 'Von einem griechischen Wort für Bart', 'Von einem persischen König']],
              ['Wie hieß die Priesterin des Orakels von Delphi?', 'Pythia', ['Ariadne', 'Kassandra', 'Penelope']],
              ['Welchem Gott gehörte das Orakel von Delphi?', 'Apollon', ['Zeus', 'Athene', 'Poseidon']],
              ['Ab wann gründeten die Griechen Kolonien?', 'Ab etwa 750 v. Chr.', ['Ab etwa 1500 v. Chr.', 'Ab etwa 300 v. Chr.', 'Ab etwa 50 n. Chr.']],
              ['Warum gründeten die Griechen Kolonien?', 'Ackerland war knapp und die Bevölkerung wuchs', ['Die Perser vertrieben sie', 'Ein Orakel verbot das Leben in der Heimat', 'Sparta zwang alle Poleis dazu']],
              ['Welche Kolonie lag auf Sizilien?', 'Syrakus', ['Massalia', 'Byzantion', 'Neapolis']],
              ['Welche Kolonie lag am Bosporus?', 'Byzantion', ['Syrakus', 'Massalia', 'Neapolis']],
              ['Womit verglich Platon die Griechen rund ums Mittelmeer?', 'Mit Fröschen um einen Teich', ['Mit Ameisen in einem Haufen', 'Mit Bienen im Stock', 'Mit Vögeln auf einem Ast']],
              ['Wie waren die Kolonien mit ihrer Mutterstadt verbunden?', 'Sie waren selbstständig, aber durch Handel verbunden', ['Die Mutterstadt regierte sie', 'Sie zahlten Tribut an Sparta', 'Gar nicht']],
              ['Welche Landschaft eroberte Sparta und machte deren Bewohner zu Heloten?', 'Messenien', ['Attika', 'Böotien', 'Makedonien']],
              ['Warum lebten die Spartaner wie in einem dauernden Kriegslager?', 'Die Heloten waren in der Überzahl und erhoben sich', ['Die Perser griffen jedes Jahr an', 'Sie wollten ganz Asien erobern', 'Ihr Gesetz verbot Häuser']],
              ['Auf welchen Gesetzgeber ging Spartas Ordnung angeblich zurück?', 'Lykurg', ['Solon', 'Drakon', 'Kleisthenes']],
              ['Wie hieß die spartanische Erziehung?', 'Agoge', ['Akademie', 'Ekklesia', 'Agora']],
              ['Was mussten spartanische Jungen in der Agoge ertragen lernen?', 'Hunger, Kälte und Schmerz', ['Reden vor der Volksversammlung', 'Handel und Seefahrt', 'Reiten und Bogenschießen']],
              ['Wie unterschieden sich Spartanerinnen von den Frauen in Athen?', 'Sie trieben Sport und hatten mehr Rechte', ['Sie durften wählen', 'Sie kämpften in der Phalanx', 'Sie durften das Haus nie verlassen']],
              ['Wo aßen erwachsene spartanische Männer?', 'In Speisegemeinschaften', ['Allein zu Hause', 'Im Tempel des Zeus', 'Bei den Heloten']],
              ['Womit kämpften die Hopliten?', 'Mit Rundschild und Speer', ['Mit Pfeil und Bogen', 'Mit Streitwagen', 'Mit Steinschleudern']],
              ['Was war Massalia?', 'Eine griechische Kolonie, heute Marseille', ['Eine Insel bei Kreta', 'Ein spartanischer König', 'Der Marktplatz Athens']],
              ['Was verband die Griechen trotz der Trennung in Poleis?', 'Sprache, Götter und Heiligtümer', ['Ein gemeinsamer König', 'Eine gemeinsame Hauptstadt', 'Ein gemeinsames Heer']],
            ],
            schwer: [
              ['Was bedeutet „Akropolis“?', 'Oberstadt', ['Marktplatz', 'Neue Stadt', 'Totenstadt']],
              ['Wie lautet die Mehrzahl von „Polis“?', 'Poleis', ['Polisse', 'Polien', 'Polen']],
              ['Was bedeutet „Neapolis“?', 'Neue Stadt', ['Große Stadt', 'Hafenstadt', 'Heilige Stadt']],
              ['Um wann kamen in Lydien die ersten Münzen auf?', 'Um 600 v. Chr.', ['Um 1200 v. Chr.', 'Um 300 v. Chr.', 'Um 100 n. Chr.']],
              ['Wonach ist das Wort „lakonisch“ benannt?', 'Nach Spartas Landschaft Lakonien', ['Nach einem König namens Lakon', 'Nach einer Göttin', 'Nach einem Fluss bei Athen']],
              ['Was gab es in Sparta außer den beiden Königen?', 'Einen Ältestenrat', ['Einen Kaiser', 'Einen Senat aus Heloten', 'Einen Pharao']],
              ['Welche Aufgabe hatten Spartas Könige?', 'Sie führten das Heer', ['Sie leiteten das Orakel', 'Sie richteten die Spiele aus', 'Sie verwalteten die Kolonien']],
              ['Was mussten die Heloten tun?', 'Das Land bestellen', ['In der Phalanx kämpfen', 'Die Könige wählen', 'Die Kolonien regieren']],
              ['Wie oft erhoben sich die Heloten?', 'Mehrmals', ['Nie', 'Genau einmal', 'Erst unter Alexander']],
              ['Woraus bestand die „schwarze Suppe“?', 'Aus Schweinefleisch, Blut und Essig', ['Aus Fisch und Honig', 'Aus Linsen und Wein', 'Aus Oliven und Ziegenmilch']],
              ['An welchem Meer außer dem Mittelmeer gründeten Griechen Kolonien?', 'Am Schwarzen Meer', ['An der Nordsee', 'Am Kaspischen Meer', 'Am Roten Meer']],
              ['Wer hatte in Sparta mehr Rechte als in Athen?', 'Die Frauen', ['Die Heloten', 'Die Fremden', 'Die Sklaven']],
              ['Was ist der Olymp?', 'Der höchste Berg Griechenlands', ['Ein Vulkan auf Sizilien', 'Ein Tempel in Athen', 'Eine Insel in der Ägäis']],
              ['Wie antwortete die Pythia?', 'Rätselhaft', ['Immer mit Ja oder Nein', 'Schriftlich auf Latein', 'Gar nicht']],
              ['Was gehörte zu einer Polis außer der Stadt?', 'Ihr Umland', ['Ein Kaiserpalast', 'Eine Kolonie in Asien', 'Ein eigener Olymp']],
              ['Wo lag Sparta?', 'Auf der Peloponnes', ['In Attika', 'Auf Kreta', 'In Kleinasien']],
              ['Wo lag Lydien?', 'In Kleinasien', ['Auf Sizilien', 'In Ägypten', 'Auf der Peloponnes']],
              ['Wo setzte sich die Phalanx als Kampfform durch?', 'In ganz Griechenland', ['Ausschließlich in Sparta', 'Zuerst in Persien', 'Auf Kreta unter den Minoern']],
              ['Welcher Philosoph verglich die Griechen mit Fröschen?', 'Platon', ['Sokrates', 'Aristoteles', 'Homer']],
              ['Welche Eigenschaft der Spartaner beschreibt das Wort „lakonisch“?', 'Sie sprachen wenig und antworteten knapp', ['Sie waren sehr reich', 'Sie liebten Feste', 'Sie waren gute Händler']],
            ],
          },
        },
        {
          id: 'demokratie-perser',
          title: 'Athens Demokratie und die Perserkriege',
          date: '621–431 v. Chr.',
          text: [
            'Athen, die Hauptstadt der Landschaft Attika, wurde zuerst von Adligen beherrscht. Um 621 v. Chr. schrieb Drakon die ersten Gesetze auf; weil schon kleine Vergehen mit dem Tod bestraft wurden, nennt man sehr harte Strafen bis heute „drakonisch“. 594 v. Chr. erhielt Solon den Auftrag, die Konflikte zwischen Arm und Reich zu lösen. Er strich die Schulden der Bauern und verbot, dass Athener wegen Schulden versklavt wurden. Außerdem teilte er die Bürger nach ihrem Vermögen in vier Klassen ein.',
            'Danach herrschten Tyrannen, also Alleinherrscher, die die Macht an sich gerissen hatten – zuerst Peisistratos, dann seine Söhne. Nach ihrem Sturz schuf Kleisthenes 508/507 v. Chr. die Grundlagen der Demokratie, der „Herrschaft des Volkes“. Er teilte die Bürger neu in zehn Phylen ein, damit die alten Adelsfamilien an Einfluss verloren. Mit dem Scherbengericht, griechisch „Ostrakismos“, konnten die Bürger einmal im Jahr einen gefährlichen Politiker für zehn Jahre verbannen, indem sie seinen Namen auf Tonscherben ritzten.',
            'Um 500 v. Chr. erhoben sich die Griechen in Ionien an der Küste Kleinasiens gegen das Perserreich, und Athen unterstützte sie. Zur Strafe schickte der Perserkönig Dareios ein Heer. 490 v. Chr. besiegten die Athener unter Miltiades die Perser bei Marathon. Der Legende nach lief ein Bote die gut 40 Kilometer nach Athen, rief „Wir haben gesiegt!“ und brach tot zusammen – daran erinnert der Marathonlauf. 480 v. Chr. griff Dareios’ Sohn Xerxes mit einem riesigen Heer an.',
            'Am Engpass der Thermopylen hielten der spartanische König Leonidas, seine 300 Spartaner und ihre Verbündeten die Perser auf, bis ein Verräter ihnen einen Pfad um den Pass zeigte; Leonidas fiel mit seinen Männern. Die Perser zerstörten Athen, doch der Athener Themistokles hatte eine große Flotte bauen lassen. In der Seeschlacht von Salamis 480 v. Chr. besiegten die wendigen griechischen Dreiruderer, die „Trieren“, die persische Flotte. 479 v. Chr. folgte der Sieg zu Land bei Plataiai.',
            'Nach den Siegen gründete Athen 478/477 v. Chr. den Attischen Seebund, ein Bündnis vieler Poleis, dessen Kasse zunächst auf der Insel Delos lag und 454 v. Chr. nach Athen verlegt wurde. Unter Perikles, der Athen ab etwa 443 v. Chr. führte, erlebte die Stadt ihr „Goldenes Zeitalter“. Mit Geld aus der Kasse des Seebundes ließ er auf der Akropolis den Parthenon bauen, einen Marmortempel für die Stadtgöttin Athene. In der Volksversammlung, der „Ekklesia“, die auf dem Hügel Pnyx tagte, stimmten die Bürger direkt über Gesetze ab, und viele Ämter wurden durch das Los vergeben; Perikles führte Tagegelder ein, damit auch Arme mitmachen konnten. Abstimmen durften aber nur freie Männer mit athenischen Eltern – Frauen, Sklaven und Fremde, die „Metöken“, waren ausgeschlossen.',
          ],
          quiz: {
            leicht: [
              ['Was bedeutet „Demokratie“?', 'Herrschaft des Volkes', ['Herrschaft der Besten', 'Herrschaft eines Einzelnen', 'Herrschaft der Reichen']],
              ['In welcher Polis entstand die Demokratie?', 'In Athen', ['In Sparta', 'In Korinth', 'In Theben']],
              ['Wer schuf 508/507 v. Chr. die Grundlagen der Demokratie?', 'Kleisthenes', ['Leonidas', 'Drakon', 'Xerxes']],
              ['Nach welchem Gesetzgeber heißen sehr harte Strafen „drakonisch“?', 'Nach Drakon', ['Nach Solon', 'Nach Lykurg', 'Nach Perikles']],
              ['Wie hieß das Verfahren, mit dem die Athener einen Politiker verbannen konnten?', 'Scherbengericht', ['Totengericht', 'Gottesurteil', 'Ritterschlag']],
              ['Worauf ritzten die Athener beim Scherbengericht Namen?', 'Auf Tonscherben', ['Auf Wachstafeln', 'Auf Papyrus', 'Auf Marmor']],
              ['Wo besiegten die Athener 490 v. Chr. die Perser?', 'Bei Marathon', ['Bei Salamis', 'An den Thermopylen', 'Bei Troja']],
              ['Woran erinnert der Marathonlauf?', 'An einen Boten, der nach dem Sieg nach Athen lief', ['An die Olympischen Spiele des Zeus', 'An die Flucht des Xerxes', 'An Alexanders Feldzug']],
              ['Welcher spartanische König kämpfte an den Thermopylen?', 'Leonidas', ['Lykurg', 'Perikles', 'Xerxes']],
              ['Wie viele Spartaner führte Leonidas an den Thermopylen?', '300', ['30', '3000', '30.000']],
              ['Wo siegte die griechische Flotte 480 v. Chr.?', 'Bei Salamis', ['Bei Marathon', 'Bei Plataiai', 'Bei Troja']],
              ['Welcher Perserkönig griff 480 v. Chr. an?', 'Xerxes', ['Dareios', 'Kyros', 'Alexander']],
              ['Welcher berühmte Tempel steht auf der Akropolis von Athen?', 'Der Parthenon', ['Das Pantheon', 'Das Kolosseum', 'Der Apollontempel von Delphi']],
              ['Welcher Göttin war der Parthenon geweiht?', 'Athene', ['Hera', 'Aphrodite', 'Artemis']],
              ['Wer führte Athen in seinem Goldenen Zeitalter?', 'Perikles', ['Xerxes', 'Leonidas', 'Drakon']],
              ['Durften Frauen in Athen abstimmen?', 'Nein', ['Ja', 'Nur reiche Frauen', 'Nur Priesterinnen']],
              ['Welches Reich griff Griechenland um 490 v. Chr. an?', 'Das Perserreich', ['Das Römische Reich', 'Das Ägyptische Reich', 'Das Osmanische Reich']],
              ['Wie hießen die griechischen Kriegsschiffe mit drei Ruderreihen?', 'Trieren', ['Galeonen', 'Koggen', 'Drachenboote']],
              ['Wie hieß das Bündnis, das Athen nach den Perserkriegen gründete?', 'Attischer Seebund', ['Peloponnesischer Bund', 'Hanse', 'Korinthischer Bund']],
              ['Was war ein Tyrann im alten Griechenland?', 'Ein Alleinherrscher, der die Macht an sich gerissen hatte', ['Ein gewählter Richter', 'Ein Priester des Apollon', 'Ein spartanischer Krieger']],
            ],
            mittel: [
              ['Wer schrieb um 621 v. Chr. Athens erste Gesetze auf?', 'Drakon', ['Solon', 'Kleisthenes', 'Perikles']],
              ['Was tat Solon 594 v. Chr. für die Bauern?', 'Er strich ihre Schulden', ['Er schenkte ihnen Sklaven', 'Er schickte sie in Kolonien', 'Er erhöhte ihre Steuern']],
              ['Was verbot Solon?', 'Athener wegen Schulden zu versklaven', ['Tempel zu bauen', 'Mit Persien zu handeln', 'Olympische Spiele zu feiern']],
              ['Wie teilte Solon die Bürger ein?', 'Nach Vermögen in vier Klassen', ['Nach Herkunft in zwei Stämme', 'Nach Alter in zehn Gruppen', 'Nach Beruf in sieben Zünfte']],
              ['Welcher Tyrann herrschte nach Solon in Athen?', 'Peisistratos', ['Kleisthenes', 'Miltiades', 'Themistokles']],
              ['In wie viele Phylen teilte Kleisthenes die Bürger ein?', 'Zehn', ['Zwei', 'Vier', 'Zwölf']],
              ['Warum teilte Kleisthenes die Bürger neu ein?', 'Damit die alten Adelsfamilien an Einfluss verloren', ['Damit Sparta schwächer wurde', 'Damit Frauen mitbestimmen durften', 'Damit die Perser abzogen']],
              ['Für wie lange verbannte das Scherbengericht einen Politiker?', 'Zehn Jahre', ['Ein Jahr', 'Lebenslang', 'Hundert Tage']],
              ['Welcher Aufstand löste die Perserkriege aus?', 'Der Aufstand der Ionier', ['Der Aufstand der Heloten', 'Der Aufstand der Ägypter', 'Der Aufstand der Makedonen']],
              ['Wer führte die Athener bei Marathon?', 'Miltiades', ['Themistokles', 'Leonidas', 'Perikles']],
              ['Wie weit ist es ungefähr von Marathon nach Athen?', 'Gut 40 Kilometer', ['Gut 4 Kilometer', 'Gut 400 Kilometer', 'Gut 100 Kilometer']],
              ['Wie gelangten die Perser an den Thermopylen hinter die Griechen?', 'Ein Verräter zeigte ihnen einen Pfad', ['Sie segelten um den Pass herum', 'Sie bestachen Leonidas', 'Sie gruben einen Tunnel']],
              ['Wer ließ eine große athenische Flotte bauen?', 'Themistokles', ['Miltiades', 'Leonidas', 'Solon']],
              ['Was geschah 480 v. Chr. mit der Stadt Athen?', 'Die Perser zerstörten sie', ['Sie wurde Hauptstadt Persiens', 'Ein Erdbeben zerstörte sie', 'Sparta eroberte sie']],
              ['Wo besiegten die Griechen 479 v. Chr. die Perser zu Land?', 'Bei Plataiai', ['Bei Marathon', 'Bei Salamis', 'Bei Troja']],
              ['Wo lag zunächst die Kasse des Attischen Seebundes?', 'Auf der Insel Delos', ['In Sparta', 'In Delphi', 'Auf Kreta']],
              ['Woher kam das Geld für den Parthenon?', 'Aus der Kasse des Seebundes', ['Aus Spenden Spartas', 'Aus dem Schatz von Troja', 'Aus Steuern der Heloten']],
              ['Wie hieß die Volksversammlung in Athen?', 'Ekklesia', ['Agoge', 'Senat', 'Phalanx']],
              ['Warum führte Perikles Tagegelder ein?', 'Damit auch Arme mitmachen konnten', ['Damit Soldaten kämpften', 'Um Tempel zu bauen', 'Um die Perser zu bezahlen']],
              ['Wie wurden viele Ämter in Athen vergeben?', 'Durch das Los', ['Durch Erbe', 'Durch den König', 'Durch Kauf']],
            ],
            schwer: [
              ['Wie hießen Fremde ohne Bürgerrecht in Athen?', 'Metöken', ['Heloten', 'Hopliten', 'Ephoren']],
              ['Wer durfte in Athen abstimmen?', 'Freie Männer mit athenischen Eltern', ['Alle Einwohner', 'Alle Männer einschließlich der Sklaven', 'Nur die Adligen']],
              ['Wann besiegten die Athener die Perser bei Marathon?', '490 v. Chr.', ['480 v. Chr.', '508 v. Chr.', '431 v. Chr.']],
              ['Was rief der Bote der Legende nach in Athen?', '„Wir haben gesiegt!“', ['„Die Perser kommen!“', '„Rettet euch!“', '„Es lebe Sparta!“']],
              ['Wessen Sohn war Xerxes?', 'Der Sohn des Dareios', ['Der Sohn des Kyros', 'Der Sohn des Leonidas', 'Der Sohn des Miltiades']],
              ['Was waren die Thermopylen?', 'Ein Engpass', ['Eine Insel', 'Ein Tempel', 'Eine Stadt in Persien']],
              ['Wann gründete Athen den Attischen Seebund?', '478/477 v. Chr.', ['508/507 v. Chr.', '490 v. Chr.', '404 v. Chr.']],
              ['Ab wann führte Perikles Athen etwa?', 'Ab etwa 443 v. Chr.', ['Ab etwa 594 v. Chr.', 'Ab etwa 490 v. Chr.', 'Ab etwa 338 v. Chr.']],
              ['Woraus besteht der Parthenon?', 'Aus Marmor', ['Aus Holz', 'Aus Ziegeln', 'Aus Beton']],
              ['Wie heißt das Scherbengericht auf Griechisch?', 'Ostrakismos', ['Ekklesia', 'Agoge', 'Phalanx']],
              ['Zu welcher Landschaft gehörte Athen?', 'Attika', ['Lakonien', 'Messenien', 'Ionien']],
              ['Wohin wurde die Kasse des Seebundes 454 v. Chr. verlegt?', 'Nach Athen', ['Nach Sparta', 'Nach Delphi', 'Nach Olympia']],
              ['Wo tagte die Volksversammlung Athens?', 'Auf dem Hügel Pnyx', ['In Olympia', 'Im Parthenon', 'In Delphi']],
              ['Wer herrschte nach Peisistratos in Athen?', 'Seine Söhne', ['Solon', 'Leonidas', 'Dareios']],
              ['Wie entschieden die Bürger in der Ekklesia über Gesetze?', 'Sie stimmten direkt ab', ['Über gewählte Abgeordnete', 'Gar nicht', 'Schriftlich in Delphi']],
              ['Wann erhielt Solon seinen Auftrag?', '594 v. Chr.', ['621 v. Chr.', '508 v. Chr.', '490 v. Chr.']],
              ['Warum heißen harte Strafen „drakonisch“?', 'Bei Drakon wurden schon kleine Vergehen mit dem Tod bestraft', ['Drakon war ein Drache', 'Drakon war ein Perserkönig', 'Drakon erfand das Scherbengericht']],
              ['Welchen Auftrag erhielt Solon?', 'Die Konflikte zwischen Arm und Reich zu lösen', ['Die Perser zu besiegen', 'Kolonien zu gründen', 'Sparta zu erobern']],
              ['Was zeichnete die griechischen Trieren bei Salamis aus?', 'Sie waren wendig', ['Sie hatten Kanonen', 'Sie hatten Segel aus Eisen', 'Sie waren unbewaffnet']],
              ['Wo lag Ionien?', 'An der Küste Kleinasiens', ['Auf der Peloponnes', 'Auf Sizilien', 'In Ägypten']],
            ],
          },
        },
        {
          id: 'philosophie-peloponnes',
          title: 'Theater, Philosophie und der Peloponnesische Krieg',
          date: '500–371 v. Chr.',
          text: [
            'Im 5. Jahrhundert v. Chr. erfanden die Athener das Theater. Bei den Festen für den Gott Dionysos wurden Tragödien und Komödien in riesigen Freilufttheatern aufgeführt; das Theater von Epidauros fasst rund 14.000 Zuschauer und ist für seine Akustik berühmt: Ein Flüstern hört man noch in der letzten Reihe. Die großen Tragödiendichter waren Aischylos, der älteste, der selbst bei Marathon gekämpft hatte, Sophokles („König Ödipus“, „Antigone“) und Euripides („Medea“). Aristophanes schrieb Komödien, in denen er Politiker verspottete. Alle Rollen spielten Männer mit Masken.',
            'Herodot schrieb über die Perserkriege und gilt als „Vater der Geschichtsschreibung“. Thukydides beschrieb den Peloponnesischen Krieg und suchte nüchtern nach seinen Ursachen. Der Arzt Hippokrates erklärte Krankheiten nicht als Strafe der Götter, sondern durch natürliche Ursachen; nach ihm ist der Ärzte-Eid, der Hippokratische Eid, benannt. Der Mathematiker Pythagoras, bekannt für seinen Satz über rechtwinklige Dreiecke, und später Euklid legten Grundlagen der Geometrie.',
            'Philosophie heißt „Liebe zur Weisheit“. Sokrates ging auf die Agora und stellte den Menschen Fragen, um zu zeigen, dass sie weniger wissen, als sie glauben – „Ich weiß, dass ich nichts weiß“. Er selbst schrieb nichts auf. 399 v. Chr. wurde er angeklagt, die Jugend zu verderben und die Götter nicht zu ehren, und zum Tod verurteilt; er trank den Schierlingsbecher. Sein Schüler Platon gründete die Akademie und schrieb Dialoge. Im Höhlengleichnis beschreibt er Menschen, die nur Schatten an einer Höhlenwand sehen und sie für die Wirklichkeit halten. Platons Schüler Aristoteles erforschte fast alle Wissensgebiete, gründete das Lykeion und wurde Lehrer Alexanders des Großen.',
            'Athen, die Seemacht mit dem Attischen Seebund, und Sparta, die Landmacht an der Spitze des Peloponnesischen Bundes, wurden immer stärkere Rivalen. 431–404 v. Chr. führten sie den Peloponnesischen Krieg. Auf Perikles’ Rat zog sich die Landbevölkerung hinter die Langen Mauern zurück, die Athen mit seinem Hafen Piräus verbanden. 430 v. Chr. brach in der überfüllten Stadt eine Seuche aus, die „Pest“ genannt wird; 429 v. Chr. starb Perikles. 415 v. Chr. schickte Athen eine riesige Flotte gegen Syrakus auf Sizilien, doch die Sizilienexpedition scheiterte 413 v. Chr. vollständig. Der athenische Politiker Alkibiades lief sogar zu Sparta über.',
            'Mit Geld von den Persern baute Sparta eine Flotte. 405 v. Chr. vernichtete der spartanische Feldherr Lysander die athenische Flotte bei Aigospotamoi, 404 v. Chr. kapitulierte Athen. Die Langen Mauern wurden abgerissen, und Sparta setzte die „Dreißig Tyrannen“ ein, doch schon 403 v. Chr. wurde die Demokratie wiederhergestellt. Danach kämpften die Poleis weiter gegeneinander: 371 v. Chr. besiegte Theben unter Epaminondas die Spartaner bei Leuktra. Die Poleis erschöpften sich – Nutznießer war das Königreich Makedonien im Norden.',
          ],
          quiz: {
            leicht: [
              ['Welche Kunstform erfanden die Athener im 5. Jahrhundert v. Chr.?', 'Das Theater', ['Die Oper', 'Das Kino', 'Den Roman']],
              ['Zu Ehren welches Gottes wurde Theater gespielt?', 'Dionysos', ['Zeus', 'Ares', 'Hermes']],
              ['Welche zwei Arten von Theaterstücken gab es?', 'Tragödien und Komödien', ['Opern und Operetten', 'Musicals und Ballette', 'Sagen und Märchen']],
              ['Wer spielte im griechischen Theater die Rollen?', 'Männer mit Masken', ['Frauen und Männer ohne Masken', 'Kinder aus Sparta', 'Sklavinnen']],
              ['Wer gilt als „Vater der Geschichtsschreibung“?', 'Herodot', ['Homer', 'Platon', 'Sokrates']],
              ['Nach welchem Arzt ist der Ärzte-Eid benannt?', 'Hippokrates', ['Aristoteles', 'Pythagoras', 'Euklid']],
              ['Was bedeutet „Philosophie“?', 'Liebe zur Weisheit', ['Lehre von den Sternen', 'Kunst der Rede', 'Herrschaft des Volkes']],
              ['Welcher Philosoph sagte „Ich weiß, dass ich nichts weiß“?', 'Sokrates', ['Platon', 'Aristoteles', 'Herodot']],
              ['Wie starb Sokrates?', 'Er trank den Schierlingsbecher', ['Er fiel in einer Schlacht', 'Er starb an der Seuche', 'Persische Soldaten töteten ihn']],
              ['Wer war der berühmteste Schüler des Sokrates?', 'Platon', ['Perikles', 'Herodot', 'Aristoteles']],
              ['Welche Schule gründete Platon?', 'Die Akademie', ['Das Lykeion', 'Die Agoge', 'Die Universität Bologna']],
              ['Wen unterrichtete Aristoteles?', 'Alexander den Großen', ['Perikles', 'Sokrates', 'Leonidas']],
              ['Welche Mächte kämpften im Peloponnesischen Krieg gegeneinander?', 'Athen und Sparta', ['Athen und Persien', 'Sparta und Troja', 'Rom und Karthago']],
              ['Wer gewann den Peloponnesischen Krieg?', 'Sparta', ['Athen', 'Persien', 'Theben']],
              ['Was brach 430 v. Chr. im überfüllten Athen aus?', 'Eine Seuche', ['Ein Vulkan', 'Ein Erdbeben', 'Ein Großbrand']],
              ['Welcher Mathematiker ist für einen Satz über rechtwinklige Dreiecke bekannt?', 'Pythagoras', ['Euklid', 'Hippokrates', 'Herodot']],
              ['Welcher Hafen war durch die Langen Mauern mit Athen verbunden?', 'Piräus', ['Delos', 'Marathon', 'Korinth']],
              ['Welches Stück schrieb Sophokles?', '„König Ödipus“', ['„Medea“', '„Ilias“', '„Odyssee“']],
              ['Wann kapitulierte Athen im Peloponnesischen Krieg?', '404 v. Chr.', ['490 v. Chr.', '431 v. Chr.', '338 v. Chr.']],
              ['Welche Art von Stücken schrieb Aristophanes?', 'Komödien', ['Tragödien', 'Heldenepen', 'Geschichtswerke']],
            ],
            mittel: [
              ['Wie viele Zuschauer fasst das Theater von Epidauros etwa?', 'Rund 14.000', ['Rund 1.400', 'Rund 140.000', 'Rund 400']],
              ['Wofür ist das Theater von Epidauros berühmt?', 'Für seine Akustik', ['Für sein Dach aus Gold', 'Für seine Lage auf Kreta', 'Für seine Wasserspiele']],
              ['Welche Tragödie schrieb Euripides?', '„Medea“', ['„Antigone“', '„König Ödipus“', '„Die Frösche“']],
              ['Wer schrieb über den Peloponnesischen Krieg?', 'Thukydides', ['Herodot', 'Homer', 'Platon']],
              ['Wie erklärte Hippokrates Krankheiten?', 'Durch natürliche Ursachen', ['Als Strafe der Götter', 'Durch Sternzeichen', 'Durch Flüche']],
              ['Wofür legten Pythagoras und Euklid Grundlagen?', 'Für die Geometrie', ['Für die Medizin', 'Für Athens Gesetze', 'Für die Olympischen Spiele']],
              ['Wo stellte Sokrates seine Fragen?', 'Auf der Agora', ['Im Parthenon', 'In Sparta', 'Im Theater von Epidauros']],
              ['Was schrieb Sokrates auf?', 'Nichts', ['Viele Dialoge', 'Ein Gesetzbuch', 'Die Ilias']],
              ['Wofür wurde Sokrates angeklagt?', 'Die Jugend zu verderben und die Götter nicht zu ehren', ['Für Verrat an Sparta', 'Für Diebstahl aus der Seebundkasse', 'Für den Mord an Perikles']],
              ['In welcher Form schrieb Platon?', 'In Dialogen', ['In Versen wie Homer', 'In Komödien', 'Auf Gesetzestafeln']],
              ['Welche Schule gründete Aristoteles?', 'Das Lykeion', ['Die Akademie', 'Die Agoge', 'Die Ekklesia']],
              ['Was erforschte Aristoteles?', 'Fast alle Wissensgebiete', ['Ausschließlich die Geschichte der Perserkriege', 'Die Heilkunst als Stadtarzt Athens', 'Den Bau von Trieren']],
              ['Wann dauerte der Peloponnesische Krieg?', '431–404 v. Chr.', ['490–479 v. Chr.', '338–323 v. Chr.', '594–508 v. Chr.']],
              ['Welchen Bund führte Sparta an?', 'Den Peloponnesischen Bund', ['Den Attischen Seebund', 'Den Korinthischen Bund', 'Die Hanse']],
              ['Was tat die Landbevölkerung Attikas auf Perikles’ Rat, als Sparta angriff?', 'Sie zog sich hinter die Langen Mauern zurück', ['Sie floh nach Sizilien', 'Sie ergab sich sofort', 'Sie griff Sparta an']],
              ['Wann starb Perikles?', '429 v. Chr.', ['404 v. Chr.', '490 v. Chr.', '399 v. Chr.']],
              ['Gegen welche Stadt richtete sich die Sizilienexpedition?', 'Syrakus', ['Karthago', 'Rom', 'Neapolis']],
              ['Welcher athenische Politiker lief zu Sparta über?', 'Alkibiades', ['Perikles', 'Thukydides', 'Sokrates']],
              ['Woher hatte Sparta das Geld für seine Flotte?', 'Von den Persern', ['Aus der Kasse des Seebundes', 'Von den Römern', 'Von den Ägyptern']],
              ['Wer besiegte Sparta 371 v. Chr. bei Leuktra?', 'Theben', ['Athen', 'Persien', 'Makedonien']],
            ],
            schwer: [
              ['Wo vernichtete Lysander 405 v. Chr. die athenische Flotte?', 'Bei Aigospotamoi', ['Bei Salamis', 'Bei Leuktra', 'Bei Marathon']],
              ['Welche Regierung setzte Sparta 404 v. Chr. in Athen ein?', 'Die „Dreißig Tyrannen“', ['Einen König', 'Einen persischen Statthalter', 'Die „Zehn Phylen“']],
              ['Wann wurde Athens Demokratie wiederhergestellt?', '403 v. Chr.', ['429 v. Chr.', '431 v. Chr.', '338 v. Chr.']],
              ['Was geschah 404 v. Chr. mit den Langen Mauern?', 'Sie wurden abgerissen', ['Sie wurden verlängert', 'Sie wurden zum Tempel umgebaut', 'Sie wurden bis Sparta weitergebaut']],
              ['Wann scheiterte die Sizilienexpedition?', '413 v. Chr.', ['429 v. Chr.', '431 v. Chr.', '404 v. Chr.']],
              ['Welcher Thebaner führte bei Leuktra?', 'Epaminondas', ['Lysander', 'Alkibiades', 'Leonidas']],
              ['Wer profitierte davon, dass sich die Poleis erschöpften?', 'Makedonien', ['Karthago', 'Ägypten', 'Troja']],
              ['Welche Tragödie schrieb Sophokles außer „König Ödipus“?', '„Antigone“', ['„Medea“', '„Die Frösche“', '„Ilias“']],
              ['Welcher Tragödiendichter hatte selbst bei Marathon gekämpft?', 'Aischylos', ['Sophokles', 'Euripides', 'Aristophanes']],
              ['Wie suchte Thukydides nach den Ursachen des Krieges?', 'Nüchtern', ['Durch Befragung des Orakels', 'Durch Traumdeutung', 'Durch Sternendeutung']],
              ['Was beschreibt Platons Höhlengleichnis?', 'Menschen, die Schatten für die Wirklichkeit halten', ['Den Bau der Akropolis', 'Das Leben der Heloten', 'Die Geburt des Zeus']],
              ['Was wollte Sokrates mit seinen Fragen zeigen?', 'Dass die Menschen weniger wissen, als sie glauben', ['Dass es keine Götter gibt', 'Dass Sparta besser ist als Athen', 'Dass Reichtum glücklich macht']],
              ['Wann wurde Sokrates zum Tod verurteilt?', '399 v. Chr.', ['404 v. Chr.', '431 v. Chr.', '338 v. Chr.']],
              ['Wo wurden die griechischen Theaterstücke aufgeführt?', 'In Freilufttheatern', ['In geschlossenen Hallen', 'Im Parthenon', 'Auf Schiffen']],
              ['Wer war Lysander?', 'Ein spartanischer Feldherr', ['Ein athenischer Dichter', 'Ein Perserkönig', 'Ein Arzt aus Kos']],
              ['Was ist nach Hippokrates benannt?', 'Der Ärzte-Eid', ['Ein Orakel', 'Ein Bund griechischer Städte', 'Ein Satz über Dreiecke']],
              ['Was war Athen im Gegensatz zu Sparta?', 'Eine Seemacht', ['Eine Landmacht', 'Ein Verbündeter Persiens', 'Ein Königreich']],
              ['Wann begann die Sizilienexpedition?', '415 v. Chr.', ['413 v. Chr.', '431 v. Chr.', '405 v. Chr.']],
              ['Welcher Mathematiker legte nach Pythagoras Grundlagen der Geometrie?', 'Euklid', ['Herodot', 'Aischylos', 'Sokrates']],
              ['Wer war der Lehrer des Aristoteles?', 'Platon', ['Sokrates', 'Herodot', 'Perikles']],
            ],
          },
        },
      ],
    },
    {
      id: 'alexander',
      title: 'Alexander der Große und der Hellenismus',
      date: '359–30 v. Chr.',
      text: [
        'Makedonien unterwarf die erschöpften Poleis, und Alexander der Große eroberte in nur elf Jahren das Perserreich bis nach Indien. Nach seinem Tod zerfiel sein Reich, doch griechische Sprache und Kultur verbreiteten sich von Ägypten bis Indien, bis Rom die hellenistischen Reiche eroberte.',
      ],
      subtopics: [
        {
          id: 'alexander-hellenismus',
          title: 'Philipp, Alexander und die hellenistische Welt',
          date: '359–30 v. Chr.',
          text: [
            'Im Norden Griechenlands lag das Königreich Makedonien, das viele Griechen als halb barbarisch ansahen. 359 v. Chr. kam dort König Philipp II. an die Macht. Er schuf ein schlagkräftiges Heer mit einer starken Reiterei und einer Phalanx, deren Krieger bis zu sechs Meter lange Lanzen trugen, die „Sarissen“. Der athenische Redner Demosthenes warnte in flammenden Reden, den „Philippika“, vor ihm – bis heute nennt man eine Kampfrede so. 338 v. Chr. besiegte Philipp Athen und Theben bei Chaironeia und vereinte Griechenland unter seiner Führung im Korinthischen Bund. 336 v. Chr. wurde er ermordet.',
            'Sein Sohn Alexander war erst 20 Jahre alt. Sein Lehrer war Aristoteles gewesen, und schon als Junge soll er das wilde Pferd Bukephalos gezähmt haben. Er schlug einen Aufstand nieder und zerstörte Theben. 334 v. Chr. zog er mit rund 40.000 Mann gegen das Perserreich. In Gordion in Kleinasien soll er den Gordischen Knoten mit dem Schwert durchgehauen haben, denn wer ihn löste, sollte nach einer Prophezeiung Herr über Asien werden. 333 v. Chr. besiegte er den Perserkönig Dareios III. bei Issos.',
            'Danach eroberte Alexander die Küste, darunter die Stadt Tyros nach sieben Monaten Belagerung, und Ägypten, wo man ihn als Pharao begrüßte. An der Nilmündung gründete er 331 v. Chr. Alexandria. Im selben Jahr besiegte er die Perser bei Gaugamela endgültig, und in Persepolis brannte der Königspalast. Dareios III. wurde auf der Flucht von seinen eigenen Leuten ermordet. Alexander zog weiter bis nach Indien und besiegte 326 v. Chr. am Fluss Hydaspes den König Poros, der mit Kriegselefanten kämpfte. Dann weigerten sich seine erschöpften Soldaten weiterzuziehen, und Alexander kehrte durch die Wüste Gedrosien zurück.',
            'Alexander wollte Griechen und Perser zu einem Volk verschmelzen. 324 v. Chr. ließ er bei der Massenhochzeit von Susa Tausende Makedonen persische Frauen heiraten; er selbst nahm persische Prinzessinnen zur Frau, nachdem er schon Roxane aus Baktrien geheiratet hatte. Überall gründete er Städte namens Alexandria. 323 v. Chr. starb er mit nur 32 Jahren in Babylon an einem Fieber. Seine Nachfolger, die „Diadochen“, kämpften jahrzehntelang um das Reich und teilten es: Die Ptolemäer herrschten in Ägypten, die Seleukiden über große Teile Asiens und die Antigoniden in Makedonien.',
            'Die Zeit nach Alexander heißt „Hellenismus“. Griechisch, in der gemeinsamen Umgangssprache „Koine“, wurde zur Weltsprache von Ägypten bis Indien; auch das Neue Testament wurde später auf Griechisch geschrieben. Alexandria wurde zum Zentrum der Wissenschaft, mit einer berühmten Bibliothek voller Schriftrollen und dem Leuchtturm Pharos, einem der sieben Weltwunder – ebenso wie der Koloss von Rhodos. Eratosthenes berechnete dort ziemlich genau den Erdumfang, und Archimedes aus Syrakus soll beim Baden „Heureka!“ („Ich hab’s gefunden!“) gerufen haben. Doch Rom wurde immer mächtiger: 146 v. Chr. zerstörten die Römer Korinth, Griechenland wurde römisch. 30 v. Chr. tötete sich Kleopatra VII., die letzte Herrscherin der Ptolemäer, und Ägypten fiel an Rom. Der römische Dichter Horaz schrieb, das eroberte Griechenland habe den wilden Sieger erobert – denn die Römer übernahmen die griechische Kultur.',
          ],
          quiz: {
            leicht: [
              ['Welches Königreich lag im Norden Griechenlands?', 'Makedonien', ['Sparta', 'Persien', 'Lydien']],
              ['Wer war Alexanders Vater?', 'Philipp II.', ['Dareios III.', 'Perikles', 'Leonidas']],
              ['Wer war Alexanders Lehrer?', 'Aristoteles', ['Sokrates', 'Platon', 'Herodot']],
              ['Wie hieß Alexanders Pferd?', 'Bukephalos', ['Pegasus', 'Rosinante', 'Incitatus']],
              ['Welchen Knoten soll Alexander durchgehauen haben?', 'Den Gordischen Knoten', ['Den Trojanischen Knoten', 'Den Persischen Knoten', 'Den Delphischen Knoten']],
              ['Wo besiegte Alexander 333 v. Chr. die Perser?', 'Bei Issos', ['Bei Marathon', 'Bei Salamis', 'Bei Troja']],
              ['Welche Stadt gründete Alexander in Ägypten?', 'Alexandria', ['Kairo', 'Memphis', 'Theben']],
              ['Als was wurde Alexander in Ägypten begrüßt?', 'Als Pharao', ['Als Sklave', 'Als Feind', 'Als Priester des Zeus']],
              ['Bis in welches Land zog Alexander nach Osten?', 'Bis nach Indien', ['Bis nach China', 'Bis nach Japan', 'Bis nach Australien']],
              ['Wie alt wurde Alexander der Große?', '32 Jahre', ['20 Jahre', '50 Jahre', '70 Jahre']],
              ['Wo starb Alexander der Große?', 'In Babylon', ['In Athen', 'In Alexandria', 'In Rom']],
              ['Wie nennt man Alexanders Nachfolger?', 'Diadochen', ['Pharaonen', 'Cäsaren', 'Heloten']],
              ['Wie heißt die Epoche nach Alexander?', 'Hellenismus', ['Mittelalter', 'Renaissance', 'Barock']],
              ['Welcher Leuchtturm war eines der sieben Weltwunder?', 'Der Pharos von Alexandria', ['Der Leuchtturm von Athen', 'Der Turm von Babel', 'Der Leuchtturm von Sparta']],
              ['Welcher Gelehrte soll „Heureka!“ gerufen haben?', 'Archimedes', ['Aristoteles', 'Sokrates', 'Euklid']],
              ['Welches Reich eroberte am Ende Griechenland?', 'Das Römische Reich', ['Das Perserreich', 'Das Osmanische Reich', 'Das Reich der Hunnen']],
              ['Wer war die letzte Herrscherin der Ptolemäer?', 'Kleopatra VII.', ['Roxane', 'Nofretete', 'Pythia']],
              ['Wofür war Alexandria berühmt?', 'Für seine Bibliothek', ['Für seine Gladiatoren', 'Für sein Orakel', 'Für die Olympischen Spiele']],
              ['Wie nennt man nach Demosthenes’ Reden bis heute eine Kampfrede?', 'Philippika', ['Odyssee', 'Ilias', 'Tragödie']],
              ['Gegen welches Reich zog Alexander 334 v. Chr.?', 'Gegen das Perserreich', ['Gegen das Römische Reich', 'Gegen Karthago', 'Gegen die Kelten']],
            ],
            mittel: [
              ['Wann kam Philipp II. in Makedonien an die Macht?', '359 v. Chr.', ['404 v. Chr.', '336 v. Chr.', '323 v. Chr.']],
              ['Wie hießen die langen Lanzen der makedonischen Phalanx?', 'Sarissen', ['Pilen', 'Hellebarden', 'Trieren']],
              ['Wie lang waren die Sarissen?', 'Bis zu sechs Meter', ['Bis zu zwei Meter', 'Bis zu einem Meter', 'Bis zu zwölf Meter']],
              ['Welcher athenische Redner warnte vor Philipp II.?', 'Demosthenes', ['Perikles', 'Sokrates', 'Aristophanes']],
              ['Wo besiegte Philipp II. 338 v. Chr. Athen und Theben?', 'Bei Chaironeia', ['Bei Issos', 'Bei Leuktra', 'Bei Gaugamela']],
              ['In welchem Bund vereinte Philipp II. Griechenland?', 'Im Korinthischen Bund', ['Im Attischen Seebund', 'Im Peloponnesischen Bund', 'In der Hanse']],
              ['Was geschah 336 v. Chr. mit Philipp II.?', 'Er wurde ermordet', ['Er eroberte Persien', 'Er wurde Pharao', 'Er starb in Indien']],
              ['Wie alt war Alexander, als er König wurde?', '20 Jahre', ['12 Jahre', '32 Jahre', '40 Jahre']],
              ['Welche Stadt zerstörte Alexander nach einem Aufstand?', 'Theben', ['Athen', 'Sparta', 'Korinth']],
              ['Welcher Perserkönig unterlag bei Issos?', 'Dareios III.', ['Xerxes', 'Kyros', 'Poros']],
              ['Welche Stadt belagerte Alexander sieben Monate lang?', 'Tyros', ['Troja', 'Babylon', 'Athen']],
              ['Wo besiegte Alexander die Perser 331 v. Chr. endgültig?', 'Bei Gaugamela', ['Bei Issos', 'Bei Chaironeia', 'Am Hydaspes']],
              ['Wie endete Dareios III.?', 'Seine eigenen Leute ermordeten ihn auf der Flucht', ['Er fiel bei Issos', 'Er wurde Alexanders Berater', 'Er floh nach Indien']],
              ['Welchen indischen König besiegte Alexander?', 'Poros', ['Dareios', 'Ashoka', 'Kyros']],
              ['Warum kehrte Alexander aus Indien um?', 'Seine Soldaten weigerten sich weiterzuziehen', ['Er wurde besiegt', 'Rom griff Makedonien an', 'Ein Orakel befahl es']],
              ['Was wollte Alexander mit der Massenhochzeit von Susa erreichen?', 'Griechen und Perser verschmelzen', ['Frieden mit Rom', 'Sparta belohnen', 'Ägypten erobern']],
              ['Welches Herrscherhaus regierte nach Alexander in Ägypten?', 'Die Ptolemäer', ['Die Seleukiden', 'Die Antigoniden', 'Die Achämeniden']],
              ['Wer herrschte nach Alexander über große Teile Asiens?', 'Die Seleukiden', ['Die Ptolemäer', 'Die Antigoniden', 'Die Römer']],
              ['Welche Sprache wurde im Hellenismus zur Weltsprache?', 'Griechisch', ['Latein', 'Persisch', 'Ägyptisch']],
              ['Welcher Gelehrte berechnete den Erdumfang?', 'Eratosthenes', ['Archimedes', 'Euklid', 'Aristoteles']],
            ],
            schwer: [
              ['Wie hieß die gemeinsame griechische Umgangssprache des Hellenismus?', 'Koine', ['Linear B', 'Aramäisch', 'Sanskrit']],
              ['In welcher Sprache wurde das Neue Testament geschrieben?', 'Griechisch', ['Latein', 'Hebräisch', 'Persisch']],
              ['Was sollte nach der Prophezeiung werden, wer den Gordischen Knoten löste?', 'Herr über Asien', ['Unsterblich', 'König von Athen', 'Pharao von Ägypten']],
              ['Wann brach Alexander gegen das Perserreich auf?', '334 v. Chr.', ['333 v. Chr.', '331 v. Chr.', '323 v. Chr.']],
              ['Was geschah in Persepolis?', 'Der Königspalast brannte', ['Alexander starb dort', 'Dareios III. siegte dort', 'Aristoteles lehrte dort']],
              ['Wo besiegte Alexander 326 v. Chr. König Poros?', 'Am Fluss Hydaspes', ['Am Nil', 'Bei Issos', 'Am Euphrat']],
              ['Womit kämpfte König Poros?', 'Mit Kriegselefanten', ['Mit Trieren', 'Mit Kanonen', 'Mit Kamelreitern']],
              ['Durch welche Wüste kehrte Alexander zurück?', 'Durch die Wüste Gedrosien', ['Durch die Sahara', 'Durch die Wüste Gobi', 'Durch die Wüste Negev']],
              ['Wann fand die Massenhochzeit von Susa statt?', '324 v. Chr.', ['334 v. Chr.', '338 v. Chr.', '301 v. Chr.']],
              ['Wie hieß Alexanders Frau aus Baktrien?', 'Roxane', ['Kleopatra', 'Pythia', 'Antigone']],
              ['Woran starb Alexander der Große?', 'An einem Fieber', ['In einer Schlacht', 'Durch einen Sturz vom Pferd', 'Durch Ertrinken im Nil']],
              ['Welches Herrscherhaus regierte nach Alexander in Makedonien?', 'Die Antigoniden', ['Die Ptolemäer', 'Die Seleukiden', 'Die Achämeniden']],
              ['Wann zerstörten die Römer Korinth?', '146 v. Chr.', ['338 v. Chr.', '30 v. Chr.', '323 v. Chr.']],
              ['Wann fiel Ägypten an Rom?', '30 v. Chr.', ['146 v. Chr.', '323 v. Chr.', '476 n. Chr.']],
              ['Welcher römische Dichter schrieb, das eroberte Griechenland habe den Sieger erobert?', 'Horaz', ['Homer', 'Herodot', 'Platon']],
              ['Was meinte Horaz mit diesem Satz?', 'Die Römer übernahmen die griechische Kultur', ['Griechen eroberten Rom im Krieg', 'Rom zerstörte die griechische Kultur', 'Griechenland wurde nie römisch']],
              ['Aus welcher Stadt stammte Archimedes?', 'Aus Syrakus', ['Aus Athen', 'Aus Sparta', 'Aus Babylon']],
              ['Welches Weltwunder stand außer dem Pharos in der hellenistischen Welt?', 'Der Koloss von Rhodos', ['Der Eiffelturm', 'Die Chinesische Mauer', 'Das Kolosseum']],
              ['Mit wie vielen Soldaten brach Alexander ungefähr auf?', 'Mit rund 40.000', ['Mit rund 4.000', 'Mit rund 400.000', 'Mit rund einer Million']],
              ['Wie sahen viele Griechen Makedonien?', 'Als halb barbarisch', ['Als Heimat der Götter', 'Als Teil Persiens', 'Als Kolonie Athens']],
            ],
          },
        },
      ],
    },
  ],
};
