import type { Epoch } from '../types';

export const E1: Epoch = {
  id: 'fruehzeit',
  name: 'Frühzeit, Burgund und Habsburg',
  period: 'bis 1568',
  events: [
    {
      id: 'anfaenge',
      title: 'Vom Leben mit dem Wasser bis zu den 17 Provinzen',
      date: '3400 v. Chr. – 1568',
      text: [
        'Die Niederlande – „niedrige Länder“ – liegen zu einem Viertel unter dem Meeresspiegel. Seit jeher kämpften ihre Bewohner gegen das Wasser. Römer, Friesen und Franken prägten das Land, bevor Burgunder und Habsburger die reichen Provinzen vereinten.',
      ],
      subtopics: [
        {
          id: 'roemer-friesen',
          title: 'Hünengräber, Römer und Friesen',
          date: '3400 v. Chr. – 1000',
          text: [
            'In der Provinz Drenthe stehen über 50 „Hunebedden“, Großsteingräber aus riesigen Findlingen, die Bauern um 3400 v. Chr. errichteten. Die Steine hatten eiszeitliche Gletscher aus Skandinavien mitgebracht. An der Küste lebten Menschen auf künstlich aufgeschütteten Hügeln („Terpen“ oder „Warften“), um sich vor Sturmfluten zu schützen.',
            'Ab 12 v. Chr. eroberten die Römer den Süden bis zum Rhein, der die Grenze des Reiches (Limes) bildete. Nijmegen (Noviomagus) gilt als älteste Stadt der Niederlande. Im Jahr 69 erhob sich der germanische Stamm der Bataver unter Julius Civilis gegen Rom; später sahen die Niederländer in den Batavern ihre Vorfahren und nannten ihren Staat um 1800 „Batavische Republik“. Nördlich des Rheins lebten die freien Friesen.',
            'Im 7. und 8. Jahrhundert eroberten die Franken das Land. Der englische Mönch Willibrord gründete um 695 das Bistum Utrecht und missionierte die Friesen. Der Missionar Bonifatius wurde 754 bei Dokkum von Friesen erschlagen. Der Handelsort Dorestad am Rhein war einer der wichtigsten Märkte Nordeuropas, bis ihn Wikinger im 9. Jahrhundert mehrfach plünderten.',
            'Um das Jahr 1000 begannen die Menschen, Deiche zu bauen und Sümpfe trockenzulegen. Daraus entstanden die „Polder“: tiefliegende Flächen, die von Deichen umgeben und entwässert werden. Weil alle zusammenarbeiten mussten, entstanden „Wasserschappen“ (Wasserverbände), die zu den ältesten demokratischen Einrichtungen des Landes gehören. Man sagt: „Gott schuf die Welt, aber die Niederländer schufen die Niederlande.“',
            'Schwere Sturmfluten veränderten die Küste. Die Elisabethflut von 1421 überschwemmte Dutzende Dörfer; Tausende ertranken. Der Legende nach trieb eine Wiege mit einem Kind und einer Katze, die sie im Gleichgewicht hielt, ans Ufer. Erst später halfen Windmühlen, das Wasser aus den Poldern zu pumpen.',
          ],
          quiz: {
            leicht: [
              ['Was bedeutet „Niederlande“?', 'Niedrige Länder', ['Neue Länder', 'Nördliche Länder', 'Nasse Länder']],
              ['Wie viel der Niederlande liegt unter dem Meeresspiegel?', 'Etwa ein Viertel', ['Die Hälfte', 'Gar nichts', 'Alles']],
              ['Wie heißen die Großsteingräber in Drenthe?', 'Hunebedden', ['Terpen', 'Polder', 'Grachten']],
              ['Wer brachte die Steine der Hunebedden?', 'Eiszeitliche Gletscher aus Skandinavien', ['Die Römer', 'Riesen', 'Die Wikinger']],
              ['Worauf lebten Menschen an der Küste?', 'Auf künstlichen Hügeln (Terpen)', ['Auf Pfählen', 'Auf Schiffen', 'In Höhlen']],
              ['Welcher Fluss war die Grenze des Römischen Reiches?', 'Der Rhein', ['Die Maas', 'Die Schelde', 'Die IJssel']],
              ['Welche Stadt gilt als älteste der Niederlande?', 'Nijmegen', ['Amsterdam', 'Utrecht', 'Rotterdam']],
              ['Welcher Stamm erhob sich 69 gegen Rom?', 'Die Bataver', ['Die Friesen', 'Die Franken', 'Die Sachsen']],
              ['Wer führte den Bataveraufstand?', 'Julius Civilis', ['Arminius', 'Vercingetorix', 'Willibrord']],
              ['Wie nannten die Niederländer ihren Staat um 1800?', 'Batavische Republik', ['Friesische Republik', 'Römische Republik', 'Holländische Union']],
              ['Welches Volk lebte nördlich des Rheins?', 'Die Friesen', ['Die Bataver', 'Die Römer', 'Die Kelten']],
              ['Welcher Mönch gründete das Bistum Utrecht?', 'Willibrord', ['Bonifatius', 'Gallus', 'Columban']],
              ['Wo wurde Bonifatius erschlagen?', 'Bei Dokkum', ['In Utrecht', 'In Fulda', 'In Amsterdam']],
              ['Welcher Handelsort wurde von Wikingern geplündert?', 'Dorestad', ['Amsterdam', 'Brügge', 'Haithabu']],
              ['Wie heißen eingedeichte, entwässerte Flächen?', 'Polder', ['Terpen', 'Hunebedden', 'Grachten']],
              ['Wie heißen die alten Wasserverbände?', 'Wasserschappen', ['Gilden', 'Hansen', 'Zünfte']],
              ['Was sagt ein Spruch über die Niederlande?', '„Gott schuf die Welt, aber die Niederländer schufen die Niederlande“', ['„Alles fließt“', '„Land unter“', '„Wasser ist Leben“']],
              ['Welche Flut 1421 überschwemmte Dutzende Dörfer?', 'Die Elisabethflut', ['Die Marcellusflut', 'Die Allerheiligenflut', 'Die Weihnachtsflut']],
              ['Was trieb der Legende nach ans Ufer?', 'Eine Wiege mit Kind und Katze', ['Ein Schiff voller Gold', 'Eine Kirche', 'Ein Pferd']],
              ['Was pumpte später Wasser aus den Poldern?', 'Windmühlen', ['Dampfschiffe', 'Dampfloks', 'Elefanten']],
            ],
            mittel: [
              ['In welcher Provinz stehen die Hunebedden?', 'In Drenthe', ['In Holland', 'In Zeeland', 'In Friesland']],
              ['Wie viele Hunebedden gibt es etwa?', 'Über 50', ['Rund 5', 'Über 500', 'Rund 15']],
              ['Wann wurden die Hunebedden errichtet?', 'Um 3400 v. Chr.', ['Um 69 n. Chr.', 'Um 1000', 'Um 12 v. Chr.']],
              ['Wie nennt man Terpen auch?', 'Warften', ['Polder', 'Deiche', 'Dünen']],
              ['Ab wann eroberten die Römer den Süden?', 'Ab 12 v. Chr.', ['Ab 69 n. Chr.', 'Ab 754', 'Ab 3400 v. Chr.']],
              ['Wie hieß Nijmegen bei den Römern?', 'Noviomagus', ['Traiectum', 'Lugdunum', 'Colonia']],
              ['In welchem Jahr erhoben sich die Bataver?', '69', ['12 v. Chr.', '695', '754']],
              ['Wann gründete Willibrord das Bistum Utrecht?', 'Um 695', ['Um 754', 'Um 1000', 'Um 69']],
              ['Woher stammte Willibrord?', 'Aus England', ['Aus Irland', 'Aus Rom', 'Aus Friesland']],
              ['Wann wurde Bonifatius erschlagen?', '754', ['695', '800', '1000']],
              ['Von wem wurde Bonifatius erschlagen?', 'Von Friesen', ['Von Wikingern', 'Von Römern', 'Von Franken']],
              ['Wer eroberte das Land im 7. und 8. Jahrhundert?', 'Die Franken', ['Die Römer', 'Die Wikinger', 'Die Spanier']],
              ['An welchem Fluss lag Dorestad?', 'Am Rhein', ['An der Maas', 'An der Amstel', 'An der Schelde']],
              ['Wann plünderten Wikinger Dorestad?', 'Im 9. Jahrhundert', ['Im 5. Jahrhundert', 'Im 12. Jahrhundert', 'Im 1. Jahrhundert']],
              ['Ab wann begann man mit dem Deichbau?', 'Um das Jahr 1000', ['Um 12 v. Chr.', 'Um 1600', 'Um 1900']],
              ['Warum entstanden die Wasserschappen?', 'Weil alle beim Deichbau zusammenarbeiten mussten', ['Weil der König es befahl', 'Weil die Kirche es wollte', 'Für den Krieg']],
              ['Als was gelten die Wasserschappen?', 'Als älteste demokratische Einrichtungen des Landes', ['Als Armee', 'Als Kirche', 'Als Bank']],
              ['Was hielt die Wiege laut Legende im Gleichgewicht?', 'Eine Katze', ['Ein Hund', 'Ein Engel', 'Ein Stein']],
              ['Wann war die Elisabethflut?', '1421', ['1953', '1000', '1570']],
              ['Was war Dorestad?', 'Einer der wichtigsten Märkte Nordeuropas', ['Eine Festung', 'Ein Kloster', 'Eine Burg']],
            ],
            schwer: [
              ['Was zeigt der Spruch über Gott und die Niederländer?', 'Dass viel Land durch Menschen geschaffen wurde', ['Dass die Niederländer Götter sind', 'Dass es keine Natur gibt', 'Dass Gott die Polder schuf']],
              ['Warum sahen Niederländer die Bataver als Vorfahren?', 'Als Symbol für Freiheitskampf gegen eine Großmacht', ['Weil sie Römer waren', 'Weil sie Friesisch sprachen', 'Zufall']],
              ['Was unterscheidet Terpen von Poldern?', 'Terpen sind Hügel, Polder eingedeichte Tiefflächen', ['Kein Unterschied', 'Terpen sind Mühlen', 'Polder sind Hügel']],
              ['Welche Rolle spielte Utrecht im Frühmittelalter?', 'Bistum und Missionszentrum', ['Hafenstadt der Wikinger', 'Römische Hauptstadt', 'Burgundische Residenz']],
              ['Warum war das Leben an der Küste gefährlich?', 'Wegen Sturmfluten', ['Wegen Vulkanen', 'Wegen Lawinen', 'Wegen Wüstenstürmen']],
              ['Was bildete im Süden die römische Grenze?', 'Der Rhein (Limes)', ['Die Nordsee', 'Die Maas', 'Die Elbe']],
              ['Welche Missionare wirkten bei den Friesen?', 'Willibrord und Bonifatius', ['Gallus und Columban', 'Patrick und Brigid', 'Kyrill und Method']],
              ['Was symbolisieren die Wasserschappen politisch?', 'Gemeinsame Selbstverwaltung', ['Königsmacht', 'Kirchenmacht', 'Militärherrschaft']],
              ['Wie entstanden Hunebedden technisch?', 'Aus riesigen Findlingen', ['Aus Ziegeln', 'Aus Holz', 'Aus Beton']],
              ['Was war die Folge der Wikingerüberfälle für Dorestad?', 'Es verlor seine Bedeutung', ['Es wurde Hauptstadt', 'Es wurde reicher', 'Nichts']],
              ['Welches heutige Wort erinnert an die Bataver?', 'Batavisch', ['Friesisch', 'Holländisch', 'Flämisch']],
              ['Welche Jahrhunderte gehören zur fränkischen Eroberung?', '7. und 8. Jahrhundert', ['3. und 4. Jahrhundert', '11. und 12. Jahrhundert', '15. Jahrhundert']],
              ['Wie wirkten Gletscher auf Drenthe?', 'Sie brachten Findlinge', ['Sie schufen Berge', 'Sie schufen Polder', 'Gar nicht']],
              ['Welche Stadt war Sitz des ersten Bistums?', 'Utrecht', ['Amsterdam', 'Haarlem', 'Leiden']],
              ['Wann begann der Kampf gegen das Wasser mit Deichen?', 'Um 1000', ['Um 1600', 'Um 1953', 'Um 69']],
              ['Was erinnert an die Elisabethflut?', 'Die Sage von der Wiege mit der Katze', ['Ein Denkmal in Rom', 'Ein Gemälde von Rembrandt', 'Nichts']],
              ['Welche Bevölkerung missionierte Willibrord?', 'Die Friesen', ['Die Bataver', 'Die Römer', 'Die Wikinger']],
              ['Was waren Wasserschappen genau?', 'Wasserverbände zur Deichpflege', ['Fischereigilden', 'Schiffswerften', 'Wasserburgen']],
              ['Warum nennt man das Land „niedrig“?', 'Weil viel Land unter dem Meeresspiegel liegt', ['Weil die Menschen klein sind', 'Weil es im Süden liegt', 'Wegen niedriger Steuern']],
              ['Welche Technik verbreitete sich später gegen Wasser?', 'Windmühlen zum Pumpen', ['Staudämme in Bergen', 'Wasserleitungen der Römer', 'Kanäle zum Bewässern']],
            ],
          },
        },
        {
          id: 'burgund-habsburg',
          title: 'Städte, Burgund und Karl V.',
          date: '1100–1568',
          text: [
            'Im Mittelalter entstanden viele kleine Herrschaften: die Grafschaften Holland und Zeeland, das Bistum Utrecht, das Herzogtum Geldern und andere. Städte wie Dordrecht, Leiden, Haarlem und Amsterdam wuchsen durch Handel, Fischfang und Tuchherstellung. Amsterdam entstand um einen Damm in der Amstel – daher der Name „Amstelredam“. Der Hering, haltbar gemacht durch das Einsalzen an Bord, wurde zum Grundstein des Wohlstands.',
            'Im 15. Jahrhundert vereinigten die Herzöge von Burgund, vor allem Philipp der Gute, die meisten dieser Gebiete. Sie schufen 1464 die „Generalstaaten“, eine Versammlung der Provinzen. Brügge, Gent und Antwerpen im Süden waren die reichsten Städte nördlich der Alpen. Maler wie Jan van Eyck und Hieronymus Bosch, dessen „Garten der Lüste“ voller fantastischer Wesen ist, schufen hier berühmte Werke.',
            'Nach dem Tod Karls des Kühnen 1477 heiratete seine Tochter Maria von Burgund Maximilian von Habsburg; so kamen die Niederlande an die Habsburger. Ihr Enkel Karl V., 1500 in Gent geboren, vereinte die „17 Provinzen“ – ungefähr die heutigen Niederlande, Belgien und Luxemburg. Er sprach Französisch und Flämisch und fühlte sich hier zu Hause.',
            'Der Gelehrte Erasmus von Rotterdam (um 1466–1536) war der berühmteste Humanist Europas. Er spottete in „Lob der Torheit“ über Missstände in der Kirche und gab das Neue Testament auf Griechisch heraus. Reformatorische Ideen von Luther und später Calvin verbreiteten sich rasch; Karl V. ließ Ketzer verfolgen, 1523 wurden in Brüssel die ersten lutherischen Märtyrer verbrannt.',
            '1555 übergab Karl V. die Niederlande seinem Sohn Philipp II., der in Spanien aufgewachsen war, kein Niederländisch sprach und streng katholisch regierte. Er erhöhte Steuern, verschärfte die Ketzerverfolgung und missachtete die alten Rechte der Städte und des Adels. 1566 stürmten Calvinisten im „Bildersturm“ Hunderte Kirchen und zerstörten Heiligenbilder und Statuen.',
          ],
          quiz: {
            leicht: [
              ['Welche Grafschaft gab es im Mittelalter im Norden?', 'Holland', ['Kastilien', 'Bayern', 'Savoyen']],
              ['Woraus entstand der Name Amsterdam?', 'Aus einem Damm in der Amstel', ['Aus einem Bischofsnamen', 'Aus dem Latein', 'Aus „Amsel“']],
              ['Welcher Fisch wurde Grundstein des Wohlstands?', 'Der Hering', ['Der Lachs', 'Der Kabeljau', 'Der Aal']],
              ['Wie wurde der Hering haltbar gemacht?', 'Durch Einsalzen an Bord', ['Durch Kochen', 'Durch Einfrieren', 'Durch Trocknen in der Sonne']],
              ['Welche Herzöge vereinigten die Gebiete im 15. Jahrhundert?', 'Die Herzöge von Burgund', ['Die Habsburger', 'Die Oranier', 'Die Bourbonen']],
              ['Welcher Herzog von Burgund war besonders wichtig?', 'Philipp der Gute', ['Karl der Große', 'Philipp II.', 'Wilhelm von Oranien']],
              ['Welche Versammlung schufen die Burgunder 1464?', 'Die Generalstaaten', ['Den Reichstag', 'Das Parlament von Paris', 'Die Hanse']],
              ['Welche Städte waren die reichsten nördlich der Alpen?', 'Brügge, Gent und Antwerpen', ['Amsterdam und Rotterdam', 'Köln und Mainz', 'London und York']],
              ['Welcher Maler malte den „Garten der Lüste“?', 'Hieronymus Bosch', ['Jan van Eyck', 'Rembrandt', 'Vermeer']],
              ['Wen heiratete Maria von Burgund?', 'Maximilian von Habsburg', ['Philipp II.', 'Karl V.', 'Ludwig XI.']],
              ['An wen kamen die Niederlande dadurch?', 'An die Habsburger', ['An Frankreich', 'An England', 'An Spanien direkt']],
              ['Wo wurde Karl V. geboren?', 'In Gent', ['In Madrid', 'In Wien', 'In Amsterdam']],
              ['Wie viele Provinzen vereinte Karl V.?', '17', ['7', '12', '26']],
              ['Welche heutigen Länder umfassten die 17 Provinzen etwa?', 'Niederlande, Belgien und Luxemburg', ['Deutschland und Dänemark', 'Frankreich und Spanien', 'Nur die Niederlande']],
              ['Welcher Humanist stammte aus Rotterdam?', 'Erasmus', ['Spinoza', 'Grotius', 'Calvin']],
              ['Wie heißt Erasmus’ berühmte Spottschrift?', '„Lob der Torheit“', ['„Der Fürst“', '„Utopia“', '„Narrenschiff“']],
              ['Wem übergab Karl V. 1555 die Niederlande?', 'Seinem Sohn Philipp II.', ['Seinem Bruder Ferdinand', 'Wilhelm von Oranien', 'Maria von Burgund']],
              ['Welche Sprache sprach Philipp II. nicht?', 'Niederländisch', ['Spanisch', 'Latein', 'Kastilisch']],
              ['Wie nennt man die Kirchenstürme von 1566?', 'Bildersturm', ['Sturmflut', 'Glaubenskrieg', 'Reconquista']],
              ['Wer stürmte 1566 die Kirchen?', 'Calvinisten', ['Katholiken', 'Spanier', 'Juden']],
            ],
            mittel: [
              ['Welche Herrschaften gab es im Mittelalter?', 'Holland, Zeeland, Utrecht, Geldern', ['Bayern und Sachsen', 'Burgund und Savoyen', 'Kastilien und Aragón']],
              ['Wodurch wuchsen die Städte?', 'Durch Handel, Fischfang und Tuchherstellung', ['Durch Bergbau', 'Durch Kriege', 'Durch Weinbau']],
              ['Wie hieß Amsterdam ursprünglich?', 'Amstelredam', ['Amsterburg', 'Amstelland', 'Damstadt']],
              ['Wann wurden die Generalstaaten geschaffen?', '1464', ['1477', '1555', '1568']],
              ['Welcher Maler gehört zu den burgundischen Niederlanden?', 'Jan van Eyck', ['Rembrandt', 'Van Gogh', 'Vermeer']],
              ['Was zeigt der „Garten der Lüste“?', 'Fantastische Wesen', ['Ein Stillleben', 'Eine Landkarte', 'Ein Porträt des Königs']],
              ['Wann starb Karl der Kühne?', '1477', ['1464', '1500', '1555']],
              ['Wann wurde Karl V. geboren?', '1500', ['1477', '1555', '1519']],
              ['Welche Sprachen sprach Karl V.?', 'Französisch und Flämisch', ['Nur Spanisch', 'Nur Deutsch', 'Englisch und Russisch']],
              ['Wann lebte Erasmus?', 'Um 1466–1536', ['1566–1632', '1400–1450', '1600–1650']],
              ['Was gab Erasmus heraus?', 'Das Neue Testament auf Griechisch', ['Eine Landkarte', 'Ein Gesetzbuch', 'Den Koran']],
              ['Worüber spottete Erasmus?', 'Über Missstände in der Kirche', ['Über die Römer', 'Über Deiche', 'Über den Handel']],
              ['Welche Reformatoren beeinflussten die Niederlande?', 'Luther und Calvin', ['Thomas von Aquin', 'Hus und Wyclif', 'Augustinus und Ambrosius']],
              ['Wann wurden in Brüssel die ersten lutherischen Märtyrer verbrannt?', '1523', ['1566', '1517', '1555']],
              ['Wo war Philipp II. aufgewachsen?', 'In Spanien', ['In Gent', 'In Wien', 'In Amsterdam']],
              ['Was erhöhte Philipp II.?', 'Die Steuern', ['Die Freiheiten', 'Die Zahl der Provinzen', 'Die Toleranz']],
              ['Was missachtete Philipp II.?', 'Die alten Rechte der Städte und des Adels', ['Die Bibel', 'Den Papst', 'Die Deiche']],
              ['Wie viele Kirchen wurden 1566 gestürmt?', 'Hunderte', ['Eine', 'Zehn', 'Keine']],
              ['Was zerstörten die Bilderstürmer?', 'Heiligenbilder und Statuen', ['Deiche', 'Schiffe', 'Rathäuser']],
              ['Wie regierte Philipp II. religiös?', 'Streng katholisch', ['Tolerant', 'Protestantisch', 'Gleichgültig']],
            ],
            schwer: [
              ['Warum war Philipp II. in den Niederlanden unbeliebt?', 'Fremd, streng katholisch, hohe Steuern, Missachtung alter Rechte', ['Er war zu tolerant', 'Er senkte die Steuern', 'Er sprach nur Niederländisch']],
              ['Was unterschied Karl V. von Philipp II. in den Niederlanden?', 'Karl war dort geboren und fühlte sich zu Hause', ['Philipp war dort geboren', 'Kein Unterschied', 'Karl war Calvinist']],
              ['Was war der Bildersturm ein Vorbote von?', 'Dem Aufstand gegen Spanien', ['Der Französischen Revolution', 'Der Industrialisierung', 'Der Pest']],
              ['Welche Rolle spielten die Generalstaaten?', 'Gemeinsame Versammlung der Provinzen', ['Ein Gericht', 'Eine Armee', 'Eine Kirche']],
              ['Wo lag der wirtschaftliche Schwerpunkt im 15. Jahrhundert?', 'Im Süden (Flandern, Brabant)', ['Im Norden (Friesland)', 'In Utrecht', 'Auf See']],
              ['Wie gelangten die Niederlande an Spanien?', 'Über das Erbe der Habsburger', ['Durch Krieg', 'Durch Kauf', 'Durch den Papst']],
              ['Was zeigt der Hering für die Wirtschaft?', 'Fischfang und Handel als Wohlstandsquelle', ['Landwirtschaft als Hauptsache', 'Bergbau', 'Nichts']],
              ['Warum war Erasmus bedeutend?', 'Berühmtester Humanist Europas', ['Erster Calvinist', 'König von Holland', 'Seefahrer']],
              ['Welches Ereignis brachte Burgunds Erbe an Habsburg?', 'Die Heirat Marias mit Maximilian 1477', ['Die Geburt Karls V.', 'Der Bildersturm', 'Die Gründung der Generalstaaten']],
              ['Welche Stadt war Geburtsort eines Kaisers?', 'Gent', ['Brügge', 'Antwerpen', 'Haarlem']],
              ['Was war „Lob der Torheit“?', 'Eine satirische Schrift', ['Ein Gesetz', 'Ein Gemälde', 'Eine Bibelübersetzung']],
              ['Wie reagierte Karl V. auf die Reformation?', 'Er ließ Ketzer verfolgen', ['Er wurde Protestant', 'Er duldete alles', 'Er floh']],
              ['Welche Glaubensrichtung prägte den Bildersturm?', 'Der Calvinismus', ['Der Katholizismus', 'Der Islam', 'Die Orthodoxie']],
              ['Was umfassten die 17 Provinzen nicht?', 'Deutschland', ['Belgien', 'Luxemburg', 'Holland']],
              ['Wann übernahm Philipp II. die Niederlande?', '1555', ['1477', '1500', '1568']],
              ['Woher stammt der Wohlstand Amsterdams zuerst?', 'Handel und Fischfang', ['Gold aus Amerika', 'Kolonien in Asien sofort', 'Bergbau']],
              ['Welche Rolle spielten Brügge und Antwerpen?', 'Reichste Handelsstädte', ['Fischerdörfer', 'Militärhäfen', 'Dörfer']],
              ['Welcher Maler ist für Fantasiewelten bekannt?', 'Hieronymus Bosch', ['Jan van Eyck', 'Frans Hals', 'Pieter de Hooch']],
              ['Was entstand aus den 17 Provinzen später?', 'Die Niederlande, Belgien und Luxemburg', ['Frankreich', 'Deutschland', 'Dänemark']],
              ['Welches Jahr nennt den Bildersturm?', '1566', ['1523', '1555', '1568']],
            ],
          },
        },
      ],
    },
  ],
};
