import type { Epoch } from '../types';

export const E3: Epoch = {
  id: 'koenigreich',
  name: 'Das Königreich',
  period: '1795–1939',
  events: [
    {
      id: 'koenigreich',
      title: 'Von Napoleon zum modernen Königreich',
      date: '1795–1939',
      text: [
        'Unter französischem Einfluss wurde aus der Republik ein Königreich. Belgien spaltete sich ab, eine liberale Verfassung machte die Niederlande zur parlamentarischen Monarchie. Die Kolonie Niederländisch-Indien brachte Reichtum, die Gesellschaft teilte sich in „Säulen“.',
      ],
      subtopics: [
        {
          id: 'napoleon-koenigreich',
          title: 'Batavische Republik, Napoleon und das Königreich',
          date: '1795–1848',
          text: [
            '1795 marschierten französische Revolutionstruppen über die zugefrorenen Flüsse ein; der Statthalter Wilhelm V. floh nach England. Die „Batavische Republik“ entstand, ein Einheitsstaat nach französischem Vorbild. 1798 erhielt sie ihre erste Verfassung, Kirche und Staat wurden getrennt, Juden wurden gleichberechtigt. Die VOC, längst verschuldet, wurde 1799 aufgelöst.',
            '1806 machte Napoleon seinen Bruder Louis Bonaparte zum König von Holland. Louis bemühte sich, Niederländisch zu lernen, und stellte sich oft auf die Seite seiner Untertanen; als er 1810 Napoleons Befehlen nicht mehr gehorchte, schaffte Napoleon das Königreich ab und gliederte die Niederlande in Frankreich ein. Aus dieser Zeit stammen Familiennamen, die alle Niederländer annehmen mussten, das Standesamt und der Code civil.',
            'Nach Napoleons Niederlage kehrte der Sohn des letzten Statthalters 1813 zurück und wurde 1815 als Wilhelm I. König. Der Wiener Kongress vereinte Nord und Süd zum „Vereinigten Königreich der Niederlande“ als Puffer gegen Frankreich. Wilhelm I. förderte Kanäle, Industrie und Handel und wurde „Kaufmannskönig“ genannt.',
            'Doch die katholischen, teils französischsprachigen Südprovinzen fühlten sich benachteiligt. 1830 erhoben sie sich nach einer Opernaufführung in Brüssel; Belgien erklärte seine Unabhängigkeit. Wilhelm I. erkannte sie erst 1839 an. Auch Luxemburg, das in Personalunion mit dem niederländischen König verbunden war, wurde 1890 eigenständig.',
            'Nach den Revolutionen von 1848 in Europa ließ König Wilhelm II. eine neue Verfassung ausarbeiten, die der liberale Politiker Johan Rudolf Thorbecke entwarf. Sie machte die Niederlande zur parlamentarischen Monarchie: Die Minister waren dem Parlament verantwortlich, nicht mehr dem König. Wilhelm II. sagte, er sei „in einer Nacht von konservativ zu liberal geworden“. Die Grundzüge dieser Verfassung gelten bis heute.',
          ],
          quiz: {
            leicht: [
              ['Wann marschierten die Franzosen ein?', '1795', ['1815', '1830', '1848']],
              ['Worüber marschierten die Franzosen 1795?', 'Über zugefrorene Flüsse', ['Über Brücken', 'Mit Schiffen', 'Durch Tunnel']],
              ['Wohin floh Wilhelm V.?', 'Nach England', ['Nach Preußen', 'Nach Spanien', 'Nach Amerika']],
              ['Wie hieß der Staat ab 1795?', 'Batavische Republik', ['Königreich Holland', 'Republik der Sieben Provinzen', 'Vereinigtes Königreich']],
              ['Wann wurde die VOC aufgelöst?', '1799', ['1795', '1602', '1815']],
              ['Wen machte Napoleon 1806 zum König von Holland?', 'Seinen Bruder Louis', ['Seinen Bruder Joseph', 'Wilhelm I.', 'Sich selbst']],
              ['Was versuchte Louis Bonaparte zu lernen?', 'Niederländisch', ['Englisch', 'Deutsch', 'Latein']],
              ['Was tat Napoleon 1810?', 'Er gliederte die Niederlande in Frankreich ein', ['Er machte sie unabhängig', 'Er gab sie England', 'Er verkaufte sie']],
              ['Was mussten alle Niederländer unter Napoleon annehmen?', 'Familiennamen', ['Den katholischen Glauben', 'Französische Vornamen', 'Neue Häuser']],
              ['Wer wurde 1815 König der Niederlande?', 'Wilhelm I.', ['Louis Bonaparte', 'Wilhelm V.', 'Wilhelm III.']],
              ['Welches Königreich schuf der Wiener Kongress?', 'Vereinigtes Königreich der Niederlande', ['Königreich Holland', 'Königreich Belgien', 'Batavische Republik']],
              ['Wie nannte man Wilhelm I.?', '„Kaufmannskönig“', ['„Bürgerkönig“', '„Sonnenkönig“', '„Seekönig“']],
              ['Welches Land spaltete sich 1830 ab?', 'Belgien', ['Luxemburg', 'Friesland', 'Zeeland']],
              ['Wo begann der belgische Aufstand?', 'Nach einer Opernaufführung in Brüssel', ['In einer Kirche in Gent', 'Auf einem Schiff', 'In Amsterdam']],
              ['Wann erkannte Wilhelm I. Belgien an?', '1839', ['1830', '1815', '1848']],
              ['Welches Land wurde 1890 eigenständig?', 'Luxemburg', ['Belgien', 'Friesland', 'Limburg']],
              ['Wer entwarf die Verfassung von 1848?', 'Johan Rudolf Thorbecke', ['Wilhelm II.', 'Johan de Witt', 'Hugo Grotius']],
              ['Was wurden die Niederlande 1848?', 'Eine parlamentarische Monarchie', ['Eine Republik', 'Eine absolute Monarchie', 'Ein Teil Frankreichs']],
              ['Wem waren die Minister nun verantwortlich?', 'Dem Parlament', ['Dem König', 'Dem Papst', 'Frankreich']],
              ['Gilt die Verfassung von 1848 in Grundzügen noch?', 'Ja', ['Nein, sie wurde abgeschafft', 'Nur in Belgien', 'Nur für Amsterdam']],
            ],
            mittel: [
              ['Wann erhielt die Batavische Republik ihre erste Verfassung?', '1798', ['1795', '1806', '1815']],
              ['Was wurde 1798 getrennt?', 'Kirche und Staat', ['Holland und Zeeland', 'Nord und Süd', 'König und Volk']],
              ['Wer wurde 1798 gleichberechtigt?', 'Die Juden', ['Die Frauen', 'Die Adligen', 'Die Sklaven']],
              ['Warum wurde die VOC aufgelöst?', 'Sie war längst verschuldet', ['Sie war zu reich', 'Napoleon kaufte sie', 'England eroberte sie']],
              ['Auf wessen Seite stellte sich Louis oft?', 'Auf die Seite seiner Untertanen', ['Auf Napoleons Seite', 'Auf Englands Seite', 'Auf Spaniens Seite']],
              ['Wann schaffte Napoleon das Königreich Holland ab?', '1810', ['1806', '1813', '1815']],
              ['Welche Einrichtungen stammen aus der Franzosenzeit?', 'Standesamt und Code civil', ['Die Börse', 'Die Universität Leiden', 'Die Wasserschappen']],
              ['Wann kehrte der Oranier zurück?', '1813', ['1815', '1795', '1830']],
              ['Wessen Sohn war Wilhelm I.?', 'Des letzten Statthalters Wilhelm V.', ['Louis Bonapartes', 'Napoleons', 'Johan de Witts']],
              ['Warum vereinte der Wiener Kongress Nord und Süd?', 'Als Puffer gegen Frankreich', ['Aus Liebe', 'Für den Handel mit England', 'Auf Wunsch der Belgier']],
              ['Was förderte Wilhelm I.?', 'Kanäle, Industrie und Handel', ['Kriege', 'Kolonien in Afrika', 'Die Kirche']],
              ['Warum fühlten sich die Südprovinzen benachteiligt?', 'Sie waren katholisch und teils französischsprachig', ['Sie waren protestantisch', 'Sie waren reicher', 'Sie hatten keinen König']],
              ['Wann erklärte Belgien seine Unabhängigkeit?', '1830', ['1839', '1815', '1848']],
              ['Wie war Luxemburg mit den Niederlanden verbunden?', 'In Personalunion mit dem König', ['Als Provinz', 'Gar nicht', 'Als Kolonie']],
              ['Welcher König ließ die Verfassung 1848 ausarbeiten?', 'Wilhelm II.', ['Wilhelm I.', 'Wilhelm III.', 'Louis Bonaparte']],
              ['Was löste die Verfassung von 1848 aus?', 'Die Revolutionen in Europa', ['Ein Krieg mit Belgien', 'Eine Flut', 'Napoleons Rückkehr']],
              ['Was sagte Wilhelm II. über sich?', 'Er sei in einer Nacht liberal geworden', ['Er sei ein absoluter König', 'Er wolle abdanken', 'Er sei Franzose']],
              ['Welcher politischen Richtung gehörte Thorbecke an?', 'Liberal', ['Konservativ', 'Sozialistisch', 'Monarchistisch']],
              ['Was bedeutete die Ministerverantwortlichkeit?', 'Die Regierung hängt vom Parlament ab', ['Der König regiert allein', 'Minister werden vererbt', 'Nichts']],
              ['Wie lange regierte Louis Bonaparte?', 'Von 1806 bis 1810', ['Von 1795 bis 1815', 'Nur einen Monat', 'Bis 1830']],
            ],
            schwer: [
              ['Warum konnten die Franzosen 1795 leicht einmarschieren?', 'Die Flüsse waren zugefroren', ['Die Niederländer luden sie ein', 'Es gab keine Armee', 'Sie kamen über das Meer']],
              ['Was blieb aus der Franzosenzeit dauerhaft?', 'Familiennamen, Standesamt und Code civil', ['Die französische Sprache', 'Der Kaiser', 'Die Batavische Republik']],
              ['Warum scheiterte das Vereinigte Königreich der Niederlande?', 'Konfessionelle und sprachliche Gegensätze zum Süden', ['Wegen einer Flut', 'Wegen Napoleon', 'Wegen der VOC']],
              ['Wie lange zögerte Wilhelm I. mit der Anerkennung Belgiens?', 'Neun Jahre', ['Einen Tag', 'Hundert Jahre', 'Ein Jahr']],
              ['Was ist der Kern der Verfassung von 1848?', 'Ministerverantwortlichkeit gegenüber dem Parlament', ['Absolute Königsmacht', 'Eine Republik', 'Ein Wahlrecht für alle']],
              ['Warum wurde Louis Bonaparte abgesetzt?', 'Er gehorchte Napoleons Befehlen nicht mehr', ['Er war zu streng', 'Er starb', 'Er floh nach England']],
              ['Was symbolisiert der Beiname „Kaufmannskönig“?', 'Wilhelms Förderung der Wirtschaft', ['Seine Herkunft aus einer Händlerfamilie', 'Seinen Reichtum aus Gold', 'Nichts']],
              ['Welche Rolle hatte Thorbecke?', 'Vater der Verfassung von 1848', ['König', 'Admiral', 'Maler']],
              ['Wie wurde aus der Republik eine Monarchie?', 'Über Napoleons Königreich und den Wiener Kongress', ['Durch eine Volksabstimmung 1795', 'Durch Erbe aus Spanien', 'Durch Kauf']],
              ['Welches Ereignis trennte Belgien endgültig?', 'Die Anerkennung 1839', ['Der Wiener Kongress', 'Die Verfassung 1848', 'Der Code civil']],
              ['Welcher Teil der Bevölkerung erhielt 1798 Rechte?', 'Juden', ['Frauen', 'Sklaven in den Kolonien', 'Kinder']],
              ['Wofür war das Vereinigte Königreich von 1815 gedacht?', 'Als Bollwerk gegen Frankreich', ['Als Kolonie Englands', 'Als Teil Preußens', 'Als Republik']],
              ['Wie lange bestand das Vereinigte Königreich von Nord und Süd?', 'Bis 1830', ['Bis 1890', 'Bis 1848', 'Bis heute']],
              ['Was wurde 1890 aus der Personalunion mit Luxemburg?', 'Sie endete', ['Sie wurde verstärkt', 'Luxemburg wurde Provinz', 'Nichts']],
              ['Welches Jahr ist mit dem Ende des Statthaltertums verbunden?', '1795', ['1815', '1848', '1672']],
              ['Was galt in der Batavischen Republik für Kirche und Staat?', 'Sie wurden getrennt', ['Sie wurden vereint', 'Die Kirche regierte', 'Der Staat verbot die Kirche']],
              ['Welche Folge hatte 1848 für den König?', 'Er verlor politische Macht an das Parlament', ['Er wurde mächtiger', 'Er wurde abgesetzt', 'Nichts']],
              ['Woher stammte die Dynastie Wilhelms I.?', 'Aus dem Haus Oranien', ['Aus dem Haus Bonaparte', 'Aus dem Haus Habsburg', 'Aus dem Haus Hohenzollern']],
              ['Wer war König von Holland vor 1815?', 'Louis Bonaparte', ['Wilhelm I.', 'Napoleon selbst als König von Holland', 'Wilhelm V.']],
              ['Wann wurde der Wiener Kongress für die Niederlande wichtig?', '1815', ['1795', '1830', '1848']],
            ],
          },
        },
        {
          id: 'kolonien-versaeulung',
          title: 'Kolonien, Säulen und Van Gogh',
          date: '1830–1939',
          text: [
            'Die wichtigste Kolonie war Niederländisch-Indien, das heutige Indonesien. Ab 1830 zwang das „Kultursystem“ javanische Bauern, einen Teil ihres Landes für Exportpflanzen wie Kaffee, Zucker und Indigo zu nutzen und an die Regierung abzuliefern. Die Gewinne finanzierten Eisenbahnen und Kanäle in den Niederlanden, während auf Java Hungersnöte herrschten. 1860 prangerte der Roman „Max Havelaar“ von Multatuli (Eduard Douwes Dekker) diese Ausbeutung an.',
            'Um 1900 eroberte die Armee in langen Kriegen den Rest des Archipels, etwa im Aceh-Krieg auf Sumatra (1873–1904), der Zehntausende Tote forderte. Gleichzeitig verkündete die Regierung eine „ethische Politik“ mit Schulen und Bewässerung. In Indonesien wuchs eine Unabhängigkeitsbewegung, deren Führer wie Sukarno inhaftiert wurden. Weitere Kolonien waren Surinam und die Karibikinseln wie Curaçao; die Sklaverei wurde dort erst 1863 abgeschafft.',
            'Die niederländische Gesellschaft teilte sich in „Säulen“ (Versäulung): Katholiken, Protestanten, Sozialisten und Liberale hatten jeweils eigene Parteien, Zeitungen, Schulen, Gewerkschaften, Sportvereine und Radiosender. Man lebte weitgehend innerhalb seiner Säule und heiratete selten außerhalb. Nur die Führungsschichten verhandelten miteinander. 1917 brachte die „Pazifikation“ die Gleichstellung konfessioneller Schulen und das allgemeine Männerwahlrecht, 1919 erhielten die Frauen das Wahlrecht.',
            'Im Ersten Weltkrieg blieben die Niederlande neutral; der deutsche Kaiser Wilhelm II. floh 1918 ins niederländische Exil nach Doorn. Nach einer verheerenden Sturmflut 1916 baute man den Afsluitdijk (Abschlussdeich), einen 32 Kilometer langen Damm, der 1932 die Zuiderzee vom Meer trennte und zum IJsselmeer machte. Daraus wurden neue Polder gewonnen; die Provinz Flevoland entstand später ganz aus dem Meer.',
            'Kunst und Wissenschaft blühten: Vincent van Gogh (1853–1890) malte leuchtende Bilder wie „Die Sonnenblumen“ und „Sternennacht“, verkaufte zu Lebzeiten aber kaum ein Bild. Piet Mondrian schuf abstrakte Werke aus Rechtecken in Grundfarben („De Stijl“). Physiker wie Hendrik Lorentz und Heike Kamerlingh Onnes, der die Supraleitung entdeckte, erhielten Nobelpreise.',
          ],
          quiz: {
            leicht: [
              ['Wie hieß die wichtigste Kolonie?', 'Niederländisch-Indien', ['Neuseeland', 'Kapkolonie', 'Neu-Amsterdam']],
              ['Wie heißt Niederländisch-Indien heute?', 'Indonesien', ['Indien', 'Malaysia', 'Philippinen']],
              ['Wie hieß das Zwangsanbausystem ab 1830?', 'Kultursystem', ['Plantagensystem', 'Säulensystem', 'Poldersystem']],
              ['Welche Pflanzen mussten Bauern anbauen?', 'Kaffee, Zucker und Indigo', ['Weizen und Roggen', 'Tulpen', 'Kartoffeln']],
              ['Welcher Roman prangerte die Ausbeutung an?', '„Max Havelaar“', ['„Das Tagebuch der Anne Frank“', '„Die Nachtwache“', '„Robinson Crusoe“']],
              ['Unter welchem Pseudonym schrieb Douwes Dekker?', 'Multatuli', ['Erasmus', 'Spinoza', 'Rembrandt']],
              ['Welcher lange Krieg fand auf Sumatra statt?', 'Der Aceh-Krieg', ['Der Java-Krieg', 'Der Burenkrieg', 'Der Opiumkrieg']],
              ['Welcher indonesische Unabhängigkeitsführer wurde inhaftiert?', 'Sukarno', ['Gandhi', 'Ho Chi Minh', 'Nehru']],
              ['Welche Kolonie lag in Südamerika?', 'Surinam', ['Brasilien', 'Venezuela', 'Chile']],
              ['Wann wurde die Sklaverei in den Kolonien abgeschafft?', '1863', ['1795', '1917', '1945']],
              ['Wie nennt man die Aufteilung der Gesellschaft?', 'Versäulung', ['Verdeichung', 'Verpolderung', 'Vereinigung']],
              ['Welche Säulen gab es?', 'Katholiken, Protestanten, Sozialisten, Liberale', ['Adel, Bürger, Bauern', 'Nord, Süd, Ost, West', 'Kaufleute und Seeleute']],
              ['Wann erhielten Frauen das Wahlrecht?', '1919', ['1917', '1848', '1945']],
              ['Waren die Niederlande im Ersten Weltkrieg neutral?', 'Ja', ['Nein, für Deutschland', 'Nein, für England', 'Nein, gegen Belgien']],
              ['Welcher Kaiser floh 1918 in die Niederlande?', 'Wilhelm II.', ['Franz Joseph', 'Nikolaus II.', 'Karl I.']],
              ['Wie heißt der Abschlussdeich?', 'Afsluitdijk', ['Deltawerk', 'Zuiderdijk', 'Oosterschelde']],
              ['Wann wurde der Abschlussdeich fertig?', '1932', ['1916', '1953', '1900']],
              ['Was wurde aus der Zuiderzee?', 'Das IJsselmeer', ['Die Nordsee', 'Der Rhein', 'Das Wattenmeer']],
              ['Wer malte „Die Sonnenblumen“?', 'Vincent van Gogh', ['Rembrandt', 'Mondrian', 'Vermeer']],
              ['Welcher Maler schuf abstrakte Bilder aus Rechtecken?', 'Piet Mondrian', ['Van Gogh', 'Escher', 'Frans Hals']],
            ],
            mittel: [
              ['Welche Insel war Zentrum des Kultursystems?', 'Java', ['Sumatra', 'Borneo', 'Bali']],
              ['Was finanzierten die Gewinne des Kultursystems?', 'Eisenbahnen und Kanäle in den Niederlanden', ['Schulen auf Java', 'Krankenhäuser in Indien', 'Kriege gegen England']],
              ['Was herrschte auf Java während des Kultursystems?', 'Hungersnöte', ['Wohlstand', 'Frieden und Überfluss', 'Krieg mit China']],
              ['Wann erschien „Max Havelaar“?', '1860', ['1830', '1900', '1917']],
              ['Wann dauerte der Aceh-Krieg?', '1873–1904', ['1830–1860', '1914–1918', '1945–1949']],
              ['Wie viele Tote forderte der Aceh-Krieg?', 'Zehntausende', ['Einige Dutzend', 'Keine', 'Millionen']],
              ['Wie hieß die neue Kolonialpolitik um 1900?', '„Ethische Politik“', ['„Kultursystem“', '„Versäulung“', '„Pazifikation“']],
              ['Was brachte die ethische Politik?', 'Schulen und Bewässerung', ['Kriege', 'Sklaverei', 'Steuersenkungen in Holland']],
              ['Welche Karibikinsel war niederländisch?', 'Curaçao', ['Jamaika', 'Kuba', 'Haiti']],
              ['Was hatte jede Säule?', 'Eigene Parteien, Zeitungen, Schulen und Vereine', ['Eigene Könige', 'Eigene Armeen', 'Eigene Währungen']],
              ['Wie oft heiratete man außerhalb seiner Säule?', 'Selten', ['Immer', 'Oft', 'Pflichtmäßig']],
              ['Wer verhandelte zwischen den Säulen?', 'Die Führungsschichten', ['Die Bauern', 'Die Kinder', 'Ausländer']],
              ['Wie heißt der Kompromiss von 1917?', 'Pazifikation', ['Versäulung', 'Ausgleich', 'Konkordat']],
              ['Was brachte die Pazifikation?', 'Gleichstellung konfessioneller Schulen und Männerwahlrecht', ['Abschaffung der Monarchie', 'Unabhängigkeit Indonesiens', 'Ein Kaiserreich']],
              ['Wo lebte Kaiser Wilhelm II. im Exil?', 'In Doorn', ['In Amsterdam', 'In Den Haag', 'In Utrecht']],
              ['Was löste den Bau des Abschlussdeichs aus?', 'Eine verheerende Sturmflut 1916', ['Ein Krieg', 'Ein Erdbeben', 'Eine Dürre']],
              ['Wie lang ist der Afsluitdijk?', '32 Kilometer', ['3 Kilometer', '320 Kilometer', '12 Kilometer']],
              ['Welche Provinz entstand ganz aus dem Meer?', 'Flevoland', ['Friesland', 'Zeeland', 'Drenthe']],
              ['Wann lebte Van Gogh?', '1853–1890', ['1606–1669', '1872–1944', '1632–1675']],
              ['Wie hieß Mondrians Kunstrichtung?', 'De Stijl', ['Impressionismus', 'Kubismus', 'Barock']],
            ],
            schwer: [
              ['Was ist das Problem des Kultursystems?', 'Reichtum für die Niederlande, Hunger für Java', ['Es brachte Java Wohlstand', 'Es war freiwillig', 'Es gab keine Folgen']],
              ['Welche Rolle spielte „Max Havelaar“?', 'Es machte koloniale Ausbeutung öffentlich', ['Es lobte das Kultursystem', 'Es war ein Reiseführer', 'Es war ein Kinderbuch']],
              ['Was war die Versäulung im Kern?', 'Leben in getrennten weltanschaulichen Milieus', ['Bau von Säulen', 'Eine Steuer', 'Eine Armee']],
              ['Was gewann man durch den Abschlussdeich?', 'Neues Land (Polder)', ['Neue Kolonien', 'Neue Berge', 'Ölquellen']],
              ['Was entdeckte Kamerlingh Onnes?', 'Die Supraleitung', ['Die Röntgenstrahlen', 'Die Radioaktivität', 'Das Penicillin']],
              ['Was ist am Leben Van Goghs tragisch?', 'Er verkaufte zu Lebzeiten kaum ein Bild', ['Er wurde reich', 'Er malte nie', 'Er war König']],
              ['Welches Bild malte Van Gogh außer den Sonnenblumen?', '„Sternennacht“', ['„Die Nachtwache“', '„Komposition mit Rot, Gelb und Blau“', '„Die Milchmagd“']],
              ['Welche Farben nutzte Mondrian?', 'Grundfarben', ['Nur Grau', 'Pastellfarben', 'Gold']],
              ['Welcher Physiker erhielt den Nobelpreis neben Kamerlingh Onnes?', 'Hendrik Lorentz', ['Albert Einstein', 'Niels Bohr', 'Max Planck']],
              ['Wo galt die Sklaverei bis 1863?', 'In Surinam und auf den Karibikinseln', ['In Amsterdam', 'In Friesland', 'In Belgien']],
              ['Was beweist der Aceh-Krieg?', 'Gewaltsame Kolonialeroberung um 1900', ['Friedliche Kolonisation', 'Indonesiens Unabhängigkeit', 'Nichts']],
              ['Wie wirkte die Versäulung auf die Politik?', 'Kompromisse zwischen Eliten der Säulen', ['Diktatur einer Säule', 'Keine Parteien', 'Monarchie ohne Parlament']],
              ['Welches Gewässer trennte der Abschlussdeich vom Meer?', 'Die Zuiderzee', ['Den Rhein', 'Die Oosterschelde', 'Die Maas']],
              ['Welches Jahr brachte das Männerwahlrecht für alle?', '1917', ['1919', '1848', '1900']],
              ['Welche Funktion hatte Doorn für Wilhelm II.?', 'Exilort', ['Kriegshauptquartier', 'Geburtsort', 'Krönungsort']],
              ['Woher kam die Gewinnquelle für niederländische Eisenbahnen?', 'Aus dem Kultursystem auf Java', ['Aus Japan', 'Aus Deutschland', 'Aus Steuern auf Tulpen']],
              ['Was ist Flevoland?', 'Eine aus dem Meer gewonnene Provinz', ['Eine Insel in der Karibik', 'Eine Stadt', 'Ein Fluss']],
              ['Was war die Pazifikation 1917?', 'Ein Kompromiss über Schulen und Wahlrecht', ['Ein Friedensvertrag', 'Eine Kriegserklärung', 'Ein Deichbau']],
              ['Welcher Schriftsteller hieß eigentlich Eduard Douwes Dekker?', 'Multatuli', ['Max Havelaar', 'Thorbecke', 'Lorentz']],
              ['Wann wurden Frauen wahlberechtigt im Verhältnis zu Männern?', 'Zwei Jahre später', ['Gleichzeitig', 'Zehn Jahre früher', '50 Jahre später']],
            ],
          },
        },
      ],
    },
  ],
};
