import type { Epoch } from '../types';

export const E2: Epoch = {
  id: 'adelsrepublik',
  name: 'Die Adelsrepublik',
  period: '1569–1764',
  events: [
    {
      id: 'adelsrepublik',
      title: 'Polen-Litauen: Republik der beiden Völker',
      date: '1569–1764',
      text: [
        'Polen-Litauen war einer der größten Staaten Europas, in dem der Adel seinen König wählte. Die „Adelsfreiheit“ war einzigartig, lähmte den Staat aber zunehmend. Kriege mit Schweden, Russland und Kosaken schwächten das Land, obwohl König Sobieski 1683 Wien rettete.',
      ],
      subtopics: [
        {
          id: 'lublin-wahlkoenige',
          title: 'Union von Lublin und Wahlkönigtum',
          date: '1569–1648',
          text: [
            'In der Union von Lublin 1569 wurden das Königreich Polen und das Großfürstentum Litauen zu einem Staat, der „Rzeczpospolita Obojga Narodów“ (Republik der beiden Völker), mit gemeinsamem König und Reichstag (Sejm), aber eigenen Heeren und Ämtern. Mit rund einer Million Quadratkilometern war sie einer der größten Staaten Europas und reichte von der Ostsee bis in die heutige Ukraine.',
            'Nach dem Tod des letzten Jagiellonen Sigismund II. August 1572 wurde der König frei gewählt. Jeder Adlige konnte persönlich an der Wahl auf einem Feld bei Warschau teilnehmen – manchmal kamen über 10.000 Männer. Der erste gewählte König, der Franzose Heinrich von Valois (gewählt 1573), musste die „Henrich-Artikel“ beschwören, die die Rechte des Adels festschrieben. Nach wenigen Monaten floh er heimlich nach Frankreich, um dort König zu werden.',
            'Die Konföderation von Warschau 1573 garantierte allen Adligen Religionsfreiheit – eine der frühesten Toleranzgarantien Europas. Der Adel, die Szlachta, umfasste rund acht bis zehn Prozent der Bevölkerung, deutlich mehr als in anderen Ländern. Vom einfachen Kleinadligen bis zum mächtigen Magnaten galten alle als gleich („Bruder Adliger“). Die Bauern dagegen waren als Leibeigene an das Land gebunden.',
            'Der Adel sah sich als Nachfahre der antiken Sarmaten („Sarmatismus“), trug orientalisch anmutende Gewänder (Żupan, Kontusz) und Säbel. Unter König Sigismund III. Wasa aus Schweden wurde 1596 die Hauptstadt von Krakau nach Warschau verlegt, das zentraler lag. Die Sigismundsäule in Warschau erinnert an ihn. Durch seinen Anspruch auf den schwedischen Thron begannen lange Kriege mit Schweden.',
            'Ab 1652 konnte ein einziger Abgeordneter mit dem „Liberum veto“ („Ich erlaube es nicht“) einen ganzen Reichstag sprengen und alle Beschlüsse ungültig machen. Was als Schutz der Freiheit gedacht war, machte den Staat zunehmend handlungsunfähig; ausländische Mächte bestachen Abgeordnete, um Reformen zu verhindern. In der Zeit der „Wirren“ (Smuta) besetzten polnische Truppen 1610 sogar kurz Moskau.',
          ],
          quiz: {
            leicht: [
              ['Welche Union verband Polen und Litauen 1569?', 'Die Union von Lublin', ['Die Union von Krewo', 'Die Union von Brest', 'Die Kalmarer Union']],
              ['Wie hieß der gemeinsame Staat?', 'Republik der beiden Völker', ['Königreich Groß-Polen', 'Ostreich', 'Kaiserreich Polen']],
              ['Wie heißt der polnische Reichstag?', 'Sejm', ['Duma', 'Rada', 'Tag']],
              ['Wie groß war Polen-Litauen etwa?', 'Rund eine Million Quadratkilometer', ['100.000 Quadratkilometer', '10 Millionen Quadratkilometer', '10.000 Quadratkilometer']],
              ['Wer war der letzte Jagiellone?', 'Sigismund II. August', ['Sigismund III. Wasa', 'Stephan Báthory', 'Jan Sobieski']],
              ['Wie wurde der König ab 1572 bestimmt?', 'Durch freie Wahl des Adels', ['Durch Erbe', 'Durch den Papst', 'Durch Los']],
              ['Wo fand die Königswahl statt?', 'Auf einem Feld bei Warschau', ['Im Wawel', 'In Gnesen', 'In Danzig']],
              ['Wer war der erste gewählte König?', 'Heinrich von Valois', ['Stephan Báthory', 'Sigismund III.', 'August der Starke']],
              ['Woher stammte Heinrich von Valois?', 'Aus Frankreich', ['Aus Schweden', 'Aus Ungarn', 'Aus Sachsen']],
              ['Was tat Heinrich nach wenigen Monaten?', 'Er floh heimlich nach Frankreich', ['Er eroberte Moskau', 'Er wurde Papst', 'Er starb']],
              ['Was garantierte die Konföderation von Warschau 1573?', 'Religionsfreiheit für Adlige', ['Freiheit für Bauern', 'Die Abschaffung des Adels', 'Ein Bündnis mit Frankreich']],
              ['Wie heißt der polnische Adel?', 'Szlachta', ['Junker', 'Bojaren', 'Samurai']],
              ['Welchen Anteil der Bevölkerung stellte der Adel etwa?', 'Acht bis zehn Prozent', ['Ein Prozent', 'Die Hälfte', 'Neunzig Prozent']],
              ['Was waren die Bauern?', 'Leibeigene', ['Freie Bürger', 'Adlige', 'Soldaten']],
              ['Als wessen Nachfahren sah sich der Adel?', 'Als Nachfahren der Sarmaten', ['Der Römer', 'Der Wikinger', 'Der Griechen']],
              ['Welcher König verlegte die Hauptstadt nach Warschau?', 'Sigismund III. Wasa', ['Sigismund I.', 'Kasimir der Große', 'Jan Sobieski']],
              ['Wann wurde Warschau Hauptstadt?', '1596', ['1569', '1652', '1683']],
              ['Woher stammte Sigismund III. Wasa?', 'Aus Schweden', ['Aus Frankreich', 'Aus Litauen', 'Aus Sachsen']],
              ['Was bedeutet „Liberum veto“?', '„Ich erlaube es nicht“', ['„Ich stimme zu“', '„Freiheit für alle“', '„Gott will es“']],
              ['Welche Stadt besetzten polnische Truppen 1610 kurz?', 'Moskau', ['Stockholm', 'Berlin', 'Wien']],
            ],
            mittel: [
              ['Was blieb in der Union getrennt?', 'Heere und Ämter', ['König und Sejm', 'Die Hauptstadt', 'Die Münze für den König']],
              ['Bis wohin reichte Polen-Litauen?', 'Von der Ostsee bis in die heutige Ukraine', ['Von der Nordsee bis zur Adria', 'Von Berlin bis Paris', 'Nur bis Krakau']],
              ['Wann starb Sigismund II. August?', '1572', ['1569', '1596', '1548']],
              ['Wie viele Männer kamen manchmal zur Königswahl?', 'Über 10.000', ['Rund 100', 'Rund 1000', 'Über eine Million']],
              ['Was mussten gewählte Könige beschwören?', 'Die Henrich-Artikel', ['Das Liberum veto', 'Das Statut von Kalisch', 'Die Pragmatische Sanktion']],
              ['Was legten die Henrich-Artikel fest?', 'Die Rechte des Adels', ['Die Rechte der Bauern', 'Das Kirchenrecht', 'Die Steuern der Juden']],
              ['Warum floh Heinrich nach Frankreich?', 'Um dort König zu werden', ['Wegen einer Seuche', 'Weil er abgesetzt wurde', 'Wegen eines Krieges']],
              ['Als was gilt die Konföderation von Warschau?', 'Eine der frühesten Toleranzgarantien Europas', ['Ein Kriegsbündnis', 'Ein Handelsvertrag', 'Eine Kirchenordnung']],
              ['Wie nannten sich Adlige untereinander?', '„Bruder Adliger“', ['„Herr Graf“', '„Euer Gnaden“', '„Bürger“']],
              ['Wie hießen die mächtigsten Adligen?', 'Magnaten', ['Kleinadlige', 'Patrizier', 'Ritter']],
              ['Wie nennt man die Ideologie des Adels?', 'Sarmatismus', ['Humanismus', 'Absolutismus', 'Pietismus']],
              ['Welche Gewänder trug der Adel?', 'Żupan und Kontusz', ['Toga und Tunika', 'Kilt und Plaid', 'Kimono']],
              ['Welche Waffe trug der Adel?', 'Den Säbel', ['Das Langschwert', 'Die Armbrust', 'Den Bogen']],
              ['Warum wurde Warschau Hauptstadt?', 'Es lag zentraler', ['Es war größer als alle', 'Es lag am Meer', 'Der Papst wollte es']],
              ['Welches Denkmal erinnert an Sigismund III.?', 'Die Sigismundsäule', ['Die Sigismundglocke', 'Der Wawel', 'Das Schloss Wilanów']],
              ['Was begann wegen Sigismunds schwedischem Thronanspruch?', 'Lange Kriege mit Schweden', ['Frieden mit Schweden', 'Eine Union mit Schweden', 'Nichts']],
              ['Ab wann gab es das Liberum veto praktisch?', 'Ab 1652', ['Ab 1569', 'Ab 1573', 'Ab 1791']],
              ['Was konnte ein Abgeordneter mit dem Liberum veto?', 'Einen ganzen Reichstag sprengen', ['Einen König wählen', 'Krieg erklären', 'Steuern senken']],
              ['Wie nutzten ausländische Mächte das Liberum veto?', 'Sie bestachen Abgeordnete', ['Sie verboten es', 'Sie wussten nichts davon', 'Sie stimmten mit']],
              ['Wie heißt die Zeit der Wirren in Russland?', 'Smuta', ['Potop', 'Sejm', 'Rokosz']],
            ],
            schwer: [
              ['Warum lähmte das Liberum veto den Staat?', 'Eine Stimme konnte alle Beschlüsse verhindern', ['Es gab zu viele Könige', 'Der Papst entschied alles', 'Es gab keinen Sejm']],
              ['Was war an Polens Adel besonders?', 'Er war ungewöhnlich zahlreich und formal gleich', ['Er war sehr klein', 'Er war besitzlos', 'Er wählte keinen König']],
              ['Was unterschied Polen-Litauen von absoluten Monarchien?', 'Der Adel wählte den König und beschränkte ihn', ['Der König herrschte unbeschränkt', 'Es gab keinen Adel', 'Die Bauern regierten']],
              ['Für wen galt die Religionsfreiheit von 1573?', 'Für Adlige', ['Für alle Bauern', 'Nur für Katholiken', 'Nur für Juden']],
              ['Was zeigt Heinrichs Flucht?', 'Die Schwäche des Wahlkönigtums', ['Polens Stärke', 'Frankreichs Schwäche', 'Nichts']],
              ['Welcher Teil der Bevölkerung hatte kaum Rechte?', 'Die leibeigenen Bauern', ['Der Kleinadel', 'Die Magnaten', 'Die Geistlichen']],
              ['Welche Dynastie stellte nach den Jagiellonen Könige aus Schweden?', 'Die Wasa', ['Die Habsburger', 'Die Romanows', 'Die Hohenzollern']],
              ['Was war der Sejm?', 'Der Reichstag des Adels', ['Ein Gericht', 'Eine Armee', 'Eine Kirche']],
              ['Woher stammt die Kleidung der Szlachta?', 'Sie war orientalisch beeinflusst', ['Aus Frankreich', 'Aus England', 'Aus Rom']],
              ['Was war ursprünglich der Zweck des Liberum veto?', 'Schutz der Adelsfreiheit', ['Schwächung des Adels', 'Stärkung des Königs', 'Hilfe für Bauern']],
              ['Welches Jahr ist mit der Verlegung der Hauptstadt verbunden?', '1596', ['1569', '1610', '1652']],
              ['Was bedeutet „Rzeczpospolita“?', 'Republik', ['Königreich', 'Kaiserreich', 'Fürstentum']],
              ['Welches Ereignis zeigt Polens Stärke um 1610?', 'Die kurze Besetzung Moskaus', ['Die Eroberung Berlins', 'Die Eroberung Stockholms', 'Ein Sieg über Frankreich']],
              ['Wann wurde der erste König gewählt?', '1573', ['1569', '1596', '1652']],
              ['Wer stand in der Szlachta ganz oben?', 'Die Magnaten', ['Die Kleinadligen', 'Die Bauern', 'Die Bürger']],
              ['Wie nennt man die Freiheiten des Adels zusammen?', 'Adelsfreiheit (Goldene Freiheit)', ['Bürgerrechte', 'Bauernfreiheit', 'Königsrecht']],
              ['Was machte Polen-Litauen attraktiv für Verfolgte?', 'Religiöse Toleranz', ['Reichtum an Gold', 'Ein mildes Klima', 'Kolonien']],
              ['Wer konnte an der Königswahl teilnehmen?', 'Jeder Adlige persönlich', ['Nur Magnaten', 'Alle Bürger', 'Nur Bischöfe']],
              ['Wo liegt das Wahlfeld?', 'Bei Warschau', ['Bei Krakau', 'Bei Wilna', 'Bei Danzig']],
              ['Welches Land wurde durch die Union eng mit Polen verbunden?', 'Litauen', ['Schweden', 'Ungarn', 'Böhmen']],
            ],
          },
        },
        {
          id: 'sintflut-sobieski',
          title: 'Kosaken, „Sintflut“ und Sobieski',
          date: '1648–1764',
          text: [
            '1648 erhoben sich die ukrainischen Kosaken unter Bohdan Chmelnyzkyj gegen den polnischen Adel. Die Kosaken waren freie Krieger am Dnjepr. Der Aufstand war blutig; Zehntausende Juden und Polen wurden getötet. 1654 unterstellte sich Chmelnyzkyj dem russischen Zaren – der Beginn des russischen Einflusses in der Ukraine.',
            '1655 fiel Schweden in Polen ein und eroberte in kurzer Zeit Warschau und Krakau. Diese verheerende Zeit heißt „Sintflut“ (Potop). Ein Wendepunkt war die erfolgreiche Verteidigung des Klosters Jasna Góra in Tschenstochau mit der verehrten „Schwarzen Madonna“. König Johann II. Kasimir weihte Polen danach der Muttergottes als „Königin Polens“. Henryk Sienkiewicz schrieb später darüber den Roman „Die Sintflut“. Polen verlor ein Drittel seiner Bevölkerung und musste 1657 die Souveränität Preußens anerkennen.',
            'Johann III. Sobieski, ein erfolgreicher Feldherr gegen Türken und Tataren, wurde 1674 König. Am 12. September 1683 führte er das Entsatzheer am Kahlenberg gegen die Osmanen, die Wien belagerten. Den Angriff seiner gefürchteten „Flügelhusaren“ – Reiter mit Flügeln aus Federn am Rücken – gilt als eine der größten Kavallerieattacken der Geschichte. Er schrieb dem Papst: „Venimus, vidimus, Deus vicit“ (Wir kamen, sahen, Gott siegte). Sein Sommerpalast Wilanów steht in Warschau.',
            '1697 wurde der sächsische Kurfürst August der Starke König von Polen; er trat dafür zum Katholizismus über. Im Großen Nordischen Krieg (1700–1721) wurde Polen zum Schlachtfeld zwischen Schweden und Russland. Danach mischte sich Russland immer stärker in die polnische Politik ein; der Zar ließ Truppen im Land stehen. Unter den sächsischen Königen verfiel der Staat weiter; man spottete: „Unter dem Sachsenkönig iss, trink und lockere den Gürtel.“',
            'Trotz des Niedergangs gab es Aufbrüche: Stanisław Konarski gründete 1740 eine moderne Adelsschule (Collegium Nobilium) und kämpfte gegen das Liberum veto. Die Brüder Załuski eröffneten 1747 in Warschau eine der ersten öffentlichen Bibliotheken Europas. 1764 wurde mit Unterstützung der russischen Zarin Katharina der Großen ihr früherer Liebhaber Stanisław August Poniatowski zum König gewählt – der letzte König Polens.',
          ],
          quiz: {
            leicht: [
              ['Wer erhob sich 1648 gegen den polnischen Adel?', 'Die ukrainischen Kosaken', ['Die Schweden', 'Die Tataren', 'Die Preußen']],
              ['Wer führte den Kosakenaufstand?', 'Bohdan Chmelnyzkyj', ['Stenka Rasin', 'Jan Sobieski', 'Tadeusz Kościuszko']],
              ['An welchem Fluss lebten die Kosaken?', 'Am Dnjepr', ['An der Weichsel', 'An der Oder', 'An der Wolga']],
              ['Wem unterstellte sich Chmelnyzkyj 1654?', 'Dem russischen Zaren', ['Dem Sultan', 'Dem schwedischen König', 'Dem Papst']],
              ['Welches Land fiel 1655 in Polen ein?', 'Schweden', ['Russland', 'Preußen', 'Österreich']],
              ['Wie nennt man die Zeit ab 1655?', 'Sintflut (Potop)', ['Goldenes Zeitalter', 'Wirren', 'Teilungen']],
              ['Welches Kloster wurde erfolgreich verteidigt?', 'Jasna Góra in Tschenstochau', ['Die Marienburg', 'Der Wawel', 'Kloster Oliva']],
              ['Welches Bild wird in Tschenstochau verehrt?', 'Die Schwarze Madonna', ['Die Sixtinische Madonna', 'Das Turiner Grabtuch', 'Die Mona Lisa']],
              ['Wer schrieb den Roman „Die Sintflut“?', 'Henryk Sienkiewicz', ['Adam Mickiewicz', 'Bolesław Prus', 'Joseph Conrad']],
              ['Welcher Anteil der Bevölkerung ging in der Sintflut verloren?', 'Ein Drittel', ['Ein Zehntel', 'Die Hälfte', 'Fast alle']],
              ['Wann wurde Jan Sobieski König?', '1674', ['1683', '1655', '1697']],
              ['Wo führte Sobieski 1683 das Entsatzheer?', 'Am Kahlenberg bei Wien', ['Bei Tschenstochau', 'Bei Grunwald', 'Bei Warschau']],
              ['Gegen wen kämpfte Sobieski bei Wien?', 'Gegen die Osmanen', ['Gegen die Schweden', 'Gegen die Russen', 'Gegen die Franzosen']],
              ['Wie hießen Sobieskis Reiter?', 'Flügelhusaren', ['Kosaken', 'Ulanen', 'Dragoner']],
              ['Was trugen die Flügelhusaren am Rücken?', 'Flügel aus Federn', ['Fahnen', 'Schilde', 'Körbe']],
              ['Was schrieb Sobieski an den Papst?', '„Wir kamen, sahen, Gott siegte“', ['„Ich kam, sah und siegte“', '„Gott schütze Polen“', '„Wien ist frei“']],
              ['Wie heißt Sobieskis Palast in Warschau?', 'Wilanów', ['Łazienki', 'Wawel', 'Belweder']],
              ['Welcher Sachse wurde 1697 König von Polen?', 'August der Starke', ['Friedrich der Große', 'Stanisław Leszczyński', 'Moritz von Sachsen']],
              ['Wer wurde 1764 König?', 'Stanisław August Poniatowski', ['August der Starke', 'Jan Sobieski', 'Kościuszko']],
              ['Mit Hilfe welcher Zarin wurde er König?', 'Katharina der Großen', ['Elisabeth', 'Anna', 'Maria Theresia']],
            ],
            mittel: [
              ['Was waren die Kosaken?', 'Freie Krieger am Dnjepr', ['Polnische Adlige', 'Schwedische Söldner', 'Tatarische Händler']],
              ['Wer wurde im Kosakenaufstand getötet?', 'Zehntausende Juden und Polen', ['Nur Soldaten', 'Niemand', 'Nur Kosaken']],
              ['Was begann 1654?', 'Russischer Einfluss in der Ukraine', ['Die Sintflut', 'Die Teilungen', 'Die Union mit Litauen']],
              ['Welche Städte eroberten die Schweden 1655?', 'Warschau und Krakau', ['Danzig und Thorn', 'Wilna und Lemberg', 'Posen und Breslau']],
              ['Was war Jasna Góra für die Sintflut?', 'Ein Wendepunkt', ['Der Beginn', 'Ein Hafen', 'Ein schwedisches Lager']],
              ['Welcher König weihte Polen der Muttergottes?', 'Johann II. Kasimir', ['Sigismund III.', 'Jan Sobieski', 'August der Starke']],
              ['Als was wurde Maria verehrt?', 'Als Königin Polens', ['Als Schutzheilige Schwedens', 'Als Kaiserin', 'Als Feldherrin']],
              ['Wessen Souveränität musste Polen 1657 anerkennen?', 'Preußens', ['Schwedens', 'Russlands', 'Litauens']],
              ['Gegen wen war Sobieski vor 1674 erfolgreich?', 'Gegen Türken und Tataren', ['Gegen Schweden', 'Gegen Frankreich', 'Gegen Russland']],
              ['Wann war der Entsatz von Wien?', '12. September 1683', ['11. November 1683', '15. Juli 1410', '1. September 1683']],
              ['Als was gilt der Angriff der Flügelhusaren?', 'Eine der größten Kavallerieattacken der Geschichte', ['Eine kleine Patrouille', 'Eine Seeschlacht', 'Eine Niederlage']],
              ['Was tat August der Starke für die Krone?', 'Er trat zum Katholizismus über', ['Er wurde Protestant', 'Er zahlte dem Papst', 'Er heiratete eine Polin']],
              ['Wann war der Große Nordische Krieg?', '1700–1721', ['1655–1660', '1618–1648', '1756–1763']],
              ['Zwischen wem wurde Polen zum Schlachtfeld?', 'Zwischen Schweden und Russland', ['Zwischen Frankreich und England', 'Zwischen Österreich und Preußen', 'Zwischen Türken und Tataren']],
              ['Was tat Russland nach 1721?', 'Es mischte sich stärker in polnische Politik ein', ['Es zog sich zurück', 'Es wurde Polens Teil', 'Es kämpfte gegen Schweden in Polen weiter']],
              ['Was sagte man spöttisch über die Sachsenzeit?', '„Iss, trink und lockere den Gürtel“', ['„Bete und arbeite“', '„Alles für Polen“', '„Gott mit uns“']],
              ['Welche Schule gründete Konarski 1740?', 'Das Collegium Nobilium', ['Die Krakauer Akademie', 'Die Universität Warschau', 'Das Jesuitenkolleg']],
              ['Wogegen kämpfte Konarski?', 'Gegen das Liberum veto', ['Gegen die Schulen', 'Gegen den König', 'Gegen Sachsen']],
              ['Was eröffneten die Brüder Załuski 1747?', 'Eine der ersten öffentlichen Bibliotheken Europas', ['Ein Theater', 'Eine Bank', 'Ein Krankenhaus']],
              ['Welche Rolle spielte Poniatowski für Polen?', 'Letzter König Polens', ['Erster König', 'Feldherr bei Wien', 'Sachsenkönig']],
            ],
            schwer: [
              ['Was hatte Poniatowski mit Katharina verbunden?', 'Er war ihr früherer Liebhaber', ['Er war ihr Sohn', 'Er war ihr Bruder', 'Er war ihr General']],
              ['Was zeigt die Wahl 1764?', 'Russlands starken Einfluss auf Polen', ['Polens Unabhängigkeit', 'Schwedens Macht', 'Frankreichs Einfluss']],
              ['Welches Ereignis machte Tschenstochau zum Nationalheiligtum?', 'Die Verteidigung gegen die Schweden', ['Die Taufe 966', 'Die Union von Lublin', 'Der Sieg bei Wien']],
              ['Welche Folge hatte der Kosakenaufstand langfristig?', 'Russland gewann Einfluss in der Ukraine', ['Polen eroberte Moskau', 'Die Kosaken wurden Polen', 'Nichts']],
              ['Was verlor Polen 1657?', 'Die Lehnshoheit über Preußen', ['Danzig', 'Krakau', 'Litauen']],
              ['Woran erinnert Sobieskis Brief an Caesar?', 'An „Veni, vidi, vici“', ['An das Vaterunser', 'An die Bibel', 'An Homer']],
              ['Welche Rolle spielte Sobieski für Europa?', 'Retter Wiens vor den Osmanen', ['Eroberer Wiens', 'Verbündeter der Osmanen', 'Keine']],
              ['Warum verfiel der Staat unter den Sachsenkönigen?', 'Schwache Regierung und fremder Einfluss', ['Zu viele Reformen', 'Eine Revolution', 'Zu viel Geld']],
              ['Welche Neuerungen gab es trotz Niedergang?', 'Moderne Schule und öffentliche Bibliothek', ['Eisenbahnen', 'Fabriken', 'Kolonien']],
              ['Welcher Roman behandelt die schwedische Invasion?', '„Die Sintflut“', ['„Quo vadis“', '„Pan Tadeusz“', '„Die Kreuzritter“']],
              ['Was ist Jasna Góra?', 'Ein Kloster in Tschenstochau', ['Ein Königsschloss', 'Eine Festung in Danzig', 'Ein Berg bei Krakau']],
              ['Wann unterstellte sich Chmelnyzkyj Russland?', '1654', ['1648', '1655', '1667']],
              ['Wann begann die Sintflut?', '1655', ['1648', '1683', '1700']],
              ['Was waren die Flügelhusaren?', 'Schwere Reiterei Polens', ['Fußsoldaten', 'Matrosen', 'Kanoniere']],
              ['Welches Land ließ nach 1721 Truppen in Polen stehen?', 'Russland', ['Schweden', 'Frankreich', 'England']],
              ['Woher kam August der Starke?', 'Aus Sachsen', ['Aus Bayern', 'Aus Schweden', 'Aus Frankreich']],
              ['Welche Haltung hatte Konarski zur Adelsfreiheit?', 'Er wollte Missbrauch wie das Liberum veto abschaffen', ['Er wollte den Adel abschaffen', 'Er unterstützte das Veto', 'Er war Russe']],
              ['Was zeigt der Verlust eines Drittels der Bevölkerung?', 'Die Verheerung durch die Kriege', ['Eine Auswanderung nach Amerika', 'Eine Volkszählung', 'Nichts']],
              ['Wofür steht Wilanów?', 'Sobieskis Sommerresidenz', ['Den Sitz des Sejm', 'Eine Kosakenburg', 'Ein Kloster']],
              ['Welche Zarin prägte Polens Ende im 18. Jahrhundert?', 'Katharina die Große', ['Elisabeth', 'Anna', 'Maria']],
            ],
          },
        },
      ],
    },
  ],
};
