import type { HistEvent } from '../types';

export const FIRST_FLEET: HistEvent = {
  id: 'first-fleet',
  title: 'Die Sträflingskolonie',
  date: '1788–1850',
  text: [
    '1788 gründeten die Briten mit der „First Fleet“ in Sydney eine Sträflingskolonie. In den folgenden 80 Jahren kamen rund 162.000 Sträflinge. Die Kolonie breitete sich über den ganzen Kontinent aus – auf Kosten der Aborigines, die Land, Leben und Lebensweise verloren.',
  ],
  subtopics: [
    {
      id: 'first-fleet',
      title: 'Die First Fleet und die Anfänge von Sydney',
      date: '1787–1810',
      text: [
        'Im Mai 1787 verließen elf Schiffe unter Kapitän Arthur Phillip England: die „First Fleet“. An Bord waren rund 1.400 Menschen, davon etwa 750 Sträflinge – Männer, Frauen und sogar Kinder, oft wegen kleiner Diebstähle verurteilt. Nach über acht Monaten und rund 24.000 Kilometern erreichten sie im Januar 1788 die Botany Bay.',
        'Phillip fand die Botany Bay ungeeignet und zog weiter nach Norden in einen großen Naturhafen, Port Jackson. Am 26. Januar 1788 hissten die Briten in der Sydney Cove die britische Flagge. Dieser Tag ist heute „Australia Day“; viele Aborigines nennen ihn dagegen „Invasion Day“ oder „Survival Day“. Die Siedlung wurde nach dem britischen Innenminister Lord Sydney benannt.',
        'Die ersten Jahre waren hart: Die Böden waren schlecht, Saatgut und Vieh gingen ein, und die Kolonie stand kurz vor dem Verhungern, bis 1790 die Zweite Flotte Vorräte brachte – mit vielen halb toten Sträflingen an Bord. Phillip ließ das Land der Eora besetzen. 1789 brach eine Pockenepidemie aus, die einen großen Teil der Aborigines um Sydney tötete.',
        'Phillip versuchte, Kontakt zu den Aborigines aufzunehmen, und ließ Männer entführen, um sie als Vermittler zu gewinnen. Einer von ihnen, Bennelong, wurde Vermittler zwischen den Kulturen und reiste 1792 sogar mit Phillip nach England. Der Krieger Pemulwuy dagegen führte über zehn Jahre Widerstand gegen die Siedler, bis er 1802 erschossen wurde.',
        'Bald dominierten Offiziere des „New South Wales Corps“ die Kolonie und handelten mit Rum, das als Zahlungsmittel diente („Rum Corps“). Als Gouverneur William Bligh – berühmt durch die Meuterei auf der „Bounty“ – dagegen vorging, setzten sie ihn 1808 in der „Rum-Rebellion“ ab, dem einzigen Militärputsch der australischen Geschichte.',
      ],
      quiz: {
        leicht: [
          ['Wie heißt die erste Flotte nach Australien?', 'First Fleet', ['Royal Navy', 'Armada', 'Mayflower']],
          ['Wer führte die First Fleet?', 'Arthur Phillip', ['James Cook', 'William Bligh', 'Lachlan Macquarie']],
          ['Wann verließ die First Fleet England?', '1787', ['1770', '1788', '1801']],
          ['Wie viele Schiffe hatte die First Fleet?', 'Elf', ['Drei', 'Fünfzig', 'Eines']],
          ['Wer war vor allem an Bord?', 'Sträflinge', ['Goldsucher', 'Missionare', 'Kaufleute']],
          ['Weswegen waren viele Sträflinge verurteilt?', 'Wegen kleiner Diebstähle', ['Wegen Mordes', 'Wegen Hochverrats', 'Wegen Piraterie']],
          ['Wie lange dauerte die Reise etwa?', 'Über acht Monate', ['Zwei Wochen', 'Drei Jahre', 'Einen Monat']],
          ['Wann kamen die Schiffe an?', 'Im Januar 1788', ['Im Mai 1787', 'Im April 1770', 'Im Januar 1901']],
          ['Wohin zog Phillip von der Botany Bay?', 'Nach Port Jackson', ['Nach Perth', 'Nach Hobart', 'Nach Melbourne']],
          ['Welcher Tag ist Australia Day?', 'Der 26. Januar', ['Der 25. April', 'Der 1. Januar', 'Der 4. Juli']],
          ['Wie nennen viele Aborigines den 26. Januar?', 'Invasion Day', ['Freedom Day', 'Discovery Day', 'Cook Day']],
          ['Nach wem wurde Sydney benannt?', 'Nach Lord Sydney', ['Nach einem Aborigine', 'Nach Sydney Cook', 'Nach einer Stadt in England']],
          ['Wie waren die ersten Jahre?', 'Hart, fast verhungerte die Kolonie', ['Sehr reich', 'Ohne Probleme', 'Voller Gold']],
          ['Welche Krankheit tötete 1789 viele Aborigines?', 'Die Pocken', ['Die Pest', 'Die Grippe', 'Die Cholera']],
          ['Welches Volk lebte um Sydney?', 'Die Eora', ['Die Anangu', 'Die Maori', 'Die Gunditjmara']],
          ['Welcher Aborigine reiste 1792 nach England?', 'Bennelong', ['Pemulwuy', 'Yagan', 'Truganini']],
          ['Wer leistete über zehn Jahre Widerstand?', 'Pemulwuy', ['Bennelong', 'Phillip', 'Bligh']],
          ['Welches Getränk diente als Zahlungsmittel?', 'Rum', ['Tee', 'Wein', 'Bier']],
          ['Welcher Gouverneur wurde 1808 abgesetzt?', 'William Bligh', ['Arthur Phillip', 'Lachlan Macquarie', 'James Cook']],
          ['Wofür ist Bligh noch berühmt?', 'Für die Meuterei auf der Bounty', ['Für die Entdeckung Australiens', 'Für den Goldrausch', 'Für den Bau Sydneys']],
        ],
        mittel: [
          ['Wie viele Menschen waren an Bord der First Fleet?', 'Rund 1.400', ['Rund 140', 'Rund 14.000', 'Rund 40']],
          ['Wie viele Sträflinge waren an Bord?', 'Etwa 750', ['Etwa 75', 'Etwa 7.500', 'Etwa 1.400']],
          ['Wer war unter den Sträflingen?', 'Männer, Frauen und sogar Kinder', ['Nur Männer', 'Nur Adlige', 'Nur Seeleute']],
          ['Wie weit war die Reise etwa?', 'Rund 24.000 Kilometer', ['Rund 2.400 Kilometer', 'Rund 240.000 Kilometer', 'Rund 500 Kilometer']],
          ['Warum verließ Phillip die Botany Bay?', 'Er fand sie ungeeignet', ['Sie war besetzt', 'Ein Sturm zwang ihn', 'Cook hatte es befohlen']],
          ['Wo hissten die Briten die Flagge?', 'In der Sydney Cove', ['In der Botany Bay', 'Auf Possession Island', 'In Hobart']],
          ['Welchen weiteren Namen geben manche Aborigines dem 26. Januar?', 'Survival Day', ['Celebration Day', 'Anzac Day', 'Boxing Day']],
          ['Welches Amt hatte Lord Sydney?', 'Britischer Innenminister', ['König', 'Kapitän', 'Bischof']],
          ['Wann kam die Zweite Flotte?', '1790', ['1788', '1800', '1808']],
          ['In welchem Zustand waren viele Sträflinge der Zweiten Flotte?', 'Halb tot', ['Sehr gesund', 'Reich', 'Bewaffnet']],
          ['Was ging in den ersten Jahren ein?', 'Saatgut und Vieh', ['Die Schiffe', 'Die Häuser', 'Das Gold']],
          ['Wie gewann Phillip Vermittler?', 'Er ließ Männer entführen', ['Er bezahlte sie mit Gold', 'Er heiratete eine Aborigine', 'Durch einen Vertrag']],
          ['Wann wurde Pemulwuy erschossen?', '1802', ['1788', '1792', '1820']],
          ['Welche Truppe dominierte die Kolonie?', 'Das New South Wales Corps', ['Die Royal Navy', 'Die Anzacs', 'Die Bounty-Meuterer']],
          ['Wie nannte man das New South Wales Corps spöttisch?', 'Rum Corps', ['Gin Corps', 'Tea Corps', 'Gold Corps']],
          ['Wann fand die Rum-Rebellion statt?', '1808', ['1788', '1790', '1854']],
          ['Was ist die Rum-Rebellion in der Geschichte Australiens?', 'Der einzige Militärputsch', ['Der erste Goldrausch', 'Ein Sträflingsaufstand', 'Ein Krieg mit Frankreich']],
          ['Warum wurde Bligh abgesetzt?', 'Er ging gegen den Rumhandel vor', ['Er war zu freundlich', 'Er wollte König werden', 'Er war krank']],
          ['Wie viele Sträflinge kamen insgesamt in 80 Jahren?', 'Rund 162.000', ['Rund 16.000', 'Rund 1,6 Millionen', 'Rund 1.400']],
          ['Welches Volk verlor bei Sydney zuerst sein Land?', 'Die Eora', ['Die Yolŋu', 'Die Noongar', 'Die Palawa']],
        ],
        schwer: [
          ['In welchem Monat 1787 verließ die First Fleet England?', 'Im Mai', ['Im Januar', 'Im August', 'Im Dezember']],
          ['Welcher Naturhafen wurde Standort Sydneys?', 'Port Jackson', ['Botany Bay', 'Port Phillip', 'Moreton Bay']],
          ['Welche Ereignisse verbinden 1789 und die Aborigines um Sydney?', 'Eine verheerende Pockenepidemie', ['Ein Friedensvertrag', 'Ein Goldfund', 'Eine Missionsschule']],
          ['Welcher Mann gilt als erster Vermittler zwischen Aborigines und Briten?', 'Bennelong', ['Pemulwuy', 'Windradyne', 'Jandamarra']],
          ['Welcher Widerstandskämpfer starb 1802?', 'Pemulwuy', ['Bennelong', 'Yagan', 'Windradyne']],
          ['Welcher Gouverneur war früher Kapitän der Bounty?', 'William Bligh', ['Arthur Phillip', 'John Hunter', 'Philip King']],
          ['Welche Funktion hatte Rum in der frühen Kolonie?', 'Zahlungsmittel', ['Baumaterial', 'Treibstoff', 'Tauschgut mit China']],
          ['Welches Ereignis heißt „einziger Militärputsch Australiens“?', 'Die Rum-Rebellion 1808', ['Die Eureka-Rebellion', 'Die Entlassung 1975', 'Der Castle-Hill-Aufstand']],
          ['Was brachte die Zweite Flotte 1790?', 'Vorräte und viele kranke Sträflinge', ['Gold', 'Elefanten', 'Truppen gegen Frankreich']],
          ['Welche Bezeichnung trägt der 26. Januar offiziell?', 'Australia Day', ['Invasion Day', 'Anzac Day', 'Federation Day']],
          ['Welche Distanz legte die First Fleet zurück?', 'Rund 24.000 Kilometer', ['Rund 12.000 Kilometer', 'Rund 50.000 Kilometer', 'Rund 4.000 Kilometer']],
          ['Welche Gruppe machte etwa die Hälfte der First Fleet aus?', 'Sträflinge', ['Soldaten', 'Seeleute', 'Freie Siedler']],
          ['Wie viele Jahre leistete Pemulwuy Widerstand?', 'Über zehn', ['Eines', 'Fünfzig', 'Drei Monate']],
          ['Welches Ereignis rettete die Kolonie 1790 vor dem Verhungern?', 'Die Ankunft der Zweiten Flotte', ['Ein Goldfund', 'Hilfe der Niederländer', 'Ein Vertrag mit Frankreich']],
          ['Welche Stadt wurde 1788 gegründet?', 'Sydney', ['Melbourne', 'Brisbane', 'Perth']],
          ['Wohin reiste Bennelong 1792?', 'Nach England', ['Nach Amerika', 'Nach Indien', 'Nach Neuseeland']],
          ['Welche Rolle hatten Offiziere des NSW Corps wirtschaftlich?', 'Sie kontrollierten den Rumhandel', ['Sie waren Bauern ohne Macht', 'Sie waren Goldsucher', 'Sie waren Walfänger']],
          ['Welcher Kapitän wurde erster Gouverneur von New South Wales?', 'Arthur Phillip', ['William Bligh', 'James Cook', 'Lachlan Macquarie']],
          ['Welcher britische Minister gab Sydney den Namen?', 'Lord Sydney', ['Lord Melbourne', 'William Pitt', 'Lord Nelson']],
          ['Wie lange wurden Sträflinge nach Australien gebracht?', 'Rund 80 Jahre', ['Rund 8 Jahre', 'Rund 200 Jahre', 'Rund 800 Jahre']],
        ],
      },
    },
    {
      id: 'ausbreitung',
      title: 'Macquarie, Ausbreitung und Grenzkriege',
      date: '1810–1868',
      text: [
        'Gouverneur Lachlan Macquarie (1810–1821) machte aus dem Lager eine richtige Kolonie. Er ließ Straßen, Kirchen und Gebäude bauen, oft vom ehemaligen Sträfling und Architekten Francis Greenway, und behandelte freigelassene Sträflinge, die „Emancipists“, als gleichberechtigte Bürger. Er förderte den Namen „Australia“, den der Seefahrer Matthew Flinders vorgeschlagen hatte, der 1802/03 als Erster den Kontinent umsegelte.',
        '1813 überquerten Gregory Blaxland, William Lawson und William Wentworth die Blue Mountains westlich von Sydney und öffneten das Binnenland für Schafzucht; Wentworth wurde später ein bekannter Politiker. Wolle von Merinoschafen wurde zum wichtigsten Exportgut; man sagte, Australien „reite auf dem Rücken des Schafes“. Großgrundbesitzer, die „Squatters“, besetzten oft ohne Erlaubnis riesige Weidegebiete.',
        'Neue Kolonien entstanden: Van-Diemens-Land (Tasmanien) 1803/1825, Western Australia mit Perth 1829, South Australia mit Adelaide 1836 als Kolonie für freie Siedler ohne Sträflinge, Victoria mit Melbourne 1851 und Queensland 1859. In South Australia siedelten ab 1838 auch viele deutsche Lutheraner, etwa im Barossa Valley, wo sie Wein anbauten.',
        'Überall kam es zu „Grenzkriegen“ mit den Aborigines, die ihr Land verteidigten. In Tasmanien führte der „Schwarze Krieg“ (1824–1831) fast zur Vernichtung der Palawa; die letzten Überlebenden wurden auf die Flinders-Insel gebracht. 1838 ermordeten Siedler bei Myall Creek 28 Aborigines – es war das erste Mal, dass Weiße dafür gehängt wurden. Insgesamt starben in den Grenzkriegen Zehntausende Aborigines.',
        'Seit den 1830er-Jahren protestierten freie Siedler gegen die Sträflingstransporte. Nach New South Wales wurden 1840 keine Sträflinge mehr geschickt; der letzte Transport erreichte 1868 Western Australia. Ab 1855 erhielten die Kolonien eine eigene Selbstverwaltung mit Parlamenten.',
      ],
      quiz: {
        leicht: [
          ['Welcher Gouverneur machte aus dem Lager eine Kolonie?', 'Lachlan Macquarie', ['Arthur Phillip', 'William Bligh', 'James Cook']],
          ['Wann regierte Macquarie?', '1810–1821', ['1788–1792', '1851–1861', '1901–1910']],
          ['Wie hießen freigelassene Sträflinge?', 'Emancipists', ['Squatters', 'Bushrangers', 'Diggers']],
          ['Wer schlug den Namen „Australia“ vor?', 'Matthew Flinders', ['James Cook', 'Macquarie', 'Abel Tasman']],
          ['Was tat Flinders als Erster?', 'Er umsegelte den Kontinent', ['Er durchquerte die Wüste', 'Er fand Gold', 'Er gründete Melbourne']],
          ['Welches Gebirge wurde 1813 überquert?', 'Die Blue Mountains', ['Die Snowy Mountains', 'Die Alpen', 'Der Uluru']],
          ['Welches Tier wurde zur Grundlage der Wirtschaft?', 'Das Schaf', ['Das Känguru', 'Das Pferd', 'Das Kamel']],
          ['Welche Schafrasse war besonders wichtig?', 'Merino', ['Heidschnucke', 'Texel', 'Suffolk']],
          ['Was war das wichtigste Exportgut?', 'Wolle', ['Gold', 'Kohle', 'Weizen']],
          ['Wie hießen die Großgrundbesitzer mit riesigen Weiden?', 'Squatters', ['Emancipists', 'Convicts', 'Diggers']],
          ['Wann wurde Perth gegründet?', '1829', ['1788', '1836', '1901']],
          ['Welche Kolonie war für freie Siedler ohne Sträflinge?', 'South Australia', ['New South Wales', 'Tasmanien', 'Queensland']],
          ['Welche Stadt ist Hauptstadt von South Australia?', 'Adelaide', ['Perth', 'Melbourne', 'Brisbane']],
          ['Welche Einwanderer siedelten im Barossa Valley?', 'Deutsche Lutheraner', ['Chinesen', 'Italiener', 'Iren']],
          ['Was bauten die Deutschen im Barossa Valley an?', 'Wein', ['Reis', 'Tee', 'Baumwolle']],
          ['Wie heißen die Kämpfe zwischen Siedlern und Aborigines?', 'Grenzkriege', ['Burenkriege', 'Opiumkriege', 'Rosenkriege']],
          ['Wo fand der „Schwarze Krieg“ statt?', 'In Tasmanien', ['In Queensland', 'In Victoria', 'In Sydney']],
          ['Was geschah bei Myall Creek 1838?', 'Siedler ermordeten 28 Aborigines', ['Ein Friedensvertrag', 'Ein Goldfund', 'Die Gründung einer Stadt']],
          ['Wann kam der letzte Sträflingstransport?', '1868', ['1840', '1788', '1901']],
          ['Wer protestierte gegen die Sträflingstransporte?', 'Freie Siedler', ['Die Aborigines', 'Die Sträflinge', 'Die Niederländer']],
        ],
        mittel: [
          ['Wer war der Architekt vieler Macquarie-Bauten?', 'Francis Greenway', ['Jørn Utzon', 'Walter Burley Griffin', 'Christopher Wren']],
          ['Was war Francis Greenway früher?', 'Ein Sträfling', ['Ein Gouverneur', 'Ein Aborigine', 'Ein Seefahrer']],
          ['Wie behandelte Macquarie die Emancipists?', 'Als gleichberechtigte Bürger', ['Als Sklaven', 'Er schickte sie zurück', 'Er ignorierte sie']],
          ['Wann umsegelte Flinders den Kontinent?', '1802/03', ['1770', '1813', '1642']],
          ['Wer überquerte 1813 die Blue Mountains?', 'Blaxland, Lawson und Wentworth', ['Cook, Banks und Phillip', 'Burke und Wills', 'Flinders und Bass']],
          ['Wofür öffnete die Überquerung das Binnenland?', 'Für die Schafzucht', ['Für den Goldbergbau', 'Für Reisanbau', 'Für Städte']],
          ['Welcher Spruch beschrieb die Bedeutung der Wolle?', 'Australien reite auf dem Rücken des Schafes', ['Australien schwimme im Gold', 'Australien lebe vom Känguru', 'Australien sei ein Weizenland']],
          ['Wann wurde Adelaide gegründet?', '1836', ['1829', '1851', '1788']],
          ['Wann wurde Victoria eigene Kolonie?', '1851', ['1836', '1859', '1825']],
          ['Wann wurde Queensland eigene Kolonie?', '1859', ['1851', '1829', '1901']],
          ['Ab wann siedelten deutsche Lutheraner in South Australia?', 'Ab 1838', ['Ab 1788', 'Ab 1901', 'Ab 1950']],
          ['Wann dauerte der Schwarze Krieg?', '1824–1831', ['1788–1800', '1851–1854', '1914–1918']],
          ['Welches Volk wurde in Tasmanien fast vernichtet?', 'Die Palawa', ['Die Eora', 'Die Yolŋu', 'Die Noongar']],
          ['Wohin wurden die letzten Palawa gebracht?', 'Auf die Flinders-Insel', ['Nach Sydney', 'Nach England', 'Nach Neuseeland']],
          ['Was war am Myall-Creek-Massaker besonders?', 'Erstmals wurden Weiße dafür gehängt', ['Es gab keine Opfer', 'Aborigines gewannen', 'Es war ein Unfall']],
          ['Wie viele Aborigines starben in den Grenzkriegen insgesamt?', 'Zehntausende', ['Rund hundert', 'Keine', 'Rund zehn Millionen']],
          ['Wann endeten die Transporte nach New South Wales?', '1840', ['1868', '1808', '1901']],
          ['Welche Kolonie erhielt den letzten Sträflingstransport?', 'Western Australia', ['New South Wales', 'Tasmanien', 'Victoria']],
          ['Ab wann erhielten die Kolonien Selbstverwaltung?', 'Ab 1855', ['Ab 1788', 'Ab 1901', 'Ab 1840']],
          ['Seit wann protestierten freie Siedler gegen Transporte?', 'Seit den 1830er-Jahren', ['Seit 1788', 'Seit 1900', 'Nie']],
        ],
        schwer: [
          ['Welcher Gouverneur förderte den Namen „Australia“?', 'Macquarie', ['Phillip', 'Bligh', 'Hunter']],
          ['Welcher Seefahrer umsegelte als Erster Australien?', 'Matthew Flinders', ['James Cook', 'George Bass', 'Abel Tasman']],
          ['Welches Gebirge trennte Sydney vom Binnenland?', 'Die Blue Mountains', ['Die Pyrenäen', 'Die Flinders Ranges', 'Die MacDonnell Ranges']],
          ['Welche Gruppe besetzte ohne Erlaubnis riesige Weidegebiete?', 'Die Squatters', ['Die Emancipists', 'Die Bushrangers', 'Die Diggers']],
          ['Welche Kolonie war ausdrücklich ohne Sträflinge geplant?', 'South Australia', ['Western Australia', 'Van-Diemens-Land', 'Queensland']],
          ['Welche Weinregion gründeten deutsche Siedler?', 'Barossa Valley', ['Hunter Valley', 'Yarra Valley', 'Margaret River']],
          ['Welcher Konflikt dezimierte die Palawa?', 'Der Schwarze Krieg', ['Der Burenkrieg', 'Die Rum-Rebellion', 'Die Eureka-Rebellion']],
          ['Wie viele Aborigines wurden bei Myall Creek ermordet?', '28', ['2', '280', '2.800']],
          ['Welches Jahr markiert das Ende der Sträflingstransporte überhaupt?', '1868', ['1840', '1853', '1901']],
          ['Welcher frühere Sträfling wurde bedeutender Architekt?', 'Francis Greenway', ['Francis Drake', 'Ned Kelly', 'Henry Parkes']],
          ['Welche Kolonie hieß zuvor Van-Diemens-Land?', 'Tasmanien', ['Victoria', 'Queensland', 'Neuseeland']],
          ['Welche Folge hatte die Selbstverwaltung ab 1855?', 'Eigene Parlamente der Kolonien', ['Ein gemeinsamer Staat', 'Die Unabhängigkeit von Großbritannien', 'Ein König für Australien']],
          ['Welche Kolonie wurde 1829 mit Perth gegründet?', 'Western Australia', ['South Australia', 'Victoria', 'Northern Territory']],
          ['Welche Religion hatten die deutschen Siedler in South Australia?', 'Lutherisch', ['Katholisch', 'Jüdisch', 'Orthodox']],
          ['Welches Ereignis war das erste, bei dem Weiße für Morde an Aborigines gehängt wurden?', 'Myall Creek 1838', ['Der Schwarze Krieg', 'Die Rum-Rebellion', 'Eureka 1854']],
          ['Welcher der drei Bergüberquerer wurde später ein bekannter Politiker?', 'William Wentworth', ['Gregory Blaxland', 'William Lawson', 'Matthew Flinders']],
          ['Welche Insel wurde zum Verbannungsort der Palawa?', 'Flinders-Insel', ['Rottnest', 'Kangaroo Island', 'Hawaii']],
          ['Welches Produkt machte Australien im 19. Jahrhundert vor dem Gold reich?', 'Wolle', ['Kohle', 'Weizen', 'Zucker']],
          ['Wann wurden keine Sträflinge mehr nach New South Wales geschickt?', 'Ab 1840', ['Ab 1820', 'Ab 1868', 'Ab 1855']],
          ['Welche Zeit gilt als Macquaries Amtszeit?', '1810–1821', ['1800–1806', '1821–1831', '1840–1850']],
        ],
      },
    },
  ],
};
