import { IMPORTED_VOCAB } from './vocab-imported';
import { B1_VOCAB } from './vocab-b1';
import type { TopicId } from './vocab-topics';

export interface CatalogWord {
  de: string;
  it: string;
  topic: TopicId;
}

// Main vocabulary catalog (~2,900 words, A1–B1), walked in order by the "Learn"
// tab: the hand-written core (common, concrete themes first), then the imported
// Grund- and Ausbauwortschatz (lib/vocab-imported.ts), then the B1 extension
// (lib/vocab-b1.ts). Nouns carry their article so the gender is learned with the
// word; "a / b" lists accepted alternatives.
const CORE_VOCAB: CatalogWord[] = [
  // ── Häufige Verben ───────────────────────────────────────────────────────
  { de: 'sein', it: 'essere', topic: 'verben' },
  { de: 'sich befinden / bleiben', it: 'stare', topic: 'verben' },
  { de: 'haben', it: 'avere', topic: 'verben' },
  { de: 'machen / tun', it: 'fare', topic: 'verben' },
  { de: 'können', it: 'potere', topic: 'verben' },
  { de: 'sagen', it: 'dire', topic: 'verben' },
  { de: 'gehen', it: 'andare', topic: 'verben' },
  { de: 'sehen', it: 'vedere', topic: 'verben' },
  { de: 'geben', it: 'dare', topic: 'verben' },
  { de: 'wissen', it: 'sapere', topic: 'verben' },
  { de: 'wollen', it: 'volere', topic: 'verben' },
  { de: 'müssen', it: 'dovere', topic: 'verben' },
  { de: 'kommen', it: 'venire', topic: 'verben' },
  { de: 'legen / stellen', it: 'mettere', topic: 'verben' },
  { de: 'sprechen', it: 'parlare', topic: 'verben' },
  { de: 'lassen / verlassen', it: 'lasciare', topic: 'verben' },
  { de: 'folgen', it: 'seguire', topic: 'verben' },
  { de: 'ankommen', it: 'arrivare', topic: 'verben' },
  { de: 'kennen', it: 'conoscere', topic: 'verben' },
  { de: 'leben', it: 'vivere', topic: 'verben' },
  { de: 'wohnen', it: 'abitare', topic: 'verben' },
  { de: 'nehmen', it: 'prendere', topic: 'verben' },
  { de: 'denken', it: 'pensare', topic: 'verben' },
  { de: 'fragen', it: 'chiedere', topic: 'verben' },
  { de: 'finden', it: 'trovare', topic: 'verben' },
  { de: 'glauben', it: 'credere', topic: 'verben' },
  { de: 'tragen / bringen', it: 'portare', topic: 'verben' },
  { de: 'rufen / anrufen', it: 'chiamare', topic: 'verben' },
  { de: 'arbeiten', it: 'lavorare', topic: 'verben' },
  { de: 'lesen', it: 'leggere', topic: 'verben' },
  { de: 'hören', it: 'ascoltare', topic: 'verben' },
  { de: 'öffnen', it: 'aprire', topic: 'verben' },
  { de: 'schließen', it: 'chiudere', topic: 'verben' },
  { de: 'schreiben', it: 'scrivere', topic: 'verben' },
  { de: 'kaufen', it: 'comprare', topic: 'verben' },
  { de: 'essen', it: 'mangiare', topic: 'verben' },
  { de: 'trinken', it: 'bere', topic: 'verben' },
  { de: 'schlafen', it: 'dormire', topic: 'verben' },
  { de: 'spielen', it: 'giocare', topic: 'verben' },
  { de: 'beginnen', it: 'cominciare', topic: 'verben' },
  { de: 'helfen', it: 'aiutare', topic: 'verben' },
  { de: 'schauen / anschauen', it: 'guardare', topic: 'verben' },
  { de: 'brauchen', it: 'avere bisogno di', topic: 'verben' },
  { de: 'lieben', it: 'amare', topic: 'verben' },
  { de: 'rennen / laufen', it: 'correre', topic: 'verben' },
  { de: 'lernen', it: 'imparare', topic: 'verben' },
  { de: 'vergessen', it: 'dimenticare', topic: 'verben' },
  { de: 'erinnern', it: 'ricordare', topic: 'verben' },
  { de: 'bezahlen', it: 'pagare', topic: 'verben' },
  { de: 'verlieren', it: 'perdere', topic: 'verben' },
  { de: 'zeigen', it: 'mostrare', topic: 'verben' },
  { de: 'verstehen', it: 'capire', topic: 'verben' },
  { de: 'erklären', it: 'spiegare', topic: 'verben' },
  { de: 'warten', it: 'aspettare', topic: 'verben' },
  { de: 'versuchen / probieren', it: 'provare', topic: 'verben' },
  { de: 'reisen', it: 'viaggiare', topic: 'verben' },
  { de: 'tanzen', it: 'ballare', topic: 'verben' },
  { de: 'singen', it: 'cantare', topic: 'verben' },
  { de: 'kochen', it: 'cucinare', topic: 'verben' },
  { de: 'schicken / senden', it: 'mandare', topic: 'verben' },
  { de: 'antworten', it: 'rispondere', topic: 'verben' },
  { de: 'entscheiden', it: 'decidere', topic: 'verben' },
  { de: 'passieren / geschehen', it: 'succedere', topic: 'verben' },
  { de: 'bedeuten', it: 'significare', topic: 'verben' },
  { de: 'heiraten', it: 'sposarsi', topic: 'verben' },
  { de: 'sterben', it: 'morire', topic: 'verben' },
  { de: 'gewinnen', it: 'vincere', topic: 'verben' },
  { de: 'empfehlen', it: 'consigliare', topic: 'verben' },
  { de: 'erlauben', it: 'permettere', topic: 'verben' },
  { de: 'sich setzen', it: 'sedersi', topic: 'verben' },
  { de: 'aufstehen', it: 'alzarsi', topic: 'verben' },
  { de: 'waschen', it: 'lavare', topic: 'verben' },
  { de: 'malen', it: 'dipingere', topic: 'verben' },
  { de: 'bauen', it: 'costruire', topic: 'verben' },
  { de: 'zählen', it: 'contare', topic: 'verben' },
  { de: 'fehlen', it: 'mancare', topic: 'verben' },
  { de: 'gehören', it: 'appartenere', topic: 'verben' },
  { de: 'sich interessieren', it: 'interessarsi', topic: 'verben' },
  { de: 'landen', it: 'atterrare', topic: 'verben' },
  { de: 'hinaufgehen / einsteigen', it: 'salire', topic: 'verben' },
  { de: 'hinuntergehen / aussteigen', it: 'scendere', topic: 'verben' },
  { de: 'fallen', it: 'cadere', topic: 'verben' },
  { de: 'lächeln', it: 'sorridere', topic: 'verben' },
  { de: 'weinen', it: 'piangere', topic: 'verben' },
  { de: 'lachen', it: 'ridere', topic: 'verben' },
  { de: 'besuchen', it: 'visitare', topic: 'verben' },
  { de: 'telefonieren', it: 'telefonare', topic: 'verben' },
  { de: 'fahren (Auto)', it: 'guidare', topic: 'verben' },
  { de: 'fliegen', it: 'volare', topic: 'verben' },
  { de: 'schwimmen', it: 'nuotare', topic: 'verben' },
  { de: 'schieben / drücken', it: 'spingere', topic: 'verben' },
  { de: 'ziehen', it: 'tirare', topic: 'verben' },
  { de: 'buchen / reservieren', it: 'prenotare', topic: 'verben' },
  { de: 'teilen', it: 'condividere', topic: 'verben' },
  { de: 'genießen', it: 'godersi', topic: 'verben' },
  { de: 'verbessern', it: 'migliorare', topic: 'verben' },
  { de: 'ändern / wechseln', it: 'cambiare', topic: 'verben' },
  { de: 'sich treffen', it: 'incontrarsi', topic: 'verben' },

  // ── Körper ───────────────────────────────────────────────────────────────
  { de: 'der Kopf', it: 'la testa', topic: 'koerper' },
  { de: 'die Haare', it: 'i capelli', topic: 'koerper' },
  { de: 'das Gesicht', it: 'la faccia', topic: 'koerper' },
  { de: 'das Auge', it: "l'occhio", topic: 'koerper' },
  { de: 'die Nase', it: 'il naso', topic: 'koerper' },
  { de: 'der Mund', it: 'la bocca', topic: 'koerper' },
  { de: 'das Ohr', it: "l'orecchio", topic: 'koerper' },
  { de: 'der Hals', it: 'il collo', topic: 'koerper' },
  { de: 'die Schulter', it: 'la spalla', topic: 'koerper' },
  { de: 'der Arm', it: 'il braccio', topic: 'koerper' },
  { de: 'die Hand', it: 'la mano', topic: 'koerper' },
  { de: 'der Finger', it: 'il dito', topic: 'koerper' },
  { de: 'die Brust', it: 'il petto', topic: 'koerper' },
  { de: 'der Bauch', it: 'la pancia', topic: 'koerper' },
  { de: 'der Magen', it: 'lo stomaco', topic: 'koerper' },
  { de: 'der Rücken', it: 'la schiena', topic: 'koerper' },
  { de: 'das Bein', it: 'la gamba', topic: 'koerper' },
  { de: 'das Knie', it: 'il ginocchio', topic: 'koerper' },
  { de: 'der Fuß', it: 'il piede', topic: 'koerper' },
  { de: 'die Haut', it: 'la pelle', topic: 'koerper' },
  { de: 'das Blut', it: 'il sangue', topic: 'koerper' },
  { de: 'das Herz', it: 'il cuore', topic: 'koerper' },
  { de: 'die Lunge', it: 'il polmone', topic: 'koerper' },
  { de: 'das Gehirn', it: 'il cervello', topic: 'koerper' },
  { de: 'der Zahn', it: 'il dente', topic: 'koerper' },
  { de: 'die Lippe', it: 'il labbro', topic: 'koerper' },

  // ── Familie & Personen ───────────────────────────────────────────────────
  { de: 'die Mutter', it: 'la madre', topic: 'familie' },
  { de: 'der Vater', it: 'il padre', topic: 'familie' },
  { de: 'die Eltern', it: 'i genitori', topic: 'familie' },
  { de: 'die Tochter', it: 'la figlia', topic: 'familie' },
  { de: 'der Sohn', it: 'il figlio', topic: 'familie' },
  { de: 'die Kinder (eigene)', it: 'i figli', topic: 'familie' },
  { de: 'die Schwester', it: 'la sorella', topic: 'familie' },
  { de: 'der Bruder', it: 'il fratello', topic: 'familie' },
  { de: 'die Geschwister', it: 'i fratelli', topic: 'familie' },
  { de: 'die Großmutter', it: 'la nonna', topic: 'familie' },
  { de: 'der Großvater', it: 'il nonno', topic: 'familie' },
  { de: 'die Tante', it: 'la zia', topic: 'familie' },
  { de: 'der Onkel', it: 'lo zio', topic: 'familie' },
  { de: 'die Cousine', it: 'la cugina', topic: 'familie' },
  { de: 'der Cousin', it: 'il cugino', topic: 'familie' },
  { de: 'die Nichte / die Enkelin', it: 'la nipote', topic: 'familie' },
  { de: 'der Neffe / der Enkel', it: 'il nipote', topic: 'familie' },
  { de: 'die Ehefrau', it: 'la moglie', topic: 'familie' },
  { de: 'der Ehemann', it: 'il marito', topic: 'familie' },
  { de: 'der Freund / die Freundin (Partner)', it: 'il ragazzo / la ragazza', topic: 'familie' },
  { de: 'der Freund / die Freundin', it: "l'amico / l'amica", topic: 'familie' },
  { de: 'der Nachbar', it: 'il vicino di casa', topic: 'familie' },
  { de: 'der Kollege', it: 'il collega', topic: 'familie' },
  { de: 'das Baby', it: 'il neonato', topic: 'familie' },
  { de: 'das Kind', it: 'il bambino', topic: 'familie' },
  { de: 'der Jugendliche', it: 'il ragazzo', topic: 'familie' },
  { de: 'der Erwachsene', it: "l'adulto", topic: 'familie' },
  { de: 'die Person', it: 'la persona', topic: 'familie' },
  { de: 'der Mensch', it: "l'essere umano", topic: 'familie' },

  // ── Essen & Trinken ──────────────────────────────────────────────────────
  { de: 'das Brot', it: 'il pane', topic: 'essen' },
  { de: 'die Butter', it: 'il burro', topic: 'essen' },
  { de: 'der Käse', it: 'il formaggio', topic: 'essen' },
  { de: 'das Ei', it: "l'uovo", topic: 'essen' },
  { de: 'die Milch', it: 'il latte', topic: 'essen' },
  { de: 'der Joghurt', it: "lo yogurt", topic: 'essen' },
  { de: 'das Fleisch', it: 'la carne', topic: 'essen' },
  { de: 'der Fisch', it: 'il pesce', topic: 'essen' },
  { de: 'das Hühnchen', it: 'il pollo', topic: 'essen' },
  { de: 'das Schweinefleisch', it: 'il maiale', topic: 'essen' },
  { de: 'das Rindfleisch', it: 'il manzo', topic: 'essen' },
  { de: 'der Schinken', it: 'il prosciutto', topic: 'essen' },
  { de: 'die Wurst', it: 'la salsiccia', topic: 'essen' },
  { de: 'das Gemüse', it: 'la verdura', topic: 'essen' },
  { de: 'die Kartoffel', it: 'la patata', topic: 'essen' },
  { de: 'die Tomate', it: 'il pomodoro', topic: 'essen' },
  { de: 'die Zwiebel', it: 'la cipolla', topic: 'essen' },
  { de: 'der Knoblauch', it: "l'aglio", topic: 'essen' },
  { de: 'die Karotte', it: 'la carota', topic: 'essen' },
  { de: 'der Salat', it: "l'insalata", topic: 'essen' },
  { de: 'die Bohne', it: 'il fagiolo', topic: 'essen' },
  { de: 'der Reis', it: 'il riso', topic: 'essen' },
  { de: 'die Nudeln', it: 'la pasta', topic: 'essen' },
  { de: 'das Obst', it: 'la frutta', topic: 'essen' },
  { de: 'der Apfel', it: 'la mela', topic: 'essen' },
  { de: 'die Birne', it: 'la pera', topic: 'essen' },
  { de: 'die Banane', it: 'la banana', topic: 'essen' },
  { de: 'die Orange', it: "l'arancia", topic: 'essen' },
  { de: 'die Erdbeere', it: 'la fragola', topic: 'essen' },
  { de: 'die Traube', it: "l'uva", topic: 'essen' },
  { de: 'die Zitrone', it: 'il limone', topic: 'essen' },
  { de: 'die Wassermelone', it: "l'anguria", topic: 'essen' },
  { de: 'das Wasser', it: "l'acqua", topic: 'essen' },
  { de: 'der Kaffee', it: 'il caffè', topic: 'essen' },
  { de: 'der Tee', it: 'il tè', topic: 'essen' },
  { de: 'der Saft', it: 'il succo', topic: 'essen' },
  { de: 'das Bier', it: 'la birra', topic: 'essen' },
  { de: 'der Wein', it: 'il vino', topic: 'essen' },
  { de: 'der Zucker', it: 'lo zucchero', topic: 'essen' },
  { de: 'das Salz', it: 'il sale', topic: 'essen' },
  { de: 'der Pfeffer', it: 'il pepe', topic: 'essen' },
  { de: 'das Öl', it: "l'olio", topic: 'essen' },
  { de: 'die Soße', it: 'la salsa', topic: 'essen' },
  { de: 'die Suppe', it: 'la zuppa', topic: 'essen' },
  { de: 'der Kuchen', it: 'la torta', topic: 'essen' },
  { de: 'das Eis', it: 'il gelato', topic: 'essen' },
  { de: 'die Schokolade', it: 'il cioccolato', topic: 'essen' },
  { de: 'das Frühstück', it: 'la colazione', topic: 'essen' },
  { de: 'das Mittagessen', it: 'il pranzo', topic: 'essen' },
  { de: 'das Abendessen', it: 'la cena', topic: 'essen' },

  // ── Zuhause & Möbel ──────────────────────────────────────────────────────
  { de: 'das Haus', it: 'la casa', topic: 'wohnen' },
  { de: 'die Wohnung', it: "l'appartamento", topic: 'wohnen' },
  { de: 'das Zimmer', it: 'la stanza', topic: 'wohnen' },
  { de: 'die Küche', it: 'la cucina', topic: 'wohnen' },
  { de: 'das Badezimmer', it: 'il bagno', topic: 'wohnen' },
  { de: 'das Wohnzimmer', it: 'il soggiorno', topic: 'wohnen' },
  { de: 'das Schlafzimmer', it: 'la camera da letto', topic: 'wohnen' },
  { de: 'die Tür', it: 'la porta', topic: 'wohnen' },
  { de: 'das Fenster', it: 'la finestra', topic: 'wohnen' },
  { de: 'die Treppe', it: 'la scala', topic: 'wohnen' },
  { de: 'der Tisch', it: 'il tavolo', topic: 'wohnen' },
  { de: 'der Stuhl', it: 'la sedia', topic: 'wohnen' },
  { de: 'das Sofa', it: 'il divano', topic: 'wohnen' },
  { de: 'das Bett', it: 'il letto', topic: 'wohnen' },
  { de: 'der Schrank', it: "l'armadio", topic: 'wohnen' },
  { de: 'das Regal', it: 'lo scaffale', topic: 'wohnen' },
  { de: 'die Lampe', it: 'la lampada', topic: 'wohnen' },
  { de: 'der Spiegel', it: 'lo specchio', topic: 'wohnen' },
  { de: 'der Teppich', it: 'il tappeto', topic: 'wohnen' },
  { de: 'der Vorhang', it: 'la tenda', topic: 'wohnen' },
  { de: 'der Kühlschrank', it: 'il frigorifero', topic: 'wohnen' },
  { de: 'der Herd', it: 'il fornello', topic: 'wohnen' },
  { de: 'die Waschmaschine', it: 'la lavatrice', topic: 'wohnen' },
  { de: 'der Staubsauger', it: "l'aspirapolvere", topic: 'wohnen' },
  { de: 'der Schlüssel', it: 'la chiave', topic: 'wohnen' },

  // ── Farben ───────────────────────────────────────────────────────────────
  { de: 'rot', it: 'rosso', topic: 'farben' },
  { de: 'blau', it: 'blu', topic: 'farben' },
  { de: 'hellblau', it: 'azzurro', topic: 'farben' },
  { de: 'grün', it: 'verde', topic: 'farben' },
  { de: 'gelb', it: 'giallo', topic: 'farben' },
  { de: 'schwarz', it: 'nero', topic: 'farben' },
  { de: 'weiß', it: 'bianco', topic: 'farben' },
  { de: 'grau', it: 'grigio', topic: 'farben' },
  { de: 'orange', it: 'arancione', topic: 'farben' },
  { de: 'lila / violett', it: 'viola', topic: 'farben' },
  { de: 'rosa', it: 'rosa', topic: 'farben' },
  { de: 'braun', it: 'marrone', topic: 'farben' },
  { de: 'beige', it: 'beige', topic: 'farben' },
  { de: 'golden', it: 'dorato', topic: 'farben' },
  { de: 'silbern', it: 'argentato', topic: 'farben' },

  // ── Zeit ─────────────────────────────────────────────────────────────────
  { de: 'die Sekunde', it: 'il secondo', topic: 'zeit' },
  { de: 'die Minute', it: 'il minuto', topic: 'zeit' },
  { de: 'die Stunde', it: "l'ora", topic: 'zeit' },
  { de: 'der Tag', it: 'il giorno', topic: 'zeit' },
  { de: 'die Woche', it: 'la settimana', topic: 'zeit' },
  { de: 'der Monat', it: 'il mese', topic: 'zeit' },
  { de: 'das Jahr', it: "l'anno", topic: 'zeit' },
  { de: 'heute', it: 'oggi', topic: 'zeit' },
  { de: 'gestern', it: 'ieri', topic: 'zeit' },
  { de: 'morgen', it: 'domani', topic: 'zeit' },
  { de: 'jetzt', it: 'adesso / ora', topic: 'zeit' },
  { de: 'später', it: 'più tardi', topic: 'zeit' },
  { de: 'früher / vorher', it: 'prima', topic: 'zeit' },
  { de: 'immer', it: 'sempre', topic: 'zeit' },
  { de: 'nie / niemals', it: 'mai', topic: 'zeit' },
  { de: 'manchmal', it: 'a volte', topic: 'zeit' },
  { de: 'oft', it: 'spesso', topic: 'zeit' },
  { de: 'selten', it: 'raramente', topic: 'zeit' },
  { de: 'bald', it: 'presto', topic: 'zeit' },
  { de: 'schon / bereits', it: 'già', topic: 'zeit' },
  { de: 'noch', it: 'ancora', topic: 'zeit' },
  { de: 'der Morgen', it: 'la mattina', topic: 'zeit' },
  { de: 'der Nachmittag', it: 'il pomeriggio', topic: 'zeit' },
  { de: 'der Abend', it: 'la sera', topic: 'zeit' },
  { de: 'die Nacht', it: 'la notte', topic: 'zeit' },
  { de: 'das Wochenende', it: 'il fine settimana', topic: 'zeit' },
  { de: 'Montag', it: 'il lunedì', topic: 'zeit' },
  { de: 'Dienstag', it: 'il martedì', topic: 'zeit' },
  { de: 'Mittwoch', it: 'il mercoledì', topic: 'zeit' },
  { de: 'Donnerstag', it: 'il giovedì', topic: 'zeit' },
  { de: 'Freitag', it: 'il venerdì', topic: 'zeit' },
  { de: 'Samstag', it: 'il sabato', topic: 'zeit' },
  { de: 'Sonntag', it: 'la domenica', topic: 'zeit' },
  { de: 'Januar', it: 'gennaio', topic: 'zeit' },
  { de: 'Februar', it: 'febbraio', topic: 'zeit' },
  { de: 'März', it: 'marzo', topic: 'zeit' },
  { de: 'April', it: 'aprile', topic: 'zeit' },
  { de: 'Mai', it: 'maggio', topic: 'zeit' },
  { de: 'Juni', it: 'giugno', topic: 'zeit' },
  { de: 'Juli', it: 'luglio', topic: 'zeit' },
  { de: 'August', it: 'agosto', topic: 'zeit' },
  { de: 'September', it: 'settembre', topic: 'zeit' },
  { de: 'Oktober', it: 'ottobre', topic: 'zeit' },
  { de: 'November', it: 'novembre', topic: 'zeit' },
  { de: 'Dezember', it: 'dicembre', topic: 'zeit' },

  // ── Natur & Wetter ───────────────────────────────────────────────────────
  { de: 'die Natur', it: 'la natura', topic: 'natur' },
  { de: 'der Baum', it: "l'albero", topic: 'natur' },
  { de: 'die Blume', it: 'il fiore', topic: 'natur' },
  { de: 'das Gras', it: "l'erba", topic: 'natur' },
  { de: 'der Wald', it: 'il bosco', topic: 'natur' },
  { de: 'der Berg', it: 'la montagna', topic: 'natur' },
  { de: 'das Tal', it: 'la valle', topic: 'natur' },
  { de: 'der Fluss', it: 'il fiume', topic: 'natur' },
  { de: 'der See', it: 'il lago', topic: 'natur' },
  { de: 'das Meer', it: 'il mare', topic: 'natur' },
  { de: 'der Strand', it: 'la spiaggia', topic: 'natur' },
  { de: 'die Insel', it: "l'isola", topic: 'natur' },
  { de: 'die Küste', it: 'la costa', topic: 'natur' },
  { de: 'die Wüste', it: 'il deserto', topic: 'natur' },
  { de: 'der Himmel', it: 'il cielo', topic: 'natur' },
  { de: 'die Sonne', it: 'il sole', topic: 'natur' },
  { de: 'der Mond', it: 'la luna', topic: 'natur' },
  { de: 'der Stern', it: 'la stella', topic: 'natur' },
  { de: 'die Wolke', it: 'la nuvola', topic: 'natur' },
  { de: 'der Regen', it: 'la pioggia', topic: 'natur' },
  { de: 'der Schnee', it: 'la neve', topic: 'natur' },
  { de: 'der Wind', it: 'il vento', topic: 'natur' },
  { de: 'das Gewitter', it: 'il temporale', topic: 'natur' },
  { de: 'der Blitz', it: 'il fulmine', topic: 'natur' },
  { de: 'der Nebel', it: 'la nebbia', topic: 'natur' },
  { de: 'der Frühling', it: 'la primavera', topic: 'natur' },
  { de: 'der Sommer', it: "l'estate", topic: 'natur' },
  { de: 'der Herbst', it: "l'autunno", topic: 'natur' },
  { de: 'der Winter', it: "l'inverno", topic: 'natur' },
  { de: 'die Temperatur', it: 'la temperatura', topic: 'natur' },

  // ── Stadt & Orte ─────────────────────────────────────────────────────────
  { de: 'die Stadt', it: 'la città', topic: 'stadt' },
  { de: 'das Dorf', it: 'il paese', topic: 'stadt' },
  { de: 'das Land (Staat)', it: 'la nazione', topic: 'stadt' },
  { de: 'die Straße', it: 'la strada', topic: 'stadt' },
  { de: 'der Platz', it: 'la piazza', topic: 'stadt' },
  { de: 'die Brücke', it: 'il ponte', topic: 'stadt' },
  { de: 'das Geschäft / der Laden', it: 'il negozio', topic: 'stadt' },
  { de: 'der Supermarkt', it: 'il supermercato', topic: 'stadt' },
  { de: 'der Markt', it: 'il mercato', topic: 'stadt' },
  { de: 'der Bahnhof', it: 'la stazione', topic: 'stadt' },
  { de: 'der Flughafen', it: "l'aeroporto", topic: 'stadt' },
  { de: 'das Hotel', it: "l'albergo", topic: 'stadt' },
  { de: 'das Restaurant', it: 'il ristorante', topic: 'stadt' },
  { de: 'die Bar / das Café', it: 'il bar', topic: 'stadt' },
  { de: 'die Kirche', it: 'la chiesa', topic: 'stadt' },
  { de: 'das Museum', it: 'il museo', topic: 'stadt' },
  { de: 'das Krankenhaus', it: "l'ospedale", topic: 'stadt' },
  { de: 'die Apotheke', it: 'la farmacia', topic: 'stadt' },
  { de: 'die Bank', it: 'la banca', topic: 'stadt' },
  { de: 'das Büro', it: "l'ufficio", topic: 'stadt' },
  { de: 'die Schule', it: 'la scuola', topic: 'stadt' },
  { de: 'die Universität', it: "l'università", topic: 'stadt' },
  { de: 'die Bibliothek', it: 'la biblioteca', topic: 'stadt' },
  { de: 'das Theater', it: 'il teatro', topic: 'stadt' },
  { de: 'das Kino', it: 'il cinema', topic: 'stadt' },
  { de: 'der Park', it: 'il parco', topic: 'stadt' },
  { de: 'der Friedhof', it: 'il cimitero', topic: 'stadt' },
  { de: 'das Rathaus', it: 'il municipio', topic: 'stadt' },
  { de: 'die Post', it: "l'ufficio postale", topic: 'stadt' },
  { de: 'die Polizei', it: 'la polizia', topic: 'stadt' },

  // ── Arbeit & Berufe ──────────────────────────────────────────────────────
  { de: 'die Arbeit', it: 'il lavoro', topic: 'arbeit' },
  { de: 'der Beruf', it: 'la professione', topic: 'arbeit' },
  { de: 'das Gehalt', it: 'lo stipendio', topic: 'arbeit' },
  { de: 'der Chef / die Chefin', it: 'il capo', topic: 'arbeit' },
  { de: 'der Mitarbeiter', it: "l'impiegato", topic: 'arbeit' },
  { de: 'die Firma', it: "l'azienda", topic: 'arbeit' },
  { de: 'die Besprechung', it: 'la riunione', topic: 'arbeit' },
  { de: 'das Projekt', it: 'il progetto', topic: 'arbeit' },
  { de: 'der Termin', it: "l'appuntamento", topic: 'arbeit' },
  { de: 'die Pause', it: 'la pausa', topic: 'arbeit' },
  { de: 'der Urlaub', it: 'le ferie', topic: 'arbeit' },
  { de: 'der Vertrag', it: 'il contratto', topic: 'arbeit' },
  { de: 'der Arzt / die Ärztin', it: 'il medico', topic: 'arbeit' },
  { de: 'der Anwalt', it: "l'avvocato", topic: 'arbeit' },
  { de: 'der Ingenieur', it: "l'ingegnere", topic: 'arbeit' },
  { de: 'der Lehrer', it: "l'insegnante", topic: 'arbeit' },
  { de: 'der Koch', it: 'il cuoco', topic: 'arbeit' },
  { de: 'der Fahrer', it: "l'autista", topic: 'arbeit' },
  { de: 'der Polizist', it: 'il poliziotto', topic: 'arbeit' },
  { de: 'der Architekt', it: "l'architetto", topic: 'arbeit' },
  { de: 'der Programmierer', it: 'il programmatore', topic: 'arbeit' },
  { de: 'der Journalist', it: 'il giornalista', topic: 'arbeit' },
  { de: 'der Verkäufer', it: 'il commesso', topic: 'arbeit' },
  { de: 'der Kellner', it: 'il cameriere', topic: 'arbeit' },
  { de: 'die Sekretärin', it: 'la segretaria', topic: 'arbeit' },

  // ── Reisen & Transport ───────────────────────────────────────────────────
  { de: 'die Reise', it: 'il viaggio', topic: 'reisen' },
  { de: 'das Gepäck', it: 'il bagaglio', topic: 'reisen' },
  { de: 'der Koffer', it: 'la valigia', topic: 'reisen' },
  { de: 'der Pass', it: 'il passaporto', topic: 'reisen' },
  { de: 'das Visum', it: 'il visto', topic: 'reisen' },
  { de: 'die Unterkunft', it: "l'alloggio", topic: 'reisen' },
  { de: 'die Reservierung', it: 'la prenotazione', topic: 'reisen' },
  { de: 'das Ticket / die Fahrkarte', it: 'il biglietto', topic: 'reisen' },
  { de: 'der Ausflug', it: "la gita", topic: 'reisen' },
  { de: 'die Sehenswürdigkeit', it: "l'attrazione", topic: 'reisen' },
  { de: 'der Stadtplan', it: 'la cartina', topic: 'reisen' },
  { de: 'der Tourist', it: 'il turista', topic: 'reisen' },
  { de: 'das Auto', it: 'la macchina', topic: 'reisen' },
  { de: 'der Bus', it: "l'autobus", topic: 'reisen' },
  { de: 'die U-Bahn', it: 'la metropolitana', topic: 'reisen' },
  { de: 'das Taxi', it: 'il taxi', topic: 'reisen' },
  { de: 'das Flugzeug', it: "l'aereo", topic: 'reisen' },
  { de: 'der Zug', it: 'il treno', topic: 'reisen' },
  { de: 'das Schiff', it: 'la nave', topic: 'reisen' },
  { de: 'das Fahrrad', it: 'la bicicletta', topic: 'reisen' },

  // ── Gesundheit ───────────────────────────────────────────────────────────
  { de: 'die Gesundheit', it: 'la salute', topic: 'gesundheit' },
  { de: 'der Patient', it: 'il paziente', topic: 'gesundheit' },
  { de: 'das Medikament', it: 'la medicina', topic: 'gesundheit' },
  { de: 'die Tablette', it: 'la pastiglia', topic: 'gesundheit' },
  { de: 'die Krankheit', it: 'la malattia', topic: 'gesundheit' },
  { de: 'der Schmerz', it: 'il dolore', topic: 'gesundheit' },
  { de: 'das Fieber', it: 'la febbre', topic: 'gesundheit' },
  { de: 'der Husten', it: 'la tosse', topic: 'gesundheit' },
  { de: 'der Schnupfen / die Erkältung', it: 'il raffreddore', topic: 'gesundheit' },
  { de: 'die Grippe', it: "l'influenza", topic: 'gesundheit' },
  { de: 'die Allergie', it: "l'allergia", topic: 'gesundheit' },
  { de: 'die Operation', it: "l'operazione", topic: 'gesundheit' },
  { de: 'die Untersuchung', it: 'la visita medica', topic: 'gesundheit' },
  { de: 'der Verband', it: 'la benda', topic: 'gesundheit' },
  { de: 'die Verletzung', it: 'la ferita', topic: 'gesundheit' },
  { de: 'der Notfall', it: "l'emergenza", topic: 'gesundheit' },
  { de: 'das Rezept (Arzt)', it: 'la ricetta', topic: 'gesundheit' },
  { de: 'die Spritze', it: "l'iniezione", topic: 'gesundheit' },

  // ── Technologie ──────────────────────────────────────────────────────────
  { de: 'der Computer', it: 'il computer', topic: 'technik' },
  { de: 'das Handy', it: 'il cellulare', topic: 'technik' },
  { de: 'das Internet', it: 'internet', topic: 'technik' },
  { de: 'die Webseite', it: 'il sito web', topic: 'technik' },
  { de: 'die App', it: "l'app", topic: 'technik' },
  { de: 'die E-Mail', it: "l'email", topic: 'technik' },
  { de: 'der Drucker', it: 'la stampante', topic: 'technik' },
  { de: 'der Bildschirm', it: 'lo schermo', topic: 'technik' },
  { de: 'die Tastatur', it: 'la tastiera', topic: 'technik' },
  { de: 'die Kamera', it: 'la macchina fotografica', topic: 'technik' },
  { de: 'das Foto', it: 'la foto', topic: 'technik' },
  { de: 'das Video', it: 'il video', topic: 'technik' },
  { de: 'das Passwort', it: 'la password', topic: 'technik' },
  { de: 'die Datei', it: 'il file', topic: 'technik' },
  { de: 'das Netzwerk', it: 'la rete', topic: 'technik' },

  // ── Geld & Einkaufen ─────────────────────────────────────────────────────
  { de: 'das Geld', it: 'i soldi', topic: 'geld' },
  { de: 'der Preis', it: 'il prezzo', topic: 'geld' },
  { de: 'teuer', it: 'caro', topic: 'geld' },
  { de: 'günstig / billig', it: 'economico', topic: 'geld' },
  { de: 'die Rechnung (Restaurant)', it: 'il conto', topic: 'geld' },
  { de: 'die Rechnung (Firma)', it: 'la fattura', topic: 'geld' },
  { de: 'die Quittung / der Kassenbon', it: 'lo scontrino', topic: 'geld' },
  { de: 'die Kreditkarte', it: 'la carta di credito', topic: 'geld' },
  { de: 'das Bargeld', it: 'i contanti', topic: 'geld' },
  { de: 'der Rabatt', it: 'lo sconto', topic: 'geld' },
  { de: 'das Angebot', it: "l'offerta", topic: 'geld' },
  { de: 'die Kasse', it: 'la cassa', topic: 'geld' },
  { de: 'das Kaufhaus', it: 'il grande magazzino', topic: 'geld' },
  { de: 'die Steuer', it: 'la tassa', topic: 'geld' },
  { de: 'das Budget', it: 'il budget', topic: 'geld' },

  // ── Kleidung ─────────────────────────────────────────────────────────────
  { de: 'die Kleidung', it: 'i vestiti', topic: 'kleidung' },
  { de: 'das Hemd', it: 'la camicia', topic: 'kleidung' },
  { de: 'die Hose', it: 'i pantaloni', topic: 'kleidung' },
  { de: 'das Kleid', it: 'il vestito', topic: 'kleidung' },
  { de: 'der Rock', it: 'la gonna', topic: 'kleidung' },
  { de: 'der Pullover', it: 'il maglione', topic: 'kleidung' },
  { de: 'die Jacke', it: 'la giacca', topic: 'kleidung' },
  { de: 'der Mantel', it: 'il cappotto', topic: 'kleidung' },
  { de: 'der Schuh', it: 'la scarpa', topic: 'kleidung' },
  { de: 'der Stiefel', it: 'lo stivale', topic: 'kleidung' },
  { de: 'die Socke', it: 'il calzino', topic: 'kleidung' },
  { de: 'die Unterwäsche', it: 'la biancheria intima', topic: 'kleidung' },
  { de: 'der Hut', it: 'il cappello', topic: 'kleidung' },
  { de: 'die Mütze', it: 'il berretto', topic: 'kleidung' },
  { de: 'der Schal', it: 'la sciarpa', topic: 'kleidung' },
  { de: 'die Handschuhe', it: 'i guanti', topic: 'kleidung' },
  { de: 'der Gürtel', it: 'la cintura', topic: 'kleidung' },
  { de: 'die Brille', it: 'gli occhiali', topic: 'kleidung' },

  // ── Tiere ────────────────────────────────────────────────────────────────
  { de: 'das Tier', it: "l'animale", topic: 'tiere' },
  { de: 'der Hund', it: 'il cane', topic: 'tiere' },
  { de: 'die Katze', it: 'il gatto', topic: 'tiere' },
  { de: 'das Pferd', it: 'il cavallo', topic: 'tiere' },
  { de: 'die Kuh', it: 'la mucca', topic: 'tiere' },
  { de: 'das Schwein', it: 'il maiale', topic: 'tiere' },
  { de: 'das Schaf', it: 'la pecora', topic: 'tiere' },
  { de: 'der Vogel', it: "l'uccello", topic: 'tiere' },
  { de: 'die Schlange', it: 'il serpente', topic: 'tiere' },
  { de: 'der Löwe', it: 'il leone', topic: 'tiere' },
  { de: 'der Tiger', it: 'la tigre', topic: 'tiere' },
  { de: 'der Bär', it: "l'orso", topic: 'tiere' },
  { de: 'der Wolf', it: 'il lupo', topic: 'tiere' },
  { de: 'der Elefant', it: "l'elefante", topic: 'tiere' },
  { de: 'der Affe', it: 'la scimmia', topic: 'tiere' },
  { de: 'die Maus', it: 'il topo', topic: 'tiere' },
  { de: 'das Insekt', it: "l'insetto", topic: 'tiere' },

  // ── Adjektive ────────────────────────────────────────────────────────────
  { de: 'groß', it: 'grande', topic: 'adjektive' },
  { de: 'klein', it: 'piccolo', topic: 'adjektive' },
  { de: 'lang', it: 'lungo', topic: 'adjektive' },
  { de: 'kurz', it: 'corto', topic: 'adjektive' },
  { de: 'breit', it: 'largo', topic: 'adjektive' },
  { de: 'schmal / eng', it: 'stretto', topic: 'adjektive' },
  { de: 'hoch', it: 'alto', topic: 'adjektive' },
  { de: 'niedrig / tief', it: 'basso', topic: 'adjektive' },
  { de: 'schwer', it: 'pesante', topic: 'adjektive' },
  { de: 'leicht (Gewicht)', it: 'leggero', topic: 'adjektive' },
  { de: 'schnell', it: 'veloce', topic: 'adjektive' },
  { de: 'langsam', it: 'lento', topic: 'adjektive' },
  { de: 'neu', it: 'nuovo', topic: 'adjektive' },
  { de: 'alt', it: 'vecchio', topic: 'adjektive' },
  { de: 'jung', it: 'giovane', topic: 'adjektive' },
  { de: 'modern', it: 'moderno', topic: 'adjektive' },
  { de: 'gut', it: 'buono', topic: 'adjektive' },
  { de: 'schlecht', it: 'cattivo', topic: 'adjektive' },
  { de: 'schön', it: 'bello', topic: 'adjektive' },
  { de: 'hässlich', it: 'brutto', topic: 'adjektive' },
  { de: 'sauber', it: 'pulito', topic: 'adjektive' },
  { de: 'schmutzig', it: 'sporco', topic: 'adjektive' },
  { de: 'voll', it: 'pieno', topic: 'adjektive' },
  { de: 'leer', it: 'vuoto', topic: 'adjektive' },
  { de: 'warm / heiß', it: 'caldo', topic: 'adjektive' },
  { de: 'kalt', it: 'freddo', topic: 'adjektive' },
  { de: 'kühl / frisch', it: 'fresco', topic: 'adjektive' },
  { de: 'trocken', it: 'secco', topic: 'adjektive' },
  { de: 'nass', it: 'bagnato', topic: 'adjektive' },
  { de: 'laut', it: 'rumoroso', topic: 'adjektive' },
  { de: 'leise / still', it: 'silenzioso', topic: 'adjektive' },
  { de: 'hell', it: 'chiaro', topic: 'adjektive' },
  { de: 'dunkel', it: 'scuro', topic: 'adjektive' },
  { de: 'stark', it: 'forte', topic: 'adjektive' },
  { de: 'schwach', it: 'debole', topic: 'adjektive' },
  { de: 'reich', it: 'ricco', topic: 'adjektive' },
  { de: 'arm', it: 'povero', topic: 'adjektive' },
  { de: 'glücklich', it: 'felice', topic: 'adjektive' },
  { de: 'traurig', it: 'triste', topic: 'adjektive' },
  { de: 'müde', it: 'stanco', topic: 'adjektive' },
  { de: 'krank', it: 'malato', topic: 'adjektive' },
  { de: 'gesund', it: 'sano', topic: 'adjektive' },
  { de: 'interessant', it: 'interessante', topic: 'adjektive' },
  { de: 'langweilig', it: 'noioso', topic: 'adjektive' },
  { de: 'wichtig', it: 'importante', topic: 'adjektive' },
  { de: 'nötig', it: 'necessario', topic: 'adjektive' },
  { de: 'möglich', it: 'possibile', topic: 'adjektive' },
  { de: 'unmöglich', it: 'impossibile', topic: 'adjektive' },
  { de: 'sicher', it: 'sicuro', topic: 'adjektive' },
  { de: 'gefährlich', it: 'pericoloso', topic: 'adjektive' },
  { de: 'einfach', it: 'semplice', topic: 'adjektive' },
  { de: 'kompliziert', it: 'complicato', topic: 'adjektive' },
  { de: 'berühmt', it: 'famoso', topic: 'adjektive' },
  { de: 'allgemein', it: 'generale', topic: 'adjektive' },
  { de: 'besonders', it: 'speciale', topic: 'adjektive' },
  { de: 'normal', it: 'normale', topic: 'adjektive' },
  { de: 'anders / verschieden', it: 'diverso', topic: 'adjektive' },
  { de: 'ähnlich', it: 'simile', topic: 'adjektive' },
  { de: 'gleich', it: 'uguale', topic: 'adjektive' },
  { de: 'typisch', it: 'tipico', topic: 'adjektive' },

  // ── Emotionen & Charakter ────────────────────────────────────────────────
  { de: 'die Freude', it: 'la gioia', topic: 'gefuehle' },
  { de: 'die Traurigkeit', it: 'la tristezza', topic: 'gefuehle' },
  { de: 'die Angst', it: 'la paura', topic: 'gefuehle' },
  { de: 'die Wut', it: 'la rabbia', topic: 'gefuehle' },
  { de: 'die Überraschung', it: 'la sorpresa', topic: 'gefuehle' },
  { de: 'die Liebe', it: "l'amore", topic: 'gefuehle' },
  { de: 'der Hass', it: "l'odio", topic: 'gefuehle' },
  { de: 'die Hoffnung', it: 'la speranza', topic: 'gefuehle' },
  { de: 'die Enttäuschung', it: 'la delusione', topic: 'gefuehle' },
  { de: 'stolz', it: 'orgoglioso', topic: 'gefuehle' },
  { de: 'neidisch', it: 'invidioso', topic: 'gefuehle' },
  { de: 'dankbar', it: 'grato', topic: 'gefuehle' },
  { de: 'freundlich', it: 'gentile', topic: 'gefuehle' },
  { de: 'höflich', it: 'educato', topic: 'gefuehle' },
  { de: 'unhöflich', it: 'maleducato', topic: 'gefuehle' },
  { de: 'ehrlich', it: 'onesto', topic: 'gefuehle' },
  { de: 'treu', it: 'fedele', topic: 'gefuehle' },
  { de: 'mutig', it: 'coraggioso', topic: 'gefuehle' },
  { de: 'schüchtern', it: 'timido', topic: 'gefuehle' },
  { de: 'neugierig', it: 'curioso', topic: 'gefuehle' },
  { de: 'geduldig', it: 'paziente', topic: 'gefuehle' },
  { de: 'ungeduldig', it: 'impaziente', topic: 'gefuehle' },
  { de: 'selbstbewusst', it: 'sicuro di sé', topic: 'gefuehle' },
  { de: 'großzügig', it: 'generoso', topic: 'gefuehle' },
  { de: 'geizig', it: 'tirchio', topic: 'gefuehle' },
  { de: 'verantwortungsbewusst', it: 'responsabile', topic: 'gefuehle' },
  { de: 'kreativ', it: 'creativo', topic: 'gefuehle' },
  { de: 'intelligent', it: 'intelligente', topic: 'gefuehle' },
  { de: 'lustig', it: 'divertente', topic: 'gefuehle' },
  { de: 'ernst', it: 'serio', topic: 'gefuehle' },

  // ── Bildung ──────────────────────────────────────────────────────────────
  { de: 'das Buch', it: 'il libro', topic: 'schule' },
  { de: 'das Heft', it: 'il quaderno', topic: 'schule' },
  { de: 'der Kugelschreiber', it: 'la penna', topic: 'schule' },
  { de: 'der Bleistift', it: 'la matita', topic: 'schule' },
  { de: 'das Papier', it: 'la carta', topic: 'schule' },
  { de: 'der Schüler', it: 'lo studente', topic: 'schule' },
  { de: 'die Prüfung', it: "l'esame", topic: 'schule' },
  { de: 'die Note', it: 'il voto', topic: 'schule' },
  { de: 'die Hausaufgaben', it: 'i compiti', topic: 'schule' },
  { de: 'die Klasse', it: 'la classe', topic: 'schule' },
  { de: 'das Schulfach', it: 'la materia', topic: 'schule' },
  { de: 'die Sprache', it: 'la lingua', topic: 'schule' },
  { de: 'das Wort', it: 'la parola', topic: 'schule' },
  { de: 'der Satz', it: 'la frase', topic: 'schule' },
  { de: 'der Fehler', it: "l'errore", topic: 'schule' },
  { de: 'das Zeugnis', it: 'la pagella', topic: 'schule' },

  // ── Musik & Freizeit ─────────────────────────────────────────────────────
  { de: 'die Musik', it: 'la musica', topic: 'freizeit' },
  { de: 'das Lied', it: 'la canzone', topic: 'freizeit' },
  { de: 'das Konzert', it: 'il concerto', topic: 'freizeit' },
  { de: 'der Film', it: 'il film', topic: 'freizeit' },
  { de: 'der Sport', it: 'lo sport', topic: 'freizeit' },
  { de: 'das Spiel', it: 'il gioco', topic: 'freizeit' },
  { de: 'das Hobby', it: "l'hobby", topic: 'freizeit' },
  { de: 'die Freizeit', it: 'il tempo libero', topic: 'freizeit' },
  { de: 'die Ferien', it: 'le vacanze', topic: 'freizeit' },
  { de: 'das Fest / die Party', it: 'la festa', topic: 'freizeit' },
  { de: 'der Geburtstag', it: 'il compleanno', topic: 'freizeit' },
  { de: 'das Geschenk', it: 'il regalo', topic: 'freizeit' },
  { de: 'der Fußball', it: 'il calcio', topic: 'freizeit' },
  { de: 'das Tennis', it: 'il tennis', topic: 'freizeit' },

  // ── Abstrakte Begriffe ───────────────────────────────────────────────────
  { de: 'die Idee', it: "l'idea", topic: 'abstrakt' },
  { de: 'das Problem', it: 'il problema', topic: 'abstrakt' },
  { de: 'die Lösung', it: 'la soluzione', topic: 'abstrakt' },
  { de: 'der Grund', it: 'il motivo', topic: 'abstrakt' },
  { de: 'das Ergebnis', it: 'il risultato', topic: 'abstrakt' },
  { de: 'die Möglichkeit', it: 'la possibilità', topic: 'abstrakt' },
  { de: 'der Unterschied', it: 'la differenza', topic: 'abstrakt' },
  { de: 'die Wahl', it: 'la scelta', topic: 'abstrakt' },
  { de: 'der Erfolg', it: 'il successo', topic: 'abstrakt' },
  { de: 'die Erfahrung', it: "l'esperienza", topic: 'abstrakt' },
  { de: 'das Wissen', it: 'la conoscenza', topic: 'abstrakt' },
  { de: 'die Meinung', it: "l'opinione", topic: 'abstrakt' },
  { de: 'die Frage', it: 'la domanda', topic: 'abstrakt' },
  { de: 'die Antwort', it: 'la risposta', topic: 'abstrakt' },
  { de: 'die Hilfe', it: "l'aiuto", topic: 'abstrakt' },
  { de: 'der Rat', it: 'il consiglio', topic: 'abstrakt' },
  { de: 'die Information', it: "l'informazione", topic: 'abstrakt' },
  { de: 'die Nachricht', it: 'il messaggio', topic: 'abstrakt' },
  { de: 'das Gespräch', it: 'la conversazione', topic: 'abstrakt' },
  { de: 'die Entscheidung', it: 'la decisione', topic: 'abstrakt' },
  { de: 'die Veränderung', it: 'il cambiamento', topic: 'abstrakt' },
  { de: 'der Plan', it: 'il piano', topic: 'abstrakt' },
  { de: 'das Ziel', it: "l'obiettivo", topic: 'abstrakt' },
  { de: 'die Aufgabe', it: 'il compito', topic: 'abstrakt' },
  { de: 'die Verantwortung', it: 'la responsabilità', topic: 'abstrakt' },
  { de: 'die Freiheit', it: 'la libertà', topic: 'abstrakt' },
  { de: 'die Wahrheit', it: 'la verità', topic: 'abstrakt' },
  { de: 'die Lüge', it: 'la bugia', topic: 'abstrakt' },
  { de: 'das Vertrauen', it: 'la fiducia', topic: 'abstrakt' },
  { de: 'der Respekt', it: 'il rispetto', topic: 'abstrakt' },
  { de: 'die Gesellschaft', it: 'la società', topic: 'abstrakt' },
  { de: 'die Kultur', it: 'la cultura', topic: 'abstrakt' },
  { de: 'die Geschichte', it: 'la storia', topic: 'abstrakt' },
  { de: 'die Politik', it: 'la politica', topic: 'abstrakt' },
  { de: 'die Wirtschaft', it: "l'economia", topic: 'abstrakt' },
  { de: 'die Umwelt', it: "l'ambiente", topic: 'abstrakt' },
  { de: 'die Energie', it: "l'energia", topic: 'abstrakt' },
  { de: 'das Recht', it: 'il diritto', topic: 'abstrakt' },
  { de: 'die Pflicht', it: 'il dovere', topic: 'abstrakt' },
  { de: 'der Vorteil', it: 'il vantaggio', topic: 'abstrakt' },
  { de: 'der Nachteil', it: 'lo svantaggio', topic: 'abstrakt' },
  { de: 'der Fortschritt', it: 'il progresso', topic: 'abstrakt' },
  { de: 'die Entwicklung', it: 'lo sviluppo', topic: 'abstrakt' },
  { de: 'die Situation', it: 'la situazione', topic: 'abstrakt' },
  { de: 'das Thema', it: "l'argomento", topic: 'abstrakt' },
  { de: 'der Bereich', it: "l'ambito / il settore", topic: 'abstrakt' },
  { de: 'das Beispiel', it: "l'esempio", topic: 'abstrakt' },
  { de: 'der Teil', it: 'la parte', topic: 'abstrakt' },
  { de: 'die Gruppe', it: 'il gruppo', topic: 'abstrakt' },
  { de: 'die Mehrheit', it: 'la maggioranza', topic: 'abstrakt' },
  { de: 'die Minderheit', it: 'la minoranza', topic: 'abstrakt' },
];

export const VOCAB_CATALOG: CatalogWord[] = [...CORE_VOCAB, ...IMPORTED_VOCAB, ...B1_VOCAB];
