import type { CatalogWord } from './vocab-catalog';

// B1 extension of the vocabulary catalog: frequent words for everyday topics at
// A2/B1 level (work, housing, environment, media, health, travel, feelings,
// connectors …) that the core and imported lists lacked. Hand-written; entries
// already present elsewhere in the catalog were removed. Walked after the rest.
export const B1_VOCAB: CatalogWord[] = [
  { de: 'trotzdem / jedenfalls', it: 'comunque', topic: 'grundwoerter' },
  { de: 'und doch', it: 'eppure', topic: 'grundwoerter' },
  { de: 'stattdessen / dagegen', it: 'invece', topic: 'grundwoerter' },
  { de: 'also / deshalb', it: 'quindi', topic: 'grundwoerter' },
  { de: 'also', it: 'dunque', topic: 'grundwoerter' },
  { de: 'inzwischen / mittlerweile', it: 'ormai', topic: 'grundwoerter' },
  { de: "vielleicht / schön wär's", it: 'magari', topic: 'grundwoerter' },
  { de: 'sogar', it: 'addirittura', topic: 'grundwoerter' },
  { de: 'leider', it: 'purtroppo', topic: 'grundwoerter' },
  { de: 'bisher', it: 'finora', topic: 'grundwoerter' },
  { de: 'inzwischen / währenddessen', it: 'intanto', topic: 'grundwoerter' },
  { de: 'im Gegenteil / vielmehr', it: 'anzi', topic: 'grundwoerter' },
  { de: 'jedoch', it: 'tuttavia', topic: 'grundwoerter' },
  { de: 'während', it: 'mentre', topic: 'grundwoerter' },
  { de: 'solange / bis', it: 'finché', topic: 'grundwoerter' },
  { de: 'damit', it: 'affinché', topic: 'grundwoerter' },
  { de: 'trotz / obwohl', it: 'nonostante', topic: 'grundwoerter' },
  { de: 'da (weil)', it: 'siccome', topic: 'grundwoerter' },
  { de: 'da / weil', it: 'dato che', topic: 'grundwoerter' },
  { de: 'es sei denn', it: 'a meno che', topic: 'grundwoerter' },
  { de: 'weder … noch', it: 'né … né', topic: 'grundwoerter' },
  { de: 'nicht einmal', it: 'neppure', topic: 'grundwoerter' },
  { de: 'oder', it: 'oppure', topic: 'grundwoerter' },
  { de: 'sogar', it: 'persino', topic: 'grundwoerter' },
  { de: 'genau', it: 'appunto', topic: 'grundwoerter' },
  { de: 'nach und nach', it: 'piano piano', topic: 'grundwoerter' },
  { de: 'plötzlich', it: "all'improvviso", topic: 'grundwoerter' },
  { de: 'normalerweise', it: 'di solito', topic: 'grundwoerter' },
  { de: 'früher oder später', it: 'prima o poi', topic: 'grundwoerter' },
  { de: 'übrigens', it: 'a proposito', topic: 'grundwoerter' },
  { de: 'eilig / schnell', it: 'in fretta', topic: 'grundwoerter' },
  { de: 'zufällig', it: 'per caso', topic: 'grundwoerter' },
  { de: 'im Ernst', it: 'sul serio', topic: 'grundwoerter' },
  { de: 'allein', it: 'da solo', topic: 'grundwoerter' },
  { de: 'ab und zu', it: 'ogni tanto', topic: 'grundwoerter' },
  { de: 'innerhalb / bis spätestens', it: 'entro', topic: 'grundwoerter' },
  { de: 'außer / über … hinaus', it: 'oltre', topic: 'grundwoerter' },
  { de: 'statt', it: 'invece di', topic: 'grundwoerter' },
  { de: 'wegen', it: 'a causa di', topic: 'grundwoerter' },
  { de: 'dank', it: 'grazie a', topic: 'grundwoerter' },
  { de: 'kurz gesagt', it: 'insomma', topic: 'grundwoerter' },
  { de: 'auf jeden Fall', it: "senz'altro", topic: 'grundwoerter' },
  { de: 'außer', it: 'eccetto', topic: 'grundwoerter' },
  { de: 'außer', it: 'tranne', topic: 'grundwoerter' },
  { de: 'bei', it: 'presso', topic: 'grundwoerter' },
  { de: 'nicht einmal', it: 'nemmeno', topic: 'grundwoerter' },
  { de: 'etwas', it: 'qualcosa', topic: 'grundwoerter' },
  { de: 'jemand', it: 'qualcuno', topic: 'grundwoerter' },
  { de: 'nichts', it: 'niente', topic: 'grundwoerter' },
  { de: 'niemand', it: 'nessuno', topic: 'grundwoerter' },
  { de: 'jeder beliebige', it: 'qualsiasi', topic: 'grundwoerter' },
  { de: 'einige', it: 'alcuni', topic: 'grundwoerter' },
  { de: 'ziemlich viel', it: 'parecchio', topic: 'grundwoerter' },
  { de: 'jeder (einzelne)', it: 'ciascuno', topic: 'grundwoerter' },
  { de: 'beide', it: 'entrambi', topic: 'grundwoerter' },
  { de: 'sonst', it: 'altrimenti', topic: 'grundwoerter' },
  { de: 'nirgendwo', it: 'da nessuna parte', topic: 'grundwoerter' },
  { de: 'irgendwo', it: 'da qualche parte', topic: 'grundwoerter' },
  { de: 'neben', it: 'accanto a', topic: 'grundwoerter' },
  { de: 'gegenüber', it: 'di fronte a', topic: 'grundwoerter' },
  { de: 'mitten in', it: 'in mezzo a', topic: 'grundwoerter' },
  { de: 'anstelle von', it: 'al posto di', topic: 'grundwoerter' },
  { de: 'abgesehen von', it: 'a parte', topic: 'grundwoerter' },
  { de: 'bezüglich', it: 'riguardo a', topic: 'grundwoerter' },
  { de: 'auf Grundlage von', it: 'in base a', topic: 'grundwoerter' },
  { de: 'übrigens / im Übrigen', it: 'del resto', topic: 'grundwoerter' },
  { de: 'einverstanden', it: "d'accordo", topic: 'grundwoerter' },
  { de: 'hier ist / da ist', it: 'ecco', topic: 'grundwoerter' },
  { de: 'die Frist / das Ablaufdatum', it: 'la scadenza', topic: 'zeit' },
  { de: 'die Verspätung', it: 'il ritardo', topic: 'zeit' },
  { de: 'der Vorsprung / die Anzahlung', it: "l'anticipo", topic: 'zeit' },
  { de: 'der Zeitraum', it: 'il periodo', topic: 'zeit' },
  { de: 'die Epoche', it: "l'epoca", topic: 'zeit' },
  { de: 'die Zwischenzeit', it: 'il frattempo', topic: 'zeit' },
  { de: 'der Moment', it: 'il momento', topic: 'zeit' },
  { de: 'der Augenblick', it: "l'attimo", topic: 'zeit' },
  { de: 'die Zukunft', it: 'il futuro', topic: 'zeit' },
  { de: 'die Gegenwart', it: 'il presente', topic: 'zeit' },
  { de: 'die Mitternacht', it: 'la mezzanotte', topic: 'zeit' },
  { de: 'der Mittag', it: 'il mezzogiorno', topic: 'zeit' },
  { de: 'die Morgendämmerung', it: "l'alba", topic: 'zeit' },
  { de: 'der Sonnenuntergang', it: 'il tramonto', topic: 'zeit' },
  { de: 'der Kalender', it: 'il calendario', topic: 'zeit' },
  { de: 'der Jahrestag', it: "l'anniversario", topic: 'zeit' },
  { de: 'das Jahrzehnt', it: 'il decennio', topic: 'zeit' },
  { de: 'der Fahrplan / die Öffnungszeiten', it: "l'orario", topic: 'zeit' },
  { de: 'pünktlich', it: 'puntuale', topic: 'zeit' },
  { de: 'neu / kürzlich', it: 'recente', topic: 'zeit' },
  { de: 'vorherig', it: 'precedente', topic: 'zeit' },
  { de: 'folgend', it: 'successivo', topic: 'zeit' },
  { de: 'wöchentlich', it: 'settimanale', topic: 'zeit' },
  { de: 'monatlich', it: 'mensile', topic: 'zeit' },
  { de: 'bis wann', it: 'fino a quando', topic: 'zeit' },
  { de: 'seit wann', it: 'da quando', topic: 'zeit' },
  { de: 'letztes Jahr', it: "l'anno scorso", topic: 'zeit' },
  { de: 'nächste Woche', it: 'la settimana prossima', topic: 'zeit' },
  { de: 'heute Morgen', it: 'stamattina', topic: 'zeit' },
  { de: 'heute Nacht', it: 'stanotte', topic: 'zeit' },
  { de: 'gestern Abend', it: 'ieri sera', topic: 'zeit' },
  { de: 'morgen früh', it: 'domani mattina', topic: 'zeit' },
  { de: 'inzwischen', it: 'nel frattempo', topic: 'zeit' },
  { de: 'die Vorspeise', it: "l'antipasto", topic: 'essen' },
  { de: 'der erste Gang (Pasta, Risotto)', it: 'il primo piatto', topic: 'essen' },
  { de: 'der Hauptgang', it: 'il secondo piatto', topic: 'essen' },
  { de: 'die Beilage', it: 'il contorno', topic: 'essen' },
  { de: 'die Speisekarte', it: 'il menù', topic: 'essen' },
  { de: 'das Gedeck (Gebühr)', it: 'il coperto', topic: 'essen' },
  { de: 'der Topf', it: 'la pentola', topic: 'essen' },
  { de: 'die Pfanne', it: 'la padella', topic: 'essen' },
  { de: 'das Gewürz', it: 'la spezia', topic: 'essen' },
  { de: 'die Chili', it: 'il peperoncino', topic: 'essen' },
  { de: 'das Basilikum', it: 'il basilico', topic: 'essen' },
  { de: 'der Rosmarin', it: 'il rosmarino', topic: 'essen' },
  { de: 'die Petersilie', it: 'il prezzemolo', topic: 'essen' },
  { de: 'die Zucchini', it: 'la zucchina', topic: 'essen' },
  { de: 'die Aubergine', it: 'la melanzana', topic: 'essen' },
  { de: 'die Paprika', it: 'il peperone', topic: 'essen' },
  { de: 'der Spinat', it: 'gli spinaci', topic: 'essen' },
  { de: 'die Pilze', it: 'i funghi', topic: 'essen' },
  { de: 'die Erbsen', it: 'i piselli', topic: 'essen' },
  { de: 'die Linsen', it: 'le lenticchie', topic: 'essen' },
  { de: 'die Kichererbsen', it: 'i ceci', topic: 'essen' },
  { de: 'die Walnuss', it: 'la noce', topic: 'essen' },
  { de: 'die Mandel', it: 'la mandorla', topic: 'essen' },
  { de: 'der Pfirsich', it: 'la pesca', topic: 'essen' },
  { de: 'die Pflaume', it: 'la prugna', topic: 'essen' },
  { de: 'die Ananas', it: "l'ananas", topic: 'essen' },
  { de: 'der Honig', it: 'il miele', topic: 'essen' },
  { de: 'die Hefe', it: 'il lievito', topic: 'essen' },
  { de: 'die Salami', it: 'il salame', topic: 'essen' },
  { de: 'der Mozzarella', it: 'la mozzarella', topic: 'essen' },
  { de: 'der Ricotta', it: 'la ricotta', topic: 'essen' },
  { de: 'der Parmesan', it: 'il parmigiano', topic: 'essen' },
  { de: 'der Thunfisch', it: 'il tonno', topic: 'essen' },
  { de: 'die Garnelen', it: 'i gamberi', topic: 'essen' },
  { de: 'die Miesmuscheln', it: 'le cozze', topic: 'essen' },
  { de: 'der Oktopus', it: 'il polpo', topic: 'essen' },
  { de: 'der Keks', it: 'il biscotto', topic: 'essen' },
  { de: 'der Snack (am Nachmittag)', it: 'la merenda', topic: 'essen' },
  { de: 'der Imbiss', it: 'lo spuntino', topic: 'essen' },
  { de: 'das Getränk', it: 'la bevanda', topic: 'essen' },
  { de: 'das Sprudelwasser', it: "l'acqua frizzante", topic: 'essen' },
  { de: 'das stille Wasser', it: "l'acqua naturale", topic: 'essen' },
  { de: 'der frisch gepresste Saft', it: 'la spremuta', topic: 'essen' },
  { de: 'der Aperitif', it: "l'aperitivo", topic: 'essen' },
  { de: 'das Hörnchen / das Croissant', it: 'il cornetto', topic: 'essen' },
  { de: 'der Cappuccino', it: 'il cappuccino', topic: 'essen' },
  { de: 'die Pizzeria', it: 'la pizzeria', topic: 'essen' },
  { de: 'die Trattoria (einfaches Restaurant)', it: 'la trattoria', topic: 'essen' },
  { de: 'vegetarisch', it: 'vegetariano', topic: 'essen' },
  { de: 'vegan', it: 'vegano', topic: 'essen' },
  { de: 'Vollkorn-', it: 'integrale', topic: 'essen' },
  { de: 'frittiert', it: 'fritto', topic: 'essen' },
  { de: 'gekocht', it: 'bollito', topic: 'essen' },
  { de: 'gebraten / der Braten', it: 'arrosto', topic: 'essen' },
  { de: 'im Ofen gebacken', it: 'al forno', topic: 'essen' },
  { de: 'gekocht / gar', it: 'cotto', topic: 'essen' },
  { de: 'tiefgefroren', it: 'surgelato', topic: 'essen' },
  { de: 'würzig / schmackhaft', it: 'saporito', topic: 'essen' },
  { de: 'fade', it: 'insipido', topic: 'essen' },
  { de: 'die Portion', it: 'la porzione', topic: 'essen' },
  { de: '100 Gramm', it: 'etto', topic: 'essen' },
  { de: 'das Kilo', it: 'il chilo', topic: 'essen' },
  { de: 'der Liter', it: 'il litro', topic: 'essen' },
  { de: 'die Scheibe', it: 'la fetta', topic: 'essen' },
  { de: 'das Stückchen', it: 'il pezzetto', topic: 'essen' },
  { de: 'das Frühstück in der Bar', it: 'la colazione al bar', topic: 'essen' },
  { de: 'die Kellnerin', it: 'la cameriera', topic: 'essen' },
  { de: 'die Einkaufsliste', it: 'la lista della spesa', topic: 'essen' },
  { de: 'den Tisch decken', it: 'apparecchiare', topic: 'essen' },
  { de: 'den Tisch abräumen', it: 'sparecchiare', topic: 'essen' },
  { de: 'probieren (Essen)', it: 'assaggiare', topic: 'essen' },
  { de: 'umrühren / mischen', it: 'mescolare', topic: 'essen' },
  { de: 'frittieren', it: 'friggere', topic: 'essen' },
  { de: 'in Stücke schneiden', it: 'tagliare a pezzi', topic: 'essen' },
  { de: 'die Miete', it: "l'affitto", topic: 'wohnen' },
  { de: 'die Rechnung (Strom, Gas …)', it: 'la bolletta', topic: 'wohnen' },
  { de: 'das Mehrfamilienhaus / die Hausgemeinschaft', it: 'il condominio', topic: 'wohnen' },
  { de: 'der Mieter', it: "l'inquilino", topic: 'wohnen' },
  { de: 'der Eigentümer', it: 'il proprietario', topic: 'wohnen' },
  { de: 'der Umzug', it: 'il trasloco', topic: 'wohnen' },
  { de: 'die Einrichtung', it: "l'arredamento", topic: 'wohnen' },
  { de: 'die Heizung', it: 'il riscaldamento', topic: 'wohnen' },
  { de: 'die Klimaanlage', it: "l'aria condizionata", topic: 'wohnen' },
  { de: 'der Keller', it: 'la cantina', topic: 'wohnen' },
  { de: 'der Dachboden', it: 'la soffitta', topic: 'wohnen' },
  { de: 'das Waschbecken', it: 'il lavandino', topic: 'wohnen' },
  { de: 'der Wasserhahn', it: 'il rubinetto', topic: 'wohnen' },
  { de: 'die Dusche', it: 'la doccia', topic: 'wohnen' },
  { de: 'die Badewanne', it: 'la vasca da bagno', topic: 'wohnen' },
  { de: 'der Backofen', it: 'il forno', topic: 'wohnen' },
  { de: 'die Mikrowelle', it: 'il microonde', topic: 'wohnen' },
  { de: 'die Spülmaschine', it: 'la lavastoviglie', topic: 'wohnen' },
  { de: 'der Müll', it: 'la spazzatura', topic: 'wohnen' },
  { de: 'das Haushaltsgerät', it: "l'elettrodomestico", topic: 'wohnen' },
  { de: 'die Gegensprechanlage', it: 'il citofono', topic: 'wohnen' },
  { de: 'die Klingel', it: 'il campanello', topic: 'wohnen' },
  { de: 'der Treppenabsatz', it: 'il pianerottolo', topic: 'wohnen' },
  { de: 'die Terrasse', it: 'la terrazza', topic: 'wohnen' },
  { de: 'das Gärtchen', it: 'il giardinetto', topic: 'wohnen' },
  { de: 'der Nachttisch', it: 'il comodino', topic: 'wohnen' },
  { de: 'der Sessel', it: 'la poltrona', topic: 'wohnen' },
  { de: 'das Bücherregal / die Buchhandlung', it: 'la libreria', topic: 'wohnen' },
  { de: 'die Steckdose', it: 'la presa', topic: 'wohnen' },
  { de: 'der Lichtschalter', it: "l'interruttore", topic: 'wohnen' },
  { de: 'der Kronleuchter / die Deckenlampe', it: 'il lampadario', topic: 'wohnen' },
  { de: 'das Wandbrett', it: 'la mensola', topic: 'wohnen' },
  { de: 'die Bettwäsche', it: 'le lenzuola', topic: 'wohnen' },
  { de: 'der Hausputz', it: 'le pulizie', topic: 'wohnen' },
  { de: 'die Wäsche', it: 'il bucato', topic: 'wohnen' },
  { de: 'bügeln', it: 'stirare', topic: 'wohnen' },
  { de: 'umziehen', it: 'traslocare', topic: 'wohnen' },
  { de: 'einrichten', it: 'arredare', topic: 'wohnen' },
  { de: 'sich die Wohnung teilen', it: "condividere l'appartamento", topic: 'wohnen' },
  { de: 'der Mitbewohner', it: 'il coinquilino', topic: 'wohnen' },
  { de: 'die Nachbarschaft', it: 'il vicinato', topic: 'wohnen' },
  { de: 'das Stadtviertel', it: 'il quartiere', topic: 'wohnen' },
  { de: 'der Stadtrand', it: 'la periferia', topic: 'wohnen' },
  { de: 'die Altstadt', it: 'il centro storico', topic: 'wohnen' },
  { de: 'der Bürgersteig', it: 'il marciapiede', topic: 'stadt' },
  { de: 'die Ampel', it: 'il semaforo', topic: 'stadt' },
  { de: 'die Kreuzung', it: "l'incrocio", topic: 'stadt' },
  { de: 'der Zebrastreifen', it: 'le strisce pedonali', topic: 'stadt' },
  { de: 'der Kreisverkehr', it: 'la rotonda', topic: 'stadt' },
  { de: 'die Allee', it: 'il viale', topic: 'stadt' },
  { de: 'die Gasse', it: 'il vicolo', topic: 'stadt' },
  { de: 'der Brunnen', it: 'la fontana', topic: 'stadt' },
  { de: 'das Denkmal', it: 'il monumento', topic: 'stadt' },
  { de: 'der Kiosk', it: "l'edicola", topic: 'stadt' },
  { de: 'der Tabakladen', it: 'la tabaccheria', topic: 'stadt' },
  { de: 'die Konditorei', it: 'la pasticceria', topic: 'stadt' },
  { de: 'die Eisdiele', it: 'la gelateria', topic: 'stadt' },
  { de: 'der Eisenwarenladen', it: 'la ferramenta', topic: 'stadt' },
  { de: 'die Wäscherei', it: 'la lavanderia', topic: 'stadt' },
  { de: 'das Bekleidungsgeschäft', it: 'il negozio di abbigliamento', topic: 'stadt' },
  { de: 'das Einkaufszentrum', it: 'il centro commerciale', topic: 'stadt' },
  { de: 'der Parkplatz', it: 'il parcheggio', topic: 'stadt' },
  { de: 'das Polizeipräsidium', it: 'la questura', topic: 'stadt' },
  { de: 'die Touristeninformation', it: "l'ufficio turistico", topic: 'stadt' },
  { de: 'das Stadion', it: 'lo stadio', topic: 'stadt' },
  { de: 'das Fitnessstudio / die Turnhalle', it: 'la palestra', topic: 'stadt' },
  { de: 'das Schwimmbad', it: 'la piscina', topic: 'stadt' },
  { de: 'der Kindergarten', it: "l'asilo", topic: 'stadt' },
  { de: 'der Einwohner', it: "l'abitante", topic: 'stadt' },
  { de: 'der Verkehr', it: 'il traffico', topic: 'stadt' },
  { de: 'die Fußgängerzone', it: 'la zona pedonale', topic: 'stadt' },
  { de: 'die Fußgängerzone', it: "l'isola pedonale", topic: 'stadt' },
  { de: 'die Bushaltestelle', it: "la fermata dell'autobus", topic: 'stadt' },
  { de: 'der Flug', it: 'il volo', topic: 'reisen' },
  { de: 'das Boarding / die Einschiffung', it: "l'imbarco", topic: 'reisen' },
  { de: 'die Bordkarte', it: "la carta d'imbarco", topic: 'reisen' },
  { de: 'das Handgepäck', it: 'il bagaglio a mano', topic: 'reisen' },
  { de: 'der Zoll', it: 'la dogana', topic: 'reisen' },
  { de: 'die Grenze', it: 'la frontiera', topic: 'reisen' },
  { de: 'die Jugendherberge', it: "l'ostello", topic: 'reisen' },
  { de: 'der Campingplatz', it: 'il campeggio', topic: 'reisen' },
  { de: 'die Vermietung / der Verleih', it: 'il noleggio', topic: 'reisen' },
  { de: 'die Autobahn', it: "l'autostrada", topic: 'reisen' },
  { de: 'die Maut', it: 'il pedaggio', topic: 'reisen' },
  { de: 'die Tankstelle', it: 'il distributore', topic: 'reisen' },
  { de: 'der Strafzettel', it: 'la multa', topic: 'reisen' },
  { de: 'das Gleis', it: 'il binario', topic: 'reisen' },
  { de: 'der Reiseführer / die Führung', it: 'la guida', topic: 'reisen' },
  { de: 'die Reiseroute', it: "l'itinerario", topic: 'reisen' },
  { de: 'das Andenken', it: 'il souvenir', topic: 'reisen' },
  { de: 'die Kreuzfahrt', it: 'la crociera', topic: 'reisen' },
  { de: 'der Reisende', it: 'il viaggiatore', topic: 'reisen' },
  { de: 'der Urlaub', it: 'la vacanza', topic: 'reisen' },
  { de: 'das Drei-Sterne-Hotel', it: "l'albergo a tre stelle", topic: 'reisen' },
  { de: 'das Einzelzimmer', it: 'la camera singola', topic: 'reisen' },
  { de: 'das Doppelzimmer', it: 'la camera doppia', topic: 'reisen' },
  { de: 'die Halbpension', it: 'la mezza pensione', topic: 'reisen' },
  { de: 'die Vollpension', it: 'la pensione completa', topic: 'reisen' },
  { de: 'der Check-in', it: 'il check-in', topic: 'reisen' },
  { de: 'hin und zurück', it: 'andata e ritorno', topic: 'reisen' },
  { de: 'einfache Fahrt', it: 'sola andata', topic: 'reisen' },
  { de: 'der Fahrkartenschalter', it: 'la biglietteria', topic: 'reisen' },
  { de: 'der Wartesaal', it: "la sala d'attesa", topic: 'reisen' },
  { de: 'die Landung', it: "l'atterraggio", topic: 'reisen' },
  { de: 'der Start (Flugzeug)', it: 'il decollo', topic: 'reisen' },
  { de: 'der Sicherheitsgurt', it: 'la cintura di sicurezza', topic: 'reisen' },
  { de: 'der Führerschein', it: 'la patente', topic: 'reisen' },
  { de: 'der Personalausweis', it: "la carta d'identità", topic: 'reisen' },
  { de: 'im Ausland', it: "all'estero", topic: 'reisen' },
  { de: 'mieten (Auto, Fahrrad)', it: 'noleggiare', topic: 'reisen' },
  { de: 'abfahren', it: 'partire', topic: 'reisen' },
  { de: 'den Zug verpassen', it: 'perdere il treno', topic: 'reisen' },
  { de: 'die Koffer packen', it: 'fare le valigie', topic: 'reisen' },
  { de: 'tanken', it: 'fare benzina', topic: 'reisen' },
  { de: 'parken', it: 'parcheggiare', topic: 'reisen' },
  { de: 'starten (Flugzeug)', it: 'decollare', topic: 'reisen' },
  { de: 'das Vorstellungsgespräch', it: 'il colloquio di lavoro', topic: 'arbeit' },
  { de: 'der Lebenslauf', it: 'il curriculum', topic: 'arbeit' },
  { de: 'der Bewerber', it: 'il candidato', topic: 'arbeit' },
  { de: 'die Bewerbung', it: 'la candidatura', topic: 'arbeit' },
  { de: 'die Arbeitslosigkeit', it: 'la disoccupazione', topic: 'arbeit' },
  { de: 'arbeitslos', it: 'disoccupato', topic: 'arbeit' },
  { de: 'die Schicht', it: 'il turno', topic: 'arbeit' },
  { de: 'die Überstunden', it: 'gli straordinari', topic: 'arbeit' },
  { de: 'die Gewerkschaft', it: 'il sindacato', topic: 'arbeit' },
  { de: 'der Arbeitgeber', it: 'il datore di lavoro', topic: 'arbeit' },
  { de: 'die Karriere', it: 'la carriera', topic: 'arbeit' },
  { de: 'die Ausbildung', it: 'la formazione', topic: 'arbeit' },
  { de: 'das Praktikum', it: 'il tirocinio', topic: 'arbeit' },
  { de: 'der Praktikant', it: 'lo stagista', topic: 'arbeit' },
  { de: 'die Stellenanzeige', it: "l'annuncio di lavoro", topic: 'arbeit' },
  { de: 'der Arbeitsplatz', it: 'il posto di lavoro', topic: 'arbeit' },
  { de: 'der Mitarbeiter', it: 'il collaboratore', topic: 'arbeit' },
  { de: 'die Führungskraft', it: 'il dirigente', topic: 'arbeit' },
  { de: 'der Freiberufler', it: 'il libero professionista', topic: 'arbeit' },
  { de: 'die Teilzeitarbeit', it: 'il lavoro part-time', topic: 'arbeit' },
  { de: 'die Vollzeitarbeit', it: 'il lavoro a tempo pieno', topic: 'arbeit' },
  { de: 'die Arbeit von zu Hause', it: 'il lavoro da casa', topic: 'arbeit' },
  { de: 'das Homeoffice', it: 'lo smart working', topic: 'arbeit' },
  { de: 'die Gehaltserhöhung', it: "l'aumento", topic: 'arbeit' },
  { de: 'die Kündigung', it: 'il licenziamento', topic: 'arbeit' },
  { de: 'der Rentner', it: 'il pensionato', topic: 'arbeit' },
  { de: 'der Steuerberater', it: 'il commercialista', topic: 'arbeit' },
  { de: 'der Klempner', it: "l'idraulico", topic: 'arbeit' },
  { de: 'der Elektriker', it: "l'elettricista", topic: 'arbeit' },
  { de: 'der Tischler', it: 'il falegname', topic: 'arbeit' },
  { de: 'der Maurer', it: 'il muratore', topic: 'arbeit' },
  { de: 'der Krankenpfleger', it: "l'infermiere", topic: 'arbeit' },
  { de: 'der Apotheker', it: 'il farmacista', topic: 'arbeit' },
  { de: 'die Angestellte', it: "l'impiegata", topic: 'arbeit' },
  { de: 'der Kassierer', it: 'il cassiere', topic: 'arbeit' },
  { de: 'der Barkeeper', it: 'il barista', topic: 'arbeit' },
  { de: 'der Übersetzer', it: 'il traduttore', topic: 'arbeit' },
  { de: 'einstellen', it: 'assumere', topic: 'arbeit' },
  { de: 'kündigen (jemandem)', it: 'licenziare', topic: 'arbeit' },
  { de: 'kündigen (selbst)', it: 'licenziarsi', topic: 'arbeit' },
  { de: 'sich bewerben', it: 'candidarsi', topic: 'arbeit' },
  { de: 'selbstständig arbeiten', it: 'lavorare in proprio', topic: 'arbeit' },
  { de: 'Karriere machen', it: 'fare carriera', topic: 'arbeit' },
  { de: 'in Rente gehen', it: 'andare in pensione', topic: 'arbeit' },
  { de: 'der Hochschulabschluss', it: 'la laurea', topic: 'schule' },
  { de: 'den Abschluss machen (Uni)', it: 'laurearsi', topic: 'schule' },
  { de: 'die Fakultät', it: 'la facoltà', topic: 'schule' },
  { de: 'das Abitur', it: "l'esame di maturità", topic: 'schule' },
  { de: 'das Gymnasium', it: 'il liceo', topic: 'schule' },
  { de: 'die Grundschule', it: 'la scuola elementare', topic: 'schule' },
  { de: 'die Mittelschule', it: 'la scuola media', topic: 'schule' },
  { de: 'der Klassenkamerad', it: 'il compagno di classe', topic: 'schule' },
  { de: 'die Lehrerin', it: 'la professoressa', topic: 'schule' },
  { de: 'der Schulleiter', it: 'il preside', topic: 'schule' },
  { de: 'der Kurs', it: 'il corso', topic: 'schule' },
  { de: 'die Anmeldung', it: "l'iscrizione", topic: 'schule' },
  { de: 'das Stipendium', it: 'la borsa di studio', topic: 'schule' },
  { de: 'die Notizen / die Mitschrift', it: 'gli appunti', topic: 'schule' },
  { de: 'die Zusammenfassung', it: 'il riassunto', topic: 'schule' },
  { de: 'die Abschlussarbeit', it: 'la tesi', topic: 'schule' },
  { de: 'die Forschung / die Recherche', it: 'la ricerca', topic: 'schule' },
  { de: 'der Wortschatz / das Wörterbuch', it: 'il vocabolario', topic: 'schule' },
  { de: 'die Grammatik', it: 'la grammatica', topic: 'schule' },
  { de: 'die Aussprache', it: 'la pronuncia', topic: 'schule' },
  { de: 'durchfallen lassen', it: 'bocciare', topic: 'schule' },
  { de: 'versetzen / bestehen lassen', it: 'promuovere', topic: 'schule' },
  { de: 'besuchen (Schule, Kurs)', it: 'frequentare', topic: 'schule' },
  { de: 'sich anmelden', it: 'iscriversi', topic: 'schule' },
  { de: 'wiederholen (Lernstoff)', it: 'ripassare', topic: 'schule' },
  { de: 'auswendig lernen', it: 'imparare a memoria', topic: 'schule' },
  { de: 'eine Prüfung bestehen', it: 'superare un esame', topic: 'schule' },
  { de: 'die Mathematik', it: 'la matematica', topic: 'schule' },
  { de: 'die Kunstgeschichte', it: "la storia dell'arte", topic: 'schule' },
  { de: 'die Fremdsprache', it: 'la lingua straniera', topic: 'schule' },
  { de: 'die Muttersprache', it: 'la madrelingua', topic: 'schule' },
  { de: 'die Anwendung / die App', it: "l'applicazione", topic: 'technik' },
  { de: 'die Website', it: 'il sito internet', topic: 'technik' },
  { de: 'das soziale Netzwerk', it: 'il social network', topic: 'technik' },
  { de: 'die Benachrichtigung', it: 'la notifica', topic: 'technik' },
  { de: 'der Anhang', it: "l'allegato", topic: 'technik' },
  { de: 'das Profil', it: 'il profilo', topic: 'technik' },
  { de: 'das Konto (online)', it: "l'account", topic: 'technik' },
  { de: 'der Benutzername', it: 'il nome utente', topic: 'technik' },
  { de: 'das Ladegerät', it: 'il caricabatterie', topic: 'technik' },
  { de: 'der Akku / die Batterie', it: 'la batteria', topic: 'technik' },
  { de: 'die Kopfhörer', it: 'le cuffie', topic: 'technik' },
  { de: 'das Tablet', it: 'il tablet', topic: 'technik' },
  { de: 'der Laptop', it: 'il portatile', topic: 'technik' },
  { de: 'der USB-Stick', it: 'la chiavetta', topic: 'technik' },
  { de: 'die Verbindung', it: 'la connessione', topic: 'technik' },
  { de: 'das WLAN', it: 'il wifi', topic: 'technik' },
  { de: 'das Update', it: "l'aggiornamento", topic: 'technik' },
  { de: 'die Taste', it: 'il tasto', topic: 'technik' },
  { de: 'der Chat', it: 'la chat', topic: 'technik' },
  { de: 'der Videoanruf', it: 'la videochiamata', topic: 'technik' },
  { de: 'die Sprachnachricht', it: 'il messaggio vocale', topic: 'technik' },
  { de: 'aufladen', it: 'ricaricare', topic: 'technik' },
  { de: 'herunterladen', it: 'scaricare', topic: 'technik' },
  { de: 'installieren', it: 'installare', topic: 'technik' },
  { de: 'löschen', it: 'cancellare', topic: 'technik' },
  { de: 'drucken', it: 'stampare', topic: 'technik' },
  { de: 'klicken', it: 'cliccare', topic: 'technik' },
  { de: 'ausschalten', it: 'spegnere', topic: 'technik' },
  { de: 'verbinden', it: 'collegare', topic: 'technik' },
  { de: 'funktionieren', it: 'funzionare', topic: 'technik' },
  { de: 'sich aufhängen (Gerät)', it: 'bloccarsi', topic: 'technik' },
  { de: 'kaputt / die Panne', it: 'guasto', topic: 'technik' },
  { de: 'das Training', it: "l'allenamento", topic: 'freizeit' },
  { de: 'die Mannschaft', it: 'la squadra', topic: 'freizeit' },
  { de: 'das Spiel (Sport)', it: 'la partita', topic: 'freizeit' },
  { de: 'der Fan', it: 'il tifoso', topic: 'freizeit' },
  { de: 'die Meisterschaft', it: 'il campionato', topic: 'freizeit' },
  { de: 'der Wettkampf', it: 'la gara', topic: 'freizeit' },
  { de: 'der Ausflug / die Wanderung', it: "l'escursione", topic: 'freizeit' },
  { de: 'der Spaziergang', it: 'la passeggiata', topic: 'freizeit' },
  { de: 'die Vorstellung / die Show', it: 'lo spettacolo', topic: 'freizeit' },
  { de: 'das Festival', it: 'il festival', topic: 'freizeit' },
  { de: 'die Warteschlange', it: 'la coda', topic: 'freizeit' },
  { de: 'die Eintrittskarte', it: "il biglietto d'ingresso", topic: 'freizeit' },
  { de: 'die Fernsehserie', it: 'la serie tv', topic: 'freizeit' },
  { de: 'die Nachrichten (TV)', it: 'il telegiornale', topic: 'freizeit' },
  { de: 'die Sendung / das Programm', it: 'il programma', topic: 'freizeit' },
  { de: 'die Werbung', it: 'la pubblicità', topic: 'freizeit' },
  { de: 'die Nachricht (Neuigkeit)', it: 'la notizia', topic: 'freizeit' },
  { de: 'das Interview', it: "l'intervista", topic: 'freizeit' },
  { de: 'der Sender / der Kanal', it: 'il canale', topic: 'freizeit' },
  { de: 'das Abonnement', it: "l'abbonamento", topic: 'freizeit' },
  { de: 'das Videospiel', it: 'il videogioco', topic: 'freizeit' },
  { de: 'die Spielkarten', it: 'le carte da gioco', topic: 'freizeit' },
  { de: 'das Schach', it: 'gli scacchi', topic: 'freizeit' },
  { de: 'die Gartenarbeit', it: 'il giardinaggio', topic: 'freizeit' },
  { de: 'das Lesen', it: 'la lettura', topic: 'freizeit' },
  { de: 'das Yoga', it: 'lo yoga', topic: 'freizeit' },
  { de: 'das Laufen / das Rennen', it: 'la corsa', topic: 'freizeit' },
  { de: 'der Radsport', it: 'il ciclismo', topic: 'freizeit' },
  { de: 'das Schwimmen', it: 'il nuoto', topic: 'freizeit' },
  { de: 'der Volleyball', it: 'la pallavolo', topic: 'freizeit' },
  { de: 'der Basketball', it: 'la pallacanestro', topic: 'freizeit' },
  { de: 'der freie Strand', it: 'la spiaggia libera', topic: 'freizeit' },
  { de: 'der Sonnenschirm', it: "l'ombrellone", topic: 'freizeit' },
  { de: 'der Liegestuhl', it: 'la sdraio', topic: 'freizeit' },
  { de: 'die Sonnencreme', it: 'la crema solare', topic: 'freizeit' },
  { de: 'braun werden', it: 'abbronzarsi', topic: 'freizeit' },
  { de: 'trainieren', it: 'allenarsi', topic: 'freizeit' },
  { de: 'sich amüsieren', it: 'divertirsi', topic: 'freizeit' },
  { de: 'sich entspannen', it: 'rilassarsi', topic: 'freizeit' },
  { de: 'anfeuern / Fan sein', it: 'tifare', topic: 'freizeit' },
  { de: 'einen Spaziergang machen', it: 'fare una passeggiata', topic: 'freizeit' },
  { de: 'Sport treiben', it: 'fare sport', topic: 'freizeit' },
  { de: 'mit Freunden ausgehen', it: 'uscire con gli amici', topic: 'freizeit' },
  { de: 'die Notaufnahme', it: 'il pronto soccorso', topic: 'gesundheit' },
  { de: 'das Symptom', it: 'il sintomo', topic: 'gesundheit' },
  { de: 'die Kopfschmerzen', it: 'il mal di testa', topic: 'gesundheit' },
  { de: 'die Halsschmerzen', it: 'il mal di gola', topic: 'gesundheit' },
  { de: 'die Bauchschmerzen', it: 'il mal di pancia', topic: 'gesundheit' },
  { de: 'die Impfung', it: 'il vaccino', topic: 'gesundheit' },
  { de: 'das Medikament', it: 'il farmaco', topic: 'gesundheit' },
  { de: 'das Pflaster', it: 'il cerotto', topic: 'gesundheit' },
  { de: 'das Thermometer', it: 'il termometro', topic: 'gesundheit' },
  { de: 'der Stress', it: 'lo stress', topic: 'gesundheit' },
  { de: 'die Untersuchung / der Besuch', it: 'la visita', topic: 'gesundheit' },
  { de: 'die Einlieferung ins Krankenhaus', it: 'il ricovero', topic: 'gesundheit' },
  { de: 'die Genesung', it: 'la guarigione', topic: 'gesundheit' },
  { de: 'die Arztpraxis', it: "l'ambulatorio", topic: 'gesundheit' },
  { de: 'der Hausarzt', it: 'il medico di famiglia', topic: 'gesundheit' },
  { de: 'die Brille', it: 'gli occhiali da vista', topic: 'gesundheit' },
  { de: 'die Kontaktlinsen', it: 'le lenti a contatto', topic: 'gesundheit' },
  { de: 'hohes Fieber', it: 'febbre alta', topic: 'gesundheit' },
  { de: 'die Übelkeit', it: 'la nausea', topic: 'gesundheit' },
  { de: 'sich übergeben', it: 'vomitare', topic: 'gesundheit' },
  { de: 'ohnmächtig werden', it: 'svenire', topic: 'gesundheit' },
  { de: 'sich ein Bein brechen', it: 'rompersi una gamba', topic: 'gesundheit' },
  { de: 'sich wehtun', it: 'farsi male', topic: 'gesundheit' },
  { de: 'sich erkälten', it: 'prendere freddo', topic: 'gesundheit' },
  { de: 'sich besser fühlen', it: 'stare meglio', topic: 'gesundheit' },
  { de: 'abnehmen', it: 'dimagrire', topic: 'gesundheit' },
  { de: 'zunehmen', it: 'ingrassare', topic: 'gesundheit' },
  { de: 'Diät machen', it: 'fare la dieta', topic: 'gesundheit' },
  { de: 'mit dem Rauchen aufhören', it: 'smettere di fumare', topic: 'gesundheit' },
  { de: 'die psychische Gesundheit', it: 'la salute mentale', topic: 'gesundheit' },
  { de: 'der Bürger', it: 'il cittadino', topic: 'gesellschaft' },
  { de: 'die Wahlen', it: 'le elezioni', topic: 'gesellschaft' },
  { de: 'das Gesetz', it: 'la legge', topic: 'gesellschaft' },
  { de: 'die Rechte', it: 'i diritti', topic: 'gesellschaft' },
  { de: 'die Einwanderung', it: "l'immigrazione", topic: 'gesellschaft' },
  { de: 'der Einwanderer', it: "l'immigrato", topic: 'gesellschaft' },
  { de: 'die Integration', it: "l'integrazione", topic: 'gesellschaft' },
  { de: 'die Freiwilligenarbeit', it: 'il volontariato', topic: 'gesellschaft' },
  { de: 'der Freiwillige', it: 'il volontario', topic: 'gesellschaft' },
  { de: 'die Wohltätigkeit', it: 'la beneficenza', topic: 'gesellschaft' },
  { de: 'der Rassismus', it: 'il razzismo', topic: 'gesellschaft' },
  { de: 'der Streik', it: 'lo sciopero', topic: 'gesellschaft' },
  { de: 'das Parlament', it: 'il parlamento', topic: 'gesellschaft' },
  { de: 'der Präsident', it: 'il presidente', topic: 'gesellschaft' },
  { de: 'der Minister', it: 'il ministro', topic: 'gesellschaft' },
  { de: 'die Region', it: 'la regione', topic: 'gesellschaft' },
  { de: 'die Provinz', it: 'la provincia', topic: 'gesellschaft' },
  { de: 'die Tradition', it: 'la tradizione', topic: 'gesellschaft' },
  { de: 'die Religion', it: 'la religione', topic: 'gesellschaft' },
  { de: 'der Nationalfeiertag', it: 'la festa nazionale', topic: 'gesellschaft' },
  { de: 'die Jugendarbeitslosigkeit', it: 'la disoccupazione giovanile', topic: 'gesellschaft' },
  { de: 'die Kriminalität', it: 'la criminalità', topic: 'gesellschaft' },
  { de: 'die Carabinieri (Polizei)', it: 'i carabinieri', topic: 'gesellschaft' },
  { de: 'das Gericht', it: 'il tribunale', topic: 'gesellschaft' },
  { de: 'die öffentliche Meinung', it: "l'opinione pubblica", topic: 'gesellschaft' },
  { de: 'die Debatte', it: 'il dibattito', topic: 'gesellschaft' },
  { de: 'wählen (Wahl)', it: 'votare', topic: 'gesellschaft' },
  { de: 'die Umweltverschmutzung', it: "l'inquinamento", topic: 'natur' },
  { de: 'der Abfall', it: 'i rifiuti', topic: 'natur' },
  { de: 'die Mülltrennung', it: 'la raccolta differenziata', topic: 'natur' },
  { de: 'das Recycling', it: 'il riciclaggio', topic: 'natur' },
  { de: 'die Erderwärmung', it: 'il riscaldamento globale', topic: 'natur' },
  { de: 'der Klimawandel', it: 'il cambiamento climatico', topic: 'natur' },
  { de: 'die erneuerbare Energie', it: "l'energia rinnovabile", topic: 'natur' },
  { de: 'die Solaranlage', it: 'il pannello solare', topic: 'natur' },
  { de: 'die Dürre', it: 'la siccità', topic: 'natur' },
  { de: 'die Überschwemmung', it: "l'alluvione", topic: 'natur' },
  { de: 'die Abholzung', it: 'la deforestazione', topic: 'natur' },
  { de: 'die Landschaft', it: 'il paesaggio', topic: 'natur' },
  { de: 'das Land (im Gegensatz zur Stadt)', it: 'la campagna', topic: 'natur' },
  { de: 'der Vulkan', it: 'il vulcano', topic: 'natur' },
  { de: 'der Gletscher', it: 'il ghiacciaio', topic: 'natur' },
  { de: 'der Ozean', it: "l'oceano", topic: 'natur' },
  { de: 'der Sand', it: 'la sabbia', topic: 'natur' },
  { de: 'der Fels', it: 'la roccia', topic: 'natur' },
  { de: 'die Höhle', it: 'la grotta', topic: 'natur' },
  { de: 'der Wald', it: 'la foresta', topic: 'natur' },
  { de: 'die Pflanze', it: 'la pianta', topic: 'natur' },
  { de: 'der Samen', it: 'il seme', topic: 'natur' },
  { de: 'die Ernte', it: 'il raccolto', topic: 'natur' },
  { de: 'der Wetterbericht', it: 'le previsioni del tempo', topic: 'natur' },
  { de: 'feucht', it: 'umido', topic: 'natur' },
  { de: 'heiter / klar', it: 'sereno', topic: 'natur' },
  { de: 'bewölkt', it: 'nuvoloso', topic: 'natur' },
  { de: 'die Schwüle', it: "l'afa", topic: 'natur' },
  { de: 'der Hagel', it: 'la grandine', topic: 'natur' },
  { de: 'der Regenbogen', it: "l'arcobaleno", topic: 'natur' },
  { de: 'recyceln', it: 'riciclare', topic: 'natur' },
  { de: 'verschmutzen', it: 'inquinare', topic: 'natur' },
  { de: 'verschwenden', it: 'sprecare', topic: 'natur' },
  { de: 'das Gefühl / die Emotion', it: "l'emozione", topic: 'gefuehle' },
  { de: 'das Gefühl', it: 'il sentimento', topic: 'gefuehle' },
  { de: 'die Sehnsucht / das Heimweh', it: 'la nostalgia', topic: 'gefuehle' },
  { de: 'das Glück', it: 'la felicità', topic: 'gefuehle' },
  { de: 'die Verlegenheit', it: "l'imbarazzo", topic: 'gefuehle' },
  { de: 'die Erleichterung', it: 'il sollievo', topic: 'gefuehle' },
  { de: 'die Zufriedenheit', it: 'la soddisfazione', topic: 'gefuehle' },
  { de: 'die Sorge', it: 'la preoccupazione', topic: 'gefuehle' },
  { de: 'die Langeweile', it: 'la noia', topic: 'gefuehle' },
  { de: 'die Begeisterung', it: "l'entusiasmo", topic: 'gefuehle' },
  { de: 'der Stolz', it: "l'orgoglio", topic: 'gefuehle' },
  { de: 'die Ruhe', it: 'la calma', topic: 'gefuehle' },
  { de: 'die Zuneigung', it: "l'affetto", topic: 'gefuehle' },
  { de: 'der Streit', it: 'il litigio', topic: 'gefuehle' },
  { de: 'ehrgeizig', it: 'ambizioso', topic: 'gefuehle' },
  { de: 'unsympathisch', it: 'antipatico', topic: 'gefuehle' },
  { de: 'arrogant', it: 'arrogante', topic: 'gefuehle' },
  { de: 'tüchtig / gut', it: 'bravo', topic: 'gefuehle' },
  { de: 'enttäuscht', it: 'deluso', topic: 'gefuehle' },
  { de: 'unordentlich', it: 'disordinato', topic: 'gefuehle' },
  { de: 'aufgeregt / gerührt', it: 'emozionato', topic: 'gefuehle' },
  { de: 'anspruchsvoll', it: 'esigente', topic: 'gefuehle' },
  { de: 'eifersüchtig', it: 'geloso', topic: 'gefuehle' },
  { de: 'unabhängig', it: 'indipendente', topic: 'gefuehle' },
  { de: 'verliebt', it: 'innamorato', topic: 'gefuehle' },
  { de: 'unerträglich', it: 'insopportabile', topic: 'gefuehle' },
  { de: 'nervös', it: 'nervoso', topic: 'gefuehle' },
  { de: 'ordentlich', it: 'ordinato', topic: 'gefuehle' },
  { de: 'besorgt', it: 'preoccupato', topic: 'gefuehle' },
  { de: 'sensibel', it: 'sensibile', topic: 'gefuehle' },
  { de: 'gestresst', it: 'stressato', topic: 'gefuehle' },
  { de: 'stur', it: 'testardo', topic: 'gefuehle' },
  { de: 'lebhaft', it: 'vivace', topic: 'gefuehle' },
  { de: 'zuverlässig', it: 'affidabile', topic: 'gefuehle' },
  { de: 'gesellig', it: 'socievole', topic: 'gefuehle' },
  { de: 'wütend', it: 'arrabbiato', topic: 'gefuehle' },
  { de: 'erschrocken', it: 'spaventato', topic: 'gefuehle' },
  { de: 'gelangweilt', it: 'annoiato', topic: 'gefuehle' },
  { de: 'entspannt', it: 'rilassato', topic: 'gefuehle' },
  { de: 'zuversichtlich', it: 'fiducioso', topic: 'gefuehle' },
  { de: 'optimistisch', it: 'ottimista', topic: 'gefuehle' },
  { de: 'pessimistisch', it: 'pessimista', topic: 'gefuehle' },
  { de: 'vertrauen', it: 'fidarsi', topic: 'gefuehle' },
  { de: 'sich ärgern', it: 'arrabbiarsi', topic: 'gefuehle' },
  { de: 'sich Sorgen machen', it: 'preoccuparsi', topic: 'gefuehle' },
  { de: 'streiten', it: 'litigare', topic: 'gefuehle' },
  { de: 'sich versöhnen', it: 'fare pace', topic: 'gefuehle' },
  { de: 'sich langweilen', it: 'annoiarsi', topic: 'gefuehle' },
  { de: 'gerührt sein / aufgeregt sein', it: 'emozionarsi', topic: 'gefuehle' },
  { de: 'sich einsam fühlen', it: 'sentirsi solo', topic: 'gefuehle' },
  { de: 'Lust haben auf', it: 'avere voglia di', topic: 'gefuehle' },
  { de: 'bequem', it: 'comodo', topic: 'adjektive' },
  { de: 'unbequem', it: 'scomodo', topic: 'adjektive' },
  { de: 'kostenlos', it: 'gratuito', topic: 'adjektive' },
  { de: 'gratis', it: 'gratis', topic: 'adjektive' },
  { de: 'praktisch', it: 'pratico', topic: 'adjektive' },
  { de: 'nutzlos', it: 'inutile', topic: 'adjektive' },
  { de: 'selten', it: 'raro', topic: 'adjektive' },
  { de: 'häufig', it: 'frequente', topic: 'adjektive' },
  { de: 'verpflichtend', it: 'obbligatorio', topic: 'adjektive' },
  { de: 'freiwillig', it: 'facoltativo', topic: 'adjektive' },
  { de: 'dringend', it: 'urgente', topic: 'adjektive' },
  { de: 'anstrengend', it: 'faticoso', topic: 'adjektive' },
  { de: 'entspannend', it: 'rilassante', topic: 'adjektive' },
  { de: 'weich', it: 'morbido', topic: 'adjektive' },
  { de: 'rau', it: 'ruvido', topic: 'adjektive' },
  { de: 'lauwarm', it: 'tiepido', topic: 'adjektive' },
  { de: 'richtig / gerecht', it: 'giusto', topic: 'adjektive' },
  { de: 'falsch', it: 'sbagliato', topic: 'adjektive' },
  { de: 'wahr', it: 'vero', topic: 'adjektive' },
  { de: 'riesig', it: 'enorme', topic: 'adjektive' },
  { de: 'winzig', it: 'minuscolo', topic: 'adjektive' },
  { de: 'traditionell', it: 'tradizionale', topic: 'adjektive' },
  { de: 'unbekannt', it: 'sconosciuto', topic: 'adjektive' },
  { de: 'glücklich (Glück habend)', it: 'fortunato', topic: 'adjektive' },
  { de: 'unglücklich (Pech habend)', it: 'sfortunato', topic: 'adjektive' },
  { de: 'zufrieden', it: 'soddisfatto', topic: 'adjektive' },
  { de: 'schlau', it: 'furbo', topic: 'adjektive' },
  { de: 'großartig', it: 'magnifico', topic: 'adjektive' },
  { de: 'herrlich', it: 'splendido', topic: 'adjektive' },
  { de: 'wirksam', it: 'efficace', topic: 'adjektive' },
  { de: 'sich stellen / angehen', it: 'affrontare', topic: 'verben' },
  { de: 'aktualisieren', it: 'aggiornare', topic: 'verben' },
  { de: 'sich entfernen', it: 'allontanarsi', topic: 'verben' },
  { de: 'absagen / stornieren', it: 'annullare', topic: 'verben' },
  { de: 'anklopfen', it: 'bussare', topic: 'verben' },
  { de: 'plaudern', it: 'chiacchierare', topic: 'verben' },
  { de: 'ausfüllen (Formular)', it: 'compilare', topic: 'verben' },
  { de: 'abgeben / liefern', it: 'consegnare', topic: 'verben' },
  { de: 'nähen', it: 'cucire', topic: 'verben' },
  { de: 'sich widmen', it: 'dedicarsi', topic: 'verben' },
  { de: 'vergessen', it: 'dimenticarsi', topic: 'verben' },
  { de: 'absagen / kündigen', it: 'disdire', topic: 'verben' },
  { de: 'teilen', it: 'dividere', topic: 'verben' },
  { de: 'entfernen', it: 'eliminare', topic: 'verben' },
  { de: 'übertreiben', it: 'esagerare', topic: 'verben' },
  { de: 'vortäuschen', it: 'fingere', topic: 'verben' },
  { de: 'fotografieren', it: 'fotografare', topic: 'verben' },
  { de: 'verwalten / managen', it: 'gestire', topic: 'verben' },
  { de: 'ignorieren / nicht wissen', it: 'ignorare', topic: 'verben' },
  { de: 'sich anstrengen / sich verpflichten', it: 'impegnarsi', topic: 'verben' },
  { de: 'sich informieren', it: 'informarsi', topic: 'verben' },
  { de: 'anfangen', it: 'iniziare', topic: 'verben' },
  { de: 'interviewen', it: 'intervistare', topic: 'verben' },
  { de: 'kämpfen', it: 'lottare', topic: 'verben' },
  { de: 'aufbauen / montieren', it: 'montare', topic: 'verben' },
  { de: 'bemerken', it: 'notare', topic: 'verben' },
  { de: 'sich kümmern um', it: 'occuparsi', topic: 'verben' },
  { de: 'organisieren', it: 'organizzare', topic: 'verben' },
  { de: 'beherbergen', it: 'ospitare', topic: 'verben' },
  { de: 'teilnehmen', it: 'partecipare', topic: 'verben' },
  { de: 'verzeihen', it: 'perdonare', topic: 'verben' },
  { de: 'falten / biegen', it: 'piegare', topic: 'verben' },
  { de: 'vorstellen', it: 'presentare', topic: 'verben' },
  { de: 'leihen', it: 'prestare', topic: 'verben' },
  { de: 'vorhersehen', it: 'prevedere', topic: 'verben' },
  { de: 'erreichen', it: 'raggiungere', topic: 'verben' },
  { de: 'verwirklichen', it: 'realizzare', topic: 'verben' },
  { de: 'schenken', it: 'regalare', topic: 'verben' },
  { de: 'zusammenfassen', it: 'riassumere', topic: 'verben' },
  { de: 'reduzieren', it: 'ridurre', topic: 'verben' },
  { de: 'ablehnen', it: 'rifiutare', topic: 'verben' },
  { de: 'sparen', it: 'risparmiare', topic: 'verben' },
  { de: 'ruinieren', it: 'rovinare', topic: 'verben' },
  { de: 'wählen / aussuchen', it: 'scegliere', topic: 'verben' },
  { de: 'wetten', it: 'scommettere', topic: 'verben' },
  { de: 'abraten', it: 'sconsigliare', topic: 'verben' },
  { de: 'sich entschuldigen', it: 'scusarsi', topic: 'verben' },
  { de: 'scheinen', it: 'sembrare', topic: 'verben' },
  { de: 'sich fühlen', it: 'sentirsi', topic: 'verben' },
  { de: 'aufhören', it: 'smettere', topic: 'verben' },
  { de: 'überleben', it: 'sopravvivere', topic: 'verben' },
  { de: 'ersetzen', it: 'sostituire', topic: 'verben' },
  { de: 'verschieben / umstellen', it: 'spostare', topic: 'verben' },
  { de: 'müde werden', it: 'stancarsi', topic: 'verben' },
  { de: 'vorschlagen', it: 'suggerire', topic: 'verben' },
  { de: 'überwinden / bestehen', it: 'superare', topic: 'verben' },
  { de: 'aufwachen', it: 'svegliarsi', topic: 'verben' },
  { de: 'versuchen', it: 'tentare', topic: 'verben' },
  { de: 'behandeln / verhandeln', it: 'trattare', topic: 'verben' },
  { de: 'sich schminken', it: 'truccarsi', topic: 'verben' },
  { de: 'schreien', it: 'urlare', topic: 'verben' },
  { de: 'sich anziehen', it: 'vestirsi', topic: 'verben' },
  { de: 'sich einigen', it: "mettersi d'accordo", topic: 'verben' },
  { de: 'merken / sich klarmachen', it: 'rendersi conto', topic: 'verben' },
  { de: 'einkaufen', it: 'fare la spesa', topic: 'verben' },
  { de: 'Schlange stehen', it: 'fare la fila', topic: 'verben' },
  { de: 'aufpassen', it: 'fare attenzione', topic: 'verben' },
  { de: 'brauchen', it: 'avere bisogno', topic: 'verben' },
  { de: 'recht haben', it: 'avere ragione', topic: 'verben' },
  { de: 'unrecht haben', it: 'avere torto', topic: 'verben' },
  { de: 'es eilig haben', it: 'avere fretta', topic: 'verben' },
  { de: 'müde sein', it: 'avere sonno', topic: 'verben' },
  { de: 'stören', it: 'dare fastidio', topic: 'verben' },
  { de: 'so tun als ob', it: 'fare finta', topic: 'verben' },
  { de: 'seine Meinung ändern', it: 'cambiare idea', topic: 'verben' },
  { de: 'Wert legen auf', it: 'tenere a', topic: 'verben' },
  { de: 'brauchen (Zeit / Menge)', it: 'volerci', topic: 'verben' },
  { de: 'brauchen (Zeit)', it: 'metterci', topic: 'verben' },
  { de: 'es schaffen', it: 'farcela', topic: 'verben' },
  { de: 'das Girokonto', it: 'il conto corrente', topic: 'geld' },
  { de: 'der Geldautomat / die Bankkarte', it: 'il bancomat', topic: 'geld' },
  { de: 'abheben', it: 'prelevare', topic: 'geld' },
  { de: 'einzahlen / gießen', it: 'versare', topic: 'geld' },
  { de: 'die Überweisung', it: 'il bonifico', topic: 'geld' },
  { de: 'der Kredit / das Darlehen', it: 'il prestito', topic: 'geld' },
  { de: 'die Hypothek', it: 'il mutuo', topic: 'geld' },
  { de: 'die Ersparnisse', it: 'i risparmi', topic: 'geld' },
  { de: 'der Einkauf / die Ausgabe', it: 'la spesa', topic: 'geld' },
  { de: 'das Wechselgeld', it: 'il resto', topic: 'geld' },
  { de: 'der Schlussverkauf', it: 'i saldi', topic: 'geld' },
  { de: 'der Festpreis', it: 'il prezzo fisso', topic: 'geld' },
  { de: 'die Kosten', it: 'il costo', topic: 'geld' },
  { de: 'die Stromrechnung', it: 'la bolletta della luce', topic: 'geld' },
  { de: 'bar bezahlen', it: 'pagare in contanti', topic: 'geld' },
  { de: 'mit Karte zahlen', it: 'pagare con la carta', topic: 'geld' },
  { de: 'shoppen gehen', it: 'fare shopping', topic: 'geld' },
  { de: 'die Kleidergröße', it: 'la taglia', topic: 'geld' },
  { de: 'die Schuhgröße', it: 'il numero di scarpe', topic: 'geld' },
  { de: 'die Umkleidekabine', it: 'il camerino', topic: 'geld' },
  { de: 'die Verkäuferin', it: 'la commessa', topic: 'geld' },
  { de: 'das T-Shirt', it: 'la maglietta', topic: 'kleidung' },
  { de: 'das Sweatshirt', it: 'la felpa', topic: 'kleidung' },
  { de: 'die Jeans', it: 'i jeans', topic: 'kleidung' },
  { de: 'die kurze Hose', it: 'i pantaloncini', topic: 'kleidung' },
  { de: 'die Strümpfe', it: 'le calze', topic: 'kleidung' },
  { de: 'der Schlafanzug', it: 'il pigiama', topic: 'kleidung' },
  { de: 'die Krawatte', it: 'la cravatta', topic: 'kleidung' },
  { de: 'die Jacke (Anorak)', it: 'il giubbotto', topic: 'kleidung' },
  { de: 'der Regenmantel', it: "l'impermeabile", topic: 'kleidung' },
  { de: 'der Regenschirm', it: "l'ombrello", topic: 'kleidung' },
  { de: 'die Sandalen', it: 'i sandali', topic: 'kleidung' },
  { de: 'die Turnschuhe', it: 'le scarpe da ginnastica', topic: 'kleidung' },
  { de: 'die hohen Absätze', it: 'i tacchi', topic: 'kleidung' },
  { de: 'die Geldbörse', it: 'il portafoglio', topic: 'kleidung' },
  { de: 'der Rucksack', it: 'lo zaino', topic: 'kleidung' },
  { de: 'die Ohrringe', it: 'gli orecchini', topic: 'kleidung' },
  { de: 'die Halskette', it: 'la collana', topic: 'kleidung' },
  { de: 'die Mode', it: 'la moda', topic: 'kleidung' },
  { de: 'der Stil', it: 'lo stile', topic: 'kleidung' },
  { de: 'elegant', it: 'elegante', topic: 'kleidung' },
  { de: 'sportlich', it: 'sportivo', topic: 'kleidung' },
  { de: 'leger', it: 'casual', topic: 'kleidung' },
  { de: 'modisch', it: 'di moda', topic: 'kleidung' },
  { de: 'unmodern', it: 'fuori moda', topic: 'kleidung' },
  { de: 'anziehen', it: 'mettersi', topic: 'kleidung' },
  { de: 'ausziehen', it: 'togliersi', topic: 'kleidung' },
  { de: 'sich gut anziehen', it: 'vestirsi bene', topic: 'kleidung' },
  { de: 'die Verwandten', it: 'i parenti', topic: 'familie' },
  { de: 'die Cousins', it: 'i cugini', topic: 'familie' },
  { de: 'die Enkel / die Neffen', it: 'i nipoti', topic: 'familie' },
  { de: 'der Verlobte / der feste Freund', it: 'il fidanzato', topic: 'familie' },
  { de: 'der Partner', it: 'il compagno', topic: 'familie' },
  { de: 'die Partnerin', it: 'la compagna', topic: 'familie' },
  { de: 'Single', it: 'single', topic: 'familie' },
  { de: 'geschieden', it: 'divorziato', topic: 'familie' },
  { de: 'verwitwet', it: 'vedovo', topic: 'familie' },
  { de: 'die Hochzeit', it: 'le nozze', topic: 'familie' },
  { de: 'die Taufe', it: 'il battesimo', topic: 'familie' },
  { de: 'die Kindheit', it: "l'infanzia", topic: 'familie' },
  { de: 'die Jugend', it: "l'adolescenza", topic: 'familie' },
  { de: 'die Jugend', it: 'la gioventù', topic: 'familie' },
  { de: 'das Alter', it: 'la vecchiaia', topic: 'familie' },
  { de: 'der ältere Mensch / alt', it: "l'anziano", topic: 'familie' },
  { de: 'der Jugendliche', it: "l'adolescente", topic: 'familie' },
  { de: 'das Paar', it: 'la coppia', topic: 'familie' },
  { de: 'der Zwilling', it: 'il gemello', topic: 'familie' },
  { de: 'das Einzelkind', it: 'il figlio unico', topic: 'familie' },
  { de: 'erziehen', it: 'educare', topic: 'familie' },
  { de: 'auf die Kinder aufpassen', it: 'badare ai bambini', topic: 'familie' },
  { de: 'die Ursache', it: 'la causa', topic: 'abstrakt' },
  { de: 'die Folge', it: 'la conseguenza', topic: 'abstrakt' },
  { de: 'das Scheitern', it: 'il fallimento', topic: 'abstrakt' },
  { de: 'die Anstrengung', it: 'lo sforzo', topic: 'abstrakt' },
  { de: 'das Engagement / die Verpflichtung', it: "l'impegno", topic: 'abstrakt' },
  { de: 'die Gelegenheit', it: "l'occasione", topic: 'abstrakt' },
  { de: 'die Chance', it: "l'opportunità", topic: 'abstrakt' },
  { de: 'die Schwierigkeit', it: 'la difficoltà', topic: 'abstrakt' },
  { de: 'der Vergleich', it: 'il paragone', topic: 'abstrakt' },
  { de: 'die Ähnlichkeit', it: 'la somiglianza', topic: 'abstrakt' },
  { de: 'der Standpunkt', it: 'il punto di vista', topic: 'abstrakt' },
  { de: 'der Vorschlag', it: 'la proposta', topic: 'abstrakt' },
  { de: 'die Anfrage / die Bitte', it: 'la richiesta', topic: 'abstrakt' },
  { de: 'der Zweifel', it: 'il dubbio', topic: 'abstrakt' },
  { de: 'die Gewissheit', it: 'la certezza', topic: 'abstrakt' },
  { de: 'die Ausnahme', it: "l'eccezione", topic: 'abstrakt' },
  { de: 'die Erlaubnis', it: 'il permesso', topic: 'abstrakt' },
  { de: 'das Verbot', it: 'il divieto', topic: 'abstrakt' },
  { de: 'die Qualität', it: 'la qualità', topic: 'abstrakt' },
  { de: 'die Menge', it: 'la quantità', topic: 'abstrakt' },
  { de: 'der Grund / die Vernunft', it: 'la ragione', topic: 'abstrakt' },
  { de: 'das Unrecht', it: 'il torto', topic: 'abstrakt' },
];
