import { CatalogWord } from './vocab-catalog';
import { normWord } from './norm';

// ─── A1 → A2 starter path ───────────────────────────────────────────────────────
// A gentle, ordered on-ramp for complete beginners (A1 profiles). The Vocabulary "Learn"
// tab walks this array in order, so the ORDER here is the teaching order: start with
// greetings, courtesy, question words, pronouns and numbers — the things the main
// VOCAB_CATALOG lacks and that a true beginner needs first — then move through the
// most concrete everyday themes (family, food, house, city, travel…) before the
// lighter abstract words. German (`de`) side is the learner's L1.
//
// Deduped at the bottom so an accidental repeat never produces a double flashcard.
// After the starter, app/vokabeln/page.tsx flows beginners into the rest of the
// full catalog, so they never run out.

const RAW: CatalogWord[] = [
  // ── Begrüßung & Höflichkeit ────────────────────────────────────────────────
  { de: 'hallo / tschüss (informell)', it: 'ciao', topic: 'begruessung' },
  { de: 'guten Morgen / guten Tag', it: 'buongiorno', topic: 'begruessung' },
  { de: 'guten Abend', it: 'buonasera', topic: 'begruessung' },
  { de: 'gute Nacht', it: 'buonanotte', topic: 'begruessung' },
  { de: 'auf Wiedersehen', it: 'arrivederci', topic: 'begruessung' },
  { de: 'bis später', it: 'a dopo', topic: 'begruessung' },
  { de: 'bis morgen', it: 'a domani', topic: 'begruessung' },
  { de: 'bis bald', it: 'a presto', topic: 'begruessung' },
  { de: 'willkommen', it: 'benvenuto', topic: 'begruessung' },
  { de: 'ja', it: 'sì', topic: 'begruessung' },
  { de: 'nein', it: 'no', topic: 'begruessung' },
  { de: 'vielleicht', it: 'forse', topic: 'begruessung' },
  { de: 'bitte', it: 'per favore', topic: 'begruessung' },
  { de: 'danke', it: 'grazie', topic: 'begruessung' },
  { de: 'vielen Dank', it: 'grazie mille', topic: 'begruessung' },
  { de: 'gern geschehen / bitte', it: 'prego', topic: 'begruessung' },
  { de: 'entschuldigung', it: 'scusa', topic: 'begruessung' },
  { de: 'Entschuldigung (höflich)', it: 'mi scusi', topic: 'begruessung' },
  { de: 'es tut mir leid', it: 'mi dispiace', topic: 'begruessung' },
  { de: 'wie geht es dir?', it: 'come stai?', topic: 'begruessung' },
  { de: 'gut', it: 'bene', topic: 'begruessung' },
  { de: 'schlecht', it: 'male', topic: 'begruessung' },
  { de: 'so lala', it: 'così così', topic: 'begruessung' },
  { de: 'sehr erfreut', it: 'piacere', topic: 'begruessung' },
  { de: 'wie heißt du?', it: 'come ti chiami?', topic: 'begruessung' },
  { de: 'ich heiße …', it: 'mi chiamo', topic: 'begruessung' },
  { de: 'ich verstehe nicht', it: 'non capisco', topic: 'begruessung' },
  { de: 'sprichst du Deutsch?', it: 'parli tedesco?', topic: 'begruessung' },
  { de: 'Prost!', it: 'salute!', topic: 'begruessung' },
  { de: 'herzlichen Glückwunsch', it: 'auguri', topic: 'begruessung' },
  { de: 'guten Appetit', it: 'buon appetito', topic: 'begruessung' },

  // ── Fragewörter ─────────────────────────────────────────────────────────────
  { de: 'was', it: 'che cosa', topic: 'grundwoerter' },
  { de: 'wer', it: 'chi', topic: 'grundwoerter' },
  { de: 'wo', it: 'dove', topic: 'grundwoerter' },
  { de: 'wann', it: 'quando', topic: 'grundwoerter' },
  { de: 'wie', it: 'come', topic: 'grundwoerter' },
  { de: 'warum / weil', it: 'perché', topic: 'grundwoerter' },
  { de: 'wie viel', it: 'quanto', topic: 'grundwoerter' },
  { de: 'welcher / welche', it: 'quale', topic: 'grundwoerter' },

  // ── Personalpronomen & Possessiv ───────────────────────────────────────────────
  { de: 'ich', it: 'io', topic: 'grundwoerter' },
  { de: 'du', it: 'tu', topic: 'grundwoerter' },
  { de: 'er', it: 'lui', topic: 'grundwoerter' },
  { de: 'sie (Einzahl)', it: 'lei', topic: 'grundwoerter' },
  { de: 'Sie (höflich)', it: 'Lei', topic: 'grundwoerter' },
  { de: 'wir', it: 'noi', topic: 'grundwoerter' },
  { de: 'ihr', it: 'voi', topic: 'grundwoerter' },
  { de: 'sie (Mehrzahl)', it: 'loro', topic: 'grundwoerter' },
  { de: 'mein', it: 'mio', topic: 'grundwoerter' },
  { de: 'dein', it: 'tuo', topic: 'grundwoerter' },
  { de: 'sein / ihr', it: 'suo', topic: 'grundwoerter' },
  { de: 'unser', it: 'nostro', topic: 'grundwoerter' },
  { de: 'euer', it: 'vostro', topic: 'grundwoerter' },

  // ── Zahlen 0–20 ──────────────────────────────────────────────────────────────
  { de: 'null', it: 'zero', topic: 'zahlen' },
  { de: 'eins', it: 'uno', topic: 'zahlen' },
  { de: 'zwei', it: 'due', topic: 'zahlen' },
  { de: 'drei', it: 'tre', topic: 'zahlen' },
  { de: 'vier', it: 'quattro', topic: 'zahlen' },
  { de: 'fünf', it: 'cinque', topic: 'zahlen' },
  { de: 'sechs', it: 'sei', topic: 'zahlen' },
  { de: 'sieben', it: 'sette', topic: 'zahlen' },
  { de: 'acht', it: 'otto', topic: 'zahlen' },
  { de: 'neun', it: 'nove', topic: 'zahlen' },
  { de: 'zehn', it: 'dieci', topic: 'zahlen' },
  { de: 'elf', it: 'undici', topic: 'zahlen' },
  { de: 'zwölf', it: 'dodici', topic: 'zahlen' },
  { de: 'dreizehn', it: 'tredici', topic: 'zahlen' },
  { de: 'vierzehn', it: 'quattordici', topic: 'zahlen' },
  { de: 'fünfzehn', it: 'quindici', topic: 'zahlen' },
  { de: 'sechzehn', it: 'sedici', topic: 'zahlen' },
  { de: 'siebzehn', it: 'diciassette', topic: 'zahlen' },
  { de: 'achtzehn', it: 'diciotto', topic: 'zahlen' },
  { de: 'neunzehn', it: 'diciannove', topic: 'zahlen' },
  { de: 'zwanzig', it: 'venti', topic: 'zahlen' },
  // ── Zahlen 30–100 & Ordnungszahlen ─────────────────────────────────────────────
  { de: 'einundzwanzig', it: 'ventuno', topic: 'zahlen' },
  { de: 'dreißig', it: 'trenta', topic: 'zahlen' },
  { de: 'vierzig', it: 'quaranta', topic: 'zahlen' },
  { de: 'fünfzig', it: 'cinquanta', topic: 'zahlen' },
  { de: 'sechzig', it: 'sessanta', topic: 'zahlen' },
  { de: 'siebzig', it: 'settanta', topic: 'zahlen' },
  { de: 'achtzig', it: 'ottanta', topic: 'zahlen' },
  { de: 'neunzig', it: 'novanta', topic: 'zahlen' },
  { de: 'hundert', it: 'cento', topic: 'zahlen' },
  { de: 'tausend', it: 'mille', topic: 'zahlen' },
  { de: 'erster', it: 'primo', topic: 'zahlen' },
  { de: 'zweiter', it: 'secondo', topic: 'zahlen' },
  { de: 'dritter', it: 'terzo', topic: 'zahlen' },
  { de: 'letzter', it: 'ultimo', topic: 'zahlen' },
  { de: 'die Hälfte', it: 'la metà', topic: 'zahlen' },
  { de: 'das Doppelte', it: 'il doppio', topic: 'zahlen' },

  // ── Zeit, Tage, Monate, Jahreszeiten ────────────────────────────────────────────
  { de: 'Montag', it: 'il lunedì', topic: 'zeit' },
  { de: 'Dienstag', it: 'il martedì', topic: 'zeit' },
  { de: 'Mittwoch', it: 'il mercoledì', topic: 'zeit' },
  { de: 'Donnerstag', it: 'il giovedì', topic: 'zeit' },
  { de: 'Freitag', it: 'il venerdì', topic: 'zeit' },
  { de: 'Samstag', it: 'il sabato', topic: 'zeit' },
  { de: 'Sonntag', it: 'la domenica', topic: 'zeit' },
  { de: 'Januar', it: 'gennaio', topic: 'zeit' },
  { de: 'Februar', it: 'febbraio', topic: 'zeit' },
  { de: 'März', it: 'marzo', topic: 'zeit' },
  { de: 'April', it: 'aprile', topic: 'zeit' },
  { de: 'Mai', it: 'maggio', topic: 'zeit' },
  { de: 'Juni', it: 'giugno', topic: 'zeit' },
  { de: 'Juli', it: 'luglio', topic: 'zeit' },
  { de: 'August', it: 'agosto', topic: 'zeit' },
  { de: 'September', it: 'settembre', topic: 'zeit' },
  { de: 'Oktober', it: 'ottobre', topic: 'zeit' },
  { de: 'November', it: 'novembre', topic: 'zeit' },
  { de: 'Dezember', it: 'dicembre', topic: 'zeit' },
  { de: 'der Frühling', it: 'la primavera', topic: 'zeit' },
  { de: 'der Sommer', it: "l'estate", topic: 'zeit' },
  { de: 'der Herbst', it: "l'autunno", topic: 'zeit' },
  { de: 'der Winter', it: "l'inverno", topic: 'zeit' },
  { de: 'heute', it: 'oggi', topic: 'zeit' },
  { de: 'morgen', it: 'domani', topic: 'zeit' },
  { de: 'gestern', it: 'ieri', topic: 'zeit' },
  { de: 'jetzt', it: 'adesso', topic: 'zeit' },
  { de: 'später', it: 'più tardi', topic: 'zeit' },
  { de: 'früher / vorher', it: 'prima', topic: 'zeit' },
  { de: 'immer', it: 'sempre', topic: 'zeit' },
  { de: 'nie / niemals', it: 'mai', topic: 'zeit' },
  { de: 'manchmal', it: 'a volte', topic: 'zeit' },
  { de: 'oft', it: 'spesso', topic: 'zeit' },
  { de: 'bald', it: 'presto', topic: 'zeit' },
  { de: 'schon / bereits', it: 'già', topic: 'zeit' },
  { de: 'noch', it: 'ancora', topic: 'zeit' },
  { de: 'die Sekunde', it: 'il secondo', topic: 'zeit' },
  { de: 'die Minute', it: 'il minuto', topic: 'zeit' },
  { de: 'die Stunde', it: "l'ora", topic: 'zeit' },
  { de: 'der Tag', it: 'il giorno', topic: 'zeit' },
  { de: 'die Woche', it: 'la settimana', topic: 'zeit' },
  { de: 'der Monat', it: 'il mese', topic: 'zeit' },
  { de: 'das Jahr', it: "l'anno", topic: 'zeit' },
  { de: 'der Morgen', it: 'la mattina', topic: 'zeit' },
  { de: 'der Nachmittag', it: 'il pomeriggio', topic: 'zeit' },
  { de: 'der Abend', it: 'la sera', topic: 'zeit' },
  { de: 'die Nacht', it: 'la notte', topic: 'zeit' },
  { de: 'das Wochenende', it: 'il fine settimana', topic: 'zeit' },

  // ── Farben ───────────────────────────────────────────────────────────────────
  { de: 'rot', it: 'rosso', topic: 'farben' },
  { de: 'blau', it: 'blu', topic: 'farben' },
  { de: 'hellblau', it: 'azzurro', topic: 'farben' },
  { de: 'grün', it: 'verde', topic: 'farben' },
  { de: 'gelb', it: 'giallo', topic: 'farben' },
  { de: 'schwarz', it: 'nero', topic: 'farben' },
  { de: 'weiß', it: 'bianco', topic: 'farben' },
  { de: 'grau', it: 'grigio', topic: 'farben' },
  { de: 'orange', it: 'arancione', topic: 'farben' },
  { de: 'lila / violett', it: 'viola', topic: 'farben' },
  { de: 'rosa', it: 'rosa', topic: 'farben' },
  { de: 'braun', it: 'marrone', topic: 'farben' },

  // ── Familie & Personen ─────────────────────────────────────────────────────────
  { de: 'die Mutter', it: 'la madre', topic: 'familie' },
  { de: 'der Vater', it: 'il padre', topic: 'familie' },
  { de: 'die Eltern', it: 'i genitori', topic: 'familie' },
  { de: 'die Tochter', it: 'la figlia', topic: 'familie' },
  { de: 'der Sohn', it: 'il figlio', topic: 'familie' },
  { de: 'die Kinder (eigene)', it: 'i figli', topic: 'familie' },
  { de: 'die Schwester', it: 'la sorella', topic: 'familie' },
  { de: 'der Bruder', it: 'il fratello', topic: 'familie' },
  { de: 'die Großmutter', it: 'la nonna', topic: 'familie' },
  { de: 'der Großvater', it: 'il nonno', topic: 'familie' },
  { de: 'die Tante', it: 'la zia', topic: 'familie' },
  { de: 'der Onkel', it: 'lo zio', topic: 'familie' },
  { de: 'die Cousine', it: 'la cugina', topic: 'familie' },
  { de: 'der Cousin', it: 'il cugino', topic: 'familie' },
  { de: 'die Ehefrau', it: 'la moglie', topic: 'familie' },
  { de: 'der Ehemann', it: 'il marito', topic: 'familie' },
  { de: 'der Freund / die Freundin (Partner)', it: 'il ragazzo / la ragazza', topic: 'familie' },
  { de: 'der Freund / die Freundin', it: "l'amico / l'amica", topic: 'familie' },
  { de: 'der Nachbar', it: 'il vicino', topic: 'familie' },
  { de: 'der Kollege', it: 'il collega', topic: 'familie' },
  { de: 'das Baby', it: 'il bambino piccolo', topic: 'familie' },
  { de: 'das Kind', it: 'il bambino', topic: 'familie' },
  { de: 'die Frau', it: 'la donna', topic: 'familie' },
  { de: 'der Mann', it: "l'uomo", topic: 'familie' },
  { de: 'die Person', it: 'la persona', topic: 'familie' },
  { de: 'die Leute', it: 'la gente', topic: 'familie' },
  { de: 'der Name', it: 'il nome', topic: 'familie' },

  // ── Körper ─────────────────────────────────────────────────────────────────────
  { de: 'der Kopf', it: 'la testa', topic: 'koerper' },
  { de: 'die Haare', it: 'i capelli', topic: 'koerper' },
  { de: 'das Gesicht', it: 'la faccia', topic: 'koerper' },
  { de: 'das Auge', it: "l'occhio", topic: 'koerper' },
  { de: 'die Nase', it: 'il naso', topic: 'koerper' },
  { de: 'der Mund', it: 'la bocca', topic: 'koerper' },
  { de: 'das Ohr', it: "l'orecchio", topic: 'koerper' },
  { de: 'der Zahn', it: 'il dente', topic: 'koerper' },
  { de: 'der Hals', it: 'il collo', topic: 'koerper' },
  { de: 'der Arm', it: 'il braccio', topic: 'koerper' },
  { de: 'die Hand', it: 'la mano', topic: 'koerper' },
  { de: 'der Finger', it: 'il dito', topic: 'koerper' },
  { de: 'das Bein', it: 'la gamba', topic: 'koerper' },
  { de: 'der Fuß', it: 'il piede', topic: 'koerper' },
  { de: 'der Bauch', it: 'la pancia', topic: 'koerper' },
  { de: 'der Rücken', it: 'la schiena', topic: 'koerper' },
  { de: 'das Herz', it: 'il cuore', topic: 'koerper' },
  { de: 'die Haut', it: 'la pelle', topic: 'koerper' },

  // ── Essen & Trinken ────────────────────────────────────────────────────────────
  { de: 'das Essen', it: 'il cibo', topic: 'essen' },
  { de: 'das Frühstück', it: 'la colazione', topic: 'essen' },
  { de: 'das Mittagessen', it: 'il pranzo', topic: 'essen' },
  { de: 'das Abendessen', it: 'la cena', topic: 'essen' },
  { de: 'das Wasser', it: "l'acqua", topic: 'essen' },
  { de: 'der Kaffee', it: 'il caffè', topic: 'essen' },
  { de: 'der Tee', it: 'il tè', topic: 'essen' },
  { de: 'der Saft', it: 'il succo', topic: 'essen' },
  { de: 'die Milch', it: 'il latte', topic: 'essen' },
  { de: 'das Bier', it: 'la birra', topic: 'essen' },
  { de: 'der Wein', it: 'il vino', topic: 'essen' },
  { de: 'das Brot', it: 'il pane', topic: 'essen' },
  { de: 'die Butter', it: 'il burro', topic: 'essen' },
  { de: 'der Käse', it: 'il formaggio', topic: 'essen' },
  { de: 'das Ei', it: "l'uovo", topic: 'essen' },
  { de: 'das Fleisch', it: 'la carne', topic: 'essen' },
  { de: 'der Fisch', it: 'il pesce', topic: 'essen' },
  { de: 'das Hühnchen', it: 'il pollo', topic: 'essen' },
  { de: 'der Schinken', it: 'il prosciutto', topic: 'essen' },
  { de: 'das Gemüse', it: 'la verdura', topic: 'essen' },
  { de: 'die Kartoffel', it: 'la patata', topic: 'essen' },
  { de: 'die Tomate', it: 'il pomodoro', topic: 'essen' },
  { de: 'die Zwiebel', it: 'la cipolla', topic: 'essen' },
  { de: 'der Salat', it: "l'insalata", topic: 'essen' },
  { de: 'der Reis', it: 'il riso', topic: 'essen' },
  { de: 'die Nudeln', it: 'la pasta', topic: 'essen' },
  { de: 'das Obst', it: 'la frutta', topic: 'essen' },
  { de: 'der Apfel', it: 'la mela', topic: 'essen' },
  { de: 'die Banane', it: 'la banana', topic: 'essen' },
  { de: 'die Orange', it: "l'arancia", topic: 'essen' },
  { de: 'die Zitrone', it: 'il limone', topic: 'essen' },
  { de: 'der Zucker', it: 'lo zucchero', topic: 'essen' },
  { de: 'das Salz', it: 'il sale', topic: 'essen' },
  { de: 'das Öl', it: "l'olio", topic: 'essen' },
  { de: 'die Suppe', it: 'la zuppa', topic: 'essen' },
  { de: 'der Kuchen', it: 'la torta', topic: 'essen' },
  { de: 'das Eis', it: 'il gelato', topic: 'essen' },
  { de: 'die Schokolade', it: 'il cioccolato', topic: 'essen' },

  // ── Zuhause, Möbel & Küche ─────────────────────────────────────────────────────
  { de: 'das Haus', it: 'la casa', topic: 'wohnen' },
  { de: 'die Wohnung', it: "l'appartamento", topic: 'wohnen' },
  { de: 'das Zimmer', it: 'la stanza', topic: 'wohnen' },
  { de: 'die Küche', it: 'la cucina', topic: 'wohnen' },
  { de: 'das Badezimmer', it: 'il bagno', topic: 'wohnen' },
  { de: 'das Wohnzimmer', it: 'il soggiorno', topic: 'wohnen' },
  { de: 'das Schlafzimmer', it: 'la camera da letto', topic: 'wohnen' },
  { de: 'der Garten', it: 'il giardino', topic: 'wohnen' },
  { de: 'die Tür', it: 'la porta', topic: 'wohnen' },
  { de: 'das Fenster', it: 'la finestra', topic: 'wohnen' },
  { de: 'die Wand', it: 'la parete', topic: 'wohnen' },
  { de: 'der Boden', it: 'il pavimento', topic: 'wohnen' },
  { de: 'der Tisch', it: 'il tavolo', topic: 'wohnen' },
  { de: 'der Stuhl', it: 'la sedia', topic: 'wohnen' },
  { de: 'das Sofa', it: 'il divano', topic: 'wohnen' },
  { de: 'das Bett', it: 'il letto', topic: 'wohnen' },
  { de: 'der Schrank', it: "l'armadio", topic: 'wohnen' },
  { de: 'die Lampe', it: 'la lampada', topic: 'wohnen' },
  { de: 'der Schlüssel', it: 'la chiave', topic: 'wohnen' },
  { de: 'der Teller', it: 'il piatto', topic: 'wohnen' },
  { de: 'das Glas', it: 'il bicchiere', topic: 'wohnen' },
  { de: 'die Tasse', it: 'la tazza', topic: 'wohnen' },
  { de: 'die Flasche', it: 'la bottiglia', topic: 'wohnen' },
  { de: 'das Messer', it: 'il coltello', topic: 'wohnen' },
  { de: 'die Gabel', it: 'la forchetta', topic: 'wohnen' },
  { de: 'der Löffel', it: 'il cucchiaio', topic: 'wohnen' },

  // ── Stadt & Orte ───────────────────────────────────────────────────────────────
  { de: 'die Stadt', it: 'la città', topic: 'stadt' },
  { de: 'das Dorf', it: 'il paese', topic: 'stadt' },
  { de: 'das Land (Staat)', it: 'il paese / la nazione', topic: 'stadt' },
  { de: 'die Straße', it: 'la strada', topic: 'stadt' },
  { de: 'der Platz', it: 'la piazza', topic: 'stadt' },
  { de: 'das Geschäft / der Laden', it: 'il negozio', topic: 'stadt' },
  { de: 'der Supermarkt', it: 'il supermercato', topic: 'stadt' },
  { de: 'der Markt', it: 'il mercato', topic: 'stadt' },
  { de: 'das Restaurant', it: 'il ristorante', topic: 'stadt' },
  { de: 'die Bar / das Café', it: 'il bar', topic: 'stadt' },
  { de: 'das Hotel', it: "l'albergo", topic: 'stadt' },
  { de: 'der Bahnhof', it: 'la stazione', topic: 'stadt' },
  { de: 'der Flughafen', it: "l'aeroporto", topic: 'stadt' },
  { de: 'das Krankenhaus', it: "l'ospedale", topic: 'stadt' },
  { de: 'die Apotheke', it: 'la farmacia', topic: 'stadt' },
  { de: 'die Bank', it: 'la banca', topic: 'stadt' },
  { de: 'die Schule', it: 'la scuola', topic: 'stadt' },
  { de: 'die Kirche', it: 'la chiesa', topic: 'stadt' },
  { de: 'das Museum', it: 'il museo', topic: 'stadt' },
  { de: 'der Park', it: 'il parco', topic: 'stadt' },
  { de: 'der Strand', it: 'la spiaggia', topic: 'stadt' },
  { de: 'das Kino', it: 'il cinema', topic: 'stadt' },

  // ── Reisen & Transport ──────────────────────────────────────────────────────────
  { de: 'die Reise', it: 'il viaggio', topic: 'reisen' },
  { de: 'der Koffer', it: 'la valigia', topic: 'reisen' },
  { de: 'der Pass', it: 'il passaporto', topic: 'reisen' },
  { de: 'das Ticket / die Fahrkarte', it: 'il biglietto', topic: 'reisen' },
  { de: 'die Reservierung', it: 'la prenotazione', topic: 'reisen' },
  { de: 'der Tourist', it: 'il turista', topic: 'reisen' },
  { de: 'das Auto', it: 'la macchina', topic: 'reisen' },
  { de: 'der Bus', it: "l'autobus", topic: 'reisen' },
  { de: 'die U-Bahn', it: 'la metropolitana', topic: 'reisen' },
  { de: 'das Taxi', it: 'il taxi', topic: 'reisen' },
  { de: 'das Flugzeug', it: "l'aereo", topic: 'reisen' },
  { de: 'der Zug', it: 'il treno', topic: 'reisen' },
  { de: 'das Fahrrad', it: 'la bicicletta', topic: 'reisen' },
  { de: 'rechts', it: 'a destra', topic: 'reisen' },
  { de: 'links', it: 'a sinistra', topic: 'reisen' },
  { de: 'geradeaus', it: 'dritto', topic: 'reisen' },
  { de: 'nah', it: 'vicino', topic: 'reisen' },
  { de: 'weit', it: 'lontano', topic: 'reisen' },

  // ── Kleidung ─────────────────────────────────────────────────────────────────────
  { de: 'die Kleidung', it: 'i vestiti', topic: 'kleidung' },
  { de: 'das Hemd', it: 'la camicia', topic: 'kleidung' },
  { de: 'die Hose', it: 'i pantaloni', topic: 'kleidung' },
  { de: 'das Kleid', it: 'il vestito', topic: 'kleidung' },
  { de: 'der Rock', it: 'la gonna', topic: 'kleidung' },
  { de: 'die Jacke', it: 'la giacca', topic: 'kleidung' },
  { de: 'der Schuh', it: 'la scarpa', topic: 'kleidung' },
  { de: 'die Socke', it: 'il calzino', topic: 'kleidung' },
  { de: 'der Hut', it: 'il cappello', topic: 'kleidung' },
  { de: 'die Brille', it: 'gli occhiali', topic: 'kleidung' },

  // ── Grundverben (regelmäßig) ─────────────────────────────────────────────────────
  { de: 'sprechen', it: 'parlare', topic: 'verben' },
  { de: 'arbeiten', it: 'lavorare', topic: 'verben' },
  { de: 'studieren / lernen', it: 'studiare', topic: 'verben' },
  { de: 'kaufen', it: 'comprare', topic: 'verben' },
  { de: 'bezahlen', it: 'pagare', topic: 'verben' },
  { de: 'anschauen', it: 'guardare', topic: 'verben' },
  { de: 'hören / zuhören', it: 'ascoltare', topic: 'verben' },
  { de: 'fragen', it: 'domandare', topic: 'verben' },
  { de: 'antworten', it: 'rispondere', topic: 'verben' },
  { de: 'anrufen / rufen', it: 'chiamare', topic: 'verben' },
  { de: 'warten', it: 'aspettare', topic: 'verben' },
  { de: 'helfen', it: 'aiutare', topic: 'verben' },
  { de: 'brauchen', it: 'avere bisogno di', topic: 'verben' },
  { de: 'tragen / bringen', it: 'portare', topic: 'verben' },
  { de: 'tanzen', it: 'ballare', topic: 'verben' },
  { de: 'singen', it: 'cantare', topic: 'verben' },
  { de: 'kochen', it: 'cucinare', topic: 'verben' },
  { de: 'reisen', it: 'viaggiare', topic: 'verben' },
  { de: 'lieben', it: 'amare', topic: 'verben' },
  { de: 'nehmen', it: 'prendere', topic: 'verben' },
  { de: 'essen', it: 'mangiare', topic: 'verben' },
  { de: 'trinken', it: 'bere', topic: 'verben' },
  { de: 'lernen', it: 'imparare', topic: 'verben' },
  { de: 'lesen', it: 'leggere', topic: 'verben' },
  { de: 'laufen / rennen', it: 'correre', topic: 'verben' },
  { de: 'verstehen', it: 'capire', topic: 'verben' },
  { de: 'leben', it: 'vivere', topic: 'verben' },
  { de: 'wohnen', it: 'abitare', topic: 'verben' },
  { de: 'schreiben', it: 'scrivere', topic: 'verben' },
  { de: 'öffnen', it: 'aprire', topic: 'verben' },
  { de: 'empfangen / bekommen', it: 'ricevere', topic: 'verben' },

  // ── Grundverben (unregelmäßig & häufig) ──────────────────────────────────────────
  { de: 'sein', it: 'essere', topic: 'verben' },
  { de: 'sich befinden / bleiben', it: 'stare', topic: 'verben' },
  { de: 'haben', it: 'avere', topic: 'verben' },
  { de: 'es gibt', it: "c'è", topic: 'verben' },
  { de: 'machen / tun', it: 'fare', topic: 'verben' },
  { de: 'gehen', it: 'andare', topic: 'verben' },
  { de: 'kommen', it: 'venire', topic: 'verben' },
  { de: 'sagen', it: 'dire', topic: 'verben' },
  { de: 'sehen', it: 'vedere', topic: 'verben' },
  { de: 'geben', it: 'dare', topic: 'verben' },
  { de: 'wissen', it: 'sapere', topic: 'verben' },
  { de: 'kennen', it: 'conoscere', topic: 'verben' },
  { de: 'können', it: 'potere', topic: 'verben' },
  { de: 'wollen', it: 'volere', topic: 'verben' },
  { de: 'müssen', it: 'dovere', topic: 'verben' },
  { de: 'denken', it: 'pensare', topic: 'verben' },
  { de: 'glauben', it: 'credere', topic: 'verben' },
  { de: 'finden', it: 'trovare', topic: 'verben' },
  { de: 'schlafen', it: 'dormire', topic: 'verben' },
  { de: 'spielen', it: 'giocare', topic: 'verben' },
  { de: 'beginnen', it: 'cominciare', topic: 'verben' },
  { de: 'beenden / aufhören', it: 'finire', topic: 'verben' },
  { de: 'heißen', it: 'chiamarsi', topic: 'verben' },
  { de: 'sich setzen', it: 'sedersi', topic: 'verben' },
  { de: 'aufstehen', it: 'alzarsi', topic: 'verben' },

  // ── Einfache Adjektive ────────────────────────────────────────────────────────────
  { de: 'groß', it: 'grande', topic: 'adjektive' },
  { de: 'klein', it: 'piccolo', topic: 'adjektive' },
  { de: 'lang', it: 'lungo', topic: 'adjektive' },
  { de: 'kurz', it: 'corto', topic: 'adjektive' },
  { de: 'hoch / groß (Person)', it: 'alto', topic: 'adjektive' },
  { de: 'niedrig / klein (Person)', it: 'basso', topic: 'adjektive' },
  { de: 'gut', it: 'buono', topic: 'adjektive' },
  { de: 'schlecht', it: 'cattivo', topic: 'adjektive' },
  { de: 'schön', it: 'bello', topic: 'adjektive' },
  { de: 'hässlich', it: 'brutto', topic: 'adjektive' },
  { de: 'neu', it: 'nuovo', topic: 'adjektive' },
  { de: 'alt', it: 'vecchio', topic: 'adjektive' },
  { de: 'jung', it: 'giovane', topic: 'adjektive' },
  { de: 'schnell', it: 'veloce', topic: 'adjektive' },
  { de: 'langsam', it: 'lento', topic: 'adjektive' },
  { de: 'einfach', it: 'facile', topic: 'adjektive' },
  { de: 'schwierig', it: 'difficile', topic: 'adjektive' },
  { de: 'teuer', it: 'caro', topic: 'adjektive' },
  { de: 'günstig / billig', it: 'economico', topic: 'adjektive' },
  { de: 'warm / heiß', it: 'caldo', topic: 'adjektive' },
  { de: 'kalt', it: 'freddo', topic: 'adjektive' },
  { de: 'sauber', it: 'pulito', topic: 'adjektive' },
  { de: 'schmutzig', it: 'sporco', topic: 'adjektive' },
  { de: 'voll', it: 'pieno', topic: 'adjektive' },
  { de: 'leer', it: 'vuoto', topic: 'adjektive' },
  { de: 'glücklich', it: 'felice', topic: 'adjektive' },
  { de: 'traurig', it: 'triste', topic: 'adjektive' },
  { de: 'müde', it: 'stanco', topic: 'adjektive' },
  { de: 'krank', it: 'malato', topic: 'adjektive' },
  { de: 'wichtig', it: 'importante', topic: 'adjektive' },
  { de: 'gleich', it: 'uguale', topic: 'adjektive' },
  { de: 'anders / verschieden', it: 'diverso', topic: 'adjektive' },
  { de: 'viel', it: 'molto / tanto', topic: 'adjektive' },
  { de: 'wenig', it: 'poco', topic: 'adjektive' },
  { de: 'mehr', it: 'più', topic: 'adjektive' },
  { de: 'weniger', it: 'meno', topic: 'adjektive' },

  // ── Natur & Wetter ──────────────────────────────────────────────────────────────
  { de: 'die Natur', it: 'la natura', topic: 'natur' },
  { de: 'der Baum', it: "l'albero", topic: 'natur' },
  { de: 'die Blume', it: 'il fiore', topic: 'natur' },
  { de: 'der Berg', it: 'la montagna', topic: 'natur' },
  { de: 'der Fluss', it: 'il fiume', topic: 'natur' },
  { de: 'das Meer', it: 'il mare', topic: 'natur' },
  { de: 'der Himmel', it: 'il cielo', topic: 'natur' },
  { de: 'die Sonne', it: 'il sole', topic: 'natur' },
  { de: 'der Mond', it: 'la luna', topic: 'natur' },
  { de: 'der Stern', it: 'la stella', topic: 'natur' },
  { de: 'die Wolke', it: 'la nuvola', topic: 'natur' },
  { de: 'der Regen', it: 'la pioggia', topic: 'natur' },
  { de: 'der Schnee', it: 'la neve', topic: 'natur' },
  { de: 'der Wind', it: 'il vento', topic: 'natur' },
  { de: 'das Feuer', it: 'il fuoco', topic: 'natur' },
  { de: 'die Erde', it: 'la terra', topic: 'natur' },

  // ── Tiere ─────────────────────────────────────────────────────────────────────────
  { de: 'das Tier', it: "l'animale", topic: 'tiere' },
  { de: 'der Hund', it: 'il cane', topic: 'tiere' },
  { de: 'die Katze', it: 'il gatto', topic: 'tiere' },
  { de: 'das Pferd', it: 'il cavallo', topic: 'tiere' },
  { de: 'der Vogel', it: "l'uccello", topic: 'tiere' },
  { de: 'die Kuh', it: 'la mucca', topic: 'tiere' },
  { de: 'das Schwein', it: 'il maiale', topic: 'tiere' },

  // ── Schule & Bildung ──────────────────────────────────────────────────────────────
  { de: 'das Buch', it: 'il libro', topic: 'schule' },
  { de: 'das Heft', it: 'il quaderno', topic: 'schule' },
  { de: 'der Kugelschreiber', it: 'la penna', topic: 'schule' },
  { de: 'das Papier', it: 'la carta', topic: 'schule' },
  { de: 'der Schüler', it: 'lo studente', topic: 'schule' },
  { de: 'der Lehrer', it: "l'insegnante", topic: 'schule' },
  { de: 'die Klasse / der Unterricht', it: 'la lezione', topic: 'schule' },
  { de: 'die Prüfung', it: "l'esame", topic: 'schule' },
  { de: 'die Hausaufgaben', it: 'i compiti', topic: 'schule' },
  { de: 'die Sprache', it: 'la lingua', topic: 'schule' },
  { de: 'das Wort', it: 'la parola', topic: 'schule' },
  { de: 'der Satz', it: 'la frase', topic: 'schule' },
  { de: 'die Frage', it: 'la domanda', topic: 'schule' },
  { de: 'die Antwort', it: 'la risposta', topic: 'schule' },

  // ── Arbeit & Berufe ───────────────────────────────────────────────────────────────
  { de: 'die Arbeit', it: 'il lavoro', topic: 'arbeit' },
  { de: 'der Beruf', it: 'la professione', topic: 'arbeit' },
  { de: 'das Büro', it: "l'ufficio", topic: 'arbeit' },
  { de: 'der Chef / die Chefin', it: 'il capo', topic: 'arbeit' },
  { de: 'die Firma', it: "l'azienda", topic: 'arbeit' },
  { de: 'der Arzt / die Ärztin', it: 'il medico', topic: 'arbeit' },
  { de: 'der Lehrer (Grundschule)', it: 'il maestro', topic: 'arbeit' },
  { de: 'der Koch', it: 'il cuoco', topic: 'arbeit' },
  { de: 'der Kellner', it: 'il cameriere', topic: 'arbeit' },
  { de: 'der Verkäufer', it: 'il commesso', topic: 'arbeit' },
  { de: 'der Urlaub / die Ferien', it: 'le vacanze', topic: 'arbeit' },
  { de: 'der Termin', it: "l'appuntamento", topic: 'arbeit' },

  // ── Gesundheit ─────────────────────────────────────────────────────────────────────
  { de: 'die Gesundheit', it: 'la salute', topic: 'gesundheit' },
  { de: 'der Schmerz', it: 'il dolore', topic: 'gesundheit' },
  { de: 'das Fieber', it: 'la febbre', topic: 'gesundheit' },
  { de: 'die Krankheit', it: 'la malattia', topic: 'gesundheit' },
  { de: 'das Medikament', it: 'la medicina', topic: 'gesundheit' },
  { de: 'die Tablette', it: 'la pastiglia', topic: 'gesundheit' },
  { de: 'der Notfall', it: "l'emergenza", topic: 'gesundheit' },
  { de: 'der Schlaf', it: 'il sonno', topic: 'gesundheit' },

  // ── Technologie ─────────────────────────────────────────────────────────────────────
  { de: 'der Computer', it: 'il computer', topic: 'technik' },
  { de: 'das Handy', it: 'il cellulare', topic: 'technik' },
  { de: 'das Internet', it: 'internet', topic: 'technik' },
  { de: 'die E-Mail', it: "l'email", topic: 'technik' },
  { de: 'das Foto', it: 'la foto', topic: 'technik' },
  { de: 'das Video', it: 'il video', topic: 'technik' },
  { de: 'das Passwort', it: 'la password', topic: 'technik' },
  { de: 'der Bildschirm', it: 'lo schermo', topic: 'technik' },

  // ── Geld & Einkaufen ────────────────────────────────────────────────────────────────
  { de: 'das Geld', it: 'i soldi', topic: 'geld' },
  { de: 'der Preis', it: 'il prezzo', topic: 'geld' },
  { de: 'die Rechnung', it: 'il conto', topic: 'geld' },
  { de: 'die Kreditkarte', it: 'la carta di credito', topic: 'geld' },
  { de: 'das Bargeld', it: 'i contanti', topic: 'geld' },
  { de: 'das Angebot', it: "l'offerta", topic: 'geld' },
  { de: 'der Rabatt', it: 'lo sconto', topic: 'geld' },

  // ── Emotionen & Charakter ────────────────────────────────────────────────────────────
  { de: 'die Liebe', it: "l'amore", topic: 'gefuehle' },
  { de: 'die Freude', it: 'la gioia', topic: 'gefuehle' },
  { de: 'die Angst', it: 'la paura', topic: 'gefuehle' },
  { de: 'die Hoffnung', it: 'la speranza', topic: 'gefuehle' },
  { de: 'freundlich', it: 'gentile', topic: 'gefuehle' },
  { de: 'nett / sympathisch', it: 'simpatico', topic: 'gefuehle' },
  { de: 'höflich', it: 'educato', topic: 'gefuehle' },
  { de: 'ehrlich', it: 'onesto', topic: 'gefuehle' },
  { de: 'mutig', it: 'coraggioso', topic: 'gefuehle' },
  { de: 'schüchtern', it: 'timido', topic: 'gefuehle' },
  { de: 'geduldig', it: 'paziente', topic: 'gefuehle' },
  { de: 'lustig', it: 'divertente', topic: 'gefuehle' },
  { de: 'intelligent', it: 'intelligente', topic: 'gefuehle' },

  // ── Nützliche kleine Wörter (Adverbien, Präpositionen, Verbindungen) ──────────────────
  { de: 'und', it: 'e', topic: 'grundwoerter' },
  { de: 'oder', it: 'o', topic: 'grundwoerter' },
  { de: 'aber', it: 'ma', topic: 'grundwoerter' },
  { de: 'wenn / falls', it: 'se', topic: 'grundwoerter' },
  { de: 'auch', it: 'anche', topic: 'grundwoerter' },
  { de: 'auch nicht', it: 'neanche', topic: 'grundwoerter' },
  { de: 'sehr', it: 'molto', topic: 'grundwoerter' },
  { de: 'ein bisschen', it: "un po'", topic: 'grundwoerter' },
  { de: 'okay / einverstanden', it: "va bene", topic: 'grundwoerter' },
  { de: 'natürlich / klar', it: 'certo', topic: 'grundwoerter' },
  { de: 'fast', it: 'quasi', topic: 'grundwoerter' },
  { de: 'nur', it: 'solo', topic: 'grundwoerter' },
  { de: 'sogar', it: 'perfino', topic: 'grundwoerter' },
  { de: 'hier', it: 'qui', topic: 'grundwoerter' },
  { de: 'dort', it: 'lì', topic: 'grundwoerter' },
  { de: 'oben', it: 'sopra', topic: 'grundwoerter' },
  { de: 'unten', it: 'giù', topic: 'grundwoerter' },
  { de: 'drinnen', it: 'dentro', topic: 'grundwoerter' },
  { de: 'draußen', it: 'fuori', topic: 'grundwoerter' },
  { de: 'in', it: 'in', topic: 'grundwoerter' },
  { de: 'von / aus', it: 'di / da', topic: 'grundwoerter' },
  { de: 'mit', it: 'con', topic: 'grundwoerter' },
  { de: 'ohne', it: 'senza', topic: 'grundwoerter' },
  { de: 'für', it: 'per', topic: 'grundwoerter' },
  { de: 'zwischen', it: 'tra', topic: 'grundwoerter' },
  { de: 'gegen', it: 'contro', topic: 'grundwoerter' },
  { de: 'unter', it: 'sotto', topic: 'grundwoerter' },
  { de: 'über / auf', it: 'su', topic: 'grundwoerter' },
  { de: 'bis', it: 'fino a', topic: 'grundwoerter' },
  { de: 'während', it: 'durante', topic: 'grundwoerter' },
  { de: 'nach', it: 'dopo', topic: 'grundwoerter' },
  { de: 'vor (zeitlich)', it: 'prima di', topic: 'grundwoerter' },
];

// Dedupe by normalized Italian so an accidental repeat never yields a double card.
const seen = new Set<string>();
export const STARTER_VOCAB: CatalogWord[] = RAW.filter(w => {
  const k = normWord(w.it);
  if (seen.has(k)) return false;
  seen.add(k);
  return true;
});
