import type { Epoch } from '../types';

export const E4: Epoch = {
  id: 'nachkrieg',
  name: 'Aufstand und Freiheit',
  period: 'seit 1945',
  events: [
    {
      id: 'aufstand-1956',
      title: 'Aufstand 1956 und Grenzöffnung 1989',
      date: 'seit 1945',
      text: [
        'Nach 1945 errichteten die Kommunisten eine stalinistische Diktatur. Der Volksaufstand von 1956 wurde von sowjetischen Panzern niedergeschlagen. Unter Kádár entstand der vergleichsweise lockere „Gulaschkommunismus“, und 1989 öffnete Ungarn als erstes Land den Eisernen Vorhang. Heute ist Ungarn Mitglied von NATO und EU.',
      ],
      subtopics: [
        {
          id: 'kommunismus-1956',
          title: 'Rákosi, die Goldene Elf und der Aufstand 1956',
          date: '1945–1956',
          text: [
            'Bei den freien Wahlen im November 1945 gewann die Partei der Kleinlandwirte mit 57 Prozent, die Kommunisten erhielten nur 17 Prozent. Doch mit Unterstützung der Sowjetunion schalteten die Kommunisten ihre Gegner Stück für Stück aus – ihr Führer Mátyás Rákosi nannte das „Salamitaktik“. 1949 wurde Ungarn Volksrepublik. Zwischen 1946 und 1948 wurde etwa die Hälfte der Ungarndeutschen nach Deutschland vertrieben.',
            'Rákosi, der sich „Stalins besten Schüler“ nannte, ließ sich wie ein Gott verehren. Die Geheimpolizei ÁVH folterte Gegner in ihrem Hauptquartier in der Andrássy-Straße 60, heute das Museum „Haus des Terrors“. Kardinal József Mindszenty wurde 1949 in einem Schauprozess zu lebenslanger Haft verurteilt, und sogar der kommunistische Innenminister László Rajk wurde hingerichtet. Bauern wurden in Genossenschaften gezwungen, und Zehntausende kamen in Arbeitslager wie Recsk.',
            'Im Sport glänzte Ungarn: Die „Goldene Elf“ um Ferenc Puskás gewann 1952 olympisches Gold und besiegte 1953 England in Wembley 6:3 – Englands erste Heimniederlage gegen eine Mannschaft vom Kontinent. Im WM-Finale 1954 in Bern verlor sie jedoch überraschend 2:3 gegen Deutschland.',
            'Nach Stalins Tod 1953 wurde der Reformer Imre Nagy Ministerpräsident und lockerte die Diktatur, doch 1955 stürzte ihn Rákosi. 1956 kritisierte Chruschtschow in Moskau Stalin, und in Budapest diskutierten Intellektuelle im „Petőfi-Kreis“ offen über Freiheit.',
            'Am 23. Oktober 1956 demonstrierten Studenten aus Solidarität mit Polen. Die Menge stürzte das riesige Stalin-Denkmal, von dem nur die Stiefel übrig blieben. Als die Geheimpolizei am Rundfunkgebäude schoss, wurde daraus ein Volksaufstand. Imre Nagy wurde wieder Regierungschef, ließ andere Parteien zu und verkündete am 1. November den Austritt aus dem Warschauer Pakt. Am 4. November rollten sowjetische Panzer in Budapest ein; rund 2.500 Ungarn starben, etwa 200.000 flohen, vor allem über Österreich. Nagy wurde 1958 hingerichtet. Der 23. Oktober ist heute Nationalfeiertag.',
          ],
          quiz: {
            leicht: [
              ['Welche Partei gewann die freien Wahlen 1945?', 'Die Partei der Kleinlandwirte', ['Die Kommunisten', 'Die Pfeilkreuzler', 'Die Sozialdemokraten']],
              ['Wie viel Prozent erhielten die Kommunisten 1945?', '17 Prozent', ['57 Prozent', '7 Prozent', '87 Prozent']],
              ['Wer führte die ungarischen Kommunisten?', 'Mátyás Rákosi', ['Imre Nagy', 'János Kádár', 'Béla Kun']],
              ['Wie nannte Rákosi seine Methode, Gegner auszuschalten?', 'Salamitaktik', ['Gulaschkommunismus', 'Blitzkrieg', 'Kuhhandel']],
              ['Wann wurde Ungarn Volksrepublik?', '1949', ['1945', '1956', '1989']],
              ['Wie nannte sich Rákosi?', 'Stalins bester Schüler', ['Vater der Nation', 'Weiser der Nation', 'Retter Ungarns']],
              ['Wie hieß die ungarische Geheimpolizei?', 'ÁVH', ['Stasi', 'KGB', 'PIDE']],
              ['Welches Museum befindet sich heute im früheren Hauptquartier der ÁVH?', 'Das Haus des Terrors', ['Das Nationalmuseum', 'Das Parlament', 'Das Holocaust-Zentrum']],
              ['Welcher Kardinal wurde 1949 zu lebenslanger Haft verurteilt?', 'József Mindszenty', ['František Tomášek', 'Karol Wojtyła', 'Ottokár Prohászka']],
              ['Wie hieß die berühmte ungarische Fußballmannschaft der 1950er?', 'Die Goldene Elf', ['Die Rote Elf', 'Die Wunderelf', 'Die Donauelf']],
              ['Welcher Star führte die Goldene Elf?', 'Ferenc Puskás', ['Ferenc Molnár', 'Lajos Kossuth', 'Imre Nagy']],
              ['Gegen wen gewann Ungarn 1953 in Wembley 6:3?', 'Gegen England', ['Gegen Deutschland', 'Gegen Brasilien', 'Gegen Italien']],
              ['Gegen wen verlor Ungarn das WM-Finale 1954?', 'Gegen Deutschland', ['Gegen England', 'Gegen Brasilien', 'Gegen Uruguay']],
              ['Welcher Reformer wurde 1953 Ministerpräsident?', 'Imre Nagy', ['János Kádár', 'Mátyás Rákosi', 'László Rajk']],
              ['Wann begann der Ungarische Volksaufstand?', 'Am 23. Oktober 1956', ['Am 15. März 1956', 'Am 4. November 1956', 'Am 20. August 1956']],
              ['Welches Denkmal stürzte die Menge 1956?', 'Das Stalin-Denkmal', ['Das Lenin-Denkmal', 'Die Freiheitsstatue', 'Das Kossuth-Denkmal']],
              ['Was blieb vom Stalin-Denkmal übrig?', 'Die Stiefel', ['Der Kopf', 'Die Hand', 'Nichts']],
              ['Aus welchem Bündnis wollte Nagy austreten?', 'Aus dem Warschauer Pakt', ['Aus der NATO', 'Aus der EU', 'Aus der UNO']],
              ['Wer schlug den Aufstand nieder?', 'Sowjetische Panzer', ['Amerikanische Truppen', 'Österreichische Polizei', 'Die Goldene Elf']],
              ['Welcher Tag ist heute Nationalfeiertag zur Erinnerung an 1956?', 'Der 23. Oktober', ['Der 4. November', 'Der 15. März', 'Der 20. August']],
            ],
            mittel: [
              ['Wie viel Prozent erhielt die Partei der Kleinlandwirte 1945?', '57 Prozent', ['17 Prozent', '37 Prozent', '87 Prozent']],
              ['Mit wessen Unterstützung schalteten die Kommunisten Gegner aus?', 'Mit Unterstützung der Sowjetunion', ['Mit Unterstützung der USA', 'Mit Unterstützung der Kirche', 'Mit Unterstützung Österreichs']],
              ['Was bedeutet „Salamitaktik“?', 'Gegner Stück für Stück ausschalten', ['Wurst an Arme verteilen', 'Alles auf einmal verbieten', 'Mit allen Parteien teilen']],
              ['Wie viele Ungarndeutsche wurden 1946–1948 etwa vertrieben?', 'Etwa die Hälfte', ['Alle', 'Keiner', 'Ein Hundertstel']],
              ['Wo lag das Hauptquartier der ÁVH?', 'In der Andrássy-Straße 60', ['Auf der Burg', 'Im Parlament', 'Am Heldenplatz']],
              ['Wie ließ sich Rákosi verehren?', 'Wie ein Gott', ['Gar nicht', 'Wie ein Bettler', 'Wie ein Fußballspieler']],
              ['Welcher kommunistische Innenminister wurde hingerichtet?', 'László Rajk', ['Imre Nagy', 'János Kádár', 'Mátyás Rákosi']],
              ['Wann wurde Mindszenty verurteilt?', '1949', ['1945', '1956', '1953']],
              ['Wie hieß ein berüchtigtes Arbeitslager?', 'Recsk', ['Tarrafal', 'Jáchymov', 'Gulag Workuta']],
              ['Wohin wurden die Bauern gezwungen?', 'In Genossenschaften', ['In die Städte', 'Nach Sibirien', 'Ins Ausland']],
              ['Wann gewann die Goldene Elf olympisches Gold?', '1952', ['1956', '1948', '1964']],
              ['Was war besonders am 6:3 in Wembley 1953?', 'Englands erste Heimniederlage gegen eine Mannschaft vom Kontinent', ['Es war das erste Länderspiel', 'Ungarn verlor', 'Es war ein WM-Finale']],
              ['Wo fand das WM-Finale 1954 statt?', 'In Bern', ['In Budapest', 'In London', 'In Paris']],
              ['Wie endete das WM-Finale 1954?', '2:3 gegen Deutschland', ['6:3 gegen England', '1:0 für Ungarn', '4:0 für Ungarn']],
              ['Wann stürzte Rákosi Imre Nagy?', '1955', ['1953', '1956', '1949']],
              ['Wer kritisierte 1956 in Moskau Stalin?', 'Chruschtschow', ['Breschnew', 'Molotow', 'Gorbatschow']],
              ['Wie hieß der Diskussionskreis der Intellektuellen?', 'Petőfi-Kreis', ['Kossuth-Klub', 'Charta 56', 'Széchenyi-Bund']],
              ['Mit welchem Land zeigten die Studenten 1956 Solidarität?', 'Mit Polen', ['Mit der Tschechoslowakei', 'Mit Österreich', 'Mit Jugoslawien']],
              ['Wo schoss die Geheimpolizei auf die Menge?', 'Am Rundfunkgebäude', ['Am Parlament', 'An der Oper', 'Am Bahnhof']],
              ['Wann rollten sowjetische Panzer in Budapest ein?', 'Am 4. November 1956', ['Am 23. Oktober 1956', 'Am 1. November 1956', 'Am 15. März 1957']],
            ],
            schwer: [
              ['Wann verkündete Nagy den Austritt aus dem Warschauer Pakt?', 'Am 1. November 1956', ['Am 23. Oktober 1956', 'Am 4. November 1956', 'Am 16. Juni 1958']],
              ['Wann wurde Imre Nagy hingerichtet?', '1958', ['1956', '1957', '1989']],
              ['Wie viele Ungarn starben beim Aufstand etwa?', 'Rund 2.500', ['Rund 25', 'Rund 250.000', 'Rund 25.000.000']],
              ['Wie viele Ungarn flohen nach 1956 etwa?', 'Rund 200.000', ['Rund 2.000', 'Rund 20.000', 'Rund zwei Millionen']],
              ['Über welches Land flohen die meisten Ungarn 1956?', 'Über Österreich', ['Über Rumänien', 'Über die Sowjetunion', 'Über Polen']],
              ['Was ließ Nagy 1956 wieder zu?', 'Andere Parteien', ['Die Monarchie', 'Die ÁVH', 'Die Kollektivierung']],
              ['Wann wurden die Wahlen gewonnen, die die Kommunisten später unterliefen?', 'Im November 1945', ['Im März 1949', 'Im Oktober 1956', 'Im März 1990']],
              ['Was ist das Haus des Terrors heute?', 'Ein Museum', ['Ein Hotel', 'Ein Gefängnis', 'Ein Regierungssitz']],
              ['Wer war Ferenc Puskás?', 'Ein Fußballstar', ['Ein Ministerpräsident', 'Ein Dichter', 'Ein Kardinal']],
              ['In welchem Stadion besiegte Ungarn England 1953?', 'In Wembley', ['Im Népstadion', 'Im Wankdorfstadion', 'Im Maracanã']],
              ['Was folgte auf Stalins Tod 1953 in Ungarn?', 'Nagy wurde Ministerpräsident und lockerte die Diktatur', ['Rákosi wurde Präsident auf Lebenszeit', 'Ungarn trat der NATO bei', 'Der Aufstand begann']],
              ['Welches Ereignis machte den Aufstand aus einer Demonstration?', 'Die Schüsse der Geheimpolizei am Rundfunkgebäude', ['Ein Fußballspiel', 'Eine Rede Chruschtschows', 'Ein Erdbeben']],
              ['Welcher Kardinal wurde zum Symbol des kirchlichen Widerstands?', 'Mindszenty', ['Rajk', 'Nagy', 'Puskás']],
              ['Was wollte Nagy für Ungarn am 1. November 1956 verkünden?', 'Neutralität und Austritt aus dem Warschauer Pakt', ['Den Beitritt zur NATO', 'Die Rückkehr der Monarchie', 'Einen Krieg gegen Österreich']],
              ['Wie wirkte das 2:3 im WM-Finale 1954?', 'Als überraschende Niederlage', ['Als erwarteter Sieg', 'Als Unentschieden', 'Als Sieg Ungarns']],
              ['Wann starb Stalin?', '1953', ['1949', '1956', '1945']],
              ['Wer wurde 1949 als Innenminister Opfer eines Schauprozesses?', 'László Rajk', ['Mátyás Rákosi', 'Ernő Gerő', 'Imre Nagy']],
              ['Wohin wurde ein Teil der Ungarndeutschen vertrieben?', 'Nach Deutschland', ['Nach Amerika', 'Nach Rumänien', 'Nach Sibirien']],
              ['Welche Parteiführung stand hinter der Salamitaktik?', 'Die Kommunisten', ['Die Kleinlandwirte', 'Die Kirche', 'Die Sozialdemokraten']],
              ['Welche Strafe erhielt Mindszenty?', 'Lebenslange Haft', ['Die Todesstrafe', 'Eine Geldstrafe', 'Freispruch']],
            ],
          },
        },
        {
          id: 'kadar-1989',
          title: 'Gulaschkommunismus und Grenzöffnung 1989',
          date: '1956–1991',
          text: [
            'Nach dem Aufstand setzte Moskau János Kádár an die Spitze. Zuerst ließ er Hunderte Aufständische hinrichten, doch 1963 erließ er eine Amnestie und verkündete: „Wer nicht gegen uns ist, ist mit uns.“ Es entstand der „Gulaschkommunismus“, eine vergleichsweise lockere Form des Sozialismus.',
            '1968 führte Ungarn mit dem „Neuen Wirtschaftsmechanismus“ Elemente der Marktwirtschaft ein. Viele Menschen verdienten mit kleinen Nebengeschäften dazu, bauten Wochenendhäuser und durften alle paar Jahre in den Westen reisen. Man nannte Ungarn „die lustigste Baracke im Ostblock“. 1974 erfand der Architekt Ernő Rubik den Zauberwürfel, der ab 1980 weltweit verkauft wurde. Am Balaton trafen sich Familien aus West- und Ostdeutschland. Doch der Wohlstand wurde mit hohen Schulden im Westen bezahlt.',
            '1988 wurde Kádár abgesetzt, und Reformkommunisten wie Miklós Németh und Gyula Horn übernahmen die Führung. Am 2. Mai 1989 begann Ungarn, den Grenzzaun zu Österreich abzubauen; am 27. Juni zerschnitten Außenminister Gyula Horn und sein österreichischer Kollege Alois Mock symbolisch den Stacheldraht. Am 16. Juni 1989 wurde Imre Nagy vor rund 250.000 Menschen feierlich neu bestattet; der junge Viktor Orbán forderte dabei den Abzug der sowjetischen Truppen.',
            'Am 19. August 1989 nutzten Hunderte DDR-Bürger das „Paneuropäische Picknick“ an der Grenze bei Sopron zur Flucht nach Österreich. Am 11. September 1989 öffnete Ungarn die Grenze offiziell für alle DDR-Bürger – ein wichtiger Schritt auf dem Weg zum Fall der Berliner Mauer.',
            'Am 23. Oktober 1989, dem Jahrestag des Aufstands, wurde die Republik Ungarn ausgerufen; die Volksrepublik endete. Im Frühjahr 1990 fanden freie Wahlen statt, und József Antall vom Ungarischen Demokratischen Forum wurde Ministerpräsident, der Schriftsteller Árpád Göncz Präsident. Bis Juni 1991 zogen die sowjetischen Truppen ab.',
          ],
          quiz: {
            leicht: [
              ['Wen setzte Moskau nach dem Aufstand an die Spitze Ungarns?', 'János Kádár', ['Imre Nagy', 'Mátyás Rákosi', 'Viktor Orbán']],
              ['Wie nennt man Kádárs lockere Form des Sozialismus?', 'Gulaschkommunismus', ['Salamitaktik', 'Prager Frühling', 'Perestroika']],
              ['Welchen Satz verkündete Kádár?', '„Wer nicht gegen uns ist, ist mit uns.“', ['„Wer nicht für uns ist, ist gegen uns.“', '„Die Wahrheit siegt.“', '„Nein, nein, niemals!“']],
              ['Wie nannte man Ungarn im Ostblock?', 'Die lustigste Baracke', ['Das Gefängnis', 'Den Bruderstaat', 'Die Festung']],
              ['Wer erfand den Zauberwürfel?', 'Ernő Rubik', ['Ferenc Puskás', 'János Kádár', 'Tivadar Puskás']],
              ['Wann wurde der Zauberwürfel erfunden?', '1974', ['1956', '1989', '1968']],
              ['An welchem See trafen sich Familien aus Ost- und Westdeutschland?', 'Am Balaton', ['Am Bodensee', 'Am Gardasee', 'Am Neusiedler See']],
              ['Wann wurde Kádár abgesetzt?', '1988', ['1956', '1989', '1968']],
              ['Wann begann Ungarn, den Grenzzaun zu Österreich abzubauen?', 'Am 2. Mai 1989', ['Am 9. November 1989', 'Am 23. Oktober 1956', 'Am 1. Mai 2004']],
              ['Welche Außenminister zerschnitten 1989 symbolisch den Grenzzaun?', 'Gyula Horn und Alois Mock', ['Viktor Orbán und Helmut Kohl', 'Imre Nagy und Bruno Kreisky', 'János Kádár und Erich Honecker']],
              ['Wessen feierliche Neubestattung fand am 16. Juni 1989 statt?', 'Die von Imre Nagy', ['Die von János Kádár', 'Die von Mátyás Rákosi', 'Die von Lajos Kossuth']],
              ['Welcher junge Politiker forderte 1989 den Abzug der sowjetischen Truppen?', 'Viktor Orbán', ['Gyula Horn', 'József Antall', 'Ferenc Gyurcsány']],
              ['Wie hieß das Ereignis, bei dem im August 1989 Hunderte DDR-Bürger flohen?', 'Paneuropäisches Picknick', ['Wiener Walzer', 'Grenzfest Sopron', 'Balaton-Treffen']],
              ['Bei welcher Stadt fand das Paneuropäische Picknick statt?', 'Bei Sopron', ['Bei Budapest', 'Bei Debrecen', 'Bei Szeged']],
              ['Wann öffnete Ungarn die Grenze offiziell für DDR-Bürger?', 'Am 11. September 1989', ['Am 9. November 1989', 'Am 19. August 1989', 'Am 2. Mai 1989']],
              ['Wozu trug die Grenzöffnung Ungarns bei?', 'Zum Fall der Berliner Mauer', ['Zum Bau der Mauer', 'Zum Aufstand 1956', 'Zur Teilung Deutschlands']],
              ['Wann wurde die Republik Ungarn ausgerufen?', 'Am 23. Oktober 1989', ['Am 1. Mai 2004', 'Am 4. November 1956', 'Am 15. März 1990']],
              ['Wer wurde 1990 Ministerpräsident?', 'József Antall', ['Viktor Orbán', 'Gyula Horn', 'Miklós Németh']],
              ['Wer wurde 1990 Präsident?', 'Árpád Göncz', ['János Kádár', 'Imre Pozsgay', 'Ferenc Mádl']],
              ['Bis wann zogen die sowjetischen Truppen ab?', 'Bis Juni 1991', ['Bis 1989', 'Bis 1995', 'Bis 1956']],
            ],
            mittel: [
              ['Was tat Kádár zuerst nach dem Aufstand?', 'Er ließ Hunderte Aufständische hinrichten', ['Er erließ eine Amnestie', 'Er trat zurück', 'Er floh nach Moskau']],
              ['Wann erließ Kádár eine Amnestie?', '1963', ['1956', '1968', '1989']],
              ['Was führte Ungarn 1968 ein?', 'Den Neuen Wirtschaftsmechanismus', ['Den Euro', 'Die Kollektivierung', 'Den Warschauer Pakt']],
              ['Was brachte der Neue Wirtschaftsmechanismus?', 'Elemente der Marktwirtschaft', ['Eine strengere Planwirtschaft', 'Die Abschaffung des Geldes', 'Den Austritt aus dem Ostblock']],
              ['Was durften viele Ungarn alle paar Jahre?', 'In den Westen reisen', ['Den Präsidenten wählen', 'Nach Moskau ziehen', 'Ein Auto aus dem Westen geschenkt bekommen']],
              ['Was bauten viele Ungarn im Gulaschkommunismus?', 'Wochenendhäuser', ['Raketen', 'Kirchen', 'Grenzzäune']],
              ['Was war Ernő Rubik von Beruf?', 'Architekt', ['Fußballspieler', 'Politiker', 'Arzt']],
              ['Ab wann wurde der Zauberwürfel weltweit verkauft?', 'Ab 1980', ['Ab 1974', 'Ab 1990', 'Ab 1968']],
              ['Womit wurde der Wohlstand im Gulaschkommunismus bezahlt?', 'Mit hohen Schulden im Westen', ['Mit Gold aus Russland', 'Mit Öl', 'Mit Kolonien']],
              ['Welche Reformkommunisten übernahmen 1988 die Führung?', 'Miklós Németh und Gyula Horn', ['Rákosi und Gerő', 'Orbán und Antall', 'Kádár und Nagy']],
              ['Wann zerschnitten Horn und Mock den Zaun?', 'Am 27. Juni 1989', ['Am 2. Mai 1989', 'Am 19. August 1989', 'Am 11. September 1989']],
              ['Wie viele Menschen kamen zur Neubestattung Nagys?', 'Rund 250.000', ['Rund 2.500', 'Rund 25.000', 'Rund 2,5 Millionen']],
              ['Wann fand das Paneuropäische Picknick statt?', 'Am 19. August 1989', ['Am 11. September 1989', 'Am 9. November 1989', 'Am 16. Juni 1989']],
              ['Wohin flohen die DDR-Bürger beim Picknick?', 'Nach Österreich', ['Nach Jugoslawien', 'Nach Polen', 'Nach Westberlin direkt']],
              ['Warum wählte man den 23. Oktober 1989 für die Ausrufung der Republik?', 'Es war der Jahrestag des Aufstands', ['Es war Kádárs Geburtstag', 'Es war der Tag des Mauerfalls', 'Es war der Stephanstag']],
              ['Was endete mit der Ausrufung der Republik?', 'Die Volksrepublik', ['Die Monarchie', 'Die NATO-Mitgliedschaft', 'Die EU-Mitgliedschaft']],
              ['Wann fanden die ersten freien Wahlen statt?', 'Im Frühjahr 1990', ['Im Herbst 1989', 'Im Jahr 1991', 'Im Jahr 1994']],
              ['Was war Árpád Göncz außer Präsident?', 'Schriftsteller', ['General', 'Fußballspieler', 'Kardinal']],
              ['Wer war österreichischer Außenminister 1989?', 'Alois Mock', ['Bruno Kreisky', 'Kurt Waldheim', 'Franz Vranitzky']],
              ['Was zerschnitten die beiden Außenminister?', 'Den Stacheldraht des Grenzzauns', ['Ein Band zur Brückeneröffnung', 'Einen Vertrag', 'Eine Fahne']],
            ],
            schwer: [
              ['Wann verkündete Kádár „Wer nicht gegen uns ist, ist mit uns“?', 'In den frühen 1960er-Jahren', ['1956 vor dem Aufstand', '1989', '1945']],
              ['Wer war Miklós Németh?', 'Reformkommunistischer Ministerpräsident 1988/89', ['Erfinder des Zauberwürfels', 'Fußballstar', 'Präsident 1990']],
              ['Welches Ereignis am 16. Juni 1989 war ein Bruch mit der Vergangenheit?', 'Die Neubestattung von Imre Nagy', ['Die Wahl Antalls', 'Der Mauerfall', 'Der NATO-Beitritt']],
              ['Was forderte Orbán bei der Neubestattung Nagys?', 'Den Abzug der sowjetischen Truppen', ['Die Rückkehr Kádárs', 'Den Beitritt zur NATO sofort', 'Die Wiedervereinigung Deutschlands']],
              ['Welche Rolle spielte Ungarn 1989 für die DDR-Bürger?', 'Es öffnete ihnen den Weg in den Westen', ['Es schickte sie zurück', 'Es nahm sie gefangen', 'Es schloss die Grenze']],
              ['Wie lange dauerte es von der Grenzöffnung bis zum Mauerfall?', 'Knapp zwei Monate', ['Zwei Jahre', 'Zwei Tage', 'Zehn Jahre']],
              ['Welches Spielzeug wurde zum ungarischen Exportschlager?', 'Der Zauberwürfel', ['Die Barbie', 'Lego', 'Der Gameboy']],
              ['Was wurde 1974 in Ungarn erfunden?', 'Der Zauberwürfel', ['Der Kugelschreiber', 'Die Telefonzentrale', 'Der Elektromotor']],
              ['Welches Ziel hatte der Neue Wirtschaftsmechanismus?', 'Mehr Marktwirtschaft', ['Weniger Handel', 'Die Abschaffung der Industrie', 'Die Rückkehr zum Stalinismus']],
              ['Wie wurde Ungarn unter Kádár im Vergleich zu anderen Ostblockländern gesehen?', 'Als freier und lockerer', ['Als strenger', 'Als ärmer', 'Als gleich']],
              ['Welche Partei stellte 1990 den Ministerpräsidenten?', 'Das Ungarische Demokratische Forum', ['Die Kommunisten', 'Fidesz', 'Die Sozialisten']],
              ['Wann zogen die letzten sowjetischen Truppen ab?', 'Im Juni 1991', ['Im Juni 1989', 'Im Dezember 1990', 'Im Jahr 1994']],
              ['Wie viele Aufständische ließ Kádár hinrichten?', 'Hunderte', ['Keinen', 'Einen', 'Hunderttausende']],
              ['Welcher Grenzzaun wurde 1989 abgebaut?', 'Der zu Österreich', ['Der zu Rumänien', 'Der zur Sowjetunion', 'Der zu Jugoslawien']],
              ['Welcher Staat entstand am 23. Oktober 1989?', 'Die Republik Ungarn', ['Die Volksrepublik Ungarn', 'Das Königreich Ungarn', 'Die Ungarische Räterepublik']],
              ['Wer reiste zum Balaton, um Verwandte zu treffen?', 'Familien aus West- und Ostdeutschland', ['Familien aus Russland', 'Touristen aus Amerika', 'Niemand']],
              ['Wann öffnete Ungarn die Grenze für alle DDR-Bürger?', 'Im September 1989', ['Im August 1989', 'Im November 1989', 'Im Mai 1989']],
              ['Was war 1963 in Ungarn neu?', 'Eine Amnestie', ['Der Zauberwürfel', 'Der Warschauer Pakt', 'Die Grenzöffnung']],
              ['Woher kam die Ernennung Kádárs?', 'Aus Moskau', ['Aus Wien', 'Aus Washington', 'Vom ungarischen Volk']],
              ['Wie viele DDR-Bürger flohen beim Paneuropäischen Picknick?', 'Hunderte', ['Einer', 'Hunderttausende', 'Keiner']],
            ],
          },
        },
        {
          id: 'ungarn-heute',
          title: 'Ungarn in NATO und EU',
          date: 'seit 1990',
          text: [
            'Nach der Wende führte Ungarn die Marktwirtschaft ein; Staatsbetriebe wurden privatisiert, und viele Menschen verloren ihre Arbeit. 1999 trat Ungarn zusammen mit Polen und Tschechien der NATO bei, am 1. Mai 2004 der Europäischen Union und 2007 dem Schengen-Raum. Den Euro hat Ungarn nicht eingeführt; die Währung ist der Forint.',
            '2006 wurde eine geheime Rede des sozialistischen Ministerpräsidenten Ferenc Gyurcsány bekannt, in der er zugab, die Regierung habe die Bürger über die Lage des Landes belogen. Es kam zu schweren Unruhen. In der Finanzkrise 2008 brauchte Ungarn einen Notkredit des Internationalen Währungsfonds.',
            '2010 gewann Viktor Orbán mit seiner Partei Fidesz eine Zweidrittelmehrheit und ließ eine neue Verfassung ausarbeiten, das „Grundgesetz“, das 2012 in Kraft trat. Die EU kritisiert seitdem Einschränkungen der Pressefreiheit, der Justiz und des Rechtsstaats; 2014 sprach Orbán selbst von einer „illiberalen Demokratie“. In der Flüchtlingskrise 2015 ließ Ungarn einen Grenzzaun zu Serbien und Kroatien bauen. Die von George Soros gegründete Central European University musste 2019 nach Wien umziehen, und die EU hielt wegen Rechtsstaatsbedenken Fördergelder zurück.',
            'Ungarn ist reich an Nobelpreisträgern. Der Auschwitz-Überlebende Imre Kertész erhielt 2002 den Literaturnobelpreis für seinen „Roman eines Schicksallosen“. 2023 erhielten Katalin Karikó für ihre Forschung zur mRNA, die die Grundlage für Corona-Impfstoffe legte, den Medizinnobelpreis und Ferenc Krausz den Physiknobelpreis.',
            'Seit 1986 findet auf dem Hungaroring bei Budapest ein Formel-1-Rennen statt – das erste hinter dem Eisernen Vorhang. Bei Olympischen Spielen ist Ungarn im Verhältnis zu seiner Größe eines der erfolgreichsten Länder, vor allem im Wasserball, Schwimmen und Fechten.',
          ],
          quiz: {
            leicht: [
              ['Welches Wirtschaftssystem führte Ungarn nach der Wende ein?', 'Die Marktwirtschaft', ['Die Planwirtschaft', 'Den Feudalismus', 'Den Tauschhandel']],
              ['Wann trat Ungarn der NATO bei?', '1999', ['1989', '2004', '2010']],
              ['Mit welchen Ländern trat Ungarn 1999 der NATO bei?', 'Mit Polen und Tschechien', ['Mit Österreich und der Slowakei', 'Mit Rumänien und Bulgarien', 'Mit Schweden und Finnland']],
              ['Wann trat Ungarn der EU bei?', 'Am 1. Mai 2004', ['Am 1. Januar 1995', 'Im Jahr 1999', 'Im Jahr 2010']],
              ['Wie heißt die ungarische Währung?', 'Forint', ['Euro', 'Krone', 'Zloty']],
              ['Hat Ungarn den Euro eingeführt?', 'Nein', ['Ja, 2004', 'Ja, 2007', 'Ja, 2010']],
              ['Wer gewann 2010 eine Zweidrittelmehrheit?', 'Viktor Orbán', ['Ferenc Gyurcsány', 'Gyula Horn', 'József Antall']],
              ['Wie heißt die Partei von Viktor Orbán?', 'Fidesz', ['MSZP', 'Jobbik', 'MDF']],
              ['Wie heißt Ungarns Verfassung von 2012?', 'Grundgesetz', ['Goldene Bulle', 'Aprilgesetze', 'Magna Carta']],
              ['Was kritisiert die EU an Ungarn?', 'Einschränkungen von Pressefreiheit, Justiz und Rechtsstaat', ['Zu viele Steuern', 'Zu wenige Brücken', 'Den Forint']],
              ['Von welcher Art Demokratie sprach Orbán 2014?', 'Von einer illiberalen Demokratie', ['Von einer direkten Demokratie', 'Von einer Rätedemokratie', 'Von einer Monarchie']],
              ['Was ließ Ungarn 2015 an der Grenze bauen?', 'Einen Grenzzaun', ['Eine Brücke', 'Einen Flughafen', 'Einen Kanal']],
              ['Welche Universität musste 2019 nach Wien umziehen?', 'Die Central European University', ['Die Universität Budapest', 'Die Universität Szeged', 'Die Universität Oxford']],
              ['Welcher ungarische Autor erhielt 2002 den Literaturnobelpreis?', 'Imre Kertész', ['Sándor Márai', 'Péter Esterházy', 'Sándor Petőfi']],
              ['Welches Buch schrieb Imre Kertész?', '„Roman eines Schicksallosen“', ['„Die Glut“', '„Der Zauberwürfel“', '„Die Tragödie des Menschen“']],
              ['Welche Forscherin erhielt 2023 den Medizinnobelpreis?', 'Katalin Karikó', ['Marie Curie', 'Ada Lovelace', 'Emmy Noether']],
              ['Wofür legte Karikós Forschung die Grundlage?', 'Für Corona-Impfstoffe', ['Für Antibiotika', 'Für Röntgenstrahlen', 'Für Insulin']],
              ['Welcher Ungar erhielt 2023 den Physiknobelpreis?', 'Ferenc Krausz', ['Ernő Rubik', 'Ferenc Puskás', 'Albert Szent-Györgyi']],
              ['Wie heißt die Formel-1-Rennstrecke bei Budapest?', 'Hungaroring', ['Nürburgring', 'Monza', 'Spa']],
              ['In welcher Sportart ist Ungarn bei Olympia besonders stark?', 'Im Wasserball', ['Im Baseball', 'Im Eishockey', 'Im Cricket']],
            ],
            mittel: [
              ['Was geschah mit vielen Staatsbetrieben nach der Wende?', 'Sie wurden privatisiert', ['Sie wurden vergrößert', 'Sie wurden verstaatlicht', 'Sie blieben unverändert']],
              ['Was verloren viele Menschen nach der Wende?', 'Ihre Arbeit', ['Ihr Wahlrecht', 'Ihre Sprache', 'Ihre Staatsbürgerschaft']],
              ['Wann trat Ungarn dem Schengen-Raum bei?', '2007', ['2004', '1999', '2015']],
              ['Welcher Ministerpräsident gab 2006 in einer geheimen Rede Lügen zu?', 'Ferenc Gyurcsány', ['Viktor Orbán', 'Gyula Horn', 'Péter Medgyessy']],
              ['Welcher Partei gehörte Gyurcsány an?', 'Den Sozialisten', ['Fidesz', 'Den Kleinlandwirten', 'Den Grünen']],
              ['Was folgte auf das Bekanntwerden der Rede 2006?', 'Schwere Unruhen', ['Ein Volksfest', 'Ein Krieg', 'Der Euro-Beitritt']],
              ['Was brauchte Ungarn in der Finanzkrise 2008?', 'Einen Notkredit des IWF', ['Einen Krieg', 'Eine neue Währung', 'Eine Monarchie']],
              ['Wann trat das neue Grundgesetz in Kraft?', '2012', ['2010', '1989', '2004']],
              ['Wann sprach Orbán von einer „illiberalen Demokratie“?', '2014', ['2010', '2006', '2019']],
              ['Zu welchen Ländern ließ Ungarn 2015 einen Grenzzaun bauen?', 'Zu Serbien und Kroatien', ['Zu Österreich und der Slowakei', 'Zu Rumänien und der Ukraine', 'Zu Slowenien und Italien']],
              ['Wer gründete die Central European University?', 'George Soros', ['Viktor Orbán', 'Ernő Rubik', 'Imre Kertész']],
              ['Was hielt die EU wegen Rechtsstaatsbedenken zurück?', 'Fördergelder', ['Truppen', 'Den Euro', 'Flüchtlinge']],
              ['Was hatte Imre Kertész überlebt?', 'Auschwitz', ['Den Aufstand 1956 im Gefängnis', 'Ein Erdbeben', 'Den Untergang der Titanic']],
              ['Woran forschte Katalin Karikó?', 'An mRNA', ['An Kernspaltung', 'An Robotern', 'An Klimamodellen']],
              ['Wann erhielten Karikó und Krausz ihre Nobelpreise?', '2023', ['2002', '2010', '1989']],
              ['Seit wann findet auf dem Hungaroring ein Formel-1-Rennen statt?', 'Seit 1986', ['Seit 1956', 'Seit 2004', 'Seit 1999']],
              ['Was war das Besondere am Formel-1-Rennen in Ungarn 1986?', 'Es war das erste hinter dem Eisernen Vorhang', ['Es war das erste der Welt', 'Es fand im Winter statt', 'Es gewann ein Ungar']],
              ['In welchen Sportarten ist Ungarn außer Wasserball stark?', 'Im Schwimmen und Fechten', ['Im Skispringen und Rodeln', 'Im Basketball und Baseball', 'Im Surfen und Segeln']],
              ['Wie erfolgreich ist Ungarn bei Olympia im Verhältnis zu seiner Größe?', 'Eines der erfolgreichsten Länder', ['Eines der schwächsten Länder', 'Es nimmt nicht teil', 'Durchschnittlich']],
              ['Wer kritisiert Ungarns Umgang mit dem Rechtsstaat?', 'Die EU', ['Die Sowjetunion', 'Der Papst', 'Österreich-Ungarn']],
            ],
            schwer: [
              ['Welche Mehrheit gewann Fidesz 2010?', 'Eine Zweidrittelmehrheit', ['Eine knappe Mehrheit', 'Keine Mehrheit', 'Hundert Prozent']],
              ['Was ermöglichte die Zweidrittelmehrheit?', 'Eine neue Verfassung', ['Den Euro', 'Den Austritt aus der EU', 'Die Monarchie']],
              ['Wohin zog die Central European University?', 'Nach Wien', ['Nach Prag', 'Nach Berlin', 'Nach London']],
              ['Wann musste die Central European University umziehen?', '2019', ['2010', '2015', '2004']],
              ['Wann wurde Gyurcsánys geheime Rede bekannt?', '2006', ['2008', '2010', '2004']],
              ['Welche Folge hatte Karikós Forschung in der Pandemie?', 'Sie ermöglichte Corona-Impfstoffe', ['Sie verhinderte Lockdowns', 'Sie erfand Masken', 'Sie hatte keine Folgen']],
              ['Wofür erhielt Imre Kertész den Nobelpreis?', 'Für Literatur', ['Für Frieden', 'Für Medizin', 'Für Physik']],
              ['Welche drei Länder traten 1999 gemeinsam der NATO bei?', 'Ungarn, Polen und Tschechien', ['Ungarn, Österreich und die Slowakei', 'Ungarn, Rumänien und Bulgarien', 'Ungarn, Schweden und Finnland']],
              ['Was war die Grenze 2015 für Ungarn?', 'Ein Brennpunkt der Flüchtlingskrise', ['Ein Ferienziel', 'Eine geöffnete Grenze ohne Kontrolle', 'Ein Kriegsgebiet']],
              ['Welches Ereignis brachte Ungarn 2008 in Not?', 'Die Finanzkrise', ['Der NATO-Beitritt', 'Der Aufstand', 'Ein Erdbeben']],
              ['Welcher ungarische Forscher erhielt 2023 den Physiknobelpreis?', 'Ferenc Krausz', ['Ferenc Gyurcsány', 'Ferenc Puskás', 'Ferenc Deák']],
              ['Was ist der Forint?', 'Die ungarische Währung', ['Ein Gericht', 'Eine Partei', 'Ein Fluss']],
              ['Welche Rolle spielte Fidesz ab 2010?', 'Regierungspartei mit Zweidrittelmehrheit', ['Kleine Opposition', 'Verbotene Partei', 'Gewerkschaft']],
              ['Wann trat Ungarn der Europäischen Union bei?', '2004', ['1995', '2007', '1999']],
              ['Was gab Gyurcsány in seiner Rede zu?', 'Dass die Regierung die Bürger belogen hatte', ['Dass er zurücktreten wolle', 'Dass Ungarn den Euro einführe', 'Dass er Kommunist sei']],
              ['Wie heißt die Verfassung Ungarns seit 2012 auf Deutsch?', 'Grundgesetz', ['Hauptgesetz', 'Staatsbrief', 'Kronrecht']],
              ['Was ist am Hungaroring geschichtlich besonders?', 'Erstes Formel-1-Rennen hinter dem Eisernen Vorhang', ['Älteste Rennstrecke der Welt', 'Längste Rennstrecke Europas', 'Erste Strecke mit Nachtrennen']],
              ['Wann ließ Ungarn den Grenzzaun bauen?', '2015', ['2010', '2004', '1989']],
              ['Was ist der „Roman eines Schicksallosen“?', 'Ein Roman über das Leben in Auschwitz', ['Ein Kinderbuch', 'Ein Sachbuch über Fußball', 'Ein Gedichtband über den Balaton']],
              ['Wie viele Nobelpreise gingen 2023 an Ungarn?', 'Zwei', ['Einen', 'Drei', 'Keinen']],
            ],
          },
        },
      ],
    },
  ],
};
