import type { Epoch } from '../types';

export const E1: Epoch = {
  id: 'fruehzeit',
  name: 'Kelten, Slawen und Přemysliden',
  period: 'bis 1306',
  events: [
    {
      id: 'premysliden',
      title: 'Großmähren und die Přemysliden',
      date: 'bis 1306',
      text: [
        'Nach Kelten und Germanen wanderten im 6. Jahrhundert Slawen ein. Im 9. Jahrhundert entstand das Großmährische Reich, in dem Kyrill und Method in slawischer Sprache predigten. Danach machten die Přemysliden Böhmen zu einem reichen Königreich im Heiligen Römischen Reich.',
      ],
      subtopics: [
        {
          id: 'kelten-grossmaehren',
          title: 'Kelten, Germanen und Großmähren',
          date: '29.000 v. Chr.–906',
          text: [
            'Zu den ältesten Kunstwerken der Menschheit gehört die „Venus von Dolní Věstonice“ aus Südmähren, eine Frauenfigur aus gebranntem Ton, rund 29.000 Jahre alt. Sie ist eine der ältesten Keramiken der Welt. In Mähren lebten damals Mammutjäger.',
            'Ab etwa 400 v. Chr. lebte in Böhmen der keltische Stamm der Boier. Von ihnen stammt der lateinische Name „Boiohaemum“, „Heimat der Boier“, aus dem „Böhmen“ wurde. Die Kelten bauten große befestigte Siedlungen, „Oppida“. Um die Zeitenwende kamen germanische Markomannen unter ihrem König Marbod. Im 2. Jahrhundert kämpften sie unter Kaiser Mark Aurel in den Markomannenkriegen gegen Rom.',
            'Im 6. Jahrhundert wanderten Slawen ein, die Vorfahren der Tschechen. Um 623 vereinte der fränkische Kaufmann Samo die Slawen gegen die Awaren, ein Reitervolk aus dem Osten. „Samos Reich“ gilt als erstes slawisches Staatsgebilde; 631 besiegte Samo sogar ein Heer des Frankenkönigs Dagobert.',
            'Im 9. Jahrhundert entstand das Großmährische Reich (um 830–906). Fürst Rastislav bat den byzantinischen Kaiser um Missionare, die in der Sprache des Volkes predigen konnten. 863 kamen die Brüder Kyrill und Method aus Thessaloniki. Sie schufen die glagolitische Schrift und übersetzten die Gottesdienstbücher ins Altkirchenslawische. Unter Fürst Svatopluk erreichte Großmähren seine größte Ausdehnung.',
            'Nach Methods Tod 885 vertrieben fränkische Priester seine Schüler, die nach Bulgarien zogen; dort entstand später die kyrillische Schrift. Um 906 zerstörten die Magyaren, die Vorfahren der Ungarn, das Großmährische Reich. Danach stieg Böhmen unter dem Geschlecht der Přemysliden auf.',
          ],
          quiz: {
            leicht: [
              ['Wie heißt die berühmte Tonfigur aus Südmähren?', 'Venus von Dolní Věstonice', ['Venus von Milo', 'Venus von Willendorf', 'Nofretete']],
              ['Woraus besteht die Venus von Dolní Věstonice?', 'Aus gebranntem Ton', ['Aus Elfenbein', 'Aus Bronze', 'Aus Marmor']],
              ['Wie alt ist die Venus von Dolní Věstonice etwa?', 'Rund 29.000 Jahre', ['Rund 2.900 Jahre', 'Rund 290 Jahre', 'Rund 290.000 Jahre']],
              ['Welche Tiere jagten die Menschen damals in Mähren?', 'Mammuts', ['Elefanten', 'Dinosaurier', 'Kängurus']],
              ['Welcher keltische Stamm lebte in Böhmen?', 'Die Boier', ['Die Helvetier', 'Die Gallier', 'Die Briten']],
              ['Woher hat Böhmen seinen Namen?', 'Von den keltischen Boiern', ['Von den Bohnen', 'Von einem König Bohemund', 'Von den Böhmerwäldern']],
              ['Was bedeutet „Boiohaemum“?', 'Heimat der Boier', ['Land der Wälder', 'Burg der Kelten', 'Fluss der Slawen']],
              ['Welches germanische Volk kam um die Zeitenwende nach Böhmen?', 'Die Markomannen', ['Die Goten', 'Die Sachsen', 'Die Wikinger']],
              ['Wie hieß der König der Markomannen?', 'Marbod', ['Arminius', 'Attila', 'Samo']],
              ['Gegen wen kämpften die Markomannen?', 'Gegen Rom', ['Gegen die Wikinger', 'Gegen die Osmanen', 'Gegen China']],
              ['Wann wanderten Slawen in Böhmen ein?', 'Im 6. Jahrhundert', ['Im 1. Jahrhundert v. Chr.', 'Im 12. Jahrhundert', 'Im 15. Jahrhundert']],
              ['Wer vereinte um 623 die Slawen?', 'Samo', ['Marbod', 'Svatopluk', 'Karl der Große']],
              ['Gegen welches Reitervolk kämpfte Samo?', 'Gegen die Awaren', ['Gegen die Mongolen', 'Gegen die Hunnen', 'Gegen die Türken']],
              ['Welches Reich entstand im 9. Jahrhundert?', 'Das Großmährische Reich', ['Das Heilige Römische Reich', 'Das Osmanische Reich', 'Das Königreich Polen']],
              ['Welche Brüder kamen 863 als Missionare nach Großmähren?', 'Kyrill und Method', ['Peter und Paul', 'Romulus und Remus', 'Jacob und Wilhelm']],
              ['Aus welcher Stadt kamen Kyrill und Method?', 'Aus Thessaloniki', ['Aus Rom', 'Aus Prag', 'Aus Kiew']],
              ['Welche Schrift schufen Kyrill und Method?', 'Die glagolitische Schrift', ['Die lateinische Schrift', 'Die Runenschrift', 'Die arabische Schrift']],
              ['Welche Schrift entstand später in Bulgarien?', 'Die kyrillische Schrift', ['Die glagolitische Schrift', 'Die griechische Schrift', 'Die lateinische Schrift']],
              ['Wer zerstörte um 906 das Großmährische Reich?', 'Die Magyaren', ['Die Franken', 'Die Römer', 'Die Wikinger']],
              ['Welches Geschlecht stieg danach in Böhmen auf?', 'Die Přemysliden', ['Die Habsburger', 'Die Luxemburger', 'Die Jagiellonen']],
            ],
            mittel: [
              ['Was ist das Besondere an der Venus von Dolní Věstonice?', 'Sie ist eine der ältesten Keramiken der Welt', ['Sie ist aus Gold', 'Sie ist die größte Statue Europas', 'Sie stammt aus Rom']],
              ['Ab wann lebten die Boier in Böhmen?', 'Ab etwa 400 v. Chr.', ['Ab etwa 29.000 v. Chr.', 'Ab etwa 600 n. Chr.', 'Ab etwa 1000 n. Chr.']],
              ['Wie heißen die befestigten Siedlungen der Kelten?', 'Oppida', ['Poleis', 'Castros', 'Burgen']],
              ['Unter welchem Kaiser kämpften die Markomannen gegen Rom?', 'Unter Mark Aurel', ['Unter Augustus', 'Unter Nero', 'Unter Konstantin']],
              ['In welchem Jahrhundert waren die Markomannenkriege?', 'Im 2. Jahrhundert', ['Im 5. Jahrhundert v. Chr.', 'Im 9. Jahrhundert', 'Im 13. Jahrhundert']],
              ['Wer waren die Slawen für die Tschechen?', 'Ihre Vorfahren', ['Ihre Feinde aus dem Westen', 'Römische Siedler', 'Keltische Nachbarn']],
              ['Was war Samo von Beruf?', 'Fränkischer Kaufmann', ['Slawischer Fürst', 'Römischer Soldat', 'Mönch aus Byzanz']],
              ['Als was gilt Samos Reich?', 'Als erstes slawisches Staatsgebilde', ['Als Teil des Römischen Reiches', 'Als erstes Königreich Polens', 'Als Kolonie der Franken']],
              ['Wen besiegte Samo 631?', 'Ein Heer des Frankenkönigs Dagobert', ['Die Römer unter Mark Aurel', 'Die Magyaren', 'Die Wikinger']],
              ['Wann bestand das Großmährische Reich etwa?', 'Um 830–906', ['Um 623–631', 'Um 1212–1306', 'Um 400–100 v. Chr.']],
              ['Welcher Fürst bat um Missionare aus Byzanz?', 'Rastislav', ['Svatopluk', 'Samo', 'Bořivoj']],
              ['Warum wollte Rastislav Missionare aus Byzanz?', 'Sie sollten in der Sprache des Volkes predigen', ['Sie sollten Latein lehren', 'Sie sollten Krieg führen', 'Sie sollten Gold bringen']],
              ['In welche Sprache übersetzten Kyrill und Method die Gottesdienstbücher?', 'Ins Altkirchenslawische', ['Ins Lateinische', 'Ins Griechische', 'Ins Deutsche']],
              ['Unter welchem Fürsten erreichte Großmähren seine größte Ausdehnung?', 'Unter Svatopluk', ['Unter Rastislav', 'Unter Samo', 'Unter Marbod']],
              ['Wann starb Method?', '885', ['863', '906', '623']],
              ['Wer vertrieb nach Methods Tod seine Schüler?', 'Fränkische Priester', ['Die Magyaren', 'Der Papst persönlich', 'Byzantinische Soldaten']],
              ['Wohin zogen Methods Schüler?', 'Nach Bulgarien', ['Nach Rom', 'Nach Russland', 'Nach Polen']],
              ['Wer waren die Magyaren?', 'Die Vorfahren der Ungarn', ['Die Vorfahren der Tschechen', 'Ein keltischer Stamm', 'Ein germanisches Volk']],
              ['Woher kamen die Awaren?', 'Aus dem Osten', ['Aus dem Westen', 'Aus dem Süden Italiens', 'Aus Skandinavien']],
              ['Was waren die Awaren?', 'Ein Reitervolk', ['Ein Seefahrervolk', 'Ein keltischer Stamm', 'Ein römisches Heer']],
            ],
            schwer: [
              ['Wann vereinte Samo die Slawen?', 'Um 623', ['Um 863', 'Um 906', 'Um 400']],
              ['Wann besiegte Samo die Franken?', '631', ['623', '863', '885']],
              ['Wann kamen Kyrill und Method nach Großmähren?', '863', ['885', '906', '623']],
              ['Aus welchem Reich kamen Kyrill und Method?', 'Aus dem Byzantinischen Reich', ['Aus dem Frankenreich', 'Aus dem Römischen Reich der Antike', 'Aus Ungarn']],
              ['In welchem Landesteil wurde die Venus von Dolní Věstonice gefunden?', 'In Südmähren', ['In Nordböhmen', 'In Prag', 'In Schlesien']],
              ['Welcher Name entstand aus „Boiohaemum“?', 'Böhmen', ['Bayern', 'Mähren', 'Bosnien']],
              ['Wer waren die Gegner Samos im Westen?', 'Die Franken', ['Die Awaren', 'Die Magyaren', 'Die Römer']],
              ['Welche Sprache hatten Kyrill und Methods Bücher?', 'Altkirchenslawisch', ['Latein', 'Griechisch', 'Gotisch']],
              ['Was folgte auf das Ende Großmährens?', 'Der Aufstieg Böhmens unter den Přemysliden', ['Die Herrschaft der Römer', 'Die Gründung Polens in Prag', 'Die Ankunft der Kelten']],
              ['Welche Schrift ist älter: die glagolitische oder die kyrillische?', 'Die glagolitische', ['Die kyrillische', 'Beide entstanden am selben Tag', 'Keine von beiden existierte']],
              ['Wer herrschte über die Markomannen um die Zeitenwende?', 'Marbod', ['Samo', 'Rastislav', 'Mark Aurel']],
              ['Was bauten die Kelten in Böhmen?', 'Große befestigte Siedlungen', ['Pyramiden', 'Kathedralen', 'Wasserleitungen nach Rom']],
              ['Wie nennt man die frühen Jäger Mährens nach ihrer Beute?', 'Mammutjäger', ['Bärenjäger', 'Walfänger', 'Löwenjäger']],
              ['Was erreichte Großmähren unter Svatopluk?', 'Seine größte Ausdehnung', ['Seinen Untergang', 'Die Taufe durch den Papst', 'Die Erfindung der Schrift']],
              ['Wann zerstörten die Magyaren Großmähren?', 'Um 906', ['Um 863', 'Um 631', 'Um 1306']],
              ['Für wen gilt Samos Reich als erster Staat?', 'Für die Slawen', ['Für die Germanen', 'Für die Kelten', 'Für die Ungarn']],
              ['Was wollte Rastislav mit Predigten in Volkssprache erreichen?', 'Dass das Volk den Gottesdienst versteht', ['Dass Latein verboten wird', 'Dass Byzanz ihn erobert', 'Dass er Kaiser wird']],
              ['Wer schrieb die erste Schrift für eine slawische Sprache?', 'Kyrill und Method', ['Samo', 'Svatopluk', 'Fränkische Priester']],
              ['Welcher Landesname geht auf ein keltisches Volk zurück?', 'Böhmen', ['Mähren', 'Schlesien', 'Polen']],
              ['Welches Volk lebte vor den Slawen in Böhmen?', 'Germanen wie die Markomannen', ['Die Ungarn', 'Die Türken', 'Die Wikinger']],
            ],
          },
        },
        {
          id: 'premysliden-reich',
          title: 'Libuše, der heilige Wenzel und die Přemysliden',
          date: '870–1306',
          text: [
            'Nach der Sage herrschte die weise Fürstin Libuše auf dem Vyšehrad über die Tschechen. Als das Volk einen Herrscher verlangte, wählte sie den Bauern Přemysl, der gerade sein Feld pflügte, zum Mann – er wurde Stammvater der Přemysliden. Libuše soll die Gründung Prags vorhergesagt haben, einer Stadt, „deren Ruhm bis zu den Sternen reicht“. Der erste geschichtlich belegte Fürst war Bořivoj, der um 880 von Method getauft wurde und die Prager Burg gründete.',
            'Sein Enkel, Herzog Wenzel (Václav), wurde 935 von seinem Bruder Boleslav ermordet. Er wurde als Heiliger verehrt und ist Schutzpatron Böhmens; sein Todestag, der 28. September, ist heute Staatsfeiertag, und auf dem Prager Wenzelsplatz steht seine Reiterstatue. 973 wurde Prag Bistum. Böhmen gehörte zum Heiligen Römischen Reich. 1085 erhielt Herzog Vratislav II. als Erster die Königswürde, allerdings nur für sich persönlich.',
            '1198 wurde Ottokar I. erblicher König, und 1212 bestätigte Kaiser Friedrich II. dies mit der „Goldenen Bulle von Sizilien“. Später gehörte der König von Böhmen zu den sieben Kurfürsten, die den deutschen König wählten. Ab dem 12. und 13. Jahrhundert holten die Herrscher deutsche Siedler ins Land, die Wälder rodeten, Städte gründeten und Bergbau betrieben. Tschechen und Deutsche lebten danach über Jahrhunderte zusammen.',
            'Ende des 13. Jahrhunderts machten Silberfunde bei Kuttenberg (Kutná Hora) Böhmen reich; ab 1300 ließ König Wenzel II. dort den „Prager Groschen“ prägen. Sein Vater Ottokar II. Přemysl, der „eiserne und goldene König“, herrschte zeitweise bis an die Adria über Österreich, die Steiermark, Kärnten und Krain. Er wollte selbst deutscher König werden, verlor aber 1278 die Schlacht auf dem Marchfeld gegen Rudolf von Habsburg und fiel.',
            'Wenzel II. wurde 1300 auch König von Polen, sein Sohn Wenzel III. König von Ungarn. 1306 wurde Wenzel III. mit nur 16 Jahren in Olmütz ermordet – er war der letzte männliche Přemyslide. 1310 heiratete Johann von Luxemburg seine Schwester Elisabeth (Eliška) und wurde König von Böhmen.',
          ],
          quiz: {
            leicht: [
              ['Welche sagenhafte Fürstin herrschte auf dem Vyšehrad?', 'Libuše', ['Eliška', 'Ludmila', 'Maria Theresia']],
              ['Wen wählte Libuše zum Mann?', 'Den Bauern Přemysl', ['Den König von Polen', 'Einen Ritter aus Bayern', 'Den heiligen Wenzel']],
              ['Was tat Přemysl, als man ihn holte?', 'Er pflügte sein Feld', ['Er jagte im Wald', 'Er betete in der Kirche', 'Er kämpfte gegen Ungarn']],
              ['Welche Stadt soll Libuše vorhergesagt haben?', 'Prag', ['Brünn', 'Wien', 'Krakau']],
              ['Welches Geschlecht stammt von Přemysl ab?', 'Die Přemysliden', ['Die Luxemburger', 'Die Habsburger', 'Die Piasten']],
              ['Welcher Fürst gründete die Prager Burg?', 'Bořivoj', ['Wenzel', 'Ottokar II.', 'Karl IV.']],
              ['Wer taufte Bořivoj?', 'Method', ['Der Papst', 'Kyrill', 'Adalbert']],
              ['Welcher Herzog wurde 935 von seinem Bruder ermordet?', 'Wenzel', ['Bořivoj', 'Ottokar', 'Vratislav']],
              ['Wie heißt der heilige Wenzel auf Tschechisch?', 'Václav', ['Vojtěch', 'Vladislav', 'Vratislav']],
              ['Wessen Schutzpatron ist der heilige Wenzel?', 'Böhmens', ['Polens', 'Ungarns', 'Österreichs']],
              ['Wo steht die Reiterstatue des heiligen Wenzel?', 'Auf dem Prager Wenzelsplatz', ['Auf der Karlsbrücke', 'In Brünn', 'In Wien']],
              ['Zu welchem Reich gehörte Böhmen?', 'Zum Heiligen Römischen Reich', ['Zum Byzantinischen Reich', 'Zum Osmanischen Reich', 'Zum Großmährischen Reich bis 1918']],
              ['Wer wurde 1198 erblicher König von Böhmen?', 'Ottokar I.', ['Wenzel I.', 'Karl IV.', 'Johann von Luxemburg']],
              ['Wie heißt die Urkunde von 1212?', 'Goldene Bulle von Sizilien', ['Goldene Bulle Karls IV.', 'Magna Carta', 'Majestätsbrief']],
              ['Wen holten die Herrscher ab dem 12. Jahrhundert ins Land?', 'Deutsche Siedler', ['Italienische Händler', 'Wikinger', 'Türken']],
              ['Welches Metall machte Böhmen reich?', 'Silber', ['Gold', 'Kupfer', 'Eisen']],
              ['Wo wurde Silber gefunden?', 'Bei Kuttenberg', ['Bei Prag', 'Bei Pilsen', 'Bei Karlsbad']],
              ['Welche Münze ließ Wenzel II. prägen?', 'Den Prager Groschen', ['Den Taler', 'Den Gulden', 'Die Krone']],
              ['Wie nannte man Ottokar II. Přemysl?', 'Den eisernen und goldenen König', ['Den Löwen aus Mitternacht', 'Den Winterkönig', 'Den Vater des Vaterlandes']],
              ['Gegen wen verlor Ottokar II. 1278?', 'Gegen Rudolf von Habsburg', ['Gegen Karl IV.', 'Gegen den Papst', 'Gegen die Mongolen']],
            ],
            mittel: [
              ['Wo herrschte Libuše der Sage nach?', 'Auf dem Vyšehrad', ['Auf dem Hradschin', 'In Brünn', 'In Kuttenberg']],
              ['Was sagte Libuše über Prags Ruhm voraus?', 'Er werde bis zu den Sternen reichen', ['Er werde nie vergehen', 'Er werde bis Rom reichen', 'Er werde im Feuer enden']],
              ['Um wann wurde Bořivoj getauft?', 'Um 880', ['Um 935', 'Um 1085', 'Um 623']],
              ['Wer war der erste geschichtlich belegte Fürst Böhmens?', 'Bořivoj', ['Přemysl', 'Libuše', 'Samo']],
              ['Wer ermordete den heiligen Wenzel?', 'Sein Bruder Boleslav', ['Sein Sohn', 'Ein ungarischer Krieger', 'Der Kaiser']],
              ['Wessen Enkel war Wenzel?', 'Bořivojs', ['Přemysls', 'Ottokars', 'Libušes']],
              ['Welcher Tag ist heute tschechischer Staatsfeiertag zu Ehren Wenzels?', 'Der 28. September', ['Der 28. Oktober', 'Der 17. November', 'Der 6. Juli']],
              ['Wann wurde Prag Bistum?', '973', ['935', '1085', '1212']],
              ['Wer erhielt 1085 als Erster die Königswürde?', 'Vratislav II.', ['Ottokar I.', 'Wenzel I.', 'Bořivoj']],
              ['Was war an Vratislavs Königswürde besonders?', 'Sie galt nur für ihn persönlich', ['Sie galt für immer', 'Er erhielt sie vom Papst', 'Er lehnte sie ab']],
              ['Welcher Kaiser stellte die Goldene Bulle von Sizilien aus?', 'Friedrich II.', ['Karl IV.', 'Barbarossa', 'Otto der Große']],
              ['Was bestätigte die Goldene Bulle von Sizilien?', 'Das erbliche Königtum Böhmens', ['Die Unabhängigkeit Böhmens vom Reich', 'Die Gründung der Universität', 'Die Wahl des Papstes']],
              ['Zu welcher Gruppe gehörte der König von Böhmen später?', 'Zu den sieben Kurfürsten', ['Zu den zwölf Aposteln', 'Zu den Hanseaten', 'Zu den Templern']],
              ['Was taten die deutschen Siedler?', 'Sie rodeten Wälder, gründeten Städte und betrieben Bergbau', ['Sie führten Krieg gegen Prag', 'Sie bauten Pyramiden', 'Sie verließen das Land gleich wieder']],
              ['Wie heißt Kuttenberg auf Tschechisch?', 'Kutná Hora', ['Karlovy Vary', 'České Budějovice', 'Olomouc']],
              ['Ab wann wurde der Prager Groschen geprägt?', 'Ab 1300', ['Ab 1212', 'Ab 1348', 'Ab 973']],
              ['Bis wohin herrschte Ottokar II. zeitweise?', 'Bis an die Adria', ['Bis an die Ostsee', 'Bis nach Rom', 'Bis nach Kiew']],
              ['Was wollte Ottokar II. werden?', 'Deutscher König', ['Papst', 'König von Frankreich', 'Kaiser von Byzanz']],
              ['Wo verlor Ottokar II. 1278?', 'Auf dem Marchfeld', ['Am Weißen Berg', 'Bei Lützen', 'Bei Mohács']],
              ['Wann wurde Wenzel III. ermordet?', '1306', ['1278', '1310', '1212']],
            ],
            schwer: [
              ['Wo wurde Wenzel III. ermordet?', 'In Olmütz', ['In Prag', 'In Brünn', 'In Krakau']],
              ['Wie alt war Wenzel III. bei seinem Tod?', '16 Jahre', ['6 Jahre', '36 Jahre', '60 Jahre']],
              ['Welches Land regierte Wenzel II. ab 1300 außerdem?', 'Polen', ['Ungarn', 'Österreich', 'Bayern']],
              ['Welches Land regierte Wenzel III. außerdem?', 'Ungarn', ['Polen', 'Österreich', 'Sachsen']],
              ['Wer heiratete 1310 die Schwester Wenzels III.?', 'Johann von Luxemburg', ['Rudolf von Habsburg', 'Karl IV.', 'Ludwig der Bayer']],
              ['Wie hieß die Schwester Wenzels III.?', 'Elisabeth (Eliška)', ['Libuše', 'Ludmila', 'Anna']],
              ['Welche Länder beherrschte Ottokar II. außer Böhmen?', 'Österreich, Steiermark, Kärnten und Krain', ['Polen und Litauen', 'Bayern und Sachsen', 'Ungarn und Kroatien']],
              ['Wann fiel Ottokar II.?', '1278', ['1306', '1212', '1198']],
              ['Wann wurde Ottokar I. erblicher König?', '1198', ['1212', '1085', '1278']],
              ['Wann wurde der heilige Wenzel ermordet?', '935', ['880', '973', '1085']],
              ['Wer war der letzte männliche Přemyslide?', 'Wenzel III.', ['Ottokar II.', 'Wenzel II.', 'Karl IV.']],
              ['Wessen Sohn war Wenzel II.?', 'Ottokars II.', ['Ottokars I.', 'Johanns von Luxemburg', 'Rudolfs von Habsburg']],
              ['Wofür nutzten die Könige das Silber aus Kuttenberg?', 'Für den Prager Groschen', ['Für die Karlsbrücke', 'Für Kreuzzüge', 'Für den Kölner Dom']],
              ['Welches Volk lebte nach der Ansiedlung jahrhundertelang mit den Tschechen zusammen?', 'Die Deutschen', ['Die Spanier', 'Die Schweden', 'Die Franzosen']],
              ['Was wählten die sieben Kurfürsten?', 'Den deutschen König', ['Den Papst', 'Den König von Böhmen', 'Den Bischof von Prag']],
              ['Wann wurde die Goldene Bulle von Sizilien ausgestellt?', '1212', ['1198', '1356', '1085']],
              ['Wann erhielt Böhmen zum ersten Mal einen König?', '1085', ['935', '1198', '973']],
              ['Wer war Přemysl vor seiner Wahl?', 'Ein Bauer', ['Ein Ritter', 'Ein Mönch', 'Ein Kaufmann']],
              ['Was steht auf dem Wenzelsplatz?', 'Eine Reiterstatue des heiligen Wenzel', ['Die Prager Burg', 'Das Rathaus mit der Uhr', 'Der Veitsdom']],
              ['Wann wurde Johann von Luxemburg König von Böhmen?', '1310', ['1306', '1346', '1278']],
            ],
          },
        },
      ],
    },
  ],
};
