import type { Epoch } from '../types';

export const E2: Epoch = {
  id: 'boehmen',
  name: 'Königreich Böhmen',
  period: '1310–1918',
  events: [
    {
      id: 'karl-iv',
      title: 'Karl IV. und das goldene Prag',
      date: '1310–1419',
      text: [
        'Unter Kaiser Karl IV. aus dem Haus Luxemburg wurde Prag im 14. Jahrhundert Hauptstadt des Heiligen Römischen Reiches und eine der größten Städte Europas, mit der ersten Universität Mitteleuropas, der Karlsbrücke und dem Veitsdom.',
      ],
      subtopics: [
        {
          id: 'luxemburger',
          title: 'Die Luxemburger und Kaiser Karl IV.',
          date: '1310–1419',
          text: [
            'Johann von Luxemburg, König von Böhmen ab 1310, war ein abenteuerlustiger Ritter, der sich oft im Ausland aufhielt. Obwohl er erblindet war, ließ er sich 1346 im Hundertjährigen Krieg in die Schlacht von Crécy führen, wo er auf französischer Seite fiel.',
            'Sein Sohn Karl IV. (1316–1378) war als Wenzel getauft worden, wuchs aber am französischen Königshof in Paris auf und nahm dort den Namen Karl an. Er sprach fünf Sprachen. 1346 wurde er König von Böhmen und römisch-deutscher König, 1355 krönte man ihn in Rom zum Kaiser. Prag wurde damit Hauptstadt des Heiligen Römischen Reiches.',
            '1344 wurde Prag Erzbistum, und der Bau des gotischen Veitsdoms begann, den später Peter Parler fortführte. 1348 gründete Karl die Prager Universität, die heutige Karls-Universität, die erste Universität in Mitteleuropa, und im selben Jahr die Prager Neustadt mit einem großen Pferdemarkt, dem heutigen Wenzelsplatz. 1357 wurde der Grundstein der Karlsbrücke über die Moldau gelegt, der Legende nach am 9. 7. 1357 um 5:31 Uhr – die Zahlenfolge 1-3-5-7-9-7-5-3-1 liest sich vorwärts und rückwärts gleich. Auf der Burg Karlštejn ließ Karl die Reichskleinodien aufbewahren, die Krone und die übrigen Zeichen der Kaiserwürde.',
            '1356 erließ Karl die „Goldene Bulle“, das wichtigste Grundgesetz des Reiches. Sie regelte, dass sieben Kurfürsten den König mit Mehrheit wählen, die Wahl in Frankfurt und die Krönung in Aachen stattfinden. Der König von Böhmen war der vornehmste weltliche Kurfürst. Die Goldene Bulle galt bis 1806.',
            'Prag wurde mit rund 40.000 Einwohnern eine der größten Städte Europas, und Karl wurde „Vater des Vaterlandes“ genannt. Der Kurort Karlsbad (Karlovy Vary) trägt seinen Namen. Sein Sohn Wenzel IV. war ein schwacher Herrscher. 1393 ließ er den Generalvikar Johannes Nepomuk von der Karlsbrücke in die Moldau werfen; Nepomuk wurde später als Heiliger der Brücken verehrt. 1400 setzten die Kurfürsten Wenzel als deutschen König ab.',
          ],
          quiz: {
            leicht: [
              ['Aus welchem Haus stammte Karl IV.?', 'Aus dem Haus Luxemburg', ['Aus dem Haus Habsburg', 'Aus dem Haus der Přemysliden', 'Aus dem Haus Wittelsbach']],
              ['Welche Stadt machte Karl IV. zur Hauptstadt des Reiches?', 'Prag', ['Wien', 'Aachen', 'Frankfurt']],
              ['Wann wurde Karl IV. zum Kaiser gekrönt?', '1355', ['1346', '1378', '1310']],
              ['Wo wurde Karl IV. zum Kaiser gekrönt?', 'In Rom', ['In Prag', 'In Aachen', 'In Paris']],
              ['Welche Universität gründete Karl IV. 1348?', 'Die Prager Universität', ['Die Universität Wien', 'Die Universität Heidelberg', 'Die Sorbonne']],
              ['Wie heißt die Prager Universität heute?', 'Karls-Universität', ['Wenzels-Universität', 'Hus-Universität', 'Moldau-Universität']],
              ['Welche Brücke ließ Karl IV. über die Moldau bauen?', 'Die Karlsbrücke', ['Die Rialtobrücke', 'Die Tower Bridge', 'Die Wenzelsbrücke']],
              ['Über welchen Fluss führt die Karlsbrücke?', 'Über die Moldau', ['Über die Elbe', 'Über die Donau', 'Über den Rhein']],
              ['Welcher gotische Dom wurde ab 1344 in Prag gebaut?', 'Der Veitsdom', ['Der Stephansdom', 'Der Kölner Dom', 'Die Teynkirche']],
              ['Welches Grundgesetz erließ Karl IV. 1356?', 'Die Goldene Bulle', ['Die Magna Carta', 'Den Majestätsbrief', 'Die Goldene Bulle von Sizilien']],
              ['Wie viele Kurfürsten wählten nach der Goldenen Bulle den König?', 'Sieben', ['Drei', 'Zwölf', 'Fünf']],
              ['Wo sollte der König nach der Goldenen Bulle gewählt werden?', 'In Frankfurt', ['In Prag', 'In Rom', 'In Wien']],
              ['Wo sollte der König gekrönt werden?', 'In Aachen', ['In Frankfurt', 'In Prag', 'In Köln']],
              ['Welcher Kurort ist nach Karl IV. benannt?', 'Karlsbad', ['Marienbad', 'Baden-Baden', 'Franzensbad']],
              ['Wie wurde Karl IV. genannt?', 'Vater des Vaterlandes', ['Löwe aus Mitternacht', 'Eiserner Kanzler', 'Winterkönig']],
              ['Wo wuchs Karl IV. auf?', 'Am französischen Königshof in Paris', ['In Rom', 'In Luxemburg', 'In Wien']],
              ['Wie viele Sprachen sprach Karl IV.?', 'Fünf', ['Eine', 'Zwei', 'Zehn']],
              ['Auf welcher Burg ließ Karl die Reichskleinodien aufbewahren?', 'Auf Karlštejn', ['Auf dem Vyšehrad', 'Auf Wartburg', 'Auf Neuschwanstein']],
              ['Wer wurde von der Karlsbrücke in die Moldau geworfen?', 'Johannes Nepomuk', ['Jan Hus', 'Karl IV.', 'Wenzel IV.']],
              ['Als was wird Johannes Nepomuk verehrt?', 'Als Heiliger der Brücken', ['Als Heiliger der Bergleute', 'Als Schutzpatron der Ärzte', 'Als König von Böhmen']],
            ],
            mittel: [
              ['Ab wann war Johann von Luxemburg König von Böhmen?', 'Ab 1310', ['Ab 1346', 'Ab 1278', 'Ab 1355']],
              ['Was war an Johann von Luxemburg in der Schlacht von Crécy besonders?', 'Er war blind', ['Er war ein Kind', 'Er kämpfte für England', 'Er überlebte als Einziger']],
              ['In welchem Krieg fiel Johann von Luxemburg?', 'Im Hundertjährigen Krieg', ['Im Dreißigjährigen Krieg', 'In den Hussitenkriegen', 'Im Ersten Kreuzzug']],
              ['Auf welcher Seite kämpfte Johann bei Crécy?', 'Auf französischer Seite', ['Auf englischer Seite', 'Auf deutscher Seite', 'Auf ungarischer Seite']],
              ['Wann fiel Johann von Luxemburg?', '1346', ['1310', '1355', '1378']],
              ['Auf welchen Namen war Karl IV. getauft worden?', 'Wenzel', ['Johann', 'Rudolf', 'Ottokar']],
              ['Wann wurde Karl IV. König von Böhmen?', '1346', ['1316', '1355', '1310']],
              ['Wann lebte Karl IV.?', '1316–1378', ['1278–1306', '1370–1415', '1576–1612']],
              ['Wann wurde Prag Erzbistum?', '1344', ['973', '1348', '1356']],
              ['Welcher Baumeister führte den Veitsdom fort?', 'Peter Parler', ['Matthias Grünewald', 'Balthasar Neumann', 'Albrecht Dürer']],
              ['Was gründete Karl IV. 1348 außer der Universität?', 'Die Prager Neustadt', ['Die Prager Burg', 'Die Karlsbrücke', 'Den Vyšehrad']],
              ['Was war der heutige Wenzelsplatz ursprünglich?', 'Ein großer Pferdemarkt', ['Ein Friedhof', 'Ein See', 'Ein Weinberg']],
              ['Wann wurde der Grundstein der Karlsbrücke gelegt?', '1357', ['1348', '1344', '1393']],
              ['Was ist besonders an der Uhrzeit der Grundsteinlegung?', 'Die Zahlenfolge liest sich vorwärts und rückwärts gleich', ['Es war genau Mitternacht', 'Es war bei Sonnenfinsternis', 'Es war am Geburtstag Karls']],
              ['Wie wählten die Kurfürsten den König nach der Goldenen Bulle?', 'Mit Mehrheit', ['Einstimmig', 'Durch Los', 'Durch den Papst']],
              ['Welcher Kurfürst war der vornehmste weltliche?', 'Der König von Böhmen', ['Der Erzbischof von Mainz', 'Der Pfalzgraf bei Rhein', 'Der Herzog von Sachsen']],
              ['Bis wann galt die Goldene Bulle?', 'Bis 1806', ['Bis 1648', 'Bis 1918', 'Bis 1415']],
              ['Wie viele Einwohner hatte Prag unter Karl IV. etwa?', 'Rund 40.000', ['Rund 4.000', 'Rund 400.000', 'Rund eine Million']],
              ['Wann ließ Wenzel IV. Johannes Nepomuk in die Moldau werfen?', '1393', ['1357', '1415', '1419']],
              ['Was geschah 1400 mit Wenzel IV.?', 'Die Kurfürsten setzten ihn als deutschen König ab', ['Er wurde Kaiser', 'Er starb in einer Schlacht', 'Er gründete eine Universität']],
            ],
            schwer: [
              ['Welches Amt hatte Johannes Nepomuk?', 'Generalvikar', ['Erzbischof', 'Bürgermeister', 'Kanzler']],
              ['Was für ein Herrscher war Wenzel IV.?', 'Ein schwacher Herrscher', ['Ein großer Eroberer', 'Ein Gelehrter wie sein Vater', 'Ein Kreuzfahrer']],
              ['Was war Prags Universität 1348?', 'Die erste Universität Mitteleuropas', ['Die älteste Universität der Welt', 'Eine reine Kunstschule', 'Eine Schule für Ritter']],
              ['Wie lautet die Zahlenfolge der Grundsteinlegung der Karlsbrücke?', '1-3-5-7-9-7-5-3-1', ['1-2-3-4-5-4-3-2-1', '1-3-4-8-1-3-4-8', '9-7-5-3-1-3-5-7-9']],
              ['Wann erließ Karl IV. die Goldene Bulle?', '1356', ['1348', '1357', '1346']],
              ['Was waren die Reichskleinodien?', 'Die Krone und die Zeichen der Kaiserwürde', ['Die Bücher der Universität', 'Die Steine der Karlsbrücke', 'Die Glocken des Veitsdoms']],
              ['Wann wurde Karl IV. römisch-deutscher König?', '1346', ['1355', '1316', '1378']],
              ['Wer war Karl IV. in Bezug auf Johann von Luxemburg?', 'Sein Sohn', ['Sein Bruder', 'Sein Enkel', 'Sein Vater']],
              ['Wer war Wenzel IV. in Bezug auf Karl IV.?', 'Sein Sohn', ['Sein Bruder', 'Sein Vater', 'Sein Neffe']],
              ['Welchen Status erhielt Prag 1344?', 'Erzbistum', ['Reichsstadt', 'Universitätsstadt', 'Hansestadt']],
              ['Wo fand die Schlacht von Crécy statt?', 'In Frankreich', ['In Böhmen', 'In England', 'In Italien']],
              ['Wofür stand die Goldene Bulle?', 'Für Regeln der Königswahl', ['Für die Gründung der Universität', 'Für den Bau der Karlsbrücke', 'Für die Krönung in Rom']],
              ['Welcher Baustil prägt den Veitsdom?', 'Die Gotik', ['Der Barock', 'Die Romanik', 'Der Jugendstil']],
              ['In welcher Stadt wurde Karl IV. erzogen?', 'In Paris', ['In Prag', 'In Rom', 'In Luxemburg']],
              ['Welche zwei Städte waren nach der Goldenen Bulle für Wahl und Krönung bestimmt?', 'Frankfurt und Aachen', ['Prag und Rom', 'Wien und Mainz', 'Köln und Trier']],
              ['Wie wurde Prag unter Karl IV. eingestuft?', 'Als eine der größten Städte Europas', ['Als Dorf', 'Als Kleinstadt', 'Als Hafenstadt']],
              ['Was wurde nach Karls Tod aus dem Reich unter Wenzel IV.?', 'Wenzel wurde 1400 als König abgesetzt', ['Es wurde größer', 'Es wurde Republik', 'Es zerfiel 1378']],
              ['Woran erinnert die Schlacht von Crécy in Böhmen?', 'An den Tod des blinden Königs Johann', ['An den Sieg Karls IV.', 'An die Gründung Prags', 'An die Hussiten']],
              ['Wer begann den Veitsdom-Bau neu zu leiten, nachdem er schon begonnen war?', 'Peter Parler', ['Karl IV. selbst', 'Johannes Nepomuk', 'Jan Hus']],
              ['Welcher Platz in Prag geht auf Karls Neustadt zurück?', 'Der Wenzelsplatz', ['Der Altstädter Ring', 'Der Hradschin', 'Die Kleinseite']],
            ],
          },
        },
      ],
    },
    {
      id: 'hus',
      title: 'Jan Hus und die Hussiten',
      date: '1402–1648',
      text: [
        'Der Prediger Jan Hus kritisierte die Kirche und wurde 1415 verbrannt. Seine Anhänger, die Hussiten, wehrten sich in den Hussitenkriegen erfolgreich gegen mehrere Kreuzzüge. Später regierten die Habsburger Böhmen; der Prager Fenstersturz von 1618 löste den Dreißigjährigen Krieg aus, und nach der Niederlage am Weißen Berg wurde das Land wieder katholisch.',
      ],
      subtopics: [
        {
          id: 'hus-hussiten',
          title: 'Jan Hus und die Hussitenkriege',
          date: '1402–1471',
          text: [
            'Die Kirche war reich, viele Geistliche lebten im Luxus, und Ämter wurden gekauft. Der Priester Jan Hus (um 1370–1415), Rektor der Prager Universität, predigte ab 1402 in der Bethlehemskapelle auf Tschechisch gegen diese Missstände; er war beeinflusst vom englischen Theologen John Wyclif. 1409 gab König Wenzel IV. im Kuttenberger Dekret den Tschechen die Mehrheit an der Universität, worauf viele deutsche Lehrer und Studenten Prag verließen und in Leipzig eine neue Universität gründeten.',
            'Hus wurde mit dem Kirchenbann belegt und zum Konzil von Konstanz geladen. König Sigismund hatte ihm freies Geleit versprochen, doch Hus wurde verhaftet. Weil er sich weigerte, seine Lehren zu widerrufen, wurde er am 6. Juli 1415 als Ketzer verbrannt. Der 6. Juli ist heute tschechischer Staatsfeiertag. Sein Leitsatz „Die Wahrheit siegt“ wurde später das Motto der tschechischen Präsidenten.',
            'Am 30. Juli 1419 warfen aufgebrachte Hussiten unter dem Prediger Jan Želivský Ratsherren aus dem Fenster des Neustädter Rathauses – der Erste Prager Fenstersturz. Damit begannen die Hussitenkriege (1419–1434). Ihr Zeichen war der Kelch, denn die Hussiten forderten, dass beim Abendmahl alle Gläubigen nicht nur Brot, sondern auch Wein erhalten. Radikale Hussiten gründeten die Stadt Tábor.',
            'Ihr Feldherr Jan Žižka, der ein Auge verloren hatte und später ganz erblindete, verlor keine einzige Schlacht. Er setzte Wagenburgen aus Kampfwagen und frühe Feuerwaffen ein; das tschechische Wort „píšťala“ (Pfeife) für eine Handfeuerwaffe lebt im Wort „Pistole“ weiter. Fünf Kreuzzüge gegen die Hussiten scheiterten; schon ihr Kampflied „Ihr, die ihr Gottes Streiter seid“ soll Feinde in die Flucht geschlagen haben. Žižka starb 1424 an der Pest.',
            'Die Hussiten zerstritten sich: 1434 besiegten die gemäßigten Utraquisten die radikalen Taboriten bei Lipany. 1436 erlaubten die Basler Kompaktaten den Böhmen den Laienkelch. 1458 wählten die Stände Georg von Podiebrad zum König, den „Hussitenkönig“. Er schlug 1464 einen Friedensbund christlicher Fürsten vor – ein früher Vorläufer der europäischen Einigung.',
          ],
          quiz: {
            leicht: [
              ['Welcher Prediger kritisierte im frühen 15. Jahrhundert die Kirche in Prag?', 'Jan Hus', ['Martin Luther', 'Jan Žižka', 'Johannes Nepomuk']],
              ['In welcher Sprache predigte Jan Hus?', 'Auf Tschechisch', ['Auf Latein', 'Auf Deutsch', 'Auf Griechisch']],
              ['In welcher Kapelle predigte Hus?', 'In der Bethlehemskapelle', ['In der Sixtinischen Kapelle', 'Im Veitsdom', 'In der Teynkirche']],
              ['Zu welchem Konzil wurde Hus geladen?', 'Zum Konzil von Konstanz', ['Zum Konzil von Trient', 'Zum Konzil von Basel', 'Zum Konzil von Nicäa']],
              ['Was geschah mit Jan Hus 1415?', 'Er wurde als Ketzer verbrannt', ['Er wurde Papst', 'Er floh nach England', 'Er wurde König']],
              ['Welcher Tag ist zu Ehren von Hus Staatsfeiertag?', 'Der 6. Juli', ['Der 28. Oktober', 'Der 28. September', 'Der 17. November']],
              ['Wie lautet der Leitsatz von Hus?', '„Die Wahrheit siegt“', ['„Gott mit uns“', '„Freiheit oder Tod“', '„Ich dien“']],
              ['Wie nennt man die Anhänger von Jan Hus?', 'Hussiten', ['Lutheraner', 'Calvinisten', 'Templer']],
              ['Was war das Zeichen der Hussiten?', 'Der Kelch', ['Das Kreuz', 'Der Löwe', 'Die Rose']],
              ['Was forderten die Hussiten beim Abendmahl?', 'Wein für alle Gläubigen', ['Kein Brot mehr', 'Abendmahl nur für Priester', 'Abendmahl auf Latein']],
              ['Wie heißt das Ereignis von 1419 am Neustädter Rathaus?', 'Erster Prager Fenstersturz', ['Zweiter Prager Fenstersturz', 'Kuttenberger Dekret', 'Weißer Berg']],
              ['Wer war der berühmteste Feldherr der Hussiten?', 'Jan Žižka', ['Jan Hus', 'Wallenstein', 'Georg von Podiebrad']],
              ['Was war besonders an Jan Žižka?', 'Er verlor keine Schlacht, obwohl er erblindete', ['Er war ein Kind', 'Er war ein Engländer', 'Er kämpfte für den Kaiser']],
              ['Was setzte Žižka im Kampf ein?', 'Wagenburgen und frühe Feuerwaffen', ['Kriegselefanten', 'Schiffe', 'Panzer']],
              ['Welches deutsche Wort stammt vom tschechischen „píšťala“?', 'Pistole', ['Kanone', 'Gewehr', 'Säbel']],
              ['Wie viele Kreuzzüge gegen die Hussiten scheiterten?', 'Fünf', ['Einer', 'Zwei', 'Zehn']],
              ['Welche Stadt gründeten radikale Hussiten?', 'Tábor', ['Prag', 'Brünn', 'Pilsen']],
              ['Woran starb Jan Žižka?', 'An der Pest', ['In einer Schlacht', 'Auf dem Scheiterhaufen', 'An Altersschwäche']],
              ['Wer wurde 1458 zum „Hussitenkönig“ gewählt?', 'Georg von Podiebrad', ['Sigismund', 'Wenzel IV.', 'Jan Žižka']],
              ['Was schlug Georg von Podiebrad 1464 vor?', 'Einen Friedensbund christlicher Fürsten', ['Einen Kreuzzug nach Jerusalem', 'Die Abschaffung der Kirche', 'Eine Union mit Polen']],
            ],
            mittel: [
              ['Welche Missstände kritisierte Hus?', 'Den Reichtum der Kirche und den Kauf von Ämtern', ['Die Universität', 'Die tschechische Sprache', 'Den König']],
              ['Welches Amt hatte Hus an der Universität?', 'Rektor', ['Kanzler', 'Pförtner', 'Student']],
              ['Ab wann predigte Hus in der Bethlehemskapelle?', 'Ab 1402', ['Ab 1348', 'Ab 1415', 'Ab 1419']],
              ['Von welchem englischen Theologen war Hus beeinflusst?', 'John Wyclif', ['Thomas Morus', 'William Tyndale', 'Martin Luther']],
              ['Was regelte das Kuttenberger Dekret 1409?', 'Die Tschechen erhielten die Mehrheit an der Universität', ['Hus wurde verbannt', 'Der Kelch wurde verboten', 'Die Karlsbrücke wurde gebaut']],
              ['Welche Universität gründeten die Deutschen nach 1409?', 'Die Universität Leipzig', ['Die Universität Wien', 'Die Universität Heidelberg', 'Die Universität Krakau']],
              ['Welcher König versprach Hus freies Geleit?', 'Sigismund', ['Wenzel IV.', 'Karl IV.', 'Georg von Podiebrad']],
              ['Warum wurde Hus verbrannt?', 'Er weigerte sich, seine Lehren zu widerrufen', ['Er hatte den König ermordet', 'Er war geflohen', 'Er hatte die Universität angezündet']],
              ['Wer führte die Hussiten beim Ersten Fenstersturz?', 'Jan Želivský', ['Jan Žižka', 'Jan Hus', 'Prokop der Große']],
              ['Wann fand der Erste Prager Fenstersturz statt?', 'Am 30. Juli 1419', ['Am 6. Juli 1415', 'Am 23. Mai 1618', 'Am 8. November 1620']],
              ['Wie lange dauerten die Hussitenkriege?', '1419–1434', ['1415–1420', '1618–1648', '1458–1471']],
              ['Was bedeutet „píšťala“?', 'Pfeife', ['Donner', 'Schwert', 'Wagen']],
              ['Wie hieß das Kampflied der Hussiten?', '„Ihr, die ihr Gottes Streiter seid“', ['„Ein feste Burg ist unser Gott“', '„Die Moldau“', '„Kde domov můj?“']],
              ['Wann starb Jan Žižka?', '1424', ['1415', '1434', '1419']],
              ['Wer siegte 1434 bei Lipany?', 'Die gemäßigten Utraquisten', ['Die radikalen Taboriten', 'Der Kaiser', 'Die Kreuzfahrer']],
              ['Wen besiegten die Utraquisten bei Lipany?', 'Die radikalen Taboriten', ['Die Kreuzfahrer', 'Die Osmanen', 'Die Polen']],
              ['Was erlaubten die Basler Kompaktaten 1436?', 'Den Laienkelch', ['Die Verbrennung von Ketzern', 'Die Wahl eines Papstes in Prag', 'Die Rückkehr der Deutschen']],
              ['Wann wurde Georg von Podiebrad König?', '1458', ['1436', '1471', '1415']],
              ['Wer wählte Georg von Podiebrad zum König?', 'Die Stände', ['Der Papst', 'Der Kaiser', 'Die Universität']],
              ['Als was gilt Podiebrads Friedensplan heute?', 'Als früher Vorläufer der europäischen Einigung', ['Als Kriegserklärung', 'Als Fälschung', 'Als Kreuzzugsplan']],
            ],
            schwer: [
              ['Wann lebte Jan Hus?', 'Um 1370–1415', ['1316–1378', '1483–1546', '1592–1670']],
              ['Wann wurde Hus verbrannt?', 'Am 6. Juli 1415', ['Am 30. Juli 1419', 'Am 28. Oktober 1415', 'Am 6. Juli 1419']],
              ['Wann erließ Wenzel IV. das Kuttenberger Dekret?', '1409', ['1402', '1415', '1348']],
              ['Wessen Motto wurde der Leitsatz „Die Wahrheit siegt“ später?', 'Das Motto der tschechischen Präsidenten', ['Das Motto der Habsburger', 'Das Motto der Universität Leipzig', 'Das Motto des Papstes']],
              ['Aus welchem Gebäude wurden 1419 Ratsherren geworfen?', 'Aus dem Neustädter Rathaus', ['Aus der Prager Burg', 'Aus dem Altstädter Rathaus', 'Aus der Bethlehemskapelle']],
              ['Wann siegten die Utraquisten bei Lipany?', '1434', ['1419', '1436', '1424']],
              ['Wann wurden die Basler Kompaktaten beschlossen?', '1436', ['1434', '1458', '1415']],
              ['Wann schlug Podiebrad seinen Friedensbund vor?', '1464', ['1458', '1436', '1471']],
              ['Woher stammt der Name „Utraquisten“?', 'Vom Abendmahl in beiderlei Gestalt', ['Von einer Stadt', 'Von einem Anführer', 'Von einem Berg']],
              ['Wie hießen die radikalen Hussiten nach ihrer Stadt?', 'Taboriten', ['Utraquisten', 'Pikarden', 'Brüder']],
              ['Was gründeten deutsche Studenten 1409?', 'Die Universität Leipzig', ['Die Hanse', 'Die Stadt Tábor', 'Die Universität Prag']],
              ['Wofür wurde Hus der Kirchenbann auferlegt?', 'Für seine Kritik an der Kirche', ['Für den Mord an Nepomuk', 'Für den Fenstersturz', 'Für die Gründung Tábors']],
              ['Wie viele Augen hatte Žižka anfangs verloren?', 'Eines', ['Keines', 'Beide sofort', 'Er war nie verletzt']],
              ['Wer brach das Versprechen des freien Geleits für Hus?', 'Das Konzil ließ ihn verhaften, obwohl Sigismund es versprochen hatte', ['Hus selbst floh', 'Wenzel IV. lieferte ihn aus', 'Žižka verriet ihn']],
              ['Welche Waffe der Hussiten ist ein Vorläufer der Pistole?', 'Die Píšťala', ['Die Armbrust', 'Die Hellebarde', 'Der Morgenstern']],
              ['Was schützte die Hussiten in der Schlacht?', 'Wagenburgen aus Kampfwagen', ['Burgmauern aus Stein', 'Schiffe auf der Moldau', 'Gräben voller Wasser']],
              ['Wer gab den Tschechen 1409 die Mehrheit an der Universität?', 'Wenzel IV.', ['Karl IV.', 'Sigismund', 'Jan Hus']],
              ['Welche Rolle hatte Jan Želivský?', 'Er war ein radikaler Prediger', ['Er war König', 'Er war Feldherr in Lipany', 'Er war Papst']],
              ['Wie viele Kreuzzüge führte man gegen die Hussiten insgesamt erfolglos?', 'Fünf', ['Drei', 'Sieben', 'Neun']],
              ['Was war das Ziel der Kreuzzüge gegen die Hussiten?', 'Die Hussiten zu besiegen', ['Jerusalem zu erobern', 'Die Osmanen zu vertreiben', 'Polen zu erobern']],
            ],
          },
        },
        {
          id: 'habsburg-weisser-berg',
          title: 'Habsburger, Fenstersturz und Weißer Berg',
          date: '1526–1648',
          text: [
            '1526 fiel König Ludwig II. in der Schlacht bei Mohács gegen die Osmanen. Daraufhin wurde der Habsburger Ferdinand I. König von Böhmen; die Habsburger regierten das Land bis 1918. Im böhmischen Joachimsthal wurden ab 1520 Silbermünzen geprägt, die „Joachimsthaler“ oder kurz „Taler“ hießen – davon stammt das Wort „Dollar“.',
            'Kaiser Rudolf II. machte Prag 1583 zu seiner Residenz. Er sammelte Kunstwerke und Kuriositäten und holte Alchemisten und Astronomen an seinen Hof, darunter Tycho Brahe und Johannes Kepler, der in Prag seine Gesetze der Planetenbewegung entdeckte. Aus dieser Zeit stammt die Legende vom Golem, einer Lehmfigur, die Rabbi Löw zum Leben erweckt haben soll. 1609 gewährte Rudolf den Protestanten im Majestätsbrief Religionsfreiheit.',
            'Der streng katholische Ferdinand II. bedrohte diese Rechte. Am 23. Mai 1618 warfen protestantische Adlige zwei kaiserliche Statthalter und einen Sekretär aus einem Fenster der Prager Burg – den Zweiten Prager Fenstersturz. Alle drei überlebten den Sturz. Damit begann der Dreißigjährige Krieg. Die böhmischen Stände wählten den Protestanten Friedrich V. von der Pfalz zum König; weil er nur einen Winter regierte, nennt man ihn den „Winterkönig“.',
            'Am 8. November 1620 wurde das Heer der Stände in der Schlacht am Weißen Berg bei Prag in weniger als zwei Stunden geschlagen. Am 21. Juni 1621 wurden 27 Anführer des Aufstands auf dem Altstädter Ring hingerichtet; 27 Kreuze im Pflaster erinnern daran. Die „Verneuerte Landesordnung“ von 1627 erlaubte nur noch den katholischen Glauben, machte Böhmen erblich habsburgisch und Deutsch gleichberechtigt mit Tschechisch. Zehntausende Protestanten verließen das Land.',
            'Unter den Vertriebenen war Johann Amos Comenius, Bischof der Brüderunität, der als „Lehrer der Völker“ gilt und mit dem „Orbis pictus“ das erste Bilderbuch für Kinder schuf; er starb 1670 im Exil in Amsterdam. Der Böhme Albrecht von Wallenstein wurde der mächtigste Feldherr des Kaisers, bis er 1634 in Eger ermordet wurde. 1648 plünderten die Schweden die Prager Burg und brachten Kunstschätze wie die riesige Handschrift „Codex Gigas“ („Teufelsbibel“) nach Stockholm.',
          ],
          quiz: {
            leicht: [
              ['Welches Herrscherhaus regierte Böhmen ab 1526?', 'Die Habsburger', ['Die Luxemburger', 'Die Přemysliden', 'Die Hohenzollern']],
              ['Bis wann regierten die Habsburger Böhmen?', 'Bis 1918', ['Bis 1620', 'Bis 1806', 'Bis 1945']],
              ['Welches Wort stammt vom böhmischen „Taler“?', 'Dollar', ['Euro', 'Pfund', 'Rubel']],
              ['Welcher Kaiser machte Prag 1583 zu seiner Residenz?', 'Rudolf II.', ['Karl IV.', 'Ferdinand II.', 'Maria Theresia']],
              ['Welcher Astronom entdeckte in Prag die Gesetze der Planetenbewegung?', 'Johannes Kepler', ['Galileo Galilei', 'Nikolaus Kopernikus', 'Isaac Newton']],
              ['Welcher dänische Astronom arbeitete am Hof Rudolfs II.?', 'Tycho Brahe', ['Kepler', 'Galilei', 'Hubble']],
              ['Wie heißt die Lehmfigur aus der Prager Legende?', 'Golem', ['Gollum', 'Troll', 'Homunkulus']],
              ['Wer soll den Golem zum Leben erweckt haben?', 'Rabbi Löw', ['Kaiser Rudolf', 'Johannes Kepler', 'Jan Hus']],
              ['Was gewährte der Majestätsbrief 1609?', 'Religionsfreiheit für Protestanten', ['Die Unabhängigkeit Böhmens', 'Die Abschaffung des Adels', 'Den Bau der Karlsbrücke']],
              ['Was geschah am 23. Mai 1618 auf der Prager Burg?', 'Der Zweite Prager Fenstersturz', ['Der Erste Prager Fenstersturz', 'Die Krönung Karls IV.', 'Die Schlacht am Weißen Berg']],
              ['Welcher Krieg begann mit dem Zweiten Prager Fenstersturz?', 'Der Dreißigjährige Krieg', ['Der Hundertjährige Krieg', 'Der Siebenjährige Krieg', 'Die Hussitenkriege']],
              ['Überlebten die Männer den Zweiten Prager Fenstersturz?', 'Ja, alle drei', ['Nein, alle starben', 'Nur einer', 'Niemand weiß es']],
              ['Wie nennt man Friedrich V. von der Pfalz?', 'Den Winterkönig', ['Den Sonnenkönig', 'Den Hussitenkönig', 'Den Löwen aus Mitternacht']],
              ['Wo wurden die Stände 1620 geschlagen?', 'Am Weißen Berg', ['Bei Lipany', 'Auf dem Marchfeld', 'Bei Mohács']],
              ['Wie lange dauerte die Schlacht am Weißen Berg?', 'Weniger als zwei Stunden', ['Drei Tage', 'Eine Woche', 'Ein Jahr']],
              ['Woran erinnern 27 Kreuze im Pflaster des Altstädter Rings?', 'An 27 hingerichtete Anführer', ['An 27 Könige', 'An 27 Kirchen', 'An 27 Brücken']],
              ['Welcher Glaube war nach 1627 in Böhmen allein erlaubt?', 'Der katholische', ['Der hussitische', 'Der lutherische', 'Der jüdische']],
              ['Wer gilt als „Lehrer der Völker“?', 'Johann Amos Comenius', ['Jan Hus', 'Johannes Kepler', 'Wallenstein']],
              ['Welcher Böhme war der mächtigste Feldherr des Kaisers im Dreißigjährigen Krieg?', 'Wallenstein', ['Tilly', 'Gustav Adolf', 'Friedrich V.']],
              ['Welches Land plünderte 1648 die Prager Burg?', 'Schweden', ['Frankreich', 'Polen', 'Dänemark']],
            ],
            mittel: [
              ['Wo fiel König Ludwig II. 1526?', 'Bei Mohács', ['Am Weißen Berg', 'Bei Lipany', 'Bei Crécy']],
              ['Gegen wen fiel Ludwig II.?', 'Gegen die Osmanen', ['Gegen die Habsburger', 'Gegen die Schweden', 'Gegen die Hussiten']],
              ['Welcher Habsburger wurde 1526 König von Böhmen?', 'Ferdinand I.', ['Ferdinand II.', 'Rudolf II.', 'Karl V.']],
              ['Wo wurden die ersten Taler geprägt?', 'In Joachimsthal', ['In Kuttenberg', 'In Prag', 'In Wien']],
              ['Ab wann wurden in Joachimsthal Silbermünzen geprägt?', 'Ab 1520', ['Ab 1300', 'Ab 1620', 'Ab 1418']],
              ['Wen holte Rudolf II. an seinen Hof?', 'Alchemisten und Astronomen', ['Wikinger', 'Seefahrer', 'Hussiten']],
              ['Was sammelte Rudolf II.?', 'Kunstwerke und Kuriositäten', ['Schiffe', 'Waffen der Hussiten', 'Briefmarken']],
              ['Wie hieß der streng katholische Herrscher, der die Rechte der Protestanten bedrohte?', 'Ferdinand II.', ['Rudolf II.', 'Ferdinand I.', 'Maximilian II.']],
              ['Wer wurde beim Zweiten Prager Fenstersturz aus dem Fenster geworfen?', 'Zwei kaiserliche Statthalter und ein Sekretär', ['Zwei Bischöfe', 'Der König selbst', 'Drei Hussitenführer']],
              ['Wer warf die Statthalter aus dem Fenster?', 'Protestantische Adlige', ['Katholische Bauern', 'Schwedische Soldaten', 'Studenten der Universität']],
              ['Wen wählten die böhmischen Stände 1619 zum König?', 'Friedrich V. von der Pfalz', ['Ferdinand II.', 'Wallenstein', 'Gustav Adolf']],
              ['Warum heißt Friedrich V. „Winterkönig“?', 'Er regierte nur einen Winter', ['Er wurde im Winter geboren', 'Er liebte den Schnee', 'Er siegte im Winter']],
              ['Wann fand die Schlacht am Weißen Berg statt?', 'Am 8. November 1620', ['Am 23. Mai 1618', 'Am 21. Juni 1621', 'Am 6. Juli 1415']],
              ['Wann wurden 27 Anführer hingerichtet?', 'Am 21. Juni 1621', ['Am 8. November 1620', 'Am 23. Mai 1618', 'Am 1. Januar 1627']],
              ['Wo wurden die 27 Anführer hingerichtet?', 'Auf dem Altstädter Ring', ['Auf dem Wenzelsplatz', 'Auf der Karlsbrücke', 'Am Weißen Berg']],
              ['Wie hieß die Ordnung, die Böhmen 1627 katholisch machte?', 'Verneuerte Landesordnung', ['Goldene Bulle', 'Majestätsbrief', 'Kuttenberger Dekret']],
              ['Welche Sprache wurde 1627 gleichberechtigt mit Tschechisch?', 'Deutsch', ['Latein', 'Spanisch', 'Ungarisch']],
              ['Welches Kinderbuch schuf Comenius?', '„Orbis pictus“', ['„Der Golem“', '„Die Großmutter“', '„Pinocchio“']],
              ['Wo wurde Wallenstein 1634 ermordet?', 'In Eger', ['In Prag', 'In Wien', 'In Lützen']],
              ['Welche riesige Handschrift brachten die Schweden nach Stockholm?', 'Den Codex Gigas', ['Die Gutenberg-Bibel', 'Die Goldene Bulle', 'Den Majestätsbrief']],
            ],
            schwer: [
              ['Wie nennt man den Codex Gigas auch?', 'Teufelsbibel', ['Silberbibel', 'Hussitenbibel', 'Kaiserbibel']],
              ['Wo starb Comenius?', 'In Amsterdam', ['In Prag', 'In Stockholm', 'In London']],
              ['Wann starb Comenius?', '1670', ['1620', '1648', '1700']],
              ['Welcher Kirche stand Comenius als Bischof vor?', 'Der Brüderunität', ['Der katholischen Kirche', 'Der lutherischen Kirche', 'Der orthodoxen Kirche']],
              ['Wann wurde Wallenstein ermordet?', '1634', ['1620', '1648', '1618']],
              ['Wann machte Rudolf II. Prag zur Residenz?', '1583', ['1526', '1609', '1618']],
              ['Wann wurde der Majestätsbrief erlassen?', '1609', ['1583', '1618', '1627']],
              ['Wann erließ man die Verneuerte Landesordnung?', '1627', ['1620', '1648', '1609']],
              ['Was machte die Verneuerte Landesordnung aus Böhmen?', 'Ein erblich habsburgisches Land', ['Eine Republik', 'Ein Wahlkönigtum', 'Ein Teil Schwedens']],
              ['Wann fiel Ludwig II. bei Mohács?', '1526', ['1520', '1618', '1453']],
              ['Wie hieß der Golem-Schöpfer mit vollem Titel?', 'Rabbi Löw', ['Rabbi Akiba', 'Rabbi Hillel', 'Rabbi Moses']],
              ['Wie viele Anführer wurden 1621 hingerichtet?', '27', ['7', '72', '270']],
              ['Was entdeckte Kepler in Prag?', 'Die Gesetze der Planetenbewegung', ['Die Schwerkraft', 'Das Fernrohr', 'Den Blutkreislauf']],
              ['Wie verließen Zehntausende Protestanten Böhmen?', 'Sie gingen ins Exil', ['Sie wurden Mönche', 'Sie traten dem Heer bei', 'Sie zogen nach Wien']],
              ['Woher stammt das Wort „Taler“?', 'Von Joachimsthal', ['Vom Wort „Tal“ für Geld', 'Von König Taler', 'Von der Moldau']],
              ['Welcher Feldherr stammte selbst aus Böhmen?', 'Wallenstein', ['Tilly', 'Gustav Adolf', 'Pappenheim']],
              ['Wie wurde Prag 1648 beraubt?', 'Die Schweden plünderten die Burg', ['Ein Brand zerstörte alles', 'Die Osmanen eroberten die Stadt', 'Die Kunst wurde nach Wien gebracht']],
              ['Was war der „Orbis pictus“?', 'Das erste Bilderbuch für Kinder', ['Eine Landkarte', 'Ein Gesetzbuch', 'Ein Astronomiebuch']],
              ['Was war das Ergebnis des Zweiten Prager Fenstersturzes für die Geworfenen?', 'Alle drei überlebten', ['Alle drei starben', 'Sie wurden später heiliggesprochen', 'Sie flohen nach Schweden']],
              ['Welcher Habsburger regierte, als der Dreißigjährige Krieg begann?', 'Ferdinand II.', ['Rudolf II.', 'Ferdinand I.', 'Joseph II.']],
            ],
          },
        },
      ],
    },
    {
      id: 'wiedergeburt',
      title: 'Habsburger Zeit und nationale Wiedergeburt',
      date: '1648–1918',
      text: [
        'Nach dem Dreißigjährigen Krieg prägten Barock und Gegenreformation Böhmen, und Deutsch wurde die Sprache der Oberschicht. Im 19. Jahrhundert erweckten Gelehrte und Künstler die tschechische Sprache und Kultur zu neuem Leben. Böhmen wurde das Industriezentrum der Habsburgermonarchie, bis 1918 die Tschechoslowakei entstand.',
      ],
      subtopics: [
        {
          id: 'barock-aufklaerung',
          title: 'Barock, Aufklärung und Erwachen der Nation',
          date: '1648–1848',
          text: [
            'Nach 1648 setzte die katholische Kirche mit den Jesuiten die Gegenreformation durch. Prachtvolle Barockkirchen wie die Nikolauskirche auf der Prager Kleinseite entstanden, und 1729 wurde Johannes Nepomuk heiliggesprochen. Adel und Städte sprachen nun überwiegend Deutsch; Tschechisch blieb vor allem die Sprache der Bauern. Tschechische Patrioten nannten diese Zeit später „Temno“, „Dunkelheit“.',
            'Kaiserin Maria Theresia verlor 1742 fast ganz Schlesien an Preußen. Sie führte 1774 die allgemeine Schulpflicht ein. Ihr Sohn Joseph II. erließ 1781 das Toleranzpatent, das Protestanten und Juden duldete, und hob im selben Jahr die Leibeigenschaft auf. 1784 machte er Deutsch zur Amtssprache.',
            'Prag war eine Musikstadt. 1787 wurde Mozarts Oper „Don Giovanni“ im Prager Ständetheater uraufgeführt; Mozart soll gesagt haben: „Meine Prager verstehen mich.“',
            'Ende des 18. Jahrhunderts begann die „Nationale Wiedergeburt“. Josef Dobrovský erforschte die tschechische Sprache, Josef Jungmann schuf ein großes tschechisch-deutsches Wörterbuch, und František Palacký schrieb eine Geschichte Böhmens und wurde „Vater der Nation“ genannt. 1818 wurde das Nationalmuseum gegründet. 1834 erklang in einem Theaterstück zum ersten Mal das Lied „Kde domov můj?“ („Wo ist meine Heimat?“), die heutige Nationalhymne.',
            'In der Revolution von 1848 lehnte Palacký eine Einladung zur Frankfurter Nationalversammlung ab, weil er sich nicht als Deutscher fühlte: „Ich bin ein Böhme slawischen Stammes.“ Er wollte ein Österreich, in dem die slawischen Völker gleichberechtigt sind. Im Juni 1848 tagte in Prag ein Slawenkongress, doch ein Aufstand wurde von österreichischen Truppen unter Fürst Windischgrätz niedergeschlagen. Immerhin wurden 1848 die Frondienste der Bauern abgeschafft.',
          ],
          quiz: {
            leicht: [
              ['Wer setzte nach 1648 die Gegenreformation durch?', 'Die katholische Kirche mit den Jesuiten', ['Die Hussiten', 'Die Schweden', 'Die Protestanten']],
              ['Welcher Baustil prägte Böhmen nach 1648?', 'Der Barock', ['Die Gotik', 'Die Romanik', 'Der Jugendstil']],
              ['Welche berühmte Barockkirche steht auf der Prager Kleinseite?', 'Die Nikolauskirche', ['Der Veitsdom', 'Die Teynkirche', 'Die Bethlehemskapelle']],
              ['Welche Sprache sprachen Adel und Städte nach 1648 überwiegend?', 'Deutsch', ['Tschechisch', 'Latein', 'Französisch']],
              ['Wer sprach vor allem weiter Tschechisch?', 'Die Bauern', ['Der Adel', 'Die Jesuiten', 'Der Kaiser']],
              ['Wie nannten tschechische Patrioten diese Zeit?', 'Temno (Dunkelheit)', ['Goldene Zeit', 'Wiedergeburt', 'Barockfrühling']],
              ['Welche Kaiserin verlor Schlesien an Preußen?', 'Maria Theresia', ['Elisabeth', 'Katharina die Große', 'Libuše']],
              ['Was führte Maria Theresia 1774 ein?', 'Die allgemeine Schulpflicht', ['Die Pressefreiheit', 'Das Wahlrecht', 'Den Euro']],
              ['Wer erließ 1781 das Toleranzpatent?', 'Joseph II.', ['Maria Theresia', 'Rudolf II.', 'Franz Joseph']],
              ['Was hob Joseph II. 1781 auf?', 'Die Leibeigenschaft', ['Die Kirche', 'Die Universität', 'Die Monarchie']],
              ['Welche Mozart-Oper wurde 1787 in Prag uraufgeführt?', '„Don Giovanni“', ['„Die Zauberflöte“', '„Figaros Hochzeit“', '„Così fan tutte“']],
              ['Was soll Mozart über Prag gesagt haben?', '„Meine Prager verstehen mich.“', ['„Prag ist zu klein.“', '„Ich komme nie wieder.“', '„Wien ist schöner.“']],
              ['Wie heißt die Bewegung zur Erneuerung der tschechischen Sprache und Kultur?', 'Nationale Wiedergeburt', ['Gegenreformation', 'Hussitismus', 'Prager Frühling']],
              ['Wer wurde „Vater der Nation“ genannt?', 'František Palacký', ['Jan Hus', 'Karl IV.', 'Josef Jungmann']],
              ['Was schuf Josef Jungmann?', 'Ein tschechisch-deutsches Wörterbuch', ['Eine Oper', 'Eine Universität', 'Ein Gesetzbuch']],
              ['Wann wurde das Nationalmuseum gegründet?', '1818', ['1781', '1848', '1881']],
              ['Wie heißt die tschechische Nationalhymne?', '„Kde domov můj?“', ['„Die Moldau“', '„Ihr, die ihr Gottes Streiter seid“', '„Hej, Slované“']],
              ['Was bedeutet „Kde domov můj?“', 'Wo ist meine Heimat?', ['Gott schütze uns', 'Die Wahrheit siegt', 'Böhmen ist frei']],
              ['Welche Einladung lehnte Palacký 1848 ab?', 'Zur Frankfurter Nationalversammlung', ['Zur Krönung in Wien', 'Zum Konzil von Konstanz', 'Zum Slawenkongress']],
              ['Was wurde 1848 für die Bauern abgeschafft?', 'Die Frondienste', ['Die Steuern ganz', 'Die Schulpflicht', 'Die Religion']],
            ],
            mittel: [
              ['Wann wurde Johannes Nepomuk heiliggesprochen?', '1729', ['1393', '1648', '1781']],
              ['Wann verlor Maria Theresia fast ganz Schlesien?', '1742', ['1648', '1781', '1866']],
              ['An welches Land verlor Maria Theresia Schlesien?', 'An Preußen', ['An Polen', 'An Sachsen', 'An Russland']],
              ['Wen duldete das Toleranzpatent?', 'Protestanten und Juden', ['Nur Katholiken', 'Muslime und Hindus', 'Nur Adlige']],
              ['Wann machte Joseph II. Deutsch zur Amtssprache?', '1784', ['1781', '1774', '1848']],
              ['Wessen Sohn war Joseph II.?', 'Maria Theresias', ['Rudolfs II.', 'Ferdinands II.', 'Karls IV.']],
              ['In welchem Theater wurde „Don Giovanni“ uraufgeführt?', 'Im Ständetheater', ['Im Nationaltheater', 'In der Staatsoper Wien', 'In der Scala']],
              ['Wer erforschte die tschechische Sprache am Beginn der Wiedergeburt?', 'Josef Dobrovský', ['Bedřich Smetana', 'Franz Kafka', 'Jan Žižka']],
              ['Was schrieb František Palacký?', 'Eine Geschichte Böhmens', ['Die Nationalhymne', 'Ein Wörterbuch', 'Eine Oper']],
              ['Wann erklang „Kde domov můj?“ zum ersten Mal?', '1834', ['1818', '1848', '1918']],
              ['Woraus stammt die tschechische Nationalhymne?', 'Aus einem Theaterstück', ['Aus einer Messe', 'Aus einem Kinderbuch', 'Aus einem Kampflied der Hussiten']],
              ['Mit welchen Worten beschrieb sich Palacký 1848?', '„Ich bin ein Böhme slawischen Stammes.“', ['„Ich bin ein Deutscher.“', '„Ich bin ein Österreicher.“', '„Ich bin ein Hussit.“']],
              ['Was für ein Österreich wollte Palacký?', 'Eines mit gleichberechtigten slawischen Völkern', ['Eines ohne Habsburger', 'Ein Teil Deutschlands', 'Ein Teil Russlands']],
              ['Was tagte im Juni 1848 in Prag?', 'Ein Slawenkongress', ['Das Konzil', 'Der Reichstag', 'Die Frankfurter Nationalversammlung']],
              ['Wer schlug den Prager Aufstand 1848 nieder?', 'Fürst Windischgrätz', ['Fürst Metternich', 'Kaiser Joseph II.', 'Wallenstein']],
              ['Wann begann die Nationale Wiedergeburt?', 'Ende des 18. Jahrhunderts', ['Im 14. Jahrhundert', 'Nach 1918', 'Im 16. Jahrhundert']],
              ['Wie wird die Zeit nach 1648 von Patrioten bewertet?', 'Als Zeit der Dunkelheit', ['Als goldenes Zeitalter', 'Als Zeit der Freiheit', 'Als Hussitenzeit']],
              ['Was war Tschechisch nach 1648 vor allem?', 'Die Sprache der Bauern', ['Die Sprache des Hofes', 'Die Sprache der Universität', 'Die Sprache der Kirche']],
              ['Welche Rechte gab Joseph II. den Bauern 1781?', 'Er hob die Leibeigenschaft auf', ['Er gab ihnen das Wahlrecht', 'Er schenkte ihnen Land', 'Er befreite sie von Steuern']],
              ['Was ist der Prager Ort der Mozart-Uraufführung?', 'Das Ständetheater', ['Die Prager Burg', 'Das Rudolfinum', 'Die Bethlehemskapelle']],
            ],
            schwer: [
              ['Wann erließ Joseph II. das Toleranzpatent?', '1781', ['1784', '1774', '1742']],
              ['Wann wurde „Don Giovanni“ uraufgeführt?', '1787', ['1781', '1791', '1818']],
              ['Wann führte Maria Theresia die allgemeine Schulpflicht ein?', '1774', ['1742', '1781', '1848']],
              ['Was bedeutet „Temno“?', 'Dunkelheit', ['Heimat', 'Freiheit', 'Wahrheit']],
              ['Wer war Josef Dobrovský?', 'Ein Sprachforscher', ['Ein Komponist', 'Ein Feldherr', 'Ein Kaiser']],
              ['Wie viel von Schlesien verlor Maria Theresia?', 'Fast ganz Schlesien', ['Nur eine Stadt', 'Nichts', 'Nur Mähren']],
              ['In welchem Monat 1848 tagte der Slawenkongress?', 'Im Juni', ['Im März', 'Im Oktober', 'Im Dezember']],
              ['Was folgte auf den Slawenkongress?', 'Ein niedergeschlagener Aufstand', ['Die Unabhängigkeit Böhmens', 'Die Krönung eines tschechischen Königs', 'Die Gründung der Tschechoslowakei']],
              ['Wer erhielt durch das Toleranzpatent Duldung?', 'Protestanten und Juden', ['Jesuiten', 'Hussiten in Tábor', 'Türken']],
              ['Wann wurde Deutsch durch Joseph II. Amtssprache?', '1784', ['1627', '1848', '1918']],
              ['Welche Rolle spielten die Jesuiten nach 1648?', 'Sie setzten die Gegenreformation durch', ['Sie führten die Hussiten', 'Sie gründeten das Nationalmuseum', 'Sie schrieben die Hymne']],
              ['Wer schrieb ein großes tschechisch-deutsches Wörterbuch?', 'Josef Jungmann', ['Josef Dobrovský', 'František Palacký', 'Jan Hus']],
              ['Wer nannte sich einen „Böhmen slawischen Stammes“?', 'František Palacký', ['Josef Jungmann', 'Mozart', 'Windischgrätz']],
              ['Welches Ereignis machte Prag 1787 musikalisch berühmt?', 'Die Uraufführung von „Don Giovanni“', ['Die Eröffnung des Nationaltheaters', 'Die erste Aufführung der „Moldau“', 'Dvořáks Neue Welt']],
              ['Welche Institution wurde 1818 gegründet?', 'Das Nationalmuseum', ['Das Nationaltheater', 'Die Karls-Universität', 'Die Brüderunität']],
              ['Was wollte die Nationale Wiedergeburt erneuern?', 'Die tschechische Sprache und Kultur', ['Die Macht der Habsburger', 'Den katholischen Glauben', 'Die deutsche Sprache in Böhmen']],
              ['Wer war Windischgrätz?', 'Ein österreichischer Fürst und Feldherr', ['Ein tschechischer Dichter', 'Ein preußischer König', 'Ein Bischof']],
              ['Welches Gebiet ging Böhmen 1742 großteils verloren?', 'Schlesien', ['Mähren', 'Die Lausitz', 'Das Egerland']],
              ['Wann tagte die Frankfurter Nationalversammlung, zu der Palacký nicht ging?', '1848', ['1815', '1871', '1918']],
              ['Was wurde 1729 erklärt?', 'Die Heiligsprechung Nepomuks', ['Die Unabhängigkeit Böhmens', 'Das Toleranzpatent', 'Die Schulpflicht']],
            ],
          },
        },
        {
          id: 'industrie-1918',
          title: 'Industrie, Nationaltheater und der Weg zur Unabhängigkeit',
          date: '1848–1918',
          text: [
            'Böhmen und Mähren wurden das Industriezentrum der Habsburgermonarchie: Kohle, Maschinenbau, Glas und Porzellan. 1842 braute man in Pilsen das erste helle Pils, 1869 übernahm Emil Škoda in Pilsen eine Maschinenfabrik, aus der die berühmten Škoda-Werke wurden. 1894 gründete Tomáš Baťa in Zlín eine Schuhfabrik, die später zur größten der Welt wurde.',
            'Die Tschechen sammelten unter dem Motto „Das Volk sich selbst“ Spenden für ein Nationaltheater. Es wurde 1881 eröffnet, brannte kurz darauf ab und wurde durch neue Spenden bis 1883 wieder aufgebaut. 1862 entstand der Turnverein „Sokol“ („Falke“), der Sport und Nationalgefühl verband.',
            'Bedřich Smetana komponierte die Oper „Die verkaufte Braut“ und den Zyklus „Mein Vaterland“ mit dem berühmten Stück „Die Moldau“. Antonín Dvořák schrieb 1893 in den USA seine Sinfonie „Aus der Neuen Welt“. Božena Němcová schrieb den Roman „Die Großmutter“, und Alfons Mucha prägte mit seinen Plakaten den Jugendstil. In Prag lebten auch deutschsprachige Schriftsteller wie Franz Kafka und Rainer Maria Rilke.',
            'Zwischen Tschechen und Deutschen wuchs der Streit um die Sprache. 1882 wurde die Prager Universität in eine tschechische und eine deutsche geteilt. 1897 sollten Beamte nach der Badeni-Sprachverordnung beide Sprachen beherrschen; nach heftigen Unruhen wurde sie zurückgenommen. Der Professor Tomáš Garrigue Masaryk setzte sich für Wahrheit und Demokratie ein und verteidigte 1899 den Juden Leopold Hilsner gegen einen antisemitischen Ritualmordvorwurf.',
            'Im Ersten Weltkrieg kämpften viele Tschechen nur widerwillig für Österreich; Jaroslav Hašek verspottete das in seinem Roman „Der brave Soldat Schwejk“. Masaryk ging ins Exil und gründete mit Edvard Beneš und dem Slowaken Milan Rastislav Štefánik in Paris den Tschechoslowakischen Nationalrat. Tschechoslowakische Legionen kämpften auf Seiten der Alliierten, in Russland zogen sie über die Transsibirische Eisenbahn bis Wladiwostok. Am 28. Oktober 1918 wurde in Prag die unabhängige Tschechoslowakei ausgerufen.',
          ],
          quiz: {
            leicht: [
              ['Welche Gebiete wurden das Industriezentrum der Habsburgermonarchie?', 'Böhmen und Mähren', ['Tirol und Kärnten', 'Ungarn und Kroatien', 'Galizien und die Bukowina']],
              ['In welcher Stadt wurde 1842 das erste helle Pils gebraut?', 'In Pilsen', ['In Prag', 'In München', 'In Budweis']],
              ['Wie heißen die berühmten Werke aus Pilsen?', 'Škoda-Werke', ['Baťa-Werke', 'Tatra-Werke', 'Krupp-Werke']],
              ['Was stellte Tomáš Baťa her?', 'Schuhe', ['Autos', 'Bier', 'Glas']],
              ['In welcher Stadt gründete Baťa seine Fabrik?', 'In Zlín', ['In Prag', 'In Brünn', 'In Pilsen']],
              ['Unter welchem Motto sammelten Tschechen für das Nationaltheater?', '„Das Volk sich selbst“', ['„Die Wahrheit siegt“', '„Gott mit uns“', '„Ein Volk, ein Reich“']],
              ['Wann wurde das Nationaltheater eröffnet?', '1881', ['1818', '1918', '1848']],
              ['Was geschah kurz nach der Eröffnung mit dem Nationaltheater?', 'Es brannte ab', ['Es wurde verkauft', 'Es wurde verboten', 'Es stürzte ein']],
              ['Was bedeutet „Sokol“?', 'Falke', ['Adler', 'Löwe', 'Bär']],
              ['Was war Sokol?', 'Ein Turnverein', ['Eine Partei', 'Eine Zeitung', 'Eine Brauerei']],
              ['Wer komponierte „Die Moldau“?', 'Bedřich Smetana', ['Antonín Dvořák', 'Mozart', 'Leoš Janáček']],
              ['Zu welchem Zyklus gehört „Die Moldau“?', '„Mein Vaterland“', ['„Aus der Neuen Welt“', '„Die vier Jahreszeiten“', '„Slawische Tänze“']],
              ['Welche Sinfonie schrieb Dvořák in den USA?', '„Aus der Neuen Welt“', ['„Die Moldau“', '„Eroica“', '„Unvollendete“']],
              ['Welcher Künstler prägte mit Plakaten den Jugendstil?', 'Alfons Mucha', ['Gustav Klimt', 'Egon Schiele', 'Pablo Picasso']],
              ['Welcher deutschsprachige Schriftsteller lebte in Prag?', 'Franz Kafka', ['Thomas Mann', 'Goethe', 'Bertolt Brecht']],
              ['Welcher Roman verspottet den Ersten Weltkrieg?', '„Der brave Soldat Schwejk“', ['„Im Westen nichts Neues“', '„Der Prozess“', '„Die Großmutter“']],
              ['Wer schrieb „Der brave Soldat Schwejk“?', 'Jaroslav Hašek', ['Franz Kafka', 'Karel Čapek', 'Václav Havel']],
              ['Wer gründete den Tschechoslowakischen Nationalrat im Exil?', 'Tomáš Garrigue Masaryk mit Beneš und Štefánik', ['Kaiser Karl I.', 'Bedřich Smetana', 'Franz Kafka']],
              ['Wann wurde die Tschechoslowakei ausgerufen?', 'Am 28. Oktober 1918', ['Am 6. Juli 1918', 'Am 17. November 1918', 'Am 1. Januar 1918']],
              ['In welcher Stadt wurde die Tschechoslowakei ausgerufen?', 'In Prag', ['In Paris', 'In Wien', 'In Bratislava']],
            ],
            mittel: [
              ['Was übernahm Emil Škoda 1869?', 'Eine Maschinenfabrik in Pilsen', ['Eine Brauerei', 'Eine Schuhfabrik', 'Eine Glashütte']],
              ['Wann gründete Baťa seine Schuhfabrik?', '1894', ['1842', '1869', '1918']],
              ['Was wurde Baťas Fabrik später?', 'Die größte Schuhfabrik der Welt', ['Eine Autofabrik', 'Eine Brauerei', 'Ein Museum']],
              ['Bis wann wurde das Nationaltheater wieder aufgebaut?', 'Bis 1883', ['Bis 1881', 'Bis 1900', 'Bis 1918']],
              ['Wie wurde das Nationaltheater wieder aufgebaut?', 'Durch neue Spenden', ['Durch den Kaiser', 'Durch eine Steuer', 'Durch die Kirche']],
              ['Wann entstand der Sokol?', '1862', ['1848', '1881', '1918']],
              ['Was verband der Sokol?', 'Sport und Nationalgefühl', ['Musik und Religion', 'Handel und Politik', 'Bier und Brauchtum']],
              ['Welche Oper komponierte Smetana?', '„Die verkaufte Braut“', ['„Rusalka“', '„Don Giovanni“', '„Jenůfa“']],
              ['Wann schrieb Dvořák „Aus der Neuen Welt“?', '1893', ['1874', '1918', '1848']],
              ['Wer schrieb den Roman „Die Großmutter“?', 'Božena Němcová', ['Franz Kafka', 'Alfons Mucha', 'Jaroslav Hašek']],
              ['Welcher deutschsprachige Dichter lebte außer Kafka in Prag?', 'Rainer Maria Rilke', ['Heinrich Heine', 'Friedrich Schiller', 'Hermann Hesse']],
              ['Wann wurde die Prager Universität geteilt?', '1882', ['1848', '1918', '1409']],
              ['In welche Universitäten wurde sie geteilt?', 'In eine tschechische und eine deutsche', ['In eine katholische und eine protestantische', 'In eine für Männer und eine für Frauen', 'In eine Prager und eine Brünner']],
              ['Was verlangte die Badeni-Sprachverordnung 1897?', 'Beamte sollten beide Sprachen beherrschen', ['Tschechisch wurde verboten', 'Deutsch wurde verboten', 'Latein wurde Amtssprache']],
              ['Was geschah mit der Badeni-Sprachverordnung?', 'Sie wurde nach Unruhen zurückgenommen', ['Sie gilt bis heute', 'Sie wurde ausgeweitet', 'Sie wurde nie veröffentlicht']],
              ['Wen verteidigte Masaryk 1899?', 'Leopold Hilsner', ['Franz Kafka', 'Jan Hus', 'Edvard Beneš']],
              ['Wogegen verteidigte Masaryk Hilsner?', 'Gegen einen antisemitischen Ritualmordvorwurf', ['Gegen eine Steuerforderung', 'Gegen Spionagevorwürfe', 'Gegen einen Diebstahlvorwurf']],
              ['Wo gründeten Masaryk und seine Mitstreiter den Nationalrat?', 'In Paris', ['In Prag', 'In London', 'In Moskau']],
              ['Wie kämpften die Tschechoslowakischen Legionen?', 'Auf Seiten der Alliierten', ['Auf Seiten Österreichs', 'Auf Seiten Deutschlands', 'Sie kämpften gar nicht']],
              ['Bis wohin zogen die Legionen in Russland?', 'Bis Wladiwostok', ['Bis Moskau', 'Bis Sankt Petersburg', 'Bis Kiew']],
            ],
            schwer: [
              ['Über welche Bahn zogen die Legionen durch Russland?', 'Über die Transsibirische Eisenbahn', ['Über den Orient-Express', 'Über die Bagdadbahn', 'Über die Erzbahn']],
              ['Welcher Slowake gründete den Nationalrat mit?', 'Milan Rastislav Štefánik', ['Alexander Dubček', 'Jozef Tiso', 'Andrej Hlinka']],
              ['Wann wurde in Pilsen das erste helle Pils gebraut?', '1842', ['1869', '1894', '1881']],
              ['Wann wurde die Badeni-Sprachverordnung erlassen?', '1897', ['1882', '1899', '1907']],
              ['Wann verteidigte Masaryk Hilsner?', '1899', ['1882', '1914', '1918']],
              ['Wofür setzte sich Masaryk ein?', 'Für Wahrheit und Demokratie', ['Für die Habsburger', 'Für die Monarchie', 'Für den Krieg']],
              ['Wie kämpften viele Tschechen im Ersten Weltkrieg für Österreich?', 'Nur widerwillig', ['Mit großer Begeisterung', 'Gar nicht, sie waren befreit', 'Als Generäle']],
              ['Welche Industrien prägten Böhmen außer Maschinenbau?', 'Kohle, Glas und Porzellan', ['Erdöl und Gold', 'Tee und Seide', 'Fischerei und Walfang']],
              ['Woher stammte Dvořáks Inspiration für die Sinfonie „Aus der Neuen Welt“?', 'Aus seinem Aufenthalt in den USA', ['Aus einer Reise nach China', 'Aus Russland', 'Aus dem Böhmerwald']],
              ['Wer schrieb „Mein Vaterland“?', 'Bedřich Smetana', ['Antonín Dvořák', 'Leoš Janáček', 'Gustav Mahler']],
              ['Welche Kunstrichtung prägte Mucha?', 'Den Jugendstil', ['Den Barock', 'Den Kubismus', 'Die Gotik']],
              ['Was war Masaryk von Beruf?', 'Professor', ['General', 'Bischof', 'Bierbrauer']],
              ['Wer gründete mit Masaryk den Nationalrat außer Štefánik?', 'Edvard Beneš', ['Emil Hácha', 'Klement Gottwald', 'Karel Čapek']],
              ['Welcher Satiriker beschrieb einen einfachen Soldaten im Krieg?', 'Jaroslav Hašek', ['Franz Kafka', 'Bedřich Smetana', 'Rilke']],
              ['Was ist am Motto „Das Volk sich selbst“ besonders?', 'Das Volk finanzierte sein Theater selbst', ['Der Kaiser bezahlte alles', 'Es war ein Kriegsruf', 'Es stand auf Münzen']],
              ['Wie viele Male wurde das Nationaltheater eröffnet?', 'Zweimal, 1881 und nach dem Brand 1883', ['Nur einmal 1918', 'Dreimal', 'Nie']],
              ['Wofür ist Pilsen weltbekannt?', 'Für Bier und die Škoda-Werke', ['Für Porzellan und Schuhe', 'Für Glas und Uhren', 'Für Wein und Käse']],
              ['Wie hieß der Ort von Baťas Fabrik?', 'Zlín', ['Pilsen', 'Brünn', 'Ostrau']],
              ['Was war 1918 das Ziel des Nationalrats?', 'Ein unabhängiger Staat der Tschechen und Slowaken', ['Ein Bündnis mit Österreich', 'Eine Monarchie unter Habsburg', 'Ein Teil Polens']],
              ['Auf welcher Seite standen die Legionen gegen Österreich?', 'Auf Seiten der Alliierten', ['Auf Seiten Deutschlands', 'Auf Seiten der Osmanen', 'Neutral']],
            ],
          },
        },
      ],
    },
  ],
};
