import type { Epoch } from '../types';

export const E2: Epoch = {
  id: 'expansion',
  name: 'Eisenbahn und Westen',
  period: '1867–1914',
  events: [
    {
      id: 'eisenbahn',
      title: 'Eisenbahn, Westen und Einwanderung',
      date: '1867–1914',
      text: [
        'Nach 1867 dehnte sich Kanada nach Westen aus. Die Métis unter Louis Riel wehrten sich gegen die neue Herrschaft, die transkontinentale Eisenbahn verband 1885 Atlantik und Pazifik, und Hunderttausende Einwanderer besiedelten die Prärien – auf Kosten der indigenen Völker.',
      ],
      subtopics: [
        {
          id: 'westen-riel',
          title: 'Louis Riel, Mounties und die Eisenbahn',
          date: '1869–1885',
          text: [
            '1869 kaufte Kanada der Hudson’s Bay Company das riesige Rupertsland ab. Dort lebten aber schon Indigene und die Métis, Nachfahren von französischen Pelzhändlern und indigenen Frauen. Die Métis am Red River fürchteten um ihr Land und ihre Sprache. Ihr Anführer Louis Riel bildete 1869/70 eine eigene provisorische Regierung. Nach Verhandlungen entstand 1870 die Provinz Manitoba mit Rechten für die französische Sprache und die katholische Kirche. Weil Riels Leute jedoch einen Gegner, Thomas Scott, hingerichtet hatten, musste Riel in die USA fliehen.',
            '1873 wurde die „North-West Mounted Police“ gegründet, die heutige Royal Canadian Mounted Police, kurz „Mounties“, mit ihren berühmten roten Uniformen. Sie sollte im Westen für Ordnung sorgen und den Whiskyhandel amerikanischer Händler unterbinden. Zwischen 1871 und 1921 schloss Kanada mit vielen First Nations nummerierte Verträge („Numbered Treaties“): Sie traten riesige Gebiete ab und erhielten dafür kleine Reservate und Versprechen.',
            'Die Bisonherden, von denen die Prärievölker lebten, waren um 1880 fast ausgerottet; viele Indigene litten Hunger. 1885 kehrte Louis Riel zurück und führte die Métis in der Nordwest-Rebellion an; auch Cree-Krieger kämpften mit. Regierungstruppen, die schnell mit der neuen Eisenbahn herangebracht wurden, schlugen den Aufstand bei Batoche nieder. Riel wurde in Regina wegen Hochverrats gehängt. In Québec löste das große Empörung aus; heute gilt er vielen als Gründer Manitobas.',
            'Premierminister Macdonald hatte British Columbia eine Eisenbahn zur Pazifikküste versprochen. Die Canadian Pacific Railway (CPR) wurde unter großen Mühen durch die Prärie und die Rocky Mountains gebaut. Tausende chinesische Arbeiter übernahmen die gefährlichsten Arbeiten; viele starben bei Sprengungen. Am 7. November 1885 wurde in Craigellachie in British Columbia der „letzte Nagel“ eingeschlagen.',
            'Die Eisenbahn verband das Land von Montréal bis Vancouver und machte die Besiedlung des Westens möglich. Bald entstanden entlang der Strecke Städte, und in den Rocky Mountains wurde 1885 bei Banff der erste Nationalpark Kanadas gegründet. Nach Fertigstellung der Bahn erhob Kanada 1885 eine Kopfsteuer auf chinesische Einwanderer, um sie fernzuhalten.',
          ],
          quiz: {
            leicht: [
              ['Von wem kaufte Kanada 1869 Rupertsland?', 'Von der Hudson’s Bay Company', ['Von Frankreich', 'Von den USA', 'Von Russland']],
              ['Wie heißen die Nachfahren französischer Pelzhändler und indigener Frauen?', 'Métis', ['Inuit', 'Loyalisten', 'Akadier']],
              ['Wer führte die Métis am Red River?', 'Louis Riel', ['John A. Macdonald', 'Tecumseh', 'Wilfrid Laurier']],
              ['Welche Provinz entstand 1870?', 'Manitoba', ['Alberta', 'Saskatchewan', 'British Columbia']],
              ['Wohin musste Riel nach 1870 fliehen?', 'In die USA', ['Nach Frankreich', 'Nach England', 'Nach Mexiko']],
              ['Wie nennt man die kanadische Bundespolizei?', 'Mounties', ['Rangers', 'Bobbies', 'Gendarmen']],
              ['Welche Farbe haben die berühmten Uniformen der Mounties?', 'Rot', ['Blau', 'Grün', 'Schwarz']],
              ['Wann wurde die North-West Mounted Police gegründet?', '1873', ['1867', '1885', '1920']],
              ['Welchen Handel sollten die Mounties im Westen unterbinden?', 'Den Whiskyhandel', ['Den Pelzhandel', 'Den Fischhandel', 'Den Goldhandel']],
              ['Wie heißen die Verträge mit vielen First Nations?', 'Numbered Treaties', ['Golden Treaties', 'Royal Treaties', 'Peace Charters']],
              ['Welche Tiere waren um 1880 fast ausgerottet?', 'Die Bisons', ['Die Biber', 'Die Elche', 'Die Wölfe']],
              ['Welche Rebellion führte Riel 1885 an?', 'Die Nordwest-Rebellion', ['Die Rebellion von 1837', 'Die Oktoberkrise', 'Den Krieg von 1812']],
              ['Wo wurde der Aufstand 1885 niedergeschlagen?', 'Bei Batoche', ['Bei Vimy', 'Bei Québec', 'Bei Queenston']],
              ['Was geschah 1885 mit Louis Riel?', 'Er wurde gehängt', ['Er wurde Premierminister', 'Er floh nach Frankreich', 'Er wurde begnadigt']],
              ['Wie heißt die transkontinentale Eisenbahn?', 'Canadian Pacific Railway', ['Union Pacific', 'Orient-Express', 'Transsibirische Eisenbahn']],
              ['Durch welches Gebirge führte die Eisenbahn?', 'Durch die Rocky Mountains', ['Durch die Alpen', 'Durch die Anden', 'Durch die Appalachen']],
              ['Welche Arbeiter übernahmen die gefährlichsten Arbeiten an der Bahn?', 'Chinesische Arbeiter', ['Französische Soldaten', 'Indigene Kinder', 'Britische Adlige']],
              ['Wann wurde der letzte Nagel eingeschlagen?', '1885', ['1867', '1871', '1905']],
              ['Welche Städte verband die Eisenbahn?', 'Montréal und Vancouver', ['Toronto und New York', 'Québec und Halifax', 'Ottawa und Chicago']],
              ['Wo wurde Kanadas erster Nationalpark gegründet?', 'Bei Banff', ['Bei Niagara', 'Bei Québec', 'Auf Neufundland']],
            ],
            mittel: [
              ['Wann bildete Riel eine provisorische Regierung?', '1869/70', ['1885', '1867', '1837']],
              ['Wofür fürchteten die Métis am Red River?', 'Um ihr Land und ihre Sprache', ['Um ihr Gold', 'Um ihre Schiffe', 'Um ihre Eisenbahn']],
              ['Welche Rechte erhielt Manitoba 1870?', 'Rechte für die französische Sprache und die katholische Kirche', ['Die Unabhängigkeit', 'Ein eigenes Heer', 'Das Recht auf Sklaverei']],
              ['Wen hatten Riels Leute 1870 hingerichtet?', 'Thomas Scott', ['John A. Macdonald', 'Isaac Brock', 'Lord Durham']],
              ['Wie heißen die Mounties heute offiziell?', 'Royal Canadian Mounted Police', ['North-West Rangers', 'Canadian Army Police', 'Royal Prairie Guard']],
              ['Was erhielten die First Nations in den Numbered Treaties?', 'Kleine Reservate und Versprechen', ['Große Städte', 'Eigene Staaten', 'Gold und Waffen']],
              ['Was traten die First Nations in den Verträgen ab?', 'Riesige Gebiete', ['Nichts', 'Nur Flüsse', 'Ihre Sprache']],
              ['Zwischen welchen Jahren wurden die Numbered Treaties geschlossen?', '1871 und 1921', ['1763 und 1791', '1812 und 1815', '1982 und 2000']],
              ['Woran litten viele Prärievölker nach dem Ende der Bisonherden?', 'An Hunger', ['An Überfluss', 'An Übergewicht', 'An Langeweile']],
              ['Welches Volk kämpfte 1885 mit den Métis?', 'Die Cree', ['Die Inuit', 'Die Haida', 'Die Irokesen']],
              ['Wie gelangten Regierungstruppen 1885 schnell in den Westen?', 'Mit der neuen Eisenbahn', ['Mit Flugzeugen', 'Mit Schiffen über den Pazifik', 'Zu Fuß']],
              ['Wo wurde Riel gehängt?', 'In Regina', ['In Ottawa', 'In Winnipeg', 'In Québec']],
              ['Weshalb wurde Riel verurteilt?', 'Wegen Hochverrats', ['Wegen Diebstahls', 'Wegen Mordes an Macdonald', 'Wegen Spionage für Frankreich']],
              ['Wo löste Riels Hinrichtung große Empörung aus?', 'In Québec', ['In Ontario', 'In British Columbia', 'In England']],
              ['Als was gilt Riel heute vielen?', 'Als Gründer Manitobas', ['Als Verräter', 'Als Premierminister', 'Als Erfinder']],
              ['Wo wurde der letzte Nagel eingeschlagen?', 'In Craigellachie in British Columbia', ['In Montréal', 'In Banff', 'In Winnipeg']],
              ['An welchem Tag wurde der letzte Nagel eingeschlagen?', 'Am 7. November 1885', ['Am 1. Juli 1867', 'Am 16. November 1885', 'Am 20. Juli 1871']],
              ['Woran starben viele chinesische Bahnarbeiter?', 'Bei Sprengungen', ['An Langeweile', 'An Überernährung', 'In Kriegen']],
              ['Was erhob Kanada 1885 auf chinesische Einwanderer?', 'Eine Kopfsteuer', ['Einen Zoll auf Tee', 'Nichts', 'Eine Prämie']],
              ['Was machte die Eisenbahn möglich?', 'Die Besiedlung des Westens', ['Den Krieg mit den USA', 'Den Pelzhandel mit Frankreich', 'Die Unabhängigkeit']],
            ],
            schwer: [
              ['Wann kaufte Kanada Rupertsland?', '1869', ['1867', '1870', '1885']],
              ['Wo lebten die Métis, die sich 1869 wehrten?', 'Am Red River', ['Am Sankt-Lorenz-Strom', 'Am Yukon', 'An der Hudson Bay']],
              ['Was war das Ziel der Mounties im Westen?', 'Ordnung zu schaffen', ['Gold zu suchen', 'Indigene zu bewaffnen', 'Die Eisenbahn zu bauen']],
              ['Woher kamen die Whiskyhändler, die die Mounties bekämpften?', 'Aus den USA', ['Aus Schottland', 'Aus Frankreich', 'Aus China']],
              ['Wann erhob sich Riel ein zweites Mal?', '1885', ['1870', '1873', '1890']],
              ['Welche Schlacht beendete die Nordwest-Rebellion?', 'Batoche', ['Queenston Heights', 'Abraham-Ebene', 'Vimy']],
              ['Wer hatte British Columbia die Eisenbahn versprochen?', 'John A. Macdonald', ['Wilfrid Laurier', 'Louis Riel', 'Königin Victoria']],
              ['Was symbolisiert der „letzte Nagel“?', 'Die Fertigstellung der transkontinentalen Bahn', ['Das Ende der Konföderation', 'Den Bau eines Forts', 'Den Tod Riels']],
              ['Welche Folge hatte die Kopfsteuer von 1885?', 'Sie sollte chinesische Einwanderer fernhalten', ['Sie lockte Chinesen an', 'Sie finanzierte Schulen für Chinesen', 'Sie galt für alle Einwanderer gleich']],
              ['In welchem Gebirge liegt Banff?', 'In den Rocky Mountains', ['In den Appalachen', 'In den Laurentiden', 'In den Alpen']],
              ['Wann wurde der Banff-Nationalpark gegründet?', '1885', ['1867', '1905', '1931']],
              ['Welche Volksgruppe stand im Zentrum der Konflikte von 1870 und 1885?', 'Die Métis', ['Die Inuit', 'Die Akadier', 'Die Loyalisten']],
              ['Was war Rupertsland vor 1869?', 'Gebiet der Hudson’s Bay Company', ['Eine französische Kolonie', 'Ein US-Bundesstaat', 'Ein Teil Alaskas']],
              ['Warum war die Eisenbahn 1885 militärisch wichtig?', 'Sie brachte Truppen schnell in den Westen', ['Sie brachte Gold nach England', 'Sie verband Kanada mit Mexiko', 'Sie war nicht wichtig']],
              ['Wie reagierte Québec auf Riels Hinrichtung?', 'Mit großer Empörung', ['Mit Jubel', 'Gleichgültig', 'Mit einem Krieg']],
              ['Welche Rechte schützte die Provinzgründung Manitobas?', 'Französische Sprache und katholische Kirche', ['Englisch als einzige Sprache', 'Die anglikanische Staatskirche', 'Die Rechte der Hudson’s Bay Company']],
              ['Welche Stadt wurde zum Endpunkt der Bahn am Pazifik?', 'Vancouver', ['Victoria', 'Seattle', 'Calgary']],
              ['Welche Polizei ist bis heute für ihre roten Röcke bekannt?', 'Die Mounties', ['Die Sûreté du Québec', 'Die Ontario Provincial Police', 'Die Metropolitan Police']],
              ['Was geschah mit den Bisons im 19. Jahrhundert?', 'Sie wurden fast ausgerottet', ['Sie vermehrten sich stark', 'Sie wurden nach Europa gebracht', 'Sie wurden gezähmt']],
              ['Was erhielten die First Nations in den Verträgen nicht?', 'Eigene Staaten', ['Reservate', 'Versprechen', 'Kleine Landstücke']],
            ],
          },
        },
        {
          id: 'goldrausch-einwanderung',
          title: 'Klondike, Einwanderung und Residential Schools',
          date: '1876–1914',
          text: [
            '1896 wurde am Klondike-Fluss im Yukon Gold gefunden. Rund 100.000 Glücksritter machten sich auf den Weg, viele über den eisigen Chilkoot-Pass; nur ein Teil kam an, und nur wenige wurden reich. Die Stadt Dawson wuchs in kurzer Zeit auf rund 30.000 Einwohner. 1898 wurde das Yukon-Territorium gegründet. Schriftsteller wie Jack London machten den Goldrausch berühmt.',
            'Wilfrid Laurier (1896–1911) war der erste französischsprachige Premierminister. Er sagte, das 20. Jahrhundert werde „Kanada gehören“. Unter seinem Minister Clifford Sifton warb Kanada mit Plakaten und kostenlosem Land um Siedler. Millionen Menschen kamen, darunter viele Ukrainer, Polen, Deutsche und Skandinavier, die als Bauern die Prärien besiedelten; Kanada wurde ein wichtiger Weizenproduzent. 1905 entstanden die Provinzen Alberta und Saskatchewan.',
            'Für indigene Kinder richtete der Staat ab den 1880er-Jahren gemeinsam mit den Kirchen „Residential Schools“ ein, Internate, in die die Kinder oft gegen den Willen der Eltern gebracht wurden. Ihr Ziel war es, die indigenen Kulturen auszulöschen; die Kinder durften ihre Sprache nicht sprechen. Viele erlitten Misshandlungen, Tausende starben. Die letzte dieser Schulen schloss erst 1996.',
            'Auch andere Gruppen wurden diskriminiert. Die Kopfsteuer für Chinesen stieg 1903 auf 500 Dollar. 1914 durfte das Schiff Komagata Maru mit Hunderten Einwanderern aus Indien in Vancouver nicht anlegen und musste zurückkehren.',
            'Der Telefonerfinder Alexander Graham Bell lebte zeitweise in Kanada; in Brantford in Ontario entwickelte er wichtige Ideen. Der kanadische Arzt James Naismith erfand 1891 in den USA das Basketballspiel. Die Gemälde der „Group of Seven“ machten später die wilde kanadische Landschaft berühmt.',
          ],
          quiz: {
            leicht: [
              ['Wo wurde 1896 Gold gefunden?', 'Am Klondike-Fluss im Yukon', ['In Toronto', 'In Québec', 'Auf Neufundland']],
              ['Wie viele Glücksritter machten sich auf den Weg zum Klondike?', 'Rund 100.000', ['Rund 1.000', 'Rund 100', 'Rund zehn Millionen']],
              ['Über welchen eisigen Pass zogen viele Goldsucher?', 'Über den Chilkoot-Pass', ['Über den Brenner', 'Über den Khyber-Pass', 'Über den Panamakanal']],
              ['Welche Stadt wuchs im Goldrausch schnell?', 'Dawson', ['Toronto', 'Halifax', 'Ottawa']],
              ['Welcher Schriftsteller machte den Goldrausch berühmt?', 'Jack London', ['Mark Twain', 'Charles Dickens', 'Ernest Hemingway']],
              ['Wann wurde das Yukon-Territorium gegründet?', '1898', ['1867', '1905', '1949']],
              ['Wer war der erste französischsprachige Premierminister?', 'Wilfrid Laurier', ['John A. Macdonald', 'Pierre Trudeau', 'Louis Riel']],
              ['Was sagte Laurier über das 20. Jahrhundert?', 'Es werde Kanada gehören', ['Es werde Krieg bringen', 'Es gehöre den USA', 'Es werde Frankreich gehören']],
              ['Womit lockte Kanada Siedler an?', 'Mit kostenlosem Land', ['Mit Gold', 'Mit Häusern in der Stadt', 'Mit Sklaven']],
              ['Welche Einwanderer besiedelten unter anderem die Prärien?', 'Ukrainer, Polen, Deutsche und Skandinavier', ['Brasilianer und Mexikaner', 'Franzosen und Spanier', 'Engländer ausschließlich']],
              ['Welches Getreide machte Kanada wichtig?', 'Weizen', ['Reis', 'Kaffee', 'Hirse']],
              ['Welche Provinzen entstanden 1905?', 'Alberta und Saskatchewan', ['Manitoba und Ontario', 'Yukon und Nunavut', 'Québec und Ontario']],
              ['Wie hießen die Internate für indigene Kinder?', 'Residential Schools', ['Boarding Colleges', 'Mission Houses', 'Royal Academies']],
              ['Was war das Ziel der Residential Schools?', 'Die indigenen Kulturen auszulöschen', ['Indigene Sprachen zu fördern', 'Indigene zu Häuptlingen auszubilden', 'Kinder zu ihren Familien zu bringen']],
              ['Durften die Kinder in den Schulen ihre Sprache sprechen?', 'Nein', ['Ja', 'Nur am Sonntag', 'Nur mit den Lehrern']],
              ['Wann schloss die letzte Residential School?', '1996', ['1905', '1950', '1867']],
              ['Welches Schiff mit Einwanderern aus Indien durfte 1914 nicht anlegen?', 'Die Komagata Maru', ['Die Titanic', 'Die Mayflower', 'Die Bounty']],
              ['Welcher Erfinder lebte zeitweise in Kanada?', 'Alexander Graham Bell', ['Thomas Edison', 'Nikola Tesla', 'Henry Ford']],
              ['Welches Spiel erfand der Kanadier James Naismith?', 'Basketball', ['Eishockey', 'Baseball', 'Fußball']],
              ['Welche Malergruppe machte die kanadische Landschaft berühmt?', 'Die Group of Seven', ['Die Brücke', 'Der Blaue Reiter', 'Die Impressionisten']],
            ],
            mittel: [
              ['Wie viele Einwohner hatte Dawson zur Blütezeit etwa?', 'Rund 30.000', ['Rund 300', 'Rund 3 Millionen', 'Rund 3.000']],
              ['Wie viele Goldsucher wurden wirklich reich?', 'Nur wenige', ['Fast alle', 'Die Hälfte', 'Keiner']],
              ['Wann regierte Wilfrid Laurier?', '1896–1911', ['1867–1873', '1921–1930', '1968–1979']],
              ['Welcher Minister warb um Siedler?', 'Clifford Sifton', ['John A. Macdonald', 'Lord Durham', 'Robert Borden']],
              ['Womit warb Kanada außer kostenlosem Land?', 'Mit Plakaten', ['Mit Fernsehwerbung', 'Mit Briefen an Könige', 'Gar nicht']],
              ['Wie viele Menschen kamen unter Laurier nach Kanada?', 'Millionen', ['Einige Hundert', 'Einige Tausend', 'Niemand']],
              ['Als was arbeiteten die meisten Prärie-Einwanderer?', 'Als Bauern', ['Als Fischer', 'Als Bergleute in Gold', 'Als Soldaten']],
              ['Wer betrieb die Residential Schools gemeinsam mit dem Staat?', 'Die Kirchen', ['Die Indigenen selbst', 'Die Hudson’s Bay Company', 'Die USA']],
              ['Ab wann gab es Residential Schools?', 'Ab den 1880er-Jahren', ['Ab 1600', 'Ab 1950', 'Ab 1996']],
              ['Wie kamen viele Kinder in die Residential Schools?', 'Oft gegen den Willen der Eltern', ['Freiwillig auf Wunsch der Eltern', 'Durch Losverfahren', 'Nur als Waisen']],
              ['Was erlitten viele Kinder in den Schulen?', 'Misshandlungen', ['Gute Behandlung', 'Reichtum', 'Reisen']],
              ['Wie viele Kinder starben in den Residential Schools?', 'Tausende', ['Keine', 'Zwei', 'Millionen']],
              ['Auf welchen Betrag stieg die chinesische Kopfsteuer 1903?', '500 Dollar', ['5 Dollar', '50 Dollar', '5.000 Dollar']],
              ['Woher kamen die Passagiere der Komagata Maru?', 'Aus Indien', ['Aus China', 'Aus Japan', 'Aus Irland']],
              ['In welcher Stadt durfte die Komagata Maru nicht anlegen?', 'In Vancouver', ['In Halifax', 'In Montréal', 'In Toronto']],
              ['Wo entwickelte Bell wichtige Ideen?', 'In Brantford in Ontario', ['In Québec', 'In Halifax', 'In Winnipeg']],
              ['Wo erfand Naismith Basketball?', 'In den USA', ['In Kanada', 'In England', 'In Frankreich']],
              ['Wann erfand Naismith Basketball?', '1891', ['1867', '1920', '1950']],
              ['Was wurde Kanada durch die Besiedlung der Prärien?', 'Ein wichtiger Weizenproduzent', ['Ein Goldproduzent', 'Ein Kaffeeproduzent', 'Ein Ölland']],
              ['In welchem Territorium liegt der Klondike?', 'Im Yukon', ['In Nunavut', 'In Alberta', 'In Labrador']],
            ],
            schwer: [
              ['Was bedeutete Lauriers Satz über das 20. Jahrhundert?', 'Er glaubte an Kanadas großen Aufstieg', ['Er erwartete Kanadas Untergang', 'Er wollte Krieg gegen die USA', 'Er meinte die Monarchie']],
              ['Wann wurden Alberta und Saskatchewan Provinzen?', '1905', ['1898', '1870', '1949']],
              ['Wie nennt man die Internate, deren letzte 1996 schloss?', 'Residential Schools', ['Grammar Schools', 'Public Schools', 'Mission Colleges']],
              ['Welche Diskriminierung betraf chinesische Einwanderer?', 'Eine hohe Kopfsteuer', ['Ein Verbot des Reisanbaus', 'Eine Pflicht zum Militärdienst', 'Ein Verbot des Teetrinkens']],
              ['Wann wurde die Komagata Maru abgewiesen?', '1914', ['1885', '1903', '1923']],
              ['Welches Gebiet wurde 1898 eigenes Territorium?', 'Der Yukon', ['Nunavut', 'Manitoba', 'Labrador']],
              ['Woher stammte Basketball-Erfinder James Naismith?', 'Aus Kanada', ['Aus den USA', 'Aus Schottland', 'Aus Irland']],
              ['Welche Nationalität hatten viele Prärie-Siedler?', 'Ukrainisch', ['Japanisch', 'Brasilianisch', 'Australisch']],
              ['Wie wuchs Dawson im Goldrausch?', 'In kurzer Zeit auf rund 30.000 Einwohner', ['Gar nicht', 'Langsam über 100 Jahre', 'Auf eine Million']],
              ['Was verband die Residential Schools mit den Kirchen?', 'Die Kirchen betrieben sie mit dem Staat', ['Die Kirchen bekämpften sie', 'Die Kirchen wussten nichts', 'Die Kirchen finanzierten indigene Schulen in eigener Sprache']],
              ['Wann stieg die Kopfsteuer auf 500 Dollar?', '1903', ['1885', '1914', '1923']],
              ['Welcher Premierminister regierte während des Klondike-Goldrauschs?', 'Wilfrid Laurier', ['John A. Macdonald', 'Robert Borden', 'Mackenzie King']],
              ['Welcher Minister war für die Siedlerwerbung zuständig?', 'Clifford Sifton', ['George Brown', 'Henri Bourassa', 'Sam Hughes']],
              ['Welche Erfindung verbindet man mit Bell?', 'Das Telefon', ['Die Glühbirne', 'Das Radio', 'Das Auto']],
              ['Welche Rolle spielte der Chilkoot-Pass?', 'Er war ein beschwerlicher Weg zum Goldfeld', ['Er war ein Hafen', 'Er war eine Grenze zu Mexiko', 'Er war eine Eisenbahnstation']],
              ['Welche Gruppe durfte 1914 in Vancouver nicht an Land?', 'Einwanderer aus Indien', ['Einwanderer aus England', 'Goldsucher aus den USA', 'Soldaten aus Frankreich']],
              ['Was erhielten Siedler unter Laurier?', 'Kostenloses Land', ['Kostenlose Häuser in Toronto', 'Gold', 'Nichts']],
              ['Wofür ist die Group of Seven bekannt?', 'Für Landschaftsgemälde', ['Für Eishockey', 'Für Erfindungen', 'Für Politik']],
              ['Was geschah mit den indigenen Sprachen in den Schulen?', 'Sie wurden verboten', ['Sie wurden gelehrt', 'Sie wurden aufgeschrieben und gefördert', 'Sie wurden Amtssprache']],
              ['Wann fand man Gold am Klondike?', '1896', ['1848', '1905', '1867']],
            ],
          },
        },
      ],
    },
  ],
};
