import type { Epoch } from '../types';

export const E3: Epoch = {
  id: 'jh20',
  name: 'Eigenständige Nation',
  period: '1914–1982',
  events: [
    {
      id: 'weltkriege',
      title: 'Kanada in den Weltkriegen',
      date: '1914–1945',
      text: [
        'In beiden Weltkriegen kämpften Hunderttausende Kanadier auf der Seite Großbritanniens. Der Sieg bei Vimy 1917 und der Einsatz am Juno Beach 1944 stärkten das Selbstbewusstsein. Mit dem Statut von Westminster wurde Kanada 1931 außenpolitisch unabhängig.',
      ],
      subtopics: [
        {
          id: 'erster-weltkrieg',
          title: 'Ypern, Vimy und die Wehrpflichtkrise',
          date: '1914–1918',
          text: [
            'Als Großbritannien 1914 Deutschland den Krieg erklärte, war Kanada automatisch mit im Krieg. Über 600.000 Kanadier dienten, bei rund acht Millionen Einwohnern; rund 60.000 kamen ums Leben. 1915 erlebten kanadische Soldaten bei Ypern in Belgien einen der ersten deutschen Giftgasangriffe und hielten dennoch stand. Der kanadische Arzt John McCrae schrieb dort das Gedicht „In Flanders Fields“; seitdem ist die Mohnblume Zeichen des Gedenkens.',
            'Vom 9. bis 12. April 1917 eroberten alle vier kanadischen Divisionen zum ersten Mal gemeinsam den Vimy-Rücken in Frankreich, an dem Briten und Franzosen zuvor gescheitert waren. Die Schlacht gilt als Geburtsstunde eines kanadischen Nationalgefühls; heute erinnert dort ein großes Denkmal daran. 1917 kämpften Kanadier auch in der verlustreichen Schlacht von Passchendaele.',
            'Am 6. Dezember 1917 stießen im Hafen von Halifax zwei Schiffe zusammen, darunter der mit Sprengstoff beladene französische Frachter „Mont-Blanc“. Die Explosion von Halifax war eine der größten nicht-atomaren Explosionen der Geschichte: Rund 2.000 Menschen starben, und ein Teil der Stadt wurde zerstört.',
            '1917 führte Premierminister Robert Borden die Wehrpflicht ein. Das löste die „Wehrpflichtkrise“ aus: Viele französischsprachige Kanadier in Québec wollten nicht für Großbritannien kämpfen, und 1918 kam es in Québec zu Unruhen mit Toten. Der Graben zwischen Englisch- und Französischsprachigen vertiefte sich.',
            'Frauen arbeiteten im Krieg in Fabriken und erhielten 1918 das Wahlrecht für Bundeswahlen; nur in Québec durften Frauen erst ab 1940 bei Provinzwahlen wählen. Nach dem Krieg unterzeichnete Kanada den Versailler Vertrag selbst und wurde eigenes Mitglied im Völkerbund. Der 11. November ist als „Remembrance Day“ Gedenktag.',
          ],
          quiz: {
            leicht: [
              ['Warum war Kanada 1914 automatisch im Krieg?', 'Weil Großbritannien den Krieg erklärt hatte', ['Weil Deutschland Kanada angriff', 'Weil die USA es verlangten', 'Weil Kanada Frankreich erobern wollte']],
              ['Wie viele Kanadier dienten im Ersten Weltkrieg?', 'Über 600.000', ['Rund 6.000', 'Rund 60.000', 'Über sechs Millionen']],
              ['Wie viele Kanadier kamen im Ersten Weltkrieg ums Leben?', 'Rund 60.000', ['Rund 600', 'Rund 6.000', 'Rund 600.000']],
              ['Wo erlebten Kanadier 1915 einen Giftgasangriff?', 'Bei Ypern in Belgien', ['Bei Verdun', 'Bei Gallipoli', 'Bei Tannenberg']],
              ['Welches Gedicht schrieb John McCrae?', '„In Flanders Fields“', ['„O Canada“', '„The Raven“', '„If“']],
              ['Welche Blume ist Zeichen des Gedenkens?', 'Die Mohnblume', ['Die Rose', 'Das Ahornblatt', 'Die Lilie']],
              ['Welchen Höhenzug eroberten die Kanadier 1917?', 'Den Vimy-Rücken', ['Den Montmartre', 'Die Abraham-Ebene', 'Queenston Heights']],
              ['In welchem Land liegt Vimy?', 'In Frankreich', ['In Belgien', 'In Deutschland', 'In Kanada']],
              ['Als was gilt die Schlacht von Vimy?', 'Als Geburtsstunde eines kanadischen Nationalgefühls', ['Als schwerste Niederlage', 'Als Ende des Krieges', 'Als Bürgerkrieg']],
              ['Welche Stadt wurde 1917 von einer gewaltigen Explosion getroffen?', 'Halifax', ['Toronto', 'Montréal', 'Vancouver']],
              ['Wie viele Menschen starben bei der Explosion von Halifax?', 'Rund 2.000', ['Rund 20', 'Rund 200.000', 'Niemand']],
              ['Welcher Premierminister führte 1917 die Wehrpflicht ein?', 'Robert Borden', ['Wilfrid Laurier', 'Mackenzie King', 'John A. Macdonald']],
              ['Wo war der Widerstand gegen die Wehrpflicht besonders stark?', 'In Québec', ['In Ontario', 'In British Columbia', 'In Nova Scotia']],
              ['Wann erhielten Frauen das Wahlrecht für Bundeswahlen?', '1918', ['1867', '1940', '1960']],
              ['Wo durften Frauen erst ab 1940 bei Provinzwahlen wählen?', 'In Québec', ['In Ontario', 'In Alberta', 'In Manitoba']],
              ['Welchen Vertrag unterzeichnete Kanada nach dem Krieg selbst?', 'Den Versailler Vertrag', ['Den Vertrag von Paris 1763', 'Den Frieden von Gent', 'Den NATO-Vertrag']],
              ['Welcher Organisation trat Kanada als eigenes Mitglied bei?', 'Dem Völkerbund', ['Der NATO', 'Der EU', 'Dem Warschauer Pakt']],
              ['Wie heißt der Gedenktag am 11. November?', 'Remembrance Day', ['Canada Day', 'Victoria Day', 'Thanksgiving']],
              ['Wo arbeiteten Frauen im Krieg?', 'In Fabriken', ['An der Front als Generäle', 'Im Parlament', 'Gar nicht']],
              ['Was erinnert heute in Vimy an die Schlacht?', 'Ein großes Denkmal', ['Eine Moschee', 'Ein Stadion', 'Nichts']],
            ],
            mittel: [
              ['Wie viele Einwohner hatte Kanada 1914 etwa?', 'Rund acht Millionen', ['Rund 80 Millionen', 'Rund 800.000', 'Rund 30 Millionen']],
              ['Wann erlebten Kanadier den Giftgasangriff bei Ypern?', '1915', ['1914', '1917', '1918']],
              ['Was war John McCrae von Beruf?', 'Arzt', ['General', 'Pfarrer', 'Journalist']],
              ['Wann eroberten die Kanadier den Vimy-Rücken?', 'Vom 9. bis 12. April 1917', ['Am 11. November 1918', 'Am 6. Juni 1944', 'Am 1. Juli 1916']],
              ['Was war das Besondere am Angriff auf Vimy?', 'Alle vier kanadischen Divisionen kämpften erstmals gemeinsam', ['Es kämpften nur Frauen', 'Es gab keinen Widerstand', 'Er fand auf See statt']],
              ['Wer war am Vimy-Rücken zuvor gescheitert?', 'Briten und Franzosen', ['Amerikaner und Russen', 'Deutsche', 'Japaner']],
              ['In welcher weiteren verlustreichen Schlacht kämpften Kanadier 1917?', 'Passchendaele', ['Verdun', 'Stalingrad', 'Waterloo']],
              ['Wann ereignete sich die Explosion von Halifax?', 'Am 6. Dezember 1917', ['Am 11. November 1918', 'Am 9. April 1917', 'Am 1. Juli 1917']],
              ['Wie hieß das mit Sprengstoff beladene Schiff?', 'Mont-Blanc', ['Titanic', 'Lusitania', 'Bismarck']],
              ['Woher stammte die Mont-Blanc?', 'Aus Frankreich', ['Aus Deutschland', 'Aus Kanada', 'Aus Norwegen']],
              ['Was ist besonders an der Explosion von Halifax?', 'Sie war eine der größten nicht-atomaren Explosionen', ['Sie war ein Feuerwerk', 'Sie geschah im All', 'Sie hatte keine Folgen']],
              ['Wann führte Borden die Wehrpflicht ein?', '1917', ['1914', '1918', '1939']],
              ['Was geschah 1918 in Québec wegen der Wehrpflicht?', 'Unruhen mit Toten', ['Ein Volksfest', 'Die Unabhängigkeit', 'Nichts']],
              ['Warum wollten viele in Québec nicht kämpfen?', 'Sie wollten nicht für Großbritannien kämpfen', ['Sie waren für Deutschland', 'Sie waren zu alt', 'Sie hatten keine Waffen']],
              ['Wie nennt man den Streit um die Wehrpflicht?', 'Wehrpflichtkrise', ['Oktoberkrise', 'Stille Revolution', 'Nordwest-Rebellion']],
              ['Was vertiefte sich durch die Wehrpflichtkrise?', 'Der Graben zwischen Englisch- und Französischsprachigen', ['Die Freundschaft mit Deutschland', 'Die Einheit Kanadas', 'Die Bindung an Frankreich']],
              ['Was zeigte die eigene Unterschrift unter Versailles?', 'Kanadas wachsende Eigenständigkeit', ['Kanadas Niederlage', 'Kanadas Austritt aus dem Empire', 'Nichts']],
              ['Was ist das Symbol des Remembrance Day?', 'Die Mohnblume', ['Das Ahornblatt', 'Der Biber', 'Die Lilie']],
              ['Wofür arbeiteten Frauen im Krieg in Fabriken?', 'Für die Kriegsproduktion', ['Für Mode', 'Für den Export nach Deutschland', 'Gar nicht']],
              ['Wann durften Frauen in Québec bei Provinzwahlen wählen?', 'Ab 1940', ['Ab 1918', 'Ab 1960', 'Ab 1867']],
            ],
            schwer: [
              ['Welches Gedicht machte die Mohnblume zum Gedenkzeichen?', '„In Flanders Fields“', ['„Dulce et decorum est“', '„The Soldier“', '„Anthem for Doomed Youth“']],
              ['Wie viele kanadische Divisionen griffen Vimy an?', 'Vier', ['Zwei', 'Zehn', 'Eine']],
              ['Welche Folge hatte die Explosion für Halifax?', 'Ein Teil der Stadt wurde zerstört', ['Die Stadt wurde reich', 'Der Hafen wurde vergrößert', 'Nichts']],
              ['Welcher Kriegsschauplatz in Belgien war 1915 Ort des Gasangriffs?', 'Ypern', ['Lüttich', 'Brügge', 'Antwerpen']],
              ['Welche Mitgliedschaft erhielt Kanada nach dem Ersten Weltkrieg?', 'Im Völkerbund', ['In der NATO', 'In der UNO', 'In der EU']],
              ['Wer war Robert Borden?', 'Premierminister im Ersten Weltkrieg', ['General bei Vimy', 'Dichter', 'Arzt']],
              ['Was löste die Wehrpflicht in Québec aus?', 'Die Wehrpflichtkrise', ['Die Stille Revolution', 'Die Oktoberkrise', 'Das Referendum']],
              ['Welche Provinz verweigerte Frauen das Wahlrecht am längsten?', 'Québec', ['Ontario', 'Manitoba', 'British Columbia']],
              ['Was symbolisiert Vimy für Kanadier?', 'Ein gemeinsames Nationalgefühl', ['Eine Niederlage', 'Den Bruch mit Frankreich', 'Die Gründung Québecs']],
              ['Wie viele Tage dauerte die Schlacht um Vimy?', 'Rund vier Tage', ['Ein Tag', 'Ein Jahr', 'Vier Monate']],
              ['Welcher Teil der Bevölkerung diente im Krieg ungefähr?', 'Rund jeder Dreizehnte', ['Jeder Zweite', 'Jeder Hundertste', 'Niemand']],
              ['Wie heißt die Schlacht im Schlamm von 1917 in Belgien?', 'Passchendaele', ['Somme', 'Marne', 'Vimy']],
              ['Welcher Tag erinnert an das Kriegsende 1918?', 'Der 11. November', ['Der 1. Juli', 'Der 6. Juni', 'Der 9. April']],
              ['Welche zwei Schiffe stießen in Halifax zusammen?', 'Die Mont-Blanc und ein anderes Schiff', ['Die Titanic und ein Eisberg', 'Zwei U-Boote', 'Zwei Kriegsschiffe der Deutschen']],
              ['Wann erhielt Kanada eine eigene Stimme im Völkerbund?', 'Nach dem Ersten Weltkrieg', ['1867', '1945', '1982']],
              ['Was erlebten kanadische Soldaten bei Ypern zum ersten Mal?', 'Einen deutschen Giftgasangriff', ['Einen Panzerangriff', 'Einen Luftangriff mit Bomben', 'Eine Atombombe']],
              ['Welches Ereignis 1917 erschütterte die Heimatfront in Nova Scotia?', 'Die Explosion von Halifax', ['Ein Erdbeben', 'Ein Hurrikan', 'Ein Aufstand']],
              ['Welcher Ort steht für den kanadischen Sieg 1917?', 'Vimy', ['Dieppe', 'Ortona', 'Ypern']],
              ['Wie viele Tote hatte Kanada im Verhältnis zu den Dienenden?', 'Rund jeder Zehnte', ['Fast alle', 'Niemand', 'Die Hälfte']],
              ['Was erhielten Frauen für ihren Einsatz im Krieg?', 'Das Wahlrecht für Bundeswahlen', ['Das Recht, Soldat zu werden', 'Steuerfreiheit', 'Land im Westen']],
            ],
          },
        },
        {
          id: 'zweiter-weltkrieg',
          title: 'Westminster, Depression und Zweiter Weltkrieg',
          date: '1919–1945',
          text: [
            'Nach dem Krieg wurde Kanada immer selbstständiger. 1919 kam es zum Generalstreik von Winnipeg. Mit dem Statut von Westminster 1931 erhielt Kanada die volle Unabhängigkeit in der Gesetzgebung und Außenpolitik; der britische Monarch blieb Staatsoberhaupt. 1929 entschied ein britisches Gericht, der Privy Council in London, im „Persons Case“, dass Frauen rechtlich „Personen“ sind und in den Senat berufen werden dürfen.',
            'In der Weltwirtschaftskrise der 1930er-Jahre war jeder Vierte arbeitslos, und in den Prärien zerstörten Dürren und Staubstürme die Ernten. Premierminister William Lyon Mackenzie King, der insgesamt über 21 Jahre regierte – länger als jeder andere –, führte Kanada durch Depression und Krieg. 1939 nahm Kanada ein Schiff mit über 900 jüdischen Flüchtlingen, die „St. Louis“, nicht auf.',
            'Im September 1939 erklärte Kanada Deutschland eine Woche nach Großbritannien den Krieg – diesmal mit eigener Entscheidung. Über eine Million Kanadier dienten, rund 45.000 starben. Kanada bildete im „British Commonwealth Air Training Plan“ Zehntausende Piloten aus. Der Angriff auf Dieppe 1942 endete in einer Katastrophe; über 900 Kanadier fielen, fast 2.000 gerieten in Gefangenschaft.',
            'Am 6. Juni 1944, dem D-Day, landeten kanadische Truppen in der Normandie am Strandabschnitt „Juno Beach“. 1944/45 befreiten kanadische Soldaten große Teile der Niederlande. Als Dank schicken die Niederlande bis heute jedes Jahr Tausende Tulpenzwiebeln nach Ottawa, wo die niederländische Prinzessin Margriet 1943 im Exil geboren worden war.',
            'Im eigenen Land wurden nach dem Angriff Japans auf Pearl Harbor rund 22.000 japanischstämmige Kanadier aus British Columbia in Lager gebracht und enteignet. 1988 entschuldigte sich die Regierung dafür. Nach dem Krieg wurde Kanada Gründungsmitglied der Vereinten Nationen.',
          ],
          quiz: {
            leicht: [
              ['Welches Gesetz gab Kanada 1931 volle Unabhängigkeit in der Gesetzgebung?', 'Das Statut von Westminster', ['Der BNA Act', 'Der Québec Act', 'Die Charta von 1982']],
              ['Wer blieb nach 1931 Staatsoberhaupt?', 'Der britische Monarch', ['Der Premierminister', 'Der US-Präsident', 'Niemand']],
              ['Was entschied der „Persons Case“ 1929?', 'Dass Frauen rechtlich Personen sind', ['Dass Indigene Bürger sind', 'Dass Kinder wählen dürfen', 'Dass Kanada unabhängig ist']],
              ['Wie viele waren in der Weltwirtschaftskrise arbeitslos?', 'Jeder Vierte', ['Jeder Hundertste', 'Niemand', 'Fast alle']],
              ['Was zerstörte in den Prärien die Ernten?', 'Dürren und Staubstürme', ['Überschwemmungen', 'Tsunamis', 'Vulkanausbrüche']],
              ['Welcher Premierminister regierte länger als jeder andere?', 'William Lyon Mackenzie King', ['John A. Macdonald', 'Pierre Trudeau', 'Wilfrid Laurier']],
              ['Welches Flüchtlingsschiff nahm Kanada 1939 nicht auf?', 'Die St. Louis', ['Die Titanic', 'Die Komagata Maru', 'Die Mayflower']],
              ['Wer war auf der St. Louis?', 'Jüdische Flüchtlinge', ['Deutsche Soldaten', 'Chinesische Arbeiter', 'Britische Touristen']],
              ['Wann erklärte Kanada Deutschland den Krieg?', 'Im September 1939', ['Im Juni 1944', 'Im Dezember 1941', 'Im August 1914']],
              ['Wie viele Kanadier dienten im Zweiten Weltkrieg?', 'Über eine Million', ['Rund 10.000', 'Rund 100.000', 'Über zehn Millionen']],
              ['Was bildete Kanada im Zweiten Weltkrieg in großer Zahl aus?', 'Piloten', ['Köche', 'Bergsteiger', 'Ärzte für Japan']],
              ['Welcher Angriff 1942 endete in einer Katastrophe?', 'Dieppe', ['Vimy', 'Juno Beach', 'Ortona']],
              ['Wo landeten Kanadier am D-Day?', 'Am Juno Beach', ['Am Omaha Beach', 'In Dieppe', 'In Sizilien']],
              ['Wann war der D-Day?', 'Am 6. Juni 1944', ['Am 11. November 1918', 'Am 8. Mai 1945', 'Am 1. September 1939']],
              ['Welches Land befreiten Kanadier 1944/45 großteils?', 'Die Niederlande', ['Polen', 'Norwegen', 'Griechenland']],
              ['Was schicken die Niederlande jedes Jahr nach Ottawa?', 'Tulpenzwiebeln', ['Käse', 'Holzschuhe', 'Windmühlen']],
              ['Welche niederländische Prinzessin wurde in Ottawa geboren?', 'Margriet', ['Beatrix', 'Juliana', 'Amalia']],
              ['Welche Gruppe wurde nach Pearl Harbor in Lager gebracht?', 'Japanischstämmige Kanadier', ['Deutschstämmige Kanadier', 'Italiener', 'Ukrainer']],
              ['Wann entschuldigte sich die Regierung bei den japanischstämmigen Kanadiern?', '1988', ['1945', '1967', '2015']],
              ['Welcher Organisation war Kanada 1945 Gründungsmitglied?', 'Den Vereinten Nationen', ['Der EU', 'Der OPEC', 'Dem Warschauer Pakt']],
            ],
            mittel: [
              ['Wann fand der Generalstreik von Winnipeg statt?', '1919', ['1929', '1939', '1945']],
              ['Wann wurde das Statut von Westminster erlassen?', '1931', ['1919', '1867', '1982']],
              ['Wann wurde der Persons Case entschieden?', '1929', ['1918', '1931', '1940']],
              ['Wohin durften Frauen nach dem Persons Case berufen werden?', 'In den Senat', ['In die Armee', 'In den Papststuhl', 'In den Papstrat']],
              ['Wie lange regierte Mackenzie King insgesamt?', 'Über 21 Jahre', ['Rund 5 Jahre', 'Über 40 Jahre', 'Ein Jahr']],
              ['Wie viele Flüchtlinge waren auf der St. Louis?', 'Über 900', ['Rund 90', 'Über 9.000', 'Rund 9']],
              ['Wann nahm Kanada die St. Louis nicht auf?', '1939', ['1933', '1945', '1914']],
              ['Wie viele Tage nach Großbritannien erklärte Kanada den Krieg?', 'Eine Woche', ['Sofort am selben Tag', 'Ein Jahr', 'Nie']],
              ['Was war 1939 anders als 1914?', 'Kanada entschied selbst über den Kriegseintritt', ['Kanada war neutral', 'Kanada kämpfte für Deutschland', 'Kanada hatte keine Armee']],
              ['Wie viele Kanadier starben im Zweiten Weltkrieg?', 'Rund 45.000', ['Rund 4.500', 'Rund 450.000', 'Rund 450']],
              ['Wie hieß das Ausbildungsprogramm für Piloten?', 'British Commonwealth Air Training Plan', ['Operation Overlord', 'Manhattan Project', 'Marshall Plan']],
              ['Wie viele Kanadier fielen in Dieppe?', 'Über 900', ['Rund 9', 'Rund 90', 'Über 9.000']],
              ['Wie viele Kanadier gerieten in Dieppe in Gefangenschaft?', 'Fast 2.000', ['Rund 20', 'Rund 200', 'Rund 20.000']],
              ['Wann fand der Angriff auf Dieppe statt?', '1942', ['1944', '1940', '1917']],
              ['In welcher Region landeten die Alliierten am D-Day?', 'In der Normandie', ['In der Bretagne', 'In Sizilien', 'In Norwegen']],
              ['Warum wurde Prinzessin Margriet in Ottawa geboren?', 'Ihre Familie lebte dort im Exil', ['Ihr Vater war Kanadier', 'Sie war auf Urlaub', 'Ottawa gehörte zu den Niederlanden']],
              ['Wann wurde Prinzessin Margriet geboren?', '1943', ['1945', '1939', '1950']],
              ['Wie viele japanischstämmige Kanadier wurden in Lager gebracht?', 'Rund 22.000', ['Rund 220', 'Rund 2.200', 'Rund 220.000']],
              ['Aus welcher Provinz wurden die japanischstämmigen Kanadier gebracht?', 'Aus British Columbia', ['Aus Québec', 'Aus Ontario', 'Aus Neufundland']],
              ['Was geschah außer der Internierung mit ihrem Besitz?', 'Sie wurden enteignet', ['Er wurde verdoppelt', 'Er blieb unberührt', 'Er wurde nach Japan geschickt']],
            ],
            schwer: [
              ['Welches Gericht entschied den Persons Case letztlich?', 'Ein britisches Gericht', ['Der Papst', 'Ein US-Gericht', 'Ein Gericht in Québec']],
              ['Was bedeutete das Statut von Westminster außenpolitisch?', 'Volle Unabhängigkeit in der Außenpolitik', ['Anschluss an die USA', 'Austritt aus dem Empire', 'Verbot einer Armee']],
              ['Wie viele Jahre regierte Mackenzie King mindestens?', 'Über 21', ['Über 12', 'Über 31', 'Genau 10']],
              ['Welche Wirtschaftskatastrophe prägte die 1930er?', 'Die Weltwirtschaftskrise', ['Die Ölkrise', 'Der Goldrausch', 'Die Finanzkrise 2008']],
              ['Wofür steht der Name „Juno Beach“?', 'Für den kanadischen Landeabschnitt am D-Day', ['Für einen Strand in Kanada', 'Für eine Schlacht 1917', 'Für einen Hafen in Japan']],
              ['Welches Land dankt Kanada jährlich mit Tulpen?', 'Die Niederlande', ['Belgien', 'Frankreich', 'Dänemark']],
              ['Was folgte 1988 für die japanischstämmigen Kanadier?', 'Eine offizielle Entschuldigung', ['Eine neue Internierung', 'Die Ausbürgerung', 'Nichts']],
              ['Welches Ereignis löste die Internierung aus?', 'Der Angriff Japans auf Pearl Harbor', ['Der D-Day', 'Der Angriff auf Dieppe', 'Die Atombombe']],
              ['Welche Haltung zeigte Kanada 1939 gegenüber jüdischen Flüchtlingen?', 'Es wies die St. Louis ab', ['Es nahm alle auf', 'Es schickte Schiffe nach Europa', 'Es gab ihnen Land im Westen']],
              ['Welcher Angriff 1942 war eine Katastrophe für Kanada?', 'Dieppe', ['Ortona', 'Normandie', 'Hongkong']],
              ['Was traf die Prärien in den 1930er-Jahren?', 'Dürren und Staubstürme', ['Schneestürme ganzjährig', 'Ein Ölboom', 'Ein Goldrausch']],
              ['Welcher Generalstreik erschütterte 1919 eine Stadt im Westen?', 'Winnipeg', ['Vancouver', 'Calgary', 'Regina']],
              ['Welche Rolle hatte Kanada beim Air Training Plan?', 'Es bildete Zehntausende Piloten aus', ['Es baute Panzer', 'Es lieferte Atombomben', 'Es lehnte ihn ab']],
              ['Was entschied ein Gericht 1929 über Frauen?', 'Sie sind rechtlich „Personen“', ['Sie dürfen nicht arbeiten', 'Sie dürfen keine Autos fahren', 'Sie müssen Militärdienst leisten']],
              ['Wann wurde Kanada Gründungsmitglied der UNO?', '1945', ['1919', '1931', '1949']],
              ['Welche Ernten gingen in den Prärien verloren?', 'Getreideernten', ['Reisernten', 'Kaffeeernten', 'Teeernten']],
              ['Welches Land befreiten Kanadier in Europa außer Teilen Frankreichs besonders?', 'Die Niederlande', ['Spanien', 'Schweden', 'Österreich']],
              ['Wie entschied Kanada 1939 über den Kriegseintritt?', 'Selbstständig', ['London entschied', 'Washington entschied', 'Es wurde gelost']],
              ['Was erhielt Kanada mit dem Statut von Westminster nicht?', 'Ein eigenes Staatsoberhaupt', ['Gesetzgebungsfreiheit', 'Außenpolitische Freiheit', 'Ein Parlament']],
              ['Welche Bevölkerungsgruppe litt an der Westküste besonders unter Diskriminierung im Krieg?', 'Japanischstämmige Kanadier', ['Deutschstämmige Mennoniten', 'Franzosen', 'Iren']],
            ],
          },
        },
      ],
    },
    {
      id: 'wohlfahrt-quebec',
      title: 'Wohlfahrt, Ahornblatt und Québec',
      date: '1945–1982',
      text: [
        'Nach 1945 wurde Kanada ein wohlhabender Sozialstaat und ein Vermittler in der Welt. Es erhielt 1965 seine Ahornblattflagge, und in Québec veränderte die „Stille Revolution“ die Gesellschaft. Viele Québecer wollten die Unabhängigkeit. Mit der Verfassung von 1982 wurde Kanada endgültig rechtlich eigenständig.',
      ],
      subtopics: [
        {
          id: 'nachkrieg-pearson',
          title: 'Neufundland, Blauhelme und Ahornblatt',
          date: '1945–1970',
          text: [
            '1949 trat Neufundland nach zwei knappen Volksabstimmungen als zehnte Provinz Kanada bei. Im selben Jahr wurde Kanada Gründungsmitglied der NATO. Kanadische Soldaten kämpften im Koreakrieg.',
            'Außenminister Lester B. Pearson schlug 1956 in der Suezkrise vor, eine Friedenstruppe der Vereinten Nationen zu schicken – die ersten „Blauhelme“. Dafür erhielt er 1957 den Friedensnobelpreis. Kanada wurde für seine friedenserhaltenden Einsätze bekannt. Pearson war von 1963 bis 1968 Premierminister.',
            'Unter Pearson erhielt Kanada 1965 seine rote Flagge mit dem weißen Feld und dem roten Ahornblatt, nachdem die alte Flagge noch den britischen „Union Jack“ enthalten hatte. Man führte die Rentenversicherung und 1966 eine landesweite öffentliche Krankenversicherung ein, die Kanadier bis heute als wichtigen Teil ihrer Identität sehen.',
            '1967 feierte Kanada seinen 100. Geburtstag mit der Weltausstellung Expo 67 in Montréal, die über 50 Millionen Besuche zählte. Bei einem Besuch rief der französische Präsident Charles de Gaulle in Montréal „Vive le Québec libre!“ („Es lebe das freie Québec!“), was einen diplomatischen Skandal auslöste.',
            'Der St.-Lorenz-Seeweg, 1959 eröffnet, verband die Großen Seen für Hochseeschiffe mit dem Atlantik. Kanadas Wirtschaft wuchs dank Rohstoffen wie Öl aus Alberta, Holz und Erzen. 1969 machte das Gesetz über die Amtssprachen Englisch und Französisch auf Bundesebene gleichberechtigt.',
          ],
          quiz: {
            leicht: [
              ['Welche Provinz trat 1949 als zehnte bei?', 'Neufundland', ['Alberta', 'Prince Edward Island', 'Nunavut']],
              ['Welchem Bündnis trat Kanada 1949 als Gründungsmitglied bei?', 'Der NATO', ['Der EU', 'Dem Warschauer Pakt', 'Der OPEC']],
              ['In welchem Krieg kämpften kanadische Soldaten in den 1950er-Jahren?', 'Im Koreakrieg', ['Im Vietnamkrieg', 'Im Golfkrieg', 'Im Krimkrieg']],
              ['Wer schlug 1956 eine UN-Friedenstruppe vor?', 'Lester B. Pearson', ['Pierre Trudeau', 'Mackenzie King', 'John Diefenbaker']],
              ['Wie nennt man UN-Friedenssoldaten?', 'Blauhelme', ['Rothelme', 'Grünjacken', 'Mounties']],
              ['Welchen Preis erhielt Pearson 1957?', 'Den Friedensnobelpreis', ['Den Literaturnobelpreis', 'Einen Oscar', 'Den Pulitzerpreis']],
              ['Wofür wurde Kanada international bekannt?', 'Für friedenserhaltende Einsätze', ['Für Eroberungen', 'Für Atomwaffen', 'Für Kolonien']],
              ['Wann erhielt Kanada die Ahornblattflagge?', '1965', ['1867', '1931', '1982']],
              ['Welches Symbol zeigt die kanadische Flagge?', 'Ein rotes Ahornblatt', ['Einen Biber', 'Einen Elch', 'Eine Krone']],
              ['Was enthielt die alte kanadische Flagge?', 'Den Union Jack', ['Ein Ahornblatt', 'Eine Lilie', 'Sterne und Streifen']],
              ['Was führte Kanada 1966 landesweit ein?', 'Eine öffentliche Krankenversicherung', ['Die Monarchie', 'Den Euro', 'Die Wehrpflicht']],
              ['Wo fand die Expo 67 statt?', 'In Montréal', ['In Toronto', 'In Vancouver', 'In Ottawa']],
              ['Welchen Geburtstag feierte Kanada 1967?', 'Den 100.', ['Den 50.', 'Den 200.', 'Den 1000.']],
              ['Wer rief „Vive le Québec libre!“?', 'Charles de Gaulle', ['Napoleon', 'François Mitterrand', 'Pierre Trudeau']],
              ['Was löste de Gaulles Ruf aus?', 'Einen diplomatischen Skandal', ['Einen Krieg', 'Die Unabhängigkeit Québecs', 'Nichts']],
              ['Was verband der St.-Lorenz-Seeweg?', 'Die Großen Seen mit dem Atlantik', ['Den Pazifik mit dem Atlantik', 'Kanada mit Mexiko', 'Ontario mit Alaska']],
              ['Welche Rohstoffe trugen zum Wachstum bei?', 'Öl, Holz und Erze', ['Kaffee und Tee', 'Kakao', 'Reis']],
              ['Woher kommt Kanadas Öl vor allem?', 'Aus Alberta', ['Aus Québec', 'Aus Nova Scotia', 'Aus dem Yukon']],
              ['Welche Sprachen machte das Gesetz von 1969 gleichberechtigt?', 'Englisch und Französisch', ['Englisch und Spanisch', 'Französisch und Cree', 'Englisch und Deutsch']],
              ['Wie sehen Kanadier ihre Krankenversicherung?', 'Als wichtigen Teil ihrer Identität', ['Als unwichtig', 'Als amerikanische Erfindung', 'Als Last ohne Nutzen']],
            ],
            mittel: [
              ['Wie trat Neufundland bei?', 'Nach zwei knappen Volksabstimmungen', ['Durch Krieg', 'Durch Kauf', 'Durch Entscheidung der USA']],
              ['In welcher Krise schlug Pearson die Blauhelme vor?', 'In der Suezkrise', ['In der Kubakrise', 'In der Berlinkrise', 'In der Koreakrise']],
              ['Wann war die Suezkrise?', '1956', ['1962', '1948', '1973']],
              ['Wann war Pearson Premierminister?', '1963–1968', ['1949–1957', '1968–1979', '1984–1993']],
              ['Welche Farben hat die kanadische Flagge?', 'Rot und Weiß', ['Blau und Weiß', 'Grün und Gold', 'Rot und Blau']],
              ['Was wurde unter Pearson außer der Krankenversicherung eingeführt?', 'Die Rentenversicherung', ['Die Monarchie', 'Die Wehrpflicht', 'Eine Kirchensteuer']],
              ['Wie viele Besuche zählte die Expo 67?', 'Über 50 Millionen', ['Rund 500.000', 'Rund 5 Millionen', 'Über 500 Millionen']],
              ['Was bedeutet „Vive le Québec libre!“?', 'Es lebe das freie Québec!', ['Es lebe Kanada!', 'Es lebe Frankreich!', 'Freiheit für alle!']],
              ['Welches Amt hatte de Gaulle?', 'Französischer Präsident', ['Premierminister Québecs', 'König', 'UN-Generalsekretär']],
              ['Wann wurde der St.-Lorenz-Seeweg eröffnet?', '1959', ['1867', '1945', '1982']],
              ['Für welche Schiffe öffnete der Seeweg die Großen Seen?', 'Für Hochseeschiffe', ['Für Kanus', 'Für Flöße', 'Für Flugzeuge']],
              ['Wann wurde das Gesetz über die Amtssprachen beschlossen?', '1969', ['1867', '1982', '1995']],
              ['Auf welcher Ebene galt die Gleichberechtigung der Sprachen 1969?', 'Auf Bundesebene', ['Nur in Québec', 'Nur in Ontario', 'In keiner']],
              ['Was war die Krankenversicherung von 1966?', 'Öffentlich und landesweit', ['Privat und teuer', 'Nur für Soldaten', 'Nur für Québec']],
              ['Was war Pearson vor seiner Zeit als Premierminister?', 'Außenminister', ['General', 'Bürgermeister von Montréal', 'Bischof']],
              ['Welche Organisation stellte die ersten Blauhelme?', 'Die Vereinten Nationen', ['Die NATO', 'Der Völkerbund', 'Die EU']],
              ['Welche Rolle übernahm Kanada in der Welt?', 'Die eines Vermittlers', ['Die einer Kolonialmacht', 'Die eines Angreifers', 'Keine']],
              ['Wofür steht das Jahr 1967 in Kanada?', 'Für den 100. Geburtstag und die Expo', ['Für die Unabhängigkeit', 'Für den NATO-Beitritt', 'Für die neue Verfassung']],
              ['Welche Provinz trat als letzte bei, bevor Territorien hinzukamen?', 'Neufundland', ['Prince Edward Island', 'British Columbia', 'Alberta']],
              ['Wann trat Neufundland bei?', '1949', ['1867', '1905', '1965']],
            ],
            schwer: [
              ['Wann erhielt Pearson den Friedensnobelpreis?', '1957', ['1956', '1965', '1949']],
              ['Was war die Expo 67?', 'Eine Weltausstellung', ['Eine Olympiade', 'Ein Krieg', 'Eine Messe nur für Autos']],
              ['Welche Flagge ersetzte die Ahornblattflagge?', 'Eine Flagge mit dem Union Jack', ['Die französische Trikolore', 'Die US-Flagge', 'Eine grüne Flagge']],
              ['Wie viele Volksabstimmungen gab es in Neufundland 1948?', 'Zwei', ['Eine', 'Drei', 'Keine']],
              ['Welches Programm ist Kanadiern besonders wichtig?', 'Die öffentliche Krankenversicherung', ['Das Militär', 'Die Monarchie', 'Die Ölindustrie']],
              ['Welche Wasserstraße wurde 1959 eröffnet?', 'Der St.-Lorenz-Seeweg', ['Der Panamakanal', 'Der Rideau-Kanal', 'Der Suezkanal']],
              ['Welcher Gast sorgte 1967 für einen Skandal?', 'Charles de Gaulle', ['Queen Elizabeth', 'John F. Kennedy', 'Nikita Chruschtschow']],
              ['Was erkannte das Sprachengesetz von 1969 an?', 'Die Gleichberechtigung von Englisch und Französisch', ['Englisch als einzige Sprache', 'Französisch als einzige Sprache', 'Indigene Sprachen als Amtssprachen']],
              ['Welche Erfindung nannte man nach Pearsons Idee?', 'Die UN-Friedenstruppe', ['Das Ahornblatt', 'Die Expo', 'Die Krankenversicherung']],
              ['Welches Militärbündnis gründete Kanada 1949 mit?', 'Die NATO', ['Den Warschauer Pakt', 'Die SEATO', 'Die ASEAN']],
              ['Welche Provinz liefert viel Öl?', 'Alberta', ['Manitoba', 'New Brunswick', 'Prince Edward Island']],
              ['Wann führte Kanada die landesweite öffentliche Krankenversicherung ein?', '1966', ['1945', '1984', '1999']],
              ['Unter welchem Premierminister kam die Ahornblattflagge?', 'Lester B. Pearson', ['Pierre Trudeau', 'John Diefenbaker', 'Mackenzie King']],
              ['Wie hieß Kanadas Außenminister 1956?', 'Lester B. Pearson', ['Louis St. Laurent', 'Pierre Trudeau', 'Brian Mulroney']],
              ['Wofür steht der Begriff „Blauhelme“ heute?', 'Für UN-Friedenseinsätze', ['Für Bauarbeiter', 'Für Polizei in Québec', 'Für Feuerwehr']],
              ['Was verursachte de Gaulles Ausruf diplomatisch?', 'Spannungen zwischen Kanada und Frankreich', ['Ein Bündnis', 'Einen Handelsvertrag', 'Nichts']],
              ['Welche Stadt war Gastgeber der Weltausstellung 1967?', 'Montréal', ['Québec', 'Toronto', 'Ottawa']],
              ['Wann wurde die Ahornblattflagge eingeführt?', '1965', ['1967', '1949', '1982']],
              ['Welchen Krieg in Asien unterstützte Kanada in den 1950ern mit Soldaten?', 'Den Koreakrieg', ['Den Vietnamkrieg', 'Den Opiumkrieg', 'Den Afghanistankrieg']],
              ['Was war Neufundland vor 1949?', 'Eine eigene britische Kolonie', ['Ein Teil der USA', 'Ein Teil Frankreichs', 'Ein Teil Québecs']],
            ],
          },
        },
        {
          id: 'quebec-verfassung',
          title: 'Stille Revolution, Oktoberkrise und Verfassung 1982',
          date: '1960–1982',
          text: [
            'Bis 1959 regierte in Québec Premier Maurice Duplessis konservativ und eng mit der katholischen Kirche verbunden; man nennt diese Zeit „Grande Noirceur“ („Große Finsternis“). Ab 1960 veränderte die „Stille Revolution“ unter Premier Jean Lesage die Provinz: Schulen und Krankenhäuser wurden von der Kirche an den Staat übergeben, die Stromwirtschaft verstaatlicht (Hydro-Québec), und das Motto lautete „Maîtres chez nous“ („Herren im eigenen Haus“).',
            'Eine kleine Terrorgruppe, die „Front de libération du Québec“ (FLQ), verübte Bombenanschläge. Im Oktober 1970 entführte sie einen britischen Diplomaten und den Québecer Minister Pierre Laporte, der ermordet wurde. Premierminister Pierre Elliott Trudeau setzte das Kriegsmaßnahmengesetz ein, Soldaten patrouillierten in Montréal, Hunderte wurden verhaftet – die „Oktoberkrise“.',
            'Pierre Trudeau (1968–1979 und 1980–1984) war ein charismatischer Premierminister aus Québec, der für ein geeintes, zweisprachiges Kanada kämpfte. 1971 erklärte Kanada als erstes Land den Multikulturalismus zur offiziellen Politik.',
            '1976 gewann die Unabhängigkeitspartei Parti Québécois unter René Lévesque die Wahl in Québec. 1977 machte das Gesetz „Charte de la langue française“ (Bill 101) Französisch zur einzigen Amtssprache Québecs. 1980 lehnten rund 60 Prozent in einem Referendum die Unabhängigkeit ab. 1976 war Montréal Gastgeber der Olympischen Sommerspiele.',
            'Bis 1982 musste das britische Parlament Änderungen der kanadischen Verfassung zustimmen. Mit dem Constitution Act von 1982, den Königin Elizabeth II. am 17. April 1982 in Ottawa unterzeichnete, holte Trudeau die Verfassung „nach Hause“; sie enthält eine Charta der Rechte und Freiheiten und erkennt die Rechte der Indigenen an. Québec stimmte der neuen Verfassung jedoch nicht zu.',
          ],
          quiz: {
            leicht: [
              ['Wie nennt man die Modernisierung Québecs ab 1960?', 'Stille Revolution', ['Samtene Revolution', 'Oktoberkrise', 'Große Finsternis']],
              ['Welcher Premier leitete die Stille Revolution?', 'Jean Lesage', ['Maurice Duplessis', 'René Lévesque', 'Pierre Trudeau']],
              ['Wie nennt man die Zeit unter Duplessis?', 'Große Finsternis', ['Stille Revolution', 'Goldene Zeit', 'Tulpenzeit']],
              ['Mit welcher Institution war Duplessis eng verbunden?', 'Mit der katholischen Kirche', ['Mit den Gewerkschaften', 'Mit den USA', 'Mit der FLQ']],
              ['Welches Unternehmen wurde verstaatlicht?', 'Hydro-Québec', ['Bombardier', 'Air Canada', 'Hudson’s Bay Company']],
              ['Was bedeutet „Maîtres chez nous“?', 'Herren im eigenen Haus', ['Es lebe Québec', 'Freiheit für alle', 'Gott schütze Kanada']],
              ['Wie hieß die Terrorgruppe in Québec?', 'FLQ', ['IRA', 'ETA', 'PKK']],
              ['Welcher Minister wurde 1970 ermordet?', 'Pierre Laporte', ['René Lévesque', 'Jean Lesage', 'Robert Bourassa']],
              ['Wie nennt man die Ereignisse vom Oktober 1970?', 'Oktoberkrise', ['Stille Revolution', 'Wehrpflichtkrise', 'Oktoberrevolution']],
              ['Welcher Premierminister setzte das Kriegsmaßnahmengesetz ein?', 'Pierre Elliott Trudeau', ['Lester B. Pearson', 'Brian Mulroney', 'Justin Trudeau']],
              ['Wofür kämpfte Pierre Trudeau?', 'Für ein geeintes, zweisprachiges Kanada', ['Für Québecs Unabhängigkeit', 'Für den Anschluss an die USA', 'Für die Monarchie in Québec']],
              ['Was erklärte Kanada 1971 als erstes Land zur offiziellen Politik?', 'Den Multikulturalismus', ['Den Kommunismus', 'Die Neutralität', 'Die Monarchie']],
              ['Welche Partei gewann 1976 in Québec?', 'Die Parti Québécois', ['Die Liberale Partei', 'Die Konservative Partei', 'Die NDP']],
              ['Wer führte die Parti Québécois?', 'René Lévesque', ['Pierre Trudeau', 'Jean Lesage', 'Maurice Duplessis']],
              ['Was machte Bill 101 zur einzigen Amtssprache Québecs?', 'Französisch', ['Englisch', 'Englisch und Französisch', 'Cree']],
              ['Wie viele lehnten 1980 Québecs Unabhängigkeit ab?', 'Rund 60 Prozent', ['Rund 40 Prozent', 'Rund 90 Prozent', 'Genau 50 Prozent']],
              ['Wo fanden die Olympischen Sommerspiele 1976 statt?', 'In Montréal', ['In Toronto', 'In Vancouver', 'In Calgary']],
              ['Welches Gesetz holte die Verfassung 1982 „nach Hause“?', 'Der Constitution Act von 1982', ['Der BNA Act', 'Das Statut von Westminster', 'Der Québec Act']],
              ['Was enthält die Verfassung von 1982?', 'Eine Charta der Rechte und Freiheiten', ['Ein Verbot der Monarchie', 'Den Anschluss an die USA', 'Ein Verbot des Französischen']],
              ['Welche Provinz stimmte der Verfassung von 1982 nicht zu?', 'Québec', ['Ontario', 'Alberta', 'Neufundland']],
            ],
            mittel: [
              ['Bis wann regierte Duplessis?', 'Bis 1959', ['Bis 1945', 'Bis 1970', 'Bis 1980']],
              ['Was wurde in der Stillen Revolution von der Kirche an den Staat übergeben?', 'Schulen und Krankenhäuser', ['Die Armee', 'Die Banken', 'Die Eisenbahn']],
              ['Wie regierte Duplessis?', 'Konservativ', ['Kommunistisch', 'Liberal-revolutionär', 'Gar nicht']],
              ['Wofür steht die Abkürzung FLQ?', 'Front de libération du Québec', ['Force libre québécoise', 'Front libéral du Québec', 'Fédération des langues québécoises']],
              ['Wen entführte die FLQ außer Laporte?', 'Einen britischen Diplomaten', ['Den Premierminister', 'Den Papst', 'Einen US-Präsidenten']],
              ['Wann fand die Oktoberkrise statt?', '1970', ['1960', '1976', '1980']],
              ['Was geschah während der Oktoberkrise in Montréal?', 'Soldaten patrouillierten', ['Es fand die Expo statt', 'Die Stadt wurde unabhängig', 'Ein Erdbeben']],
              ['Wie viele Menschen wurden in der Oktoberkrise verhaftet?', 'Hunderte', ['Keiner', 'Zwei', 'Hunderttausende']],
              ['Wann war Pierre Trudeau Premierminister?', '1968–1979 und 1980–1984', ['1963–1968', '1984–1993', '2015–2025']],
              ['Woher stammte Pierre Trudeau?', 'Aus Québec', ['Aus Ontario', 'Aus Alberta', 'Aus Frankreich']],
              ['Wann wurde der Multikulturalismus offizielle Politik?', '1971', ['1967', '1982', '1995']],
              ['Wann gewann die Parti Québécois?', '1976', ['1970', '1980', '1995']],
              ['Wann wurde Bill 101 beschlossen?', '1977', ['1969', '1982', '1995']],
              ['Wann fand das erste Referendum über Québecs Unabhängigkeit statt?', '1980', ['1976', '1995', '1970']],
              ['Wer musste bis 1982 Verfassungsänderungen zustimmen?', 'Das britische Parlament', ['Der US-Kongress', 'Der Papst', 'Niemand']],
              ['Wer unterzeichnete den Constitution Act 1982?', 'Königin Elizabeth II.', ['Brian Mulroney', 'René Lévesque', 'Der Papst']],
              ['An welchem Tag wurde die Verfassung 1982 unterzeichnet?', 'Am 17. April 1982', ['Am 1. Juli 1982', 'Am 1. Juli 1867', 'Am 11. Dezember 1931']],
              ['Wo wurde die Verfassung 1982 unterzeichnet?', 'In Ottawa', ['In London', 'In Montréal', 'In Québec']],
              ['Wessen Rechte erkennt die Verfassung von 1982 ausdrücklich an?', 'Die Rechte der Indigenen', ['Die Rechte des Papstes', 'Die Rechte der USA', 'Die Rechte der Hudson’s Bay Company']],
              ['Was bedeutet „die Verfassung nach Hause holen“?', 'Kanada kann seine Verfassung selbst ändern', ['Die Verfassung wurde aus Paris geholt', 'Die Verfassung wurde gedruckt', 'Die Verfassung wurde abgeschafft']],
            ],
            schwer: [
              ['Was bedeutet „Grande Noirceur“?', 'Große Finsternis', ['Große Freiheit', 'Großer Krieg', 'Große Stille']],
              ['Welches Gesetz nutzte Trudeau 1970?', 'Das Kriegsmaßnahmengesetz', ['Das Sprachengesetz', 'Den Constitution Act', 'Bill 101']],
              ['Wie heißt Bill 101 offiziell?', 'Charte de la langue française', ['Loi sur les langues officielles', 'Charte des droits', 'Acte de Québec']],
              ['Welche Partei vertrat die Unabhängigkeit Québecs?', 'Die Parti Québécois', ['Die Liberale Partei Kanadas', 'Die Bloc Conservateur', 'Die Grünen']],
              ['Wann lehnte Québec die Unabhängigkeit erstmals ab?', '1980', ['1976', '1995', '1982']],
              ['Welches Motto stand für die Stille Revolution?', '„Maîtres chez nous“', ['„Je me souviens“', '„Vive le Québec libre“', '„Liberté, égalité“']],
              ['Was war Hydro-Québec?', 'Das verstaatlichte Stromunternehmen', ['Eine Bank', 'Eine Partei', 'Eine Universität']],
              ['Welche Politik wurde 1971 offiziell?', 'Multikulturalismus', ['Assimilation', 'Monokultur', 'Segregation']],
              ['Welcher Premier Québecs prägte die 1950er?', 'Maurice Duplessis', ['Jean Lesage', 'René Lévesque', 'Robert Bourassa']],
              ['Welche Provinz verweigerte 1982 ihre Zustimmung?', 'Québec', ['Alberta', 'Manitoba', 'Nova Scotia']],
              ['Welches Opfer forderte die Oktoberkrise?', 'Minister Pierre Laporte', ['Premier Lévesque', 'Trudeau', 'Ein britischer König']],
              ['Was enthielt die Verfassung von 1982 Neues?', 'Die Charta der Rechte und Freiheiten', ['Ein Wahlrecht für Kinder', 'Den Austritt aus der NATO', 'Die Republik']],
              ['Welcher Premierminister amtierte bei der Verfassung von 1982?', 'Pierre Trudeau', ['Brian Mulroney', 'Joe Clark', 'Lester Pearson']],
              ['Wer war Jean Lesage?', 'Premier Québecs ab 1960', ['Premierminister Kanadas', 'Anführer der FLQ', 'Bürgermeister von Toronto']],
              ['Wie hoch war die Ablehnung beim Referendum 1980?', 'Rund 60 Prozent', ['Rund 51 Prozent', 'Rund 80 Prozent', 'Rund 30 Prozent']],
              ['Welches Jahr brachte Bill 101?', '1977', ['1969', '1974', '1988']],
              ['Wer verübte in Québec Bombenanschläge?', 'Die FLQ', ['Die Parti Québécois', 'Die Mounties', 'Die Kirche']],
              ['Welche Wahl gewann René Lévesque?', 'Die Wahl in Québec 1976', ['Die Bundeswahl 1980', 'Die Wahl zum Bürgermeister', 'Keine']],
              ['Welche Stadt war Gastgeber der Olympischen Spiele 1976?', 'Montréal', ['Calgary', 'Toronto', 'Québec']],
              ['Was war vor 1982 nötig, um die Verfassung zu ändern?', 'Die Zustimmung des britischen Parlaments', ['Eine Volksabstimmung in Québec', 'Die Zustimmung der USA', 'Nichts']],
            ],
          },
        },
      ],
    },
  ],
};
