import type { Epoch } from '../types';

export const E4: Epoch = {
  id: 'heute',
  name: 'Kanada heute',
  period: 'seit 1982',
  events: [
    {
      id: 'gegenwart',
      title: 'Ahornblatt, Québec und Versöhnung',
      date: 'seit 1982',
      text: [
        'Nach 1982 rang Kanada um die Stellung Québecs, das 1995 nur knapp in Kanada blieb. Mit Nunavut erhielten die Inuit 1999 ein eigenes Territorium. Heute ist Kanada ein vielfältiges Einwanderungsland, das sich seiner Kolonialgeschichte gegenüber den Indigenen stellt.',
      ],
      subtopics: [
        {
          id: 'referendum-nunavut',
          title: 'Freihandel, Referendum 1995 und Nunavut',
          date: '1982–2005',
          text: [
            'Premierminister Brian Mulroney (1984–1993) versuchte, Québec mit dem Meech-Lake-Abkommen (1987) als „besondere Gesellschaft“ anzuerkennen und so für die Verfassung zu gewinnen. Das Abkommen scheiterte 1990, als die Provinzen Manitoba und Neufundland es nicht billigten; in Manitoba blockierte der Cree-Abgeordnete Elijah Harper die Abstimmung mit einer Adlerfeder in der Hand. Auch das Charlottetown-Abkommen fiel 1992 in einer Volksabstimmung durch.',
            '1988 schloss Kanada ein Freihandelsabkommen mit den USA, 1994 kam mit Mexiko die Nordamerikanische Freihandelszone (NAFTA) hinzu. 1990 kam es in Oka bei Montréal zu einer 78 Tage dauernden Konfrontation zwischen Mohawk und Polizei und Armee um ein Stück Land, auf dem ein Golfplatz erweitert werden sollte.',
            'Am 30. Oktober 1995 stimmte Québec erneut über die Unabhängigkeit ab. Das Ergebnis war denkbar knapp: 50,58 Prozent stimmten mit „Nein“ und 49,42 Prozent mit „Ja“. Später entschied der Oberste Gerichtshof, dass sich Québec nicht einseitig abspalten darf, und das „Klarheitsgesetz“ von 2000 legte Regeln für künftige Referenden fest.',
            'Am 1. April 1999 entstand im Nordosten aus einem Teil der Nordwest-Territorien das Territorium Nunavut („unser Land“ auf Inuktitut). Hier sind rund 85 Prozent der Bewohner Inuit, und Inuktitut ist eine Amtssprache. Hauptstadt ist Iqaluit.',
            '2003 verweigerte Kanada unter Premierminister Jean Chrétien die Teilnahme am Irakkrieg, kämpfte aber von 2001 bis 2014 in Afghanistan. 2005 erlaubte Kanada als viertes Land der Welt die gleichgeschlechtliche Ehe.',
          ],
          quiz: {
            leicht: [
              ['Welcher Premierminister versuchte, Québec für die Verfassung zu gewinnen?', 'Brian Mulroney', ['Pierre Trudeau', 'Justin Trudeau', 'Stephen Harper']],
              ['Wie hieß das Abkommen von 1987?', 'Meech-Lake-Abkommen', ['Charlottetown-Abkommen', 'NAFTA', 'Kyoto-Protokoll']],
              ['Als was sollte Québec anerkannt werden?', 'Als besondere Gesellschaft', ['Als eigener Staat', 'Als Teil Frankreichs', 'Als Territorium']],
              ['Hatte das Meech-Lake-Abkommen Erfolg?', 'Nein, es scheiterte', ['Ja', 'Teilweise', 'Es wurde nie verhandelt']],
              ['Was hielt Elijah Harper bei seiner Blockade in der Hand?', 'Eine Adlerfeder', ['Ein Gewehr', 'Ein Ahornblatt', 'Eine Bibel']],
              ['Welchem Volk gehörte Elijah Harper an?', 'Den Cree', ['Den Inuit', 'Den Haida', 'Den Mohawk']],
              ['Mit welchem Land schloss Kanada 1988 ein Freihandelsabkommen?', 'Mit den USA', ['Mit Mexiko', 'Mit Großbritannien', 'Mit China']],
              ['Wie hieß die Freihandelszone mit den USA und Mexiko?', 'NAFTA', ['EU', 'ASEAN', 'Mercosur']],
              ['Wo kam es 1990 zur Konfrontation mit den Mohawk?', 'In Oka', ['In Toronto', 'In Vancouver', 'In Halifax']],
              ['Was sollte auf dem umstrittenen Land in Oka erweitert werden?', 'Ein Golfplatz', ['Ein Flughafen', 'Eine Autobahn', 'Ein Stadion']],
              ['Wann stimmte Québec zum zweiten Mal über die Unabhängigkeit ab?', 'Am 30. Oktober 1995', ['1980', '1982', '2000']],
              ['Wie war das Ergebnis 1995?', 'Denkbar knapp für das Nein', ['Klar für die Unabhängigkeit', 'Klar dagegen', 'Unentschieden']],
              ['Wie viele stimmten 1995 mit Nein?', '50,58 Prozent', ['60 Prozent', '40 Prozent', '75 Prozent']],
              ['Welches Territorium entstand 1999?', 'Nunavut', ['Yukon', 'Nordwest-Territorien', 'Labrador']],
              ['Was bedeutet „Nunavut“?', 'Unser Land', ['Kaltes Land', 'Großes Eis', 'Weißer Bär']],
              ['Wer bildet die Mehrheit in Nunavut?', 'Die Inuit', ['Die Métis', 'Die Franzosen', 'Die Engländer']],
              ['Wie heißt die Hauptstadt Nunavuts?', 'Iqaluit', ['Whitehorse', 'Yellowknife', 'Dawson']],
              ['An welchem Krieg nahm Kanada 2003 nicht teil?', 'Am Irakkrieg', ['Am Afghanistankrieg', 'Am Zweiten Weltkrieg', 'Am Koreakrieg']],
              ['Welcher Premierminister lehnte 2003 die Teilnahme am Irakkrieg ab?', 'Jean Chrétien', ['Brian Mulroney', 'Stephen Harper', 'Pierre Trudeau']],
              ['Wann erlaubte Kanada die gleichgeschlechtliche Ehe?', '2005', ['1995', '2015', '2020']],
            ],
            mittel: [
              ['Wann war Brian Mulroney Premierminister?', '1984–1993', ['1968–1984', '1993–2003', '2006–2015']],
              ['Wann scheiterte das Meech-Lake-Abkommen?', '1990', ['1987', '1992', '1995']],
              ['Welche Provinzen billigten Meech Lake nicht?', 'Manitoba und Neufundland', ['Ontario und Québec', 'Alberta und British Columbia', 'Nova Scotia und Yukon']],
              ['In welcher Provinz blockierte Elijah Harper die Abstimmung?', 'In Manitoba', ['In Québec', 'In Ontario', 'In Neufundland']],
              ['Welches Abkommen fiel 1992 in einer Volksabstimmung durch?', 'Das Charlottetown-Abkommen', ['Das Meech-Lake-Abkommen', 'NAFTA', 'Das Klarheitsgesetz']],
              ['Wann kam Mexiko zur Freihandelszone hinzu?', '1994', ['1988', '2000', '1982']],
              ['Wie lange dauerte die Konfrontation in Oka?', '78 Tage', ['7 Tage', '78 Stunden', '7 Monate']],
              ['Welches Volk stand in Oka der Polizei gegenüber?', 'Die Mohawk', ['Die Inuit', 'Die Cree', 'Die Métis']],
              ['Wann war die Oka-Krise?', '1990', ['1970', '1995', '1982']],
              ['Wie viele stimmten 1995 mit Ja?', '49,42 Prozent', ['40 Prozent', '30 Prozent', '55 Prozent']],
              ['Was entschied der Oberste Gerichtshof später?', 'Dass Québec sich nicht einseitig abspalten darf', ['Dass Québec sofort unabhängig ist', 'Dass Québec zu Frankreich gehört', 'Dass Referenden verboten sind']],
              ['Was legte das Klarheitsgesetz fest?', 'Regeln für künftige Referenden', ['Die Unabhängigkeit Québecs', 'Neue Steuern', 'Eine neue Flagge']],
              ['Wann wurde das Klarheitsgesetz beschlossen?', '2000', ['1995', '1982', '2005']],
              ['Aus welchem Gebiet entstand Nunavut?', 'Aus einem Teil der Nordwest-Territorien', ['Aus Québec', 'Aus dem Yukon', 'Aus Manitoba']],
              ['Wann entstand Nunavut?', 'Am 1. April 1999', ['Am 1. Juli 1999', 'Am 1. April 1949', 'Am 30. Oktober 1995']],
              ['Wie hoch ist der Anteil der Inuit in Nunavut?', 'Rund 85 Prozent', ['Rund 15 Prozent', 'Rund 50 Prozent', 'Rund 5 Prozent']],
              ['Welche Sprache ist in Nunavut Amtssprache?', 'Inuktitut', ['Cree', 'Mohawk', 'Gälisch']],
              ['In welchem Land kämpfte Kanada von 2001 bis 2014?', 'In Afghanistan', ['Im Irak', 'In Vietnam', 'In Korea']],
              ['Als wievieltes Land erlaubte Kanada die gleichgeschlechtliche Ehe?', 'Als viertes', ['Als erstes', 'Als zehntes', 'Als zwanzigstes']],
              ['Wo liegt Nunavut?', 'Im Nordosten', ['Im Südwesten', 'An der Pazifikküste', 'Bei Toronto']],
            ],
            schwer: [
              ['Was bedeutete „besondere Gesellschaft“ für Québec?', 'Eine Anerkennung seiner Eigenart', ['Die Unabhängigkeit', 'Den Ausschluss aus Kanada', 'Einen Sonderstatus als Territorium']],
              ['Welches Abkommen folgte nach Meech Lake und scheiterte 1992?', 'Charlottetown', ['Ottawa', 'Kyoto', 'Montréal']],
              ['Welches Symbol nutzte Elijah Harper?', 'Eine Adlerfeder', ['Eine Friedenspfeife', 'Ein Totem', 'Einen Mokassin']],
              ['Wie knapp war das Referendum 1995 ungefähr?', 'Rund ein Prozentpunkt Unterschied', ['Zehn Prozentpunkte', 'Zwanzig Prozentpunkte', 'Eine Stimme']],
              ['Welches Gesetz regelt künftige Referenden in Québec?', 'Das Klarheitsgesetz', ['Bill 101', 'Der BNA Act', 'Die Charta der Rechte']],
              ['Was ist Iqaluit?', 'Die Hauptstadt Nunavuts', ['Ein Inuit-Wort für Eis', 'Ein Berg', 'Ein Fluss in Québec']],
              ['Welches Freihandelsabkommen verband Kanada, USA und Mexiko?', 'NAFTA', ['GATT', 'CETA', 'TPP']],
              ['Welche Krise 1990 betraf Indigene und Landrechte?', 'Die Oka-Krise', ['Die Oktoberkrise', 'Die Wehrpflichtkrise', 'Die Suezkrise']],
              ['Welche Sprache sprechen viele Bewohner Nunavuts?', 'Inuktitut', ['Ojibwe', 'Mohawk', 'Haida']],
              ['Welcher Premierminister regierte 1995 während des Referendums?', 'Jean Chrétien', ['Brian Mulroney', 'Pierre Trudeau', 'Kim Campbell']],
              ['Wann schloss Kanada das Freihandelsabkommen mit den USA?', '1988', ['1994', '1982', '2000']],
              ['Warum lehnte Kanada 2003 den Irakkrieg ab?', 'Es verweigerte die Teilnahme', ['Es hatte keine Armee', 'Es war mit dem Irak verbündet', 'Es wurde nicht gefragt']],
              ['Wie lange kämpfte Kanada in Afghanistan?', 'Von 2001 bis 2014', ['Von 2003 bis 2005', 'Von 1990 bis 1991', 'Von 2014 bis 2021']],
              ['Was entschied der Oberste Gerichtshof zur Abspaltung?', 'Nicht einseitig erlaubt', ['Jederzeit erlaubt', 'Verboten für immer', 'Nur mit Zustimmung der USA']],
              ['Welche Volksgruppe erhielt 1999 ein eigenes Territorium?', 'Die Inuit', ['Die Métis', 'Die Cree', 'Die Akadier']],
              ['Wann scheiterte Meech Lake endgültig?', '1990', ['1987', '1988', '1995']],
              ['Wie viele Tage blockierten Mohawk und Behörden sich in Oka?', '78', ['7', '780', '17']],
              ['Was symbolisiert das Ergebnis 1995 für Kanada?', 'Wie knapp Québec in Kanada blieb', ['Dass Québec unabhängig wurde', 'Dass alle für Kanada waren', 'Dass niemand abstimmte']],
              ['Welche Provinz blockierte Meech Lake außer Manitoba?', 'Neufundland', ['Ontario', 'Saskatchewan', 'Québec']],
              ['In welchem Jahr erlaubte Kanada die Ehe für alle?', '2005', ['2001', '2010', '1999']],
            ],
          },
        },
        {
          id: 'versoehnung-gegenwart',
          title: 'Versöhnung, Vielfalt und Gegenwart',
          date: 'seit 2006',
          text: [
            '2008 entschuldigte sich Premierminister Stephen Harper im Parlament offiziell bei den Überlebenden der Residential Schools. Von 2008 bis 2015 untersuchte eine Wahrheits- und Versöhnungskommission das Unrecht und sprach von „kulturellem Völkermord“; sie stellte 94 Handlungsaufforderungen auf. 2021 entdeckte man bei ehemaligen Schulen, etwa in Kamloops, Hinweise auf Hunderte nicht gekennzeichnete Gräber. Seit 2021 ist der 30. September ein Gedenktag, der „Tag der Wahrheit und Versöhnung“, an dem viele orange T-Shirts tragen.',
            '2015 wurde Justin Trudeau, der Sohn von Pierre Trudeau, Premierminister. Er stellte ein Kabinett mit gleich vielen Frauen und Männern zusammen und erklärte es mit den Worten „Weil wir 2015 haben“. 2018 legalisierte Kanada nach Uruguay als zweites Land der Welt Cannabis. Kanada nahm in den Jahren nach 2015 Zehntausende syrische Flüchtlinge auf.',
            'Kanada ist ein Einwanderungsland: Rund ein Viertel der Bevölkerung wurde im Ausland geboren, und Städte wie Toronto gehören zu den vielfältigsten der Welt. Über 40 Millionen Menschen leben heute in Kanada, die meisten in einem schmalen Streifen nahe der Grenze zu den USA.',
            'Kanada leidet unter dem Klimawandel: 2023 brannten bei Waldbränden mehr Flächen als je zuvor gemessen; der Rauch zog bis nach New York und Europa. Gleichzeitig ist das Land ein großer Produzent von Öl aus Ölsanden.',
            '2025 drohte US-Präsident Donald Trump mit hohen Zöllen und spottete, Kanada solle der „51. Bundesstaat“ der USA werden; viele Kanadier boykottierten daraufhin amerikanische Waren. Im März 2025 folgte Mark Carney, früher Chef der Bank of Canada und der Bank of England, Justin Trudeau als Premierminister und gewann im April die Wahl. Staatsoberhaupt ist seit 2022 König Charles III.',
          ],
          quiz: {
            leicht: [
              ['Welcher Premierminister entschuldigte sich 2008 bei Überlebenden der Residential Schools?', 'Stephen Harper', ['Justin Trudeau', 'Jean Chrétien', 'Brian Mulroney']],
              ['Welche Kommission untersuchte das Unrecht der Residential Schools?', 'Die Wahrheits- und Versöhnungskommission', ['Die Warren-Kommission', 'Die Durham-Kommission', 'Die UNO-Kommission']],
              ['Wie nannte die Kommission das Unrecht?', 'Kulturellen Völkermord', ['Einen Unfall', 'Eine Bildungsreform', 'Einen Erfolg']],
              ['Wie viele Handlungsaufforderungen stellte die Kommission auf?', '94', ['9', '940', '4']],
              ['Was entdeckte man 2021 bei ehemaligen Schulen?', 'Hinweise auf nicht gekennzeichnete Gräber', ['Gold', 'Alte Bücher', 'Ein Museum']],
              ['Welcher Tag ist seit 2021 der Tag der Wahrheit und Versöhnung?', 'Der 30. September', ['Der 1. Juli', 'Der 11. November', 'Der 21. Juni']],
              ['Welche Farbe haben die T-Shirts am Tag der Versöhnung?', 'Orange', ['Rot', 'Grün', 'Blau']],
              ['Wessen Sohn ist Justin Trudeau?', 'Pierre Trudeaus', ['Brian Mulroneys', 'Jean Chrétiens', 'Lester Pearsons']],
              ['Wann wurde Justin Trudeau Premierminister?', '2015', ['2008', '2019', '2025']],
              ['Wie war Trudeaus erstes Kabinett zusammengesetzt?', 'Mit gleich vielen Frauen und Männern', ['Nur mit Männern', 'Nur mit Frauen', 'Nur mit Québecern']],
              ['Was legalisierte Kanada 2018?', 'Cannabis', ['Die Monarchie', 'Die Todesstrafe', 'Das Glücksspiel']],
              ['Aus welchem Land nahm Kanada nach 2015 Zehntausende Flüchtlinge auf?', 'Aus Syrien', ['Aus Mexiko', 'Aus Japan', 'Aus Australien']],
              ['Welcher Anteil der Kanadier wurde im Ausland geboren?', 'Rund ein Viertel', ['Fast niemand', 'Die Hälfte', 'Drei Viertel']],
              ['Welche Stadt gehört zu den vielfältigsten der Welt?', 'Toronto', ['Iqaluit', 'Regina', 'Charlottetown']],
              ['Wie viele Menschen leben heute etwa in Kanada?', 'Über 40 Millionen', ['Rund 4 Millionen', 'Rund 400 Millionen', 'Rund 10 Millionen']],
              ['Wo leben die meisten Kanadier?', 'Nahe der Grenze zu den USA', ['Im hohen Norden', 'In Nunavut', 'Auf Inseln im Pazifik']],
              ['Was brannte 2023 in Kanada auf Rekordflächen?', 'Wälder', ['Städte', 'Ölfelder', 'Gletscher']],
              ['Wie nannte Donald Trump Kanada spöttisch?', '„51. Bundesstaat“', ['„Kleiner Bruder“', '„Nordmexiko“', '„Eisland“']],
              ['Wer wurde im März 2025 Premierminister?', 'Mark Carney', ['Pierre Poilievre', 'Stephen Harper', 'Chrystia Freeland']],
              ['Wer ist seit 2022 Staatsoberhaupt Kanadas?', 'König Charles III.', ['Königin Elizabeth II.', 'Justin Trudeau', 'Der Generalgouverneur']],
            ],
            mittel: [
              ['Wann entschuldigte sich Harper?', '2008', ['2015', '2021', '1996']],
              ['Wann arbeitete die Wahrheits- und Versöhnungskommission?', '2008–2015', ['1996–2000', '2015–2021', '1982–1990']],
              ['Wo fand man 2021 Hinweise auf Hunderte Gräber?', 'Unter anderem in Kamloops', ['In Ottawa', 'In Québec', 'In Halifax']],
              ['Wann wurde der Tag der Wahrheit und Versöhnung eingeführt?', '2021', ['2008', '2015', '1996']],
              ['Mit welchen Worten begründete Justin Trudeau sein Kabinett?', '„Weil wir 2015 haben“', ['„Weil die Frauen es verlangen“', '„Weil Québec es will“', '„Weil es Gesetz ist“']],
              ['Als wievieltes Land legalisierte Kanada Cannabis?', 'Als zweites', ['Als erstes', 'Als zehntes', 'Als fünfzigstes']],
              ['Wie viele syrische Flüchtlinge nahm Kanada auf?', 'Zehntausende', ['Einige Dutzend', 'Einige Hundert', 'Millionen']],
              ['Wie wird Kanada wegen seiner Zuwanderung beschrieben?', 'Als Einwanderungsland', ['Als Auswanderungsland', 'Als geschlossenes Land', 'Als Insel']],
              ['Wohin zog 2023 der Rauch der Waldbrände?', 'Bis nach New York und Europa', ['Nur bis Toronto', 'Bis nach Australien', 'Gar nicht weit']],
              ['Woraus produziert Kanada viel Öl?', 'Aus Ölsanden', ['Aus Meerwasser', 'Aus Holz', 'Aus Gletschern']],
              ['Womit drohte Trump 2025?', 'Mit hohen Zöllen', ['Mit Krieg', 'Mit einer Mauer', 'Mit einem Einreiseverbot für alle Kanadier']],
              ['Wie reagierten viele Kanadier auf Trumps Drohungen?', 'Sie boykottierten amerikanische Waren', ['Sie zogen in die USA', 'Sie wählten Trump', 'Gar nicht']],
              ['Was war Mark Carney früher?', 'Chef der Bank of Canada und der Bank of England', ['Eishockeyspieler', 'General', 'Schauspieler']],
              ['Wann gewann Mark Carney die Wahl?', 'Im April 2025', ['Im März 2025', 'Im Oktober 2019', 'Im Jahr 2015']],
              ['Wem folgte Carney als Premierminister?', 'Justin Trudeau', ['Stephen Harper', 'Jean Chrétien', 'Pierre Trudeau']],
              ['Wann wurde Charles III. König Kanadas?', '2022', ['2015', '1982', '2025']],
              ['Welches Thema beschreibt der „kulturelle Völkermord“?', 'Die Auslöschung indigener Kulturen durch Residential Schools', ['Den Krieg 1812', 'Die Akadier-Vertreibung', 'Die Oktoberkrise']],
              ['Welcher Teil der Welt ist in Toronto vertreten?', 'Menschen aus aller Welt', ['Nur Engländer', 'Nur Franzosen', 'Nur Inuit']],
              ['Welches Umweltproblem traf Kanada 2023 besonders?', 'Rekord-Waldbrände', ['Ein Tsunami', 'Ein Vulkanausbruch', 'Eine Dürre in Nunavut']],
              ['Welche Rolle hat der König in Kanada?', 'Er ist Staatsoberhaupt', ['Er ist Premierminister', 'Er hat keine Rolle', 'Er ist Präsident der USA']],
            ],
            schwer: [
              ['Was trugen viele Menschen am Tag der Wahrheit und Versöhnung?', 'Orange T-Shirts', ['Rote Mohnblumen', 'Grüne Schals', 'Weiße Federn']],
              ['Welche Stadt in British Columbia ist mit den Gräberfunden 2021 verbunden?', 'Kamloops', ['Victoria', 'Kelowna', 'Prince George']],
              ['Wie viele Handlungsaufforderungen hatte die Kommission?', '94', ['49', '194', '24']],
              ['Welcher Premierminister ist der Sohn eines früheren Premierministers?', 'Justin Trudeau', ['Stephen Harper', 'Mark Carney', 'Jean Chrétien']],
              ['Welches Land legalisierte Cannabis vor Kanada?', 'Uruguay', ['Die USA', 'Deutschland', 'Mexiko']],
              ['Wie hoch ist die Einwohnerzahl Kanadas heute etwa?', 'Über 40 Millionen', ['Über 60 Millionen', 'Unter 20 Millionen', 'Über 100 Millionen']],
              ['Was erlebte Kanada 2023 bei Waldbränden?', 'Die größte je gemessene verbrannte Fläche', ['Keine Brände', 'Nur kleine Brände', 'Brände nur in Nunavut']],
              ['Welche Zentralbanken leitete Mark Carney?', 'Die Bank of Canada und die Bank of England', ['Die US-Notenbank', 'Die EZB', 'Die Weltbank']],
              ['Wann folgte Carney auf Trudeau?', 'Im März 2025', ['Im April 2025', 'Im Jahr 2023', 'Im Jahr 2021']],
              ['Welcher US-Präsident drohte 2025 mit Zöllen gegen Kanada?', 'Donald Trump', ['Joe Biden', 'Barack Obama', 'George W. Bush']],
              ['Welche Bezeichnung zeigte Trumps Spott über Kanada?', '51. Bundesstaat', ['Neuengland', 'Nordterritorium', 'Kolonie Kanada']],
              ['Wie lange arbeitete die Wahrheits- und Versöhnungskommission?', 'Rund sieben Jahre', ['Ein Jahr', 'Zwanzig Jahre', 'Einen Monat']],
              ['Was ist am Kabinett von 2015 besonders?', 'Gleich viele Frauen und Männer', ['Nur Indigene', 'Nur Junge unter 30', 'Nur Québecer']],
              ['Woher kamen viele Flüchtlinge, die Kanada nach 2015 aufnahm?', 'Aus Syrien', ['Aus Venezuela', 'Aus Neuseeland', 'Aus Island']],
              ['Wer bildete nach der Wahl 2025 die Regierung?', 'Mark Carney', ['Pierre Poilievre', 'Jagmeet Singh', 'Justin Trudeau']],
              ['Welche Stadt in den USA war 2023 vom Rauch der kanadischen Brände betroffen?', 'New York', ['Miami', 'Los Angeles', 'Honolulu']],
              ['Welcher Tag dient dem Gedenken an die Opfer der Residential Schools?', 'Der 30. September', ['Der 1. April', 'Der 24. Juni', 'Der 31. Oktober']],
              ['Wofür entschuldigte sich Harper?', 'Für die Residential Schools', ['Für den Krieg 1812', 'Für die Oktoberkrise', 'Für NAFTA']],
              ['Welcher Monarch folgte 2022 Elizabeth II.?', 'Charles III.', ['William', 'Edward VIII.', 'George VI.']],
              ['Welcher Anteil der Kanadier ist im Ausland geboren ungefähr?', 'Ein Viertel', ['Ein Zehntel', 'Die Hälfte', 'Neun Zehntel']],
            ],
          },
        },
      ],
    },
  ],
};
