import type { Epoch } from '../types';

export const E3: Epoch = {
  id: 'renaissance',
  name: 'Renaissance und Fremdherrschaft',
  period: '1400–1796',
  events: [
    {
      id: 'renaissance',
      title: 'Die Renaissance',
      date: '1400–1530',
      text: [
        'Im 15. Jahrhundert wurde Italien zur Wiege der Renaissance: In Florenz und Rom schufen Künstler wie Leonardo, Michelangelo und Raffael Werke für die Ewigkeit. Politisch aber blieb Italien zersplittert und wurde zum Schlachtfeld fremder Mächte.',
      ],
      subtopics: [
        {
          id: 'medici-florenz',
          title: 'Die Medici und Florenz',
          date: '1400–1498',
          text: [
            '„Renaissance“ heißt „Wiedergeburt“: Gelehrte entdeckten die Kunst und Schriften der Antike neu und stellten den Menschen in den Mittelpunkt („Humanismus“). Nach dem Fall Konstantinopels 1453 brachten griechische Gelehrte alte Handschriften nach Italien. Florenz mit seinen reichen Kaufleuten und Bankiers wurde zum Zentrum der neuen Bewegung.',
            'Die Bankiersfamilie Medici beherrschte Florenz ab 1434 ohne offizielles Amt. Cosimo de’ Medici („der Alte“) machte die Medici-Bank zur größten Europas, war Bankier des Papstes und förderte Künstler und Gelehrte. Sein Enkel Lorenzo „il Magnifico“ (der Prächtige, 1449–1492) war selbst Dichter und holte den jungen Michelangelo in seinen Haushalt.',
            'Der Baumeister Filippo Brunelleschi vollendete 1436 die riesige Kuppel des Florentiner Doms, die ohne Gerüst vom Boden aus gebaut wurde – sie ist bis heute die größte Ziegelkuppel der Welt. Brunelleschi entdeckte auch die Zentralperspektive, mit der Maler räumliche Tiefe darstellen konnten. Der Bildhauer Donatello schuf mit seinem bronzenen David die erste freistehende Aktfigur seit der Antike.',
            'Sandro Botticelli malte für die Medici „Die Geburt der Venus“ und „Den Frühling“ (Primavera). 1478 versuchte die rivalisierende Familie Pazzi in der „Pazzi-Verschwörung“, die Medici während der Ostermesse im Dom zu ermorden. Lorenzos Bruder Giuliano starb, Lorenzo entkam verletzt; die Verschwörer wurden gehängt.',
            'Nach Lorenzos Tod predigte der Dominikanermönch Girolamo Savonarola gegen Luxus und Sittenverfall. Die Medici wurden 1494 vertrieben. Im „Fegefeuer der Eitelkeiten“ 1497 verbrannten seine Anhänger Spiegel, Schmuck, Bücher und Gemälde – angeblich warf sogar Botticelli eigene Bilder ins Feuer. 1498 wurde Savonarola selbst auf demselben Platz, der Piazza della Signoria, gehängt und verbrannt. Die Medici kehrten später zurück, stellten zwei Päpste und wurden Großherzöge der Toskana.',
          ],
          quiz: {
            leicht: [
              ['Was bedeutet „Renaissance“?', 'Wiedergeburt', ['Neuzeit', 'Aufklärung', 'Erneuerung der Kirche']],
              ['Welche Zeit entdeckten die Gelehrten neu?', 'Die Antike', ['Die Steinzeit', 'Das Mittelalter', 'Die Zukunft']],
              ['Wie heißt die Bewegung, die den Menschen in den Mittelpunkt stellte?', 'Humanismus', ['Barock', 'Romantik', 'Scholastik']],
              ['Welche Stadt war das Zentrum der Renaissance?', 'Florenz', ['Venedig', 'Neapel', 'Mailand']],
              ['Welche Bankiersfamilie beherrschte Florenz?', 'Die Medici', ['Die Pazzi', 'Die Borgia', 'Die Sforza']],
              ['Wie nannte man Lorenzo de’ Medici?', '„Il Magnifico“ (der Prächtige)', ['„Der Alte“', '„Der Große“', '„Der Grausame“']],
              ['Welchen jungen Künstler holte Lorenzo in sein Haus?', 'Michelangelo', ['Leonardo', 'Raffael', 'Botticelli']],
              ['Wer baute die Kuppel des Florentiner Doms?', 'Filippo Brunelleschi', ['Michelangelo', 'Donatello', 'Bramante']],
              ['Was ist die Domkuppel von Florenz bis heute?', 'Die größte Ziegelkuppel der Welt', ['Die höchste Kirche der Welt', 'Eine Ruine', 'Ein Gefängnis']],
              ['Was entdeckte Brunelleschi für die Malerei?', 'Die Zentralperspektive', ['Die Ölfarbe', 'Den Buchdruck', 'Die Fotografie']],
              ['Welchen David schuf Donatello?', 'Einen bronzenen David', ['Einen marmornen David', 'Einen goldenen David', 'Einen hölzernen David']],
              ['Wer malte „Die Geburt der Venus“?', 'Botticelli', ['Leonardo', 'Raffael', 'Tizian']],
              ['Welche Familie verschwor sich 1478 gegen die Medici?', 'Die Pazzi', ['Die Borgia', 'Die Sforza', 'Die Este']],
              ['Wo griffen die Verschwörer die Medici an?', 'Während der Ostermesse im Dom', ['Auf dem Marktplatz', 'Auf der Jagd', 'Beim Bankett']],
              ['Welcher Medici starb 1478?', 'Giuliano', ['Lorenzo', 'Cosimo', 'Piero']],
              ['Welcher Mönch predigte gegen Luxus?', 'Savonarola', ['Franz von Assisi', 'Luther', 'Thomas von Aquin']],
              ['Wann wurden die Medici vertrieben?', '1494', ['1434', '1478', '1530']],
              ['Was verbrannte man im „Fegefeuer der Eitelkeiten“?', 'Spiegel, Schmuck, Bücher und Gemälde', ['Ketzer', 'Häuser der Medici', 'Schiffe']],
              ['Was geschah 1498 mit Savonarola?', 'Er wurde gehängt und verbrannt', ['Er wurde Papst', 'Er floh nach Spanien', 'Er wurde Herzog']],
              ['Was wurden die Medici später?', 'Großherzöge der Toskana', ['Könige von Frankreich', 'Dogen von Venedig', 'Kaiser']],
            ],
            mittel: [
              ['Was brachten griechische Gelehrte nach 1453 nach Italien?', 'Alte Handschriften', ['Kanonen', 'Gewürze', 'Seide']],
              ['Welches Ereignis trieb griechische Gelehrte nach Italien?', 'Der Fall Konstantinopels 1453', ['Die Entdeckung Amerikas', 'Die Pest', 'Der Vierte Kreuzzug']],
              ['Ab wann beherrschten die Medici Florenz?', '1434', ['1494', '1252', '1530']],
              ['Mit welchem Amt herrschten die Medici zunächst?', 'Ohne offizielles Amt', ['Als Könige', 'Als Dogen', 'Als Bischöfe']],
              ['Wie nannte man Cosimo de’ Medici?', '„Der Alte“', ['„Der Prächtige“', '„Der Rote“', '„Der Kühne“']],
              ['Wessen Bankier war Cosimo?', 'Des Papstes', ['Des Sultans', 'Des Kaisers von China', 'Venedigs']],
              ['Wie war Lorenzo mit Cosimo verwandt?', 'Enkel', ['Sohn', 'Bruder', 'Neffe']],
              ['Wann lebte Lorenzo il Magnifico?', '1449–1492', ['1389–1464', '1475–1564', '1265–1321']],
              ['Was war Lorenzo neben Politiker?', 'Dichter', ['Maler', 'Admiral', 'Bischof']],
              ['Wann vollendete Brunelleschi die Domkuppel?', '1436', ['1492', '1504', '1348']],
              ['Wie wurde die Domkuppel gebaut?', 'Ohne Gerüst vom Boden aus', ['Mit Hilfe von Kränen aus Stahl', 'Aus Holz', 'In Rom vorgefertigt']],
              ['Was war Donatellos David?', 'Die erste freistehende Aktfigur seit der Antike', ['Ein Gemälde', 'Eine Kirche', 'Ein Relief am Dom']],
              ['Welches weitere Werk malte Botticelli?', '„Der Frühling“ (Primavera)', ['„Das Abendmahl“', '„Die Schule von Athen“', '„Mona Lisa“']],
              ['Wann war die Pazzi-Verschwörung?', '1478', ['1434', '1494', '1498']],
              ['Was geschah mit den Pazzi-Verschwörern?', 'Sie wurden gehängt', ['Sie übernahmen Florenz', 'Sie flohen nach Venedig', 'Sie wurden begnadigt']],
              ['Welchem Orden gehörte Savonarola an?', 'Den Dominikanern', ['Den Franziskanern', 'Den Jesuiten', 'Den Benediktinern']],
              ['Wann war das „Fegefeuer der Eitelkeiten“?', '1497', ['1478', '1492', '1527']],
              ['Welcher Maler warf angeblich eigene Bilder ins Feuer?', 'Botticelli', ['Leonardo', 'Michelangelo', 'Raffael']],
              ['Auf welchem Platz starb Savonarola?', 'Piazza della Signoria', ['Petersplatz', 'Markusplatz', 'Piazza Navona']],
              ['Wie viele Päpste stellten die Medici?', 'Zwei', ['Keinen', 'Zehn', 'Einen']],
            ],
            schwer: [
              ['Was war Brunelleschis Beruf?', 'Baumeister', ['Mönch', 'Bankier', 'Dichter']],
              ['Was ermöglichte die Zentralperspektive?', 'Räumliche Tiefe in Bildern', ['Farbige Fenster', 'Größere Kirchen', 'Schnelleres Malen']],
              ['Wie entkam Lorenzo der Pazzi-Verschwörung?', 'Verletzt', ['Unverletzt im Ausland', 'Gar nicht, er starb', 'Als Mönch verkleidet']],
              ['Wann wurde Savonarola hingerichtet?', '1498', ['1494', '1497', '1478']],
              ['Was ironisch am Ort von Savonarolas Tod?', 'Es war derselbe Platz wie das Fegefeuer der Eitelkeiten', ['Es war der Dom', 'Es war in Rom', 'Es war im Gefängnis der Medici']],
              ['Wogegen predigte Savonarola?', 'Gegen Luxus und Sittenverfall', ['Gegen die Kunst der Antike', 'Gegen die Pest', 'Gegen die Türken']],
              ['Was machte Cosimo aus der Medici-Bank?', 'Die größte Europas', ['Eine Kirche', 'Eine Universität', 'Eine kleine Wechselstube']],
              ['Wann starb Lorenzo il Magnifico?', '1492', ['1478', '1498', '1464']],
              ['Für wen malte Botticelli seine berühmten Bilder?', 'Für die Medici', ['Für den Papst in Avignon', 'Für den König von Frankreich', 'Für Venedig']],
              ['Was förderte Cosimo?', 'Künstler und Gelehrte', ['Nur Soldaten', 'Seefahrer', 'Ketzer']],
              ['Wer starb bei der Pazzi-Verschwörung?', 'Giuliano de’ Medici', ['Lorenzo de’ Medici', 'Cosimo de’ Medici', 'Savonarola']],
              ['Was ist Humanismus?', 'Eine Bewegung, die den Menschen in den Mittelpunkt stellt', ['Eine Kirche', 'Eine Kunst der Gotik', 'Eine Bankform']],
              ['Was war Florenz vor allem wirtschaftlich?', 'Eine Stadt reicher Kaufleute und Bankiers', ['Ein Hafen', 'Eine Bergbaustadt', 'Ein Bauerndorf']],
              ['Welcher Familie wurde Florenz 1494 genommen?', 'Den Medici', ['Den Pazzi', 'Den Sforza', 'Den Borgia']],
              ['Welches Material verwendete Donatello für David?', 'Bronze', ['Marmor', 'Holz', 'Gold']],
              ['Wofür steht „Primavera“?', 'Frühling', ['Venus', 'Prinzessin', 'Erste Liebe']],
              ['Woraus besteht die Florentiner Domkuppel?', 'Aus Ziegeln', ['Aus Glas', 'Aus Holz', 'Aus Beton']],
              ['Was folgte auf Lorenzos Tod?', 'Savonarolas Predigten und die Vertreibung der Medici', ['Ein goldenes Zeitalter der Medici', 'Die Einigung Italiens', 'Die Pest']],
              ['Welche Rolle hatten die Medici in der Kirche?', 'Sie stellten zwei Päpste', ['Keine', 'Sie gründeten die Jesuiten', 'Sie waren Ketzer']],
              ['Welches Ereignis verbindet sich mit 1453?', 'Fall Konstantinopels', ['Tod Lorenzos', 'Bau der Domkuppel', 'Pazzi-Verschwörung']],
            ],
          },
        },
        {
          id: 'kuenstler',
          title: 'Leonardo, Michelangelo und Raffael',
          date: '1452–1564',
          text: [
            'Leonardo da Vinci (1452–1519) aus dem Dorf Vinci bei Florenz war Maler, Bildhauer, Ingenieur, Erfinder und Naturforscher – das Urbild des „Universalgenies“. Er malte in Mailand für Herzog Ludovico Sforza „Das Abendmahl“ an die Wand eines Klosterspeisesaals und später „Mona Lisa“ mit ihrem rätselhaften Lächeln, die heute im Louvre in Paris hängt. In seinen Notizbüchern, in Spiegelschrift geschrieben, entwarf er Flugmaschinen, Fallschirme und Panzer und zeichnete den menschlichen Körper nach eigenen Sektionen.',
            'Michelangelo Buonarroti (1475–1564) sah sich vor allem als Bildhauer. Mit 24 Jahren schuf er die „Pietà“ im Petersdom – Maria mit dem toten Jesus auf dem Schoß –, 1504 aus einem einzigen, von anderen verworfenen Marmorblock den über fünf Meter hohen „David“, Symbol der Freiheit von Florenz. Von 1508 bis 1512 bemalte er im Auftrag von Papst Julius II. die Decke der Sixtinischen Kapelle mit über 300 Figuren – darunter die „Erschaffung Adams“ –, auf einem Gerüst stehend, den Kopf nach hinten gebeugt.',
            'Raffael (1483–1520) aus Urbino malte sanfte Madonnenbilder und für den Papst im Vatikan „Die Schule von Athen“, auf der antike Philosophen wie Platon und Aristoteles zu sehen sind – Platon trägt die Züge Leonardos. Er starb mit nur 37 Jahren. In Venedig malte Tizian leuchtende Bilder mit kräftigen Farben, die venezianische Malerei wurde für ihre Farbe berühmt.',
            'Die Päpste der Renaissance waren mächtige Fürsten und Kunstförderer, aber oft wenig fromm. Papst Alexander VI. aus der Familie Borgia hatte mehrere Kinder; sein Sohn Cesare Borgia eroberte rücksichtslos Gebiete in Mittelitalien. Julius II., der „Kriegerpapst“, zog selbst in Rüstung in den Krieg und ließ 1506 den Neubau des Petersdoms beginnen; dafür gründete er die Schweizergarde, die den Papst bis heute bewacht.',
            'Um den Bau des Petersdoms zu bezahlen, verkaufte die Kirche Ablassbriefe, die den Erlass von Sündenstrafen versprachen. Dagegen protestierte 1517 Martin Luther in Deutschland – der Beginn der Reformation. Michelangelo entwarf im Alter die gewaltige Kuppel des Petersdoms, die nach seinem Tod vollendet wurde.',
          ],
          quiz: {
            leicht: [
              ['Wer malte die „Mona Lisa“?', 'Leonardo da Vinci', ['Michelangelo', 'Raffael', 'Botticelli']],
              ['Wo hängt die „Mona Lisa“ heute?', 'Im Louvre in Paris', ['In den Uffizien', 'Im Vatikan', 'In London']],
              ['Wer malte „Das Abendmahl“?', 'Leonardo da Vinci', ['Michelangelo', 'Tizian', 'Raffael']],
              ['In welcher Stadt ist „Das Abendmahl“?', 'Mailand', ['Florenz', 'Rom', 'Venedig']],
              ['Wie nennt man Leonardo wegen seiner vielen Talente?', 'Universalgenie', ['Wunderkind', 'Meisterdieb', 'Kriegerpapst']],
              ['In welcher Schrift schrieb Leonardo seine Notizen?', 'In Spiegelschrift', ['In Geheimschrift der Medici', 'Auf Arabisch', 'In Keilschrift']],
              ['Was entwarf Leonardo?', 'Flugmaschinen', ['Dampfmaschinen', 'Computer', 'Autos mit Motor']],
              ['Wer schuf die Statue „David“ aus Marmor?', 'Michelangelo', ['Donatello', 'Leonardo', 'Bernini']],
              ['Wie hoch ist Michelangelos David?', 'Über fünf Meter', ['Ein Meter', 'Zwanzig Meter', 'Zwei Meter']],
              ['Wofür steht der David?', 'Für die Freiheit von Florenz', ['Für den Papst', 'Für Mailand', 'Für Venedig']],
              ['Welche Decke bemalte Michelangelo?', 'Die der Sixtinischen Kapelle', ['Die des Louvre', 'Die des Florentiner Doms', 'Die des Dogenpalasts']],
              ['Welche Szene ist an der Sixtinischen Decke besonders berühmt?', 'Die Erschaffung Adams', ['Das Abendmahl', 'Die Geburt der Venus', 'Die Schule von Athen']],
              ['Welcher Papst beauftragte Michelangelo mit der Sixtina?', 'Julius II.', ['Alexander VI.', 'Leo X.', 'Gregor der Große']],
              ['Woher stammte Raffael?', 'Aus Urbino', ['Aus Florenz', 'Aus Venedig', 'Aus Vinci']],
              ['Wer malte „Die Schule von Athen“?', 'Raffael', ['Leonardo', 'Michelangelo', 'Tizian']],
              ['Welcher Maler wirkte in Venedig?', 'Tizian', ['Raffael', 'Botticelli', 'Giotto']],
              ['Wie nannte man Papst Julius II.?', '„Kriegerpapst“', ['„Bauernpapst“', '„Friedenspapst“', '„Der Gute“']],
              ['Welche Garde gründete Julius II.?', 'Die Schweizergarde', ['Die Carabinieri', 'Die Leibgarde der Medici', 'Die Templer']],
              ['Was verkaufte die Kirche für den Petersdom?', 'Ablassbriefe', ['Kirchen', 'Reliquien aus Venedig', 'Grundstücke in Amerika']],
              ['Wer protestierte 1517 gegen den Ablass?', 'Martin Luther', ['Savonarola', 'Calvin', 'Erasmus']],
            ],
            mittel: [
              ['Wann lebte Leonardo?', '1452–1519', ['1475–1564', '1483–1520', '1265–1321']],
              ['Woher stammte Leonardo?', 'Aus Vinci bei Florenz', ['Aus Mailand', 'Aus Rom', 'Aus Urbino']],
              ['Für welchen Herzog malte Leonardo „Das Abendmahl“?', 'Ludovico Sforza', ['Lorenzo de’ Medici', 'Cesare Borgia', 'Julius II.']],
              ['Wo ist „Das Abendmahl“ gemalt?', 'An der Wand eines Klosterspeisesaals', ['Auf Leinwand im Louvre', 'An der Sixtinischen Decke', 'Im Dom von Florenz']],
              ['Was ist an der Mona Lisa berühmt?', 'Ihr rätselhaftes Lächeln', ['Ihre Krone', 'Ihr Hund', 'Ihr rotes Kleid']],
              ['Wie studierte Leonardo den menschlichen Körper?', 'Durch eigene Sektionen', ['Gar nicht', 'Nur aus Büchern', 'Durch Röntgen']],
              ['Wann lebte Michelangelo?', '1475–1564', ['1452–1519', '1483–1520', '1400–1450']],
              ['Als was sah sich Michelangelo vor allem?', 'Als Bildhauer', ['Als Maler', 'Als Architekt', 'Als Dichter']],
              ['Wie alt war Michelangelo bei der „Pietà“?', '24', ['14', '44', '64']],
              ['Wo steht die „Pietà“?', 'Im Petersdom', ['In Florenz', 'Im Louvre', 'In Mailand']],
              ['Wann vollendete Michelangelo den David?', '1504', ['1436', '1512', '1478']],
              ['Woraus schuf Michelangelo den David?', 'Aus einem verworfenen Marmorblock', ['Aus Bronze', 'Aus mehreren Steinen', 'Aus Holz']],
              ['Wann bemalte Michelangelo die Sixtinische Decke?', '1508–1512', ['1494–1498', '1527–1530', '1550–1560']],
              ['Wie viele Figuren malte Michelangelo an die Decke?', 'Über 300', ['Zwölf', 'Über 3000', 'Eine']],
              ['Wann lebte Raffael?', '1483–1520', ['1452–1519', '1475–1564', '1490–1576']],
              ['Welche Philosophen zeigt „Die Schule von Athen“?', 'Platon und Aristoteles', ['Cicero und Seneca', 'Dante und Vergil', 'Luther und Calvin']],
              ['Wofür wurde die venezianische Malerei berühmt?', 'Für ihre Farbe', ['Für ihre Perspektive', 'Für Schwarz-Weiß', 'Für ihre Größe']],
              ['Aus welcher Familie stammte Papst Alexander VI.?', 'Borgia', ['Medici', 'Sforza', 'Pazzi']],
              ['Wer war Cesare Borgia?', 'Sohn des Papstes, Eroberer in Mittelitalien', ['Ein Maler', 'Ein Bankier', 'Ein Doge']],
              ['Wann begann der Neubau des Petersdoms?', '1506', ['1436', '1517', '1626']],
            ],
            schwer: [
              ['Wessen Züge trägt Platon in der „Schule von Athen“?', 'Leonardos', ['Michelangelos', 'Raffaels', 'Julius’ II.']],
              ['Wie alt wurde Raffael?', '37', ['89', '67', '24']],
              ['Wie malte Michelangelo die Decke?', 'Auf einem Gerüst stehend, den Kopf nach hinten gebeugt', ['Liegend auf dem Rücken im Bett', 'Am Boden auf Leinwand', 'Von einem Ballon aus']],
              ['Was war an den Renaissancepäpsten auffällig?', 'Sie waren mächtige Fürsten, aber oft wenig fromm', ['Sie lebten in Armut', 'Sie lebten in Avignon', 'Sie verboten die Kunst']],
              ['Was zeigte Alexander VI. über die Päpste der Zeit?', 'Er hatte mehrere Kinder', ['Er war ein Heiliger', 'Er war ein Bettelmönch', 'Er war Deutscher']],
              ['Wie zog Julius II. in den Krieg?', 'Selbst in Rüstung', ['Gar nicht', 'Nur mit Gebeten', 'Mit Schweizer Bankiers']],
              ['Was entwarf Michelangelo im Alter?', 'Die Kuppel des Petersdoms', ['Die Florentiner Domkuppel', 'Das Kolosseum', 'Den Schiefen Turm']],
              ['Wann wurde die Kuppel des Petersdoms vollendet?', 'Nach Michelangelos Tod', ['1506', 'Vor seiner Geburt', 'Nie']],
              ['Was versprach ein Ablassbrief?', 'Den Erlass von Sündenstrafen', ['Land in Amerika', 'Einen Adelstitel', 'Steuerfreiheit']],
              ['Welche Folge hatte der Ablasshandel?', 'Die Reformation in Deutschland', ['Die Einigung Italiens', 'Die Pest', 'Die Gründung Venedigs']],
              ['Was entwarf Leonardo außer Flugmaschinen?', 'Fallschirme und Panzer', ['Telefone', 'Glühbirnen', 'Eisenbahnen']],
              ['Was ist besonders am Marmorblock des David?', 'Andere hatten ihn verworfen', ['Er kam aus Griechenland', 'Er war schwarz', 'Er war sehr klein']],
              ['Wer bewacht bis heute den Papst?', 'Die Schweizergarde', ['Die Carabinieri', 'Die Templer', 'Die italienische Armee']],
              ['Welches Motiv malte Raffael besonders oft?', 'Sanfte Madonnenbilder', ['Schlachten', 'Landschaften ohne Menschen', 'Stillleben']],
              ['Welche Berufe vereinte Leonardo?', 'Maler, Bildhauer, Ingenieur, Erfinder, Naturforscher', ['Bankier und Papst', 'Admiral und Doge', 'Bauer und Händler']],
              ['Wo malte Raffael „Die Schule von Athen“?', 'Im Vatikan', ['In Florenz', 'In Urbino', 'In Venedig']],
              ['Was eroberte Cesare Borgia?', 'Gebiete in Mittelitalien', ['Sizilien', 'Venedig', 'Mailand und Genua']],
              ['Wofür wurden Ablassbriefe verkauft?', 'Für den Bau des Petersdoms', ['Für Kreuzzüge nach Amerika', 'Für die Schweizergarde', 'Für die Medici-Bank']],
              ['Welcher Künstler lebte am längsten?', 'Michelangelo', ['Leonardo', 'Raffael', 'Botticelli']],
              ['Wofür steht die Pietà?', 'Maria mit dem toten Jesus', ['David gegen Goliath', 'Die Geburt Christi', 'Das Abendmahl']],
            ],
          },
        },
        {
          id: 'machiavelli-kriege',
          title: 'Machiavelli und die Italienkriege',
          date: '1494–1559',
          text: [
            'Ende des 15. Jahrhunderts teilten sich fünf Mächte Italien: das Herzogtum Mailand, die Republiken Venedig und Florenz, der Kirchenstaat und das Königreich Neapel. Lorenzo de’ Medici hielt sie im Gleichgewicht. Kurz nach seinem Tod fiel 1494 der französische König Karl VIII. in Italien ein, um Neapel zu erobern – der Beginn der „Italienkriege“.',
            'Über 60 Jahre lang kämpften Frankreich und Spanien mit dem Kaiser um Italien und seine reichen Städte. Die italienischen Staaten waren zu schwach und uneins, um sich zu wehren, und wechselten ständig die Seiten. Heere aus Söldnern („Condottieri“ hießen ihre Anführer) kämpften für den, der am meisten zahlte.',
            'Der Florentiner Beamte und Diplomat Niccolò Machiavelli (1469–1527) erlebte das Chaos aus nächster Nähe. Nach der Rückkehr der Medici 1512 verlor er sein Amt, wurde gefoltert und schrieb auf seinem Landgut 1513 „Der Fürst“ (Il Principe). Darin riet er, ein Herrscher müsse notfalls grausam und listig sein; es sei sicherer, gefürchtet als geliebt zu werden. Sein Vorbild war Cesare Borgia. „Machiavellistisch“ steht bis heute für skrupellose Machtpolitik.',
            'Den Tiefpunkt brachte der „Sacco di Roma“ 1527: Meuternde, unbezahlte Söldner Kaiser Karls V., darunter viele deutsche Landsknechte, plünderten Rom monatelang. Tausende Menschen starben, Papst Clemens VII. (ein Medici) floh in die Engelsburg. 147 Schweizergardisten fielen bei seiner Verteidigung; deshalb werden neue Gardisten bis heute am 6. Mai vereidigt.',
            'Im Frieden von Cateau-Cambrésis 1559 setzte sich Spanien durch: Es beherrschte nun Mailand, Neapel, Sizilien und Sardinien direkt und hatte großen Einfluss auf den Rest. Nur Venedig, der Kirchenstaat und Savoyen blieben wirklich selbstständig. Damit begann eine rund 150-jährige spanische Vorherrschaft, und Italien verlor seine führende Stellung in Europa – auch weil der Welthandel sich nach der Entdeckung Amerikas zum Atlantik verlagerte.',
          ],
          quiz: {
            leicht: [
              ['Wer schrieb „Der Fürst“?', 'Niccolò Machiavelli', ['Dante', 'Lorenzo de’ Medici', 'Petrarca']],
              ['Woher stammte Machiavelli?', 'Aus Florenz', ['Aus Rom', 'Aus Venedig', 'Aus Neapel']],
              ['Was riet Machiavelli einem Herrscher?', 'Notfalls grausam und listig zu sein', ['Immer gütig zu sein', 'Auf die Macht zu verzichten', 'Dem Papst zu gehorchen']],
              ['Ist es laut Machiavelli sicherer, geliebt oder gefürchtet zu werden?', 'Gefürchtet', ['Geliebt', 'Beides gleich', 'Keines']],
              ['Wofür steht „machiavellistisch“?', 'Für skrupellose Machtpolitik', ['Für Frömmigkeit', 'Für Kunstliebe', 'Für Demokratie']],
              ['Welcher König fiel 1494 in Italien ein?', 'Karl VIII. von Frankreich', ['Karl V.', 'Franz I.', 'Ludwig XIV.']],
              ['Welches Königreich wollte Karl VIII. erobern?', 'Neapel', ['Sizilien', 'Venedig', 'Mailand']],
              ['Wie nennt man die Kriege um Italien ab 1494?', 'Italienkriege', ['Punische Kriege', 'Rosenkriege', 'Kreuzzüge']],
              ['Welche Länder kämpften um Italien?', 'Frankreich und Spanien', ['England und Holland', 'Russland und Polen', 'Schweden und Dänemark']],
              ['Wie hießen die Söldnerführer?', 'Condottieri', ['Dogen', 'Podestà', 'Kardinäle']],
              ['Was war der „Sacco di Roma“?', 'Die Plünderung Roms 1527', ['Ein Friedensvertrag', 'Eine Kirche', 'Ein Fest']],
              ['Wessen Söldner plünderten Rom 1527?', 'Die Kaiser Karls V.', ['Die Frankreichs', 'Die Venedigs', 'Die Türken']],
              ['Wohin floh Papst Clemens VII.?', 'In die Engelsburg', ['Nach Avignon', 'Nach Florenz', 'In den Petersdom']],
              ['Welche Garde verteidigte den Papst 1527?', 'Die Schweizergarde', ['Die Carabinieri', 'Die Medici-Garde', 'Die Templer']],
              ['An welchem Tag werden Schweizergardisten vereidigt?', 'Am 6. Mai', ['Am 1. Januar', 'Am 25. Dezember', 'Am 15. März']],
              ['Wer setzte sich 1559 in Italien durch?', 'Spanien', ['Frankreich', 'Venedig', 'England']],
              ['Welche Gebiete beherrschte Spanien direkt?', 'Mailand, Neapel, Sizilien, Sardinien', ['Venedig und Genua', 'Florenz und Rom', 'Savoyen und Piemont']],
              ['Welcher Staat blieb selbstständig?', 'Venedig', ['Mailand', 'Neapel', 'Sizilien']],
              ['Wohin verlagerte sich der Welthandel?', 'Zum Atlantik', ['Zum Mittelmeer', 'Zur Ostsee', 'Nach Russland']],
              ['Welche Entdeckung verlagerte den Handel?', 'Die Entdeckung Amerikas', ['Die Entdeckung Australiens', 'Die Erfindung des Autos', 'Der Bau des Suezkanals']],
            ],
            mittel: [
              ['Wie viele große Mächte teilten sich Italien um 1490?', 'Fünf', ['Zwei', 'Zehn', 'Zwanzig']],
              ['Wer hielt die fünf Mächte im Gleichgewicht?', 'Lorenzo de’ Medici', ['Machiavelli', 'Karl VIII.', 'Julius II.']],
              ['Wie lange dauerten die Italienkriege?', 'Über 60 Jahre', ['Zehn Jahre', 'Hundert Tage', 'Zweihundert Jahre']],
              ['Warum konnten sich die italienischen Staaten nicht wehren?', 'Sie waren zu schwach und uneins', ['Sie hatten keine Städte', 'Der Papst verbot es', 'Sie waren mit Frankreich vereint']],
              ['Für wen kämpften Söldner?', 'Für den, der am meisten zahlte', ['Nur für den Papst', 'Für ihre Heimat', 'Umsonst']],
              ['Wann lebte Machiavelli?', '1469–1527', ['1265–1321', '1449–1492', '1564–1642']],
              ['Welche Ämter hatte Machiavelli?', 'Beamter und Diplomat', ['Papst und Kardinal', 'Maler und Bildhauer', 'Söldnerführer']],
              ['Wann verlor Machiavelli sein Amt?', '1512', ['1494', '1527', '1559']],
              ['Was geschah mit Machiavelli nach 1512?', 'Er wurde gefoltert', ['Er wurde Papst', 'Er wurde Herzog', 'Er floh nach Spanien']],
              ['Wann schrieb Machiavelli „Der Fürst“?', '1513', ['1494', '1527', '1559']],
              ['Wie heißt „Der Fürst“ auf Italienisch?', '„Il Principe“', ['„Il Milione“', '„Il Duce“', '„Il Magnifico“']],
              ['Wer war Machiavellis Vorbild?', 'Cesare Borgia', ['Lorenzo de’ Medici', 'Savonarola', 'Karl V.']],
              ['Wer plünderte Rom 1527 unter anderem?', 'Deutsche Landsknechte', ['Venezianer', 'Türken', 'Engländer']],
              ['Warum meuterten die Söldner 1527?', 'Sie waren unbezahlt', ['Sie hatten Hunger auf Kunst', 'Der Papst befahl es', 'Wegen der Pest']],
              ['Aus welcher Familie stammte Clemens VII.?', 'Medici', ['Borgia', 'Sforza', 'Pazzi']],
              ['Wie viele Schweizergardisten fielen 1527?', '147', ['14', '1470', '7']],
              ['Wann war der Frieden von Cateau-Cambrésis?', '1559', ['1527', '1494', '1648']],
              ['Welche Staaten blieben außer Venedig selbstständig?', 'Der Kirchenstaat und Savoyen', ['Mailand und Neapel', 'Sizilien und Sardinien', 'Neapel und Sizilien']],
              ['Wie lange dauerte die spanische Vorherrschaft etwa?', 'Rund 150 Jahre', ['Rund 15 Jahre', 'Rund 500 Jahre', 'Rund 50 Jahre']],
              ['Was verlor Italien nach 1559?', 'Seine führende Stellung in Europa', ['Seine Sprache', 'Den Papst', 'Alle Städte']],
            ],
            schwer: [
              ['Welche fünf Mächte gab es um 1490?', 'Mailand, Venedig, Florenz, Kirchenstaat, Neapel', ['Rom, Genua, Pisa, Amalfi, Sizilien', 'Savoyen, Toskana, Parma, Modena, Lucca', 'Frankreich, Spanien, Kaiser, Papst, Venedig']],
              ['Wann begannen die Italienkriege?', '1494', ['1453', '1527', '1559']],
              ['Wie verhielten sich italienische Staaten in den Kriegen?', 'Sie wechselten ständig die Seiten', ['Sie blieben neutral', 'Sie kämpften gemeinsam', 'Sie flohen nach Amerika']],
              ['Wo schrieb Machiavelli „Der Fürst“?', 'Auf seinem Landgut', ['Im Gefängnis von Rom', 'In Paris', 'Im Vatikan']],
              ['Wann kehrten die Medici nach Florenz zurück?', '1512', ['1494', '1527', '1434']],
              ['Wie lange plünderten die Söldner Rom?', 'Monatelang', ['Einen Tag', 'Zehn Jahre', 'Eine Stunde']],
              ['Warum werden Gardisten am 6. Mai vereidigt?', 'Zur Erinnerung an die Gefallenen von 1527', ['Weil es Papstgeburtstag ist', 'Weil die Garde 1506 gegründet wurde', 'Zufällig']],
              ['Welche Folge hatte der Frieden von 1559?', 'Spanische Vorherrschaft in Italien', ['Italienische Einigung', 'Französische Herrschaft über Neapel', 'Venedigs Untergang']],
              ['Welche Rolle hatte der Kaiser in den Italienkriegen?', 'Er kämpfte an der Seite Spaniens', ['Er blieb neutral', 'Er kämpfte für Frankreich', 'Er war der Papst']],
              ['Welcher Kaiser war 1527 an der Macht?', 'Karl V.', ['Karl VIII.', 'Friedrich II.', 'Barbarossa']],
              ['Was war ein Condottiere?', 'Ein Söldnerführer', ['Ein Kaufmann', 'Ein Mönch', 'Ein Seefahrer']],
              ['Was erlebte Machiavelli aus nächster Nähe?', 'Das Chaos der Italienkriege', ['Die Entdeckung Amerikas', 'Den Bau des Petersdoms', 'Die Pest von 1348']],
              ['Wann starb Machiavelli?', '1527', ['1513', '1559', '1494']],
              ['Was bedeutet „Sacco“?', 'Plünderung', ['Sack Mehl', 'Krönung', 'Friede']],
              ['Welcher Medici-Papst erlebte den Sacco di Roma?', 'Clemens VII.', ['Leo X.', 'Julius II.', 'Alexander VI.']],
              ['Wo lagen Sizilien und Sardinien nach 1559 politisch?', 'Unter spanischer Herrschaft', ['Unter französischer', 'Unter venezianischer', 'Unabhängig']],
              ['Was hatte Spanien außerdem auf den Rest Italiens?', 'Großen Einfluss', ['Keinen Einfluss', 'Nur kulturellen Einfluss', 'Gar nichts']],
              ['Warum war die Herrschaft über Italien für Fremde attraktiv?', 'Wegen der reichen Städte', ['Wegen des Öls', 'Wegen der Kolonien', 'Wegen der Kälte']],
              ['Was verlor Machiavelli 1512?', 'Sein Amt', ['Sein Landgut', 'Sein Augenlicht', 'Seine Bücher']],
              ['Welche Rolle spielte Lorenzos Tod für Italien?', 'Danach brach das Gleichgewicht zusammen', ['Er brachte die Einigung', 'Er beendete die Kriege', 'Keine']],
            ],
          },
        },
      ],
    },
    {
      id: 'fremdherrschaft',
      title: 'Gegenreformation, Barock und Aufklärung',
      date: '1545–1796',
      text: [
        'Unter spanischer und später österreichischer Herrschaft wurde Italien zum Zentrum der katholischen Gegenreformation und des Barock. Galilei begründete die moderne Naturwissenschaft, und Italien schenkte Europa die Oper.',
      ],
      subtopics: [
        {
          id: 'gegenreformation-galilei',
          title: 'Gegenreformation und Galilei',
          date: '1545–1642',
          text: [
            'Als Antwort auf die Reformation tagte von 1545 bis 1563 in der Stadt Trient (Trento) das Konzil von Trient. Es bekräftigte die katholische Lehre, verbot den Ämterkauf und ordnete die Ausbildung der Priester in Seminaren an. Die Römische Inquisition verfolgte Ketzer, und ab 1559 verzeichnete ein Index verbotene Bücher, darunter Werke Machiavellis.',
            'Der Jesuitenorden, 1540 vom Spanier Ignatius von Loyola gegründet, wurde zur wichtigsten Waffe der Gegenreformation: Er gründete Schulen und schickte Missionare bis nach Indien, China und Südamerika. 1582 führte Papst Gregor XIII. den Gregorianischen Kalender ein, nach dem auf den 4. Oktober direkt der 15. Oktober folgte; er gilt heute weltweit.',
            '1571 besiegte eine christliche Flotte aus Spanien, Venedig und dem Papst die Osmanen in der Seeschlacht von Lepanto vor Griechenland – die größte Seeschlacht der Galeerenzeit. Die Osmanen bauten ihre Flotte jedoch schnell wieder auf, und Venedig verlor Zypern.',
            'Der Philosoph Giordano Bruno lehrte, das Universum sei unendlich und es gebe viele Welten. Er wurde 1600 auf dem Campo de’ Fiori in Rom als Ketzer verbrannt; dort steht heute sein Denkmal.',
            'Galileo Galilei (1564–1642) aus Pisa untersuchte die Fallgesetze und baute 1609 ein Fernrohr nach. Damit entdeckte er die Mondkrater, die vier großen Jupitermonde und die Phasen der Venus. Er verteidigte die Lehre des Kopernikus, dass sich die Erde um die Sonne dreht. 1633 zwang ihn die Inquisition, dieser Lehre abzuschwören; er verbrachte seine letzten Jahre unter Hausarrest. Ob er danach „Und sie bewegt sich doch“ (Eppur si muove) murmelte, ist eine Legende. Erst 1992 rehabilitierte ihn Papst Johannes Paul II.',
          ],
          quiz: {
            leicht: [
              ['In welcher Stadt tagte das Konzil gegen die Reformation?', 'In Trient', ['In Rom', 'In Florenz', 'In Mailand']],
              ['Wogegen richtete sich das Konzil von Trient?', 'Gegen die Reformation', ['Gegen die Osmanen', 'Gegen Spanien', 'Gegen die Pest']],
              ['Welcher Orden war die wichtigste Waffe der Gegenreformation?', 'Die Jesuiten', ['Die Franziskaner', 'Die Templer', 'Die Benediktiner']],
              ['Wer gründete den Jesuitenorden?', 'Ignatius von Loyola', ['Franz von Assisi', 'Martin Luther', 'Gregor XIII.']],
              ['Was gründeten die Jesuiten?', 'Schulen', ['Banken', 'Armeen', 'Theater']],
              ['Welcher Papst führte einen neuen Kalender ein?', 'Gregor XIII.', ['Julius II.', 'Leo X.', 'Johannes Paul II.']],
              ['Wann wurde der Gregorianische Kalender eingeführt?', '1582', ['1492', '1517', '1633']],
              ['Gilt der Gregorianische Kalender heute weltweit?', 'Ja', ['Nein, nur in Italien', 'Nein, er wurde abgeschafft', 'Nur in der Kirche']],
              ['Wo siegte 1571 eine christliche Flotte über die Osmanen?', 'Bei Lepanto', ['Bei Trafalgar', 'Bei Actium', 'Bei Meloria']],
              ['Welche Insel verlor Venedig an die Osmanen?', 'Zypern', ['Sizilien', 'Kreta', 'Sardinien']],
              ['Welcher Philosoph wurde 1600 in Rom verbrannt?', 'Giordano Bruno', ['Galileo Galilei', 'Savonarola', 'Machiavelli']],
              ['Was lehrte Giordano Bruno?', 'Das Universum ist unendlich', ['Die Erde ist eine Scheibe', 'Die Sonne kreist um die Erde', 'Es gibt keine Sterne']],
              ['Woher stammte Galilei?', 'Aus Pisa', ['Aus Florenz', 'Aus Rom', 'Aus Venedig']],
              ['Welches Instrument nutzte Galilei für den Himmel?', 'Ein Fernrohr', ['Ein Mikroskop', 'Einen Kompass', 'Ein Thermometer']],
              ['Was entdeckte Galilei auf dem Mond?', 'Krater', ['Wasser', 'Leben', 'Städte']],
              ['Welche Monde entdeckte Galilei?', 'Die vier großen Jupitermonde', ['Die Saturnringe', 'Den Erdmond', 'Die Marsmonde']],
              ['Wessen Lehre verteidigte Galilei?', 'Die des Kopernikus', ['Die des Ptolemäus', 'Die des Aristoteles', 'Die Luthers']],
              ['Was besagt die Lehre des Kopernikus?', 'Die Erde dreht sich um die Sonne', ['Die Sonne dreht sich um die Erde', 'Die Erde ist flach', 'Der Mond ist ein Stern']],
              ['Wer zwang Galilei 1633 zum Abschwören?', 'Die Inquisition', ['Der König von Spanien', 'Die Medici', 'Der Doge von Venedig']],
              ['Was soll Galilei gemurmelt haben?', '„Und sie bewegt sich doch“', ['„Der Würfel ist gefallen“', '„Ich kam, sah und siegte“', '„Gott ist tot“']],
            ],
            mittel: [
              ['Wann tagte das Konzil von Trient?', '1545–1563', ['1517–1521', '1600–1633', '1492–1500']],
              ['Was verbot das Konzil?', 'Den Ämterkauf', ['Die Messe', 'Die Bibel', 'Den Papst']],
              ['Wo sollten Priester ausgebildet werden?', 'In Seminaren', ['An Universitäten in Deutschland', 'Bei den Medici', 'Gar nicht']],
              ['Was war der Index?', 'Ein Verzeichnis verbotener Bücher', ['Ein Kalender', 'Ein Gesetzbuch', 'Eine Liste der Päpste']],
              ['Ab wann gab es den Index?', '1559', ['1517', '1633', '1582']],
              ['Wessen Werke standen auf dem Index?', 'Machiavellis', ['Dantes Bibel', 'Des Papstes', 'Der Jesuiten']],
              ['Wann wurde der Jesuitenorden gegründet?', '1540', ['1517', '1582', '1600']],
              ['Woher stammte Ignatius von Loyola?', 'Aus Spanien', ['Aus Italien', 'Aus Frankreich', 'Aus Portugal']],
              ['Wohin schickten die Jesuiten Missionare?', 'Nach Indien, China und Südamerika', ['Nur nach Rom', 'Nach Island', 'Nach Australien']],
              ['Welcher Tag folgte 1582 auf den 4. Oktober?', 'Der 15. Oktober', ['Der 5. Oktober', 'Der 1. November', 'Der 14. Oktober']],
              ['Wer kämpfte bei Lepanto gegen die Osmanen?', 'Spanien, Venedig und der Papst', ['Frankreich und England', 'Genua und Pisa', 'Österreich und Polen']],
              ['Wo liegt Lepanto?', 'Vor Griechenland', ['Vor Sizilien', 'Vor Spanien', 'Vor Ägypten']],
              ['Als was gilt Lepanto?', 'Größte Seeschlacht der Galeerenzeit', ['Erste Seeschlacht', 'Kleinste Schlacht', 'Niederlage Venedigs']],
              ['Wo wurde Giordano Bruno verbrannt?', 'Auf dem Campo de’ Fiori', ['Auf dem Petersplatz', 'Auf der Piazza della Signoria', 'In Trient']],
              ['Wann lebte Galilei?', '1564–1642', ['1452–1519', '1469–1527', '1600–1680']],
              ['Wann baute Galilei sein Fernrohr?', '1609', ['1582', '1633', '1600']],
              ['Welche Planetenerscheinung entdeckte Galilei?', 'Die Phasen der Venus', ['Die Ringe des Saturn', 'Die Monde des Mars', 'Den Planeten Neptun']],
              ['Was untersuchte Galilei außer dem Himmel?', 'Die Fallgesetze', ['Den Blutkreislauf', 'Die Elektrizität', 'Die Evolution']],
              ['Wie verbrachte Galilei seine letzten Jahre?', 'Unter Hausarrest', ['Im Kerker', 'Als Papstberater', 'Auf Reisen']],
              ['Wann rehabilitierte die Kirche Galilei?', '1992', ['1642', '1870', '1929']],
            ],
            schwer: [
              ['Welcher Papst rehabilitierte Galilei?', 'Johannes Paul II.', ['Gregor XIII.', 'Pius IX.', 'Franziskus']],
              ['Ist „Eppur si muove“ belegt?', 'Nein, es ist eine Legende', ['Ja, vor Gericht gesagt', 'Ja, in einem Brief', 'Ja, in der Bibel']],
              ['Was bekräftigte das Konzil von Trient?', 'Die katholische Lehre', ['Luthers Lehre', 'Die Lehre des Kopernikus', 'Die Macht der Kaiser']],
              ['Was verfolgte die Römische Inquisition?', 'Ketzer', ['Piraten', 'Bankiers', 'Künstler']],
              ['Was geschah nach Lepanto mit der osmanischen Flotte?', 'Sie wurde schnell wieder aufgebaut', ['Sie verschwand für immer', 'Sie wurde venezianisch', 'Sie eroberte Rom']],
              ['Was lehrte Bruno außer dem unendlichen Universum?', 'Es gebe viele Welten', ['Die Erde sei der Mittelpunkt', 'Es gebe keinen Gott', 'Die Sonne sei kalt']],
              ['Was steht heute auf dem Campo de’ Fiori?', 'Ein Denkmal für Giordano Bruno', ['Der Petersdom', 'Ein Bahnhof', 'Eine Statue Galileis']],
              ['Welche Lehre musste Galilei 1633 abschwören?', 'Dass sich die Erde um die Sonne dreht', ['Dass der Mond Krater hat', 'Dass es Jupitermonde gibt', 'Dass Körper fallen']],
              ['Hat Galilei das Fernrohr erfunden?', 'Nein, er baute es nach', ['Ja, als Erster 1600', 'Ja, mit Leonardo', 'Nein, er nutzte nie eins']],
              ['Wie viele Tage fielen bei der Kalenderreform 1582 aus?', 'Zehn', ['Einer', 'Dreißig', 'Hundert']],
              ['In welchem Jahr wurde Giordano Bruno hingerichtet?', '1600', ['1582', '1633', '1559']],
              ['Wann musste Galilei abschwören?', '1633', ['1609', '1642', '1600']],
              ['Was verband die Jesuiten mit der Gegenreformation?', 'Sie waren ihre wichtigste Waffe', ['Sie bekämpften sie', 'Sie waren Protestanten', 'Keine Verbindung']],
              ['Welche Insel verlor Venedig trotz Lepanto?', 'Zypern', ['Kreta', 'Korfu', 'Malta']],
              ['Welche Himmelskörper zeigten Galilei Phasen?', 'Die Venus', ['Der Mars', 'Der Jupiter', 'Die Sonne']],
              ['Welche Zahl der Jupitermonde entdeckte Galilei?', 'Vier', ['Zwei', 'Zwölf', 'Einen']],
              ['Wie heißt Trient auf Italienisch?', 'Trento', ['Treviso', 'Trieste', 'Torino']],
              ['Wofür steht der Name Gregors XIII. bis heute?', 'Für unseren Kalender', ['Für einen Choral', 'Für eine Universität', 'Für eine Kirche in Paris']],
              ['Was ordnete das Konzil für Priester an?', 'Ausbildung in Seminaren', ['Heirat', 'Kriegsdienst', 'Wanderpredigt']],
              ['Welche Strafe erhielt Galilei?', 'Hausarrest', ['Tod auf dem Scheiterhaufen', 'Verbannung nach Amerika', 'Keine']],
            ],
          },
        },
        {
          id: 'barock-aufklaerung',
          title: 'Barock, Oper und Grand Tour',
          date: '1600–1796',
          text: [
            'Rom wurde im 17. Jahrhundert zur Hauptstadt des Barock. Gian Lorenzo Bernini gestaltete den Petersplatz mit seinen Kolonnaden, die wie zwei Arme die Gläubigen umfangen, und schuf den Vierströmebrunnen auf der Piazza Navona. Der Maler Caravaggio arbeitete mit starken Hell-Dunkel-Kontrasten und malte Heilige als einfache Leute von der Straße; er tötete im Streit einen Mann und musste fliehen.',
            'Um 1600 entstand in Florenz die Oper. Claudio Monteverdis „L’Orfeo“ (1607) gilt als erste große Oper. In Venedig öffnete 1637 das erste öffentliche Opernhaus, für das man Eintritt zahlte. Antonio Vivaldi, der „rote Priester“ aus Venedig, komponierte „Die vier Jahreszeiten“. In Cremona bauten Antonio Stradivari und andere Geigen, die bis heute Millionen wert sind. Musikbegriffe wie „piano“ (leise), „forte“ (laut), „allegro“ und „adagio“ sind deshalb italienisch.',
            'Nach dem Spanischen Erbfolgekrieg (1701–1714) übernahm Österreich die Herrschaft über Mailand und zunächst auch Neapel. 1720 erhielt der Herzog von Savoyen die Insel Sardinien und nannte sich fortan „König von Sardinien“, regierte aber von Turin aus über Piemont – dieses Königreich sollte später Italien einigen. Neapel und Sizilien fielen 1734 an eine eigene Linie der spanischen Bourbonen.',
            'Venedig verlor an Macht, blieb aber berühmt für seinen Karneval mit Masken, der Monate dauern konnte. Der Venezianer Giacomo Casanova wurde durch seine Liebesabenteuer und seine Flucht aus dem Bleikammer-Gefängnis des Dogenpalastes 1756 berühmt. Carlo Goldoni erneuerte das Theater mit Komödien aus dem Alltag.',
            'Junge Adlige aus England, Frankreich und Deutschland reisten auf ihrer „Grand Tour“ nach Italien, um antike Ruinen und Kunst zu sehen. Ab 1738 wurden Herculaneum und ab 1748 Pompeji ausgegraben. Johann Wolfgang von Goethe reiste 1786–1788 durch Italien und beschrieb das in seiner „Italienischen Reise“. In Mailand forderte Cesare Beccaria 1764 in „Von den Verbrechen und von den Strafen“ die Abschaffung von Folter und Todesstrafe; 1786 schaffte die Toskana als erster Staat der Welt die Todesstrafe ab.',
          ],
          quiz: {
            leicht: [
              ['Welche Kunstepoche prägte Rom im 17. Jahrhundert?', 'Der Barock', ['Die Gotik', 'Die Romanik', 'Der Jugendstil']],
              ['Wer gestaltete den Petersplatz?', 'Gian Lorenzo Bernini', ['Michelangelo', 'Brunelleschi', 'Caravaggio']],
              ['Wie wirken die Kolonnaden des Petersplatzes?', 'Wie zwei Arme, die die Gläubigen umfangen', ['Wie eine Festungsmauer', 'Wie ein Schiff', 'Wie ein Kreuz']],
              ['Welcher Brunnen auf der Piazza Navona ist von Bernini?', 'Der Vierströmebrunnen', ['Der Trevi-Brunnen', 'Der Neptunbrunnen in Florenz', 'Der Löwenbrunnen']],
              ['Wofür ist Caravaggio bekannt?', 'Für starke Hell-Dunkel-Kontraste', ['Für Landschaften', 'Für Kuppeln', 'Für Mosaiken']],
              ['Wo entstand um 1600 die Oper?', 'In Florenz', ['In Wien', 'In Paris', 'In London']],
              ['Wer schrieb „L’Orfeo“?', 'Claudio Monteverdi', ['Antonio Vivaldi', 'Giuseppe Verdi', 'Mozart']],
              ['Wo öffnete das erste öffentliche Opernhaus?', 'In Venedig', ['In Mailand', 'In Rom', 'In Neapel']],
              ['Wer komponierte „Die vier Jahreszeiten“?', 'Antonio Vivaldi', ['Monteverdi', 'Verdi', 'Puccini']],
              ['Wie nannte man Vivaldi?', 'Den „roten Priester“', ['Den „schwarzen Mönch“', 'Den „goldenen Geiger“', 'Den „Prächtigen“']],
              ['Wer baute in Cremona berühmte Geigen?', 'Antonio Stradivari', ['Vivaldi', 'Bernini', 'Casanova']],
              ['Warum sind viele Musikbegriffe italienisch?', 'Weil Italien in der Musik führend war', ['Wegen der Römer', 'Weil der Papst es befahl', 'Zufällig']],
              ['Welcher Musikbegriff ist italienisch?', 'Allegro', ['Walzer', 'Ballade', 'Choral']],
              ['Welches Land übernahm nach 1714 Mailand?', 'Österreich', ['Frankreich', 'Spanien', 'England']],
              ['Welche Insel erhielt der Herzog von Savoyen 1720?', 'Sardinien', ['Sizilien', 'Korsika', 'Elba']],
              ['Von welcher Stadt aus regierte der König von Sardinien?', 'Turin', ['Cagliari', 'Mailand', 'Genua']],
              ['Wofür war Venedig im 18. Jahrhundert berühmt?', 'Für seinen Karneval', ['Für seine Armee', 'Für Fabriken', 'Für Kolonien in Amerika']],
              ['Welcher Venezianer wurde durch Liebesabenteuer berühmt?', 'Giacomo Casanova', ['Carlo Goldoni', 'Marco Polo', 'Vivaldi']],
              ['Was war die „Grand Tour“?', 'Eine Bildungsreise junger Adliger nach Italien', ['Ein Radrennen', 'Ein Feldzug', 'Eine Pilgerfahrt nach Jerusalem']],
              ['Welcher deutsche Dichter reiste 1786–1788 durch Italien?', 'Goethe', ['Schiller', 'Heine', 'Luther']],
            ],
            mittel: [
              ['Wie malte Caravaggio Heilige?', 'Als einfache Leute von der Straße', ['Mit Goldhintergrund', 'Als Engel', 'Ohne Gesichter']],
              ['Warum musste Caravaggio fliehen?', 'Er tötete im Streit einen Mann', ['Er malte den Papst nackt', 'Er war Protestant', 'Er hatte Schulden bei den Medici']],
              ['Wann entstand „L’Orfeo“?', '1607', ['1637', '1582', '1700']],
              ['Wann öffnete das erste öffentliche Opernhaus?', '1637', ['1607', '1700', '1786']],
              ['Was war am Opernhaus von 1637 neu?', 'Man zahlte Eintritt, es war öffentlich', ['Es hatte elektrisches Licht', 'Es war unter Wasser', 'Es war kostenlos']],
              ['Woher stammte Vivaldi?', 'Aus Venedig', ['Aus Cremona', 'Aus Florenz', 'Aus Neapel']],
              ['Wie viel sind Stradivari-Geigen heute wert?', 'Millionen', ['Ein paar Euro', 'Nichts', 'Hundert Euro']],
              ['Wann war der Spanische Erbfolgekrieg?', '1701–1714', ['1618–1648', '1756–1763', '1494–1559']],
              ['Wie nannte sich der Herzog von Savoyen ab 1720?', 'König von Sardinien', ['König von Italien', 'Doge von Turin', 'Kaiser']],
              ['Über welche Region regierte der König von Sardinien?', 'Piemont', ['Toskana', 'Lombardei', 'Kalabrien']],
              ['Welche Rolle spielte das Königreich Sardinien später?', 'Es einigte Italien', ['Es wurde spanisch', 'Es löste sich auf', 'Es wurde Kirchenstaat']],
              ['An wen fielen Neapel und Sizilien 1734?', 'An die spanischen Bourbonen', ['An Österreich', 'An Savoyen', 'An Venedig']],
              ['Wie lange konnte der venezianische Karneval dauern?', 'Monate', ['Einen Tag', 'Eine Stunde', 'Jahre']],
              ['Aus welchem Gefängnis floh Casanova?', 'Aus den Bleikammern des Dogenpalasts', ['Aus der Engelsburg', 'Aus dem Tower', 'Aus der Bastille']],
              ['Wann floh Casanova?', '1756', ['1637', '1786', '1797']],
              ['Wer erneuerte das venezianische Theater?', 'Carlo Goldoni', ['Casanova', 'Vivaldi', 'Monteverdi']],
              ['Wann begann die Ausgrabung Herculaneums?', '1738', ['1748', '1786', '1600']],
              ['Wann begann die Ausgrabung Pompejis?', '1748', ['1738', '1786', '1860']],
              ['Wie heißt Goethes Buch über Italien?', '„Italienische Reise“', ['„Faust“', '„Werther“', '„Römische Briefe“']],
              ['Was forderte Cesare Beccaria?', 'Abschaffung von Folter und Todesstrafe', ['Mehr Steuern', 'Einen König für Italien', 'Die Inquisition']],
            ],
            schwer: [
              ['Wie heißt Beccarias Werk?', '„Von den Verbrechen und von den Strafen“', ['„Der Fürst“', '„Il Milione“', '„Italienische Reise“']],
              ['Wann erschien Beccarias Buch?', '1764', ['1786', '1748', '1700']],
              ['Welcher Staat schaffte 1786 als erster die Todesstrafe ab?', 'Die Toskana', ['Venedig', 'Frankreich', 'England']],
              ['In welcher Stadt wirkte Beccaria?', 'Mailand', ['Florenz', 'Neapel', 'Turin']],
              ['Welche Art Komödien schrieb Goldoni?', 'Komödien aus dem Alltag', ['Tragödien über Götter', 'Opern', 'Heldenepen']],
              ['Woher kamen die jungen Adligen der Grand Tour?', 'Aus England, Frankreich und Deutschland', ['Aus Amerika und Japan', 'Aus Italien selbst', 'Aus Indien']],
              ['Was wollten die Reisenden auf der Grand Tour sehen?', 'Antike Ruinen und Kunst', ['Fabriken', 'Strände', 'Kolonien']],
              ['Wo bauten Geigenbauer Instrumente?', 'In Cremona', ['In Venedig', 'In Rom', 'In Neapel']],
              ['Welcher Krieg brachte Österreich nach Italien?', 'Der Spanische Erbfolgekrieg', ['Der Dreißigjährige Krieg', 'Die Italienkriege', 'Der Siebenjährige Krieg']],
              ['Wann wurde aus Savoyen das Königreich Sardinien?', '1720', ['1714', '1734', '1559']],
              ['Was beherrschte Österreich nach 1714 zunächst neben Mailand?', 'Neapel', ['Venedig', 'Sardinien', 'Rom']],
              ['Was ist das Besondere an Berninis Petersplatz?', 'Kolonnaden wie umfangende Arme', ['Eine Kuppel aus Glas', 'Ein Wassergraben', 'Ein Turm']],
              ['Welche Stadt wurde zur Hauptstadt des Barock?', 'Rom', ['Florenz', 'Venedig', 'Turin']],
              ['Was gilt als erste große Oper?', '„L’Orfeo“', ['„Die vier Jahreszeiten“', '„Aida“', '„Tosca“']],
              ['Welcher Musikbegriff bedeutet „leise“?', 'Piano', ['Forte', 'Allegro', 'Adagio']],
              ['Wofür war Casanova außer Abenteuern berühmt?', 'Für seine Flucht aus dem Gefängnis', ['Für Opern', 'Für Gemälde', 'Für Seeschlachten']],
              ['Welche Dynastie regierte ab 1734 in Neapel?', 'Eine Linie der spanischen Bourbonen', ['Die Habsburger', 'Die Medici', 'Die Savoyer']],
              ['Wann reiste Goethe nach Italien?', '1786–1788', ['1748–1750', '1764–1766', '1800–1802']],
              ['Welche Rolle spielte Caravaggios Stil?', 'Starkes Hell-Dunkel', ['Helle Pastellfarben', 'Abstrakte Formen', 'Nur Gold']],
              ['Welche Stadt war in der Musik durch Vivaldi bekannt?', 'Venedig', ['Turin', 'Genua', 'Palermo']],
            ],
          },
        },
      ],
    },
  ],
};
