import type { Epoch } from '../types';

export const E1: Epoch = {
  id: 'antike',
  name: 'Gallier, Römer und Franken',
  period: 'bis 987',
  events: [
    {
      id: 'gallien',
      title: 'Gallien',
      date: 'ca. 600 v. Chr. – 476',
      text: [
        'Das Land, das heute Frankreich heißt, nannten die Römer Gallien. Hier lebten keltische Stämme, bis Julius Caesar sie unterwarf. Fast 500 Jahre lang war Gallien danach eine reiche römische Provinz – mit Straßen, Städten und der lateinischen Sprache, aus der später das Französische wurde.',
      ],
      subtopics: [
        {
          id: 'gallier',
          title: 'Die Gallier',
          date: 'ca. 600–58 v. Chr.',
          text: [
            'Die Gallier waren Kelten. Sie bildeten kein gemeinsames Reich, sondern rund 60 Stämme, etwa die Arverner in der Auvergne, die Haeduer in Burgund, die Sequaner, die Helvetier in der heutigen Schweiz und die Parisier an der Seine, nach denen Paris benannt ist. Im Norden lebten die Belger, im Südwesten die Aquitanier. Ihre Kultur nennt man nach einem Fundort in der Schweiz La-Tène-Kultur (ab etwa 450 v. Chr.).',
            'Die Gallier waren geschickte Handwerker. Sie schmiedeten Waffen und Schmuck, etwa die Torques genannten Halsreifen, bauten Holzfässer und trugen – für Römer ungewöhnlich – lange Hosen, die „braccae“. Größere Siedlungen waren befestigte Städte auf Hügeln, die Oppida, etwa Bibracte, Gergovia und Alesia. Die Gallier betrieben Landwirtschaft, prägten Münzen und handelten mit dem Mittelmeerraum.',
            'Besonderes Ansehen genossen die Druiden: Sie waren Priester, Richter, Lehrer und Ärzte. Ihr Wissen gaben sie nur mündlich weiter. Nach dem römischen Schriftsteller Plinius schnitten sie mit einer goldenen Sichel Misteln von heiligen Eichen. Einmal im Jahr trafen sich die Druiden im Gebiet der Carnuten bei Chartres.',
            'Um 600 v. Chr. gründeten griechische Siedler aus Phokaia an der Mittelmeerküste die Stadt Massalia, das heutige Marseille, die älteste Stadt Frankreichs. Von dort kamen Wein, Olivenöl und die griechische Schrift ins Land.',
            'Die Gallier waren als kühne Krieger gefürchtet. Um 387 v. Chr. eroberte ein gallisches Heer unter Brennus sogar Rom. Als die Römer sich über die falschen Gewichte beim Abwiegen des Lösegelds beschwerten, warf Brennus der Überlieferung nach sein Schwert auf die Waage und rief: „Vae victis!“ – „Wehe den Besiegten!“',
            'Ab 121 v. Chr. eroberten die Römer das südliche Gallien und machten es zur Provinz Gallia Narbonensis mit der 118 v. Chr. gegründeten Stadt Narbo (Narbonne); die Römer nannten das Gebiet einfach „die Provinz“ – daher stammt der Name Provence. Heute kennt jedes Kind die Gallier aus den Comics „Asterix“ von René Goscinny und Albert Uderzo, die 1959 erstmals erschienen.',
          ],
          quiz: {
            leicht: [
              ['Wie nannten die Römer das Land, das heute Frankreich ist?', 'Gallien', ['Germanien', 'Hispanien', 'Britannien']],
              ['Zu welchem Volk gehörten die Gallier?', 'Zu den Kelten', ['Zu den Germanen', 'Zu den Griechen', 'Zu den Slawen']],
              ['Bildeten die Gallier ein gemeinsames Reich?', 'Nein, es gab viele Stämme', ['Ja, mit einem König', 'Ja, als Republik', 'Ja, unter Rom']],
              ['Nach welchem Stamm ist Paris benannt?', 'Nach den Parisiern', ['Nach den Arvernern', 'Nach den Belgern', 'Nach den Helvetiern']],
              ['Wer waren bei den Galliern Priester, Richter und Lehrer?', 'Die Druiden', ['Die Senatoren', 'Die Pharaonen', 'Die Mönche']],
              ['Welche Pflanze schnitten Druiden mit einer goldenen Sichel?', 'Die Mistel', ['Den Efeu', 'Die Rose', 'Den Lorbeer']],
              ['Welche französische Stadt ist die älteste?', 'Marseille', ['Paris', 'Lyon', 'Bordeaux']],
              ['Wer gründete Marseille?', 'Griechen', ['Römer', 'Gallier', 'Phönizier']],
              ['Was trugen die Gallier, was die Römer ungewöhnlich fanden?', 'Lange Hosen', ['Togen', 'Kettenhemden', 'Sandalen']],
              ['Welche Comicfiguren zeigen die Gallier?', 'Asterix und Obelix', ['Tim und Struppi', 'Lucky Luke', 'Spirou']],
              ['Welche Stadt eroberten die Gallier um 387 v. Chr.?', 'Rom', ['Athen', 'Karthago', 'Massalia']],
              ['Was rief Brennus der Überlieferung nach?', '„Vae victis!“', ['„Veni, vidi, vici!“', '„Alea iacta est!“', '„Carpe diem!“']],
              ['Was bedeutet „Vae victis“?', 'Wehe den Besiegten', ['Es lebe der Sieger', 'Ich kam, sah und siegte', 'Der Würfel ist gefallen']],
              ['Wie nannte man die befestigten Städte der Gallier?', 'Oppida', ['Kastelle', 'Pfalzen', 'Poleis']],
              ['Welche Region ist nach der römischen „Provinz“ benannt?', 'Die Provence', ['Die Bretagne', 'Die Normandie', 'Das Elsass']],
              ['Welche Behälter aus Holz stellten die Gallier her?', 'Fässer', ['Amphoren aus Ton', 'Glasflaschen', 'Metalldosen']],
              ['Wie gaben die Druiden ihr Wissen weiter?', 'Nur mündlich', ['In dicken Büchern', 'Auf Steintafeln', 'In Briefen']],
              ['In welchem heutigen Land lebten die Helvetier?', 'In der Schweiz', ['In Belgien', 'In Spanien', 'In Italien']],
              ['Was brachten die Griechen aus Marseille unter anderem ins Land?', 'Wein und Olivenöl', ['Kartoffeln und Mais', 'Tee und Reis', 'Kaffee und Kakao']],
              ['Wer zeichnete Asterix?', 'Albert Uderzo', ['Hergé', 'Morris', 'Walt Disney']],
            ],
            mittel: [
              ['Wie heißt die Kultur der Kelten ab etwa 450 v. Chr.?', 'La-Tène-Kultur', ['Hallstatt-Kultur', 'Jastorf-Kultur', 'Glockenbecherkultur']],
              ['Woher stammt der Name der La-Tène-Kultur?', 'Von einem Fundort in der Schweiz', ['Von einem Druiden', 'Von einem Fluss in Paris', 'Von einem römischen Kaiser']],
              ['Welcher Stamm lebte in der Auvergne?', 'Die Arverner', ['Die Haeduer', 'Die Belger', 'Die Parisier']],
              ['Welcher Stamm lebte in Burgund?', 'Die Haeduer', ['Die Arverner', 'Die Sequaner', 'Die Carnuten']],
              ['Wo trafen sich die Druiden einmal im Jahr?', 'Im Gebiet der Carnuten bei Chartres', ['In Rom', 'In Marseille', 'In Alesia']],
              ['Welcher römische Schriftsteller berichtete von der goldenen Sichel?', 'Plinius', ['Caesar', 'Tacitus', 'Cicero']],
              ['Aus welcher griechischen Stadt kamen die Gründer Marseilles?', 'Aus Phokaia', ['Aus Athen', 'Aus Sparta', 'Aus Korinth']],
              ['Um welches Jahr wurde Marseille gegründet?', 'Um 600 v. Chr.', ['Um 100 v. Chr.', 'Um 1000 v. Chr.', 'Um 300 n. Chr.']],
              ['Wie hieß Marseille in der Antike?', 'Massalia', ['Lutetia', 'Lugdunum', 'Narbo']],
              ['Wie hieß der gallische Anführer, der Rom eroberte?', 'Brennus', ['Vercingetorix', 'Ariovist', 'Asterix']],
              ['Worüber beschwerten sich die Römer bei Brennus?', 'Über falsche Gewichte beim Lösegeld', ['Über zu wenig Wein', 'Über den Lärm', 'Über die Hosen']],
              ['Wie nannten die Römer die gallischen Hosen?', 'Braccae', ['Tunica', 'Toga', 'Palla']],
              ['Wie heißen die gallischen Halsreifen?', 'Torques', ['Fibeln', 'Diademe', 'Armillae']],
              ['Ab wann eroberten die Römer Südgallien?', 'Ab 121 v. Chr.', ['Ab 387 v. Chr.', 'Ab 52 v. Chr.', 'Ab 12 v. Chr.']],
              ['Wie hieß die römische Provinz in Südgallien?', 'Gallia Narbonensis', ['Gallia Belgica', 'Gallia Lugdunensis', 'Gallia Aquitania']],
              ['Welche Stadt gründeten die Römer 118 v. Chr.?', 'Narbo (Narbonne)', ['Lugdunum (Lyon)', 'Lutetia (Paris)', 'Massalia (Marseille)']],
              ['Wer lebte im Norden Galliens?', 'Die Belger', ['Die Aquitanier', 'Die Helvetier', 'Die Haeduer']],
              ['Wer lebte im Südwesten Galliens?', 'Die Aquitanier', ['Die Belger', 'Die Parisier', 'Die Sequaner']],
              ['Wann erschien Asterix zum ersten Mal?', '1959', ['1929', '1979', '1945']],
              ['Wer schrieb die Texte zu Asterix?', 'René Goscinny', ['Albert Uderzo', 'Jules Verne', 'Hergé']],
            ],
            schwer: [
              ['Wie viele Stämme gab es in Gallien etwa?', 'Rund 60', ['Rund 6', 'Rund 600', 'Genau 3']],
              ['Welches Oppidum war ein Hauptort der Haeduer?', 'Bibracte', ['Gergovia', 'Alesia', 'Massalia']],
              ['Welches Oppidum lag im Gebiet der Arverner?', 'Gergovia', ['Bibracte', 'Lutetia', 'Narbo']],
              ['Wann eroberten die Gallier unter Brennus Rom?', 'Um 387 v. Chr.', ['Um 52 v. Chr.', 'Um 121 v. Chr.', 'Um 600 v. Chr.']],
              ['Was tat Brennus beim Abwiegen des Lösegelds?', 'Er warf sein Schwert auf die Waage', ['Er schenkte das Gold zurück', 'Er zerbrach die Waage', 'Er nahm die Römer gefangen']],
              ['Von welchen Bäumen schnitten die Druiden die Mistel?', 'Von heiligen Eichen', ['Von Buchen', 'Von Tannen', 'Von Olivenbäumen']],
              ['Was brachten die Griechen außer Wein und Öl nach Gallien?', 'Die Schrift', ['Das Christentum', 'Die Druiden', 'Das Eisen']],
              ['Welche Rollen hatten Druiden außer Priester?', 'Richter, Lehrer und Ärzte', ['Könige und Feldherren', 'Händler und Seefahrer', 'Bauern und Hirten']],
              ['Wofür stand bei den Römern „die Provinz“ zuerst?', 'Für Südgallien', ['Für Britannien', 'Für Germanien', 'Für Spanien']],
              ['Welcher Stamm lebte im heutigen Franche-Comté?', 'Die Sequaner', ['Die Carnuten', 'Die Parisier', 'Die Veneter']],
              ['Woraus bestanden viele gallische Schmuckstücke?', 'Aus Gold und Bronze', ['Aus Plastik', 'Aus Porzellan', 'Aus Glas']],
              ['Was prägten die Gallier ebenfalls?', 'Münzen', ['Briefmarken', 'Papiergeld', 'Medaillen der Olympiade']],
              ['Welche Rolle spielte Massalia für den Handel?', 'Es verband Gallien mit dem Mittelmeerraum', ['Es war ein Wikingerhafen', 'Es war Hauptstadt der Druiden', 'Es war eine römische Festung gegen die Griechen']],
              ['Mit welchem Raum handelten die Gallier besonders?', 'Mit dem Mittelmeerraum', ['Mit China', 'Mit Amerika', 'Mit Indien']],
              ['Welcher Teil Galliens war bei Caesars Ankunft schon römisch?', 'Der Süden (Gallia Narbonensis)', ['Der Norden', 'Die Bretagne', 'Das ganze Land']],
              ['Wann begann die La-Tène-Kultur etwa?', 'Um 450 v. Chr.', ['Um 50 v. Chr.', 'Um 1500 v. Chr.', 'Um 500 n. Chr.']],
              ['Wann gründeten die Römer Narbo?', '118 v. Chr.', ['121 v. Chr.', '52 v. Chr.', '600 v. Chr.']],
              ['Was bedeutet der Name „Gallia Narbonensis“?', 'Gallien um Narbo', ['Gallien jenseits der Alpen', 'Langhaariges Gallien', 'Nördliches Gallien']],
              ['An welchem Fluss lebten die Parisier?', 'An der Seine', ['An der Loire', 'An der Rhone', 'An der Garonne']],
              ['Was war ein gallisches Oppidum?', 'Eine befestigte Stadt auf einem Hügel', ['Ein Tempel aus Stein', 'Ein Schiff', 'Ein Druidenhain']],
            ],
          },
        },
        {
          id: 'caesar-vercingetorix',
          title: 'Caesar und Vercingetorix',
          date: '58–46 v. Chr.',
          text: [
            '58 v. Chr. wurde Gaius Julius Caesar Statthalter in Gallien. Er suchte Ruhm, Beute und Macht für seine Karriere in Rom. Einen Anlass fand er sofort: Die Helvetier wollten aus der heutigen Schweiz nach Westen ziehen. Caesar besiegte sie bei Bibracte und zwang sie zur Rückkehr. Im selben Jahr schlug er den germanischen Heerführer Ariovist, der sich im Elsass festgesetzt hatte.',
            'Danach unterwarf Caesar Stamm um Stamm: 57 v. Chr. die Belger im Norden, 56 v. Chr. die Veneter in der Bretagne mit ihrer Flotte. 55 v. Chr. überquerte er auf einer Brücke als erster Römer den Rhein und setzte nach Britannien über; beides wiederholte er in den folgenden Jahren. Seinen Bericht „Commentarii de bello Gallico“ (Über den Gallischen Krieg) beginnt er mit dem berühmten Satz: „Gallia est omnis divisa in partes tres“ – ganz Gallien ist in drei Teile geteilt, bewohnt von Belgern, Aquitaniern und Kelten.',
            '52 v. Chr. erhoben sich fast alle gallischen Stämme. Ihr Anführer war Vercingetorix, ein junger Adliger der Arverner. Er ließ Dörfer und Vorräte verbrennen, damit die Römer nichts zu essen fanden (Taktik der verbrannten Erde), und besiegte Caesar bei Gergovia, seiner Heimatstadt.',
            'Schließlich zog sich Vercingetorix mit rund 80.000 Kriegern in die Festung Alesia in Burgund zurück. Caesar ließ zwei Ringe aus Wällen, Gräben und Fallen um die Stadt bauen: einen nach innen gegen die Belagerten und einen nach außen gegen ein gallisches Entsatzheer. Als dieses Heer gescheitert war und die Belagerten hungerten, ergab sich Vercingetorix. Er soll seine Waffen vor Caesar niedergelegt haben.',
            'Vercingetorix wurde nach Rom gebracht und sechs Jahre gefangen gehalten. 46 v. Chr. führte ihn Caesar in seinem Triumphzug vor; danach wurde er hingerichtet. Nach antiken Angaben, etwa bei Plutarch, kostete der Gallische Krieg rund eine Million Gallier das Leben, eine weitere Million wurde versklavt. Der Krieg dauerte bis 51/50 v. Chr.; mit Ruhm, Reichtum und einem treuen Heer überschritt Caesar 49 v. Chr. den Rubikon und griff nach der Macht in Rom.',
            'Im 19. Jahrhundert wurde Vercingetorix zum französischen Nationalhelden. Kaiser Napoleon III. ließ in Alesia (auf dem Mont Auxois beim heutigen Alise-Sainte-Reine) Ausgrabungen durchführen und 1865 eine riesige Statue des Galliers aufstellen. Für die Comics „Asterix“ ist die Niederlage von Alesia ein so heikles Thema, dass die Gallier dort behaupten, niemand wisse, wo Alesia liege.',
          ],
          quiz: {
            leicht: [
              ['Welcher römische Feldherr eroberte Gallien?', 'Julius Caesar', ['Augustus', 'Hannibal', 'Pompeius']],
              ['Wann begann Caesar den Krieg in Gallien?', '58 v. Chr.', ['121 v. Chr.', '9 n. Chr.', '476 n. Chr.']],
              ['Wer führte 52 v. Chr. den großen Aufstand der Gallier an?', 'Vercingetorix', ['Asterix', 'Brennus', 'Ariovist']],
              ['Zu welchem Stamm gehörte Vercingetorix?', 'Zu den Arvernern', ['Zu den Parisiern', 'Zu den Belgern', 'Zu den Helvetiern']],
              ['In welcher Festung wurde Vercingetorix eingeschlossen?', 'In Alesia', ['In Rom', 'In Gergovia', 'In Massalia']],
              ['Wo besiegte Vercingetorix Caesar?', 'Bei Gergovia', ['Bei Alesia', 'Bei Bibracte', 'Bei Rom']],
              ['Wie endete die Belagerung von Alesia?', 'Vercingetorix ergab sich', ['Caesar zog ab', 'Die Gallier eroberten Rom', 'Ein Frieden wurde geschlossen']],
              ['Was geschah mit Vercingetorix in Rom?', 'Er wurde vorgeführt und hingerichtet', ['Er wurde Senator', 'Er floh', 'Er wurde König Galliens']],
              ['Welches Buch schrieb Caesar über den Krieg?', '„Über den Gallischen Krieg“', ['„Germania“', '„Ilias“', '„Aeneis“']],
              ['In wie viele Teile war Gallien laut Caesar geteilt?', 'Drei', ['Zwei', 'Vier', 'Sieben']],
              ['Welchen Fluss überquerte Caesar als erster Römer?', 'Den Rhein', ['Die Seine', 'Die Donau', 'Den Nil']],
              ['Auf welche Insel setzte Caesar über?', 'Nach Britannien', ['Nach Sizilien', 'Nach Irland', 'Nach Korsika']],
              ['Wie nennt man es, Dörfer und Vorräte vor dem Feind zu verbrennen?', 'Taktik der verbrannten Erde', ['Blitzkrieg', 'Belagerung', 'Guerillakrieg']],
              ['Was ließ Caesar um Alesia bauen?', 'Zwei Ringe aus Wällen und Gräben', ['Eine Mauer aus Gold', 'Einen Kanal', 'Eine Brücke']],
              ['Welches Volk wollte 58 v. Chr. aus der Schweiz nach Westen ziehen?', 'Die Helvetier', ['Die Germanen', 'Die Belger', 'Die Veneter']],
              ['Wer wurde im 19. Jahrhundert französischer Nationalheld?', 'Vercingetorix', ['Caesar', 'Ariovist', 'Brennus']],
              ['Welcher Kaiser ließ eine Statue des Vercingetorix aufstellen?', 'Napoleon III.', ['Napoleon I.', 'Karl der Große', 'Ludwig XIV.']],
              ['Welche Gallier behaupten im Comic, niemand wisse, wo Alesia liegt?', 'Asterix und seine Freunde', ['Die Römer', 'Die Druiden der Carnuten', 'Die Belger']],
              ['Was suchte Caesar in Gallien?', 'Ruhm, Beute und Macht', ['Frieden', 'Eine Frau', 'Ein neues Zuhause']],
              ['Wie viele Gallier starben laut antiken Angaben etwa?', 'Rund eine Million', ['Rund tausend', 'Rund zehntausend', 'Rund hundert Millionen']],
            ],
            mittel: [
              ['Wo besiegte Caesar 58 v. Chr. die Helvetier?', 'Bei Bibracte', ['Bei Alesia', 'Bei Gergovia', 'Bei Narbo']],
              ['Welchen germanischen Heerführer schlug Caesar 58 v. Chr.?', 'Ariovist', ['Arminius', 'Marbod', 'Brennus']],
              ['Wo hatte sich Ariovist festgesetzt?', 'Im Elsass', ['In der Bretagne', 'In der Provence', 'In Paris']],
              ['Welches Volk unterwarf Caesar 57 v. Chr.?', 'Die Belger', ['Die Veneter', 'Die Arverner', 'Die Aquitanier']],
              ['Welches Volk mit einer Flotte unterwarf Caesar 56 v. Chr.?', 'Die Veneter', ['Die Belger', 'Die Haeduer', 'Die Helvetier']],
              ['Wo lebten die Veneter?', 'In der Bretagne', ['In Venedig', 'In Burgund', 'Im Elsass']],
              ['Wann überquerte Caesar zum ersten Mal den Rhein?', '55 v. Chr.', ['58 v. Chr.', '52 v. Chr.', '46 v. Chr.']],
              ['Wie beginnt Caesars Bericht?', '„Gallia est omnis divisa in partes tres“', ['„Arma virumque cano“', '„Veni, vidi, vici“', '„Alea iacta est“']],
              ['Welche drei Völker nennt Caesar für Gallien?', 'Belger, Aquitanier und Kelten', ['Franken, Goten und Römer', 'Helvetier, Germanen und Briten', 'Druiden, Krieger und Bauern']],
              ['Wann erhoben sich die Gallier unter Vercingetorix?', '52 v. Chr.', ['58 v. Chr.', '46 v. Chr.', '121 v. Chr.']],
              ['Was war Gergovia für Vercingetorix?', 'Seine Heimatstadt', ['Eine römische Festung', 'Ein Druidenhain', 'Eine Stadt in Germanien']],
              ['Wie viele Krieger hatte Vercingetorix in Alesia etwa?', 'Rund 80.000', ['Rund 800', 'Rund 8000', 'Rund 800.000']],
              ['Wozu diente Caesars äußerer Ring um Alesia?', 'Zur Abwehr eines gallischen Entsatzheeres', ['Als Viehweide', 'Als Rennbahn', 'Als Grenze nach Germanien']],
              ['In welcher Region liegt Alesia?', 'In Burgund', ['In der Bretagne', 'In der Normandie', 'In der Provence']],
              ['Wie lange wurde Vercingetorix in Rom gefangen gehalten?', 'Sechs Jahre', ['Sechs Tage', 'Sechs Monate', 'Sechzig Jahre']],
              ['Wann wurde Vercingetorix im Triumphzug vorgeführt?', '46 v. Chr.', ['52 v. Chr.', '44 v. Chr.', '58 v. Chr.']],
              ['Wie viele Gallier wurden laut antiken Angaben versklavt?', 'Rund eine Million', ['Rund tausend', 'Keiner', 'Alle']],
              ['Wie heißt der Ort bei Alesia heute?', 'Alise-Sainte-Reine', ['Clermont-Ferrand', 'Autun', 'Dijon']],
              ['Wann wurde die Vercingetorix-Statue in Alesia aufgestellt?', '1865', ['1789', '1815', '1914']],
              ['Was soll Vercingetorix bei seiner Kapitulation getan haben?', 'Seine Waffen vor Caesar niedergelegt', ['Caesar angegriffen', 'Sich selbst getötet', 'Eine Rede an Rom gehalten']],
            ],
            schwer: [
              ['Wie lautet der lateinische Titel von Caesars Kriegsbericht?', '„Commentarii de bello Gallico“', ['„De civitate Dei“', '„Res gestae“', '„Ab urbe condita“']],
              ['Gegen wen richtete sich Caesars innerer Ring um Alesia?', 'Gegen die Belagerten', ['Gegen ein Entsatzheer', 'Gegen Germanen', 'Gegen wilde Tiere']],
              ['Was gab es neben Wällen und Gräben noch an Caesars Belagerungsringen?', 'Fallen', ['Wassergräben mit Krokodilen', 'Türme aus Gold', 'Brücken']],
              ['Welches Amt hatte Caesar ab 58 v. Chr. in Gallien?', 'Statthalter (Prokonsul)', ['Kaiser', 'Volkstribun', 'Diktator auf Lebenszeit']],
              ['Wie oft überquerte Caesar insgesamt den Rhein?', 'Zweimal', ['Einmal', 'Dreimal', 'Gar nicht']],
              ['Was veranlasste die Helvetier, Caesar zu provozieren?', 'Ihr geplanter Zug nach Westen', ['Ein Angriff auf Rom', 'Ein Bündnis mit Karthago', 'Eine Hungersnot in Rom']],
              ['Woran scheiterte die Verteidigung von Alesia vor allem?', 'Am Scheitern des Entsatzheeres und am Hunger', ['An einem Erdbeben', 'An Verrat der Druiden', 'An einer Pestwelle in Rom']],
              ['Wer ließ in Alesia im 19. Jahrhundert Ausgrabungen durchführen?', 'Napoleon III.', ['Ludwig XVI.', 'Charles de Gaulle', 'Napoleon I.']],
              ['Was tat Vercingetorix mit Dörfern und Vorräten?', 'Er ließ sie verbrennen', ['Er verkaufte sie an Rom', 'Er verschenkte sie an Caesar', 'Er versteckte sie in Alesia']],
              ['Welche Rolle spielte Vercingetorix im Nationalgefühl des 19. Jahrhunderts?', 'Er wurde als erster Held Frankreichs verehrt', ['Er wurde als Verräter gesehen', 'Er war vergessen', 'Er galt als Römer']],
              ['Wie viele Jahre dauerte Caesars Krieg in Gallien etwa?', 'Rund acht Jahre', ['Ein Jahr', 'Dreißig Jahre', 'Hundert Jahre']],
              ['Welche Insel besuchte Caesar 55 und 54 v. Chr.?', 'Britannien', ['Irland', 'Sardinien', 'Kreta']],
              ['Was erzählen die Asterix-Comics über Alesia?', 'Dass niemand wisse, wo es liegt', ['Dass die Gallier dort siegten', 'Dass Caesar dort starb', 'Dass Obelix es gründete']],
              ['Wer war in der Antike für die Zahl von einer Million toten Galliern die Quelle?', 'Antike Schriftsteller wie Plutarch', ['Druidenbücher', 'Gallische Chroniken', 'Ägyptische Papyri']],
              ['Was bedeutet „Gallia est omnis divisa in partes tres“?', 'Ganz Gallien ist in drei Teile geteilt', ['Gallien ist frei', 'Gallien gehört Rom', 'Gallien hat drei Könige']],
              ['Welche Rolle spielten die Kelten in Caesars Dreiteilung?', 'Sie bewohnten den mittleren Teil', ['Sie lebten nur im Norden', 'Sie lebten in Britannien', 'Sie waren Römer']],
              ['Was erhielt Caesar durch den Gallischen Krieg für seine Karriere?', 'Ruhm, Reichtum und ein treues Heer', ['Nichts', 'Eine Strafe des Senats', 'Ein Bistum']],
              ['Welches Ereignis folgte 49 v. Chr. auf den Gallischen Krieg?', 'Caesar überschritt den Rubikon', ['Caesar wurde ermordet', 'Augustus wurde Kaiser', 'Gallien wurde frei']],
              ['Wie heißt der Hügel von Alesia heute?', 'Mont Auxois', ['Mont Blanc', 'Montmartre', 'Mont Ventoux']],
              ['Wie hieß Vercingetorix’ Volk in seiner Hauptstadt Gergovia?', 'Arverner', ['Haeduer', 'Senonen', 'Parisier']],
            ],
          },
        },
        {
          id: 'gallia-romana',
          title: 'Das römische Gallien',
          date: '52 v. Chr. – 476 n. Chr.',
          text: [
            'Nach der Eroberung gliederte Kaiser Augustus Gallien in vier Provinzen: Narbonensis im Süden sowie Aquitania, Lugdunensis und Belgica, die man zusammen die „Tres Galliae“ (drei Gallien) nannte. Hauptort der drei Gallien war Lugdunum, das heutige Lyon. Dort stand ab 12 v. Chr. der Altar der drei Gallien, an dem sich jedes Jahr Vertreter der Stämme versammelten. Kaiser Claudius wurde 10 v. Chr. in Lyon geboren.',
            'Die Römer bauten Straßen, Städte, Bäder, Theater und Wasserleitungen. Der Pont du Gard, eine dreistöckige Brücke, gehört zu einem Aquädukt, das im 1. Jahrhundert die Stadt Nemausus (Nîmes) mit Wasser versorgte. In Nîmes stehen bis heute der gut erhaltene Tempel „Maison Carrée“ und ein Amphitheater, ebenso in Arles (Arelate); in Orange steht ein großes römisches Theater. Bordeaux hieß Burdigala, Paris hieß damals Lutetia und lag vor allem auf der Seine-Insel und am linken Ufer.',
            'Die Gallier übernahmen rasch die römische Lebensweise. Die Oberschicht sprach Latein, trug Togen und erhielt das römische Bürgerrecht; Gallier saßen sogar im Senat. Aus dem gesprochenen Latein entwickelte sich über viele Jahrhunderte das Französische. Man spricht von der gallo-römischen Kultur.',
            'Früh kam das Christentum ins Land. 177 starben in Lyon zahlreiche Christen als Märtyrer, darunter die Sklavin Blandina. Der heilige Dionysius (Saint Denis), der erste Bischof von Paris, wurde um 250 enthauptet; der Legende nach trug er seinen Kopf noch ein Stück weit – in der Kunst nennt man solche Heiligen Kephalophoren (Kopfträger). Martin von Tours, ein ehemaliger Soldat, der der Legende nach in Amiens seinen Mantel mit einem Bettler teilte, wurde 371 Bischof von Tours und gründete mit Ligugé und Marmoutier die ersten Klöster Galliens.',
            'Im 3. Jahrhundert geriet das Reich in eine Krise. Von 260 bis 274 bestand sogar ein eigenes „Gallisches Sonderreich“ unter Kaisern wie Postumus. Germanische Völker fielen immer wieder ein. Im 5. Jahrhundert ließen sich die Westgoten (mit der Hauptstadt Toulouse), die Burgunder (im Rhonetal und am Genfersee) und die Franken in Gallien nieder.',
            '451 besiegten Römer und Germanen unter dem Feldherrn Aëtius die Hunnen Attilas in der Schlacht auf den Katalaunischen Feldern in der Champagne. Der Legende nach hatte die heilige Genoveva (Sainte Geneviève) die Pariser zuvor ermutigt, nicht zu fliehen; sie ist bis heute Schutzpatronin von Paris. 476 endete das Weströmische Reich.',
          ],
          quiz: {
            leicht: [
              ['Wie hieß Paris in römischer Zeit?', 'Lutetia', ['Lugdunum', 'Massalia', 'Nemausus']],
              ['Wie hieß Lyon in römischer Zeit?', 'Lugdunum', ['Lutetia', 'Narbo', 'Arelate']],
              ['Welche berühmte römische Brücke gehört zu einem Aquädukt?', 'Der Pont du Gard', ['Der Pont Neuf', 'Die Pont Alexandre III', 'Die Brücke von Avignon']],
              ['Welche Stadt versorgte der Pont du Gard mit Wasser?', 'Nîmes', ['Paris', 'Marseille', 'Lyon']],
              ['Aus welcher Sprache entwickelte sich das Französische?', 'Aus dem Latein', ['Aus dem Griechischen', 'Aus dem Keltischen', 'Aus dem Germanischen']],
              ['Was bauten die Römer in Gallien?', 'Straßen, Städte und Wasserleitungen', ['Pyramiden', 'Burgen', 'Kathedralen']],
              ['Wer war der erste Bischof von Paris?', 'Der heilige Dionysius (Saint Denis)', ['Der heilige Martin', 'Der heilige Petrus', 'Der heilige Remigius']],
              ['Was tat der heilige Martin der Legende nach?', 'Er teilte seinen Mantel mit einem Bettler', ['Er tötete einen Drachen', 'Er baute eine Brücke', 'Er eroberte Rom']],
              ['Wo war Martin Bischof?', 'In Tours', ['In Paris', 'In Lyon', 'In Rom']],
              ['Wer ist die Schutzpatronin von Paris?', 'Die heilige Genoveva', ['Die heilige Johanna', 'Die heilige Maria Magdalena', 'Die heilige Blandina']],
              ['Gegen wen kämpften Römer und Germanen 451?', 'Gegen die Hunnen', ['Gegen die Wikinger', 'Gegen die Araber', 'Gegen die Gallier']],
              ['Wie hieß der König der Hunnen?', 'Attila', ['Alarich', 'Chlodwig', 'Brennus']],
              ['Wann endete das Weströmische Reich?', '476', ['52 v. Chr.', '800', '1066']],
              ['Welcher römische Kaiser wurde in Lyon geboren?', 'Claudius', ['Augustus', 'Nero', 'Konstantin']],
              ['Welcher Kaiser gliederte Gallien in Provinzen?', 'Augustus', ['Caesar', 'Nero', 'Trajan']],
              ['Wie nennt man die Mischung aus gallischer und römischer Kultur?', 'Gallo-römische Kultur', ['Keltisch-griechische Kultur', 'Fränkische Kultur', 'Byzantinische Kultur']],
              ['Welche Religion verbreitete sich in Gallien während der Römerzeit?', 'Das Christentum', ['Der Islam', 'Der Buddhismus', 'Das Judentum']],
              ['Welches Gebäude in Nîmes ist ein gut erhaltener römischer Tempel?', 'Die Maison Carrée', ['Der Louvre', 'Die Sainte-Chapelle', 'Der Panthéon']],
              ['In welcher Stadt steht ein großes römisches Theater?', 'In Orange', ['In Calais', 'In Lille', 'In Brest']],
              ['Welches germanische Volk machte Toulouse zur Hauptstadt?', 'Die Westgoten', ['Die Franken', 'Die Burgunder', 'Die Vandalen']],
            ],
            mittel: [
              ['In wie viele Provinzen gliederte Augustus Gallien?', 'Vier', ['Zwei', 'Drei', 'Sieben']],
              ['Wie nannte man Aquitania, Lugdunensis und Belgica zusammen?', '„Tres Galliae“', ['„Gallia Narbonensis“', '„Gallia Cisalpina“', '„Septem Provinciae“']],
              ['Was stand ab 12 v. Chr. in Lyon?', 'Der Altar der drei Gallien', ['Das Kolosseum', 'Der Pont du Gard', 'Ein Druidenhain']],
              ['Wann wurde Kaiser Claudius geboren?', '10 v. Chr.', ['52 v. Chr.', '44 v. Chr.', '41 n. Chr.']],
              ['In welchem Jahrhundert entstand der Pont du Gard?', 'Im 1. Jahrhundert', ['Im 5. Jahrhundert', 'Im 12. Jahrhundert', 'Im 3. Jahrhundert v. Chr.']],
              ['Wie viele Stockwerke hat der Pont du Gard?', 'Drei', ['Eines', 'Zwei', 'Fünf']],
              ['Wie hieß Nîmes in römischer Zeit?', 'Nemausus', ['Narbo', 'Arelate', 'Arausio']],
              ['In welchen Städten stehen römische Amphitheater?', 'In Nîmes und Arles', ['In Paris und Lille', 'In Brest und Calais', 'In Straßburg und Metz']],
              ['Wo lag Lutetia vor allem?', 'Auf der Seine-Insel und am linken Ufer', ['Auf dem Montmartre', 'Am Meer', 'An der Loire']],
              ['Welches Recht erhielt die gallische Oberschicht?', 'Das römische Bürgerrecht', ['Das Recht auf einen König', 'Das Druidenrecht', 'Kein Recht']],
              ['Wann starben in Lyon viele Christen als Märtyrer?', '177', ['451', '52 v. Chr.', '800']],
              ['Welche Sklavin gehörte zu den Märtyrern von Lyon?', 'Blandina', ['Genoveva', 'Johanna', 'Radegunde']],
              ['Um welches Jahr wurde Saint Denis enthauptet?', 'Um 250', ['Um 50', 'Um 500', 'Um 800']],
              ['Was soll Saint Denis der Legende nach nach seiner Enthauptung getan haben?', 'Seinen Kopf noch ein Stück weit getragen', ['Ein Lied gesungen', 'Paris verflucht', 'Eine Kirche gebaut']],
              ['In welcher Stadt teilte Martin seinen Mantel?', 'In Amiens', ['In Tours', 'In Paris', 'In Rom']],
              ['Wann wurde Martin Bischof von Tours?', '371', ['177', '451', '496']],
              ['Wie lange bestand das Gallische Sonderreich?', 'Von 260 bis 274', ['Von 52 v. Chr. bis 476', 'Von 400 bis 500', 'Nur ein Jahr']],
              ['Welcher römische Feldherr siegte 451 über Attila?', 'Aëtius', ['Stilicho', 'Caesar', 'Belisar']],
              ['Wo fand die Schlacht von 451 statt?', 'Auf den Katalaunischen Feldern', ['Bei Alesia', 'Bei Poitiers', 'Bei Soissons']],
              ['Welche germanischen Völker ließen sich im 5. Jahrhundert in Gallien nieder?', 'Westgoten, Burgunder und Franken', ['Sachsen, Angeln und Jüten', 'Vandalen, Alanen und Sueben', 'Wikinger und Normannen']],
            ],
            schwer: [
              ['Was geschah jährlich am Altar der drei Gallien?', 'Vertreter der Stämme versammelten sich', ['Gladiatoren kämpften', 'Druiden opferten Menschen', 'Der Kaiser wurde gekrönt']],
              ['Welcher Kaiser des Gallischen Sonderreichs ist bekannt?', 'Postumus', ['Postumius', 'Constantius', 'Aurelian']],
              ['In welcher Landschaft liegen die Katalaunischen Felder?', 'In der Champagne', ['In der Bretagne', 'In der Provence', 'Im Elsass']],
              ['Was tat die heilige Genoveva der Legende nach 451?', 'Sie ermutigte die Pariser, nicht zu fliehen', ['Sie besiegte Attila im Zweikampf', 'Sie öffnete die Tore', 'Sie floh nach Rom']],
              ['Welche Klöster gründete Martin von Tours?', 'Die ersten Klöster Galliens (Ligugé, Marmoutier)', ['Cluny und Cîteaux', 'Saint-Denis und Fulda', 'Mont-Saint-Michel']],
              ['Welchen Beruf hatte Martin von Tours zuerst?', 'Soldat', ['Bauer', 'Kaufmann', 'Sklave']],
              ['Warum hatte Gallien im 3. Jahrhundert ein Sonderreich?', 'Wegen einer Krise des Römischen Reiches', ['Weil die Druiden herrschten', 'Weil Caesar es schuf', 'Weil die Franken es gründeten']],
              ['In welcher Provinz lag Lutetia?', 'In der Lugdunensis', ['In der Narbonensis', 'In der Belgica', 'In der Aquitania']],
              ['Welche Stadt war Hauptort der „Tres Galliae“?', 'Lugdunum', ['Lutetia', 'Narbo', 'Treveri']],
              ['Woran erkennt man, dass Gallier hohe römische Ämter erreichten?', 'Gallier saßen im Senat', ['Gallier wurden Pharaonen', 'Gallier regierten Karthago', 'Gallier waren Päpste']],
              ['Wie hieß Arles in römischer Zeit?', 'Arelate', ['Arausio', 'Nemausus', 'Burdigala']],
              ['Wie hieß Bordeaux in römischer Zeit?', 'Burdigala', ['Burgundia', 'Bononia', 'Brigantium']],
              ['Was ist die Maison Carrée?', 'Ein römischer Tempel', ['Ein Wohnhaus', 'Ein Aquädukt', 'Ein Theater']],
              ['Wie nennt man Heilige, die ihren Kopf tragen, in der Kunst?', 'Kephalophoren', ['Stigmatisierte', 'Märtyrerkönige', 'Kirchenväter']],
              ['Wann entstand der Altar der drei Gallien?', '12 v. Chr.', ['52 v. Chr.', '177', '451']],
              ['Woher kam das Französische letztlich?', 'Aus dem gesprochenen Volkslatein', ['Aus dem klassischen Griechisch', 'Aus der Sprache der Franken', 'Aus dem Keltischen ohne Latein']],
              ['Welches Ereignis markiert das Jahr 476?', 'Das Ende des Weströmischen Reiches', ['Die Taufe Chlodwigs', 'Die Schlacht auf den Katalaunischen Feldern', 'Die Gründung von Paris']],
              ['Wofür ist die Stadt Orange bekannt?', 'Für ihr römisches Theater', ['Für ihre Kathedrale', 'Für ihren Hafen', 'Für ihre Universität']],
              ['Welcher Teil Galliens war besonders stark romanisiert?', 'Der Süden', ['Der Nordosten', 'Die Bretagne', 'Die Alpen']],
              ['Welche Gruppe zog im 5. Jahrhundert ins Rhonetal und an den Genfersee?', 'Die Burgunder', ['Die Franken', 'Die Westgoten', 'Die Bretonen']],
            ],
          },
        },
      ],
    },
    {
      id: 'franken',
      title: 'Das Reich der Franken',
      date: '481–987',
      text: [
        'Die Franken gaben Frankreich seinen Namen. Mit Chlodwig begann ein katholisches Königtum, dessen Könige in Reims gesalbt wurden – eine Tradition, die bis ins 19. Jahrhundert reichte. Nach Karl dem Großen zerfiel das Reich; aus seinem Westteil wurde nach und nach Frankreich.',
      ],
      subtopics: [
        {
          id: 'chlodwig-merowinger',
          title: 'Chlodwig und die Merowinger',
          date: '481–751',
          text: [
            'Chlodwig (französisch Clovis) wurde um 481 König der salischen Franken; die wichtigste Quelle über ihn ist der Bischof Gregor von Tours. Viele Franzosen sehen in ihm den ersten König Frankreichs; der Name Louis, den 18 französische Könige trugen, ist eine Form von Chlodwig. 486 besiegte er bei Soissons Syagrius, den letzten römischen Machthaber in Nordgallien.',
            'Nach der Schlacht soll sich die Geschichte vom „Krug von Soissons“ ereignet haben: Chlodwig wollte einem Bischof einen kostbaren Krug aus der Beute zurückgeben, doch ein Krieger zerschlug ihn mit der Axt, weil jeder seinen Anteil wollte. Ein Jahr später erschlug Chlodwig den Krieger und erinnerte ihn an den Krug – eine Geschichte über die wachsende Macht des Königs.',
            'Um 496 ließ sich Chlodwig, angeregt von seiner katholischen Frau Chlothilde, einer burgundischen Prinzessin, von Bischof Remigius in Reims taufen. Eine spätere Legende erzählt, eine Taube habe dabei ein Fläschchen mit heiligem Öl gebracht, die „Sainte Ampoule“. Mit diesem Öl wurden später fast alle französischen Könige in der Kathedrale von Reims gesalbt. Da die anderen germanischen Könige Arianer waren, gewann Chlodwig die Unterstützung der katholischen Bischöfe.',
            '507 besiegte Chlodwig die Westgoten bei Vouillé und eroberte Aquitanien; Paris machte er zu seiner Hauptstadt. Er ließ das fränkische Recht als „Lex Salica“ aufschreiben. Ein Satz daraus wurde im 14. Jahrhundert genutzt, um Frauen und ihre Nachkommen von der französischen Krone auszuschließen („salisches Gesetz“). Chlodwig starb 511 und wurde in Paris begraben.',
            'Seine Nachkommen, die Merowinger, teilten das Reich immer wieder. König Dagobert I. (gestorben 639) förderte die Abtei Saint-Denis bei Paris, die zur Grablege der französischen Könige wurde. Danach verloren die Könige ihre Macht an die Hausmeier.',
            'Der Hausmeier Karl Martell (Charles Martel) besiegte 732 zwischen Tours und Poitiers ein arabisches Heer aus Spanien. In Frankreich gilt die Schlacht als Rettung des christlichen Abendlandes, auch wenn Historiker ihre Bedeutung heute vorsichtiger sehen. 751 setzte Karl Martells Sohn Pippin den letzten Merowinger ab und wurde König – die Karolinger begannen.',
          ],
          quiz: {
            leicht: [
              ['Wie heißt Chlodwig auf Französisch?', 'Clovis', ['Charles', 'Louis', 'Philippe']],
              ['Welcher Name französischer Könige ist eine Form von Chlodwig?', 'Louis', ['Henri', 'Charles', 'François']],
              ['Wo wurde Chlodwig getauft?', 'In Reims', ['In Paris', 'In Rom', 'In Soissons']],
              ['Welche Stadt machte Chlodwig zur Hauptstadt?', 'Paris', ['Reims', 'Lyon', 'Orléans']],
              ['Wer gab Frankreich seinen Namen?', 'Die Franken', ['Die Gallier', 'Die Römer', 'Die Normannen']],
              ['Wie hieß Chlodwigs katholische Frau?', 'Chlothilde', ['Genoveva', 'Blandina', 'Brunichild']],
              ['Wo wurden fast alle französischen Könige gesalbt?', 'In der Kathedrale von Reims', ['In Notre-Dame de Paris', 'In Saint-Denis', 'In Versailles']],
              ['Was brachte laut Legende eine Taube bei Chlodwigs Taufe?', 'Ein Fläschchen mit heiligem Öl', ['Eine Krone', 'Ein Schwert', 'Einen Brief des Papstes']],
              ['Wie heißt dieses Fläschchen?', 'Sainte Ampoule', ['Saint Graal', 'Sainte Chapelle', 'Sainte Croix']],
              ['Wie hieß Chlodwigs Königsfamilie?', 'Die Merowinger', ['Die Kapetinger', 'Die Karolinger', 'Die Valois']],
              ['Welche Abtei wurde zur Grablege der französischen Könige?', 'Saint-Denis', ['Cluny', 'Mont-Saint-Michel', 'Fontevraud']],
              ['Wer besiegte 732 ein arabisches Heer?', 'Karl Martell', ['Chlodwig', 'Karl der Große', 'Dagobert']],
              ['Wie heißt Karl Martell auf Französisch?', 'Charles Martel', ['Charlemagne', 'Charles le Chauve', 'Charles le Simple']],
              ['Woher kam das arabische Heer 732?', 'Aus Spanien', ['Aus Italien', 'Aus Afrika direkt über Sizilien', 'Aus der Türkei']],
              ['Wann starb Chlodwig?', '511', ['496', '732', '800']],
              ['Welche Familie folgte 751 den Merowingern?', 'Die Karolinger', ['Die Kapetinger', 'Die Bourbonen', 'Die Valois']],
              ['Wer setzte 751 den letzten Merowinger ab?', 'Pippin', ['Karl Martell', 'Chlodwig', 'Dagobert']],
              ['Wie heißt das Gesetzbuch der Franken?', 'Lex Salica', ['Code civil', 'Magna Carta', 'Sachsenspiegel']],
              ['Welcher Bischof taufte Chlodwig?', 'Remigius', ['Martin', 'Dionysius', 'Bonifatius']],
              ['Welche Geschichte erzählt von einem zerschlagenen Gefäß?', 'Der Krug von Soissons', ['Die Vase von Versailles', 'Der Becher von Reims', 'Die Schale von Paris']],
            ],
            mittel: [
              ['Wann wurde Chlodwig König?', 'Um 481', ['Um 400', 'Um 511', 'Um 732']],
              ['Wen besiegte Chlodwig 486 bei Soissons?', 'Syagrius', ['Alarich II.', 'Attila', 'Aëtius']],
              ['Wann ließ sich Chlodwig taufen?', 'Um 496', ['Um 481', 'Um 511', 'Um 600']],
              ['Wen besiegte Chlodwig 507 bei Vouillé?', 'Die Westgoten', ['Die Burgunder', 'Die Alamannen', 'Die Hunnen']],
              ['Welche Region eroberte Chlodwig 507?', 'Aquitanien', ['Die Bretagne', 'Burgund', 'Die Provence']],
              ['Warum unterstützten die Bischöfe Chlodwig?', 'Weil er katholisch war, die anderen Germanenkönige Arianer', ['Weil er Rom eroberte', 'Weil er Bischof war', 'Weil er Latein sprach']],
              ['Was geschah mit dem Krieger, der den Krug zerschlug?', 'Chlodwig erschlug ihn ein Jahr später', ['Er wurde König', 'Er wurde Bischof', 'Er bekam den Krug']],
              ['Wofür steht die Geschichte vom Krug von Soissons?', 'Für die wachsende Macht des Königs', ['Für die Armut der Franken', 'Für die Kunst der Römer', 'Für die Macht der Bischöfe']],
              ['Wozu wurde ein Satz der Lex Salica im 14. Jahrhundert genutzt?', 'Um Frauen von der Krone auszuschließen', ['Um die Steuern zu senken', 'Um den Papst zu wählen', 'Um Kriege zu verbieten']],
              ['Welcher Merowinger förderte die Abtei Saint-Denis?', 'Dagobert I.', ['Chlodwig', 'Childerich III.', 'Chilperich']],
              ['Wann starb Dagobert I.?', '639', ['511', '732', '751']],
              ['An wen verloren die Merowingerkönige ihre Macht?', 'An die Hausmeier', ['An die Päpste', 'An die Araber', 'An die Bauern']],
              ['Wie viele französische Könige hießen Louis?', '18', ['5', '10', '30']],
              ['Zwischen welchen Städten fand die Schlacht von 732 statt?', 'Zwischen Tours und Poitiers', ['Zwischen Paris und Reims', 'Zwischen Lyon und Marseille', 'Zwischen Bordeaux und Toulouse']],
              ['Wessen Sohn war Pippin?', 'Karl Martells', ['Chlodwigs', 'Dagoberts', 'Karls des Großen']],
              ['Welchen Glauben hatten viele andere germanische Könige?', 'Den Arianismus', ['Den Islam', 'Das Judentum', 'Den Druidenglauben']],
              ['Wo wurde Chlodwig begraben?', 'In Paris', ['In Reims', 'In Saint-Denis', 'In Soissons']],
              ['Welcher Teil der Franken war Chlodwigs Volk?', 'Die salischen Franken', ['Die ripuarischen Franken', 'Die Ostfranken', 'Die Sachsen']],
              ['Wie sehen Historiker die Bedeutung der Schlacht von 732 heute?', 'Vorsichtiger als früher', ['Als völlig unwichtig', 'Als größte Schlacht der Welt', 'Als Erfindung']],
              ['Wie gilt die Schlacht von 732 in Frankreich traditionell?', 'Als Rettung des christlichen Abendlandes', ['Als schwerste Niederlage', 'Als Beginn der Revolution', 'Als Ende der Römerzeit']],
            ],
            schwer: [
              ['Was war Syagrius?', 'Der letzte römische Machthaber in Nordgallien', ['Ein Westgotenkönig', 'Ein Bischof von Reims', 'Ein Hunnenführer']],
              ['Womit zerschlug der Krieger den Krug?', 'Mit einer Axt', ['Mit einem Schwert', 'Mit einem Stein', 'Mit der Faust']],
              ['Wem wollte Chlodwig den Krug zurückgeben?', 'Einem Bischof', ['Dem Papst', 'Seiner Frau', 'Dem Kaiser']],
              ['Mit welchem Öl wurden französische Könige laut Tradition gesalbt?', 'Mit dem Öl der Sainte Ampoule', ['Mit Olivenöl aus Rom', 'Mit Öl aus Jerusalem', 'Mit Lavendelöl']],
              ['Wann wurde das „salische Gesetz“ gegen weibliche Thronfolge genutzt?', 'Im 14. Jahrhundert', ['Im 6. Jahrhundert', 'Im 18. Jahrhundert', 'Im 9. Jahrhundert']],
              ['Bis wann reichte die Tradition der Salbung in Reims etwa?', 'Bis ins 19. Jahrhundert', ['Bis 800', 'Bis 1066', 'Bis heute']],
              ['Was ist die Grablege von Saint-Denis?', 'Begräbnisort der französischen Könige', ['Ein Kloster für Nonnen', 'Ein römisches Theater', 'Ein Druidenfriedhof']],
              ['Was bedeutet „Hausmeier“?', 'Verwalter des königlichen Hofes', ['Hausmeister eines Klosters', 'Ein Bürgermeister', 'Ein Heerführer der Araber']],
              ['Wann setzte Pippin den letzten Merowinger ab?', '751', ['732', '768', '800']],
              ['Wo liegt Vouillé?', 'Bei Poitiers', ['Bei Paris', 'Bei Reims', 'Bei Lyon']],
              ['Wie viele Jahre nach seiner Taufe starb Chlodwig etwa?', 'Etwa 15 Jahre', ['Etwa 1 Jahr', 'Etwa 50 Jahre', 'Etwa 100 Jahre']],
              ['Welches Werk berichtet über Chlodwig?', 'Die Geschichte des Gregor von Tours', ['Caesars Gallischer Krieg', 'Die Chanson de Roland', 'Der Code civil']],
              ['Was war der Grund für die Teilungen des Merowingerreiches?', 'Das Reich wurde unter allen Söhnen aufgeteilt', ['Der Papst teilte es', 'Kriege mit Rom', 'Naturkatastrophen']],
              ['Von welchem Bischof wurde Chlodwig getauft und an welchem Ort?', 'Von Remigius in Reims', ['Von Martin in Tours', 'Von Dionysius in Paris', 'Von Gregor in Tours']],
              ['Was ist das Besondere an den Königen von Reims nach Chlodwig?', 'Sie wurden dort gesalbt und galten so als heilige Könige', ['Sie wurden dort begraben', 'Sie wurden dort gewählt', 'Sie wurden dort geboren']],
              ['Wie viele Könige wurden nach der Tradition in Reims gesalbt?', 'Fast alle französischen Könige', ['Nur Chlodwig', 'Nur die Kapetinger', 'Keiner']],
              ['Welche Frau überzeugte Chlodwig vom Christentum?', 'Chlothilde, eine Burgunderin', ['Genoveva, eine Pariserin', 'Blandina, eine Sklavin', 'Radegunde, eine Thüringerin']],
              ['Wann besiegte Karl Martell die Araber?', '732', ['751', '711', '778']],
              ['Welches Gebiet beherrschten die Araber 732 bereits?', 'Spanien', ['Italien', 'Frankreich', 'Germanien']],
              ['Welcher Merowingerkönig gilt als letzter starker Herrscher?', 'Dagobert I.', ['Childerich III.', 'Chilperich I.', 'Sigibert I.']],
            ],
          },
        },
        {
          id: 'karolinger-westfranken',
          title: 'Karolinger, Wikinger und das Westfrankenreich',
          date: '751–987',
          text: [
            'Karl der Große – auf Französisch Charlemagne – gilt in Frankreich wie in Deutschland als „Vater Europas“. 800 wurde er in Rom zum Kaiser gekrönt. Das französische Heldenepos „Chanson de Roland“ (Rolandslied) aus dem 11. Jahrhundert erzählt, wie sein Neffe Roland 778 im Pyrenäental von Roncesvalles fiel – und wie er dabei in sein Horn Olifant blies, um Karl zu rufen. Im Lied kämpft Roland mit seinem Freund Olivier und seinem Schwert Durendal gegen die Sarazenen (Muslime) statt, wie historisch, gegen Basken; verraten wurde er von Ganelon. Karls eigenes Schwert hieß der Sage nach Joyeuse.',
            'Im Vertrag von Verdun 843 erhielt Karl der Kahle (Charles le Chauve) das Westfrankenreich, aus dem Frankreich hervorging. Die Straßburger Eide von 842, die er mit seinem Bruder Ludwig schwor, sind das älteste Schriftstück in einer frühen Form des Französischen.',
            'Im 9. Jahrhundert fuhren Wikinger mit ihren Booten die Flüsse hinauf und plünderten Städte und Klöster. 845 belagerten sie Paris und zogen erst gegen ein hohes Lösegeld ab. 885/886 verteidigte Graf Odo (Eudes) von Paris die Stadt monatelang erfolgreich gegen ein großes Wikingerheer. Dafür wählten ihn die Großen 888 zum König – als ersten aus der Familie der Robertiner, die mit den Karolingern um die Krone rang.',
            '911 schloss König Karl der Einfältige (Charles le Simple) mit dem Wikingerführer Rollo den Vertrag von Saint-Clair-sur-Epte: Rollo erhielt das Land um Rouen an der unteren Seine, ließ sich taufen und sollte das Reich gegen andere Wikinger verteidigen. Aus diesem Gebiet der „Nordmänner“ wurde die Normandie. Rollos Nachfahre Wilhelm der Eroberer eroberte 1066 England.',
            'Die Könige wurden immer schwächer, und mächtige Herzöge und Grafen herrschten fast selbstständig. Überall entstanden Burgen. In Burgund wurde 910 das Kloster Cluny gegründet, das eine große Reformbewegung der Kirche anführte. Mit dem „Gottesfrieden“ (zuerst 989 in Charroux) versuchte die Kirche, die Gewalt der Ritter gegen Wehrlose einzudämmen.',
            '987 starb der letzte westfränkische Karolinger, Ludwig V., genannt „der Faule“, nach einem Jagdunfall bei Senlis. Die Großen wählten in Senlis Hugo Capet, einen Robertiner, zum König; er wurde im Juli 987 gekrönt. Seine Familie, die Kapetinger, regierte Frankreich in direkter Linie und in Nebenlinien (Valois, Bourbonen) bis 1848. 987 gilt deshalb oft als Geburtsjahr des französischen Königtums.',
          ],
          quiz: {
            leicht: [
              ['Wie heißt Karl der Große auf Französisch?', 'Charlemagne', ['Charles Martel', 'Carlos Magno', 'Charles le Chauve']],
              ['Wann wurde Karl der Große Kaiser?', '800', ['843', '911', '987']],
              ['Welches französische Heldenepos erzählt von Roland?', 'Die Chanson de Roland', ['Der Roman de la Rose', 'Les Misérables', 'Die Marseillaise']],
              ['Wie hieß Rolands Horn?', 'Olifant', ['Excalibur', 'Durendal', 'Gjallarhorn']],
              ['Wer erhielt 843 das Westfrankenreich?', 'Karl der Kahle', ['Ludwig der Deutsche', 'Lothar', 'Karl der Große']],
              ['Aus welchem Teilreich ging Frankreich hervor?', 'Aus dem Westfrankenreich', ['Aus dem Ostfrankenreich', 'Aus dem Mittelreich', 'Aus Burgund']],
              ['Welche Seeräuber plünderten im 9. Jahrhundert Frankreich?', 'Die Wikinger', ['Die Piraten der Karibik', 'Die Römer', 'Die Hunnen']],
              ['Welche Stadt belagerten die Wikinger 845?', 'Paris', ['Rom', 'London', 'Aachen']],
              ['Wer verteidigte Paris 885/886 gegen die Wikinger?', 'Graf Odo', ['Karl der Große', 'Rollo', 'Hugo Capet']],
              ['Welcher Wikingerführer bekam 911 Land?', 'Rollo', ['Ragnar', 'Erik der Rote', 'Harald Blauzahn']],
              ['Welche Region entstand aus dem Land der Wikinger?', 'Die Normandie', ['Die Bretagne', 'Die Picardie', 'Die Champagne']],
              ['Woher kommt der Name Normandie?', 'Von den „Nordmännern“', ['Von einem König Norman', 'Von einem Fluss', 'Von den Normen der Kirche']],
              ['Welcher Nachfahre Rollos eroberte 1066 England?', 'Wilhelm der Eroberer', ['Richard Löwenherz', 'Hugo Capet', 'Karl der Kahle']],
              ['Welches berühmte Kloster wurde 910 in Burgund gegründet?', 'Cluny', ['Cîteaux', 'Saint-Denis', 'Mont-Saint-Michel']],
              ['Wer wurde 987 König von Frankreich?', 'Hugo Capet', ['Ludwig V.', 'Odo', 'Rollo']],
              ['Wie heißt Hugo Capets Herrscherfamilie?', 'Die Kapetinger', ['Die Karolinger', 'Die Merowinger', 'Die Habsburger']],
              ['Woran starb der letzte westfränkische Karolinger?', 'An einem Jagdunfall', ['In einer Schlacht', 'An der Pest', 'Durch Gift']],
              ['Was versuchte die Kirche mit dem „Gottesfrieden“?', 'Die Gewalt gegen Wehrlose einzudämmen', ['Kriege gegen England zu beginnen', 'Steuern zu erhöhen', 'Burgen zu bauen']],
              ['Was entstand im 10. Jahrhundert überall in Frankreich?', 'Burgen', ['Fabriken', 'Universitäten', 'Bahnhöfe']],
              ['Welches Jahr gilt oft als Geburtsjahr des französischen Königtums?', '987', ['843', '800', '1066']],
            ],
            mittel: [
              ['Wann fiel Roland?', '778', ['732', '800', '843']],
              ['In welchem Tal fiel Roland?', 'In Roncesvalles', ['In Poitiers', 'Im Loiretal', 'In Verdun']],
              ['Wann entstand die Chanson de Roland?', 'Im 11. Jahrhundert', ['Im 8. Jahrhundert', 'Im 15. Jahrhundert', 'Im 19. Jahrhundert']],
              ['Was tat Roland mit seinem Horn?', 'Er blies hinein, um Karl zu rufen', ['Er trank daraus', 'Er warf es weg', 'Er schenkte es dem König']],
              ['Welche Eide von 842 sind ein frühes Zeugnis des Französischen?', 'Die Straßburger Eide', ['Die Eide von Verdun', 'Die Pariser Eide', 'Die Eide von Reims']],
              ['Mit welchem Bruder schwor Karl der Kahle die Eide?', 'Mit Ludwig (dem Deutschen)', ['Mit Lothar', 'Mit Pippin', 'Mit Odo']],
              ['Wie wurden die Wikinger 845 zum Abzug bewegt?', 'Durch ein hohes Lösegeld', ['Durch eine Schlacht', 'Durch eine Seuche', 'Durch eine Heirat']],
              ['Wann wurde Odo zum König gewählt?', '888', ['845', '911', '987']],
              ['Zu welcher Familie gehörte Odo?', 'Zu den Robertinern', ['Zu den Karolingern', 'Zu den Merowingern', 'Zu den Normannen']],
              ['Welcher König schloss 911 den Vertrag mit Rollo?', 'Karl der Einfältige', ['Karl der Kahle', 'Ludwig V.', 'Hugo Capet']],
              ['Wie heißt der Vertrag von 911?', 'Vertrag von Saint-Clair-sur-Epte', ['Vertrag von Verdun', 'Vertrag von Paris', 'Vertrag von Rouen']],
              ['Um welche Stadt lag das Land, das Rollo bekam?', 'Um Rouen', ['Um Paris', 'Um Caen', 'Um Calais']],
              ['Was musste Rollo im Gegenzug tun?', 'Sich taufen lassen und das Reich gegen Wikinger verteidigen', ['Tribut zahlen', 'Nach Norwegen zurückkehren', 'Paris erobern']],
              ['Wann wurde Cluny gegründet?', '910', ['843', '987', '1098']],
              ['Wo wurde der Gottesfrieden zuerst verkündet?', 'In Charroux', ['In Cluny', 'In Paris', 'In Reims']],
              ['Wann wurde der Gottesfrieden zuerst verkündet?', '989', ['910', '1095', '843']],
              ['Wie hieß der letzte westfränkische Karolinger?', 'Ludwig V.', ['Karl der Einfältige', 'Lothar', 'Ludwig der Fromme']],
              ['Welchen Beinamen hatte Ludwig V.?', '„Der Faule“', ['„Der Kahle“', '„Der Fromme“', '„Der Große“']],
              ['Wo wurde Hugo Capet gewählt?', 'In Senlis', ['In Reims', 'In Paris', 'In Saint-Denis']],
              ['Bis wann regierten die Kapetinger und ihre Nebenlinien?', 'Bis 1848', ['Bis 1328', 'Bis 1589', 'Bis 1789']],
            ],
            schwer: [
              ['Welche Nebenlinien der Kapetinger regierten später?', 'Valois und Bourbonen', ['Habsburger und Stuarts', 'Tudors und Windsor', 'Medici und Sforza']],
              ['Wann wurde Hugo Capet gekrönt?', 'Im Juli 987', ['Im Dezember 987', 'Im Januar 988', 'Im Mai 986']],
              ['Wie lange belagerten die Wikinger Paris 885/886 etwa?', 'Monatelang', ['Einen Tag', 'Zehn Jahre', 'Eine Stunde']],
              ['Mit welcher Familie rangen die Robertiner um die Krone?', 'Mit den Karolingern', ['Mit den Merowingern', 'Mit den Plantagenets', 'Mit den Ottonen']],
              ['Wie hießen Schwert und Horn Rolands?', 'Durendal und Olifant', ['Excalibur und Gjallarhorn', 'Joyeuse und Olifant', 'Balmung und Tuba']],
              ['Wie hieß Karls des Großen Schwert in den Legenden?', 'Joyeuse', ['Durendal', 'Excalibur', 'Hauteclaire']],
              ['An welchem Fluss lag das Gebiet Rollos?', 'An der unteren Seine', ['An der Loire', 'An der Garonne', 'An der Rhone']],
              ['Welchen christlichen Namen nahm Rollo an?', 'Robert', ['Richard', 'Wilhelm', 'Odo']],
              ['Welche Aufgabe hatte die Reformbewegung von Cluny?', 'Die Kirche zu erneuern', ['Kriege zu führen', 'Handel zu treiben', 'Universitäten zu gründen']],
              ['Wer herrschte im 10. Jahrhundert faktisch über große Teile Frankreichs?', 'Mächtige Herzöge und Grafen', ['Der König', 'Der Kaiser in Aachen', 'Der Papst']],
              ['In welchem Jahr ging die Normandie an Rollo?', '911', ['843', '885', '1066']],
              ['Wer ist Rolands Freund im Lied?', 'Olivier', ['Ganelon', 'Rollo', 'Odo']],
              ['Wer ist der Verräter in der Chanson de Roland?', 'Ganelon', ['Olivier', 'Turpin', 'Roland']],
              ['Gegen wen kämpft Roland im Lied (statt historisch gegen Basken)?', 'Gegen Sarazenen (Muslime)', ['Gegen Wikinger', 'Gegen Engländer', 'Gegen Hunnen']],
              ['Wie oft belagerten Wikinger Paris im Text?', 'Zweimal (845 und 885/886)', ['Einmal', 'Nie', 'Zehnmal']],
              ['Welche Familie stellte mit Odo 888 erstmals einen König?', 'Die Robertiner', ['Die Habsburger', 'Die Valois', 'Die Bourbonen']],
              ['Warum gilt 987 als Wendepunkt?', 'Die Kapetinger begannen ihre jahrhundertelange Herrschaft', ['Frankreich wurde Republik', 'Die Wikinger eroberten Paris', 'Karl der Große starb']],
              ['Was ist der Vertrag von Verdun?', 'Die Teilung des Karolingerreiches 843', ['Ein Frieden mit den Wikingern', 'Ein Vertrag über die Normandie', 'Die Wahl Hugo Capets']],
              ['Welcher Beiname von Karl III. bedeutet eigentlich „der Einfache, Aufrichtige“?', '„Der Einfältige“ (le Simple)', ['„Der Kahle“', '„Der Dicke“', '„Der Faule“']],
              ['Wo starb Ludwig V.?', 'Nach einem Jagdunfall in der Nähe von Senlis', ['In einer Schlacht gegen Wikinger', 'In Rom', 'In Reims bei der Krönung']],
            ],
          },
        },
      ],
    },
  ],
};
