import type { Epoch } from '../types';

export const E3: Epoch = {
  id: 'absolutismus',
  name: 'Renaissance, Glaubenskriege und Absolutismus',
  period: '1494–1789',
  events: [
    {
      id: 'renaissance',
      title: 'Renaissance in Frankreich',
      date: '1494–1547',
      text: [
        'In den Italienkriegen lernten die französischen Könige die Kunst der italienischen Renaissance kennen. Franz I. holte Künstler wie Leonardo da Vinci ins Land, baute prächtige Schlösser an der Loire und machte Französisch zur Sprache des Staates.',
      ],
      subtopics: [
        {
          id: 'franz-i',
          title: 'Franz I. und die Renaissance',
          date: '1494–1547',
          text: [
            '1494 zog König Karl VIII. mit einem großen Heer nach Italien, um Ansprüche auf das Königreich Neapel durchzusetzen. Damit begannen die Italienkriege, in denen Frankreich jahrzehntelang mit Spanien und dem Kaiser um Italien kämpfte. Die Franzosen kehrten begeistert von den Palästen, Gärten und Kunstwerken der italienischen Renaissance zurück.',
            'Franz I., geboren 1494, wurde 1515 König. Noch im selben Jahr siegte er am 13. und 14. September in der Schlacht von Marignano über die Schweizer und eroberte Mailand. 1516 lud er den über 60-jährigen Leonardo da Vinci nach Frankreich ein; Leonardo lebte im Herrenhaus Clos Lucé bei Amboise an der Loire und starb dort am 2. Mai 1519. Er brachte die „Mona Lisa“ mit, die deshalb heute im Louvre hängt.',
            'Franz ließ an der Loire das riesige Schloss Chambord bauen (ab 1519), mit einer berühmten doppelten Wendeltreppe, die vielleicht auf eine Idee Leonardos zurückgeht. Auch Fontainebleau ließ er prachtvoll ausgestalten. 1530 gründete er das „Collège royal“, das heutige Collège de France, an dem auch Griechisch und Hebräisch gelehrt wurden. Der Arzt und Dichter François Rabelais schrieb die derb-witzigen Romane über die Riesen Gargantua und Pantagruel.',
            '1519 bewarb sich Franz um die Kaiserkrone, verlor die Wahl aber gegen Karl V. Fortan bekämpften sich beide. 1520 traf Franz den englischen König Heinrich VIII. auf dem prunkvollen „Feld des Goldenen Tuchs“ bei Calais. 1525 wurde Franz in der Schlacht von Pavia von den Truppen Karls V. gefangen genommen und nach Madrid gebracht; an seine Mutter schrieb er: „Alles ist verloren, außer der Ehre.“ Gegen seine Freiheit musste er 1526 Burgund abtreten – ein Versprechen, das er nicht hielt. Um den Kaiser zu schwächen, verbündete er sich 1536 sogar mit dem osmanischen Sultan Süleyman.',
            'Mit dem Edikt von Villers-Cotterêts vom August 1539 bestimmte Franz, dass alle Gerichtsurteile und amtlichen Urkunden auf Französisch statt auf Latein abgefasst werden mussten; außerdem mussten die Pfarrer Taufen in Registern verzeichnen. Das Edikt gilt bis heute als ältestes noch gültiges Gesetz Frankreichs.',
            '1534 segelte der Seefahrer Jacques Cartier im Auftrag des Königs nach Nordamerika, nahm Land bei Gaspé für Frankreich in Besitz und fuhr den Sankt-Lorenz-Strom hinauf. Das Wort „Canada“, das er von den Einheimischen hörte, wurde zum Namen des Landes. Franz I. starb 1547.',
          ],
          quiz: {
            leicht: [
              ['Welcher König holte Leonardo da Vinci nach Frankreich?', 'Franz I.', ['Ludwig XIV.', 'Heinrich IV.', 'Karl VIII.']],
              ['In welchem Land lernten die Franzosen die Renaissance kennen?', 'In Italien', ['In England', 'In Spanien', 'In Deutschland']],
              ['Welches berühmte Gemälde brachte Leonardo mit nach Frankreich?', 'Die Mona Lisa', ['Das Abendmahl', 'Die Geburt der Venus', 'Die Nachtwache']],
              ['Wo hängt die Mona Lisa heute?', 'Im Louvre', ['In Versailles', 'In den Uffizien', 'Im Prado']],
              ['An welchem Fluss stehen die berühmten Renaissance-Schlösser?', 'An der Loire', ['An der Seine', 'An der Rhone', 'Am Rhein']],
              ['Welches riesige Schloss ließ Franz I. bauen?', 'Chambord', ['Versailles', 'Neuschwanstein', 'Schönbrunn']],
              ['Wofür ist die Treppe in Chambord berühmt?', 'Sie ist eine doppelte Wendeltreppe', ['Sie ist aus Gold', 'Sie ist 1000 Stufen lang', 'Sie ist unterirdisch']],
              ['Wo starb Leonardo da Vinci?', 'Bei Amboise in Frankreich', ['In Florenz', 'In Rom', 'In Mailand']],
              ['Welche Sprache machte Franz I. zur Sprache der Urkunden?', 'Französisch', ['Latein', 'Italienisch', 'Griechisch']],
              ['Gegen wen verlor Franz I. die Kaiserwahl 1519?', 'Gegen Karl V.', ['Gegen Heinrich VIII.', 'Gegen Maximilian I.', 'Gegen Süleyman']],
              ['Was schrieb Franz nach Pavia an seine Mutter?', '„Alles ist verloren, außer der Ehre“', ['„Ich kam, sah und siegte“', '„Der Staat bin ich“', '„Paris ist eine Messe wert“']],
              ['Wohin wurde Franz nach seiner Gefangennahme gebracht?', 'Nach Madrid', ['Nach Wien', 'Nach London', 'Nach Rom']],
              ['Welcher Seefahrer erkundete 1534 Kanada?', 'Jacques Cartier', ['Christoph Kolumbus', 'Samuel de Champlain', 'Vasco da Gama']],
              ['Woher stammt der Name „Canada“?', 'Aus der Sprache der Einheimischen', ['Von einem König', 'Von einem Schiff', 'Von einer Stadt in Frankreich']],
              ['Welcher Dichter schrieb über die Riesen Gargantua und Pantagruel?', 'François Rabelais', ['Molière', 'Voltaire', 'Villon']],
              ['Welchen englischen König traf Franz 1520?', 'Heinrich VIII.', ['Heinrich V.', 'Eduard VI.', 'Richard III.']],
              ['Wie hieß das prunkvolle Treffen mit Heinrich VIII.?', '„Feld des Goldenen Tuchs“', ['„Gipfel von Calais“', '„Wiese der Könige“', '„Fest der Rose“']],
              ['Mit welchem Sultan verbündete sich Franz I.?', 'Süleyman', ['Saladin', 'Mehmed II.', 'Harun ar-Raschid']],
              ['Wann wurde Franz I. König?', '1515', ['1494', '1547', '1589']],
              ['Wann starb Franz I.?', '1547', ['1515', '1525', '1559']],
            ],
            mittel: [
              ['Welcher König begann 1494 die Italienkriege?', 'Karl VIII.', ['Franz I.', 'Ludwig XII.', 'Heinrich II.']],
              ['Um welches Königreich ging es Karl VIII.?', 'Um Neapel', ['Um Venedig', 'Um Sizilien', 'Um Spanien']],
              ['Mit wem kämpfte Frankreich in den Italienkriegen?', 'Mit Spanien und dem Kaiser', ['Mit England und Schweden', 'Mit Russland', 'Mit Portugal']],
              ['Wann fand die Schlacht von Marignano statt?', '13./14. September 1515', ['24. Februar 1525', '2. Mai 1519', '1. September 1494']],
              ['Gegen wen siegte Franz bei Marignano?', 'Gegen die Schweizer', ['Gegen die Engländer', 'Gegen die Spanier', 'Gegen die Venezianer']],
              ['Welche Stadt eroberte Franz 1515?', 'Mailand', ['Rom', 'Neapel', 'Florenz']],
              ['Wann kam Leonardo nach Frankreich?', '1516', ['1515', '1519', '1494']],
              ['In welchem Herrenhaus lebte Leonardo?', 'Clos Lucé', ['Chambord', 'Fontainebleau', 'Blois']],
              ['Wann starb Leonardo?', '2. Mai 1519', ['13. September 1515', '24. Februar 1525', '1. Januar 1520']],
              ['Ab wann wurde Chambord gebaut?', '1519', ['1494', '1539', '1600']],
              ['Welches Schloss ließ Franz außerdem prachtvoll ausgestalten?', 'Fontainebleau', ['Versailles', 'Vincennes', 'Malmaison']],
              ['Wann gründete Franz das Collège royal?', '1530', ['1515', '1539', '1257']],
              ['Wie heißt das Collège royal heute?', 'Collège de France', ['Sorbonne', 'École normale', 'Académie française']],
              ['Welche Sprachen lehrte man am Collège royal neu?', 'Griechisch und Hebräisch', ['Englisch und Deutsch', 'Arabisch und Chinesisch', 'Nur Latein']],
              ['Wann wurde Franz bei Pavia gefangen?', '1525', ['1515', '1519', '1536']],
              ['Welches Gebiet musste Franz 1526 versprechen abzutreten?', 'Burgund', ['Die Bretagne', 'Die Normandie', 'Mailand']],
              ['Hielt Franz sein Versprechen von 1526?', 'Nein', ['Ja', 'Nur zur Hälfte', 'Erst nach 50 Jahren']],
              ['Wann wurde das Edikt von Villers-Cotterêts erlassen?', 'August 1539', ['September 1515', 'Mai 1519', 'Februar 1525']],
              ['Was mussten Pfarrer nach dem Edikt von 1539 führen?', 'Taufregister', ['Steuerlisten', 'Soldatenlisten', 'Chroniken']],
              ['Wo nahm Cartier Land für Frankreich in Besitz?', 'Bei Gaspé', ['Bei Québec', 'In Louisiana', 'In Florida']],
            ],
            schwer: [
              ['Wann wurde Franz I. geboren?', '1494', ['1515', '1500', '1488']],
              ['Welchen Fluss fuhr Cartier hinauf?', 'Den Sankt-Lorenz-Strom', ['Den Mississippi', 'Den Hudson', 'Den Amazonas']],
              ['Was gilt als ältestes noch gültiges Gesetz Frankreichs?', 'Das Edikt von Villers-Cotterêts', ['Das Edikt von Nantes', 'Die Lex Salica', 'Der Code civil']],
              ['Auf wessen Idee geht Chambords Treppe vielleicht zurück?', 'Leonardo da Vincis', ['Michelangelos', 'Raffaels', 'Vaubans']],
              ['Wann verbündete sich Franz mit dem Sultan?', '1536', ['1515', '1525', '1547']],
              ['Warum verbündete sich Franz mit dem Sultan?', 'Um den Kaiser zu schwächen', ['Um Jerusalem zu erobern', 'Um Handel mit Indien zu treiben', 'Um gegen England zu kämpfen']],
              ['Bei welcher Stadt fand das Treffen mit Heinrich VIII. statt?', 'Bei Calais', ['Bei Paris', 'Bei London', 'Bei Rouen']],
              ['Welchen Beruf hatte Rabelais außer Dichter?', 'Arzt', ['Soldat', 'König', 'Bankier']],
              ['Wie sind Rabelais’ Romane?', 'Derb und witzig', ['Fromm und ernst', 'Traurig und düster', 'Wissenschaftliche Abhandlungen']],
              ['Wohin wurde Franz nach Pavia gebracht?', 'Nach Madrid', ['Nach Pavia ins Gefängnis', 'Nach Neapel', 'Nach Wien']],
              ['In welchem Jahr kam Cartier nach Nordamerika?', '1534', ['1492', '1608', '1515']],
              ['Wer war Franz’ großer Gegenspieler?', 'Kaiser Karl V.', ['Heinrich VIII.', 'Papst Leo X.', 'Süleyman']],
              ['Was beeindruckte die Franzosen in Italien besonders?', 'Paläste, Gärten und Kunstwerke', ['Kanonen', 'Schiffe', 'Gesetze']],
              ['Welches Ziel hatten die Italienkriege für Frankreich?', 'Herrschaft über Teile Italiens', ['Die Eroberung Spaniens', 'Ein Kreuzzug', 'Die Befreiung Roms vom Papst']],
              ['Was ersetzte im Edikt von 1539 das Latein?', 'Französisch in Urteilen und Urkunden', ['Italienisch', 'Okzitanisch', 'Bretonisch']],
              ['Welche Stadt liegt nahe bei Clos Lucé?', 'Amboise', ['Blois', 'Tours', 'Orléans']],
              ['Welches Gebiet versuchte Karl VIII. zu gewinnen?', 'Das Königreich Neapel', ['Mailand', 'Venedig', 'Sardinien']],
              ['Wer siegte bei Pavia?', 'Die Truppen Karls V.', ['Die Franzosen', 'Die Schweizer', 'Die Engländer']],
              ['Woran erkennt man Franz’ Interesse an Bildung?', 'An der Gründung des Collège royal', ['An der Schließung der Sorbonne', 'An Bücherverbrennungen', 'An einem Verbot des Griechischen']],
              ['Wie alt war Leonardo, als er nach Frankreich kam?', 'Über 60 Jahre', ['20 Jahre', '35 Jahre', '90 Jahre']],
            ],
          },
        },
      ],
    },
    {
      id: 'religionskriege',
      title: 'Die Religionskriege',
      date: '1559–1610',
      text: [
        'Die Reformation spaltete Frankreich. Katholiken und reformierte Protestanten, die Hugenotten, führten fast 40 Jahre lang Bürgerkrieg. Den grausamen Höhepunkt bildete die Bartholomäusnacht; erst Heinrich IV. brachte mit dem Edikt von Nantes Frieden.',
      ],
      subtopics: [
        {
          id: 'hugenotten-bartholomaeus',
          title: 'Hugenotten und Bartholomäusnacht',
          date: '1559–1572',
          text: [
            'Die Lehre des Franzosen Johannes Calvin, der in Genf wirkte, fand in Frankreich viele Anhänger, besonders im Adel und unter Handwerkern und Kaufleuten in den Städten. Man nannte die französischen Reformierten Hugenotten. Um 1560 bekannte sich vielleicht jeder zehnte Franzose zu ihnen.',
            '1559 wurde König Heinrich II. bei einem Turnier vom Lanzensplitter seines Gegners, des Grafen von Montgomery, am Auge getroffen und starb wenige Tage später. Es folgten nacheinander seine drei jungen, schwachen Söhne Franz II. (1559–1560), Karl IX. und Heinrich III. Die eigentliche Macht lag oft bei ihrer Mutter Katharina von Medici, einer Italienerin, die zwischen den Parteien zu vermitteln versuchte.',
            'Die Führer der Katholiken war die mächtige Familie Guise, die Führer der Hugenotten waren die Bourbonen (das Haus Navarra) und Admiral Gaspard de Coligny. Am 1. März 1562 überfielen Bewaffnete des Herzogs von Guise in Wassy in der Champagne einen Gottesdienst von Hugenotten und töteten Dutzende. Damit begannen die Religionskriege (Hugenottenkriege), acht Kriege zwischen 1562 und 1598.',
            'Um Frieden zu stiften, verheiratete Katharina ihre Tochter Margarete von Valois mit dem protestantischen Heinrich von Navarra. Zur Hochzeit am 18. August 1572 kamen viele hugenottische Adlige nach Paris. Am 22. August wurde ein Anschlag auf Coligny verübt. In der Nacht vom 23. auf den 24. August 1572, dem Bartholomäustag, ließen der König und seine Mutter die hugenottischen Anführer ermorden; Coligny wurde getötet und aus dem Fenster geworfen.',
            'Das Morden griff auf die ganze Stadt über: In Paris wurden etwa 3000, in ganz Frankreich in den folgenden Wochen vermutlich 10.000 bis 20.000 Hugenotten getötet. Wegen der Hochzeit nennt man die Bartholomäusnacht auch „Pariser Bluthochzeit“. Heinrich von Navarra überlebte, weil er zum Schein katholisch wurde. Papst Gregor XIII. ließ zur Feier eine Gedenkmünze prägen.',
            'Nach der Bartholomäusnacht ging der Krieg mit noch größerer Erbitterung weiter. Viele Hugenotten zweifelten nun daran, dass man einem König gehorchen müsse, der seine Untertanen ermorden ließ. Der Roman „Die Bartholomäusnacht“ (La Reine Margot) von Alexandre Dumas machte die Ereignisse später weltbekannt.',
          ],
          quiz: {
            leicht: [
              ['Wie nannte man die französischen Protestanten?', 'Hugenotten', ['Lutheraner', 'Puritaner', 'Katharer']],
              ['Wessen Lehre folgten die Hugenotten?', 'Johannes Calvins', ['Martin Luthers', 'Thomas Müntzers', 'Jan Hus’']],
              ['In welcher Stadt wirkte Calvin?', 'In Genf', ['In Paris', 'In Zürich', 'In Wittenberg']],
              ['Wie starb König Heinrich II.?', 'Bei einem Turnier', ['In einer Schlacht', 'Durch Gift', 'An der Pest']],
              ['Welche Königinmutter hatte viel Macht?', 'Katharina von Medici', ['Maria Stuart', 'Marie Antoinette', 'Eleonore von Aquitanien']],
              ['Woher stammte Katharina von Medici?', 'Aus Italien', ['Aus Spanien', 'Aus England', 'Aus Österreich']],
              ['Welche Familie führte die Katholiken an?', 'Die Guise', ['Die Bourbonen', 'Die Valois', 'Die Medici']],
              ['Wie viele Religionskriege gab es zwischen 1562 und 1598?', 'Acht', ['Einen', 'Drei', 'Dreißig']],
              ['Wann war die Bartholomäusnacht?', '1572', ['1562', '1598', '1610']],
              ['Wen heiratete Margarete von Valois 1572?', 'Heinrich von Navarra', ['Heinrich III.', 'Karl IX.', 'Philipp II.']],
              ['Wie nennt man die Bartholomäusnacht auch?', '„Pariser Bluthochzeit“', ['„Pariser Kommune“', '„Nacht der langen Messer“', '„Sizilianische Vesper“']],
              ['Welcher Hugenottenführer wurde in der Bartholomäusnacht ermordet?', 'Admiral Coligny', ['Heinrich von Navarra', 'Calvin', 'Condé']],
              ['Wie überlebte Heinrich von Navarra?', 'Er wurde zum Schein katholisch', ['Er floh nach England', 'Er versteckte sich in einem Fass', 'Er war gar nicht in Paris']],
              ['Wie viele Hugenotten starben in Paris etwa?', 'Etwa 3000', ['Etwa 30', 'Etwa 300.000', 'Niemand']],
              ['Welcher Schriftsteller machte die Ereignisse in einem Roman bekannt?', 'Alexandre Dumas', ['Victor Hugo', 'Voltaire', 'Émile Zola']],
              ['Wie reagierte der Papst auf die Bartholomäusnacht?', 'Er ließ eine Gedenkmünze prägen', ['Er bannte den König', 'Er weinte öffentlich', 'Er schwieg']],
              ['Welche Gruppen bekannten sich besonders zu den Hugenotten?', 'Adlige sowie Handwerker und Kaufleute', ['Nur Bauern', 'Nur Bischöfe', 'Nur Könige']],
              ['Wie viele Söhne Heinrichs II. wurden nacheinander König?', 'Drei', ['Einer', 'Zwei', 'Fünf']],
              ['Wann begannen die Religionskriege?', '1562', ['1517', '1572', '1598']],
              ['Was versuchte Katharina mit der Hochzeit ihrer Tochter?', 'Frieden zu stiften', ['Spanien zu erobern', 'Den Papst zu stürzen', 'Geld zu verdienen']],
            ],
            mittel: [
              ['Wann starb Heinrich II.?', '1559', ['1547', '1562', '1572']],
              ['Wer traf Heinrich II. beim Turnier?', 'Der Graf von Montgomery', ['Der Herzog von Guise', 'Coligny', 'Heinrich von Navarra']],
              ['Wie hießen die drei Söhne Heinrichs II., die König wurden?', 'Franz II., Karl IX. und Heinrich III.', ['Ludwig XII., Franz I. und Heinrich IV.', 'Karl VIII., Karl IX. und Karl X.', 'Heinrich III., Heinrich IV. und Ludwig XIII.']],
              ['Welche Familie führte die Hugenotten mit an?', 'Die Bourbonen (Haus Navarra)', ['Die Guise', 'Die Medici', 'Die Habsburger']],
              ['Was geschah am 1. März 1562 in Wassy?', 'Ein Gottesdienst der Hugenotten wurde überfallen', ['Ein Frieden wurde geschlossen', 'Calvin predigte', 'Der König wurde gekrönt']],
              ['Wessen Leute überfielen die Hugenotten in Wassy?', 'Die des Herzogs von Guise', ['Die des Königs', 'Die Coligny', 'Die des Papstes']],
              ['Wie viele Franzosen waren um 1560 vielleicht Hugenotten?', 'Jeder zehnte', ['Jeder zweite', 'Jeder hundertste', 'Alle']],
              ['Wann fand die Hochzeit von Margarete und Heinrich statt?', '18. August 1572', ['24. August 1572', '1. März 1562', '13. April 1598']],
              ['Wann wurde ein erster Anschlag auf Coligny verübt?', '22. August 1572', ['24. August 1572', '18. August 1572', '1. März 1562']],
              ['In welcher Nacht fand das Massaker statt?', 'Vom 23. auf den 24. August 1572', ['Vom 13. auf den 14. Juli 1572', 'Vom 24. auf den 25. Dezember 1572', 'Vom 31. Oktober auf den 1. November 1572']],
              ['Welcher König regierte während der Bartholomäusnacht?', 'Karl IX.', ['Heinrich III.', 'Franz II.', 'Heinrich IV.']],
              ['Was geschah mit Colignys Leiche?', 'Sie wurde aus dem Fenster geworfen', ['Sie wurde in Saint-Denis begraben', 'Sie wurde nach Genf gebracht', 'Sie verschwand']],
              ['Wie viele Hugenotten starben in ganz Frankreich vermutlich?', '10.000 bis 20.000', ['100 bis 200', '1 bis 2 Millionen', '500 bis 1000']],
              ['Welcher Papst ließ eine Gedenkmünze prägen?', 'Gregor XIII.', ['Pius V.', 'Sixtus V.', 'Leo X.']],
              ['Woran zweifelten viele Hugenotten nach 1572?', 'Ob man einem mordenden König gehorchen müsse', ['Ob Gott existiert', 'Ob Calvin recht hatte', 'Ob Paris die Hauptstadt ist']],
              ['Wie heißt Dumas’ Roman im Original?', '„La Reine Margot“', ['„Les Trois Mousquetaires“', '„Le Comte de Monte-Cristo“', '„Notre-Dame de Paris“']],
              ['Wer versuchte zwischen den Parteien zu vermitteln?', 'Katharina von Medici', ['Der Herzog von Guise', 'Coligny', 'Calvin']],
              ['Was war Margarete von Valois?', 'Die Tochter Katharinas von Medici', ['Eine Hugenottin aus Genf', 'Die Frau Karls IX.', 'Eine Nonne']],
              ['Wie nennt man die Religionskriege auch?', 'Hugenottenkriege', ['Bauernkriege', 'Rosenkriege', 'Italienkriege']],
              ['Wie lange dauerten die Religionskriege insgesamt?', 'Fast 40 Jahre', ['Vier Jahre', 'Hundert Jahre', 'Ein Jahr']],
            ],
            schwer: [
              ['Wo wurde Heinrich II. beim Turnier getroffen?', 'Am Auge', ['Am Herzen', 'Am Bein', 'Am Arm']],
              ['Womit wurde Heinrich II. verletzt?', 'Mit einem Lanzensplitter', ['Mit einem Pfeil', 'Mit einem Schwert', 'Mit einer Kugel']],
              ['Welche Stände gehörten besonders zu den Hugenotten?', 'Adel und städtisches Bürgertum', ['Klerus', 'Leibeigene', 'Bettelorden']],
              ['Wie nennt man Heinrich von Navarras Haus?', 'Bourbon', ['Valois', 'Guise', 'Orléans']],
              ['Welcher Bartholomäus gab der Nacht ihren Namen?', 'Der Apostel Bartholomäus, dessen Fest am 24. August ist', ['Ein Hugenottenführer', 'Ein Bischof von Paris', 'Ein König von Navarra']],
              ['Was war die Folge der Bartholomäusnacht für den Krieg?', 'Er wurde noch erbitterter', ['Er endete sofort', 'Die Hugenotten ergaben sich', 'Spanien griff ein und siegte']],
              ['In welchem Jahr endeten die Religionskriege?', '1598', ['1572', '1589', '1610']],
              ['Woher stammte Calvin ursprünglich?', 'Aus Frankreich', ['Aus der Schweiz', 'Aus Deutschland', 'Aus den Niederlanden']],
              ['Wann regierte Franz II.?', '1559–1560', ['1515–1547', '1574–1589', '1560–1574']],
              ['Welche Rolle hatte Coligny?', 'Admiral und Führer der Hugenotten', ['König von Navarra', 'Bischof von Paris', 'Herzog von Guise']],
              ['Wer heiratete 1572 in Paris?', 'Heinrich von Navarra und Margarete von Valois', ['Karl IX. und Elisabeth', 'Heinrich III. und Louise', 'Franz II. und Maria Stuart']],
              ['Wer ordnete die Ermordung der Anführer an?', 'Der König und seine Mutter', ['Der Papst', 'Calvin', 'Spanien']],
              ['Was wollte Katharina von Medici zunächst?', 'Zwischen den Parteien vermitteln', ['Alle Hugenotten töten', 'Spanien ausliefern', 'Die Krone für Guise']],
              ['Wie wurde die Bartholomäusnacht im katholischen Ausland teils gefeiert?', 'Mit einer päpstlichen Gedenkmünze', ['Mit einem Feiertag in England', 'Mit einer Oper', 'Gar nicht']],
              ['Wie viele Kriege umfassten die Hugenottenkriege?', 'Acht', ['Drei', 'Zwölf', 'Einen']],
              ['Welcher Herzog war der Anführer der Katholiken 1562?', 'Franz von Guise', ['Heinrich von Guise', 'Anne de Montmorency', 'Coligny']],
              ['Wo liegt Wassy?', 'In der Champagne', ['In der Bretagne', 'In der Provence', 'In Paris']],
              ['Welche Wirkung hatte die Ermordung auf das Verhältnis zum König?', 'Viele Hugenotten verloren das Vertrauen in den König', ['Sie vertrauten ihm mehr', 'Sie wählten ihn erneut', 'Nichts änderte sich']],
              ['Wann wurde Dumas’ Roman veröffentlicht?', 'Im 19. Jahrhundert', ['Im 16. Jahrhundert', 'Im 18. Jahrhundert', 'Im 20. Jahrhundert']],
              ['Welcher Teil der Bevölkerung war um 1560 nicht hugenottisch?', 'Die große Mehrheit', ['Nur der König', 'Nur Paris', 'Niemand']],
            ],
          },
        },
        {
          id: 'heinrich-iv',
          title: 'Heinrich IV. und das Edikt von Nantes',
          date: '1584–1610',
          text: [
            'Als 1584 der jüngste Bruder des kinderlosen Heinrich III. starb, wurde der Protestant Heinrich von Navarra rechtmäßiger Thronerbe. Die katholische Liga unter Herzog Heinrich von Guise, unterstützt von Spanien, wollte das verhindern. Es begann der „Krieg der drei Heinriche“: Heinrich III., Heinrich von Guise und Heinrich von Navarra.',
            '1588 vertrieb die Liga Heinrich III. aus Paris. Daraufhin ließ der König den Herzog von Guise im Schloss Blois ermorden. Am 1. August 1589 wurde Heinrich III. selbst von dem Dominikanermönch Jacques Clément erstochen. Damit endete die Herrschaft der Valois, und Heinrich von Navarra wurde als Heinrich IV. der erste König aus dem Haus Bourbon.',
            'Doch Paris und viele Katholiken erkannten keinen protestantischen König an. Nach jahrelangem Kampf trat Heinrich im Juli 1593 zum Katholizismus über; ihm wird der Satz zugeschrieben: „Paris ist eine Messe wert.“ 1594 wurde er in Chartres gekrönt – Reims war noch in der Hand der Liga – und zog in Paris ein.',
            'Am 13. April 1598 erließ Heinrich IV. das Edikt von Nantes. Es gab den Hugenotten Gewissensfreiheit, erlaubte ihnen Gottesdienste an bestimmten Orten, öffnete ihnen alle Ämter und überließ ihnen rund 100 befestigte Sicherheitsplätze, darunter La Rochelle. Damit endeten die Religionskriege. Im selben Jahr schloss er Frieden mit Spanien.',
            'Mit seinem Minister, dem Herzog von Sully, baute Heinrich das verwüstete Land wieder auf: Er förderte die Landwirtschaft, ließ Straßen, Kanäle und Brücken bauen – in Paris wurde der Pont Neuf vollendet, heute die älteste erhaltene Brücke der Stadt – und brachte die Staatsfinanzen in Ordnung. Heinrich soll gesagt haben, jeder Bauer solle sonntags ein Huhn im Topf haben („la poule au pot“). 1608 gründete Samuel de Champlain in seinem Auftrag Québec in Kanada.',
            'Heinrich IV. war volkstümlich und wurde später „der gute König Heinrich“ genannt. Doch religiöse Eiferer hassten ihn. Am 14. Mai 1610 erstach ihn der katholische Fanatiker François Ravaillac in Paris in der Rue de la Ferronnerie, als seine Kutsche im Verkehr feststeckte. Sein Sohn Ludwig XIII. war erst acht Jahre alt.',
          ],
          quiz: {
            leicht: [
              ['Wer war der erste König aus dem Haus Bourbon?', 'Heinrich IV.', ['Ludwig XIII.', 'Heinrich III.', 'Ludwig XIV.']],
              ['Welcher Religion gehörte Heinrich von Navarra zuerst an?', 'Er war Protestant', ['Er war Katholik', 'Er war Muslim', 'Er war Jude']],
              ['Welcher Satz wird Heinrich IV. zugeschrieben?', '„Paris ist eine Messe wert“', ['„Der Staat bin ich“', '„Nach uns die Sintflut“', '„Alles ist verloren außer der Ehre“']],
              ['Zu welcher Religion trat Heinrich 1593 über?', 'Zum Katholizismus', ['Zum Calvinismus', 'Zum Islam', 'Zum Judentum']],
              ['Welches Edikt beendete 1598 die Religionskriege?', 'Das Edikt von Nantes', ['Das Edikt von Fontainebleau', 'Das Edikt von Potsdam', 'Das Edikt von Worms']],
              ['Wann wurde das Edikt von Nantes erlassen?', '1598', ['1572', '1610', '1685']],
              ['Was erhielten die Hugenotten durch das Edikt?', 'Gewissensfreiheit', ['Ein eigenes Königreich', 'Die Kaiserkrone', 'Nichts']],
              ['Wie hieß Heinrichs berühmter Minister?', 'Sully', ['Richelieu', 'Colbert', 'Mazarin']],
              ['Was sollte jeder Bauer sonntags haben?', 'Ein Huhn im Topf', ['Ein Pferd', 'Ein Glas Wein', 'Ein neues Haus']],
              ['Welche Stadt in Kanada wurde 1608 gegründet?', 'Québec', ['Montréal', 'Toronto', 'Ottawa']],
              ['Wer gründete Québec?', 'Samuel de Champlain', ['Jacques Cartier', 'La Salle', 'Cabot']],
              ['Wie starb Heinrich IV.?', 'Er wurde erstochen', ['Er starb an der Pest', 'Er fiel in einer Schlacht', 'Er stürzte vom Pferd']],
              ['Wer ermordete Heinrich IV.?', 'François Ravaillac', ['Jacques Clément', 'Coligny', 'Guise']],
              ['Wann wurde Heinrich IV. ermordet?', '1610', ['1598', '1589', '1643']],
              ['Wie nannte man Heinrich IV. später?', '„Der gute König Heinrich“', ['„Der Sonnenkönig“', '„Der Heilige“', '„Der Grausame“']],
              ['Welche Brücke in Paris wurde unter Heinrich IV. vollendet?', 'Der Pont Neuf', ['Die Pont Alexandre III', 'Der Pont des Arts', 'Die Tower Bridge']],
              ['Wie hieß der Krieg zwischen drei Männern gleichen Namens?', 'Krieg der drei Heinriche', ['Krieg der Rosen', 'Krieg der drei Könige', 'Bruderkrieg']],
              ['Mit welchem Land schloss Heinrich 1598 Frieden?', 'Mit Spanien', ['Mit England', 'Mit dem Kaiser', 'Mit Schweden']],
              ['Welcher Sohn folgte Heinrich IV.?', 'Ludwig XIII.', ['Ludwig XIV.', 'Heinrich V.', 'Karl X.']],
              ['Welche Familie regierte vor den Bourbonen?', 'Die Valois', ['Die Habsburger', 'Die Guise', 'Die Kapetinger direkt']],
            ],
            mittel: [
              ['Wann wurde Heinrich von Navarra rechtmäßiger Thronerbe?', '1584', ['1572', '1589', '1598']],
              ['Wer führte die katholische Liga an?', 'Heinrich von Guise', ['Heinrich III.', 'Katharina von Medici', 'Philipp II.']],
              ['Welches Land unterstützte die Liga?', 'Spanien', ['England', 'Schweden', 'Venedig']],
              ['Wann wurde Heinrich III. aus Paris vertrieben?', '1588', ['1584', '1589', '1593']],
              ['Wo ließ Heinrich III. den Herzog von Guise ermorden?', 'Im Schloss Blois', ['Im Louvre', 'In Versailles', 'In Chambord']],
              ['Wer ermordete Heinrich III.?', 'Der Mönch Jacques Clément', ['François Ravaillac', 'Heinrich von Guise', 'Coligny']],
              ['Wann wurde Heinrich III. ermordet?', '1. August 1589', ['14. Mai 1610', '24. August 1572', '13. April 1598']],
              ['Welchem Orden gehörte Jacques Clément an?', 'Den Dominikanern', ['Den Jesuiten', 'Den Franziskanern', 'Den Templern']],
              ['Wann trat Heinrich IV. zum Katholizismus über?', 'Juli 1593', ['August 1589', 'April 1598', 'Mai 1610']],
              ['Wo wurde Heinrich IV. 1594 gekrönt?', 'In Chartres', ['In Reims', 'In Paris', 'In Saint-Denis']],
              ['Warum wurde Heinrich IV. nicht in Reims gekrönt?', 'Reims war in der Hand der Liga', ['Reims war zerstört', 'Er mochte Reims nicht', 'Der Papst verbot es']],
              ['An welchem Tag wurde das Edikt von Nantes erlassen?', '13. April 1598', ['14. Mai 1610', '1. August 1589', '24. August 1572']],
              ['Wie viele befestigte Sicherheitsplätze erhielten die Hugenotten etwa?', 'Rund 100', ['Rund 10', 'Rund 1000', 'Keine']],
              ['Welche Hafenstadt war ein Sicherheitsplatz der Hugenotten?', 'La Rochelle', ['Marseille', 'Calais', 'Le Havre']],
              ['Was öffnete das Edikt den Hugenotten?', 'Alle Ämter', ['Nur das Militär', 'Nur die Kirche', 'Gar nichts']],
              ['Was ließ Heinrich mit Sully bauen?', 'Straßen, Kanäle und Brücken', ['Kathedralen', 'Burgen', 'Theater']],
              ['Wie heißt das Huhn im Topf auf Französisch?', '„La poule au pot“', ['„Le coq au vin“', '„La bouillabaisse“', '„Le pot-au-feu“']],
              ['Wo wurde Heinrich IV. erstochen?', 'In der Rue de la Ferronnerie in Paris', ['Im Louvre', 'In Versailles', 'In Saint-Denis']],
              ['Was tat Heinrichs Kutsche beim Attentat?', 'Sie steckte im Verkehr fest', ['Sie raste davon', 'Sie stand vor einer Kirche', 'Sie war umgestürzt']],
              ['Wie alt war Ludwig XIII. beim Tod seines Vaters?', 'Acht Jahre', ['Zwei Jahre', 'Achtzehn Jahre', 'Dreißig Jahre']],
            ],
            schwer: [
              ['Warum wurde Heinrich von Navarra 1584 Thronerbe?', 'Der jüngste Bruder des kinderlosen Heinrich III. starb', ['Heinrich III. dankte ab', 'Der Papst ernannte ihn', 'Er eroberte Paris']],
              ['Was endete 1589 mit dem Tod Heinrichs III.?', 'Die Herrschaft der Valois', ['Die Religionskriege', 'Die Herrschaft der Bourbonen', 'Der Hundertjährige Krieg']],
              ['Wann wurde der Herzog von Guise ermordet?', '1588', ['1584', '1589', '1572']],
              ['Wann zog Heinrich IV. in Paris ein?', '1594', ['1589', '1593', '1598']],
              ['Was war das Ziel der katholischen Liga?', 'Einen protestantischen König zu verhindern', ['Die Hugenotten zu schützen', 'Spanien zu erobern', 'Den Papst abzusetzen']],
              ['Was war Ravaillac?', 'Ein katholischer Fanatiker', ['Ein Hugenottenführer', 'Ein spanischer Soldat', 'Ein Minister']],
              ['Wofür stand das Edikt von Nantes im Rückblick?', 'Für eine frühe Form religiöser Duldung', ['Für den Beginn der Verfolgung', 'Für die Abschaffung der Kirche', 'Für die Teilung Frankreichs']],
              ['Was brachte Sully in Ordnung?', 'Die Staatsfinanzen', ['Die Armee', 'Die Universität', 'Die Kolonien']],
              ['Wie war Heinrich IV. beim Volk?', 'Volkstümlich und beliebt', ['Verhasst', 'Unbekannt', 'Gefürchtet als Tyrann']],
              ['Wer waren die „drei Heinriche“?', 'Heinrich III., Heinrich von Guise und Heinrich von Navarra', ['Heinrich II., III. und IV.', 'Heinrich VIII., Heinrich IV. und Heinrich von Guise', 'Drei Söhne Katharinas']],
              ['In welcher Region liegt Québec?', 'Am Sankt-Lorenz-Strom', ['Am Mississippi', 'An der Hudson Bay', 'An den Großen Seen']],
              ['Welches Ereignis beendete 1598 den Krieg mit Spanien?', 'Ein Friedensschluss im selben Jahr wie das Edikt', ['Die Armada', 'Die Seeschlacht von Lepanto', 'Die Eroberung Madrids']],
              ['Wann wurde Québec gegründet?', '1608', ['1534', '1598', '1610']],
              ['Wie viele Jahre regierte Heinrich IV. als König von Frankreich?', 'Rund 21 Jahre (1589–1610)', ['Rund 5 Jahre', 'Rund 50 Jahre', 'Rund 72 Jahre']],
              ['Was blieb den Hugenotten bei Gottesdiensten verwehrt?', 'Sie durften nur an bestimmten Orten feiern', ['Sie durften überall feiern', 'Sie durften gar nicht feiern', 'Nur in Paris']],
              ['Was ist der Pont Neuf heute?', 'Die älteste erhaltene Brücke von Paris', ['Die neueste Brücke', 'Eine Eisenbahnbrücke', 'Eine Fußgängerbrücke aus Glas']],
              ['Wem schreibt man die Formulierung vom Huhn im Topf zu?', 'Heinrich IV.', ['Ludwig XIV.', 'Napoleon', 'Sully']],
              ['Welches Schloss war Ort des Mordes an Guise?', 'Blois', ['Chambord', 'Amboise', 'Fontainebleau']],
              ['Wie nannte man die Krönungsstadt Chartres im Vergleich zu Reims?', 'Eine Ausnahme von der Tradition', ['Die übliche Krönungsstadt', 'Die Hauptstadt', 'Die Stadt der Päpste']],
              ['Was bedeutete Heinrichs Übertritt für Paris?', 'Die Stadt öffnete ihm die Tore', ['Paris rebellierte noch 30 Jahre', 'Paris wurde protestantisch', 'Nichts']],
            ],
          },
        },
      ],
    },
    {
      id: 'absolutismus-ludwig',
      title: 'Absolutismus und Sonnenkönig',
      date: '1610–1715',
      text: [
        'Im 17. Jahrhundert wurde der französische König zum mächtigsten Herrscher Europas. Kardinal Richelieu brach den Widerstand von Adel und Hugenotten; Ludwig XIV. regierte als „Sonnenkönig“ von Versailles aus mit unbeschränkter Macht – und führte Frankreich in zahllose Kriege.',
      ],
      subtopics: [
        {
          id: 'richelieu-fronde',
          title: 'Richelieu, Mazarin und die Fronde',
          date: '1610–1661',
          text: [
            'Für den jungen Ludwig XIII. regierte zunächst seine Mutter Maria von Medici. 1624 holte der König Kardinal Armand-Jean du Plessis, Herzog von Richelieu, als leitenden Minister in den Rat. Richelieu verfolgte drei Ziele: die Macht der Hugenotten zu brechen, den Hochadel zu zähmen und Frankreich gegen die Habsburger zu stärken.',
            '1627/28 belagerte Richelieu die Hugenottenfestung La Rochelle über ein Jahr lang; ein riesiger Damm schnitt die Stadt vom Meer und von englischer Hilfe ab, und die Einwohner verhungerten. Im „Gnadenedikt“ von Alès 1629 durften die Hugenotten ihren Glauben behalten, verloren aber ihre Festungen. Adlige, die sich verschworen oder Duelle ausfochten, ließ Richelieu hinrichten. In die Provinzen schickte er königliche Beamte, die Intendanten.',
            'Obwohl er Kardinal der katholischen Kirche war, unterstützte Richelieu im Dreißigjährigen Krieg die protestantischen Gegner des Kaisers und trat 1635 offen in den Krieg ein – die Staatsräson ging ihm über die Religion. 1635 gründete er außerdem die Académie française, die die französische Sprache pflegen sollte. Richelieu starb 1642, Ludwig XIII. 1643. Alexandre Dumas machte Richelieu in „Die drei Musketiere“ (1844) zum berühmten Gegenspieler der Helden.',
            'Ludwig XIV. war beim Tod seines Vaters erst vier Jahre alt. Für ihn regierten seine Mutter Anna von Österreich und Richelieus Nachfolger, der italienische Kardinal Jules Mazarin (Giulio Mazzarino). Die hohen Steuern für den Krieg und Mazarins Machtfülle führten zur Fronde (1648–1653), einem Aufstand erst der obersten Gerichtshöfe, der Parlamente, dann des Hochadels. Der Name kommt von einer Kinderschleuder.',
            'In der Nacht zum 6. Januar 1649 musste die königliche Familie aus Paris fliehen. Der junge Ludwig vergaß die Demütigungen nie: Später misstraute er Paris und dem Adel und wollte nie wieder einen Ersten Minister neben sich. Mazarin siegte schließlich. Im Westfälischen Frieden 1648 gewann Frankreich Gebiete im Elsass, im Pyrenäenfrieden mit Spanien 1659 das Roussillon und Teile des Artois; Ludwig XIV. heiratete 1660 die spanische Infantin Maria Theresia.',
            'Als Mazarin am 9. März 1661 starb, erklärte der 22-jährige Ludwig XIV., er werde von nun an selbst regieren.',
          ],
          quiz: {
            leicht: [
              ['Welcher Kardinal war leitender Minister Ludwigs XIII.?', 'Richelieu', ['Mazarin', 'Colbert', 'Sully']],
              ['Welche Hugenottenfestung belagerte Richelieu?', 'La Rochelle', ['Nantes', 'Calais', 'Bordeaux']],
              ['Welche Akademie gründete Richelieu 1635?', 'Die Académie française', ['Die Akademie der Wissenschaften', 'Die Sorbonne', 'Das Collège de France']],
              ['Was sollte die Académie française pflegen?', 'Die französische Sprache', ['Die Malerei', 'Die Musik', 'Die Medizin']],
              ['In welchem Roman ist Richelieu ein berühmter Gegenspieler?', '„Die drei Musketiere“', ['„Les Misérables“', '„Der Graf von Monte Christo“', '„Notre-Dame de Paris“']],
              ['Wer schrieb „Die drei Musketiere“?', 'Alexandre Dumas', ['Victor Hugo', 'Molière', 'Jules Verne']],
              ['Wie alt war Ludwig XIV. beim Tod seines Vaters?', 'Vier Jahre', ['Vierzehn Jahre', 'Vierzig Jahre', 'Ein Jahr']],
              ['Welcher Kardinal folgte Richelieu?', 'Mazarin', ['Fleury', 'Retz', 'Colbert']],
              ['Woher stammte Mazarin?', 'Aus Italien', ['Aus Spanien', 'Aus England', 'Aus Österreich']],
              ['Wie hieß der Aufstand gegen Mazarin?', 'Die Fronde', ['Die Jacquerie', 'Die Kommune', 'Die Liga']],
              ['Woher kommt das Wort „Fronde“?', 'Von einer Kinderschleuder', ['Von einem Fluss', 'Von einer Burg', 'Von einem Anführer']],
              ['Was musste die königliche Familie 1649 tun?', 'Aus Paris fliehen', ['Nach England segeln', 'Abdanken', 'Krieg erklären']],
              ['Wem misstraute Ludwig XIV. danach?', 'Paris und dem Adel', ['Den Bauern', 'Der Kirche', 'Spanien']],
              ['In welchen Krieg trat Frankreich 1635 offen ein?', 'In den Dreißigjährigen Krieg', ['In den Hundertjährigen Krieg', 'In den Siebenjährigen Krieg', 'In den Spanischen Erbfolgekrieg']],
              ['Gegen welche Herrscherfamilie wollte Richelieu Frankreich stärken?', 'Die Habsburger', ['Die Bourbonen', 'Die Tudors', 'Die Romanows']],
              ['Wen heiratete Ludwig XIV. 1660?', 'Die spanische Infantin Maria Theresia', ['Marie Antoinette', 'Anna von Österreich', 'Madame de Pompadour']],
              ['Wann starb Mazarin?', '1661', ['1643', '1648', '1715']],
              ['Was erklärte Ludwig XIV. nach Mazarins Tod?', 'Dass er selbst regieren werde', ['Dass er abdanke', 'Dass er Papst werden wolle', 'Dass er nach Spanien ziehe']],
              ['Wer regierte für den jungen Ludwig XIII.?', 'Seine Mutter Maria von Medici', ['Richelieu sofort', 'Heinrich IV.', 'Der Papst']],
              ['Was ließ Richelieu mit Adligen machen, die Duelle ausfochten?', 'Hinrichten', ['Belohnen', 'Zu Ministern machen', 'Nichts']],
            ],
            mittel: [
              ['Wann wurde Richelieu leitender Minister?', '1624', ['1610', '1635', '1642']],
              ['Welche drei Ziele hatte Richelieu?', 'Hugenotten, Hochadel und Habsburger in Schach halten', ['Kolonien, Handel und Flotte', 'Kirche, Schulen und Kunst', 'Frieden mit allen']],
              ['Wann belagerte Richelieu La Rochelle?', '1627/28', ['1572', '1598', '1648']],
              ['Was schnitt La Rochelle vom Meer ab?', 'Ein riesiger Damm', ['Eine Flotte aus Spanien', 'Eine Eiszeit', 'Ein Erdbeben']],
              ['Welche Hilfe sollte der Damm verhindern?', 'Englische Hilfe', ['Spanische Hilfe', 'Deutsche Hilfe', 'Päpstliche Hilfe']],
              ['Wie heißt das Edikt von 1629?', 'Gnadenedikt von Alès', ['Edikt von Nantes', 'Edikt von Fontainebleau', 'Edikt von Potsdam']],
              ['Was verloren die Hugenotten 1629?', 'Ihre Festungen', ['Ihren Glauben', 'Ihr Leben', 'Ihre Bürgerrechte ganz']],
              ['Wie hießen die königlichen Beamten in den Provinzen?', 'Intendanten', ['Baillis', 'Präfekten', 'Gauleiter']],
              ['Was ging Richelieu über die Religion?', 'Die Staatsräson', ['Die Kunst', 'Die Familie', 'Das Geld']],
              ['Wann starb Richelieu?', '1642', ['1635', '1643', '1661']],
              ['Wann starb Ludwig XIII.?', '1643', ['1642', '1610', '1661']],
              ['Wer regierte neben Mazarin für Ludwig XIV.?', 'Seine Mutter Anna von Österreich', ['Maria von Medici', 'Katharina von Medici', 'Maria Theresia']],
              ['Wie lange dauerte die Fronde?', '1648–1653', ['1610–1624', '1661–1715', '1562–1598']],
              ['Wer begann die Fronde zuerst?', 'Die Parlamente (oberste Gerichtshöfe)', ['Die Bauern', 'Die Hugenotten', 'Die Engländer']],
              ['Wann musste die königliche Familie aus Paris fliehen?', 'Januar 1649', ['Juli 1789', 'August 1572', 'März 1661']],
              ['Welche Gebiete gewann Frankreich 1648?', 'Gebiete im Elsass', ['Die Normandie', 'Savoyen', 'Korsika']],
              ['Welcher Frieden wurde 1659 mit Spanien geschlossen?', 'Der Pyrenäenfrieden', ['Der Westfälische Frieden', 'Der Frieden von Utrecht', 'Der Frieden von Nimwegen']],
              ['Welches Gebiet gewann Frankreich 1659?', 'Das Roussillon', ['Die Bretagne', 'Lothringen', 'Nizza']],
              ['Wie alt war Ludwig XIV. bei Mazarins Tod?', '22 Jahre', ['12 Jahre', '32 Jahre', '4 Jahre']],
              ['Wann erschien „Die drei Musketiere“?', '1844', ['1644', '1789', '1900']],
            ],
            schwer: [
              ['Wie lautet Richelieus vollständiger Name?', 'Armand-Jean du Plessis, Herzog von Richelieu', ['Jules Mazarin', 'Jean-Baptiste Colbert', 'Maximilien de Béthune']],
              ['Wie hieß Mazarin auf Italienisch?', 'Giulio Mazzarino', ['Giulio Medici', 'Giuliano Mazzini', 'Giovanni Mazarini']],
              ['An welchem Tag starb Mazarin?', '9. März 1661', ['14. Mai 1610', '1. September 1715', '6. Januar 1649']],
              ['In welcher Nacht floh die königliche Familie?', 'In der Nacht zum 6. Januar 1649', ['In der Nacht zum 14. Juli 1649', 'In der Nacht zum 24. August 1649', 'In der Nacht zum 1. Mai 1649']],
              ['Wer erhob sich in der zweiten Phase der Fronde?', 'Der Hochadel', ['Die Bauern', 'Die Hugenotten', 'Die Bürger von Lyon']],
              ['Welche Lehre zog Ludwig XIV. aus der Fronde?', 'Nie wieder einen Ersten Minister neben sich zu haben', ['Paris zur einzigen Residenz zu machen', 'Dem Adel mehr Macht zu geben', 'Abzudanken']],
              ['Welche Gebiete gewann Frankreich 1659 außer dem Roussillon?', 'Teile des Artois', ['Burgund', 'Savoyen', 'Korsika']],
              ['Was geschah mit den Einwohnern von La Rochelle bei der Belagerung?', 'Viele verhungerten', ['Sie flohen nach Amerika', 'Sie wurden reich', 'Sie wurden Spanier']],
              ['Warum war Richelieus Kriegseintritt 1635 bemerkenswert?', 'Als Kardinal half er Protestanten gegen den Kaiser', ['Er kämpfte an der Seite Spaniens', 'Er trat dem Kaiser bei', 'Er zog sich zurück']],
              ['Wie lange dauerte die Belagerung von La Rochelle?', 'Über ein Jahr', ['Eine Woche', 'Zehn Jahre', 'Einen Tag']],
              ['Wann heiratete Ludwig XIV.?', '1660', ['1659', '1661', '1648']],
              ['Wer war Anna von Österreich?', 'Die Mutter Ludwigs XIV.', ['Die Frau Ludwigs XIV.', 'Eine Kaiserin aus Wien', 'Die Mutter Ludwigs XIII.']],
              ['Welche Strafe drohte Duellanten unter Richelieu?', 'Die Todesstrafe', ['Eine Geldstrafe', 'Verbannung nach Amerika', 'Gar keine']],
              ['Was war die Aufgabe der Intendanten?', 'Die Provinzen im Auftrag des Königs zu verwalten', ['Kathedralen zu bauen', 'Die Kirche zu leiten', 'Duelle zu veranstalten']],
              ['In welchem Jahr endete die Fronde?', '1653', ['1648', '1659', '1661']],
              ['Wann trat Frankreich offen in den Dreißigjährigen Krieg ein?', '1635', ['1618', '1629', '1648']],
              ['Welcher Satz beschreibt Richelieus Politik?', 'Die Staatsräson geht vor der Religion', ['Die Kirche geht vor dem Staat', 'Frieden um jeden Preis', 'Paris ist eine Messe wert']],
              ['Wer war Maria von Medici für Ludwig XIII.?', 'Seine Mutter', ['Seine Frau', 'Seine Schwester', 'Seine Großmutter']],
              ['Was waren die „Parlamente“ in Frankreich?', 'Oberste Gerichtshöfe', ['Gewählte Volksvertretungen', 'Kirchenversammlungen', 'Adelsclubs']],
              ['Welches Gebiet am Rhein erhielt Frankreich im Westfälischen Frieden?', 'Teile des Elsass', ['Die Pfalz', 'Lothringen ganz', 'Köln']],
            ],
          },
        },
        {
          id: 'sonnenkoenig',
          title: 'Ludwig XIV. und Versailles',
          date: '1661–1715',
          text: [
            'Ludwig XIV., geboren am 5. September 1638, regierte von 1643 bis 1715 – 72 Jahre, länger als jeder andere König Europas. Als Sinnbild wählte er die Sonne, um die sich alles dreht; man nannte ihn den „Sonnenkönig“. Der Satz „Der Staat bin ich“ („L’État, c’est moi“) wird ihm zugeschrieben, ist aber wohl nicht echt. Diese Herrschaftsform, in der der König allein und unbeschränkt regiert, nennt man Absolutismus.',
            'Gleich 1661 ließ Ludwig seinen reichen Finanzminister Nicolas Fouquet verhaften, nachdem dieser ihm in seinem prächtigen Schloss Vaux-le-Vicomte ein glanzvolles Fest gegeben hatte – der König duldete niemanden, der mehr Pracht zeigte als er. Die Baumeister von Vaux-le-Vicomte, der Architekt Louis Le Vau und der Gartenkünstler André Le Nôtre, arbeiteten danach für den König.',
            'Aus einem Jagdschloss seines Vaters ließ Ludwig das gewaltige Schloss Versailles bauen; später leitete Jules Hardouin-Mansart die Arbeiten. Le Nôtre legte die streng geometrischen Gärten an. Der Spiegelsaal (1678–1684) mit 357 Spiegeln wurde zum Prunkstück. Am 6. Mai 1682 zog der Hof ganz nach Versailles. Tausende Adlige lebten dort und mussten am höfischen Zeremoniell teilnehmen, etwa am „Lever“, dem morgendlichen Aufstehen des Königs. So hielt Ludwig den Adel unter Kontrolle.',
            'Sein Finanzminister Jean-Baptiste Colbert (Generalkontrolleur der Finanzen 1665–1683) förderte nach den Ideen des Merkantilismus Ausfuhren und heimische Manufakturen, etwa die Gobelin-Manufaktur für Wandteppiche, und erhob hohe Zölle auf Einfuhren. 1664 gründete er die Ostindische Handelskompanie, 1666 die Akademie der Wissenschaften. Von 1666 bis 1681 wurde der Canal du Midi gebaut, der den Atlantik mit dem Mittelmeer verbindet.',
            'Die Kunst blühte: Molière schrieb Komödien wie „Tartuffe“ über einen religiösen Heuchler und „Der eingebildete Kranke“ – bei dessen vierter Aufführung 1673 brach er auf der Bühne zusammen und starb. Jean Racine schrieb Tragödien wie „Phädra“, der aus Italien stammende Jean-Baptiste Lully komponierte Musik und Ballette für den Hof, in denen der junge König selbst als Sonne tanzte.',
            'Ludwig XIV. starb am 1. September 1715 an Wundbrand. Sein Sohn und sein Enkel waren schon gestorben, und so wurde sein fünfjähriger Urenkel als Ludwig XV. König. Er hinterließ ein prächtiges, aber hoch verschuldetes Land.',
          ],
          quiz: {
            leicht: [
              ['Welchen Beinamen hatte Ludwig XIV.?', 'Sonnenkönig', ['Mondkönig', 'Bürgerkönig', 'Der Heilige']],
              ['Welches Sinnbild wählte Ludwig XIV.?', 'Die Sonne', ['Den Löwen', 'Den Adler', 'Den Bären']],
              ['Welcher Satz wird Ludwig XIV. zugeschrieben?', '„Der Staat bin ich“', ['„Paris ist eine Messe wert“', '„Nach uns die Sintflut“', '„Ich kam, sah und siegte“']],
              ['Wie nennt man die unbeschränkte Herrschaft eines Königs?', 'Absolutismus', ['Demokratie', 'Republik', 'Feudalismus']],
              ['Welches gewaltige Schloss ließ Ludwig XIV. bauen?', 'Versailles', ['Chambord', 'Sanssouci', 'Schönbrunn']],
              ['Welcher Saal in Versailles ist besonders berühmt?', 'Der Spiegelsaal', ['Der Thronsaal aus Gold', 'Der Rittersaal', 'Der Sängersaal']],
              ['Wer legte die Gärten von Versailles an?', 'André Le Nôtre', ['Leonardo da Vinci', 'Vauban', 'Colbert']],
              ['Wie sind die Gärten von Versailles gestaltet?', 'Streng geometrisch', ['Wild wie ein Wald', 'Als englischer Landschaftspark', 'Als Gemüsegarten']],
              ['Wie lange regierte Ludwig XIV.?', '72 Jahre', ['27 Jahre', '7 Jahre', '100 Jahre']],
              ['Welcher Minister förderte Handel und Manufakturen?', 'Colbert', ['Richelieu', 'Mazarin', 'Fouquet']],
              ['Wie nennt man Colberts Wirtschaftspolitik?', 'Merkantilismus', ['Kapitalismus', 'Kommunismus', 'Freihandel']],
              ['Welcher Kanal verbindet Atlantik und Mittelmeer?', 'Der Canal du Midi', ['Der Suezkanal', 'Der Panamakanal', 'Der Nord-Ostsee-Kanal']],
              ['Welcher Komödiendichter lebte am Hof Ludwigs XIV.?', 'Molière', ['Shakespeare', 'Goethe', 'Voltaire']],
              ['Welche Komödie schrieb Molière?', '„Der eingebildete Kranke“', ['„Faust“', '„Hamlet“', '„Die Räuber“']],
              ['Welcher Komponist schrieb Musik für Ludwigs Hof?', 'Lully', ['Mozart', 'Bach', 'Beethoven']],
              ['Als was tanzte der junge König in einem Ballett?', 'Als Sonne', ['Als Mond', 'Als Löwe', 'Als Adler']],
              ['Welchen Finanzminister ließ Ludwig 1661 verhaften?', 'Nicolas Fouquet', ['Colbert', 'Mazarin', 'Sully']],
              ['Wie hinterließ Ludwig XIV. Frankreich?', 'Prächtig, aber hoch verschuldet', ['Arm, aber schuldenfrei', 'Als Republik', 'Erobert von Spanien']],
              ['Wer folgte Ludwig XIV. als König?', 'Sein Urenkel Ludwig XV.', ['Sein Sohn', 'Sein Enkel', 'Sein Bruder']],
              ['Wie hielt Ludwig den Adel unter Kontrolle?', 'Er band ihn an den Hof in Versailles', ['Er ließ alle Adligen hinrichten', 'Er schickte sie nach Amerika', 'Er gab ihnen Paris']],
            ],
            mittel: [
              ['Wann wurde Ludwig XIV. geboren?', '5. September 1638', ['1. September 1715', '14. Juli 1643', '9. März 1661']],
              ['Ist der Satz „Der Staat bin ich“ sicher echt?', 'Nein, wohl nicht', ['Ja, er ist belegt', 'Ja, in einem Brief', 'Er stammt von Napoleon']],
              ['Wo gab Fouquet sein glanzvolles Fest?', 'In Vaux-le-Vicomte', ['In Versailles', 'In Fontainebleau', 'Im Louvre']],
              ['Warum ließ Ludwig Fouquet verhaften?', 'Er duldete niemanden, der mehr Pracht zeigte', ['Fouquet war Hugenotte', 'Fouquet hatte Paris angezündet', 'Fouquet war Spion Englands']],
              ['Welcher Architekt arbeitete zuerst an Vaux-le-Vicomte und Versailles?', 'Louis Le Vau', ['Hardouin-Mansart', 'Vauban', 'Haussmann']],
              ['Wer leitete später die Arbeiten in Versailles?', 'Jules Hardouin-Mansart', ['Le Nôtre', 'Colbert', 'Lully']],
              ['Was war Versailles ursprünglich?', 'Ein Jagdschloss seines Vaters', ['Ein Kloster', 'Eine Festung', 'Ein Bauernhof']],
              ['Wann wurde der Spiegelsaal gebaut?', '1678–1684', ['1661–1665', '1700–1715', '1624–1630']],
              ['Wie viele Spiegel hat der Spiegelsaal?', '357', ['57', '1000', '12']],
              ['Wann zog der Hof ganz nach Versailles?', '6. Mai 1682', ['9. März 1661', '1. September 1715', '14. Juli 1789']],
              ['Wie hieß das morgendliche Aufsteh-Zeremoniell?', 'Lever', ['Coucher', 'Dîner', 'Réveil']],
              ['Wann war Colbert Generalkontrolleur der Finanzen?', '1665–1683', ['1624–1642', '1700–1715', '1661–1715']],
              ['Welche Manufaktur stellte Wandteppiche her?', 'Die Gobelin-Manufaktur', ['Die Porzellanmanufaktur Meißen', 'Die Glashütte Murano', 'Die Seidenweberei Lyon']],
              ['Wann gründete Colbert die Ostindische Handelskompanie?', '1664', ['1600', '1682', '1715']],
              ['Wann wurde die Akademie der Wissenschaften gegründet?', '1666', ['1635', '1700', '1682']],
              ['Wann wurde der Canal du Midi gebaut?', '1666–1681', ['1600–1610', '1700–1720', '1804–1810']],
              ['Was belegte Colbert mit hohen Zöllen?', 'Einfuhren', ['Ausfuhren', 'Brot', 'Bücher']],
              ['Welche Tragödie schrieb Racine?', '„Phädra“', ['„Tartuffe“', '„Der Geizige“', '„Der Cid“']],
              ['Wann starb Molière?', '1673', ['1715', '1682', '1650']],
              ['Woran starb Ludwig XIV.?', 'An Wundbrand', ['An der Pest', 'Durch einen Mord', 'In einer Schlacht']],
            ],
            schwer: [
              ['An welchem Tag starb Ludwig XIV.?', '1. September 1715', ['5. September 1715', '14. Mai 1715', '9. März 1715']],
              ['Wie alt war Ludwig XV. bei seinem Regierungsantritt?', 'Fünf Jahre', ['Fünfzehn Jahre', 'Zwei Jahre', 'Fünfundzwanzig Jahre']],
              ['Warum folgte der Urenkel und nicht Sohn oder Enkel?', 'Sohn und Enkel waren schon gestorben', ['Sie verzichteten', 'Sie waren im Gefängnis', 'Sie waren Spanier']],
              ['Wann ließ Ludwig Fouquet verhaften?', '1661', ['1665', '1682', '1715']],
              ['Bei welcher Aufführung brach Molière zusammen?', 'Bei der vierten Aufführung des „Eingebildeten Kranken“', ['Bei der Premiere des „Tartuffe“', 'Bei einem Ballett Lullys', 'Bei einer Probe in Versailles']],
              ['Welches Molière-Stück handelt von einem Heuchler?', '„Tartuffe“', ['„Der Menschenfeind“', '„Phädra“', '„Der Bürger als Edelmann“']],
              ['Welche Meere verbindet der Canal du Midi über die Garonne?', 'Atlantik und Mittelmeer', ['Nordsee und Ostsee', 'Ärmelkanal und Mittelmeer direkt', 'Schwarzes Meer und Mittelmeer']],
              ['Welche Idee steckt hinter dem Merkantilismus?', 'Mehr ausführen als einführen, um Geld ins Land zu holen', ['Freier Handel ohne Zölle', 'Selbstversorgung ohne Handel', 'Abschaffung des Geldes']],
              ['Welche Rolle spielte das Zeremoniell in Versailles?', 'Es band den Adel an den König', ['Es diente der Unterhaltung der Bauern', 'Es war eine religiöse Messe', 'Es war ein Militärtraining']],
              ['Welcher Gartenkünstler arbeitete erst für Fouquet, dann für den König?', 'André Le Nôtre', ['Louis Le Vau', 'Charles Le Brun', 'Vauban']],
              ['Wie viele Jahre regierte Ludwig XIV. selbst nach Mazarins Tod?', 'Rund 54 Jahre', ['Rund 5 Jahre', 'Rund 72 Jahre', 'Rund 20 Jahre']],
              ['Wann begann Ludwigs Herrschaft offiziell?', '1643', ['1661', '1638', '1648']],
              ['Was unterscheidet Ludwigs Regierungsdauer von allen anderen?', 'Sie ist die längste eines europäischen Königs', ['Sie ist die kürzeste', 'Sie fiel ins Mittelalter', 'Sie war unterbrochen']],
              ['Welche Handelskompanie gründete Colbert 1664?', 'Die Ostindische', ['Die Hanse', 'Die Hudson’s Bay Company', 'Die Hanse']],
              ['Was ist Vaux-le-Vicomte?', 'Fouquets prächtiges Schloss', ['Ein Kloster', 'Ein Palast der Medici', 'Eine Festung Vaubans']],
              ['Welcher Komponist kam aus Italien an Ludwigs Hof?', 'Lully', ['Rameau', 'Couperin', 'Charpentier']],
              ['Was bedeutet „Lever“?', 'Das Aufstehen', ['Das Zubettgehen', 'Das Essen', 'Das Beten']],
              ['Welcher Teil von Versailles entstand von 1678 bis 1684?', 'Der Spiegelsaal', ['Der Park', 'Die Kapelle zuerst', 'Das Jagdschloss']],
              ['Was symbolisierte die Sonne für Ludwig?', 'Dass sich alles um ihn dreht', ['Dass er Gott sei', 'Dass er aus dem Süden stamme', 'Dass er gern draußen sei']],
              ['Welches Jahr markiert Ludwigs Selbstregierung?', '1661', ['1643', '1648', '1682']],
            ],
          },
        },
        {
          id: 'kriege-ludwig-xiv',
          title: 'Ludwigs Kriege und die Hugenottenverfolgung',
          date: '1667–1715',
          text: [
            'Ludwig XIV. wollte Frankreich vergrößern und „natürliche Grenzen“ wie den Rhein erreichen. Im Devolutionskrieg (1667–1668) beanspruchte er Teile der Spanischen Niederlande im Namen seiner Frau. Im Holländischen Krieg (1672–1678) griff er die Niederlande an; im Frieden von Nimwegen 1678 gewann er die Franche-Comté.',
            'Danach ließ er durch eigene Gerichte, die „Reunionskammern“, alte Ansprüche auf Gebiete im Elsass und an der Grenze prüfen und diese besetzen (Reunionen). Am 30. September 1681 nahmen französische Truppen mitten im Frieden die freie Reichsstadt Straßburg ein. Sein Festungsbaumeister Sébastien Le Prestre de Vauban sicherte die neuen Grenzen mit einem Gürtel sternförmiger Festungen, etwa Neuf-Brisach.',
            'Im Pfälzischen Erbfolgekrieg (1688–1697) verwüsteten französische Truppen planmäßig die Pfalz; 1689 und 1693 wurden das Heidelberger Schloss zerstört und Städte wie Mannheim, Worms und Speyer niedergebrannt. Im Frieden von Rijswijk 1697 musste Ludwig einen Teil seiner Eroberungen herausgeben, behielt aber Straßburg.',
            'Als 1700 der letzte spanische Habsburger, König Karl II., starb, erbte Ludwigs Enkel Philipp von Anjou das spanische Weltreich. Gegen diese Machtballung kämpften Österreich, England und die Niederlande im Spanischen Erbfolgekrieg (1701–1714). 1704 wurden die Franzosen bei Höchstädt (englisch Blenheim) vom Herzog von Marlborough und Prinz Eugen besiegt. Im Frieden von Utrecht 1713 (und Rastatt 1714) blieb Philipp V. König von Spanien, durfte aber nie Frankreich erben.',
            'Im Inneren wollte Ludwig nur einen Glauben dulden: „Ein König, ein Gesetz, ein Glaube“. Soldaten wurden zwangsweise bei Hugenotten einquartiert, um sie zur Bekehrung zu zwingen (Dragonaden). Am 18. Oktober 1685 hob Ludwig im Edikt von Fontainebleau das Edikt von Nantes auf. Rund 200.000 Hugenotten flohen trotz Verbots ins Ausland – nach Brandenburg-Preußen, in die Niederlande, nach England und in die Schweiz – und nahmen ihr Können mit. In den Cevennen erhoben sich ab 1702 die protestantischen Kamisarden.',
            'In Nordamerika nahm der Entdecker Robert Cavelier de La Salle 1682 das Gebiet am Mississippi für Frankreich in Besitz und nannte es zu Ehren des Königs Louisiana. Am Ende seines Lebens war Frankreich durch die Kriege erschöpft und hoch verschuldet; Ludwig soll seinem Urenkel geraten haben, er solle nicht so viel Krieg führen wie er.',
          ],
          quiz: {
            leicht: [
              ['Welchen Fluss sah Ludwig XIV. als „natürliche Grenze“?', 'Den Rhein', ['Die Elbe', 'Die Donau', 'Die Loire']],
              ['Welche Stadt besetzte Frankreich 1681 im Frieden?', 'Straßburg', ['Köln', 'Mainz', 'Basel']],
              ['Welcher Festungsbaumeister diente Ludwig XIV.?', 'Vauban', ['Le Nôtre', 'Colbert', 'Le Vau']],
              ['Welche Form hatten Vaubans Festungen?', 'Sternförmig', ['Rund', 'Quadratisch', 'Dreieckig']],
              ['Welches deutsche Schloss wurde 1689 und 1693 zerstört?', 'Das Heidelberger Schloss', ['Neuschwanstein', 'Sanssouci', 'Die Wartburg']],
              ['Welche Region verwüsteten die Franzosen planmäßig?', 'Die Pfalz', ['Bayern', 'Sachsen', 'Holstein']],
              ['Wer erbte 1700 das spanische Weltreich?', 'Ludwigs Enkel Philipp von Anjou', ['Ludwig XIV. selbst', 'Ein Habsburger aus Wien', 'Der König von England']],
              ['Wie heißt der Krieg um das spanische Erbe?', 'Spanischer Erbfolgekrieg', ['Hundertjähriger Krieg', 'Dreißigjähriger Krieg', 'Siebenjähriger Krieg']],
              ['Welcher Frieden beendete 1713 den Spanischen Erbfolgekrieg?', 'Der Frieden von Utrecht', ['Der Frieden von Versailles', 'Der Westfälische Frieden', 'Der Frieden von Paris']],
              ['Was durfte Philipp V. nach 1713 nie?', 'Frankreich erben', ['Spanien regieren', 'Heiraten', 'Nach Paris reisen']],
              ['Welches Edikt hob 1685 das Edikt von Nantes auf?', 'Das Edikt von Fontainebleau', ['Das Edikt von Potsdam', 'Das Edikt von Alès', 'Das Edikt von Worms']],
              ['Wie viele Hugenotten flohen etwa ins Ausland?', 'Rund 200.000', ['Rund 2000', 'Rund 2 Millionen', 'Rund 200']],
              ['In welches deutsche Land flohen viele Hugenotten?', 'Nach Brandenburg-Preußen', ['Nach Bayern', 'Nach Österreich', 'Nach Sachsen']],
              ['Wie lautete Ludwigs Grundsatz zur Religion?', '„Ein König, ein Gesetz, ein Glaube“', ['„Jeder nach seiner Façon“', '„Freiheit für alle“', '„Gott will es“']],
              ['Welches Gebiet in Nordamerika ist nach Ludwig XIV. benannt?', 'Louisiana', ['Virginia', 'Georgia', 'Carolina']],
              ['Welcher Entdecker benannte Louisiana?', 'La Salle', ['Champlain', 'Cartier', 'Cook']],
              ['An welchem Fluss liegt Louisiana?', 'Am Mississippi', ['Am Sankt-Lorenz-Strom', 'Am Amazonas', 'Am Hudson']],
              ['Wie war Frankreich am Ende von Ludwigs Leben?', 'Erschöpft und verschuldet', ['Reich und friedlich', 'Eine Republik', 'Erobert']],
              ['Was soll Ludwig seinem Urenkel geraten haben?', 'Nicht so viel Krieg zu führen', ['Mehr Krieg zu führen', 'Versailles abzureißen', 'Nach Spanien zu ziehen']],
              ['Gegen welches Land führte Ludwig den Krieg von 1672?', 'Die Niederlande', ['England', 'Russland', 'Portugal']],
            ],
            mittel: [
              ['Wann fand der Devolutionskrieg statt?', '1667–1668', ['1672–1678', '1688–1697', '1701–1714']],
              ['In wessen Namen beanspruchte Ludwig Teile der Spanischen Niederlande?', 'Im Namen seiner Frau', ['Im Namen seines Bruders', 'Im Namen des Papstes', 'Im Namen des Kaisers']],
              ['Wann fand der Holländische Krieg statt?', '1672–1678', ['1667–1668', '1688–1697', '1701–1714']],
              ['Welches Gebiet gewann Ludwig 1678 in Nimwegen?', 'Die Franche-Comté', ['Lothringen', 'Savoyen', 'Flandern ganz']],
              ['Wie hießen die Gerichte, die alte Gebietsansprüche prüften?', 'Reunionskammern', ['Parlamente', 'Generalstände', 'Intendanturen']],
              ['An welchem Tag wurde Straßburg besetzt?', '30. September 1681', ['18. Oktober 1685', '1. September 1715', '14. Juli 1681']],
              ['Welche Festung Vaubans ist ein berühmtes Beispiel?', 'Neuf-Brisach', ['Carcassonne', 'Château-Gaillard', 'La Bastille']],
              ['Wann fand der Pfälzische Erbfolgekrieg statt?', '1688–1697', ['1672–1678', '1701–1714', '1618–1648']],
              ['Welche Städte wurden im Pfälzischen Krieg niedergebrannt?', 'Mannheim, Worms und Speyer', ['Köln, Bonn und Aachen', 'München, Augsburg und Ulm', 'Berlin, Potsdam und Dresden']],
              ['Welcher Frieden beendete 1697 den Pfälzischen Krieg?', 'Der Frieden von Rijswijk', ['Der Frieden von Nimwegen', 'Der Frieden von Utrecht', 'Der Frieden von Rastatt']],
              ['Welche Stadt behielt Ludwig 1697?', 'Straßburg', ['Heidelberg', 'Mannheim', 'Freiburg']],
              ['Wann fand der Spanische Erbfolgekrieg statt?', '1701–1714', ['1688–1697', '1667–1668', '1740–1748']],
              ['Welche Länder kämpften gegen Frankreich im Spanischen Erbfolgekrieg?', 'Österreich, England und die Niederlande', ['Russland, Schweden und Polen', 'Spanien, Portugal und Italien', 'Preußen, Sachsen und Bayern']],
              ['Wo wurden die Franzosen 1704 besiegt?', 'Bei Höchstädt (Blenheim)', ['Bei Malplaquet', 'Bei Rossbach', 'Bei Sedan']],
              ['Welche Feldherren siegten 1704?', 'Marlborough und Prinz Eugen', ['Vauban und Turenne', 'Wellington und Blücher', 'Nelson und Drake']],
              ['Wie nannte man die erzwungenen Einquartierungen bei Hugenotten?', 'Dragonaden', ['Reunionen', 'Fronden', 'Razzien']],
              ['Wann wurde das Edikt von Fontainebleau erlassen?', '18. Oktober 1685', ['13. April 1598', '30. September 1681', '1. September 1715']],
              ['Wohin flohen Hugenotten außer Preußen?', 'In die Niederlande, nach England und in die Schweiz', ['Nach Spanien und Italien', 'Nach Russland', 'Nach Österreich']],
              ['Wie hießen die aufständischen Protestanten in den Cevennen?', 'Kamisarden', ['Hugenotten der Liga', 'Frondeure', 'Albigenser']],
              ['Wann nahm La Salle Louisiana in Besitz?', '1682', ['1608', '1715', '1534']],
            ],
            schwer: [
              ['Wie hieß Vauban vollständig?', 'Sébastien Le Prestre de Vauban', ['Louis Le Vau de Vauban', 'Jean de Vauban-Colbert', 'Michel de Vauban']],
              ['In welchem Jahr wurde das Heidelberger Schloss zuerst zerstört?', '1689', ['1693', '1681', '1697']],
              ['Wann begann der Aufstand der Kamisarden?', '1702', ['1685', '1715', '1690']],
              ['Wann wurde der Frieden von Rastatt geschlossen?', '1714', ['1713', '1697', '1678']],
              ['Wie heißt Höchstädt auf Englisch?', 'Blenheim', ['Ramillies', 'Oudenaarde', 'Malplaquet']],
              ['Warum kämpfte Europa gegen Philipp von Anjou als König Spaniens?', 'Aus Angst vor einer französisch-spanischen Übermacht', ['Weil er Protestant war', 'Weil er zu jung war', 'Weil Spanien bankrott war']],
              ['Welcher spanische König starb 1700 als letzter Habsburger?', 'Karl II.', ['Philipp II.', 'Philipp IV.', 'Karl V.']],
              ['Was war an der Besetzung Straßburgs besonders?', 'Sie geschah mitten im Frieden', ['Sie geschah durch Heirat', 'Die Stadt bat darum', 'Sie dauerte zehn Jahre']],
              ['Was verbot Ludwig den Hugenotten 1685 außerdem?', 'Die Auswanderung', ['Den Kirchgang in Paris', 'Das Lesen', 'Das Heiraten']],
              ['Was nahmen die Hugenotten mit ins Ausland?', 'Ihr Können und ihr Wissen', ['Die französische Krone', 'Nichts', 'Ludwigs Schätze']],
              ['Was bedeutet „Reunion“ im Zusammenhang mit Ludwig XIV.?', 'Besetzung von Gebieten aufgrund alter Ansprüche', ['Wiedervereinigung mit Spanien', 'Familientreffen am Hof', 'Ein Friedensvertrag']],
              ['Was bedeutet „Devolution“ in Ludwigs erstem Krieg?', 'Ein Erbrecht, auf das sich Ludwig berief', ['Ein Rückzug', 'Eine Revolution', 'Ein Bündnis']],
              ['In welchem Gebirge liegen die Cevennen?', 'Im Süden Frankreichs (Zentralmassiv)', ['In den Alpen', 'In den Pyrenäen', 'In den Vogesen']],
              ['Welche Grenzen wollte Ludwig erreichen?', '„Natürliche Grenzen“ wie den Rhein', ['Die Grenzen Roms', 'Die Grenzen Karls des Großen', 'Keine neuen Grenzen']],
              ['Was sicherte Vaubans Festungsgürtel?', 'Die neuen Grenzen Frankreichs', ['Die Kolonien', 'Paris', 'Die Pyrenäen gegen Spanien']],
              ['Welche Rolle spielte Prinz Eugen?', 'Feldherr Österreichs gegen Frankreich', ['Französischer Marschall', 'Spanischer König', 'Holländischer Admiral']],
              ['Wie nannte Ludwig das Gebiet am Mississippi?', 'Louisiana', ['Nouvelle-France', 'Acadie', 'Ludovicia']],
              ['Wie viele große Kriege führte Ludwig nach dem Text etwa?', 'Vier', ['Einen', 'Zwanzig', 'Keinen']],
              ['Was blieb Philipp V. nach dem Frieden?', 'König von Spanien', ['König von Frankreich', 'Kaiser', 'Herzog von Anjou ohne Land']],
              ['Welches Ziel hatten die Dragonaden?', 'Hugenotten zur Bekehrung zu zwingen', ['Steuern einzutreiben', 'Soldaten zu ernähren', 'Kriege vorzubereiten']],
            ],
          },
        },
      ],
    },
    {
      id: 'aufklaerung',
      title: 'Aufklärung und Krise des Königtums',
      date: '1715–1789',
      text: [
        'Im 18. Jahrhundert wurde Frankreich zum Zentrum der Aufklärung. Denker wie Voltaire, Montesquieu und Rousseau stellten Kirche und absolute Monarchie in Frage. Gleichzeitig verlor das Königtum durch teure Kriege und Skandale an Ansehen – bis 1789 der Staatsbankrott drohte.',
      ],
      subtopics: [
        {
          id: 'philosophen',
          title: 'Die Philosophen der Aufklärung',
          date: 'um 1720–1789',
          text: [
            'Die Aufklärer, in Frankreich „philosophes“ genannt, wollten mit der Vernunft gegen Aberglauben, Unterdrückung und Vorurteile kämpfen. Charles-Louis de Secondat, Baron de Montesquieu, schrieb 1721 die „Persischen Briefe“, in denen zwei fiktive Perser die französische Gesellschaft verspotten. In seinem Hauptwerk „Vom Geist der Gesetze“ (1748) forderte er die Gewaltenteilung: Gesetzgebung, Regierung und Rechtsprechung sollten getrennt sein, damit niemand zu viel Macht hat. Diese Idee prägt bis heute demokratische Verfassungen.',
            'Voltaire, eigentlich François-Marie Arouet (1694–1778), war der berühmteste Schriftsteller seiner Zeit. Wegen spöttischer Verse saß er 1717 in der Bastille, später lebte er im Exil in England. 1750–1753 war er Gast Friedrichs des Großen in Potsdam. Sein Roman „Candide“ (1759) verspottet die Vorstellung des deutschen Philosophen Leibniz, wir lebten in der „besten aller möglichen Welten“. Er kämpfte gegen religiöse Intoleranz – sein Motto lautete „Écrasez l’infâme“ (Zerschmettert das Niederträchtige).',
            'Berühmt wurde Voltaires Einsatz für Jean Calas, einen Protestanten aus Toulouse, der 1762 zu Unrecht beschuldigt worden war, seinen Sohn ermordet zu haben, um dessen Übertritt zum Katholizismus zu verhindern; er wurde grausam hingerichtet. Voltaire schrieb 1763 den „Traktat über die Toleranz“ und erreichte 1765 die Rehabilitierung von Calas. Seine letzten Jahre verbrachte er in Ferney nahe der Grenze zu Genf.',
            'Jean-Jacques Rousseau (1712–1778) stammte aus Genf. In „Der Gesellschaftsvertrag“ (1762) schrieb er: „Der Mensch ist frei geboren, und überall liegt er in Ketten.“ Die Macht solle vom Volk ausgehen und dem „Gemeinwillen“ (volonté générale) folgen. Im Erziehungsroman „Émile“ (1762) forderte er eine natürliche Erziehung. Beide Bücher wurden verboten.',
            'Denis Diderot aus Langres und der Mathematiker Jean-Baptiste d’Alembert gaben von 1751 bis 1772 die „Encyclopédie“ heraus, ein riesiges Nachschlagewerk in 28 Bänden (17 Text- und 11 Bildbände), das das gesamte Wissen der Zeit – auch über Handwerk und Technik – im Geist der Vernunft darstellte. 1759 wurde sie verboten, erschien aber heimlich weiter. In den Pariser Salons, die gebildete Frauen wie Madame Geoffrin führten, trafen sich Gelehrte zum Gespräch.',
            'Die Ideen der Aufklärer verbreiteten sich in ganz Europa und bereiteten die Revolution von 1789 vor. Während der Revolution wurden Voltaire (1791) und Rousseau (1794) feierlich ins Panthéon in Paris überführt.',
          ],
          quiz: {
            leicht: [
              ['Womit wollten die Aufklärer kämpfen?', 'Mit der Vernunft', ['Mit Waffen', 'Mit Magie', 'Mit Gebeten']],
              ['Wie nannte man die Aufklärer in Frankreich?', '„Philosophes“', ['„Troubadoure“', '„Jakobiner“', '„Hugenotten“']],
              ['Welcher Aufklärer forderte die Gewaltenteilung?', 'Montesquieu', ['Voltaire', 'Rousseau', 'Diderot']],
              ['Welche drei Gewalten sollten getrennt sein?', 'Gesetzgebung, Regierung und Rechtsprechung', ['König, Adel und Kirche', 'Heer, Polizei und Gericht', 'Stadt, Land und Fluss']],
              ['Wie hieß Voltaire eigentlich?', 'François-Marie Arouet', ['Jean-Jacques Rousseau', 'Denis Diderot', 'Charles de Secondat']],
              ['In welchem Gefängnis saß Voltaire 1717?', 'In der Bastille', ['Im Tower', 'In Alcatraz', 'In der Conciergerie']],
              ['Welcher König lud Voltaire nach Potsdam ein?', 'Friedrich der Große', ['Ludwig XV.', 'Katharina die Große', 'Joseph II.']],
              ['Welchen berühmten Roman schrieb Voltaire?', '„Candide“', ['„Émile“', '„Les Misérables“', '„Germinal“']],
              ['Wogegen kämpfte Voltaire besonders?', 'Gegen religiöse Intoleranz', ['Gegen die Wissenschaft', 'Gegen England', 'Gegen den Handel']],
              ['Aus welcher Stadt stammte Rousseau?', 'Aus Genf', ['Aus Paris', 'Aus Lyon', 'Aus Brüssel']],
              ['Welches Buch schrieb Rousseau 1762?', '„Der Gesellschaftsvertrag“', ['„Candide“', '„Vom Geist der Gesetze“', '„Persische Briefe“']],
              ['Wie beginnt der „Gesellschaftsvertrag“?', '„Der Mensch ist frei geboren, und überall liegt er in Ketten“', ['„Ich denke, also bin ich“', '„Alle Menschen sind gleich“', '„Wissen ist Macht“']],
              ['Welcher Erziehungsroman stammt von Rousseau?', '„Émile“', ['„Candide“', '„Werther“', '„Robinson Crusoe“']],
              ['Welches große Nachschlagewerk gaben Diderot und d’Alembert heraus?', 'Die Encyclopédie', ['Den Duden', 'Den Brockhaus', 'Die Bibel']],
              ['Wo trafen sich Gelehrte in Paris zum Gespräch?', 'In Salons', ['In Kasernen', 'In Klöstern', 'In Fabriken']],
              ['Wer führte viele Pariser Salons?', 'Gebildete Frauen', ['Bischöfe', 'Generäle', 'Kinder']],
              ['Welches Ereignis bereiteten die Ideen der Aufklärer vor?', 'Die Revolution von 1789', ['Die Reformation', 'Die Kreuzzüge', 'Den Hundertjährigen Krieg']],
              ['Wohin wurden Voltaire und Rousseau während der Revolution überführt?', 'Ins Panthéon', ['Nach Saint-Denis', 'Nach Versailles', 'Nach Genf']],
              ['Für wen setzte sich Voltaire 1762 ein?', 'Für Jean Calas', ['Für Ludwig XV.', 'Für Rousseau', 'Für die Jesuiten']],
              ['Wurden „Der Gesellschaftsvertrag“ und „Émile“ erlaubt?', 'Nein, sie wurden verboten', ['Ja, der König lobte sie', 'Ja, sie wurden Schulbücher', 'Sie erschienen nie']],
            ],
            mittel: [
              ['Wann erschienen die „Persischen Briefe“?', '1721', ['1748', '1759', '1762']],
              ['Wer verspottet in den „Persischen Briefen“ die Franzosen?', 'Zwei fiktive Perser', ['Zwei Engländer', 'Ein König', 'Ein Papst']],
              ['Wann erschien „Vom Geist der Gesetze“?', '1748', ['1721', '1762', '1789']],
              ['Wann lebte Voltaire?', '1694–1778', ['1712–1778', '1689–1755', '1713–1784']],
              ['Wann war Voltaire Gast in Potsdam?', '1750–1753', ['1717–1720', '1762–1765', '1740–1745']],
              ['Wann erschien „Candide“?', '1759', ['1748', '1762', '1734']],
              ['Was verspottet „Candide“?', 'Die Idee der „besten aller möglichen Welten“', ['Die Revolution', 'Die Monarchie Englands', 'Die Bibel']],
              ['Wie lautete Voltaires Motto?', '„Écrasez l’infâme“', ['„Liberté, égalité, fraternité“', '„Sapere aude“', '„L’État, c’est moi“']],
              ['Wessen wurde Jean Calas beschuldigt?', 'Seinen Sohn ermordet zu haben', ['Den König bestohlen zu haben', 'Eine Kirche angezündet zu haben', 'Spion Englands zu sein']],
              ['Aus welcher Stadt stammte Calas?', 'Aus Toulouse', ['Aus Paris', 'Aus Genf', 'Aus Lyon']],
              ['Welche Religion hatte Jean Calas?', 'Er war Protestant', ['Er war Katholik', 'Er war Jude', 'Er war Muslim']],
              ['Welche Schrift verfasste Voltaire 1763?', '„Traktat über die Toleranz“', ['„Candide“', '„Philosophische Briefe“', '„Zadig“']],
              ['Wann erreichte Voltaire die Rehabilitierung von Calas?', '1765', ['1762', '1778', '1789']],
              ['Wo verbrachte Voltaire seine letzten Jahre?', 'In Ferney nahe Genf', ['In Potsdam', 'In London', 'In der Bastille']],
              ['Wann lebte Rousseau?', '1712–1778', ['1694–1778', '1713–1784', '1689–1755']],
              ['Wie heißt Rousseaus Begriff für den Willen des Volkes?', 'Gemeinwille (volonté générale)', ['Staatsräson', 'Gottesgnadentum', 'Volksgeist']],
              ['Wann erschien die Encyclopédie?', '1751–1772', ['1700–1710', '1789–1799', '1648–1660']],
              ['Wie viele Bände hatte die Encyclopédie?', '28', ['8', '100', '2']],
              ['Welchen Beruf hatte d’Alembert?', 'Mathematiker', ['Maler', 'Bischof', 'General']],
              ['Wann wurde die Encyclopédie verboten?', '1759', ['1751', '1772', '1789']],
            ],
            schwer: [
              ['Wie viele Text- und Bildbände hatte die Encyclopédie?', '17 Text- und 11 Bildbände', ['10 und 18', '28 Textbände', '20 und 8']],
              ['Worüber berichtete die Encyclopédie neben Wissenschaft auch?', 'Über Handwerk und Technik', ['Nur über Theologie', 'Nur über Adelsgeschlechter', 'Über Horoskope']],
              ['Welche Salonnière ist im Text genannt?', 'Madame Geoffrin', ['Madame de Pompadour', 'Marie Antoinette', 'Madame de Staël']],
              ['Wann wurde Voltaire ins Panthéon überführt?', '1791', ['1778', '1794', '1789']],
              ['Wann wurde Rousseau ins Panthéon überführt?', '1794', ['1778', '1791', '1800']],
              ['Wo lebte Voltaire im Exil?', 'In England', ['In Spanien', 'In Russland', 'In Italien']],
              ['Was bedeutet „Écrasez l’infâme“?', 'Zerschmettert das Niederträchtige', ['Freiheit für alle', 'Es lebe der König', 'Gott ist tot']],
              ['Warum soll Calas’ Sohn laut Anklage getötet worden sein?', 'Um seinen Übertritt zum Katholizismus zu verhindern', ['Wegen einer Erbschaft', 'Aus Eifersucht', 'Wegen Schulden']],
              ['Wie wurde Jean Calas bestraft?', 'Er wurde grausam hingerichtet', ['Er wurde verbannt', 'Er wurde freigesprochen', 'Er musste Geld zahlen']],
              ['Welche Idee Montesquieus prägt bis heute Verfassungen?', 'Die Gewaltenteilung', ['Der Gemeinwille', 'Der Merkantilismus', 'Das Gottesgnadentum']],
              ['Wie hieß Montesquieu mit vollem Namen?', 'Charles-Louis de Secondat, Baron de Montesquieu', ['François-Marie Arouet', 'Jean le Rond d’Alembert', 'Claude-Adrien Helvétius']],
              ['Von wem stammt die Vorstellung der „besten aller möglichen Welten“, die „Candide“ verspottet?', 'Von Leibniz', ['Von Rousseau', 'Von Descartes', 'Von Montesquieu']],
              ['Was forderte Rousseau in „Émile“?', 'Eine natürliche Erziehung', ['Strenge Prügelstrafen', 'Erziehung nur durch Priester', 'Keine Schule']],
              ['Wie erschien die Encyclopédie nach dem Verbot?', 'Heimlich weiter', ['Gar nicht mehr', 'Nur in England', 'Als Comic']],
              ['Von wo stammt der Herausgeber Diderot?', 'Aus Frankreich (Langres)', ['Aus Genf', 'Aus Belgien', 'Aus Deutschland']],
              ['Wer hatte die Macht laut Rousseau?', 'Das Volk', ['Der König', 'Die Kirche', 'Der Adel']],
              ['Was verspotteten die „Persischen Briefe“?', 'Die französische Gesellschaft', ['Persien', 'England', 'Die Antike']],
              ['Wofür setzte Voltaire seine Berühmtheit ein?', 'Für Opfer der Justiz und gegen Intoleranz', ['Für den Krieg gegen England', 'Für den Papst', 'Für die Folter']],
              ['Wie hießen die gelehrten Gesprächsrunden der Aufklärung?', 'Salons', ['Clubs der Jakobiner', 'Logen der Templer', 'Akademien des Königs']],
              ['Wann wurde „Der Gesellschaftsvertrag“ veröffentlicht?', '1762', ['1748', '1759', '1789']],
            ],
          },
        },
        {
          id: 'krise-des-koenigtums',
          title: 'Ludwig XV., Ludwig XVI. und die Krise',
          date: '1715–1789',
          text: [
            'Für den fünfjährigen Ludwig XV. regierte bis 1723 sein Onkel Philipp von Orléans (die „Régence“). Er holte den schottischen Bankier John Law, der Papiergeld einführte und Aktien seiner Mississippi-Gesellschaft verkaufte. 1720 platzte diese Spekulationsblase, und viele verloren ihr Vermögen – die Franzosen misstrauten Papiergeld und Banken danach lange.',
            'Ludwig XV. (1715–1774) wurde anfangs „le Bien-Aimé“ (der Vielgeliebte) genannt, verlor aber an Ansehen. Großen Einfluss hatte seine Geliebte Madame de Pompadour (ab 1745), die Künstler und Philosophen förderte. Ihr wird der Satz zugeschrieben: „Nach uns die Sintflut“ („Après nous le déluge“).',
            'Im Siebenjährigen Krieg (1756–1763) kämpfte Frankreich an der Seite Österreichs gegen Preußen und Großbritannien. Im Frieden von Paris 1763 verlor es fast sein ganzes Kolonialreich in Nordamerika (Neufrankreich mit Kanada) und den Großteil seiner Besitzungen in Indien an Großbritannien. 1768 kaufte Frankreich dafür Korsika von Genua – ein Jahr bevor dort Napoleon geboren wurde. Ludwig XV. starb 1774 an den Pocken.',
            'Sein Enkel Ludwig XVI., geboren 1754, war gutmütig, aber unentschlossen; er beschäftigte sich lieber mit Schlosserei und Jagd. 1770 hatte er Marie Antoinette geheiratet, eine Tochter der österreichischen Kaiserin Maria Theresia. Wegen ihrer Verschwendung war sie bald als „Madame Defizit“ verhasst; 1785 schadete ihr die Halsbandaffäre, ein Betrug um ein kostbares Diamantkollier, obwohl sie daran unschuldig war.',
            'Um Großbritannien zu schwächen, unterstützte Frankreich ab 1778 die amerikanischen Kolonien in ihrem Unabhängigkeitskrieg; der junge Marquis de La Fayette kämpfte als Freiwilliger mit. Der Sieg bei Yorktown 1781 war auch ein französischer Erfolg – doch der Krieg verschlang riesige Summen. Reformversuche der Finanzminister Turgot und Jacques Necker scheiterten am Widerstand von Adel und Klerus, die keine Steuern zahlen wollten. Necker veröffentlichte 1781 mit dem „Compte rendu“ erstmals eine Übersicht über die Staatsfinanzen.',
            '1787 verweigerte eine Versammlung von Notabeln neue Steuern. 1788 vernichtete ein Hagelsturm am 13. Juli große Teile der Ernte; der Brotpreis stieg stark. Der Staat stand vor dem Bankrott. Am 8. August 1788 berief Ludwig XVI. die Generalstände für Mai 1789 ein – zum ersten Mal seit 1614.',
          ],
          quiz: {
            leicht: [
              ['Wie alt war Ludwig XV. bei seinem Regierungsantritt?', 'Fünf Jahre', ['Fünfzehn Jahre', 'Fünfundzwanzig Jahre', 'Zwei Jahre']],
              ['Welcher Bankier führte in Frankreich Papiergeld ein?', 'John Law', ['Jacques Necker', 'Colbert', 'Rothschild']],
              ['Was geschah 1720 mit Laws Gesellschaft?', 'Die Spekulationsblase platzte', ['Sie wurde sehr reich', 'Sie kaufte Amerika', 'Sie wurde verstaatlicht']],
              ['Wie wurde Ludwig XV. anfangs genannt?', '„Der Vielgeliebte“', ['„Der Sonnenkönig“', '„Der Heilige“', '„Der Grausame“']],
              ['Welche Geliebte Ludwigs XV. hatte großen Einfluss?', 'Madame de Pompadour', ['Marie Antoinette', 'Jeanne d’Arc', 'Katharina von Medici']],
              ['Welcher Satz wird Madame de Pompadour zugeschrieben?', '„Nach uns die Sintflut“', ['„Sollen sie doch Kuchen essen“', '„Der Staat bin ich“', '„Paris ist eine Messe wert“']],
              ['Was verlor Frankreich 1763 in Nordamerika?', 'Kanada (Neufrankreich)', ['Louisiana', 'Florida', 'Mexiko']],
              ['An wen verlor Frankreich seine Kolonien 1763?', 'An Großbritannien', ['An Spanien', 'An Preußen', 'An die USA']],
              ['Welche Insel kaufte Frankreich 1768?', 'Korsika', ['Sardinien', 'Sizilien', 'Malta']],
              ['Welcher berühmte Franzose wurde 1769 auf Korsika geboren?', 'Napoleon', ['Voltaire', 'Ludwig XVI.', 'La Fayette']],
              ['Woran starb Ludwig XV.?', 'An den Pocken', ['An der Pest', 'Durch die Guillotine', 'In einer Schlacht']],
              ['Wen heiratete Ludwig XVI. 1770?', 'Marie Antoinette', ['Madame de Pompadour', 'Maria Theresia', 'Joséphine']],
              ['Aus welchem Land stammte Marie Antoinette?', 'Aus Österreich', ['Aus Spanien', 'Aus Preußen', 'Aus England']],
              ['Wie nannte man Marie Antoinette spöttisch?', '„Madame Defizit“', ['„Madame Sonnenschein“', '„Die Heilige“', '„Die Gute“']],
              ['Welche Kolonien unterstützte Frankreich ab 1778?', 'Die amerikanischen', ['Die spanischen', 'Die indischen', 'Die australischen']],
              ['Welcher junge Adlige kämpfte in Amerika mit?', 'La Fayette', ['Robespierre', 'Danton', 'Napoleon']],
              ['Wer wollte keine Steuern zahlen?', 'Adel und Klerus', ['Bauern', 'Arbeiter', 'Bürger']],
              ['Welche Versammlung berief Ludwig XVI. 1788 ein?', 'Die Generalstände', ['Den Reichstag', 'Das Parlament von London', 'Die Nationalversammlung']],
              ['Was zerstörte 1788 große Teile der Ernte?', 'Ein Hagelsturm', ['Ein Erdbeben', 'Ein Krieg', 'Eine Überschwemmung']],
              ['Was stieg 1788 stark?', 'Der Brotpreis', ['Der Lohn', 'Die Ernte', 'Die Zahl der Feiertage']],
            ],
            mittel: [
              ['Wer regierte bis 1723 für Ludwig XV.?', 'Philipp von Orléans', ['Kardinal Fleury', 'Madame de Pompadour', 'John Law']],
              ['Wie nennt man diese Zeit der Regentschaft?', 'Régence', ['Fronde', 'Restauration', 'Terreur']],
              ['Aus welchem Land stammte John Law?', 'Aus Schottland', ['Aus Irland', 'Aus den Niederlanden', 'Aus Italien']],
              ['Wie hieß Laws Gesellschaft?', 'Mississippi-Gesellschaft', ['Ostindische Kompanie', 'Hudson’s Bay Company', 'Banque de France']],
              ['Wann platzte Laws Spekulationsblase?', '1720', ['1715', '1763', '1789']],
              ['Ab wann hatte Madame de Pompadour Einfluss?', '1745', ['1715', '1770', '1789']],
              ['Mit wem verbündete sich Frankreich im Siebenjährigen Krieg?', 'Mit Österreich', ['Mit Preußen', 'Mit Großbritannien', 'Mit den Niederlanden']],
              ['Wann fand der Siebenjährige Krieg statt?', '1756–1763', ['1740–1748', '1701–1714', '1778–1783']],
              ['Wie heißt der Frieden von 1763?', 'Frieden von Paris', ['Frieden von Utrecht', 'Frieden von Hubertusburg', 'Frieden von Versailles']],
              ['Was verlor Frankreich 1763 außer Kanada?', 'Den Großteil seiner Besitzungen in Indien', ['Korsika', 'Elsass', 'Die Bretagne']],
              ['Von wem kaufte Frankreich Korsika?', 'Von Genua', ['Von Venedig', 'Von Spanien', 'Vom Papst']],
              ['Wann starb Ludwig XV.?', '1774', ['1763', '1789', '1715']],
              ['Wann wurde Ludwig XVI. geboren?', '1754', ['1774', '1738', '1770']],
              ['Womit beschäftigte sich Ludwig XVI. gern?', 'Mit Schlosserei und Jagd', ['Mit Malerei', 'Mit Theater', 'Mit Seefahrt']],
              ['Wessen Tochter war Marie Antoinette?', 'Maria Theresias', ['Katharinas der Großen', 'Friedrichs des Großen', 'Ludwigs XV.']],
              ['Worum ging es in der Halsbandaffäre?', 'Um einen Betrug mit einem Diamantkollier', ['Um eine verlorene Krone', 'Um ein gestohlenes Gemälde', 'Um einen Mord']],
              ['Wann war die Halsbandaffäre?', '1785', ['1770', '1789', '1774']],
              ['Wann siegten Amerikaner und Franzosen bei Yorktown?', '1781', ['1776', '1778', '1789']],
              ['Welche Finanzminister scheiterten mit Reformen?', 'Turgot und Necker', ['Colbert und Sully', 'Richelieu und Mazarin', 'Law und Fouquet']],
              ['Was veröffentlichte Necker 1781?', 'Eine Übersicht über die Staatsfinanzen', ['Ein Gesetzbuch', 'Eine Zeitung', 'Einen Roman']],
            ],
            schwer: [
              ['Was misstrauten die Franzosen nach 1720 lange?', 'Papiergeld und Banken', ['Dem Adel', 'Der Kirche', 'Dem Handel']],
              ['Wann verweigerten die Notabeln neue Steuern?', '1787', ['1785', '1788', '1774']],
              ['An welchem Tag zerstörte der Hagel die Ernte 1788?', '13. Juli 1788', ['14. Juli 1788', '8. August 1788', '5. Mai 1788']],
              ['Wann berief Ludwig XVI. die Generalstände ein?', '8. August 1788', ['5. Mai 1789', '14. Juli 1789', '13. Juli 1788']],
              ['Wann hatten die Generalstände zuletzt getagt?', '1614', ['1302', '1789', '1715']],
              ['Für wann wurden die Generalstände einberufen?', 'Für Mai 1789', ['Für Juli 1789', 'Für Januar 1788', 'Für Dezember 1789']],
              ['Warum unterstützte Frankreich die Amerikaner?', 'Um Großbritannien zu schwächen', ['Aus Liebe zur Demokratie', 'Weil der Papst es verlangte', 'Um Amerika zu erobern']],
              ['Ab wann unterstützte Frankreich die Amerikaner offiziell?', '1778', ['1776', '1781', '1763']],
              ['Was war Marie Antoinettes Rolle in der Halsbandaffäre?', 'Sie war unschuldig, aber ihr Ruf litt', ['Sie hatte das Kollier gestohlen', 'Sie hatte den Betrug geplant', 'Sie war die Klägerin und gewann Ansehen']],
              ['Wie nannte man Ludwig XV. anfangs auf Französisch?', '„Le Bien-Aimé“', ['„Le Roi-Soleil“', '„Le Bon“', '„Le Juste“']],
              ['Wie lautet „Nach uns die Sintflut“ auf Französisch?', '„Après nous le déluge“', ['„Après moi la mer“', '„Avant nous la nuit“', '„Après la pluie le beau temps“']],
              ['Wie war Ludwig XVI. als Charakter?', 'Gutmütig, aber unentschlossen', ['Grausam und klug', 'Faul und böse', 'Mutig und entschlossen']],
              ['Wann heirateten Ludwig XVI. und Marie Antoinette?', '1770', ['1774', '1789', '1765']],
              ['Was war für Frankreich das Ergebnis des amerikanischen Krieges?', 'Ein Erfolg, aber riesige Schulden', ['Neue Kolonien in Amerika', 'Die Eroberung Englands', 'Keine Kosten']],
              ['Woran scheiterten die Reformen Turgots und Neckers?', 'Am Widerstand von Adel und Klerus', ['Am Volk', 'Am Papst', 'An England']],
              ['Wie nennt man Neckers Finanzbericht von 1781?', '„Compte rendu“', ['„Cahier de doléances“', '„Encyclopédie“', '„Code noir“']],
              ['Wann endete die Régence?', '1723', ['1715', '1720', '1745']],
              ['Was führte John Law ein?', 'Papiergeld', ['Den Franc', 'Den Euro', 'Die Börse in London']],
              ['Wann wurde Napoleon geboren?', '1769', ['1768', '1754', '1789']],
              ['Was drohte dem Staat 1788?', 'Der Bankrott', ['Eine Invasion aus England', 'Eine Pest', 'Eine Hungersnot in Amerika']],
            ],
          },
        },
      ],
    },
  ],
};
