import type { Epoch } from '../types';

export const E4: Epoch = {
  id: 'revolution',
  name: 'Revolution und Napoleon',
  period: '1789–1815',
  events: [
    {
      id: 'franzoesische-revolution',
      title: 'Die Französische Revolution',
      date: '1789–1799',
      text: [
        'Die Revolution von 1789 stürzte die jahrhundertealte Monarchie, verkündete die Menschenrechte und schuf eine Republik – aber sie führte auch in eine Zeit des Terrors. Ihre Ideen „Freiheit, Gleichheit, Brüderlichkeit“ veränderten die ganze Welt.',
      ],
      subtopics: [
        {
          id: 'revolution-1789',
          title: '1789: Bastille und Menschenrechte',
          date: '1789–1791',
          text: [
            'Die französische Gesellschaft war in drei Stände geteilt: Klerus (erster Stand), Adel (zweiter Stand) und alle anderen (dritter Stand) – rund 98 Prozent der Menschen, von reichen Bürgern bis zu armen Bauern. Nur der dritte Stand zahlte die meisten Steuern. Anfang 1789 fragte der Abbé Sieyès in einer berühmten Flugschrift: „Was ist der Dritte Stand? Alles. Was war er bisher? Nichts.“ In „Beschwerdeheften“ (cahiers de doléances) schrieben die Menschen ihre Klagen auf.',
            'Am 5. Mai 1789 traten in Versailles die Generalstände zusammen. Streit gab es sofort um die Abstimmung: nach Ständen (dann hätten Klerus und Adel immer zwei zu eins gewonnen) oder nach Köpfen. Am 17. Juni erklärten sich die Abgeordneten des dritten Standes zur Nationalversammlung. Als man sie aus ihrem Saal aussperrte, schworen sie am 20. Juni im Ballhaus (Serment du Jeu de paume), nicht auseinanderzugehen, bis Frankreich eine Verfassung habe (Ballhausschwur), den der Maler Jacques-Louis David später darstellte.',
            'Der König zog Truppen um Paris zusammen und entließ am 11. Juli den beliebten Minister Necker. Da stürmte das Volk am 14. Juli 1789 die Bastille, ein Gefängnis und Symbol der Willkür, in dem nur noch sieben Gefangene saßen. Ihr Kommandant de Launay wurde getötet. Der 14. Juli ist heute Nationalfeiertag. Der Marquis de La Fayette wurde Kommandant der neuen Nationalgarde; die Kokarde in Blau-Weiß-Rot (die Farben von Paris und das Weiß des Königs) wurde zum Zeichen der Revolution.',
            'Auf dem Land brach die „Große Furcht“ aus: Bauern stürmten Schlösser und verbrannten die Urkunden über ihre Abgaben. In der Nacht des 4. August 1789 schaffte die Nationalversammlung die Vorrechte des Adels und die Feudallasten ab. Am 26. August verkündete sie die „Erklärung der Menschen- und Bürgerrechte“ mit 17 Artikeln. Der erste lautet: „Die Menschen werden frei und gleich an Rechten geboren und bleiben es.“',
            'Am 5. und 6. Oktober 1789 zogen Tausende Pariser Marktfrauen wegen des teuren Brotes nach Versailles und zwangen die königliche Familie, in die Tuilerien nach Paris umzuziehen. Der Satz „Sollen sie doch Kuchen essen“, den man Marie Antoinette zuschreibt, ist erfunden. Die Kirchengüter wurden verstaatlicht, und das Land wurde 1790 in 83 Departements eingeteilt. Olympe de Gouges verlangte 1791 in der „Erklärung der Rechte der Frau und Bürgerin“ gleiche Rechte für Frauen.',
            'In der Nacht zum 21. Juni 1791 versuchte der König mit seiner Familie zu fliehen. In Varennes wurde er erkannt – angeblich vom Postmeister Drouet anhand seines Bildes auf einem Geldschein – und nach Paris zurückgebracht. Das Vertrauen in ihn war zerstört. Im September 1791 trat die erste Verfassung in Kraft: Frankreich wurde eine konstitutionelle Monarchie, in der der König an Gesetze gebunden war.',
          ],
          quiz: {
            leicht: [
              ['Wann begann die Französische Revolution?', '1789', ['1776', '1799', '1815']],
              ['Welches Gebäude stürmte das Volk am 14. Juli 1789?', 'Die Bastille', ['Den Louvre', 'Versailles', 'Notre-Dame']],
              ['Was ist die Bastille?', 'Ein Gefängnis', ['Ein Schloss', 'Eine Kirche', 'Ein Theater']],
              ['Welcher Tag ist Frankreichs Nationalfeiertag?', 'Der 14. Juli', ['Der 1. Mai', 'Der 3. Oktober', 'Der 11. November']],
              ['In wie viele Stände war die Gesellschaft geteilt?', 'Drei', ['Zwei', 'Vier', 'Fünf']],
              ['Wer gehörte zum ersten Stand?', 'Der Klerus', ['Der Adel', 'Die Bauern', 'Die Bürger']],
              ['Wer gehörte zum zweiten Stand?', 'Der Adel', ['Der Klerus', 'Die Bauern', 'Die Arbeiter']],
              ['Wie viel Prozent der Menschen gehörten zum dritten Stand etwa?', 'Rund 98 Prozent', ['Rund 50 Prozent', 'Rund 10 Prozent', 'Rund 2 Prozent']],
              ['Was versprachen die Abgeordneten im Ballhausschwur?', 'Nicht auseinanderzugehen bis zu einer Verfassung', ['Den König zu töten', 'Krieg gegen England zu führen', 'Nach Amerika zu gehen']],
              ['Welche Erklärung wurde am 26. August 1789 verkündet?', 'Die Erklärung der Menschen- und Bürgerrechte', ['Die Unabhängigkeitserklärung', 'Die Magna Carta', 'Das Grundgesetz']],
              ['Welche Farben hatte die Kokarde der Revolution?', 'Blau-Weiß-Rot', ['Schwarz-Rot-Gold', 'Rot-Weiß', 'Grün-Weiß-Rot']],
              ['Wer wurde Kommandant der Nationalgarde?', 'La Fayette', ['Robespierre', 'Napoleon', 'Danton']],
              ['Wer zog im Oktober 1789 nach Versailles?', 'Pariser Marktfrauen', ['Soldaten aus England', 'Bischöfe', 'Adlige']],
              ['Warum zogen die Frauen nach Versailles?', 'Wegen des teuren Brotes', ['Wegen eines Festes', 'Wegen eines Krieges', 'Wegen der Pest']],
              ['Ist der Satz „Sollen sie doch Kuchen essen“ von Marie Antoinette echt?', 'Nein, er ist erfunden', ['Ja, sie sagte ihn', 'Ja, er steht in ihrem Tagebuch', 'Er stammt von Napoleon']],
              ['Wo wurde der fliehende König 1791 erkannt?', 'In Varennes', ['In Calais', 'In Versailles', 'In Brüssel']],
              ['Was wurde Frankreich 1791 laut Verfassung?', 'Eine konstitutionelle Monarchie', ['Eine Republik', 'Eine Diktatur', 'Ein Kaiserreich']],
              ['Welche Frau forderte 1791 gleiche Rechte für Frauen?', 'Olympe de Gouges', ['Marie Antoinette', 'Jeanne d’Arc', 'Madame de Pompadour']],
              ['In welche Einheiten wurde Frankreich 1790 eingeteilt?', 'In Departements', ['In Bundesländer', 'In Kantone', 'In Grafschaften']],
              ['Welcher Maler stellte den Ballhausschwur dar?', 'Jacques-Louis David', ['Eugène Delacroix', 'Claude Monet', 'Pablo Picasso']],
            ],
            mittel: [
              ['Wer schrieb „Was ist der Dritte Stand?“', 'Der Abbé Sieyès', ['Voltaire', 'Robespierre', 'Rousseau']],
              ['Wie beantwortete Sieyès die Frage nach dem Dritten Stand?', '„Alles. Was war er bisher? Nichts.“', ['„Ein Teil des Volkes“', '„Die Diener des Königs“', '„Nichts“']],
              ['Wie hießen die Hefte, in denen das Volk seine Klagen aufschrieb?', 'Cahiers de doléances', ['Compte rendu', 'Encyclopédie', 'Code civil']],
              ['Wann traten die Generalstände zusammen?', '5. Mai 1789', ['14. Juli 1789', '17. Juni 1789', '26. August 1789']],
              ['Worum stritt man bei den Generalständen zuerst?', 'Um die Abstimmung nach Ständen oder Köpfen', ['Um den Sitzplatz des Königs', 'Um einen Krieg', 'Um die Religion']],
              ['Wann erklärte sich der dritte Stand zur Nationalversammlung?', '17. Juni 1789', ['5. Mai 1789', '20. Juni 1789', '14. Juli 1789']],
              ['Wann fand der Ballhausschwur statt?', '20. Juni 1789', ['17. Juni 1789', '14. Juli 1789', '4. August 1789']],
              ['Welchen Minister entließ der König am 11. Juli 1789?', 'Necker', ['Turgot', 'Calonne', 'Colbert']],
              ['Wie viele Gefangene saßen noch in der Bastille?', 'Sieben', ['Siebzig', 'Siebenhundert', 'Keiner']],
              ['Wie hieß der getötete Kommandant der Bastille?', 'De Launay', ['La Fayette', 'Drouet', 'Bailly']],
              ['Woher stammen Blau und Rot der Kokarde?', 'Von den Farben von Paris', ['Von der Fahne Englands', 'Von Napoleon', 'Von der Kirche']],
              ['Wie nennt man die Bauernunruhen im Sommer 1789?', 'Große Furcht', ['Jacquerie', 'Fronde', 'Vendée']],
              ['Was geschah in der Nacht des 4. August 1789?', 'Die Vorrechte des Adels wurden abgeschafft', ['Die Bastille fiel', 'Der König floh', 'Die Republik wurde ausgerufen']],
              ['Wie viele Artikel hatte die Menschenrechtserklärung?', '17', ['7', '30', '100']],
              ['Wie lautet der erste Artikel der Menschenrechtserklärung?', '„Die Menschen werden frei und gleich an Rechten geboren und bleiben es.“', ['„Die Würde des Menschen ist unantastbar.“', '„Alle Macht geht vom König aus.“', '„Der Staat bin ich.“']],
              ['Wohin musste die königliche Familie im Oktober 1789 umziehen?', 'In die Tuilerien nach Paris', ['Nach Fontainebleau', 'Nach Vincennes', 'Nach London']],
              ['Was geschah 1789 mit den Kirchengütern?', 'Sie wurden verstaatlicht', ['Sie wurden dem Papst geschenkt', 'Sie wurden vergrößert', 'Nichts']],
              ['In wie viele Departements wurde Frankreich 1790 eingeteilt?', '83', ['13', '100', '50']],
              ['Wann versuchte der König zu fliehen?', 'Juni 1791', ['Juli 1789', 'August 1792', 'Januar 1793']],
              ['Wann trat die erste Verfassung in Kraft?', 'September 1791', ['August 1789', 'September 1792', 'Juni 1793']],
            ],
            schwer: [
              ['Wer erkannte den König in Varennes angeblich?', 'Der Postmeister Drouet', ['La Fayette', 'Ein Bauer namens Jacques', 'Ein Soldat aus Paris']],
              ['Woran soll Drouet den König erkannt haben?', 'An seinem Bild auf einem Geldschein', ['An seiner Krone', 'An seiner Stimme', 'An seinem Hund']],
              ['Woher stammt das Weiß der Kokarde?', 'Von der Farbe des Königs', ['Von der Fahne der Kirche', 'Von England', 'Vom Schnee']],
              ['Welchen Titel hat das Werk von Olympe de Gouges?', '„Erklärung der Rechte der Frau und Bürgerin“', ['„Vindication of the Rights of Woman“', '„Der Gesellschaftsvertrag“', '„Émile“']],
              ['Wann schrieb Olympe de Gouges ihre Erklärung?', '1791', ['1789', '1793', '1804']],
              ['Was hätte die Abstimmung nach Ständen bedeutet?', 'Klerus und Adel hätten immer zwei zu eins gewonnen', ['Der dritte Stand hätte immer gewonnen', 'Der König hätte allein entschieden', 'Es hätte keine Abstimmung gegeben']],
              ['Was verbrannten die Bauern in der Großen Furcht?', 'Urkunden über ihre Abgaben', ['Kirchen', 'Bücher der Aufklärer', 'Getreide']],
              ['Wie nennt man den Schwur vom 20. Juni 1789 auf Französisch?', 'Serment du Jeu de paume', ['Serment de Versailles', 'Serment de la Bastille', 'Serment civique']],
              ['Warum versammelten sich die Abgeordneten im Ballhaus?', 'Sie waren aus ihrem Saal ausgesperrt worden', ['Weil es dort warm war', 'Weil der König sie dorthin lud', 'Weil dort ein Fest war']],
              ['Was bedeutete die Flucht nach Varennes für den König?', 'Das Vertrauen in ihn war zerstört', ['Er wurde beliebter', 'Er wurde Kaiser', 'Nichts']],
              ['Wann zogen die Marktfrauen nach Versailles?', '5./6. Oktober 1789', ['14. Juli 1789', '4. August 1789', '20. Juni 1791']],
              ['In welchem Monat 1789 wurden die Generalstände eröffnet?', 'Mai', ['Juli', 'Januar', 'Oktober']],
              ['Was hatten Klerus und Adel vor der Revolution?', 'Vorrechte und weitgehende Steuerfreiheit', ['Keine Rechte', 'Nur Pflichten', 'Das Wahlrecht für alle']],
              ['Was war die Bastille außer Gefängnis?', 'Ein Symbol königlicher Willkür', ['Ein Symbol der Freiheit', 'Ein Bahnhof', 'Ein Kloster']],
              ['Welche neue Truppe entstand 1789?', 'Die Nationalgarde', ['Die Fremdenlegion', 'Die Schweizergarde', 'Die Grande Armée']],
              ['Welche Staatsform bestand nach der Verfassung von 1791?', 'Konstitutionelle Monarchie', ['Absolute Monarchie', 'Republik', 'Diktatur']],
              ['Was beendete die Nacht des 4. August?', 'Die Feudallasten', ['Die Monarchie', 'Die Kirche', 'Den Krieg']],
              ['Wofür steht der 14. Juli in Frankreich bis heute?', 'Für den Beginn der Revolution', ['Für den Sieg über England', 'Für die Krönung Napoleons', 'Für das Ende des Krieges']],
              ['Wer stellte die Revolution später in Gemälden dar?', 'Jacques-Louis David', ['Leonardo da Vinci', 'Rembrandt', 'Dürer']],
              ['Wann wurde die Nationalversammlung ausgerufen?', 'Im Juni 1789', ['Im Mai 1789', 'Im Juli 1789', 'Im Januar 1789']],
            ],
          },
        },
        {
          id: 'republik-terror',
          title: 'Republik und Schreckensherrschaft',
          date: '1792–1794',
          text: [
            'Im April 1792 erklärte Frankreich Österreich den Krieg, dem sich Preußen anschloss. Für die Freiwilligen der Rheinarmee schrieb Claude-Joseph Rouget de Lisle in Straßburg ein Kampflied; weil Freiwillige aus Marseille es beim Einzug in Paris sangen, hieß es bald „Marseillaise“ – heute die Nationalhymne.',
            'Am 10. August 1792 stürmten Pariser die Tuilerien; der König wurde abgesetzt und mit seiner Familie eingesperrt. Am 20. September 1792 hielten die französischen Truppen bei Valmy einer preußischen Armee stand. Der Dichter Goethe, der dabei war, schrieb: „Von hier und heute geht eine neue Epoche der Weltgeschichte aus.“ Am 21./22. September rief der neu gewählte Nationalkonvent die Republik aus.',
            'Im Konvent rangen die gemäßigten Girondisten mit den radikalen Jakobinern, die auf den oberen Bänken saßen und deshalb „Bergpartei“ (Montagnards) hießen. Ludwig XVI., nun „Bürger Louis Capet“ genannt, wurde wegen Verrats verurteilt und am 21. Januar 1793 auf der heutigen Place de la Concorde mit der Guillotine hingerichtet. Das Fallbeil hatte der Arzt Joseph-Ignace Guillotin als „menschlichere“ Hinrichtungsart vorgeschlagen.',
            'Frankreich war nun von Feinden umgeben, und in der Vendée erhoben sich ab März 1793 katholische Bauern gegen die Republik. Ein „Wohlfahrtsausschuss“ übernahm die Macht. Im Juni 1793 wurden die Girondisten verhaftet. Am 13. Juli 1793 erstach die junge Charlotte Corday den radikalen Journalisten Jean-Paul Marat in seiner Badewanne; David malte „Der Tod des Marat“. Im August 1793 wurden alle unverheirateten Männer zwischen 18 und 25 Jahren zum Kriegsdienst gezwungen (Levée en masse).',
            'Getragen von den Sansculottes – einfachen Pariser Revolutionären, die statt Kniebundhosen lange Hosen trugen – begann unter Maximilien de Robespierre die „Schreckensherrschaft“ (Terreur, 1793–1794). Nach dem „Gesetz über die Verdächtigen“ konnte fast jeder angeklagt werden. Marie Antoinette wurde am 16. Oktober 1793 hingerichtet, später auch Revolutionäre wie Georges Danton (5. April 1794) und der Chemiker Antoine Lavoisier. Etwa 17.000 Menschen wurden offiziell zum Tod verurteilt, viele weitere ohne Urteil getötet, besonders in der Vendée. Robespierre führte einen „Kult des Höchsten Wesens“ ein.',
            'Die Revolution wollte alles neu ordnen: Ein Revolutionskalender zählte die Jahre ab dem 22. September 1792 (Jahr I) und gab den Monaten neue Namen wie Brumaire, Thermidor oder Germinal. Bald wurde auch das metrische System mit Meter und Kilogramm eingeführt. Am 9. Thermidor (27. Juli 1794) stürzten Robespierres Gegner ihn aus Angst um ihr eigenes Leben; am nächsten Tag wurde er selbst guillotiniert.',
          ],
          quiz: {
            leicht: [
              ['Wie heißt die französische Nationalhymne?', 'Die Marseillaise', ['Die Internationale', 'Gott erhalte', 'Rule Britannia']],
              ['In welcher Stadt wurde die Marseillaise geschrieben?', 'In Straßburg', ['In Marseille', 'In Paris', 'In Lyon']],
              ['Warum heißt das Lied Marseillaise?', 'Freiwillige aus Marseille sangen es in Paris', ['Es wurde in Marseille geschrieben', 'Der König kam aus Marseille', 'Es ist ein Fischerlied']],
              ['Wann wurde Frankreich Republik?', '1792', ['1789', '1793', '1804']],
              ['Wie wurde Ludwig XVI. hingerichtet?', 'Mit der Guillotine', ['Durch Erschießen', 'Durch den Strang', 'Gar nicht']],
              ['Wann wurde Ludwig XVI. hingerichtet?', '1793', ['1789', '1792', '1815']],
              ['Auf welchem heutigen Platz wurde der König hingerichtet?', 'Place de la Concorde', ['Place de la Bastille', 'Place Vendôme', 'Champ de Mars']],
              ['Welche Königin wurde 1793 hingerichtet?', 'Marie Antoinette', ['Joséphine', 'Katharina von Medici', 'Anna von Österreich']],
              ['Wer führte die Schreckensherrschaft an?', 'Robespierre', ['Napoleon', 'La Fayette', 'Ludwig XVI.']],
              ['Wie nennt man die Schreckensherrschaft auf Französisch?', 'Terreur', ['Fronde', 'Régence', 'Restauration']],
              ['Wer erstach Marat?', 'Charlotte Corday', ['Marie Antoinette', 'Olympe de Gouges', 'Joséphine']],
              ['Wo wurde Marat erstochen?', 'In seiner Badewanne', ['Im Bett', 'Auf der Straße', 'Im Konvent']],
              ['Welcher deutsche Dichter war bei Valmy dabei?', 'Goethe', ['Schiller', 'Heine', 'Lessing']],
              ['Welche Radikalen gab es im Konvent?', 'Die Jakobiner', ['Die Hugenotten', 'Die Templer', 'Die Bonapartisten']],
              ['Wie wurden die Gemäßigten im Konvent genannt?', 'Girondisten', ['Jakobiner', 'Royalisten', 'Sansculotten']],
              ['Welche Region erhob sich 1793 gegen die Republik?', 'Die Vendée', ['Die Provence', 'Das Elsass', 'Die Normandie']],
              ['Welches Maßsystem führte die Revolution ein?', 'Das metrische System', ['Das Zollsystem', 'Das Ellensystem', 'Das Meilensystem']],
              ['Was geschah am Ende mit Robespierre?', 'Er wurde selbst guillotiniert', ['Er wurde Kaiser', 'Er floh nach Amerika', 'Er wurde König']],
              ['Welchen Namen erhielt Ludwig XVI. in der Republik?', 'Bürger Louis Capet', ['Bürger Bourbon', 'König Louis', 'Herr Valois']],
              ['Gegen welches Land erklärte Frankreich 1792 den Krieg?', 'Österreich', ['England', 'Spanien', 'Russland']],
            ],
            mittel: [
              ['Wer schrieb die Marseillaise?', 'Rouget de Lisle', ['Robespierre', 'Danton', 'Victor Hugo']],
              ['Wann erklärte Frankreich Österreich den Krieg?', 'April 1792', ['Juli 1789', 'Januar 1793', 'September 1792']],
              ['Welches Land schloss sich Österreich an?', 'Preußen', ['England', 'Spanien', 'Schweden']],
              ['Was geschah am 10. August 1792?', 'Die Tuilerien wurden gestürmt und der König abgesetzt', ['Die Bastille fiel', 'Der König floh', 'Napoleon wurde Kaiser']],
              ['Wann fand die Kanonade von Valmy statt?', '20. September 1792', ['14. Juli 1789', '21. Januar 1793', '27. Juli 1794']],
              ['Was schrieb Goethe über Valmy?', '„Von hier und heute geht eine neue Epoche der Weltgeschichte aus.“', ['„Mehr Licht!“', '„Edel sei der Mensch“', '„Der Krieg ist verloren.“']],
              ['Wann rief der Nationalkonvent die Republik aus?', '21./22. September 1792', ['14. Juli 1789', '21. Januar 1793', '2. Dezember 1804']],
              ['Warum hießen die Jakobiner „Bergpartei“?', 'Sie saßen auf den oberen Bänken', ['Sie kamen aus den Bergen', 'Sie trafen sich auf dem Montmartre', 'Ihr Anführer hieß Berg']],
              ['An welchem Tag wurde Ludwig XVI. hingerichtet?', '21. Januar 1793', ['16. Oktober 1793', '14. Juli 1793', '10. August 1792']],
              ['Wer schlug die Guillotine vor?', 'Der Arzt Joseph-Ignace Guillotin', ['Robespierre', 'Marat', 'Danton']],
              ['Welcher Ausschuss übernahm 1793 die Macht?', 'Der Wohlfahrtsausschuss', ['Der Sicherheitsrat', 'Das Direktorium', 'Das Konsulat']],
              ['Wann wurden die Girondisten verhaftet?', 'Juni 1793', ['Januar 1793', 'Juli 1794', 'September 1792']],
              ['Wann wurde Marat ermordet?', '13. Juli 1793', ['14. Juli 1789', '16. Oktober 1793', '27. Juli 1794']],
              ['Welches Gemälde malte David über Marat?', '„Der Tod des Marat“', ['„Die Freiheit führt das Volk“', '„Der Ballhausschwur“', '„Napoleon überquert die Alpen“']],
              ['Wie hieß die Massenaushebung von 1793?', 'Levée en masse', ['Grande Peur', 'Terreur', 'Thermidor']],
              ['Wann wurde Marie Antoinette hingerichtet?', '16. Oktober 1793', ['21. Januar 1793', '5. April 1794', '27. Juli 1794']],
              ['Welcher Revolutionär wurde am 5. April 1794 hingerichtet?', 'Georges Danton', ['Robespierre', 'Marat', 'Saint-Just']],
              ['Wie viele Menschen wurden in der Terreur offiziell zum Tod verurteilt?', 'Etwa 17.000', ['Etwa 170', 'Etwa 1,7 Millionen', 'Etwa 1700']],
              ['Welchen Kult führte Robespierre ein?', 'Den Kult des Höchsten Wesens', ['Den Kult der Göttin Venus', 'Den Napoleonkult', 'Den Sonnenkult']],
              ['Wann wurde Robespierre gestürzt?', '9. Thermidor (27. Juli 1794)', ['14. Juli 1789', '18. Brumaire 1799', '21. Januar 1793']],
            ],
            schwer: [
              ['Ab welchem Tag zählte der Revolutionskalender das Jahr I?', 'Ab dem 22. September 1792', ['Ab dem 14. Juli 1789', 'Ab dem 1. Januar 1793', 'Ab dem 21. Januar 1793']],
              ['Welcher dieser Namen ist ein Monat des Revolutionskalenders?', 'Germinal', ['Florentin', 'Marianne', 'Concorde']],
              ['Welches Gesetz erlaubte, fast jeden anzuklagen?', 'Das Gesetz über die Verdächtigen', ['Das Ermächtigungsgesetz', 'Die Menschenrechtserklärung', 'Der Code civil']],
              ['Welcher berühmte Chemiker wurde 1794 hingerichtet?', 'Antoine Lavoisier', ['Louis Pasteur', 'Marie Curie', 'Joseph Gay-Lussac']],
              ['Wer erhob sich in der Vendée?', 'Katholische Bauern', ['Protestantische Bürger', 'Englische Soldaten', 'Pariser Arbeiter']],
              ['Wo wurden besonders viele Menschen ohne Urteil getötet?', 'In der Vendée', ['In Lille', 'In Marseille', 'In Straßburg']],
              ['Wer wurde zum Kriegsdienst gezwungen (Levée en masse)?', 'Unverheiratete Männer von 18 bis 25', ['Alle Frauen', 'Nur Adlige', 'Nur Freiwillige']],
              ['Warum stürzten Robespierres Gegner ihn?', 'Aus Angst um ihr eigenes Leben', ['Weil er König werden wollte', 'Weil England es verlangte', 'Weil er Frieden wollte']],
              ['Wann wurde Robespierre hingerichtet?', '28. Juli 1794', ['27. Juli 1794', '21. Januar 1793', '5. April 1794']],
              ['Welche Truppen sangen die Marseillaise beim Einzug in Paris?', 'Freiwillige aus Marseille', ['Soldaten aus Straßburg', 'Die Nationalgarde', 'Österreichische Gefangene']],
              ['Für welche Armee wurde die Marseillaise ursprünglich geschrieben?', 'Für die Rheinarmee', ['Für die Italienarmee', 'Für die Marine', 'Für die Nationalgarde Paris']],
              ['Wie wurde die Guillotine begründet?', 'Als „menschlichere“ Hinrichtungsart', ['Als besonders grausam', 'Als Strafe nur für Adlige', 'Als Werkzeug für Holz']],
              ['Wann begann der Aufstand in der Vendée?', 'März 1793', ['Juli 1789', 'August 1792', 'Juli 1794']],
              ['Wie heißt der Platz der Hinrichtungen damals?', 'Place de la Révolution', ['Place de la Bastille', 'Place de Grève', 'Place Vendôme']],
              ['Welcher Thermidor-Tag beendete die Terreur?', 'Der 9. Thermidor', ['Der 18. Brumaire', 'Der 14. Juillet', 'Der 1. Vendémiaire']],
              ['Welche Einheiten führte das metrische System ein?', 'Meter und Kilogramm', ['Fuß und Pfund', 'Elle und Scheffel', 'Meile und Unze']],
              ['Wie nannte man die einfachen Revolutionäre in langen Hosen?', 'Sansculottes', ['Girondisten', 'Chouans', 'Feuillants']],
              ['Wann wurde der König abgesetzt?', '10. August 1792', ['21. September 1792', '21. Januar 1793', '14. Juli 1789']],
              ['Welcher Maler war selbst Jakobiner?', 'Jacques-Louis David', ['Eugène Delacroix', 'Ingres', 'Watteau']],
              ['Gegen welches Heer hielten die Franzosen bei Valmy stand?', 'Gegen ein preußisches Heer', ['Gegen ein englisches Heer', 'Gegen ein russisches Heer', 'Gegen ein spanisches Heer']],
            ],
          },
        },
        {
          id: 'direktorium-bonaparte',
          title: 'Direktorium und Aufstieg Bonapartes',
          date: '1795–1799',
          text: [
            'Nach dem Sturz Robespierres regierte ab 1795 das Direktorium, eine Regierung aus fünf Direktoren. Es galt als schwach und korrupt; die Reichen genossen das Leben, während die Armen hungerten. Immer wieder musste die Armee Aufstände niederschlagen. Im Oktober 1795 (13. Vendémiaire) ließ ein junger General einen royalistischen Aufstand in Paris mit Kanonen zusammenschießen: Napoleon Bonaparte.',
            'Napoleon (korsisch Napoleone Buonaparte) wurde am 15. August 1769 in Ajaccio auf Korsika geboren, ein Jahr nachdem Frankreich die Insel gekauft hatte. Er besuchte die Militärschule in Brienne und wurde Artillerieoffizier. 1793 machte er sich bei der Rückeroberung von Toulon einen Namen. 1796 heiratete er Joséphine de Beauharnais, eine Witwe aus der Karibikinsel Martinique.',
            'Im Italienfeldzug 1796/97 besiegte Napoleon die Österreicher in einer Reihe glänzender Schlachten, etwa bei Arcole und Rivoli. Im Frieden von Campo Formio 1797 musste Österreich Belgien und die Lombardei abtreten und das linke Rheinufer als französisch anerkennen. In Italien entstanden von Frankreich abhängige „Tochterrepubliken“. Napoleon wurde in Frankreich zum gefeierten Helden.',
            '1798 brach er nach Ägypten auf, um Großbritanniens Weg nach Indien zu bedrohen. Er siegte in der „Schlacht bei den Pyramiden“ und soll zu seinen Soldaten gesagt haben: „Soldaten, vierzig Jahrhunderte blicken auf euch herab!“ Doch am 1. August 1798 vernichtete der britische Admiral Horatio Nelson die französische Flotte bei Abukir. Napoleon hatte über 150 Wissenschaftler mitgenommen; 1799 fanden französische Soldaten den Stein von Rosetta mit demselben Text in Hieroglyphen, demotischer Schrift und Griechisch, mit dessen Hilfe Jean-François Champollion 1822 die Hieroglyphen entzifferte.',
            '1799 kehrte Napoleon heimlich nach Frankreich zurück und ließ seine Armee in Ägypten zurück. Am 18. Brumaire – Brumaire war der „Nebelmonat“ im Herbst – (9. November 1799) stürzte er zusammen mit dem Direktor Sieyès das Direktorium; Soldaten vertrieben die Abgeordneten. Napoleon wurde Erster Konsul und damit Herrscher Frankreichs. Er erklärte: „Die Revolution ist beendet.“',
          ],
          quiz: {
            leicht: [
              ['Wie hieß die Regierung nach Robespierre ab 1795?', 'Das Direktorium', ['Das Konsulat', 'Der Konvent', 'Das Kaiserreich']],
              ['Aus wie vielen Direktoren bestand das Direktorium?', 'Fünf', ['Drei', 'Zwei', 'Zehn']],
              ['Wie galt das Direktorium?', 'Als schwach und korrupt', ['Als stark und ehrlich', 'Als besonders beliebt', 'Als königstreu']],
              ['Wo wurde Napoleon geboren?', 'Auf Korsika', ['In Paris', 'Auf Elba', 'In Italien']],
              ['In welcher Stadt wurde Napoleon geboren?', 'In Ajaccio', ['In Bastia', 'In Marseille', 'In Nizza']],
              ['Welche Waffengattung wählte Napoleon?', 'Die Artillerie', ['Die Kavallerie', 'Die Marine', 'Die Infanterie']],
              ['Wen heiratete Napoleon 1796?', 'Joséphine de Beauharnais', ['Marie-Louise', 'Marie Antoinette', 'Désirée Clary']],
              ['Wo siegte Napoleon 1796/97?', 'In Italien', ['In Russland', 'In England', 'In Spanien']],
              ['In welches Land zog Napoleon 1798?', 'Nach Ägypten', ['Nach Indien', 'Nach Amerika', 'Nach Russland']],
              ['Was soll Napoleon bei den Pyramiden gesagt haben?', '„Vierzig Jahrhunderte blicken auf euch herab!“', ['„Ich kam, sah und siegte!“', '„Der Staat bin ich!“', '„Vorwärts, Marsch!“']],
              ['Welcher britische Admiral vernichtete die französische Flotte?', 'Horatio Nelson', ['Francis Drake', 'Wellington', 'James Cook']],
              ['Welcher berühmte Stein wurde 1799 in Ägypten gefunden?', 'Der Stein von Rosetta', ['Der Stein der Weisen', 'Der Blarney-Stein', 'Der Stein von Gizeh']],
              ['Wer entzifferte die Hieroglyphen?', 'Champollion', ['Napoleon', 'Nelson', 'Rousseau']],
              ['Wann stürzte Napoleon das Direktorium?', '1799', ['1795', '1804', '1815']],
              ['Welches Amt übernahm Napoleon 1799?', 'Erster Konsul', ['Kaiser', 'König', 'Präsident']],
              ['Was erklärte Napoleon 1799?', '„Die Revolution ist beendet“', ['„Die Revolution beginnt“', '„Es lebe der König“', '„Ich bin Gott“']],
              ['Wen nahm Napoleon nach Ägypten mit?', 'Wissenschaftler', ['Den Papst', 'Den König', 'Seine Mutter']],
              ['Wie kehrte Napoleon aus Ägypten zurück?', 'Heimlich, ohne seine Armee', ['Mit der ganzen Armee', 'Als Gefangener', 'Gar nicht']],
              ['Womit schlug Napoleon 1795 einen Aufstand nieder?', 'Mit Kanonen', ['Mit Reden', 'Mit Geld', 'Mit Gift']],
              ['Wogegen wollte Napoleon in Ägypten vorgehen?', 'Gegen Großbritanniens Weg nach Indien', ['Gegen Russland', 'Gegen Spanien', 'Gegen den Papst']],
            ],
            mittel: [
              ['Ab wann regierte das Direktorium?', '1795', ['1792', '1799', '1804']],
              ['Was für einen Aufstand schlug Napoleon im Oktober 1795 nieder?', 'Einen royalistischen', ['Einen jakobinischen', 'Einen Bauernaufstand', 'Einen Arbeiterstreik']],
              ['Wann wurde Napoleon geboren?', '15. August 1769', ['14. Juli 1769', '5. Mai 1769', '2. Dezember 1769']],
              ['Welche Militärschule besuchte Napoleon?', 'Brienne', ['Saint-Cyr', 'Sandhurst', 'West Point']],
              ['Wo machte sich Napoleon 1793 einen Namen?', 'Bei Toulon', ['Bei Valmy', 'In der Vendée', 'In Ägypten']],
              ['Woher stammte Joséphine?', 'Von Martinique', ['Von Korsika', 'Aus Paris', 'Aus Österreich']],
              ['Wo siegte Napoleon in Italien?', 'Bei Arcole und Rivoli', ['Bei Austerlitz und Jena', 'Bei Marengo und Wagram', 'Bei Waterloo und Ligny']],
              ['Welcher Frieden beendete 1797 den Italienfeldzug?', 'Frieden von Campo Formio', ['Frieden von Lunéville', 'Frieden von Amiens', 'Frieden von Tilsit']],
              ['Was musste Österreich 1797 abtreten?', 'Belgien', ['Tirol', 'Ungarn', 'Böhmen']],
              ['Wie hießen die von Frankreich abhängigen Staaten in Italien?', 'Tochterrepubliken', ['Rheinbundstaaten', 'Kolonien', 'Protektorate']],
              ['Wann zog Napoleon nach Ägypten?', '1798', ['1796', '1799', '1801']],
              ['Wann vernichtete Nelson die französische Flotte?', '1. August 1798', ['21. Oktober 1805', '9. November 1799', '15. August 1798']],
              ['Wo wurde die französische Flotte vernichtet?', 'Bei Abukir', ['Bei Trafalgar', 'Bei Toulon', 'Bei Alexandria']],
              ['Wie viele Wissenschaftler nahm Napoleon etwa mit?', 'Über 150', ['Rund 5', 'Rund 15', 'Rund 1500']],
              ['Wann entzifferte Champollion die Hieroglyphen?', '1822', ['1799', '1804', '1850']],
              ['Mit welchem Direktor stürzte Napoleon das Direktorium?', 'Sieyès', ['Barras', 'Talleyrand', 'Fouché']],
              ['Wie nennt man den Staatsstreich von 1799?', '18. Brumaire', ['9. Thermidor', '13. Vendémiaire', '14. Juillet']],
              ['Welches Datum entspricht dem 18. Brumaire?', '9. November 1799', ['14. Juli 1799', '2. Dezember 1799', '27. Juli 1799']],
              ['Wer vertrieb die Abgeordneten beim Staatsstreich?', 'Soldaten', ['Pariser Bürger', 'Die Polizei', 'Niemand']],
              ['Wie nennt man Napoleons Regierungsform ab 1799?', 'Konsulat', ['Direktorium', 'Kaiserreich', 'Republik der Jakobiner']],
            ],
            schwer: [
              ['Wie viele Jahre nach dem Kauf Korsikas wurde Napoleon geboren?', 'Ein Jahr', ['Zehn Jahre', 'Hundert Jahre', 'Ein Jahr davor']],
              ['Wie hieß Napoleons Vorname auf Korsisch?', 'Napoleone Buonaparte', ['Napoleone Bonaparto', 'Leone Bonaparte', 'Paolo Buonaparte']],
              ['Welchen Rang hatte Joséphine vor der Ehe?', 'Sie war Witwe', ['Sie war Prinzessin', 'Sie war Nonne', 'Sie war Schauspielerin']],
              ['Welches Gebiet musste Österreich 1797 anerkennen?', 'Das linke Rheinufer als französisch', ['Die Unabhängigkeit Ungarns', 'Die Teilung Polens', 'Die Herrschaft Englands']],
              ['Welche Schlacht gewann Napoleon 1798 in Ägypten?', 'Die Schlacht bei den Pyramiden', ['Die Schlacht von Abukir zur See', 'Die Schlacht von Akkon', 'Die Schlacht von Marengo']],
              ['Was ließ Napoleon in Ägypten zurück?', 'Seine Armee', ['Seine Frau', 'Seinen Bruder', 'Nichts']],
              ['Welchem Ziel diente der Stein von Rosetta?', 'Er half, die Hieroglyphen zu entziffern', ['Er war Napoleons Thron', 'Er war eine Grabplatte', 'Er war ein Meilenstein']],
              ['In welchen Sprachen war der Stein von Rosetta beschriftet?', 'In Hieroglyphen, Demotisch und Griechisch', ['In Latein und Arabisch', 'In Französisch und Englisch', 'Nur in Hieroglyphen']],
              ['Wann besiegte Napoleon den royalistischen Aufstand?', 'Im Oktober 1795 (13. Vendémiaire)', ['Im Juli 1794', 'Im November 1799', 'Im Dezember 1804']],
              ['Wie verhielt sich das Direktorium gegenüber Armen und Reichen?', 'Die Reichen genossen, die Armen hungerten', ['Es verteilte alles gleich', 'Es förderte die Armen', 'Es enteignete die Reichen']],
              ['Wer stand Napoleon beim Staatsstreich als Verbündeter zur Seite?', 'Der Abbé Sieyès', ['Robespierre', 'Ludwig XVIII.', 'Danton']],
              ['Welcher Ort in Italien ist ein Sieg Napoleons 1797?', 'Rivoli', ['Pavia', 'Marignano', 'Solferino']],
              ['Welche Rolle hatte Napoleon bei Toulon?', 'Artillerieoffizier', ['Admiral', 'Bürgermeister', 'Spion']],
              ['Was wollte Großbritannien in Ägypten schützen?', 'Den Weg nach Indien', ['Die Pyramiden', 'Den Suezkanal, den es schon gab', 'Seine Kolonien in Amerika']],
              ['Was bedeutete der Titel „Erster Konsul“ praktisch?', 'Napoleon war Herrscher Frankreichs', ['Er war ein Berater', 'Er war Bürgermeister von Paris', 'Er war Oberbefehlshaber ohne Macht']],
              ['Wann heiratete Napoleon Joséphine?', '1796', ['1795', '1804', '1810']],
              ['Wofür nutzte Napoleon seine Erfolge in Italien?', 'Er wurde zum gefeierten Helden', ['Er wurde vergessen', 'Er wurde angeklagt', 'Er ging ins Kloster']],
              ['Welches Gebiet trat Österreich 1797 außer Belgien de facto ab?', 'Die Lombardei', ['Tirol', 'Böhmen', 'Galizien']],
              ['Welcher Monat des Revolutionskalenders ist Brumaire?', 'Der „Nebelmonat“ im Herbst', ['Der Hitzemonat im Sommer', 'Der Blütenmonat', 'Der Schneemonat']],
              ['Wie lange regierte das Direktorium?', 'Von 1795 bis 1799', ['Von 1792 bis 1795', 'Von 1799 bis 1804', 'Von 1789 bis 1792']],
            ],
          },
        },
      ],
    },
    {
      id: 'napoleon',
      title: 'Napoleon Bonaparte',
      date: '1799–1821',
      text: [
        'Als Erster Konsul und dann als Kaiser baute Napoleon einen modernen Staat auf, dessen Einrichtungen bis heute bestehen. Gleichzeitig führte er Krieg in ganz Europa, bis sein Reich nach dem Russlandfeldzug zusammenbrach.',
      ],
      subtopics: [
        {
          id: 'konsulat-kaiserreich',
          title: 'Code civil und Kaiserkrönung',
          date: '1799–1804',
          text: [
            'Als Erster Konsul ordnete Napoleon Frankreich neu. 1800 setzte er in jedem Departement einen Präfekten ein, der direkt der Regierung in Paris unterstand – ein zentralistisches System, das bis heute besteht. Im selben Jahr wurde die Banque de France gegründet. 1802 entstanden die Lycées als Gymnasien für den Nachwuchs des Staates, und Napoleon stiftete die Ehrenlegion, bis heute Frankreichs höchsten Orden.',
            'Mit Papst Pius VII. schloss er 1801 ein Konkordat: Der Katholizismus wurde als „Religion der Mehrheit der Franzosen“ anerkannt, der Staat bezahlte die Priester, die Kirche verzichtete auf ihre enteigneten Güter. 1802 ließ sich Napoleon in einer Volksabstimmung zum Konsul auf Lebenszeit machen.',
            'Am 21. März 1804 trat der „Code civil des Français“ in Kraft, später „Code Napoléon“ genannt, mit 2281 Artikeln. Er garantierte Gleichheit vor dem Gesetz, Schutz des Eigentums, Religionsfreiheit und die Zivilehe mit Scheidung – gab aber Ehemännern viel Macht über ihre Frauen. Der Code verbreitete sich in viele Länder Europas und der Welt und gilt in Frankreich in überarbeiteter Form bis heute. Napoleon sagte später, sein wahrer Ruhm seien nicht seine Schlachten, sondern dieses Gesetzbuch.',
            'Nicht alles war fortschrittlich: 1802 führte Napoleon in den Kolonien die Sklaverei wieder ein, die die Revolution 1794 abgeschafft hatte. In Haiti (Saint-Domingue, dem Westteil der Insel Hispaniola) hatten sich die Versklavten unter Toussaint Louverture erhoben; Napoleon ließ ihn gefangen nehmen, doch seine Truppen wurden geschlagen, und Haiti erklärte am 1. Januar 1804 seine Unabhängigkeit. 1803 verkaufte Napoleon das riesige Louisiana für 15 Millionen Dollar an die USA.',
            'Im März 1804 ließ Napoleon den Herzog von Enghien, einen Bourbonen, entführen und erschießen, weil er ihn einer Verschwörung verdächtigte. Im Mai 1804 wurde er zum „Kaiser der Franzosen“ erklärt. Am 2. Dezember 1804 fand in Notre-Dame die Krönung statt: Im Beisein von Papst Pius VII. setzte sich Napoleon die Krone selbst auf und krönte dann Joséphine. Jacques-Louis David hielt die Szene in einem riesigen Gemälde fest.',
            'Viele Bewunderer waren enttäuscht. Ludwig van Beethoven, der Napoleon seine dritte Sinfonie widmen wollte, soll den Namen auf dem Titelblatt wütend ausgekratzt haben; die Sinfonie hieß dann „Eroica“.',
          ],
          quiz: {
            leicht: [
              ['Welches berühmte Gesetzbuch ließ Napoleon schaffen?', 'Den Code civil', ['Die Magna Carta', 'Das Grundgesetz', 'Die Goldene Bulle']],
              ['Wie nennt man den Code civil auch?', 'Code Napoléon', ['Code Louis', 'Code de Paris', 'Code Bonaparte']],
              ['Was garantierte der Code civil?', 'Gleichheit vor dem Gesetz', ['Vorrechte für den Adel', 'Das Wahlrecht für Frauen', 'Die Abschaffung des Eigentums']],
              ['Gilt der Code civil heute noch?', 'Ja, in überarbeiteter Form', ['Nein, er wurde 1815 abgeschafft', 'Nur in Korsika', 'Nur in Haiti']],
              ['Welchen Orden stiftete Napoleon 1802?', 'Die Ehrenlegion', ['Das Eiserne Kreuz', 'Den Hosenbandorden', 'Den Orden vom Goldenen Vlies']],
              ['Welche Schulen gründete Napoleon?', 'Die Lycées', ['Die Universitäten von Oxford', 'Die Kindergärten', 'Die Sorbonne']],
              ['Welche Bank wurde 1800 gegründet?', 'Die Banque de France', ['Die Bank of England', 'Die Deutsche Bank', 'Die Weltbank']],
              ['Wen setzte Napoleon in jedem Departement ein?', 'Einen Präfekten', ['Einen König', 'Einen Bischof', 'Einen Bürgermeister des Volkes']],
              ['Mit welchem Papst schloss Napoleon ein Konkordat?', 'Pius VII.', ['Pius IX.', 'Leo XIII.', 'Johannes Paul II.']],
              ['Wann wurde Napoleon Kaiser?', '1804', ['1799', '1810', '1815']],
              ['Wo wurde Napoleon gekrönt?', 'In Notre-Dame de Paris', ['In Reims', 'In Rom', 'In Versailles']],
              ['Wer setzte Napoleon die Krone auf?', 'Er selbst', ['Der Papst', 'Joséphine', 'Talleyrand']],
              ['Welchen Titel trug Napoleon als Kaiser?', '„Kaiser der Franzosen“', ['„Kaiser von Frankreich“', '„König von Frankreich“', '„Kaiser von Europa“']],
              ['Wer malte die Krönung Napoleons?', 'Jacques-Louis David', ['Delacroix', 'Goya', 'Monet']],
              ['Welches Land wurde 1804 unabhängig?', 'Haiti', ['Kanada', 'Mexiko', 'Algerien']],
              ['Wer führte den Aufstand in Haiti an?', 'Toussaint Louverture', ['Simón Bolívar', 'Napoleon', 'George Washington']],
              ['Welches Gebiet verkaufte Napoleon 1803 an die USA?', 'Louisiana', ['Kanada', 'Florida', 'Alaska']],
              ['Was führte Napoleon 1802 wieder ein?', 'Die Sklaverei in den Kolonien', ['Die Monarchie', 'Den Revolutionskalender', 'Die Inquisition']],
              ['Welcher Komponist strich Napoleons Namen von seiner Sinfonie?', 'Beethoven', ['Mozart', 'Haydn', 'Bach']],
              ['Wie heißt Beethovens dritte Sinfonie?', '„Eroica“', ['„Pastorale“', '„Ode an die Freude“', '„Unvollendete“']],
            ],
            mittel: [
              ['Wann setzte Napoleon Präfekten ein?', '1800', ['1799', '1804', '1815']],
              ['Wann wurden die Lycées gegründet?', '1802', ['1800', '1806', '1789']],
              ['Wann schloss Napoleon das Konkordat?', '1801', ['1799', '1804', '1789']],
              ['Wie wurde der Katholizismus im Konkordat bezeichnet?', 'Als „Religion der Mehrheit der Franzosen“', ['Als Staatsreligion', 'Als verbotene Religion', 'Als einzige Religion']],
              ['Wer bezahlte nach dem Konkordat die Priester?', 'Der Staat', ['Der Papst', 'Die Gemeinden', 'Niemand']],
              ['Worauf verzichtete die Kirche im Konkordat?', 'Auf ihre enteigneten Güter', ['Auf den Papst', 'Auf Gottesdienste', 'Auf Bischöfe']],
              ['Wann wurde Napoleon Konsul auf Lebenszeit?', '1802', ['1799', '1804', '1801']],
              ['Wann trat der Code civil in Kraft?', '21. März 1804', ['2. Dezember 1804', '14. Juli 1804', '1. Januar 1800']],
              ['Wie viele Artikel hatte der Code civil?', '2281', ['281', '17', '10.000']],
              ['Wem gab der Code civil viel Macht?', 'Den Ehemännern über ihre Frauen', ['Den Frauen', 'Den Kindern', 'Den Priestern']],
              ['Welche Eheform führte der Code civil ein?', 'Die Zivilehe mit Scheidung', ['Die Kirchenehe', 'Die Vielehe', 'Gar keine']],
              ['Was sah Napoleon als seinen wahren Ruhm?', 'Den Code civil', ['Austerlitz', 'Die Krönung', 'Ägypten']],
              ['Wann schaffte die Revolution die Sklaverei ab?', '1794', ['1789', '1802', '1848']],
              ['Wie hieß Haiti als französische Kolonie?', 'Saint-Domingue', ['Martinique', 'Guadeloupe', 'Cayenne']],
              ['Wann erklärte Haiti seine Unabhängigkeit?', '1. Januar 1804', ['14. Juli 1804', '2. Dezember 1804', '21. März 1804']],
              ['Für wie viel Geld verkaufte Napoleon Louisiana?', '15 Millionen Dollar', ['1 Million Dollar', '150 Millionen Dollar', '15.000 Dollar']],
              ['Welchen Bourbonen ließ Napoleon 1804 erschießen?', 'Den Herzog von Enghien', ['Ludwig XVIII.', 'Karl X.', 'Den Grafen von Artois']],
              ['Wann fand die Kaiserkrönung statt?', '2. Dezember 1804', ['21. März 1804', '1. Januar 1804', '18. Mai 1804']],
              ['Wen krönte Napoleon nach sich selbst?', 'Joséphine', ['Seinen Bruder', 'Den Papst', 'Seine Mutter']],
              ['Wann wurde Napoleon zum Kaiser erklärt?', 'Im Mai 1804', ['Im Dezember 1804', 'Im März 1804', 'Im November 1799']],
            ],
            schwer: [
              ['Wie heißt der Code civil im vollen Titel?', '„Code civil des Français“', ['„Code de l’Empire“', '„Code Bonaparte“', '„Code de la République“']],
              ['Welches System schuf Napoleon mit den Präfekten?', 'Ein zentralistisches, das bis heute besteht', ['Ein föderalistisches', 'Ein feudales', 'Ein kirchliches']],
              ['Wie entschied Napoleon über das Konsulat auf Lebenszeit?', 'Durch eine Volksabstimmung', ['Durch den Papst', 'Durch einen Krieg', 'Durch Losentscheid']],
              ['Was geschah mit Toussaint Louverture?', 'Er wurde gefangen genommen', ['Er wurde Kaiser von Haiti', 'Er wurde General Napoleons', 'Er floh nach Amerika']],
              ['Wann verkaufte Napoleon Louisiana?', '1803', ['1802', '1804', '1812']],
              ['Wann wurde der Herzog von Enghien erschossen?', 'März 1804', ['Dezember 1804', 'Mai 1802', 'Januar 1801']],
              ['Warum ließ Napoleon den Herzog von Enghien töten?', 'Er verdächtigte ihn einer Verschwörung', ['Wegen eines Duells', 'Weil er Spion Russlands war', 'Weil er Joséphine beleidigte']],
              ['Was tat Beethoven angeblich mit Napoleons Namen?', 'Er kratzte ihn wütend aus', ['Er schrieb ihn in Gold', 'Er vertonte ihn', 'Er widmete ihm eine Oper']],
              ['Was bedeutet „Eroica“?', 'Die Heldenhafte', ['Die Traurige', 'Die Fröhliche', 'Die Kaiserliche']],
              ['Welche Rechte garantierte der Code civil außer Gleichheit?', 'Schutz des Eigentums und Religionsfreiheit', ['Wahlrecht für Frauen', 'Recht auf Arbeit', 'Recht auf Bildung für alle']],
              ['Wohin verbreitete sich der Code civil?', 'In viele Länder Europas und der Welt', ['Nur nach Korsika', 'Nirgendwohin', 'Nur nach England']],
              ['Welche Stellung hat die Ehrenlegion heute?', 'Höchster Orden Frankreichs', ['Abgeschafft', 'Ein Sportverein', 'Eine Militärschule']],
              ['Wer war beim Kaiserkrönungs-Gemälde anwesend, setzte aber nicht die Krone auf?', 'Papst Pius VII.', ['Ludwig XVIII.', 'Talleyrand', 'Joséphines Vater']],
              ['Was war die Banque de France?', 'Die Zentralbank Frankreichs', ['Eine Privatbank Napoleons', 'Eine englische Bank', 'Eine Kirchenbank']],
              ['Welches Gebiet erhielten die USA 1803?', 'Ein riesiges Gebiet westlich des Mississippi', ['Kanada', 'Mexiko', 'Kuba']],
              ['Wer schuf die Lycées als Schulen für den Staatsnachwuchs?', 'Napoleon', ['Ludwig XIV.', 'Jules Ferry', 'Rousseau']],
              ['Welches Gemälde schuf David über die Krönung?', '„Die Krönung Napoleons“', ['„Der Tod des Marat“', '„Die Freiheit führt das Volk“', '„Der Ballhausschwur“']],
              ['Wie viele Jahre galt die Sklavereiabschaffung, bis Napoleon sie aufhob?', 'Acht Jahre', ['Ein Jahr', 'Fünfzig Jahre', 'Hundert Jahre']],
              ['Wer setzte sich bei der Krönung die Krone auf?', 'Napoleon sich selbst', ['Der Papst Napoleon', 'Joséphine Napoleon', 'Der Erzbischof von Paris']],
              ['Welche Insel heißt heute Haiti?', 'Saint-Domingue (Westteil von Hispaniola)', ['Martinique', 'Kuba', 'Jamaika']],
            ],
          },
        },
        {
          id: 'napoleons-kriege',
          title: 'Napoleons Kriege und Großreich',
          date: '1805–1811',
          text: [
            'Gegen Napoleon schlossen sich immer wieder Koalitionen aus Großbritannien, Österreich, Russland und Preußen zusammen. Seinen Plan, in England zu landen, musste er aufgeben: Am 21. Oktober 1805 vernichtete Admiral Nelson die französisch-spanische Flotte bei Trafalgar vor Spanien; Nelson selbst fiel. Seitdem beherrschte Großbritannien die Meere.',
            'An Land war Napoleon fast unschlagbar. Am 2. Dezember 1805, genau ein Jahr nach seiner Krönung, besiegte er bei Austerlitz die Kaiser von Österreich und Russland – die „Dreikaiserschlacht“; die „Sonne von Austerlitz“ wurde sprichwörtlich. 1806 gründete er den Rheinbund, worauf das Heilige Römische Reich endete, und schlug Preußen bei Jena und Auerstedt. Im Frieden von Tilsit 1807 einigte er sich mit dem russischen Zaren Alexander I.',
            'Um Großbritannien wirtschaftlich zu treffen, verbot Napoleon im November 1806 mit dem Berliner Dekret allen Ländern auf dem Kontinent den Handel mit den Briten (Kontinentalsperre). Viele Länder litten darunter, und Schmuggel blühte.',
            'Napoleon setzte seine Familie auf Throne: Sein Bruder Joseph wurde König von Neapel und 1808 von Spanien, Louis König von Holland, Jérôme König von Westphalen, sein Schwager Joachim Murat König von Neapel. In Spanien erhob sich das Volk 1808 gegen die Franzosen; in einem zermürbenden „kleinen Krieg“ (spanisch guerrilla) banden Partisanen mit britischer Hilfe Hunderttausende Soldaten. Der Maler Francisco de Goya hielt die Erschießung spanischer Aufständischer im Bild „Der 3. Mai 1808“ fest.',
            '1809 besiegte Napoleon Österreich erneut bei Wagram. Weil Joséphine ihm keinen Sohn gebar, ließ er sich 1809 scheiden und heiratete 1810 Marie-Louise, die Tochter des österreichischen Kaisers. 1811 wurde ihr Sohn geboren, dem Napoleon den Titel „König von Rom“ gab.',
            'Um 1811 stand Napoleons Reich auf dem Höhepunkt: Frankreich umfasste 130 Departements von Hamburg bis Rom, dazu kamen abhängige Staaten in fast ganz Europa. Nur Großbritannien, Russland, Schweden und das Osmanische Reich waren unabhängig. Überall brachten die Franzosen moderne Gesetze, aber auch Besatzung, Steuern und Zwangsrekrutierungen – das weckte Nationalgefühl und Widerstand.',
          ],
          quiz: {
            leicht: [
              ['Wo vernichtete Nelson 1805 die französische Flotte?', 'Bei Trafalgar', ['Bei Abukir', 'Bei Calais', 'Bei Brest']],
              ['Was geschah mit Nelson bei Trafalgar?', 'Er fiel', ['Er wurde gefangen', 'Er floh', 'Er wurde Kaiser']],
              ['Wer beherrschte nach Trafalgar die Meere?', 'Großbritannien', ['Frankreich', 'Spanien', 'Russland']],
              ['Wo siegte Napoleon 1805 über Österreich und Russland?', 'Bei Austerlitz', ['Bei Waterloo', 'Bei Leipzig', 'Bei Borodino']],
              ['Wie nennt man die Schlacht bei Austerlitz?', 'Dreikaiserschlacht', ['Völkerschlacht', 'Seeschlacht', 'Pyramidenschlacht']],
              ['Was wurde bei Austerlitz sprichwörtlich?', 'Die „Sonne von Austerlitz“', ['Der „Regen von Austerlitz“', 'Der „Schnee von Austerlitz“', 'Der „Mond von Austerlitz“']],
              ['Welchen Bund gründete Napoleon 1806?', 'Den Rheinbund', ['Den Deutschen Bund', 'Die Hanse', 'Die NATO']],
              ['Wie nennt man Napoleons Handelsverbot gegen Großbritannien?', 'Kontinentalsperre', ['Seeblockade', 'Embargo von Paris', 'Zollverein']],
              ['Was blühte durch die Kontinentalsperre?', 'Der Schmuggel', ['Der Handel mit England', 'Die Landwirtschaft', 'Der Frieden']],
              ['Wer wurde 1808 König von Spanien?', 'Napoleons Bruder Joseph', ['Napoleon selbst', 'Murat', 'Ferdinand VII.']],
              ['Wer wurde König von Westphalen?', 'Jérôme', ['Louis', 'Joseph', 'Lucien']],
              ['Welches Volk erhob sich 1808 gegen die Franzosen?', 'Das spanische', ['Das englische', 'Das russische', 'Das italienische']],
              ['Woher stammt das Wort „Guerrilla“?', 'Aus dem Spanischen', ['Aus dem Französischen', 'Aus dem Italienischen', 'Aus dem Russischen']],
              ['Welcher spanische Maler malte „Der 3. Mai 1808“?', 'Goya', ['Velázquez', 'Picasso', 'Dalí']],
              ['Wen heiratete Napoleon 1810?', 'Marie-Louise von Österreich', ['Joséphine', 'Marie Antoinette', 'Désirée']],
              ['Warum ließ sich Napoleon von Joséphine scheiden?', 'Sie gebar ihm keinen Sohn', ['Sie war untreu', 'Sie war Royalistin', 'Sie wollte nach Martinique']],
              ['Welchen Titel gab Napoleon seinem Sohn?', '„König von Rom“', ['„Kaiser von Paris“', '„Prinz von Korsika“', '„Dauphin“']],
              ['Wie viele Departements umfasste Frankreich 1811?', '130', ['83', '50', '300']],
              ['Von wo bis wo reichte Frankreich 1811?', 'Von Hamburg bis Rom', ['Von Paris bis Lyon', 'Von London bis Madrid', 'Von Moskau bis Lissabon']],
              ['Welches Land blieb 1811 unabhängig?', 'Großbritannien', ['Holland', 'Westphalen', 'Neapel']],
            ],
            mittel: [
              ['Wann fand die Schlacht von Trafalgar statt?', '21. Oktober 1805', ['2. Dezember 1805', '18. Juni 1815', '1. August 1798']],
              ['Vor welchem Land liegt Trafalgar?', 'Vor Spanien', ['Vor England', 'Vor Frankreich', 'Vor Ägypten']],
              ['Welchen Plan musste Napoleon nach Trafalgar aufgeben?', 'Die Landung in England', ['Den Russlandfeldzug', 'Die Kaiserkrönung', 'Den Code civil']],
              ['Wann war die Schlacht bei Austerlitz?', '2. Dezember 1805', ['21. Oktober 1805', '14. Oktober 1806', '2. Dezember 1804']],
              ['Was ist besonders am Datum von Austerlitz?', 'Es war der erste Jahrestag der Krönung', ['Es war Weihnachten', 'Es war Napoleons Geburtstag', 'Es war Neujahr']],
              ['Was endete 1806 nach der Gründung des Rheinbunds?', 'Das Heilige Römische Reich', ['Das Britische Empire', 'Das Osmanische Reich', 'Die Republik Venedig']],
              ['Wo schlug Napoleon 1806 Preußen?', 'Bei Jena und Auerstedt', ['Bei Austerlitz', 'Bei Wagram', 'Bei Leipzig']],
              ['Mit welchem Zaren einigte sich Napoleon in Tilsit?', 'Alexander I.', ['Nikolaus I.', 'Peter der Große', 'Katharina die Große']],
              ['Wann wurde der Frieden von Tilsit geschlossen?', '1807', ['1806', '1809', '1812']],
              ['Mit welchem Dekret verhängte Napoleon die Kontinentalsperre?', 'Mit dem Berliner Dekret', ['Mit dem Pariser Dekret', 'Mit dem Code civil', 'Mit dem Konkordat']],
              ['Wann wurde die Kontinentalsperre verhängt?', 'November 1806', ['Oktober 1805', 'Juni 1812', 'März 1804']],
              ['Wer wurde König von Holland?', 'Louis', ['Jérôme', 'Joseph', 'Murat']],
              ['Wer war Joachim Murat?', 'Napoleons Schwager und König von Neapel', ['Napoleons Bruder', 'Ein spanischer König', 'Ein russischer General']],
              ['Wer unterstützte die spanischen Partisanen?', 'Großbritannien', ['Russland', 'Österreich', 'Preußen']],
              ['Wo besiegte Napoleon Österreich 1809?', 'Bei Wagram', ['Bei Austerlitz', 'Bei Leipzig', 'Bei Marengo']],
              ['Wann ließ sich Napoleon scheiden?', '1809', ['1804', '1810', '1812']],
              ['Wessen Tochter war Marie-Louise?', 'Des österreichischen Kaisers', ['Des russischen Zaren', 'Des Königs von Preußen', 'Des Papstes']],
              ['Wann wurde Napoleons Sohn geboren?', '1811', ['1809', '1810', '1815']],
              ['Welche Länder waren 1811 außer Großbritannien unabhängig?', 'Russland, Schweden und das Osmanische Reich', ['Spanien, Portugal und Italien', 'Preußen, Österreich und Bayern', 'Holland, Belgien und Dänemark']],
              ['Was weckte die französische Besatzung in vielen Ländern?', 'Nationalgefühl und Widerstand', ['Liebe zu Napoleon', 'Gleichgültigkeit', 'Wunsch nach französischer Sprache']],
            ],
            schwer: [
              ['Welche Flotten unterlagen bei Trafalgar?', 'Die französische und die spanische', ['Die französische und die russische', 'Die spanische und die portugiesische', 'Nur die französische']],
              ['Welches Bild schuf Goya über die Besatzung?', '„Der 3. Mai 1808“', ['„Die nackte Maja“', '„Der Sonnenschirm“', '„Guernica“']],
              ['Wo war Joseph Bonaparte König, bevor er nach Spanien ging?', 'In Neapel', ['In Holland', 'In Westphalen', 'In Schweden']],
              ['Wie viele französische Soldaten banden die spanischen Partisanen?', 'Hunderttausende', ['Einige Dutzend', 'Wenige Tausend', 'Keine']],
              ['Was brachten die Franzosen in besetzte Länder neben Gesetzen?', 'Besatzung, Steuern und Zwangsrekrutierungen', ['Geschenke und Freiheit', 'Nur Kunst', 'Nichts']],
              ['Welche Folge hatte die Kontinentalsperre für viele Länder?', 'Sie litten wirtschaftlich darunter', ['Sie wurden reich', 'Sie wurden britisch', 'Sie verbündeten sich mit England sofort']],
              ['Welcher Teil Europas blieb von Napoleon abhängig?', 'Fast ganz Europa', ['Nur Italien', 'Nur Belgien', 'Kein Land']],
              ['Gegen welche Kaiser kämpfte Napoleon bei Austerlitz?', 'Franz II. von Österreich und Alexander I. von Russland', ['Wilhelm I. und Nikolaus I.', 'Karl V. und Iwan IV.', 'Joseph II. und Peter III.']],
              ['Wie hießen Bündnisse gegen Napoleon?', 'Koalitionen', ['Allianzen der Achse', 'Ententen', 'Ligen']],
              ['Welche Stadt war nördlichster Punkt des französischen Kaiserreichs 1811?', 'Hamburg', ['Kopenhagen', 'Danzig', 'Amsterdam']],
              ['Was beendete der Frieden von Tilsit?', 'Den Krieg mit Russland und Preußen', ['Den Krieg mit England', 'Den Krieg in Spanien', 'Den Hundertjährigen Krieg']],
              ['Was meinte Napoleon mit „König von Rom“?', 'Er machte seinen Sohn zum Titelkönig der italienischen Hauptstadt', ['Er wollte Papst werden', 'Er verschenkte Rom an Österreich', 'Er war selbst König von Rom']],
              ['Woher stammte die Kontinentalsperre ihren Namen?', 'Vom europäischen Kontinent, der gesperrt wurde', ['Von einem Kontinent in Afrika', 'Von einem Schiff', 'Von einem Minister']],
              ['Wann erhob sich Spanien gegen die Franzosen?', '1808', ['1805', '1812', '1814']],
              ['Was erschwerte die Kontinentalsperre den Briten nicht wirklich?', 'Den Seehandel mit der übrigen Welt', ['Den Handel mit Frankreich', 'Den Handel mit Preußen', 'Den Schmuggel']],
              ['Wer war Napoleons Gegner zur See?', 'Großbritannien', ['Russland', 'Österreich', 'Preußen']],
              ['Wann siegte Napoleon bei Wagram?', '1809', ['1805', '1807', '1812']],
              ['Wie viele Brüder Napoleons wurden laut Text Könige?', 'Drei', ['Einer', 'Fünf', 'Keiner']],
              ['Welches Ereignis folgte direkt auf Austerlitz im Reich?', 'Die Gründung des Rheinbunds 1806', ['Die Völkerschlacht', 'Der Wiener Kongress', 'Die Krönung in Rom']],
              ['Was symbolisierte die „Sonne von Austerlitz“?', 'Napoleons glänzenden Sieg', ['Einen Sonnenaufgang auf Korsika', 'Ein Gemälde Davids', 'Eine Münze']],
            ],
          },
        },
        {
          id: 'untergang-napoleon',
          title: 'Russlandfeldzug, Waterloo und St. Helena',
          date: '1812–1821',
          text: [
            'Weil Russland sich nicht mehr an die Kontinentalsperre hielt, überschritt Napoleon im Juni 1812 mit der „Grande Armée“ von rund 600.000 Mann aus vielen Ländern Europas die Memel. Die Russen wichen zurück und verbrannten alles. Am 7. September 1812 kam es bei Borodino zur blutigsten Schlacht des Feldzugs. Am 14. September zog Napoleon in Moskau ein – doch die Stadt brannte, und der Zar verhandelte nicht.',
            'Im Oktober begann der Rückzug. Kälte, Hunger, Krankheiten und Angriffe der Kosaken vernichteten das Heer. Beim Übergang über die Beresina im November starben Zehntausende. Nur ein Bruchteil der Soldaten kehrte zurück. Napoleon eilte voraus nach Paris, um ein neues Heer aufzustellen.',
            'Nun erhoben sich Preußen, Russland, Österreich und Schweden gemeinsam. Im Oktober 1813 wurde Napoleon in der Völkerschlacht bei Leipzig besiegt. Am 31. März 1814 zogen die Verbündeten in Paris ein. Am 6. April 1814 dankte Napoleon in Fontainebleau ab und wurde auf die Insel Elba vor Italien verbannt. Der Bruder Ludwigs XVI. wurde als Ludwig XVIII. König (Restauration).',
            'Doch am 1. März 1815 landete Napoleon mit wenigen Getreuen bei Golfe-Juan an der Mittelmeerküste. Die Truppen, die ihn aufhalten sollten, liefen zu ihm über, und am 20. März zog er wieder in Paris ein – die „Herrschaft der Hundert Tage“ begann. Am 18. Juni 1815 wurde er bei Waterloo in Belgien von den Briten unter dem Herzog von Wellington und den Preußen unter Feldmarschall Blücher endgültig geschlagen.',
            'Diesmal verbannten ihn die Briten auf die ferne Insel St. Helena im Südatlantik. Dort diktierte er seine Erinnerungen, die als „Mémorial de Sainte-Hélène“ erschienen und die Legende vom großen Kaiser verbreiteten. Napoleon starb am 5. Mai 1821. 1840 wurden seine Gebeine nach Paris überführt und im Invalidendom beigesetzt.',
            'Napoleon bleibt umstritten: Für die einen ist er ein Genie, das Frankreich modernisierte und dessen Gesetze bis heute gelten, für die anderen ein Eroberer, dessen Kriege Millionen Menschen das Leben kosteten.',
          ],
          quiz: {
            leicht: [
              ['Gegen welches Land zog Napoleon 1812?', 'Russland', ['England', 'Spanien', 'Preußen']],
              ['Wie hieß Napoleons riesige Armee?', 'Grande Armée', ['Wehrmacht', 'Rote Armee', 'Fremdenlegion']],
              ['Welche Stadt brannte, als Napoleon einzog?', 'Moskau', ['Paris', 'Berlin', 'Sankt Petersburg']],
              ['Was vernichtete Napoleons Heer auf dem Rückzug?', 'Kälte, Hunger und Krankheiten', ['Hitze', 'Ein Erdbeben', 'Eine Flut']],
              ['Wo wurde Napoleon 1813 besiegt?', 'In der Völkerschlacht bei Leipzig', ['Bei Austerlitz', 'Bei Trafalgar', 'Bei Jena']],
              ['Auf welche Insel wurde Napoleon 1814 verbannt?', 'Elba', ['St. Helena', 'Korsika', 'Sardinien']],
              ['Wer wurde 1814 König von Frankreich?', 'Ludwig XVIII.', ['Ludwig XVI.', 'Karl X.', 'Louis-Philippe']],
              ['Wie nennt man Napoleons Rückkehr 1815?', 'Herrschaft der Hundert Tage', ['Tausendjähriges Reich', 'Sieben Wochen', 'Restauration']],
              ['Wo wurde Napoleon 1815 endgültig geschlagen?', 'Bei Waterloo', ['Bei Leipzig', 'Bei Borodino', 'Bei Austerlitz']],
              ['In welchem heutigen Land liegt Waterloo?', 'In Belgien', ['In Frankreich', 'In England', 'In den Niederlanden']],
              ['Welcher britische Feldherr siegte bei Waterloo?', 'Wellington', ['Nelson', 'Marlborough', 'Montgomery']],
              ['Welcher preußische Feldmarschall kämpfte bei Waterloo?', 'Blücher', ['Moltke', 'Bismarck', 'Hindenburg']],
              ['Wohin wurde Napoleon zuletzt verbannt?', 'Nach St. Helena', ['Nach Elba', 'Nach Korsika', 'Nach Amerika']],
              ['In welchem Ozean liegt St. Helena?', 'Im Südatlantik', ['Im Pazifik', 'Im Indischen Ozean', 'Im Mittelmeer']],
              ['Wann starb Napoleon?', '1821', ['1815', '1840', '1812']],
              ['Wo liegt Napoleon heute begraben?', 'Im Invalidendom in Paris', ['Auf St. Helena', 'In Ajaccio', 'In Notre-Dame']],
              ['Wo dankte Napoleon 1814 ab?', 'In Fontainebleau', ['In Versailles', 'In Paris', 'In Moskau']],
              ['Was diktierte Napoleon auf St. Helena?', 'Seine Erinnerungen', ['Einen neuen Code civil', 'Eine Oper', 'Einen Kriegsplan']],
              ['Wie sehen viele Menschen Napoleon heute?', 'Als umstritten: Genie und Eroberer', ['Nur als Heiligen', 'Nur als Verbrecher', 'Er ist vergessen']],
              ['Welchen Fluss überquerte die Grande Armée 1812 zu Beginn?', 'Die Memel', ['Den Rhein', 'Die Wolga', 'Die Seine']],
            ],
            mittel: [
              ['Warum zog Napoleon gegen Russland?', 'Russland hielt sich nicht mehr an die Kontinentalsperre', ['Russland hatte Paris angegriffen', 'Der Zar beleidigte Joséphine', 'Er wollte Indien erreichen']],
              ['Wie groß war die Grande Armée 1812 etwa?', 'Rund 600.000 Mann', ['Rund 60.000 Mann', 'Rund 6 Millionen Mann', 'Rund 6000 Mann']],
              ['Wann zog Napoleon in Moskau ein?', '14. September 1812', ['7. September 1812', '24. Juni 1812', '1. Dezember 1812']],
              ['Wo fand am 7. September 1812 die blutigste Schlacht statt?', 'Bei Borodino', ['Bei Smolensk', 'An der Beresina', 'Bei Leipzig']],
              ['Was taten die Russen beim Rückzug vor Napoleon?', 'Sie verbrannten alles', ['Sie ergaben sich', 'Sie flohen nach Sibirien', 'Sie verbündeten sich mit ihm']],
              ['Wann begann der französische Rückzug?', 'Im Oktober 1812', ['Im Juni 1812', 'Im Januar 1813', 'Im September 1812']],
              ['An welchem Fluss starben im November 1812 Zehntausende?', 'An der Beresina', ['An der Memel', 'An der Wolga', 'An der Elbe']],
              ['Wer griff die zurückweichenden Franzosen an?', 'Kosaken', ['Wikinger', 'Engländer', 'Spanier']],
              ['Wann fand die Völkerschlacht bei Leipzig statt?', 'Oktober 1813', ['Juni 1815', 'Dezember 1812', 'April 1814']],
              ['Wann zogen die Verbündeten in Paris ein?', '31. März 1814', ['6. April 1814', '18. Juni 1815', '1. März 1815']],
              ['Wann dankte Napoleon zum ersten Mal ab?', '6. April 1814', ['31. März 1814', '18. Juni 1815', '5. Mai 1821']],
              ['Wer war Ludwig XVIII.?', 'Ein Bruder Ludwigs XVI.', ['Ein Sohn Napoleons', 'Ein Sohn Ludwigs XVI.', 'Ein Neffe Robespierres']],
              ['Wie nennt man die Rückkehr der Bourbonen?', 'Restauration', ['Revolution', 'Reformation', 'Renaissance']],
              ['Wo landete Napoleon am 1. März 1815?', 'Bei Golfe-Juan', ['Bei Calais', 'Bei Marseille', 'Bei Brest']],
              ['Was taten die Truppen, die Napoleon 1815 aufhalten sollten?', 'Sie liefen zu ihm über', ['Sie nahmen ihn gefangen', 'Sie flohen', 'Sie schossen auf ihn']],
              ['Wann zog Napoleon 1815 wieder in Paris ein?', '20. März 1815', ['1. März 1815', '18. Juni 1815', '6. April 1815']],
              ['An welchem Tag war die Schlacht bei Waterloo?', '18. Juni 1815', ['20. März 1815', '16. Oktober 1813', '5. Mai 1821']],
              ['Wer verbannte Napoleon nach St. Helena?', 'Die Briten', ['Die Preußen', 'Die Russen', 'Die Franzosen']],
              ['Wann wurden Napoleons Gebeine nach Paris überführt?', '1840', ['1821', '1815', '1870']],
              ['Wie heißen Napoleons Erinnerungen?', '„Mémorial de Sainte-Hélène“', ['„Mein Kampf“', '„Krieg und Frieden“', '„Code civil“']],
            ],
            schwer: [
              ['An welchem Tag starb Napoleon?', '5. Mai 1821', ['18. Juni 1821', '15. August 1821', '2. Dezember 1821']],
              ['Welcher Teil der Grande Armée kehrte zurück?', 'Nur ein Bruchteil', ['Fast alle', 'Die Hälfte', 'Keiner']],
              ['Aus welchen Ländern kamen die Soldaten der Grande Armée?', 'Aus vielen Ländern Europas', ['Nur aus Frankreich', 'Aus Russland', 'Aus Amerika']],
              ['Warum eilte Napoleon 1812 vor seinem Heer nach Paris?', 'Um ein neues Heer aufzustellen', ['Um abzudanken', 'Um zu heiraten', 'Um sich zu verstecken']],
              ['Welche Länder erhoben sich 1813 gemeinsam?', 'Preußen, Russland, Österreich und Schweden', ['Spanien, Portugal und England', 'Italien und die Schweiz', 'Holland und Belgien']],
              ['Wo liegt Elba?', 'Vor Italien', ['Vor Spanien', 'Vor England', 'Im Atlantik']],
              ['Wo liegt Golfe-Juan?', 'An der Mittelmeerküste', ['An der Atlantikküste', 'Am Ärmelkanal', 'Am Rhein']],
              ['Wie verhielt sich der Zar nach dem Brand Moskaus?', 'Er verhandelte nicht', ['Er ergab sich', 'Er floh nach Paris', 'Er wurde Napoleons Freund']],
              ['Was verbreitete das „Mémorial de Sainte-Hélène“?', 'Die Legende vom großen Kaiser', ['Napoleons Schuldeingeständnis', 'Einen Friedensplan', 'Kochrezepte']],
              ['In welchem Gebäude in Paris liegt Napoleon?', 'Im Invalidendom', ['Im Panthéon', 'In Notre-Dame', 'Im Louvre']],
              ['Welcher Teil von Napoleons Werk gilt bis heute?', 'Seine Gesetze', ['Seine Eroberungen', 'Sein Kaiserreich', 'Seine Kontinentalsperre']],
              ['Wie lange regierte Napoleon in den „Hundert Tagen“ etwa?', 'Rund drei Monate', ['Hundert Jahre', 'Ein Jahr', 'Zehn Tage']],
              ['In welchem Monat 1812 überschritt die Grande Armée die Memel?', 'Juni', ['September', 'Dezember', 'März']],
              ['Was war Borodino für den Feldzug?', 'Die blutigste Schlacht', ['Ein Sieg der Russen ohne Kampf', 'Ein Friedensort', 'Ein Hafen']],
              ['Welches Herrscherhaus kehrte 1814 zurück?', 'Die Bourbonen', ['Die Valois', 'Die Bonapartes', 'Die Orléans']],
              ['Welcher Herzog kommandierte die Briten bei Waterloo?', 'Der Herzog von Wellington', ['Der Herzog von Marlborough', 'Der Herzog von York', 'Der Herzog von Kent']],
              ['Wie viele Tage dauerte Napoleons zweite Herrschaft der Legende nach?', 'Hundert', ['Tausend', 'Zehn', 'Dreihundert']],
              ['Was sehen Kritiker in Napoleon?', 'Einen Eroberer, dessen Kriege Millionen das Leben kosteten', ['Einen Friedensstifter', 'Einen Heiligen', 'Einen Demokraten']],
              ['Wann kehrte Napoleon von Elba zurück?', 'März 1815', ['April 1814', 'Juni 1815', 'Januar 1815']],
              ['Wie viele Jahre lebte Napoleon auf St. Helena?', 'Rund sechs Jahre', ['Ein Jahr', 'Zwanzig Jahre', 'Einen Monat']],
            ],
          },
        },
      ],
    },
  ],
};
