import type { Epoch } from '../types';

export const E6: Epoch = {
  id: 'weltkriege',
  name: 'Weltkriege',
  period: '1914–1945',
  events: [
    {
      id: 'erster-weltkrieg-fr',
      title: 'Erster Weltkrieg und Zwischenkriegszeit',
      date: '1914–1939',
      text: [
        'Im Ersten Weltkrieg lag die Westfront auf französischem Boden; Frankreich verlor fast 1,4 Millionen Soldaten. Nach dem Sieg folgten „verrückte Jahre“, Wirtschaftskrise und die Volksfront – und die Angst vor einem neuen Krieg mit Deutschland.',
      ],
      subtopics: [
        {
          id: 'grande-guerre',
          title: 'Die „Grande Guerre“',
          date: '1914–1919',
          text: [
            'Am 31. Juli 1914 wurde der Sozialist Jean Jaurès, der für den Frieden eintrat, in einem Pariser Café ermordet. Am 3. August erklärte Deutschland Frankreich den Krieg. Die Parteien schlossen die „Union sacrée“ (heilige Einheit), und viele Soldaten zogen zuversichtlich los, um Elsass-Lothringen zurückzugewinnen. Die Uniform mit roten Hosen machte sie anfangs zu leichten Zielen.',
            'Die deutschen Armeen stießen durch Belgien bis kurz vor Paris vor. In der Schlacht an der Marne im September 1914 wurden sie unter Marschall Joseph Joffre gestoppt; Pariser Taxis brachten Soldaten an die Front („Taxis der Marne“). Danach erstarrte die Front: Von der Nordsee bis zur Schweiz gruben sich die Soldaten, die „Poilus“ (die Behaarten), in Schützengräben ein.',
            'Von Februar bis Dezember 1916 versuchten die Deutschen, die französische Armee bei Verdun „ausbluten“ zu lassen. General Philippe Pétain organisierte die Verteidigung; über die einzige Nachschubstraße, die „Voie sacrée“ (heiliger Weg), rollten Tag und Nacht Lastwagen. „Ils ne passeront pas!“ – „Sie kommen nicht durch!“ wurde zum Motto. Rund 300.000 Franzosen und Deutsche fielen. Im Beinhaus von Douaumont ruhen die Gebeine von rund 130.000 unbekannten Soldaten.',
            '1917 scheiterte am Chemin des Dames eine französische Offensive unter General Nivelle mit schweren Verlusten. Daraufhin weigerten sich Zehntausende Soldaten, weiter anzugreifen (Meutereien). Pétain beruhigte die Armee durch bessere Versorgung und Urlaub. Staatspräsident war während des Krieges Raymond Poincaré. Im November 1917 wurde der 76-jährige Georges Clemenceau, „der Tiger“, Regierungschef und führte das Land entschlossen zum Sieg. Marschall Ferdinand Foch wurde 1918 Oberbefehlshaber aller alliierten Truppen.',
            'Am 11. November 1918 um 11 Uhr trat der Waffenstillstand in Kraft, unterzeichnet in einem Eisenbahnwagen im Wald von Compiègne (bei Rethondes). Frankreich hatte fast 1,4 Millionen Soldaten verloren; Millionen waren verwundet, viele „Gueules cassées“ (zerschlagene Gesichter) blieben entstellt. Fast jedes Dorf errichtete ein Kriegerdenkmal. Seit 1920 ruht unter dem Arc de Triomphe der „Unbekannte Soldat“ mit einer ewigen Flamme.',
            'Im Vertrag von Versailles, unterzeichnet am 28. Juni 1919 im Spiegelsaal, erhielt Frankreich Elsass-Lothringen zurück. Clemenceau setzte harte Bedingungen und hohe Reparationen durch; das Saargebiet kam für 15 Jahre unter Verwaltung des Völkerbundes, und das Rheinland wurde besetzt. Der 11. November ist bis heute Feiertag in Frankreich.',
          ],
          quiz: {
            leicht: [
              ['Wie nennen die Franzosen den Ersten Weltkrieg?', '„La Grande Guerre“', ['„La Guerre froide“', '„La Révolution“', '„La Belle Époque“']],
              ['Welcher Sozialist wurde am 31. Juli 1914 ermordet?', 'Jean Jaurès', ['Léon Blum', 'Clemenceau', 'Dreyfus']],
              ['Welches Gebiet wollten die Franzosen zurückgewinnen?', 'Elsass-Lothringen', ['Korsika', 'Nizza', 'Belgien']],
              ['Welche Farbe hatten die Hosen der französischen Soldaten 1914?', 'Rot', ['Grün', 'Grau', 'Schwarz']],
              ['Wo wurden die Deutschen im September 1914 gestoppt?', 'An der Marne', ['An der Somme', 'Bei Verdun', 'An der Loire']],
              ['Womit wurden Soldaten an die Marne gebracht?', 'Mit Pariser Taxis', ['Mit Flugzeugen', 'Mit Schiffen', 'Mit Pferdekutschen']],
              ['Wie nannte man die französischen Frontsoldaten?', 'Poilus', ['Tommies', 'Doughboys', 'Landser']],
              ['Um welche Stadt wurde 1916 monatelang gekämpft?', 'Verdun', ['Paris', 'Lyon', 'Reims']],
              ['Welcher General organisierte die Verteidigung von Verdun?', 'Pétain', ['De Gaulle', 'Foch', 'Napoleon']],
              ['Was bedeutet „Ils ne passeront pas“?', '„Sie kommen nicht durch!“', ['„Wir geben auf!“', '„Es lebe Frankreich!“', '„Vorwärts!“']],
              ['Wie hieß die Nachschubstraße nach Verdun?', '„Voie sacrée“', ['„Champs-Élysées“', '„Route Napoléon“', '„Chemin des Dames“']],
              ['Wie nannte man Clemenceau?', '„Der Tiger“', ['„Der Löwe“', '„Der Fuchs“', '„Der Adler“']],
              ['Wann trat der Waffenstillstand in Kraft?', '11. November 1918 um 11 Uhr', ['14. Juli 1918', '8. Mai 1918', '28. Juni 1918']],
              ['Wo wurde der Waffenstillstand unterzeichnet?', 'In einem Eisenbahnwagen bei Compiègne', ['In Versailles', 'In Berlin', 'In Paris']],
              ['Wie viele französische Soldaten fielen etwa?', 'Fast 1,4 Millionen', ['Rund 14.000', 'Rund 140.000', 'Rund 14 Millionen']],
              ['Wer ruht seit 1920 unter dem Arc de Triomphe?', 'Der Unbekannte Soldat', ['Napoleon', 'Clemenceau', 'Foch']],
              ['Was brennt am Grab des Unbekannten Soldaten?', 'Eine ewige Flamme', ['Ein Feuerwerk', 'Eine Kerze nur an Feiertagen', 'Nichts']],
              ['Welches Gebiet erhielt Frankreich 1919 zurück?', 'Elsass-Lothringen', ['Nizza', 'Belgien', 'Kanada']],
              ['Wo wurde der Vertrag von Versailles unterzeichnet?', 'Im Spiegelsaal', ['Im Louvre', 'In Compiègne', 'In Notre-Dame']],
              ['Welcher Tag ist in Frankreich bis heute Feiertag?', 'Der 11. November', ['Der 9. November', 'Der 3. Oktober', 'Der 1. September']],
            ],
            mittel: [
              ['Wann erklärte Deutschland Frankreich den Krieg?', '3. August 1914', ['1. August 1914', '28. Juni 1914', '11. November 1914']],
              ['Wie nannte man die Einheit der Parteien 1914?', 'Union sacrée', ['Front populaire', 'Entente cordiale', 'Burgfrieden auf Französisch: Paix civile']],
              ['Wofür trat Jean Jaurès ein?', 'Für den Frieden', ['Für den Krieg', 'Für die Monarchie', 'Für Deutschland']],
              ['Welcher Marschall führte die Franzosen an der Marne?', 'Joseph Joffre', ['Ferdinand Foch', 'Philippe Pétain', 'Robert Nivelle']],
              ['Was bedeutet „Poilus“?', 'Die Behaarten', ['Die Tapferen', 'Die Blauen', 'Die Bauern']],
              ['Von wann bis wann dauerte die Schlacht um Verdun?', 'Februar bis Dezember 1916', ['August bis September 1914', 'April bis Mai 1917', 'März bis November 1918']],
              ['Wie viele Soldaten fielen bei Verdun etwa?', 'Rund 300.000', ['Rund 30.000', 'Rund 3 Millionen', 'Rund 3000']],
              ['Wo ruhen die Gebeine von 130.000 unbekannten Soldaten?', 'Im Beinhaus von Douaumont', ['Im Panthéon', 'Im Invalidendom', 'In Saint-Denis']],
              ['Wo scheiterte 1917 eine französische Offensive?', 'Am Chemin des Dames', ['An der Marne', 'An der Somme', 'Bei Ypern']],
              ['Welcher General leitete die gescheiterte Offensive 1917?', 'Nivelle', ['Pétain', 'Foch', 'Joffre']],
              ['Was geschah nach der Offensive am Chemin des Dames?', 'Meutereien in der Armee', ['Der Waffenstillstand', 'Die Eroberung Berlins', 'Eine Revolution in Paris']],
              ['Wie beruhigte Pétain die Armee?', 'Durch bessere Versorgung und Urlaub', ['Durch Entlassung aller Offiziere', 'Durch höhere Steuern', 'Durch neue Uniformen']],
              ['Wann wurde Clemenceau Regierungschef?', 'November 1917', ['August 1914', 'November 1918', 'Juni 1919']],
              ['Wie alt war Clemenceau 1917?', '76', ['46', '56', '86']],
              ['Wer wurde 1918 Oberbefehlshaber aller alliierten Truppen?', 'Ferdinand Foch', ['Joseph Joffre', 'Philippe Pétain', 'Douglas Haig']],
              ['Bei welchem Ort lag der Eisenbahnwagen des Waffenstillstands?', 'Rethondes', ['Verdun', 'Sedan', 'Reims']],
              ['Wie nannte man Soldaten mit entstellten Gesichtern?', '„Gueules cassées“', ['„Poilus“', '„Grognards“', '„Chasseurs“']],
              ['Wann wurde der Vertrag von Versailles unterzeichnet?', '28. Juni 1919', ['11. November 1918', '14. Juli 1919', '1. Januar 1920']],
              ['Unter wessen Verwaltung kam das Saargebiet?', 'Unter die des Völkerbundes', ['Unter die Frankreichs direkt', 'Unter die Englands', 'Unter die der USA']],
              ['Wie lange stand das Saargebiet unter Verwaltung des Völkerbundes?', '15 Jahre', ['5 Jahre', '50 Jahre', 'Für immer']],
            ],
            schwer: [
              ['Wo wurde Jean Jaurès ermordet?', 'In einem Pariser Café', ['In der Nationalversammlung', 'Auf einer Demonstration', 'Zu Hause']],
              ['Warum waren die französischen Soldaten 1914 leichte Ziele?', 'Wegen ihrer roten Hosen', ['Wegen fehlender Gewehre', 'Wegen Gasmasken', 'Wegen Pferden']],
              ['Was rollte Tag und Nacht über die Voie sacrée?', 'Lastwagen', ['Panzer', 'Pferdewagen', 'Züge']],
              ['Wann ruht der Unbekannte Soldat unter dem Arc de Triomphe?', 'Seit 1920', ['Seit 1918', 'Seit 1945', 'Seit 1871']],
              ['Was errichtete fast jedes französische Dorf nach dem Krieg?', 'Ein Kriegerdenkmal', ['Eine Kirche', 'Ein Schloss', 'Einen Bahnhof']],
              ['Welches Gebiet am Rhein wurde nach 1919 besetzt?', 'Das Rheinland', ['Bayern', 'Westfalen', 'Sachsen']],
              ['Was setzte Clemenceau in Versailles durch?', 'Harte Bedingungen und hohe Reparationen', ['Einen milden Frieden', 'Die Teilung Frankreichs', 'Ein Bündnis mit Deutschland']],
              ['Wie viele unbekannte Soldaten ruhen in Douaumont?', 'Rund 130.000', ['Rund 1300', 'Rund 13.000', 'Rund 1,3 Millionen']],
              ['Welche Strategie verfolgten die Deutschen bei Verdun?', 'Die französische Armee „ausbluten“ zu lassen', ['Paris direkt zu erobern', 'Die Engländer zu umgehen', 'Frieden zu erzwingen ohne Kampf']],
              ['Wer war Regierungschef in den letzten Kriegsjahren?', 'Georges Clemenceau', ['Raymond Poincaré', 'Aristide Briand', 'Léon Blum']],
              ['Welches Amt hatte Raymond Poincaré im Krieg?', 'Staatspräsident', ['Regierungschef', 'General', 'Außenminister']],
              ['Wie hieß das Gelände der Offensive von 1917?', 'Chemin des Dames', ['Voie sacrée', 'Mort-Homme', 'Champ de Mars']],
              ['Was waren die „Taxis der Marne“?', 'Pariser Taxis, die Soldaten an die Front brachten', ['Krankenwagen', 'Panzer', 'Flugzeuge']],
              ['Wo verlief die Westfront?', 'Von der Nordsee bis zur Schweiz', ['Von Paris bis Marseille', 'Entlang des Rheins', 'Am Ärmelkanal']],
              ['Wie viele Stunden nach Mitternacht trat der Waffenstillstand in Kraft?', 'Um 11 Uhr', ['Um 12 Uhr', 'Um 9 Uhr', 'Um 23 Uhr']],
              ['Durch welches Land stießen die Deutschen 1914 vor?', 'Durch Belgien', ['Durch die Schweiz', 'Durch Italien', 'Durch Spanien']],
              ['Was bedeutet „Union sacrée“?', 'Heilige Einheit', ['Heiliger Krieg', 'Heilige Allianz', 'Heiliger Weg']],
              ['Welche Rolle spielte Pétain 1917?', 'Er wurde Oberbefehlshaber und beendete die Meutereien', ['Er wurde Präsident', 'Er führte die Offensive', 'Er floh nach England']],
              ['In welchem Jahr wurde Foch Oberbefehlshaber?', '1918', ['1914', '1916', '1917']],
              ['Was war Verdun für die Franzosen?', 'Ein Symbol des Durchhaltens', ['Ein schneller Sieg', 'Eine Niederlage ohne Bedeutung', 'Ein Friedensort']],
            ],
          },
        },
        {
          id: 'zwischenkriegszeit',
          title: 'Verrückte Jahre und Volksfront',
          date: '1919–1939',
          text: [
            'In den 1920er Jahren, den „Années folles“ (verrückte Jahre), feierte Paris mit Jazz, Cabarets und neuer Mode. Die Tänzerin Josephine Baker trat im Bananenrock auf, Coco Chanel erfand bequeme Mode für Frauen und das „kleine Schwarze“, und Künstler wie Picasso, Hemingway und die Surrealisten um André Breton trafen sich in Montparnasse. Marcel Proust vollendete „Auf der Suche nach der verlorenen Zeit“ (À la recherche du temps perdu).',
            'Weil Deutschland mit den Reparationen in Rückstand war, besetzten französische und belgische Truppen im Januar 1923 das Ruhrgebiet. Später setzte Außenminister Aristide Briand auf Versöhnung: Mit Gustav Stresemann schloss er 1925 den Vertrag von Locarno, wofür beide 1926 den Friedensnobelpreis erhielten; 1928 unterzeichnete er mit dem US-Außenminister Frank B. Kellogg den Briand-Kellogg-Pakt, der den Krieg ächtete.',
            'Zum Schutz vor Deutschland baute Frankreich ab 1929 entlang der Ostgrenze die Maginot-Linie, eine Kette von Bunkern und Festungen, benannt nach Kriegsminister André Maginot. An der Grenze zu Belgien und in den bewaldeten Ardennen war sie jedoch kaum ausgebaut.',
            'Die Weltwirtschaftskrise erreichte Frankreich in den 1930er Jahren. Am 6. Februar 1934 kam es in Paris zu gewalttätigen Unruhen rechtsextremer Verbände vor dem Parlament. Aus Angst vor dem Faschismus schlossen sich Sozialisten, Kommunisten und Radikale zur „Volksfront“ (Front populaire) zusammen und gewannen 1936 die Wahl. Léon Blum wurde der erste sozialistische und erste jüdische Regierungschef Frankreichs.',
            'Nach großen Streiks setzte die Volksfront 1936 im Abkommen von Matignon – benannt nach dem Amtssitz des Regierungschefs – wichtige Reformen durch: die 40-Stunden-Woche, Lohnerhöhungen und erstmals zwei Wochen bezahlten Urlaub. Im Sommer 1936 fuhren viele Arbeiterfamilien zum ersten Mal ans Meer. Im Spanischen Bürgerkrieg verfolgte Blum jedoch eine Politik der Nichteinmischung. 1938 zerbrach die Volksfront.',
            'Im September 1938 unterzeichnete Ministerpräsident Édouard Daladier zusammen mit dem Briten Chamberlain das Münchner Abkommen, das Hitler das Sudetenland überließ. Bei seiner Rückkehr wurde er bejubelt, obwohl er wusste, dass der Frieden nur aufgeschoben war. Als Deutschland am 1. September 1939 Polen überfiel, erklärten Frankreich und Großbritannien am 3. September Deutschland den Krieg.',
          ],
          quiz: {
            leicht: [
              ['Wie nennt man die 1920er Jahre in Frankreich?', '„Années folles“ (verrückte Jahre)', ['„Belle Époque“', '„Trente Glorieuses“', '„Grande Guerre“']],
              ['Welche Musik war in den 1920ern in Paris beliebt?', 'Jazz', ['Rock ’n’ Roll', 'Techno', 'Barockmusik']],
              ['Welche Tänzerin trat im Bananenrock auf?', 'Josephine Baker', ['Édith Piaf', 'Coco Chanel', 'Marlene Dietrich']],
              ['Welche Modeschöpferin erfand das „kleine Schwarze“?', 'Coco Chanel', ['Christian Dior', 'Yves Saint Laurent', 'Josephine Baker']],
              ['Welche Region besetzten Frankreich und Belgien 1923?', 'Das Ruhrgebiet', ['Das Saarland', 'Bayern', 'Das Elsass']],
              ['Welcher französische Außenminister setzte auf Versöhnung?', 'Aristide Briand', ['Clemenceau', 'Daladier', 'Pétain']],
              ['Welchen Preis erhielt Briand?', 'Den Friedensnobelpreis', ['Den Literaturnobelpreis', 'Den Karlspreis', 'Einen Oscar']],
              ['Welche Befestigungslinie baute Frankreich?', 'Die Maginot-Linie', ['Den Westwall', 'Den Atlantikwall', 'Den Limes']],
              ['Wo war die Maginot-Linie kaum ausgebaut?', 'An der Grenze zu Belgien und in den Ardennen', ['Am Rhein', 'In den Alpen', 'An der Küste']],
              ['Wie hieß das Bündnis der Linken 1936?', 'Volksfront (Front populaire)', ['Union sacrée', 'Résistance', 'Entente cordiale']],
              ['Wer wurde 1936 Regierungschef?', 'Léon Blum', ['Charles de Gaulle', 'Édouard Daladier', 'Philippe Pétain']],
              ['Was erhielten Arbeiter 1936 erstmals?', 'Bezahlten Urlaub', ['Das Wahlrecht', 'Ein Auto', 'Eine Rente']],
              ['Wie viele Wochen bezahlten Urlaub gab es 1936?', 'Zwei', ['Eine', 'Vier', 'Sechs']],
              ['Wie viele Stunden hatte die Arbeitswoche nach 1936?', '40', ['60', '35', '48']],
              ['Wohin fuhren viele Arbeiterfamilien 1936 zum ersten Mal?', 'Ans Meer', ['Nach Amerika', 'In die Berge nach Nepal', 'Nach Berlin']],
              ['Welches Abkommen überließ Hitler 1938 das Sudetenland?', 'Das Münchner Abkommen', ['Der Vertrag von Versailles', 'Der Vertrag von Locarno', 'Das Abkommen von Matignon']],
              ['Welcher französische Regierungschef unterzeichnete in München?', 'Édouard Daladier', ['Léon Blum', 'Charles de Gaulle', 'Paul Reynaud']],
              ['Wann erklärte Frankreich Deutschland den Krieg?', '3. September 1939', ['1. September 1939', '10. Mai 1940', '22. Juni 1940']],
              ['Welches Land überfiel Deutschland am 1. September 1939?', 'Polen', ['Frankreich', 'Belgien', 'Österreich']],
              ['In welchem Pariser Viertel trafen sich viele Künstler?', 'Montparnasse', ['La Défense', 'Belleville', 'Neuilly']],
            ],
            mittel: [
              ['Welche Kunstbewegung gründete André Breton?', 'Den Surrealismus', ['Den Impressionismus', 'Den Kubismus', 'Den Expressionismus']],
              ['Welcher amerikanische Schriftsteller lebte in Paris?', 'Ernest Hemingway', ['Mark Twain', 'Edgar Allan Poe', 'Jack London']],
              ['Welchen großen Roman vollendete Marcel Proust?', '„Auf der Suche nach der verlorenen Zeit“', ['„Der Fremde“', '„Die Pest“', '„Der kleine Prinz“']],
              ['Wann besetzten Franzosen und Belgier das Ruhrgebiet?', 'Januar 1923', ['November 1918', 'September 1939', 'März 1936']],
              ['Warum wurde das Ruhrgebiet besetzt?', 'Deutschland war mit den Reparationen in Rückstand', ['Wegen eines Grenzstreits', 'Wegen Kohlemangels in Frankreich', 'Wegen des Hitlerputsches']],
              ['Mit welchem deutschen Politiker schloss Briand den Vertrag von Locarno?', 'Gustav Stresemann', ['Friedrich Ebert', 'Hitler', 'Heinrich Brüning']],
              ['Wann wurde der Vertrag von Locarno geschlossen?', '1925', ['1919', '1928', '1933']],
              ['Welcher Pakt ächtete 1928 den Krieg?', 'Der Briand-Kellogg-Pakt', ['Der Warschauer Pakt', 'Der Hitler-Stalin-Pakt', 'Der Stabilitätspakt']],
              ['Ab wann wurde die Maginot-Linie gebaut?', '1929', ['1919', '1936', '1939']],
              ['Nach wem ist die Maginot-Linie benannt?', 'Nach Kriegsminister André Maginot', ['Nach einem General', 'Nach einer Stadt', 'Nach einem Fluss']],
              ['Was geschah am 6. Februar 1934?', 'Gewalttätige Unruhen rechtsextremer Verbände', ['Die Volksfront siegte', 'Hitler besuchte Paris', 'Ein Generalstreik']],
              ['Welche Parteien bildeten die Volksfront?', 'Sozialisten, Kommunisten und Radikale', ['Konservative und Monarchisten', 'Nur Kommunisten', 'Gaullisten und Liberale']],
              ['Was war Léon Blum außer erster sozialistischer Regierungschef?', 'Der erste jüdische Regierungschef Frankreichs', ['Der jüngste Regierungschef', 'Ein General', 'Ein Kaiser']],
              ['Wie heißt das Abkommen von 1936 mit den Reformen?', 'Abkommen von Matignon', ['Vertrag von Locarno', 'Abkommen von München', 'Vertrag von Rapallo']],
              ['Was ging dem Abkommen von Matignon voraus?', 'Große Streiks', ['Ein Krieg', 'Eine Revolution', 'Eine Hungersnot']],
              ['Welche Politik verfolgte Blum im Spanischen Bürgerkrieg?', 'Nichteinmischung', ['Offene Unterstützung der Republik mit Truppen', 'Unterstützung Francos', 'Einmarsch in Spanien']],
              ['Wann zerbrach die Volksfront?', '1938', ['1936', '1937', '1940']],
              ['Wann wurde das Münchner Abkommen unterzeichnet?', 'September 1938', ['März 1938', 'September 1939', 'Juni 1940']],
              ['Mit welchem britischen Premier unterzeichnete Daladier?', 'Neville Chamberlain', ['Winston Churchill', 'Clement Attlee', 'Stanley Baldwin']],
              ['Wie wurde Daladier nach München empfangen?', 'Er wurde bejubelt', ['Er wurde ausgebuht', 'Er wurde verhaftet', 'Er trat zurück']],
            ],
            schwer: [
              ['Was wusste Daladier über den Münchner Frieden?', 'Dass er nur aufgeschoben war', ['Dass er ewig halten würde', 'Dass Hitler abdanken würde', 'Nichts']],
              ['Wer unterzeichnete den Briand-Kellogg-Pakt auf amerikanischer Seite?', 'Frank B. Kellogg', ['Woodrow Wilson', 'Franklin D. Roosevelt', 'Herbert Hoover']],
              ['Wann wurde der Briand-Kellogg-Pakt unterzeichnet?', '1928', ['1925', '1919', '1936']],
              ['Was war die Maginot-Linie?', 'Eine Kette von Bunkern und Festungen', ['Eine Eisenbahnlinie', 'Ein Kanal', 'Eine Telefonleitung']],
              ['Was erfand Coco Chanel neben dem kleinen Schwarzen?', 'Bequeme Mode für Frauen', ['Den Minirock', 'Die Jeans', 'Den Bikini']],
              ['Wer war André Breton?', 'Begründer des Surrealismus', ['Ein Maler des Impressionismus', 'Ein Minister', 'Ein General']],
              ['Wann siegte die Volksfront bei der Wahl?', '1936', ['1934', '1938', '1932']],
              ['Was erhielten die Arbeiter durch Matignon außerdem?', 'Lohnerhöhungen', ['Ein Auto', 'Eigene Fabriken', 'Das Frauenwahlrecht']],
              ['Gegen was wollte die Volksfront kämpfen?', 'Gegen den Faschismus', ['Gegen die Monarchie', 'Gegen England', 'Gegen die Kirche']],
              ['Welches Gebiet gab München an Hitler?', 'Das Sudetenland', ['Danzig', 'Österreich', 'Elsass']],
              ['Wann erreichte die Weltwirtschaftskrise Frankreich?', 'In den 1930er Jahren', ['In den 1920er Jahren', '1945', '1914']],
              ['Welches Ereignis schwächte die Maginot-Linie militärisch?', 'Sie endete an der belgischen Grenze', ['Sie war aus Holz', 'Sie lag in Spanien', 'Sie wurde nie gebaut']],
              ['Welcher Teil der Bevölkerung profitierte besonders von 1936?', 'Die Arbeiter', ['Der Adel', 'Die Großindustrie', 'Die Kirche']],
              ['In welchem Jahr wurden Briand und Stresemann mit dem Friedensnobelpreis ausgezeichnet?', '1926', ['1925', '1928', '1929']],
              ['Welche Schlüsselrolle hatte Briand in den 1920er Jahren?', 'Außenminister der Versöhnung', ['Kriegsminister', 'Präsident', 'Gewerkschaftsführer']],
              ['Wofür steht der Name Matignon heute?', 'Für den Amtssitz des Premierministers', ['Für den Präsidentenpalast', 'Für eine Kaserne', 'Für ein Museum']],
              ['Was folgte auf den deutschen Überfall auf Polen für Frankreich?', 'Die Kriegserklärung an Deutschland', ['Ein Bündnis mit Deutschland', 'Neutralität', 'Die Besetzung Belgiens']],
              ['Welche Stimmung prägte die Années folles?', 'Lebensfreude nach dem Krieg', ['Trauer und Stille', 'Revolution', 'Hunger']],
              ['Welche zwei Länder besetzten 1923 das Ruhrgebiet?', 'Frankreich und Belgien', ['Frankreich und England', 'Belgien und Holland', 'Frankreich und Polen']],
              ['Wie heißt Prousts Romanwerk im Original?', '„À la recherche du temps perdu“', ['„Les Fleurs du mal“', '„L’Étranger“', '„Germinal“']],
            ],
          },
        },
      ],
    },
    {
      id: 'zweiter-weltkrieg-fr',
      title: 'Niederlage, Vichy und Befreiung',
      date: '1939–1945',
      text: [
        '1940 brach Frankreich in wenigen Wochen zusammen. Das Land wurde besetzt, das Vichy-Regime unter Pétain arbeitete mit den Deutschen zusammen. Gleichzeitig rief General de Gaulle aus London zum Widerstand auf. 1944 wurde Frankreich befreit.',
      ],
      subtopics: [
        {
          id: 'niederlage-vichy',
          title: 'Niederlage und Vichy-Regime',
          date: '1939–1944',
          text: [
            'Nach der Kriegserklärung im September 1939 geschah an der Westfront monatelang fast nichts – die Franzosen nannten diese Zeit „drôle de guerre“ (seltsamer Krieg). Am 10. Mai 1940 griffen die Deutschen an. Ihre Panzer stießen überraschend durch die Ardennen vor, umgingen die Maginot-Linie und erreichten die Kanalküste. Bei Dünkirchen wurden über 300.000 britische und französische Soldaten über das Meer nach England gerettet.',
            'Am 14. Juni 1940 marschierten deutsche Truppen in das kampflos geräumte Paris ein. Die Regierung floh nach Bordeaux. Der 84-jährige Marschall Pétain, der Held von Verdun, wurde Regierungschef und bat um Waffenstillstand. Am 22. Juni 1940 musste Frankreich ihn im selben Eisenbahnwagen in Compiègne unterzeichnen, in dem 1918 die Deutschen kapituliert hatten – Hitler hatte das so gewollt.',
            'Frankreich wurde geteilt: Der Norden und die Atlantikküste waren von Deutschland besetzt, der Süden blieb zunächst „frei“. Das Elsass und Lothringen wurden faktisch annektiert. Am 10. Juli 1940 übertrug das Parlament in Vichy Pétain alle Macht; die Dritte Republik endete. Der „État français“ ersetzte „Freiheit, Gleichheit, Brüderlichkeit“ durch „Arbeit, Familie, Vaterland“ (Travail, Famille, Patrie).',
            'Nach einem Treffen mit Hitler in Montoire im Oktober 1940 rief Pétain zur „Kollaboration“ (Zusammenarbeit) mit Deutschland auf. Sein Regierungschef Pierre Laval trieb sie voran. Vichy erließ schon im Oktober 1940 aus eigenem Antrieb ein „Judenstatut“, das Juden aus vielen Berufen ausschloss. Hunderttausende Franzosen mussten als Zwangsarbeiter nach Deutschland (STO).',
            'Am 16. und 17. Juli 1942 nahm die französische Polizei in Paris rund 13.000 Juden fest, darunter etwa 4000 Kinder, und sperrte viele von ihnen im Radstadion Vélodrome d’Hiver ein (Rafle du Vel d’Hiv). Von dort wurden sie über Drancy nach Auschwitz deportiert. Insgesamt wurden etwa 75.000 Juden aus Frankreich deportiert; nur wenige überlebten. Erst 1995 erkannte Präsident Jacques Chirac offiziell die Mitschuld des französischen Staates an.',
            'Im November 1942, nach der Landung der Alliierten in Nordafrika, besetzten die Deutschen auch den Süden Frankreichs. Die französische Flotte in Toulon versenkte sich selbst, um nicht in deutsche Hände zu fallen.',
          ],
          quiz: {
            leicht: [
              ['Wie nannten die Franzosen die ruhigen Monate 1939/40?', '„Drôle de guerre“ (seltsamer Krieg)', ['„Blitzkrieg“', '„Grande Guerre“', '„Guerre froide“']],
              ['Wann griffen die Deutschen im Westen an?', '10. Mai 1940', ['1. September 1939', '14. Juni 1940', '6. Juni 1944']],
              ['Durch welches Gebiet stießen die deutschen Panzer vor?', 'Durch die Ardennen', ['Durch die Alpen', 'Durch die Pyrenäen', 'Durch die Bretagne']],
              ['Welche Befestigung umgingen die Deutschen?', 'Die Maginot-Linie', ['Den Atlantikwall', 'Den Limes', 'Die Chinesische Mauer']],
              ['Wo wurden britische und französische Soldaten übers Meer gerettet?', 'Bei Dünkirchen', ['Bei Marseille', 'Bei Brest', 'Bei Nizza']],
              ['Wann marschierten die Deutschen in Paris ein?', '14. Juni 1940', ['10. Mai 1940', '22. Juni 1940', '25. August 1944']],
              ['Welcher Marschall bat um Waffenstillstand?', 'Pétain', ['Foch', 'De Gaulle', 'Joffre']],
              ['Wo wurde der Waffenstillstand 1940 unterzeichnet?', 'Im Eisenbahnwagen von Compiègne', ['In Versailles', 'In Berlin', 'In Vichy']],
              ['In welcher Stadt saß Pétains Regierung?', 'In Vichy', ['In Paris', 'In Lyon', 'In Algier']],
              ['Welcher Wahlspruch ersetzte „Freiheit, Gleichheit, Brüderlichkeit“?', '„Arbeit, Familie, Vaterland“', ['„Gott mit uns“', '„Ein Volk, ein Reich“', '„Ordnung und Fortschritt“']],
              ['Wie nennt man die Zusammenarbeit mit den Deutschen?', 'Kollaboration', ['Résistance', 'Union sacrée', 'Appeasement']],
              ['Welcher Teil Frankreichs war ab 1940 zuerst besetzt?', 'Der Norden und die Atlantikküste', ['Nur Korsika', 'Der Süden', 'Gar keiner']],
              ['Wer nahm 1942 in Paris Juden fest?', 'Die französische Polizei', ['Nur die SS', 'Die britische Armee', 'Die Résistance']],
              ['In welchem Stadion wurden viele Juden eingesperrt?', 'Im Vélodrome d’Hiver', ['Im Stade de France', 'Im Parc des Princes', 'Im Olympiastadion']],
              ['Wohin wurden die Juden deportiert?', 'Nach Auschwitz', ['Nach Amerika', 'Nach Algerien', 'Nach England']],
              ['Wie viele Juden wurden aus Frankreich etwa deportiert?', 'Etwa 75.000', ['Etwa 750', 'Etwa 7500', 'Etwa 750.000']],
              ['Welcher Präsident erkannte 1995 die Mitschuld des Staates an?', 'Jacques Chirac', ['François Mitterrand', 'Charles de Gaulle', 'Emmanuel Macron']],
              ['Was tat die französische Flotte in Toulon 1942?', 'Sie versenkte sich selbst', ['Sie floh nach England', 'Sie ergab sich den Deutschen', 'Sie griff Italien an']],
              ['Wann besetzten die Deutschen auch den Süden?', 'November 1942', ['Juni 1940', 'Juni 1944', 'September 1939']],
              ['Was endete am 10. Juli 1940?', 'Die Dritte Republik', ['Der Krieg', 'Die Besatzung', 'Das Kaiserreich']],
            ],
            mittel: [
              ['Wie viele Soldaten wurden bei Dünkirchen gerettet?', 'Über 300.000', ['Rund 3000', 'Rund 30.000', 'Über 3 Millionen']],
              ['Wohin floh die französische Regierung 1940 zuerst?', 'Nach Bordeaux', ['Nach Vichy', 'Nach London', 'Nach Algier']],
              ['Wie alt war Pétain 1940?', '84', ['64', '74', '94']],
              ['Wann wurde der Waffenstillstand 1940 unterzeichnet?', '22. Juni 1940', ['14. Juni 1940', '10. Juli 1940', '18. Juni 1940']],
              ['Warum wählte Hitler den Eisenbahnwagen von Compiègne?', 'Dort hatte Deutschland 1918 kapituliert', ['Er war besonders bequem', 'Er lag in Paris', 'Zufall']],
              ['Wie hieß der Vichy-Staat offiziell?', '„État français“', ['„République française“', '„Empire français“', '„Royaume de France“']],
              ['Was geschah mit dem Elsass und Lothringen 1940?', 'Sie wurden faktisch annektiert', ['Sie wurden unabhängig', 'Sie blieben frei', 'Sie wurden italienisch']],
              ['Wann übertrug das Parlament Pétain alle Macht?', '10. Juli 1940', ['22. Juni 1940', '14. Juli 1940', '18. Juni 1940']],
              ['Wo traf Pétain im Oktober 1940 Hitler?', 'In Montoire', ['In Vichy', 'In Berlin', 'In Compiègne']],
              ['Welcher Regierungschef trieb die Kollaboration voran?', 'Pierre Laval', ['Léon Blum', 'Jean Moulin', 'Paul Reynaud']],
              ['Was erließ Vichy im Oktober 1940 aus eigenem Antrieb?', 'Ein „Judenstatut“', ['Eine Verfassung', 'Ein Friedensabkommen', 'Ein Wahlrecht für Frauen']],
              ['Was bedeutet „STO“?', 'Zwangsarbeitsdienst in Deutschland', ['Widerstandsgruppe', 'Polizeieinheit', 'Zeitung']],
              ['Wann fand die Razzia des Vel d’Hiv statt?', '16./17. Juli 1942', ['14. Juli 1942', '10. Mai 1940', '6. Juni 1944']],
              ['Wie viele Juden wurden bei der Razzia etwa festgenommen?', 'Rund 13.000', ['Rund 1300', 'Rund 130.000', 'Rund 130']],
              ['Wie viele Kinder waren unter den Festgenommenen etwa?', 'Etwa 4000', ['Etwa 40', 'Etwa 400', 'Etwa 40.000']],
              ['Über welches Lager wurden die Juden deportiert?', 'Über Drancy', ['Über Dachau', 'Über Vichy', 'Über Lyon']],
              ['Was löste die Besetzung Südfrankreichs aus?', 'Die Landung der Alliierten in Nordafrika', ['Der D-Day', 'Der Fall von Paris', 'Die Schlacht von Stalingrad']],
              ['Wann erkannte Frankreich die Mitschuld an der Deportation offiziell an?', '1995', ['1945', '1968', '2010']],
              ['Was war die Kanalküste für die Deutschen 1940?', 'Ziel ihres Vorstoßes', ['Ein Fluchtort', 'Unwichtig', 'Neutrales Gebiet']],
              ['Wie hieß der Teil Frankreichs, der zunächst nicht besetzt war?', 'Die „freie“ Zone im Süden', ['Die Atlantikzone', 'Die Nordzone', 'Die Elsasszone']],
            ],
            schwer: [
              ['Was bedeutet „Rafle du Vel d’Hiv“?', 'Die Razzia im Winter-Radstadion', ['Der Sieg im Radrennen', 'Die Flucht über den Kanal', 'Die Befreiung von Paris']],
              ['Wie viele der deportierten Juden überlebten?', 'Nur wenige', ['Fast alle', 'Die Hälfte', 'Keiner kam je ins Lager']],
              ['Was war Pétain im Ersten Weltkrieg?', 'Der Held von Verdun', ['Ein Meuterer', 'Ein Diplomat', 'Ein Gegner Frankreichs']],
              ['Welche Stadt wurde kampflos geräumt?', 'Paris', ['Dünkirchen', 'Lille', 'Straßburg']],
              ['Wohin zogen sich die Engländer 1940 zurück?', 'Nach England', ['Nach Spanien', 'In die Schweiz', 'Nach Algerien']],
              ['Was versenkte sich 1942 in Toulon?', 'Die französische Flotte', ['Die britische Flotte', 'Die italienische Flotte', 'Ein U-Boot']],
              ['Welches Gesetz schloss Juden 1940 aus Berufen aus?', 'Das Judenstatut', ['Die Nürnberger Gesetze', 'Das Ermächtigungsgesetz', 'Das Trennungsgesetz']],
              ['Was war Vichy vorher?', 'Ein Kurort', ['Eine Hafenstadt', 'Die Hauptstadt', 'Ein Militärlager']],
              ['Wohin mussten Hunderttausende Franzosen als Zwangsarbeiter?', 'Nach Deutschland', ['Nach Russland', 'Nach Italien', 'Nach Spanien']],
              ['Welche Rolle spielte die französische Polizei bei der Judenverfolgung?', 'Sie führte Festnahmen selbst durch', ['Sie verhinderte alle Deportationen', 'Sie war nicht beteiligt', 'Sie half nur Kindern zur Flucht']],
              ['Wie lange dauerte der Westfeldzug bis zum Waffenstillstand etwa?', 'Rund sechs Wochen', ['Sechs Monate', 'Sechs Jahre', 'Sechs Tage']],
              ['Wann fand das Treffen von Montoire statt?', 'Oktober 1940', ['Juni 1940', 'Juli 1942', 'November 1942']],
              ['Welcher Wahlspruch steht für Vichy auf Französisch?', '„Travail, Famille, Patrie“', ['„Liberté, Égalité, Fraternité“', '„Honneur et Patrie“', '„Dieu et mon droit“']],
              ['Wer hatte nach dem Gesetz vom 10. Juli 1940 alle Macht?', 'Pétain', ['Laval', 'De Gaulle', 'Hitler direkt']],
              ['Welche Stadt war Sitz der Exilregierung des Freien Frankreichs?', 'London', ['Vichy', 'Bordeaux', 'Washington']],
              ['Welche Armeen wurden in Dünkirchen evakuiert?', 'Britische und französische', ['Nur polnische', 'Nur belgische', 'Deutsche']],
              ['Welcher Ort war Zwischenlager vor Auschwitz?', 'Drancy', ['Lourdes', 'Natzweiler', 'Vichy']],
              ['Was tat Vichy 1940 beim Judenstatut ohne deutschen Befehl?', 'Es handelte aus eigenem Antrieb', ['Es weigerte sich', 'Es wartete auf Befehle', 'Es schützte die Juden']],
              ['Wann endete die „freie“ Zone?', 'November 1942', ['Juni 1940', 'August 1944', 'Mai 1945']],
              ['Was war das Ziel der Selbstversenkung der Flotte?', 'Nicht in deutsche Hände zu fallen', ['Die Engländer anzugreifen', 'Die Italiener zu ärgern', 'Ein Unfall']],
            ],
          },
        },
        {
          id: 'resistance-befreiung',
          title: 'De Gaulle, Résistance und Befreiung',
          date: '1940–1945',
          text: [
            'Am 18. Juni 1940 sprach der bis dahin wenig bekannte General Charles de Gaulle aus London über das Radio der BBC zu den Franzosen. In seinem „Appell vom 18. Juni“ rief er dazu auf, den Kampf fortzusetzen: Frankreich habe eine Schlacht verloren, aber nicht den Krieg. Er gründete das „Freie Frankreich“ (France libre); sein Zeichen war das Lothringerkreuz. Vichy verurteilte ihn in Abwesenheit zum Tod.',
            'In Frankreich entstand die Résistance (Widerstand): Menschen druckten heimlich Zeitungen, versteckten Juden und abgeschossene Piloten, sammelten Informationen für die Alliierten und verübten Sabotage. Junge Männer, die der Zwangsarbeit entgehen wollten, flohen in Wälder und Berge und bildeten den „Maquis“ – benannt nach dem dichten Buschland Korsikas und Südfrankreichs. Auch Frauen wie Lucie Aubrac kämpften mit.',
            'Im Auftrag de Gaulles vereinigte der frühere Präfekt Jean Moulin die verschiedenen Widerstandsgruppen 1943 im Nationalen Widerstandsrat (CNR). Im Juni 1943 wurde er bei Lyon verhaftet und von Gestapo-Chef Klaus Barbie gefoltert; er starb an den Folgen, ohne Namen preiszugeben. Seit 1964 ruht er im Panthéon.',
            'Am 6. Juni 1944 („D-Day“) landeten amerikanische, britische, kanadische und französische Truppen in der Normandie. Die SS verübte daraufhin grausame Vergeltung: Am 10. Juni 1944 ermordete sie im Dorf Oradour-sur-Glane 642 Männer, Frauen und Kinder; das zerstörte Dorf ist bis heute als Mahnmal erhalten. Am 15. August 1944 landeten weitere Truppen in der Provence.',
            'Ab dem 19. August erhob sich Paris gegen die Besatzer. Am 25. August 1944 zog die französische 2. Panzerdivision unter General Leclerc in die Stadt ein; der deutsche Kommandant Dietrich von Choltitz kapitulierte, ohne Paris wie befohlen zu zerstören. De Gaulle rief vor dem Rathaus: „Paris empört! Paris gebrochen! Paris gemartert! Aber Paris befreit!“ Am nächsten Tag zog er unter Jubel die Champs-Élysées hinunter.',
            'De Gaulle leitete die provisorische Regierung. Im April 1944 erhielten die Französinnen das Wahlrecht; 1945 wählten sie zum ersten Mal. Mit Kollaborateuren wurde abgerechnet (épuration): Viele wurden verurteilt, manche ohne Prozess getötet, Frauen, die Beziehungen zu Deutschen hatten, wurden öffentlich kahl geschoren. Pétain wurde 1945 zum Tod verurteilt, de Gaulle wandelte das Urteil in lebenslange Haft um; Laval wurde hingerichtet. Am 8. Mai 1945 war Frankreich bei der Kapitulation Deutschlands unter den Siegermächten.',
          ],
          quiz: {
            leicht: [
              ['Welcher General rief am 18. Juni 1940 zum Widerstand auf?', 'Charles de Gaulle', ['Pétain', 'Leclerc', 'Foch']],
              ['Von welcher Stadt aus sprach de Gaulle?', 'London', ['Paris', 'Algier', 'Washington']],
              ['Über welchen Sender sprach de Gaulle?', 'Die BBC', ['Radio Paris', 'Radio Vichy', 'CNN']],
              ['Was hatte Frankreich laut de Gaulle verloren?', 'Eine Schlacht, aber nicht den Krieg', ['Den ganzen Krieg', 'Nichts', 'Seine Ehre']],
              ['Wie hieß de Gaulles Bewegung?', 'Freies Frankreich', ['Vichy-Frankreich', 'Volksfront', 'Union sacrée']],
              ['Welches Zeichen hatte das Freie Frankreich?', 'Das Lothringerkreuz', ['Den Adler', 'Die Lilie', 'Das Hakenkreuz']],
              ['Wie heißt der französische Widerstand?', 'Résistance', ['Kollaboration', 'Milice', 'Fronde']],
              ['Wie nannte man die Widerstandskämpfer in Wäldern und Bergen?', 'Maquis', ['Poilus', 'Chouans', 'Sansculottes']],
              ['Wer vereinigte die Widerstandsgruppen?', 'Jean Moulin', ['Pétain', 'Laval', 'Blum']],
              ['Wo ruht Jean Moulin heute?', 'Im Panthéon', ['Im Invalidendom', 'In Saint-Denis', 'In London']],
              ['Wann landeten die Alliierten in der Normandie?', '6. Juni 1944', ['25. August 1944', '8. Mai 1945', '15. August 1944']],
              ['Wie nennt man den 6. Juni 1944?', 'D-Day', ['V-Day', 'Tag X', 'Stunde null']],
              ['In welchem Dorf verübte die SS ein Massaker?', 'Oradour-sur-Glane', ['Vichy', 'Compiègne', 'Domrémy']],
              ['Wann wurde Paris befreit?', '25. August 1944', ['6. Juni 1944', '8. Mai 1945', '14. Juli 1944']],
              ['Welche Panzerdivision zog in Paris ein?', 'Die französische 2. Panzerdivision', ['Eine britische Division', 'Eine russische Division', 'Die Fremdenlegion']],
              ['Welcher General führte die 2. Panzerdivision?', 'Leclerc', ['De Gaulle', 'Patton', 'Montgomery']],
              ['Über welche Prachtstraße zog de Gaulle nach der Befreiung?', 'Die Champs-Élysées', ['Die Rue de Rivoli', 'Den Boulevard Saint-Michel', 'Die Avenue Foch']],
              ['Wann durften Französinnen zum ersten Mal wählen?', '1945', ['1918', '1789', '1968']],
              ['Wie nennt man die Abrechnung mit Kollaborateuren?', 'Épuration', ['Résistance', 'Restauration', 'Collaboration']],
              ['Zu welcher Strafe wurde Pétain 1945 verurteilt?', 'Zum Tod, umgewandelt in lebenslange Haft', ['Zu einer Geldstrafe', 'Er wurde freigesprochen', 'Zu Exil in Amerika']],
            ],
            mittel: [
              ['Wie nennt man de Gaulles Rede vom 18. Juni?', 'Appell vom 18. Juni', ['Rede von Bayeux', 'Erklärung von Vichy', 'Aufruf von Algier']],
              ['Wie war de Gaulle vor dem 18. Juni 1940?', 'Wenig bekannt', ['Präsident', 'Sehr berühmt', 'Marschall']],
              ['Was tat Vichy mit de Gaulle?', 'Es verurteilte ihn in Abwesenheit zum Tod', ['Es machte ihn zum Minister', 'Es lud ihn ein', 'Nichts']],
              ['Was taten Résistance-Kämpfer unter anderem?', 'Sie druckten heimlich Zeitungen und verübten Sabotage', ['Sie bauten Bunker für die Deutschen', 'Sie gründeten Parteien in Vichy', 'Sie führten Wahlen durch']],
              ['Warum flohen junge Männer in den Maquis?', 'Um der Zwangsarbeit zu entgehen', ['Um zu jagen', 'Um Urlaub zu machen', 'Um nach Spanien zu ziehen']],
              ['Welche Frau kämpfte in der Résistance?', 'Lucie Aubrac', ['Coco Chanel', 'Édith Piaf', 'Mistinguett']],
              ['Welches Gremium vereinte die Widerstandsgruppen 1943?', 'Der Nationale Widerstandsrat (CNR)', ['Die Volksfront', 'Der Wohlfahrtsausschuss', 'Die Nationalversammlung']],
              ['Welches Amt hatte Jean Moulin früher?', 'Präfekt', ['General', 'Bischof', 'Minister']],
              ['Wo wurde Jean Moulin verhaftet?', 'Bei Lyon', ['In Paris', 'In Marseille', 'In London']],
              ['Wer folterte Jean Moulin?', 'Klaus Barbie', ['Pierre Laval', 'Dietrich von Choltitz', 'Pétain']],
              ['Wann wurde Moulin ins Panthéon überführt?', '1964', ['1945', '1944', '1995']],
              ['Welche Truppen landeten am D-Day?', 'Amerikanische, britische, kanadische und französische', ['Nur amerikanische', 'Nur sowjetische', 'Nur französische']],
              ['Wann verübte die SS das Massaker von Oradour?', '10. Juni 1944', ['6. Juni 1944', '25. August 1944', '1. September 1939']],
              ['Wie viele Menschen wurden in Oradour ermordet?', '642', ['64', '6420', '6']],
              ['Wann landeten weitere alliierte Truppen in der Provence?', '15. August 1944', ['6. Juni 1944', '25. August 1944', '8. Mai 1945']],
              ['Ab wann erhob sich Paris?', '19. August 1944', ['6. Juni 1944', '25. August 1944', '14. Juli 1944']],
              ['Welcher deutsche Kommandant kapitulierte in Paris?', 'Dietrich von Choltitz', ['Erwin Rommel', 'Klaus Barbie', 'Gerd von Rundstedt']],
              ['Was tat Choltitz entgegen dem Befehl nicht?', 'Paris zerstören', ['Kapitulieren', 'Fliehen', 'Verhandeln']],
              ['Wann erhielten die Französinnen das Wahlrecht?', 'April 1944', ['November 1918', 'Mai 1968', 'Juli 1936']],
              ['Welcher Vichy-Politiker wurde hingerichtet?', 'Pierre Laval', ['Pétain', 'Darlan', 'Blum']],
            ],
            schwer: [
              ['Wie lautet der Kern von de Gaulles Ruf bei der Befreiung von Paris?', '„… Aber Paris befreit!“', ['„Vive la France libre!“', '„Paris ist eine Messe wert!“', '„Ils ne passeront pas!“']],
              ['Wo rief de Gaulle „Paris befreit“?', 'Vor dem Rathaus', ['Unter dem Arc de Triomphe', 'In Notre-Dame', 'Am Eiffelturm']],
              ['Wie gab Jean Moulin unter Folter nach?', 'Gar nicht, er verriet keine Namen', ['Er verriet alle', 'Er floh', 'Er wurde Kollaborateur']],
              ['Was ist Oradour-sur-Glane heute?', 'Ein erhaltenes zerstörtes Dorf als Mahnmal', ['Eine neue Stadt', 'Ein Museum in Paris', 'Abgerissen']],
              ['Was geschah mit Frauen, die Beziehungen zu Deutschen hatten?', 'Sie wurden öffentlich kahl geschoren', ['Sie wurden geehrt', 'Nichts', 'Sie wurden Ministerinnen']],
              ['Wer wandelte Pétains Todesurteil um?', 'De Gaulle', ['Laval', 'Leclerc', 'Churchill']],
              ['War Frankreich 1945 bei den Siegermächten?', 'Ja', ['Nein', 'Nur als Beobachter', 'Es war neutral']],
              ['Welche Gestapo-Funktion hatte Klaus Barbie?', 'Gestapo-Chef in Lyon', ['General in Paris', 'Botschafter in Vichy', 'Kommandant in Dachau']],
              ['Wofür stand das Lothringerkreuz?', 'Für das Freie Frankreich', ['Für Vichy', 'Für die Kirche', 'Für die Monarchie']],
              ['Welche Rolle spielte de Gaulle nach der Befreiung?', 'Er leitete die provisorische Regierung', ['Er wurde König', 'Er zog sich zurück', 'Er wurde verhaftet']],
              ['Was versteckte die Résistance unter anderem?', 'Juden und abgeschossene Piloten', ['Gold der Bank', 'Deutsche Generäle', 'Kunstwerke für Hitler']],
              ['Welche Abkürzung hat der Nationale Widerstandsrat?', 'CNR', ['STO', 'FFI', 'SNCF']],
              ['Wann wurde Jean Moulin verhaftet?', 'Juni 1943', ['Juni 1940', 'Juni 1944', 'Mai 1945']],
              ['Welche Truppen marschierten als erste in Paris ein?', 'Französische', ['Amerikanische', 'Britische', 'Kanadische']],
              ['Warum war der 18. Juni ein wichtiger Gedenktag?', 'Wegen de Gaulles Appell zum Widerstand', ['Wegen des Waffenstillstands', 'Wegen der Befreiung', 'Wegen Waterloo']],
              ['Was folgte am 26. August 1944?', 'De Gaulles Zug über die Champs-Élysées', ['Die Landung in der Normandie', 'Die Kapitulation Deutschlands', 'Der Waffenstillstand']],
              ['Wann wählten Frauen in Frankreich erstmals?', '1945', ['1944', '1946', '1919']],
              ['Wie gingen manche bei der Épuration vor?', 'Manche töteten Kollaborateure ohne Prozess', ['Alle wurden fair verurteilt', 'Niemand wurde bestraft', 'Alle wurden begnadigt']],
              ['Was ist ein „Maquis“ ursprünglich?', 'Ein dichtes Buschland in Korsika und im Süden', ['Eine Stadt', 'Ein Fluss', 'Ein Gefängnis']],
              ['Wie viele Tage nach dem D-Day geschah das Massaker von Oradour?', 'Vier', ['Eins', 'Zehn', 'Dreißig']],
            ],
          },
        },
      ],
    },
  ],
};
