import { Subject, topic } from './types';

const S = 'geografie';

export const geografie: Subject = {
  id: S,
  name: ['Geography', 'Geografie'],
  icon: '🗺️',
  blurb: ['Capitals, rivers, mountains and records', 'Hauptstädte, Flüsse, Gebirge und Rekorde'],
  color: { bg: 'bg-emerald-50', text: 'text-emerald-800', bar: 'bg-emerald-500', border: 'border-emerald-200' },
  topics: [
    topic(S, 'europa', ['Capitals of Europe', 'Hauptstädte Europas'], '🇪🇺', [
      ['Was ist die Hauptstadt von Spanien?', 'Madrid'],
      ['Was ist die Hauptstadt von Portugal?', 'Lissabon'],
      ['Was ist die Hauptstadt von Polen?', 'Warschau'],
      ['Was ist die Hauptstadt von Schweden?', 'Stockholm'],
      ['Was ist die Hauptstadt von Norwegen?', 'Oslo'],
      ['Was ist die Hauptstadt von Finnland?', 'Helsinki'],
      ['Was ist die Hauptstadt von Ungarn?', 'Budapest'],
      ['Was ist die Hauptstadt von Rumänien?', 'Bukarest'],
      ['Was ist die Hauptstadt von Bulgarien?', 'Sofia'],
      ['Was ist die Hauptstadt von Tschechien?', 'Prag'],
      ['Was ist die Hauptstadt von Kroatien?', 'Zagreb'],
      ['Was ist die Hauptstadt von Irland?', 'Dublin'],
      ['Was ist die Hauptstadt der Schweiz?', 'Bern', null, 'Offiziell „Bundesstadt“ – die Schweiz hat keine Hauptstadt im Gesetz.'],
      ['Was ist die Hauptstadt der Slowakei?', 'Bratislava'],
      ['Was ist die Hauptstadt von Slowenien?', 'Ljubljana'],
      ['Was ist die Hauptstadt von Litauen?', 'Vilnius'],
      ['Was ist die Hauptstadt von Lettland?', 'Riga'],
      ['Was ist die Hauptstadt von Estland?', 'Tallinn'],
    ]),
    topic(S, 'welt', ['Capitals of the world', 'Hauptstädte der Welt'], '🌐', [
      ['Was ist die Hauptstadt von Kanada?', 'Ottawa'],
      ['Was ist die Hauptstadt von Australien?', 'Canberra'],
      ['Was ist die Hauptstadt von Brasilien?', 'Brasília'],
      ['Was ist die Hauptstadt der Türkei?', 'Ankara'],
      ['Was ist die Hauptstadt von Japan?', 'Tokio'],
      ['Was ist die Hauptstadt von China?', 'Peking'],
      ['Was ist die Hauptstadt von Indien?', 'Neu-Delhi'],
      ['Was ist die Hauptstadt von Ägypten?', 'Kairo'],
      ['Was ist die Hauptstadt von Argentinien?', 'Buenos Aires'],
      ['Was ist die Hauptstadt von Nigeria?', 'Abuja'],
      ['Was ist die Hauptstadt von Kenia?', 'Nairobi'],
      ['Was ist die Hauptstadt von Thailand?', 'Bangkok'],
      ['Was ist die Hauptstadt von Neuseeland?', 'Wellington'],
      ['Was ist die Hauptstadt von Marokko?', 'Rabat'],
      ['Was ist die Hauptstadt von Peru?', 'Lima'],
      ['Was ist die Hauptstadt von Vietnam?', 'Hanoi'],
      ['Was ist die Hauptstadt von Südkorea?', 'Seoul'],
      ['Was ist die Hauptstadt des Iran?', 'Teheran'],
    ]),
    topic(S, 'deutschland', ['German states', 'Bundesländer'], '🇩🇪', [
      ['Was ist die Landeshauptstadt von Bayern?', 'München'],
      ['Was ist die Landeshauptstadt von Baden-Württemberg?', 'Stuttgart'],
      ['Was ist die Landeshauptstadt von Hessen?', 'Wiesbaden', null, 'Nicht Frankfurt – die größte Stadt Hessens.'],
      ['Was ist die Landeshauptstadt von Niedersachsen?', 'Hannover'],
      ['Was ist die Landeshauptstadt von Nordrhein-Westfalen?', 'Düsseldorf', null, 'Nicht Köln – die größte Stadt des Landes.'],
      ['Was ist die Landeshauptstadt von Rheinland-Pfalz?', 'Mainz'],
      ['Was ist die Landeshauptstadt des Saarlandes?', 'Saarbrücken'],
      ['Was ist die Landeshauptstadt von Sachsen?', 'Dresden'],
      ['Was ist die Landeshauptstadt von Sachsen-Anhalt?', 'Magdeburg'],
      ['Was ist die Landeshauptstadt von Thüringen?', 'Erfurt'],
      ['Was ist die Landeshauptstadt von Brandenburg?', 'Potsdam'],
      ['Was ist die Landeshauptstadt von Mecklenburg-Vorpommern?', 'Schwerin', null, 'Nicht Rostock – die größte Stadt des Landes.'],
      ['Was ist die Landeshauptstadt von Schleswig-Holstein?', 'Kiel'],
    ]),
    topic(S, 'natur', ['Rivers, mountains & records', 'Flüsse, Berge & Rekorde'], '⛰️', [
      ['Welcher Fluss hat die längste Strecke in Deutschland?', 'Rhein', ['Elbe', 'Donau', 'Main'], 'Rund 865 km des Rheins liegen in Deutschland.'],
      ['Wie heißt der höchste Berg Deutschlands?', 'Zugspitze', ['Watzmann', 'Feldberg', 'Brocken'], '2.962 m, an der Grenze zu Österreich.'],
      ['Wie heißt der höchste Berg der Alpen?', 'Mont Blanc', ['Matterhorn', 'Großglockner', 'Eiger']],
      ['Wie heißt der höchste Berg der Erde?', 'Mount Everest', ['K2', 'Kilimandscharo', 'Aconcagua'], 'Etwa 8.849 m im Himalaya.'],
      ['Welcher ist der größte Ozean?', 'Pazifik', ['Atlantik', 'Indischer Ozean', 'Arktischer Ozean']],
      ['Welche ist die größte Wüste außerhalb der Polargebiete?', 'Sahara', ['Gobi', 'Kalahari', 'Atacama']],
      ['Welches Land hat die größte Fläche?', 'Russland', ['Kanada', 'China', 'USA']],
      ['Welches ist der größte See, der ganz in Deutschland liegt?', 'Müritz', ['Chiemsee', 'Bodensee', 'Starnberger See'], 'Der Bodensee ist größer, liegt aber auch in Österreich und der Schweiz.'],
      ['Welcher ist der längste Fluss Europas?', 'Wolga', ['Donau', 'Rhein', 'Dnepr']],
      ['Durch wie viele Hauptstädte fließt die Donau?', 'Vier', ['Zwei', 'Drei', 'Fünf'], 'Wien, Bratislava, Budapest und Belgrad.'],
      ['Welches Gebirge gilt als Grenze zwischen Europa und Asien?', 'Ural', ['Karpaten', 'Pyrenäen', 'Apennin']],
      ['Welcher Fluss fließt durch Paris?', 'Seine', ['Loire', 'Rhône', 'Garonne']],
      ['Welcher Kontinent hat die meisten Länder?', 'Afrika', ['Asien', 'Europa', 'Südamerika'], '54 Staaten.'],
      ['Welches Land hat die meisten Einwohner?', 'Indien', ['China', 'USA', 'Indonesien'], 'Indien hat China um 2023 überholt.'],
    ]),
  ],
};
