// Events for the timeline game (/zeitstrahl): [year, event]; negative = BC.
export type TimelineEvent = [year: number, text: string];

export const EVENTS: TimelineEvent[] = [
  [-776, 'Erste überlieferte Olympische Spiele'],
  [-753, 'Gründung Roms (der Sage nach)'],
  [-490, 'Schlacht bei Marathon'],
  [-336, 'Alexander der Große wird König von Makedonien'],
  [-44, 'Ermordung Julius Caesars'],
  [79, 'Der Vesuv begräbt Pompeji'],
  [476, 'Ende des Weströmischen Reichs'],
  [622, 'Mohammeds Auswanderung nach Medina (Hidschra)'],
  [800, 'Kaiserkrönung Karls des Großen'],
  [1066, 'Schlacht bei Hastings'],
  [1096, 'Beginn des Ersten Kreuzzugs'],
  [1215, 'Magna Carta'],
  [1347, 'Die Pest erreicht Europa'],
  [1453, 'Die Osmanen erobern Konstantinopel'],
  [1492, 'Kolumbus erreicht Amerika'],
  [1517, 'Luthers 95 Thesen'],
  [1519, 'Magellan bricht zur ersten Weltumsegelung auf'],
  [1618, 'Beginn des Dreißigjährigen Kriegs'],
  [1648, 'Westfälischer Friede'],
  [1687, 'Newtons „Principia“ erscheint'],
  [1776, 'Unabhängigkeitserklärung der USA'],
  [1789, 'Sturm auf die Bastille'],
  [1804, 'Napoleon krönt sich zum Kaiser'],
  [1815, 'Schlacht bei Waterloo'],
  [1848, 'Märzrevolution in Deutschland'],
  [1859, 'Darwins „Über die Entstehung der Arten“'],
  [1869, 'Eröffnung des Suezkanals'],
  [1871, 'Gründung des Deutschen Kaiserreichs'],
  [1886, 'Carl Benz meldet das Automobil zum Patent an'],
  [1903, 'Erster Motorflug der Brüder Wright'],
  [1912, 'Untergang der Titanic'],
  [1914, 'Beginn des Ersten Weltkriegs'],
  [1917, 'Oktoberrevolution in Russland'],
  [1929, 'Börsencrash in New York'],
  [1933, 'Hitler wird Reichskanzler'],
  [1939, 'Beginn des Zweiten Weltkriegs'],
  [1945, 'Ende des Zweiten Weltkriegs'],
  [1949, 'Gründung der Bundesrepublik und der DDR'],
  [1957, 'Start des Satelliten Sputnik 1'],
  [1961, 'Bau der Berliner Mauer'],
  [1963, 'Ermordung John F. Kennedys'],
  [1969, 'Erste Mondlandung'],
  [1989, 'Fall der Berliner Mauer'],
  [1990, 'Deutsche Wiedervereinigung'],
  [1991, 'Auflösung der Sowjetunion'],
  [1993, 'Der Vertrag von Maastricht tritt in Kraft'],
  [2001, 'Anschläge vom 11. September'],
  [2002, 'Einführung des Euro-Bargelds'],
  [2007, 'Vorstellung des ersten iPhones'],
  [2020, 'Die WHO erklärt Corona zur Pandemie'],
];

export function formatYear(y: number): string {
  return y < 0 ? `${-y} v. Chr.` : String(y);
}
