import type { HistEvent } from '../types';

export const UNABHAENGIGKEIT: HistEvent = {
  id: 'unabhaengigkeit',
  title: 'Königshof in Rio und Unabhängigkeit',
  date: '1808–1889',
  text: [
    'Auf der Flucht vor Napoleon kam 1808 der portugiesische Königshof nach Rio de Janeiro. 1822 erklärte Kronprinz Pedro die Unabhängigkeit, und Brasilien wurde ein Kaiserreich – als einziges großes Land Lateinamerikas mit einem Monarchen. Unter Pedro II. erlebte es eine lange Zeit der Stabilität.',
  ],
  subtopics: [
    {
      id: 'koenigshof-rio',
      title: 'Der Königshof in Rio und der Ruf von Ipiranga',
      date: '1808–1831',
      text: [
        'Als Napoleons Truppen 1807 Portugal angriffen, floh der Prinzregent Johann mit rund 10.000 bis 15.000 Menschen unter britischem Schutz nach Brasilien. Im März 1808 erreichte der Hof Rio de Janeiro, das damit zur Hauptstadt eines europäischen Reiches wurde – einmalig in der Geschichte. Johann öffnete die Häfen für den Handel mit befreundeten Nationen, gründete die erste Bank, eine Druckerei, die Nationalbibliothek und den Botanischen Garten.',
        '1815 wurde Brasilien zum gleichberechtigten Königreich erhoben. Nach dem Tod seiner Mutter Maria I., für die er als Prinzregent regiert hatte, wurde Johann 1816 König Johann VI. 1821 musste er auf Druck einer Revolution in Portugal nach Lissabon zurückkehren; sein Sohn Pedro blieb als Regent in Brasilien. Das portugiesische Parlament wollte Brasilien wieder zur Kolonie machen und Pedro zurückholen.',
        'Am 9. Januar 1822 erklärte Pedro, er werde bleiben („Dia do Fico“, „Tag des Ich bleibe“). Am 7. September 1822 erhielt er am Bach Ipiranga bei São Paulo Briefe aus Lissabon, zog sein Schwert und rief „Unabhängigkeit oder Tod!“ – der „Schrei von Ipiranga“. Der 7. September ist heute Brasiliens Nationalfeiertag. Ein wichtiger Berater Pedros war José Bonifácio de Andrada, der „Patriarch der Unabhängigkeit“.',
        'Am 1. Dezember 1822 wurde Pedro als Pedro I. zum Kaiser von Brasilien gekrönt. Anders als die spanischen Kolonien, die in viele Republiken zerfielen, blieb Brasilien als großes Reich zusammen. Portugal erkannte die Unabhängigkeit 1825 an, gegen eine Entschädigung, für die Brasilien Geld in England lieh.',
        'Pedro I. regierte zunehmend autoritär, verlor 1828 einen Krieg um die Provinz Cisplatina, aus der Uruguay wurde, und war unbeliebt. 1831 dankte er zugunsten seines fünfjährigen Sohnes Pedro ab und kehrte nach Portugal zurück, wo er für seine Tochter Maria II. kämpfte.',
      ],
      quiz: {
        leicht: [
          ['Vor wem floh der portugiesische Hof 1807?', 'Vor Napoleon', ['Vor den Spaniern', 'Vor den Engländern', 'Vor den Türken']],
          ['Wohin floh der portugiesische Hof?', 'Nach Rio de Janeiro', ['Nach Salvador', 'Nach London', 'Nach Madrid']],
          ['Wann erreichte der Hof Rio?', '1808', ['1500', '1822', '1889']],
          ['Was war an Rio de Janeiro ab 1808 einmalig?', 'Es war Hauptstadt eines europäischen Reiches', ['Es war die älteste Stadt der Welt', 'Es lag am Nordpol', 'Es hatte keinen Hafen']],
          ['Wer schützte die Flucht des Hofes?', 'Die Briten', ['Die Franzosen', 'Die Spanier', 'Die Niederländer']],
          ['Was gründete Johann in Rio unter anderem?', 'Den Botanischen Garten', ['Den Zuckerhut', 'Die Copacabana', 'Das Maracanã']],
          ['Was öffnete Johann für den Handel?', 'Die Häfen', ['Die Goldminen', 'Die Quilombos', 'Die Grenzen nach Spanien']],
          ['Wann wurde Brasilien gleichberechtigtes Königreich?', '1815', ['1808', '1822', '1889']],
          ['Welchen Namen hatte Johann als König?', 'Johann VI.', ['Johann III.', 'Pedro I.', 'Manuel I.']],
          ['Wer blieb 1821 als Regent in Brasilien?', 'Pedro', ['Johann VI.', 'Maria I.', 'José Bonifácio']],
          ['Wie heißt der Tag, an dem Pedro erklärte, er bleibe?', 'Dia do Fico', ['Dia da Independência', 'Grito', 'Dia de Muertos']],
          ['An welchem Bach rief Pedro die Unabhängigkeit aus?', 'Am Ipiranga', ['Am Amazonas', 'Am Tejo', 'Am Paraná']],
          ['Was rief Pedro am Ipiranga?', '„Unabhängigkeit oder Tod!“', ['„Freiheit oder Tod!“', '„Es lebe der König!“', '„Land und Freiheit!“']],
          ['Welcher Tag ist Brasiliens Nationalfeiertag?', 'Der 7. September', ['Der 22. April', 'Der 15. November', 'Der 13. Mai']],
          ['Bei welcher Stadt liegt der Bach Ipiranga?', 'Bei São Paulo', ['Bei Rio', 'Bei Salvador', 'Bei Recife']],
          ['Wie hieß Pedro als Kaiser?', 'Pedro I.', ['Pedro II.', 'Johann I.', 'Manuel II.']],
          ['Welche Staatsform hatte Brasilien nach 1822?', 'Kaiserreich', ['Republik', 'Kolonie', 'Diktatur']],
          ['Zerfiel Brasilien wie die spanischen Kolonien in viele Staaten?', 'Nein, es blieb zusammen', ['Ja, in zehn', 'Ja, in zwei', 'Ja, in hundert']],
          ['Welches Land entstand aus der Provinz Cisplatina?', 'Uruguay', ['Paraguay', 'Argentinien', 'Bolivien']],
          ['Zugunsten wessen dankte Pedro I. 1831 ab?', 'Seines Sohnes Pedro', ['Seiner Frau', 'Seines Vaters', 'Eines Generals']],
        ],
        mittel: [
          ['Mit wie vielen Menschen floh der Hof etwa?', '10.000 bis 15.000', ['100', '1.000', '100.000']],
          ['In welchem Monat 1808 erreichte der Hof Rio?', 'Im März', ['Im Januar', 'Im September', 'Im Dezember']],
          ['Was gründete Johann außer dem Botanischen Garten?', 'Die erste Bank, eine Druckerei und die Nationalbibliothek', ['Eine Universität in Lissabon', 'Eine Kolonie in Afrika', 'Ein Fußballstadion']],
          ['Wann wurde Johann König?', '1816', ['1808', '1821', '1792']],
          ['Warum musste Johann 1821 zurückkehren?', 'Wegen einer Revolution in Portugal', ['Wegen eines Erdbebens', 'Wegen einer Krankheit', 'Weil Napoleon zurückkam']],
          ['Was wollte das portugiesische Parlament mit Brasilien?', 'Es wieder zur Kolonie machen', ['Es freigeben', 'Es an England verkaufen', 'Es zum Kaiserreich machen']],
          ['Wann war der Dia do Fico?', 'Am 9. Januar 1822', ['Am 7. September 1822', 'Am 1. Dezember 1822', 'Am 15. November 1889']],
          ['Was erhielt Pedro am Ipiranga?', 'Briefe aus Lissabon', ['Eine Krone', 'Gold', 'Eine Armee']],
          ['Wer war der „Patriarch der Unabhängigkeit“?', 'José Bonifácio de Andrada', ['Tiradentes', 'Pedro II.', 'Johann VI.']],
          ['Wann wurde Pedro I. gekrönt?', 'Am 1. Dezember 1822', ['Am 7. September 1822', 'Am 9. Januar 1822', 'Am 13. Mai 1888']],
          ['Wann erkannte Portugal die Unabhängigkeit an?', '1825', ['1822', '1831', '1889']],
          ['Was verlangte Portugal für die Anerkennung?', 'Eine Entschädigung', ['Nichts', 'Die Rückgabe Rios', 'Die Hälfte des Goldes jedes Jahr']],
          ['Wo lieh sich Brasilien das Geld für die Entschädigung?', 'In England', ['In Frankreich', 'In Spanien', 'In den USA']],
          ['Wie regierte Pedro I. zunehmend?', 'Autoritär', ['Demokratisch', 'Gar nicht', 'Als Präsident']],
          ['Wann verlor Brasilien den Krieg um Cisplatina?', '1828', ['1822', '1831', '1865']],
          ['Wie alt war Pedros Sohn bei der Abdankung?', 'Fünf Jahre', ['Fünfzehn Jahre', 'Ein Jahr', 'Dreißig Jahre']],
          ['Wohin kehrte Pedro I. 1831 zurück?', 'Nach Portugal', ['Nach Frankreich', 'Nach Spanien', 'Nach Österreich']],
          ['Für wen kämpfte Pedro I. in Portugal?', 'Für seine Tochter Maria II.', ['Für Napoleon', 'Für seinen Bruder Miguel', 'Für die Republik']],
          ['Was war Pedro I. beim Volk am Ende?', 'Unbeliebt', ['Sehr beliebt', 'Heiliggesprochen', 'Präsident']],
          ['Welche Kolonien zerfielen in viele Republiken?', 'Die spanischen Kolonien', ['Die portugiesischen', 'Die englischen in Kanada', 'Die französischen in Afrika']],
        ],
        schwer: [
          ['Was bedeutet „Dia do Fico“?', 'Tag des Ich bleibe', ['Tag der Freiheit', 'Tag der Krone', 'Tag des Abschieds']],
          ['Wie heißt der Ruf von Ipiranga auf Portugiesisch sinngemäß?', '„Independência ou Morte!“', ['„Ordem e Progresso!“', '„Liberdade!“', '„Viva o Rei!“']],
          ['Wer regierte Portugal formal, als Johann Prinzregent war?', 'Seine Mutter Maria I.', ['Sein Sohn Pedro', 'Napoleon', 'Der Papst']],
          ['Welche Institution für Bücher gründete Johann in Rio?', 'Die Nationalbibliothek', ['Die Universität Coimbra', 'Das Goethe-Institut', 'Die Schwedische Akademie']],
          ['Welcher Krieg kostete Brasilien eine Provinz im Süden?', 'Der Krieg um Cisplatina', ['Der Paraguaykrieg', 'Der Krieg mit Napoleon', 'Der Krieg mit den Niederlanden']],
          ['Welche Rolle spielte José Bonifácio?', 'Er war Pedros wichtiger Berater', ['Er war Pedros Gegner', 'Er war König Portugals', 'Er war ein Bandeirante']],
          ['Wann dankte Pedro I. ab?', '1831', ['1825', '1840', '1822']],
          ['In welchem Jahr wurde Brasilien unabhängig?', '1822', ['1808', '1815', '1825']],
          ['Was war der Grund, dass Brasilien nicht zerfiel?', 'Es blieb unter einem Monarchen vereint', ['Es war eine Insel', 'Es hatte keine Provinzen', 'Spanien verbot es']],
          ['Welche Hauptstadt hatte das Reich Portugal-Brasilien 1808–1821?', 'Rio de Janeiro', ['Lissabon', 'Salvador', 'London']],
          ['Welche Handelsentscheidung traf Johann 1808?', 'Die Öffnung der Häfen für befreundete Nationen', ['Das Verbot jedes Handels', 'Den Handel nur mit Frankreich', 'Die Schließung aller Häfen']],
          ['Welcher König kehrte 1821 nach Lissabon zurück?', 'Johann VI.', ['Pedro I.', 'Manuel II.', 'Sebastian']],
          ['Wo liegt der Ort des Unabhängigkeitsrufs heute?', 'In São Paulo', ['In Rio', 'In Lissabon', 'In Brasília']],
          ['Welches Land finanzierte Brasiliens Entschädigung an Portugal?', 'England', ['Frankreich', 'Spanien', 'Die USA']],
          ['Wofür war Rio als Königssitz besonders?', 'Einmalig als Hauptstadt eines europäischen Reiches in Amerika', ['Es hatte die größte Kathedrale', 'Es war vom Meer weit entfernt', 'Es war eine spanische Stadt']],
          ['Wann wurde Brasilien zum Königreich erhoben?', '1815', ['1808', '1816', '1822']],
          ['Welches Ereignis fand am 1. Dezember 1822 statt?', 'Die Krönung Pedros I.', ['Die Ankunft des Hofes', 'Der Schrei von Ipiranga', 'Die Abdankung']],
          ['Welches Ziel hatte das Parlament in Lissabon 1821/22?', 'Pedro zurückzuholen', ['Pedro zum Kaiser zu machen', 'Brasilien zu verkaufen', 'Portugal nach Brasilien zu verlegen']],
          ['Wofür steht der 7. September in Brasilien?', 'Für die Unabhängigkeit', ['Für die Republik', 'Für das Ende der Sklaverei', 'Für die Entdeckung']],
          ['Welche Tochter unterstützte Pedro I. in Portugal?', 'Maria II.', ['Isabel', 'Leopoldina', 'Januária']],
        ],
      },
    },
    {
      id: 'pedro-zwei',
      title: 'Kaiser Pedro II. und der Paraguaykrieg',
      date: '1831–1870',
      text: [
        'Weil Pedro II. 1831 erst fünf Jahre alt war, regierten von 1831 bis 1840 Regenten. In dieser Zeit erschütterten Aufstände das Land, etwa die „Cabanagem“ im Amazonasgebiet und der „Farrapos-Krieg“ („Krieg der Lumpen“) im Süden (1835–1845). 1840 wurde Pedro II. mit nur 14 Jahren für volljährig erklärt und regierte dann fast 50 Jahre lang.',
        'Pedro II. war gebildet und an Wissenschaft interessiert: Er sprach mehrere Sprachen, förderte Forschung und Kunst, war mit Gelehrten wie Charles Darwin und Victor Hugo in Briefkontakt und besuchte 1876 die Weltausstellung in Philadelphia, wo er Alexander Graham Bells Telefon ausprobierte. Er galt als bescheiden und gerecht, und Brasilien war unter ihm vergleichsweise stabil.',
        'Ab der Mitte des 19. Jahrhunderts wurde Kaffee zum wichtigsten Exportgut, angebaut vor allem im Tal des Paraíba und in São Paulo. Brasilien wurde der größte Kaffeeproduzent der Welt. Auf den Kaffeeplantagen arbeiteten weiterhin versklavte Afrikaner.',
        'Von 1864 bis 1870 kämpfte Brasilien zusammen mit Argentinien und Uruguay im Paraguaykrieg, dem „Krieg der Tripel-Allianz“, gegen Paraguay unter dem Diktator Francisco Solano López. Es war der blutigste Krieg der Geschichte Südamerikas: Paraguay verlor einen großen Teil seiner Bevölkerung, vor allem der Männer. Auch Zehntausende Brasilianer starben, darunter viele Soldaten afrikanischer Herkunft.',
        'Der Krieg stärkte die Armee, deren Offiziere danach mehr politischen Einfluss wollten. Gleichzeitig wuchs die Bewegung gegen die Sklaverei, und erste Republikaner gründeten 1870 eine Republikanische Partei.',
      ],
      quiz: {
        leicht: [
          ['Wie lange regierte Pedro II. etwa?', 'Fast 50 Jahre', ['Fünf Jahre', 'Zehn Jahre', 'Hundert Jahre']],
          ['Mit wie vielen Jahren wurde Pedro II. für volljährig erklärt?', 'Mit 14', ['Mit 21', 'Mit 7', 'Mit 30']],
          ['Wer regierte, als Pedro II. noch ein Kind war?', 'Regenten', ['Sein Vater', 'Der Papst', 'Ein Präsident']],
          ['Welcher Aufstand fand im Amazonasgebiet statt?', 'Die Cabanagem', ['Der Farrapos-Krieg', 'Die Inconfidência', 'Canudos']],
          ['Wo fand der Farrapos-Krieg statt?', 'Im Süden', ['Im Amazonas', 'In Bahia', 'In Rio']],
          ['Wofür interessierte sich Pedro II. besonders?', 'Für Wissenschaft', ['Für Kriege', 'Für Pferderennen', 'Für Mode']],
          ['Mit welchem Naturforscher stand Pedro II. in Kontakt?', 'Charles Darwin', ['Isaac Newton', 'Galileo Galilei', 'Albert Einstein']],
          ['Welche Erfindung probierte Pedro II. 1876 aus?', 'Das Telefon', ['Das Auto', 'Das Flugzeug', 'Das Radio']],
          ['Wo probierte er das Telefon aus?', 'Auf der Weltausstellung in Philadelphia', ['In Rio', 'In Paris', 'In London']],
          ['Wie galt Pedro II.?', 'Als bescheiden und gerecht', ['Als grausam', 'Als faul', 'Als ungebildet']],
          ['Welches Produkt wurde zum wichtigsten Exportgut?', 'Kaffee', ['Zucker', 'Gold', 'Gummi']],
          ['Was wurde Brasilien beim Kaffee?', 'Der größte Produzent der Welt', ['Der kleinste Produzent', 'Ein Importeur', 'Gar nichts']],
          ['Wer arbeitete auf den Kaffeeplantagen?', 'Versklavte Afrikaner', ['Nur Portugiesen', 'Maschinen', 'Indigene Könige']],
          ['Gegen welches Land kämpfte Brasilien 1864–1870?', 'Gegen Paraguay', ['Gegen Argentinien', 'Gegen Uruguay', 'Gegen Portugal']],
          ['Mit welchen Ländern verbündete sich Brasilien gegen Paraguay?', 'Mit Argentinien und Uruguay', ['Mit Chile und Peru', 'Mit Portugal und Spanien', 'Mit den USA']],
          ['Wie heißt der Paraguaykrieg auch?', 'Krieg der Tripel-Allianz', ['Krieg der Pasteten', 'Salpeterkrieg', 'Chacokrieg']],
          ['Wer regierte Paraguay im Krieg?', 'Francisco Solano López', ['Simón Bolívar', 'Juan Perón', 'Pedro II.']],
          ['Welcher war der blutigste Krieg Südamerikas?', 'Der Paraguaykrieg', ['Der Farrapos-Krieg', 'Der Falklandkrieg', 'Der Chacokrieg']],
          ['Was verlor Paraguay im Krieg?', 'Einen großen Teil seiner Bevölkerung', ['Nur eine Stadt', 'Nichts', 'Nur seine Hauptstadt']],
          ['Welche Partei wurde 1870 gegründet?', 'Eine Republikanische Partei', ['Eine Kommunistische Partei', 'Eine Grüne Partei', 'Eine Kaiserpartei']],
        ],
        mittel: [
          ['Wann regierten Regenten für Pedro II.?', '1831 bis 1840', ['1822 bis 1831', '1840 bis 1889', '1808 bis 1821']],
          ['Wann dauerte der Farrapos-Krieg?', '1835–1845', ['1864–1870', '1822–1825', '1889–1893']],
          ['Wann wurde Pedro II. für volljährig erklärt?', '1840', ['1831', '1850', '1864']],
          ['Mit welchem Schriftsteller stand Pedro II. in Briefkontakt?', 'Victor Hugo', ['Goethe', 'Shakespeare', 'Cervantes']],
          ['Wann besuchte Pedro II. die Weltausstellung in Philadelphia?', '1876', ['1867', '1889', '1851']],
          ['Wessen Telefon probierte Pedro II. aus?', 'Alexander Graham Bells', ['Thomas Edisons', 'Nikola Teslas', 'Guglielmo Marconis']],
          ['Wie war Brasilien unter Pedro II.?', 'Vergleichsweise stabil', ['Im ständigen Bürgerkrieg', 'Eine Kolonie', 'Ohne Regierung']],
          ['Wo wurde Kaffee vor allem angebaut?', 'Im Paraíba-Tal und in São Paulo', ['Im Amazonas', 'In Pernambuco', 'In Rio Grande do Sul']],
          ['Ab wann wurde Kaffee das wichtigste Exportgut?', 'Ab der Mitte des 19. Jahrhunderts', ['Ab 1500', 'Ab 1700', 'Ab 1950']],
          ['Wann dauerte der Paraguaykrieg?', '1864–1870', ['1835–1845', '1914–1918', '1822–1828']],
          ['Welche Bevölkerungsgruppe Paraguays starb besonders?', 'Die Männer', ['Die Priester', 'Die Ausländer', 'Niemand']],
          ['Wie viele Brasilianer starben im Paraguaykrieg?', 'Zehntausende', ['Keiner', 'Hundert', 'Millionen']],
          ['Welche Soldaten starben in großer Zahl auf brasilianischer Seite?', 'Viele Soldaten afrikanischer Herkunft', ['Nur Offiziere', 'Nur Portugiesen', 'Nur Indigene']],
          ['Was stärkte der Paraguaykrieg in Brasilien?', 'Die Armee', ['Die Kirche', 'Die Monarchie', 'Die Sklaverei']],
          ['Was wollten die Offiziere nach dem Krieg?', 'Mehr politischen Einfluss', ['Weniger Macht', 'Die Rückkehr nach Portugal', 'Krieg mit Argentinien']],
          ['Welche Bewegung wuchs nach dem Krieg?', 'Die Bewegung gegen die Sklaverei', ['Die Bewegung für mehr Sklaverei', 'Die Bewegung für Portugal', 'Die Bewegung der Bandeirantes']],
          ['Was war Pedro II. sprachlich?', 'Er sprach mehrere Sprachen', ['Er sprach nur Portugiesisch', 'Er konnte nicht lesen', 'Er sprach nur Latein']],
          ['Was förderte Pedro II.?', 'Forschung und Kunst', ['Nur das Militär', 'Nur den Sklavenhandel', 'Nichts']],
          ['Welches Land führte Solano López?', 'Paraguay', ['Uruguay', 'Bolivien', 'Argentinien']],
          ['Was war Solano López?', 'Diktator', ['Kaiser von Brasilien', 'Präsident Argentiniens', 'Papst']],
        ],
        schwer: [
          ['Was bedeutet der Name „Farrapos“?', 'Lumpen', ['Bauern', 'Reiter', 'Fischer']],
          ['Welche Region erschütterte die Cabanagem?', 'Das Amazonasgebiet', ['Den Süden', 'Minas Gerais', 'Bahia']],
          ['Wie wird der Paraguaykrieg wegen der Gegner genannt?', 'Krieg der Tripel-Allianz', ['Krieg der Vier Mächte', 'Pazifikkrieg', 'Krieg der zwei Kaiser']],
          ['Welche Folge hatte der Krieg für Paraguay demografisch?', 'Es verlor einen großen Teil der Männer', ['Es wuchs stark', 'Es wurde brasilianisch', 'Es wurde reicher']],
          ['Welcher Gelehrte aus Großbritannien schrieb mit Pedro II.?', 'Charles Darwin', ['Michael Faraday', 'James Watt', 'Adam Smith']],
          ['In welcher Stadt war die Weltausstellung 1876?', 'Philadelphia', ['Paris', 'London', 'Wien']],
          ['Wann wurde die Republikanische Partei gegründet?', '1870', ['1889', '1864', '1888']],
          ['Welche Region war Zentrum des Kaffeeanbaus?', 'Das Paraíba-Tal und São Paulo', ['Der Amazonas', 'Pernambuco', 'Mato Grosso']],
          ['Wie lange regierte Pedro II. selbst?', 'Von 1840 bis 1889', ['Von 1831 bis 1840', 'Von 1822 bis 1831', 'Von 1889 bis 1930']],
          ['Welches Exportgut löste den Zucker als wichtigstes ab?', 'Kaffee', ['Gold', 'Baumwolle', 'Kautschuk']],
          ['Welches Problem blieb trotz Stabilität unter Pedro II. bestehen?', 'Die Sklaverei', ['Die Fremdherrschaft', 'Der Bürgerkrieg', 'Die Hungersnot']],
          ['Wie wirkte der Paraguaykrieg auf die Armee?', 'Sie wurde stärker und politischer', ['Sie wurde aufgelöst', 'Sie wurde portugiesisch', 'Sie verlor jeden Einfluss']],
          ['Mit welcher Erfindung ist Bells Name verbunden?', 'Dem Telefon', ['Der Glühbirne', 'Dem Automobil', 'Dem Fernseher']],
          ['Wie alt war Pedro II. bei der Abdankung seines Vaters?', 'Fünf Jahre', ['Vierzehn Jahre', 'Zwanzig Jahre', 'Ein Jahr']],
          ['Welche Länder bildeten die Tripel-Allianz?', 'Brasilien, Argentinien und Uruguay', ['Brasilien, Chile und Peru', 'Paraguay, Bolivien und Peru', 'Portugal, Spanien und Brasilien']],
          ['Was zeigte Pedro II. in Philadelphia?', 'Sein Interesse an Technik', ['Seine Abneigung gegen Neues', 'Seinen Krieg gegen die USA', 'Nichts']],
          ['Wer regierte Brasilien zwischen 1831 und 1840?', 'Regenten für den minderjährigen Kaiser', ['Pedro I.', 'Eine Republik', 'Portugal']],
          ['Was war der Farrapos-Krieg?', 'Ein Aufstand im Süden', ['Ein Krieg gegen Paraguay', 'Ein Sklavenaufstand in Bahia', 'Ein Krieg mit Portugal']],
          ['Welche Folge hatte der Krieg für Brasiliens Politik langfristig?', 'Die Offiziere wollten mehr Einfluss', ['Brasilien wurde Kolonie', 'Die Armee wurde abgeschafft', 'Nichts']],
          ['Welcher Kaiser galt als gebildet und gerecht?', 'Pedro II.', ['Pedro I.', 'Johann VI.', 'Maximilian']],
        ],
      },
    },
  ],
};

export const REPUBLIK: HistEvent = {
  id: 'republik',
  title: 'Ende der Sklaverei und Republik',
  date: '1850–1930',
  text: [
    '1888 schaffte Brasilien als letztes Land Amerikas die Sklaverei ab. Ein Jahr später stürzte das Militär den Kaiser und rief die Republik aus. In der „Alten Republik“ beherrschten die Kaffeebarone aus São Paulo und Minas Gerais die Politik, und Millionen Europäer wanderten ein.',
  ],
  subtopics: [
    {
      id: 'abolition-republik',
      title: 'Abschaffung der Sklaverei und Ausrufung der Republik',
      date: '1850–1889',
      text: [
        'Unter britischem Druck verbot Brasilien 1850 den Sklavenhandel über den Atlantik, die Sklaverei selbst blieb aber erlaubt. 1871 bestimmte das „Gesetz des freien Bauches“, dass Kinder versklavter Mütter frei geboren werden; 1885 wurden Versklavte über 60 Jahre frei. Abolitionisten wie Joaquim Nabuco und der schwarze Journalist José do Patrocínio kämpften für die vollständige Abschaffung, und immer mehr Versklavte flohen.',
        'Am 13. Mai 1888 unterzeichnete Prinzessin Isabel, die Tochter Pedros II., die für ihren reisenden Vater regierte, die „Lei Áurea“ („Goldenes Gesetz“). Sie schaffte die Sklaverei ohne Entschädigung der Besitzer sofort ab und befreite rund 700.000 Menschen. Brasilien war damit das letzte Land Amerikas, das die Sklaverei beendete. Die Befreiten erhielten jedoch weder Land noch Bildung und blieben oft arm.',
        'Viele Plantagenbesitzer waren wütend und unterstützten nun die Republikaner. Auch die Armee war unzufrieden, und die Kirche lag mit dem Kaiser im Streit. Am 15. November 1889 putschte Marschall Deodoro da Fonseca fast ohne Blutvergießen und rief die Republik aus. Der 15. November ist heute Feiertag.',
        'Kaiser Pedro II. ging mit seiner Familie ins Exil nach Europa und starb 1891 in Paris. Die neue Flagge Brasiliens zeigt den Sternenhimmel über Rio am Morgen des 15. November 1889 und das Motto „Ordem e Progresso“ („Ordnung und Fortschritt“), das auf den französischen Philosophen Auguste Comte und seinen Positivismus zurückgeht.',
        '1891 erhielt Brasilien eine Verfassung nach dem Vorbild der USA: eine föderale Republik mit starken Bundesstaaten und einem Präsidenten. Staat und Kirche wurden getrennt.',
      ],
      quiz: {
        leicht: [
          ['Wann schaffte Brasilien die Sklaverei ab?', 'Am 13. Mai 1888', ['Am 7. September 1822', 'Am 15. November 1889', 'Im Jahr 1850']],
          ['Wer unterzeichnete das Gesetz zur Abschaffung der Sklaverei?', 'Prinzessin Isabel', ['Pedro II.', 'Deodoro da Fonseca', 'Getúlio Vargas']],
          ['Wie heißt das Gesetz von 1888?', 'Lei Áurea', ['Lei do Ventre Livre', 'Ordem e Progresso', 'Dia do Fico']],
          ['Was bedeutet „Lei Áurea“?', 'Goldenes Gesetz', ['Freies Gesetz', 'Neues Gesetz', 'Kaiserliches Gesetz']],
          ['Wessen Tochter war Prinzessin Isabel?', 'Die Tochter Pedros II.', ['Die Tochter Pedros I.', 'Die Tochter Johanns VI.', 'Die Tochter Napoleons']],
          ['Wie viele Menschen befreite die Lei Áurea etwa?', 'Rund 700.000', ['Rund 7.000', 'Rund 70.000', 'Rund sieben Millionen']],
          ['Was war Brasilien bei der Abschaffung der Sklaverei?', 'Das letzte Land Amerikas', ['Das erste Land der Welt', 'Das zweite Land Amerikas', 'Ein Vorreiter in Europa']],
          ['Was erhielten die Befreiten?', 'Weder Land noch Bildung', ['Viel Land', 'Gold', 'Häuser in Rio']],
          ['Wer unterstützte nach 1888 die Republikaner?', 'Viele wütende Plantagenbesitzer', ['Die Sklaven', 'Prinzessin Isabel', 'Der Papst']],
          ['Wann wurde die Republik ausgerufen?', 'Am 15. November 1889', ['Am 13. Mai 1888', 'Am 7. September 1822', 'Am 1. Januar 1900']],
          ['Wer rief die Republik aus?', 'Marschall Deodoro da Fonseca', ['Pedro II.', 'Prinzessin Isabel', 'Getúlio Vargas']],
          ['Wie verlief der Putsch von 1889?', 'Fast ohne Blutvergießen', ['Mit Tausenden Toten', 'Als langer Krieg', 'Er scheiterte']],
          ['Wohin ging Pedro II. ins Exil?', 'Nach Europa', ['Nach Afrika', 'Nach Asien', 'In die USA']],
          ['Wo starb Pedro II.?', 'In Paris', ['In Rio', 'In Lissabon', 'In London']],
          ['Welches Motto steht auf der brasilianischen Flagge?', '„Ordem e Progresso“', ['„Liberdade“', '„Deus e Pátria“', '„Independência ou Morte“']],
          ['Was bedeutet „Ordem e Progresso“?', 'Ordnung und Fortschritt', ['Freiheit und Gleichheit', 'Gott und Vaterland', 'Land und Freiheit']],
          ['Was zeigt die Flagge Brasiliens?', 'Den Sternenhimmel über Rio am 15. November 1889', ['Eine Krone', 'Den Zuckerhut', 'Eine Kaffeebohne']],
          ['Auf welchen Philosophen geht das Motto zurück?', 'Auguste Comte', ['Karl Marx', 'Voltaire', 'Rousseau']],
          ['Nach welchem Vorbild entstand die Verfassung von 1891?', 'Nach dem Vorbild der USA', ['Nach dem Vorbild Portugals', 'Nach dem Vorbild Englands', 'Nach dem Vorbild Russlands']],
          ['Was wurde 1891 getrennt?', 'Staat und Kirche', ['Nord und Süd', 'Rio und São Paulo', 'Armee und Polizei']],
        ],
        mittel: [
          ['Wann verbot Brasilien den atlantischen Sklavenhandel?', '1850', ['1888', '1822', '1871']],
          ['Unter wessen Druck geschah das Verbot von 1850?', 'Unter britischem Druck', ['Unter portugiesischem Druck', 'Unter französischem Druck', 'Unter amerikanischem Druck']],
          ['Was bestimmte das Gesetz des freien Bauches 1871?', 'Kinder versklavter Mütter wurden frei geboren', ['Alle Sklaven wurden frei', 'Sklaven durften heiraten', 'Sklavenhandel wurde erlaubt']],
          ['Wer wurde 1885 frei?', 'Versklavte über 60 Jahre', ['Alle Kinder', 'Alle Frauen', 'Niemand']],
          ['Welcher Abolitionist kämpfte gegen die Sklaverei?', 'Joaquim Nabuco', ['Deodoro da Fonseca', 'Pedro I.', 'Tiradentes']],
          ['Welcher schwarze Journalist kämpfte für die Abschaffung?', 'José do Patrocínio', ['Zumbi', 'Aleijadinho', 'Machado de Assis']],
          ['Warum regierte Isabel 1888?', 'Ihr Vater war auf Reisen', ['Ihr Vater war tot', 'Sie war Kaiserin', 'Es gab eine Revolution']],
          ['Erhielten die Sklavenbesitzer eine Entschädigung?', 'Nein', ['Ja, viel Gold', 'Ja, Land', 'Ja, vom Papst']],
          ['Was geschah mit vielen Befreiten?', 'Sie blieben oft arm', ['Sie wurden alle reich', 'Sie gingen nach Afrika', 'Sie wurden Plantagenbesitzer']],
          ['Mit wem lag die Kirche im Streit?', 'Mit dem Kaiser', ['Mit den Sklaven', 'Mit den USA', 'Mit Portugal']],
          ['Wer war außer den Plantagenbesitzern unzufrieden?', 'Die Armee', ['Die Sklaven', 'Prinzessin Isabel', 'England']],
          ['Wann starb Pedro II.?', '1891', ['1889', '1888', '1900']],
          ['Mit wem ging Pedro II. ins Exil?', 'Mit seiner Familie', ['Allein', 'Mit Deodoro', 'Mit Nabuco']],
          ['Was ist der 15. November heute in Brasilien?', 'Ein Feiertag', ['Ein normaler Tag', 'Der Unabhängigkeitstag', 'Der Tag der Sklaverei']],
          ['Welche Staatsform schuf die Verfassung von 1891?', 'Eine föderale Republik', ['Eine Monarchie', 'Eine Diktatur', 'Einen Einheitsstaat']],
          ['Was hatten die Bundesstaaten nach 1891?', 'Viel Macht', ['Keine Macht', 'Eigene Könige', 'Eigene Armeen gegen Rio']],
          ['Wer stand an der Spitze der Republik?', 'Ein Präsident', ['Ein Kaiser', 'Ein König', 'Ein Papst']],
          ['Welcher Rang hatte Deodoro da Fonseca?', 'Marschall', ['Admiral', 'Kardinal', 'Hauptmann']],
          ['Warum flohen immer mehr Versklavte vor 1888?', 'Die Bewegung gegen die Sklaverei wuchs', ['Sie wurden gezwungen', 'Es gab Gold', 'Der Kaiser befahl es']],
          ['Welche Morgenstimmung zeigt die Flagge?', 'Den Morgen des 15. November 1889', ['Den 7. September 1822', 'Den 13. Mai 1888', 'Den 22. April 1500']],
        ],
        schwer: [
          ['Wie heißt das Gesetz von 1871?', 'Gesetz des freien Bauches', ['Goldenes Gesetz', 'Sexagenarier-Gesetz', 'Eusébio-de-Queirós-Gesetz']],
          ['Welche Gruppe befreite das Gesetz von 1885?', 'Versklavte über 60', ['Kinder unter 10', 'Frauen', 'Soldaten']],
          ['Was unterschied die Lei Áurea von früheren Gesetzen?', 'Sie schaffte die Sklaverei sofort und vollständig ab', ['Sie galt nur für Kinder', 'Sie erlaubte den Sklavenhandel', 'Sie galt nur in Rio']],
          ['Welche Folge hatte die Abschaffung für die Monarchie?', 'Sie verlor die Unterstützung der Plantagenbesitzer', ['Sie wurde gestärkt', 'Sie wurde von den USA geschützt', 'Nichts']],
          ['Welche drei Gruppen trugen zum Ende der Monarchie bei?', 'Plantagenbesitzer, Armee und Kirche', ['Sklaven, Indigene und Jesuiten', 'Portugal, Spanien und England', 'Künstler, Bauern und Fischer']],
          ['Welcher Philosoph prägte das Motto der Flagge?', 'Auguste Comte', ['Montesquieu', 'John Locke', 'Hegel']],
          ['Wofür steht der Positivismus von Comte im Motto?', 'Ordnung und Fortschritt', ['Freiheit und Gleichheit', 'Glaube und Hoffnung', 'Liebe und Frieden']],
          ['Wann trat die erste republikanische Verfassung in Kraft?', '1891', ['1889', '1824', '1934']],
          ['Welche Nachricht verband 1888 und 1889?', 'Die Abschaffung der Sklaverei folgte ein Jahr vor dem Ende der Monarchie', ['Beide fanden am selben Tag statt', 'Die Republik schaffte die Sklaverei ab', 'Die Sklaverei wurde 1889 wieder eingeführt']],
          ['Wer schrieb als Journalist gegen die Sklaverei?', 'José do Patrocínio', ['Deodoro da Fonseca', 'Pedro II.', 'Santos-Dumont']],
          ['Welcher Teil der Bevölkerung wurde 1888 frei?', 'Rund 700.000 Versklavte', ['Alle Indigenen', 'Alle Portugiesen', 'Rund 70 Millionen']],
          ['Was erhielten die ehemaligen Sklavenbesitzer 1888?', 'Keine Entschädigung', ['Volle Entschädigung', 'Land in Afrika', 'Adelstitel']],
          ['Welches Datum feiern Brasilianer als Ende der Sklaverei?', '13. Mai', ['20. November', '7. September', '15. November']],
          ['Welcher Kaiser starb im Exil in Paris?', 'Pedro II.', ['Pedro I.', 'Johann VI.', 'Maximilian']],
          ['Wie wurde Brasiliens erste Verfassung als Republik gestaltet?', 'Föderal nach US-Vorbild', ['Zentralistisch nach französischem Vorbild', 'Monarchistisch', 'Sozialistisch']],
          ['Wann wurde die Kirche vom Staat getrennt?', '1891', ['1888', '1822', '1930']],
          ['Welches Land übte Druck gegen den Sklavenhandel aus?', 'Großbritannien', ['Portugal', 'Spanien', 'Frankreich']],
          ['Was geschah, als Pedro II. reiste?', 'Isabel regierte für ihn', ['Deodoro regierte', 'Niemand regierte', 'Portugal übernahm']],
          ['Welche Rolle spielte die Armee 1889?', 'Sie stürzte den Kaiser', ['Sie verteidigte den Kaiser', 'Sie floh nach Paraguay', 'Sie war unbeteiligt']],
          ['Wann trat das Gesetz über Versklavte über 60 in Kraft?', '1885', ['1871', '1850', '1888']],
        ],
      },
    },
    {
      id: 'alte-republik',
      title: 'Die Alte Republik',
      date: '1889–1930',
      text: [
        'In der „Alten Republik“ wechselten sich Präsidenten aus São Paulo und Minas Gerais ab; man nannte das die „Politik von Kaffee mit Milch“, weil São Paulo für Kaffee und Minas Gerais für Milchwirtschaft stand. Wahlen wurden von lokalen Großgrundbesitzern, den „Coronéis“, kontrolliert, die ihren Leuten vorschrieben, wen sie wählen sollten.',
        'Im Hinterland von Bahia gründete der Wanderprediger Antônio Conselheiro die Siedlung Canudos, in der zeitweise rund 25.000 arme Menschen lebten. Die Regierung sah darin eine Gefahr und zerstörte Canudos 1897 nach mehreren Feldzügen; fast alle Bewohner wurden getötet. Der Schriftsteller Euclides da Cunha beschrieb das in „Os Sertões“.',
        'Zwischen 1880 und 1930 wanderten rund vier Millionen Europäer nach Brasilien ein, vor allem Italiener, Portugiesen, Spanier und Deutsche, viele als Arbeiter auf den Kaffeeplantagen; ab 1908 kamen auch Japaner. Im Amazonasgebiet erlebte die Stadt Manaus einen Kautschukboom und baute ein prächtiges Opernhaus mitten im Regenwald. Der Erfinder Alberto Santos-Dumont flog 1906 in Paris mit einem der ersten Flugzeuge.',
        '1904 kam es in Rio zur „Impfrevolte“ („Revolta da Vacina“), als die Regierung eine Pflichtimpfung gegen Pocken einführte. 1910 meuterten Matrosen in der „Revolta da Chibata“ gegen Peitschenstrafen. 1917 trat Brasilien als einziges südamerikanisches Land auf Seiten der Alliierten in den Ersten Weltkrieg ein.',
        '1922 feierten Künstler in São Paulo die „Woche der Modernen Kunst“ und suchten eine eigene brasilianische Moderne. Junge Offiziere, die „Tenentes“ („Leutnants“), rebellierten in den 1920er-Jahren gegen das System; diese Bewegung heißt Tenentismus. Als die Weltwirtschaftskrise 1929 den Kaffeepreis abstürzen ließ, geriet die Alte Republik ins Wanken.',
      ],
      quiz: {
        leicht: [
          ['Wie nannte man die Abwechslung der Präsidenten aus São Paulo und Minas Gerais?', 'Politik von Kaffee mit Milch', ['Politik von Zucker und Gold', 'Politik von Brot und Spielen', 'Politik der Tulpen']],
          ['Wofür stand São Paulo in diesem Bild?', 'Für Kaffee', ['Für Milch', 'Für Gold', 'Für Zucker']],
          ['Wofür stand Minas Gerais?', 'Für Milchwirtschaft', ['Für Kaffee', 'Für Kautschuk', 'Für Fischfang']],
          ['Wie hießen die lokalen Großgrundbesitzer, die Wahlen kontrollierten?', 'Coronéis', ['Bandeirantes', 'Tenentes', 'Quilombolas']],
          ['Welche Siedlung gründete Antônio Conselheiro?', 'Canudos', ['Palmares', 'Brasília', 'Manaus']],
          ['In welcher Region lag Canudos?', 'Im Hinterland von Bahia', ['Im Amazonas', 'In Rio', 'In São Paulo']],
          ['Was geschah 1897 mit Canudos?', 'Die Regierung zerstörte es', ['Es wurde Hauptstadt', 'Es wurde reich', 'Es wurde von Paraguay erobert']],
          ['Welcher Schriftsteller beschrieb Canudos?', 'Euclides da Cunha', ['Machado de Assis', 'Jorge Amado', 'Paulo Coelho']],
          ['Wie viele Europäer wanderten 1880–1930 ein?', 'Rund vier Millionen', ['Rund 40.000', 'Rund 400.000', 'Rund 40 Millionen']],
          ['Welche Einwanderer kamen ab 1908 aus Asien?', 'Japaner', ['Chinesen', 'Inder', 'Koreaner']],
          ['Wo arbeiteten viele Einwanderer?', 'Auf Kaffeeplantagen', ['In Goldminen', 'In Fabriken in Portugal', 'Auf Schiffen']],
          ['Welche Stadt erlebte einen Kautschukboom?', 'Manaus', ['Salvador', 'Recife', 'Porto Alegre']],
          ['Was baute Manaus mitten im Regenwald?', 'Ein prächtiges Opernhaus', ['Eine Pyramide', 'Einen Flughafen', 'Ein Stadion']],
          ['Welcher brasilianische Erfinder flog 1906 mit einem Flugzeug?', 'Alberto Santos-Dumont', ['Orville Wright', 'Pedro II.', 'Getúlio Vargas']],
          ['Wo flog Santos-Dumont 1906?', 'In Paris', ['In Rio', 'In New York', 'In London']],
          ['Wogegen richtete sich die Impfrevolte 1904?', 'Gegen eine Pflichtimpfung gegen Pocken', ['Gegen Steuern', 'Gegen den Kaiser', 'Gegen Einwanderer']],
          ['Wogegen meuterten Matrosen 1910?', 'Gegen Peitschenstrafen', ['Gegen den Präsidenten', 'Gegen Portugal', 'Gegen Einwanderer']],
          ['Auf welcher Seite trat Brasilien 1917 in den Ersten Weltkrieg ein?', 'Auf Seiten der Alliierten', ['Auf Seiten Deutschlands', 'Es blieb neutral', 'Auf Seiten der Osmanen']],
          ['Welche Kunstwoche fand 1922 in São Paulo statt?', 'Die Woche der Modernen Kunst', ['Die Biennale', 'Die Weltausstellung', 'Der Karneval']],
          ['Was ließ 1929 die Alte Republik wanken?', 'Der Absturz des Kaffeepreises', ['Ein Erdbeben', 'Ein Krieg mit Argentinien', 'Ein Goldfund']],
        ],
        mittel: [
          ['Was schrieben die Coronéis ihren Leuten vor?', 'Wen sie wählen sollten', ['Was sie essen sollten', 'Wo sie wohnen sollten', 'Welche Sprache sie sprechen sollten']],
          ['Was war Antônio Conselheiro?', 'Ein Wanderprediger', ['Ein General', 'Ein Präsident', 'Ein Kaffeebaron']],
          ['Wie viele Menschen lebten zeitweise in Canudos?', 'Rund 25.000', ['Rund 250', 'Rund 2.500', 'Rund 250.000']],
          ['Wer lebte in Canudos?', 'Arme Menschen', ['Reiche Kaffeebarone', 'Soldaten', 'Europäische Einwanderer']],
          ['Was geschah mit den Bewohnern von Canudos?', 'Fast alle wurden getötet', ['Sie wurden umgesiedelt nach Rio', 'Sie wurden reich', 'Sie wanderten nach Europa']],
          ['Wie heißt das Werk von Euclides da Cunha?', '„Os Sertões“', ['„Dom Casmurro“', '„Der Alchimist“', '„Gabriela“']],
          ['Welche Europäer wanderten vor allem ein?', 'Italiener, Portugiesen, Spanier und Deutsche', ['Briten und Iren', 'Russen und Finnen', 'Schweden und Norweger']],
          ['Ab wann kamen japanische Einwanderer?', 'Ab 1908', ['Ab 1850', 'Ab 1945', 'Ab 1888']],
          ['Welcher Rohstoff brachte Manaus Reichtum?', 'Kautschuk', ['Kaffee', 'Gold', 'Zucker']],
          ['In welchem Gebiet liegt Manaus?', 'Im Amazonasgebiet', ['Im Süden', 'In Bahia', 'An der Küste bei Rio']],
          ['Wann flog Santos-Dumont in Paris?', '1906', ['1903', '1922', '1889']],
          ['Wann fand die Impfrevolte statt?', '1904', ['1910', '1897', '1922']],
          ['Wie heißt die Matrosenmeuterei von 1910?', 'Revolta da Chibata', ['Revolta da Vacina', 'Cabanagem', 'Inconfidência']],
          ['Was ist besonders an Brasiliens Kriegseintritt 1917?', 'Es war das einzige südamerikanische Land auf Seiten der Alliierten', ['Es kämpfte für Deutschland', 'Es eroberte Paris', 'Es trat nie ein']],
          ['Wer rebellierte in den 1920er-Jahren?', 'Junge Offiziere, die Tenentes', ['Die Coronéis', 'Die Kaffeebarone', 'Die Japaner']],
          ['Wann fand die Woche der Modernen Kunst statt?', '1922', ['1904', '1930', '1889']],
          ['Was suchten die Künstler 1922?', 'Eine eigene brasilianische Moderne', ['Eine Rückkehr zum Barock', 'Die Kunst Portugals', 'Die Kunst der Azteken']],
          ['Welche Krise traf Brasilien 1929?', 'Die Weltwirtschaftskrise', ['Die Ölkrise', 'Die Eurokrise', 'Die Asienkrise']],
          ['Wann wurde Canudos zerstört?', '1897', ['1889', '1904', '1930']],
          ['Was war die Alte Republik politisch?', 'Von Eliten aus zwei Bundesstaaten beherrscht', ['Eine echte Demokratie für alle', 'Eine Monarchie', 'Eine Militärdiktatur']],
        ],
        schwer: [
          ['Was bedeutet „Tenentes“?', 'Leutnants', ['Bauern', 'Priester', 'Präsidenten']],
          ['Wie heißt die Pockenimpf-Revolte auf Portugiesisch?', 'Revolta da Vacina', ['Revolta da Chibata', 'Guerra de Canudos', 'Farrapos']],
          ['Welche Strafe wollten die Matrosen 1910 abschaffen?', 'Peitschenstrafen', ['Todesstrafe', 'Gefängnis', 'Geldstrafen']],
          ['Welches Gebäude zeugt in Manaus vom Kautschukboom?', 'Das Opernhaus', ['Ein Wolkenkratzer', 'Eine Kathedrale aus Gold', 'Ein Fußballstadion']],
          ['Welche Rolle spielten die Coronéis im Wahlsystem?', 'Sie kontrollierten die Stimmen ihrer Leute', ['Sie zählten die Stimmen fair', 'Sie hatten keinen Einfluss', 'Sie waren Richter']],
          ['Welcher Bundesstaat stand für Kaffee in der „Kaffee mit Milch“-Politik?', 'São Paulo', ['Minas Gerais', 'Rio de Janeiro', 'Bahia']],
          ['Welcher Prediger führte Canudos?', 'Antônio Conselheiro', ['Padre Cícero', 'José de Anchieta', 'Antônio Vieira']],
          ['Welches Ereignis machte Brasilien zum Kriegsteilnehmer 1917?', 'Der Eintritt auf Seiten der Alliierten', ['Ein Angriff Argentiniens', 'Ein Bündnis mit Deutschland', 'Ein Bürgerkrieg']],
          ['Welcher Erfinder gilt in Brasilien als Pionier des Fliegens?', 'Santos-Dumont', ['Getúlio Vargas', 'Pedro II.', 'Oswaldo Cruz']],
          ['Welcher Zeitraum heißt „Alte Republik“?', '1889–1930', ['1822–1889', '1930–1945', '1964–1985']],
          ['Wie viele Feldzüge brauchte die Regierung gegen Canudos?', 'Mehrere', ['Einen', 'Keinen', 'Hundert']],
          ['Wann begann die japanische Einwanderung nach Brasilien?', '1908', ['1888', '1930', '1950']],
          ['Welche Folge hatte der Kaffeepreisabsturz 1929?', 'Die Alte Republik geriet ins Wanken', ['Brasilien wurde reich', 'Brasilien wurde Monarchie', 'Nichts']],
          ['Welches Werk gilt als Hauptwerk über Canudos?', '„Os Sertões“', ['„Macunaíma“', '„Grande Sertão“', '„Iracema“']],
          ['Welche Bewegung junger Offiziere bekämpfte das System?', 'Der Tenentismus', ['Der Positivismus', 'Der Abolitionismus', 'Der Coronelismus']],
          ['Was kennzeichnete die Wahlen der Alten Republik?', 'Kontrolle durch lokale Großgrundbesitzer', ['Frauenwahlrecht', 'Elektronische Wahl', 'Freie und geheime Wahl für alle']],
          ['Welche Stadt war Ort der Woche der Modernen Kunst?', 'São Paulo', ['Rio de Janeiro', 'Salvador', 'Ouro Preto']],
          ['Welche Einwanderergruppe aus Europa war besonders groß?', 'Die Italiener', ['Die Schweden', 'Die Griechen', 'Die Iren']],
          ['Welche Stadt war Schauplatz der Impfrevolte?', 'Rio de Janeiro', ['São Paulo', 'Manaus', 'Salvador']],
          ['Wofür steht Canudos in der Geschichte?', 'Für die brutale Unterdrückung armer Menschen im Hinterland', ['Für eine Goldentdeckung', 'Für die Gründung einer Hauptstadt', 'Für einen Sieg über Paraguay']],
        ],
      },
    },
  ],
};
