import type { HistEvent } from '../types';

export const EROBERUNG: HistEvent = {
  id: 'eroberung',
  title: 'Die spanische Eroberung',
  date: '1519–1810',
  text: [
    'Mit wenigen Hundert Soldaten, aber vielen indigenen Verbündeten eroberte Hernán Cortés 1519–1521 das Aztekenreich. Danach war Mexiko fast 300 Jahre lang als „Neuspanien“ eine spanische Kolonie, in der eine neue, gemischte Gesellschaft entstand.',
  ],
  subtopics: [
    {
      id: 'cortes-eroberung',
      title: 'Cortés und der Fall Tenochtitlans',
      date: '1519–1521',
      text: [
        '1519 landete Hernán Cortés mit rund 500 Soldaten, Pferden und Kanonen an der Küste bei Veracruz. Er ließ seine Schiffe zerstören, damit niemand umkehren konnte. Eine wichtige Helferin wurde die Indigene Malintzin, von den Spaniern Doña Marina und später „La Malinche“ genannt, die für ihn übersetzte und ihn beriet.',
        'Viele Völker hassten die Azteken, weil sie Tribut zahlen und Gefangene für Opfer liefern mussten. Vor allem die Tlaxcalteken verbündeten sich mit Cortés und stellten Zehntausende Krieger. Im November 1519 empfing Moctezuma II. die Spanier freundlich in Tenochtitlan; sie staunten über die Stadt, nahmen den Herrscher aber bald gefangen.',
        'Im Mai 1520 richtete Cortés’ Stellvertreter Pedro de Alvarado ein Massaker bei einem Fest im Templo Mayor an. Die Azteken erhoben sich, Moctezuma starb, und in der „Noche Triste“ („traurigen Nacht“) am 30. Juni 1520 mussten die Spanier fliehen, wobei viele im See ertranken, beladen mit Gold.',
        'Dann wütete eine Pockenepidemie, die die Spanier eingeschleppt hatten, und tötete viele Azteken, auch den neuen Herrscher Cuitláhuac. Cortés ließ Boote bauen und belagerte Tenochtitlan monatelang. Am 13. August 1521 ergab sich der letzte Herrscher Cuauhtémoc; die Stadt war zerstört. Cuauhtémoc wurde später hingerichtet und gilt heute als Held.',
        'Gründe für den Sieg der Spanier waren ihre Verbündeten, Krankheiten wie die Pocken, gegen die die Indigenen keine Abwehrkräfte hatten, sowie Stahlwaffen, Pferde und Kanonen. Auf den Ruinen Tenochtitlans ließ Cortés Mexiko-Stadt errichten.',
      ],
      quiz: {
        leicht: [
          ['Wer eroberte das Aztekenreich?', 'Hernán Cortés', ['Francisco Pizarro', 'Christoph Kolumbus', 'Vasco da Gama']],
          ['Wann landete Cortés in Mexiko?', '1519', ['1492', '1521', '1810']],
          ['Mit wie vielen Soldaten landete Cortés?', 'Mit rund 500', ['Mit rund 50.000', 'Mit rund 5.000', 'Mit rund 50']],
          ['Was ließ Cortés mit seinen Schiffen tun?', 'Er ließ sie zerstören', ['Er schickte sie nach China', 'Er verkaufte sie', 'Er versteckte sie']],
          ['Welche indigene Frau übersetzte für Cortés?', 'Malintzin (La Malinche)', ['Pocahontas', 'Sor Juana', 'Frida Kahlo']],
          ['Welches Volk verbündete sich vor allem mit Cortés?', 'Die Tlaxcalteken', ['Die Maya', 'Die Inka', 'Die Mexica']],
          ['Warum hassten viele Völker die Azteken?', 'Sie mussten Tribut zahlen und Opfer liefern', ['Wegen ihrer Sprache', 'Weil sie Christen waren', 'Weil sie Spanier waren']],
          ['Welcher Herrscher empfing die Spanier 1519?', 'Moctezuma II.', ['Cuauhtémoc', 'Pakal', 'Cuitláhuac']],
          ['Was taten die Spanier bald mit Moctezuma?', 'Sie nahmen ihn gefangen', ['Sie krönten ihn', 'Sie schickten ihn nach Spanien', 'Sie ließen ihn frei']],
          ['Wie heißt die Nacht der spanischen Flucht 1520?', 'Noche Triste', ['Noche Buena', 'Bartholomäusnacht', 'Walpurgisnacht']],
          ['Was bedeutet „Noche Triste“?', 'Traurige Nacht', ['Heilige Nacht', 'Lange Nacht', 'Blutige Nacht']],
          ['Welche Krankheit wütete unter den Azteken?', 'Die Pocken', ['Die Pest', 'Die Cholera', 'Malaria']],
          ['Wann ergab sich Tenochtitlan?', 'Am 13. August 1521', ['Am 12. Oktober 1492', 'Am 16. September 1810', 'Am 30. Juni 1520']],
          ['Wer war der letzte Herrscher der Azteken?', 'Cuauhtémoc', ['Moctezuma II.', 'Cuitláhuac', 'Malintzin']],
          ['Als was gilt Cuauhtémoc heute?', 'Als Held', ['Als Verräter', 'Als Spanier', 'Als König Spaniens']],
          ['Welche Stadt ließ Cortés auf den Ruinen errichten?', 'Mexiko-Stadt', ['Veracruz', 'Puebla', 'Havanna']],
          ['Welche Waffen hatten die Spanier?', 'Stahlwaffen und Kanonen', ['Blasrohre', 'Atomwaffen', 'Keine']],
          ['Welche Tiere brachten die Spanier mit?', 'Pferde', ['Elefanten', 'Kamele', 'Löwen']],
          ['Bei welcher Stadt landete Cortés?', 'Bei Veracruz', ['Bei Acapulco', 'Bei Cancún', 'Bei Tijuana']],
          ['Was hatten die Indigenen gegen die Pocken nicht?', 'Abwehrkräfte', ['Ärzte', 'Häuser', 'Wasser']],
        ],
        mittel: [
          ['Wie nannten die Spanier Malintzin?', 'Doña Marina', ['Doña Isabel', 'Doña Juana', 'Doña Maria Teresa']],
          ['Wie viele Krieger stellten die Tlaxcalteken?', 'Zehntausende', ['Einige Dutzend', 'Einige Hundert', 'Keine']],
          ['Wann empfing Moctezuma die Spanier?', 'Im November 1519', ['Im Mai 1520', 'Im August 1521', 'Im Januar 1519']],
          ['Wer richtete im Mai 1520 ein Massaker an?', 'Pedro de Alvarado', ['Hernán Cortés', 'Francisco Pizarro', 'Moctezuma']],
          ['Wo fand das Massaker 1520 statt?', 'Bei einem Fest im Templo Mayor', ['Auf dem Markt von Tlatelolco', 'In Veracruz', 'In Tlaxcala']],
          ['Was geschah nach dem Massaker?', 'Die Azteken erhoben sich', ['Die Azteken ergaben sich', 'Moctezuma wurde König Spaniens', 'Nichts']],
          ['Wann war die Noche Triste?', 'Am 30. Juni 1520', ['Am 13. August 1521', 'Am 8. November 1519', 'Am 1. Januar 1520']],
          ['Warum ertranken viele Spanier in der Noche Triste?', 'Sie waren mit Gold beladen', ['Sie konnten nicht schwimmen wegen Kälte', 'Ein Sturm kam', 'Ihre Schiffe sanken']],
          ['Welcher Herrscher starb an den Pocken?', 'Cuitláhuac', ['Cuauhtémoc', 'Moctezuma II.', 'Nezahualcóyotl']],
          ['Was ließ Cortés für die Belagerung bauen?', 'Boote', ['Mauern', 'Türme', 'Brücken aus Eisen']],
          ['Wie lange belagerte Cortés Tenochtitlan?', 'Monatelang', ['Einen Tag', 'Zehn Jahre', 'Eine Stunde']],
          ['In welchem Zustand war Tenochtitlan 1521?', 'Zerstört', ['Unversehrt', 'Verlassen ohne Kampf', 'Vergrößert']],
          ['Was geschah später mit Cuauhtémoc?', 'Er wurde hingerichtet', ['Er wurde Gouverneur', 'Er floh nach Peru', 'Er wurde Priester in Rom']],
          ['Welche Rolle spielte Malintzin?', 'Sie übersetzte und beriet Cortés', ['Sie war Königin der Azteken', 'Sie kämpfte gegen Cortés', 'Sie war Spanierin']],
          ['Warum zerstörte Cortés seine Schiffe?', 'Damit niemand umkehren konnte', ['Weil sie leck waren', 'Weil der König es befahl', 'Um Holz für Häuser zu haben']],
          ['Wer schleppte die Pocken ein?', 'Die Spanier', ['Die Maya', 'Die Tlaxcalteken', 'Die Inka']],
          ['Welche Gründe hatte der spanische Sieg?', 'Verbündete, Krankheiten und Waffen', ['Allein der Mut der Spanier', 'Eine Flotte aus England', 'Ein Erdbeben']],
          ['Wie behandelte Moctezuma die Spanier zuerst?', 'Freundlich', ['Feindlich', 'Gleichgültig', 'Er tötete sie']],
          ['Worüber staunten die Spanier?', 'Über die Stadt Tenochtitlan', ['Über die Wüste', 'Über das Eis', 'Über Pyramiden in Ägypten']],
          ['Wer war Pedro de Alvarado?', 'Der Stellvertreter von Cortés', ['Ein aztekischer Priester', 'Ein Maya-König', 'Ein Papst']],
        ],
        schwer: [
          ['Wie nennt man Malintzin heute oft?', 'La Malinche', ['La Catrina', 'La Llorona', 'La Adelita']],
          ['Welcher Herrscher folgte Moctezuma kurz vor Cuauhtémoc?', 'Cuitláhuac', ['Itzcóatl', 'Ahuítzotl', 'Tízoc']],
          ['In welchem Monat 1520 fand das Massaker im Templo Mayor statt?', 'Im Mai', ['Im Juni', 'Im November', 'Im August']],
          ['Welche Volksgruppe stellte das größte indigene Kontingent für Cortés?', 'Die Tlaxcalteken', ['Die Zapoteken', 'Die Tarasken', 'Die Mixteken']],
          ['Was bewirkte die Pockenepidemie?', 'Sie tötete viele Azteken', ['Sie tötete die Spanier', 'Sie hatte keine Folgen', 'Sie traf nur Pferde']],
          ['Wie lange dauerte die Eroberung insgesamt?', 'Rund zwei Jahre', ['Rund zwanzig Jahre', 'Einen Monat', 'Hundert Jahre']],
          ['Was wurde aus dem Platz Tenochtitlans?', 'Mexiko-Stadt', ['Ein See', 'Ein Wald', 'Eine Wüste']],
          ['Wie gelangten die Spanier zur Inselstadt bei der Belagerung?', 'Mit Booten', ['Mit Flugzeugen', 'Mit Tunneln', 'Mit Brücken aus Eisen']],
          ['Welches Ereignis nennt man auch „traurige Nacht“?', 'Die Flucht der Spanier 1520', ['Den Fall Tenochtitlans', 'Die Landung 1519', 'Den Tod Cuauhtémocs']],
          ['Mit welchen Tieren beeindruckten die Spanier die Azteken?', 'Mit Pferden', ['Mit Kamelen', 'Mit Elefanten', 'Mit Falken']],
          ['Welcher Herrscher ergab sich am 13. August 1521?', 'Cuauhtémoc', ['Cuitláhuac', 'Moctezuma', 'Nezahualpilli']],
          ['Was fehlte den Indigenen gegen eingeschleppte Krankheiten?', 'Abwehrkräfte', ['Kräuter', 'Priester', 'Mauern']],
          ['Was zeigt die Rolle der Tlaxcalteken?', 'Dass die Eroberung ohne indigene Verbündete kaum möglich gewesen wäre', ['Dass die Azteken keine Feinde hatten', 'Dass die Spanier allein kämpften', 'Dass die Maya halfen']],
          ['Warum war La Malinche für Cortés so wichtig?', 'Sie übersetzte und kannte die Verhältnisse', ['Sie war seine Generalin', 'Sie war Aztekenkaiserin', 'Sie finanzierte ihn']],
          ['Welche Stadt war Ausgangspunkt der Spanier an der Küste?', 'Veracruz', ['Acapulco', 'Mérida', 'Oaxaca']],
          ['Wie wird Cuauhtémoc heute in Mexiko gesehen?', 'Als Held', ['Als Feigling', 'Als Spanier', 'Gar nicht']],
          ['Wann starb Moctezuma II.?', '1520', ['1519', '1521', '1502']],
          ['Welche Folge hatte das Massaker von Alvarado?', 'Einen Aufstand der Azteken', ['Den Frieden', 'Die Taufe Moctezumas', 'Die Ankunft weiterer Schiffe']],
          ['Was war das Ergebnis der Belagerung für die Stadt?', 'Ihre Zerstörung', ['Ihre Rettung', 'Ihr Verkauf', 'Ihr Wiederaufbau durch Azteken']],
          ['Welche drei militärischen Vorteile hatten die Spanier?', 'Stahlwaffen, Pferde und Kanonen', ['Flugzeuge, Panzer und Schiffe', 'Gold, Silber und Kupfer', 'Elefanten, Kamele und Hunde']],
        ],
      },
    },
    {
      id: 'neuspanien',
      title: 'Das Vizekönigreich Neuspanien',
      date: '1521–1810',
      text: [
        'Nach der Eroberung wurde Mexiko 1535 Kern des Vizekönigreichs Neuspanien, das ein Vizekönig im Namen des spanischen Königs von Mexiko-Stadt aus regierte. Es reichte zeitweise von Kalifornien bis Mittelamerika und schloss sogar die Philippinen ein. Spanische Eroberer erhielten im „Encomienda“-System Indigene zugeteilt, die für sie arbeiten mussten.',
        'Die größte Katastrophe waren eingeschleppte Krankheiten: Durch Pocken, Masern und andere Seuchen sank die indigene Bevölkerung Zentralmexikos im 16. Jahrhundert von vielleicht 20 Millionen auf rund 1,5 Millionen. Der Mönch Bartolomé de las Casas klagte die Misshandlung der Indigenen an.',
        'Franziskaner und andere Mönche bekehrten die Indigenen zum Christentum. 1531 soll dem indigenen Juan Diego auf dem Hügel Tepeyac die Jungfrau Maria erschienen sein; die „Jungfrau von Guadalupe“ wurde zur Schutzpatronin Mexikos, und ihre Basilika ist heute einer der meistbesuchten Wallfahrtsorte der Welt. Auf den Ruinen des Templo Mayor entstand die große Kathedrale von Mexiko-Stadt.',
        'Neuspanien wurde durch Silber reich: In Zacatecas und Guanajuato lagen einige der reichsten Silberminen der Welt. Mexikanische Silbermünzen wurden zur Weltwährung. Über die „Manila-Galeone“ wurde Silber von Acapulco über den Pazifik nach Asien gebracht und gegen Seide und Porzellan getauscht.',
        'Die Gesellschaft war nach Herkunft geordnet: Oben standen die in Spanien geborenen „Peninsulares“, dann die in Amerika geborenen Spanier, die „Criollos“, darunter die „Mestizen“ mit gemischter Herkunft, die Indigenen und afrikanische Sklaven. Die Nonne Sor Juana Inés de la Cruz (1648–1695) war eine der bedeutendsten Dichterinnen spanischer Sprache; man nannte sie die „Zehnte Muse“. Die Criollos waren zunehmend unzufrieden, weil die Peninsulares die höchsten Ämter erhielten.',
      ],
      quiz: {
        leicht: [
          ['Wie hieß die spanische Kolonie mit Mexiko als Kern?', 'Neuspanien', ['Neugranada', 'Neufrankreich', 'Neu-England']],
          ['Wer regierte Neuspanien im Namen des Königs?', 'Ein Vizekönig', ['Ein Kaiser', 'Ein Präsident', 'Der Papst']],
          ['Von welcher Stadt aus wurde Neuspanien regiert?', 'Von Mexiko-Stadt', ['Von Veracruz', 'Von Sevilla', 'Von Havanna']],
          ['Welche Inselgruppe in Asien gehörte zu Neuspanien?', 'Die Philippinen', ['Japan', 'Indonesien', 'Hawaii']],
          ['Wie hieß das System, in dem Indigene für Spanier arbeiten mussten?', 'Encomienda', ['Hacienda', 'Fiesta', 'Siesta']],
          ['Was war die größte Katastrophe für die Indigenen?', 'Eingeschleppte Krankheiten', ['Ein Vulkanausbruch', 'Eine Eiszeit', 'Eine Hungersnot durch Heuschrecken']],
          ['Welcher Mönch klagte die Misshandlung der Indigenen an?', 'Bartolomé de las Casas', ['Hernán Cortés', 'Juan Diego', 'Miguel Hidalgo']],
          ['Wem soll 1531 die Jungfrau Maria erschienen sein?', 'Juan Diego', ['Cortés', 'Moctezuma', 'Sor Juana']],
          ['Wie heißt die Schutzpatronin Mexikos?', 'Die Jungfrau von Guadalupe', ['Die heilige Theresa', 'Die Jungfrau von Fátima', 'Die heilige Barbara']],
          ['Was entstand auf den Ruinen des Templo Mayor?', 'Die Kathedrale von Mexiko-Stadt', ['Ein Stadion', 'Ein Bahnhof', 'Ein Palast des Königs von Spanien']],
          ['Welches Metall machte Neuspanien reich?', 'Silber', ['Eisen', 'Kupfer', 'Zinn']],
          ['Welche Städte hatten reiche Silberminen?', 'Zacatecas und Guanajuato', ['Cancún und Tulum', 'Tijuana und Mexicali', 'Veracruz und Mérida']],
          ['Was wurde zur Weltwährung?', 'Mexikanische Silbermünzen', ['Kakaobohnen', 'Spanisches Papiergeld', 'Goldbarren der Azteken']],
          ['Wie hieß das Schiff, das Silber nach Asien brachte?', 'Die Manila-Galeone', ['Die Santa María', 'Die Mayflower', 'Die Armada']],
          ['Von welchem Hafen fuhr die Manila-Galeone ab?', 'Von Acapulco', ['Von Veracruz', 'Von Havanna', 'Von Sevilla']],
          ['Wogegen wurde das Silber in Asien getauscht?', 'Gegen Seide und Porzellan', ['Gegen Sklaven', 'Gegen Pferde', 'Gegen Kakao']],
          ['Wie hießen die in Spanien geborenen Spanier?', 'Peninsulares', ['Criollos', 'Mestizen', 'Conquistadores']],
          ['Wie hießen die in Amerika geborenen Spanier?', 'Criollos', ['Peninsulares', 'Mestizen', 'Indios']],
          ['Wie nannte man Menschen gemischter Herkunft?', 'Mestizen', ['Criollos', 'Peninsulares', 'Inka']],
          ['Welche Nonne war eine bedeutende Dichterin?', 'Sor Juana Inés de la Cruz', ['Teresa von Ávila', 'Mutter Teresa', 'Frida Kahlo']],
        ],
        mittel: [
          ['Wann wurde das Vizekönigreich Neuspanien gegründet?', '1535', ['1521', '1492', '1810']],
          ['Wie weit reichte Neuspanien zeitweise?', 'Von Kalifornien bis Mittelamerika', ['Von Alaska bis Feuerland', 'Nur über Mexiko-Stadt', 'Von Kanada bis Kuba']],
          ['Von wie vielen auf wie viele Menschen sank die Bevölkerung Zentralmexikos etwa?', 'Von vielleicht 20 Millionen auf rund 1,5 Millionen', ['Von 2 Millionen auf 1 Million', 'Von 100 Millionen auf 50 Millionen', 'Sie stieg']],
          ['Welche Krankheiten wüteten außer den Pocken?', 'Masern und andere Seuchen', ['Nur Erkältungen', 'Heuschnupfen', 'Keine']],
          ['Welche Mönche bekehrten die Indigenen unter anderem?', 'Die Franziskaner', ['Die Buddhisten', 'Die Lutheraner', 'Die Mormonen']],
          ['Auf welchem Hügel soll Juan Diego die Erscheinung gehabt haben?', 'Auf dem Tepeyac', ['Auf dem Popocatépetl', 'Auf dem Chapultepec', 'Auf dem Monte Albán']],
          ['Was ist die Basilika von Guadalupe heute?', 'Einer der meistbesuchten Wallfahrtsorte der Welt', ['Ein Museum', 'Eine Ruine', 'Ein Gefängnis']],
          ['Was mussten Indigene in der Encomienda tun?', 'Für Spanier arbeiten', ['Steuern an Azteken zahlen', 'Nach Spanien reisen', 'Nichts']],
          ['Wohin wurde mexikanisches Silber über den Pazifik gebracht?', 'Nach Asien', ['Nach Australien', 'Nach Afrika', 'Nach Grönland']],
          ['Welche Rolle spielten mexikanische Silbermünzen weltweit?', 'Sie wurden zur Weltwährung', ['Sie waren verboten', 'Sie galten nur in Mexiko', 'Sie waren Spielgeld']],
          ['Wer stand in der Gesellschaft Neuspaniens ganz oben?', 'Die Peninsulares', ['Die Criollos', 'Die Mestizen', 'Die Indigenen']],
          ['Wer war besonders benachteiligt?', 'Indigene und afrikanische Sklaven', ['Peninsulares', 'Vizekönige', 'Bischöfe']],
          ['Warum waren die Criollos unzufrieden?', 'Die höchsten Ämter erhielten die Peninsulares', ['Sie durften keine Kirchen bauen', 'Sie mussten Tribut an die Azteken zahlen', 'Sie waren arm wie die Indigenen']],
          ['Wann lebte Sor Juana Inés de la Cruz?', '1648–1695', ['1492–1521', '1810–1867', '1907–1954']],
          ['In welcher Sprache schrieb Sor Juana?', 'Auf Spanisch', ['Auf Französisch', 'Auf Portugiesisch', 'Auf Englisch']],
          ['Was ist Zacatecas?', 'Eine Stadt mit reichen Silberminen', ['Eine Aztekenpyramide', 'Ein Hafen', 'Ein Vulkan']],
          ['Wann erschien die Jungfrau von Guadalupe der Legende nach?', '1531', ['1521', '1810', '1492']],
          ['Welche Waren kamen aus Asien nach Neuspanien?', 'Seide und Porzellan', ['Kartoffeln', 'Mais', 'Kakao']],
          ['Was war Bartolomé de las Casas?', 'Ein Mönch', ['Ein Eroberer', 'Ein Vizekönig', 'Ein Aztekenkönig']],
          ['Wie war die Gesellschaft Neuspaniens geordnet?', 'Nach Herkunft', ['Nach Vermögen', 'Nach Alter', 'Nach Körpergröße']],
        ],
        schwer: [
          ['Wie stark sank die indigene Bevölkerung Zentralmexikos im 16. Jahrhundert?', 'Um über 90 Prozent', ['Um 10 Prozent', 'Um die Hälfte', 'Sie stieg']],
          ['Welcher Ort ist mit Juan Dieges Vision verbunden?', 'Tepeyac', ['Teotihuacán', 'Tlaxcala', 'Cholula']],
          ['Welche Route verband Acapulco mit Manila?', 'Die Manila-Galeone über den Pazifik', ['Der Panamakanal', 'Die Seidenstraße zu Land', 'Die Route ums Kap Hoorn']],
          ['Was erhielten spanische Eroberer in der Encomienda?', 'Indigene zugeteilt, die für sie arbeiten mussten', ['Land in Spanien', 'Gold vom König', 'Schiffe']],
          ['Welche Gruppe stand unter den Criollos, aber über den Indigenen?', 'Die Mestizen', ['Die Peninsulares', 'Die Vizekönige', 'Die afrikanischen Sklaven']],
          ['Welche Stadt in Guanajuato war wegen Silber reich?', 'Guanajuato', ['Puebla', 'Oaxaca', 'Mérida']],
          ['Wer verteidigte die Indigenen gegen Misshandlung schriftlich?', 'Bartolomé de las Casas', ['Hernán Cortés', 'Pedro de Alvarado', 'Antonio de Mendoza']],
          ['Welches Bauwerk steht heute an der Stelle des Templo Mayor?', 'Die Kathedrale', ['Ein Fußballstadion', 'Die Basilika von Guadalupe', 'Der Torre Latinoamericana']],
          ['Wann wurde Neuspanien Vizekönigreich?', '1535', ['1521', '1550', '1600']],
          ['Welche Nonne gilt als „Zehnte Muse“?', 'Sor Juana Inés de la Cruz', ['Teresa von Ávila', 'Rosa von Lima', 'Hildegard von Bingen']],
          ['Welches Problem führte später zur Unabhängigkeitsbewegung?', 'Die Unzufriedenheit der Criollos', ['Die Zufriedenheit aller', 'Die Pocken', 'Die Manila-Galeone']],
          ['Wer verwaltete die Philippinen in der Kolonialzeit?', 'Neuspanien', ['Portugal', 'Die Niederlande', 'England']],
          ['Welche Stadt war Pazifikhafen Neuspaniens?', 'Acapulco', ['Veracruz', 'Campeche', 'Tampico']],
          ['Was bewirkten die Silberminen weltweit?', 'Mexikanisches Silber wurde zur Weltwährung', ['Spanien wurde arm', 'China verbot Silber', 'Nichts']],
          ['Welche Herkunft hatten Peninsulares?', 'Sie waren in Spanien geboren', ['Sie waren in Amerika geboren', 'Sie waren Indigene', 'Sie waren Afrikaner']],
          ['Wie viele Menschen lebten vielleicht vor der Eroberung in Zentralmexiko?', 'Rund 20 Millionen', ['Rund 2 Millionen', 'Rund 200.000', 'Rund 200 Millionen']],
          ['Welche Rolle hatten afrikanische Sklaven in Neuspanien?', 'Sie standen am unteren Ende der Gesellschaft', ['Sie waren Vizekönige', 'Sie gab es nicht', 'Sie waren Peninsulares']],
          ['Welche Basilika ist heute ein Wallfahrtsort?', 'Die Basilika von Guadalupe', ['Die Sagrada Família', 'Die Peterskirche', 'Notre-Dame']],
          ['Welcher Orden war bei der Mission besonders aktiv?', 'Die Franziskaner', ['Die Templer', 'Die Mormonen', 'Die Johanniter']],
          ['Wofür steht der Name „Criollos“?', 'In Amerika geborene Spanier', ['In Spanien geborene Spanier', 'Afrikaner', 'Indigene Adlige']],
        ],
      },
    },
  ],
};
