import type { HistEvent } from '../types';

export const GRITO: HistEvent = {
  id: 'grito',
  title: 'Die Unabhängigkeit',
  date: '1810–1823',
  text: [
    'Mit dem „Grito de Dolores“ des Priesters Miguel Hidalgo begann 1810 der Unabhängigkeitskrieg. Nach elf Jahren Kampf wurde Mexiko 1821 unabhängig, zunächst als Kaiserreich unter Agustín de Iturbide, 1824 als Republik.',
  ],
  subtopics: [
    {
      id: 'hidalgo-morelos',
      title: 'Hidalgo, Morelos und die Unabhängigkeit',
      date: '1810–1824',
      text: [
        '1808 besetzte Napoleon Spanien und setzte den spanischen König ab. In Neuspanien nutzten Criollos die Gelegenheit, über mehr Selbstbestimmung nachzudenken. Im Städtchen Dolores im heutigen Bundesstaat Guanajuato rief der Priester Miguel Hidalgo in der Nacht zum 16. September 1810 die Menschen mit der Kirchenglocke zusammen und forderte sie zum Aufstand auf – der „Grito de Dolores“ („Ruf von Dolores“). Der 16. September ist heute Mexikos Unabhängigkeitstag; jedes Jahr wiederholt der Präsident den Ruf vom Balkon des Nationalpalastes.',
        'Hidalgo führte ein riesiges Heer aus Indigenen und Mestizen unter dem Banner der Jungfrau von Guadalupe. In Guanajuato stürmten die Aufständischen den Getreidespeicher Alhóndiga de Granaditas, in dem sich Spanier verschanzt hatten. Doch 1811 wurde Hidalgo gefangen genommen und hingerichtet; sein Kopf wurde zur Abschreckung an der Alhóndiga aufgehängt.',
        'Der Priester José María Morelos setzte den Kampf fort. 1813 forderte er auf dem Kongress von Chilpancingo in seinem Programm „Gefühle der Nation“ die Unabhängigkeit, die Abschaffung der Sklaverei und die Gleichheit aller. 1815 wurde auch er hingerichtet. Danach führte Vicente Guerrero einen Guerillakrieg in den Bergen des Südens.',
        '1820 wurde Spanien liberal, was die konservativen Criollos und die Kirche beunruhigte. Der Offizier Agustín de Iturbide, der zuvor gegen die Aufständischen gekämpft hatte, verbündete sich 1821 mit Guerrero. Im „Plan von Iguala“, den Kirche und Konservative unterstützten, versprachen sie Unabhängigkeit, katholischen Glauben und Gleichheit von Criollos und Peninsulares. Am 27. September 1821 zog ihr „Heer der drei Garantien“ in Mexiko-Stadt ein. Die drei Garantien spiegeln sich in den Farben der Flagge: Grün, Weiß und Rot.',
        '1822 ließ sich Iturbide zum Kaiser Agustín I. krönen, doch schon 1823 wurde er gestürzt. 1824 wurde Mexiko eine Bundesrepublik, und Guadalupe Victoria wurde erster Präsident. 1829 schaffte Präsident Vicente Guerrero, selbst teilweise afrikanischer Herkunft, die Sklaverei ab.',
      ],
      quiz: {
        leicht: [
          ['Welcher Priester begann 1810 den Unabhängigkeitskrieg?', 'Miguel Hidalgo', ['José María Morelos', 'Bartolomé de las Casas', 'Benito Juárez']],
          ['Wie heißt Hidalgos Ruf zum Aufstand?', 'Grito de Dolores', ['Plan von Iguala', 'Noche Triste', 'Cinco de Mayo']],
          ['Was bedeutet „Grito de Dolores“?', 'Ruf von Dolores', ['Schmerz der Nation', 'Glocke der Freiheit', 'Fest von Dolores']],
          ['Welcher Tag ist Mexikos Unabhängigkeitstag?', 'Der 16. September', ['Der 5. Mai', 'Der 4. Juli', 'Der 20. November']],
          ['Womit rief Hidalgo die Menschen zusammen?', 'Mit der Kirchenglocke', ['Mit einer Trompete', 'Mit Kanonen', 'Mit einem Brief']],
          ['Wer wiederholt den Ruf jedes Jahr?', 'Der Präsident', ['Der Papst', 'Der König von Spanien', 'Der Bürgermeister von Dolores']],
          ['Unter welchem Banner zog Hidalgos Heer?', 'Unter dem der Jungfrau von Guadalupe', ['Unter dem spanischen Wappen', 'Unter der US-Flagge', 'Unter dem Adler Napoleons']],
          ['Welches Gebäude stürmten die Aufständischen in Guanajuato?', 'Die Alhóndiga de Granaditas', ['Den Nationalpalast', 'Den Templo Mayor', 'Die Kathedrale']],
          ['Was geschah 1811 mit Hidalgo?', 'Er wurde hingerichtet', ['Er wurde Kaiser', 'Er floh nach Spanien', 'Er wurde Papst']],
          ['Wer setzte den Kampf nach Hidalgo fort?', 'José María Morelos', ['Agustín de Iturbide', 'Hernán Cortés', 'Porfirio Díaz']],
          ['Wie hieß das Programm von Morelos?', 'Gefühle der Nation', ['Plan von Iguala', 'Plan von Ayala', 'Grito de Dolores']],
          ['Was forderte Morelos?', 'Unabhängigkeit, Abschaffung der Sklaverei und Gleichheit', ['Die Rückkehr des Königs', 'Den Anschluss an die USA', 'Ein Kaiserreich']],
          ['Wer führte nach Morelos einen Guerillakrieg im Süden?', 'Vicente Guerrero', ['Agustín de Iturbide', 'Santa Anna', 'Pancho Villa']],
          ['Mit wem verbündete sich Iturbide 1821?', 'Mit Vicente Guerrero', ['Mit Hidalgo', 'Mit Napoleon', 'Mit Morelos']],
          ['Wie hieß der Plan von Iturbide und Guerrero?', 'Plan von Iguala', ['Plan von Ayala', 'Plan von San Luis', 'Gefühle der Nation']],
          ['Wann wurde Mexiko unabhängig?', '1821', ['1810', '1848', '1910']],
          ['Wie hieß das Heer, das 1821 in Mexiko-Stadt einzog?', 'Heer der drei Garantien', ['Rote Armee', 'Armee der Republik', 'Heer der Jungfrau']],
          ['Welche Farben hat die mexikanische Flagge?', 'Grün, Weiß und Rot', ['Blau, Weiß und Rot', 'Rot und Gold', 'Schwarz, Rot, Gold']],
          ['Wer ließ sich 1822 zum Kaiser krönen?', 'Agustín de Iturbide', ['Benito Juárez', 'Maximilian', 'Santa Anna']],
          ['Wann wurde Mexiko eine Bundesrepublik?', '1824', ['1821', '1810', '1867']],
        ],
        mittel: [
          ['Welches Ereignis in Europa ermutigte die Criollos 1808?', 'Napoleon besetzte Spanien', ['Die Entdeckung Amerikas', 'Der Wiener Kongress', 'Der Krimkrieg']],
          ['In welcher Nacht rief Hidalgo zum Aufstand?', 'In der Nacht zum 16. September 1810', ['Am 5. Mai 1862', 'Am 27. September 1821', 'Am 20. November 1910']],
          ['Von wo wiederholt der Präsident den Ruf?', 'Vom Balkon des Nationalpalastes', ['Von der Pyramide', 'Aus Dolores', 'Aus Madrid']],
          ['Woraus bestand Hidalgos Heer vor allem?', 'Aus Indigenen und Mestizen', ['Aus spanischen Soldaten', 'Aus Amerikanern', 'Aus Franzosen']],
          ['Was war die Alhóndiga de Granaditas?', 'Ein Getreidespeicher', ['Eine Kirche', 'Ein Palast', 'Ein Gefängnis']],
          ['Wer hatte sich in der Alhóndiga verschanzt?', 'Spanier', ['Azteken', 'Franzosen', 'Amerikaner']],
          ['Was geschah mit Hidalgos Kopf?', 'Er wurde an der Alhóndiga aufgehängt', ['Er wurde nach Spanien gebracht', 'Er wurde verbrannt', 'Er wurde in Dolores begraben']],
          ['Wann fand der Kongress von Chilpancingo statt?', '1813', ['1810', '1821', '1824']],
          ['Wann wurde Morelos hingerichtet?', '1815', ['1811', '1821', '1813']],
          ['Was war Morelos von Beruf?', 'Priester', ['General der Spanier', 'Kaufmann', 'Bauer']],
          ['Was geschah 1820 in Spanien?', 'Es wurde liberal', ['Es wurde kommunistisch', 'Es wurde von England besetzt', 'Es gab Amerika auf']],
          ['Wer war beunruhigt über das liberale Spanien?', 'Konservative Criollos und die Kirche', ['Die Indigenen', 'Die Sklaven', 'Die USA']],
          ['Gegen wen hatte Iturbide zuvor gekämpft?', 'Gegen die Aufständischen', ['Gegen Napoleon', 'Gegen die USA', 'Gegen die Azteken']],
          ['Was versprach der Plan von Iguala?', 'Unabhängigkeit, katholischen Glauben und Gleichheit von Criollos und Peninsulares', ['Die Rückkehr der Azteken', 'Die Abschaffung der Kirche', 'Den Anschluss an Spanien']],
          ['Wann zog das Heer der drei Garantien in Mexiko-Stadt ein?', 'Am 27. September 1821', ['Am 16. September 1810', 'Am 24. Februar 1821', 'Am 1. Januar 1824']],
          ['Wie lange regierte Kaiser Agustín I.?', 'Nur kurz, bis 1823', ['30 Jahre', 'Bis 1867', 'Er wurde nie gekrönt']],
          ['Wer wurde erster Präsident Mexikos?', 'Guadalupe Victoria', ['Benito Juárez', 'Vicente Guerrero', 'Santa Anna']],
          ['Wann schaffte Mexiko die Sklaverei ab?', '1829', ['1810', '1865', '1917']],
          ['Welcher Präsident schaffte die Sklaverei ab?', 'Vicente Guerrero', ['Guadalupe Victoria', 'Benito Juárez', 'Iturbide']],
          ['Welche Herkunft hatte Guerrero teilweise?', 'Afrikanische Herkunft', ['Spanischen Adel', 'Französische Herkunft', 'Deutsche Herkunft']],
        ],
        schwer: [
          ['Wie hieß Iturbide als Kaiser?', 'Agustín I.', ['Maximilian I.', 'Carlos I.', 'Fernando VII.']],
          ['Wofür stehen die drei Garantien?', 'Unabhängigkeit, katholischer Glaube und Gleichheit', ['Gold, Silber und Kakao', 'Freiheit, Gleichheit, Brüderlichkeit', 'König, Kirche und Armee']],
          ['Welche Stadt war Ort des Kongresses von 1813?', 'Chilpancingo', ['Dolores', 'Iguala', 'Querétaro']],
          ['Welche Stadt gab dem Plan von 1821 seinen Namen?', 'Iguala', ['Ayala', 'Dolores', 'Guadalajara']],
          ['Wann wurde Hidalgo hingerichtet?', '1811', ['1810', '1815', '1821']],
          ['Wann wurde Iturbide gestürzt?', '1823', ['1822', '1824', '1829']],
          ['Welches Symbol trug Hidalgos Heer?', 'Die Jungfrau von Guadalupe', ['Den Adler Napoleons', 'Das Kreuz der Templer', 'Ein Ahornblatt']],
          ['Wo liegt Dolores, wo der Aufstand begann?', 'Im Bundesstaat Guanajuato', ['In Yucatán', 'In Chiapas', 'In Sonora']],
          ['Welche Rolle spielte die Kirche 1821?', 'Sie unterstützte Iturbides Plan', ['Sie bekämpfte jede Unabhängigkeit', 'Sie wurde verboten', 'Sie war unbeteiligt']],
          ['Was war das Besondere an Vicente Guerrero als Präsident?', 'Er schaffte die Sklaverei ab', ['Er war Spanier', 'Er war der erste Kaiser', 'Er verkaufte Texas']],
          ['Wie lange dauerte der Unabhängigkeitskrieg?', 'Elf Jahre', ['Ein Jahr', 'Dreißig Jahre', 'Hundert Jahre']],
          ['Welche Staatsform wählte Mexiko 1824?', 'Bundesrepublik', ['Monarchie', 'Diktatur', 'Kolonie']],
          ['Welcher Teil des Landes war Guerreros Rückzugsgebiet?', 'Die Berge des Südens', ['Die Wüste im Norden', 'Die Halbinsel Yucatán', 'Die Inseln im Golf']],
          ['Was forderte Morelos für die Sklaverei?', 'Ihre Abschaffung', ['Ihre Ausweitung', 'Nichts', 'Ihre Übergabe an Spanien']],
          ['Welcher Ort ist mit dem Kopf Hidalgos verbunden?', 'Die Alhóndiga de Granaditas', ['Der Zócalo', 'Chapultepec', 'Teotihuacán']],
          ['Welche Gruppe gewann mit dem Plan von Iguala Gleichheit mit den Peninsulares?', 'Die Criollos', ['Die Indigenen', 'Die Sklaven', 'Die Franzosen']],
          ['Wann wurde Iturbide gekrönt?', '1822', ['1821', '1824', '1810']],
          ['Welcher Präsident war der erste der Republik?', 'Guadalupe Victoria', ['Agustín de Iturbide', 'Antonio López de Santa Anna', 'Valentín Gómez Farías']],
          ['Was ist der „Grito“ heute?', 'Ein jährliches Ritual am Unabhängigkeitstag', ['Ein Fußballspiel', 'Ein Tanz', 'Ein Gericht']],
          ['Welche Folge hatte Napoleons Besetzung Spaniens für Neuspanien?', 'Die Criollos dachten über Selbstbestimmung nach', ['Neuspanien wurde französisch', 'Die Azteken kehrten zurück', 'Nichts']],
        ],
      },
    },
  ],
};

export const JUAREZ: HistEvent = {
  id: 'juarez',
  title: 'Krieg mit den USA, Juárez und Maximilian',
  date: '1824–1876',
  text: [
    'Das junge Mexiko war politisch zerrissen. Es verlor Texas und im Krieg gegen die USA 1846–1848 die Hälfte seines Gebietes. Der indigene Präsident Benito Juárez setzte liberale Reformen durch und besiegte den von Frankreich eingesetzten Kaiser Maximilian.',
  ],
  subtopics: [
    {
      id: 'santa-anna-usa',
      title: 'Santa Anna, Texas und der Krieg gegen die USA',
      date: '1824–1853',
      text: [
        'Die ersten Jahrzehnte waren chaotisch: Liberale und Konservative, Anhänger eines Bundesstaates und eines Zentralstaates, stritten erbittert, und es gab Dutzende Regierungswechsel. Die prägende Figur war der General Antonio López de Santa Anna, der zwischen 1833 und 1855 elfmal Präsident wurde und mal liberal, mal konservativ regierte.',
        'In der Provinz Texas lebten immer mehr Siedler aus den USA, die sich gegen die Regierung in Mexiko-Stadt auflehnten, auch weil Mexiko die Sklaverei verboten hatte. 1836 erklärte Texas seine Unabhängigkeit. Santa Anna eroberte im März 1836 die Missionsstation Alamo, deren Verteidiger alle starben („Remember the Alamo!“). Im April wurde er jedoch bei San Jacinto geschlagen und gefangen genommen. 1845 nahmen die USA Texas auf.',
        'Im Streit um die Grenze begann 1846 der Mexikanisch-Amerikanische Krieg. US-Truppen landeten in Veracruz und eroberten 1847 Mexiko-Stadt. Beim Sturm auf das Schloss Chapultepec starben junge Kadetten, die „Niños Héroes“ („Kinderhelden“); einer soll sich in die Fahne gewickelt in die Tiefe gestürzt haben.',
        'Im Vertrag von Guadalupe Hidalgo 1848 musste Mexiko rund die Hälfte seines Gebietes abtreten: Kalifornien, Nevada, Utah, Arizona, New Mexico und Teile weiterer Staaten. Kurz darauf wurde in Kalifornien Gold gefunden. 1853 verkaufte Santa Anna im „Gadsden-Kauf“ noch einen Landstreifen an die USA.',
        'Am 5. Mai 1862 besiegte die mexikanische Armee bei Puebla ein französisches Heer. Daran erinnert der „Cinco de Mayo“, der in den USA heute größer gefeiert wird als in Mexiko selbst – er ist nicht der Unabhängigkeitstag.',
      ],
      quiz: {
        leicht: [
          ['Welcher General wurde elfmal Präsident?', 'Antonio López de Santa Anna', ['Benito Juárez', 'Porfirio Díaz', 'Pancho Villa']],
          ['Welche Provinz erklärte 1836 ihre Unabhängigkeit?', 'Texas', ['Kalifornien', 'Yucatán', 'Florida']],
          ['Woher kamen viele Siedler in Texas?', 'Aus den USA', ['Aus Spanien', 'Aus Kanada', 'Aus China']],
          ['Welche Missionsstation eroberte Santa Anna 1836?', 'Alamo', ['San Antonio de Padua', 'Santa Fe', 'San Diego']],
          ['Welcher Ruf erinnert an das Alamo?', '„Remember the Alamo!“', ['„Viva México!“', '„Go West!“', '„Yes we can!“']],
          ['Wo wurde Santa Anna im April 1836 geschlagen?', 'Bei San Jacinto', ['Bei Puebla', 'Bei Chapultepec', 'Bei Veracruz']],
          ['Wann nahmen die USA Texas auf?', '1845', ['1836', '1848', '1821']],
          ['Wann begann der Mexikanisch-Amerikanische Krieg?', '1846', ['1836', '1862', '1910']],
          ['Wann eroberten US-Truppen Mexiko-Stadt?', '1847', ['1846', '1848', '1862']],
          ['Wie heißen die jungen Kadetten, die in Chapultepec starben?', 'Niños Héroes', ['Los Charros', 'Los Zapatistas', 'Los Mariachis']],
          ['Welches Schloss stürmten die US-Truppen?', 'Chapultepec', ['Alamo', 'Versailles', 'Neuschwanstein']],
          ['Wie viel seines Gebietes verlor Mexiko 1848?', 'Rund die Hälfte', ['Ein Zehntel', 'Fast nichts', 'Alles']],
          ['Welcher Vertrag beendete 1848 den Krieg?', 'Der Vertrag von Guadalupe Hidalgo', ['Der Vertrag von Iguala', 'Der Vertrag von Paris', 'Der Vertrag von Versailles']],
          ['Welcher heutige US-Bundesstaat gehörte vor 1848 zu Mexiko?', 'Kalifornien', ['Florida', 'Alaska', 'Oregon']],
          ['Was wurde kurz nach 1848 in Kalifornien gefunden?', 'Gold', ['Öl', 'Diamanten', 'Kohle']],
          ['Wie heißt der Landverkauf von 1853?', 'Gadsden-Kauf', ['Louisiana-Kauf', 'Alaska-Kauf', 'Texas-Kauf']],
          ['Woran erinnert der Cinco de Mayo?', 'An einen Sieg über Frankreich bei Puebla', ['An die Unabhängigkeit', 'An die Revolution', 'An die Eroberung durch Spanien']],
          ['Ist der Cinco de Mayo Mexikos Unabhängigkeitstag?', 'Nein', ['Ja', 'Nur in Puebla', 'Nur in den USA']],
          ['Wo wird der Cinco de Mayo heute größer gefeiert?', 'In den USA', ['In Spanien', 'In Frankreich', 'In Kanada']],
          ['Wer stritt in den ersten Jahrzehnten erbittert?', 'Liberale und Konservative', ['Azteken und Maya', 'Franzosen und Engländer', 'Katholiken und Muslime']],
        ],
        mittel: [
          ['Wann war Santa Anna immer wieder Präsident?', 'Zwischen 1833 und 1855', ['Zwischen 1876 und 1911', 'Zwischen 1810 und 1821', 'Zwischen 1934 und 1940']],
          ['Wie regierte Santa Anna politisch?', 'Mal liberal, mal konservativ', ['Immer kommunistisch', 'Immer monarchistisch', 'Gar nicht']],
          ['Warum lehnten sich die Siedler in Texas unter anderem auf?', 'Mexiko hatte die Sklaverei verboten', ['Mexiko verbot Rinder', 'Mexiko erhob keine Steuern', 'Mexiko schenkte ihnen Land']],
          ['Wann eroberte Santa Anna das Alamo?', 'Im März 1836', ['Im April 1836', 'Im Mai 1862', 'Im September 1847']],
          ['Was geschah mit den Verteidigern des Alamo?', 'Sie starben alle', ['Sie flohen', 'Sie wurden freigelassen', 'Sie siegten']],
          ['Was geschah mit Santa Anna bei San Jacinto?', 'Er wurde geschlagen und gefangen', ['Er siegte', 'Er wurde Präsident der USA', 'Er fiel']],
          ['Worum stritten Mexiko und die USA 1846?', 'Um die Grenze', ['Um Kanada', 'Um Kuba', 'Um Gold in Alaska']],
          ['Wo landeten US-Truppen im Krieg?', 'In Veracruz', ['In Acapulco', 'In Yucatán', 'In Baja California']],
          ['Was soll einer der Niños Héroes getan haben?', 'Sich in die Fahne gewickelt in die Tiefe gestürzt', ['Den US-General gefangen', 'Die Stadt verraten', 'Den Frieden unterzeichnet']],
          ['Welche Gebiete verlor Mexiko 1848 unter anderem?', 'Kalifornien, Nevada, Utah, Arizona und New Mexico', ['Alaska und Hawaii', 'Florida und Louisiana', 'Kuba und Puerto Rico']],
          ['Wann fand der Gadsden-Kauf statt?', '1853', ['1848', '1845', '1862']],
          ['Wer verkaufte 1853 Land an die USA?', 'Santa Anna', ['Juárez', 'Iturbide', 'Díaz']],
          ['An welchem Datum war die Schlacht von Puebla?', 'Am 5. Mai 1862', ['Am 16. September 1810', 'Am 5. Mai 1848', 'Am 20. November 1910']],
          ['Gegen welche Macht siegte Mexiko 1862 bei Puebla?', 'Gegen Frankreich', ['Gegen Spanien', 'Gegen die USA', 'Gegen England']],
          ['Wie viele Regierungswechsel gab es in den ersten Jahrzehnten?', 'Dutzende', ['Keinen', 'Einen', 'Zwei']],
          ['Wann endete der Krieg mit den USA?', '1848', ['1846', '1853', '1836']],
          ['Was wollte ein Teil der Politiker statt eines Bundesstaates?', 'Einen Zentralstaat', ['Eine Monarchie unter Spanien', 'Den Anschluss an die USA', 'Eine Teilung in Stadtstaaten']],
          ['Welche Stadt ist mit dem Cinco de Mayo verbunden?', 'Puebla', ['Veracruz', 'Guadalajara', 'Monterrey']],
          ['Was erinnert an den Mut junger Kadetten 1847?', 'Die Niños Héroes', ['Der Grito', 'Der Plan von Iguala', 'Das Alamo']],
          ['Welche Folge hatte der Goldfund in Kalifornien für Mexiko?', 'Das Gold kam den USA zugute', ['Mexiko wurde reich', 'Mexiko eroberte Kalifornien zurück', 'Keine, da Kalifornien mexikanisch blieb']],
        ],
        schwer: [
          ['Wie oft wurde Santa Anna Präsident?', 'Elfmal', ['Zweimal', 'Einmal', 'Zwanzigmal']],
          ['Welche Schlacht folgte im April 1836 auf das Alamo?', 'San Jacinto', ['Gettysburg', 'Chapultepec', 'Puebla']],
          ['Welcher Vertrag ist nach einem Ort bei der Basilika benannt?', 'Guadalupe Hidalgo', ['Iguala', 'Querétaro', 'Córdoba']],
          ['Wie viel Gebiet verlor Mexiko insgesamt an die USA bis 1853?', 'Rund die Hälfte', ['Ein Viertel', 'Ein Zehntel', 'Drei Viertel']],
          ['Wann trat Texas den USA bei?', '1845', ['1836', '1848', '1853']],
          ['Welches Schloss in Mexiko-Stadt ist mit den Niños Héroes verbunden?', 'Chapultepec', ['Palacio Nacional', 'Castillo de San Juan de Ulúa', 'Palacio de Bellas Artes']],
          ['Welcher heutige US-Staat lag ebenfalls im 1848 abgetretenen Gebiet?', 'Nevada', ['Oregon', 'Washington', 'Montana']],
          ['Wer siegte bei San Jacinto?', 'Die Texaner', ['Santa Anna', 'Die Franzosen', 'Die Spanier']],
          ['Warum ist der Cinco de Mayo kein Unabhängigkeitstag?', 'Er erinnert an eine Schlacht gegen Frankreich', ['Er erinnert an Kolumbus', 'Er ist ein Erntefest', 'Er ist der Tag der Revolution']],
          ['Welche Stadt eroberten US-Truppen 1847?', 'Mexiko-Stadt', ['Puebla', 'Guadalajara', 'Tijuana']],
          ['Welcher Kauf ergänzte 1853 die Gebietsverluste?', 'Der Gadsden-Kauf', ['Der Louisiana-Kauf', 'Der Alaska-Kauf', 'Der Florida-Kauf']],
          ['Welche Einstellung hatte Mexiko zur Sklaverei, die Texaner störte?', 'Es hatte sie verboten', ['Es hatte sie erlaubt', 'Es hatte sie erfunden', 'Es war gleichgültig']],
          ['Wie nennt man die Kadetten von 1847 auf Deutsch?', 'Kinderhelden', ['Grenzwächter', 'Adlerkrieger', 'Freiheitssöhne']],
          ['Welches Ereignis brachte den USA kurz nach 1848 großen Reichtum?', 'Der Goldrausch in Kalifornien', ['Ein Ölfund in Texas', 'Der Bau des Panamakanals', 'Die Eisenbahn nach Mexiko']],
          ['Welches Problem prägte Mexiko nach 1824?', 'Politisches Chaos', ['Völlige Stabilität', 'Eine lange Monarchie', 'Wirtschaftlicher Überfluss']],
          ['Was war das Alamo ursprünglich?', 'Eine Missionsstation', ['Ein Fort der Azteken', 'Ein Palast', 'Ein Hafen']],
          ['Wo liegt das Alamo heute?', 'In Texas', ['In Mexiko-Stadt', 'In Kalifornien', 'In Puebla']],
          ['Welche Armee siegte 1862 bei Puebla?', 'Die mexikanische', ['Die französische', 'Die amerikanische', 'Die spanische']],
          ['Welche Staatsform stritt mit dem Bundesstaat?', 'Der Zentralstaat', ['Die Monarchie', 'Der Kommunismus', 'Die Theokratie']],
          ['Wer war der wichtigste General der ersten Republik?', 'Santa Anna', ['Juárez', 'Díaz', 'Iturbide']],
        ],
      },
    },
    {
      id: 'juarez-maximilian',
      title: 'Benito Juárez und Kaiser Maximilian',
      date: '1855–1876',
      text: [
        'Benito Juárez (1806–1872) war ein Zapoteke aus Oaxaca, der als Kind Schafe hütete und erst mit zwölf Jahren Spanisch lernte. Er wurde Anwalt, Gouverneur und schließlich Präsident – der erste indigene Präsident Mexikos. Sein berühmter Satz lautet: „Die Achtung vor dem Recht des anderen ist der Frieden.“',
        'Die Liberalen setzten in der „Reforma“ Gesetze durch, die die Macht der Kirche und des Militärs beschränkten: Kirchenbesitz wurde verkauft, Ehe und Geburten wurden staatlich registriert. Die Verfassung von 1857 garantierte Grundrechte. Die Konservativen wehrten sich im „Reformkrieg“ (1858–1861), den die Liberalen gewannen.',
        'Als Juárez 1861 die Rückzahlung von Auslandsschulden aussetzte, griff Frankreich unter Napoleon III. ein. Trotz der Niederlage bei Puebla 1862 eroberten die Franzosen 1863 Mexiko-Stadt. 1864 setzten sie den österreichischen Erzherzog Maximilian, den jüngeren Bruder Kaiser Franz Josephs, als Kaiser von Mexiko ein; er kam mit seiner Frau Charlotte (Carlota).',
        'Maximilian wollte ein guter Herrscher sein und verärgerte die Konservativen sogar mit liberalen Ideen, doch die meisten Mexikaner sahen in ihm einen Fremden. Juárez führte den Widerstand von Norden aus weiter. Als die USA nach ihrem Bürgerkrieg Druck machten, zog Frankreich 1866/67 seine Truppen ab. Charlotte reiste nach Europa, um Hilfe zu holen, und erkrankte psychisch.',
        'Maximilian wurde in Querétaro gefangen und am 19. Juni 1867 erschossen. Juárez kehrte als Präsident zurück und regierte bis zu seinem Tod 1872. Die Zeit nach 1867 nennt man „Restaurierte Republik“. Juárez gilt bis heute als einer der größten Helden Mexikos.',
      ],
      quiz: {
        leicht: [
          ['Wer war der erste indigene Präsident Mexikos?', 'Benito Juárez', ['Porfirio Díaz', 'Santa Anna', 'Vicente Guerrero']],
          ['Zu welchem Volk gehörte Juárez?', 'Zu den Zapoteken', ['Zu den Maya', 'Zu den Azteken', 'Zu den Olmeken']],
          ['Aus welcher Region stammte Juárez?', 'Aus Oaxaca', ['Aus Yucatán', 'Aus Sonora', 'Aus Texas']],
          ['Was tat Juárez als Kind?', 'Er hütete Schafe', ['Er war Soldat', 'Er war Prinz', 'Er war Seefahrer']],
          ['Mit wie vielen Jahren lernte Juárez Spanisch?', 'Mit zwölf', ['Mit zwei', 'Mit dreißig', 'Nie']],
          ['Welcher Satz stammt von Juárez?', '„Die Achtung vor dem Recht des anderen ist der Frieden.“', ['„Ich bin der Staat.“', '„Freiheit oder Tod.“', '„Land und Freiheit.“']],
          ['Wie heißen die liberalen Reformen?', 'Reforma', ['Tanzimat', 'Perestroika', 'Reconquista']],
          ['Wessen Macht beschränkte die Reforma?', 'Die Macht der Kirche und des Militärs', ['Die Macht der Indigenen', 'Die Macht der Bauern', 'Die Macht der USA']],
          ['Wann trat die liberale Verfassung in Kraft?', '1857', ['1824', '1917', '1810']],
          ['Welches Land griff 1861 in Mexiko ein?', 'Frankreich', ['Spanien', 'Deutschland', 'Russland']],
          ['Welcher französische Herrscher griff ein?', 'Napoleon III.', ['Napoleon I.', 'Ludwig XIV.', 'Charles de Gaulle']],
          ['Wer wurde 1864 Kaiser von Mexiko?', 'Maximilian', ['Iturbide', 'Napoleon III.', 'Franz Joseph']],
          ['Woher stammte Maximilian?', 'Aus Österreich', ['Aus Frankreich', 'Aus Spanien', 'Aus Preußen']],
          ['Wessen Bruder war Maximilian?', 'Kaiser Franz Josephs', ['Napoleons III.', 'Königin Victorias', 'Bismarcks']],
          ['Wie hieß Maximilians Frau?', 'Charlotte (Carlota)', ['Sisi', 'Eugénie', 'Maria Theresia']],
          ['Wie sahen die meisten Mexikaner Maximilian?', 'Als Fremden', ['Als Helden', 'Als Azteken', 'Als Befreier']],
          ['Wo wurde Maximilian gefangen?', 'In Querétaro', ['In Mexiko-Stadt', 'In Veracruz', 'In Puebla']],
          ['Wann wurde Maximilian erschossen?', 'Am 19. Juni 1867', ['Am 5. Mai 1862', 'Am 16. September 1867', 'Am 20. November 1910']],
          ['Als was gilt Juárez heute?', 'Als einer der größten Helden Mexikos', ['Als Verräter', 'Als Franzose', 'Als Kaiser']],
          ['Wann starb Juárez?', '1872', ['1867', '1810', '1910']],
        ],
        mittel: [
          ['Wann lebte Benito Juárez?', '1806–1872', ['1753–1811', '1830–1915', '1879–1919']],
          ['Welche Ämter hatte Juárez vor der Präsidentschaft?', 'Anwalt und Gouverneur', ['General und Bischof', 'Kaufmann und Bankier', 'Lehrer und Dichter']],
          ['Was geschah in der Reforma mit Kirchenbesitz?', 'Er wurde verkauft', ['Er wurde vergrößert', 'Er wurde den Indigenen geschenkt', 'Nichts']],
          ['Was wurde in der Reforma staatlich registriert?', 'Ehe und Geburten', ['Nur Häuser', 'Nur Pferde', 'Gar nichts']],
          ['Was garantierte die Verfassung von 1857?', 'Grundrechte', ['Die Monarchie', 'Die Macht der Kirche', 'Die Sklaverei']],
          ['Wie hieß der Krieg der Konservativen gegen die Reformen?', 'Reformkrieg', ['Kastenkrieg', 'Krieg der Pasteten', 'Cristero-Krieg']],
          ['Wann dauerte der Reformkrieg?', '1858–1861', ['1846–1848', '1910–1920', '1862–1867']],
          ['Wer gewann den Reformkrieg?', 'Die Liberalen', ['Die Konservativen', 'Die Franzosen', 'Die Spanier']],
          ['Was setzte Juárez 1861 aus?', 'Die Rückzahlung von Auslandsschulden', ['Die Wahlen', 'Die Verfassung', 'Den Kirchenbesitz']],
          ['Wann eroberten die Franzosen Mexiko-Stadt?', '1863', ['1862', '1867', '1861']],
          ['Wann wurde Maximilian Kaiser?', '1864', ['1862', '1867', '1860']],
          ['Womit verärgerte Maximilian die Konservativen?', 'Mit liberalen Ideen', ['Mit Grausamkeit', 'Mit Steuern auf Kakao', 'Mit dem Verkauf Mexikos']],
          ['Von wo führte Juárez den Widerstand?', 'Von Norden aus', ['Aus Paris', 'Aus Yucatán', 'Aus Kuba']],
          ['Welches Land machte nach seinem Bürgerkrieg Druck auf Frankreich?', 'Die USA', ['Großbritannien', 'Spanien', 'Russland']],
          ['Wann zog Frankreich seine Truppen ab?', '1866/67', ['1862', '1864', '1872']],
          ['Warum reiste Charlotte nach Europa?', 'Um Hilfe zu holen', ['Um sich scheiden zu lassen', 'Um Urlaub zu machen', 'Um Österreich zu regieren']],
          ['Was geschah mit Charlotte in Europa?', 'Sie erkrankte psychisch', ['Sie wurde Kaiserin von Frankreich', 'Sie kehrte siegreich zurück', 'Sie starb sofort']],
          ['Bis wann regierte Juárez nach 1867?', 'Bis zu seinem Tod 1872', ['Bis 1910', 'Bis 1867', 'Bis 1876 als Kaiser']],
          ['Wie nennt man die Zeit nach 1867?', 'Restaurierte Republik', ['Porfiriat', 'Zweites Kaiserreich', 'Reforma']],
          ['Welche Stadt ist mit Maximilians Ende verbunden?', 'Querétaro', ['Oaxaca', 'Veracruz', 'Mérida']],
        ],
        schwer: [
          ['Welche Gruppe bekämpfte Juárez im Reformkrieg?', 'Die Konservativen', ['Die Franzosen zuerst', 'Die USA', 'Die Indigenen']],
          ['Welche Verfassung verteidigte Juárez?', 'Die Verfassung von 1857', ['Die Verfassung von 1824', 'Die Verfassung von 1917', 'Die Verfassung von Cádiz']],
          ['Welcher Österreicher war Maximilians Bruder?', 'Franz Joseph', ['Karl I.', 'Rudolf', 'Ferdinand I.']],
          ['Wann wurde Maximilian hingerichtet?', '1867', ['1864', '1872', '1862']],
          ['Welcher Krieg in den USA beeinflusste Frankreichs Abzug?', 'Der Amerikanische Bürgerkrieg', ['Der Unabhängigkeitskrieg', 'Der Krieg von 1812', 'Der Spanisch-Amerikanische Krieg']],
          ['Wie hieß Charlotte auf Spanisch?', 'Carlota', ['Carolina', 'Catalina', 'Clara']],
          ['Was war das Ziel der Reforma?', 'Kirche und Militär zu entmachten', ['Die Kirche zu stärken', 'Spanien zurückzuholen', 'Die Azteken zu ehren']],
          ['Was löste die französische Intervention aus?', 'Das Aussetzen der Schuldenzahlungen', ['Ein Mord an Franzosen', 'Der Cinco de Mayo', 'Ein Erbstreit']],
          ['Welche Sprache lernte Juárez erst mit zwölf Jahren?', 'Spanisch', ['Zapotekisch', 'Französisch', 'Nahuatl']],
          ['Was verkaufte der Staat in der Reforma?', 'Kirchenbesitz', ['Silberminen an Spanien', 'Kalifornien', 'Eisenbahnen']],
          ['Wie lange regierte Maximilian etwa?', 'Rund drei Jahre', ['Rund dreißig Jahre', 'Einen Monat', 'Zehn Jahre']],
          ['Welche Rolle spielte Napoleon III.?', 'Er setzte Maximilian ein', ['Er bekämpfte Maximilian', 'Er war Mexikos Präsident', 'Er schützte Juárez']],
          ['Wann wurde Juárez geboren?', '1806', ['1810', '1821', '1790']],
          ['Welchen Status hatte Maximilian vorher?', 'Österreichischer Erzherzog', ['Französischer General', 'Spanischer König', 'Deutscher Kaiser']],
          ['Was zeigte Juárez’ Leben?', 'Den Aufstieg eines indigenen Hirtenjungen zum Präsidenten', ['Die Herrschaft der Peninsulares', 'Die Rückkehr der Azteken', 'Den Sieg der Konservativen']],
          ['Welche Verfassung garantierte Grundrechte im 19. Jahrhundert?', 'Die von 1857', ['Die von 1824', 'Die von 1836', 'Die von 1917']],
          ['Welcher Ort war Juárez’ Heimat?', 'Oaxaca', ['Chihuahua', 'Puebla', 'Jalisco']],
          ['Was bedeutet „Restaurierte Republik“?', 'Die wiederhergestellte Republik nach Maximilian', ['Die Zeit unter Díaz', 'Die erste Republik von 1824', 'Die Zeit der Azteken']],
          ['Wofür steht Juárez’ berühmter Satz?', 'Für Achtung und Frieden zwischen Völkern', ['Für Krieg', 'Für die Monarchie', 'Für die Kirche']],
          ['Wo sammelte Juárez seine Kräfte gegen die Franzosen?', 'Im Norden', ['Im Süden', 'In Europa', 'In Kuba']],
        ],
      },
    },
  ],
};
