import type { Lang } from '../lang';
import type { Gloss } from './types';

// Little words (articles, prepositions, pronouns, conjunctions …) for
// tap-to-translate. Many aren't in the vocabulary catalog, or only as part of a
// phrase. Keys are lowercase, elided forms keep their apostrophe.

const IT: Record<string, Gloss> = {
  // articles
  il: 'der (Artikel, m)', lo: 'der (Artikel, m) / ihn, es', la: 'die (Artikel, f) / sie, es', "l'": 'der/die/das (vor Vokal)',
  i: 'die (Artikel, m Mz.)', gli: 'die (Artikel, m Mz.) / ihm, ihnen', le: 'die (Artikel, f Mz.) / ihr, sie',
  un: 'ein', uno: 'ein / eins', una: 'eine', "un'": 'eine (vor Vokal)',
  // prepositions + article
  di: 'von, aus', a: 'zu, in, nach, an', da: 'von, bei, seit', in: 'in', con: 'mit', su: 'auf, über', per: 'für, durch, um zu',
  tra: 'zwischen, in (zeitlich)', fra: 'zwischen, in (zeitlich)',
  del: 'des, vom (di + il)', dello: 'des (di + lo)', della: 'der, von der (di + la)', "dell'": 'des, der (di + l’)',
  dei: 'der, von den (di + i)', degli: 'der, von den (di + gli)', delle: 'der, von den (di + le)',
  al: 'zum, am, im (a + il)', allo: 'zum (a + lo)', alla: 'zur, an der (a + la)', "all'": 'zum, zur (a + l’)',
  ai: 'zu den (a + i)', agli: 'zu den (a + gli)', alle: 'zu den, um (a + le)',
  dal: 'vom, beim (da + il)', dallo: 'vom (da + lo)', dalla: 'von der, bei der (da + la)', "dall'": 'vom, von der (da + l’)',
  dai: 'von den, bei den (da + i)', dagli: 'von den (da + gli)', dalle: 'von den (da + le)',
  nel: 'im (in + il)', nello: 'im (in + lo)', nella: 'in der (in + la)', "nell'": 'im, in der (in + l’)',
  nei: 'in den (in + i)', negli: 'in den (in + gli)', nelle: 'in den (in + le)',
  sul: 'auf dem (su + il)', sullo: 'auf dem (su + lo)', sulla: 'auf der (su + la)', "sull'": 'auf dem/der (su + l’)',
  sui: 'auf den (su + i)', sugli: 'auf den (su + gli)', sulle: 'auf den (su + le)',
  // pronouns
  io: 'ich', tu: 'du', lui: 'er', lei: 'sie / Sie', noi: 'wir', voi: 'ihr', loro: 'sie (Mz.) / ihr(e)',
  mi: 'mir, mich', ti: 'dir, dich', si: 'sich / man', ci: 'uns / dort, da', vi: 'euch', ne: 'davon, darüber',
  me: 'mich, mir (betont)', te: 'dich, dir (betont)', sé: 'sich (betont)',
  "m'": 'mir, mich (vor Vokal)', "t'": 'dir, dich (vor Vokal)', "c'": 'es (c’è = es gibt)', "s'": 'sich (vor Vokal)',
  che: 'dass / der, die, das / was', chi: 'wer', cui: 'dem, der (nach Präposition)', cosa: 'was', quale: 'welche(r)', qual: 'welche(r)',
  mio: 'mein', mia: 'meine', miei: 'meine (m Mz.)', mie: 'meine (f Mz.)', tuo: 'dein', tua: 'deine', tuoi: 'deine', tue: 'deine',
  suo: 'sein, ihr', sua: 'seine, ihre', suoi: 'seine, ihre', sue: 'seine, ihre',
  nostro: 'unser', nostra: 'unsere', nostri: 'unsere', nostre: 'unsere', vostro: 'euer', vostra: 'eure', vostri: 'eure', vostre: 'eure',
  questo: 'dieser, das hier', questa: 'diese', questi: 'diese (m Mz.)', queste: 'diese (f Mz.)', "quest'": 'diese(r) (vor Vokal)',
  quello: 'jener, das da', quella: 'jene', quelli: 'jene', quelle: 'jene', quel: 'jener', quei: 'jene', quegli: 'jene', "quell'": 'jene(r)',
  // conjunctions & adverbs
  e: 'und', ed: 'und (vor Vokal)', o: 'oder', ma: 'aber', però: 'aber, jedoch', perché: 'weil / warum', quando: 'wenn, als / wann',
  se: 'wenn, falls / ob', come: 'wie / als', mentre: 'während', anche: 'auch', non: 'nicht', no: 'nein', sì: 'ja',
  più: 'mehr / am meisten', meno: 'weniger', molto: 'sehr / viel', poco: 'wenig', tanto: 'so viel, sehr', troppo: 'zu viel, zu',
  già: 'schon', ancora: 'noch', mai: 'nie / jemals', sempre: 'immer', spesso: 'oft', subito: 'sofort', poi: 'dann, danach',
  prima: 'vorher, zuerst', dopo: 'nach, danach', ora: 'jetzt', adesso: 'jetzt', oggi: 'heute', ieri: 'gestern', domani: 'morgen',
  qui: 'hier', qua: 'hier', lì: 'dort', là: 'dort', dove: 'wo, wohin', così: 'so', allora: 'also, dann', quindi: 'also, deshalb',
  anzi: 'im Gegenteil, sogar', insieme: 'zusammen', solo: 'nur / allein', tutto: 'alles / ganz', tutti: 'alle', tutta: 'ganz',
  tutte: 'alle', niente: 'nichts', nulla: 'nichts', nessuno: 'niemand / kein', qualcosa: 'etwas', qualcuno: 'jemand',
  ogni: 'jede(r)', altro: 'andere(r)', altra: 'andere', altri: 'andere', altre: 'andere', stesso: 'selbe(r) / selbst',
  po: 'bisschen', "po'": 'bisschen (un po’ = ein bisschen)', "c'è": 'es gibt, ist da', "com'è": 'wie ist', "dov'è": 'wo ist',
  "cos'è": 'was ist', "qual'è": 'welche(r) ist', "d'accordo": 'einverstanden', "d'estate": 'im Sommer', "d'inverno": 'im Winter',
  "dell'anno": 'des Jahres', ecco: 'hier ist, da ist', ciao: 'hallo, tschüss', grazie: 'danke', prego: 'bitte',
  signora: 'Frau (Anrede)', signore: 'Herr', signor: 'Herr (vor Namen)',
  favore: 'Gefallen (per favore = bitte)', euro: 'Euro', fino: 'bis (fino a)', qualche: 'einige, ein paar', mal: 'Schmerz (mal di …)',
  meglio: 'besser', peggio: 'schlechter', benissimo: 'sehr gut', buon: 'gut (vor Nomen)', bel: 'schön (vor Nomen)',
  dover: 'müssen (verkürzt)', poter: 'können (verkürzt)', voler: 'wollen (verkürzt)', aver: 'haben (verkürzt)', esser: 'sein (verkürzt)',
  alcuni: 'einige', alcune: 'einige', alcuna: 'irgendeine', maggiore: 'größer, älter', minore: 'kleiner, jünger',
  mamma: 'Mama', papà: 'Papa', pizza: 'Pizza', spaghetti: 'Spaghetti', posto: 'Platz, Ort', banco: 'Theke, Tresen / Bank',
  fossi: ['ich wäre (congiuntivo imperfetto)', 'essere'], fosse: ['er/sie wäre', 'essere'], avessi: ['ich hätte (congiuntivo imperfetto)', 'avere'],
  avesse: ['er/sie hätte', 'avere'], piove: ['es regnet', 'piovere'], piovuto: ['geregnet', 'piovere'], pioveva: ['es regnete', 'piovere'],
  milano: 'Mailand', firenze: 'Florenz', napoli: 'Neapel', venezia: 'Venedig', torino: 'Turin', sicilia: 'Sizilien', italia: 'Italien',
  germania: 'Deutschland', vicino: 'nahe (vicino a = in der Nähe von) / Nachbar', volte: ['Male (a volte = manchmal)', 'volta'],
  "vent'": 'zwanzig (vor Vokal)', "sant'": 'heilig (vor Vokal)', "quant'": 'wie viel (vor Vokal)',
};

const ES: Record<string, Gloss> = {
  el: 'der (Artikel, m)', la: 'die (Artikel, f) / sie, es', los: 'die (m Mz.) / sie', las: 'die (f Mz.) / sie',
  un: 'ein', una: 'eine', unos: 'einige', unas: 'einige', lo: 'es, ihn / das',
  de: 'von, aus', del: 'des, vom (de + el)', a: 'zu, nach, an', al: 'zum, am (a + el)', en: 'in, auf', con: 'mit',
  por: 'durch, wegen, für', para: 'für, um zu', sin: 'ohne', sobre: 'über, auf', entre: 'zwischen', hasta: 'bis', desde: 'seit, von',
  hacia: 'nach, gegen', durante: 'während',
  yo: 'ich', tú: 'du', él: 'er', ella: 'sie', usted: 'Sie', nosotros: 'wir', nosotras: 'wir (f)', vosotros: 'ihr', ellos: 'sie (Mz.)',
  ellas: 'sie (f Mz.)', ustedes: 'Sie (Mz.)', me: 'mir, mich', te: 'dir, dich', se: 'sich / man', nos: 'uns', os: 'euch',
  le: 'ihm, ihr', les: 'ihnen', mí: 'mir, mich (betont)', ti: 'dir, dich (betont)',
  que: 'dass / der, die, das', qué: 'was / welche', quién: 'wer', cuál: 'welche(r)', cuándo: 'wann', dónde: 'wo', cómo: 'wie',
  cuánto: 'wie viel', cuántos: 'wie viele', porque: 'weil', 'por qué': 'warum',
  mi: 'mein(e)', mis: 'meine', tu: 'dein(e)', tus: 'deine', su: 'sein(e), ihr(e)', sus: 'seine, ihre', nuestro: 'unser',
  nuestra: 'unsere', nuestros: 'unsere', nuestras: 'unsere', vuestro: 'euer', vuestra: 'eure',
  este: 'dieser', esta: 'diese', estos: 'diese', estas: 'diese', esto: 'das hier', ese: 'jener', esa: 'jene', eso: 'das da',
  esos: 'jene', esas: 'jene', aquel: 'jener (dort)', aquella: 'jene (dort)',
  y: 'und', e: 'und (vor i-)', o: 'oder', u: 'oder (vor o-)', pero: 'aber', sino: 'sondern', si: 'wenn, ob', sí: 'ja',
  no: 'nein / nicht', como: 'wie / da', cuando: 'wenn, als', mientras: 'während', también: 'auch', tampoco: 'auch nicht',
  muy: 'sehr', mucho: 'viel', mucha: 'viel', muchos: 'viele', muchas: 'viele', poco: 'wenig', más: 'mehr', menos: 'weniger',
  ya: 'schon', todavía: 'noch', aún: 'noch', nunca: 'nie', siempre: 'immer', luego: 'dann, später', después: 'danach',
  antes: 'vorher', ahora: 'jetzt', hoy: 'heute', ayer: 'gestern', mañana: 'morgen / Morgen', aquí: 'hier', allí: 'dort',
  así: 'so', entonces: 'dann, also', todo: 'alles / ganz', todos: 'alle', toda: 'ganz', todas: 'alle', nada: 'nichts',
  nadie: 'niemand', algo: 'etwas', alguien: 'jemand', cada: 'jede(r)', otro: 'andere(r)', otra: 'andere', otros: 'andere',
  hay: 'es gibt', gracias: 'danke', hola: 'hallo',
  veces: ['Male (a veces = manchmal)', 'vez'], vez: 'Mal', tan: 'so', ni: 'nicht einmal / weder … noch', siquiera: 'wenigstens (ni siquiera = nicht einmal)',
  según: 'laut, gemäß', mismo: 'selbe(r) / selbst', misma: 'selbe / selbst', mismos: 'selben', quienes: 'die, welche (Mz.) / wer',
  ninguna: 'keine (de ninguna manera = auf keinen Fall)', ninguno: 'keiner', ningún: 'kein', algún: 'irgendein', alguna: 'irgendeine',
  algunos: 'einige', algunas: 'einige', euros: 'Euro', llueve: ['es regnet', 'llover'], llovió: ['es regnete', 'llover'],
  llovía: ['es regnete', 'llover'], duele: ['tut weh (doler)', 'doler'], duelen: ['tun weh', 'doler'], tuviera: ['ich hätte (subjuntivo imperfecto)', 'tener'],
  fuera: ['ich wäre (subjuntivo imperfecto) / draußen', 'ser'], sevilla: 'Sevilla', españa: 'Spanien', alemania: 'Deutschland',
  madrid: 'Madrid', europa: 'Europa',
  he: ['habe (Hilfsverb haber)', 'haber'], has: ['hast (Hilfsverb haber)', 'haber'], ha: ['hat (Hilfsverb haber)', 'haber'],
  hemos: ['haben (Hilfsverb haber)', 'haber'], habéis: ['habt (Hilfsverb haber)', 'haber'], han: ['haben (Hilfsverb haber)', 'haber'],
  había: ['hatte / es gab', 'haber'], habían: ['hatten', 'haber'], embargo: 'sin embargo = jedoch', acuerdo: 'Einverständnis (de acuerdo = einverstanden)',
  pesar: 'a pesar de = trotz', llama: ['heißt (llamarse) / ruft an', 'llamarse'],
};

const FR: Record<string, Gloss> = {
  le: 'der (Artikel, m) / ihn, es', la: 'die (Artikel, f) / sie, es', "l'": 'der/die/das (vor Vokal)', les: 'die (Mz.) / sie',
  un: 'ein', une: 'eine', des: 'einige / von den', du: 'vom / etwas (Teilungsartikel)', "d'": 'von (vor Vokal)',
  au: 'zum, am, im (à + le)', aux: 'zu den (à + les)', de: 'von, aus', à: 'zu, in, nach, an', en: 'in / davon', dans: 'in',
  avec: 'mit', pour: 'für, um zu', par: 'durch, von', sur: 'auf, über', sous: 'unter', chez: 'bei', sans: 'ohne',
  entre: 'zwischen', depuis: 'seit', pendant: 'während', vers: 'gegen, in Richtung', après: 'nach', avant: 'vor',
  je: 'ich', "j'": 'ich (vor Vokal)', tu: 'du', il: 'er / es', elle: 'sie', on: 'man / wir', nous: 'wir / uns', vous: 'ihr / Sie / euch',
  ils: 'sie (m Mz.)', elles: 'sie (f Mz.)', me: 'mir, mich', "m'": 'mir, mich (vor Vokal)', te: 'dir, dich', "t'": 'dir, dich (vor Vokal)',
  se: 'sich', "s'": 'sich (vor Vokal)', lui: 'ihm, ihr / er (betont)', leur: 'ihnen / ihr(e)', leurs: 'ihre', y: 'dort, dahin, daran',
  moi: 'ich, mich (betont)', toi: 'du, dich (betont)', eux: 'sie (betont)',
  que: 'dass / den, die, das / was', "qu'": 'dass (vor Vokal)', qui: 'wer / der, die, das', quoi: 'was', quel: 'welcher',
  quelle: 'welche', quels: 'welche', quelles: 'welche', où: 'wo, wohin', quand: 'wann / wenn, als', comment: 'wie',
  pourquoi: 'warum', combien: 'wie viel', parce: 'weil (parce que)',
  mon: 'mein', ma: 'meine', mes: 'meine', ton: 'dein', ta: 'deine', tes: 'deine', son: 'sein, ihr', sa: 'seine, ihre',
  ses: 'seine, ihre', notre: 'unser(e)', nos: 'unsere', votre: 'euer, Ihr', vos: 'eure, Ihre',
  ce: 'dieser / das', cet: 'dieser (vor Vokal)', cette: 'diese', ces: 'diese', "c'": 'das, es (vor Vokal)', "c'est": 'das ist, es ist',
  ça: 'das', cela: 'das',
  et: 'und', ou: 'oder', mais: 'aber', donc: 'also', si: 'wenn, ob / so', comme: 'wie / da', car: 'denn', puis: 'dann',
  ne: 'nicht (ne … pas)', "n'": 'nicht (vor Vokal)', pas: 'nicht', plus: 'mehr / nicht mehr', jamais: 'nie', rien: 'nichts',
  personne: 'niemand / Person', oui: 'ja', non: 'nein', aussi: 'auch', très: 'sehr', trop: 'zu, zu viel', beaucoup: 'viel, sehr',
  peu: 'wenig', déjà: 'schon', encore: 'noch', toujours: 'immer', souvent: 'oft', ensuite: 'danach', alors: 'also, dann',
  maintenant: 'jetzt', aujourd: 'heute (aujourd’hui)', "aujourd'hui": 'heute', hier: 'gestern', demain: 'morgen', ici: 'hier',
  là: 'da, dort', bien: 'gut', tout: 'alles / ganz', tous: 'alle', toute: 'ganz', toutes: 'alle', chaque: 'jede(r)',
  autre: 'andere(r)', autres: 'andere', même: 'selbe / sogar', "qu'il": 'dass er', "qu'elle": 'dass sie',
  "jusqu'à": 'bis', "d'abord": 'zuerst', "d'accord": 'einverstanden', merci: 'danke', bonjour: 'guten Tag',
  euros: 'Euro', euro: 'Euro', madame: 'Frau (Anrede), gnädige Frau', monsieur: 'Herr (Anrede)', journée: 'Tag (Tagesverlauf)',
  salle: 'Saal, Raum (salle de bains = Bad, salle de sport = Fitnessstudio)', grave: 'schlimm, ernst', mieux: 'besser', selon: 'laut, gemäß',
  faut: ['man muss (il faut)', 'falloir'], t: '(Bindelaut: raconte-t-elle)', bout: 'Ende, Spitze (au bout de = nach)',
  tour: 'Runde, Reihe (à tour de rôle = abwechselnd; faire le tour du monde = Weltreise)', certains: 'manche, einige',
  certaines: 'manche, einige', soi: 'sich (à soi = für sich)', retour: 'Rückkehr', lentement: 'langsam', vieille: ['alt (f)', 'vieux'],
  est: ['ist (être) / Osten', 'être'], ai: ['habe (avoir)', 'avoir'], as: ['hast (avoir)', 'avoir'], a: ['hat (avoir)', 'avoir'],
  avons: ['haben (avoir)', 'avoir'], avez: ['habt / haben Sie (avoir)', 'avoir'], ont: ['haben (avoir)', 'avoir'],
  "qu'est": 'was ist (qu’est-ce que = was)', "s'il": 'wenn er/es (s’il vous plaît = bitte)',
  courses: 'Einkäufe (faire les courses = einkaufen) / Rennen',
  paris: 'Paris', france: 'Frankreich', allemagne: 'Deutschland', français: 'französisch / Französisch', française: 'Französin / französisch',
};

export const COMMON_WORDS: Record<Lang, Record<string, Gloss>> = { it: IT, es: ES, fr: FR };
