import type { Epoch } from '../types';

export const E4: Epoch = {
  id: 'weltmacht',
  name: 'Aufstieg zur Weltmacht',
  period: '1870–1945',
  events: [
    {
      id: 'einwanderung',
      title: 'Einwanderung, Industrie und Gilded Age',
      date: '1870–1914',
      text: [
        'Nach dem Bürgerkrieg wurden die USA zur größten Industriemacht der Welt. Millionen Einwanderer kamen auf der Suche nach einem besseren Leben, Erfinder wie Edison veränderten den Alltag, und Unternehmer wie Rockefeller wurden unvorstellbar reich.',
      ],
      subtopics: [
        {
          id: 'gilded-age',
          title: 'Freiheitsstatue, Edison und Rockefeller',
          date: '1870–1914',
          text: [
            'Zwischen 1880 und 1920 kamen über 20 Millionen Einwanderer in die USA, zuerst viele Iren und Deutsche, dann Italiener, Juden aus Osteuropa, Polen und Griechen. 1886 wurde im Hafen von New York die Freiheitsstatue eingeweiht, ein Geschenk Frankreichs. Ab 1892 wurden die Neuankömmlinge auf Ellis Island registriert und auf Krankheiten untersucht. Chinesen dagegen wurden durch den „Chinese Exclusion Act“ von 1882 weitgehend ausgeschlossen.',
            'Erfinder veränderten den Alltag: Alexander Graham Bell ließ sich 1876 das Telefon patentieren, Thomas Edison entwickelte 1879 eine brauchbare Glühbirne und gründete das erste Elektrizitätswerk. 1903 gelang den Brüdern Wilbur und Orville Wright bei Kitty Hawk der erste Motorflug. Henry Ford baute ab 1908 das „Model T“ und senkte mit dem Fließband (1913) den Preis so, dass sich auch Arbeiter ein Auto leisten konnten.',
            'Der Schriftsteller Mark Twain nannte die Zeit spöttisch „Gilded Age“ (vergoldetes Zeitalter): außen Glanz, darunter Korruption und Armut. John D. Rockefeller beherrschte mit Standard Oil rund 90 Prozent der Ölraffinerien, Andrew Carnegie den Stahl, J. P. Morgan die Banken. Carnegie spendete später sein Vermögen für Bibliotheken und Konzertsäle. 1890 sollte das Kartellgesetz (Sherman Act) Monopole begrenzen; 1911 wurde Standard Oil zerschlagen.',
            'In den Städten entstanden Wolkenkratzer, aber Arbeiter, darunter viele Kinder, schufteten zwölf Stunden am Tag. Gewerkschaften kämpften für den Achtstundentag; bei der Haymarket-Kundgebung in Chicago 1886 explodierte eine Bombe, daraus entstand weltweit der 1. Mai als Tag der Arbeit. Präsident Theodore Roosevelt („Teddy“, nach ihm ist der Teddybär benannt) ging gegen Monopole vor und schuf Nationalparks.',
            'Die USA wurden nun auch Kolonialmacht: 1898 annektierten sie Hawaii. Im Spanisch-Amerikanischen Krieg 1898 gewannen sie Puerto Rico, Guam und die Philippinen; Kuba kam unter ihren Einfluss. 1914 wurde der Panamakanal eröffnet, den die USA gebaut hatten und der Atlantik und Pazifik verband.',
          ],
          quiz: {
            leicht: [
              ['Wie viele Einwanderer kamen 1880–1920 etwa?', 'Über 20 Millionen', ['Rund 2 Millionen', 'Rund 200.000', 'Über 200 Millionen']],
              ['Wann wurde die Freiheitsstatue eingeweiht?', '1886', ['1776', '1892', '1903']],
              ['Von welchem Land war die Freiheitsstatue ein Geschenk?', 'Frankreich', ['England', 'Spanien', 'Deutschland']],
              ['Wo wurden Einwanderer ab 1892 registriert?', 'Auf Ellis Island', ['Auf Alcatraz', 'In Boston', 'Auf Long Island']],
              ['Welche Gruppe schloss ein Gesetz 1882 aus?', 'Chinesen', ['Iren', 'Deutsche', 'Italiener']],
              ['Wer ließ sich das Telefon patentieren?', 'Alexander Graham Bell', ['Thomas Edison', 'Samuel Morse', 'Nikola Tesla']],
              ['Wer entwickelte eine brauchbare Glühbirne?', 'Thomas Edison', ['Bell', 'Ford', 'Westinghouse']],
              ['Wann gelang der erste Motorflug?', '1903', ['1876', '1913', '1927']],
              ['Wer gelang der erste Motorflug?', 'Den Brüdern Wright', ['Henry Ford', 'Charles Lindbergh', 'Edison']],
              ['Welches Auto baute Henry Ford ab 1908?', 'Das Model T', ['Den Mustang', 'Den Käfer', 'Den Cadillac']],
              ['Was führte Ford 1913 ein?', 'Das Fließband', ['Das Telefon', 'Den Motor', 'Die Ampel']],
              ['Wie nannte Mark Twain die Zeit?', 'Gilded Age (vergoldetes Zeitalter)', ['Goldenes Zeitalter', 'Roaring Twenties', 'Jazz Age']],
              ['Wer beherrschte die Ölraffinerien?', 'John D. Rockefeller', ['Andrew Carnegie', 'J. P. Morgan', 'Henry Ford']],
              ['Wie hieß Rockefellers Firma?', 'Standard Oil', ['Ford Motor', 'US Steel', 'General Electric']],
              ['Welcher Unternehmer beherrschte den Stahl?', 'Andrew Carnegie', ['Rockefeller', 'Morgan', 'Vanderbilt']],
              ['Woraus entstand der 1. Mai als Tag der Arbeit?', 'Aus der Haymarket-Kundgebung in Chicago', ['Aus Thanksgiving', 'Aus dem Bürgerkrieg', 'Aus der Boston Tea Party']],
              ['Welches Spielzeug ist nach Theodore Roosevelt benannt?', 'Der Teddybär', ['Die Barbie', 'Das Jo-Jo', 'Der Kreisel']],
              ['Welche Inseln annektierten die USA 1898?', 'Hawaii', ['Kuba', 'Jamaika', 'Bahamas']],
              ['Welche Gebiete gewannen die USA 1898 von Spanien?', 'Puerto Rico, Guam und die Philippinen', ['Mexiko und Texas', 'Kanada', 'Florida']],
              ['Wann wurde der Panamakanal eröffnet?', '1914', ['1903', '1898', '1920']],
            ],
            mittel: [
              ['Welche Einwanderer kamen zuerst in großer Zahl?', 'Iren und Deutsche', ['Chinesen und Japaner', 'Mexikaner', 'Inder']],
              ['Welche Gruppen kamen später?', 'Italiener, osteuropäische Juden, Polen, Griechen', ['Engländer', 'Franzosen', 'Australier']],
              ['Worauf wurden Einwanderer auf Ellis Island untersucht?', 'Auf Krankheiten', ['Auf Reichtum', 'Auf Religion', 'Auf Haarfarbe']],
              ['Wann ließ sich Bell das Telefon patentieren?', '1876', ['1879', '1903', '1886']],
              ['Wann entwickelte Edison die Glühbirne?', '1879', ['1876', '1903', '1913']],
              ['Was gründete Edison außerdem?', 'Das erste Elektrizitätswerk', ['Die erste Autofabrik', 'Die erste Fluglinie', 'Die erste Bank']],
              ['Wo gelang der erste Motorflug?', 'Bei Kitty Hawk', ['In Detroit', 'In Chicago', 'In New York']],
              ['Wie hießen die Brüder Wright?', 'Wilbur und Orville', ['John und Robert', 'Henry und Edsel', 'Thomas und James']],
              ['Was bewirkte das Fließband?', 'Autos wurden für Arbeiter erschwinglich', ['Autos wurden teurer', 'Nichts', 'Autos wurden verboten']],
              ['Was lag laut Mark Twain unter dem Glanz?', 'Korruption und Armut', ['Gold', 'Freiheit', 'Frieden']],
              ['Wie viel Prozent der Raffinerien beherrschte Standard Oil?', 'Rund 90 Prozent', ['Rund 10 Prozent', 'Rund 50 Prozent', 'Alle']],
              ['Wer beherrschte die Banken?', 'J. P. Morgan', ['Carnegie', 'Rockefeller', 'Ford']],
              ['Wofür spendete Carnegie sein Vermögen?', 'Für Bibliotheken und Konzertsäle', ['Für Kriege', 'Für Pferderennen', 'Für nichts']],
              ['Welches Gesetz sollte 1890 Monopole begrenzen?', 'Der Sherman Act', ['Der Homestead Act', 'Der Stamp Act', 'Der New Deal']],
              ['Wann wurde Standard Oil zerschlagen?', '1911', ['1890', '1929', '1901']],
              ['Wie lange arbeiteten viele Arbeiter täglich?', 'Zwölf Stunden', ['Vier Stunden', 'Acht Stunden', 'Zwanzig Stunden']],
              ['Wofür kämpften Gewerkschaften?', 'Für den Achtstundentag', ['Für längere Arbeit', 'Für Kinderarbeit', 'Für Monopole']],
              ['Wann war die Haymarket-Kundgebung?', '1886', ['1876', '1903', '1914']],
              ['Wogegen ging Theodore Roosevelt vor?', 'Gegen Monopole', ['Gegen Gewerkschaften', 'Gegen Nationalparks', 'Gegen Schulen']],
              ['Was verband der Panamakanal?', 'Atlantik und Pazifik', ['Atlantik und Mittelmeer', 'Pazifik und Indischen Ozean', 'Mississippi und Atlantik']],
            ],
            schwer: [
              ['Was zeigt der Chinese Exclusion Act?', 'Einwanderung war nicht für alle offen', ['Offenheit für alle', 'Eine Einladung an China', 'Nichts']],
              ['Was bedeutet „Gilded Age“ kritisch?', 'Glänzende Oberfläche über sozialen Missständen', ['Echtes Goldenes Zeitalter', 'Eine Kunstrichtung', 'Ein Goldrausch']],
              ['Warum wurde Standard Oil zerschlagen?', 'Als Monopol', ['Weil es pleite war', 'Wegen Krieg', 'Weil Rockefeller starb']],
              ['Welche Rolle spielte Carnegie als Wohltäter?', 'Er spendete für Bildung und Kultur', ['Er spendete nichts', 'Er finanzierte Kriege', 'Er gründete Kirchen']],
              ['Woraus entstand der internationale Tag der Arbeit?', 'Aus den Ereignissen in Chicago 1886', ['Aus Thanksgiving', 'Aus der Französischen Revolution', 'Aus Labor Day im September']],
              ['Was wurden die USA ab 1898 außenpolitisch?', 'Eine Kolonialmacht', ['Ein neutraler Staat', 'Eine Kolonie', 'Ein Kaiserreich']],
              ['Unter wessen Einfluss kam Kuba 1898?', 'Unter dem der USA', ['Unter dem Spaniens weiter', 'Unter dem Englands', 'Unter dem Mexikos']],
              ['Wer baute den Panamakanal fertig?', 'Die USA', ['Frankreich', 'England', 'Kanada']],
              ['Welche Branche beherrschte Morgan?', 'Banken', ['Öl', 'Stahl', 'Autos']],
              ['Was ist ein Monopol?', 'Marktbeherrschung durch ein Unternehmen', ['Ein Gesetz', 'Eine Gewerkschaft', 'Ein Kanal']],
              ['Was machte das Model T besonders?', 'Massenproduktion zu niedrigem Preis', ['Es war ein Luxusauto', 'Es flog', 'Es fuhr mit Dampf']],
              ['Was veränderte Edisons Elektrizität?', 'Den Alltag mit elektrischem Licht', ['Nur die Industrie', 'Nichts', 'Den Bergbau']],
              ['Welche Rolle spielte Ellis Island?', 'Registrierung der Einwanderer', ['Gefängnis', 'Militärbasis', 'Freizeitpark']],
              ['Was symbolisiert die Freiheitsstatue?', 'Freiheit und Willkommen für Einwanderer', ['Militärmacht', 'Reichtum', 'Den Bürgerkrieg']],
              ['Was beschränkte der Sherman Act?', 'Kartelle und Monopole', ['Einwanderung', 'Waffenbesitz', 'Alkohol']],
              ['Welches Gebiet im Pazifik kam 1898 außer den Philippinen?', 'Guam', ['Tahiti', 'Neuseeland', 'Island']],
              ['Welche Arbeitsbedingungen herrschten?', 'Lange Arbeitstage auch für Kinder', ['Kurze Arbeitstage', 'Keine Arbeit', 'Bezahlter Urlaub']],
              ['Welcher Präsident schuf Nationalparks und ging gegen Monopole vor?', 'Theodore Roosevelt', ['Franklin D. Roosevelt', 'Abraham Lincoln', 'Woodrow Wilson']],
              ['Wie wurde aus Amerika die größte Industriemacht?', 'Durch Erfindungen, Rohstoffe und Einwanderer', ['Durch Kolonien in Afrika', 'Durch Kriege in Europa', 'Durch Sklaverei']],
              ['In welchem Jahr wurde Hawaii annektiert?', '1898', ['1867', '1914', '1959']],
            ],
          },
        },
      ],
    },
    {
      id: 'new-deal',
      title: 'Weltkrieg, Roaring Twenties und New Deal',
      date: '1914–1939',
      text: [
        'Die USA entschieden den Ersten Weltkrieg mit, erlebten danach die wilden Zwanziger – und 1929 den tiefsten Wirtschaftszusammenbruch ihrer Geschichte. Präsident Franklin D. Roosevelt antwortete mit dem New Deal.',
      ],
      subtopics: [
        {
          id: 'zwanziger',
          title: 'Erster Weltkrieg und Roaring Twenties',
          date: '1914–1929',
          text: [
            'Im Ersten Weltkrieg blieben die USA zunächst neutral. Nachdem ein deutsches U-Boot 1915 den britischen Passagierdampfer „Lusitania“ versenkt hatte (128 Amerikaner starben) und Deutschland Mexiko in der „Zimmermann-Depesche“ ein Bündnis angeboten hatte, erklärte Präsident Woodrow Wilson 1917 Deutschland den Krieg. Über zwei Millionen amerikanische Soldaten kamen nach Frankreich. Wilsons „14 Punkte“ (1918) forderten einen gerechten Frieden und einen Völkerbund – doch der US-Senat lehnte den Beitritt ab.',
            '1920 erhielten Frauen mit dem 19. Zusatzartikel das Wahlrecht, nach jahrzehntelangem Kampf von Frauenrechtlerinnen wie Susan B. Anthony. Ebenfalls 1920 trat mit dem 18. Zusatzartikel die „Prohibition“ in Kraft: Herstellung und Verkauf von Alkohol waren verboten. Daraufhin blühten illegale Bars („Speakeasies“) und Schmuggel; Gangster wie Al Capone in Chicago wurden reich. 1933 hob der 21. Zusatzartikel die Prohibition wieder auf.',
            'Die 1920er-Jahre hießen „Roaring Twenties“ (wilde Zwanziger) oder „Jazz Age“. Jazzmusiker wie Louis Armstrong wurden berühmt, Frauen mit kurzen Haaren und Röcken („Flappers“) tanzten Charleston. Radio und Kino eroberten den Alltag; 1927 kam mit „The Jazz Singer“ der erste Tonfilm. In der „Harlem Renaissance“ blühte die afroamerikanische Kultur in New York. Hollywood wurde zur Filmhauptstadt der Welt.',
            '1927 flog Charles Lindbergh als Erster allein und ohne Zwischenlandung von New York nach Paris, in 33,5 Stunden. Autos, Kühlschränke und Radios wurden auf Raten gekauft, Aktienkurse stiegen immer weiter. Doch nicht alle profitierten: Bauern verarmten, und im Süden herrschte weiter Rassentrennung; der Ku-Klux-Klan hatte in den 1920ern Millionen Mitglieder.',
            'Gleichzeitig wuchs die Angst vor Fremden: Gesetze von 1921 und 1924 beschränkten die Einwanderung stark, besonders aus Süd- und Osteuropa und Asien. Die italienischen Einwanderer Sacco und Vanzetti wurden 1927 nach einem umstrittenen Prozess hingerichtet.',
          ],
          quiz: {
            leicht: [
              ['Welches Schiff versenkte ein deutsches U-Boot 1915?', 'Die Lusitania', ['Die Titanic', 'Die Maine', 'Die Mayflower']],
              ['Wann traten die USA in den Ersten Weltkrieg ein?', '1917', ['1914', '1918', '1941']],
              ['Welcher Präsident erklärte Deutschland den Krieg?', 'Woodrow Wilson', ['Theodore Roosevelt', 'Franklin D. Roosevelt', 'Herbert Hoover']],
              ['Wie hieß Wilsons Friedensprogramm?', '„14 Punkte“', ['„New Deal“', '„Fair Deal“', '„Marshallplan“']],
              ['Was lehnte der US-Senat ab?', 'Den Beitritt zum Völkerbund', ['Den Krieg', 'Die 14 Punkte ganz', 'Die Prohibition']],
              ['Wann erhielten Frauen das Wahlrecht?', '1920', ['1865', '1945', '1776']],
              ['Welcher Zusatzartikel gab Frauen das Wahlrecht?', 'Der 19.', ['Der 13.', 'Der 1.', 'Der 15.']],
              ['Wie hieß das Alkoholverbot?', 'Prohibition', ['Temperance', 'Abolition', 'Restriction']],
              ['Wann begann die Prohibition?', '1920', ['1933', '1917', '1929']],
              ['Wann wurde die Prohibition aufgehoben?', '1933', ['1929', '1920', '1945']],
              ['Wie hießen illegale Bars?', 'Speakeasies', ['Saloons', 'Pubs', 'Diners']],
              ['Welcher Gangster wurde in Chicago reich?', 'Al Capone', ['Jesse James', 'Billy the Kid', 'Wyatt Earp']],
              ['Wie nannte man die 1920er-Jahre?', 'Roaring Twenties', ['Gilded Age', 'Great Depression', 'Swinging Sixties']],
              ['Welcher Jazzmusiker wurde berühmt?', 'Louis Armstrong', ['Elvis Presley', 'Frank Sinatra', 'Bob Dylan']],
              ['Welchen Tanz tanzten die Flappers?', 'Charleston', ['Twist', 'Walzer', 'Tango']],
              ['Wann kam der erste Tonfilm?', '1927', ['1903', '1939', '1915']],
              ['Wie hieß der erste Tonfilm?', '„The Jazz Singer“', ['„Vom Winde verweht“', '„King Kong“', '„Metropolis“']],
              ['Welche Stadt wurde Filmhauptstadt?', 'Hollywood', ['New York', 'Chicago', 'Las Vegas']],
              ['Wer flog 1927 allein nach Paris?', 'Charles Lindbergh', ['Amelia Earhart', 'Die Brüder Wright', 'Howard Hughes']],
              ['Wie nennt man die Blüte der afroamerikanischen Kultur in New York?', 'Harlem Renaissance', ['Brooklyn Revival', 'Beat Generation', 'Bronx Movement']],
            ],
            mittel: [
              ['Wie viele Amerikaner starben auf der Lusitania?', '128', ['12', '1280', '28']],
              ['Was bot die Zimmermann-Depesche Mexiko an?', 'Ein Bündnis mit Deutschland', ['Frieden mit den USA', 'Geld für Öl', 'Einen König']],
              ['Wie viele US-Soldaten kamen nach Frankreich?', 'Über zwei Millionen', ['Rund 20.000', 'Rund 200.000', 'Über 20 Millionen']],
              ['Was forderten die 14 Punkte?', 'Einen gerechten Frieden und einen Völkerbund', ['Die Teilung Deutschlands', 'Kolonien für die USA', 'Krieg gegen Russland']],
              ['Welche Frauenrechtlerin kämpfte jahrzehntelang?', 'Susan B. Anthony', ['Rosa Parks', 'Eleanor Roosevelt', 'Harriet Tubman']],
              ['Was war während der Prohibition verboten?', 'Herstellung und Verkauf von Alkohol', ['Tabak', 'Glücksspiel', 'Tanzen']],
              ['Was blühte während der Prohibition?', 'Schmuggel und illegale Bars', ['Weinbau', 'Die Kirche', 'Die Bierbrauereien']],
              ['Wie hießen moderne junge Frauen der 1920er?', 'Flappers', ['Suffragetten', 'Pin-ups', 'Hippies']],
              ['Was eroberte den Alltag?', 'Radio und Kino', ['Fernsehen und Internet', 'Telegraf', 'Theater']],
              ['Wie lange dauerte Lindberghs Flug?', '33,5 Stunden', ['3,5 Stunden', '335 Stunden', '12 Stunden']],
              ['Wie kaufte man Autos und Radios oft?', 'Auf Raten', ['Mit Gold', 'Gar nicht', 'Mit Tauschhandel']],
              ['Was stieg in den 1920ern immer weiter?', 'Die Aktienkurse', ['Die Arbeitslosigkeit', 'Die Zahl der Bauern', 'Die Prohibition']],
              ['Wer profitierte nicht vom Boom?', 'Bauern', ['Aktionäre', 'Autohersteller', 'Hollywood']],
              ['Wie viele Mitglieder hatte der Ku-Klux-Klan in den 1920ern?', 'Millionen', ['Hunderte', 'Tausende', 'Keine']],
              ['Wann wurde die Einwanderung beschränkt?', '1921 und 1924', ['1800 und 1810', '1965', '1945']],
              ['Woher wurde Einwanderung besonders beschränkt?', 'Aus Süd- und Osteuropa und Asien', ['Aus England', 'Aus Kanada', 'Aus Frankreich']],
              ['Welche Einwanderer wurden 1927 hingerichtet?', 'Sacco und Vanzetti', ['Bonnie und Clyde', 'Al Capone und Nitti', 'Die Rosenbergs']],
              ['Woher stammten Sacco und Vanzetti?', 'Aus Italien', ['Aus Irland', 'Aus Russland', 'Aus Mexiko']],
              ['Wie nennt man die 1920er auch?', 'Jazz Age', ['Gilded Age', 'Space Age', 'Iron Age']],
              ['Wann verkündete Wilson die 14 Punkte?', '1918', ['1914', '1920', '1929']],
            ],
            schwer: [
              ['Warum traten die USA 1917 in den Krieg ein?', 'U-Boot-Krieg und Zimmermann-Depesche', ['Angriff auf Pearl Harbor', 'Angriff auf New York', 'Um Kanada zu erobern']],
              ['Was ist das Paradox von Wilsons Völkerbund?', 'Er schlug ihn vor, aber die USA traten nicht bei', ['Er war dagegen', 'Die USA leiteten ihn', 'Er existierte nie']],
              ['Welche Folge hatte die Prohibition?', 'Aufstieg des organisierten Verbrechens', ['Weniger Kriminalität', 'Mehr Steuern', 'Nichts']],
              ['Was zeigt die Harlem Renaissance?', 'Eine Blüte afroamerikanischer Kunst und Kultur', ['Einen Aufstand', 'Eine Kirche', 'Rassentrennung']],
              ['Warum war der Boom der 1920er gefährlich?', 'Kauf auf Raten und Spekulation', ['Zu viel Sparen', 'Zu niedrige Kurse', 'Keine Kredite']],
              ['Was zeigt der Fall Sacco und Vanzetti?', 'Fremdenfeindlichkeit und umstrittene Justiz', ['Einen fairen Prozess', 'Einen Gangsterkrieg', 'Einen Streik']],
              ['Welche gesellschaftliche Wende brachte 1920 für Frauen?', 'Das Wahlrecht', ['Die Wehrpflicht', 'Das Alkoholverbot', 'Nichts']],
              ['Was war die Zimmermann-Depesche?', 'Ein deutsches Bündnisangebot an Mexiko', ['Ein Friedensvertrag', 'Ein Zeitungsartikel', 'Ein Gesetz']],
              ['Was symbolisieren die Flappers?', 'Neues Selbstbewusstsein junger Frauen', ['Kriegsveteranen', 'Bauern', 'Gangster']],
              ['Welche Erfindung brachte 1927 einen Wandel im Kino?', 'Der Tonfilm', ['Der Farbfilm', 'Das Fernsehen', 'Das 3D-Kino']],
              ['Warum war Lindberghs Flug besonders?', 'Erster Alleinflug nonstop über den Atlantik', ['Erster Flug überhaupt', 'Erster Flug zum Mond', 'Erster Flug nach Asien']],
              ['Welche Städte wurden Zentren von Jazz und Gangstern?', 'New York und Chicago', ['Boston und Philadelphia', 'Los Angeles und Seattle', 'Miami und Dallas']],
              ['Welcher Teil der USA blieb von Rassentrennung geprägt?', 'Der Süden', ['Der Norden', 'Der Westen', 'Alaska']],
              ['Was bewirkten die Einwanderungsgesetze der 1920er?', 'Starke Beschränkung bestimmter Gruppen', ['Offene Grenzen', 'Mehr Einwanderer aus Asien', 'Nichts']],
              ['Welche Branche wurde in Hollywood zentriert?', 'Die Filmindustrie', ['Die Autoindustrie', 'Die Ölindustrie', 'Die Stahlindustrie']],
              ['Wie viele Jahre dauerte die Prohibition?', '13', ['3', '30', '1']],
              ['Welcher Zusatzartikel brachte die Prohibition (1920)?', 'Der 18.', ['Der 19.', 'Der 13.', 'Der 21.']],
              ['Welcher Zusatzartikel hob die Prohibition auf?', 'Der 21.', ['Der 18.', 'Der 19.', 'Der 22.']],
              ['Was wurde in den 1920ern auf Raten gekauft?', 'Autos, Kühlschränke und Radios', ['Schiffe', 'Gold', 'Pferde']],
              ['Welcher Präsident führte die USA in den Ersten Weltkrieg?', 'Wilson', ['Hoover', 'Coolidge', 'Harding']],
            ],
          },
        },
        {
          id: 'krise-new-deal',
          title: 'Große Depression und New Deal',
          date: '1929–1939',
          text: [
            'Am „Schwarzen Donnerstag“, dem 24. Oktober 1929, und an den folgenden Tagen stürzten die Aktienkurse an der New Yorker Börse an der Wall Street ab. Tausende Banken brachen zusammen, Sparer verloren alles. Die „Große Depression“ folgte und wurde zur Weltwirtschaftskrise: 1933 war ein Viertel der Arbeitskräfte arbeitslos, Menschen standen in langen Schlangen vor Suppenküchen und lebten in Hüttensiedlungen, spöttisch „Hoovervilles“ genannt nach Präsident Herbert Hoover.',
            'Zugleich verwandelten Dürre und Stürme die ausgelaugten Felder der Great Plains in die „Dust Bowl“ (Staubschüssel). Riesige Staubstürme verdunkelten den Himmel; Hunderttausende Farmerfamilien, die „Okies“ (nach Oklahoma), zogen nach Kalifornien. John Steinbeck beschrieb ihr Schicksal in „Früchte des Zorns“ (1939), die Fotografin Dorothea Lange in ihrem Bild „Migrant Mother“.',
            '1932 wurde der Demokrat Franklin D. Roosevelt (FDR) Präsident. In seiner Antrittsrede sagte er: „Das Einzige, was wir zu fürchten haben, ist die Furcht selbst.“ In den ersten „100 Tagen“ beschloss der Kongress zahlreiche Gesetze. Über Radioansprachen, die „Kamingespräche“, sprach er direkt zu den Bürgern.',
            'Sein Programm hieß „New Deal“. Der Staat schuf Arbeit durch große Bauprojekte: Das Civilian Conservation Corps pflanzte Bäume, die Tennessee Valley Authority baute Staudämme und brachte Strom aufs Land, die Works Progress Administration beschäftigte Millionen beim Bau von Straßen, Schulen und Brücken – sogar Künstler und Schriftsteller. 1935 entstand mit dem „Social Security Act“ die erste staatliche Rentenversicherung, Gewerkschaften wurden gestärkt.',
            'Kritiker hielten den New Deal für zu teuer oder zu sozialistisch; der Oberste Gerichtshof kippte einige Gesetze. Ganz überwunden wurde die Krise erst durch die Rüstung im Zweiten Weltkrieg. Roosevelt wurde viermal gewählt (1932, 1936, 1940, 1944) – als einziger Präsident; danach begrenzte der 22. Zusatzartikel die Amtszeit auf zwei Wahlperioden. Seine Frau Eleanor Roosevelt setzte sich für Bürgerrechte und Frauen ein.',
          ],
          quiz: {
            leicht: [
              ['Wie heißt der Börsentag vom 24. Oktober 1929?', 'Schwarzer Donnerstag', ['Roter Mittwoch', 'Blauer Montag', 'Roter Dienstag']],
              ['An welcher Straße liegt die New Yorker Börse?', 'Wall Street', ['Broadway', 'Fifth Avenue', 'Main Street']],
              ['Wie heißt die Wirtschaftskrise nach 1929?', 'Große Depression', ['Gilded Age', 'New Deal', 'Roaring Twenties']],
              ['Welcher Anteil war 1933 arbeitslos?', 'Ein Viertel', ['Ein Hundertstel', 'Die Hälfte', 'Fast niemand']],
              ['Wie nannte man die Hüttensiedlungen?', 'Hoovervilles', ['Rooseveltvilles', 'Wilsonvilles', 'Dustvilles']],
              ['Welcher Präsident regierte bei Krisenbeginn?', 'Herbert Hoover', ['Franklin D. Roosevelt', 'Woodrow Wilson', 'Calvin Coolidge']],
              ['Wie nennt man die Staubstürme der Great Plains?', 'Dust Bowl', ['Sand Storm', 'Great Plains Disaster', 'Black Wind']],
              ['Wohin zogen die „Okies“?', 'Nach Kalifornien', ['Nach Kanada', 'Nach New York', 'Nach Mexiko']],
              ['Wer schrieb „Früchte des Zorns“?', 'John Steinbeck', ['Ernest Hemingway', 'Mark Twain', 'F. Scott Fitzgerald']],
              ['Welches Foto machte Dorothea Lange berühmt?', '„Migrant Mother“', ['„Raising the Flag“', '„Afghan Girl“', '„Lunch atop a Skyscraper“']],
              ['Wer wurde 1932 Präsident?', 'Franklin D. Roosevelt', ['Herbert Hoover', 'Harry Truman', 'Theodore Roosevelt']],
              ['Was sagte FDR in seiner Antrittsrede?', '„Das Einzige, was wir zu fürchten haben, ist die Furcht selbst“', ['„Ich habe einen Traum“', '„Ich bin ein Berliner“', '„Read my lips“']],
              ['Wie hießen FDRs Radioansprachen?', 'Kamingespräche', ['Sonntagsreden', 'Fireworks', 'State of the Union']],
              ['Wie hieß FDRs Programm?', 'New Deal', ['Fair Deal', 'Great Society', 'New Frontier']],
              ['Was entstand 1935 mit dem Social Security Act?', 'Die erste staatliche Rentenversicherung', ['Die Krankenversicherung für alle', 'Die Arbeitslosenpflicht', 'Die Börse']],
              ['Was baute die Tennessee Valley Authority?', 'Staudämme', ['Wolkenkratzer', 'Flughäfen', 'Kriegsschiffe']],
              ['Wie oft wurde FDR gewählt?', 'Viermal', ['Zweimal', 'Dreimal', 'Einmal']],
              ['Was beendete die Krise endgültig?', 'Die Rüstung im Zweiten Weltkrieg', ['Die Dust Bowl', 'Die Prohibition', 'Ein Goldfund']],
              ['Welcher Zusatzartikel begrenzt die Amtszeit?', 'Der 22.', ['Der 19.', 'Der 13.', 'Der 1.']],
              ['Wer war Roosevelts Frau?', 'Eleanor Roosevelt', ['Edith Roosevelt', 'Jackie Kennedy', 'Martha Washington']],
            ],
            mittel: [
              ['Was geschah mit Tausenden Banken?', 'Sie brachen zusammen', ['Sie wurden reich', 'Sie fusionierten', 'Nichts']],
              ['Was verloren viele Sparer?', 'Alles', ['Nichts', 'Die Hälfte', 'Nur Zinsen']],
              ['Wo standen Menschen in langen Schlangen?', 'Vor Suppenküchen', ['Vor Kinos', 'Vor Börsen', 'Vor Autohäusern']],
              ['Wann war ein Viertel arbeitslos?', '1933', ['1929', '1939', '1945']],
              ['Was verursachte die Dust Bowl?', 'Dürre, Stürme und ausgelaugte Felder', ['Ein Vulkan', 'Ein Erdbeben', 'Eine Flut']],
              ['Wie viele Farmerfamilien zogen weg?', 'Hunderttausende', ['Einige Dutzend', 'Keine', 'Millionen Städter']],
              ['Wann erschien „Früchte des Zorns“?', '1939', ['1929', '1945', '1935']],
              ['Welcher Partei gehörte FDR an?', 'Den Demokraten', ['Den Republikanern', 'Den Sozialisten', 'Den Föderalisten']],
              ['Was beschloss der Kongress in den ersten 100 Tagen?', 'Zahlreiche Gesetze', ['Nichts', 'Eine Kriegserklärung', 'Die Prohibition']],
              ['Was tat das Civilian Conservation Corps?', 'Es pflanzte Bäume', ['Es baute Panzer', 'Es druckte Geld', 'Es führte Kriege']],
              ['Was brachte die TVA aufs Land?', 'Strom', ['Gold', 'Erdöl', 'Internet']],
              ['Wen beschäftigte die Works Progress Administration?', 'Millionen, sogar Künstler und Schriftsteller', ['Nur Soldaten', 'Nur Ingenieure', 'Niemanden']],
              ['Was baute die WPA?', 'Straßen, Schulen und Brücken', ['Kriegsschiffe', 'Kasinos', 'Paläste']],
              ['Wann entstand der Social Security Act?', '1935', ['1929', '1933', '1945']],
              ['Was wurde unter dem New Deal gestärkt?', 'Die Gewerkschaften', ['Die Monopole', 'Die Prohibition', 'Die Börse']],
              ['Was kritisierten Gegner am New Deal?', 'Zu teuer oder zu sozialistisch', ['Zu billig', 'Zu wenig Gesetze', 'Zu kurz']],
              ['Wer kippte einige New-Deal-Gesetze?', 'Der Oberste Gerichtshof', ['Der Präsident', 'Die Gewerkschaften', 'Die Kirchen']],
              ['In welchen Jahren wurde FDR gewählt?', '1932, 1936, 1940, 1944', ['1928, 1932, 1936, 1940', '1928 und 1948', '1936 bis 1948']],
              ['Wofür setzte sich Eleanor Roosevelt ein?', 'Für Bürgerrechte und Frauen', ['Für die Prohibition', 'Gegen Gewerkschaften', 'Für die Monarchie']],
              ['Was ist einzigartig an FDR?', 'Einziger Präsident mit vier Wahlsiegen', ['Erster Präsident', 'Jüngster Präsident', 'Erster Demokrat']],
            ],
            schwer: [
              ['Warum hießen die Hüttensiedlungen „Hoovervilles“?', 'Spott auf Präsident Hoover', ['Nach einem Erfinder', 'Nach einem Fluss', 'Nach einer Firma']],
              ['Was bedeutet „Dust Bowl“?', 'Staubschüssel', ['Staubsauger', 'Goldschüssel', 'Wüste']],
              ['Was zeigt „Migrant Mother“?', 'Die Not der Wanderarbeiter in der Depression', ['Einen Filmstar', 'Den Krieg', 'Den Wohlstand der 1920er']],
              ['Was war die Grundidee des New Deal?', 'Der Staat schafft Arbeit und soziale Sicherheit', ['Der Staat zieht sich zurück', 'Krieg als Lösung', 'Prohibition']],
              ['Wie nutzte FDR das Radio?', 'Für direkte Ansprachen an die Bürger', ['Für Morsecode', 'Für Werbung', 'Gar nicht']],
              ['Warum gibt es seit dem 22. Zusatzartikel keine vier Amtszeiten mehr?', 'Er begrenzt auf zwei Wahlperioden', ['Er verbietet Wahlen', 'Er gilt nur für Demokraten', 'Er wurde nie beschlossen']],
              ['Welche Rolle spielte der Krieg für die Wirtschaft?', 'Die Rüstung beendete die Krise', ['Er verschärfte die Krise', 'Keine', 'Er führte zur Prohibition']],
              ['Wer waren die „Okies“?', 'Vertriebene Farmer aus den Great Plains (Oklahoma)', ['Ölmagnaten', 'Indianer', 'Soldaten']],
              ['Was war die Tennessee Valley Authority?', 'Ein staatliches Programm für Dämme und Strom', ['Eine Bank', 'Eine Armee', 'Eine Universität']],
              ['Wie wirkte der Börsenkrach weltweit?', 'Er löste eine Weltwirtschaftskrise aus', ['Er betraf nur New York', 'Er half Europa', 'Gar nicht']],
              ['Welcher Satz FDRs sollte Mut machen?', 'Die Furcht selbst ist das Einzige, was zu fürchten ist', ['Wir haben nichts zu essen', 'Spart Gold', 'Kauft Aktien']],
              ['Was war die Social Security?', 'Staatliche Rentenversicherung', ['Eine Polizei', 'Ein Geheimdienst', 'Eine Gewerkschaft']],
              ['Welche Folge hatte die Krise für Banken 1929–1933?', 'Tausende Pleiten', ['Rekordgewinne', 'Steigende Kurse', 'Keine Folgen']],
              ['Wofür stand Eleanor Roosevelt?', 'Für Bürgerrechte und Frauen', ['Für Prohibition', 'Für Monopole', 'Für Kriege']],
              ['Wann war der Schwarze Donnerstag?', '24. Oktober 1929', ['29. Oktober 1929', '4. März 1933', '24. Oktober 1933']],
              ['Welche Region traf die Dust Bowl?', 'Die Great Plains', ['Neuengland', 'Florida', 'Kalifornien']],
              ['Was symbolisiert „Früchte des Zorns“?', 'Das Elend der vertriebenen Farmer', ['Den Reichtum Kaliforniens', 'Den Krieg', 'Hollywood']],
              ['Wie wirkte der New Deal auf Gewerkschaften?', 'Er stärkte sie', ['Er verbot sie', 'Keine Wirkung', 'Er schwächte sie']],
              ['Wer folgte auf Hoover?', 'FDR', ['Truman', 'Coolidge', 'Wilson']],
              ['Welches Problem löste der New Deal nicht ganz?', 'Die Arbeitslosigkeit', ['Die Prohibition', 'Die Sklaverei', 'Den Bürgerkrieg']],
            ],
          },
        },
      ],
    },
    {
      id: 'pearl-harbor',
      title: 'Die USA im Zweiten Weltkrieg',
      date: '1939–1945',
      text: [
        'Nach dem japanischen Angriff auf Pearl Harbor traten die USA in den Zweiten Weltkrieg ein. Mit ihrer gewaltigen Industrie wurden sie zum „Arsenal der Demokratie“ und gingen als Supermacht aus dem Krieg hervor.',
      ],
      subtopics: [
        {
          id: 'zweiter-wk-us',
          title: 'Pearl Harbor, D-Day und Hiroshima',
          date: '1939–1945',
          text: [
            'Als 1939 der Krieg in Europa begann, blieben die USA offiziell neutral, unterstützten aber Großbritannien ab 1941 mit dem Leih- und Pachtgesetz („Lend-Lease“) mit Waffen und Material; Roosevelt nannte die USA das „Arsenal der Demokratie“. Am 7. Dezember 1941 griffen japanische Flugzeuge die US-Pazifikflotte in Pearl Harbor auf Hawaii an. Über 2400 Amerikaner starben. Roosevelt sprach von einem „Tag, der in Schande fortleben wird“. Die USA erklärten Japan den Krieg; Deutschland und Italien erklärten den USA den Krieg.',
            'Die Wirtschaft stellte auf Rüstung um: Fabriken bauten statt Autos Panzer, Flugzeuge und Schiffe. Millionen Frauen arbeiteten in der Industrie; „Rosie the Riveter“ (Rosie die Nieterin) wurde zu ihrem Symbol. Rund 120.000 Menschen japanischer Herkunft, die meisten US-Bürger, wurden als angebliches Sicherheitsrisiko in Lager an der Westküste gesperrt – 1988 entschuldigte sich die Regierung dafür.',
            'Im Pazifik besiegte die US-Marine Japan im Juni 1942 bei den Midway-Inseln – der Wendepunkt im Pazifikkrieg. Danach eroberten die Amerikaner Insel für Insel zurück („Inselspringen“), unter schweren Verlusten etwa auf Iwo Jima, wo das berühmte Foto der Flaggenhissung entstand, und Okinawa. In Europa landeten US-Truppen 1942 in Nordafrika, 1943 in Italien und am 6. Juni 1944 („D-Day“) unter General Dwight D. Eisenhower in der Normandie; Eisenhower wurde später Präsident.',
            'Roosevelt starb im April 1945 kurz vor Kriegsende; Vizepräsident Harry S. Truman übernahm. Im geheimen „Manhattan-Projekt“ unter Leitung von J. Robert Oppenheimer hatten Wissenschaftler, darunter viele Flüchtlinge aus Europa, die Atombombe entwickelt; der erste Test fand im Juli 1945 in New Mexico statt. Auf Trumans Befehl warf am 6. August 1945 ein US-Bomber eine Atombombe auf Hiroshima, am 9. August auf Nagasaki. Über 200.000 Menschen starben. Am 2. September 1945 kapitulierte Japan.',
            'Rund 400.000 amerikanische Soldaten waren gestorben. Anders als Europa und Asien war die USA selbst kaum zerstört; sie produzierten nun die Hälfte aller Industriegüter der Welt. 1945 wurde in San Francisco die Charta der Vereinten Nationen unterzeichnet, die ihren Sitz in New York erhielten. Die USA waren zur Supermacht geworden.',
          ],
          quiz: {
            leicht: [
              ['Wann griff Japan Pearl Harbor an?', '7. Dezember 1941', ['6. Juni 1944', '1. September 1939', '6. August 1945']],
              ['Wo liegt Pearl Harbor?', 'Auf Hawaii', ['In Kalifornien', 'In Alaska', 'Auf den Philippinen']],
              ['Wie viele Amerikaner starben in Pearl Harbor etwa?', 'Über 2400', ['Rund 24', 'Rund 240', 'Über 24.000']],
              ['Wie nannte Roosevelt den 7. Dezember?', 'Einen Tag, der in Schande fortleben wird', ['Den längsten Tag', 'Den Tag der Freiheit', 'Den schwarzen Donnerstag']],
              ['Welches Gesetz half Großbritannien ab 1941?', 'Lend-Lease (Leih- und Pachtgesetz)', ['New Deal', 'Marshallplan', 'Homestead Act']],
              ['Wie nannte Roosevelt die USA?', '„Arsenal der Demokratie“', ['„Land der Freien“', '„Weltpolizist“', '„Neue Welt“']],
              ['Wer erklärte den USA nach Pearl Harbor den Krieg?', 'Deutschland und Italien', ['Frankreich', 'Die Sowjetunion', 'England']],
              ['Welche Frauenfigur wurde Symbol der Rüstungsarbeiterinnen?', 'Rosie the Riveter', ['Lady Liberty', 'Wonder Woman', 'Betty Boop']],
              ['Wer wurde in Lager an der Westküste gesperrt?', 'Menschen japanischer Herkunft', ['Deutsche', 'Iren', 'Mexikaner']],
              ['Wo besiegte die US-Marine Japan im Juni 1942?', 'Bei Midway', ['Bei Pearl Harbor', 'Bei Okinawa', 'Bei Iwo Jima']],
              ['Wie nennt man die Taktik im Pazifik?', 'Inselspringen', ['Blitzkrieg', 'Stellungskrieg', 'Grabenkrieg']],
              ['Auf welcher Insel entstand das Foto der Flaggenhissung?', 'Iwo Jima', ['Midway', 'Hawaii', 'Guam']],
              ['Wann war der D-Day?', '6. Juni 1944', ['7. Dezember 1941', '8. Mai 1945', '6. August 1945']],
              ['Welcher General führte die Landung in der Normandie?', 'Dwight D. Eisenhower', ['Douglas MacArthur', 'Chester Nimitz', 'Omar Bradley']],
              ['Wer übernahm nach Roosevelts Tod?', 'Harry S. Truman', ['Eisenhower', 'Eleanor Roosevelt', 'MacArthur']],
              ['Wie hieß das Atombombenprojekt?', 'Manhattan-Projekt', ['Apollo-Projekt', 'Brooklyn-Projekt', 'Overlord']],
              ['Wer leitete das Manhattan-Projekt wissenschaftlich?', 'J. Robert Oppenheimer', ['Albert Einstein', 'Thomas Edison', 'Werner Heisenberg']],
              ['Auf welche Städte fielen Atombomben?', 'Hiroshima und Nagasaki', ['Tokio und Osaka', 'Kyoto und Kobe', 'Berlin und Dresden']],
              ['Wann kapitulierte Japan?', '2. September 1945', ['8. Mai 1945', '6. August 1945', '7. Dezember 1945']],
              ['Wo erhielt die UNO ihren Sitz?', 'In New York', ['In Genf', 'In Washington', 'In San Francisco']],
            ],
            mittel: [
              ['Wie verhielten sich die USA 1939 offiziell?', 'Neutral', ['Als Kriegspartei', 'Als Verbündeter Deutschlands', 'Als Verbündeter Japans']],
              ['Was lieferte Lend-Lease?', 'Waffen und Material', ['Soldaten', 'Gold', 'Soldatenpässe']],
              ['Was bauten Fabriken statt Autos?', 'Panzer, Flugzeuge und Schiffe', ['Kühlschränke', 'Radios', 'Möbel']],
              ['Wie viele Menschen japanischer Herkunft wurden interniert?', 'Rund 120.000', ['Rund 1200', 'Rund 12.000', 'Rund 1,2 Millionen']],
              ['Was waren die meisten Internierten?', 'US-Bürger', ['Japanische Soldaten', 'Spione', 'Touristen']],
              ['Wann entschuldigte sich die Regierung für die Internierung?', '1988', ['1945', '1965', '2001']],
              ['Warum war Midway wichtig?', 'Wendepunkt im Pazifikkrieg', ['Erster Angriff Japans', 'Ort der Kapitulation', 'Ort der Atombombe']],
              ['Auf welchen Inseln gab es schwere Verluste?', 'Iwo Jima und Okinawa', ['Hawaii und Guam', 'Kuba und Puerto Rico', 'Hawaii und Alaska']],
              ['Wann landeten US-Truppen in Nordafrika?', '1942', ['1944', '1941', '1945']],
              ['Wann landeten US-Truppen in Italien?', '1943', ['1942', '1944', '1945']],
              ['Wann starb Roosevelt?', 'April 1945', ['Dezember 1941', 'August 1945', 'Mai 1944']],
              ['Wer arbeitete am Manhattan-Projekt mit?', 'Viele Flüchtlinge aus Europa', ['Nur Japaner', 'Nur Soldaten', 'Niemand aus Europa']],
              ['Wo fand der erste Atombombentest statt?', 'In New Mexico', ['In Nevada', 'In Kalifornien', 'Auf Hawaii']],
              ['Wann wurde Hiroshima bombardiert?', '6. August 1945', ['9. August 1945', '2. September 1945', '6. Juni 1944']],
              ['Wann wurde Nagasaki bombardiert?', '9. August 1945', ['6. August 1945', '15. August 1945', '2. September 1945']],
              ['Wie viele Menschen starben durch die Atombomben?', 'Über 200.000', ['Rund 2000', 'Rund 20.000', 'Über 2 Millionen']],
              ['Wie viele US-Soldaten starben im Krieg?', 'Rund 400.000', ['Rund 40.000', 'Rund 4 Millionen', 'Rund 4000']],
              ['Welchen Anteil der Industriegüter produzierten die USA 1945?', 'Die Hälfte', ['Ein Zehntel', 'Alles', 'Ein Viertel']],
              ['Wo wurde die UN-Charta unterzeichnet?', 'In San Francisco', ['In New York', 'In Washington', 'In Genf']],
              ['Was waren die USA nach 1945?', 'Eine Supermacht', ['Ein besiegtes Land', 'Ein neutraler Kleinstaat', 'Eine Kolonie']],
            ],
            schwer: [
              ['Warum war die USA nach dem Krieg so stark?', 'Kaum zerstört und industriell überlegen', ['Sie hatte Kolonien in Europa', 'Sie gewann Gold aus Japan', 'Zufall']],
              ['Was zeigt die Internierung der Japanischstämmigen?', 'Ein Unrecht gegen eigene Bürger aus Angst', ['Eine notwendige Maßnahme ohne Kritik', 'Einen Spionagefall', 'Nichts']],
              ['Was symbolisiert „Rosie the Riveter“?', 'Frauen in der Kriegsindustrie', ['Krankenschwestern', 'Soldatinnen an der Front', 'Filmstars']],
              ['Warum erklärten Deutschland und Italien den USA den Krieg?', 'Als Verbündete Japans', ['Weil die USA Berlin bombardierten', 'Weil die USA angriffen', 'Aus Versehen']],
              ['Was war das „Inselspringen“?', 'Schrittweise Eroberung pazifischer Inseln', ['Eine Sportart', 'Eine Flucht', 'Eine Seeblockade Japans']],
              ['Was bedeutete Lend-Lease vor Pearl Harbor?', 'Unterstützung Großbritanniens trotz Neutralität', ['Krieg gegen Deutschland', 'Neutralität ohne Hilfe', 'Bündnis mit Japan']],
              ['Was folgte auf die Atombomben?', 'Die Kapitulation Japans', ['Ein Gegenangriff Japans', 'Ein Friedensvertrag 1950', 'Nichts']],
              ['Welche Wissenschaftler halfen beim Manhattan-Projekt besonders?', 'Flüchtlinge aus Europa', ['Japanische Physiker', 'Sowjetische Forscher', 'Keine']],
              ['Welche Rolle spielte Eisenhower später?', 'Er wurde Präsident', ['Er wurde UNO-Chef', 'Er wurde Kanzler', 'Keine']],
              ['Welches Ereignis brachte die USA in den Krieg?', 'Pearl Harbor', ['D-Day', 'Midway', 'Hiroshima']],
              ['Wo hatte die UNO ihren Gründungsort?', 'San Francisco', ['Genf', 'Paris', 'London']],
              ['Welche Insel war Schauplatz einer berühmten Flaggenhissung?', 'Iwo Jima', ['Okinawa', 'Midway', 'Hawaii']],
              ['Wann war der erste Atombombentest?', 'Juli 1945', ['August 1945', 'Mai 1945', 'Dezember 1944']],
              ['Wer warf die Atombomben ab?', 'Ein US-Bomber', ['Die Sowjetunion', 'Großbritannien', 'Japan selbst']],
              ['Welches Ziel hatte Lend-Lease?', 'Großbritannien im Krieg zu halten', ['Japan zu helfen', 'Gold zu verdienen', 'Mexiko zu stärken']],
              ['Welche Folge hatte die Kriegswirtschaft für Frauen?', 'Millionen arbeiteten in der Industrie', ['Sie verloren das Wahlrecht', 'Keine', 'Sie gingen nach Europa']],
              ['Was symbolisiert „Arsenal der Demokratie“?', 'Die USA als Waffenlieferant der Demokratien', ['Ein Waffenlager in Washington', 'Eine Fabrik', 'Ein Gesetz']],
              ['Welcher Präsident ordnete die Atombombenabwürfe an?', 'Truman', ['Roosevelt', 'Eisenhower', 'Hoover']],
              ['Wie wirkte der Krieg auf die Weltrolle der USA?', 'Sie wurden zur führenden Supermacht', ['Sie zogen sich zurück', 'Sie wurden besetzt', 'Keine Wirkung']],
              ['Wann endete der Krieg im Pazifik?', '2. September 1945', ['8. Mai 1945', '6. Juni 1944', '7. Dezember 1945']],
            ],
          },
        },
      ],
    },
  ],
};
