import type { Epoch } from '../types';

export const E5: Epoch = {
  id: 'supermacht',
  name: 'Supermacht',
  period: 'seit 1945',
  events: [
    {
      id: 'kalter-krieg',
      title: 'Kalter Krieg, Vietnam und Mondlandung',
      date: '1945–1991',
      text: [
        'Nach 1945 standen sich die USA und die Sowjetunion im Kalten Krieg gegenüber. Es ging um Einfluss in der Welt, Atomwaffen und den Wettlauf ins All – bis die Sowjetunion 1991 zerfiel.',
      ],
      subtopics: [
        {
          id: 'kalter-krieg-anfang',
          title: 'Containment, Korea und Kubakrise',
          date: '1945–1963',
          text: [
            'Präsident Harry S. Truman verkündete 1947 die „Truman-Doktrin“: Die USA würden freie Völker gegen kommunistische Bedrohung unterstützen („Containment“, Eindämmung). Mit dem Marshallplan halfen sie ab 1948 beim Wiederaufbau Westeuropas mit rund 13 Milliarden Dollar. Während der Berlin-Blockade 1948/49 versorgten amerikanische und britische Flugzeuge West-Berlin über die „Luftbrücke“. 1949 gründeten die USA mit westeuropäischen Staaten und Kanada die NATO.',
            '1950 überfiel das kommunistische Nordkorea den Süden. Im Koreakrieg kämpften US-Truppen unter UNO-Flagge; nach drei Jahren und Millionen Toten endete er 1953 mit einem Waffenstillstand ungefähr an der alten Grenze, dem 38. Breitengrad. In den USA führte Senator Joseph McCarthy eine Hetzjagd auf angebliche Kommunisten („McCarthyismus“), bei der viele, auch Hollywood-Künstler, ihre Arbeit verloren.',
            'Der Kriegsheld Dwight D. Eisenhower war 1953–1961 Präsident. Als die Sowjetunion 1957 mit „Sputnik“ den ersten Satelliten ins All schoss, löste das den „Sputnik-Schock“ aus; die USA gründeten 1958 die Raumfahrtbehörde NASA und investierten in Bildung. Vorstädte („Suburbs“) wuchsen, Fernseher und Autos wurden Standard; der Rock’n’Roll von Elvis Presley begeisterte die Jugend.',
            '1960 wurde der 43-jährige John F. Kennedy der jüngste gewählte Präsident. 1961 scheiterte eine von der CIA organisierte Invasion von Exilkubanern in der Schweinebucht. Im Oktober 1962 entdeckten US-Aufklärungsflugzeuge sowjetische Atomraketen auf Kuba. 13 Tage lang stand die Welt in der „Kubakrise“ am Rand eines Atomkriegs, bis Chruschtschow die Raketen abzog; die USA zogen im Gegenzug heimlich ihre Raketen aus der Türkei ab. 1963 sagte Kennedy in West-Berlin: „Ich bin ein Berliner.“',
            'Am 22. November 1963 wurde Kennedy in Dallas (Texas) während einer Fahrt im offenen Wagen erschossen. Als Täter galt Lee Harvey Oswald, der zwei Tage später selbst erschossen wurde. Um den Mord ranken sich bis heute zahlreiche Verschwörungstheorien. Vizepräsident Lyndon B. Johnson übernahm das Amt.',
          ],
          quiz: {
            leicht: [
              ['Welcher Präsident verkündete 1947 eine Doktrin gegen den Kommunismus?', 'Harry S. Truman', ['Franklin D. Roosevelt', 'Dwight D. Eisenhower', 'John F. Kennedy']],
              ['Wie nennt man die Politik der Eindämmung?', 'Containment', ['Appeasement', 'Isolationismus', 'Détente']],
              ['Welcher Plan half beim Wiederaufbau Westeuropas?', 'Der Marshallplan', ['Der New Deal', 'Der Morgenthau-Plan', 'Der Schlieffen-Plan']],
              ['Wie wurde West-Berlin 1948/49 versorgt?', 'Über die Luftbrücke', ['Über einen Tunnel', 'Über die Ostsee', 'Gar nicht']],
              ['Welches Bündnis gründeten die USA 1949?', 'Die NATO', ['Den Warschauer Pakt', 'Die UNO', 'Die EU']],
              ['Welches Land überfiel 1950 Südkorea?', 'Nordkorea', ['China', 'Japan', 'Die Sowjetunion direkt']],
              ['Unter welcher Flagge kämpften US-Truppen in Korea?', 'Unter UNO-Flagge', ['Unter NATO-Flagge', 'Unter britischer Flagge', 'Unter koreanischer Flagge']],
              ['An welchem Breitengrad liegt die Grenze in Korea etwa?', 'Am 38. Breitengrad', ['Am 17. Breitengrad', 'Am 50. Breitengrad', 'Am Äquator']],
              ['Welcher Senator jagte angebliche Kommunisten?', 'Joseph McCarthy', ['Richard Nixon', 'Robert Kennedy', 'Barry Goldwater']],
              ['Wer war 1953–1961 Präsident?', 'Dwight D. Eisenhower', ['Harry Truman', 'John F. Kennedy', 'Richard Nixon']],
              ['Welcher Satellit löste 1957 einen Schock aus?', 'Sputnik', ['Apollo', 'Explorer', 'Hubble']],
              ['Welche Behörde gründeten die USA 1958?', 'Die NASA', ['Die CIA', 'Das FBI', 'Die NSA']],
              ['Wer begeisterte die Jugend mit Rock’n’Roll?', 'Elvis Presley', ['Frank Sinatra', 'Louis Armstrong', 'Bob Dylan']],
              ['Wer wurde 1960 jüngster gewählter Präsident?', 'John F. Kennedy', ['Lyndon B. Johnson', 'Richard Nixon', 'Bill Clinton']],
              ['Wo scheiterte 1961 eine Invasion auf Kuba?', 'In der Schweinebucht', ['In Havanna', 'In Guantánamo', 'Auf Hawaii']],
              ['Wann war die Kubakrise?', 'Oktober 1962', ['November 1963', 'Juni 1961', 'Juli 1969']],
              ['Was entdeckten US-Flugzeuge auf Kuba?', 'Sowjetische Atomraketen', ['Ein Ölfeld', 'Eine Goldmine', 'Ein Goldschatz']],
              ['Was sagte Kennedy 1963 in West-Berlin?', '„Ich bin ein Berliner“', ['„Reißen Sie diese Mauer nieder“', '„Yes we can“', '„Ich habe einen Traum“']],
              ['Wo wurde Kennedy erschossen?', 'In Dallas', ['In Washington', 'In New York', 'In Berlin']],
              ['Wer übernahm nach Kennedys Tod?', 'Lyndon B. Johnson', ['Richard Nixon', 'Robert Kennedy', 'Gerald Ford']],
            ],
            mittel: [
              ['Wann verkündete Truman seine Doktrin?', '1947', ['1945', '1949', '1950']],
              ['Wie viel Geld umfasste der Marshallplan etwa?', 'Rund 13 Milliarden Dollar', ['Rund 13 Millionen', 'Rund 130 Milliarden', 'Rund 1,3 Milliarden']],
              ['Ab wann lief der Marshallplan?', '1948', ['1945', '1952', '1947']],
              ['Wer versorgte West-Berlin über die Luftbrücke?', 'Amerikanische und britische Flugzeuge', ['Sowjetische Flugzeuge', 'Französische Schiffe', 'Deutsche Züge']],
              ['Wer gründete die NATO mit den USA?', 'Westeuropäische Staaten und Kanada', ['Die Sowjetunion', 'China', 'Japan']],
              ['Wie lange dauerte der Koreakrieg?', 'Drei Jahre', ['Drei Monate', 'Zehn Jahre', 'Einen Tag']],
              ['Wie endete der Koreakrieg?', 'Mit einem Waffenstillstand', ['Mit einem Friedensvertrag', 'Mit der Einigung Koreas', 'Mit einem Atomangriff']],
              ['Wann endete der Koreakrieg?', '1953', ['1950', '1960', '1945']],
              ['Wer verlor durch den McCarthyismus Arbeit?', 'Auch Hollywood-Künstler', ['Nur Soldaten', 'Nur Kommunisten in Moskau', 'Niemand']],
              ['Wann flog Sputnik?', '1957', ['1961', '1969', '1949']],
              ['Worin investierten die USA nach dem Sputnik-Schock?', 'In Bildung', ['In Landwirtschaft', 'In Kolonien', 'In Prohibition']],
              ['Was wuchs in den 1950ern?', 'Vorstädte (Suburbs)', ['Dörfer', 'Plantagen', 'Kolonien']],
              ['Wie alt war Kennedy bei der Wahl?', '43', ['33', '53', '63']],
              ['Wer organisierte die Invasion in der Schweinebucht?', 'Die CIA', ['Das Militär offen', 'Die NASA', 'Die UNO']],
              ['Wer landete in der Schweinebucht?', 'Exilkubaner', ['US-Marines', 'Sowjetische Soldaten', 'Mexikaner']],
              ['Wie lange dauerte die Kubakrise?', '13 Tage', ['13 Monate', '3 Tage', '30 Tage']],
              ['Wer zog die Raketen von Kuba ab?', 'Chruschtschow', ['Stalin', 'Castro', 'Breschnew']],
              ['Was zogen die USA im Gegenzug heimlich ab?', 'Raketen aus der Türkei', ['Truppen aus Deutschland', 'Schiffe aus Japan', 'Nichts']],
              ['Wann wurde Kennedy erschossen?', '22. November 1963', ['4. April 1968', '22. Oktober 1962', '20. Juli 1969']],
              ['Wer galt als Kennedys Mörder?', 'Lee Harvey Oswald', ['Jack Ruby', 'James Earl Ray', 'John Wilkes Booth']],
            ],
            schwer: [
              ['Was bedeutete „Containment“?', 'Die Ausbreitung des Kommunismus einzudämmen', ['Den Kommunismus zu unterstützen', 'Sich aus der Welt zurückzuziehen', 'Krieg gegen China']],
              ['Warum war die Kubakrise so gefährlich?', 'Die Welt stand am Rand eines Atomkriegs', ['Kuba griff Florida an', 'Es gab einen Bürgerkrieg in den USA', 'Nichts']],
              ['Was beendete die Kubakrise?', 'Ein Abzug der Raketen auf beiden Seiten', ['Ein Atomschlag', 'Eine Invasion Kubas', 'Castros Sturz']],
              ['Was zeigte der Sputnik-Schock?', 'Die Angst, technologisch hinter der Sowjetunion zu liegen', ['Freude über Raumfahrt', 'Nichts', 'Den Sieg der USA im All']],
              ['Was war der McCarthyismus?', 'Eine Hetzjagd auf angebliche Kommunisten', ['Eine Friedensbewegung', 'Ein Wirtschaftsprogramm', 'Eine Raumfahrtmission']],
              ['Was geschah mit Oswald?', 'Er wurde zwei Tage später erschossen', ['Er wurde verurteilt', 'Er floh nach Kuba', 'Er gestand vor Gericht']],
              ['Warum gibt es zum Kennedy-Mord Verschwörungstheorien?', 'Weil der Täter selbst getötet wurde und Fragen offen blieben', ['Weil er nie starb', 'Weil er in Berlin starb', 'Weil es kein Video gab']],
              ['Was war die Schweinebucht für Kennedy?', 'Eine peinliche Niederlage', ['Ein Sieg', 'Ein Friedensvertrag', 'Ein Urlaub']],
              ['Was bedeutete „Ich bin ein Berliner“?', 'Solidarität mit dem eingeschlossenen West-Berlin', ['Kennedy war Deutscher', 'Ein Witz über Gebäck', 'Eine Kriegserklärung']],
              ['Welche Rolle spielte die Luftbrücke?', 'Sie verhinderte, dass West-Berlin an die Sowjets fiel', ['Sie brachte Truppen nach Moskau', 'Sie war ein Bombardement', 'Keine']],
              ['Welcher Krieg war der erste große „heiße“ Konflikt des Kalten Krieges?', 'Der Koreakrieg', ['Der Vietnamkrieg', 'Die Kubakrise', 'Der Golfkrieg']],
              ['Was war der Zweck des Marshallplans politisch?', 'Westeuropa stabilisieren gegen den Kommunismus', ['Deutschland bestrafen', 'Kolonien kaufen', 'Die Sowjetunion stärken']],
              ['Wer war Eisenhower vor seiner Präsidentschaft?', 'Kriegsheld (Oberbefehlshaber im Zweiten Weltkrieg)', ['Schauspieler', 'Senator aus Texas', 'Gouverneur von Kalifornien']],
              ['Welche Lebensweise entstand in den 1950ern?', 'Leben in Vorstädten mit Auto und Fernseher', ['Leben auf Farmen', 'Leben in Mietskasernen', 'Nomadenleben']],
              ['Welches Ereignis führte zur Gründung der NASA?', 'Der Sputnik-Schock', ['Die Mondlandung', 'Die Kubakrise', 'Der Koreakrieg']],
              ['Wie nennt man die Konfrontation USA–Sowjetunion?', 'Kalter Krieg', ['Großer Krieg', 'Hundertjähriger Krieg', 'Dritter Weltkrieg']],
              ['Wann wurde die NATO gegründet?', '1949', ['1945', '1955', '1961']],
              ['Welche Stadt wurde 1948/49 blockiert?', 'West-Berlin', ['Wien', 'Paris', 'Seoul']],
              ['Wie lautete Trumans Versprechen?', 'Freie Völker gegen den Kommunismus zu unterstützen', ['Alle Kolonien freizugeben', 'Die Sowjetunion anzugreifen', 'Neutral zu bleiben']],
              ['Wo gab es US-Raketen, die heimlich abgezogen wurden?', 'In der Türkei', ['In Kuba', 'In Japan', 'In Kanada']],
            ],
          },
        },
        {
          id: 'vietnam-mond',
          title: 'Vietnam, Mondlandung, Watergate und das Ende des Kalten Krieges',
          date: '1964–1991',
          text: [
            'Um die Ausbreitung des Kommunismus in Südostasien zu verhindern („Dominotheorie“), schickten die USA immer mehr Soldaten nach Südvietnam, 1968 über eine halbe Million. Gegen die kommunistischen Vietcong und Nordvietnam kämpften sie in Dschungel und Reisfeldern; Bombenangriffe und das Entlaubungsmittel „Agent Orange“ verwüsteten das Land. Die „Tet-Offensive“ 1968 zeigte, dass der Krieg nicht zu gewinnen war.',
            'In den USA wuchs der Protest, besonders an Universitäten; 1970 erschossen Nationalgardisten an der Kent State University vier Studenten. Die Hippie-Bewegung und das Woodstock-Festival 1969 standen für „Peace and Love“. 1973 zogen die USA ihre Truppen ab, 1975 eroberte Nordvietnam Saigon, das heute Ho-Chi-Minh-Stadt heißt. Rund 58.000 Amerikaner und Millionen Vietnamesen waren gestorben.',
            'Am 20. Juli 1969 landete Apollo 11 auf dem Mond. Neil Armstrong betrat als erster Mensch die Mondoberfläche: „Das ist ein kleiner Schritt für einen Menschen, aber ein riesiger Sprung für die Menschheit.“ Mit Buzz Aldrin sammelte er Gestein, Michael Collins blieb in der Kapsel. Rund 600 Millionen Menschen sahen live im Fernsehen zu. Bis 1972 betraten zwölf Astronauten den Mond.',
            'Präsident Richard Nixon öffnete 1972 die Beziehungen zu China und schloss Abrüstungsverträge mit der Sowjetunion. Doch in der „Watergate-Affäre“ kam heraus, dass Nixons Mitarbeiter 1972 in das Hauptquartier der Demokraten eingebrochen waren und er die Vertuschung unterstützt hatte. Die Reporter Bob Woodward und Carl Bernstein von der „Washington Post“ deckten den Skandal auf. 1974 trat Nixon als bisher einziger Präsident zurück.',
            'Der frühere Schauspieler Ronald Reagan (1981–1989) rüstete stark auf und nannte die Sowjetunion ein „Reich des Bösen“. 1987 forderte er in Berlin: „Mr. Gorbatschow, reißen Sie diese Mauer nieder!“ Zugleich schloss er mit Michail Gorbatschow Abrüstungsverträge. 1989 fiel die Berliner Mauer, 1991 zerfiel die Sowjetunion. Die USA waren nun die einzige Supermacht.',
          ],
          quiz: {
            leicht: [
              ['In welches Land schickten die USA Soldaten gegen den Kommunismus in Südostasien?', 'Vietnam', ['Korea', 'Kuba', 'Thailand']],
              ['Wie hieß die Theorie, nach der Länder nacheinander kommunistisch würden?', 'Dominotheorie', ['Kartenhaustheorie', 'Kettentheorie', 'Brückentheorie']],
              ['Wie viele US-Soldaten waren 1968 in Vietnam?', 'Über eine halbe Million', ['Rund 5000', 'Rund 50.000', 'Über fünf Millionen']],
              ['Wie hießen die kommunistischen Kämpfer in Südvietnam?', 'Vietcong', ['Rote Khmer', 'Taliban', 'Mujaheddin']],
              ['Welches Entlaubungsmittel wurde eingesetzt?', 'Agent Orange', ['Napalm', 'DDT', 'Senfgas']],
              ['Welche Offensive 1968 zeigte die Aussichtslosigkeit?', 'Die Tet-Offensive', ['Die Ardennenoffensive', 'Die Frühjahrsoffensive', 'Operation Desert Storm']],
              ['An welcher Universität wurden 1970 Studenten erschossen?', 'Kent State', ['Harvard', 'Berkeley', 'Yale']],
              ['Welches Festival stand 1969 für „Peace and Love“?', 'Woodstock', ['Coachella', 'Live Aid', 'Glastonbury']],
              ['Wann zogen die USA ihre Truppen aus Vietnam ab?', '1973', ['1968', '1975', '1980']],
              ['Wann eroberte Nordvietnam Saigon?', '1975', ['1973', '1968', '1980']],
              ['Wie viele Amerikaner starben in Vietnam etwa?', 'Rund 58.000', ['Rund 5800', 'Rund 580.000', 'Rund 580']],
              ['Wann landete Apollo 11 auf dem Mond?', '20. Juli 1969', ['4. Oktober 1957', '12. April 1961', '22. November 1963']],
              ['Wer betrat als Erster den Mond?', 'Neil Armstrong', ['Buzz Aldrin', 'Michael Collins', 'Juri Gagarin']],
              ['Was sagte Armstrong auf dem Mond?', '„Ein kleiner Schritt für einen Menschen, ein riesiger Sprung für die Menschheit“', ['„Houston, wir haben ein Problem“', '„Ich bin ein Berliner“', '„Yes we can“']],
              ['Wie viele Astronauten betraten bis 1972 den Mond?', 'Zwölf', ['Zwei', 'Hundert', 'Drei']],
              ['Welcher Präsident trat 1974 zurück?', 'Richard Nixon', ['Gerald Ford', 'Lyndon B. Johnson', 'Jimmy Carter']],
              ['Wie heißt der Skandal um Nixon?', 'Watergate', ['Irangate', 'Lewinsky-Affäre', 'Teapot Dome']],
              ['Welche Zeitung deckte Watergate auf?', 'Die Washington Post', ['Die New York Times', 'Die Chicago Tribune', 'Das Wall Street Journal']],
              ['Welcher frühere Schauspieler wurde 1981 Präsident?', 'Ronald Reagan', ['Arnold Schwarzenegger', 'John Wayne', 'Clint Eastwood']],
              ['Wann fiel die Berliner Mauer?', '1989', ['1987', '1991', '1961']],
            ],
            mittel: [
              ['Wo kämpften US-Soldaten in Vietnam?', 'In Dschungel und Reisfeldern', ['In Wüsten', 'Im Eis', 'In Städten Europas']],
              ['Was verwüstete Vietnam außer Bomben?', 'Agent Orange', ['Ein Erdbeben', 'Eine Flut', 'Ein Vulkan']],
              ['Wann war die Tet-Offensive?', '1968', ['1965', '1973', '1975']],
              ['Wo wuchs der Protest besonders?', 'An Universitäten', ['In Kasernen', 'In Kasinos', 'Auf dem Land']],
              ['Wer erschoss die Studenten in Kent State?', 'Nationalgardisten', ['Polizisten aus Vietnam', 'Studenten', 'Der FBI']],
              ['Wie viele Studenten starben in Kent State?', 'Vier', ['Vierzig', 'Einer', 'Vierhundert']],
              ['Wer starb in Vietnam außer Amerikanern?', 'Millionen Vietnamesen', ['Niemand', 'Tausende Schweizer', 'Hunderte Briten']],
              ['Wer begleitete Armstrong auf dem Mond?', 'Buzz Aldrin', ['Michael Collins', 'John Glenn', 'Alan Shepard']],
              ['Wer blieb in der Kapsel?', 'Michael Collins', ['Buzz Aldrin', 'Neil Armstrong', 'Jim Lovell']],
              ['Wie viele Menschen sahen die Mondlandung live?', 'Rund 600 Millionen', ['Rund 6 Millionen', 'Rund 6 Milliarden', 'Rund 60.000']],
              ['Bis wann flogen Menschen zum Mond?', '1972', ['1969', '1980', '2000']],
              ['Zu welchem Land öffnete Nixon 1972 die Beziehungen?', 'Zu China', ['Zu Kuba', 'Zu Vietnam', 'Zu Nordkorea']],
              ['Was schloss Nixon mit der Sowjetunion?', 'Abrüstungsverträge', ['Ein Militärbündnis', 'Einen Handelskrieg', 'Nichts']],
              ['Wo brachen Nixons Mitarbeiter ein?', 'Im Hauptquartier der Demokraten', ['Im Kreml', 'In der CIA', 'Im Weißen Haus']],
              ['Welche Reporter deckten Watergate auf?', 'Bob Woodward und Carl Bernstein', ['Walter Cronkite und Dan Rather', 'Woodward und Rather', 'Hunter S. Thompson']],
              ['Was ist an Nixons Rücktritt einzigartig?', 'Einziger Präsident, der zurücktrat', ['Erster ermordeter Präsident', 'Jüngster Präsident', 'Er trat zweimal zurück']],
              ['Wie nannte Reagan die Sowjetunion?', '„Reich des Bösen“', ['„Freund des Westens“', '„Großer Bruder“', '„Bester Freund“']],
              ['Was forderte Reagan 1987 in Berlin?', 'Gorbatschow solle die Mauer niederreißen', ['Die Mauer solle höher werden', 'Berlin solle geteilt bleiben', 'Nichts']],
              ['Mit wem schloss Reagan Abrüstungsverträge?', 'Mit Michail Gorbatschow', ['Mit Breschnew', 'Mit Chruschtschow', 'Mit Jelzin']],
              ['Wann zerfiel die Sowjetunion?', '1991', ['1989', '1985', '1993']],
            ],
            schwer: [
              ['Warum scheiterten die USA in Vietnam?', 'Der Krieg war militärisch und politisch nicht zu gewinnen', ['Sie hatten zu wenig Waffen', 'China griff die USA an', 'Sie siegten eigentlich']],
              ['Was zeigte die Tet-Offensive der Öffentlichkeit?', 'Dass der Krieg nicht zu gewinnen war', ['Dass der Krieg bald gewonnen war', 'Dass Vietnam neutral war', 'Nichts']],
              ['Was symbolisiert Woodstock?', 'Die Gegenkultur der Hippies', ['Den Krieg', 'Die Mondlandung', 'Die Prohibition']],
              ['Was bewies die Mondlandung im Kalten Krieg?', 'Den Sieg der USA im Wettlauf ins All', ['Eine Niederlage der USA', 'Zusammenarbeit mit der Sowjetunion', 'Nichts']],
              ['Was bedeutet Watergate für die Pressefreiheit?', 'Journalisten deckten Machtmissbrauch auf', ['Die Presse wurde verboten', 'Die Presse half Nixon', 'Nichts']],
              ['Was unterstützte Nixon bei Watergate?', 'Die Vertuschung', ['Die Aufklärung', 'Die Verhaftung der Täter', 'Nichts']],
              ['Welche Doppelstrategie verfolgte Reagan?', 'Aufrüstung und Abrüstungsverträge', ['Nur Abrüstung', 'Nur Krieg', 'Isolation']],
              ['Was waren die USA nach 1991?', 'Die einzige Supermacht', ['Eine von zwei Supermächten', 'Ein Kleinstaat', 'Teil der Sowjetunion']],
              ['Welches Ereignis 1989 kündigte das Ende des Kalten Krieges an?', 'Der Fall der Berliner Mauer', ['Die Mondlandung', 'Watergate', 'Woodstock']],
              ['Wann besuchte Nixon China?', '1972', ['1969', '1974', '1979']],
              ['Welche Stadt wurde 1975 erobert und umbenannt?', 'Saigon (heute Ho-Chi-Minh-Stadt)', ['Hanoi', 'Hue', 'Da Nang']],
              ['Welche Folge hatte der Vietnamkrieg innenpolitisch?', 'Tiefe Spaltung der Gesellschaft', ['Große Einigkeit', 'Keine', 'Wirtschaftsboom ohne Kritik']],
              ['Wann trat Nixon zurück?', '1974', ['1972', '1976', '1969']],
              ['Wie hieß die Mondmission von 1969?', 'Apollo 11', ['Apollo 13', 'Gemini 4', 'Mercury 7']],
              ['Was sammelten Armstrong und Aldrin?', 'Mondgestein', ['Wasser', 'Pflanzen', 'Tiere']],
              ['Warum war Vietnam Teil des Kalten Krieges?', 'Kampf gegen kommunistische Ausbreitung', ['Kampf um Öl', 'Kampf gegen Japan', 'Kampf um Gold']],
              ['Was war Reagans Beruf vor der Politik?', 'Schauspieler', ['General', 'Astronaut', 'Journalist']],
              ['Welcher Satz Reagans steht für das Ende des Kalten Krieges?', '„Reißen Sie diese Mauer nieder!“', ['„Ich bin ein Berliner“', '„Das Einzige, was wir fürchten müssen“', '„Yes we can“']],
              ['Wie viele Menschen landeten mit Apollo 11 auf dem Mond?', 'Zwei', ['Drei', 'Einer', 'Zwölf']],
              ['Welches Symbol hatte die Protestbewegung?', '„Peace and Love“', ['„Law and Order“', '„God and Country“', '„Gold and Glory“']],
            ],
          },
        },
      ],
    },
    {
      id: 'buergerrechte',
      title: 'Die Bürgerrechtsbewegung',
      date: '1954–1968',
      text: [
        'Fast 100 Jahre nach dem Ende der Sklaverei lebten Afroamerikaner im Süden noch immer unter Rassentrennung. Mit gewaltlosem Widerstand erkämpfte die Bürgerrechtsbewegung unter Martin Luther King gleiche Rechte.',
      ],
      subtopics: [
        {
          id: 'buergerrechte-king',
          title: 'Rosa Parks, Martin Luther King und „I Have a Dream“',
          date: '1954–1968',
          text: [
            'Im Süden galten „Jim-Crow-Gesetze“: getrennte Schulen, Busse, Restaurants, Toiletten und Trinkbrunnen für Weiße und Schwarze. 1954 erklärte der Oberste Gerichtshof im Urteil „Brown gegen Board of Education“ getrennte Schulen für verfassungswidrig. Als 1957 neun schwarze Schüler die Central High School in Little Rock (Arkansas) besuchen wollten, schickte Präsident Eisenhower Fallschirmjäger, um sie zu schützen.',
            'Am 1. Dezember 1955 weigerte sich die Näherin Rosa Parks in Montgomery (Alabama), ihren Sitzplatz im Bus für einen Weißen zu räumen, und wurde verhaftet. Daraufhin boykottierten die Schwarzen Montgomerys über ein Jahr lang die Busse, angeführt vom jungen Pastor Martin Luther King Jr. 1956 erklärte das Oberste Gericht die Rassentrennung in Bussen für verfassungswidrig.',
            'King setzte nach dem Vorbild Mahatma Gandhis auf gewaltlosen Widerstand: Sitzstreiks in „Nur-Weiße“-Restaurants, „Freedom Rides“ in Bussen, Märsche. In Birmingham (Alabama) setzte die Polizei 1963 Hunde und Wasserwerfer gegen demonstrierende Kinder ein; die Bilder schockierten das Land. Am 28. August 1963 hielt King beim „Marsch auf Washington“ vor über 250.000 Menschen am Lincoln Memorial seine Rede „I Have a Dream“: Er träume davon, dass seine Kinder nicht nach ihrer Hautfarbe, sondern nach ihrem Charakter beurteilt würden.',
            '1964 verbot der unter Präsident Lyndon B. Johnson beschlossene „Civil Rights Act“ die Rassentrennung in öffentlichen Einrichtungen und Diskriminierung bei der Arbeit; King erhielt den Friedensnobelpreis. 1965 marschierten Demonstranten von Selma nach Montgomery für das Wahlrecht; am „Bloody Sunday“ schlug die Polizei sie auf der Edmund-Pettus-Brücke nieder. Im selben Jahr garantierte der „Voting Rights Act“ Schwarzen tatsächlich das Wahlrecht.',
            'Nicht alle setzten auf Gewaltlosigkeit: Malcolm X forderte Selbstbewusstsein und Selbstverteidigung der Schwarzen; er wurde 1965 ermordet. Später entstand die „Black Power“-Bewegung und die Black Panther Party. Am 4. April 1968 wurde Martin Luther King in Memphis (Tennessee) von James Earl Ray erschossen; in vielen Städten kam es zu Unruhen. Seit 1986 ist der dritte Montag im Januar „Martin Luther King Day“, ein nationaler Feiertag.',
          ],
          quiz: {
            leicht: [
              ['Wie hießen die Rassentrennungsgesetze im Süden?', 'Jim-Crow-Gesetze', ['Homestead Codes', 'Bill of Rights', 'Homestead Acts']],
              ['Welches Urteil erklärte getrennte Schulen 1954 für verfassungswidrig?', 'Brown gegen Board of Education', ['Dred Scott', 'Roe gegen Wade', 'Plessy gegen Ferguson']],
              ['In welcher Stadt wollten neun schwarze Schüler 1957 zur Schule?', 'Little Rock', ['Montgomery', 'Selma', 'Memphis']],
              ['Wen schickte Eisenhower nach Little Rock?', 'Fallschirmjäger', ['Polizisten', 'Lehrer', 'Niemanden']],
              ['Wer weigerte sich 1955, ihren Sitzplatz zu räumen?', 'Rosa Parks', ['Harriet Tubman', 'Coretta Scott King', 'Michelle Obama']],
              ['In welcher Stadt geschah das?', 'Montgomery (Alabama)', ['Atlanta', 'Birmingham', 'Little Rock']],
              ['Was folgte auf Rosa Parks’ Verhaftung?', 'Ein Busboykott', ['Ein Krieg', 'Ein Streik der Fabriken', 'Nichts']],
              ['Wer führte den Busboykott an?', 'Martin Luther King Jr.', ['Malcolm X', 'Frederick Douglass', 'Barack Obama']],
              ['Welchen Beruf hatte King?', 'Pastor', ['Anwalt', 'Lehrer', 'Arzt']],
              ['Nach wessen Vorbild setzte King auf Gewaltlosigkeit?', 'Mahatma Gandhi', ['Nelson Mandela', 'Abraham Lincoln', 'Malcolm X']],
              ['Wie heißt Kings berühmte Rede?', '„I Have a Dream“', ['„Yes We Can“', '„Ich bin ein Berliner“', '„Gettysburg Address“']],
              ['Wann hielt King die Rede?', '28. August 1963', ['4. April 1968', '1. Dezember 1955', '4. Juli 1964']],
              ['Wo hielt King die Rede?', 'Am Lincoln Memorial in Washington', ['In Montgomery', 'In Memphis', 'Im Weißen Haus']],
              ['Welches Gesetz verbot 1964 die Rassentrennung?', 'Civil Rights Act', ['Voting Rights Act', 'Homestead Act', 'New Deal']],
              ['Welchen Preis erhielt King 1964?', 'Den Friedensnobelpreis', ['Einen Oscar', 'Den Pulitzer-Preis', 'Keinen']],
              ['Welches Gesetz garantierte 1965 das Wahlrecht?', 'Voting Rights Act', ['Civil Rights Act', 'Bill of Rights', 'Patriot Act']],
              ['Welcher Bürgerrechtler forderte Selbstverteidigung?', 'Malcolm X', ['Martin Luther King', 'Rosa Parks', 'John Lewis']],
              ['Wann wurde King ermordet?', '4. April 1968', ['22. November 1963', '21. Februar 1965', '28. August 1963']],
              ['Wo wurde King ermordet?', 'In Memphis', ['In Washington', 'In Atlanta', 'In Selma']],
              ['Welcher Feiertag erinnert an King?', 'Martin Luther King Day', ['Thanksgiving', 'Labor Day', 'Memorial Day']],
            ],
            mittel: [
              ['Was war nach den Jim-Crow-Gesetzen getrennt?', 'Schulen, Busse, Restaurants und Toiletten', ['Nur Kirchen', 'Nur Züge', 'Nichts']],
              ['In welchem Staat liegt Little Rock?', 'Arkansas', ['Alabama', 'Mississippi', 'Georgia']],
              ['Welche Schule war betroffen?', 'Die Central High School', ['Harvard', 'Ole Miss', 'Howard University']],
              ['Wann weigerte sich Rosa Parks?', '1. Dezember 1955', ['28. August 1963', '4. April 1968', '1. Januar 1960']],
              ['Welchen Beruf hatte Rosa Parks?', 'Näherin', ['Lehrerin', 'Anwältin', 'Krankenschwester']],
              ['Wie lange dauerte der Busboykott?', 'Über ein Jahr', ['Einen Tag', 'Eine Woche', 'Zehn Jahre']],
              ['Was entschied das Oberste Gericht 1956?', 'Rassentrennung in Bussen ist verfassungswidrig', ['Busse sind verboten', 'Parks muss Strafe zahlen', 'Nichts']],
              ['Welche Protestformen nutzte die Bewegung?', 'Sitzstreiks, Freedom Rides und Märsche', ['Bomben', 'Bewaffnete Aufstände', 'Streiks der Armee']],
              ['Was setzte die Polizei 1963 in Birmingham ein?', 'Hunde und Wasserwerfer', ['Panzer', 'Flugzeuge', 'Kanonen']],
              ['Gegen wen richteten sich die Hunde in Birmingham?', 'Gegen demonstrierende Kinder', ['Gegen Soldaten', 'Gegen Polizisten', 'Gegen Diebe']],
              ['Wie viele Menschen nahmen am Marsch auf Washington teil?', 'Über 250.000', ['Rund 2500', 'Rund 25.000', 'Über 2,5 Millionen']],
              ['Wovon träumte King?', 'Dass seine Kinder nach ihrem Charakter beurteilt würden', ['Von Reichtum', 'Von einem eigenen Staat', 'Von der Präsidentschaft']],
              ['Was verbot der Civil Rights Act außerdem?', 'Diskriminierung bei der Arbeit', ['Waffenbesitz', 'Alkohol', 'Einwanderung']],
              ['Von wo nach wo marschierten Demonstranten 1965?', 'Von Selma nach Montgomery', ['Von Memphis nach Atlanta', 'Von New York nach Washington', 'Von Little Rock nach Dallas']],
              ['Wofür marschierten sie 1965?', 'Für das Wahlrecht', ['Gegen den Vietnamkrieg', 'Für Gold', 'Für Steuersenkungen']],
              ['Wo schlug die Polizei am Bloody Sunday zu?', 'Auf der Edmund-Pettus-Brücke', ['Am Lincoln Memorial', 'In Memphis', 'In Little Rock']],
              ['Wann wurde Malcolm X ermordet?', '1965', ['1968', '1963', '1970']],
              ['Welche Bewegung entstand später?', 'Black Power und die Black Panther Party', ['Die Prohibitionsbewegung', 'Der Ku-Klux-Klan', 'Die Tea Party']],
              ['Wer erschoss Martin Luther King?', 'James Earl Ray', ['Lee Harvey Oswald', 'Sirhan Sirhan', 'John Wilkes Booth']],
              ['Seit wann ist Martin Luther King Day Feiertag?', 'Seit 1986', ['Seit 1968', 'Seit 1964', 'Seit 2000']],
            ],
            schwer: [
              ['Warum war Rosa Parks’ Handlung so wirksam?', 'Sie löste einen großen, erfolgreichen Boykott aus', ['Sie wurde Bürgermeisterin', 'Sie wurde Präsidentin', 'Sie führte einen Krieg']],
              ['Was war Kings Strategie?', 'Gewaltloser Widerstand', ['Bewaffneter Kampf', 'Auswanderung nach Afrika', 'Rückzug']],
              ['Warum schockierten die Bilder aus Birmingham?', 'Die Polizei ging mit Hunden und Wasser gegen Kinder vor', ['Weil Kinder Gewalt nutzten', 'Weil es Fälschungen waren', 'Weil King verletzt wurde']],
              ['Was war der Unterschied zwischen Civil Rights Act und Voting Rights Act?', 'Ersterer gegen Trennung und Diskriminierung, letzterer für das Wahlrecht', ['Kein Unterschied', 'Beide betrafen Schulen', 'Beide betrafen Waffen']],
              ['Wie unterschied sich Malcolm X von King?', 'Er forderte Selbstverteidigung statt Gewaltlosigkeit', ['Er war für Rassentrennung', 'Er war Weißer', 'Kein Unterschied']],
              ['Warum musste Eisenhower in Little Rock eingreifen?', 'Um schwarze Schüler gegen Widerstand zu schützen', ['Um die Schule zu schließen', 'Wegen eines Brandes', 'Wegen eines Krieges']],
              ['Was bedeutete das Urteil von 1954?', 'Ende der rechtlichen Trennung an Schulen', ['Ende der Sklaverei', 'Frauenwahlrecht', 'Nichts']],
              ['Wo liegt Memphis?', 'In Tennessee', ['In Alabama', 'In Georgia', 'In Texas']],
              ['Was geschah nach Kings Ermordung in vielen Städten?', 'Unruhen', ['Feiern', 'Nichts', 'Ein Bürgerkrieg']],
              ['Was ist der „Bloody Sunday“ von 1965?', 'Polizeigewalt gegen Wahlrechtsmarschierende in Selma', ['Ein Massaker in Irland', 'Ein Krieg', 'Ein Unfall']],
              ['Warum brauchte es 1965 noch ein Wahlrechtsgesetz?', 'Schwarzen wurde das Wahlrecht trotz Verfassung mit Tricks verwehrt', ['Sie hatten nie Wahlrecht in der Verfassung', 'Weil Frauen nicht wählten', 'Wegen Vietnam']],
              ['Was war ein „Freedom Ride“?', 'Gemeinsame Busfahrten gegen Rassentrennung', ['Ein Pferderennen', 'Eine Flucht nach Kanada', 'Ein Militärzug']],
              ['Welcher Feiertag liegt am dritten Montag im Januar?', 'Martin Luther King Day', ['Thanksgiving', 'Presidents Day', 'Memorial Day']],
              ['Wofür steht der Marsch auf Washington?', 'Den Höhepunkt der Bürgerrechtsbewegung', ['Den Beginn des Bürgerkriegs', 'Einen Militärputsch', 'Einen Streik']],
              ['In welchem Staat liegen Montgomery, Birmingham und Selma?', 'Alabama', ['Georgia', 'Mississippi', 'Tennessee']],
              ['Welcher Preis ehrte Kings Gewaltlosigkeit?', 'Der Friedensnobelpreis', ['Der Literaturnobelpreis', 'Ein Grammy', 'Keiner']],
              ['Wie lange nach der Sklavenbefreiung herrschte noch Rassentrennung?', 'Fast 100 Jahre', ['10 Jahre', '200 Jahre', 'Gar nicht']],
              ['Wer war Präsident beim Civil Rights Act 1964?', 'Lyndon B. Johnson', ['John F. Kennedy', 'Eisenhower', 'Nixon']],
              ['Welche Rolle spielte das Oberste Gericht?', 'Es erklärte Trennung für verfassungswidrig', ['Es förderte Trennung', 'Keine', 'Es verbot Boykotte']],
              ['Welches Jahr brachte zwei große Bürgerrechtsgesetze?', '1964 und 1965', ['1954 und 1955', '1968 und 1969', '1970 und 1975']],
            ],
          },
        },
      ],
    },
    {
      id: 'elfter-september',
      title: '11. September und die Gegenwart',
      date: '1991–heute',
      text: [
        'Als einzige Supermacht erlebten die USA einen Wirtschaftsboom, dann die Terroranschläge vom 11. September 2001 und lange Kriege. Barack Obama wurde erster schwarzer Präsident, Donald Trump spaltete das Land.',
      ],
      subtopics: [
        {
          id: 'neunelf-heute',
          title: '9/11, Obama und Trump',
          date: '1991–heute',
          text: [
            '1991 befreite eine von den USA geführte Koalition im Golfkrieg („Operation Desert Storm“) Kuwait vom Irak. Unter Präsident Bill Clinton (1993–2001) boomte die Wirtschaft durch das Internet; Firmen wie Microsoft, Apple, Amazon und Google aus dem „Silicon Valley“ in Kalifornien veränderten die Welt.',
            'Am 11. September 2001 entführten 19 Terroristen der islamistischen Gruppe Al-Qaida vier Passagierflugzeuge. Zwei steuerten sie in die Türme des World Trade Center in New York, die einstürzten, eines ins Verteidigungsministerium Pentagon; das vierte stürzte in Pennsylvania ab, nachdem Passagiere sich wehrten. Fast 3000 Menschen starben. Präsident George W. Bush erklärte den „Krieg gegen den Terror“.',
            'Die USA griffen noch 2001 Afghanistan an, wo die Taliban Al-Qaida-Chef Osama bin Laden Unterschlupf gewährt hatten. 2003 marschierten sie mit Verbündeten in den Irak ein, angeblich wegen Massenvernichtungswaffen, die nie gefunden wurden; Saddam Hussein wurde gestürzt. 2011 töteten US-Spezialkräfte bin Laden in Pakistan. 2021 zogen die USA chaotisch aus Afghanistan ab, und die Taliban übernahmen wieder die Macht.',
            '2008 löste der Zusammenbruch der Bank Lehman Brothers eine weltweite Finanzkrise aus. Im selben Jahr wurde Barack Obama mit dem Slogan „Yes We Can“ zum ersten afroamerikanischen Präsidenten gewählt. Er führte eine Krankenversicherung für Millionen Unversicherte ein („Obamacare“) und erhielt 2009 den Friedensnobelpreis. 2015 erlaubte der Oberste Gerichtshof die gleichgeschlechtliche Ehe im ganzen Land.',
            '2016 gewann der Unternehmer Donald Trump mit „America First“ und „Make America Great Again“ überraschend die Wahl. 2020 verlor er gegen Joe Biden, erkannte die Niederlage aber nicht an; am 6. Januar 2021 stürmten seine Anhänger das Kapitol in Washington. Die Corona-Pandemie forderte in den USA über eine Million Tote. 2024 wurde Trump erneut zum Präsidenten gewählt. Die USA haben heute rund 340 Millionen Einwohner und sind die größte Volkswirtschaft der Welt.',
          ],
          quiz: {
            leicht: [
              ['Welches Land befreiten die USA 1991 im Golfkrieg?', 'Kuwait', ['Irak', 'Iran', 'Afghanistan']],
              ['Wie hieß die Operation im Golfkrieg?', 'Desert Storm', ['Overlord', 'Enduring Freedom', 'Iraqi Freedom']],
              ['Welcher Präsident regierte 1993–2001?', 'Bill Clinton', ['George W. Bush', 'Barack Obama', 'Ronald Reagan']],
              ['Wie heißt das Technologiezentrum in Kalifornien?', 'Silicon Valley', ['Wall Street', 'Hollywood', 'Death Valley']],
              ['Welche Terrorgruppe verübte 9/11?', 'Al-Qaida', ['IS', 'Hamas', 'Hisbollah']],
              ['Wie viele Flugzeuge wurden am 11. September entführt?', 'Vier', ['Zwei', 'Drei', 'Sechs']],
              ['Welche Türme stürzten ein?', 'Die Türme des World Trade Center', ['Das Empire State Building', 'Der Sears Tower', 'Die Freiheitsstatue']],
              ['Welches Gebäude wurde außerdem getroffen?', 'Das Pentagon', ['Das Weiße Haus', 'Das Kapitol', 'Die Börse']],
              ['Wo stürzte das vierte Flugzeug ab?', 'In Pennsylvania', ['In New York', 'In Washington', 'In Ohio']],
              ['Wie viele Menschen starben am 11. September etwa?', 'Fast 3000', ['Rund 300', 'Rund 30.000', 'Rund 30']],
              ['Welcher Präsident erklärte den „Krieg gegen den Terror“?', 'George W. Bush', ['Bill Clinton', 'Barack Obama', 'Donald Trump']],
              ['Welches Land griffen die USA 2001 an?', 'Afghanistan', ['Irak', 'Iran', 'Syrien']],
              ['Wer war Al-Qaida-Chef?', 'Osama bin Laden', ['Saddam Hussein', 'Muammar al-Gaddafi', 'Abu Bakr al-Baghdadi']],
              ['Welches Land griffen die USA 2003 an?', 'Den Irak', ['Afghanistan', 'Iran', 'Nordkorea']],
              ['Wo wurde bin Laden 2011 getötet?', 'In Pakistan', ['In Afghanistan', 'Im Irak', 'In Saudi-Arabien']],
              ['Wer wurde 2008 erster afroamerikanischer Präsident?', 'Barack Obama', ['Colin Powell', 'Jesse Jackson', 'Joe Biden']],
              ['Wie lautete Obamas Slogan?', '„Yes We Can“', ['„Make America Great Again“', '„I Have a Dream“', '„Hope and Fear“']],
              ['Wie nennt man Obamas Krankenversicherung?', 'Obamacare', ['Trumpcare', 'New Deal', 'Social Security']],
              ['Wer gewann 2016 die Wahl?', 'Donald Trump', ['Hillary Clinton', 'Joe Biden', 'Bernie Sanders']],
              ['Was geschah am 6. Januar 2021?', 'Trump-Anhänger stürmten das Kapitol', ['Biden wurde vereidigt', 'Ein Erdbeben', 'Ein Terroranschlag von außen']],
            ],
            mittel: [
              ['Von wem befreiten die USA Kuwait?', 'Vom Irak', ['Vom Iran', 'Von Saudi-Arabien', 'Von Syrien']],
              ['Was ließ die Wirtschaft unter Clinton boomen?', 'Das Internet', ['Kohle und Stahl', 'Kohle', 'Landwirtschaft']],
              ['Welche Firmen stammen aus dem Silicon Valley?', 'Apple und Google', ['Ford und GM', 'Coca-Cola und Pepsi', 'Boeing und Lockheed']],
              ['Wie viele Terroristen waren am 11. September beteiligt?', '19', ['4', '9', '50']],
              ['Warum stürzte das vierte Flugzeug ab?', 'Passagiere wehrten sich', ['Es wurde abgeschossen', 'Es hatte keinen Treibstoff', 'Ein Sturm']],
              ['Wer gewährte bin Laden in Afghanistan Unterschlupf?', 'Die Taliban', ['Der Irak', 'Pakistan offiziell', 'Die UNO']],
              ['Mit welcher Begründung griffen die USA 2003 den Irak an?', 'Angebliche Massenvernichtungswaffen', ['Ein Angriff auf New York', 'Ein Angriff auf Kanada', 'Ein UNO-Beschluss']],
              ['Wurden die Massenvernichtungswaffen gefunden?', 'Nein, nie', ['Ja, sofort', 'Ja, 2010', 'Teilweise in Kuwait']],
              ['Welcher Diktator wurde 2003 gestürzt?', 'Saddam Hussein', ['Gaddafi', 'Assad', 'Bin Laden']],
              ['Wer tötete bin Laden?', 'US-Spezialkräfte', ['Die Taliban', 'Pakistan', 'Die UNO']],
              ['Wann zogen die USA aus Afghanistan ab?', '2021', ['2011', '2014', '2001']],
              ['Wer übernahm 2021 in Afghanistan die Macht?', 'Die Taliban', ['Al-Qaida', 'Der IS', 'Eine Demokratie']],
              ['Welcher Bankenzusammenbruch löste 2008 die Finanzkrise aus?', 'Lehman Brothers', ['Goldman Sachs', 'J. P. Morgan', 'Bank of America']],
              ['Wann erhielt Obama den Friedensnobelpreis?', '2009', ['2008', '2012', '2016']],
              ['Wann erlaubte das Oberste Gericht die gleichgeschlechtliche Ehe landesweit?', '2015', ['2001', '2008', '2020']],
              ['Wie lauteten Trumps Slogans?', '„America First“ und „Make America Great Again“', ['„Yes We Can“', '„Hope“', '„New Frontier“']],
              ['Gegen wen verlor Trump 2020?', 'Joe Biden', ['Hillary Clinton', 'Kamala Harris', 'Bernie Sanders']],
              ['Wie viele Tote forderte Corona in den USA?', 'Über eine Million', ['Rund 10.000', 'Rund 100.000', 'Über zehn Millionen']],
              ['Wann wurde Trump erneut gewählt?', '2024', ['2020', '2016', '2022']],
              ['Wie viele Einwohner haben die USA etwa?', 'Rund 340 Millionen', ['Rund 140 Millionen', 'Rund 540 Millionen', 'Rund 1 Milliarde']],
            ],
            schwer: [
              ['Was war die Folge von 9/11 außenpolitisch?', 'Lange Kriege in Afghanistan und im Irak', ['Isolation der USA', 'Frieden mit Al-Qaida', 'Nichts']],
              ['Warum ist der Irakkrieg umstritten?', 'Die Begründung mit Massenvernichtungswaffen war falsch', ['Weil er kurz war', 'Weil der Irak angriff', 'Er ist nicht umstritten']],
              ['Was zeigte der Abzug aus Afghanistan 2021?', 'Das Scheitern des langen Einsatzes', ['Einen großen Sieg', 'Den Beginn des Krieges', 'Nichts']],
              ['Was war Obamacare?', 'Krankenversicherung für Millionen Unversicherte', ['Eine Steuer auf Banken', 'Ein Militärprogramm', 'Ein Wahlgesetz']],
              ['Was symbolisiert der Sturm auf das Kapitol?', 'Einen Angriff auf die demokratische Machtübergabe', ['Eine Feier', 'Einen Staatsbesuch', 'Eine Naturkatastrophe']],
              ['Warum stürmten Anhänger das Kapitol?', 'Trump erkannte seine Wahlniederlage nicht an', ['Biden verlor', 'Wegen Corona', 'Wegen des Irakkriegs']],
              ['Was war Lehman Brothers?', 'Eine Investmentbank', ['Ein Autohersteller', 'Ein Ölkonzern', 'Eine Partei']],
              ['Welche Rolle spielt Silicon Valley?', 'Zentrum der Technologiebranche', ['Zentrum der Ölindustrie', 'Militärstützpunkt', 'Weinregion']],
              ['Welche Stadt war Hauptziel von 9/11?', 'New York', ['Los Angeles', 'Chicago', 'Boston']],
              ['Was ist das Pentagon?', 'Das Verteidigungsministerium', ['Das Außenministerium', 'Der Sitz des Präsidenten', 'Ein Gefängnis']],
              ['Was bedeutete Obamas Wahl symbolisch?', 'Erster afroamerikanischer Präsident', ['Erster Präsident aus Kalifornien', 'Jüngster Präsident', 'Erster Präsident ohne Partei']],
              ['Wie reagierte Trump 2020 auf die Niederlage?', 'Er erkannte sie nicht an', ['Er gratulierte sofort', 'Er trat zurück', 'Er wanderte aus']],
              ['Welche Ereignisse liegen zwischen 2001 und 2011?', 'Krieg in Afghanistan bis zur Tötung bin Ladens', ['Kubakrise', 'Watergate', 'Mondlandung']],
              ['Welcher Krieg 1991 wurde von einer Koalition geführt?', 'Der Golfkrieg', ['Der Vietnamkrieg', 'Der Koreakrieg', 'Der Bürgerkrieg']],
              ['Was ist die größte Volkswirtschaft der Welt?', 'Die USA', ['China', 'Japan', 'Deutschland']],
              ['Wann begann der Afghanistankrieg?', '2001', ['2003', '1991', '2011']],
              ['Welche Rolle hatte das Oberste Gericht 2015?', 'Es erlaubte die gleichgeschlechtliche Ehe landesweit', ['Es verbot sie', 'Es wählte den Präsidenten', 'Es beendete den Irakkrieg']],
              ['Welche Präsidenten folgten 2017–2025 aufeinander?', 'Trump, dann Biden', ['Obama, dann Trump', 'Bush, dann Obama', 'Biden, dann Obama']],
              ['Was war „Desert Storm“?', 'Die Militäroperation zur Befreiung Kuwaits 1991', ['Ein Sandsturm', 'Der Irakkrieg 2003', 'Ein Film']],
              ['Wie wurde Trump erstmals Präsident?', 'Überraschend 2016', ['Erwartet 2012', 'Durch Erbe', '2008 gegen Obama']],
            ],
          },
        },
      ],
    },
  ],
};
