import type { Epoch } from '../types';

export const E4: Epoch = {
  id: 'republik',
  name: 'Erste Republik, NS-Zeit und Besatzung',
  period: '1918–1955',
  events: [
    {
      id: 'erste-republik',
      title: 'Erste Republik und „Anschluss“',
      date: '1918–1945',
      text: [
        'Aus den Trümmern der Monarchie entstand eine kleine Republik, an die kaum jemand glaubte. Wirtschaftskrise und politischer Hass führten 1934 zum Bürgerkrieg und zur Diktatur; 1938 wurde Österreich an Hitlers Deutschland angeschlossen.',
      ],
      subtopics: [
        {
          id: 'erste-republik-1918',
          title: 'Der „Staat, den keiner wollte“',
          date: '1918–1934',
          text: [
            'Am 12. November 1918 rief die Provisorische Nationalversammlung vor dem Parlament in Wien die Republik „Deutschösterreich“ aus; sie erklärte sich zum Teil der Deutschen Republik. Erster Staatskanzler war der Sozialdemokrat Karl Renner. Der Vertrag von Saint-Germain 1919 verbot jedoch den Anschluss an Deutschland, verlangte den Namen „Republik Österreich“ und sprach Südtirol Italien zu. Das Burgenland kam 1921 von Ungarn zu Österreich, Kärnten blieb nach einer Volksabstimmung 1920 ungeteilt.',
            'Vom riesigen Reich mit über 50 Millionen Menschen blieb ein Kleinstaat mit 6,5 Millionen, ein Drittel davon in Wien. Viele hielten ihn nicht für lebensfähig – man sprach vom „Staat, den keiner wollte“. Die Inflation ließ das Geld wertlos werden; 1925 ersetzte der Schilling die Krone, 10.000 Kronen wurden ein Schilling. Eine Anleihe des Völkerbunds unter Bundeskanzler Ignaz Seipel stabilisierte die Währung. 1919 erhielten die Frauen das Wahlrecht, der Adel wurde abgeschafft.',
            'Im „Roten Wien“ baute die sozialdemokratische Stadtregierung über 60.000 Gemeindewohnungen mit Licht, Wasser und Grünflächen, bezahlt durch eine Luxussteuer (Breitner-Steuern). Der riesige Karl-Marx-Hof ist über einen Kilometer lang. Dazu kamen Kindergärten, Bäder und Volksbildung. Die Bundesländer waren dagegen konservativ und christlichsozial geprägt.',
            'Beide Lager hatten bewaffnete Verbände: die sozialdemokratischen „Schutzbund“ und die konservative „Heimwehr“. Als 1927 Geschworene Männer freisprachen, die bei Schattendorf einen Kriegsinvaliden und ein Kind erschossen hatten, setzten empörte Arbeiter den Justizpalast in Brand; die Polizei schoss in die Menge, 89 Menschen starben. Die Weltwirtschaftskrise ab 1929 brachte Massenarbeitslosigkeit; 1931 brach die größte Bank, die Creditanstalt, zusammen.',
            '1933 nutzte der christlichsoziale Bundeskanzler Engelbert Dollfuß eine Geschäftsordnungskrise, um das Parlament auszuschalten, und regierte per Notverordnung. Im Februar 1934 kam es zum Bürgerkrieg: Der Schutzbund kämpfte in Linz, Wien und anderen Städten gegen Bundesheer und Heimwehr, die den Karl-Marx-Hof mit Kanonen beschossen. Über 300 Menschen starben, die Sozialdemokratie wurde verboten, Anführer hingerichtet. Dollfuß errichtete den autoritären „Ständestaat“ nach dem Vorbild Mussolinis.',
          ],
          quiz: {
            leicht: [
              ['Wann wurde die Republik ausgerufen?', '12. November 1918', ['11. November 1918', '15. Mai 1955', '13. März 1938']],
              ['Wie hieß der neue Staat zunächst?', '„Deutschösterreich“', ['„Österreich-Ungarn“', '„Ostmark“', '„Alpenland“']],
              ['Wer war erster Staatskanzler?', 'Karl Renner', ['Engelbert Dollfuß', 'Ignaz Seipel', 'Kurt Schuschnigg']],
              ['Welcher Vertrag verbot den Anschluss an Deutschland?', 'Der Vertrag von Saint-Germain', ['Der Vertrag von Versailles', 'Der Staatsvertrag', 'Der Vertrag von Trianon']],
              ['Welches Gebiet fiel 1919 an Italien?', 'Südtirol', ['Kärnten', 'Burgenland', 'Vorarlberg']],
              ['Welches Bundesland kam 1921 von Ungarn zu Österreich?', 'Burgenland', ['Steiermark', 'Kärnten', 'Niederösterreich']],
              ['Wie viele Einwohner hatte die Republik etwa?', '6,5 Millionen', ['50 Millionen', '1 Million', '20 Millionen']],
              ['Wie nannte man die Republik wegen der Zweifel?', '„Staat, den keiner wollte“', ['„Insel der Seligen“', '„Alpenfestung“', '„Rotes Land“']],
              ['Welche Währung ersetzte 1925 die Krone?', 'Der Schilling', ['Der Euro', 'Die Mark', 'Der Gulden']],
              ['Wann erhielten Frauen das Wahlrecht?', '1919', ['1945', '1907', '1955']],
              ['Was wurde 1919 abgeschafft?', 'Der Adel', ['Die Kirche', 'Die Armee', 'Die Wahlen']],
              ['Wie nennt man Wien unter der sozialdemokratischen Regierung?', 'Rotes Wien', ['Schwarzes Wien', 'Kaiserliches Wien', 'Neues Wien']],
              ['Was baute das Rote Wien in großer Zahl?', 'Gemeindewohnungen', ['Schlösser', 'Kirchen', 'Kasernen']],
              ['Welcher Gemeindebau ist über einen Kilometer lang?', 'Der Karl-Marx-Hof', ['Der Reumannhof', 'Die Hofburg', 'Der Goethehof']],
              ['Wie hieß der sozialdemokratische Wehrverband?', 'Schutzbund', ['Heimwehr', 'SA', 'Bundesheer']],
              ['Wie hieß der konservative Wehrverband?', 'Heimwehr', ['Schutzbund', 'Rotfront', 'Volkswehr']],
              ['Welches Gebäude brannte 1927?', 'Der Justizpalast', ['Das Parlament', 'Die Oper', 'Die Hofburg']],
              ['Welche Bank brach 1931 zusammen?', 'Die Creditanstalt', ['Die Nationalbank', 'Die Erste Bank', 'Die Raiffeisenbank']],
              ['Welcher Kanzler schaltete 1933 das Parlament aus?', 'Engelbert Dollfuß', ['Karl Renner', 'Ignaz Seipel', 'Leopold Figl']],
              ['Wann war der Bürgerkrieg in Österreich?', 'Februar 1934', ['November 1918', 'März 1938', 'Juli 1927']],
            ],
            mittel: [
              ['Was erklärte sich Deutschösterreich 1918?', 'Zum Teil der Deutschen Republik', ['Zum Teil Ungarns', 'Für neutral', 'Zum Königreich']],
              ['Welchen Namen verlangte Saint-Germain?', '„Republik Österreich“', ['„Ostmark“', '„Deutschösterreich“', '„Donaurepublik“']],
              ['Wann war der Vertrag von Saint-Germain?', '1919', ['1918', '1921', '1938']],
              ['Wie entschied Kärnten 1920 über seine Zugehörigkeit?', 'Durch eine Volksabstimmung', ['Durch Krieg', 'Durch Kauf', 'Durch Los']],
              ['Wie viele Menschen hatte das alte Reich?', 'Über 50 Millionen', ['10 Millionen', '100 Millionen', '6 Millionen']],
              ['Welcher Anteil der Bevölkerung lebte in Wien?', 'Ein Drittel', ['Die Hälfte', 'Ein Zehntel', 'Fast alle']],
              ['Wie viele Kronen wurden 1925 ein Schilling?', '10.000', ['10', '100', '1 Million']],
              ['Wer stabilisierte die Währung mit einer Völkerbundanleihe?', 'Ignaz Seipel', ['Karl Renner', 'Dollfuß', 'Schuschnigg']],
              ['Wie viele Gemeindewohnungen baute das Rote Wien?', 'Über 60.000', ['Rund 600', 'Rund 6000', 'Über 600.000']],
              ['Wie wurden die Wohnungen bezahlt?', 'Durch eine Luxussteuer (Breitner-Steuern)', ['Durch Kredite aus Amerika', 'Durch den Kaiser', 'Durch Spenden der Kirche']],
              ['Wie waren die Bundesländer politisch geprägt?', 'Konservativ und christlichsozial', ['Sozialdemokratisch', 'Kommunistisch', 'Liberal']],
              ['Was geschah in Schattendorf?', 'Ein Kriegsinvalide und ein Kind wurden erschossen', ['Ein Bergwerksunglück', 'Ein Bankraub', 'Eine Hochzeit']],
              ['Wie viele Menschen starben beim Justizpalastbrand 1927?', '89', ['8', '890', '3']],
              ['Wann brannte der Justizpalast?', '1927', ['1918', '1934', '1931']],
              ['Was brachte die Weltwirtschaftskrise?', 'Massenarbeitslosigkeit', ['Wohlstand', 'Neue Kolonien', 'Vollbeschäftigung']],
              ['Wie regierte Dollfuß ab 1933?', 'Per Notverordnung', ['Mit dem Parlament', 'Als Kaiser', 'Mit den Sozialdemokraten']],
              ['Was beschossen Bundesheer und Heimwehr 1934?', 'Den Karl-Marx-Hof', ['Das Parlament', 'Die Hofburg', 'Den Stephansdom']],
              ['Wie viele Menschen starben im Bürgerkrieg 1934?', 'Über 300', ['Rund 30', 'Rund 3000', 'Rund 30.000']],
              ['Was wurde nach dem Bürgerkrieg verboten?', 'Die Sozialdemokratie', ['Die Kirche', 'Die Heimwehr', 'Die Christlichsozialen']],
              ['Wie heißt Dollfuß’ Regime?', 'Ständestaat', ['Rotes Wien', 'Erste Republik', 'Volksfront']],
            ],
            schwer: [
              ['Nach wessen Vorbild errichtete Dollfuß den Ständestaat?', 'Nach dem Vorbild Mussolinis', ['Nach Hitler', 'Nach Stalin', 'Nach Roosevelt']],
              ['Welche Krise nutzte Dollfuß 1933?', 'Eine Geschäftsordnungskrise im Parlament', ['Einen Krieg', 'Eine Pest', 'Eine Naturkatastrophe']],
              ['Was löste den Justizpalastbrand aus?', 'Freisprüche für die Schützen von Schattendorf', ['Ein Blitz', 'Ein Unfall', 'Ein Krieg']],
              ['Was bot das Rote Wien außer Wohnungen?', 'Kindergärten, Bäder und Volksbildung', ['Kasernen', 'Kirchen', 'Banken']],
              ['Welche Folge hatte das Ende des Reiches wirtschaftlich?', 'Ein Kleinstaat galt als kaum lebensfähig', ['Wohlstand', 'Kolonien', 'Ölfunde']],
              ['Wo kämpfte der Schutzbund 1934?', 'In Linz, Wien und anderen Städten', ['Nur in Tirol', 'In Ungarn', 'Gar nicht']],
              ['Was geschah mit Anführern des Schutzbunds?', 'Sie wurden hingerichtet', ['Sie wurden Minister', 'Sie wurden geehrt', 'Sie gründeten eine Partei']],
              ['Welche Lager standen sich in der Ersten Republik gegenüber?', 'Sozialdemokraten und Christlichsoziale', ['Monarchisten und Kommunisten', 'Liberale und Grüne', 'Habsburger und Hohenzollern']],
              ['Was verlangte der Vertrag von Saint-Germain zu Südtirol?', 'Es fiel an Italien', ['Es blieb österreichisch', 'Es wurde unabhängig', 'Es fiel an die Schweiz']],
              ['Wie entstand die Bevölkerungsverteilung?', 'Wien blieb riesig für den kleinen Staat („Wasserkopf“)', ['Wien war klein', 'Alle lebten auf dem Land', 'Gleichmäßig verteilt']],
              ['Welche Rolle spielte Seipel?', 'Bundeskanzler, der die Währung stabilisierte', ['Bürgermeister des Roten Wien', 'Schutzbundführer', 'Kaiser']],
              ['Wann wurde der Schilling eingeführt?', '1925', ['1918', '1938', '1945']],
              ['Was symbolisiert der Karl-Marx-Hof?', 'Den sozialen Wohnbau des Roten Wien', ['Den Ständestaat', 'Die Monarchie', 'Den Nationalsozialismus']],
              ['Wann kam das Burgenland zu Österreich?', '1921', ['1919', '1918', '1938']],
              ['Was bedeutete 1931 für die Wirtschaft?', 'Zusammenbruch der größten Bank', ['Wirtschaftswunder', 'Euro-Einführung', 'Ende der Inflation']],
              ['Wann wurde die Sozialdemokratie verboten?', '1934', ['1933', '1938', '1927']],
              ['Welche Partei gehörte Dollfuß an?', 'Den Christlichsozialen', ['Den Sozialdemokraten', 'Den Nationalsozialisten', 'Den Kommunisten']],
              ['Was war Karl Renner politisch?', 'Sozialdemokrat', ['Christlichsozialer', 'Monarchist', 'Nationalsozialist']],
              ['Wie wurde die Inflation besiegt?', 'Mit einer Völkerbundanleihe und dem Schilling', ['Mit Gold aus Amerika', 'Gar nicht', 'Durch Krieg']],
              ['Welche Bevölkerungsgruppe erhielt 1919 das Wahlrecht?', 'Frauen', ['Kinder', 'Adelige', 'Ausländer']],
            ],
          },
        },
        {
          id: 'anschluss-ns',
          title: 'Ständestaat, „Anschluss“ und NS-Herrschaft',
          date: '1934–1945',
          text: [
            'Im Juli 1934 versuchten österreichische Nationalsozialisten einen Putsch und ermordeten Bundeskanzler Dollfuß im Kanzleramt; der Putsch scheiterte. Sein Nachfolger Kurt Schuschnigg geriet immer mehr unter Druck Hitlers, der selbst aus Braunau am Inn stammte. Im Februar 1938 zwang Hitler ihn in Berchtesgaden, Nationalsozialisten in die Regierung aufzunehmen.',
            'Schuschnigg setzte für den 13. März 1938 eine Volksbefragung über die Unabhängigkeit an. Hitler forderte die Absage, Schuschnigg trat am 11. März mit den Worten „Gott schütze Österreich!“ zurück. Am 12. März 1938 marschierte die deutsche Wehrmacht ein, ohne auf Widerstand zu stoßen, und wurde vielerorts bejubelt. Am 15. März sprach Hitler vor Hunderttausenden auf dem Wiener Heldenplatz. Eine gelenkte Volksabstimmung im April ergab angeblich 99,7 Prozent Zustimmung. Österreich hieß nun „Ostmark“.',
            'Sofort begann die Verfolgung der rund 200.000 Juden Österreichs, die meisten in Wien. Sie wurden gedemütigt, mussten Gehsteige schrubben („Reibpartien“), wurden enteignet („arisiert“) und vertrieben. Im Novemberpogrom 1938 wurden fast alle Wiener Synagogen zerstört. Rund 65.000 österreichische Juden wurden ermordet. Unter den Vertriebenen waren Sigmund Freud, der 1938 nach London floh, und viele Künstler und Wissenschaftler.',
            'Bei Mauthausen in Oberösterreich entstand 1938 ein Konzentrationslager, in dem Häftlinge im Steinbruch auf der „Todesstiege“ Granitblöcke schleppen mussten; rund 90.000 Menschen starben dort. In Schloss Hartheim wurden Kranke und Behinderte ermordet. Viele Österreicher waren Täter: Adolf Eichmann organisierte die Deportationen, der Österreicher Odilo Globocnik leitete Vernichtungslager im besetzten Polen.',
            'Es gab auch Widerstand, etwa von Kommunisten, katholischen Gruppen und Kärntner Slowenen. Der Bauer Franz Jägerstätter verweigerte den Kriegsdienst und wurde 1943 hingerichtet; 2007 wurde er seliggesprochen. Rund 250.000 Österreicher fielen als Soldaten der Wehrmacht. In der Moskauer Deklaration 1943 erklärten die Alliierten Österreich zum „ersten Opfer“ Hitlers, aber auch mitverantwortlich. Im April 1945 eroberte die Rote Armee Wien.',
          ],
          quiz: {
            leicht: [
              ['Wer wurde im Juli 1934 ermordet?', 'Engelbert Dollfuß', ['Kurt Schuschnigg', 'Karl Renner', 'Ignaz Seipel']],
              ['Wer ermordete Dollfuß?', 'Österreichische Nationalsozialisten', ['Sozialdemokraten', 'Kommunisten', 'Monarchisten']],
              ['Wer folgte Dollfuß als Kanzler?', 'Kurt Schuschnigg', ['Arthur Seyß-Inquart', 'Karl Renner', 'Leopold Figl']],
              ['Woher stammte Hitler?', 'Aus Braunau am Inn', ['Aus Wien', 'Aus Linz', 'Aus München']],
              ['Mit welchen Worten trat Schuschnigg zurück?', '„Gott schütze Österreich!“', ['„Österreich ist frei!“', '„Heil Hitler!“', '„Es lebe der Kaiser!“']],
              ['Wann marschierte die Wehrmacht in Österreich ein?', '12. März 1938', ['13. März 1938', '1. September 1939', '15. Mai 1955']],
              ['Stieß die Wehrmacht auf Widerstand?', 'Nein, sie wurde vielerorts bejubelt', ['Ja, heftigen', 'Ja, in Wien', 'Ja, in Tirol']],
              ['Wo sprach Hitler am 15. März 1938?', 'Auf dem Wiener Heldenplatz', ['In Linz', 'In Braunau', 'In Salzburg']],
              ['Wie hieß Österreich nach dem Anschluss?', '„Ostmark“', ['„Deutschösterreich“', '„Alpenreich“', '„Donauland“']],
              ['Wie viel Zustimmung ergab die gelenkte Abstimmung angeblich?', '99,7 Prozent', ['51 Prozent', '75 Prozent', '30 Prozent']],
              ['Wie viele Juden lebten in Österreich etwa?', 'Rund 200.000', ['Rund 2000', 'Rund 20.000', 'Rund 2 Millionen']],
              ['Was mussten Juden bei den „Reibpartien“ tun?', 'Gehsteige schrubben', ['Steine schleppen', 'Singen', 'Bäume pflanzen']],
              ['Was wurde im Novemberpogrom 1938 zerstört?', 'Fast alle Wiener Synagogen', ['Der Stephansdom', 'Die Hofburg', 'Nichts']],
              ['Wie viele österreichische Juden wurden ermordet?', 'Rund 65.000', ['Rund 6500', 'Rund 650', 'Rund 650.000']],
              ['Wohin floh Sigmund Freud 1938?', 'Nach London', ['Nach New York', 'Nach Paris', 'Nach Zürich']],
              ['Wo entstand 1938 ein Konzentrationslager?', 'In Mauthausen', ['In Dachau', 'In Auschwitz', 'In Salzburg']],
              ['Wie hieß die Treppe im Steinbruch von Mauthausen?', '„Todesstiege“', ['„Himmelsleiter“', '„Granitweg“', '„Steile Stiege“']],
              ['Wer organisierte die Deportationen der Juden?', 'Adolf Eichmann', ['Franz Jägerstätter', 'Kurt Schuschnigg', 'Karl Renner']],
              ['Welcher Bauer verweigerte den Kriegsdienst?', 'Franz Jägerstätter', ['Andreas Hofer', 'Leopold Figl', 'Odilo Globocnik']],
              ['Wer eroberte im April 1945 Wien?', 'Die Rote Armee', ['Die US-Armee', 'Die Briten', 'Die Franzosen']],
            ],
            mittel: [
              ['Wann wurde Dollfuß ermordet?', 'Juli 1934', ['Februar 1934', 'März 1938', 'Juli 1927']],
              ['Wo wurde Dollfuß ermordet?', 'Im Kanzleramt', ['Im Parlament', 'In der Hofburg', 'Auf der Straße']],
              ['Wie ging der Juli-Putsch 1934 aus?', 'Er scheiterte', ['Er war erfolgreich', 'Hitler marschierte ein', 'Schuschnigg wurde ermordet']],
              ['Wo zwang Hitler Schuschnigg im Februar 1938?', 'In Berchtesgaden', ['In Wien', 'In Berlin', 'In München']],
              ['Wozu zwang Hitler Schuschnigg?', 'Nationalsozialisten in die Regierung aufzunehmen', ['Abzudanken', 'Krieg zu erklären', 'Wien zu verlassen']],
              ['Für wann setzte Schuschnigg eine Volksbefragung an?', '13. März 1938', ['12. März 1938', '10. April 1938', '1. Mai 1938']],
              ['Wann trat Schuschnigg zurück?', '11. März 1938', ['12. März 1938', '13. März 1938', '15. März 1938']],
              ['Wann war die gelenkte Volksabstimmung?', 'April 1938', ['März 1938', 'November 1938', 'Januar 1939']],
              ['Was bedeutete „Arisierung“?', 'Enteignung jüdischen Besitzes', ['Bau neuer Häuser', 'Einbürgerung', 'Schulreform']],
              ['Wo lebten die meisten österreichischen Juden?', 'In Wien', ['In Tirol', 'In Graz', 'In Salzburg']],
              ['Wann war das Novemberpogrom?', 'November 1938', ['März 1938', 'November 1918', 'Januar 1942']],
              ['Wie viele Menschen starben in Mauthausen etwa?', 'Rund 90.000', ['Rund 900', 'Rund 9000', 'Rund 900.000']],
              ['Was mussten Häftlinge in Mauthausen schleppen?', 'Granitblöcke', ['Holz', 'Kohle', 'Sandsäcke']],
              ['Was geschah im Schloss Hartheim?', 'Kranke und Behinderte wurden ermordet', ['Es war ein Lazarett', 'Es war ein Museum', 'Es war Hitlers Wohnsitz']],
              ['Welcher Österreicher leitete Vernichtungslager in Polen?', 'Odilo Globocnik', ['Adolf Eichmann', 'Kurt Schuschnigg', 'Franz Jägerstätter']],
              ['Wann wurde Jägerstätter hingerichtet?', '1943', ['1938', '1945', '1950']],
              ['Wann wurde Jägerstätter seliggesprochen?', '2007', ['1945', '1955', '1995']],
              ['Wer leistete Widerstand?', 'Kommunisten, katholische Gruppen und Kärntner Slowenen', ['Nur die SS', 'Niemand', 'Nur Adlige']],
              ['Wie viele Österreicher fielen als Wehrmachtssoldaten?', 'Rund 250.000', ['Rund 25.000', 'Rund 2,5 Millionen', 'Rund 2500']],
              ['Was erklärte die Moskauer Deklaration 1943?', 'Österreich als „erstes Opfer“, aber mitverantwortlich', ['Österreich als Siegermacht', 'Österreich als Teil Deutschlands für immer', 'Österreich als neutral']],
            ],
            schwer: [
              ['Wie wurde die „Opferthese“ später kritisiert?', 'Viele Österreicher waren Täter', ['Sie wurde nie kritisiert', 'Österreich war gar nicht besetzt', 'Österreich war neutral']],
              ['Warum setzte Schuschnigg eine Volksbefragung an?', 'Um die Unabhängigkeit zu bestätigen', ['Um den Anschluss zu beschließen', 'Um den Kaiser zurückzuholen', 'Um Wahlen abzuschaffen']],
              ['Was bezweckte Hitler mit dem Einmarsch vor der Befragung?', 'Ein Votum für die Unabhängigkeit zu verhindern', ['Die Abstimmung zu schützen', 'Den Kaiser einzusetzen', 'Nichts']],
              ['Welche Bilder prägen das Gedächtnis an den März 1938?', 'Jubel auf dem Heldenplatz', ['Kämpfe in Wien', 'Leere Straßen', 'Proteste gegen Hitler']],
              ['Was ist am Ergebnis von 99,7 Prozent problematisch?', 'Die Abstimmung war gelenkt und nicht frei', ['Es war zu niedrig', 'Es war echt und frei', 'Es betraf nur Wien']],
              ['Welche Rolle spielte Eichmann?', 'Er organisierte die Deportationen', ['Er leistete Widerstand', 'Er war Kanzler', 'Er befreite Juden']],
              ['Warum wurde Jägerstätter hingerichtet?', 'Er verweigerte den Kriegsdienst', ['Er war Spion', 'Er stahl', 'Er war Jude']],
              ['Was ist die „Todesstiege“?', 'Eine Treppe im Steinbruch von Mauthausen', ['Ein Turm in Wien', 'Ein Bergweg in Tirol', 'Eine Kirche']],
              ['In welchem Bundesland liegt Mauthausen?', 'Oberösterreich', ['Niederösterreich', 'Tirol', 'Kärnten']],
              ['Was erlebten jüdische Wissenschaftler und Künstler?', 'Vertreibung ins Exil', ['Förderung', 'Beförderung', 'Ehrungen']],
              ['Welches Ereignis folgte auf die Eroberung Wiens 1945?', 'Das Kriegsende und die Wiedererrichtung Österreichs', ['Der Anschluss', 'Der Bürgerkrieg', 'Die Monarchie']],
              ['Wie reagierte die Bevölkerung vielerorts 1938?', 'Mit Jubel', ['Mit bewaffnetem Widerstand', 'Mit Flucht', 'Mit Generalstreik']],
              ['Was war die Absicht des Juli-Putsches 1934?', 'Die Macht für die Nationalsozialisten zu erobern', ['Den Kaiser zurückzuholen', 'Die Sozialdemokraten zu stärken', 'Neutralität']],
              ['Woher stammte Hitler genau?', 'Aus Braunau am Inn in Oberösterreich', ['Aus Linz', 'Aus Wien', 'Aus Graz']],
              ['Wann sprach Hitler auf dem Heldenplatz?', '15. März 1938', ['12. März 1938', '11. März 1938', '10. April 1938']],
              ['Welche Minderheit leistete in Kärnten Widerstand?', 'Kärntner Slowenen', ['Kärntner Ungarn', 'Kärntner Italiener', 'Kärntner Tschechen']],
              ['Wofür steht die Moskauer Deklaration?', 'Die Absicht der Alliierten, Österreich wiederherzustellen', ['Den Anschluss', 'Die Teilung Österreichs für immer', 'Den Beitritt zur Sowjetunion']],
              ['Wie viele Jahre dauerte die NS-Herrschaft in Österreich?', 'Sieben', ['Zwölf', 'Drei', 'Zwanzig']],
              ['Wie endete der Ständestaat?', 'Mit dem Anschluss 1938', ['Mit Wahlen 1936', 'Mit einer Revolution 1945', 'Mit dem Staatsvertrag']],
              ['Was symbolisiert Jägerstätters Seligsprechung?', 'Anerkennung seines Gewissensentscheids', ['Eine Verurteilung', 'Einen Kriegsorden', 'Nichts']],
            ],
          },
        },
      ],
    },
    {
      id: 'staatsvertrag',
      title: 'Besatzung und Staatsvertrag',
      date: '1945–1955',
      text: [
        'Nach dem Krieg wurde Österreich wiederhergestellt, aber zehn Jahre lang von den vier Siegermächten besetzt. 1955 erreichte es mit dem Staatsvertrag seine volle Freiheit und erklärte sich für immerwährend neutral.',
      ],
      subtopics: [
        {
          id: 'besatzung-staatsvertrag',
          title: '„Österreich ist frei!“',
          date: '1945–1955',
          text: [
            'Am 27. April 1945 erklärte eine provisorische Regierung unter dem 74-jährigen Karl Renner – der schon 1918 Staatskanzler gewesen war – die Unabhängigkeit Österreichs; die Zweite Republik entstand. Renner wurde im Dezember 1945 erster Bundespräsident. Bei den Wahlen im November 1945 erreichten die Kommunisten nur rund fünf Prozent; Bundeskanzler wurde Leopold Figl von der ÖVP.',
            'Österreich und Wien wurden in vier Besatzungszonen aufgeteilt: Die Sowjetunion besetzte Niederösterreich, das Burgenland und das Mühlviertel, die USA Salzburg und Oberösterreich südlich der Donau, die Briten Kärnten, Steiermark und Osttirol, die Franzosen Tirol und Vorarlberg. Die Wiener Innenstadt wurde von den vier Mächten im Monatswechsel gemeinsam verwaltet – „vier im Jeep“. Der Film „Der dritte Mann“ (1949) mit der Zither-Melodie zeigt das zerbombte Wien dieser Zeit.',
            'Der Wiederaufbau begann mühsam: Frauen räumten Trümmer weg („Trümmerfrauen“), Stephansdom und Staatsoper waren ausgebrannt. Mit Hilfe des Marshallplans erholte sich die Wirtschaft. ÖVP und SPÖ regierten in einer großen Koalition und teilten Posten nach Parteiproporz auf; Gewerkschaften und Wirtschaftskammern einigten sich in der „Sozialpartnerschaft“ auf Löhne und Preise. 1950 scheiterte ein von Kommunisten getragener Streik.',
            'Jahrelang verhandelten die Alliierten über einen Staatsvertrag. Nach Stalins Tod 1953 zeigte sich die Sowjetunion bereit. Im April 1955 sagte Österreich in Moskau zu, sich nach dem Vorbild der Schweiz für neutral zu erklären. Am 15. Mai 1955 unterzeichneten die Außenminister der vier Mächte und Österreichs im Schloss Belvedere den Staatsvertrag. Außenminister Figl zeigte das Dokument vom Balkon der jubelnden Menge; berühmt wurde sein Satz: „Österreich ist frei!“',
            'Der Staatsvertrag verbietet einen Anschluss an Deutschland, schützt die Rechte der slowenischen und kroatischen Minderheiten und verbietet NS-Organisationen. Bis Oktober 1955 zogen die letzten Besatzungssoldaten ab. Am 26. Oktober 1955 beschloss das Parlament die „immerwährende Neutralität“; dieser Tag ist heute Nationalfeiertag.',
          ],
          quiz: {
            leicht: [
              ['Wer erklärte 1945 die Unabhängigkeit Österreichs?', 'Karl Renner', ['Leopold Figl', 'Bruno Kreisky', 'Kurt Schuschnigg']],
              ['Wann wurde die Unabhängigkeit erklärt?', '27. April 1945', ['8. Mai 1945', '15. Mai 1955', '12. November 1918']],
              ['Welche Republik entstand 1945?', 'Die Zweite Republik', ['Die Erste Republik', 'Die Dritte Republik', 'Die Volksrepublik']],
              ['Wer wurde 1945 Bundeskanzler?', 'Leopold Figl', ['Karl Renner', 'Julius Raab', 'Theodor Körner']],
              ['In wie viele Zonen wurde Österreich aufgeteilt?', 'Vier', ['Zwei', 'Drei', 'Fünf']],
              ['Welche Macht besetzte Tirol und Vorarlberg?', 'Frankreich', ['Großbritannien', 'USA', 'Sowjetunion']],
              ['Welche Macht besetzte Niederösterreich?', 'Die Sowjetunion', ['Die USA', 'Frankreich', 'Großbritannien']],
              ['Wie nannte man die gemeinsame Verwaltung der Wiener Innenstadt?', '„Vier im Jeep“', ['„Vier Musketiere“', '„Viererbande“', '„Großes Quartett“']],
              ['Welcher Film zeigt das zerbombte Wien?', '„Der dritte Mann“', ['„Sound of Music“', '„Sisi“', '„Casablanca“']],
              ['Welches Instrument prägt die Musik von „Der dritte Mann“?', 'Die Zither', ['Die Geige', 'Das Klavier', 'Die Gitarre']],
              ['Wie nannte man die Frauen, die Trümmer räumten?', 'Trümmerfrauen', ['Bauernfrauen', 'Heimatfrauen', 'Kriegsfrauen']],
              ['Welcher Plan half beim Wiederaufbau?', 'Der Marshallplan', ['Der Morgenthau-Plan', 'Der Schlieffen-Plan', 'Der Fünfjahresplan']],
              ['Welche Parteien bildeten die große Koalition?', 'ÖVP und SPÖ', ['FPÖ und KPÖ', 'Grüne und NEOS', 'ÖVP und FPÖ']],
              ['Wann wurde der Staatsvertrag unterzeichnet?', '15. Mai 1955', ['26. Oktober 1955', '27. April 1945', '1. Januar 1995']],
              ['Wo wurde der Staatsvertrag unterzeichnet?', 'Im Schloss Belvedere', ['In der Hofburg', 'Im Parlament', 'In Schönbrunn']],
              ['Welchen berühmten Satz sagte Figl?', '„Österreich ist frei!“', ['„Gott schütze Österreich!“', '„Wir sind neutral!“', '„Ich bin ein Wiener!“']],
              ['Was beschloss das Parlament am 26. Oktober 1955?', 'Die immerwährende Neutralität', ['Den EU-Beitritt', 'Die Republik', 'Den Euro']],
              ['Was ist der 26. Oktober heute?', 'Nationalfeiertag', ['Tag der Arbeit', 'Weihnachten', 'Staatsvertragstag']],
              ['Nach welchem Vorbild wurde Österreich neutral?', 'Nach dem Vorbild der Schweiz', ['Nach Schweden', 'Nach Finnland', 'Nach Irland']],
              ['Was verbietet der Staatsvertrag?', 'Einen Anschluss an Deutschland', ['Den Tourismus', 'Die Monarchie in Ungarn', 'Den Handel']],
            ],
            mittel: [
              ['Wie alt war Karl Renner 1945?', '74', ['54', '64', '84']],
              ['Wann wurde Renner Bundespräsident?', 'Dezember 1945', ['April 1945', 'Mai 1955', 'November 1918']],
              ['Wie viel Prozent erreichten die Kommunisten 1945 etwa?', 'Rund fünf Prozent', ['Rund 50 Prozent', 'Rund 25 Prozent', 'Null Prozent']],
              ['Welcher Partei gehörte Figl an?', 'ÖVP', ['SPÖ', 'KPÖ', 'FPÖ']],
              ['Welche Gebiete besetzten die USA?', 'Salzburg und Oberösterreich südlich der Donau', ['Tirol', 'Kärnten', 'Niederösterreich']],
              ['Welche Gebiete besetzten die Briten?', 'Kärnten, Steiermark und Osttirol', ['Vorarlberg', 'Salzburg', 'Burgenland']],
              ['Welches Gebiet Oberösterreichs besetzte die Sowjetunion?', 'Das Mühlviertel', ['Das Innviertel', 'Das Salzkammergut', 'Linz-Süd']],
              ['Wie wechselte die Verwaltung der Wiener Innenstadt?', 'Im Monatswechsel', ['Jährlich', 'Täglich', 'Nie']],
              ['Wann kam „Der dritte Mann“ heraus?', '1949', ['1945', '1955', '1938']],
              ['Welche Wahrzeichen Wiens waren ausgebrannt?', 'Stephansdom und Staatsoper', ['Schönbrunn und Belvedere', 'Riesenrad und Parlament', 'Karlskirche und Hofburg']],
              ['Wie teilten ÖVP und SPÖ Posten auf?', 'Nach Parteiproporz', ['Nach Losentscheid', 'Nach Alter', 'Gar nicht']],
              ['Wer einigte sich in der Sozialpartnerschaft?', 'Gewerkschaften und Wirtschaftskammern', ['Kirche und Staat', 'Alliierte und Regierung', 'Bund und Länder']],
              ['Worauf einigten sich die Sozialpartner?', 'Auf Löhne und Preise', ['Auf Grenzen', 'Auf Religion', 'Auf Wahlen']],
              ['Wann scheiterte ein kommunistischer Streik?', '1950', ['1945', '1955', '1968']],
              ['Wessen Tod machte die Sowjetunion verhandlungsbereit?', 'Stalins', ['Lenins', 'Hitlers', 'Roosevelts']],
              ['Wann starb Stalin?', '1953', ['1945', '1955', '1950']],
              ['Wo sagte Österreich im April 1955 Neutralität zu?', 'In Moskau', ['In Washington', 'In London', 'In Paris']],
              ['Welche Minderheiten schützt der Staatsvertrag?', 'Slowenen und Kroaten', ['Ungarn und Tschechen', 'Deutsche', 'Italiener']],
              ['Bis wann zogen die Besatzungssoldaten ab?', 'Oktober 1955', ['Mai 1955', 'Dezember 1945', '1960']],
              ['Was verbietet der Staatsvertrag außer dem Anschluss?', 'NS-Organisationen', ['Gewerkschaften', 'Kirchen', 'Parteien']],
            ],
            schwer: [
              ['Was ist besonders an Renner?', 'Er gründete 1918 und 1945 die Republik mit', ['Er war Kaiser', 'Er war Kommunist', 'Er war Hitlers Minister']],
              ['Was zeigte Figl vom Balkon?', 'Das Staatsvertragsdokument', ['Eine Fahne', 'Eine Krone', 'Ein Foto']],
              ['Warum war die Neutralität Bedingung?', 'Die Sowjetunion wollte kein westlich gebundenes Österreich', ['Die USA wollten es', 'Die Schweiz verlangte es', 'Der Papst befahl es']],
              ['Welche Folge hatte die Neutralität?', 'Österreich trat keinem Militärbündnis bei', ['Österreich trat der NATO bei', 'Österreich wurde Teil des Warschauer Pakts', 'Österreich schaffte die Armee ab']],
              ['Was symbolisiert „Der dritte Mann“?', 'Das geteilte Nachkriegswien', ['Das Rote Wien', 'Den Wiener Kongress', 'Die Kaiserzeit']],
              ['Welche Zone hatte Wien als Umgebung?', 'Die sowjetische', ['Die amerikanische', 'Die britische', 'Die französische']],
              ['Was ist die Sozialpartnerschaft?', 'Zusammenarbeit von Arbeitnehmer- und Arbeitgebervertretern', ['Ein Militärbündnis', 'Eine Partei', 'Ein Kirchenvertrag']],
              ['Wie lange dauerte die Besatzung?', 'Zehn Jahre', ['Ein Jahr', 'Zwanzig Jahre', 'Fünf Jahre']],
              ['Welches Datum ist Nationalfeiertag?', '26. Oktober', ['15. Mai', '12. November', '27. April']],
              ['Wer unterzeichnete den Staatsvertrag?', 'Die Außenminister der vier Mächte und Österreichs', ['Nur Figl', 'Der Papst', 'Die UNO']],
              ['Wie nennt man die Neutralität Österreichs genau?', '„Immerwährende Neutralität“', ['„Bewaffnete Allianz“', '„Zeitweise Neutralität“', '„Teilneutralität“']],
              ['Was lernten ÖVP und SPÖ aus 1934?', 'Zusammenarbeit statt Bürgerkrieg', ['Getrennt zu regieren', 'Nichts', 'Militärisch aufzurüsten']],
              ['Wie verhielt sich die Bevölkerung zum Kommunismus 1945?', 'Kaum Unterstützung (rund fünf Prozent)', ['Große Mehrheit', 'Die Hälfte', 'Alle']],
              ['Wann wurde die Neutralität beschlossen im Verhältnis zum Staatsvertrag?', 'Gut fünf Monate später', ['Am selben Tag', 'Zehn Jahre früher', 'Nie']],
              ['Welche Zone hatte Kärnten?', 'Die britische', ['Die französische', 'Die sowjetische', 'Die amerikanische']],
              ['Welche Zone hatte Salzburg?', 'Die amerikanische', ['Die britische', 'Die französische', 'Die sowjetische']],
              ['Warum zeigte Figl das Dokument vom Balkon?', 'Der jubelnden Menge im Park', ['Den Alliierten', 'Dem Papst', 'Den Russen']],
              ['Welche Rolle spielt das Belvedere 1955?', 'Ort der Staatsvertragsunterzeichnung', ['Ort des Anschlusses', 'Ort der Kaiserkrönung', 'Parlament']],
              ['Welches Wahrzeichen wurde nach dem Krieg wieder aufgebaut?', 'Der Stephansdom', ['Der Eiffelturm', 'Die Sagrada Família', 'Der Kölner Dom']],
              ['Was ist der Unterschied zwischen 1945 und 1955?', '1945 Republik ausgerufen, 1955 volle Freiheit', ['1945 Monarchie, 1955 Republik', 'Kein Unterschied', '1945 Anschluss, 1955 Krieg']],
            ],
          },
        },
      ],
    },
  ],
};
